extensions/integration-tests/src/tests/objectExplorer.test.ts

Integration tests were broken after #10326 since a new action was added to the right click menu.
This PR adds the new menu option to the expected elements array.

Fixes integration tests

---

CHANGELOG.md

Change log for hotfix 1.18.1 (assuming release on 27th)

Hotfix change log

---

README.md

updated the localization section

---

build/azure-pipelines/sql-product-build.yml
build/azure-pipelines/sql-product-compile.yml

https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=65688&view=results

Don't run platform builds if compile fails

---

extensions/mssql/package.json

update bdc tab category

---

extensions/machine-learning/package.json

format and add metadata

---

extensions/machine-learning/src/prediction/predictService.ts

MI now supports ONNX runtime so the extension should support is as well

ML- MI now supports ONNX runtime so the extension should support is as well

---

src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerTable.ts
src/sql/workbench/contrib/dashboard/browser/widgets/explorer/objectMetadataWrapper.ts

This PR fixes #10601
previously, we perform filtering on schema, name and full name for objects in database, during my recent change, i missed the full name filtering, now adding it back.

fix object filtering regression

---

extensionsGallery-insider.json
extensionsGallery.json

Just insiders for now - changes in core aren't in stable build yet.

Add SQL assessment to extension gallery

---

extensions/sql-assessment/README.md
extensions/sql-assessment/package.json

@vchvlad I'd suggest adding some more useful content to the README - such as describing how to view and use it (or at least providing a link to documentation of that if you have that somewhere else).

Adds README to sql assessment and bump min ADS version

---

extensions/machine-learning/src/common/constants.ts
extensions/machine-learning/src/views/widgets/dashboardWidget.ts

ML - Added documents for MI

---

extensionsGallery-insider.json

Update ML extension version extensionsGallery-insider.json

---

.github/workflows/ci.yml
scripts/test-extensions-unit.bat

Temporary until we can figure out what's causing these test timeouts

Disable sql-database-projects tests

---

extensions/resource-deployment/src/services/notebookService.ts
extensions/resource-deployment/src/services/platformService.ts
extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts

This adds a uniquifier to the notebook that is opened by the NotebookWizard.

Unique title for opened notebooks

---

extensionsGallery-insider.json
extensionsGallery.json

Update datavirtualization icon

---

extensions/machine-learning/src/prediction/predictService.ts

ML - Fixed the issue with opening none SQL editor for predict script

---

scripts/test-extensions-unit.sh

seems like @Charles-Gagnon only updated the .bat file.

disable the sql proj tests

---

extensions/azurecore/src/azureResource/commands.ts
src/sql/platform/connection/common/connectionProfile.ts
src/sql/workbench/contrib/azure/browser/azure.contribution.ts
src/sql/workbench/services/connection/common/connectionContextKey.ts

Adds the right click -> Open in Azure to the servers view

Make azure portal work from server area

---

extensionsGallery-insider.json
extensionsGallery.json

Update extensionsGallery-insider.json for ML extension

---

extensions/machine-learning/package.json

Updating extension version to 0.2.1

ML - Updating ML extension version for the latest fixes

---

extensionsGallery-insider.json

Also added azdata engine check

Update to latest arc deployment extension

---

extensionsGallery-insider.json
extensionsGallery.json

Add sql-assessment extension to stable gallery
Update data-virtualization extension to 1.5.0

Add sql-assessment and update datavirt

---

src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts

Only show edit cell action for markdown cells (#10719)

---

src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts
src/sql/workbench/contrib/notebook/browser/notebook.component.ts

Change markdown cell to text cell (#10715)

---

build/azure-pipelines/sql-product-compile.yml
build/gulpfile.vscode.js

Add upload of sourcemaps

---

product.json

Address issue https://github.com/microsoft/azuredatastudio/issues/10748 in master.

Add Redgate Search to recommendation list

---

product.json

Ports a fix for https://github.com/microsoft/azuredatastudio/issues/10748 to release/1.19

Port: Add Redgate Search to recommendation list (#10749)

---

extensions/notebook/src/dialog/configurePython/configurePythonWizard.ts

Add custom width to Python wizard to reduce wasted space.

---

package.json

reduce max memory (#10775)

---

src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts

Bring back hover state setting on cell model (#10758)

---

src/sql/workbench/contrib/notebook/browser/cellViews/code.css

Removed style that was interfering with text selection within code cell

---

src/sql/workbench/contrib/notebook/browser/notebook.css

Notebook UI - Adjusted cell spacing

---

extensionsGallery-insider.json
extensionsGallery.json

Update the Dacpac extension to 1.5.0

Update Dacpac extension in gallery

---

src/sql/workbench/services/accountManagement/browser/accountDialog.ts

This PR fixes #10734
I'm not ENTIRELY sure what this container does (as its literally an empty class), but....this fixes the problem.
I know for sure that we do need this container though, and we should probably look to see if we're adding views directly without tying them to anything because it's likely going to break in the future.

Fixes #10734, register a container for the view

---

src/sql/base/browser/ui/table/plugins/buttonColumn.plugin.ts

This PR fixes #10736 
cause the fix has been explained in the code comments

fix button column click issue

---

src/sql/workbench/services/connection/browser/connectionManagementService.ts

Fixes #10753
bug was reported by the ossrdbmbs team.

Fixes the azure auth for postgresql (#10662)

---

src/sql/workbench/contrib/query/browser/queryActions.ts
src/sql/workbench/contrib/query/test/browser/queryActions.test.ts

…t statement in the selection
This PR fixes #10538

Fix for "Run Current Query" keybind no longer behaving as expected (#10538)

---

extensions/notebook/src/book/bookModel.ts
extensions/notebook/src/book/bookTreeView.ts
extensions/notebook/src/extension.ts

* highlight correct notebook on navigation.
Ports #10807 to release to address the below:
This PR fixes #10780

highlight correct notebook on navigation. (#10807)

---

extensions/resource-deployment/package.json

This PR fixes #10721 
adjusting the order of the available versions.

change default versions

---

src/sql/workbench/browser/modelComponents/declarativeTable.component.ts

This PR fixes #10656 
Before fix:
After fix:

Change Declarative column header from type 'text' to 'column header'

---

extensions/sql-database-projects/package.json
extensions/sql-database-projects/package.nls.json
extensions/sql-database-projects/src/common/constants.ts
extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts
extensions/sql-database-projects/src/controllers/mainController.ts
extensions/sql-database-projects/src/controllers/projectController.ts

Just a simple welcome message for empty state with buttons to help user get started

Adds welcome message for database projects

---

src/sql/workbench/contrib/notebook/browser/notebook.css

Fixed notebook toolbar icon issue in dark and hc-black themes. (#10802)

---

extensions/mssql/config.json

Update SQL Tools Service to address https://github.com/microsoft/azuredatastudio/issues/10816

Update SQL Tools Service to include "use master" revert

---

extensions/mssql/config.json

Port fix for https://github.com/microsoft/azuredatastudio/issues/10816

Update SQL Tools Service to include "use master" revert (#10834)

---

extensions/notebook/src/book/bookTreeView.ts
extensions/notebook/src/extension.ts

Fix Notebook Viewlet Highlighting (#10868)

---

test/automation/src/sql/notebook.ts
test/automation/src/sql/queryEditor.ts
test/automation/src/workbench.ts
test/smoke/src/sql/areas/notebook/notebook.test.ts
test/smoke/src/sql/areas/queryEditor/queryEditor.test.ts
test/smoke/src/sql/main.ts

rewrite some automation; add notebook tests

---

build/azure-pipelines/sql-product-build.yml
build/azure-pipelines/web/sql-product-build-web.yml

Add web compile

---

extensions/resource-deployment/notebooks/bdc/2019/deploy-bdc-aks.ipynb
extensions/resource-deployment/notebooks/bdc/2019/deploy-bdc-existing-aks.ipynb
extensions/resource-deployment/notebooks/bdc/2019/deploy-bdc-existing-aro.ipynb
extensions/resource-deployment/notebooks/bdc/2019/deploy-bdc-existing-kubeadm.ipynb
extensions/resource-deployment/notebooks/bdc/2019/deploy-bdc-existing-openshift.ipynb
extensions/resource-deployment/notebooks/docker/2017/deploy-sql2017-image.ipynb
extensions/resource-deployment/notebooks/docker/2019/deploy-sql2019-image.ipynb

update the notebooks to reflect the recent notebook toolbar changes.

update the notebook description

---

src/sql/workbench/api/browser/mainThreadConnectionManagement.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/10773

If the connectionProfile was undefined, then return undefined

---

src/sql/workbench/services/accountManagement/browser/accountManagementService.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/10476

Add close button

---

CHANGELOG.md
README.md

Update readme and changelog for 1.19.0

Update readme for 1.19.0

---

extensions/sql-database-projects/src/models/project.ts

Fix sql proj round trip test failures 

---

extensions/sql-database-projects/src/extension.ts
extensions/sql-database-projects/src/test/datasource.test.ts
extensions/sql-database-projects/src/test/deployDatabaseDialog.test.ts
extensions/sql-database-projects/src/test/netCoreTool.test.ts
extensions/sql-database-projects/src/test/projectController.test.ts
extensions/sql-database-projects/src/test/projectTree.test.ts
extensions/sql-database-projects/src/test/utils.test.ts

Disable half of the tests for sql database projects and added a couple of logging lines around activation of extension.

Disable half of the tests for sql database projects

---

src/vs/code/browser/workbench/workbench.html

fix edit data

---

src/sql/workbench/contrib/dashboard/browser/widgets/insights/insightsWidget.component.ts
src/sql/workbench/services/insights/browser/insightsDialogController.ts
src/sql/workbench/services/insights/common/insightsUtils.ts
src/sql/workbench/services/insights/test/electron-browser/insightsUtils.test.ts

maintain scheme in insights

---

extensions/sql-database-projects/src/common/constants.ts
extensions/sql-database-projects/src/dialogs/deployDatabaseDialog.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/10932

Fixes issue where wrong property was checked for deployment type

---

src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts

This is a port of #6630 by @MaddyDev to editdatagridpanel
This PR fixes #1303

Port of #6630: edit data line breaks port

---

extensions/dacpac/package.json
package.json

Bump Azure Data Studio version

---

.github/pull_request_template.md
extensions/asde-deployment/notebooks/edge/deploy-sql-edge-local.ipynb
extensions/asde-deployment/notebooks/edge/deploy-sql-edge-remote.ipynb
extensions/azurecore/README.md
extensions/query-history/README.md
extensions/resource-deployment/notebooks/bdc/2019/deploy-bdc-aks.ipynb
extensions/resource-deployment/notebooks/bdc/2019/deploy-bdc-existing-aks.ipynb
extensions/resource-deployment/notebooks/bdc/2019/deploy-bdc-existing-kubeadm.ipynb
extensions/resource-deployment/notebooks/docker/2017/deploy-sql2017-image.ipynb
extensions/resource-deployment/notebooks/docker/2019/deploy-sql2019-image.ipynb
extensions/schema-compare/README.md
extensions/schema-compare/package.json
extensions/sql-assessment/README.md
extensions/sql-assessment/package.json
extensions/sql-database-projects/README.md
extensions/sql-database-projects/package.json
extensions/sql/syntaxes/sql.tmLanguage.json
samples/notebookSamples/SampleTSQLNotebook.ipynb
samples/sample-resource-deployment/package.json
samples/serverReports/README.md
samples/sp_whoIsActive/README.md
samples/sqlservices/package.json

Update more stuff to new `main` branch

Update branch references

---

extensions/azurecore/src/azureResource/commands.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/10962

Account value was never set in the `this` context

---

extensions/notebook/coverConfig.json
extensions/notebook/src/test/model/notebookManager.test.ts
extensions/notebook/src/test/model/serverManager.test.ts

Had no test coverage for Jupyter Notebook Manager. Pretty simple tests here.

Add Jupyter Notebook Manager Tests

---

extensionsGallery-insider.json

Update schema compare extension in insiders to 1.5.0 for the changes that Sql Project needs. This PR fixes #10967.

Update schema compare extension in insiders

---

extensionsGallery-insider.json
extensionsGallery.json

update master to main for azuredatastudio repo references

update the branch references

---

extensions/arc/src/common/utils.ts
extensions/arc/src/localizedConstants.ts
extensions/arc/src/models/controllerModel.ts
extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts

Hooking up the deletion button for MIAA and updating PG and MIAA to use the same deletion request prompt.
Also improved the error message when an HttpError occurs since the default message wasn't very useful (would just say HTTP request failed)

Hook up deletion for MIAA

---

extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts
extensions/sql-database-projects/src/controllers/mainController.ts
extensions/sql-database-projects/src/controllers/projectController.ts

Caught a few missing awaits by running sqllint. Verified with Benjin that these need to be updated.

Add missing await

---

test/smoke/src/sql/main.ts

Small improvement to make the errors from the smoke test start up make more sense.

Better Smoke test setup

---

build/azure-pipelines/linux/sql-product-build-linux.yml

Use cp for coverage copy

---

extensions/arc/package.json
extensions/arc/src/controller/auth.ts
extensions/big-data-cluster/package.json
extensions/big-data-cluster/package.nls.json
extensions/big-data-cluster/src/bigDataCluster/constants.ts
extensions/big-data-cluster/src/bigDataCluster/tree/connectControllerNode.ts
extensions/big-data-cluster/src/bigDataCluster/tree/controllerTreeDataProvider.ts
extensions/big-data-cluster/src/bigDataCluster/tree/controllerTreeNode.ts
extensions/big-data-cluster/src/commands.ts
extensions/big-data-cluster/src/extension.ts
src/vs/base/common/codicons.ts

Matching with behavior for the Arc view.
2 actions - existing one (previously the + icon) moved to "Connect" icon. New action added for creating new controller that will open deployment dialog.
@anthonydresser - Added new codicon since the debug-disconnect is colored red by default. Let me know if there's a better way I could be handling that. (I considered making a separate codicons file in sql but didn't seem worth the effort for a single line thing)
(also did some other general cleanup of unused stuff)

Add BDC create controller action

---

extensions/sql-database-projects/src/dialogs/deployDatabaseDialog.ts

This PR fixes # https://github.com/microsoft/azuredatastudio/issues/10983 for this insiders with minimal change. Will re-enable post insiders for further work. Validated with all enabled/disabled tests

removing datasource from publish dialog for insiders

---

extensions/sql-database-projects/src/controllers/projectController.ts

Don't show error message when cancelling connection dialog for import project

---

extensions/kusto/package.json

2729 Fixed connection dialog for kusto server

---

extensionsGallery-insider.json

Going to wait until things have been tested a bit more before adding the new extension to the gallery.

Revert arc extension changes

---

extensions/arc/src/ui/components/keyValueContainer.ts
extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts

Fixes an issue with concurrent refreshes of the KeyValueContainer

Arc - Fix KeyValueContainer refresh

---

extensions/arc/src/models/controllerModel.ts
extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts
extensions/arc/src/ui/tree/azureArcTreeDataProvider.ts
extensions/arc/src/ui/tree/controllerTreeNode.ts

Add dashboard links to arc controller dashboard

---

extensions/asde-deployment/notebooks/edge/deploy-sql-edge-local.ipynb
extensions/resource-deployment/notebooks/docker/2017/deploy-sql2017-image.ipynb
extensions/resource-deployment/notebooks/docker/2019/deploy-sql2019-image.ipynb

This PR fixes #11024
for the commands that contains password, we shouldn't print the commands

add to parameter to decide whether to print the command

---

extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts
extensions/arc/src/ui/dashboards/postgres/postgresResourceHealthPage.ts

- Removes the new database button until we support all the options for it
- Minor style fixes to resource health page to match the design

Arc Postgres - Remove new database and style fixes

---

extensions/arc/src/extension.ts
extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts
extensions/resource-deployment/src/main.ts
extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts

Add resource type filtering to deployment wizard

---

extensions/asde-deployment/notebooks/edge/deploy-sql-edge-local.ipynb
extensions/asde-deployment/notebooks/edge/deploy-sql-edge-remote.ipynb
extensions/resource-deployment/notebooks/bdc/2019/deploy-bdc-aks.ipynb
extensions/resource-deployment/notebooks/bdc/2019/deploy-bdc-existing-aks.ipynb
extensions/resource-deployment/notebooks/bdc/2019/deploy-bdc-existing-aro.ipynb
extensions/resource-deployment/notebooks/bdc/2019/deploy-bdc-existing-kubeadm.ipynb
extensions/resource-deployment/notebooks/bdc/2019/deploy-bdc-existing-openshift.ipynb
extensions/resource-deployment/notebooks/docker/2017/deploy-sql2017-image.ipynb
extensions/resource-deployment/notebooks/docker/2019/deploy-sql2019-image.ipynb

Chatted with @yualan offline, and he is ok adding this note to remind user about the password in the connect to sql server link.

add note about the password

---

extensionsGallery-insider.json

Adding SQL Database Projects extension to gallery

---

extensions/arc/src/models/controllerModel.ts
extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts
extensions/arc/src/ui/tree/controllerTreeNode.ts

When deleting sqlmiaa and postgres, delete the registration too

Arc - Delete registration

---

extensionsGallery-insider.json
extensionsGallery.json

This PR adds WakaTime extension to the list.
@alanrenmsft @llali

Add WakaTime extension

---

extensions/sql-database-projects/src/controllers/mainController.ts
extensions/sql-database-projects/src/controllers/projectController.ts
extensions/sql-database-projects/src/test/deployDatabaseDialog.test.ts
extensions/sql-database-projects/src/test/projectController.test.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/11100

Spot-fix for incorrect placement of sqlproj when importing to new project

---

extensions/sql-database-projects/src/controllers/projectController.ts

This PR fixes #10982
old:
fixed:

Fix sql proj import asking for db twice if connection was to a db

---

extensions/arc/package.json
extensions/resource-deployment/src/ui/modelViewUtils.ts

fix: 'Arc data controller deployment fails' #11086

---

extensionsGallery-insider.json

Update sql-database-projects to 0.1.1

---

src/sql/workbench/contrib/notebook/browser/notebookEditor.ts
src/sql/workbench/contrib/notebook/test/browser/notebookEditor.test.ts

Reverting back to the original code. 
@ranasaria  Can you fix your tests accordingly or disable them temporarily until we figure out a way.
This PR fixes #11109

revert back to original code

---

extensions/sql-assessment/package.json

since this is now in gallery, the metadata is getting added automatically.

format file and add metadata

---

extensions/arc/.vscodeignore
extensions/arc/package.json
extensions/resource-deployment/src/ui/deployClusterWizard/pages/azureSettingsPage.ts
extensions/resource-deployment/src/ui/deployClusterWizard/pages/clusterSettingsPage.ts
extensions/resource-deployment/src/ui/deployClusterWizard/pages/deploymentProfilePage.ts
extensions/resource-deployment/src/ui/deployClusterWizard/pages/serviceSettingsPage.ts
extensions/resource-deployment/src/ui/deployClusterWizard/pages/summaryPage.ts
extensions/resource-deployment/src/ui/deployClusterWizard/pages/targetClusterPage.ts
extensions/resource-deployment/src/ui/modelViewUtils.ts
extensions/resource-deployment/src/ui/notebookWizard/notebookWizardAutoSummaryPage.ts
extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts
extensions/resource-deployment/src/ui/wizardBase.ts
extensions/resource-deployment/src/ui/wizardPageBase.ts

Use azurecore API for getting display name. Also fixed it so it actually respects the defaultValue field.

Change Azure region dropdown to use azurecore API

---

extensionsGallery-insider.json
extensionsGallery.json

Updates Schema visualization to v0.3.0

Update Schema visualization to v0.3.0

---

extensionsGallery-insider.json
extensionsGallery.json

We need to rename our extension to Sql-Assessment

update display name for sql assessment extension

---

extensions/arc/coverConfig.json
extensions/arc/src/common/utils.ts
extensions/arc/src/test/common/date.test.ts
extensions/arc/src/test/common/utils.test.ts
extensions/arc/src/test/controller/auth.test.ts

And added a few more files to ignore that don't have anything worth testing in them

Add more arc tests

---

extensionsGallery-insider.json
extensionsGallery.json

Fixes https://github.com/microsoft/azuredatastudio/issues/11091

Update Data Virtualization to 1.6.0

---

extensions/integration-tests/src/onboarding/developers.ts

 Onboarding pull request

---

extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
extensions/sql-database-projects/src/test/buildHelper.test.ts
extensions/sql-database-projects/src/test/datasource.test.ts
extensions/sql-database-projects/src/test/mainController.test.ts
extensions/sql-database-projects/src/test/netCoreTool.test.ts
extensions/sql-database-projects/src/test/projectController.test.ts
extensions/sql-database-projects/src/test/projectTree.test.ts
extensions/sql-database-projects/src/test/publishDatabaseDialog.test.ts

Cleanup publish database dialog and test sqllint errors

---

extensions/sql-database-projects/package.json
extensions/sql-database-projects/package.nls.json
extensions/sql-database-projects/src/common/constants.ts
extensions/sql-database-projects/src/controllers/mainController.ts
extensions/sql-database-projects/src/controllers/projectController.ts

This PR fixes ##11101. This opens the folder that the sqlproj is in.

Add "Open Containing Folder" to project context menu

---

extensions/azurecore/src/account-provider/auths/azureAuth.ts

Gives more information on https://github.com/microsoft/azuredatastudio/issues/8829

Prints out the actual error that happened

---

resources/linux/code.appdata.xml
resources/linux/debian/control.template

This PR fixes https://github.com/microsoft/azuredatastudio/issues/10613

Change branding of linux version

---

extensions/azurecore/src/account-provider/auths/azureAuth.ts

Reverts microsoft/azuredatastudio#11208

Revert "Prints out the actual error that happened"

---

src/sql/workbench/services/accountManagement/browser/accountDialog.ts

https://github.com/microsoft/azuredatastudio/issues/11172

Fixes the azure account pane location

---

src/sql/workbench/services/accountManagement/browser/accountDialog.ts

Fixes the azure account pane location (#11211)

---

src/sql/workbench/contrib/notebook/browser/notebookEditor.ts

Port #11215 to release branch.
This PR ports fix for #11120 into release branch

set currentMatch on find changes only

---

extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts

Don't update database name to master in publish dialog

---

extensions/resource-deployment/src/ui/modelViewUtils.ts

I thought I pushed this commit, but when I was about to delete the local branch i noticed this is not pushed to remote branch. the original PR has been merged. original pr:https://github.com/microsoft/azuredatastudio/pull/11202

remove px from width string and then parse

---

extensions/notebook/package.json
extensions/notebook/resources/pythonScripts/startNotebook.py
extensions/notebook/src/common/apiWrapper.ts
extensions/notebook/src/jupyter/jupyterServerInstallation.ts
extensions/notebook/src/jupyter/jupyterServerManager.ts
extensions/notebook/src/jupyter/serverInstance.ts
extensions/notebook/src/test/managePackages/managePackagesDialogModel.test.ts
extensions/notebook/src/test/model/serverInstance.test.ts

Disable python downloads when running notebooks on a SAW. (#11186)

---

extensions/sql-assessment/README.md
extensions/sql-assessment/package.nls.json

rename SQL Server Extension to SQL Extension. Fixing display name and description.

SQL Assessment display name and description update

---

src/vs/workbench/contrib/files/browser/fileCommands.ts

Fix issues with file menu commands

---

src/vs/workbench/contrib/files/browser/fileCommands.ts

fix issues with file menu commands (#11254)

---

extensions/resource-deployment/src/ui/modelViewUtils.ts

fix account dropdown list issue

---

src/sql/workbench/contrib/commandLine/electron-browser/commandLine.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/11230

Fixes the SSMS launch issue

---

src/sql/workbench/contrib/commandLine/electron-browser/commandLine.ts

* Fixes the SSMS launch issue
* Spelling
This PR fixes #11230

Fixes the SSMS launch issue (#11257)

---

extensions/notebook/src/book/bookTreeView.ts

Related (approved) issue #11268

Fix no books currently selected error in viewlet (#11269)

---

extensions/integration-tests/src/onboarding/developers.ts

Onboarding Pull Request

---

build/lib/extensions.js
src/sql/workbench/contrib/query/browser/gridPanel.ts
src/sql/workbench/contrib/query/browser/queryInputFactory.ts

fix configuration access for grid

---

extensions/integration-tests/src/onboarding/developers.ts

Not sure if I was supposed to do this when I onboarded but I see others doing it now so 🤷‍♂️

Onboarding PR

---

src/sql/workbench/services/insights/browser/insightsDialogView.ts

fixes issue #11284 
port the fix to release branch. original PR: https://github.com/microsoft/azuredatastudio/pull/11309

fix insight details dialog issue (#11309)

---

src/sql/workbench/services/accountManagement/browser/accountDialog.ts
src/vs/workbench/common/views.ts

Port request for https://github.com/microsoft/azuredatastudio/issues/11283
(cherry picked from commit 3db33de69fe68910026f7b894e393390ec701586)

Add new ViewContainerLocation for dialogs (#11289)

---

extensions/dacpac/src/test/DacFxTestConfigPages.ts
extensions/dacpac/src/test/configPages.test.ts
extensions/dacpac/src/test/testContext.ts
extensions/dacpac/src/test/wizard.test.ts
extensions/dacpac/src/wizard/dataTierApplicationWizard.ts
extensions/dacpac/src/wizard/pages/deployConfigPage.ts

Added more tests for wizard and some for config pages

Dacpac extensions tests - for investigation

---

src/vs/workbench/api/browser/mainThreadTreeViews.ts

Port https://github.com/microsoft/azuredatastudio/commit/73fd3d358493e4b52e96a648edbfb655a3835a6d

Revert to previous behavior for tree data providers getChildren (#11308)

---

src/sql/platform/query/common/query.ts
src/sql/workbench/common/editor/query/queryEditorInput.ts
src/sql/workbench/contrib/query/browser/query.contribution.ts
src/sql/workbench/services/query/common/queryRunner.ts
src/sql/workbench/services/query/common/resultSerializer.ts
src/sql/workbench/services/queryEditor/browser/queryEditorService.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/11315

Fix access to query editor configuration

---

src/sql/workbench/common/workspaceActions.ts
src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
src/sql/workbench/services/query/common/resultSerializer.ts

This reverts commit 381a747b623f877db5f58970e2c72838c54691d1.
This PR addresses #11316

Revert "fix export for remote (#10934)"

---

src/sql/workbench/services/connection/browser/connectionController.ts

Fix default connection group by changing ordering of groups

---

src/sql/workbench/services/connection/browser/connectionController.ts

fix default connection group by changing ordering of groups (#11303)

---

src/sql/platform/query/common/query.ts
src/sql/workbench/common/editor/query/queryEditorInput.ts
src/sql/workbench/contrib/query/browser/query.contribution.ts
src/sql/workbench/services/query/common/queryRunner.ts
src/sql/workbench/services/query/common/resultSerializer.ts
src/sql/workbench/services/queryEditor/browser/queryEditorService.ts

* fix access to query editor configuration
* fix configuration type
* fix setting type

Fix access to query editor configuration (#11321)

---

src/sql/workbench/browser/modelComponents/declarativeTable.component.ts

Fixes the declarative table issue (#11330)

---

extensions/azurecore/package.json
extensions/azurecore/package.nls.json
extensions/azurecore/src/account-provider/auths/azureAuth.ts
extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts
extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts
extensions/azurecore/src/account-provider/interfaces.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/11070

Handle don't ask again button

---

test/smoke/src/main.ts

fix screenshots for smoketests

---

extensions/import/config.json

Bumping up the import services version to 0.0.4

---

extensions/import/package.json

0.16 is already in insider build, we need a new version.

bump import extension version

---

CHANGELOG.md
README.md

update change log and readme

---

extensionsGallery-insider.json
extensionsGallery.json

update gallery files

---

extensions/import/package.json
extensions/sql-assessment/package.json
package.json
product.json

update the ads version to 1.21, also update the extensions that were updated during the release.

post release vbump

---

src/sql/workbench/services/query/common/resultSerializer.ts

Add option to open excel file externally

---

src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts

Accessibility issue: #10623. Non header element is announced with heading level. This PR fixes the issues by replacing them with label tags.
This PR fixes #10623

accessibility fix: swaps header tags for label tags on most recent list

---

src/vs/workbench/services/themes/browser/workbenchThemeService.ts

Default theme to light

---

src/sql/workbench/contrib/welcome/page/browser/gettingStartedTour.ts

This PR updates the copy seen in the command palette for starting the getting started tour per PM request.

updates copy for starting the getting started tour in the command palette

---

test/automation/src/sql/connectionDialog.ts

Fix issues with web smoke tests

---

src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts
src/vs/workbench/browser/parts/editor/editorDropTarget.ts

Fixed the formatting of the dragged table name
This PR fixes #11372

fix for dragged table name

---

package.json
src/vs/base/browser/ui/contextview/contextview.ts
src/vs/editor/contrib/suggest/suggestModel.ts
src/vs/platform/workspaces/common/workspaces.ts
src/vs/workbench/api/common/extHostTreeViews.ts
src/vs/workbench/api/common/extHostTypes.ts
src/vs/workbench/contrib/logs/common/logs.contribution.ts
src/vs/workbench/contrib/scm/browser/scmViewPane.ts
src/vs/workbench/contrib/webview/electron-browser/webview.contribution.ts
src/vs/workbench/services/extensionManagement/common/webExtensionsScannerService.ts

https://github.com/microsoft/vscode/commit/17299e413d5590b14ab0340ea477cdd86ff13daf (vscode/release/1.47) fixes https://www.github.com/microsoft/vscode/issues/102409 (https://www.github.com/microsoft/vscode/issues/102544)
https://github.com/microsoft/vscode/commit/21651b0e98c5f4c66d4bbcebee1931b01ba4a936 chore: cherry pick commits from robo/msrc_58478 (https://www.github.com/microsoft/vscode/issues/102524)
https://github.com/microsoft/vscode/commit/282ac0e481fbd41aeff01fbc3fe56070bc29c2bc Merge pull request https://www.github.com/microsoft/vscode/issues/102479 from microsoft/joao/release/1.47/fix-102358
https://github.com/microsoft/vscode/commit/70ced3a23e1fb19a9691ed1903f6c3b1107a87e6 Merge pull request https://www.github.com/microsoft/vscode/issues/102490 from …

Merge from vscode 17299e413d5590b14ab0340ea477cdd86ff13daf

---

src/vs/workbench/services/themes/browser/workbenchThemeService.ts

default theme to light (#11358)

---

src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts
src/vs/workbench/browser/parts/editor/editorDropTarget.ts

port drag and drop fix

---

CHANGELOG.md

update change log for 1.20.1

---

extensions/integration-tests/src/test/dacpac.test.ts
extensions/integration-tests/src/test/objectExplorer.test.ts
extensions/integration-tests/src/test/schemaCompare.test.ts
extensions/integration-tests/src/test/utils.ts

We shouldn't be failing tests if cleanup fails sine that's not an actual product issue.

Don't throw if cleanup drop fails

---

extensions/azurecore/src/account-provider/auths/azureAuth.ts
extensions/azurecore/src/test/account-provider/auths/azureAuth.test.ts

This PR fixes a mistake made by https://github.com/microsoft/azuredatastudio/pull/11236

Tenant filter fix

---

extensions/azurecore/src/account-provider/auths/azureAuth.ts
extensions/azurecore/src/azureResource/commands.ts
extensions/azurecore/src/azureResource/tree/accountTreeNode.ts
extensions/azurecore/src/test/azureResource/tree/accountTreeNode.test.ts
extensions/mssql/src/features.ts
src/sql/azdata.d.ts
src/sql/azdata.proposed.d.ts
src/sql/workbench/services/accountManagement/browser/accountListRenderer.ts
src/sql/workbench/services/connection/browser/connectionWidget.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/11353

Use a unique key for the accounts

---

extensions/azdata/package.json
extensions/azdata/src/azdata.ts
extensions/azdata/src/common/childProcess.ts
extensions/azdata/src/common/httpClient.ts
extensions/azdata/src/extension.ts
extensions/azdata/src/localizedConstants.ts
extensions/azdata/yarn.lock

Other platforms will come later

Add support for installing azdata on Windows

---

src/sql/workbench/contrib/notebook/browser/notebookThemingContribution.ts

This PR fixes the issue with notebooks results grid not updating when settings (font size, weight, etc.) are changed.
This PR fixes #https://github.com/microsoft/azuredatastudio/issues/11004

Fix notebook results grid settings not updating

---

build/azure-pipelines/darwin/sql-product-build-darwin.yml

disable web smoke again

---

extensions/import/package.json

revert it back to 0.18.0 as we already bumped the version post release.

update import extension version

---

extensionsGallery-insider.json
extensionsGallery.json

bump import to 0.18

---

extensions/import/package.json

0.18.0 just got released, bump the version

---

extensions/notebook/src/jupyter/jupyterController.ts
extensions/notebook/src/jupyter/localPipPackageManageProvider.ts
extensions/notebook/src/jupyter/pypiClient.ts
extensions/notebook/src/test/managePackages/localPackageManageProvider.test.ts

Also fixed a typo in the class name.

Add some unit tests for PyPiClient.

---

extensions/azdata/package.json
extensions/azdata/src/azdata.ts
extensions/azdata/src/common/childProcess.ts
extensions/azdata/src/extension.ts
extensions/azdata/yarn.lock

Will follow up with updating tests to account for the new logic.
A couple things I want to iron out but will do in separate PRs : 
1. Currently this prompts for each command executed which gets pretty spammy. Will look into doing all commands at once to reduce down to one prompt
1. Making sure errors are localized correctly when displayed to user
1. Verifying lsb_release usage and how it works with the download path for the repo

Adds support for installing azdata on Linux

---

extensions/arc/notebooks/arcDeployment/deploy.postgres.existing.arc.ipynb
extensions/arc/package.json

Arc - Remove Azure params from Postgres deployment.

Arc - Remove Azure params from Postgres deployment

---

src/sql/base/browser/ui/selectBox/selectBox.ts
src/sql/base/test/browser/ui/selectBox/selectBox.test.ts
src/sql/workbench/services/connection/browser/connectionWidget.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/11481

change userName to match what the azure account display name is

---

extensions/asde-deployment/notebooks/edge/deploy-sql-edge-single-device.ipynb
extensions/asde-deployment/package.json
extensions/asde-deployment/package.nls.json

deploy to single existing device

---

extensions/azurecore/src/azureResource/utils.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/11501

Changes to getAccountSecurityToken

---

extensions/arc/notebooks/arcDeployment/deploy.arc.control.plane.ipynb

Not sure when this broke. And display_location seems like the wrong var name to be using - but this fixes the issue so doing this now to unblock deployment.

Fix location parameter for Arc controller deployment

---

extensions/integration-tests/src/onboarding/developers.ts

Onboarding Check In (new PR uses GitHub username instead of MS alias)

Onboarding Check In

---

src/sql/platform/serialization/common/serializationService.ts
src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/11068
Added includeHeaders parameter when getting rows for serialization.

Fix Notebook data export to excel/csv not including headers

---

extensions/resource-deployment/src/ui/modelViewUtils.ts
extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts

emit error for kube file not found

---

extensions/sql-database-projects/src/common/utils.ts
extensions/sql-database-projects/src/test/projectController.test.ts
extensions/sql-database-projects/src/test/utils.test.ts
extensions/sql-database-projects/src/tools/netcoreTool.ts

This PR fixes # https://github.com/microsoft/azuredatastudio/issues/10973 and some minor test cleanup

Small fixes for output window and test

---

src/sql/workbench/contrib/query/browser/queryActions.ts
src/sql/workbench/services/queryEditor/browser/queryEditorService.ts

Issue when a new query is opened by selecting either the Kusto cluster or database from Connections list

New query fix from Cluster/Database kusto connection

---

src/sql/workbench/contrib/query/browser/media/messagePanel.css

add wrap for error message

---

extensions/azurecore/src/account-provider/auths/azureAuth.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/11537

Special case personal accounts

---

extensions/arc/notebooks/arcDeployment/deploy.arc.control.plane.ipynb
extensions/resource-deployment/src/ui/modelViewUtils.ts

change back to using locationVariableName

---

src/sql/workbench/contrib/query/browser/queryInputFactory.ts
src/sql/workbench/contrib/query/test/browser/queryInputFactory.test.ts
src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
src/sql/workbench/services/queryEditor/common/queryEditorService.ts

Use existing resource for untitled if it is already open

---

extensions/azdata/src/extension.ts

Fixes #11574
Will figure out better way to handle this later - just getting rid of the annoying popup for now.

Remove azdata toast startup notifications

---

extensions/asde-deployment/notebooks/edge/deploy-sql-edge-multi-device.ipynb
extensions/asde-deployment/package.json
extensions/asde-deployment/package.nls.json

deploy ASDE to multiple devices

---

extensions/sql-database-projects/src/controllers/mainController.ts
extensions/sql-database-projects/src/controllers/projectController.ts

Fix focus going to file explorer viewlet when automatically opening sql projects in the open folder

---

extensions/asde-deployment/notebooks/edge/deploy-sql-edge-azure.ipynb

use correct environment variable for location, the value of AZDATA_NB_VAR_ASDE_AZURE_LOCATION_TEXT was recently updated by this PR: https://github.com/microsoft/azuredatastudio/pull/11559

update to use correct environment variable

---

src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
src/sql/workbench/services/objectExplorer/test/browser/testObjectExplorerService.ts

Cleaning up for readability - no functional changes here

Thenable -> Promise in OE Service

---

extensions/import/src/wizard/pages/fileConfigPage.ts

added focus to first element in the form

---

extensions/sql-database-projects/src/controllers/projectController.ts

Update sql project already exists error message

---

extensionsGallery-insider.json

This PR updates extension version for Sql DB project extension

updating sql db project extensions version

---

extensions/notebook/package.json

remove old code

---

extensions/notebook/package.json

Ports #11620 to release.
This PR fixes #11612

remove old code (#11620)

---

extensions/azurecore/src/test/account-provider/auths/azureAuth.test.ts

test case failing

---

extensionsGallery-insider.json
extensionsGallery.json

bump sanddance version to 3.1.0

---

extensions/resource-deployment/package.json
extensions/resource-deployment/src/services/azdataService.ts
extensions/resource-deployment/src/test/apiService.test.ts
extensions/resource-deployment/src/test/azdataService.test.ts
extensions/resource-deployment/yarn.lock

add some unit test for resource deployment ext

---

extensions/notebook/src/jupyter/serverInstance.ts

Use a regex to detect notebook started message. (#11642)

---

src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts

This PR fixes the issue of the open button text not showing.
This PR fixes #11598
Before: 
After:

fixes button font color not showing on welcome page #11598

---

src/sql/workbench/services/accountManagement/browser/accountPickerImpl.ts

This fixes an issue with the dropdowns not being populated correctly:

Firewall dropdown fix

---

extensions/azurecore/src/account-provider/auths/azureAuth.ts
extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts
extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts
extensions/azurecore/src/account-provider/azureAccountProvider.ts
extensions/azurecore/src/account-provider/interfaces.ts

I really need to enable strict TSConfig rules...
Going to need to port this into release as well.

 Return cancelled, not undefined for azure login

---

src/sql/workbench/services/accountManagement/browser/accountPickerImpl.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/11662

Dropdown fix (#11660)

---

extensions/azurecore/src/account-provider/auths/azureAuth.ts
extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts
extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts
extensions/azurecore/src/account-provider/azureAccountProvider.ts
extensions/azurecore/src/account-provider/interfaces.ts

Not a fix, but addresses a side effect of https://github.com/microsoft/azuredatastudio/issues/11493

 Return cancelled, not undefined for azure login (#11656)

---

src/sql/platform/dashboard/browser/interfaces.ts
src/sql/workbench/browser/modelComponents/modelStore.ts
src/sql/workbench/browser/modelComponents/viewBase.ts

Fixes #11666
Fixes #11665
This reverts commit 9bdd5f2899b36a44bca4add1f05164cf1489929b.
I'll be coming back to this to try and dig into what exactly is going on here because this is going to keep causing us problems - but this broke a lot of core scenarios so rolling back for now.

Revert "Do ModelView initialization actions before others (#11512)"

---

src/vs/workbench/services/textfile/browser/textFileService.ts

* regression fix from vscode merge
* pass language not mode for getting the extension
* fix compile errors on vscode.
* case sensitive update
This PR fixes #11564

Fix/save defaults to txt (#11623)

---

build/azure-pipelines/win32/sql-product-build-win32.yml

Add task for downloading Python package when building ADS for SAW devices. (#11659)

---

src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts

Fix for notebook intellisense

---

extensions/kusto/package.json
extensions/kusto/package.nls.json
extensions/kusto/yarn.lock

Fix manage dashboard

---

src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts

This PR fixes #https://github.com/microsoft/azuredatastudio/issues/11684

Add welcomePageWithTour to startupEditor check (#11702)

---

src/sql/workbench/contrib/dashboard/browser/dashboardRegistry.ts
src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerWidget.component.ts

custom hint text

---

src/sql/workbench/services/dialog/browser/dialogContainer.component.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/11199
Change wizard page title to heading 2 if there is a page number, otherwise title is heading 1.

change wizard page title to heading 2

---

extensions/machine-learning/src/common/apiWrapper.ts
extensions/machine-learning/src/modelManagement/azureModelRegistryService.ts

ML - Removing reference to deprecated API

---

extensions/machine-learning/package.json

Updating ML ext version to 0.2.3

---

extensionsGallery-insider.json
extensionsGallery.json

Update ML extension version 

---

build/azure-pipelines/darwin/createDrop.sh
build/azure-pipelines/darwin/sql-product-build-darwin.yml
build/azure-pipelines/linux/createDrop.sh
build/azure-pipelines/linux/sql-product-build-linux.yml
build/azure-pipelines/sql-product-build.yml
build/azure-pipelines/win32/createDrop.ps1
build/azure-pipelines/win32/sql-product-build-win32.yml
package.json

Publish server

---

extensions/mssql/config.json

This PR fixes #https://github.com/microsoft/azuredatastudio/issues/11697 (due to get connection string) and update dacfx for a bug too

update sqltoolsService version for a sqltoolsservice and a dacfx fix

---

extensions/sql-migration/src/models/migrationWizardPage.ts
extensions/sql-migration/src/models/strings.ts
extensions/sql-migration/src/wizard/sourceConfigurationPage.ts
extensions/sql-migration/src/wizard/wizardController.ts

Page changing

---

build/azure-pipelines/darwin/sql-product-build-darwin.yml
test/automation/src/sql/connectionDialog.ts

Fix web smoke tests

---

extensions/machine-learning/src/modelManagement/modelPythonClient.ts
extensions/machine-learning/src/prediction/predictService.ts
extensions/machine-learning/src/prediction/queries.ts
extensions/machine-learning/src/test/prediction/predictService.test.ts
extensions/machine-learning/src/views/models/prediction/columnsTable.ts

ML - Fixed script formatting for prediction

---

extensions/sql-migration/src/models/migrationWizardPage.ts
extensions/sql-migration/src/models/stateMachine.ts
extensions/sql-migration/src/wizard/sourceConfigurationPage.ts

The next piece of work needed to introduce certainty into the UI code is having a way of awaiting property changes for the components

Introduces event queue processor to create a consistent UI for Migrations

---

src/sql/workbench/contrib/query/browser/query.contribution.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/11749

Fix default query shortcuts not being available

---

extensions/notebook/src/book/githubRemoteBook.ts
extensions/notebook/src/book/remoteBookController.ts
extensions/notebook/src/common/constants.ts
extensions/notebook/src/common/utils.ts
extensions/notebook/src/extension.ts
extensions/notebook/src/jupyter/jupyterController.ts
extensions/notebook/src/jupyter/jupyterServerInstallation.ts
extensions/notebook/src/test/common/utils.test.ts

More cleanup (JupyterNotebookProvider handles cleanup, not the controller... Which was always trying to cleanup an empty array!)
Also added to a couple of simple tests.

Notebook Code Cleanup + Utils Test

---

src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts

Fix Notebook Grid Layout Issue

---

extensions/mssql/config.json

This PR fixes https://github.com/microsoft/azuredatastudio/issues/11689

update sqltoolsservice version to fix intellisense bug

---

extensions/azurecore/package.json
extensions/azurecore/package.nls.json
extensions/azurecore/src/azureResource/commands.ts

Removed connectazuredataexplorer command from command.ts, package.json, and package.nls.json

Removed connectAzuredataExplorer command

---

extensions/sql-migration/src/models/product.ts
extensions/sql-migration/src/models/strings.ts
extensions/sql-migration/src/wizard/sourceConfigurationPage.ts

Start with the SKU recommendation screen

---

src/sql/base/browser/ui/loadingSpinner/loadingSpinner.component.ts
src/sql/base/browser/ui/panel/panel.component.ts
src/sql/base/browser/ui/panel/tab.component.ts
src/sql/base/browser/ui/scrollableView/scrollableView.ts
src/sql/base/browser/ui/selectBox/selectBox.ts
src/sql/base/browser/ui/table/highPerf/tableWidget.ts
src/sql/base/browser/ui/table/plugins/buttonColumn.plugin.ts
src/sql/base/browser/ui/table/plugins/textWithIconColumn.ts
src/sql/base/browser/ui/taskbar/overflowActionbar.ts
src/sql/base/test/browser/ui/scrollableView/scrollableView.test.ts
src/sql/base/test/browser/ui/selectBox/selectBox.test.ts
src/sql/platform/accounts/common/accountActions.ts
src/sql/platform/accounts/test/common/testAccountManagementService.ts
src/sql/platform/connection/test/common/connectionProfile.test.ts
src/sql/platform/connection/test/common/testConfigurationService.ts
src/sql/platform/connection/test/common/testConnectionManagementService.ts
src/sql/platform/opener/common/openerServiceStub.ts
src/sql/platform/serialization/common/serializationService.ts
src/sql/workbench/contrib/assessment/test/browser/asmtActions.test.ts
src/tsconfig.vscode.json

Fix a bunch of strict issues

---

build/azure-pipelines/linux/sql-product-build-linux.yml

This PR adds an extensions signing step to the build pipeline. Ideally, everything should work fine and the extensions should be unaffected.

Added ESRP task for signing extensions 

---

extensions/sql-migration/src/models/externalContract.ts
extensions/sql-migration/src/models/migrationWizardPage.ts
extensions/sql-migration/src/models/product.ts
extensions/sql-migration/src/models/stateMachine.ts
extensions/sql-migration/src/models/strings.ts
extensions/sql-migration/src/wizard/skuRecommendationPage.ts
extensions/sql-migration/src/wizard/sourceConfigurationPage.ts
extensions/sql-migration/src/wizard/wizardController.ts
src/sql/azdata.d.ts

skuRecommendationPage & azdata change

---

test/automation/src/playwrightDriver.ts

Disable telemetry on web smoke

---

src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/11867

change notebook grid actions orientation to horizontal

---

extensions/notebook/src/jupyter/serverInstance.ts
extensions/notebook/src/test/model/serverInstance.test.ts

This PR refactors the Server Instance tests by removing the helper methods and changing the test to use Sinon.

Refactored Server Instance Tests

---

src/sql/platform/common/pathUtilities.ts
src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
src/sql/workbench/contrib/notebook/test/browser/dataResourceDataProvider.test.ts

This PR adds tests for DataResourceDataProvider class. So far I've only added tests for getRowRange(), but I wanted to make sure my overall test class format is correct before adding more test cases.

Adding tests for DataResourceDataProvider

---

src/sql/platform/accounts/common/accountStore.ts
src/sql/platform/accounts/common/accountViewModel.ts
src/sql/platform/accounts/common/eventTypes.ts
src/sql/platform/accounts/common/interfaces.ts
src/sql/platform/accounts/test/common/testAccountManagementService.ts
src/sql/workbench/browser/modal/modal.ts
src/sql/workbench/services/accountManagement/browser/accountDialog.ts
src/sql/workbench/services/accountManagement/browser/accountDialogController.ts
src/sql/workbench/services/accountManagement/browser/accountManagementService.ts
src/sql/workbench/services/accountManagement/browser/accountPickerImpl.ts
src/sql/workbench/services/accountManagement/browser/accountPickerService.ts
src/sql/workbench/services/accountManagement/browser/autoOAuthDialog.ts
src/sql/workbench/services/accountManagement/browser/autoOAuthDialogController.ts
src/sql/workbench/services/accountManagement/test/browser/accountManagementService.test.ts
src/sql/workbench/services/accountManagement/test/browser/accountPickerService.test.ts
src/sql/workbench/services/languageAssociation/common/doHandleUpgrade.ts
src/sql/workbench/services/languageAssociation/common/languageAssociation.ts
src/sql/workbench/services/query/common/queryManagement.ts
src/sql/workbench/services/query/common/queryModelService.ts
src/sql/workbench/services/query/common/queryRunner.ts
src/tsconfig.vscode.json
src/vs/workbench/browser/dnd.ts

Add more to strict nulls

---

extensions/sql-migration/src/models/migrationWizardPage.ts
extensions/sql-migration/src/models/strings.ts
extensions/sql-migration/src/wizard/skuRecommendationPage.ts
extensions/sql-migration/src/wizard/subscriptionSelectionPage.ts
extensions/sql-migration/src/wizard/wizardController.ts
src/sql/azdata.d.ts

Azure Subscription Page and another azdata change

---

extensions/sql-database-projects/images/databaseProjectToolbar.svg
extensions/sql-database-projects/package.json

Update the import project toolbar icon to match the other toolbar icons

Update import project toolbar icon to be blue

---

extensions/admin-tool-ext-win/package.json
extensions/admin-tool-ext-win/yarn.lock
extensions/agent/package.json
extensions/agent/yarn.lock
extensions/arc/package.json
extensions/arc/yarn.lock
extensions/azdata/package.json
extensions/azdata/yarn.lock
extensions/azurecore/package.json
extensions/azurecore/yarn.lock
extensions/cms/package.json
extensions/cms/yarn.lock
extensions/dacpac/package.json
extensions/dacpac/yarn.lock
extensions/import/package.json
extensions/import/yarn.lock
extensions/integration-tests/package.json
extensions/integration-tests/yarn.lock
extensions/machine-learning/package.json
extensions/machine-learning/yarn.lock
extensions/mssql/package.json
extensions/mssql/yarn.lock
extensions/notebook/package.json
extensions/notebook/yarn.lock
extensions/resource-deployment/package.json
extensions/resource-deployment/yarn.lock
extensions/schema-compare/package.json
extensions/schema-compare/yarn.lock
extensions/sql-database-projects/package.json
extensions/sql-database-projects/yarn.lock

This PR fixes the coverage reports intermittently going up and down for no good reason

Update test cover dependency

---

src/sql/workbench/services/connection/browser/connectionDialogWidget.ts

Fix clicking on a profile in azure connection dialog

---

extensions/notebook/src/book/bookTreeView.ts
extensions/notebook/src/test/book/book.test.ts

Tests for missing methods in BooksTreeView.

bookTreeView tests

---

extensions/arc/src/common/utils.ts
extensions/arc/src/test/common/utils.test.ts
extensions/arc/src/ui/dashboards/miaa/miaaConnectionStringsPage.ts
extensions/arc/src/ui/dashboards/miaa/miaaDashboard.ts
extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
extensions/azdata/src/typings/azdata-ext.d.ts

Adds back in connection strings and host property value.

Add external miaa endpoint property

---

src/sql/workbench/contrib/dataExplorer/browser/media/connectionViewletPanel.css
src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/11873
Don't use absolute positioning so that the badge can be indented properly.

Fix connection status badge display

---

extensions/arc/src/models/controllerModel.ts
extensions/arc/src/test/models/controllerModel.test.ts

Adding tests for Arc ControllerModel.
Also fixed a few code issues.

Add arc controllerModel tests

---

src/sql/azdata.d.ts
src/sql/platform/connection/common/connectionManagement.ts
src/sql/platform/connection/common/connectionProfile.ts
src/sql/platform/connection/common/connectionProfileGroup.ts
src/sql/platform/connection/common/connectionStore.ts
src/sql/platform/connection/common/providerConnectionInfo.ts
src/sql/platform/connection/test/common/connectionProfile.test.ts
src/sql/platform/connection/test/common/providerConnectionInfo.test.ts
src/sql/workbench/api/browser/mainThreadObjectExplorer.ts
src/sql/workbench/contrib/azure/browser/azure.contribution.ts
src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
src/sql/workbench/services/connection/browser/connectionManagementService.ts
src/sql/workbench/services/connection/common/connectionDialogService.ts
src/sql/workbench/services/connection/common/serverInfoContextKey.ts
src/sql/workbench/services/objectExplorer/browser/connectionTreeAction.ts
src/sql/workbench/services/objectExplorer/browser/mssqlNodeContext.ts
src/sql/workbench/services/objectExplorer/browser/objectExplorerActions.ts
src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
src/sql/workbench/services/objectExplorer/browser/serverTreeActionProvider.ts
src/sql/workbench/services/objectExplorer/browser/treeSelectionHandler.ts
src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts
src/sql/workbench/services/objectExplorer/common/treeNode.ts
src/sql/workbench/services/objectExplorer/common/treeNodeContextKey.ts
src/tsconfig.vscode.json

https://github.com/microsoft/azuredatastudio/issues/9169

strict null checks azure

---

extensions/notebook/src/jupyter/jupyterSessionManager.ts
extensions/notebook/src/test/model/sessionManager.test.ts

Add tests for Jupyter Session

---

extensions/import/src/controllers/controllerBase.ts
extensions/import/src/controllers/mainController.ts
extensions/import/src/test/controllers/mainController.test.ts

This PR partially fi x es https://github.com/microsoft/azuredatastudio/issues/11896

Potentially fixes the test percentage

---

extensions/integration-tests/src/test/objectExplorer.test.ts

Fix test failure

---

extensions/arc/src/localizedConstants.ts
extensions/arc/src/models/miaaModel.ts
extensions/arc/src/ui/dashboards/miaa/miaaConnectionStringsPage.ts
extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/11958

Show message when external endpoint isn't configured

---

extensions/arc/notebooks/arcDeployment/deploy.arc.control.plane.ipynb

Fixes https://github.com/microsoft/azuredatastudio/issues/11985

Use namespace instead of listing all pods

---

extensions/arc/src/ui/dialogs/connectControllerDialog.ts
extensions/azdata/package.nls.json

Missed this during the recent refactoring in the code - need to pass in the password for the initial connection. 
Also updating extension description based on PM feedback

Fix arc controller connect

---

extensions/kusto/package.json
extensions/kusto/yarn.lock

Updates service-downloader version in Kusto extension

Update service-downloader version in Kusto extension

---

extensions/kusto/package.json

Fixes the error while generating VSIX file for Kusto

Fix VSIX file generation for Kusto

---

extensions/azdata/src/azdata.ts

This is a quick change to remove extra quotes. It fixes: #11992
This PR fixes part 1 of #11992

quick change to remove extra quotes.

---

extensions/notebook/package.json
extensions/notebook/src/common/constants.ts
extensions/notebook/src/protocol/notebookUriHandler.ts
extensions/notebook/src/test/protocol/notebookUriHandler.test.ts
extensions/notebook/yarn.lock

Add tests to NotebookUriHandler.

Add tests to NotebookUriHandler

---

extensions/azdata/src/azdata.ts

Also added version string to result from api call to be consistent with other API methods

azdata debug logging on all commands and always accept eula

---

extensions/azdata/README.md
extensions/azdata/package.nls.json
extensions/azdata/src/azdata.ts

- Update docs
- Fix error message parsing (not all errors are from azdata itself)
- Fix path for azdata commands

azdata extension fix/updates

---

extensions/arc/package.json
extensions/arc/src/localizedConstants.ts
extensions/arc/src/ui/dashboards/controller/controllerDashboard.ts
extensions/arc/src/ui/dashboards/miaa/miaaDashboard.ts
extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
extensions/arc/src/ui/dashboards/postgres/postgresDashboard.ts
extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts
extensions/arc/src/ui/tree/azureArcTreeDataProvider.ts
extensions/arc/src/ui/tree/controllerTreeNode.ts
extensions/azdata/package.json

- Fixes bug where clicking on dashboard link on Controller dashboard would fail unless the controller tree node had been expanded already
- Fixes https://github.com/microsoft/azuredatastudio/issues/11532
- Fixes https://github.com/microsoft/azuredatastudio/issues/12016

Arc dashboard fixes

---

src/sql/workbench/api/browser/mainThreadModelViewDialog.ts
src/sql/workbench/services/dialog/browser/customDialogService.ts
src/sql/workbench/services/dialog/browser/wizardModal.ts

This PR makes the setCurrentPage button use the same logic as the next button on wizards
I'll update that checkbox once i test this

fix setCurrentPage

---

src/sql/workbench/services/connection/browser/connectionManagementService.ts
src/sql/workbench/services/connection/common/serverInfoContextKey.ts
src/sql/workbench/services/objectExplorer/browser/serverTreeActionProvider.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/12017
Broken by https://github.com/microsoft/azuredatastudio/pull/11928/files?file-filters%5B%5D=.ts#diff-106cd39f7916f803919ecb6b2c4c5322L36
Also fixing return type I noticed was incorrect while investigating this issue.

Fix context menu for disconnected server nodes

---

extensions/machine-learning/src/packageManagement/packageManageProviderBase.ts
extensions/machine-learning/src/typings/notebookServices.d.ts
extensions/notebook/src/dialog/managePackages/installedPackagesTab.ts
extensions/notebook/src/dialog/managePackages/managePackagesDialogModel.ts
extensions/notebook/src/jupyter/localCondaPackageManageProvider.ts
extensions/notebook/src/jupyter/localPipPackageManageProvider.ts
extensions/notebook/src/test/managePackages/managePackagesDialogModel.test.ts
extensions/notebook/src/types.d.ts

ML- Package Management - Setting selected db name in drop down to current connection db name 

---

extensions/sql-migration/src/api/azure.ts
extensions/sql-migration/src/wizard/wizardController.ts

Amir/enable sql vms for sql migration/assessments

---

src/tsconfig.vscode.json

Update strict compile numbers

---

extensions/azdata/src/azdata.ts
extensions/azdata/src/constants.ts
extensions/azdata/src/extension.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/12031

Add dont show prompt to azdata toasts

---

src/sql/workbench/contrib/tasks/browser/tasks.contribution.ts
src/sql/workbench/contrib/tasks/browser/tasksDataSource.ts
src/sql/workbench/contrib/tasks/browser/tasksRenderer.ts
src/sql/workbench/contrib/tasks/browser/tasksView.ts
src/sql/workbench/contrib/tasks/common/tasksAction.ts
src/tsconfig.vscode.json

Add contrib/tasks to strict compile

---

src/sql/workbench/contrib/query/browser/flavorStatus.ts

Fix for language provider text to include non sql languages too

Fix for language provider text -non sql family too

---

extensions/arc/package.json

Missed doing this in my latest change

vBump arc extension

---

extensionsGallery-insider.json
extensionsGallery.json

Submitting v1.0.0 of the eltsnap-simpleDataFlow extension to the gallery

eltsnap extension added

---

extensions/sql-database-projects/src/controllers/projectController.ts

Auto-increments default name when user adds a view, table, script, folder, or any other object to their sql project, based on the existing files that are present.

Auto incrementing default name when adding object to database project

---

extensions/kusto/config.json
extensions/kusto/src/kustoServer.ts
extensions/kusto/src/main.ts
extensions/mssql/config.json

Updates the KustoServer.ts to download from the latest binaries for SQL Tools Service containing the Kusto bits

Updating config to point to latest service layer

---

extensions/azurecore/src/azureResource/providers/kusto/kustoTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcTreeDataProvider.ts

Add check for all azure resources for the azure tree when in the connection dialog.

Fix children expand in connection dialog azure tree

---

src/sql/workbench/browser/actions.ts
src/sql/workbench/browser/editor/profiler/dashboardInput.ts
src/sql/workbench/browser/taskUtilities.ts
src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerWidget.component.ts
src/sql/workbench/contrib/dashboard/browser/widgets/explorer/objectMetadataWrapper.ts
src/sql/workbench/contrib/dashboard/test/electron-browser/explorerWidget.component.test.ts
src/sql/workbench/contrib/restore/browser/restore.contribution.ts
src/sql/workbench/contrib/restore/browser/restoreActions.ts
src/sql/workbench/contrib/views/browser/nodeContext.ts
src/sql/workbench/contrib/views/browser/treeView.ts
src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts
src/sql/workbench/services/tasks/common/tasks.ts
src/tsconfig.vscode.json

Strict nulls for contrib/restore and contrib/views

---

src/sql/azdata.d.ts
src/sql/workbench/browser/modal/dialogHelper.ts
src/sql/workbench/browser/modal/optionsDialog.ts
src/sql/workbench/browser/modal/optionsDialogHelper.ts
src/sql/workbench/services/restore/browser/restoreDialog.ts
src/sql/workbench/services/restore/browser/restoreServiceImpl.ts
src/sql/workbench/services/restore/browser/restoreViewModel.ts
src/sql/workbench/services/restore/test/browser/restoreViewModel.test.ts
src/tsconfig.vscode.json

Add strict compile for restore

---

extensions/azurecore/package.json
extensions/azurecore/src/azureResource/providers/database/databaseTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/kusto/kustoTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcTreeDataProvider.ts
src/sql/workbench/contrib/connection/browser/connection.contribution.ts

Add different flag for azure dialog

---

src/sql/base/test/browser/ui/scrollableView/scrollableView.test.ts

attempt to adjust timing

---

extensionsGallery-insider.json

Add the entry for the Kusto extension to the insiders marketplace. Will add to main market place later...

Update the Kusto extension to the insiders market place

---

extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts

Remove PG dashboard link

---

extensions/arc/package.json

vBump Arc extension to 0.3.5

---

src/sql/azdata.d.ts
src/sql/workbench/contrib/backup/browser/backup.component.ts
src/sql/workbench/contrib/backup/browser/backup.contribution.ts
src/sql/workbench/contrib/backup/browser/backupActions.ts
src/sql/workbench/contrib/backup/browser/backupDialog.ts
src/sql/workbench/contrib/backup/browser/backupUiService.ts
src/sql/workbench/contrib/backup/common/backupUiService.ts
src/tsconfig.vscode.json

Strict compile contrib/backup

---

extensions/azurecore/src/azureResource/interfaces.ts
extensions/azurecore/src/azureResource/providers/database/databaseService.ts
extensions/azurecore/src/azureResource/providers/resourceTreeDataProviderBase.ts
extensions/azurecore/src/azureResource/utils.ts
extensions/azurecore/src/test/azureResource/providers/database/databaseTreeDataProvider.test.ts
extensions/azurecore/src/test/azureResource/providers/databaseServer/databaseServerTreeDataProvider.test.ts

For perf when querying multiple subs

Update azure graph queries to allow multiple subs

---

extensionsGallery-insider.json
extensionsGallery.json

This PR adds my extension (https://tsql.tech/the-sql-diagnostic-jupyter-book/) to the Marketplace
https://github.com/EmanueleMeazzo/SQL-Server-Diagnostic-Book

Added SQL Server Diagnostic Book to marketplace

---

extensionsGallery-insider.json
extensionsGallery.json

fix the issues in this PR: https://github.com/microsoft/azuredatastudio/pull/12101

fix sql-server-diagnostic-book extension

---

src/sql/workbench/contrib/notebook/browser/cellToolbarActions.ts

add role on toggelMore action element

---

extensions/notebook/src/extension.ts

Adding an additional comment to prevent people from carelessly changing the bookTreeView command - @Charles-Gagnon, let me know if the comment should be adjusted.

Provide bookTreeView comment to ensure compatibility 

---

extensions/asde-deployment/README.md
extensions/asde-deployment/notebooks/edge/deploy-sql-edge-azure.ipynb
extensions/asde-deployment/notebooks/edge/deploy-sql-edge-multi-device.ipynb
extensions/asde-deployment/notebooks/edge/deploy-sql-edge-single-device.ipynb
extensions/asde-deployment/package.json

add note for storage account clean up post deployment
add readme file
remove a property i added earlier which i forgot to remove in the first place

ASDE updates

---

src/sql/base/browser/ui/scrollableView/scrollableView.ts

Rerender grid view on layout

---

src/sql/workbench/browser/editor/resourceViewer/resourceViewerInput.ts
src/sql/workbench/contrib/resourceViewer/browser/resourceViewerActions.ts
src/sql/workbench/contrib/resourceViewer/browser/resourceViewerEditor.ts

Edit columns isn't implemented yet

Add refresh/edit columns resource viewer actions

---

src/tsconfig.vscode.json

Add debug typings and comment out tests separtely for a few directories

---

extensions/import/package.json

Changing import extension version to 1.0 for GA

---

src/sql/workbench/browser/editData/editDataInput.ts
src/sql/workbench/browser/editData/editDataResultsInput.ts
src/sql/workbench/common/editor/query/queryEditorInput.ts
src/sql/workbench/common/editor/query/untitledQueryEditorInput.ts
src/sql/workbench/contrib/editorReplacement/common/editorReplacerContribution.ts
src/sql/workbench/services/queryEditor/browser/editorDescriptorService.ts
src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
src/tsconfig.vscode.json

Strict null check contrib/editorReplace and services/queryEditor

---

src/sql/workbench/contrib/queryPlan/browser/queryPlan.ts

Fix query plan css

---

src/sql/workbench/contrib/charts/browser/actions.ts
src/sql/workbench/contrib/charts/browser/chartView.ts
src/sql/workbench/contrib/charts/browser/countInsight.ts
src/sql/workbench/contrib/charts/browser/graphInsight.ts
src/sql/workbench/contrib/charts/browser/insight.ts
src/sql/workbench/contrib/charts/browser/tableInsight.ts
src/tsconfig.vscode.json

Strict null contrib/chart

---

src/sql/setup.js

We finally have stacktraces back!

Fix zonejs eating all errors

---

src/sql/platform/capabilities/test/common/testCapabilitiesService.ts
src/sql/workbench/contrib/notebook/browser/notebookActions.ts
src/sql/workbench/contrib/notebook/test/electron-browser/notebookModel.test.ts
src/sql/workbench/services/connection/test/browser/connectionManagementService.test.ts
src/sql/workbench/services/notebook/browser/models/notebookModel.ts

This PR enables the New Notebook from Kusto Cluster functionality and properly changes the kernel and the attach to connection based on the provider they are connected to.

Kusto Kernel New Notebook Changes

---

extensions/mssql/config.json
src/sql/workbench/contrib/assessment/browser/asmtActions.ts
src/sql/workbench/contrib/assessment/browser/asmtResultsView.component.ts
src/sql/workbench/contrib/assessment/browser/media/asmt.css
src/sql/workbench/contrib/assessment/test/browser/asmtActions.test.ts

- prevent simultaneous actions runs 
- HTML report label rename
- showing ... for long target name
- title for tags, target, check id columns to display long values

Sql Assessment fixes

---

extensions/mssql/config.json

use latest SQL Tools Service

---

extensions/sql-database-projects/src/controllers/projectController.ts
extensions/sql-database-projects/src/models/project.ts
extensions/sql-database-projects/src/test/projectController.test.ts

This PR fixes #12141. Also fixes delete/exclude for publish.xml files because those are "none" entries in the sqlproj

Fix delete and exclude for pre and post deploy scripts

---

package.json

Increase memory size for valid layers check

---

extensions/arc/notebooks/arcDeployment/deploy.arc.control.plane.ipynb
extensions/arc/package.json
extensions/arc/package.nls.json

Add Storage Class to Data Controller Create

---

extensions/kusto/package.json
extensions/kusto/package.nls.json
extensions/kusto/src/constants.ts
extensions/kusto/syntaxes/kusto.tmLanguage

- Added color theme for Kusto
- Changes some UI labels for Kusto extension

Added color theme for Kusto

---

build/gulpfile.vscode.js

This PR fixes https://github.com/microsoft/azuredatastudio/issues/12137. Also removed splash screen.

Remove unused splash screen and fix issue reporter path

---

remote/web/package.json
remote/web/yarn.lock

Fix missing package update

---

src/sql/workbench/api/browser/mainThreadQueryEditor.ts
src/sql/workbench/api/common/extHostQueryEditor.ts
src/sql/workbench/api/common/sqlExtHost.api.impl.ts
src/sql/workbench/api/common/sqlExtHost.protocol.ts

Make SandDance work generically for Kusto

Make SandDance work generically for Kusto

---

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts

Notebooks: Ensure Cell Model Updated when Non-WYSIWYG Opened before Inactive Action

---

.vscode/launch.json
extensions/machine-learning/src/test/views/utils.ts
extensions/notebook/src/test/common.ts
extensions/notebook/src/test/managePackages/managePackagesDialog.test.ts
extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
src/sql/azdata.d.ts
src/sql/azdata.proposed.d.ts
src/sql/workbench/api/common/extHostModelView.ts
src/sql/workbench/browser/modelComponents/componentBase.ts
src/sql/workbench/browser/modelComponents/declarativeTable.component.html
src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
src/sql/workbench/browser/modelComponents/media/declarativeTable.css

Change tables to make them work for our scenario

---

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
src/sql/workbench/contrib/notebook/browser/notebook.component.ts

This PR fixes #12238 
Update get settings configuration on init

fix bug for register double click enabled on new notebook context

---

extensions/notebook/resources/notebooks/JupyterBooksCreate.ipynb

Add warning message for windows users using Python3.8 and create directory using python.

Address comments jupyter create book notebook

---

src/sql/workbench/services/notebook/browser/models/notebookModel.ts

This PR fixes an issue when opening a new notebook multiple times from the same Kusto connection.

Fix Notebook Kusto Kernel Consistency 

---

extensions/sql-migration/src/dialog/assessmentResults/assessmentResultsDialog.ts
extensions/sql-migration/src/dialog/assessmentResults/model/assessmentDialogComponent.ts
extensions/sql-migration/src/dialog/assessmentResults/sqlAssessmentResult.ts
extensions/sql-migration/src/dialog/assessmentResults/sqlAssessmentResultsList.ts
extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
extensions/sql-migration/src/models/product.ts
extensions/sql-migration/src/models/stateMachine.ts
extensions/sql-migration/src/wizard/skuRecommendationPage.ts
src/sql/azdata.d.ts
src/sql/workbench/browser/modelComponents/declarativeTable.component.html

dialog changes

---

product.json

bump vscode version

---

extensions/azurecore/src/azureResource/azure-resource.d.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/12260
Was using wrong resource type name

Fix MIAA instances not being listed

---

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts

Addresses #12285 for markdown heading style consistency.

Ensure Markdown Heading Consistency with WYSIWYG

---

src/sql/workbench/contrib/resourceViewer/browser/resourceViewer.contribution.ts

Disabling until it's at least feature complete enough for insiders.

Disable resource viewer

---

extensionsGallery-insider.json

Will merge in once the insiders build with the changes is released

Update data virt to support azdata api changes

---

extensions/data-workspace/package.json
extensions/data-workspace/package.nls.json
extensions/data-workspace/src/common/interfaces.ts
extensions/data-workspace/src/common/workspaceTreeDataProvider.ts
extensions/data-workspace/src/dataworkspace.d.ts
extensions/data-workspace/src/main.ts
extensions/data-workspace/src/services/workspaceService.ts
extensions/data-workspace/src/test/projectProviderRegistry.test.ts
extensions/data-workspace/src/test/workspaceService.test.ts
extensions/data-workspace/src/test/workspaceTreeDataProvider.test.ts
extensions/sql-database-projects/package.json
extensions/sql-database-projects/src/projectProvider/projectProvider.ts

remove project feature

---

extensions/sql-database-projects/package.json
extensions/sql-database-projects/src/controllers/mainController.ts

didn't realize I had put a hard dependency on data-workspace extension, remove the dependency in this PR and I will figure out a more reliable way.
https://github.com/microsoft/azuredatastudio/issues/12323

remove data-workspace dependency

---

extensionsGallery.json

Adding Kusto Extension entry on gallery

Add kusto extension

---

src/sql/workbench/contrib/resourceViewer/browser/resourceViewer.contribution.ts

Port removal of Resource Viewlet until it's ready
Fixes https://github.com/microsoft/azuredatastudio/issues/12259

Disable resource viewer (#12291)

---

extensions/sql-database-projects/package.json

This PR fixes #11979 (approved for Sept)
PR for master https://github.com/microsoft/azuredatastudio/pull/12265

Port request for adding icon for new/open project in view

---

extensions/sql-database-projects/package.json
extensions/sql-database-projects/src/controllers/mainController.ts

the issue has been approved for Sep release
This PR fixes #12323

remove data-workspace dependency (#12321)

---

extensions/arc/README.md
extensions/arc/package.json
extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts
extensions/azdata/README.md
extensions/azdata/package.json

- vBump extensions for public preview release
- Private preview -> Public preview

Arc public preview updates

---

extensions/sql-database-projects/src/controllers/projectController.ts

Stop watching for sqlproj updates after the file is closed

---

src/sql/workbench/browser/modelComponents/declarativeTable.component.html

Fixes https://github.com/microsoft/azuredatastudio/issues/12304

Fix component items in declarative table not showing

---

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts

Add heasdingStyle atx option (#12286)

---

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts

Add newline after caption (#12276)

---

src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
src/sql/workbench/contrib/notebook/browser/notebook.component.ts
src/sql/workbench/services/notebook/browser/models/notebookModel.ts

Watch for on load event (#12309)

---

extensions/sql-database-projects/package.json

the extension version should been bumped after the previous release
#12337

vbump sql-db-proj extension

---

extensions/sql-database-projects/package.json

update sqlproj dependency version

---

extensions/sql-database-projects/package.json

This PR fixes #12337. the port request has been approved.

vbump sql-db-proj extension (#12336)

---

extensions/notebook/src/book/bookTreeView.ts

Fix highlight issue

---

src/sql/workbench/services/notebook/browser/models/clientSession.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/12263
PR for main branch https://github.com/microsoft/azuredatastudio/pull/12300

Fix notebook cancel query bug (#12300)

---

src/sql/workbench/services/notebook/browser/models/notebookModel.ts

PR for Main branch: #12256
This PR fixes: #12255

Fix Notebook Kusto Kernel Consistency  (#12256)

---

extensions/notebook/src/book/bookTreeView.ts

* Fix highlight issue
* Address PR comments
This PR fixes #12268

Fix highlight issue (#12278)

---

extensions/arc/package.json

Fixes https://github.com/microsoft/azuredatastudio/issues/12348
Also 
- Updating package version ahead of time in preparation for release
- Increasing required azdata version to public preview version

Update arc regions for public preview

---

extensions/arc/package.json
extensions/arc/src/localizedConstants.ts
extensions/arc/src/ui/tree/controllerTreeNode.ts
extensions/arc/src/ui/tree/noInstancesTreeNode.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/12364

Add "No instances available" node for empty arc controllers

---

extensions/arc/notebooks/arcDeployment/deploy.sql.existing.arc.ipynb
extensions/arc/package.json
extensions/arc/package.nls.json

Remove port as an option for MIAA deploy, per ask from PM.
Fixes #12369.

Remove MIAA Port Deploy Option

---

extensions/resource-deployment/src/helpers/optionSources.ts
extensions/resource-deployment/src/interfaces.ts
extensions/resource-deployment/src/localizedConstants.ts
extensions/resource-deployment/src/ui/modelViewUtils.ts

Something with the webpacking was messing with the code here - I didn't dig into exactly what the issue was (something with the construction - that's definitely not a normal way of doing things) but this all was unnecessarily complex anyways so I just refactored it a bit and it works fine now in my test builds.
Fixes https://github.com/microsoft/azuredatastudio/issues/12344

Fix Arc deployment options sources

---

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts

textCell event listener - filtered keydown event for Mac and Win specific key combos.
This PR will address #12360

12360 Notebook UI - Mac/Win fix for Select all.

---

src/sql/azdata.d.ts
src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts
src/sql/workbench/services/notebook/browser/models/cell.ts
src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/12275
PR in main: https://github.com/microsoft/azuredatastudio/pull/12363

Fix notebook table rendering with multiple code cells (#12363)

---

extensions/notebook/resources/notebooks/JupyterBooksCreate.ipynb

Update windows command to copy subfolders.
And move getJupyterVersion function to another cell.

Update Windows command and minor update to installation cell

---

extensions/integration-tests/src/test/dacpac.test.ts

Once merged will pull to release branch as well
To Adress : https://github.com/microsoft/azuredatastudio/issues/12406

marking intermittent test failure as unstable

---

src/sql/workbench/contrib/notebook/browser/models/notebookTextFileModel.ts
src/sql/workbench/contrib/notebook/test/electron-browser/notebookEditorModel.test.ts

Notebooks: Fast update WYSIWYG support for source update (#12289)

---

extensions/notebook/resources/notebooks/JupyterBooksCreate.ipynb

* Fix windows command and minor update to installation cell
* Add expand_section field on the first section of the book

Update Windows command and minor update to installation cell (#12361)

---

extensions/import/src/wizard/pages/summaryPage.ts

PR for main branch https://github.com/microsoft/azuredatastudio/pull/12314
Fix for issue #11949

Release branch PR for import modify column settings fix. 

---

src/sql/workbench/services/connection/browser/media/connectionDialog.css

This PR fixes https://github.com/microsoft/azuredatastudio/issues/11891
Before -
After-

Fix connection dialog indentation

---

extensions/integration-tests/src/test/dacpac.test.ts

This PR fixes  #12406
PR in main https://github.com/microsoft/azuredatastudio/pull/12402

marking intermittent test failure as unstable (#12402)

---

src/sql/workbench/contrib/query/browser/gridPanel.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/12273 from [this commit](https://github.com/microsoft/azuredatastudio/commit/8aee87e211f30968fb1dc20ca3ba9617f3dcd1bb).
More info about the PR against main here - https://github.com/microsoft/azuredatastudio/pull/12334

fix maximize bug

---

extensions/resource-deployment/src/ui/modelViewUtils.ts

I don't think this ever worked properly...or if it does I'm not sure how it was supposed to work since the validation only ever cleared the error messages - never prevented leaving the page.
Now text validation will properly prevent the user from continuing on until the validation passes

Fix resource deployment text field validation

---

extensions/sql-database-projects/src/common/constants.ts
extensions/sql-database-projects/src/models/project.ts

This PR fixes  #12189 and a little refactoring to remove a few for loops

Remove ItemGroup from sqlproj if node being removed is the last one

---

src/sql/workbench/browser/modelComponents/card.component.html
src/sql/workbench/browser/modelComponents/card.component.ts
src/sql/workbench/browser/modelComponents/media/legacycard.css

port the fix to release branch, still waiting for ship room approval.
This PR fixes #12420

fix the legacy card style issue (#12428)

---

extensions/resource-deployment/src/ui/modelViewUtils.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/12456
This is fixing it so that text input validation for resource deployment dialogs use the built-in text field validation instead of doing its own custom checks, which greatly increases usability of the features since users get immediate feedback when a field doesn't meet the validation requirements.

[Port] Fix resource deployment text field validation (#12421)

---

extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts

Simplifies the check for the ok button in resource-deployment

small optimization for select

---

extensions/sql-database-projects/README.md

README didn't get updated when Import New Database Project was changed to Create Project From Database

Update sql database projects readme

---

extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts

Fix default values and example usage not updating when project dropdown changes

---

src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/12476
PR in main: https://github.com/microsoft/azuredatastudio/pull/12478

Notebook: Fix save result grid actions

---

extensions/resource-deployment/package.json
extensions/resource-deployment/src/services/tools/azdataToolOld.ts
extensions/resource-deployment/src/services/toolsService.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/12462
Bring back old azdata experience for BDC contribution - will follow up post-September with making this work with azdata extension.

[Port] Revert BDC deployment back to using old azdata check (#12470)

---

src/sql/workbench/contrib/notebook/browser/notebookActions.ts

PR from main #12494
This PR fixes: #12488

Fix PySpark Kernel Connection Change

---

extensions/resource-deployment/src/localizedConstants.ts

Feedback from @twright-msft. No "ARC" in any strings.

Arc string change: Arc good ARC bad

---

extensions/notebook/src/book/bookTreeItem.ts
src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookExplorerViewlet.ts
src/vs/workbench/common/views.ts
src/vs/workbench/contrib/views/browser/treeView.ts

* fix search
* Add sql carbon tags to vs files
Co-authored-by: chlafreniere <hichise@gmail.com>
Co-authored-by: abist <adbist@microsoft.com>
This PR fixes #12370

Fix In-Viewlet Notebooks Search  (#12455)

---

extensions/resource-deployment/src/localizedConstants.ts

[Port] String fix : ARC -> Arc (#12499)

---

extensions/sql-database-projects/src/common/constants.ts
extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts

This PR fixes Reference issue with Database Project
Part of fix for #12487 and #12522

Fix the reference error due to extra $ in default variable

---

extensions/data-workspace/package.json
extensions/data-workspace/package.nls.json
extensions/data-workspace/src/common/constants.ts
extensions/data-workspace/src/common/interfaces.ts
extensions/data-workspace/src/common/workspaceTreeDataProvider.ts
extensions/data-workspace/src/dataworkspace.d.ts
extensions/data-workspace/src/main.ts
extensions/data-workspace/src/test/workspaceTreeDataProvider.test.ts
extensions/sql-database-projects/src/controllers/projectController.ts

1. add a view when there is no workspace
when no workspace is selected, add project command won't do anything because we still have the workspace check, I will handle the create workspace scenario and remove the check in a separate PR. 
2. improve the project type filter
union all types and also allow specific project type filtering.
3. fix the project node level context menu issue.

data workspace review feedback implementation

---

extensions/azdata/src/common/logger.ts

Add timestamps to azdata output channel output

---

extensions/arc/src/constants.ts
extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts
extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/12395

Add troubleshoot button to arc controller/MIAA dashboard

---

extensions/arc/package.json

fix readonly summary page field widths

---

extensions/arc/src/ui/dashboards/postgres/postgresDashboard.ts
extensions/arc/src/ui/dashboards/postgres/postgresSupportRequestPage.ts

This PR fixes #12552 to enable the support request link for Postgres

Arc - Enable Postgres support request link

---

src/sql/workbench/contrib/notebook/test/browser/dataResourceDataProvider.test.ts

Added test for converting data returned from query runner to mime type and html.

Add test for notebook result grid streaming

---

extensions/arc/package.json
extensions/asde-deployment/package.json
extensions/azdata/package.json
extensions/import/package.json
extensions/machine-learning/package.json
extensions/schema-compare/package.json
extensions/sql-database-projects/package.json
package.json

Bump ADS and extension versions

bump ads and extensions

---

src/sql/base/browser/ui/table/plugins/textWithIconColumn.ts

escape the value for display (#12547)

---

extensions/arc/notebooks/arcDeployment/deploy.arc.data.controller.ipynb

-n is deprecated, use --namespace instead

Don't use deprecated param

---

extensions/sql-database-projects/package.json
extensions/sql-database-projects/src/common/constants.ts
extensions/sql-database-projects/src/controllers/mainController.ts
extensions/sql-database-projects/src/controllers/projectController.ts
extensions/sql-database-projects/src/test/mainController.test.ts

Removing old projects view in the file explorer view so that projects only show up in the new Projects view

Remove old projects view

---

src/sql/workbench/api/browser/mainThreadModelViewDialog.ts
src/sql/workbench/services/dialog/browser/dialog.module.ts
src/sql/workbench/services/dialog/browser/dialogContainer.component.ts
src/sql/workbench/services/dialog/browser/dialogPane.ts
src/sql/workbench/services/dialog/browser/wizardModal.ts
src/sql/workbench/services/dialog/browser/wizardNavigation.component.ts
src/sql/workbench/services/dialog/common/dialogTypes.ts
src/sql/workbench/services/dialog/test/electron-browser/dialogPane.test.ts

This is needed for fixing sql/workbench/contrib/queryHistory - splitting it into separate PRs for easier reviewing.

Strict compile for sql/workbench/services/dialog

---

src/sql/workbench/common/editor/query/queryResultsInput.ts
src/sql/workbench/contrib/query/browser/queryResultsView.ts

This is needed for fixing sql/workbench/contrib/queryHistory - splitting it into separate PRs for easier reviewing.

Strict compile for queryResultsView

---

src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts

clone the object to be modified (#12583)

---

src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts

add role for the history tab
This PR fixes #11547

add role for the history tab

---

src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts

add title and tab-index for X button

---

extensionsGallery-insider.json
extensionsGallery.json

Partial fix for #12594, updating extension gallery tags (stable and insiders)

removes preview flag

---

extensions/arc/src/ui/components/dashboard.ts
extensions/arc/src/ui/dashboards/controller/controllerDashboard.ts
extensions/arc/src/ui/dashboards/miaa/miaaDashboard.ts
extensions/arc/src/ui/dashboards/postgres/postgresDashboard.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboard.ts
extensions/schema-compare/src/schemaCompareMainWindow.ts
src/sql/azdata.d.ts
src/sql/azdata.proposed.d.ts
src/sql/platform/telemetry/common/telemetryKeys.ts
src/sql/workbench/api/browser/mainThreadModelViewDialog.ts
src/sql/workbench/api/common/extHostModelViewDialog.ts
src/sql/workbench/api/common/sqlExtHost.api.impl.ts
src/sql/workbench/api/common/sqlExtHost.protocol.ts
src/sql/workbench/test/electron-browser/api/mainThreadModelViewDialog.test.ts

Adds ModelViewEditorOpened event to track when a particular dashboard was opened. Not looking to track when it was closed at this point.

Add ModelViewEditorOpened event

---

src/sql/workbench/services/objectExplorer/browser/serverTreeDataSource.ts

Fixes [AB#3774](https://mssqltools.visualstudio.com/dea8be32-0532-4a8f-a2f4-89271d8b1cc5/_workitems/edit/3774)

TEST COMMIT PLEASE IGNORE

---

extensions/kusto/config.json

Updates it to release version 3.0.0-release.34

Update sqltoolservice binaries for kusto extension

---

src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts

https://github.com/microsoft/azuredatastudio/issues/12410

Change default Select query label to "Take 10" for Kusto tables (#12396)

---

extensionsGallery-insider.json
extensionsGallery.json

Added MI dashboard v 0.4.2 (hold-off - need to upload vsix)

---

extensionsGallery-insider.json
extensionsGallery.json

Changing the version of the tag for eltsnap simple-data-flow

eltsnap simple-data-flow update

---

extensionsGallery-insider.json
extensionsGallery.json

The flags property is required

Fix missing property

---

src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts

add aria-label for images

---

src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts

use h3 instead of div

---

src/sql/workbench/services/objectExplorer/browser/serverTreeDataSource.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/12615

Fix undefined error in server tree data source (#12616)

---

extensions/mssql/config.json

This PR fixes #12582
port the fix for delete row issue to release branch.

port the fix for delete row issue (#12636)

---

package.json

Bump version for hotfix

---

README.md

1. Updated the link to the download page to the correct one. 
2. Clarified in the Insiders that the instructions is the same as the standard build.

Clarifying the instructions to install

---

src/sql/azdata.d.ts
src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts
src/sql/workbench/services/notebook/browser/models/cell.ts
src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts

(cherry picked from commit cf9754f627720f1e29693d9be1100a44c37ce010)
Fixes https://github.com/microsoft/azuredatastudio/issues/12646

[Port] revert grid streaming changes (#12650)

---

extensions/kusto/config.json
extensions/kusto/package.json

Bump kusto extension version to fix notebooks issue in current Kusto release

Bump kusto extension version

---

extensionsGallery-insider.json
extensionsGallery.json

Update Kusto version in insiders and main

---

extensions/import/README.md

Partial fix for #12594, updates extension readme

updates import readme for ga

---

extensions/import/src/wizard/pages/summaryPage.ts

Fix for modify column structure bug in import wizard. 

---

CHANGELOG.md
README.md

Changelog and readme update after release publishing

Update readme links and changelog after release

---

extensions/import/src/wizard/pages/modifyColumnsPage.ts
extensions/import/src/wizard/pages/summaryPage.ts

Exposing errors of change column settings and stopping import if they occur
This PR fixes #12624, fixes #12648.

Fixing import getting stuck on step 4 

---

build/lib/extensions.ts
extensions/arc/package.json
extensions/azdata/package.json
product.json

Minor cleanup to alphabetize builtin extension list too.

Add arc and azdata to recommended ext and vBump

---

extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts
extensions/sql-database-projects/src/controllers/mainController.ts
extensions/sql-database-projects/src/controllers/projectController.ts

@kisantia this will fix the data-workspace view not refreshing issue, but I also caused a bunch of tests to break, once you are done with the code refactoring, please also adjust the test cases.

fix action not refreshing the tree issue

---

extensionsGallery-insider.json
extensionsGallery.json

Updating marketplace for:
Query Editor Boost - release is ready and waiting, just never published to marketplace
First Responder Kit - release isn't packaged yet, just getting into marketplace of stable ahead of code freeze

Sept2020 updates to extensions

---

extensions/azurecore/src/azureResource/services/subscriptionFilterService.ts
extensions/azurecore/src/azureResource/utils.ts
extensions/azurecore/src/azurecore.d.ts
extensions/azurecore/src/extension.ts
extensions/machine-learning/src/test/stubs.ts
extensions/resource-deployment/src/localizedConstants.ts
extensions/resource-deployment/src/ui/modelViewUtils.ts

This change exposes selectedSubscription api from azurecore extension and uses that api to populate the subscriptions dropdown in wizards.
This PR fixes first part of #12261

use selected subscriptions

---

extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts
extensions/azdata/src/typings/azdata-ext.d.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/12413
Also cleaned up the PG page a bit
MIAA :
PG :

Update arc dashboards to use logs/metrics links from status

---

extensions/machine-learning/src/common/constants.ts
extensions/machine-learning/src/views/widgets/dashboardWidget.ts
src/sql/azdata.proposed.d.ts
src/sql/base/browser/ui/button/button.ts
src/sql/base/browser/ui/infoButton/infoButton.css
src/sql/base/browser/ui/infoButton/infoButton.ts
src/sql/base/browser/ui/panel/media/panel.css
src/sql/workbench/api/common/sqlExtHost.api.impl.ts
src/sql/workbench/api/common/sqlExtHostTypes.ts
src/sql/workbench/browser/modelComponents/button.component.ts

This revises button.component.ts for the correct display of both regular and informational buttons.

ML extension - revised button component

---

extensions/sql-database-projects/src/models/project.ts

This PR fixes #12671. This error was introduced in #12398 when I added deletion verification because deleting files and folders had it.

Fix can't find SQLCMD variable error

---

extensions/mssql/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts
extensions/mssql/src/sqlClusterLookUp.ts

Also fixed some return types - no logic change since we were already handling undefineds.

Add additional logging to spark command failures

---

extensions/mssql/config.json

Bumping sqltoolsservice

---

extensions/sql-database-projects/src/common/constants.ts

Fix error message typo

---

src/sql/workbench/contrib/welcome/gettingStarted/browser/abstractEnablePreviewFeatures.ts

update preview feature notification

---

extensions/arc/src/ui/components/dashboard.ts
extensions/arc/src/ui/dashboards/controller/controllerDashboard.ts
extensions/arc/src/ui/dashboards/miaa/miaaDashboard.ts
extensions/arc/src/ui/dashboards/postgres/postgresDashboard.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboard.ts
extensions/schema-compare/src/schemaCompareMainWindow.ts
src/sql/azdata.d.ts
src/sql/azdata.proposed.d.ts
src/sql/platform/telemetry/common/telemetryKeys.ts
src/sql/workbench/api/browser/mainThreadModelViewDialog.ts
src/sql/workbench/api/common/extHostModelViewDialog.ts
src/sql/workbench/api/common/sqlExtHost.api.impl.ts
src/sql/workbench/api/common/sqlExtHost.protocol.ts
src/sql/workbench/test/electron-browser/api/mainThreadModelViewDialog.test.ts

Adds ModelViewEditorOpened event to track when a particular dashboard was opened. Not looking to track when it was closed at this point.
cherry-picked from bf9646ba98c5439086a275c009f0af4276746975

[Port] Add ModelViewEditorOpened event #12597

---

src/sql/base/browser/ui/checkbox/checkbox.ts

* Fix checkbox change event not firing
cherry-picked from https://github.com/microsoft/azuredatastudio/commit/8bf1859d3615866afc578dea3000bf2278d244c4

[Port] Fix checkbox change event not firing on enter press (#12703)

---

extensions/mssql/config.json

This PR fixes #https://github.com/microsoft/azuredatastudio/issues/12720

updating SqltoolsService Version to Pick DacFx changes

---

product.json

cherry-picked from 1cd94518a85f25b7a403162d015710772d991d68

[Port] vBump notebooks to get latest CU6 version of book (#12683)

---

extensions/machine-learning/src/common/constants.ts
extensions/machine-learning/src/views/widgets/dashboardWidget.ts
src/sql/azdata.proposed.d.ts
src/sql/base/browser/ui/button/button.ts
src/sql/base/browser/ui/infoButton/infoButton.css
src/sql/base/browser/ui/infoButton/infoButton.ts
src/sql/base/browser/ui/panel/media/panel.css
src/sql/workbench/api/common/sqlExtHost.api.impl.ts
src/sql/workbench/api/common/sqlExtHostTypes.ts
src/sql/workbench/browser/modelComponents/button.component.ts

PR in Main : (#12674)
Co-authored-by: Alan Ren <alanren@microsoft.com>
https://github.com/microsoft/azuredatastudio/issues/12744

Port ML changes

---

build/azure-pipelines/darwin/sql-product-build-darwin.yml
test/smoke/src/main.ts
test/smoke/src/sql/main.ts

..and temporarily turn off browser smoketests

Update smoke tests to fix merge breaks

---

package.json

Bump insider to 1.24 release

---

extensions/azdata/src/azdata.ts
extensions/azdata/src/extension.ts
extensions/azdata/src/typings/azdata-ext.d.ts
extensions/resource-deployment/src/interfaces.ts
extensions/resource-deployment/src/localizedConstants.ts
extensions/resource-deployment/src/services/tools/azdataTool.ts
extensions/resource-deployment/src/services/tools/toolBase.ts
extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts

This PR changes the behavior of how we acquire missing Eula. Now when azdata EULA is missing, we overload the 'select' button to be 'Acquire Eula & Select' button.
cherry-picked from f47c5dcc75506373fca35305572a0f4f8b4c63f9

[Port] Improved behavior for accepting EULA. (#12453)

---

extensionsGallery-insider.json
extensionsGallery.json

these are not tied to the new release, i will publish the changes after merge.

new version of asde and db project

---

extensions/mssql/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts
extensions/mssql/src/sqlClusterLookUp.ts

cherry-picked from 1df74e8c4a9f7907a84858455499dc1847d2c748

[Port] Add additional logging to spark command failures (#12706)

---

extensions/arc/package.json
extensions/asde-deployment/package.json
extensions/azdata/package.json
extensions/kusto/package.json
extensions/sql-database-projects/package.json

auto updated when using extensions viewlet with dev build

---

extensions/asde-deployment/package.json
extensions/sql-database-projects/package.json

post publish extension vbump

---

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts

* Add redo and out/indent
* Check for active cell before doing shortcut
* PR feedback
* Remove unnecessary parameter
This PR fixes #12600.
This PR fixes #12602.

Notebooks: WYSIWYG Add Redo, Fix Shortcuts (#12752)

---

extensions/kusto/config.json
extensions/kusto/package.json

Bump kusto extension version to 0.2.0 for October release

Bump kusto extension version to 0.2.0

---

extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts

Stop using deprecated declarative table data in publish dialog

---

extensions/machine-learning/src/views/models/prediction/columnsTable.ts

ML - Fixed a regression in predict map columns page

---

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts

default to relative links in images and links (#12802)

---

extensions/data-workspace/package.json
extensions/data-workspace/src/common/interfaces.ts
extensions/data-workspace/src/main.ts
extensions/data-workspace/src/services/workspaceService.ts

show the view only when project provider is detected

---

extensions/machine-learning/src/common/constants.ts
extensions/machine-learning/src/test/views/models/modelDetailsPage.test.ts
extensions/machine-learning/src/views/models/modelDetailsPage.ts
extensions/machine-learning/src/views/models/modelsDetailsTableComponent.ts

Fixed a bug with deleting models from list in import model wizard

---

extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts

Include database-scoped credentials when deploying with default options

---

extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts

Fixes #12839 (or rather corrects the fix for it)
This patch will be properly-addressed by #12847 after the October release.

Replace literal with constant

---

extensionsGallery-insider.json

The published gallery was already updated with most of these - merging it in now so the branch version is sync'd up with what's actually released.
Also updating arc and azdata as part of this.

Update insiders with latest versions of extensions

---

extensions/resource-deployment/src/ui/modelViewUtils.ts

disableControlButtons disables generateScriptButton

---

extensions/arc/package.json
extensions/azdata/package.json

Possibly not necessary but doing this now in case we want to release a minor update between now and release.

vBump arc and azdata ext

---

extensions/kusto/config.json

updates sqltoolsversion to 3.0.0-release.41

update sqltoolsversion to 3.0.0-release.41 for Kusto extension

---

src/sql/workbench/services/notebook/browser/models/notebookModel.ts

This PR fixes #12862
PR from Main: #12881
(Discussed in Shiproom Channel)
It fixes Kusto to SQL kernel change by removing the connection based on the appropriate kernel.

Fix connection when changing kernel from Kusto to SQL (#12881)

---

extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts

Updated Fix for Deployment defaulting to first item when filter filters out all items

---

extensionsGallery-insider.json

Update Kusto extension to 0.2.0 in Insiders marketplace
This version will be released same time as October release

Update Kusto extension to 0.2.0 in Insiders marketplace

---

build/azure-pipelines/sql-product-build.yml

Conditional Exclusion of Non-Windows Build

---

extensions/mssql/src/sqlClusterLookUp.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/12905 - the casing was different so the check wasn't being done properly.

Fix HDFS node for Integrated auth

---

.github/CODEOWNERS

PR used for testing: https://github.com/microsoft/azuredatastudio/pull/12912

introduce CODEOWNERS file

---

src/sql/base/browser/ui/selectBox/selectBox.ts
src/sql/workbench/contrib/notebook/browser/notebookActions.ts
test/automation/src/sql/configurePythonDialog.ts
test/automation/src/sql/notebook.ts
test/automation/src/workbench.ts
test/smoke/src/sql/areas/notebook/notebook.test.ts

This smoke test creates a new notebook, configures Python, and executes cell.

Add simple notebook smoke test

---

src/sql/base/browser/ui/panel/media/panel.css
src/sql/base/browser/ui/panel/panel.ts

High contrast and dark border top added for results panel in query editor.

---

extensionsGallery-insider.json
extensionsGallery.json

Oct release extension gallery update

---

.github/CODEOWNERS

add codeowners to release/extensions branch

---

src/sql/azdata.proposed.d.ts
src/sql/base/browser/ui/table/formatters.ts
src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
src/sql/workbench/browser/modelComponents/table.component.ts

This PR adds a header filter plugin into the table model view component. It also allows the plugin to display distinct values in the case of an array as column data.

handling array as a table data and headerFilter.plugin

---

extensions/azdata/src/azdata.ts
extensions/azdata/src/azdataReleaseInfo.ts
extensions/azdata/src/providers/arcControllerConfigProfilesOptionsSource.ts
extensions/azdata/src/test/azdata.test.ts
extensions/azdata/src/test/azdataReleaseInfo.test.ts
extensions/azdata/src/test/providers/arcControllerConfigProfilesOptionsSource.test.ts
extensions/azdata/src/test/services/azdataToolService.test.ts

Coverage up to 71%!
- Did some cleanup of unnecessary async's
- Fixed bug in options source - we weren't awaiting when checking EULA acceptance.

Add more azdata tests

---

src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts

before:
after:
https://github.com/microsoft/azuredatastudio/issues/12909

fix missing icon issue

---

extensions/resource-deployment/src/services/resourceTypeService.ts
extensions/resource-deployment/src/test/resourceTypeService.test.ts

Consolidates the when clause processing for both into one shared function.
This PR is for issue #12873

When Clause processing added to  getokbutton and getprovider

---

extensions/asde-deployment/notebooks/edge/deploy-sql-edge-azure.ipynb
extensions/asde-deployment/notebooks/edge/deploy-sql-edge-multi-device.ipynb
extensions/asde-deployment/notebooks/edge/deploy-sql-edge-single-device.ipynb
extensions/asde-deployment/package.json

tested all 3 scenarios, all works fine with new azure-iot extension

Azure CLI's azure-cli-iot-ext extension is deprecated, use azure-iot instead

---

extensionsGallery-insider.json
extensionsGallery.json

Releasing a newer preview of the SentryOne Plan Explorer extension (0.9.8) for Azure Data Studio.

Update SentryOne Plan Explorer gallery version

---

extensions/asde-deployment/package.json
extensions/asde-deployment/package.nls.json
extensions/resource-deployment/src/ui/modelViewUtils.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/12968

add vm password validation

---

src/sql/platform/resourceViewer/common/resourceViewerRegistry.ts
src/sql/workbench/contrib/resourceViewer/browser/media/resourceViewerView.css
src/sql/workbench/contrib/resourceViewer/browser/resourceViewerView.ts
src/sql/workbench/contrib/resourceViewer/common/resourceViewerViewExtensionPoint.ts

Icon was already defined in extension contribution point - just needed to hook it up and style it correctly. 
Also changed launch action to single click instead of double click to match earlier UX discussions.

Add icon for resource view items

---

test/automation/src/sql/notebook.ts
test/smoke/src/sql/areas/notebook/notebook.test.ts
test/smoke/test/index.js

Increased the wait time for changing kernels to five minutes.

Re-enable notebook smoke test and increase timeout

---

extensions/azdata/src/azdata.ts
extensions/azdata/src/test/api.test.ts
extensions/azdata/src/test/azdata.test.ts
extensions/azdata/src/test/testUtils.ts

Pretty much done with azdata.ts, started work on api.ts

More azdata tests

---

extensionsGallery-insider.json
extensionsGallery.json

new version of asde deployment extension

---

extensions/asde-deployment/package.json

0.3.0 will be released soon, vbump the extension.

vbump asde deployment extension

---

src/sql/base/browser/ui/button/button.ts
src/sql/base/browser/ui/infoButton/infoButton.ts
src/sql/base/browser/ui/listBox/listBox.ts
src/sql/base/browser/ui/panel/panel.ts
src/sql/base/browser/ui/selectBox/selectBox.ts
src/sql/base/browser/ui/table/highPerf/tableView.ts
src/sql/base/browser/ui/table/highPerf/tableWidget.ts
src/sql/base/browser/ui/table/table.ts
src/sql/base/browser/ui/taskbar/actionbar.ts
src/sql/workbench/browser/modal/modal.ts
src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts
src/sql/workbench/contrib/notebook/browser/cellViews/output.component.ts
src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
src/sql/workbench/contrib/notebook/browser/find/notebookFindWidget.ts
src/sql/workbench/contrib/profiler/browser/profilerEditor.ts
src/sql/workbench/contrib/profiler/browser/profilerFindWidget.ts
src/sql/workbench/contrib/query/browser/queryEditor.ts
src/sql/workbench/contrib/queryHistory/browser/queryHistoryRenderer.ts
src/sql/workbench/contrib/tasks/browser/tasksRenderer.ts
src/sql/workbench/contrib/views/browser/treeView.ts
src/sql/workbench/contrib/welcome/page/browser/gettingStartedTour.ts
src/sql/workbench/services/connection/browser/connectionBrowseTab.ts
src/sql/workbench/services/connection/browser/connectionWidget.ts
src/sql/workbench/services/fileBrowser/browser/fileBrowserTreeView.ts

These functions are deprecated so just cleaning them up now.

Remove calls to DOM.addClass and DOM.removeClass

---

extensions/resource-deployment/src/test/ui/validation/validations.test.ts
extensions/resource-deployment/src/ui/validation/validations.ts

This is remerge of the PR: 
https://github.com/microsoft/azuredatastudio/pull/12953

New Validation Module for Resource Deployment Extension

---

extensions/machine-learning/config.json

ML- Updating sqlmlutils to 1.0.3

---

extensions/machine-learning/src/common/constants.ts
extensions/machine-learning/src/controllers/mainController.ts
extensions/machine-learning/src/modelManagement/modelPythonClient.ts
extensions/machine-learning/src/prediction/interfaces.ts
extensions/machine-learning/src/prediction/predictService.ts
extensions/machine-learning/src/prediction/queries.ts
extensions/machine-learning/src/test/prediction/predictService.test.ts
extensions/machine-learning/src/test/views/models/predictWizard.test.ts
extensions/machine-learning/src/views/models/prediction/columnsTable.ts
extensions/machine-learning/src/views/models/prediction/inputColumnsComponent.ts

Fixed an issue with when model has parameter with invalid type which is not supported in SQL. We remove the parameter for now since the engine only breaks if it's included.
Fixed a bug when model input parameter type is varchar. Now getting the length from database column or default to 100
Fixed a bug in predict wizard when model was loaded even before table is selected

ML - Bug fixing

---

extensions/machine-learning/src/common/processService.ts
extensions/machine-learning/src/test/common/processService.test.ts

test "execFolderListCommand should reject if command times out" was marked 'unstable' but was failing all the times. Fixed the test and marked it 'stable'

ML - Fixed a failing test

---

src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts

Changed the welcome screen text for deployments

---

extensionsGallery-insider.json
extensionsGallery.json

Suggestion for adding one new brilliant dark color theme.

Add new Dark theme.

---

src/sql/workbench/services/connection/browser/connectionBrowseTab.ts

fixes 2 issues in the master tracking issue #12909

make sure saved connections are up to date

---

extensions/sql-database-projects/src/models/project.ts
extensions/sql-database-projects/src/test/projectController.test.ts

Added a few missing awaits that were causing the "Should update sqlcmd variable values if value changes" test to fail intermittently

Fix intermittent sql database project test failure

---

extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts

Calling wrong azdata arc postgres server edit commands for Cores and Memory request/limit
Discard button stays enabled if save fails
Worker needs to be checked if undefined

Cores and memory had needed request/limit commands switched, Workers needs to be checked for undefined 

---

extensions/azurecore/src/azureResource/azure-resource.d.ts
extensions/azurecore/src/azureResource/providers/database/databaseService.ts
extensions/azurecore/src/azureResource/providers/database/databaseTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerService.ts
extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/kusto/kustoService.ts
extensions/azurecore/src/azureResource/providers/kusto/kustoTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerService.ts
extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerService.ts
extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/resourceGroup/resourceGroupService.ts
extensions/azurecore/src/azureResource/providers/resourceTreeDataProviderBase.ts
extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceService.ts
extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcService.ts
extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcTreeDataProvider.ts
extensions/azurecore/src/azureResource/utils.ts
extensions/azurecore/src/test/azureResource/providers/database/databaseTreeDataProvider.test.ts
extensions/azurecore/src/test/azureResource/providers/databaseServer/databaseServerTreeDataProvider.test.ts
extensions/machine-learning/src/test/modelManagement/azureModelRegistryService.test.ts
extensions/machine-learning/src/test/views/models/ModelManagementController.test.ts
extensions/machine-learning/src/test/views/models/azureModelsComponent.test.ts
extensions/machine-learning/src/test/views/models/predictWizard.test.ts
extensions/machine-learning/src/test/views/models/registerModelWizard.test.ts
src/sql/platform/connection/common/connectionProfileGroup.ts
src/sql/workbench/services/connection/browser/connectionBrowseTab.ts
src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts

master tracking issue: #12909 
update the label according to the ux design, subscription name needs to be introduced.
also fix an issue I introduced yesterday unexpectedly in the connectionBrowseTab.ts

resource label update

---

src/sql/workbench/contrib/commandLine/electron-browser/commandLine.ts

Fixes: https://github.com/microsoft/azuredatastudio/issues/13108
I got pinged on this issue and I believe this fixes it - also getting hacktoberfest PRs with this :)

Fix #13108

---

extensions/arc/src/models/postgresModel.ts
extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts

This PR fixes #13134 
The compute and storage page previously was getting stuck loading while waiting for the model to have data. This fix makes it so that certain UI components are not initialized until after the data is present. It takes about 5-10s for the page to populate.

Nasc/Compute and Storage Loading Page Bug Fix

---

src/sql/base/browser/ui/table/plugins/loadingSpinner.plugin.ts
src/sql/base/browser/ui/table/plugins/media/loadingSpinner.plugin.css
src/sql/workbench/browser/editor/resourceViewer/resourceViewerInput.ts
src/sql/workbench/contrib/resourceViewer/browser/resourceViewerEditor.ts
src/sql/workbench/contrib/resourceViewer/browser/resourceViewerTable.ts

Add Loading Spinner plugin for SlickGrid table

---

extensions/dacpac/package.json
extensions/mssql/config.json
extensions/schema-compare/package.json

Hiding dacpac extension from search bar for SQLOD.

Hiding dacpac from search for SQLOD

---

extensions/mssql/package.json
src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts
src/sql/workbench/contrib/query/browser/queryEditor.ts

Removing separate toggle setting - always shown when preview features enabled now.

Enable script to notebook actions under preview flag

---

extensions/notebook/src/jupyter/jupyterServerInstallation.ts
extensions/notebook/src/test/python/jupyterInstallation.test.ts

This PR updates the PowerShell Kernel to the newest version.
Changelog: https://github.com/vors/jupyter-powershell/blob/master/CHANGELOG.md

Update powershell kernel version to 0.1.4

---

extensions/mssql/config.json

This pulls in the SqlToolsService changes that add streaming job statement validation

Updating SqlToolsService version

---

extensionsGallery.json

Updating stable with new versions of arc and azdata

Update Arc and Azdata - stable

---

extensions/kusto/config.json
extensions/kusto/package.json

Update sqltoolsservice in kusto extension for kusto aria connection fix

Update sqltoolsservice in kusto extension for kusto aria connection fix

---

extensions/import/src/common/constants.ts
extensions/import/src/wizard/pages/fileConfigPage.ts

Added file path check in File Config page for Import extension

---

src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
src/sql/workbench/contrib/jobManagement/browser/jobsView.component.ts
src/sql/workbench/contrib/jobManagement/browser/notebooksView.component.ts
src/sql/workbench/services/jobManagement/browser/jobManagementUtilities.ts
src/typings/slickgrid.d.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/13125
Broken by https://github.com/microsoft/azuredatastudio/commit/6ff1e3866bcad2a8a639fdaf6e6fe4aeab49b2b2#diff-1254ef078bfae811f12516f8c9a0087b512415f974f606a921c5febe64a76f53 
@cssuh - Can you run through the merge and make sure there weren't any other changes like this? The VS Code find was a bit fancier and could handle string searching too - we need to make sure that this same thing wasn't applied to other parts of the code too.

Fix Agent not working

---

extensionsGallery-insider.json

Extension Gallery update for ML extension (Insider)

---

extensionsGallery-insider.json

Update sql database projects extension in insiders

---

src/sql/workbench/contrib/resourceViewer/browser/resourceViewer.contribution.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/13237

Only show resource viewer on insiders and dev

---

src/sql/workbench/services/jobManagement/browser/jobManagementUtilities.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/13125
Charles has a fix in main here - https://github.com/microsoft/azuredatastudio/pull/13126, but it introduced some new issues. This is a more scoped and safer fix for release. I'll do the same in main.

Fix agent for release

---

extensionsGallery-insider.json

Sql Assessment version update at the insiders gallery

sql-assessment update 0.4.0 for insiders

---

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
src/sql/workbench/contrib/notebook/browser/cellViews/textCell.css

Remove hardcoded default cell content  and add css instead.
This PR fixes #12878

fix delete behavior on text cells.

---

extensions/machine-learning/src/views/models/modelManagementController.ts
extensions/machine-learning/src/views/models/tableSelectionComponent.ts

ML - Fixed a bug with validating empty table name

---

src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts
src/sql/workbench/contrib/notebook/test/browser/htmlMarkdownConverter.test.ts

WYSIWYG fix list nesting (#13251)

---

extensionsGallery.json

the vsix can be found here: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=82779&view=artifacts&type=publishedArtifacts

update agent extension

---

extensionsGallery.json

the vsix can be found here: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=82797&view=artifacts&type=publishedArtifacts

sql-assessment update

---

extensionsGallery.json

vsix can be found here: 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=82797&view=artifacts&type=publishedArtifacts

update sql-db-project extension

---

extensions/mssql/config.json

Fixes https://github.com/microsoft/azuredatastudio/issues/13206
@Benjin  @aguzev Can you please verify that your changes are in this version? You can download the bundles here to examine : https://github.com/microsoft/sqltoolsservice/releases/tag/v3.0.0-release.52

Update to latest SQL Tools Service (.52)

---

extensions/mssql/config.json

This port request will resolve https://github.com/microsoft/azuredatastudio/issues/13206 and other issues requiring SQL Tools Service bump.

Update to latest SQL Tools Service (.52) (#13264)

---

package.json

Bump distro for icon refresh

---

src/sql/workbench/browser/modelComponents/declarativeTable.component.html
src/sql/workbench/browser/modelComponents/declarativeTable.component.ts

Adding aria label to "check all" check box in declarative table. 

---

extensions/sql-database-projects/package.json

Bumping the version since 0.4.0 got pushed to RC extensions gallery. Still anticipating one more bug fix/addition, so only bumping the minor version

Bump sql-database-projects extension version

---

src/sql/workbench/contrib/notebook/browser/notebook.component.ts
src/sql/workbench/contrib/welcome/page/browser/gettingStartedTour.ts

* Fix navigation buttons
* Remove icon set in welcome page
This PR fixes #13265

Remove button property setter causing exception (#13284)

---

extensions/sql-database-projects/src/test/project.test.ts

This PR fixes #12809. These tests would have caught the problems fixed in #12795.

Add more tests for duplicate database references

---

extensionsGallery-insider.json

Build: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=82912&view=results
File: https://mssqltools.visualstudio.com/_apis/resources/Containers/2582488/drop?itemPath=drop%2Fextensions%2Fsql-database-projects-0.4.1.vsix

Updating sql database projects extension to 0.4.1 in insiders

---

extensionsGallery.json

Build: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=82912&view=results
File: https://mssqltools.visualstudio.com/_apis/resources/Containers/2582488/drop?itemPath=drop%2Fextensions%2Fsql-database-projects-0.4.1.vsix

Updating sql database projects extension to 0.4.1 in RC

---

extensions/kusto/config.json
extensions/kusto/package.json

Update kusto extension sqltoolsservice 3.0.0-release.52

---

src/sql/workbench/contrib/dataExplorer/browser/media/dataExplorer.contribution.css
src/sql/workbench/contrib/notebook/browser/media/notebook.contribution.css

This PR fixes https://github.com/microsoft/azuredatastudio/issues/13312

fix connection and notebook icons not highlighting

---

extensions/azurecore/src/account-provider/auths/azureAuth.ts
extensions/azurecore/src/test/account-provider/auths/azureAuth.test.ts

Reverts microsoft/azuredatastudio#11593
This reverts the change that introduced https://github.com/microsoft/azuredatastudio/issues/13303

Revert "Verify the token belongs to the proper user."

---

extensions/azurecore/src/account-provider/auths/azureAuth.ts
extensions/azurecore/src/test/account-provider/auths/azureAuth.test.ts

This reverts commit 45cbaca31f3db2d6f7b1e0a799750b1bb4eddc6b.
Port the fix for https://github.com/microsoft/azuredatastudio/issues/13303 to release/1.24

Revert "Verify the token belongs to the proper user. (#11593)" (#13321)

---

extensionsGallery.json

Build link: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=83144&view=results

update kusto to 0.3.2

---

extensionsGallery-insider.json

Build link: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=83144&view=results

Update Kusto extension to 0.3.2 in Insiders marketplace

---

src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts
src/sql/workbench/contrib/notebook/test/browser/htmlMarkdownConverter.test.ts

This PR fixes #12931
 PR from Main: #13267

[Port Request] Fix for < > (non HTML) tags disappearing in WYSIWYG

---

extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts

This PR fixes #13320,  fixes #13319

Fixes for incorrect button labels and the password validation error.

---

extensions/data-workspace/src/dialogs/dialogBase.ts
extensions/data-workspace/src/dialogs/newProjectDialog.ts
extensions/data-workspace/src/dialogs/openExistingDialog.ts
extensions/data-workspace/src/main.ts
extensions/data-workspace/src/test/dialogs/newProjectDialog.test.ts
extensions/data-workspace/src/test/dialogs/openExistingDialog.test.ts
extensions/data-workspace/src/test/testUtils.ts

Adding some tests to get test coverage above 0% for the data-workspace dialogs

Add tests for data workspace dialogs

---

.github/CODEOWNERS

Adding codeowners for the dacpac, schema compare, and sql database projects extensions

Adding @kisantia as a codeowner for dacpac and schema compare extensions

---

extensions/resource-deployment/src/ui/notebookWizard/notebookWizardModel.ts
extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts
extensions/resource-deployment/src/ui/resourceTypeModel.ts
extensions/resource-deployment/src/ui/resourceTypeWizard.ts

Hook up generateScriptButton to lastPageValidation

---

src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
src/sql/workbench/contrib/jobManagement/browser/jobsView.component.ts
src/sql/workbench/contrib/jobManagement/browser/notebooksView.component.ts
src/sql/workbench/services/jobManagement/browser/jobManagementUtilities.ts
src/typings/slickgrid.d.ts

Fix agent types from the previous fix that was included in release

Fix agent types

---

scripts/test-extensions-unit.js

Moved the dir creation into the loop but forgot to move the cleanup as well

Fix extension unit test script cleanup

---

src/sql/workbench/contrib/notebook/browser/notebook.component.html
test/automation/src/sql/notebook.ts
test/smoke/src/main.ts
test/smoke/src/sql/areas/notebook/notebook.test.ts

This PR adds a smoke test that opens up a notebook file (https://github.com/kburtram/azuredatastudio-smoke-test-repo/blob/master/hello.ipynb), runs all cells, saves notebooks, opens notebook and checks that all outputs are saved.

Notebooks: Add smoke test

---

src/sql/workbench/browser/modelComponents/modelViewContent.component.ts
src/sql/workbench/browser/modelComponents/viewBase.ts

Been finding it useful to have this kind of stuff when I'm working on these ModelView issues.

Add debug logging for ModelView

---

package.json

VBump ADS in main for Dec release.

Bump ADS to 1.25 for Dec release

---

extensions/dacpac/package.json
extensions/dacpac/package.nls.json
extensions/dacpac/src/wizard/api/dacFxConfigPage.ts
extensions/dacpac/src/wizard/common/constants.ts
extensions/dacpac/src/wizard/common/fileLocationHelper.ts

Add setting for default dacpac save location

---

CHANGELOG.md
README.md

Update the changelog for 1.24.0 release.

Update readme and changelog for 1.24.0

---

extensionsGallery.json

this needs to be merged and published on release day.

November release extension updates

---

extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts

Fixed the table width so it does not overflow from the wizard.

---

src/sql/workbench/services/dialog/browser/dialogContainer.component.ts

Removing separate heading for page number and including it with wizard title

---

extensions/sql-database-projects/package.json

bump sql database projects version

---

extensions/mssql/src/dashboard/bookExtensions.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/13402
Also adding in awaits so we're sure that the context is updated correctly when unregistering/registering the commands (no race conditions)

Re-register contributed book commands when new extension loaded

---

src/sql/platform/connection/common/connectionStore.ts
src/sql/workbench/services/connection/browser/connectionController.ts
src/sql/workbench/services/connection/browser/connectionDialogService.ts
src/sql/workbench/services/connection/browser/connectionWidget.ts

Passed azureAccount into onFetchDatabases and set on tempProfile.
This PR fixes #12666
Previous PR: https://github.com/microsoft/azuredatastudio/pull/13115/files

12666 Fixed database list not being populated on connection dialog

---

extensions/data-workspace/package.json
extensions/sql-database-projects/README.md
extensions/sql-database-projects/package.json

This PR fixes #13441.
- update dependencies for new ADS version
- update sql database projects readme with the new entry points
- adds command palette commands for new project and open existing

Update package.jsons and readme

---

extensions/mssql/config.json
extensions/mssql/src/main.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/13397
(Update to STS will be added later once the fix on that side is released)

Display error when doing notebook convert

---

extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts
extensions/resource-deployment/src/ui/resourceTypeWizard.ts

This PR fixes #13318 
Invalid state:
Valid state: 
Always enabled for summary page:

Fixed the generate script logic for notebook wizards.

---

extensionsGallery-insider.json
extensionsGallery.json

build with new vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=84130&view=artifacts&type=publishedArtifacts

Update schema compare to 1.7.0

---

extensionsGallery-insider.json

Update extensionsGallery Insider for ML 0.5.0

---

extensions/arc/notebooks/arcDeployment/deploy.arc.data.controller.ipynb
extensions/asde-deployment/notebooks/edge/deploy-sql-edge-azure.ipynb
extensions/asde-deployment/notebooks/edge/deploy-sql-edge-local.ipynb
extensions/asde-deployment/notebooks/edge/deploy-sql-edge-multi-device.ipynb
extensions/asde-deployment/notebooks/edge/deploy-sql-edge-remote.ipynb
extensions/asde-deployment/notebooks/edge/deploy-sql-edge-single-device.ipynb
extensions/azurehybridtoolkit/notebooks/hybridbook/content/ConnectionDialogue.ipynb
extensions/resource-deployment/notebooks/docker/2017/deploy-sql2017-image.ipynb
extensions/resource-deployment/notebooks/docker/2019/deploy-sql2019-image.ipynb

Fixes https://github.com/microsoft/azuredatastudio/issues/10886
These don't ever use it and since we don't install it by default anymore we should remove this dependency

Remove pandas import from some notebooks

---

extensions/machine-learning/src/views/widgets/dashboardWidget.ts

ML- Fixed the issue with adding and removing flex container

---

extensionsGallery-insider.json

Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=84164&view=artifacts&type=publishedArtifacts

update sql-database-projects to 0.5.0 in insiders

---

extensions/schema-compare/package.json
extensions/sql-database-projects/package.json

Updating the versions after both these extensions were released this week

update sql-database-projects and schema compare versions

---

extensions/arc/src/test/models/controllerModel.test.ts
extensions/sql-database-projects/src/test/baselines/publishProfileSqlLoginBaseline.publish.xml

Ran the tests and verified they still passed

Suppress scan warnings

---

extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts
extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts

Move focus to inside sql database projects dialogs when they open

---

extensions/mssql/config.json

Contains updated SqlClient for issue described in https://github.com/microsoft/sqltoolsservice/pull/1124

Update SqlToolsService to .59

---

scripts/sql.bat
scripts/sql.sh

Matching the package.json scripts https://github.com/microsoft/azuredatastudio/blob/main/package.json#L24

Increase heap size for sql script compile

---

src/sql/workbench/contrib/notebook/browser/notebook.css

update css to remove extra padding

---

product.json

Adding ML and DB project to Recommended Extns

Adding ML and DB project to Recommended Extns

---

extensions/notebook/src/dialog/remoteBookDialog.ts

Add synapse repo to dropdown option

---

extensions/resource-deployment/src/ui/modelViewUtils.ts
src/sql/workbench/api/common/extHostModelView.ts

Update required icon for labels for dynamic enablement

---

extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts
src/sql/workbench/browser/modelComponents/button.component.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/13537

Fix BDC table icons

---

build/azure-pipelines/darwin/sql-product-build-darwin.yml
test/smoke/src/main.ts

This PR adds smoke test logs to drop/smokelogs folder in published artifacts.
Example log: [smoke.log](https://github.com/microsoft/azuredatastudio/files/5590949/smoke.log)

Add logs to smoke tests

---

extensions/arc/src/localizedConstants.ts
extensions/arc/src/models/miaaModel.ts
extensions/arc/src/ui/dialogs/connectMiaaDialog.ts
extensions/arc/src/ui/dialogs/connectPGDialog.ts
extensions/arc/src/ui/dialogs/connectSqlDialog.ts

Postgres will be needing connection support for its parameters page. ConnectSqlDialog was turned into an abstract class to be used separately for Miaa and Postgres.

Set connectSqlDialog to be an abstract class. Separated out Miaa and Postgres. 

---

src/sql/platform/serialization/common/serializationService.ts

This PR fixes #https://github.com/microsoft/azuredatastudio/issues/13562

Notebooks: Fix grid export column header duplication

---

src/sql/platform/serialization/common/serializationService.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/13562
PR in main: https://github.com/microsoft/azuredatastudio/pull/13568

Notebooks: Fix grid export column header duplication 

---

extensions/machine-learning/package.json

ML extension: updating to 0.6.0

---

extensions/kusto/config.json
extensions/kusto/package.json

Update kusto release to 0.4.0 for aria fix

---

src/sql/workbench/services/connection/browser/connectionBrowseTab.ts

1. show a progress bar when filtering is in progress
1. add screen reader support for filtering

accessibility support for filtering

---

extensions/arc/package.json

Move namespace and name into "Controller" section
Old : 
New :

Re-order summary fields for arc deployment

---

package.json

This update is for this issue https://github.com/microsoft/azuredatastudio/issues/13452

Bump distro to pickup new icons

---

package.json

This PR fixes https://github.com/microsoft/azuredatastudio/issues/13452

Bump distro to pickup new icons (#13598)

---

extensions/notebook/src/book/bookPinManager.ts
extensions/notebook/src/book/bookTreeView.ts
extensions/notebook/src/common/utils.ts

This PR addresses  [#13628](https://github.com/microsoft/azuredatastudio/issues/13628)

add await to thenable method

---

src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts
src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts
src/sql/workbench/contrib/notebook/test/browser/htmlMarkdownConverter.test.ts

* Improvements to highlight
* wip
* Tests pass
* Leverage escaping mechanism
* Tweak highlight logic
* PR comments
This PR fixes #13212

WYSIWYG Improvements to highlight (#13032)

---

extensions/notebook/src/book/bookPinManager.ts
extensions/notebook/src/book/bookTreeView.ts
extensions/notebook/src/common/utils.ts

add await to thenable method (#13635)

---

extensionsGallery-insider.json

Vsix link: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=85339&view=artifacts&pathAsName=false&type=publishedArtifacts

Kusto insiders gallery update to 0.4.0

---

extensionsGallery.json

kusto gallery update to 0.4.0

---

src/sql/workbench/contrib/notebook/browser/notebook.css

This PR addresses [#13607](https://github.com/microsoft/azuredatastudio/issues/13607)

add right padding to notebook toolbar action item

---

src/sql/workbench/contrib/query/browser/keyboardQueryActions.ts

Co-authored-by: Monica Gupta <mogupt@microsoft.com>

Fix empty column issue (#13641)

---

extensionsGallery-insider.json

The vsix file has already been uploaded to blob storage.

update asde deployment extension

---

src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts

This PR fixes #13304
PR from main branch: #13614

Fix notebook unordered grid values after papermill execution (#13614)

---

extensions/notebook/src/book/bookPinManager.ts

This PR addresses [#13659](https://github.com/microsoft/azuredatastudio/issues/13659)

Normalize path to change

---

extensions/resource-deployment/src/test/ui/validation/modelViewUtils.test.ts

Remove extra console log...something weird happened with the PR where the commit I did to remove this there wasn't merged in.

Remove debug console log

---

extensions/resource-deployment/src/ui/modelViewUtils.ts

Remove placeholder on deployment when field is disabled dynamically

---

samples/sqlservices/src/controllers/mainController.ts
src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts

the updated code in the sample extension looks like this:
majority of the changes are refactoring the code.

add ability to control the enabled state of checkbox cells

---

extensionsGallery-insider.json

ADO build link for ML extension0.6.0: https://mssqltools.visualstudio.com/_apis/resources/Containers/2630819/drop?itemPath=drop%2Fextensions%2Fmachine-learning-0.6.0.vsix

Update extensionsGallery-insider.json for ML 0.6.0

---

extensionsGallery.json

Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=85717&view=artifacts&pathAsName=false&type=publishedArtifacts

Update sql database projects to 0.5.1

---

extensionsGallery.json

ADO build link for ML extension0.6.0: https://mssqltools.visualstudio.com/_apis/resources/Containers/2630819/drop?itemPath=drop%2Fextensions%2Fmachine-learning-0.6.0.vsix

Update extensionsGallery.json for ML 0.6.0 in RC 

---

extensionsGallery-insider.json

Same vsix that was uploaded when RC gallery was updated in https://github.com/microsoft/azuredatastudio/pull/13668

update sql database projects to 0.5.1 in insiders

---

src/sql/workbench/contrib/query/browser/keyboardQueryActions.ts

* Fix issue with pasting results in Teams
* Addressed comment to change header tag to th
Co-authored-by: Monica Gupta <mogupt@microsoft.com>

Fix issue with pasting results in Teams (#13673)

---

build/azure-pipelines/common/publish.ts

Fix ECONNRESET errors by adding retry during upload. Based off of https://github.com/microsoft/vscode/commit/66aab34216f488c803b49ff14d50dec90147ad6c

Retry publish and always try adding asset

---

build/azure-pipelines/common/publish.ts

Cherry pick https://github.com/microsoft/azuredatastudio/commit/6c89c61b0d1bbeea78f429f5d457ba6f2a83e8d3
Fix for ECONNRESET issue

[Port] Retry publish (#13700)

---

build/azure-pipelines/common/publish.ts

This was also failing with ECONNRESET

Retry getConfig

---

build/azure-pipelines/common/publish.ts

Port https://github.com/microsoft/azuredatastudio/commit/d6e1e8eb52b20711302789d4f00f323149aa1bbd
Additional fix for ECONNRESET

[Port] Retry getConfig (#13712)

---

extensionsGallery-insider.json
extensionsGallery.json

Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=86074&view=artifacts&pathAsName=false&type=publishedArtifacts

update schema compare to 1.8.0

---

extensions/integration-tests/src/onboarding/developers.ts

Added developer name to the list of developers.

---

extensions/arc/notebooks/arcDeployment/deploy.arc.data.controller.ipynb
extensions/arc/package.json

Per https://docs.microsoft.com/en-us/azure/azure-arc/data/upload-metrics-and-logs-to-azure-monitor?pivots=client-operating-system-powershell#create-service-principal

Fix environment variables for controller create

---

extensions/schema-compare/package.json
extensions/sql-database-projects/package.json

vbumping these extensions because new versions have been published

vbump schema compare and sql database projects

---

CHANGELOG.md
README.md

December release readme

---

extensions/mssql/config.json

(cherry picked from commit 94feb1a80d7dfbfd4670ebe6e21587c1f99f6b29)
Fixes https://github.com/microsoft/azuredatastudio/issues/13751

[Port] Update STS to revert SqlClient update (#13758)

---

package.json

Bump ADS version for Hotfix

---

src/sql/azdata.d.ts
src/sql/azdata.proposed.d.ts
src/sql/workbench/api/common/extHostModelView.ts

Let users get/set the values after initial creation if they want

Clean up Loading Component typings

---

src/sql/workbench/contrib/notebook/browser/notebook.component.ts

Notebook Deep Link to Section

---

src/sql/workbench/contrib/notebook/browser/media/notebook.contribution.css

Remove hardcoded search box height

---

src/sql/workbench/contrib/telemetry/common/telemetry.contribution.ts

Lots of these being fired - we don't care about these ones.

Filter vscode delegate command events

---

extensions/dacpac/src/localizedConstants.ts
extensions/dacpac/src/test/wizardServiceInteraction.test.ts
extensions/dacpac/src/wizard/dataTierApplicationWizard.ts

Dacpac - Showing error message to user if operation fails

---

extensionsGallery-insider.json
extensionsGallery.json

Japanese Language Pack package.json url was wrong, url now corrected.
This PR fixes #13835

fixed Japanese Language Pack package url.

---

extensions/sql-database-projects/src/common/constants.ts

Cleanup unreferenced strings

---

extensions/data-workspace/src/dialogs/openExistingDialog.ts
extensions/data-workspace/src/test/dialogs/openExistingDialog.test.ts

This PR adds logging to the unit test that is failing intermittently.

Add logging for unstable data-workspace extension unit test

---

src/sql/workbench/contrib/query/browser/keyboardQueryActions.ts

Received feedback from the team to add notification after copying the wuery and results. Added the same in this PR

Notification after copying query and results

---

src/sql/workbench/services/resourceProvider/browser/firewallRuleDialog.ts

Fixed the end parentheses for adding a firewall rule. 
This PR fixes #12230

Fix parentheses for firewall ip address

---

test/automation/src/sql/notebook.ts
test/smoke/src/sql/areas/notebook/notebook.test.ts

This PR checks that iframe, dialog, embed, and svg tags are not rendered when a notebook is untrusted and are rendered when the notebook is trusted.

Notebooks: add behavior checks to untrusted notebook smoke test

---

extensionsGallery-insider.json
extensionsGallery.json

Add the new "Extra Sql Script As" extension to the extensions gallery

Add to gallery "Extra Sql Script As" extension

---

src/sql/workbench/browser/scriptingActions.ts
src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts

Fix for query select command text in manage tab for Kusto tables

---

extensions/data-workspace/src/dialogs/dialogBase.ts
extensions/data-workspace/src/dialogs/openExistingDialog.ts
extensions/data-workspace/src/test/dialogs/openExistingDialog.test.ts

Follow-up PR to requests in #13883

Preserve error messages if workspace validation fails in tests

---

build/azure-pipelines/linux/sql-product-build-linux.yml

Only archive User and logs folders (settings and logs) since those are going to mostly be the useful ones for debugging issues.

Only archive some folders

---

extensions/sql-migration/src/main.ts
extensions/sql-migration/src/models/stateMachine.ts
extensions/sql-migration/src/wizard/sourceConfigurationPage.ts
extensions/sql-migration/src/wizard/wizardController.ts

Just cleaning up the wizard.
1. Changing how connection is stored
2. Disabling some wizard pages

Changing how connection is stored in Migration Wizard and some misc code cleanup 

---

extensions/integration-tests/src/test/dacpac.test.ts
extensions/integration-tests/src/test/notebook.test.ts
extensions/integration-tests/src/test/schemaCompare.test.ts

This is being very optimistic - but these all haven't failed in a bit and so I feel like enabling them now and then having another discussion if they end up failing is worth the possible risk of random failures. 
@udeeshagautam @kisantia @SakshiS-harma How confident do you feel about re-enabling the DacPac/Schema Compare tests? Did you ever track down what the issues were?

Re-enable some unstable tests

---

src/sql/workbench/contrib/notebook/browser/notebook.component.ts

This PR is work done for 13899.

Revised section scrolling logic to fix broken user experience.

---

samples/sqlservices/README.md
samples/sqlservices/src/typings/refs.d.ts
src/sql/workbench/browser/modelComponents/tree.component.ts

fix the null reference error noticed in sqlservices extension and update the readme and add reference to proposed typings files.

fix tree component and update sqlservices

---

extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts
extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts
extensions/arc/src/ui/dashboards/postgres/postgresSupportRequestPage.ts

Was getting ResourceNotFound 404 error when trying to get to support request page. Updated hyperlink.

Updating Arc resources link to match new provider. 

---

extensionsGallery-insider.json
extensionsGallery.json

Updating Import extension to 1.2.0 

---

extensions/sql-migration/src/wizard/accountsSelectionPage.ts
extensions/sql-migration/src/wizard/databaseBackupPage.ts

- Adding null checks for onValueChanged
- Adding new event for radiobuttons onDidChangeCheckedState

Fixing errors in existing migration pages 

---

extensions/import/package.json

vbump import extension for future release

---

src/sql/base/browser/ui/radioButton/radioButton.ts

There was an issue where updating the 'checked' property of radio Button was not working.
This PR fixes #13975

Fixing radioButton checked status

---

extensions/machine-learning/src/views/models/manageModels/currentModelsComponent.ts
extensions/machine-learning/src/views/models/prediction/columnsTable.ts
extensions/machine-learning/src/views/models/tableSelectionComponent.ts

fixing an issue with infinite loop when updating the page. The issue seems to be new and might be because of a change in core but couldn't figure out what cuased it. Instead added check to only update the UI if needed

ML- Fixed the bug with refreshing the page over and over

---

src/sql/workbench/contrib/notebook/browser/notebook.component.ts

Merges changes approved for issue #13899

Revised section scrolling logic to fix broken user experience. (#13926)

---

CHANGELOG.md

Adding changelog for 1.25.2

---

resources/localization/LCL/fr/cms.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210122213024154 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210122213024154 to main

---

build/gulpfile.hygiene.js
resources/localization/LCL/fr/dacpac.xlf.lcl

We don't need to check these for proper indentation since they're generated by another tool. 
@khoiph1 Not sure how you got around the precommit hook - it should have given you an error when you tried to commit your changes. Did you see any such error?

Add lcl files to hygiene indent ignore list

---

extensions/arc/src/models/controllerModel.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/14025
The promise here was causing a deadlock because of how the logic is set up - if an error occurs during a refresh it will then recall refresh in order to reprompt the user for controller info. This meant it was stuck on the promise forever the second time.
We no longer need this promise guard though - acquireAzdataSession will guarantee that a refresh is completely finished before another starts. 
Now the behavior again will be that if the tree is expanded before azdata discovery is complete we'll display an error and prompt the user to reconnect : 
This isn't completely ideal though - we really should be either waiting for the initial azdata discovery to complete (at which point we'll show the error if azdata isn't installed) …

Fix hang when expanding arc tree node without azdata

---

extensionsGallery-insider.json
extensionsGallery.json

Update Select Top N extension version.

Update Select Top N extension version

---

extensions/sql-migration/src/models/strings.ts
extensions/sql-migration/src/wizard/tempTargetSelectionPage.ts
extensions/sql-migration/src/wizard/wizardController.ts

Adding a temporary target selection page for sql migration

---

src/sql/workbench/contrib/resourceViewer/browser/resourceViewer.contribution.ts

Fix resource viewer not showing on insiders builds

---

build/azure-pipelines/darwin/sql-product-build-darwin.yml
build/azure-pipelines/distro-build.yml
build/azure-pipelines/docker/sql-product-build-docker.yml
build/azure-pipelines/linux/sql-product-build-linux.yml
build/azure-pipelines/sql-product-compile.yml
build/azure-pipelines/web/sql-product-build-web.yml
build/azure-pipelines/win32/sql-product-build-win32.yml

I don't the email address actually matters, let's see the result of the pr validation build

update the email address

---

extensions/notebook/src/book/remoteBookController.ts
extensions/notebook/src/dialog/remoteBookDialog.ts
extensions/notebook/src/dialog/remoteBookDialogModel.ts

Initialize releases when creating remote book controller to prevent undefined error.

Initialize releases when creating remoteBookController

---

extensionsGallery-insider.json
extensionsGallery.json

this will be merged after https://github.com/microsoft/azuredatastudio/pull/14087

vbump server reports

---

extensions/azurehybridtoolkit/notebooks/hybridbook/content/Assessments/sql-server-assessment.ipynb

Adding text to point notebook readers to consider the sql assessment extension. no code changes

breadcrumbs for sql assessment extension

---

extensions/server-report/README.md
extensions/server-report/package.json

vbump server-report extension

---

extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts

Fixing the null check for agreements

---

extensions/admin-tool-ext-win/package.json
extensions/admin-tool-ext-win/yarn.lock
extensions/dacpac/package.json
extensions/dacpac/yarn.lock
extensions/data-workspace/package.json
extensions/data-workspace/yarn.lock
extensions/notebook/package.json
extensions/notebook/src/telemetry.ts
extensions/notebook/yarn.lock
extensions/schema-compare/package.json
extensions/schema-compare/yarn.lock
extensions/sql-assessment/package.json
extensions/sql-assessment/yarn.lock
extensions/sql-database-projects/package.json
extensions/sql-database-projects/yarn.lock

Bump ads-extension-telemetry

---

extensions/arc/src/test/ui/components/filePicker.test.ts
extensions/arc/src/test/ui/components/radioOptionsGroup.test.ts
extensions/arc/src/ui/components/filePicker.ts
extensions/arc/src/ui/components/radioOptionsGroup.ts
extensions/arc/src/ui/dialogs/connectControllerDialog.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/13553
We weren't setting the correct field on the components

Fix other fields being editable in password reprompt for Arc

---

extensions/machine-learning/package.json

version update for ml 0.7.0
