- extensions/dacpac/src/test/testDacFxService.ts
- extensions/mssql/src/contracts.ts
- extensions/mssql/src/dacfx/dacFxService.ts
- extensions/mssql/src/mssql.d.ts
- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/package.nls.json
- extensions/sql-database-projects/resources/templates/newTsqlExternalStreamingJobTemplate.sql
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/mainController.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/models/tree/fileFolderTreeItem.ts
- extensions/sql-database-projects/src/models/tree/projectTreeItem.ts
- extensions/sql-database-projects/src/templates/templates.ts
- extensions/sql-database-projects/src/test/baselines/openSqlProjectBaseline.xml
- extensions/sql-database-projects/src/test/baselines/openSqlProjectWithAdditionalSqlCmdVariablesBaseline.xml
- extensions/sql-database-projects/src/test/project.test.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
- extensions/sql-database-projects/src/test/templates.test.ts
- extensions/sql-database-projects/src/test/testContext.ts
Reconstruction of https://github.com/microsoft/azuredatastudio/pull/13148
This PR adds basic sqlproj and UX support for External Streaming Jobs and validation. The validation will use the model from the most recently built dacpac, or build a new one if there isn't one in the output folder.
> Adding External Streaming Job I/O validation

- src/sql/workbench/contrib/notebook/test/browser/sqlFuture.test.ts
This PR adds a unit test for the data conversion logic (converting the grid rows returned from SQL Tools Service to data resource and html) in SQLFuture class.
> Notebooks: Add unit test for data conversion in SQLFuture

- extensions/azurecore/src/account-provider/azureAccountProvider.ts
- src/sql/platform/accounts/common/accountStore.ts
Adding some more logging to help try to track down https://github.com/microsoft/azuredatastudio/issues/11260
User was seeing this error on startup so it looks like something might be wrong with the memento retrieval. 
```
/C:/Users/a/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2315   ERR e is not iterable: TypeError: e is not iterable
at p._initialize (c:\Users\a\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\azurecore\dist\extension.js:166:32362)
at p.initialize (c:\Users\a\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\azurecore\dist\extension.js:166:32302)
at c:\Users\a\AppData\Local\Programs\Azure Data Studio - …
```
> Add Azure account initialization logging

- extensions/mssql/src/hdfs/ui/hdfsManageAccessDialog.ts
Current look in dark mode : 
Fixed in dark mode : 
Fixed in light mode :
> Remove hardcoded colors for HDFS access dialog

- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
Turned on exceptions and found that we were throwing in notebookActions because we were checking a property on the clientSession before checking that clientSession existed at all.
Followed where the nearest `catch` block is, and it doesn't look like this has any adverse effects (and prevents other code from being executed).
> Notebooks: Check for clientSession before checking isInErrorState

- src/sql/workbench/contrib/resourceViewer/browser/resourceViewer.contribution.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13237
(cherry picked from commit fd8f88db4b4d22a6b9810fd7349369884973f650)
The Resource Viewer is going to be in insiders for the time being - this is hiding it for the RC builds.
> Only show resource viewer on insiders and dev (#13238)

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/resources/templates/newTsqlExternalStreamingJobTemplate.sql
* Fixes #13245: Updating the template to make the names of the sample columns more generic and add information about its dependencies
* Disabling Streaming Job validation until the dependent code in Tools Service is present in drops, issue #13234
> Disabling validation, changing template for Streaming Jobs

- extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
The progress popup waits for instance to be edited and model has been refreshed before closing out and showing update notification.
> Compute and Storage Page, progress notification waits for model to be refreshed before saying instance has been updated. 

- extensions/arc/src/ui/dashboards/postgres/postgresConnectionStringsPage.ts
The hyperlink in Connection Strings page has been corrected to point to https://docs.microsoft.com/en-us/azure/azure-arc/data/get-connection-endpoints-and-connection-strings-postgres-hyperscale.
> Changed hyperlink found on PG ConnectionString Page

- src/sql/base/browser/ui/checkbox/checkbox.ts
- src/vs/workbench/browser/media/style.css
This PR fixes #12979 
Light:
Dark:
I am taking over this change from vscode to ads.
> Adding custom focus outline-offset for checkboxes

- src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts
- src/sql/workbench/contrib/notebook/test/browser/htmlMarkdownConverter.test.ts
Fixes #12842. Turndown doesn't like nested lists and there's some discussion here: https://github.com/domchristie/turndown/issues/272.
If we generate the HTML from that issue from the contentEditable attribute set to true, then we should display it as users would expect 😄 
Based on https://github.com/domchristie/turndown/blob/8ba04467c5fd73f58a1b49f68a66266f30fa202b/src/commonmark-rules.js#L61. Just added a few lines there to see how many levels deep the list item should be indented.
> WYSIWYG fix list nesting

- extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresConnectionStringsPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresDashboard.ts
- extensions/arc/src/ui/dashboards/postgres/postgresPropertiesPage.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13262
(Workaround for https://github.com/microsoft/azuredatastudio/issues/13134)
This adds loading indicators to the Compute&Storage and Connection Strings pages when the config is waiting for data to be present. 
Also...
TODO in Properties page was completed so that LinkKeyValue takes user to controller dashboard. (not currently shown on ADS)
> [Port] Added Loading to Compute&Storage and Connection Strings Pages

- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
- src/sql/workbench/contrib/welcome/page/browser/gettingStartedTour.ts
Addresses [13265](https://github.com/microsoft/azuredatastudio/issues/13265)
Setting the button's icon property with empty was causing the DOM exception.
`Uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty`
> Remove button property setter causing exception

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/models/project.ts
Fixes #13233 by correctly tagging the in-memory object at creation time; previously only got tagged when loaded from sqlproj
Fixes #13234 by re-enabling the validation menu item now that SqlToolsService is updated
> Enables streaming job validation, minor bugfix

- src/sql/workbench/contrib/notebook/browser/turndownPluginGfm.ts
- src/sql/workbench/contrib/notebook/test/browser/htmlMarkdownConverter.test.ts
Addresses [13289](https://github.com/microsoft/azuredatastudio/issues/13289)
If we have a table with no headings and update the cell in rich text mode, then the border line and headings are removed and the table gets corrupted. To fix the issue, I check if the head of the table is empty and add the empty headings and the border line before the table's content.
> Table with no headings gets corrupted when editing 

- extensions/arc/src/ui/dashboards/miaa/miaaConnectionStringsPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresConnectionStringsPage.ts
This PR fixes #13151 
Most of apps using Orcas do not really use the web app connection string property setting from app service, so this will follow the removal of the string like in Flexible and Single server on portal.
> Removed Web App connection strings. 

- build/azure-pipelines/linux/product-build-linux.yml
- build/azure-pipelines/linux/sql-product-build-linux.yml
- scripts/test-extensions-unit.bat
- scripts/test-extensions-unit.js
- scripts/test-extensions-unit.sh
Uploads the user data directories generated during test runs as build artifacts to help with test failure debugging.
See https://mssqltools.visualstudio.com/_apis/resources/Containers/2586338/drop?itemPath=drop%2Flogs%2Flinux-x64%2Flogs-linux-x64.tar.gz for an example of the generated archive. 
Also added the names to the temp user data dirs we create for the test runs to easily tell which run the logs came from. Only did this for the JS script on purpose since we don't really use the others anymore and that functionality isn't needed there currently.
> Upload user dir from test runs

- src/sql/base/parts/editableDropdown/browser/dropdown.ts
This PR fixes #12980
there are 4 ways to invoke the dropdown list and the expected focus behavior when escape is pressed to close the dropdown list
click inside the textbox -> focus should go back to textbox
press down arrow key when textbox is being focused -> focus should go back to text box
click on the dropdown arrow when focus is not within the control: -> focus should go back to textbox (similar to native select control)
focus on the dropdown arrow and invoke it -> focus should go back to the dropdown arrow
the fix is to capture the focused element before showing the list and restore focus to it when escape is pressed.
> restore focus on escape

- .github/workflows/ci.yml
Been seeing a lot of failures similar to this lately in CI builds (where we aren't currently caching packages) :
https://github.com/microsoft/azuredatastudio/pull/13330/checks?check_run_id=1382218824
```
Tue, 10 Nov 2020 21:47:37 GMT
yarn install v1.22.5
Tue, 10 Nov 2020 21:47:37 GMT
$ node build/npm/preinstall.js
Tue, 10 Nov 2020 21:47:38 GMT
[1/4] Resolving packages...
Tue, 10 Nov 2020 21:47:39 GMT
[2/4] Fetching packages...
Tue, 10 Nov 2020 21:48:56 GMT
info There appears to be trouble with your network connection. Retrying...
Tue, 10 Nov 2020 21:49:06 GMT
info There appears to be trouble with your network connection. Retrying...
Tue, 10 Nov 2020 21:49:30 GMT
info There appears to be trouble with your network connection. Retrying...
Tue, 10 Nov 2020 21:49:39 GMT
info There appears to …
```
> Increase yarn timeout when installing packages

- extensions/sql-database-projects/src/test/dialogs/addDatabaseReferenceDialog.test.ts
- src/sql/platform/dashboard/browser/interfaces.ts
- src/sql/platform/model/browser/modelViewService.ts
- src/sql/workbench/browser/modelComponents/componentBase.ts
- src/sql/workbench/browser/modelComponents/modelStore.ts
- src/sql/workbench/browser/modelComponents/viewBase.ts
Fix for https://github.com/microsoft/azuredatastudio/issues/13134
The root issue causing this is that when we queue up actions we do so through promise chaining, which doesn't guarantee order of execution when the root Promise is resolved. This problem is made even worse by the actions never waiting to "complete" - i.e. actions such as setting properties are usually async but the actual action function call is never awaited. 
I've experimented around with completely serializing the actions but in the past I've always hit some weird issues - and so for this fix I just scoped it down to at least gather up the small set of "initial" actions (which are the ones queued. 
I plan to keep poking at this and moving it towards a much more deterministic state but in my testing this solves the …
> Run initial modelview actions first

- src/sql/workbench/services/dialog/browser/wizardNavigation.component.ts
This PR fixes #12963
add tabindex to leverage the vscode global outline color: https://github.com/microsoft/azuredatastudio/blob/main/src/vs/workbench/browser/style.ts#L114
and I noticed the page number doesn't handle keyboard selection so adding it.
before:
after:
> add tabindex and handle keyboard selection

- extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13134
Reverts the temporary changes made to the Compute+Storage page for the loading components. The actual fix was done in other PRs - this is just moving the page back to using the original loading components. 
Visiting tab only after changes have already been made (originally what was broken):
Visiting tab immediately and then having components updated afterwards:
> Change PG Dashboard page back to using original loading components

- extensions/azdata/src/azdata.ts
The progress notification makes it clearer about the status of the install - the status bar item was too easy to miss.
> Use progress notification for azdata install/updates

- build/azure-pipelines/linux/sql-product-build-linux.yml
We were only uploading the artifacts when all previous steps succeeded which meant if a test failure happened we wouldn't get the logs.
I could have made it so we only upload the logs (other artifacts are ignored) but it doesn't seem to be a bad thing to always upload the artifacts even for a failed build - the build will still fail so won't cause other pipeline tasks to run unexpectedly.
> Always upload build artifacts + logs during product build

- src/sql/workbench/services/dialog/browser/wizardModal.ts
This PR fixes #12983. The dacpac wizard adds and removes pages based on the selected radio button, so the page step and name were getting announced every time a different radio button was selected.
> Fix wizard page name and step getting announced when pages are added and removed

- extensions/azurehybridtoolkit/.gitignore
@smartguest How are these even generated? I just had them show up randomly in my repo without opening the Notebook or anything. Are users expected to have some c# compiler installed or anything to properly generate these?
And then taking a quick look through the files what is all this supposed to be doing? There's some weird stuff like hardcoded paths : https://github.com/microsoft/azuredatastudio/blob/main/extensions/azurehybridtoolkit/notebooks/hybridbook/Components/ADP/SqlPackageWrapper/Program.cs#L13
> Ignore built notebook component files

- extensions/sql-database-projects/src/models/tree/projectTreeItem.ts
This PR fixes #13361. This removes the .sqlproj file extension from the project tree nodes to match mockups
> Remove sqlproj from Project tree node

- src/sql/workbench/browser/modelComponents/componentBase.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13318
This was broken in https://github.com/microsoft/azuredatastudio/pull/13317
This changed when the event handler was hooked up - since it wasn't specified as an "initial" action that meant it was only ran after the other initial actions were done. For containers these initial actions include adding and defining child components - so now when the child component is created the event handler isn't hooked up yet and so the parts of the creation (such as setting properties) that triggered the validity update were done before that event handler was hooked up.
So the fix here is just to make the action to register the event handler for child components also an "initial" action so it gets set before the child components are created.
> Fix ModelView container validation ordering

- extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts
Before notebook generation the toolsForCurrentProvider in toolsService need to be set by the toolsAndEulaPage. It was doing it in an onComplete method that is not called from anywhere. Changed the method to onLeave so that this value gets set when toolsAndEulaPage has exited.
This PR fixes #13365
> onComplete -> onLeave for toolsAndEulaPage

- extensions/notebook/src/book/bookTreeView.ts
- extensions/notebook/src/test/common/notebookUtils.test.ts
Last night we had one notebooks extension unit test failure during one of the canary runs. Many of the tests failed with this message:
```AssertionError: There should be not any open Notebook documents```
Before running the notebookutils test suite, we weren't actually ensuring that all editors were closed, while the first line of the newNotebook test suite has the following assert:
`should(azdata.nb.notebookDocuments.length).equal(0, 'There should be not any open Notebook documents');
`
Fixed this by ensuring that we're closing all open editors in a new `beforeAll()` method.
In addition, there was an exception being thrown in bookTreeView when bookItem was undefined and we called `this._bookViewer.reveal()`. Doing a simple check removes these exceptions.
> Fixes for NotebookUtils Tests Reliability

- src/sql/workbench/browser/modelComponents/groupContainer.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13405
The issue here is that we were updating a property in the constructor before the object was fully instantiated - this caused it to fire off a bunch of other stuff including the validation logic and so the descriptor was still undefined when it ran those functions.
Doing this is pretty dangerous in general - setting properties causes all sorts of side effects and so doing it before it's fully instantiated is highly likely to cause issues elsewhere.
I debated adding an undefined check to the logging calls for safety but given the previous sentence I would rather keep this as it is and clearly break things when that happens instead of silently ignoring it. 
It might not be the worst idea to actually throw an exception when we …
> Fix ModelView logging error

- extensions/data-workspace/src/dialogs/newProjectDialog.ts
- extensions/data-workspace/src/dialogs/openExistingDialog.ts
This makes it so that the workspace text doesn't get set until both the project name and location are selected. Also fixes the workspace text not getting updated when the location inputbox is edited directly instead of selected from the file browser.
> New project dialog workspace inputbox fixes

- src/sql/base/parts/editableDropdown/browser/dropdown.ts
I was testing something together with the changes I made to address the comments and forgot to remove the comment before commit.
> uncomment the hideContextMenu

- src/sql/base/browser/ui/panel/panel.ts
while testing the browse connection feature, I noticed that there is no focus indicator when the connection dialog's tab header is getting focused. when the tab header is getting focused it will focus on the active tab header, but the css rule being removed in this PR is setting the outline to be hidden.
**Before**
look the same with or without focus
**After**
with focus:
without focus:
> enable the outline for active tab header

- extensions/schema-compare/src/schemaCompareMainWindow.ts
- src/sql/workbench/browser/modelComponents/componentBase.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13385
I'm not super confident that this won't have any side-effects but it fixes the immediate issues and I went through a bunch of other dialogs and didn't notice anything weird layout wise.
Laying out the child components before the container meant that child components which depended on layout properties of the parent (such as width) weren't having that set correctly when their layout was done. This could cause issues such as the one described in the bug - this is only happening in a few special cases though because we call layout from so many different places that most other things either don't have the specific layout dependencies or are having that called after the parent container is fully done with its layout.
> Fix ModelView container child layout issues

- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
- src/sql/workbench/services/connection/browser/connectionDialogService.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
Changed tryAddActiveConnection to always add recent connection
This PR fixes # https://github.com/microsoft/azuredatastudio/issues/12567
> 12567 Fixed Notebooks not adding to recent connections

- src/sql/azdata.d.ts
This PR fixes this issue in azdata:
node_modules/azdata/azdata.d.ts:4734:20 - error TS2430: Interface 'IDisplayResult' incorrectly extends interface 'ICellOutput'.
Types of property 'metadata' are incompatible.
Type '{ resultSet?: ResultSetSummary; }' has no properties in common with type 'ICellOutputMetadata'.
4734:    export interface IDisplayResult extends ICellOutput {
which was caused by my grid streaming changes: https://github.com/microsoft/azuredatastudio/blame/32a6385fefab8f75902dfbe4ca92fdde2836a5c6/src/sql/azdata.d.ts#L4744
The resultSet property did not need to be added in IDisplayResult, only in ICellOutputMetadata. I checked that the only places we are accessing metadata is through the metadata field in ICellOutput https://github.com/microsoft/azuredatastudio/blob/2b4986c8272 …
> Remove resultSet from IDisplayResult metadata

- src/vs/platform/extensionManagement/node/extensionManagementService.ts
Closes https://github.com/microsoft/azuredatastudio/issues/13430
We were doing both engine version checks in the same check and then using the wrong version when displaying the error to the user. Splitting them out to make it clear which version isn't compatible.
> Fix extension install version check

- extensions/data-workspace/src/dialogs/dialogBase.ts
- extensions/data-workspace/src/dialogs/newProjectDialog.ts
- extensions/data-workspace/src/dialogs/openExistingDialog.ts
This PR fixes ##13444. Previously, only the new project dialog had the workspace information. Since it's common code for both dialogs, I moved a lot of the code to the dialogBase. 
The workspace that the project is being added to only shows if the project radio card is selected and goes away when the selection is changed to open a workspace:
> add workspace information to open existing dialog

- extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
Forgot to push my changes with this line before merging https://github.com/microsoft/azuredatastudio/pull/13189. This fixes the target dropdown starting with no values until the server is selected.
> Fix schema compare database dropdown not starting with values

- src/sql/workbench/browser/modelComponents/loadingComponent.component.ts
- src/sql/workbench/browser/modelComponents/viewBase.ts
Discovered while investigating https://github.com/microsoft/azuredatastudio/issues/13476
Loading component is a bit weird - it uses container functionality like addItem which means that on the core side it has itemConfigs.
But then we have logic that assumes if a component has itemConfigs that it also implements removeFromContainer which it doesn't because it just extends from ComponentBase.
For now I'm just implementing removeFromContainer here - this shouldn't be a normal case and is more of a side effect of LoadingComponent being a pretty weird component itself. But to be safe I also guarded against addToContainer, removeFromContainer and clearContainer not being set to prevent this from happening again in the future.
> Fix Loading component removal

- extensions/data-workspace/package.nls.json
- extensions/data-workspace/src/common/constants.ts
Updating a few strings with suggestions from Drew. Since we only have one project type right now, it should be fine to have .sqlproj specific strings, but we’ll need to remember to update those in the future when more project types are added.
> Update a few strings in projects

- src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
Fixes #13472.
We currently wait until a notebook kernel is loaded before trying to set an editor's language, but this means that code cells won't have a language associated with them until the kernel is finished loading (which may be many seconds, depending on whether a Jupyter server needs to be started or not). This means that users will see un-colorized editors.
This change sets the language info based on what was serialized in a notebook previously (if it exists). Note that we're still checking for language info when the kernel is loaded; this change merely tries to optimize for the case when language info was present in the notebook previously.
> Attempt to Colorize Code Cells from Notebook Contents

- extensions/machine-learning/images/linkIcon.svg
- extensions/machine-learning/src/views/widgets/dashboardWidget.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/browser/modelComponents/hyperlink.component.ts
- src/sql/workbench/browser/modelComponents/media/hyperlink.css
I am working on the component support for migration experience, showing the link icon next to link is a common design now, so adding this option to hyperlink component,  also updated ML dashboard to use the new option.
instead of hard coding the font size of the icon, I am letting it to use the font size of the hyper link.
Before:
After:
> add option to show link icon

- src/sql/workbench/contrib/notebook/test/browser/sqlFuture.test.ts
- src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/13486 and fixes https://github.com/microsoft/azuredatastudio/issues/13433
Queries against PostgreSQL servers do not have result streaming support and the results are returned in one set.
The code changes ensure that all the rows are being displayed even when there is no streaming implemented.
> Notebooks: Fix query results not displaying table rows

- extensions/arc/package.json
- extensions/asde-deployment/package.json
- extensions/resource-deployment/src/interfaces.ts
- extensions/resource-deployment/src/ui/modelViewUtils.ts
- extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts
Doing some general cleanup : 
1. RadioGroupLoadingComponentBuilder was using the name property to store the value but this isn't correct, name should be used for grouping radio buttons together - not for storing the actual value (value should be used for that) https://www.w3schools.com/tags/att_input_type_radio.asp
1. As part of this the value for the dynamic enablement is now going to be the actual non-display value so updating that 
1. Removed the "displayName" values for the Azure sections. Instead implementing an optional getDisplayValue function for all inputs that will return the appropriate user-visible display name and then having the evaluated text use that. Currently evaluated text is only used for these kind of display scenarios so that should be safe - we can add support for …
> Cleanup Resource Deployment ModelView

- src/sql/workbench/browser/modelComponents/button.component.ts
migration workstream needs to use button image, I noticed the button with image relies on the original size of the image and the iconWidth/iconHeight properties are not being respected.
before:
after:
code used for demo purpose:
```TypeScript
view.modelBuilder.button().withProperties<azdata.ButtonProperties>({
label: this.NewStepButtonString,
title: this.NewStepButtonString,
width: 140,
iconPath: {
light: 'C:\\git\\azuredatastudio\\extensions\\agent\\resources\\light\\open_notebook.svg',
dark: 'C:\\git\\azuredatastudio\\extensions\\agent\\resources\\dark\\open_notebook_inverse.svg'
},
iconWidth: 16,
iconHeight: 16
}).component();
```
> fix icon size issue

- extensions/sql-assessment/package.json
- extensions/sql-assessment/src/tabs/assessmentMainTab.ts
- extension versions 0.5.0 and minimal ADS core version - 1.24.0 - the one with icon column feature
- use iconWigth and iconHeight props to set toolbar icon size
> bumping versions and using ComponentWithIcon props to set icon size

- src/sql/base/browser/dom.ts
- src/sql/workbench/browser/modelComponents/button.component.ts
- src/sql/workbench/browser/modelComponents/componentWithIconBase.ts
- src/sql/workbench/browser/modelComponents/media/toolbarLayout.css
This PR fixes #13521
introduced by https://github.com/microsoft/azuredatastudio/pull/13514
for toolbar, we would like a consistent sizing for all buttons, overwriting the sizing in toolbar container's CSS.
for normal buttons, I am providing a proper default size.
before:
after:
> fix the extra large icon issue

- src/sql/workbench/browser/modelComponents/componentBase.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13511
It's possible this is going to affect other components which are relying on this behavior always applying - but in general I don't think this is the best approach for this anyways. One problem we have with setting the enabled state like this is that it's not guaranteed to hold since components can update their own enabled state at any point. 
But we can probably assume/rely on people setting the enabled state on either the parent container or the child components and not trying to do both in which case this should work fine.
> Let child ModelView components control their enabled status by default

- extensions/azurecore/src/azureResource/tree/flatAccountTreeNode.ts
This PR fixes #13297
Previously we will show the resources only when all the resources are loaded, if there are a lot of subscriptions, it will take a long time for user to see anything, now changing this to show the resources as soon as they become available - to be accurate, the tree is refreshed once every 500ms (if new resources are retrieved). this is to prevent too frequent refreshing.
before we expand the node:
while it is loading
still loading
when loading is completed
> show the resources as soon as they become available

- extensions/machine-learning/src/views/externalLanguages/languagesTable.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
- src/sql/workbench/browser/modelComponents/modelStore.ts
- src/sql/workbench/browser/modelComponents/viewBase.ts
- src/sql/workbench/test/electron-browser/modalComponents/componentBase.test.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13476
Unfortunately this isn't fixing the root issue.
From my investigation what seems to be happening here is that the ML dialog is set up so that when it loads it "refreshes" the page it will remove all components and then add them back (based on current settings and such).
This is causing a race condition though - 
1. Root container for table is removed
1. This causes Angular to detect this and go through and start removing and destroying child components in the background
1. The table data is loaded and we set the table component data - this adds the components to the table which creates them in the ModelStore
1. The table component is re-added by the extension
1. Angular eventually gets down to removing the actual table …
> Fix declarative table display issues with ML ext

- extensions/machine-learning/src/views/models/modelManagementController.ts
Noticed this while fixing the table - clicking the button on an unsupported server was doing nothing and displaying this error in the console 
`[15636:1124/144543.693:INFO:CONSOLE(44)] "TypeError: Cannot read property '_apiWrapper' of undefined`
The reason here is that all these functions are being called through executeAction https://github.com/microsoft/azuredatastudio/blob/main/extensions%2Fmachine-learning%2Fsrc%2Fviews%2FcontrollerBase.ts#L25, but that is causing it to lose the this context.
TBH what I think a better pattern to use here is to wrap the function call in a lambda instead : 
`await this.executeAction(view, PredictWizardEventName, args, () => this.predictModel(models, undefined, this, this._apiWrapper, this._root));`
which doesn't have this problem so is a lot safer and …
> Fix error path for predict button on ML import

- extensions/azurecore/package.json
- extensions/azurecore/src/azureResource/commands.ts
- extensions/azurecore/src/extension.ts
the refresh command doesn't really meant to refresh both trees especially the node context menus. there is no real impact here since the tree component is doing no-op if the passed in node is not found, but we should fix it so that only the right tree gets the refresh request.
> scoped refresh commands

- src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts
- src/sql/workbench/contrib/notebook/test/browser/htmlMarkdownConverter.test.ts
This PR fixes #13454.
It fixes when a user copied both Text and images, and we now convert the image link properly (similar to how we did it in the October release of ADS).
> Fix WYSIWYG text + image paste

- extensions/sql-database-projects/package.json
With this PR, "Create Project From Database" can be called from within data-workspace extension from the ellipsis (...).
On clicking the 3dots, a new option is added for create project from database.
And this opens the import UI.
> Add Import UI to Data-workspace Ellipsis

- extensions/sql-assessment/src/assessmentResultGrid.ts
- src/sql/workbench/browser/modelComponents/table.component.ts
The focus gets lost each time new data gets appended to the table. This became an issue if a user is using keyboard for navigation through grid rows.
The fix is to restore this focus so a user can keep navigating by grid rows with keyboard keyup/keydown buttons.
> sqlAsmt: restore focus after grid append command

- extensions/data-workspace/src/dataworkspace.d.ts
- extensions/data-workspace/src/services/workspaceService.ts
- extensions/data-workspace/src/test/projectProviderRegistry.test.ts
- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
The new parameter will inform the project extension which of its project IDs was selected during `createProject()`
> Adding additional parameter to Create Project data workspace provider API

- extensions/data-workspace/src/dataworkspace.d.ts
- extensions/data-workspace/src/services/workspaceService.ts
- extensions/data-workspace/src/test/projectProviderRegistry.test.ts
- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
Business justification port request: https://github.com/microsoft/azuredatastudio/issues/13575
Tech lead port request: https://github.com/microsoft/azuredatastudio/issues/13573
This change adds a missing parameter to the contract between the new Data Workspaces extension and implementing project extensions that specifies which template was selected in the New Project dialog, which is important if the extension registers multiple templates (as in the case for Database Projects).
> Adding additional parameter to data workspace provider API (#13570)

- extensions/mssql/config.json
Main change since last Tools Service version:
* Updating DacFx dependency to take a couple bug fixes, namely for a bug that prevents applying a schema compare result to a database, if that result includes Edge/Streaming objects. (Fixes https://github.com/microsoft/azuredatastudio/issues/13246)
> Update tools service to .61

- extensions/mssql/config.json
Main change since last Tools Service version:
* Updating DacFx dependency to take a couple bug fixes, namely for a bug that prevents applying a schema compare result to a database, if that result includes Edge/Streaming objects. (Fixes https://github.com/microsoft/azuredatastudio/issues/13246)
> Updating to latest SQL Tools Service (.61) to take DacFx fix

- extensions/arc/src/localizedConstants.ts
- extensions/arc/src/ui/dashboards/miaa/miaaComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
Changed to follow resource deployment validation message. 
Current
Fix
> Changed cores validation message

- extensions/arc/src/test/mocks/fakeAzdataApi.ts
- extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts
- extensions/azdata/src/api.ts
- extensions/azdata/src/azdata.ts
- extensions/azdata/src/typings/azdata-ext.d.ts
This PR fixes #13609 
When pressing save, edit command takes engine version to add as an azdata argument.
> Added engine version argument to edit command. 

- src/sql/workbench/contrib/query/browser/keyboardQueryActions.ts
Fixes the issue where columns shift left when there is no content
> Fix empty column issue

- src/sql/workbench/contrib/notebook/browser/notebook.css
* add right padding to action item
* remove extra line and add space
This PR fixes #13607
> add right padding to notebook toolbar action item (#13640)

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/common/uiConstants.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
This PR fixes #13627 and #13580.
This PR updated the Import UI labels to be non-bold, distance between each row is increased and labels/text boxes width is updated. This is to match other existing UIs.
Also, this PR updated the dialog title and placeholder text for project location.
Older Import UI:
After this PR:
Original mockup:
> Update Import UI to match other UIs

- src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
This PR addresses issue: #13304
We will only change the grid data if we notice that the schema for the first row is not in order. If it is then we order each row based on the schema.
**Updated grid view after papermill execution (same column values 👍 )**:
> Fix notebook unordered grid values after papermill execution

- src/sql/workbench/contrib/notebook/browser/turndownPluginGfm.ts
- src/sql/workbench/contrib/notebook/test/browser/htmlMarkdownConverter.test.ts
Addresses #13681 
Prevent exception when tHead doesn't exist at the table node. That's a specific error case, so being more defensive.
> Prevent Table from Disappearing due to exception when looking for tHead

- src/sql/workbench/contrib/query/browser/keyboardQueryActions.ts
Fixes issue with pasting query and results in Teams as well as in ADS notebooks.
Teams issue: This was happening due to missing tr tag at the start of every row from 2nd row in the table.
Notebooks issue: Pasting it in text cell wasnt actually showing the markdown string and if user clicks away from the cell, it disappears. This was weirdly happening because of th tags. In Kusto explorer, they use the td tags even for header and it works fine, so I am using the same.
> Fix issue with pasting results in Teams

- extensions/schema-compare/src/schemaCompareMainWindow.ts
Previously, schema compare used table headers for the source and target names, which was a little hacky just to get the background a slightly lighter color. This changes them to be disabled inputboxes, which is the more appropriate component. I considered using text component to have more flexibility with the colors, but it doesn't have the built in overflow '...' for when the text is longer than the component width.
old: 
new:
> Switch schema compare to use inputbox instead of table headers

- build/azure-pipelines/common/publish.ts
warn logs to stderr which is causing the build pipeline to fail
> Use console.log for retry logging

- build/azure-pipelines/common/publish.ts
Port a74119038f711b77dc12f290e42b97a02e83dc57
warn logs to stderr which is causing the build pipeline to fail
> [Port] Use console.log for retry logging (#13722)

- src/sql/azdata.d.ts
DefinitelyTyped has strict linting requirements for their API definitions - cleaning this up here to make updating those easier.
> Lint azdata.d.ts

- extensions/arc/notebooks/arcDeployment/deploy.arc.data.controller.ipynb
- extensions/arc/package.json
Fixes https://github.com/microsoft/azuredatastudio/issues/13734
Port https://github.com/microsoft/azuredatastudio/commit/30289b4d14f354d7aec7e1d609042a61891f447b
This fixes an issue where the wrong environment variables were being used for the connected mode deployment causing it to fail.
Also bumped extension version to match new released version of the extension.
> [Port] Fix env var names for Arc deployment

- src/sql/workbench/contrib/dataExplorer/browser/media/connectionViewletPanel.css
- src/sql/workbench/services/objectExplorer/browser/serverTreeRenderer.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/12959
Changes the new server group look based on the review. This is just for server group and fixing the accessibility issue. The changing of colors in the dialog will be done separately in another PR.
Changes -
Follow up:
Do we want to show an expand arrow for empty groups? Current behavior doesn't show any expand arrow for an empty group, however vscode shows one for empty folders.
> Change server group look

- extensions/resource-deployment/src/ui/modelViewUtils.ts
- src/sql/workbench/browser/modelComponents/loadingComponent.component.ts
1. Make the loading component not valid while loading so that we block progress until the items are loaded
1. Improve the radio group component from resource deployment by making it load options from a provider in the background instead of blocking until it has the options.
Together these greatly improve the experience on pages which use option providers as not only will we show the loading spinner while loading the options but the user won't be able to move on until the options are loaded - so they don't end up with a value they didn't expect.
Fix comes from investigation into https://github.com/microsoft/azuredatastudio/issues/13699 - still unsure if there's an actual issue there but this should help make that a lot clearer.
> Make loading components not valid and improve RD radio group

- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/test/dialogs/publishDatabaseDialog.test.ts
- extensions/sql-database-projects/src/test/netCoreTool.test.ts
- extensions/sql-database-projects/src/test/projectTree.test.ts
- extensions/sql-database-projects/src/test/utils.test.ts
- extensions/sql-database-projects/src/tools/netcoreTool.ts
This PR adds the skipped tests back that were commented out to resolve the curious case of test failures, a few months back.
A few of those tests weren't updated as the product code changed. Fixed those.
As of now, there are 2tests that are still in skipped state- dataSource related tests (product code doesn't support data sources for now) and one createProjectFromDatabase UI test (renderer crash error).
> Un-skip and fix a few of the db projects tests

- extensions/arc/package.json
Deployments utilize features only available in the latest release so make sure we require that version
> Update required azdata versions

- src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
- src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
1. looks like the recent workspace and folder never worked before, I've been working on the data-workspace feature and noticed errors in the console and the empty recent list
2. the last opened information is simply not available right now, it meant to use the folder or files last modified time, which I don't think is correct, not to mention the fullPath parameter is not set properly. so I am showing the location along with the name just like the old welcome page and the vscode welcome page.
the corresponding vscode welcome page code: https://github.com/microsoft/azuredatastudio/blob/main/src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts#L377
Before:
After:
on Windows
on Mac
old welcome page:
> fix the recent list

- test/automation/src/code.ts
- test/automation/src/sql/notebook.ts
A notebook smoke test has failed to open a file a couple of times in the past. One theory is that there is something taking the focus away from the quick input element right before the 'enter' step. This PR adds active element information to the logs if the quick input element is not in focus.
> Log active element when notebook smoke test fails

- scripts/test-extensions-unit.bat
- scripts/test-extensions-unit.sh
With PR #10854, Sql-database-projects UTs were moved out to run just in canary until all the failures were fixed, with the use of new parameter (RUN_DBPROJECT_TESTS). But with PR #11179, the newly added parameter isn't respected anymore and the tests have been running in all pipelines regardless.
This PR cleans up the test scripts to remove the redundant parameter.
> Remove redundant parameter in test scripts

- extensions/azurecore/src/account-provider/interfaces.ts
- extensions/azurecore/src/account-provider/providerSettings.ts
- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
The main thing this is fixing is to use the correct graph endpoint for the Azure graph resource. It was `https://graph.microsoft.com` - but this resource is supposed to be for the Azure AD Graph (per https://github.com/microsoft/azuredatastudio/blob/main/extensions%2Fazurecore%2Fsrc%2Faccount-provider%2Finterfaces.ts#L75) and so the endpoint should actually be `https://graph.windows.net` per https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-request-differences#basic-requests.
While doing this I went ahead and added the MS Graph type as well though since AD Graph is deprecated and so we want to encourage using MS Graph when possible.
I also consolidated the IDs used for the resources - the china/germany ones were still left as their URLs which is something we just inherited …
> Use correct Azure graph endpoint & cleanup

- extensions/kusto/src/features.ts
- extensions/kusto/src/kustoServer.ts
- extensions/kusto/src/localize.ts
- extensions/kusto/src/main.ts
- extensions/kusto/src/telemetry.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13651
The loadMessageBundle call needs to happen in the same module that the localize call is being used - that's part of the key used to look up the strings and so having a single import like this doesn't work unless all the strings are in that file.
> Fix "not externalized correctly" warnings

- samples/serverReports/package.json
- samples/serverReports/src/constants.ts
- samples/serverReports/src/controllers/mainController.ts
- samples/serverReports/src/sql/startEvent.sql
- samples/serverReports/src/sql/stopEvent.sql
- samples/serverReports/yarn.lock
Before: "Server Reports" extension v0.2.2, TempDB tab is unable to start/stop XEvent sessions.  Task triggers query files to open into file windows instead of query windows, leading to some odd behaviors. (user is unable to close editor without closing application)
After: TempDB tab start/stop XEvent sessions tasks are run in the background with a queryprovider.
Changes:
- queries startEvent.sql and stopEvent.sql return a query result indicating success/error from try/catch
- tempdb tab tasks utilize a query provider to execute the queries instead of requiring further user interaction
- contention help link utilizes vscode.open instead of 'openurl' module to provide user with open/copy/cancel dialog
> Server Reports extension: fix for start and stop xevent sessions

- extensions/arc/package.json
- extensions/arc/package.nls.json
Arc - Update Postgres name length limit.  It was recently reduced from 12 to 11:
```
azdata arc postgres server create -n abcdefghijkl
Azure Arc enabled PostgreSQL Hyperscale server group name 'abcdefghijkl' exceeds 11 character length limit
```
> Arc - Update Postgres name length limit

- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/baselines/SSDTProjectAfterUpdateBaseline.xml
- extensions/sql-database-projects/src/test/baselines/SSDTProjectBaselineWithBeforeBuildTargetAfterUpdate.xml
- extensions/sql-database-projects/src/test/baselines/SSDTUpdatedProjectAfterSystemDbUpdateBaseline.xml
- extensions/sql-database-projects/src/test/baselines/SSDTUpdatedProjectBaseline.xml
- extensions/sql-database-projects/src/test/baselines/openSqlProjectBaseline.xml
- extensions/sql-database-projects/src/test/baselines/openSqlProjectWithAdditionalSqlCmdVariablesBaseline.xml
- extensions/sql-database-projects/src/test/baselines/openSqlProjectWithPrePostDeploymentError.xml
This PR fixes #13474. When opening a project created in SSDT in ADS, some updates are made to the project for it to work with the .NET Core build. Even though only a few lines were actually being modified, all the self closing tags were showing as a difference because a space was being removed by the xml serialization in ADS, resulting in many more differences that expected in source control. This fixes that by adding `whiteSpaceAtEndOfSelfclosingTag: true` as a parameter for the xml serialization in ADS.
before:
after:
> Fix whitespace differences in sqlproj

- extensions/arc/src/test/ui/components/filePicker.test.ts
- extensions/resource-deployment/src/test/services/platformService.test.ts
These were failing on windows due to mismatches in the separators and usage of vscode.Uri (which lower cases drive letters)
> Fix paths for tests

- extensions/resource-deployment/src/localizedConstants.ts
- extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts
This PR fixes #13679 and fixes #13719 
I have already extensively tested this change locally and I found 1 bug: Table 'withValidation' does not work. @Charles-Gagnon  what can be a potential fix for this issue?  
@ranasaria and @Charles-Gagnon, 
Please run this branch locally to see if it has fixed all the other edge cases. If not then please report the issues to this PR.
Initial State when a tool is not installed: (@Charles-Gagnon, @ranasaria   shouldn't this be an error message?)
If you click next without installing the tool:
If you click install button:
Once the tool installed: 
When you click the next button:
> Fixed the stray validation error message in Resource Deployment wizard

- extensions/data-workspace/src/test/dialogs/newProjectDialog.test.ts
- extensions/data-workspace/src/test/dialogs/openExistingDialog.test.ts
Marking these as unstable because they aren't consistently passing. Will investigate later today. These two tests have been failing because of validation errors such as:
- "Validation should fail because the selected workspace file already exists"
- "Validation should pass because the parent directory exists, workspace filepath is unique, and the file extension is correct"
> mark a couple data workspace tests as unstable

- extensions/notebook/src/jupyter/jupyterController.ts
This PR address part of https://github.com/microsoft/azuredatastudio/issues/9067.
Added "." as a trigger character so that the Intellisense suggestions list will be shown when user types "." while using Python kernel.
> Notebooks: Fix "." not showing Intellisense suggestions list

- src/sql/workbench/contrib/notebook/browser/outputs/renderers.ts
Fixes #13827.
Taking the logic from the `renderImage()` method, and clearing out content regardless. This is a longstanding bug that we've had with rendering SVG images.
Result:
> Notebooks: Fix duplicate SVG rendering

- extensions/data-workspace/src/dialogs/dialogBase.ts
- extensions/data-workspace/src/dialogs/openExistingDialog.ts
- extensions/data-workspace/src/test/dialogs/dialogBase.test.ts
- extensions/data-workspace/src/test/dialogs/newProjectDialog.test.ts
- extensions/data-workspace/src/test/dialogs/openExistingDialog.test.ts
This removes the @UNSTABLE@ from the tests marked as unstable in #13822. I wasn't able to repro the failures locally, but I suspect the tests were flaky because they were creating a file and the validation for it existing wasn't always working. The changes in this PR: 
- stub the file existing function instead of actually creating files and checking if they exist
- change the validation tests to only call new workspace validation instead of overall validation, since the tests are only meant to validation that anyway
> Fix unstable data-workspace tests

- build/azure-pipelines/win32/sql-product-build-win32.yml
the unstable test pipeline has been failing for a long time due to the unstable unit test timeout, I noticed even the stable test step has also been commented out by Anthony due to the same reason.
I will investigate the timeout issue later, now, lets unblock the other unstable test run. we don't actually have any unstable unit test.
I have verified after this we can get the unstable integration test running as expected: pass with issues. https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=87127&view=results
> comment out the unstable unit test step

- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.css
This compacts the text cell by 14px on top and bottom.
_screenshot showing recent changes_
This PR is for #13810
> Removed padding-top / bottom declarations for text cell 

- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.css
Fixes #12509. The "always center tables" bit is something we won't be addressing, but this is for table alignment issues. We were hardcoding left text-align for all tables, even though our table headers/row/cells render as left text-align regardless. This broke things like the following:
```
| Left Align | Right Align | Center |
| :- | -: | :-: |
| Stretched | Gaussian | .843 |
| Almost 100 | Is it?  | 99.99 |
```
Which should look like this:
| Left Align | Right Align | Center |
| :- | -: | :-: |
| Stretched | Gaussian | .843 |
| Almost 100 | Is it?  | 99.99 |
And in ADS:
> Notebooks: Stop forcing left text align on tables

- extensions/integration-tests/setEnvironmentVariables.js
- extensions/integration-tests/src/test/notebook.test.ts
We had different connection logic for this sole integration test vs. the other tests in the file, but given other refactorings in this file, this change is no longer needed. Because it was unstable for so long, other tests look to have been fixed up, but this one never was.
Executed an unstable test build, and verified that it succeeded.
Oh, and fixed a minor typo in the process 😄
> Fix Unstable Notebook Test

- extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts
- src/sql/base/browser/ui/selectBox/selectBox.ts
Generating events for select boxes only when the select box value is changed.
This PR fixes #13812 
For some reason, I was noticing a trailing value in the events generated. 
By trailing value, I mean, the value that was last selected and not the current one.
For example:
if A is the initial value and the user changes it to B, the event returned A instead of B
> Added fix for the infinite page refresh in resource Deployment tools page

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/common/dataWorkspaceExtension.ts
- extensions/data-workspace/src/dataworkspace.d.ts
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
- extensions/sql-database-projects/src/models/api/import.ts
- extensions/sql-database-projects/src/test/dialogs/createProjectFromDatabaseDialog.test.ts
Fixes #13799. This makes the new workspace inputbox editable for the create project from database dialog, like what was done in #13508 for the data workspace dialogs.
Default location for new workspace is in the new project folder
validates that the .code-workspace file extension is there
validates location exists
also added validation that there isn't already a folder with the same project name at the selected location
> Make new workspace inputbox editable in Create project from database dialog

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/services/workspaceService.ts
- extensions/data-workspace/src/test/workspaceService.test.ts
This PR fixes #13448. Following message pops up if a project is already opened:
> Add an informational message when a user tries to open an already opened project

- extensions/data-workspace/src/dialogs/dialogBase.ts
- extensions/data-workspace/src/dialogs/newProjectDialog.ts
- extensions/data-workspace/src/dialogs/openExistingDialog.ts
- extensions/data-workspace/src/test/dialogs/dialogBase.test.ts
Updating the new workspace validation in the data-workspace extension to throw errors to make the code more reusable like what was done in #13842
> Update new workspace validation to throw errors to make code more reusable

- extensions/data-workspace/package.json
- extensions/data-workspace/package.nls.json
- extensions/data-workspace/src/common/workspaceTreeDataProvider.ts
- extensions/data-workspace/src/main.ts
This PR fixes #13793
Changes are only in data-workspace extension.  Adds a command hidden from the command palette and visible in the menu of the workspace.  Command calls the native VSCode command to close the workspace (workbench.action.closeFolder) for consistency with the action in the File menu.
When no workspace is open, no change visible:
When a workspace is open, new section in menu with item to close workspace:
> adds close workspace to data workspace view menu

- extensions/notebook/src/jupyter/serverInstance.ts
- extensions/notebook/src/test/model/serverInstance.test.ts
This PR removes the find free port step while starting a Jupyter server. Instead, we will get the port number from the URL returned by the Jupyter server. Previously on Windows, it took >2s to find a free port and a port is not required to start the server. On average, removing this step improves Jupyter server start time by 2.3 seconds (average taken from running smoke test that starts a Python kernel 100 times).
> Notebooks: Improve Jupyter server start time

- extensions/data-workspace/src/dialogs/openExistingDialog.ts
- extensions/data-workspace/src/test/dialogs/openExistingDialog.test.ts
This PR fixes #13857. The _workspaceFile variable wasn't getting updated when the text in the inputbox changed, only when the file picker was being used. Since there isn't a reason to have intermediate variables to store the projectFile/workspaceFile, I got rid of them and now the value in the fileInputBox is used directly.
> Fix editing workspace inputbox in open existing dialog not working

- build/azure-pipelines/linux/sql-product-build-linux.yml
we had 3 canary build failures due to archive logs steps, there are not enough information about why it happened, I am separating it so that we have one zip per folder, hope it will make it easier to spot the issue. I am not sure whether this will actually fix the problem
> archive logs step

- extensions/resource-deployment/src/ui/modelViewUtils.ts
In a previous change we had stopped populating the options.values field for a dropdown from options sources. This change adds it back.
This PR fixes #13789
> populate drop down options values from options source

- samples/sqlservices/src/controllers/mainController.ts
- src/sql/workbench/browser/modelComponents/componentBase.ts
I noticed a weird border issue when I was working on a custom button backed by a div container component
and it is because the css styles are also being applied to the component wrapper by the deleted code, the element reference passed in is to the component wrapper.
for the components that needs the styles, they already have it included in the component template, for example, text component, div container, flex container. 
with the code removed, this is how it looks now.
> remove update style

- src/sql/base/browser/ui/panel/panel.ts
- src/sql/workbench/contrib/query/browser/keyboardQueryActions.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
- src/sql/workbench/contrib/query/browser/queryEditor.ts
- src/sql/workbench/contrib/query/browser/queryResultsEditor.ts
- src/sql/workbench/contrib/query/browser/queryResultsView.ts
This PR fixes #13661 
added a new action(win+shift+n) to toggle focus between the query editor and results pane
> toggle focus between query and results

- extensions/notebook/src/protocol/notebookUriHandler.ts
- src/sql/workbench/contrib/notebook/test/electron-browser/notebookModel.test.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR enables parameterization via Notebook URI as shown below.
The implementation covers how a user opens a new notebook via azuredatastudio://URI that contains parameters. 
ex. 
`URI with Parameter cell: azuredatastudio://microsoft.notebook/open?url=https://raw.githubusercontent.com/VasuBhog/AzureDataStudio-Notebooks/main/Demo_Parameterization/Input.ipynb?x=1&y=2`
Parameters will be parsed from the URI, then transformed to string format to then be added as a new cell to the notebook. The new cell will either be added as a _parameters tagged cell_ or as _injected parameters cell_ depending on if there is already a parameter cell in the notebook.
> Enable Parameterization via Notebook URI

- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
- src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/8978.
Left: line height = 1
Right: original (ADS version 1.25.1)
One thing to note:
1. Set line height to 1
2. Create new text cell
3. Type "hello"
4. Hit Enter
5. Type "world"
6. Exit cell
As shown in the GIF, space is added between "hello" and "world" upon exiting the cell. This is because they are converted to two separate p Elements and each element has margin space around it. In order to keep them as one p Element, you need to hit Shift+Enter instead of Enter.
**Question** - do we want to customize margin space between p elements as well?
> Add setting to customize notebook markdown preview line height

- .github/label-actions.yml
Update log gathering instructions to include getting the console logs. Extensions commonly log errors to console logs but this isn't written to disk anywhere and so for the time being in order to ensure we have all the information we need just including getting those as well. 
At some point we should :
- Consider logging extension console messages to disk like the main process does
- Creating a command that gathers these logs for customers and zips them up to reduce the manual effort required
> Update log gathering instructions

- test/automation/src/sql/notebook.ts
This PR changes the way we open notebook files in smoke tests to clicking on the filename in the quick input result list. The old way (typing the filename into quick input and hitting enter) sometimes failed due to the quick input box no longer being in focus.
> Fix notebook smoke tests: change openFile method implementation 

- src/sql/workbench/contrib/profiler/browser/profilerActions.ts
- src/sql/workbench/contrib/profiler/browser/profilerEditor.ts
This PR fixes #12171
also rearrange the actions to move 'clear data' next to the start/stop group
> add confirm prompt for some profiler actions

- src/sql/platform/accounts/common/accountStore.ts
Somehow my ADS instance got in a state where it would never load the Azure Accounts upon startup.
The root issue that was happening was that somehow the memento got an empty object inside it - which then caused line 44 to throw an exception when it tries to access the property `account.key.providerId` (since key was undefined).
There's three fixes here : 
1. Log the exception. There was nothing in the logs when this failed originally, now we'll at least print it to the console for debugging purposes
2. Call cleanupDeprecatedAccounts before fetching the accounts when fetching by providerId like we already do for fetching all accounts. It would be nice if this wasn't necessary but until we know for sure how the memento is getting this invalid object then this is the safest way to handle it …
> Fix account store silently failing

- extensions/integration-tests/src/test/dacpac.test.ts
Well that was fast : 
```
1) Dacpac integration test suite @DacFx@
Import and export bacpac:
TypeError: Cannot read property 'rowCount' of undefined
at Object.assertDatabaseCreationResult (E:\mssqltoolsagentworkspace\97\s\extensions\integration-tests\out\test\utils.js:244:19)
at async Context.<anonymous> (E:\mssqltoolsagentworkspace\97\s\extensions\integration-tests\out\test\dacpac.test.js:79:13)
```
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=89517&view=logs&j=bfccef3f-45d4-504d-9a7f-a8a74922e6bf&t=6a7a61df-4b52-52e2-d763-2058c7ca42b4
> Disable dacpac integration tests

- src/sql/base/browser/ui/panel/panel.ts
This PR fixes #13959
How it works previously:
the tabindex for the tab container is set to 0, (means it can receive keyboard focus by tabbing or mouse click), and the individual tab headers have tabindex set to -1 (only focusable programmatically), when the container gets focus, while handling the focus event, it will call header.focus to set the focus to individual header.
what is the problem:
when tabbing backward, the previous focusable element is the tab container, based on above description, it will set focus to the current tab header, and the focus is trapped here.
fix:
instead of letting the container to handle where the focus should go, I am setting the tabindex of the active tab to 0 and other tab's tabindex to -1, so that the tabs maintain the tab index by themselves.
> fix focus trap issue

- extensions/azurecore/src/azureResource/tree/connectionDialogTreeProvider.ts
- extensions/azurecore/src/azureResource/tree/flatAccountTreeNode.ts
This PR fixes #13757 
1. limit the impact of the error to the problematic account and show the accounts without issues
2. updated the error message slightly to tell user where to refresh the account
3. show the errors with a notification and provide an action to go to the accounts dialog.
this is how it looks in case of error now:
> handle azure account load error

- extensions/mssql/config.json
Primary update here is to get the new SqlClient version (2.1.1) that contains the Mac Kerberos fix as well as some things for Always Encrypted.
Will be doing thorough testing with private builds before merging this in.
> Update SqlToolsService to .68 (SqlClient 2.1.1)

- extensions/arc/package.json
- extensions/resource-deployment/package.json
No big changes in this release so shouldn't be anything needed to update on our side. Just keeping the tool version in sync with the latest release.
> Update azdata tool requirements to 20.2.6

- extensions/data-workspace/src/test/dialogs/openExistingDialog.test.ts
This test has been failing intermittently. The fix is similar to what was done in #13824 to stub the file existing function  instead of actually creating files and checking if they exist. Those tests have been passing, so hopefully this fixes this test too.
> Fix data workspace test

- src/sql/workbench/services/queryHistory/common/queryHistoryServiceImpl.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13982
> Don't capture query history events until service is started

- extensionsGallery-insider.json
- extensionsGallery.json
I already updated this in the published gallery files - this is just pushing that back into the branch. 
(At some point it'd be nice to have the check I added a while back download the VSIX and verify that the engine versions match)
> Match engine version for import to one in package

- samples/serverReports/package.json
bumps from 0.2.2 to 0.2.3, will be opening a PR for the marketplace galleries
related to https://github.com/microsoft/azuredatastudio/pull/13565
> increment version for fixes to tempdb xevents

- extensions/notebook/src/dialog/configurePython/configurePathPage.ts
- extensions/notebook/src/dialog/configurePython/configurePythonWizard.ts
- extensions/notebook/src/dialog/pythonPathLookup.ts
- extensions/notebook/src/jupyter/jupyterController.ts
- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
- extensions/notebook/src/test/python/configurePython.test.ts
Noticed were getting some unhandled promise rejections from some of the python unit tests due to a mocked object not being passed an OutputChannel reference. Rather than fix that undefined error directly, I opted to remove the usage of OutputChannel from PythonPathLookup since we can replace it with a console.log() statement instead. Also scoped down the usage of the method call that was producing the unhandled promise error, so that we don't get any more noise in the tests.
> Remove unnecessary OutputChannel reference from PythonPathLookup class.

- extensions/notebook/src/dialog/configurePython/configurePathPage.ts
- extensions/notebook/src/dialog/configurePython/configurePythonWizard.ts
- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
This PR fixes #13215
We throw an error during python installation if we're on Windows and Python is already running out of the specified install location. This is because Windows will throw file permission errors if we try to overwrite files that are currently in use. This same error was getting thrown when trying to install new pip packages after clicking on a notebook kernel, but we can install new pip packages without encountering any of those file permission errors. So I added a flag to skip the python-is-running check if we only want to install pip packages during setup.
> Skip checking if python is running when only doing package upgrades during python install.

- extensions/arc/src/localizedConstants.ts
- extensions/arc/src/ui/dashboards/postgres/postgresParametersPage.ts
Currently if you close the dashboard and re-open it the table will be blank since it never reloads the data into the table when the settings have already been loaded (it was only doing that when the connect button was clicked).
Also localized a few strings that weren't I noticed while working on this.
> Fix parameters page to show parameters if settings already loaded

- extensions/arc/src/models/controllerModel.ts
- extensions/arc/src/models/miaaModel.ts
- extensions/arc/src/models/postgresModel.ts
- extensions/arc/src/test/mocks/fakeAzdataApi.ts
- extensions/arc/src/test/models/controllerModel.test.ts
- extensions/arc/src/ui/dashboards/miaa/miaaComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresParametersPage.ts
- extensions/azdata/src/api.ts
- extensions/azdata/src/azdata.ts
- extensions/azdata/src/test/api.test.ts
- extensions/azdata/src/test/azdata.test.ts
- extensions/azdata/src/test/testUtils.ts
- extensions/azdata/src/typings/azdata-ext.d.ts
This adds a new function - acquireLoginSession. When this is called it will create a session and (if there are no other active sessions) set the context such that only calls made for that specific session are allowed to execute. All other commands are queued up until the session is disposed (released) at which point it will start executing those commands (creating new sessions as requested).
There's still a lot of polish that needs to go into this - as well as tests. Getting this out now for early feedback on approach and any immediate issues seen.
This is also fixing a couple of places where we weren't passing in the additional env vars to calls such as MI edit. These additional vars need to be set to the current controller vars so that we correctly set the kube config vars when …
> Add acquireLoginSession API for Azdata

- src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
We already add the items on the extension host side (https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/api/common/extHostModelView.ts#L1593) and so this should be unnecessary as far as I can tell. 
And getting rid of this gets rid of all the "Could not find ItemDescriptor..." warnings that were showing up - the reason being that when the property was set the child component may have not been created yet and so wasn't in the model store. addItem from the extension host side will ensure that the component is created before it adds it to the items of the table container.
> Remove unnecessary addItem from DeclarativeTable component

- extensions/notebook/src/common/utils.ts
- extensions/notebook/src/jupyter/jupyterSessionManager.ts
- extensions/notebook/src/jupyter/serverInstance.ts
- extensions/notebook/src/test/common/utils.test.ts
- extensions/notebook/src/test/model/serverInstance.test.ts
This PR changes some of the configure Jupyter server steps from async to sync to improve the Python kernel loading time. On Windows, the loading time decreased by 1.3 seconds on average. (No difference seen on Mac as the configuration step only took a couple of ms on Mac).
The configuration steps are creating and copying small folders/files. The abundance of async calls likely caused the configuration step to sometimes take up to 3 seconds on Windows while other times only taking <1 second.
> Change configure Jupyter server steps from async to sync

- src/sql/workbench/contrib/notebook/browser/cellViews/media/markdown.css
- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
Currently if you type only tab characters into a rich-text markdown cell, the cell itself will collapse to a height of 1px when you click away. This is because we set a minimum line-height for the preview cell's contents, but not the cell itself. Ideally we should be displaying the "Double-click to edit" placeholder when we have rich-text whitespace like this, but that's proving to be a bit complicated since rich-text "whitespace" doesn't always use actual whitespace characters. Typing a bunch of tabs results in the output containing a bunch of angle brackets instead ("> > > > > >"), which looks like valid text to the rest of the notebook code. This is a partial fix for now since it at least makes the cell clickable, but the markdown preview will still look blank on the page.
> Use a minimum cell height to prevent whitespace markdown cells from becoming invisible.

- src/sql/platform/dashboard/browser/interfaces.ts
- src/sql/workbench/browser/modelComponents/modelStore.ts
This fixes the occasional `can't read property 0 of undefined` errors that would show up occasionally. Sometimes the validations would be called for components that weren't actually in the store yet so the mapping table didn't have them. But we don't even need to do that in the first place - all we care about is the component ID so it doesn't make sense to look up the mapping anyways. 
I didn't dig into more of the reason why the validations were being called early in the first place so there may still be some underlying issues here. But this should at least expose them more directly instead of just as this original generic error.
> Fix validation errors

- src/sql/workbench/browser/modelComponents/modelComponentWrapper.component.ts
1. Registered the onLayoutRequested handler to be disposed when the wrapper is destroyed
2. Removed the theme update handler - I tested it out and didn't see any change in things using the wrapper components. And in general we should have basic background colors like that be at a higher default level - not at the wrapper level (or overridden by the components themselves if needed). So just removing it since it shouldn't be necessary @llali Do you have any context on why this was put there in the first place (you worked on this stuff early on right?)
> Cleanup model component wrapper event handlers

- src/sql/platform/theme/common/styler.ts
- src/sql/workbench/browser/modelComponents/button.component.ts
We were creating a new button styler every time the icon was changed but never getting rid of the old one until the object was disposed. This likely wasn't much of an issue since it'd be uncommon for someone to be updating the icon much but this still should be doing the right thing. 
This could probably be made slightly more efficient if we only updated the styler if it's going to be switching modes but that should be a pretty minor thing so I decided not to do that extra work. 
Also fixed an issue I noticed where if a button with an icon had that icon removed it wouldn't go back to the original style - it'd still be using the style applied when the icon was updated.
> Clean up button component disposables

- extensions/admin-tool-ext-win/package.json
- extensions/admin-tool-ext-win/src/telemetry.ts
- extensions/admin-tool-ext-win/yarn.lock
- extensions/dacpac/package.json
- extensions/dacpac/src/telemetry.ts
- extensions/dacpac/src/wizard/dataTierApplicationWizard.ts
- extensions/dacpac/yarn.lock
- extensions/data-workspace/package.json
- extensions/data-workspace/src/common/telemetry.ts
- extensions/data-workspace/yarn.lock
- extensions/schema-compare/package.json
- extensions/schema-compare/src/telemetry.ts
- extensions/schema-compare/yarn.lock
- extensions/sql-assessment/package.json
- extensions/sql-assessment/src/telemetry.ts
- extensions/sql-assessment/yarn.lock
- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/common/telemetry.ts
- extensions/sql-database-projects/yarn.lock
No functional changes - but there is an update to the latest vscode-extension-telemetry package. Verified that events are still being sent as expected with the latest update.
> Update ads-extension-telemetry package to official Microsoft org version

- extensions/resource-deployment/package.json
Adding the cloud tag to BDC deployment so that it appears under the cloud category.
> Adding cloud tag to BDC resource

- extensions/azurecore/src/azureResource/azure-resource.d.ts
- extensions/azurecore/src/azureResource/utils.ts
- extensions/azurecore/src/azurecore.d.ts
- extensions/azurecore/src/extension.ts
- extensions/machine-learning/src/test/stubs.ts
- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/models/strings.ts
- extensions/sql-migration/src/wizard/createMigrationControllerDialog.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
- extensions/sql-migration/src/wizard/wizardController.ts
- Fixed GetMigrationController
- Added createMigrationController and getControllerAuthKeys API in azure core.
- Added typings for Migration Controller
- Fixed database backup page validation logic
- Added IR page with create controller
Some Screenshots:
1. You start with no migration controller present.
2. You create a new migration controller. (setup with default does not work).
3. You fill the form and create the controller by pressing submit.
4. Once the controller is created you get the auth keys to register the local node to controller.
5. Finally when IR is registered the dialog will look something like this. 
6. Once you press done you are sent back to IR page.
> Adding Integration Runtime Page to Migration extension wizard

- extensions/resource-deployment/src/common/utils.ts
- extensions/resource-deployment/src/services/resourceTypeService.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14024
The root issue here is that we were modifying the extension contribution directly - which involved adding new properties to it. These properties were internal types and thus had references to things like tree views and much more complex objects than the original JSON definition.
This is a problem though because some VS Code implementations (such as withProgress) pass the entire extension contribution object over the RPC layer to the main thread - and so when it tried to convert that object to a string for passing over the RPC layer it failed converting these complex types since they had a circular reference loop.
This problem only showed up though after we parsed the extension contribution - which was only triggered by …
> Fix stringify error from resource deployment extension

- src/sql/platform/dashboard/browser/interfaces.ts
- src/sql/platform/model/browser/modelViewService.ts
- src/sql/workbench/api/browser/mainThreadModelView.ts
- src/sql/workbench/api/common/extHostModelView.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
- src/sql/workbench/browser/modelComponents/componentBase.ts
- src/sql/workbench/browser/modelComponents/loadingComponent.component.ts
- src/sql/workbench/browser/modelComponents/viewBase.ts
- src/sql/workbench/test/electron-browser/api/extHostModelView.test.ts
- src/sql/workbench/test/electron-browser/modalComponents/componentBase.test.ts
Improvement for https://github.com/microsoft/azuredatastudio/issues/13905
One of the perf issues we were having was that when adding multiple items to containers we were adding each item separately. This meant not only many more calls across the RPC layer but also the worst impact was that every time addItem was called we'd do a detectChanges on the Angular change ref for the table - and when adding hundreds of components like in a table this quickly bogged everything down.
So the fix is just to make it so that all the items are batched up and added all at once. There's no functional change here aside from that - we already had addItems on the internal implementation (it was just adding each item one by one previously). 
There's still some work to do on the perf side for #13905 - it still …
> Add multiple ModelView child items at once

- src/sql/workbench/browser/modelComponents/tabbedPanel.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14073
This would throw if there was a single tab registered and then another one was added (`this._itemIndexToProcess - 1` would be -1)
Undefined is the expected value for the first iteration of the loop - we'll update the currentGroup as we go through the items.
> Fix tabbed panel error

- product.json
- src/vs/code/electron-sandbox/issue/issueReporterMain.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13587
This logic pulls the base URL from either product.json or the extension package.json - but it was only checking the product.json string to see if the query prefix should be a & or a ? - and so our URL (which had a ? in it) caused it to always use a & as the prefix which wouldn't work with extension URLs which typically are just going to be something like `https://github.com/Microsoft/azuredatastudio.git`
Also removed the custom label from our issues URL - we don't even have that label defined so it wasn't doing anything anyways.
> Fix issue reporter URLs for extensions

- src/sql/workbench/browser/modelComponents/viewBase.ts
Nothing breaking here - but it would show the warnings in the console for the components that this happened for and it's good to have for perf reasons anyways.
> Skip adding empty list of items

- extensions/data-workspace/package.json
- extensions/sql-database-projects/package.json
This PR fixes #14085. The New and Open existing icon buttons stopped showing after some refactoring was done in https://github.com/microsoft/azuredatastudio/pull/13809. This PR adds them back and also moves "Create Project From Database" to be in the same group as Refresh.
Previously:
Now:
> fix projects view title commands

- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/browser/modal/modal.ts
- src/sql/workbench/contrib/jobManagement/browser/jobActions.ts
- src/sql/workbench/contrib/jobManagement/browser/jobHistory.component.ts
- src/sql/workbench/contrib/jobManagement/browser/jobStepsView.component.ts
- src/sql/workbench/contrib/jobManagement/browser/jobsView.component.ts
- src/sql/workbench/contrib/jobManagement/browser/notebookHistory.component.ts
- src/sql/workbench/contrib/jobManagement/browser/notebooksView.component.ts
- src/sql/workbench/contrib/telemetry/common/telemetry.contribution.ts
- src/sql/workbench/services/dialog/browser/wizardModal.ts
This is part of some cleanup work I've been meaning to do for a while just to get the stuff in TelemetryKeys more properly organized.
I also updated the agent stuff to use the AdsTelemetryService to align to the common schema we're using elsewhere. This does mean that we won't be able to easily correlate events from before this change to ones after - but given that we don't actually use these events for any reporting currently I don't think it's a huge deal to do this now.
> Clean up telemetry keys

- src/sql/workbench/contrib/notebook/browser/cellViews/media/markdown.css
- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.css
https://user-images.githubusercontent.com/12279161/106187691-cc736e80-615a-11eb-9d50-c4bdfb41ec64.mov
Sets minimum height to text cell element so whether empty or occupied with a single line of content, the container is the same height.
Attached MOV of UI in action.
> Notebook - text cell - minimum height fix

- extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts
- extensions/resource-deployment/src/main.ts
- extensions/resource-deployment/src/services/resourceTypeService.ts
- extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts
- extensions/resource-deployment/src/ui/resourceTypeWizard.ts
- extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts
Previously the Arc dashboards had a feature where when you clicked a button on the dashboards to deploy a new instance it would open up the Resource Deployment wizard with only certain arc-related options shown.
But a recent change put MIAA under a new overall MI resource type and so we no longer can filter down to just Arc related items - it only allowed filtering to the resource type granularity.
This PR adds in additional filtering capabilities for the optionValues to only display certain values for those as well.
> Add resource deployment filtering by option values

- src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14082
When setting data to an empty array we weren't properly checking for that and so ended up with _data being undefined which caused an error in the Angular template
> Fix error when rendering empty declarative table

- extensions/resource-deployment/src/services/resourceTypeService.ts
- extensions/resource-deployment/src/ui/resourceTypeWizard.ts
The wizard wasn't filtering the options when setting the initial model so it was still choosing the first one in the list - even if that was filtered out. 
Also cleaned up an unused param while I was looking at this.
> Fix deployment wizard for filtered options

- src/sql/workbench/services/notebook/browser/models/cell.ts
This PR fixes error shown when ADS notebook is opened in Jupyter:
The transient field in outputs of type 'display_data' was not being deleted before serialization.
> Notebooks: Fix Notebook validation Error when opened in Jupyter

- src/sql/workbench/browser/modelComponents/componentBase.ts
This PR fixes #14112
this code was removed by me in https://github.com/microsoft/azuredatastudio/commit/ab6d11596e659578f95600119dfe6b24acdddcb8 after observing weird border issue, it is setting the styles on the angular elements, I am reverting my changes for now and will work on a long term solution so that it is actually set on the elements.
> revert the changes

- extensions/arc/package.json
- extensions/azdata/package.json
- extensions/resource-deployment/src/interfaces.ts
- extensions/resource-deployment/src/services/resourceTypeService.ts
Name could potentially be confusing since people may think that it's the name of this "sub type" instead of the name of the actual resource type that's already defined elsewhere. 
It might not be a bad idea to see if we can find a better name for resourceSubType too - this isn't really a sub type at all but rather just additional options on top of an existing type.
> Rename name field of resourceSubType to resourceName

- src/sql/workbench/contrib/notebook/test/electron-browser/notebookModel.test.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
Fixes #12011.
When we were converting cells, we weren't resetting the language property on the cell model. Therefore, it was possible for a text cell to be converted to a code cell, but still think that the cell's language was markdown.
https://user-images.githubusercontent.com/40371649/106345437-0335ab80-6265-11eb-91a4-f8beea94fef7.mp4
> Notebook Cell Conversion Language Fixes

- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
This PR fixes #14141. This dropdown shouldn't be editable since an existing database needs to be chosen.
> Update db dropdown in create project from database dialog to not be editable

- extensions/arc/src/ui/dashboards/postgres/postgresParametersPage.ts
- extensions/machine-learning/src/test/views/utils.ts
- extensions/notebook/src/test/common.ts
- extensions/notebook/src/test/managePackages/managePackagesDialog.test.ts
- src/sql/azdata.proposed.d.ts
- src/sql/platform/dashboard/browser/interfaces.ts
- src/sql/workbench/api/common/extHostModelView.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/sql/workbench/browser/modelComponents/declarativeTable.component.html
- src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14131
The issue here is that when rows were removed from the table by setting data it would cause Angular to destroy those components - and so they wouldn't be available once the table was re-rendered.
A fix could have been to recreate the components each time we set the filter - but that would very easily spiral out of control with unnecessary overhead. 
So instead I've added a function on the table to filter the rows - which is vastly more performant and has advantages such as keeping values that the user has already modified.
> Add setFilter to DeclarativeTableComponent

- extensions/sql-database-projects/src/models/project.ts
A couple awaits were missing which was causing the test "Should update .sqlproj with new sqlcmd variables" to fail intermittently.
> Fix intermittent sql project test failure

- src/sql/azdata.d.ts
- src/sql/workbench/api/common/sqlExtHost.api.impl.ts
This is primarily so that extension telemetry will be able to have the ADS version added (currently it only has the VS Code version), but extension authors may find it useful. 
Promoting it directly to azdata.d.ts since this is a very simple API and already has the precedent set by `vscode.version`
> Add version to azdata api

- extensions/notebook/src/book/bookTreeItem.ts
- src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookExplorerViewlet.ts
The tree item resource uri is used to apply file decorations when a notebook is modified. 
If the tree item is a book then the resource should be the book root, and if it's a notebook then it should be the the notebook's content path.
This PR fixes #13688
> Fix decorations for modified notebooks in Books View

- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
- extensions/notebook/src/test/python/jupyterInstallation.test.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14153
The issue here is that it's failing to build the wheel for cryptography > 3.2.1 - so for now just hardcode it to always install 3.2.1 if it doesn't detect the package already being installed.
Still need to investigate why there isn't a wheel already for the latest version of this package since previous versions had one.
> Use cryptography 3.2.1 for sparkmagic dependency

- extensions/arc/src/ui/dashboards/postgres/postgresDashboard.ts
- extensions/arc/src/ui/dashboards/postgres/postgresParametersPage.ts
Postgres parameters page is at a place to be visible after bug fixes. 
This PR 
1. Gives access to the parameters page on the postgres instance dashboard
2. Better placement to information bubbles
3. Adds Azdata sessions to edit calls
> Making the Postgres Parameters Page Visible 

- extensions/arc/src/ui/dashboards/postgres/postgresDashboard.ts
- extensions/arc/src/ui/dashboards/postgres/postgresPropertiesPage.ts
Postgres properties page is at a place to be visible. Has shown to update accurately. 
This PR
Gives access to the properties page on the postgres instance dashboard
Gives a max-width for the text boxes.
> Making the Postgres Properties Page Visible

- extensions/arc/src/ui/components/dashboardPage.ts
Saw this a couple of times - the PG dashboard container references stuff from the toolbar and so with the current ordering it would throw errors. Not the most ideal fix but as a quick solution this is fine - and it makes sense anyways since generally the toolbar would only reference container stuff when the buttons are clicked so having it go first is better anyways.
> Fix arc dashboard component order error

- extensions/notebook/src/book/bookModel.ts
- extensions/notebook/src/test/book/book.test.ts
- extensions/notebook/src/test/book/bookTocManager.test.ts
- Fix Windows failing unit tests.
- Change the missingFile error to show the name of the book and the missing file.
- Add the vscode show error message after I accidentally removed it.
- The test _should set notebooks trusted to true on trustBook_ is still failing on my side, but I'll create a new pr once I have the fix.
> Fix book tests on Windows.

- extensions/sql-database-projects/src/controllers/projectController.ts
From what I can see these are sending the raw error messages which could contain PII - removing them for now until logic can be added to sanitize them before upload.
> Remove error message properties from events

- src/sql/azdata.proposed.d.ts
- src/sql/workbench/contrib/notebook/test/stubs.ts
- src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR adds the multi_connection field to notebook metadata and moves the loading content metadata logic into a separate method in NotebookModel.
> Notebooks: add multi_connection field to notebook metadata

- src/sql/platform/instantiation/test/common/instantiationServiceMock.ts
- src/sql/workbench/contrib/notebook/test/electron-browser/notebookEditorModel.test.ts
- src/sql/workbench/contrib/objectExplorer/test/browser/serverTreeView.test.ts
- src/sql/workbench/contrib/query/test/browser/queryEditor.test.ts
- src/sql/workbench/services/accountManagement/browser/accountManagementService.ts
- src/sql/workbench/services/accountManagement/test/browser/accountManagementService.test.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
- src/sql/workbench/services/connection/test/browser/connectionDialogService.test.ts
- src/sql/workbench/services/connection/test/browser/connectionDialogWidget.test.ts
- src/sql/workbench/services/connection/test/browser/connectionManagementService.test.ts
- src/sql/workbench/services/insights/test/browser/insightsDialogController.test.ts
- src/sql/workbench/services/objectExplorer/test/browser/asyncServerTreeDragAndDrop.test.ts
- src/sql/workbench/services/objectExplorer/test/browser/dragAndDropController.test.ts
This fixes the `First service dependency of e at position 2 conflicts with 0 static arguments` warnings that would show up on launch.
What was happening here is that these services had non-injected parameters, but during normal runtime these services are created as part of the instantiation service stuff which doesn't know about those so it would throw out that warning (and then leave them as undefined).
I looked into it and turns out they were just used for injecting test objects into the services for mocking - during runtime we just defaulted to creating the objects if they weren't passed in. But that isn't needed as we can just use a mocked instantiation service to handle this for us. 
This isn't really fixing any actual functionality issue here but it's been annoying me ever since I …
> Fix service dependency startup warning

- extensions/notebook/src/book/bookTocManager.ts
Replace backlash to forward slashes when moving notebooks.
> Replace backlash when moving notebooks on windows

- extensions/notebook/src/jupyter/jupyterSessionManager.ts
Fixes #12357.
The `%cd` magic, which we run behind the scenes when starting a new Jupyter session, translates Windows-style paths in an interesting way if the Windows-style newlines are included at the end of the command.
e.g. `'C:\users\chlafren\Hello World'` actually becomes `'c:\Users\chlafren\Desktop\Hello World '` (notice the extra space), resulting in Windows APIs complaining that that location doesn't exist.
In other places, we strip out the `\r` before sending it to Jupyter. Here, we're crafting a set of commands.
> Notebooks: Fix Current Directory when Folder has Space

- extensions/arc/src/localizedConstants.ts
- extensions/arc/src/models/miaaModel.ts
- extensions/arc/src/models/resourceModel.ts
- extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13373
3 main scenarios here : 
Connect with a previously saved connection - loads table automatically
Connect but either no saved connection or an error occurs during the connection - display button for user to connect
Connect but no external endpoint configured - display text informing user that we can't show the databases
> Add connect button to MIAA dashboard

- extensions/arc/src/ui/dashboards/postgres/postgresParametersPage.ts
The search function was case sensitive which is not seen in portal.  
Edited to not care about case typed into search textbox.
> Search function to be case insensitive 

- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
- src/sql/workbench/browser/modelComponents/viewBase.ts
Fix for issue described in https://github.com/microsoft/azuredatastudio/pull/14198
I didn't track down why/if this actually changed with https://github.com/microsoft/azuredatastudio/pull/13842 - but the issue here is that addItem/addItems/insertItem were adding the items immediately to the container - but withItems was delaying that until the container component was created on the main thread side - at which point it would then go create and add the ItemConfigs and add them to the container.
But because this wasn't done first we would have the addItem queued up first and thus it would try to add that first and then afterwards go add all the defined itemConfigs.
I vaguely recall that when I added the whole "initial" actions stuff in https://github.com/microsoft/azuredatastudio/pull/13317 I …
> Fix ModelView addItem/withItem ordering

- .github/workflows/ci.yml
Latest vscode merge broke some tests in Linux CI.  I'm going to turn off for a day or two while investigating various regressions from the merge.
> Turn off Linux in CI build

- src/vs/workbench/contrib/remote/browser/remote.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14240
@kburtram We should be able to also just remove the dependency on the debug service if you think this would be needed for any of the web stuff. But I figured we can start with this and then do more surgical removals later if needed.
> Remove AutomaticPortForwarding service

- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
- src/sql/workbench/browser/modelComponents/viewBase.ts
(cherry picked from commit 6f192f9af52bfa78e228ea39c6d11033c8922a88)
Fixes https://github.com/microsoft/azuredatastudio/issues/14207
Items added to a ModelView component via addItem that already had items added to it via withItems were incorrectly showing up before the withItems component
> [Port] Fix ModelView addItem/withItem ordering (#14205)

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/project.test.ts
This PR fixes #14252. I think this got broken when awaits were added in #13114 for addDatabaseReferenceToProjFile. I added a test that would have caught this.
> fix system db references going away when project target platform is changed

- product.json
The previous vscode merge brought our vscode compat level up to 1.51
> Bump vscode version product.json

- src/sql/azdata.proposed.d.ts
- src/sql/workbench/contrib/charts/browser/chartTab.ts
- src/sql/workbench/contrib/charts/browser/chartView.ts
- src/sql/workbench/contrib/query/browser/queryResultsView.ts
- src/sql/workbench/services/query/common/query.ts
This is requested by Kusto team: the ability to specify visualization options in the result set. I only implemented this in the query editor, but it is very easy to do the same in notebook by calling the `chartView.setVisualizationOptions`, I'd leave it to @rajeshka or the notebook team to use this feature since there are already cell chart option serialization, I don't want to break it accidentally. 
I'll have another PR to include the SQL tools service side of changes.
once my PRs are merged, @rajeshka you can add more charting options that you need.
> add support to accept visualization options 

- build/azure-pipelines/sql-product-build.yml
- extensions/integration-tests/src/test/notebook.test.ts
Need to re-enable the Notebook unit tests.  I expect CI will fail initially but I'll push additional commits until the CI is green.
> Turn back on Notebook unit tests

- src/sql/workbench/contrib/extensions/browser/scenarioRecommendations.ts
- src/sql/workbench/contrib/extensions/browser/staticRecommendations.ts
- src/vs/workbench/contrib/extensions/browser/configBasedRecommendations.ts
- src/vs/workbench/contrib/extensions/browser/extensionRecommendations.ts
Fixes #14250
The VS changes are updating it to bring in the latest changes on the VS Code side. I verified that the scenario and static recommendation features still work as expected.
Do note that currently we are not respecting the `Ignore Recommendations` setting. But this is behavior that currently exists in stable so I'm not going to fix that here - opened issue for tracking that https://github.com/microsoft/azuredatastudio/issues/14274
Scenario : Showing recommendations and installing : 
Scenario : Ignoring recommendation prompt
Static : Gallery shows static recommendations 
Static : Ignore recommendations
> Fix extension recommendations

- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13837
Previously we weren't firing the event when selecting an option with `this.select`. This was changed in https://github.com/microsoft/azuredatastudio/pull/13691 though but this code was never updated to take that into account.
I didn't see any reason why we'd want to open the connection dialog for the `Select Connection` option so just no-op'ing when that's selected (which is always done if the user cancels out of the connection dialog since we want have that showing in the dropdown again in that case)
> Fix notebook connection dropdown opening multiple connection dialogs

- extensions/notebook/src/test/book/book.test.ts
Mark 'openNotebookAsUntitled should open a notebook as untitled file in the editor' test as unstable.
> Notebook: Mark test as unstable

- src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookExplorerViewlet.ts
Previously, we used to identify the root of a tree item with the resourceUri but since we were sending always the root of the book instead of the actual path of a notebook it would cause the following issue: https://github.com/microsoft/azuredatastudio/issues/13688.
In order to fix how the results were display, I keep track of the opened books in the Provided Book Tree View and the actual Book Tree View. For this reason, I iterate over the Pinned Books View last.
The `folder.includePattern` is `undefined` for the new version of Jupyter Books, it's `content/**` for the legacy version of Books and it is the name of a` file + extension `for individual notebooks (either pinned or standalone notebooks in the Books View).
I added this check to identify which queries were books and check if the …
> Fix search results display

- extensions/arc/src/common/utils.ts
Recent changes made it so the endpoint we get back from the controller is in the form `<ip>,<port>` instead of `<ip>:<port>` like it was previously. Making us be able to support both to avoid these kind of issues in the future.
> Fix error when listing MIAA databases

- src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookExplorerViewlet.ts
Previously, we used to identify the root of a tree item with the resourceUri but since we were sending always the root of the book instead of the actual path of a notebook it would cause the following issue: #13688.
In order to fix how the results were display, I keep track of the opened books in the Provided Book Tree View and the actual Book Tree View. For this reason, I iterate over the Pinned Books View last.
The folder.includePattern is undefined for the new version of Jupyter Books, it's content/** for the legacy version of Books and it is the name of afile + extensionfor individual notebooks (either pinned or standalone notebooks in the Books View).
I added this check to identify which queries were books and check if the tree item (saved notebook or pinned notebook) belongs to a …
> Fix search results display (#14265)

- src/sql/workbench/browser/editor/profiler/profilerInput.ts
This PR fixes #14291 
editorInput used to support confirmSave and let us fully control the content of the process: https://github.com/microsoft/azuredatastudio/blob/eb35dae1d1238e03f1cab3bd45e151f381b22aef/src/sql/parts/profiler/editor/profilerInput.ts#L285
vscode has removed it and handle the confirmation in a common place, since we wanted to ask whether the user want to stopped the session, now it is not possible. it doesn't make sense to mark the editor as dirty anymore, it is safe to close the editor directly. the session stop is done in the dispose method of the input
> remove the dirty flag

- src/sql/workbench/services/restore/browser/restoreDialog.ts
- src/sql/workbench/services/restore/browser/restoreServiceImpl.ts
- src/sql/workbench/services/restore/browser/restoreViewModel.ts
This PR is a fix for #14282.
it contains changes to avoid flickering and ensuring the target DB is always selected correctly even if corresponding source is not present.
Both issues seem to be caused by repeated selection event of source drop down - 
- flickering due to repeated setting of values in the page
- and improper setting of database because target db is set to be overwritten by source and hence repeated select events on source were causing target to change as well.
I am not very sure as to how this started because I don't see any changes to this code. Hence I would like to test more before checkin. starting the PR anyways to get some suggestions.
> Fix for bug 14282 in Restore Dialog

- src/sql/workbench/services/dialog/browser/wizardModal.ts
This PR fixes #14221
the tree component is relying on the content width to set the size of the tree
but it is called before the page becomes visible, when things are not visible, the DOM.getContentXXX will return 0.
the fix is to make it visible first and then call the layout method.
with the fix:
tested the wizards in ADS and didn't find any issue with this change.
> show page first and then do the layout

- src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
- src/sql/workbench/contrib/notebook/test/electron-browser/notebookEditorModel.test.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
Issue: When a parameterized notebook is loaded, it updates the contents of the notebook which triggers the notebook content changed event and updates the version. When trying to close the notebook without saving it calls revert which calls load notebook and which again triggers the content update and leaving it in dirty state always.
Fix:
Do not consider changes during load time as dirty.
This PR addresses #14127
> fix for parameterized notebook closure.

- src/sql/base/browser/ui/table/interfaces.ts
- src/sql/base/browser/ui/table/media/slick.grid.css
- src/sql/base/browser/ui/table/media/table.css
- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/workbench/browser/editor/resourceViewer/resourceViewerInput.ts
I am working on adding the filtering feature to query result tables and noticed some issues with the header filter plugin.
1. the header text and button are overlapping when resized, using css to control the sizing of the elements.
2. we are using custom div as button and a few accessibility feature is missing, e.g. role, accessible name and space key press handling...., I am replacing it with html button element.
3. the jquery bind method has been marked as deprecated, replaced it with click handler.
before
after
> fix the header filter plugin issue

- extensionsGallery-insider.json
Updating insiders gallery. The vsixs already got uploaded for RC build in https://github.com/microsoft/azuredatastudio/pull/14276/ and https://github.com/microsoft/azuredatastudio/pull/14216
> update insiders gallery with data developer extensions

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/workbench/contrib/notebook/browser/turndownPluginGfm.ts
- yarn.lock
Since #14329 was throwing too many hygiene errors, I am just bumping the turndown version, which is the dependency that uses lodash (others are devDependencies)
> Bumped turndown version

- extensions/import/config.json
> Import Extension: Updating prose version to fix double backslash bug

- src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookSearch.ts
- src/vs/workbench/contrib/search/browser/searchView.ts
Fixes #12423. Hiding search editor link from notebooks viewlet; users have given us feedback that it's confusing that the link doesn't do anything currently, and would rather not see it here.
> Hide Open in Editor for notebook search

- src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
- src/sql/workbench/contrib/query/browser/statusBarItems.ts
- src/sql/workbench/services/query/common/queryModel.ts
- src/sql/workbench/services/query/common/queryModelService.ts
- src/sql/workbench/services/query/test/common/testQueryModelService.ts
This is part of the query editor enhancement planned for this semester. the summary will show when there are multiple numeric cells selected, the count include all the selected cells, but the average and sum are only considering numeric cells.
This PR fixes #512
how the same data look in Excel:
@chlafreniere I had to restrict this feature to query editor because there is no global event I can subscribe for notebook's query execution events. the sqlSessionManager is using QueryRunner and it is not associated with QueryModelService like query editor. If I get the the event when the notebook sql cell started execution (to clear the previous summary text), this feature can easily be available for notebook as well.
more screenshots:
when no numeric values are selected, the summary is not …
> selected cell summary for status bar

- src/sql/base/browser/ui/table/media/table.css
- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
1. click on the dropdown button will cause the header to be clicked, the fix is to stop the click event propagation.
2. add a cell value extractor parameter so that we can handle the scenario when data are object.
3. align the checkbox and text, right now the checkbox is higher than the text.
4. make the buttons layout horizontally 
5. set initial focus to the ok button when the menu is opened, currently the focus stays on the dropdown button and pressing tab won't move the focus to the filter pop up.
6. currently if the options can't take up all the available space, there will be whitespace added between the options, I am changing it to remove the extra space.
before
after
> fix a few issues with the table filter pop up.

- src/sql/workbench/browser/modal/modal.ts
This PR fixes one of the issue in #14367 
the button doesn't have attachButtonStyler run on them.
before:
after:
> add attach styler for modal dialog footer buttons

- src/vs/platform/actions/browser/menuEntryActionViewItem.ts
this PR fixes #14281 
I noticed in latest insider build, when you have sql-database-project extension installed, the dashboard's toolbar doesn't have all the expected items with error messages in the console.
turns out this is caused by the recent vscode merge, we added a class in the vscode's file, and in the recent vscode merge, we changed the implementation of how to add css classes to the node (the old addClass method is deprecated)
old:
https://github.com/microsoft/azuredatastudio/blob/release/1.26/src/vs/platform/actions/browser/menuEntryActionViewItem.ts#L359
new:
https://github.com/microsoft/azuredatastudio/blob/main/src/vs/platform/actions/browser/menuEntryActionViewItem.ts#L292
the new one doesn't allow empty css class names, and caused the error above.
the fix is to check …
> fix the dashboard toolbar not load issue

- src/sql/base/browser/ui/infoButton/infoButton.css
- src/sql/base/browser/ui/infoButton/infoButton.ts
- src/sql/platform/theme/common/colorRegistry.ts
- src/sql/platform/theme/common/styler.ts
- src/sql/workbench/browser/modelComponents/button.component.ts
- src/vs/base/browser/ui/button/button.ts
This PR fixes #14367 
use this opportunity to add styler for info button and use color registry instead of hard coded colors in css file.
before:
after:
> implement styler for infobutton

- extensions/mssql/config.json
- package.json
Update SQL Tools Service to revert SqlClient driver to 2.0.0 due to regression in macOS/Linux connectivity.
> Update Sql Tools for Feb Hotfix

- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
@alanrenmsft pointed out that the `notebook-button` css class isn't defined anywhere in the codebase. Just a relic from different times 😄 .
In the constructor for LabeledMenuItemActionItem, default CSS class has a default value:
`private readonly _defaultCSSClassToAdd: string = ''`
Stable:
This change:
> Notebook Toolbar: Remove Default CSS Class Name (doesn't exist)

- extensions/resource-deployment/src/ui/deployAzureSQLDBWizard/deployAzureSQLDBWizardModel.ts
- extensions/resource-deployment/src/ui/deployAzureSQLDBWizard/pages/azureSettingsPage.ts
- extensions/resource-deployment/src/ui/deployAzureSQLVMWizard/deployAzureSQLVMWizardModel.ts
- extensions/resource-deployment/src/ui/deployAzureSQLVMWizard/pages/azureSettingsPage.ts
- extensions/resource-deployment/src/ui/deployAzureSQLVMWizard/pages/networkSettingsPage.ts
- extensions/resource-deployment/src/ui/deployAzureSQLVMWizard/pages/vmSettingsPage.ts
- extensions/resource-deployment/src/ui/deployClusterWizard/deployClusterWizardModel.ts
- extensions/resource-deployment/src/ui/notebookWizard/notebookWizardModel.ts
- extensions/resource-deployment/src/ui/pageLessDeploymentModel.ts
- extensions/resource-deployment/src/ui/resourceTypeModel.ts
- extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts
Cleaning up a bunch of errors and other stuff I noticed while doing some other stuff
- Define default onCancel in base model class since most implementations don't actually need it (and get rid of one model that was throwing which was causing an exception when cancelling out of the wizard)
- Fix a bunch of the onValueChanged handlers to properly account for undefined values
- Remove unneeded awaits
- Remove unneeded setter for resourceProvider - the wizard is already updated earlier with the new provider so this was just duplicating that being done
> Resource deployment clean up

- src/sql/workbench/contrib/query/browser/statusBarItems.ts
This PR fixes #14417 
also use more strict number parsing, previously strings like '123abc' will be parsed as 123, now it is not considered to be a number.
average is whole number:
less than 3 digits after decimal point:
more than 3 digits after decimal point:
> limit the digits after decimal point

- extensions/arc/package.json
- extensions/arc/src/extension.ts
- extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts
- extensions/asde-deployment/package.json
- extensions/resource-deployment/extension.webpack.config.js
- extensions/resource-deployment/package.json
- extensions/resource-deployment/src/interfaces.ts
- extensions/resource-deployment/src/services/telemetryService.ts
- extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts
- extensions/resource-deployment/yarn.lock
- samples/sample-resource-deployment/package.json
Currently we can get data on the types of wizards and other dialogs being opened but this has a few limitations : 
1. It doesn't have anything for types that don't use wizards (such as those opening links directly)
2. It doesn't have any information about the specific provider being selected - so for example we couldn't tell whether a BDC instance was being deployed to OpenShift, AKS, Kubeadm, etc.
So this is adding a new custom event that will include that information and is fired every time the user leaves the ToolsAndEulaPage (which is always the first page they visit).
This does mean that if they go back and forth it'll generate a new event each time - but I see this as the same as someone opening the dialog and restarting a deployment multiple times and so that's still good to …
> Add telemetry for deployment type being selected

- remote/yarn.lock
Seems like this wasn't updated fully in https://github.com/microsoft/azuredatastudio/pull/14343
I'm a little confused though - @rajeshka did you not see these changes when you also updated the remote/yarn.lock in https://github.com/microsoft/azuredatastudio/pull/14227?
> Update remote yarn.lock

- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
This PR fixes #14437
turns out the issue has always been there, but since it has been using a fixed position, we can only see one icon:
this is the dom structure I captured on the stable build.
recently I fixed the text and button overlapping issue and the button is no longer using fixed position and the issue surfaced itself.
the fix is to add a check before we create the button.
with the fix:
> fix multiple button issue

- src/sql/workbench/browser/modal/calloutDialog.ts
- src/sql/workbench/browser/modal/media/calloutDialog.css
- src/sql/workbench/browser/modal/media/modal.css
- src/sql/workbench/contrib/notebook/browser/calloutDialog/common/constants.ts
- src/sql/workbench/contrib/notebook/browser/calloutDialog/imageCalloutDialog.ts
- src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts
- src/sql/workbench/contrib/notebook/browser/calloutDialog/media/calloutDialog.css
- src/sql/workbench/contrib/notebook/browser/calloutDialog/media/imageCalloutDialog.css
- src/sql/workbench/contrib/notebook/browser/calloutDialog/media/linkCalloutDialog.css
- src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts
Split code specific to image and link into their own super classes. 
Moved callout styles into a new stylesheet.
> calloutDialog refactor - new superclasses for insert image and insert link

- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
- src/sql/workbench/services/notebook/browser/models/cell.ts
- src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts
Fixes #14404.
We were incorrectly capturing keyboard shortcuts even outside of WYSIWYG mode, causing some functionality to not work (such as tab moves focus).
> Notebooks: Ensure WYSIWYG Mode for Keyboard Shortcuts

- extensions/azurecore/src/azureDataGridProvider.ts
sorting on the resource type column will result in the resource group column to be sorted(see screenshot), turns out caused by duplicate id being used.
> fix sorting issue in azure resource grid

- extensions/azdata/src/test/azdata.test.ts
There were some additional code paths in the tests that were downloading the release.json file where the HttpClient call wasn't being stubbed so those could fail intermittently. Instead we just always stub it out to return our fake version.
> Fix azdata tests

- scripts/sql.bat
- scripts/sql.sh
In order to debug the main process this option needs to be added. I'm adding it to the scripts so that no matter how they're launched (some people run the scripts directly instead of using the debug task) the port will be opened to then later attach to if desired.
> Add remote debugging port to launch scripts

- extensions/arc/src/localizedConstants.ts
- extensions/arc/src/models/postgresModel.ts
Expected - Azure portal should show different size for data and logs volume.
Actual - Azure portal shows data volume size.
Update:
> Node configuration needs to show different size for data and logs volume for postgresql.

- src/sql/workbench/browser/modal/modal.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/codeCell.component.html
- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.html
This PR fixes a conflict between the keyboard event listener for modal and the listener for textCell component. When textCell is in edit mode, and a callout dialog is open, hitting Esc will now close only the callout, leaving the editor open.
Originally, modal.ts listened for KEY_DOWN inside the show() method. In my callout dialog feature work, I changed it to KEY_UP. This led to conflicts. Lucy correct that in her PR. Now I'm using this PR to change the listeners in the textCell and codeCell template from keyup to keydown.
> Notebook cell and modal fix - follow up after Lucy's 14433.

- src/sql/azdata.proposed.d.ts
- src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts
Chris is using this event and noticed the selectorText is undefined. I found that in the component side, wrong argument name is used, I am renaming it to `description` to be more accurate.
> fix description not provided issue

- extensions/notebook/src/book/bookTocManager.ts
- extensions/notebook/src/book/bookTreeView.ts
- extensions/notebook/src/common/localizedConstants.ts
- extensions/notebook/src/dialog/createBookDialog.ts
- extensions/notebook/src/extension.ts
- extensions/notebook/src/test/book/bookTocManager.test.ts
- Add support for generating table of contents for folder with multiple subdirectories.
- Show dialog instead of loading the createJupyterBook notebook when running the create book command.
- Modify quickPick to allow moving sections to a book with no sections.
- Replace backlash to slash for windows paths.
https://user-images.githubusercontent.com/34872381/109088003-68918680-76c3-11eb-9a33-476dd19c40c2.mov
> Create book dialog improvements

- src/sql/workbench/browser/modelComponents/inputbox.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13667
The logic to add a custom input validation message is relatively new - added in https://github.com/microsoft/azuredatastudio/pull/8909. But it appears that due to race condition issues I fixed in https://github.com/microsoft/azuredatastudio/pull/13317 we never noticed any problems.
The root problem here is that we were manually calling showMessage while doing our validate - but because this was happening after the call to inputbox.validate then if we were showing an error initially (a common thing to happen since values aren't initialized until later) when the validation became successful the error message was never hidden properly.
Instead of doing this ourselves we should just be relying on the base class to handle all that …
> Fix input box validation

- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
- extensions/sql-database-projects/src/test/newProjectTool.test.ts
- extensions/sql-database-projects/src/tools/newProjectTool.ts
This PR fixes #14500. This adds a loader to the database dropdown while waiting for the list of databases and fixes the project name showing as "DatabaseProjectUndefined" when the dialog is opened from command palette or the projects viewlet. 
before: 
fixed:
> Fix a couple things in create project from db dialog

- src/sql/workbench/contrib/notebook/browser/cellViews/codeCell.component.html
- src/sql/workbench/contrib/notebook/browser/cellViews/codeCell.component.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.html
- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
Fixes #14434.
In #13078 the code below was changed. I'm reverting these changes specifically, which fixes the issue above.
> Notebooks: Fix Escape Not Unselecting Cell

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/common/utils.ts
- extensions/data-workspace/src/dialogs/dialogBase.ts
- extensions/data-workspace/src/services/workspaceService.ts
- extensions/data-workspace/src/test/workspaceService.test.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/browser/mainThreadWorkspace.ts
- src/sql/workbench/api/common/extHostWorkspace.ts
- src/sql/workbench/api/common/sqlExtHost.api.impl.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
This PR fixes #14310. Previously, untitled workspaces weren't handled because the projects are added as relative paths to the workspace, but it wasn't the correct path for untitled workspaces since they weren't saved and still in a temp location. After discussing with Raden, the fix here is to handle untitled workspaces like no workspace open scenarios and ask the user for a location to create the workspace. 
before: 
fixed:
the created workspace will have the newly created project folder and anything else, like folders, that were previously in the untitled workspace.
> Fix how data workspace handles untitled workspaces

- extensions/notebook/src/integrationTest/index.ts
Missed updating this when I switched this over to using the vscodetestcover runner (it was just using vscode test runner directly before)
Using the same coverconfig as the unit tests
> Fix error when running Notebook integration tests

- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/14192
> Notebooks: Fix pip installation not working

- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
- src/sql/workbench/contrib/notebook/test/electron-browser/notebookModel.test.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR fixes #13737.
The scenarios covered: 
- Opens kernel alias Notebook properly with kernel set to kernel alias.
- Switches Kernels properly if kernel alias notebook is open first.
- If Kusto Extension is not installed it will open notebook with SQL kernel.
> [Notebook] Open Kernel Alias (Kusto) notebook with Kernel Alias (Kusto) as selected kernel

- src/sql/workbench/api/common/extHostModelViewTree.ts
- src/vs/workbench/api/common/extHostTreeViews.ts
part of the fix for: https://github.com/microsoft/azuredatastudio/issues/14229
we override the refreshNode method of the vscode base class and commented out the clearChildren() call, this will cause the node not being disposed and cause the duplicate id error in the issue description. aside from the commented out code, the only other difference is this.componentDataProvider (in sql implementation) vs this.dataProvider(in vs implementation), but they are the same object, we pass in the componentDataProvider object in the super() constructor call. 
this will fix the scenario mentioned in the issue but to make the tree fully functional, I have to make another change in vscode: https://github.com/microsoft/vscode/pull/118091
> remove refreshNode method

- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
Notebook smoke tests were failing because `this.getInstalledPipPackages()` was returning an empty array, causing `pip.version` to throw an error. An empty array was returned because the Python Path config setting hasn't been set yet (didn't run into this issue locally since I had Python Path set).
> Notebooks: Fix re-installing pip + smoke tests

- extensions/integration-tests/package.json
- extensions/integration-tests/yarn.lock
- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/yarn.lock
The only thing this is really doing is adding the correct typings - without direct references to the 5.2.5 version it falls back to using the base ADS one which is much older so the typings are very out of date.
Adding the mocha reference isn't strictly necessary since we get it through the vscodetestcover package anyways (hence why you don't see any changes in the yarn.lock). But it's good to be explicit here since we tend to reference the mocha package in the tests so that we're sure to be using the correct version.
> Add mocha dependencies

- src/vs/workbench/api/common/extHostTypeConverters.ts
- src/vs/workbench/api/common/extHostTypes.ts
- src/vs/workbench/test/browser/api/extHostTypes.test.ts
Port over the fix for vscode issue https://github.com/microsoft/vscode/issues/111604 with minor modifications due to differences between branches.   This is for this regression from previous vscode source refresh https://github.com/microsoft/azuredatastudio/issues/14326.
> Fix hover tooltips

- src/sql/workbench/browser/modal/calloutDialog.ts
- src/sql/workbench/browser/modal/modal.ts
- src/sql/workbench/browser/modal/optionsDialog.ts
- src/sql/workbench/contrib/backup/browser/backupDialog.ts
- src/sql/workbench/contrib/charts/browser/configureChartDialog.ts
- src/sql/workbench/contrib/notebook/browser/calloutDialog/imageCalloutDialog.ts
- src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts
- src/sql/workbench/contrib/webview/browser/webViewDialog.ts
- src/sql/workbench/services/accountManagement/browser/accountDialog.ts
- src/sql/workbench/services/accountManagement/browser/autoOAuthDialog.ts
- src/sql/workbench/services/connection/browser/connectionDialogService.ts
- src/sql/workbench/services/connection/browser/connectionDialogWidget.ts
- src/sql/workbench/services/dialog/browser/customDialogService.ts
- src/sql/workbench/services/dialog/browser/dialogModal.ts
- src/sql/workbench/services/dialog/browser/wizardModal.ts
- src/sql/workbench/services/errorMessage/browser/errorMessageDialog.ts
- src/sql/workbench/services/fileBrowser/browser/fileBrowserDialog.ts
- src/sql/workbench/services/insights/browser/insightsDialogView.ts
- src/sql/workbench/services/resourceProvider/browser/firewallRuleDialog.ts
- src/sql/workbench/services/restore/browser/restoreDialog.ts
- src/sql/workbench/services/serverGroup/browser/serverGroupDialog.ts
There were a lot of places where we either weren't capturing the hide reason or had an incorrect reason. This mostly cleans them up.
The whole cancel/close/ok thing is a huge mess across all these dialogs - I didn't want to start trying to make sense of that all and so just kept my changes extremely minimal (hence why you see weird stuff like calling close with 'cancel')
> Clean up dialog event hide reasons

- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
Adding new event for capturing number of connection failures
- Inlined functions to clean things up
- Made the elapsed time values measurements and added the unit to the end. This means events before this goes out will need to be changed to correlate with the new events but seeing as we don't currently use those values anyways that doesn't seem to be a huge problem to me
> Add event for connection error

- src/sql/platform/telemetry/common/adsTelemetryService.ts
Not using this means it just was setting the local var - not the property on the class (they're actually separate vars) so it would be undefined if either of those weren't passed in the constructor.
> Fix undefined error in telemetry service

- src/sql/workbench/browser/modal/calloutDialog.ts
- src/sql/workbench/browser/modal/media/calloutDialog.css
- src/sql/workbench/browser/modal/modal.ts
- src/sql/workbench/contrib/notebook/browser/calloutDialog/imageCalloutDialog.ts
- src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
- src/sql/workbench/contrib/notebook/test/calloutDialog/linkCalloutDialog.test.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/14558
Show link callout dialog above the toolbar when there is not enough space below the toolbar.
> Notebooks: Fix callout dialog being cut off at the bottom of the document

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/common/workspaceTreeDataProvider.ts
This PR fixes #14565. An error message will show that the project can't be found, but other projects that can be found will still be loaded.
> Still load other projects even if one doesn't exist

- src/sql/workbench/contrib/query/browser/actions.ts
This PR adds a prompt warning users that encoding of the query editor results will not be saved when exporting to JSON (caused by the design of SQL service). This is to let users know of a workaround for the issue #1986 in case results are saved incorrectly. SQL service will need to be updated to handle encoding or the JSON file must be saved with encoding automatically afterwards (currently there is no way to retrieve the encoding of the results editor window when clicking "Save as JSON").
> Info prompt for results encoding when saving to JSON

- extensions/mssql/src/features.ts
Some time back when the `azdata.accounts.getAccountSecurityToken()` method was introduced, [some changes](https://github.com/microsoft/azuredatastudio/commit/587abd43c2d92d83af1214399172fe8734597915#diff-e519fbe7133b0f3ebdab4872678a1ad87ce1a8736ee4e2988ae0637a2a318c2b) were made to make use of this new method. Within one of the AE workflows, the `tenant` object was passed to this method instead of the `tenant.id` string value, which caused an exception and led to this bug.
This PR aims to correct this mistake, fix the bug and Closes #12611.
> Fix "Query Canceled by User" when querying encrypted fields Bug

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts
- extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts
- extensions/azurecore/src/account-provider/azureAccountProvider.ts
- extensions/azurecore/src/account-provider/azureAccountProviderService.ts
- extensions/azurecore/src/account-provider/interfaces.ts
- extensions/azurecore/src/azureResource/commands.ts
- extensions/azurecore/src/azureResource/interfaces.ts
- extensions/azurecore/src/azureResource/services/terminalService.ts
- extensions/azurecore/src/azureResource/tree/accountTreeNode.ts
- extensions/azurecore/src/azureResource/tree/flatAccountTreeNode.ts
- extensions/azurecore/src/azurecore.d.ts
- extensions/azurecore/src/test/account-provider/auths/azureAuth.test.ts
- extensions/azurecore/src/test/azureResource/providers/database/databaseTreeDataProvider.test.ts
- extensions/azurecore/src/test/azureResource/providers/databaseServer/databaseServerTreeDataProvider.test.ts
- extensions/azurecore/src/test/azureResource/resourceService.test.ts
- extensions/azurecore/src/test/azureResource/resourceTreeNode.test.ts
- extensions/mssql/src/features.ts
- extensions/mssql/src/typings/refs.d.ts
Follow-up to https://github.com/microsoft/azuredatastudio/pull/14588, this is adding typings to that code so that we're much less likely to have this kind of issue in the future.
I have some general questions around this implementation anyways (why is MSSQL handling general AKV token stuff?) but that's a much bigger problem to tackle so for now this should help avoid other similar types of regressions. 
(Looking through this code - we're going to have some really annoying issues to deal with if we ever support more account types than just Azure...right now pretty much everything we do assumes that getAllAccounts is returning only Azure accounts)
> Expose AzureAccount typings to other extensions

- src/vs/workbench/contrib/preferences/browser/preferences.contribution.ts
This option doesn't do anything as we don't have any settings for online services so just removing it
Before : 
After :
> Remove Online Services Settings option

- extensions/mssql/src/features.ts
Port of #14588 - tenant ID was passed incorrectly during refactoring of code
Closes https://github.com/microsoft/azuredatastudio/issues/12611
(cherry picked from commit 0bea923c0a32d6556123737ce7cc07e443629c72)
> [Port] Fix AKV security token issue

- extensions/dacpac/src/test/testDacFxConfigPages.ts
- extensions/dacpac/src/wizard/api/dacFxConfigPage.ts
- extensions/dacpac/src/wizard/pages/deployConfigPage.ts
This PR fixes #14634. The database dropdowns got changed from CategoryValues to strings in https://github.com/microsoft/azuredatastudio/pull/8909 and this missed getting updated. The model.database was getting set to undefined here since databaseDropdownValue.name was undefined, so it defaulted to the first value in the database dropdown.
> Fix deploy upgrade existing not choosing the correct database

- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/accountsSelectionPage.ts
I missed a codepath while doing previous PR and forgot to reset the subscriptions when the user changes the Azure tenant. This causes the subscriptions to not refresh when the tenant is changed.
> Resetting subscriptions after AD tenant is changed in migration wizard

- extensionsGallery-insider.json
- extensionsGallery.json
- Updating dacpac extension version in stable and insiders(doesn't need the latest ADS)
- Updating sql database projects in insiders to same version as already updated in RC #14627
Build with dacpac vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=96404&view=artifacts&pathAsName=false&type=publishedArtifacts
> update dacpac to 1.8.0 and sql database projects to 0.7.1 in insiders

- src/vs/platform/userDataSync/common/userDataAutoSyncService.ts
- src/vs/platform/userDataSync/test/common/userDataAutoSyncService.test.ts
- src/vs/workbench/services/userDataSync/browser/userDataAutoSyncEnablementService.ts
For https://github.com/microsoft/azuredatastudio/issues/14616
It's not clear how the service could have been enabled - we don't expose that anywhere as far as I'm aware. But it's possible there's a gap somewhere we haven't found yet so in the meantime just making it so the things that use the service will always be disabled regardless.
There's still a chance that the setting being enabled could cause problems elsewhere - but all the code I saw using this stuff checked the isEnabled state first before showing anything related to sync so this should cover most of the scenarios at the very least.
> Disable auto sync service

- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
- src/vs/platform/actions/browser/menuEntryActionViewItem.ts
* Added CSS to treat manage packages icon position.
* Wired up a rough concept showing how I propose to pass a masked-icon class, along with the icon name - derived from the action icon path - to the injected action prior to rendering. The end result is an injected action with an icon which behaves like the others in the notebook toolbar.
* Revert "Added CSS to treat manage packages icon position."
This reverts commit 215a67244a78224fe8fd2e6480b7e50d37a15dc0.
* Revert "Wired up a rough concept showing how I propose to pass a masked-icon class, along with the icon name - derived from the action icon path - to the injected action prior to rendering. The end result is an injected action with an icon which behaves like the others in the notebook toolbar."
This reverts commit …
> Manage Packages icon position fix (#14528)

- extensions/resource-deployment/src/ui/resourceTypeWizard.ts
- extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14673
We're modifying the objects when we're doing the filtering so make sure we clone them first since the objects passed in used across multiple deployments
> Fix filtered resource options persisting across deployments

- src/bootstrap-window.js
- src/bootstrap.js
This PR fixes loading script files in sandboxed windows, such as Issue Reporter or Process Explorer.  The sandbox windows use a custom schema (vscode-file vs. file) and need to have this configured when being bootstrapped.
This is for issue https://github.com/microsoft/azuredatastudio/issues/14623.
> Fix script loading in sandbox windows

- extensions/arc/src/models/postgresModel.ts
- extensions/arc/src/test/mocks/fakeAzdataApi.ts
- extensions/arc/src/test/models/postgresModel.test.ts
- extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresCoordinatorNodeParametersPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresWorkerNodeParametersPage.ts
- extensions/azdata/src/api.ts
- extensions/azdata/src/azdata.ts
- extensions/azdata/src/typings/azdata-ext.d.ts
This PR fixes #14729 
Adding fix to work with incoming change with azdata.
> Updated Postgres Spec for where to find engine version, removed calling calling -ev in edit commands

- extensions/resource-deployment/src/ui/modelViewUtils.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14712
I have some ideas about how to make it so that errors on pages aren't displayed until you navigate to the page that contains the components - but that's a bigger fix. For now just making it so at least the user is informed of what needs to be done to fix the issue.
> Fix blank MIAA/PG deployment wizard pages

- extensions/arc/package.json
- extensions/azdata/package.json
- extensions/azurecore/package.json
- extensions/resource-deployment/src/services/optionSourcesService.ts
- extensions/resource-deployment/src/services/valueProviderService.ts
- extensions/resource-deployment/src/ui/modelViewUtils.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14749
We need to be able to handle extensions which may not have been activated yet but still contribute a provider - this is a common pattern already used in VS Code (for example with tree views)
Package JSON defines the ID so that the RD extension can know which extension contributes what provider - and then the extension is in charge of ensuring that it's registered before the activate function returns.
> Activate extensions contributing deployment providers

- extensions/resource-deployment/src/services/azdataService.ts
- extensions/resource-deployment/src/services/bigDataClusterDeploymentProfile.ts
We only need to remove the activeDirectory settings (which is what causes the validaiton error). Other settings should be preserved. 
Also updated --target to --path, --target is deprecated and will be removed in a future release.
> Fix BDC deployment removing all security settings from config

- extensions/arc/src/ui/dashboards/miaa/miaaConnectionStringsPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaDashboard.ts
We're using the MIAA config to populate this page so it's not correct to hook into the controller config update event since that could happen before the MIAA config was populated - which would cause it to display a "No external endpoint configured" message instead of the connection strings.
> Fix MIAA connection strings page not populating

- src/sql/workbench/contrib/charts/browser/chartOptions.ts
This PR fixes #4032 by adding the missing option to the line-chart type.
Can be tested by just visualizing a result as a line-chart. The "Data Direction" will now be available.
> Add missing "Data Direction"-option to line charts

- src/sql/workbench/browser/modelComponents/declarativeTable.component.html
- src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
- src/sql/workbench/browser/modelComponents/media/declarativeTable.css
This PR fixes #14484
previously only the background color is set for the selected row, we also need to set the foreground color. 
also get rid of the hard coded color.
before:
after:
> declarative table color

- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
Convert relative paths to absolute paths based on the notebook uri before converting to markdown
This PR fixes #14736
> fix relative paths in wysiwyg

- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
Will think about how we can prevent this from happening in the future, although I'm pretty sure that DefinitelyType would have caught this when we tried to update the types and so we could have fixed it there. This mostly broke because of an extension was still using the deprecated azdata package to get the typings. But it'd be nice to catch it early on if we can.
> Fix API issues for external extensions

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/tree/baseTreeItem.ts
- extensions/sql-database-projects/src/models/tree/dataSourceTreeItem.ts
- extensions/sql-database-projects/src/models/tree/databaseReferencesTreeItem.ts
- extensions/sql-database-projects/src/models/tree/fileFolderTreeItem.ts
- extensions/sql-database-projects/src/models/tree/projectTreeItem.ts
- extensions/sql-database-projects/src/test/projectTree.test.ts
There were a few project tree tests failing only on windows caused by #14182. The tests were failing because the projectTreeItem's uri got changed to be the file system uri, which was then used in the fsPathToProjectUri conversion when constructing file and folder tree items. This only caused the windows tests to fail because the root path in those tests was set to 'z:\\' in windows and '/' for mac and linux. 
Only the uri of the vscode.TreeItem needs to be the file system uri, so changing the projectTreeItem's uri back to just the basename fixed the tests and kept the git status showing in the tree. Most of the other changes are updating the baseTreeItem's uri to projectUri to make it less confusing since the file and folder tree items also have their fileSystemUri. 
I verified that …
> fix project tree tests failing on windows

- extensions/sql-database-projects/src/models/dataSources/sqlConnectionStringSource.ts
- extensions/sql-database-projects/src/test/baselines/publishProfileSqlLoginBaseline.publish.xml
- extensions/sql-database-projects/src/test/datasource.test.ts
This PR fixes #14789, which was reported in #14754. Also changing another test password to be PLACEHOLDER for consistency.
> Fix publish profile with connection string ending in semicolon not loading

- src/sql/workbench/services/accountManagement/browser/accountDialog.ts
This PR fixes #14170 
this is a temporary fix for the accessibility issue by making the tenant list not keyboard focusable and opened an issue for @cssuh to understand what do we want to do with the tenant list: https://github.com/microsoft/azuredatastudio/issues/14808
> make tenant list not tab focusable

- src/sql/workbench/services/connection/browser/connectionBrowseTab.ts
Previously the aria-label is set to the tree node handle, which is definitely wrong, with this PR the aria-label will be the display text.
This PR fixes #14172
> use label instead of handle for aria label

- src/vs/workbench/browser/media/style.css
- src/vs/workbench/browser/style.ts
This PR fixes #14546 
right now it is using the browser default color:
update it use our common colors.
before:
after:
> radio button outline style

- extensions/mssql/config.json
https://github.com/microsoft/sqltoolsservice/releases/tag/v3.0.0-release.87
Includes the latest Migration Assessments for the SQL Migration extension.
> Bumped sqltoolsservice version

- extensions/notebook/src/test/common.ts
- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/browser/modelComponents/divContainer.component.ts
- src/sql/workbench/browser/modelComponents/flexContainer.component.ts
- src/sql/workbench/browser/modelComponents/splitviewContainer.component.ts
The code in core had already been updated to use this type so there doesn't seem to be any reason not to promote this now. 
@aasimkhan30 FYI since your migration code is using the raw type - but since you're using the proposed API you can just immediately update to use azdata.CssStyles in your code to make it more readable
> Promote CssStyles to stable API

- extensions/sql-migration/src/dialog/assessmentResults/assessmentResultsDialog.ts
- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
I was testing the migration UI and noticed the scroll is going out of control, the 3 pars, databases/issues/issue details should scroll independently. also, for db list, the scroll should happen inside the list itself, the search box and the server warning list should always be visible as shown in the 'after' screenshot
before
after:
> fix the layout issue in migration assessment dialog

- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/extHostModelView.ts
- src/sql/workbench/browser/modelComponents/declarativeTable.component.html
- src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
This PR fixes #14841
also fixes:
1. allow row selection when user click anywhere on the row
2. allow select row using keyboard
3. differentiate active & selected vs selected styles.
4. rename the selectEffect property to enableRowSelection
5. reset the selectedRow when clearContainer()
dark:
light:
> declarative table fix

- src/sql/workbench/contrib/tasks/browser/media/tasksPanel.css
- src/sql/workbench/contrib/tasks/browser/tasksView.ts
This PR fixes #14517. This adds a scrollbar and gets rid of the truncation with ... in the task history when the window is made smaller or zoomed in so that the data is viewable without a tooltip. 
before: 
after:
> Make task history horizontally scrollable

- src/sql/base/browser/ui/checkbox/checkbox.ts
- src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
1. Remove the enter key handler, as per accessibility requirement, we shouldn't need to handle Enter key. https://webaim.org/techniques/keyboard/
2. Fix the issue that user is not able to interact with the checkboxes inside the declarative table using space key. The fix is: for declarative table's row, only handle the keyboard event when the event is originated on the element itself.
> fix issue that user is not able to interact with checkbox in declarative table using keyboard

- src/sql/base/browser/dom.ts
- src/sql/workbench/browser/modal/modal.ts
This PR fixes #14519
This PR fixes #14520 
This PR fixes #14318
This PR fixes #14317
the elements returned by the query contains invisible elements and caused these 2 issues. the fix is to further filter the list to only return visible elements.
also I am moving this function out so that it can be reused (I will reuse it for the query result filter dialog).
> only return visible elements as focusable

- extensions/resource-deployment/src/localizedConstants.ts
- extensions/resource-deployment/src/services/uriHandlerService.ts
- src/sql/workbench/contrib/extensions/browser/extensions.contribution.ts
Adds support for Resource Deployment URIs to specify an extension that must be installed to start the deployment, prompting the user to install it if it isn't installed. 
There's still a slight gap here in that RD doesn't pick up the new resource types until the window is reloaded. I'll follow up with a separate PR to fix that.
> Add prompt to install required extensions for resource deployment

- extensions/resource-deployment/src/main.ts
- extensions/resource-deployment/src/services/resourceTypeService.ts
- extensions/resource-deployment/src/test/services/resourceTypeService.test.ts
2 main changes here : 
1. We now reload the resource types whenever an extension is installed/uninstalled so that we always have the latest resource type information without needing to restart ADS
2. We no longer stop loading the resource deployment extension if we detect errors in a resource type - instead we'll just skip that resource type. I never thought this made sense to do since just because one type was invalid doesn't mean we should break the entire feature for everyone else.
As part of this I did some slight refactoring of all the functions running this stuff to just makes things easier to use and follow better practices.
> Reload resource deployment types on extension changes

- extensions/arc/src/ui/dashboards/miaa/miaaComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
Have model refresh calls placed in separate try/catch - we should still show the "instance updated" message even if the refresh failed (but want to still display an error about the refresh failing).
> Add try catch block to model refresh in compute/storage pages

- extensions/arc/src/ui/dashboards/postgres/postgresCoordinatorNodeParametersPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts
- extensions/arc/src/ui/dashboards/postgres/postgresWorkerNodeParametersPage.ts
Currently to discard values put in the table by the user, the table gets refreshed and all components are recreated to show its original values. The data of the table is also reset. This change records which parameters have been altered in the UI and only changes the value of the components without  having to reset the data of the table. 
To do this change I had to no longer save the components within a flex container. The only component that needed to be within a container was textbox that took in numbers in order to be placed with an information bubble. This results in no change in the view of the table on the Parameters Dashboard. 
This PR hopefully can address  # 14366
> Updates how the Postgres Parameter Dashboard adds data to its table and discard values. 

- src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts
Notebook smoke test failure was caused by my previous PR https://github.com/microsoft/azuredatastudio/pull/14765.
The test timed out after Python download because the Jupyter server was being started twice. Added a check to make sure there is an active Jupyter session running before restarting the server.
> Notebooks: fix smoke test

- src/sql/workbench/contrib/query/browser/messagePanel.ts
- src/vs/base/browser/ui/tree/indexTreeModel.ts
- src/vs/base/common/arrays.ts
- src/vs/base/test/common/arrays.test.ts
This PR fixes #14744 
using spread operator as method parameter is not safe, it might exceed the maximum stack size when dealing with a lot of records (130k in this case).
I have a PR for vscode and I have cherrypicked the changes in this PR.
> fix maximum call stack size reached issue

- src/vs/workbench/contrib/files/electron-sandbox/fileActions.contribution.ts
This PR fixes #14760. This was already fixed in vscode microsoft/vscode@8f410da(and duplicate import fixed in https://github.com/microsoft/vscode/commit/528ca4c9ea884058308eb477572d52b7283b6218), but it might be a bit before the next vscode merge so bringing this in now so it gets in the April release.
> fix revealFileInOS command

- src/sql/workbench/contrib/query/browser/keyboardQueryActions.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
My goal is to add the ability to insert the parameter anywhere in the query. I'm modifying the execution of query shortcuts by first checking if `{arg}` is present, if true just replace it with the parameter if not add the parameter at the end of the query just like it's been working until now.
This PR fixes #14893
> Use {arg} to reference selected text in query shortcuts

- extensions/kusto/config.json
- extensions/kusto/package.json
Increased sqltoolservice version for Kusto to 90 and bumped Kusto version to 0.5.2
> Kusto Version bump

- scripts/test-extensions-unit.bat
- scripts/test-extensions-unit.sh
Adding this so that the data-workspace code coverage gets included in the code coverage reports in PRs. @Charles-Gagnon let me know if anything else needs to be updated to include them.
> Add data-workspace unit tests to test-extensions-unit scripts

- extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
This PR 
1. Adds reset ability to Cores request and limit
2. Removes unnecessary '!'
3. Uses withProps instead of withProperties
> Cleaning up PG Compute and Storage code and adding reset for Cores

- src/vs/workbench/browser/parts/editor/editorGroupView.ts
For https://github.com/microsoft/azuredatastudio/issues/14929, https://github.com/microsoft/azuredatastudio/issues/13797 and https://github.com/microsoft/azuredatastudio/issues/6763
Hard to tell where this is coming from, so log the full stack trace to console so we can actually figure that out.
> Log full stack trace for editor opened errors

- extensionsGallery-insider.json
- extensionsGallery.json
- scripts/validateGalleries.js
This isn't strictly required, but it's better that we make sure people are actually considering this before submitting.
We could probably do something with the VS Code engine version too - because the way I see it there should only be two scenarios : 
1. VS Code Engine version is * and ADS Engine version is either * or >=x.x.x
1. VS Code Engine version is * or >=x.x.x and ADS Engine version is *
I don't see having both be >=x.x.x as being something that's useful since every ADS version is strictly tied to a specific VS Code engine version anyways. 
Thoughts on this @alanrenmsft ?
> Require AzDataEngine property for galleries

- extensionsGallery-insider.json
- extensionsGallery.json
- scripts/validateGalleries.js
Only allow both engine versions to be * or one * and the other with a version specifier (>=).
Having multiple engine versions is redundant - since each ADS release is tied to a specific VS Code engine version already. 
Most extensions should be specifying an ADS engine version if anything - but we do have some that came from VS Code directly that are easier to have just use the VS Code engine version.
> Don't allow multiple engine version specifiers

- src/sql/workbench/contrib/queryPlan/common/queryPlanInput.ts
This PR fixes #14632 
turns out this feature never worked, I went all the way back to 0.33 release of sqlops studio :)
root cause:
if we use fileservice to read the text file, it is returned as binary and we use the toString method of it, the text is not the same as if we read it using textfileservice.
html-query-plan packages uses XSLT to transform the xml to html, and during rendering, it will look for the node with css class 'qp-root', but due to the malformed xml string, the html was not created successfully, and result in the error of can not read property getBoundingClientRect of null.
fix:
use textfileservice to read the file content.
with the fix:
> fix query plan doc failed to load issue

- src/sql/base/browser/lifecycle.ts
- src/sql/workbench/browser/modelComponents/modelComponentWrapper.component.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
Closes https://github.com/microsoft/azuredatastudio/issues/14917
I looked into this and there isn't really any way we can actually fix this - basically it's because of a race condition where : 
1. We create a ComponentWrapper
2. It gets initialized and calls detectChanges - at this point it isn't disposed and then goes off into Angular code
3. The container holder the component wrapper is then cleared (pretty quickly after the component is created)
4. The change detector is then marked as disposed since the component was removed
5. Finally the detectChanges call from 2 gets to a point where it checks that the changedetector isn't disposed and now throws because it sees that it is
So instead I just make it ignore any errors that happen after it's disposed - that would be an expected …
> Don't log disposed changeDetector errors

- src/sql/base/parts/editableDropdown/browser/dropdown.ts
- src/sql/base/parts/editableDropdown/browser/dropdownList.ts
- src/sql/workbench/contrib/query/browser/queryActions.ts
- src/sql/workbench/contrib/query/test/browser/queryActions.test.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14916
There's two fixes here : 
1. The dropdown map error - this is coming from this line https://github.com/microsoft/azuredatastudio/blob/main/src/sql/base/parts/editableDropdown/browser/dropdown.ts#L301
At this point the data source didn't have any values set and so filteredValues was undefined. I could have just updated it to also check for undefined like we did elsewhere - but IMO it makes more sense to just have the data source always have a list of values and then just default to an empty list. There isn't really any difference between an empty list and undefined. 
The fixes in dropdown and dropdownList are for this
2. After doing this I noticed that the query editor database name dropdown was highlighted in red after …
> Fix dropdown error & editor database dropdown validation

- extensionsGallery-insider.json
- extensionsGallery.json
The paths were changed in the repo recently so the gallery currently can't display these.
> Fix langpack URLs

- extensions/notebook/src/book/bookModel.ts
- extensions/notebook/src/book/bookTreeItem.ts
- extensions/notebook/src/book/bookTreeView.ts
- extensions/notebook/src/extension.ts
- extensions/notebook/src/test/book/book.test.ts
The main issue here was the getChildren function line 631 - when passed undefined we should pass only the root nodes of the tree view. We were getting all the children of those root nodes though and so would end up with a bunch of duplicated tree items. 
Along the way I tried to clean up some things : 
1. Create tree view and visibility changed handler in the constructor instead of each time we load a book. There should only ever be one per tree data provider so making more is likely to result in issues (I was seeing some odd stuff with the callbacks not being hooked up correctly)
2. Renamed some functions to be clearer about what they're doing
> Fix duplicated nodes

- extensions/notebook/src/book/bookTreeItem.ts
- extensions/notebook/src/book/bookTreeView.ts
Functionally should behave the same, but removed a lot of unnecessary logic, reorganized it to be more readable and added comments.
> Cleanup findAndExpandParentNode

- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/contrib/charts/browser/chartView.ts
- src/sql/workbench/contrib/charts/browser/charts.contribution.ts
- src/sql/workbench/contrib/charts/browser/interfaces.ts
- src/sql/workbench/contrib/charts/browser/utils.ts
- src/sql/workbench/contrib/charts/test/browser/chartView.test.ts
- src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
- src/sql/workbench/contrib/preferences/browser/sqlSettingsLayout.ts
- src/sql/workbench/contrib/query/browser/actions.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
- src/vs/workbench/workbench.common.main.ts
This PR fixes #14335 
Right now we are not limiting the size of the data we pass to chartjs to render charts, as described in the issue, this will cause the app to freeze or crash.
I experimented myself locally and I found 300 is a reasonable number that the charts works with no obvious lag.
I've made it configurable so that users can adjust this number based on their local environment, also provided an option to suppress this notification.
> limit the data size for chart rendering

- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR fixes #14962
there are 2 actual issues:
1. when we switch tabs and come back to the original query editor or switch between messages/charts/results inside the editor, the filter button will be visible even though row count exceeds the max allow rows.
fix: add a call to update the filter's state in onDidInsert which is called when the view is restored
2. when the result is coming in batches, the header won't be refreshed.
fix: updated the enabled property setter to force redrawing of the table header, so that the latest enabled state is used.
> fix filter button visibility issue

- src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerWidget.component.ts
in #14621, the user attached a log file indicates that `this._input` could be undefined. I couldn't reproduce it myself, but it doesn't hurt to add an extra check.
> check whether element is undefined

- extensions/notebook/src/book/bookTreeView.ts
- extensions/notebook/src/telemetry.ts
- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
- src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookExplorerViewlet.ts
- src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookSearch.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookActions.test.ts
- src/sql/workbench/services/notebook/browser/models/modelFactory.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
Closes https://github.com/microsoft/azuredatastudio/issues/14985
More notebook telemetry capturing the below actions:
Search Book through Search viewlet -> launching search from treeItem actions.
Move Book
Run All Cells
Add Cell
Change Kernel
Search in Notebooks Viewlet
Search Completed with time taken
New Notebook launched from Connections.
> [Port] Add more Notebook telemetry events #14755

- src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
- src/sql/workbench/contrib/notebook/test/calloutDialog/linkCalloutDialog.test.ts
This PR addresses #14724. 
It will show the user the currently selected link within the Callout dialog so that the user can see the current link and edit it.
> See and Edit Selected Links in Callout Dialog 

- extensions/schema-compare/src/schemaCompareMainWindow.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/12779 and addresses https://github.com/microsoft/azuredatastudio/issues/14957. This missing parenthesis was causing the string comparison to fail when looking for the previously selected server connection, so it was defaulting to the most recent connection when there were multiple active connections.
https://github.com/microsoft/azuredatastudio/blob/a3cddbc8aadf4106fd9877b111ec64b3d609cc61/extensions/schema-compare/src/dialogs/schemaCompareDialog.ts#L559-L564
> fix schema compare dropdown not selecting correct db when multiple active connections

- src/sql/base/browser/ui/checkbox/media/checkbox.css
- src/sql/workbench/contrib/charts/browser/chartView.ts
- src/sql/workbench/contrib/charts/browser/media/chartView.css
It bothers me to have a checkbox with no text next to it, finally fixing it.
also remove the default margin set on checkbox.
before
after:
> fix chart's checkbox option type

- extensions/azdata/src/api.ts
- extensions/azdata/src/azdata.ts
- extensions/azdata/src/localizedConstants.ts
- extensions/azdata/src/test/api.test.ts
- extensions/azdata/src/test/azdata.test.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15009
The Azdata extension doesn't check that the version currently installed supports the features it needs - so if someone has an older version of azdata installed then the extension and anything depending on it may break in various ways.
We should make it clear when a version is required and not allow the user to use any functionality until the version is updated.
> [Port] Add required minimum version for azdata extension (#15010)

- src/sql/platform/telemetry/common/adsTelemetryService.ts
This function was recently added to be used by certain events such as DatabaseConnected - which previously were adding similar properties directly themselves. This was mostly fine - but the provider property was named `provider` previously where as this named it `providerName`. This meant any new events weren't being processed properly since providers.provider was blank.
Given that the only users of this function are the ones that were recently modified or completely new events I decided just to have this match the original name of the property so that the processing scripts don't have to do anything extra.
> Fix event property name

- src/sql/platform/telemetry/common/adsTelemetryService.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15028
This function was recently added to be used by certain events such as DatabaseConnected - which previously were adding similar properties directly themselves. This was mostly fine - but the provider property was named provider previously where as this named it providerName. This meant any new events weren't being processed properly since providers.provider was blank.
Given that the only users of this function are the ones that were recently modified or completely new events I decided just to have this match the original name of the property so that the processing scripts don't have to do anything extra.
(cherry picked from commit 1c66499910f90f8af265c2af1c5e74486d2bd68e)
> Fix event property name (#15026)

- src/sql/workbench/contrib/backup/browser/backupActions.ts
- src/sql/workbench/contrib/restore/browser/restoreActions.ts
Ref approved issue #15040 (will close with port). 
Please note The desired behavior is **Backup to work in Database Context and Restore to work in Both Server and Database Context**. If the aprropriate context is not selected it should give the right error. **Note that backup and restore errors are similar but not same.**
Fix contains blocking to open when needed and minor error message corrections.
> Fixing an issue with backup restore launch (issue #15040)

- extensions/notebook/src/book/bookTreeView.ts
- extensions/notebook/src/book/bookTrustManager.ts
- extensions/notebook/src/test/book/book.test.ts
This PR fixes #15023 
On windows, reveal node sometimes throws 'TreeError [bookTreeView] Tree element not found: [object Object]' even when the node is valid, added a try catch block to just add that error to console and continue the reveal flow.
> Select active notebook in viewlet when opened from command pallet

- extensionsGallery-insider.json
- extensionsGallery.json
The extension submitted is "SQL Data Inspector" (sql-data-inspector).
> Submitted a new extension to the gallery

- extensions/azdata/package.json
- extensions/azdata/package.nls.json
- extensions/azdata/src/azdata.ts
- extensions/azdata/src/constants.ts
- extensions/azdata/src/localizedConstants.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15056
Add a "Don't Ask Again" prompt to the initial startup prompt.
We will still display an error message informing the user that they must install the newer version if they try to use any of the functionality of the extension that requires the minimum version
Config settings : 
Also : 
- Consolidated update logic into one helper function
- Updated some of the strings to be clearer/more accurate
> Add "Don't Ask Again' response to required azdata update prompt

- src/sql/workbench/contrib/editorReplacement/common/editorReplacerContribution.ts
Addresses #15067.
`resource.toString()` does not help us in the editorLanguageAssociation in cases where a URI is formed like the following:
```
git:/Users/blah/hello.ipynb?%7B%22path%22%3A%22%2FUsers%2Fblah%2Fhello.ipynb%22%2C%22ref%22%3A%22679a85607a5268942192715215a3158f089bae20%22%7D
```
This above scenario occurs when opening a file, going to the files viewlet, and choosing an item from the Timeline view.
Because in this scenario, `path.extName().split(1)` returns `ipynb%22%2C%22ref%22%3A%22679a85607a5268942192715215a3158f089bae20%22%7D`
The above string doesn't map to one of our known editor overrides (e.g. sql, ipynb, etc), which causes the notebook diff to appear as a text diff.
Instead of doing a `toString()` on the resource, getting the `extname` from the uri's `fspath` (which …
> Fix for Rendered Notebook Diff from Timeline View

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/controllers/projectController.ts
This PR addresses the problem in #15070.
Originally, the code wasn't looking for the outcome of deploy functionality, hence presented passed for a successful DacFx operation, but failed scenario. Now the code checks for the outcome of the deploy task and presents information based on that.
> Fix deploy data to be presented on dashboard

- extensions/integration-tests/src/test/notebook.test.ts
Some notebook integration tests are failing due to recent changes in the open notebook logic. Temporarily skipping the failing tests for now while I investigate to unblock insiders builds.
> Temporarily skip failing notebook integration tests

- extensions/import/package.json
- extensions/import/yarn.lock
- extensions/liveshare/package.json
- extensions/liveshare/yarn.lock
The dataprotocol-client was updated recently, but this update had some functional changes that broke the import wizard (it would never start up).
Something was happening in the service where the initial 'initialize' request sent by the dataprotocol-client was never responded to so it just hung infinitely. I was not able to determine exactly what the issue was - partially because at this point the code that the Import service uses (Hosting.v2) is very out of date with what's currently in the STS repo. This is likely the issue - breaking changes have been made since the service was originally created and the service hasn't been updated to handle these changes. 
At some point it would be great to go in and update the service to actually use the current Hosting.v2 code, but for now I'm just …
> Fix import extension

- extensions/notebook/src/book/bookTreeView.ts
For https://github.com/microsoft/azuredatastudio/issues/15090
By passing 3 in to reveal we tell the tree to expand not only that node but also up to 3 of its children. And because we reveal a node at each level of the path we can potentially expand many unrelated nodes.
Then in addition - some of those nodes had expand_sections set to true in the TOC, which meant that when it was revealed it was displayed as expanded automatically.
Changing this to true will mean we only expand the node we're currently looking at as we go down the path. 
This isn't a perfect solution though - since books can be ordered such that the actual paths on disk don't actually correspond to which TOC they're contained in we can't just use the path of the Notebook as the path we walk to try and find the node. …
> Only reveal parent node when finding notebook item

- src/sql/workbench/api/common/extHostModelView.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14048
We now : 
- Don't add duplicate items to container components. If an item is attempted to be added that already exists then we just skip it (and log a warning since that should not be a normal case)
- Clear out the declarative table component when setting new data values
> Declarative table component fixes

- extensions/notebook/src/book/bookTreeView.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15090
(cherry picked from commit 42cd650147185270204c52635581dd1de0376644)
> [Port] Only reveal parent node when finding notebook item (#15091)

- extensions/arc/src/ui/dashboards/miaa/miaaConnectionStringsPage.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/12853
Default to placeholder value until we get a valid username from the user (same logic we use on the overview page)
> Fix MIAA connection strings page showing user as undefined

- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/workbench/browser/modelComponents/table.component.ts
- src/sql/workbench/contrib/assessment/browser/asmtResultsView.component.ts
- src/sql/workbench/contrib/jobManagement/browser/jobsView.component.ts
- src/sql/workbench/contrib/jobManagement/browser/notebooksView.component.ts
- src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
- src/sql/workbench/contrib/resourceViewer/browser/resourceViewerTable.ts
- src/sql/workbench/test/electron-browser/modalComponents/table.component.test.ts
use the contextViewService to show the filter UI so that we don't have to calculate the location ourselves. 
A side-effect (benefit) is now we can inherit the theme colors automatically since the menu is no longer directly under document.body. 
before:
after:
> use context view provider to show the filter

- build/azure-pipelines/darwin/sql-product-build-darwin.yml
- build/azure-pipelines/linux/sql-product-build-linux.yml
- build/azure-pipelines/web/sql-product-build-web.yml
- build/azure-pipelines/win32/sql-product-build-win32.yml
Fixes https://github.com/microsoft/azuredatastudio/issues/15112
The staging directory should only be used for stuff we want to publish as a build artifact. When downloading the compilation tarball we just let it put it in the default location instead (Pipeline.Workspace) so it doesn't get re-uploaded by each of the platform compilation jobs. 
Test build : 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=100379&view=artifacts&pathAsName=false&type=publishedArtifacts
> Remove duplicate artifact upload

- extensions/integration-tests/src/test/notebook.test.ts
- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
- src/sql/workbench/services/notebook/browser/interface.ts
- src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts
This PR fixes the failing integration tests, as the isNotebookInput function was returning false due to defaultKernel and connectionProfile being undefined. Moreover, notebookUri and layoutChanged were also returning false previously so now we check there type specifically. 
After the parameterized notebook was opened, I saw that when I clicked run all cells, it said "unable to runAllCells of undefined". As such, I debugged and found runAllCells function call findNotebook, which then alters the URI as done previously by removing the query and fragment, but then it is compared to the id retrieved by the call here - 
`let editor = this.listNotebookEditors().find(n => n.id === uriString);`. 
The id contains the URI and query, as such it would return an undefined editor. 
I changed the logic …
> Fixes notebook integration tests + running parameterized notebook

- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR fixes #14545. Which now saves the language_info upon changing the kernel to Kusto and then saving the notebook.
Aliases such as Kusto in this example still use SQL as the kernel in the backed but we can set the language info to be set to kusto here before the user saves the new kusto notebook therefore the metadata will contain the proper kusto name and be opened with the Kusto kernel.
> Save Kusto Notebook with proper language notebook info

- src/sql/workbench/contrib/modelView/browser/webview.component.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts
- src/vs/editor/browser/core/markdownRenderer.ts
- src/vs/editor/browser/services/openerService.ts
- src/vs/editor/contrib/gotoError/gotoErrorWidget.ts
- src/vs/editor/contrib/hover/modesContentHover.ts
- src/vs/editor/contrib/links/links.ts
- src/vs/editor/test/browser/services/openerService.test.ts
- src/vs/platform/opener/browser/link.ts
- src/vs/platform/opener/common/opener.ts
- src/vs/workbench/api/browser/mainThreadWebviews.ts
- src/vs/workbench/browser/parts/notifications/notificationsViewer.ts
- src/vs/workbench/browser/parts/views/viewPaneContainer.ts
- src/vs/workbench/contrib/comments/browser/commentsTreeViewer.ts
- src/vs/workbench/contrib/extensions/browser/extensionEditor.ts
- src/vs/workbench/contrib/markers/browser/markersTreeViewer.ts
- src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts
- src/vs/workbench/contrib/preferences/browser/settingsTree.ts
- src/vs/workbench/contrib/remote/browser/remote.ts
- src/vs/workbench/contrib/welcome/walkThrough/browser/walkThroughPart.ts
This PR addresses https://github.com/microsoft/vscode/issues/121211 in ADS
Fix taken from - https://github.com/microsoft/vscode/commit/23e346ab55a317c322a184eab4d10597927cd491
Again the files were different, so I couldn't cherry pick and fixed the issues in different files like vscode did. 
**NOTE: If we are using commands to open links anywhere, we will also need to add the `allowCommands` flag to every `openerService.open` call. This will also need some more testing from the team**
The following files in `sql/*` use the `openerService.open()` call which is now updated. I'm adding the files and the people who worked on it (or area owners) to make sure we don't have breaking changes:
EDIT - only these need attention
> Links handling in commands

- src/sql/base/browser/dom.ts
- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/workbench/browser/modal/modal.ts
take the logic to trap keyboard navigation from modal and move it to base layer. tested dialogs/wizards/table filter menu/callout dialogs, all work as expected.
> trap keyboard navigation

- src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts
Noticed this while fixing something else, because we were hooking up the event listeners only after a successful connection that meant if an error occurred while connecting then any future attempts to run that query wouldn't display any messages. 
Scenario : 
1. New notebook
2. Try to execute code cell with a connection that will error out trying to connect
3. Re-run the cell
Expected : Error will be displayed
Actual : No error displayed, cell just immediately returns
I'd say that displaying this kind of error in the cell output isn't ideal though - really this kind of thing I think should be shown as a toast notification. But this at least is a step in the right direction so people aren't left wondering what's going wrong.
> Add notebook query event listeners before connect

- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
I noticed that the menu is not going away if I click on some places, I am changing the event phase to use capture phase so that we can reliably get the click event and close the menu properly.
also slide in a change to add the table filter styler to disposable store in query results.
more information about event phase and useCapture parameter:
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
https://www.w3.org/TR/2003/NOTE-DOM-Level-3-Events-20031107/events.html#Events-phases
before:
after:
> fix the menu not hide issue

- src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts
- src/sql/workbench/contrib/dashboard/browser/pages/databaseDashboardPage.component.ts
- src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.component.ts
This PR fixes #15154 
the preview flag should not control the visibility of the extension contributed tabs, if user decided to install an extension, it should be shown regardless whether the preview flag is turned on, preview flag should only control the built-in features
> remove the preview flag check for tabs

- src/sql/workbench/contrib/query/browser/queryActions.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15145
@aasimkhan30 - This was caused by your recent changes since we now fire this event in places that we didn't before.
Could you please take some time to go through all the places where we use this event and do a quick check to make sure they won't have the same kind of issue?
I also fixed an issue where the error wasn't being displayed properly (noticed this during a smoke test run) - the localize function can't handle error objects directly so we have to get the error string out of it first. 
Before :
After :
> Fix error when disconnecting database

- src/vs/workbench/contrib/tags/electron-browser/workspaceTags.ts
This event gets sent with a lot of different properties which makes tagging it annoying - we have no need for this at this point in time so just disabling it for now.
> Disable workspace tags event

- extensions/notebook/src/book/bookTreeView.ts
This PR addresses failed scenarios caused by expanding only parent node. (fixed by #15090 )
> select notebook in viewlet only expanding its parents

- src/sql/workbench/contrib/editorReplacement/common/editorReplacerContribution.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15180
What was happening here is that we were calling convertInput which was then returning a Promise that resolved to undefined (since the SQL diff doesn't use a specialized input for that - just the normal DiffEditorInput). But we still were returning an override to this call, which would then call openEditor and repeat the process - getting in an infinite loop.
(note this wouldn't happen for a non-Promise undefined return value, since we don't override in that case)
This was exposed by https://github.com/microsoft/azuredatastudio/commit/0d3112ef35163387cdd0653247f46b9a1c274019 but has been an issue ever since this was originally made - we just never had a case where we were returning a Promise resolving to undefined from a …
> Fix crash when opening SQL diff input

- test/automation/src/sql/configurePythonDialog.ts
- test/automation/src/sql/notebook.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
1. Always use ctrl for run all/make cell shortcuts. These have never been set up to use the windows key so I assume this was just done accidently as a copy/paste (and never noticed since the smoke tests run on a Mac currently)
2. Wait for SQL kernel to be loaded before starting the tests - I was running into an issue where the kernels wouldn't have finished loading yet and so the test would fail if we didn't add the wait there.
> Notebook smoke test fixes

- src/sql/base/parts/editableDropdown/browser/dropdown.ts
This PR fixes #14675 
before
after
> add padding to editable dropdown

- extensions/mssql/config.json
- package.json
- src/sql/workbench/api/common/extHostDataProtocol.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
- test/smoke/src/sql/areas/queryEditor/queryEditor.test.ts
- test/smoke/src/sql/main.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14044
Fixes https://github.com/microsoft/azuredatastudio/issues/10259
See previous PRs for some more explanation of the issues : 
https://github.com/microsoft/azuredatastudio/pull/13503
https://github.com/microsoft/azuredatastudio/pull/14299
Basically - we're putting the full file path URI in the "owner URI" fields to identify which file the query should be applied to. But previously we weren't encoding the paths here before parsing them as a URI - which meant that reserved characters such as %20 were getting turned into their mapped values (`%20` -> a space for example) before being sent to the providers. They then wouldn't be able to find the file because there wasn't a file opened with those decoded values.
So instead we have to …
> Fix URI encoding for connection provider calls

- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
This PR fixes #15079.
User will have to select the entire link: [](), and we will show the title in the 'Text to Display' and link in the 'Address' input box. Once user changes the link or title it will also update the selected text.
> Ability to see and edit links in split view/markdown mode

- src/sql/workbench/browser/modelComponents/dropdown.component.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/13499.
There is special-case logic in the dropdown control to ignore the `editable` flag in accessibility mode.  The event handlers for the read-only dropdown list checks the control is not editable prior to updating the selected value.  This results in the dropdown having the default, potentially incorrect, value resulting in behavior such as what is observed in #13499.
*Target Selection dialog*
*Target Selection toolbar*
> Update drop-down selected value in accessibility mode

- extensions/integration-tests/src/test/notebook.test.ts
- extensions/integration-tests/src/test/notebook.util.ts
Also did some cleanup - I'm not sure where `invocationCount` was supposed to come from but I can't find any documentation about it in mocha and it was just returning NaN in my local runs. We shouldn't really need it anyways - it'd just get reset each time we ran and each test shouldn't be running more than once normally anyways. 
Test build without URI fixes (I expect there to be integration test failures) : https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=101157&view=logs&j=bfccef3f-45d4-504d-9a7f-a8a74922e6bf&t=6a7a61df-4b52-52e2-d763-2058c7ca42b4
Test build with URI fixes : https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=101192&view=logs&j=bfccef3f-45d4-504d-9a7f-a8a74922e6bf&t=6a7a61df-4b52-52e2-d763-2058c7ca42b4
> Add encoded path name tests for SQL kernel

- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
- src/sql/workbench/contrib/notebook/browser/find/notebookFindModel.ts
- src/sql/workbench/contrib/notebook/browser/notebookEditor.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookEditor.test.ts
This PR fixes #15094 and #14455 
We had cleanMarkdownLinks to clean up markdown links back when we didn't use the renderedOutput of the markdown cell, to remove the link syntax with just the link. But we have come a long way with wysiwyg and the old logic doesn't make sense anymore. So removed it.
Added the mode change events to trigger findStateChange -> Previously on edit mode we have a code cell with markdown code and the rendered html text cell but now even in edit mode we can still be on rich text mode only and have only rendered output so updated the logic to check if the markdown is actually visible (which can happen in split view and markdown only mode) and search accordingly.
Also fixed the scroll issue to scroll to the current highlighted node.
> fix the find highlight issues

- src/sql/base/browser/ui/table/asyncDataView.ts
- src/sql/base/browser/ui/table/hybridDataProvider.ts
- src/sql/base/browser/ui/table/media/table.css
- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/base/browser/ui/table/plugins/rowDetailView.ts
- src/sql/base/browser/ui/table/tableDataView.ts
- src/sql/base/common/dataProvider.ts
- src/sql/platform/theme/common/styler.ts
- src/sql/workbench/contrib/assessment/browser/asmtResultsView.component.ts
1. use virtualized list to implement the filter options list, previously we were simply creating N dom elements directly, not really have performance issue but also not accessible
2. accessibility improvements including the keyboard navigation on the list and the total vs selected numbers screen reader improvements.
3. changed the way filters work, now filters are only showing the values that is currently being displayed
4. some margin/padding tweaks to make the right and left sides look the same
It might be easier to just show you what was changed and how it looks in action, I will ping you guys 
tomorrow to do a demo.
before:
after:
The search box area and accessibility improvements are inspired by the vscode quick pick dialog:
> Table Filter improvements

- src/vs/workbench/contrib/welcome/page/browser/welcomePage.contribution.ts
Order matters for the enum definitions.
Also removing the gettingStarted option - it doesn't appear to be working for us (it just opened the release notes for me) and we have our own welcomeTour experience anyways. 
Old : 
Fixed :
> Fix welcome page enum descriptions

- extensions/markdown-language-features/src/commands/openDocumentLink.ts
This PR reverts carbon edit changes added in https://github.com/microsoft/azuredatastudio/pull/11708 to address the below vscode introduced issue which is now fixed:
https://github.com/microsoft/vscode/issues/104267
> undo carbon edit changes for markdown relative links issue

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
There was a bug where the VM assessment page would display MI assessment results, when VM Migrations should not have any assessment issues.  I have fixed this bug and here is the new view:
> Fix VM Page displaying MI assessment results

- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
1. increase the max row count to 5000. when I first introduced this number, I didn't really think too much, later I found notebook also has a max results for query results, so I am using this number too.
2. slickgrid has its own focus management, now that we are adding a bunch of buttons to the header row, I've observed some weirdness while navigating using keyboard, sometimes I can't get to the buttons, sometimes the focus won't go into the grid itself, there is a race condition on who gets the focus, I am changing it so that the buttons are no longer keyboard focusable, add added a shortcut key to open the filter menu, I picked F3 as it is known for search related features. If the accessibility team think we to expose it through keyboard shortcut settings, I can further improve it.
3. …
> a couple more table filter improvements

- extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
- extensions/schema-compare/src/schemaCompareMainWindow.ts
- extensions/schema-compare/src/test/schemaCompare.test.ts
- extensions/schema-compare/src/test/testUtils.ts
- extensions/schema-compare/src/test/utils.test.ts
- extensions/schema-compare/src/utils.ts
fixes https://github.com/microsoft/azuredatastudio/issues/10685
Provides connectionName in place of server if provided by user.
Connection Name provided:
Connection Name not provided:
Unit tests do not seem to compare text but component states.  Will create issue to add unit tests to check text if necessary.
EDIT: Username does not appear if connectionName provided
> ISSUE10685 - Edits schemaCompareDialog to show connectionName if provided

- src/sql/workbench/services/connection/browser/connectionBrowseTab.ts
- src/sql/workbench/services/connection/browser/media/connectionBrowseTab.css
This is part of the browse connection feature GA work.
There is a feature gap for browse Azure resources between the connections view and connection dialog, currently the actions are only available as context menu in the connection dialog, in this PR, I am adding support for inline action bar, just like in the connections view, the actions are only visible when the tree item is focused/selected/hover.
In Connections View:
In Connection Dialog:
Before:
After:
> enable inline actions for connection dialog's browse tab

- src/sql/workbench/contrib/query/browser/gridPanel.ts
- src/sql/workbench/contrib/query/browser/statusBarItems.ts
- src/sql/workbench/services/query/common/query.ts
- src/sql/workbench/services/query/common/queryModel.ts
- src/sql/workbench/services/query/common/queryModelService.ts
- src/sql/workbench/services/query/test/common/testQueryModelService.ts
This PR fixes #14868 
1. The query result selection failed to parse the numbers that are formatted based on current locale. the formatting is done inside the SQL tools service (.NET core), and the original values(culture invariant) are also passed to ADS. instead of using the cell's display value, I am changing it to prefer the cultureInvariantDisplayValue when doing the selection summary calculation.
2. also fixes the issue that when filtered the selection summary still shows the numbers for the values of the original data set.
NOTE: 
1. we are still not handling the values that are not number/decimal typed when returned by SQL Server, for example, if you have a string typed cell display value: '1,2', it will not be recognized as a valid number. extra work of bringing in globalization …
> fix result selection summary issues

- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
This PR fixes #15232.
When the original notebook contains output we also retrieve that and pass that on to the parameterized notebook through the initialContent. As such, we should clear out the outputs of the model contents without affecting the original notebook.
> Fix parameterized notebook output

- src/sql/workbench/services/connection/browser/connectionDialogService.ts
- src/sql/workbench/services/connection/browser/connectionDialogWidget.ts
- test/automation/src/sql/configurePythonDialog.ts
- test/automation/src/sql/connectionDialog.ts
- test/automation/src/sql/notificationToast.ts
- test/automation/src/workbench.ts
Query editor smoke tests timed out while waiting for the Connection Dialog to go away after clicking the Connect button.
I added a retry for clicking the Connect button if the dialog is not gone after 20 seconds.
Notebook smoke tests also timed out while waiting for the Python Configuration Dialog to be gone. 
This is likely because the test was clicking the next button before the page contents finished loading and the button is enabled. 
I ​added a check to make sure the dropdown contents are loaded and modified the selector to make sure that the button is not disabled before clicking it.
> Try to make smoke tests more stable

- src/sql/workbench/api/browser/mainThreadDashboardWebview.ts
- src/sql/workbench/api/browser/mainThreadModalDialog.ts
- src/sql/workbench/api/browser/mainThreadModelViewDialog.ts
- src/sql/workbench/api/browser/mainThreadTasks.ts
With the latest VS Code merge the extension host is now shut down at the end of a test run, which is then causing a bunch of errors similar to this to appear 
```
Method not implemented.: Error: Method not implemented.
at MainThreadModelViewDialog.dispose (file:///C:/src/AzureDataStudio/out/sql/workbench/api/browser/mainThreadModelViewDialog.js:35:19) [<root>]
at ExtensionHostManager.dispose (file:///C:/src/AzureDataStudio/out/vs/workbench/services/extensions/common/extensionHostManager.js:61:30) [<root>]
at ExtensionService._stopExtensionHosts (file:///C:/src/AzureDataStudio/out/vs/workbench/services/extensions/common/abstractExtensionService.js:324:25) [<root>]
at ExtensionService._onExtensionHostExit (file:///C:/src/AzureDataStudio/out/vs/workbench/services/extensions/electron-browser/e …
```
> Fix dipose "method not implemented" errors in MainThread API classes

- extensions/mssql/config.json
Bump SQL Tools Service to 3.0.0-release.97 to pick-up SMO and SqlClient vbump.
> Bump SQL Tools Service to 3.0.0-release.97

- src/sql/platform/connection/common/connectionConfig.ts
- src/sql/platform/connection/test/common/connectionConfig.test.ts
- src/sql/workbench/contrib/dataExplorer/browser/dataExplorer.contribution.ts
- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
- src/sql/workbench/services/connection/browser/connectionBrowseTab.ts
This PR fixes #2799 by adding a user setting (enum) `datasource.connections.sortBy` for connection sorting.
This setting is default to `dateAdded` which aligns with the current implementation so the default order for connections in Saved Connections tab remains unchanged.
Users will be able to select `displayName` which sort saved connections and groups by their display names.
Before:
After:
> add sorting option for saved connections

- src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookExplorerViewlet.ts
- src/vs/workbench/contrib/files/browser/explorerViewlet.ts
https://github.com/microsoft/azuredatastudio/issues/15251
(The only ones missing keybindings were Notebooks and Explorer)
The explorer fix was taken from https://github.com/microsoft/vscode/commit/c11bf9d7dfd561c618b3793e5cd11e4557767c0d (which was done after our merge point). I'm not exactly sure why this change was necessary - it's possible that this was a bug in VS Code too at the merge point we picked up. Didn't see the need to dig into it though since this fixes the issue and is something we'll pick up in the future anyways.
> Add back open view keybindings

- build/package.json
- build/yarn.lock
VS Code has changed how they do releases pretty significantly - so they no longer use the publish.ts script (https://github.com/microsoft/vscode/commit/bbf3ae9b56772f31bf99912c13e6ca548af4e306#diff-527bc1ff28b0ec2f118291b3dd6bd342f075bd06461b6ff9f35d9f90de9f3d3d)
In the merge we picked up a commit to clean up unused dependencies since they were no longer using that - but since we still use the old publish script we need to keep this here for the time being. 
Although we should really look into getting up to date with their publish scripts as well to avoid further issues like this.
> Add back in documentdb dependency

- src/sql/platform/connection/common/connectionConfig.ts
- src/sql/platform/connection/test/common/connectionConfig.test.ts
- src/sql/workbench/contrib/dataExplorer/browser/dataExplorer.contribution.ts
This PR fixes #15272 by using a different config name for connection sorting. The original implementation was in #15229 .
> Use a different config name for connection sorting

- test/smoke/src/main.ts
This PR fixes #15268 
Not sure how does vscode run their smoke test, that seems to be a bad merge on their side that they have nested test suite with same name, the issue is beforeEach and before have different context (this) because they are created in different suite, the parent suite's beforeEach doesn't have `app` property in its context. 
fix:
remove the unnecessary nested test suite so that all the setup are done within the same context (this object).
> fix smoke test failure

- extensions/sql-database-projects/src/common/constants.ts
This PR fixes #15248. This was exposed by the project dashboard changes, since the project's target version information was retrieved every build.
https://github.com/microsoft/azuredatastudio/blob/c58b7d35d781e0e9b8c2e18a299cd66e79cad2d9/extensions/sql-database-projects/src/controllers/projectController.ts#L183
> fix DW sql project build failing

- extensions/azurecore/src/azureResource/tree/flatAccountTreeNode.ts
this is based on a discussion with Karl/Jared/Alan Yu yesterday.
1. leave the resources that have already been loaded when error occurs and show a toast notification for the error.
2. have a custom error message for throttling exception to make it more actionable for users
before
after
> error handling for browse azure resources

- src/sql/workbench/services/connection/browser/media/connectionBrowseTab.css
caused by recent vscode merge, I didn't really spend time digging into what might have happened.
before
after
> fix action label vertical alignment issue

- src/sql/workbench/contrib/dataExplorer/browser/media/connectionViewletPanel.css
- src/sql/workbench/services/objectExplorer/browser/iconRenderer.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/15254
Fixed for both the default and asyncTree
Earlier -
After change -
The connected scenario (green badge) looks the same.
> Adjust icon badge size

- extensionsGallery-insider.json
- extensionsGallery.json
This PR fixes https://github.com/PowerShell/vscode-powershell/issues/2993.
You'll need to upload [the VSIX asset](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/PowerShell/2021.2.2/vspackage) to your own blob storage
> Update PowerShell extension to v2021.2.2

- build/lib/extensions.ts
Recently with the vscode merge, the build/lib folder no longer properly builds. In addition there's a missing import that is removed in the extensions.ts file, but appears in its corresponding json file. This PR adds it back in, as its found in the main vscode branch as well.
> Fix for gulp remote in extensions.ts

- src/sql/platform/credentials/common/credentialsService.ts
- src/vs/workbench/api/browser/mainThreadSecretState.ts
This PR fixes #15299 
root cause:
the ICredentialsService is newly introduced in VSCode, and ADS also has a ICredentialsService, they happen to use the same ID when registering service singleton. so at run time we are getting the ADS version of the service, that is why we are getting the exception and also the reason Karl has commented out some code during code merge.
the fix is to use a different id, I think eventually we will remove our implementation, but I will leave it to @abist to decide.
tested all the api features with the following code:
output
also tested the connection password retrieval.
> fix secrets api issue

- src/vs/workbench/contrib/logs/common/logs.contribution.ts
Just removing clutter since we don't use the settings sync service
> Remove settings sync output channel

- extensions/arc/src/common/utils.ts
- extensions/arc/src/models/postgresModel.ts
- extensions/arc/src/test/models/postgresModel.test.ts
- extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts
This PR is meant to address the issue of the parameters table disappearing after trying to reset a value. 
1.  Instead of repopulating the table every refresh, only values that have been changed get updated within the components
2. Took out calling refresh postgres model after every azdata call since the parameter updates does not depend on the show command
3. Add promise to make sure calling engine settings only happens once at a time. 
This PR fixes #15250
> Fix for PG parameters table disappearing when trying to reset a value

- src/sql/platform/connection/test/common/testConnectionManagementService.ts
- src/sql/workbench/common/editor/query/queryEditorInput.ts
- src/sql/workbench/contrib/commandLine/test/electron-browser/commandLine.test.ts
- src/sql/workbench/contrib/query/test/browser/queryActions.test.ts
This PR fixes #15231
fix: subscribe to the connection change event and update the title when connection changes.
> keep title up to date when connection changes

- extensions/kusto/config.json
- extensions/kusto/package.json
Bumped sqltoolservice version to 99 for Kusto. Bumped Kusto version to 0.5.4
This PR bumps the Kusto version to fix an issue with databases with special characters in the name.
> Kusto to 0.5.4

- .vscode/launch.json
Was looking through launch.json a while back and saw that VS Code had a gulp task for running unit tests in the current file (core only, not extensions). I've wanted similar functionality before, so figured why not fix that to enable it for us too 😄.
Also did some minor cleanup in the launch.json file.
> Enable run unit tests current file and cleanup launch.json

- src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts
- src/vs/workbench/contrib/extensions/browser/extensionsActions.ts
- src/vs/workbench/electron-sandbox/desktop.contribution.ts
This PR fixes #15274
vscode has moved the action from extensionsActions.ts to a extensions.contributions.ts in this commit: https://github.com/microsoft/vscode/commit/a416c1534bb9159c7ad9d88f19d70019ded16a6a#diff-4a5d50360f90c6ae6aefc53feeb1824c570429a00bb07de93e77c97117fa8828
fix:
add the checks to the new location and meanwhile, vscode introduced another entry point for install VSIX: in file explorer when a vsix file is selected, I am also making it go through ADS checks.
> add ADS checks back to install extension workflow

- extensions/arc/src/ui/dialogs/connectControllerDialog.ts
Leaving username and password alone as they are able to end with spaces.
> Trim spaces from arc connect controller dialog

- build/package.json
- build/yarn.lock
Replacing the other PR - just adding back in the rollup module that was removed during the VS Code merge to fix the compile error when building the build folder in dev.
> Add rollup dependency

- src/vs/workbench/browser/parts/activitybar/activitybarPart.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/15252
This issue happened because the Activity Bar must have accidentally gotten changed to point to the vscode implementation of the account activity bar and I have just pointed it back to our own implementation
> Fixed Account Icon Issue

- extensions/sql-database-projects/src/common/uiConstants.ts
This PR fixes #15191 
Before changes:
After changes:
> Remove horizontal scrollbar

- extensions/mssql/config.json
Picks up a couple dbpool fixes and the DacFx bump.
> Bump SQL Tools Service to 3.0.0-release.101

- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/sqldbproj.d.ts
- extensions/sql-database-projects/src/test/project.test.ts
This change introduces new boolean flag for `addToProject`, `addScriptItem` and `addFolderItem` APIs that allows to skip files/folders if they are already included in the project file. Original behavior was to throw an error if duplicate entry is encountered, so I kept that as a default (new flag is not set). This new flag allows to reuse the de-dupe code that we otherwise have to add to each consumer of the API.
I started by fixing the original behavior, as it was not always working as expected. In our extension that relies on `addToProject` API we've hit an issue where duplicate items were added and no errors were thrown. There was a test for this scenario, but unfortunately the test had few bugs in it as well, so I addressed that first. First issue with the test code was missing …
> Allow to ignore duplicate entires when adding files to SQL project.

- extensions/azurecore/extension.webpack.config.js
This PR fixes #15391
This PR adds arm-subscriptions and arm-resourcegraph as external dependency to azure core extension. This will prevent the minimization of these libraries in web pack causing the above bug. 
Link for the build
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=103560&view=results
> Fixing subscriptions and azure resource graph across ads.

- src/sql/platform/actions/browser/menuEntryActionViewItem.ts
- src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts
- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
- src/vs/platform/actions/browser/menuEntryActionViewItem.ts
Fixes #15394
With the VS Code merge they changed how menu items were getting their background-image set and now use a couple of new rules that reference a var set by the code. https://github.com/microsoft/azuredatastudio/blob/main/src/vs/platform/actions/browser/menuEntryActionViewItem.css
These rules take precedence over the ones we add inline though (since they're more specific) and as a result that icon is overwritten and since the new var is never set in our code the icon is blank.
This fix isn't ideal - using !important isn't great here. But I was worried that trying to change anything else with the VS stuff would lead to more problems with their icons. If we wanted to fix this in a better way I think it would be best to look at getting rid of this custom logic since I can't really …
> Fix dashboard icons

- src/vs/code/electron-browser/sharedProcess/sharedProcessMain.ts
- src/vs/code/node/cliProcessMain.ts
Our custom event prefix `adsworkbench` got overwritten in the latest VS Code merge, putting it back in.
> Fix event prefix

- extensions/mssql/config.json
This contains a new migration assessment nuget which fixes an issue with being unable to migrate a database with a memory optimized file group
> Bump STS Version to 103

- src/sql/media/icons/loading.svg
- src/sql/media/icons/loading_inverse.svg
- src/sql/workbench/browser/modelComponents/media/loading.svg
- src/sql/workbench/browser/modelComponents/media/loading_inverse.svg
- src/sql/workbench/contrib/query/browser/modelViewTab/media/loading.svg
- src/sql/workbench/contrib/query/browser/modelViewTab/media/loading_inverse.svg
- src/sql/workbench/contrib/tasks/browser/media/loading.svg
- src/sql/workbench/contrib/tasks/browser/media/loading_inverse.svg
- src/sql/workbench/services/dialog/browser/media/loading.svg
- src/sql/workbench/services/dialog/browser/media/loading_inverse.svg
- src/vs/base/parts/tree/browser/loading-dark.svg
- src/vs/base/parts/tree/browser/loading-hc.svg
- src/vs/base/parts/tree/browser/loading.svg
This PR fixes #15395 
seems to be an issue related to the recently introduced svgo css minimizer, in the issue https://github.com/svg/svgo/issues/888, the safest fix I think is to update our SVGs to use % instead of from and to.
verified with this build: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=104114&view=results
> fix animated svg issue

- src/bootstrap-window.js
For https://github.com/microsoft/azuredatastudio/issues/15253
This was changed in the merge but I have no idea why - the URL passed in is vscode so we shouldn't be using azuredatastudio here.
> Fix Issue Reporter

- src/sql/workbench/contrib/welcome/page/browser/welcomePage.css
This PR fixes #15393
In the most recent VSCode merge, we brought in a new version of Chrome in which the column-gap and row-gap support is added: https://web.dev/flexbox-gap/. in welcome page, we are using grid-gap style for the overall layout, and it is a short hand for column-gap and row-gap, and the flex boxes inside it inherits these 2 styles, the fix is to reset the values on the flexbox.
I compared the other places of welcome page and didn't notice any other changes between current build and previous stable build.
the only other place using grid-gap which might be impacted by this is agent:
src\sql\workbench\contrib\jobManagement\browser\media\jobHistory.css
@aasimkhan30  and @abist , could you please see whether this area is impacted and if so apply the same fix there.
> fix welcome page tile spacing issue

- src/sql/base/browser/ui/taskbar/actionbar.ts
- src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15484
Took this from VS Code actionbar, it basically makes it so that we only trigger on KEY_UP if the actionbar also received the KEY_DOWN as well. This fixes the Notebook scenario since the KEY_DOWN was sent to the callout dialog and so even though the actionbar gets the KEY_UP it won't fire the event. 
Something to remember for the future as well - they've also added functionality to support triggering on KEY_DOWN as well through an option passed in to the constructor. https://github.com/microsoft/azuredatastudio/blob/main/src/vs/base/browser/ui/actionbar/actionbar.ts#L90
> Fix actionbar trigger key handling

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/services/workspaceService.ts
- extensions/data-workspace/src/test/workspaceService.test.ts
- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/package.nls.json
- extensions/sql-database-projects/src/test/netCoreTool.test.ts
- extensions/sql-database-projects/src/tools/netcoreTool.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15247 by adding a "Don't ask again" option to not prompt the user to install .NET core if it's not found.
However, adding a third button caused everything to get truncated:
so I had to update the strings a bit:
> Add setting to hide netcore installation prompt

- extensions/integration-tests/src/test/schemaCompare.test.ts
A few schema compare tests started failing after SqlToolsService got updated and https://github.com/microsoft/sqltoolsservice/pull/1188 that includes more errors was included.` GetErrors()` returns both real errors and warnings, so even if a schema compare was a success, it might still have an "error message" that's just a warning. The actual extension product code only shows errors if the compare was not a success which is why manual testing didn't catch this. The integration tests check for no error message explicitly, which is why they started failing.  
The quick fix to get the tests passing again to unblock the builds is to update the schema compare tests to remove this check in the tests for now. @ssreerama will work on the real fix in SqlToolsService to filter out warning messages …
> Fix failing schema compare integration tests

- test/automation/src/sql/configurePythonDialog.ts
- test/automation/src/sql/connectionDialog.ts
- test/automation/src/workbench.ts
Added the setting here to not show the net core prompt: https://github.com/microsoft/azuredatastudio-smoke-test-repo/pull/2
Now theres no longer a need to check for toasts when clicking wizard buttons.
Ran an adhoc build to check: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=104612&view=results
> Smoketests: remove close toast action from dialogs

- src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts
fix the issue that the extension contributed commands in dashboard is not displayed properly.
I will produce a build to check the results.
> fix extension commands loc display issue

- extensions/data-workspace/src/dataworkspace.d.ts
- extensions/data-workspace/src/dialogs/projectDashboard.ts
- extensions/data-workspace/src/test/projectProviderRegistry.test.ts
- extensions/data-workspace/src/test/workspaceTreeDataProvider.test.ts
- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
Updating this for clarity. We were showing the projectProvider to the orcas team today and I noticed it wasn't clear that the projectActions was specifically for the toolbar, not just all the project actions.
> Update project toolbar actions comments and name for clarity

- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
Fix for the first issue tracked here: https://github.com/microsoft/azuredatastudio/issues/14587
this is also a user reported issue, this was mentioned in an issue related to query results rendering. From the users' perspective, it is unpredictable when the filter button will show.
the fix is to always show the filter dropdown button regardless of the enabled state, when the filter is disabled, if user clicks the button, we will show a notification about the user setting that is related to this feature.
> Inform the user about the config for filtering

- samples/sqlservices/package.json
- samples/sqlservices/src/typings/refs.d.ts
- samples/sqlservices/tasks/buildtasks.js
- samples/sqlservices/yarn.lock
sqlservices needs to use the azdata.proposed.d.ts, if we use the definitely typed azdata package, it is very likely to hit issues due to the mismatch between these 2 typing files. update to use local typing file to avoid the issue.
> use local azdata.d.ts for sqlservices

- samples/sqlservices/.gitignore
- src/sql/workbench/browser/modelComponents/media/treeComponent.css
This PR fixes #15521
a while back I updated the checkbox to remove the default margin, it seems this scenario we do need the margins for the model view tree.
with the changes:
> add margin for checkbox in modelview tree

- build/azure-pipelines/sql-product-build.yml
Added timeouts to a few steps - we've seen a couple instances recently where the builds get stuck and hit the max timeout of 5 hours. There's no reason that our builds should take this long so in order to fail faster setting the timeouts (and updating existing ones) to a more reasonable 90 minutes for each step
> Update build timeouts

- src/sql/workbench/browser/modelComponents/treeViewDataProvider.ts
This PR fixes #15526 
root cause:
in this commit: https://github.com/microsoft/vscode/commit/b9b92e3152617ff93e903a1af018ab503eca0d53#diff-e800dadf7ee98022eb1cff5a05d091ee52885bbb48ed0f116cfb404d1320e259R238, vscode added logic to use asTreeItem as the property comparison target, our implementation didn't implement this and caused the loss of our custom properties.
fix:
override the asTreeItem method in our implementation.
after:
> fix tree view issue

- src/sql/base/common/codicons.ts
- src/sql/workbench/contrib/connection/browser/connection.contribution.ts
- src/sql/workbench/contrib/dataExplorer/browser/connectionViewletPanel.ts
- src/sql/workbench/contrib/dataExplorer/browser/dataExplorerViewlet.ts
- src/sql/workbench/contrib/objectExplorer/browser/media/serverTreeActions.css
- src/sql/workbench/contrib/objectExplorer/browser/media/server_page.svg
- src/sql/workbench/contrib/objectExplorer/browser/media/server_page_inverse.svg
- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
- src/sql/workbench/contrib/objectExplorer/test/browser/connectionTreeActions.test.ts
- src/sql/workbench/contrib/objectExplorer/test/browser/serverTreeView.test.ts
- src/sql/workbench/contrib/scripting/test/browser/scriptingActions.test.ts
- src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
- src/sql/workbench/contrib/welcome/page/browser/gettingStartedTour.ts
- src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
- src/sql/workbench/contrib/welcome2/page/browser/az_data_welcome_page.ts
- src/sql/workbench/services/objectExplorer/browser/connectionTreeAction.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
- src/sql/workbench/services/objectExplorer/browser/serverTreeActionProvider.ts
- src/vs/base/common/codicons.ts
In an [incoming VS Code merge](https://github.com/microsoft/vscode/commit/585c5cc04b99ea2a9e03d25035f73c1354188fc0#diff-3e738fc4417c6ddcfa32cbda3356cb2b2b30943137d429757e3d7585764f22b9) they removed the get*Actions functions from View Panes, which means that the servers view that utilized this no longer had any of the titlebar actions displayed.
Instead of pushing it along with thousands of other changes being made for that I figured I'd fix it here now since it shouldn't result in any behavior change and allows for actual reviewing of the changes.
The general idea of the fix for this is simple - we should be using the Menu registry to register actions instead (this is how all of the view panes that I looked at for VS Code does it).
Unfortunately it wasn't so simple in our case as just …
> Update server tree action contributions

- extensions/notebook/src/test/protocol/notebookUriHandler.test.ts
Noticed this URI test was failing on Windows. Local URI paths have to start with a forward slash, since the URL path format is "hostname/path" and we omit the host name for local paths. Unix paths already start with a forward slash, so there's no problem there, but we needed to manually prepend the forward slash to Windows paths.
For example, if we're using the path C:\Users\\[user]\notebook.ipynb on Windows, then the file URI should be file:///C:\Users\\[user]\notebook.ipynb
> Fix notebook file URI test by adding a required forward slash to Windows file paths.

- extensions/integration-tests/src/test/schemaCompare.test.ts
This PR fixes the schema compare test after uncommenting the commented line because of STS change. With the code change in Schema compare in STS, we are now filtering out the fatal error messages form warning messages and allowing only error related messages to ADS.
> Schema Compare failing test condition set to uncomment state.

- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR addresses #15544.
Ensures that Kusto Notebook with language_info containing kusto still opens up with Kusto kernel properly. 
Fixes when a user changes from Kusto (kernel alias) to another kernel by ensuring we update the language_info to use the selectedKernel language_info, and not the current kernelAlias.
> Fix changing kernels from kusto to other kernels

- extensionsGallery-insider.json
- extensionsGallery.json
This PR adds langpacks for ADS version 1.29 using the ones generated from ADS build.
> Langpack update to 1.29

- build/azure-pipelines/linux/sql-product-build-linux.yml
- package.json
This is a working PR to enable extension publishing during CI builds.  The previous webmode commit broke this.  Other aspects to this change are in the distro repo.
> Fix extension publishing during CI build

- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts
This PR fixes #15443. Also noticed another bug where the location dropdown wasn't getting updated when switching from the system db radio button to project radio button, so fixing that here too. 
before:
Fixed:
> Fixing a couple database reference dialog bugs

- src/sql/base/browser/ui/panel/tabActions.ts
- src/sql/platform/accounts/common/accountActions.ts
- src/sql/workbench/browser/actions.ts
- src/sql/workbench/browser/scriptingActions.ts
- src/sql/workbench/contrib/assessment/browser/asmtActions.ts
- src/sql/workbench/contrib/assessment/test/browser/asmtActions.test.ts
- src/sql/workbench/contrib/charts/browser/actions.ts
- src/sql/workbench/contrib/dashboard/browser/core/actions.ts
- src/sql/workbench/contrib/dashboard/browser/dashboardActions.ts
- src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerActions.ts
- src/sql/workbench/contrib/dashboard/browser/widgets/insights/actions.ts
- src/sql/workbench/contrib/editData/browser/editDataGridActions.ts
- src/sql/workbench/contrib/editData/browser/gridActions.ts
- src/sql/workbench/contrib/extensions/browser/extensionsActions.ts
- src/sql/workbench/contrib/jobManagement/browser/jobActions.ts
- src/sql/workbench/contrib/jobManagement/test/browser/jobActions.test.ts
- src/sql/workbench/contrib/notebook/browser/cellToolbarActions.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/codeActions.ts
- src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts
- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
- src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookActions.test.ts
- src/sql/workbench/contrib/profiler/browser/profilerActions.ts
- src/sql/workbench/contrib/query/browser/actions.ts
- src/sql/workbench/contrib/scripting/browser/scriptingActions.ts
- src/sql/workbench/contrib/tasks/common/tasksAction.ts
- src/sql/workbench/contrib/views/browser/treeView.ts
- src/sql/workbench/services/connection/test/browser/testTreeView.ts
- src/sql/workbench/services/objectExplorer/browser/connectionTreeAction.ts
In a recent [VS Code change](https://github.com/Microsoft/vscode/commit/7031abadeafec54c8876231e3579c938dee6e1a5#diff-f94d2d5f2236e3698d0375242f759563cf9e3e744b06f9f605f87d727c36a3f9) they changed actions to no longer return any values from the run function. This caused a ton of compile errors in places where we overrode the run function with a value with that returned a boolean - so will need to be fixed in order for the VS Code merge with that change to get through. 
Since updating this for our code is going to be a pretty big task LOC-wise I thought it best to do that separate from the VS Code merge (since otherwise trying to review these changes in that would be a lot more difficult). This shouldn't have any impact on the running of the actions in our code base as it is currently - …
> Update action run return type

- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookActions.test.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
- src/sql/workbench/services/notebook/common/notebookConstants.ts
- src/vs/workbench/contrib/notebook/common/notebookCommon.ts
This PR fixes #15170. 
We should indicate the proper formatting and kernels that we support via the documentation. This will be an ongoing effort to indicate which parameterization method the user can utilize and which ones would work best for their use case. Run with parameters focuses on the parameter cell containing syntax as such:
variable = value
variable2 = value2
...
Only parameters that have an assignment using '=' will be parsed properly and as such, any multi-line parameters will not be. If we were to support multi-line parameters then we would have to create a parser to go validate each parameter and its type.
> Run with Parameters learn more link to use correct format and kernels

- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.css
> fix image overflow in an empty notebook cell issue

- src/sql/azdata.proposed.d.ts
- src/sql/base/browser/ui/inputBox/inputBox.ts
- src/sql/workbench/api/common/extHostModelView.ts
- src/sql/workbench/browser/modelComponents/inputbox.component.ts
issues observed in this pr: https://github.com/microsoft/azuredatastudio/pull/15569
1. allow extension to set maxLength for input box
2. fix the issue that placeholder text won't wrap for multiline text area
> fix input box issues

- src/sql/base/browser/ui/table/media/table.css
I deleted the gif images earlier and didn't realized it is being used by the menu items. 
the fix is to update it to use the svg images.
before:
after:
> fix the missing asc/desc icons

- src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts
- src/sql/workbench/contrib/notebook/test/browser/htmlMarkdownConverter.test.ts
This PR fixes #15552. 
Fixes when a user presses enter within the table cell to use <br> to create a new line within the cell. This makes sure the new line is inside the table cell.
Before Fix:
With Fix:
> Fix WYWIWYG Table cell adding new line in table cell

- extensions/azdata/src/azdata.ts
When trying to scale to 0, edit command would not add worker argument: 
CLI output
[2021-06-01T21:48:20.867Z] Executing command: '"C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\wbin\azdata.cmd" arc postgres server **edit -n pgt0** --output json --debug'
> Fix edit command to take in worker count of 0

- src/sql/base/parts/editableDropdown/browser/dropdown.ts
- src/sql/workbench/browser/modal/optionsDialogHelper.ts
- src/sql/workbench/browser/modelComponents/inputbox.component.ts
- src/sql/workbench/contrib/backup/browser/backup.component.ts
- src/sql/workbench/services/connection/browser/connectionWidget.ts
- src/sql/workbench/services/serverGroup/browser/serverGroupDialog.ts
- src/sql/workbench/test/browser/modal/optionsDialogHelper.test.ts
- src/vs/base/browser/ui/inputbox/inputBox.ts
- src/vs/workbench/contrib/remote/browser/tunnelView.ts
This PR fixes #15529
Root cause:
The rename is not committed because it is treated as invalid. the root cause is vscode changed the implementation of validate method of input box component in this commit:https://github.com/microsoft/vscode/commit/e7c84aab5b172cdc59f53141f3e5679ebae13a96#diff-8530ffbbb8892d45476f17f7b5bb48305ae674ad618f9852307144a33831c588R401. 
Previously, it will return a boolean value indicating whether the input box value is valid, after this commit, it is returning messageType, undefined means valid which is the opposite of its previous behavior. in the recent merge, we kept its old behavior and but didn't update the code that is responsible for file/folder renaming: https://github.com/microsoft/azuredatastudio/blob/main/src/vs/workbench/contrib/files/browser/views/exp …
> fix the input box validation

- i18n/ads-language-pack-pt-BR/package.json
In the older langpacks, the language id for Portuguese was lowercase, while the folder was capitalized. This PR restores that and the resulting vsix package is properly capitalized, matching the extension gallery entry.
This PR fixes #15639
> fix for Portuguese

- extensionsGallery-insider.json
- extensionsGallery.json
This PR fixes #15680.
VSIX from the release build: https://mssqltools.visualstudio.com/_apis/resources/Containers/3115191/drop?itemPath=drop%2Fextensions%2Fsql-database-projects-0.10.0.vsix
> Updating extensionGallery and extensionGallery-insider for Sql Db Projects 0.10.0

- extensions/dacpac/src/wizard/api/utils.ts
The function isn't part of a class so shouldn't be using this
> Fix dacpac utils function

- extensions/arc/package.json
We still provide customer the flexibility to change the number of workers when they deploy. We just lead with a default of 2 workers.
> Changed default 2

- extensions/notebook/src/dialog/createBookDialog.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15712 - don't replace the value if the user didn't select anything
> Fix create book dialog clearing input boxes on browse cancel

- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15663
Pathname will always have a preceeding / per https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/pathname
So fixed the logic to trim that off when populating the callout dialog. 
Also fixed up the typing while I was here, it's still just assuming that it's actually an HTMLAnchorElement but given the usage that should be safe.
> Trim pathname for link callout file paths

- src/sql/platform/telemetry/common/adsTelemetryService.ts
- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/contrib/telemetry/common/telemetry.contribution.ts
- src/vs/workbench/api/common/extHostCommands.ts
When an extension executes a command contributed by another extension then it never leaves the extension host - calling the contributed command callback directly. This means it doesn't go through the command service in core and so we don't log the telemetry event for that command.
So in order to get an accurate count of command usage I'm adding a call in that scenario to log the event directly. 
I considered exposing the AdsTelemetryService through a proxy directly to avoid having to manually craft the action event - but at this point I don't see that format ever changing and I don't see the need for that kind of functionality for anything else so decided to just use the VS Code telemetry proxy instead and then if we end up needing to send more events in the future we can consider adding …
> Log extension host commands

- test/automation/src/sql/configurePythonDialog.ts
Adding time to wait for the python kernel dependencies to load. 
Smoke test has timed out here in the past:
> Make Python installation smoke test more stable

- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/extHostModelView.ts
- src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
This PR fixes #15691 
usage: `table.selectedRow = row;`
> allow extension to select row in declarative table

- test/automation/src/sql/notebook.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
- test/smoke/src/sql/areas/queryEditor/queryEditor.test.ts
Use revert and close command to close all previous untitled editors/notebooks so that they do not interfere with later tests.
> Re-enable notebook text cell smoke test

- extensions/kusto/config.json
- extensions/mssql/config.json
This is required to enable localization for STS, it adds the latest version of the sqltoolsservice to the extensions that use it.  I am testing this right now with the 1.30 build and will create a port request PR for that as well later.
> Bump sqltoolsservice version in extensions

- src/sql/workbench/contrib/notebook/browser/notebook.css
Fixes https://github.com/microsoft/azuredatastudio/issues/15785
Similar issue to https://github.com/microsoft/azuredatastudio/pull/15786 - action buttons were changed and in this case the way that we insert icons for the Notebook toolbar for the secondary actions ended up with a 0 height (since we're not using codicons).
> Fix missing secondary actions for Notebook editor toolbar

- extensions/machine-learning/src/test/views/utils.ts
- extensions/notebook/src/test/common.ts
- extensions/notebook/src/test/managePackages/managePackagesDialog.test.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/extHostModelView.ts
- src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
@brian-harris noticed that the newly introduced selectedRow of declarative table is not reliable. He was setting dataValues first and then the selectedRow, but the setter of dataValues is not a synchronous call, most of the time the actual values came after the selectedRow is set because of this.
fix:
for backward compatibility, I introduced a new async method but leaving the existing setting untouched.
> fix race condition in declarative table

- extensions/notebook/src/protocol/notebookUriHandler.ts
- extensions/notebook/src/test/protocol/notebookUriHandler.test.ts
This PR fixes #15653.
As per discussion, we do not need to prompt a user to download and open a file. VSCode also does not prompt as well upon opening a [file uri](https://code.visualstudio.com/docs/editor/command-line#_opening-vs-code-with-urls). 
As such we will prompt for HTTPS and HTTP schemas only.
> Do not prompt user on opening Notebooks with File URI

- src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts
This PR fixes #9065 by removing "Edit Data" option on SqlDataWarehouse as this feature is not currently supported for SQLDW.
SERVERS:
AZURE:
Server Management:
SERVERS:
AZURE:
Sever Management:
> remove "Edit Data" menu option for SqlDataWarehouse

- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
- src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts
- src/sql/workbench/contrib/notebook/test/electron-browser/notebookUtils.test.ts
Currently our notebook Rich Text undo/redo functionality is a bit basic, since we don't have all the features of a dedicated Editor. One of the drawbacks of that implementation is that we store a snapshot of the whole cell text in each element of the undo stack. Thus if the user is typing a lot, there will be a buildup of many similar elements in the undo stack, which could take up a nontrivial amount of memory over time if they always leave VSCode open, or if they are frequently making changes to a very large Rich Text cell. This change adds a user setting that sets the max size of the undo stack, so that we don't take up too much space when tracking changes.
> Add max size setting for Rich Text undo history in notebooks.

- src/sql/base/browser/ui/taskbar/media/taskbar.css
- src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.css
- src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.css
- src/sql/workbench/contrib/notebook/browser/cellViews/code.css
This PR fixes #15815
in recent vscode merge, vscode added some css selector that caused our styles not being applied correctly. 
the fix is to use more specific css selectors so that our own css styles can have high priority.
after:
> use more specific css selectors

- src/sql/workbench/contrib/dashboard/browser/widgets/insights/insightsWidget.component.ts
This PR fixes #15818 
during recent vscode merge, the protected modifier for the _config parameter was removed due to the newly introduced override keyword. but the actual protected variable _config in base class is not initialized.
fix: assign the value to this._config before consuming it.
I also checked other classes that extends the dashboardWidget class, and they already have the change applied, seems Charles might have missed this class during the merge.
> fix insights widget issue

- src/vs/base/browser/ui/splitview/paneview.css
Fixes https://github.com/microsoft/azuredatastudio/issues/15783
This was removed in https://github.com/microsoft/vscode/pull/120247 as part of adding the highlighted background when hovering over actions. It's not exactly clear why this was removed - but it's likely the same as the other icon-sizing related stuff where VS Code using the font icons means they don't need to set the background sizes like that (but we do since we're using SVG's)
VS Code contributed icons still appear the same 
Have private build queued to verify built version still has correct ordering for CSS rules.
> Fix view action icon sizes

- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/sql/workbench/browser/modelComponents/declarativeTable.component.html
- src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
- src/sql/workbench/browser/modelComponents/media/declarativeTable.css
This PR fixes #15723 
usage:
column definition:
````
{
displayName: '',
valueType: azdata.DeclarativeDataType.menu,
isReadOnly: true,
width: 30
}
````
data value:
````
{
value: {
commands: ['sqlmigration.openNotebooks',
['sqlmigration.openNotebooks', 'sqlmigration.openNotebooks'],
'sqlmigration.openNotebooks'],
context: 'abc'
}
}
`````
> support menu column

- extensions/notebook/src/common/localizedConstants.ts
- extensions/notebook/src/dialog/createBookDialog.ts
- test/automation/src/sql/createBookDialog.ts
The VS Code merge broke this test - they changed the input box behavior such that by default input boxes no longer set their title attribute to the placeholder value. (see https://github.com/microsoft/vscode/commit/2275dba01afe2b8814d4ebdd67d1027fa51bdcb4 and https://github.com/microsoft/vscode/commit/c2b6d30e9efb9b8a0048bef57acf09c931c8c0c0)
So fixing the smoke tests could have just been updating it to use the placeholder attribute instead, but in thinking about it I'm not really sure that text as placeholder makes sense for these input boxes anyways. Normally placeholders should indicate some example values or something - we already have the title above the input boxes to indicate what these are for. So I removed the placeholder and then just directly added an aria-label attribute on …
> Fix create book dialog smoke test

- src/vs/workbench/contrib/extensions/browser/extensionsList.ts
This PR fixes #15822
the line to set the extension context is missing during the merge: 
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/extensions/browser/extensionsList.ts#L220
and caused the actions and the recommendation widget to not showing correctly.
before:
after:
> fix extension view issues

- extensions/data-workspace/package.json
- extensions/data-workspace/src/common/utils.ts
- extensions/data-workspace/src/dialogs/dialogBase.ts
- extensions/data-workspace/src/dialogs/newProjectDialog.ts
- extensions/data-workspace/src/dialogs/openExistingDialog.ts
- extensions/data-workspace/src/dialogs/projectDashboard.ts
- extensions/data-workspace/src/services/workspaceService.ts
- extensions/data-workspace/yarn.lock
First step of getting this working in VS Code - gracefully handle azdata API not being available.
It's likely I'll be slightly changing the logic as code is added to actually replace the functionality that requires azdata (such as dialogs) - but for now this gets us to the point of being able to load the extension into VS Code
> Handle no azdata API in data-workspace extension gracefully

- test/automation/src/sql/notebook.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
I tried adding some WYSIWYG editor tests, but it looks like we can't set the editor div's inner HTML using the driver methods we have currently.
> Add Markdown Toolbar functionality to notebook smoke tests.

- test/automation/src/sql/configurePythonDialog.ts
Contents from both pages of the Python Dialog are on the DOM, the hidden one has the 'dialogModal-hidden' class. 
I changed the selectors to correctly select items that are not hidden.
Note: `:not(.dialogModal-hidden)` must be placed next to the correct element selector. Ex. previously I placed it in the nextButton selector but that didn't work since the nextButton element doesn't actually have the `.dialogModal-hidden` class, it's parent div (`.footer-button`) is what has the hidden class.
> Fix python dialog selectors in Python smoke test

- test/automation/src/sql/notebook.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
Also re-ordered the tests so that the Python dependent tests go last. This way if Python installation fails, at least other tests can be run beforehand.  (new code cell test starts on line 29 and content of other tests were not changed)
I'll be adding more to the code cell test for intellisense checks.
> Add simple notebook code cell smoke test

- src/vs/workbench/browser/parts/editor/editorGroupView.ts
- src/vs/workbench/browser/parts/editor/tabsTitleControl.ts
This PR fixes #15823
1. double click on the blank editor group area (when no editor is opened)
2. double click on the editor group title blank area
previously we were relying on the editorGroup.onWillOpenEditor event to override the input type and resolve it to UntitledQueryEditorInput, but it is removed in: 
https://github.com/microsoft/vscode/pull/119274/files#diff-4729038e6d08c333e1fca18d18afac8a5a2f7fc6dffd55f0cb16ca66dab09190L562
the fix is to use the editorService.openEditor (which has the override logic and this is the 'New Query' command is leveraging) for the scenarios that are currently broken
after:
> open query editor as default editor

- src/sql/base/browser/ui/taskbar/media/taskbar.css
This PR fixes #15885 
in this commit: https://github.com/microsoft/vscode/commit/7c3f60f86e6776c4a339c23f85fd9a11c3424bbb#diff-addd7132dee13457b17c0ce8af86416722108e69b8a60d63a865f524a8323f5fR19
the align-items property of the toolbar container is changed to 'center' from default value 'stretch', this caused the height of our task separator to become 0 (not visible).
fix: set it to stretch specifically for the separator to fit the container.
> fix separator not visible issue

- src/sql/workbench/contrib/notebook/browser/cellViews/placeholderCell.component.html
- src/sql/workbench/contrib/notebook/browser/cellViews/placeholderCell.component.ts
Fixes #15843, which is asking for screen readers to treat these links as buttons.
After fix:
> Notebooks A11Y: Add button role for Placeholder Links

- extensions/data-workspace/src/main.ts
- extensions/data-workspace/src/services/workspaceService.ts
This PR fixes #15889. 
Fixing 2 problems:
1. When creating a new project that also creates a new workspace, ADS restarts to create and enter the new workspace and the project gets added to the workspace when the extension activates. This part wasn't being awaited, so sometimes the check for not added projects was seeing that the newly added workspace folder, but it was before the project was added to the workspace. 
2. Glob returns forward slash paths, so this was notification was always showing on windows because those forward slash paths were being compared to the project paths in the workspace file which have backslashes on windows.
> fix projects notification showing when it shouldn't

- src/sql/workbench/services/objectExplorer/browser/iconRenderer.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/15877
Before - 
After -
This issue only shows when the option "Use Async Server Tree" is not checked off and thus doesn't need any change for that case.
> Fix icons getting cut off

- extensions/notebook/src/jupyter/jupyterNotebookProvider.ts
The last python notebook smoke test is failing in the product build pipeline because the Jupyter server is shutdown before the notebook finishes loading the Python kernel. It didn't happen before since we weren't closing each notebook after each test (which is what is triggering the timeout for the server to shutdown). And this doesn't happen locally since all the Python notebook tests finish before the 5 minute timeout.
I'm temporarily increasing the timeout to fix the smoke test while I work on reseting the timeout like Charles suggested here: https://github.com/microsoft/azuredatastudio/pull/7744/files#r336047335.
> Increase jupyter server shutdown timeout

- extensions/notebook/package.json
- extensions/notebook/package.nls.json
- extensions/notebook/src/common/constants.ts
- extensions/notebook/src/jupyter/jupyterNotebookProvider.ts
Follow-up to this PR https://github.com/microsoft/azuredatastudio/pull/15899. I'm setting the default timeout back to 5 minutes and will add the setting in the smoke test repo and configure to 10 minutes.
> Add jupyter server shutdown timeout setting

- extensions/data-workspace/src/main.ts
I added these awaits in #15890 because I noticed it was an async function that wasn't being awaited, but weren't actually necessary for the bug fix. Turns out they weren't there because it would block the rest of the data workspace extension getting activated if the notification showed until it got dismissed.
> Remove awaits that were blocking data workspace extension from loading

- src/sql/workbench/contrib/notebook/browser/cellViews/output.component.ts
This PR starts to address https://github.com/microsoft/azuredatastudio/issues/15543. 
Removing the layout call improves the loading time for the 475kb notebook (with result grids) that Julie used by up to 30%.
I did a bunch of testing to make sure removing this does not affect anything. Tested:
- notebooks with large text outputs
- notebooks with result grids of various sizes
- resizing ADS window and then open/run a notebook with outputs
- zoom in and then open/run a notebook with outputs
Please let me know if there are any other things I should test. In addition, here is an ad hoc build if anyone wants to test: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=108751&view=artifacts&pathAsName=false&type=publishedArtifacts
> Remove layout call in output component ngOnInit

- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
This PR partially addresses https://github.com/microsoft/azuredatastudio/issues/15835. 
Tested on mac and windows to make sure old python is removed correctly.
> Remove old python installation after new Python is successfully downloaded

- src/sql/workbench/browser/modelComponents/dropdown.component.ts
Currently we're always creating the dropdown loading component, which means we end up with duplicated select boxes in the DOM. Not only is this unnecessary for most cases but it can cause problems with CSS selectors since the select boxes are very similar.
In general we should really try to avoid hiding elements by using display: none - especially for things that are only conditionally active. 
GIF with both loading dropdowns and non-loading ones (DB is loading, server is normal)
> Hide dropdown loading container when not used

- src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
This PR fixes #15937
turns out the issue is caused by bad css selector in welcome page, it meant to apply the style to the h1.. and p to the welcome page, but it is not written correctly, as a result, the color is applied globally.
fix:
fix the css selector, I tested and it only needs p, h3, and h4.
no impact to the welcome page:
Before:
After:
Migration wizard:
Before:
After:
> fix css selector

- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/vs/code/browser/workbench/workbench-dev.html
- src/vs/code/browser/workbench/workbench-web-dev.html
- src/vs/code/browser/workbench/workbench.html
This PR fixes #15951, the Plotly rendering issue within ADS Web Notebooks was not rendering due to an uncaught promise when trying to locate: plotly.js-dist-min module. As such we need to include this to render Plotly graphs within ADS Web mode. 
Confirmed with latest ADS Web image in the build pipeline that it displays properly show below:
> [ADS Web] Fix Plotly notebook rendering issue 

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/dialogs/openExistingDialog.ts
- extensions/data-workspace/src/main.ts
- extensions/data-workspace/src/services/workspaceService.ts
- extensions/data-workspace/src/test/dialogs/openExistingDialog.test.ts
Since we don't currently support the remote git option (due to lack of the clone API being exposed) the button will just open up the folder browse dialog directly. 
Also cleaning up an unused string and fixing a missing await
> Add open existing project functionality for VS Code

- extensions/resource-deployment/src/test/ui/validation/validations.test.ts
- extensions/resource-deployment/src/ui/modelViewUtils.ts
- extensions/resource-deployment/src/ui/validation/validations.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15957
The problem here was that we were updating the message every time a validation ran if the message was different, and then on the main thread side when the property was updated it would call validate again which would trigger the validation to run again. With one validation this wasn't a problem since it would get set to the single message - but as soon as you added a second validation then the two would be both updating the message every time they ran which would then cause an infinite loop of update property -> validation -> update property as the message switched values for each validation.
The fix is to move that message update logic to the place where we're running all the validations and only update once all the …
> Fix resource deployment validations

- src/sql/workbench/browser/modelComponents/hyperlink.component.ts
- src/sql/workbench/browser/modelComponents/media/hyperlink.css
This PR fixes #15730 
This PR fixes #15741
apply the same outline color we use everywhere else to hyperlink component
> add focus outline style for hyperlink

- resources/xlf/LocProject.json
Currently when localized XLF files are retrieved in the drop file from the azuredatastudio-CI pipeline, they have the very confusing filepath of "/<language_id>/resources/xlf/en/file.<language_id>.xlf" This has been a road bump in regards to automating and simplifying the translation process as the last folder is incorrectly named.
I have read the documentation on onelocbuild: (https://ceapex.visualstudio.com/CEINTL/_wiki/wikis/CEINTL.wiki/107/Localization-with-OneLocBuild-Task?anchor=add-onelocbuild-task-to-build-definition) and following the instructions there, I have changed the output path to "resources/xlf" as "Localized" does not seem to exist in our ADS folders anywhere. Also I changed the CopyOption to having LangIDOnPath, so that creating the i18n.json files will have less …
> Change LocProject to better reflect ADS file structure.

- extensions/sql-migration/src/api/utils.ts
- extensions/sql-migration/src/dialog/assessmentResults/assessmentResultsDialog.ts
- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
- extensions/sql-migration/src/dialog/migrationStatus/migrationStatusDialog.ts
This PR fixes #15855 
* set focus to first control when Assessment results dialog is opened
* implement database filter in assessment results dialog
* block enter key in assessment results filter textbox from closing dialog
* set focus to first control when Migration status dialog is opened
* block enter key in migration status search from closing dialog
> SQL Migration extension - accessibility bug - fixes filter enter and focus

- extensions/import/src/test/wizard/pages/fileConfigPage.test.ts
- extensions/import/src/wizard/api/basePage.ts
- extensions/import/src/wizard/pages/fileConfigPage.ts
- extensions/import/src/wizard/pages/modifyColumnsPage.ts
- extensions/import/src/wizard/pages/prosePreviewPage.ts
- extensions/import/src/wizard/pages/summaryPage.ts
- src/sql/workbench/browser/modelComponents/dropdown.component.ts
This PR fixes the broken next button validation on the import wizard file selection page. 
There is another problem over here which is not addressed by the PR. The loading state of the dropdown is not correctly reflected in the extension. 
I am now invalidating the dropdown when it is in the loading state.
> Fixing next button on flat file wizard file configuration page

- src/sql/workbench/contrib/notebook/browser/cellViews/code.css
- src/sql/workbench/contrib/notebook/browser/notebook.css
This PR fixes https://github.com/microsoft/azuredatastudio/issues/15969 and  fixes https://github.com/microsoft/azuredatastudio/issues/15982 
The uneven padding was causing the highlight to be offset.
> Fix notebook icon highlights

- src/sql/workbench/browser/modelComponents/declarativeTable.component.html
- src/sql/workbench/browser/modelComponents/media/declarativeTable.css
This PR fixes #15773
The truncated checkbox in SQL Migration extensions' Assessment Dialog table can be fully focused using keyboard tabs.
Override default checkbox margins ([PR#15014](https://github.com/microsoft/azuredatastudio/pull/15014))
Ensured changes don't modify the checkbox/check all used in other parts of code. This component is currently used by Modify Columns in the Import extension  ([PR#10751](https://github.com/microsoft/azuredatastudio/pull/10751))
Before:
After:
> Fix truncated focus on checkbox for accessiblity

- extensions/notebook/package.json
- extensions/notebook/package.nls.json
- extensions/notebook/src/common/constants.ts
- extensions/notebook/src/jupyter/serverInstance.ts
This PR fixes #15927
The allow root setting allows the jupyter notebook server to run the notebook as root. This is needed for web mode as there were issues with starting the notebook server due to permission issues.
> Add allow root setting for Ubuntu and Web Mode users

- src/sql/base/browser/ui/taskbar/actionbar.ts
This PR fixes #16015 
In recent VSCode merge, a change to the toolbar was brought in, the keyboard focus will only receive one tab stop: https://github.com/microsoft/vscode/commit/da6a819b54a80c097430ad1ae034531cc607f880
, as a result of this change, ActionViewItems in our actionbar implementation are left not focusable.
this is what vscode is doing, only the first element is focusable
https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/actionbar/actionbar.ts#L328
this is not the ultimate fix for the issue, giving the time we have and focus on other projects, I am making this code change to make the toolbar items keyboard focusable for now and I've created an issue in August milestone to properly fix the issue:
https://github.com/microsoft/azuredatastudio/issues/16016
> make the toolbar items keyboard focusable

- src/sql/workbench/contrib/notebook/browser/cellViews/code.css
This PR fixes #16025 
The issue was caused by this new height setting from vscode merge: https://github.com/microsoft/azuredatastudio/blob/3cb2f552a6f004dccd153577aecfd75f3d1bacae/src/vs/base/browser/ui/toolbar/toolbar.css#L7.
> add height css

- src/sql/workbench/contrib/notebook/browser/notebook.css
Fixes https://github.com/microsoft/azuredatastudio/issues/15981
before 
after:
the offending change was introduced in this PR: https://github.com/microsoft/azuredatastudio/pull/10271, I am not sure why is it needed, I don't see any other impact to the notebook UI after removing it.
> toolbar separator overlapping with other items

- src/sql/workbench/services/connection/browser/media/connectionDialog.css
This PR fixes #15825 
previously @Charles-Gagnon fixed the sizing issue of the places using our own version of taskbar, this place is using the vscode actionbar directly, and I did a search, this is the only place in sql folder using vscode actionbar and showing both text and image. 
by default the width is set to be 16px, the fix is to let the button auto decide its width.
after:
> set the width of the 'clear list' button

- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
This PR fixes #15991. We weren't accounting for the possibility that a publish profile had previously been loaded and already added the sqlcmd table. The model view components can only get added once, but since this was adding a form component group, the title of the group was getting added again when a publish profile with sqlcmd variables is loadedmultiple times and the project didn't have sqlcmd variables.
before:
fixed:
> fix duplicate sqlcmd var header when loading publish profile multiple times

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/targetDatabaseSummary/targetDatabaseSummaryDialog.ts
- extensions/sql-migration/src/wizard/summaryPage.ts
- extensions/sql-migration/src/wizard/wizardController.ts
Reducing the spacing in the summary page.
Before:
After :
Databases to be migrated dialog when network share is selected
Database to be migrated dialog when blobs container is selected
> Migration summary page refresh

- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
This PR fixes #15660. 
The issue was when clicking the insert link dialog the document.getSelection() would return null on anchorNode and therefore would then give the error described in the issue `ERR Cannot read property 'parentNode' of null: TypeError: Cannot read property 'parentNode' of null`. So now that we check the anchornode properly it won't error out and we will open the callout dialog unfilled.
> Fix CalloutDialog not opening after bad link

- extensions/big-data-cluster/src/bigDataCluster/controller/clusterControllerApi.ts
- extensions/mssql/src/hdfs/webhdfs.ts
- extensions/mssql/src/objectExplorerNodeProvider/connection.ts
- extensions/mssql/src/objectExplorerNodeProvider/fileSources.ts
In the end I'm not exactly sure what caused this to break. Both places are using the request library which hasn't been updated so that doesn't seem likely to be the cause. But that uses the https library to do the actual calls so it's likely that either some NodeJS update brought in a new version with changed behavior or VS Code changed the behavior of the default agent.
There were two places this was broken though : 
1. BDC Extension - this was setting the rejectUnauthorized through the agentOptions we passed to the request library - which is supposed to be applied to the agent. But given that we don't specify our own agent it's possible that something changed to make this not be apply correctly. So I'm just setting the option at the top level for the request which will directly be …
> Fix BDC auth

- src/vs/workbench/contrib/files/browser/fileActions.contribution.ts
1. `New Untitled File` opens up a new query. We changed the name in the file menu to `New Query` but not here
2. The title for the `New Untitled Plain File` command was set to the command ID - this should be using the label instead
After :
> Fix new file command titles

- src/sql/base/browser/ui/taskbar/media/taskbar.css
as per @radentonev , adjusting the style of the taskbar separator style.
before:
after:
@chlafreniere , notebook has some custom width set on the buttons, I'll leave it to you to make changes there and remove the custom separator style in notebook
> new taskbar separator style

- resources/xlf/en/arc.xlf
- resources/xlf/en/azurecore.xlf
- resources/xlf/en/notebook.xlf
- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql-migration.xlf
- resources/xlf/en/sql.xlf
This adds in the small changes from the extensions' and core sql strings. This will be for a later language pack or a small update to the existing one once translated. 
One example of a change in the SQL xlf file is the moving of editor names such as notebookEditor, queryEditor, and queryResultsEditor from contribution files to the editor file.  (most of the other changes are strings moved around because they are scanned in a random order)
> Small update to English XLFs

- extensions/arc/package.json
- extensions/arc/package.nls.json
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/browser/modelComponents/text.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15807
Screen reader text : 
`Learn more about Azure Arc enabled Managed Instance  link`
Even though we don't use it here I tested the role attribute and verified it works in case anyone else has need to use it.
> Add accessibility information for MIAA deployment link

- src/vs/workbench/browser/media/style.css
This PR fixes #15767
port the change from vscode: https://github.com/microsoft/vscode/pull/127839
> make dropdown arrow larger to meet accessibility requirement (#127839)

- extensions/notebook/src/book/bookTocManager.ts
Save the original path before moving in case the fs.move method throws an error. 
The recovery method will be called in case of error and it'll move back the files to their original place and will restore the original toc file.
> Set notebook path before moving.

- src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.contribution.ts
This address this issue https://github.com/microsoft/azuredatastudio/issues/15980 regarding duplicate Getting Started item.  I'm removing this item contribution since I don't see this contribution in the latest VS Code source code for this file https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.contribution.ts.
> Remove duplicate Getting Started menu

- src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
- src/sql/workbench/services/queryEditor/common/queryEditorService.ts
- src/sql/workbench/services/queryEditor/test/common/testQueryEditorService.ts
- src/vs/workbench/browser/parts/editor/editorGroupView.ts
- src/vs/workbench/browser/parts/editor/tabsTitleControl.ts
For https://github.com/microsoft/azuredatastudio/issues/16074
Reverting logic back to original method and just changing the input created to be our own (which from talking with the VS Code person writing the override stuff is likely our best choice here)
Changed the query editor service interface to specify returning full UntitledQueryEditorInput for use here. Using interfaces is generally preferred, but we needed these to be full EditorInput objects and given the low use of this service and specialized nature of it I don't see this as being a huge deal here. We can always change it easily enough in the future if needed since it's just an internal service.
> Fix opening new untitled query by double click actions

- src/sql/workbench/services/accountManagement/browser/media/accountPicker.css
for #15820 
in recent vscode merge, the base dropdown style got a new style, justify-content:center, to restore the previous behavior I am adding a width property so that it takes full width.
before:
after:
> left align the account information

- extensions/arc/src/ui/dialogs/connectSqlDialog.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15772
Not the ideal fix, dialogs have logic for picking the first focusable element and focusing that when opened, but that doesn't work for modleview dialogs since the content is all created after that logic is called.
Doing this quick fix now and will plan on coming back to this to investigate further to see if we can fix all modal dialogs to run that logic after the content is created.
> Fix focus element on connect dialog

- resources/xlf/LocProject.json
There was an inconsistency in the tab spacing between new extensions that were added to locproject and the older ones, this PR fixes this issue (This may or may not be related to the issue of why these extensions aren't being recognized by the localization tool)
> Fixed tabs in locProject

- extensions/machine-learning/src/prediction/predictService.ts
- extensions/mssql/src/main.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/browser/mainThreadQueryEditor.ts
- src/sql/workbench/api/common/extHostQueryEditor.ts
- src/sql/workbench/api/common/sqlExtHost.api.impl.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
For https://github.com/microsoft/azuredatastudio/issues/16108
This should also fix https://github.com/microsoft/azuredatastudio/issues/13250
This is the same issue as the other query editor problems - setting the mode is no longer enough to result in a query editor to be opened. So to get around this I'm adding an API similar to vscode.workspace.openTextDocument to open a new query editor.
> Add openQueryDocument API

- extensions/notebook/src/book/bookTocManager.ts
Saved original path in set before attempting to move file.
In case of error every file will be moved to its original location and the toc.yml will be restored.
> [Port] Save notebook original path when after moving

- build/lib/locFunc.js
- build/lib/locFunc.ts
replaces 'end' with on('end' as 'end' prematurely closes the stream before files could be added.
> Fix for rename vscode langpack gulp function

- src/sql/workbench/browser/modelComponents/viewBase.ts
For https://github.com/microsoft/azuredatastudio/issues/16131
This was broken by https://github.com/microsoft/azuredatastudio/pull/15988 (specifically the addition of the new validation on the dropdown component. Commenting that out makes it so this issue doesn't occur)
But as far as I can tell that was mostly just coincident that made the race condition described in the comment be an actual issue.
Description of the issue happening here : 
On the schema compare dialog it starts off with the file picker (...) button for the target section. When that's changed from DACPAC to database the button (and other components) are removed and new ones added in their place. 
But due to the race condition described the component itself was removed from the DOM and then unregistering itself from the …
> Fix component unregistering from parent

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/createSqlMigrationService/createSqlMigrationServiceDialog.ts
- extensions/sql-migration/src/dialog/sqlMigrationService/sqlMigrationServiceDetailsDialog.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
This PR fixes #15765
* adding aria-label to image only button to populate name property.
* fix label to use sentence casing
before:  button with out name
after:  button with name
> add aria-label / name to image only buttons

- src/vs/base/browser/ui/button/button.ts
for #16142
in this VSCode commit: https://github.com/microsoft/vscode/commit/3479bb35904eb046c0974090794cac9c76173796, the logic of removing the tabindex when disabled is deleted, and caused the disabled buttons to be still keyboard focusable. I've emailed the committer for the context since there is no description in the commit.  I only added the logic back for button component since checkbox and menu don't really need this because tabindex=0 were never set on those elements to begin with, but for button, we are using html A tag, without href attribute, the element is not keyboard focusable unless we set tabindex=0.
> make button not focusable when disabled

- build/lib/locFunc.js
- build/lib/locFunc.ts
This PR fixes a bug where the non ADS extensions delete happens BEFORE the vscode langpack folder is renamed to ADS folder, (basically starting the langpack refresh task before the vscode rename task was not completed). Using a synchronous file copy fixes this issue. 
There is a minor issue (due to the asynchronous design of gulp.src) where the message for refresh pops up saying its "completed" when it still has to process the "on-end" part of the pipe stream, but its at the very end and does not affect the resulting json files.
> Removed async copy in rename function

- extensions/notebook/src/book/bookTocManager.ts
This PR is for #15690
One of the entries of the toc had a definition of sections, but didn't have any file entries below it.
So sections were not undefined, but when we tried to check the length then it'll throw an error.
Adding an conditional operator so none of the editing operations fail.
> Add conditional operator before checking length

- extensions/sql-migration/package.json
- extensions/sql-migration/package.nls.json
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
- extensions/sql-migration/src/dialog/migrationStatus/migrationStatusDialog.ts
- extensions/sql-migration/src/wizard/accountsSelectionPage.ts
This PR adds:
* context menu actions to migration status page
* database icon next to database name
* migration status and error images around migration status
* localize status display text
* add Azure account connection and authentication validation to account selection page
Migration status with context menu
Dark theme
Light theme:
In progress:
> sql-migration: update migration status page latest design

- build/lib/locFunc.js
- build/lib/locFunc.ts
The Spanish Langpack for Vscode currently contains a zip folder in it, which doesn't get removed. This code removes any zip folders found in the base directory of the vscode langpack prior to renaming.
> added delete zip files code

- src/sql/base/browser/ui/panel/panel.ts
- src/sql/base/browser/ui/table/table.ts
- src/sql/platform/dashboard/browser/interfaces.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/sql/workbench/browser/modal/modal.ts
- src/sql/workbench/browser/modelComponents/componentBase.ts
- src/sql/workbench/contrib/charts/browser/chartView.ts
- src/sql/workbench/contrib/profiler/browser/profilerEditor.ts
- src/sql/workbench/contrib/query/browser/modelViewTab/queryModelViewTab.ts
- src/sql/workbench/contrib/query/browser/queryResultsView.ts
- src/sql/workbench/contrib/queryPlan/browser/queryPlan.ts
- src/sql/workbench/contrib/queryPlan/browser/queryPlanEditor.ts
- src/sql/workbench/contrib/queryPlan/browser/topOperations.ts
- src/sql/workbench/services/connection/browser/connectionBrowseTab.ts
- src/sql/workbench/services/connection/browser/connectionDialogWidget.ts
- src/sql/workbench/services/dialog/browser/dialogContainer.component.ts
- src/sql/workbench/services/dialog/browser/dialogPane.ts
- src/sql/workbench/services/dialog/browser/wizardModal.ts
- src/sql/workbench/services/restore/browser/restoreDialog.ts
This PR fixes #15740
1. when model view dialog/wizard is launched and loaded, the focus will be set to the first focusable element in the content area when available. if the content is loaded async, this code change will at least make sure the focus is in side the dialog/wizard.
2. while testing I observed a bunch of keyboard navigation issues and turns out they are all related to the way the tabbed panel is designed, it is asking content providers to provide a focus method, as you can see in the deleted code, a lot of them don't have a proper implementation, and caused keyboard focus trapped in the tab header. and some scenarios, it is causing incorrect focus order because of this.
3. also fixed a long standing issue with table keyboard focus management, previously tables are not …
> fix keyboard focus issues

- src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts
- src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts
- src/sql/workbench/contrib/notebook/common/utils.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookMarkdown.test.ts
- src/sql/workbench/contrib/notebook/test/common/utils.ts
This PR addresses #15942. PR is a targeted fix for Windows WYSIWYG issues, as the issue was not reproable on Mac. 
This PR fixes two distinct issues: 
1. Relative Path is incorrectly formatted (fixed using a regex to edit the 
- User inserts an absolute link in WYSIWYG
- exits the cell 
- goes back into the cell and edits the cell (insert a new link)
- switch to split view the link is incorrectly formatted (.\\....\\relativePath) should be (..\\..\\relativePath) - fix shown below.
- Another issue fixed in this PR is that the link resolves incorrectly after exiting the WYSIWYG cell and therefore returns an error message below upon clicking the link: 
I found instead of joining the paths (base notebook folder and target href) incorrectly together we should be resolving it to get the …
> Fix Windows WYSIWYG linking issue (switching to splitview and resolving links in WYSIWYG) 

- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
This PR fixes #15861 
Before: 
After:
> Converting toast to modal dialog to grab focus when cancelling on going migrations.

- src/sql/workbench/contrib/profiler/browser/profilerActions.ts
While helping @aasimkhan30 looking into another issue, I realized I should also be using modal prompt here when we need user confirmation.
before:
after:
> use modal confirmation dialog

- extensions/arc/src/localizedConstants.ts
- extensions/arc/src/ui/dashboards/postgres/postgresExtensionsPage.ts
- extensions/azdata/src/typings/azdata-ext.d.ts
States no extensions are listed without adding a checkbox component. 
Added focus to buttons: Drop button gets focused after checkbox is checked, Add button gets focused once table has refreshed
This PR fixes #16181
> Handle if no extensions listed in PG spec

- src/sql/base/browser/ui/infoButton/infoButton.css
a partner is using the info button component and noticed this issue. (I am using migration extension to repro the issue and take screenshots)
before:
after:
> fix the icon size issue of info button

- src/sql/workbench/api/browser/mainThreadModelViewDialog.ts
- src/sql/workbench/services/dialog/common/dialogTypes.ts
Noticed this while investigating the issue with the model view validation affecting dialog buttons - the code that sets the properties for a dialog button fires the onUpdate event every time a property is changed. This is fine by itself - but the only place we're currently doing that has us always setting all 5 properties and so the event would be fired 5 times and end up going through a whole bunch of extra calls (including telling angular to redraw the UI) which was a huge amount of unnecessary overhead. 
So here I'm just adding a helper function to set all properties and fire the event just once at the end. 
Tested this with a couple of dialogs (including ones that set the button values manually after initial rendering) and things work as expected. 
We could get fancier with the …
> Reduce the number of onUpdate events fired for dialog buttons

- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/extHostModelView.ts
- src/sql/workbench/browser/modelComponents/media/text.css
- src/sql/workbench/browser/modelComponents/text.component.ts
Adds headingLevel to textComponent for displaying text as a header.
This required changing up some of the elements that the component used - since we can't nest h#'s inside of a span. The CSS changes were then made so that the elements all lined up as expected again.
Here's what an example text field looks like with headingLevel set to 1
Note that the large text is expected since it picks up the default styles for the appropriate heading level. Callers can specify their own CSS styles if they want to override that. 
Here's some screenshots of current UI vs UI after change for validation that these don't affect anything else. 
Before : 
After : 
Before :
After: 
Before : 
After:
> Add headingLevel to textComponent

- src/sql/azdata.proposed.d.ts
- src/sql/base/browser/ui/propertiesContainer/media/propertiesContainer.css
- src/sql/base/browser/ui/propertiesContainer/propertiesContainer.component.html
- src/sql/base/browser/ui/propertiesContainer/propertiesContainer.component.ts
- src/sql/base/browser/ui/propertiesContainer/togglePropertiesAction.ts
- src/sql/workbench/browser/modelComponents/propertiesContainer.component.ts
feature request by a partner team.
this is by default not visible.
usage:
```TypeScript
modelView.modelBuilder.propertiesContainer().withProps({ showToggleButton: true }).component();
```
> add toggle button for properties container

- extensionsGallery-insider.json
- extensionsGallery.json
Now targeting extensions/rc1
This is an update to the RC1 extensions gallery with newly updated langpacks, the build to get the vsixes from is located here (currently compiling): https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=111847&view=results
I have tested the langpacks locally (via an adhoc-build identical to that of release/1.31) and they fix the core strings that were previously missing from vscode edits. The extensions so far are not fully translated as they are still the old version. They will be bumped to the new webpacked versions for the August release.
> added updates to extensionsGallery for RC1

- extensions/liveshare/src/providers/connectionProvider.ts
- extensions/mssql/config.json
- extensions/notebook/src/test/common/utils.test.ts
- extensions/notebook/src/test/model/sessionManager.test.ts
- src/sql/azdata.d.ts
- src/sql/workbench/contrib/dashboard/test/electron-browser/propertiesWidget.component.test.ts
- src/sql/workbench/services/connection/test/browser/connectionManagementService.test.ts
I have created this PR today but will merge it tomorrow after a new STS build. This PR adds additional server PR properties like cpu count and ram.
> Adding cpu count and ram size properties to getServerInfo API

- build/lib/locFunc.js
- build/lib/locFunc.ts
Turns out vscode langpacks have the name pt-BR instead of pt-br, this generates the wrong id for the langpacks. To fix this from now on, string replacement has been added.
> Added replacement for name of Portuguese langpack

- extensions/integration-tests/src/onboarding/developers.ts
- extensions/sql-migration/src/dashboard/sqlServerDashboard.ts
This PR fixes #15854 A11y_AzureDataStudioSQLMigration_AzureSQLMigration_DeveloperTool:The role for refresh button is defined as a link.
> Fix #15854 refresh button role

- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
- extensions/sql-database-projects/src/typings/vscode-mssql.d.ts
Hooking up to the changes made in the VS Code MSSQL extension.
Also two minor fixes : 
1. ignoreFocusOut on prompt for connection
2. Hide the profile prompt right after selecting an option. If the MS SQL extension takes a while to respond (usually because it needs to be activated) then we don't want to have it waiting since it seems like it's hung then. 
(I plan on making the sql-database-projects extension actual have a dependency on the mssql extension so that it is already activated before getting to this dialog in the future though, so this shouldn't be needed at that point. But it's still good to have)
> List databases for publish quickpick

- extensions/notebook/src/test/book/bookTrustManager.test.ts
This particular test has been failing intermittently in canary, so marking as unstable as a first step.
Will ensure that we review unstable tests weekly for notebooks.
> Mark unstable book test as unstable

- src/sql/workbench/contrib/query/browser/gridPanel.ts
This option allows hiding the action bar on Plotly tables. This allows tables Notebook Views to look a little more clean when the bar is not needed.
**Normal table layout**
**Table layout with actionbar hidden**
> Allow action bar to be hidden on Plotly tables

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
- extensions/sql-database-projects/src/models/IDeploySettings.ts
- extensions/sql-database-projects/src/test/dialogs/publishDatabaseDialog.test.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
The only difference is the upgradeExisting setting which currently isn't even being used (publish always has upgradeExisting set to true). So to simplify things I combined them into a single IDeploySettings and just had the callback be told specifically whether to deploy or generate a script.
> Combine project deploy settings into one

- src/sql/workbench/contrib/notebook/browser/notebookViews/notebookViewsGrid.component.ts
- src/sql/workbench/services/notebook/browser/notebookViews/autodash.ts
- src/sql/workbench/services/notebook/browser/notebookViews/notebookViewModel.ts
- src/sql/workbench/services/notebook/browser/notebookViews/notebookViews.d.ts
The autodash feature in notebook views creates an initial grid layout for users when a view is created. It is intended to reduce the effort required by the user to start editing their view. Instead of displaying every cell and stacking them vertically like the default notebook layout, we use guidelines to determine which cells are worth displaying and how to arrange them. This is a very basic version, we intend to make it smarter over time.
> Notebook Views autodash feature

- .eslintrc.json
- src/sql/workbench/contrib/notebook/browser/outputs/plotlyOutput.component.ts
Allow Plotly graphs to resize based on the size of the output container itself, not only when the window is resized. This allows graphs contained within cells of the Notebook Views grid to adapt to the size of their container whenever the cell is resized.
**Before**
**After**
> Plotly output resize

- src/sql/azdata.d.ts
DT recently started making changes in preparation for an upcoming TS compiler option https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/#exact-optional-property-types and our file was one of the first ones changed. No issues taking this in since there's no functionality change.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54357/files?file-filters%5B%5D=#diff-e759ad18f00886ca74183c5cb21135970912510d84e07c13d0ac7bb0c50f163b
I'm not planning on going through azdata.proposed.d.ts right now since I don't have an easy way of doing that. When those get merged into azdata.d.ts and we try to make a PR then the DT linter will catch any issues and we can fix them then.
> Update azdata.d.ts for exactOptionalPropertyTypes

- src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookMarkdown.test.ts
This PR fixes #15983. 
The issue occurs when the user directly types in the email address, as the parsing `test@email.com` would double encode the `&` when converting it to a proper `mailto` format. The resulting markdown that is resolved contains the `&amp` and upon clicking the link it would send the improper format to the email client:
In order to fix it, I removed the additional encoding (specifically for emails uri's) to make sure that the `&` is still encoded for other uri schemas.
> Notebook Markdown email rendering fix

- src/sql/workbench/browser/modelComponents/hyperlink.component.ts
- src/vs/workbench/browser/media/style.css
Fixes https://github.com/microsoft/azuredatastudio/issues/15771
This does mean that ALL links in the app are now underlined. I don't think this should be an issue as VS Code doesn't tend to use that many links, but something to keep an eye on and selectively disable if we think it's appropriate. 
@radentonev Does this seem ok with you?
I don't know if we'll ever get context on why they hid the underlining to begin with, it's been like that since the very beginning.
I considered having it be fancier such as only showing the underline on hover - but opted to go for the simpler route for now. We can revisit if we get negative feedback about changing this.
> Fix link accessibilty issues

- test/automation/src/code.ts
waitForTextContent was failing because it's accept function expected a string before but after this PR (https://github.com/microsoft/azuredatastudio/pull/16336/files) we are passing in an IElement instead.
> Fix smoke tests not running

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
- extensions/sql-database-projects/src/models/IDeploySettings.ts
- extensions/sql-database-projects/src/tools/buildHelper.ts
Generate script also works, but there's still a little bit of effort to finish up on the MSSQL extension side to actually display the script (the task sends the script contents but doesn't actually display it in a window).
The TaskExecutionMode stuff is not something I'm super happy about, but I couldn't think of an easier way to fix this and given how it's used it didn't seem like too much of a pain to duplicate it (again) here.
> Hook up sql proj publish

- src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
- src/vs/workbench/services/editor/browser/editorOverrideService.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/16436
Fixes https://github.com/microsoft/azuredatastudio/issues/16435
Fixes https://github.com/microsoft/azuredatastudio/issues/16427
I'm still waiting on hearing back from the people hitting this issue to make sure I'm not missing another scenario, but the specific scenario being fixed here is that when starting up a fresh instance of ADS (i.e. no cached state) the language-based overrides weren't being registered when the editor override service looked for an appropriate editor override to use.
So here's what the order of events for the broken scenario would be : 
1. Launch ADS
2. Language (Mode) service loads its cache (empty currently except for built-in languages)
3. Editor is created, no overrides available so opens as text …
> Fix SQL/Notebook editors opening as plaintext

- src/sql/workbench/contrib/notebook/browser/calloutDialog/common/utils.ts
- src/sql/workbench/contrib/notebook/browser/calloutDialog/imageCalloutDialog.ts
- src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts
- src/sql/workbench/contrib/notebook/test/calloutDialog/linkCalloutDialog.test.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/16189
I added a simple regex to the image and link dialogs that checks for paths wrapped in quotes and then pulls out the inner quoted text.
> Remove double quotes from inserted markdown links

- extensions/arc/src/ui/dialogs/connectSqlDialog.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15808
The color contrast of disabled input fields is currently too low as the issue mentions. I chose not to fix the colors for the disabled input box because according to https://www.w3.org/TR/WCAG21/#contrast-minimum the contrast requirements apply except when `Incidental Text or images of text that are part of an inactive user interface component,`. 
Changing this to be readonly makes more sense anyways since the text is just as important as other fields on the page and so doesn't really make sense to have visually different.
Dark:
Light:
HC:
> Fix arc connect dialog color contrast

- extensions/azcli/src/extension.ts
Disable the warning prompt when starting ADS Dev about the az CLI extension not being installed.
@candiceye Apologies for not catching this during the review, but any such prompts should always have an option to never show the warning again so that people aren't spammed by it if they decide they don't want to update (mostly for dev scenarios where it's more difficult to disable extensions in the repo, but in general just a good user-experience thing to have)
> Disable az cli prompt

- extensions/sql-migration/src/dialog/createSqlMigrationService/createSqlMigrationServiceDialog.ts
The dropdown was storing resource id instead of resource name. This value was passed to API causing an error. The PR fixes that.
> Fixing create sql migration service api call in the migration wizard

- build/gulpfile.sql.js
- build/lib/extensions.js
- build/lib/extensions.ts
- extensions/data-workspace/.vscodeignore
- extensions/data-workspace/package.vscode.json
- extensions/sql-database-projects/.vscodeignore
- extensions/sql-database-projects/package.vscode.json
Add steps for creating separate VSIXs for extensions that we also publish to VS Code - this is needed because there are certain values (such as extension dependencies) which may be different in VS Code and need to be updated.
I haven't done an exhaustive look at all the values in the package.json that would need to be updated - this is just a few starter ones mostly to verify that the logic is working as expected and then I'll follow up with another PR to finish out the process. 
The VSIX's generated will have the name defined in the package.vscode.json - in this case `sql-database-projects-vscode` and `data-workspace-vscode`. I thought this best to clearly differentiate the packages to avoid potential mistakes with installing the wrong one.
> Package VS Code extensions

- src/sql/workbench/contrib/dashboard/browser/containers/dashboardGridContainer.component.ts
This PR fixes #15736 and also fixes #15737 
When zoomed (horizontal scroll bar on the bottom)
Before:
After:
Portrait Mode fixed:
Before:
After:
> Fixing horizontal scroll issue in SQL Migration Dashboard 

- src/sql/azdata.d.ts
1. Removed duplicate title property from ButtonProperties - it now inherits from ComponentWithIconProperties which has the title property on it already https://github.com/microsoft/azuredatastudio/blob/main/src/sql/azdata.d.ts#L3264
2. While fixing this I noticed that ButtonProperties was inheriting from the `ComponentWithIcon` interface. Generally this is incorrect - for ModelView stuff Properties interfaces should generally only be inheriting from other properties. Not the actual component interface definition. In this case it should be a mostly non-breaking change to do this as ComponentWithIcon directly inherited from ComponentWithIconProperties and had no other properties of its own
3. And then I fixed up ComponentWithIcon to inherit from Component itself, which should have been done …
> Fix some ModelView API definitions

- src/sql/workbench/browser/modelComponents/groupContainer.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15728
This is a really odd one. I feel like this is a bug with NVDA, Angular or some combination of the two - if I make it so clicking the button doesn't change the container display then it announces just fine. So something with setting the display on the container is messing with the announce. But nesting it in an empty div fixes it for some reason...
(Narrator is even worse - it doesn't even announce the expanded state when it changes in any scenario, just when you tab over it initially. But it announces it correctly for actual buttons, so maybe some issue with it and the button role?)
I can't seem to repro this outside of ADS so don't really have much to give to the NVDA folks - I'll see if there's any issues that seem similar …
> Fix expanded state announce for dialog headers

- extensions/resource-deployment/src/ui/deployClusterWizard/pages/clusterSettingsPage.ts
- extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts
- src/sql/workbench/browser/modal/modal.ts
Was looking at making the behavior for https://github.com/microsoft/azuredatastudio/issues/15729 better since screen readers would have to tab up to the dialog (which is annoying because they'd have no idea where it was in the DOM), find the show more button and then click it to hear the actual error details.
So I'm making the modal messages read out their description when they're shown - in addition to the message text which is read automatically. 
Also removed a few duplicated error strings that already existed in the loc constants file.
> Add alert for description when modal message is shown

- extensions/data-workspace/src/common/utils.ts
- extensions/sql-database-projects/src/common/utils.ts
This was causing the webpacked extensions to fail since it was thinking it was running with an azdata API (empty object is truthy)
> Fix azdata API check when webpacked

- extensions/data-workspace/package.json
- extensions/data-workspace/src/main.ts
- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/extension.ts
Remove "Manage" and "Schema Compare".
Tested all other actions and they work as expected except for "Create Project from Database". I'm going to look into that one to see how feasible it is to fix up for VS Code.
> Remove unused commands from vs code sql proj

- extensions/data-workspace/src/dataworkspace.d.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/sqldbproj.d.ts
- extensions/sql-database-projects/src/tools/buildHelper.ts
1. Using correct extension name based on context. Not the most elegant but I wanted to avoid having to do a runtime check for these
2. Fix build tools path so we'll copy over the build DLLs and targets file correctly
> Sql Proj VS Code fixes

- src/sql/workbench/browser/modal/modal.ts
- src/sql/workbench/browser/modelComponents/declarativeTable.component.html
- src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
- src/sql/workbench/browser/modelComponents/divContainer.component.ts
- src/sql/workbench/browser/modelComponents/hyperlink.component.ts
- src/sql/workbench/browser/modelComponents/media/declarativeTable.css
1. This PR fixes #15857
2. fixes the issue that pressing enter on the context menu button to open the context menu will cause the dialog to be closed
3. fixes the outline style of the context menu button
before:
after:
4. fixes the issue that pressing enter on the close button will cause the dialog to be reopened
for 1 and 2, I think the issue is probably coming from the recent chromium upgrade, for button and hyperlink, the keydown event when enter is pressed is not stopped when it is handled as mouse click and caused it to bubble up. I have to handle the keyboard event to stop the propagation.
for 4, i changed it to use keydown event to be consistent with the dialog and buttons to avoid needing to handle keyup events too.
> handle the keyboard event properly in hyperlink

- extensions/arc/package.json
- extensions/resource-deployment/src/interfaces.ts
- extensions/resource-deployment/src/localizedConstants.ts
- extensions/resource-deployment/src/ui/modelViewUtils.ts
Infrastructure is just a simple choice of values so we can just use the options field for that - no reason to have a custom type.
> Remove infrastructure from resource-deployment

- extensions/sql-migration/src/models/stateMachine.ts
Encoding user path like telemetry property to base64 to avoid redaction. 
I have tested it through fiddler and I can see the encoded string
> Fixing the redacted migration service id by encoding it to base64

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/sqldbproj.d.ts
- extensions/sql-database-projects/src/test/project.test.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
While using the SQL database projects through the API, I noticed that project may end up in somewhat inconsistent state, where files will be added to the project, but their parent folders will not. This in turn resulted in failure to remove these folders from project - they will show up in the UI tree, but deleting them will cause an error. In order to align with how Visual Studio manages the projects, this change will ensure that all intermediate folders are present in the project, when new files or folders are added.
While this change improves project "correctness" when accessing it through SQL projects extension APIs, there is still a possibility that someone will open an "incorrect" previously created project. This change does not address it and folder removal may still fail.
> Automatically add intermediate folders for SQL project items.

- extensions/sql-migration/src/wizard/databaseBackupPage.ts
This PR fixes 
ADS UI - Clear resource group drop down box and click Next on the Database Backup Wizard - Cannot read property 'displayName' ERROR
> Fixed 'UI hanging on clearing dropdown error' for database backup page

- extensions/sql-migration/src/constants/iconPathHelper.ts
- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
This PR fixes 
- Info icon for dark mode was set to non-existing icon
- Added migration error details to the Error banner in the migration cutover dialog - additional error details added to the banner detail section from the 'Copy Migration Details" button
> Add error details to error banner in migration cutover dialog

- src/sql/workbench/contrib/notebook/test/browser/notebookMarkdown.test.ts
Adds the first set of tests generated from TSG Notebooks that contain snippets of code which will fail if ran using the newer version of marked.js that VS Code has.
As the comment description mentions this is meant to be kind of a staging ground for these - further investigation into them to figure out exactly what breaks and why is something I plan to have happen as a follow-up. Especially since some of these seem to indicate potential bugs in the current rendering we do.
> Add marked.js parse differences tests

- src/sql/azdata.proposed.d.ts
- src/sql/workbench/browser/modelComponents/dropdown.component.ts
This PR adds tooltip to the input box on disabled editable dropdowns. Non-editable dropdowns already show tooltip on input box by default.
This will display tooltip only when editable dropdown is disabled. Similar to normal dropdowns, user can't expand the box for disabled editable dropdowns, so the tooltip is necessary.
Below is an example of a disabled, editable dropdown:
> Add tooltip to input box on disabled dropdowns

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/controllers/mainController.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseQuickpick.ts
- extensions/sql-database-projects/src/typings/vscode-mssql.d.ts
Adds "Create Project from Database" command to VS Code context menus. Doing this will skip prompting the user for a connection - but we will still prompt the user for a database to allow them to change it if they wish (keeping in line with ADS behavior of having a dropdown). If launched from a database we'll put that database at the top of the list.
From command palette
From server node
From database node
> Add Create Proj from DB to VS Code context menus

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/databaseSelectorPage.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
This PR fixes
* adds error handing and an error banner for assessment errors
* fix issue refreshing assessment results for runtime error and database selection changes
* fix issue with assessed and selected database counters on sku recommendation page
* show loader while assessments are re-run
* add context check to improve error handling for vm and mi asset queries
> UI bugbash: sql-migration fix assessment db selection

- src/sql/base/parts/editableDropdown/browser/dropdown.ts
- src/vs/base/browser/ui/contextview/contextview.ts
This PR fixes issue #15499
This PR resolves issue #15499 by correcting the rendering behavior for the select database drop down list when the list is expanded and the ADS shell window is resized. 
Steps to verify fix:
Run a query
Expand the database drop-down
Resize the ADS shell window
Correct & expected behavior: Drop-down doesn't appear at window origin position (0px, 0px) after resize.
Incorrect & previous behavior: Drop down appears at the window origin position (0px, 0px) after resize.
> Fix query database drop-down rendering location after resize

- extensions/sql-migration/src/dialog/migrationStatus/migrationStatusDialog.ts
This PR fixes
* cutover and cancel migration button visibility based on migration state and type
> fix cutover and cancel migration command state management

- src/vs/code/browser/workbench/workbench.ts
This PR is part of fixes for #15962.
Currently the webview endpoint is set to `*.vscode-webview-test.com` which is just a placeholder and will give 404 to webview requests since it doesn't actually exist.
This PR sets the correct local webview endpoint.
This `webviewEndpoint` config should only affect web mode and should not have any impact on desktop builds.
> Use local webview endpoint for web mode

- src/vs/base/test/node/keytar.test.ts
Disable failing keytar test while the break is being investigated.  This test has blocked builds for the past couple days.
> Diasable keytar test blocking build

- src/vs/workbench/api/node/extHostTask.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/16615
Looks like the ext host task system got commented out during the merge.
> Fix tasks system

- extensions/admin-tool-ext-win/package.json
The properties dialog doesn't currently support some types of objects on Azure DBs. Following what SSMS has here for ones that don't have it shown for.
> Don't show properties menu item for some items on Azure DBs

- extensions/notebook/src/test/book/bookTrustManager.test.ts
In the test, we check that the book is not trusted, before setting the book as trusted. 
The problem was that the previous test is the one that sets the book as not trusted and not the current test. Adding this to the test fixes the issue.
> Fix unstable test

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/tools/netcoreTool.ts
This PR fixes #16657.
The basic issue here was that the pop up was an informational message, which has a timeout and hence disappears after that time is reached, leaving user wondering why the projects extension didn't load. Basically the code waits on the input from the disappeared pop-up message and gets stuck there forever.
This PR updated the informational message to be presented as an error message, so that the pop-up never disappears and user knows that it is waiting on an input. Updated the code so that extension activation doesn't depend on its response.
> Update pop-up to be an error message instead of informational message

- extensions/azuremonitor/config.json
- extensions/azuremonitor/package.json
Bumped SqlToolService version to 122. Bumped AzureMonitorLogs version to 0.1.2
> AzureMonitorLogs version bump 0.1.2

- extensionsGallery-insider.json
- extensionsGallery.json
- scripts/validateGalleries.js
Azdata CLI extension has been removed so links to main no longer work. I still plan on keeping this in the gallery for the time being since it still has some marginal usefulness - but this requires changing the links to point to an older tag instead.
> Fix azdata gallery links

- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialogModel.ts
- extensions/sql-migration/src/models/migrationLocalStorage.ts
This PR fixes:
* add ability to show the user provisioning errors
* switch to get migration api that collects migration results based on operationid to see migration state for specific migration instance.  This api replaces a prior get migration api that only returns the latest migration results of last or current attempt.  if operation id is missing from migration context then the create migration operation id is used
* add provisioningError to migration get result to collect additional migration error info
* check for additional migration context error properties to catch provisioning errors
* add logic to remove duplicate error strings
* add additional null checks  to migration context status property reads
* add migration.asyncUrl check around get migration call to validate asyncUrl …
> improve migration context and error loading to improve provisioning error detection

- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
This PR fixes:
* add api support to filter assessment results by target type
* filter assessments for SQL MI target
Before
Assessment with 'Azure SQL Database" results
Server
Database
Assessment with only 'Azure SQL Managed Instance" results
Server
Database
> filter assessment results by SQL MI target type

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/tools/netcoreTool.ts
This PR provides a fix for #16676.
The error condition when dotnet couldn't be found (by running dotnet --version) didn't provide appropriate results, the code should default to present the error that states .NET core isn't installed; but it was instead presenting the installed .NET core version isn't supported- which is incorrect. This is fixed. 
Also, while throwing installation or unsupported error for .NET core, the build failure presented impractical message- this is fixed as well.
The highlighted part doesn't show up because there is nothing in the output pane to look for. As the prior behavior, it still shows the same error twice- once as an error and another to collect data from user (with options).
> Fix incorrect .NET error

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/tools/netcoreTool.ts
Issue: https://github.com/microsoft/azuredatastudio/issues/16657
PR for main: https://github.com/microsoft/azuredatastudio/pull/16660
> Porting fix for a bug where the message type for a sqlproj build failure was informational rather than an error

- extensions/data-workspace/package.json
- extensions/data-workspace/src/common/dataWorkspaceExtension.ts
- extensions/data-workspace/src/common/interfaces.ts
- extensions/data-workspace/src/common/promise.ts
- extensions/data-workspace/src/common/workspaceTreeDataProvider.ts
- extensions/data-workspace/src/dataworkspace.d.ts
- extensions/data-workspace/src/main.ts
- extensions/data-workspace/src/services/workspaceService.ts
- extensions/data-workspace/src/test/workspaceService.test.ts
- extensions/data-workspace/src/test/workspaceTreeDataProvider.test.ts
- extensions/sql-database-projects/src/test/dialogs/addDatabaseReferenceDialog.test.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
Issue: https://github.com/microsoft/azuredatastudio/issues/16227
PR for main: https://github.com/microsoft/azuredatastudio/pull/16650
Code was checking disk for preexisting projects every call, so new projects were getting detected as already there and not actually getting loaded.
Fixing this involved adding a flag to the workspace service, so piping that around meant small touches is many files.  The core fix is consolidated to `workspaceservice.ts`.
> Porting fix for a bug with loading projects from workspace after added

- .eslintrc.json
- ThirdPartyNotices.txt
- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/setup.js
- src/sql/workbench/contrib/notebook/browser/notebookViews/insertCellsModal.ts
- src/sql/workbench/contrib/notebook/browser/notebookViews/notebookViews.component.ts
- src/sql/workbench/contrib/notebook/browser/notebookViews/notebookViewsActions.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookViewsActions.test.ts
- src/vs/code/browser/workbench/workbench-dev.html
- src/vs/code/browser/workbench/workbench.html
- test/unit/electron/renderer.js
- yarn.lock
This PR fixes #16679
I am removing the html-to-image library for now. I need more time to debug this for ADS Web. This feature is not yet public, so it doesn't affect any users. 
Verified that the Web Build docker image loads ADS Web properly.
> Notebook Views Actions fix for ADS Web

- product.json
Replacing with az CLI since the azdata CLI extension is going to be (mostly) deprecated.
> Remove Azdata CLI Ext from recommend extensions

- src/vs/workbench/contrib/welcome/page/browser/welcomePage.contribution.ts
This PR addresses the Preview Welcome page load issue discussed in https://github.com/microsoft/azuredatastudio/issues/16628.  This is basically restoring the code that was previously in this file prior to the recent vscode merge.  The code was missing the `{{SQL CARBON EDIT}}` tags so was likely overwritten during the code merges.
> Use preview welcome page if enabled

- extensions/schema-compare/src/schemaCompareMainWindow.ts
- src/sql/azdata.d.ts
For https://github.com/microsoft/azuredatastudio/issues/16691
This is a targeted fix to reduce chance of other regressions - there is a more ideal long-term fix that I will be working on but that's going to be more complex so for ask mode just doing the smaller simpler fix.
This issue was caused by https://github.com/microsoft/azuredatastudio/pull/16166 - the end result of this was that in the schema compare window we were calling removeItem on the splitview component (that contained the diff editor among other things). The PR linked there fixed a bug where child items weren't being removed properly - but this had the side effect of meaning that these components were being removed and thus also being disposed. This disposed the editor and thus when the splitview was added back in the …
> Fix schema compare diff editor not showing

- src/vs/platform/environment/common/environmentService.ts
Closes https://github.com/microsoft/azuredatastudio/issues/16739
This seems generally useful to have so that users can have separate locations for ADS and VS Code if they want - since not all extensions work in both environments.
> Add new extensions location var

- src/sql/platform/connection/common/constants.ts
- src/sql/platform/connection/test/common/testConnectionManagementService.ts
- src/sql/workbench/contrib/query/browser/queryActions.ts
- src/sql/workbench/contrib/query/test/browser/queryActions.test.ts
This is a substitute for https://github.com/microsoft/azuredatastudio/pull/16485
It fixes https://github.com/microsoft/azuredatastudio/issues/16501
Seems the issue with fetching serverInfo from STS was fixed with Aasim's recent fix. I was able to remove the instance name based off of that.
> Synapse query editor dropdown fix

- src/vs/base/test/node/keytar.test.ts
Re-enabling works fine now: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=115353&view=results
This PR fixes https://github.com/microsoft/azuredatastudio/issues/16663
> Re enable keytar test

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/services/workspaceService.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/16755 (new bug filed for follow-up issue)
Original PR and bug:
Follow-up to https://github.com/microsoft/azuredatastudio/pull/16650 which was to fix the original bug https://github.com/microsoft/azuredatastudio/issues/16227
I missed a flipped boolean that resulted in scanning the disk for projects instead of using the cached list.  As a result, all projects being added were thought to already be there.
> Correcting bug to intentionally read from cached list of projects

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
This PR fixes 
- On clicking Refresh Assessment button, Assessments are re run
> Added Refresh Assessment Button in Azure SQL Target Page

- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
- extensions/sql-migration/src/dialog/migrationStatus/migrationStatusDialog.ts
- extensions/sql-migration/src/models/migrationLocalStorage.ts
- extensions/sql-migration/src/models/stateMachine.ts
This PR fixes adds autoCutoverConfiguration to local storage.
This fixes inconsistency of show/hide on cutover button and shows migration mode even during creating state.
> Add autoCutoverConfiguration to local storage

- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
Migration cutover page:
- display File Table for offline network share migrations.
- fix logic for displaying "no backup files to show" message in the file table.
- temporarily remove the error message "If results were expected, reconfirm the connection to the SQL Server Instance." from the file table.
- hide full backup files, last applied lsn, last applied backup files taken on fields only for blob migrations
https://user-images.githubusercontent.com/14362577/129428046-318e70de-17fa-45a7-b137-c25b60d14235.mp4
Database backup page:
- Network share items are now all hidden when user revisits the database backup page after changing migration mode.
> fix sql migration bugs on showing/hiding content based on scenarios

- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
The logic here was recently changed but the check wasn't updated correctly - it was relying on dbs being undefined to determine whether it had been able to fetch the list of dbs yet so having it initialized to an empty array meant that it skipped the prompt logic. 
Changing it back and adding default empty list for the no-prompt scenario.
> Fix connection prompt for publish database quickpick

- src/sql/workbench/contrib/query/browser/queryActions.ts
- src/sql/workbench/contrib/query/test/browser/queryActions.test.ts
- src/sql/workbench/contrib/query/test/browser/queryEditor.test.ts
while looking into this issue: https://github.com/microsoft/azuredatastudio/issues/16102, I noticed we have a special case for accessibility mode, it was added by me 3 years ago but I didn't add link to the issue in the PR description 😞 , so I don't remember the details, but I don't see a reason we need to special case it now.
> remove special case for query editor's db dropdown

- test/automation/src/sql/configurePythonDialog.ts
The Python smoke test sometimes times out during our product builds. Based on the smoke logs, it timed out while waiting for the install location so I am increasing the wait time for that step.
> Python smoke test: increase wait time for install location

- src/vs/workbench/contrib/extensions/browser/extensionsActions.ts
If an error occurs while trying to install a VSIX (such as invalid version) then it prompts the user to install the extension manually - but the link is for the VS Code marketplace so is broken for us. Fixing it to point to the correct link
> Fix download manually link

- src/sql/workbench/services/connection/browser/connectionDialogWidget.ts
noticed this while working on the required indicator of this dialog.
This PR fixes #16789 
if the element is not a connection profile, wrong information be passed to connection dialog and cause the details area to reset.
> only handle connection profile

- extensions/azurecore/src/azureResource/commands.ts
- extensions/azurecore/src/azureResource/errors.ts
- extensions/azurecore/src/azureResource/interfaces.ts
- extensions/azurecore/src/azureResource/services/subscriptionService.ts
- extensions/azurecore/src/azureResource/tree/accountTreeNode.ts
- extensions/azurecore/src/azureResource/tree/flatAccountTreeNode.ts
- extensions/azurecore/src/test/azureResource/tree/accountTreeNode.test.ts
Currently if a user hits an error trying to fetch subscriptions from any of their tenants then we just fail out and don't let them continue. But stuff can fail for a variety of reasons - for example a tenant may be temporarily inaccessible or require additional login requirements. Sometimes these aren't anything a customer can really do anything about and so with the current behavior they'd be completely blocked from using most of the Azure features in ADS.
This fix here is to move over a couple of places where we were doing that to query for all the subscriptions, but only fail if ALL queries failed - displaying errors for any others that failed while fetching the list. This allows the user to at least use subscriptions from those tenants that succeeded while still notifying them that an …
> Better handle errors fetching subscriptions from subset of tenants

- src/sql/workbench/contrib/tasks/common/tasksAction.ts
This PR fixes #16689 
remove the provider name check as it is not required in the task service (see code below)
with this fix, using the example code provided in the issue description, the extension can receive the status update:
> enable task cancellation for wizard operation

- test/automation/src/sql/configurePythonDialog.ts
This click is not needed since the New Python Installation option is selected by default.
> Remove extra click in python smoke test

- src/sql/workbench/api/common/extHostModelViewDialog.ts
forgot to add this yesterday when I enable the wizard page's custom buttons, the same is done for dialogs and wizard custom buttons in just a few lines below: line 913
> make custom buttons already secondary

- extensions/azurecore/src/azureResource/tree/accountTreeNode.ts
- extensions/azurecore/src/azureResource/utils.ts
- extensions/azurecore/src/test/azureResource/tree/accountTreeNode.test.ts
- extensions/machine-learning/src/common/apiWrapper.ts
- extensions/machine-learning/src/modelManagement/azureModelRegistryService.ts
- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
- src/sql/platform/accounts/common/interfaces.ts
- src/sql/platform/accounts/test/common/testAccountManagementService.ts
- src/sql/workbench/api/browser/mainThreadAccountManagement.ts
- src/sql/workbench/api/common/extHostAccountManagement.ts
- src/sql/workbench/api/common/sqlExtHost.api.impl.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
- src/sql/workbench/services/accountManagement/browser/accountManagementService.ts
Noticed this while fixing something else, but the check here isn't correct since filter doesn't support async functions. You need to generate a mapping and then filter from that if you want to do an async check.
While I was doing this I added a type for the account security token so we don't have to keep manually copying the type definition...
I'm promoting that directly to azdata.d.ts because the type is already used there and this isn't actually adding/changing a type - just giving it a strict definition.
> Fix azure account tree subscription check

- src/sql/workbench/browser/modelComponents/loadingComponent.component.ts
This PR fixes #16692
hook up the child component's validity changed event and trigger the validation.
> hook up validity changed event

- .vscode/launch.json
- Renamed tasks to more clearly indicate what they're doing (note that this meant that some tasks may have had their names changed significantly - for example `Launch azuredatastudio` -> `Launch ADS & Debug Renderer`)
- Grouped tasks according to their function. "Launch", "Debug", "Attach", "Test" and "Web"
- Removed unused tasks - this includes some generic ones like Attach to Search and Attach to CLI that I'm not aware of anyone ever using. We can always add them back in from history/what VS Code has if needed
> Clean up launch tasks

- src/sql/workbench/browser/modelComponents/loadingComponent.component.ts
This PR fixes #16693
when doing layout for the loading component we also need to invoke the layout method for the child component to make sure it is sized properly.
> layout the child component

- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
Just picked some that seem to make sense to promote. Plan on doing a few passes of this - trying to keep each of these small. 
A couple notes : 
1. I was looking at promoting the dialog properties stuff but when taking a closer look at it I'm still not super happy with the current state of the properties so I'd like to keep it in proposed for now
2. I removed the ButtonCell (proposed) interface. It was added in https://github.com/microsoft/azuredatastudio/commit/4a88adffd260393d58fa72f9ece8f8a8392f5bec but I can' t find anywhere where it's actually used - and the `columnName` property doesn't seem to be anything we actually use/need.
> Promote some proposed APIs

- src/sql/workbench/services/query/common/queryModelService.ts
This makes the callbacks set on QueryRunner use the actual QueryRunner's URI instead of the one it was initialized with, this is for handling future cases where the QueryRunner uri must be changed. (Tested and it works the same as it did before)
> added queryRunner.uri to queryModelService

- extensions/azurecore/src/account-provider/azureAccountProvider.ts
- extensions/azurecore/src/azureResource/azure-resource.d.ts
- extensions/azurecore/src/azureResource/interfaces.ts
- extensions/azurecore/src/azureResource/providers/azuremonitor/azuremonitorTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/database/databaseService.ts
- extensions/azurecore/src/azureResource/providers/database/databaseTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/kusto/kustoTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/resourceTreeDataProviderBase.ts
- extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcTreeDataProvider.ts
- extensions/azurecore/src/azureResource/resourceService.ts
- extensions/azurecore/src/azureResource/services/subscriptionFilterService.ts
- extensions/azurecore/src/azureResource/tree/connectionDialogTreeProvider.ts
- extensions/azurecore/src/azureResource/tree/subscriptionTreeNode.ts
- extensions/azurecore/src/azureResource/tree/treeProvider.ts
- extensions/azurecore/src/azureResource/utils.ts
- extensions/azurecore/src/azurecore.d.ts
- extensions/azurecore/src/extension.ts
- extensions/azurecore/src/test/azureResource/tree/accountTreeNode.test.ts
- extensions/azurecore/src/test/azureResource/tree/subscriptionTreeNode.test.ts
- extensions/azurecore/src/test/azureResource/tree/treeProvider.test.ts
Update all azdata.Account type references in AzureCore to use AzureAccount instead so that we get the strong typings for the properties.
@aasimkhan30 You may want to consider doing the same for sql-migration
> azdata.Account -> AzureAccount

- samples/sqlservices/README.md
- samples/sqlservices/package.json
- samples/sqlservices/src/Providers/IconProvider.ts
- samples/sqlservices/src/Providers/connectionProvider.ts
- samples/sqlservices/src/Providers/objectExplorerProvider.ts
- samples/sqlservices/src/controllers/connectionProvider.ts
- samples/sqlservices/src/controllers/mainController.ts
I am working with a partner team, their service has native JavaScript library, so they don't need to use the data-protocol-client, adding sample code to implement providers directly in the extension.
this is still work in progress, I will be adding more stuff/fix issues as we progress.
> sample code to implement providers

- src/sql/base/browser/ui/table/plugins/autoSizeColumns.plugin.ts
- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
Improve grid rendering performance by checking if auto size columns plugin is on. If it is, then don't call setColumns in filter plugin. This prevents the grid from getting re-rendered twice if both plugins are on.
This had a 20% loading time improvement for a 2.9m notebook with ~50 grids.
> Filter plugin: don't set columns if auto size column plugin is also on

- src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts
These aren't used and would just cause confusion currently
> Disable VS Notebook configuration settings

- test/automation/src/sql/configurePythonDialog.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
Breaking the install python step into smaller chunks so we can take a screen shot right after the smoke test fails. Last week the test was failing to get elements on the first page of the dialog so I am adding a screen shot there in case it fails again.
> Take screenshot when python installation smoke test fails

- src/sql/workbench/update/electron-browser/gettingStarted.contribution.ts
- src/sql/workbench/update/electron-browser/gettingStarted.ts
- src/vs/workbench/workbench.desktop.main.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/8468.  Current Getting Started is using Release Notes link.  The Release Notes menu item is coming from default vscode source.
> Fix link for Getting Started command

- samples/sp_whoIsActive/.vscode/launch.json
Fixes issues described in https://github.com/microsoft/azuredatastudio/issues/2768 
Two additional notes : 
1. The server-reports extension was moved so no longer has the launch.json. Just fixing it in another place it was wrong
2. Currently the debug extension isn't working. I'm working on a fix for that being tracked by https://github.com/microsoft/azuredatastudio/issues/16760
> Fix debugger type for sp_whoIsActive

- .vscode/launch.json
add the missing 'attach to render' task, without this, breakpoints in core won't be hit.
> add attach to renderer

- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
This PR fixes #16872 
in this PR https://github.com/microsoft/azuredatastudio/pull/16833/files#diff-6d616df90e2be6440c679403f6e161d5b65c7f91ba86c816789b309a764b7c3cR95, we are using the options without checking for undefined.
fix: add a default options class and use it when not specified.
> fix agent jobs not loading issue

- samples/sqlservices/src/controllers/mainController.ts
- samples/sqlservices/src/featureProviders/objectExplorerProvider.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts
- src/sql/workbench/services/objectExplorer/browser/iconRenderer.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
- src/sql/workbench/services/objectExplorer/browser/serverTreeRenderer.ts
- src/sql/workbench/services/objectExplorer/common/nodeType.ts
- src/sql/workbench/services/objectExplorer/common/treeNode.ts
This PR fixes #16374 
This custom icon path is already supported inside the core, I am adding it to the azdata API so that it can be consumed by the extension authors, also updated the sample code. tested with both default server tree and async server tree.
> allow extension to provide custom icons to data explorer tree

- test/smoke/src/sql/areas/notebook/notebook.test.ts
Adding a screenshot right after the test fails and before the revertAndCloseActiveEditor command is run. For notebooks, there will be two screenshots for each failed test, one before and one after closing the active editor.
> Take screenshot of failed test before closing the active editor

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/controllers/mainController.ts
- extensions/sql-database-projects/src/dialogs/addSqlBindingQuickpick.ts
- extensions/sql-database-projects/src/tools/installPackageHelper.ts
- extensions/sql-database-projects/src/tools/packageHelper.ts
This change makes it so after a sql binding is added using the quickpick added in https://github.com/microsoft/azuredatastudio/pull/16838, the sql bindings package reference gets added to the project using dotnet add package. If the project already has the package reference, it doesn't get added again.
Right now, it'll only add the package reference if there's one AF project in the workspace. If there are multiple, a notification will pop up to make sure the package reference is there for build to work. Created an issue to find the right project to add the reference to tackle later https://github.com/microsoft/azuredatastudio/issues/16911
error when no AF projects found in workspace:
> Add sql bindings package reference to project

- extensions/mssql/src/credentialstore/credentialstore.ts
- extensions/mssql/src/resourceProvider/resourceProvider.ts
- extensions/mssql/src/sqlToolsServer.ts
- extensions/mssql/src/utils.ts
Useful for debugging scenarios. 
Steps to use (will document this elsewhere as a follow-up):
1. Publish STS project you want to debug (such as service layer). This is needed to get full set of dependent assemblies 
2. Set ADS_SQLTOOLSSERVICE env var to publish path (e.g. `C:\src\sqltoolsservice\src\Microsoft.SqlTools.ServiceLayer\bin\Debug\net5.0\publish`
3. Launch ADS
Note that there are 3 "clients" that all come from the same STS folder. If any of them don't exist (because you didn't publish them) then it'll just fall back to using the normal STS install for those ones.
> Add STS root folder override

- extensions/notebook/.eslintrc.json
- extensions/notebook/src/book/bookModel.ts
- extensions/notebook/src/book/bookTocManager.ts
- extensions/notebook/src/book/bookTreeView.ts
- extensions/notebook/src/book/bookTrustManager.ts
- extensions/notebook/src/book/githubRemoteBook.ts
- extensions/notebook/src/common/utils.ts
- extensions/notebook/src/dialog/managePackages/installedPackagesTab.ts
- extensions/notebook/src/dialog/remoteBookDialog.ts
- extensions/notebook/src/extension.ts
- extensions/notebook/src/jupyter/jupyterController.ts
- extensions/notebook/src/jupyter/jupyterNotebookProvider.ts
- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
- extensions/notebook/src/jupyter/serverInstance.ts
- extensions/notebook/src/test/book/bookPinManager.test.ts
- extensions/notebook/src/test/book/githubRemoteBook.test.ts
- extensions/notebook/src/test/common/notebookUtils.test.ts
- extensions/notebook/src/test/managePackages/managePackagesDialogModel.test.ts
- extensions/notebook/src/test/model/jupyterController.test.ts
- extensions/notebook/src/test/model/kernel.test.ts
- extensions/notebook/src/test/model/sessionManager.test.ts
And enable the no-floating-promises rule on the directory
Lots of little issues here - nothing too major that I found but a number of the tests weren't awaiting asserts properly and there were a few cases where we weren't awaiting things that might have caused issues like the create book dialog not awaiting creation of the folder before downloading
> Fix rest of notebook unhandled promises

- test/smoke/src/sql/areas/notebook/notebook.test.ts
This prevents the python wizard from causing other non-python tests to fail.
> Escape any open wizards after each test

- extensions/profiler/package.json
- extensions/profiler/package.nls.json
This PR is a start for fixing the issue: #6327 
The main package for Profiler is not localized and that is responsible for the text of the Launch Profiler Menu Item.
This PR localizes the displayName, description, contribute titles and the category for profiler.
> added localization for profiler

- src/sql/workbench/contrib/notebook/test/browser/notebookMarkdown.test.ts
This test should continue to pass after the fix is made and we switch to the newer marked.js version (can test this by changing the useNewMarkdownRenderer value used by the test)
> Add test for markdown table rendering issue

- src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts
- src/sql/workbench/contrib/query/browser/queryActions.ts
- src/sql/workbench/services/notebook/browser/models/cell.ts
Fixes #3958, which we've recently gotten more feedback around.
Decided to execute the command instead of replicating the implementation of the command to avoid future issues with VS Code merges and avoid code duplication.
@alanrenmsft if this is something that's interesting for query editor, happy to expand this change to query editor and/or edit data as well. I believe this would also match SSMS behavior. Up to you though 😄.
> Hide suggest widget on cell execution

- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
When links are created via the callout dialog in WYSIWYG mode, we didn't include the `title` attribute, and therefore users couldn't see tooltips after creating links.
When changing a cell (WYSIWYG or through markdown) -- or when opening an existing notebook, marked.js will add default `title` attributes for us, so we're just matching that behavior for consistency's sake here.
> Add tooltip for WYSIWYG callout link

- extensions/notebook/src/test/book/book.test.ts
This test was initially marked as unstable due to the CI builds crashing. After further investigation, the real root cause was a race condition when attaching and destroying webviews.
https://github.com/microsoft/vscode/issues/99408
> Mark test as stable again

- scripts/test-unstable.bat
- scripts/test-unstable.sh
- test/unit/electron/renderer.js
This was done in https://github.com/microsoft/azuredatastudio/commit/effa50a9bd107e1ce3c9a397f776dedce33244d9 - but instead we can just surround the text in /'s to have mocha parse it as a regex properly. 
This is being done so that we can use the https://github.com/microsoft/vscode-selfhost-test-provider for our tests since that passes in the regex strings which were then being parsed incorrectly by the regex constructor.
> Revert change to unit test runner grep option

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/common/azureFunctionsUtils.ts
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/common/parseJson.ts
- extensions/sql-database-projects/src/dialogs/addSqlBindingQuickpick.ts
- extensions/sql-database-projects/src/tools/packageHelper.ts
- extensions/sql-database-projects/yarn.lock
This change loads the settings from the local.setting.json if the Azure functions project is found. Most of this logic for loading the settings is copied from the vscode-azurefunctions extension. If no AF project is found or there are multiple AF projects in the workspace, the user is prompted for the setting name (same behavior as before). Todo later is to add an option for adding a new connection string setting.
Settings get loaded if AF project is found:
User is prompted for connection string setting name if no AF project found or multiple:
I also moved out a couple functions from the packageHelper to an AF utils file.
> Load settings from local.settings.json for add sql bindings quickpick

- src/sql/workbench/browser/modal/optionsDialogHelper.ts
This PR handles the case where if a group name is undefined, it is set to a default value, which is currently unlocalized. This PR adds that in and is required to fully complete https://github.com/microsoft/azuredatastudio/issues/6333
> added localization to general in optionsDialogHelper

- src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookMarkdown.test.ts
- src/vs/base/common/marked/marked.js
Fixes #16333.
- Ports marked.js fix ([issue](https://github.com/markedjs/marked/issues/2018), [PR](https://github.com/markedjs/marked/pull/2052)). VS Code was [leveraging marked.js 2.0.0](https://github.com/microsoft/vscode/pull/117714), and this was [fixed in 2.0.4](https://github.com/markedjs/marked/releases/tag/v2.0.4).
- Fixes tests that we created during this process
- Leverages new renderer by default (setting can allow customers to go back to old renderer bits in a pinch)
> Use updated markdown renderer from vscode

- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
-Task 1339618: ADS UI - Uniform table styling on the migration extension - update the backup file table on the migration cutover page
- before:
now:
> Updated Backup File Table Styling Similar to Migration Status Dailog

- package.json
This was accidently scoped down in an earlier PR, reverting back to checking entire extensions directory
> Fix extensions-lint script

- extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts
- extensions/azurecore/src/account-provider/azureAccountProvider.ts
This fixes a bug in device code where if the tenant requests a reauthentication during connection, the reauthentication would go back to AuthCodeGrant since the auth type was incorrectly set during the initial account sign-in.
Here is the prompt when the tenant requests a reauthentication.
Unfortunately, device code can still fail if tenant has additional devicecode auth policies, such as that the machine is using machine management software, etc.  This is still a problem in webmode where the connecting machine is arbitrary Linux container.
> Properly set device code auth type

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dashboard/sqlServerDashboard.ts
This PR 
Adds a button on Migration Status Dialog when the user isnt signed in which would allow the user to jump directly to add Azure account dialog
> Add a button which would allow the user to jump directly to add account dialog from Migration Status Dialog

- .eslintrc.sql.ts.json
- extensions/.eslintrc.json
- extensions/git/.eslintrc.json
- src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookSearch.ts
https://eslint.org/docs/rules/no-cond-assign
Will help prevent issues such as https://github.com/microsoft/azuredatastudio/pull/17002
Disabling for git to avoid having more carbon edits to deal with.
> Add no-cond-assign rule

- test/automation/src/sql/configurePythonDialog.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
- test/smoke/test/index.js
I ran an ad hoc build with the 10 minute timeout and the python test was able to complete successfully. Based on logs from yesterday's product build, the installation took a little over 5 minutes.
> Increase smoke test timeout and python installation timeout

- .github/label-actions.yml
I'm planning to triage through older enhancements and plan to use labels for auto-comments/closing issues.  Please read the comment and let me know if there are suggestions.
> Add Out of Scope label comment

- extensions/sql-database-projects/src/common/telemetry.ts
- extensions/sql-database-projects/src/dialogs/addSqlBindingQuickpick.ts
Adding a couple telemetry points to measure how many times the sql bindings quick pick is opened and how many times a sql binding actually gets added.
> Adding a couple telemetry points for sql bindings quickpick

- extensions/azurecore/src/extension.ts
- extensions/notebook/src/extension.ts
Setting different default value for few settings like devicecode auth and notebook allowRoot for ADS web mode
> Change few default settings for adsweb

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/package.nls.json
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/controllers/mainController.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/deployDatabaseQuickpick.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
- extensions/sql-database-projects/src/models/deploy/deployProfile.ts
- extensions/sql-database-projects/src/models/deploy/deployService.ts
- extensions/sql-database-projects/src/test/deploy/deployService.test.ts
- extensions/sql-database-projects/src/test/utils.test.ts
- extensions/sql-database-projects/yarn.lock
Removed the "Deploy" menu item and instead added "Publish to docker" an option after selecting publish. Now when selecting publish, user see this as options:
If user selects" publish to existing server" publish works as before; 
otherwise, the menu for publish to docker will be shown to use
Also made password for deploy to docker mandatory. the password won't get generated anymore and user has to enter the value. 
Removed the Azure Function integration with deploy for now. Will have to add a new command to do the publish and app integration
> SQL Project - deploy to docker publish option

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/dialogs/deployDatabaseQuickpick.ts
- extensions/sql-database-projects/src/models/deploy/deployProfile.ts
- extensions/sql-database-projects/src/models/deploy/deployService.ts
- extensions/sql-database-projects/src/test/deploy/deployService.test.ts
Adding an option when publishing to docker container to enter the base image. Changed the default base image to SQL server 2019
> SQL Proj - Added an option to deploy to docker to select the base image

- extensions/schema-compare/src/dialogs/schemaCompareOptionsDialog.ts
This PR fixes #16981. We got some feedback that it wasn't obvious that the schema compare results aren't updated when options are changed, so this change makes it a blocking notification so the user needs to acknowledge that they need to recompare to see the options applied.
old:
new:
> Change recompare message after changing options to modal

- src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
This adds a shortcut tied to the grid panel table that deletes the current content of the cell then replaces it with 'NULL', also added support for 'NULL' as a string to be marked as a missing object (this is required as its the only form of 'NULL' (in text form) that can be parsed into STS currently, and it also changes the default value of a NULL cell to 'NULL' when it is clicked.) These changes help bring it more in line with the current version of SSMS. 
This addresses issue #17023
> Add Null Shortcut and added NULL text for default NULL value.

- src/vs/platform/extensionManagement/common/extensionGalleryService.ts
- src/vs/platform/extensionManagement/common/extensionManagement.ts
- src/vs/workbench/contrib/extensions/browser/extensionsViews.ts
This PR adds the ability to hide gallery extensions from the Extension Manager Marketplace UI if the extension has the `'hidden'` flag set.  The extension will still show up in the extension dependencies view and the Installed extensions UIs if applicable.  The use-case is to support extensions taking dependencies on "implementation detail"-type extensions that are needed at runtime but don't make sense to surface to users.
> Add excludeFlags to extenson marketplace query

- src/sql/workbench/contrib/query/browser/queryActions.ts
- src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts
- src/sql/workbench/services/query/common/queryManagement.ts
This PR fixes #17104 by adding a refresh AAD token call before calling query request handler. This allows all components that run query to take advantage of the token refresh call so we don't need to do it multiple times.
The refresh mechanism was initially added with this PR #16936 
I captured the images with following steps:
1. Create a notebook from a server connection with AAD-MFA auth.
2. Wait for 1 hour so AAD token gets expired then run a sql query that requires connection.
Before:
After:
> Add AAD token expiration handling for query runner

- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookActions.test.ts
- src/sql/workbench/services/notebook/browser/models/cell.ts
This PR adds
- the azdata_notebook_guid as an additional property to the RunAll notebook 
- add the azdata_notebook_guid and azdata_cell_guid as properties to the RunCell event 
This will help identify which notebooks and cells are being ran in our telemetry pipeline.
> Add guids to RunAll and RunCell events

- extensions/sql-migration/src/.eslintrc.json
- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/api/utils.ts
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dashboard/sqlServerDashboard.ts
- extensions/sql-migration/src/dialog/assessmentResults/assessmentResultsDialog.ts
- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
- extensions/sql-migration/src/dialog/createResourceGroup/createResourceGroupDialog.ts
- extensions/sql-migration/src/dialog/createSqlMigrationService/createSqlMigrationServiceDialog.ts
- extensions/sql-migration/src/dialog/migrationCutover/confirmCutoverDialog.ts
- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialogModel.ts
- extensions/sql-migration/src/dialog/migrationStatus/migrationStatusDialog.ts
- extensions/sql-migration/src/dialog/sqlMigrationService/sqlMigrationServiceDetailsDialog.ts
- extensions/sql-migration/src/main.ts
- extensions/sql-migration/src/models/migrationLocalStorage.ts
- extensions/sql-migration/src/models/migrationWizardPage.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/accountsSelectionPage.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
- extensions/sql-migration/src/wizard/databaseSelectorPage.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
- extensions/sql-migration/src/wizard/sqlSourceConfigurationPage.ts
- extensions/sql-migration/src/wizard/summaryPage.ts
- extensions/sql-migration/src/wizard/wizardController.ts
This PR fixes
* Add custom eslint rule to require void or await before all async calls
* Fix BackupFileInfo canceled status field name
* Add error handling and error message banner to cutover and cancel migration failures 
- VSO Task 1353075: PPG - ADS UI , surface cutover operation failed message
Cutover error
Cancel migration error
> add error banner for failed migration cutover and cancel migration

- extensions/mssql/config.json
This PR addresses: https://github.com/microsoft/azuredatastudio/issues/3231
by bumping the version of SqlToolsService.
Closing the editor while a query is running seems to correctly cancel the current query running on the sql server and allows the user to reconnect back on the connection to try again. (It originally hanged when trying to reconnect to the connection before this change).
This allows cancellation to work in general, especially in the case of infinite loop and very long running queries.
> Bump version of sqltoolsservice to fix cancellation not working

- extensions/integration-tests/src/test/schemaCompare.test.ts
Marking a couple schema compare integration tests as unstable for now since they've failed a few times in the past month or two.
> Mark schema compare tests as unstable

- extensions/theme-carbon/themes/dark_carbon.json
- extensions/theme-carbon/themes/light_carbon.json
- extensions/theme-defaults/themes/light_vs.json
- src/vs/editor/standalone/common/themes.ts
- src/vs/platform/theme/common/colorRegistry.ts
This adds in automatic lightening of the foreground letters in a dropdown list in case the active selection background color value is not set by a theme. This requires removing the list activeselection background value in carbon-light as setting that value in a light theme will cause the code to use dark letters which blends in.
Port of https://github.com/microsoft/vscode/commit/a79605c9d57b3293a62f309f520c077c348fdcd4 by @aeschli 
This PR fixes #17001
> Port of Vscode fix for colors too close
