microsoft/azuredatastudio

- extensionsGallery-insider.json
ADO build link for ML extension 0.7.0: https://mssqltools.visualstudio.com/_apis/resources/Containers/2754447/drop?itemPath=drop%2Fextensions%2Fmachine-learning-0.7.0.vsix
> Update extensionsGallery-insider.json for ML 0.7.0

- extensions/arc/src/common/utils.ts
- extensions/arc/src/ui/dashboards/postgres/postgresParametersPage.ts
- extensions/arc/tsconfig.json
Perf improvement - add debounce so we aren't updating the table until the user stops typing
> Add debounce to pg parameters search filter

- src/sql/workbench/browser/modelComponents/button.component.ts
- src/sql/workbench/browser/modelComponents/checkbox.component.ts
- src/sql/workbench/browser/modelComponents/componentBase.ts
- src/sql/workbench/browser/modelComponents/declarativeTable.component.html
- src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
- src/sql/workbench/browser/modelComponents/diffeditor.component.ts
- src/sql/workbench/browser/modelComponents/dropdown.component.ts
- src/sql/workbench/browser/modelComponents/fileBrowserTree.component.ts
- src/sql/workbench/browser/modelComponents/formContainer.component.ts
- src/sql/workbench/browser/modelComponents/groupContainer.component.ts
- src/sql/workbench/browser/modelComponents/hyperlink.component.ts
- src/sql/workbench/browser/modelComponents/image.component.ts
- src/sql/workbench/browser/modelComponents/infoBox.component.ts
- src/sql/workbench/browser/modelComponents/inputbox.component.ts
- src/sql/workbench/browser/modelComponents/listView.component.html
- src/sql/workbench/browser/modelComponents/listView.component.ts
- src/sql/workbench/browser/modelComponents/listbox.component.ts
- src/sql/workbench/browser/modelComponents/radioButton.component.ts
- src/sql/workbench/browser/modelComponents/radioCardGroup.component.html
- src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts
- src/sql/workbench/browser/modelComponents/separator.component.ts
- src/sql/workbench/browser/modelComponents/splitviewContainer.component.ts
- src/sql/workbench/browser/modelComponents/tabbedPanel.component.html
- src/sql/workbench/browser/modelComponents/table.component.ts
- src/sql/workbench/browser/modelComponents/toolbarContainer.component.ts
- src/sql/workbench/browser/modelComponents/tree.component.ts
Right now the CSS styles are applied at the angular created element, for example <modelview-text>, this has been fine until recently I was trying to set border to div component, I observed the following:
if we set the styles to the div element, things will be fine:
to actually fix the problem, we need to remove the updateStyle in componentBase class and let each component decide where the style should be applied, actually we already have some components doing this, e.g. text, divContainter, flexContainer. 
during experiment, I noticed it is ok to specify [style.xx] and [ngStyle] in the component, but ngStyle has to be the last one to be specified, to avoid future mistakes, I am overriding the CSSStyle getter to consolidate the CSSStyles when we need. I could simply add the ngStyle to the …
> apply css style at the right element

- extensions/agent/src/dialogs/agentDialog.ts
- extensions/arc/src/ui/components/dashboard.ts
- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/big-data-cluster/src/bigDataCluster/tree/treeNode.ts
- extensions/resource-deployment/src/ui/resourceTypeModel.ts
- extensions/sql-assessment/src/tabs/sqlAssessmentTab.ts
- extensions/sql-migration/src/dialog/assessmentResults/model/assessmentDialogComponent.ts
- extensions/sql-migration/src/models/migrationWizardPage.ts
https://github.com/microsoft/TypeScript/pull/39963
> Remove async keyword from abstract functions

- extensions/admin-tool-ext-win/package.json
- extensions/admin-tool-ext-win/yarn.lock
- extensions/dacpac/package.json
- extensions/dacpac/yarn.lock
- extensions/data-workspace/package.json
- extensions/data-workspace/yarn.lock
- extensions/notebook/package.json
- extensions/notebook/yarn.lock
- extensions/schema-compare/package.json
- extensions/schema-compare/yarn.lock
- extensions/sql-assessment/package.json
- extensions/sql-assessment/yarn.lock
- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/yarn.lock
Adds in adsversion to event properties from extensions
> Update ads-extension-telemetry package

- src/sql/base/browser/ui/selectBox/selectBox.ts
> Fixing Kusto is showing as the default provider in Connection Dialog

- extensions/arc/package.json
- extensions/arc/package.nls.json
- extensions/resource-deployment/package.json
- extensions/resource-deployment/package.nls.json
- extensions/resource-deployment/src/interfaces.ts
- extensions/resource-deployment/src/services/resourceTypeService.ts
- extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts
> Adding help text for resourceTypes

- src/sql/workbench/contrib/notebook/test/electron-browser/notebookModel.test.ts
This PR adds tests for reading and saving multi_connection_mode field to notebook metadata.
> Notebooks: Add unit test for multi_connection_mode metadata 

- extensions/arc/package.json
- extensions/arc/src/test/ui/components/filePicker.test.ts
- extensions/arc/src/test/ui/components/radioOptionsGroup.test.ts
- extensions/arc/yarn.lock
- extensions/resource-deployment/package.json
- extensions/resource-deployment/src/test/ui/validation/modelViewUtils.test.ts
- extensions/resource-deployment/yarn.lock
> Update azdata-test to official Microsoft org version

- extensionsGallery.json
The vsix file is already uploaded here: https://sqlopsextensions.blob.core.windows.net/extensions/machine-learning/machine-learning-0.5.0.vsix
> Update extensionsGallery.json for ML 0.7.0

- .yarnrc
- build/azure-pipelines/win32/ESRPClient/NuGet.config
- package.json
> Pick up electron update

- extensionsGallery.json
build with the two vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=92436&view=artifacts&pathAsName=false&type=publishedArtifacts
> update dacpac and schema compare extensions

- .yarnrc
> Bump electron to 9.4.3

- src/vs/workbench/contrib/extensions/browser/media/extensionsViewlet.css
Typo in CSS file introduced from code merge.
> Fix typo in extension manager CSS file

- src/sql/workbench/api/common/extHostAccountManagement.ts
For https://github.com/microsoft/azuredatastudio/issues/14223
There was a race condition here - we were storing accounts in an instance var `_accounts`, but every time someone called functions such as `getAccountSecurityToken` it would clear that array and then start fetching the accounts again. If multiple calls came in quick succession then one of the executions might be in the middle of running and thus get an empty `_accounts` list instead of the values it had populated before. 
Instead I just removed this and added a helper method `getAllProvidersAndAccounts` which does the same logic that `$getAllAccounts` did before and then returns a mapping of the accounts and their providers. There wasn't any need for us to store the accounts locally since every call would get a refreshed list …
> Fix race condition in account management

- CHANGELOG.md
Update readme for 1.25.3 release
> Update readme for 1.25.3 release

- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/14178
Added a catch block for executing `"${pythonExecutable}" -c "import site;print(site.${sitePath})"` command.
> Continue loading Notebook extension after python command fails

- extensionsGallery.json
Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=92436&view=artifacts&pathAsName=false&type=publishedArtifacts
> update sql-database-projects to 0.6.0

- cgmanifest.json
- package.json
- yarn.lock
Update couple other metadata/dev dependency references to current Electron version
> Add additional electron bump metadata

- src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookExplorerViewlet.ts
Fixes #14239.
Followed changes in dataExplorerViewlet as a guide. Not sure if this link will work or not for folks: https://github.com/microsoft/azuredatastudio/commit/ce612a3d9613a1857772150892e5f9abe1dd44f7#diff-87ed654614f7363c2a7a9ac77a7a5c9bdbabafcfafbbdc69a84d02532be6e57aL112
Before:
After:
> Fix Views not Showing in Notebooks Viewlet

- .yarnrc
- cgmanifest.json
- package.json
- yarn.lock
Port electron bump to release/1.26.  Here is the tracking issue https://github.com/microsoft/azuredatastudio/issues/14234.
> Bump electron to 9.4.3 (#14217)

- extensions/arc/src/ui/dashboards/postgres/postgresParametersPage.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14201
* Search function does looks at all uppercase
* Add toUpperCase call only in filterParameters function
(cherry picked from commit 7a0ac71b984d031ac5f505450fdd55de3aff9d8e)
> [Port] Search function to be case insensitive  (#14196)

- extensions/arc/src/localizedConstants.ts
- extensions/arc/src/models/miaaModel.ts
- extensions/arc/src/models/resourceModel.ts
- extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13373
* Add connect button to MIAA dashboard
* PR comments
(cherry picked from commit da01c75dcf7896e83b79717435c05749554a3e5e)
> [Port] Add connect button to MIAA dashboard (#14183)

- src/sql/workbench/api/common/extHostAccountManagement.ts
(cherry picked from commit d78d89e3260907e26b1f973b3756736b32c1a5ec)
Fixes https://github.com/microsoft/azuredatastudio/issues/14223
> [Port] Fix race condition in account management (#14218)

- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/14178
Cherry picked from commit 800cd2fa8936b9780f885f50479ec2813a97b0e8
> [Port] Continue loading Notebook extension after python command fails

- .github/workflows/ci.yml
- src/vs/base/browser/ui/actionbar/actionViewItems.ts
- src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts
> Turn back on Linux CI test validation

- extensions/notebook/src/book/bookTreeView.ts
> Add await to refresh book method

- extensions/arc/src/common/promise.ts
- extensions/arc/src/common/utils.ts
- extensions/azdata/src/common/promise.ts
- extensions/git/src/util.ts
- extensions/notebook/src/test/book/book.test.ts
- extensions/resource-deployment/src/test/stubs.ts
- extensions/resource-deployment/src/test/utils.ts
The one change in the git extension is just copying over what VS Code has
> Cleanup typings from vs code merge

- extensions/notebook/src/book/bookTreeView.ts
Call initializeContents and trigger the onDidChangeData tree view event.
Previously, we called the fireBookRefresh but due to the debounce decorator the only book that was refreshed was the second one.
This PR fixes #14235
> Re-initialize book contents after editing

- extensions/arc/package.json
- extensions/resource-deployment/package.json
Update to latest released version
> Update min azdata version

- extensionsGallery.json
build with the two vsixs: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=92912&view=artifacts&pathAsName=false&type=publishedArtifacts
> update schema compare and sql database projects

- extensions/arc/package.json
- extensions/azdata/package.json
Get ahead of current RC build versions
> Bump arc and azdata versions

- extensions/arc/package.json
- extensions/resource-deployment/package.json
Update to latest released version
> [Port] Bump min azdata version

- extensions/arc/src/common/utils.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14287
(cherry picked from commit 238a0c60d95a27293b0c7fb1bc9b06119834dec7)
> [Port] Fix error when listing MIAA databases (#14286)

- extensions/dacpac/package.json
- extensions/schema-compare/package.json
- extensions/sql-database-projects/package.json
> bump versions for data developer extensions

- src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
- src/sql/workbench/contrib/notebook/test/electron-browser/notebookEditorModel.test.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
* Two options
* remove commented line and add the null check
* fix tests: pass isDirty explicitly
* remove commented line
Co-authored-by: chlafreniere <hichise@gmail.com>
This PR fixes #14127
> fix for parameterized notebook closure. (#14324)

- src/sql/platform/connection/common/connectionStore.ts
This change allows the connectionWidget to display databases for a server in the connectionWidget.
> Add dstsAuth as option for saved credential in connectionStore.ts

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/workbench/contrib/notebook/browser/turndownPluginGfm.ts
- yarn.lock
* bumped turndown
* fix WYSIWYG test
* remove comment
Co-authored-by: Vasu Bhog <vabhog@microsoft.com>
Bumped turndown version because of lodash security vulnerability
> Bumped turndown version (#14343)

- test/smoke/src/sql/areas/notebook/notebook.test.ts
The notebook smoke tests have been failing during builds. Disabling them temporarily while I look into it.
> Disable nb smoke tests temporarily

- extensions/arc/src/ui/dashboards/postgres/postgresPropertiesPage.ts
> Fixed data controller name on postgres properties page

- extensions/arc/src/ui/dashboards/postgres/postgresPropertiesPage.ts
> Adds copy button to subscription id on postgres properties page

- CHANGELOG.md
> Fixing the release version in changelog

- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/dialog/createMigrationDialog/createMigrationControllerDialog.ts
- extensions/sql-migration/src/models/migrationLocalStorage.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/models/strings.ts
- extensions/sql-migration/src/wizard/accountsSelectionPage.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
- extensions/sql-migration/src/wizard/summaryPage.ts
- extensions/sql-migration/src/wizard/tempTargetSelectionPage.ts
- extensions/sql-migration/src/wizard/wizardController.ts
> Added fetch logic for controllers

- extensionsGallery-insider.json
build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=94093&view=artifacts&pathAsName=false&type=publishedArtifacts
> update sql db proj to 0.7.0 in insiders

- extensions/arc/package.json
- extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts
- extensions/resource-deployment/src/main.ts
- extensions/resource-deployment/src/services/resourceTypeService.ts
- extensions/resource-deployment/src/ui/modelViewUtils.ts
- extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14078
> Default to current controller when deploying from Arc dashboard

- extensions/machine-learning/src/views/dataInfoComponent.ts
- extensions/machine-learning/src/views/widgets/dashboardWidget.ts
- extensions/sql-migration/src/dashboard/sqlServerDashboard.ts
- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/extHostModelView.ts
- src/sql/workbench/browser/modelComponents/componentBase.ts
- src/sql/workbench/browser/modelComponents/componentWithIconBase.ts
- src/sql/workbench/browser/modelComponents/iconUtils.ts
- src/sql/workbench/browser/modelComponents/tabbedPanel.component.ts
- src/sql/workbench/browser/modelComponents/table.component.ts
Closes https://github.com/microsoft/azuredatastudio/issues/14411
> Add IconPath type

- src/sql/workbench/browser/modal/modal.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
Notebook smoke tests failed due to behavior changes in the Configure Python Wizard. This PR reverts the behavior change and turns the smoke tests back on.
> Fix notebook smoke tests

- extensions/resource-deployment/src/ui/modelViewUtils.ts
This adds in support for passing in initial values for Azure fields.
The current behavior is such that if values are passed in then it's assumed all necessary values are passed (subscription, resource group and optionally location) and as such will remove the account picker.
This may not support all scenarios that we'll need in the future - but for the time being I don't know of anyone else planning on using this feature and so am trying to keep this scoped down to the specific scenarios that are using it (in this case deploying an Arc controller from the portal)
What it looks like with the values passed in : 
Without values (normal default mode, should be the same):
> Add support for initial values of Azure fields in resource deployment

- build/hygiene.js
- package.json
Fix up the last one that needed a distro update
> Standardize SQL CARBON EDIT tag

- extensions/kusto/config.json
- extensions/kusto/package.json
> Update Kusto Version and ToolService Version

- extensions/resource-deployment/src/main.ts
- extensions/resource-deployment/src/services/uriHandlerService.ts
- extensions/resource-deployment/src/test/services/apiService.test.ts
- extensions/resource-deployment/src/test/services/resourceTypeService.test.ts
- extensions/resource-deployment/src/test/services/uriHandlerService.test.ts
- extensions/resource-deployment/src/ui/modelViewUtils.ts
Also fixes some issues I found with calculating the initial values (if no initial value was passed in for those fields then they'd throw on the toString() call)
Fixed up some import declarations while I was adding tests
> Add URI handler for resource deployment

- src/sql/azdata.d.ts
> Lint typings

- src/sql/azdata.proposed.d.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/interfaces.ts
- src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts
- src/sql/workbench/services/notebook/browser/models/cell.ts
- src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts
@Charles-Gagnon made a comment on #14449 (which was merged over the weekend). Addressing that here.
> Fixup cell attachment types

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
Changed retrival to retrieval.
This PR fixes #14489
1. Attempt to login to SQL via AAD - MFA with an expired token.
2. Get the error message.
> Fix spelling of retrieval

- src/sql/workbench/browser/modelComponents/tree.component.ts
- src/sql/workbench/browser/modelComponents/treeViewDataProvider.ts
notification service is not provided, will cause a null reference error when needed.
> pass in notification service

- extensions/kusto/package.json
> Updated Kusto version from 1.22 to 1.27

- src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts
- src/sql/workbench/services/notebook/browser/models/cell.ts
> Notebooks: Only serialize cell attachments in JSON if exists

- src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
When checking for the explicit false, forgot to remove the ! and that's the possible culprit of the test failure
> fix the check

- extensionsGallery-insider.json
> Updated Kusto version from 0.4.0 to 0.5.0

- extensions/mssql/config.json
For a few bugs across Schema Compare and project extensions.
> update sqltoolsservice for dacfx

- extensionsGallery.json
Update release gallery with recent extension version. Insiders have this version for a long time already.
> SqlAssessment extension version update to 0.6.0

- samples/sqlservices/src/controllers/treeDataProvider.ts
While working on the tree control for our extension, I noticed that the sample implementation was not optimal. For instance, `vscode.TreeDataProvider.onDidChangeTreeData` should only be called once for the top-most node that has changed, as all children will be refreshed as well.
This change updates the code of the sample to track state changes during propagation and only raise the event for the top-most parent node that has its state changing.
There also was an issue with root node `1` not rendering, which impacted the new algorithm, as it was not refreshing the tree, when invisible root was changing. In order to address this, I updated `getChildren` to actually return the `1` node, when root was requested. This in turn changed the presentation (`1` is now rendered in the tree) and …
> Improve tree control sample.

- extensions/resource-deployment/src/services/tools/azdataTool.ts
- extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14556
Also fixed it so that if there are missing tools we don't prompt for EULA acceptance (since that would then break on those missing tools)
Cleaned up a bunch of unnecessary installation commands for the azdata tool as well - it's installed by the extension so no reason to duplicate all that stuff here.
Currently the experience could be made better by supporting auto-install of the extension/tool, but that would take a bunch more work to modify the existing behavior to support that so I'm just going to put that down as an enhancement to do later.
> Fix error from azdata tool upon startup

- extensions/mssql/config.json
This PR fixes https://github.com/microsoft/azuredatastudio/issues/14551
> Updating sqltoolsservice to update Dacfx

- extensions/sql-assessment/package.json
- extensions/sql-assessment/src/assessmentResultGrid.ts
- extensions/sql-assessment/src/tabs/assessmentMainTab.ts
- extensions/sql-assessment/src/utils.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/extHostModelView.ts
- Fix for async display initial result of an assessment
- Fix for duplication of an instance assessment results after reading from history
> sqlAssessment sync display fix

- extensions/sql-migration/src/dialog/assessmentResults/assessmentResultsDialog.ts
- extensions/sql-migration/src/wizard/wizardController.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/sql/workbench/browser/modal/modal.ts
allow extension author to specify the width of dialogs and wizards directly. with this change, author can use percentage.
> give more flexibility to the dialog width setting

- src/sql/platform/connection/common/constants.ts
- src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts
- src/sql/workbench/services/objectExplorer/test/browser/dragAndDropController.test.ts
This PR fixes #14345
Branches the object bounding characters by provider type - square bracket, quotation mark, and none (for safety on new providers)
> drag n drop bounding characters (pgsql fix)

- extensions/sql-migration/package.json
Bumping to share updated preview build.  @aasimkhan30  please bump this after each build we share so we can easily share out new builds for upgrade.
> Bump migration extension to 0.0.2

- extensionsGallery.json
This has been in insiders for a while now so OK to bring to stable.
> [Stable] Update Data Virt to 1.12.0

- extensions/sql-migration/src/api/utils.ts
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/accountsSelectionPage.ts
Account with multi tenant
Account with single tenant
> Adding Azure AD tenant dropdown in migration wizard

- extensionsGallery.json
Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=96060&view=artifacts&pathAsName=false&type=publishedArtifacts
> update sql database projects to 0.7.1

- extensionsGallery-insider.json
- extensionsGallery.json
> SqlAssessment version 0.6.1

- src/vs/platform/extensionManagement/node/extensionManagementService.ts
- src/vs/workbench/api/common/extHostLanguageFeatures.ts
- src/vs/workbench/api/node/extHostTask.ts
A few tags I found that I missed last time.
> Fix a few more tags

- src/sql/workbench/contrib/dataExplorer/browser/dataExplorerViewlet.ts
- src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookExplorerViewlet.ts
- src/sql/workbench/contrib/welcome/page/browser/gettingStartedTour.ts
- src/vs/workbench/browser/parts/activitybar/activitybarPart.ts
This PR fixes #14615  in March 2021 release.
PR to the main branch #14640
> Fixing welcome page tour. (#14640)

- src/vs/platform/extensionManagement/common/extensionGalleryService.ts
port the fix for this issue to release branch
This PR fixes #14618
> handle query gallery with tags (#14633)

- extensions/notebook/src/book/bookModel.ts
* create a queue of deferred promises for initializing books
* resolve active promise and set to undefined
* remove duplicated variable
* address pr comments
This PR fixes #14578
> [Port Request] Queue concurrent calls when initializing contents in BookModel (#14586)

- extensions/azurecore/src/account-provider/azureAccountProvider.ts
- src/sql/azdata.d.ts
Make it a littler clearer what these params are supposed to be
> Update commands and param names

- src/sql/platform/connection/common/connectionManagement.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
Noticed these while fixing something else and figured I'd fix them up now (whether they should be returning undefined is a whole different story...)
> Update return types that can return undefined

- extensions/machine-learning/package.json
- extensions/machine-learning/src/views/models/azureModelsComponent.ts
- extensions/machine-learning/src/views/models/azureResourceFilterComponent.ts
- extensions/machine-learning/src/views/models/manageModels/currentModelsComponent.ts
- extensions/machine-learning/src/views/models/manageModels/manageModelsDialog.ts
- extensions/machine-learning/src/views/models/modelBrowsePage.ts
- extensions/machine-learning/src/views/wizardView.ts
There were some issue with pages getting refreshed more than once. Adding a check for make sure the page needs to refresh and also sending "item changed" events when item actually changed helps with not refreshing the pages multiple times 
Also updated the version to 0.8.0 for the new release
> Bug fixes for ML 0.8.0

- extensions/sql-migration/package.json
> Vbump and vscode engine requirements update for SQL migration extension

- src/vs/platform/userDataSync/common/userDataAutoSyncService.ts
- src/vs/platform/userDataSync/test/common/userDataAutoSyncService.test.ts
- src/vs/workbench/services/userDataSync/browser/userDataAutoSyncEnablementService.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14616
* Disable auto sync service
* skip tests
(cherry picked from commit 1c671676bfe6042a1e87213abbf94881d2a0116d)
> [Port] Disable auto sync service (#14677)

- extensions/asde-deployment/notebooks/edge/deploy-sql-edge-azure-sshkey.ipynb
- extensions/asde-deployment/package.json
- extensions/asde-deployment/package.nls.json
use the new way to deploy vm as documented here: https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux?view=iotedge-2018-06#deploy-the-iot-edge-device 
also introduced a new option to use SSH public key authentication.
closes: https://github.com/microsoft/azuredatastudio/issues/14662
> fix vm creation issue

- src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
- src/sql/workbench/contrib/welcome/page/browser/welcomePage.css
- src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
- src/vs/base/browser/dom.ts
For https://github.com/microsoft/azuredatastudio/issues/14686
The main thing that caused this to break was the VS Code merge - they had updated the static welcome page content to be ran through an HTML sanitizer (https://github.com/microsoft/vscode/pull/108332) - but the list of allowed tags/attributes was scoped to just the ones they used so a number of tags in our welcome page weren't displayed properly. 
Once that was done though it turns out that our doc had a number of syntax errors (tags not closed properly for the most part) - which were then broken when ran through the sanitizer. So I went and fixed those errors as well.
The final fix was then that we still were getting layout issues where the bottom content would be cut off until the window was manually resized. This is due to …
> Fix welcome page

- extensionsGallery-insider.json
- extensionsGallery.json
> new version of asde deployment extension for insider feed

- extensionsGallery.json
> new version of asde for RC1

- extensions/big-data-cluster/notebooks/deployment/2019/deploy-bdc-aks.ipynb
- extensions/big-data-cluster/notebooks/deployment/2019/deploy-bdc-existing-aks.ipynb
- extensions/big-data-cluster/notebooks/deployment/2019/deploy-bdc-existing-aro.ipynb
- extensions/big-data-cluster/notebooks/deployment/2019/deploy-bdc-existing-kubeadm.ipynb
- extensions/big-data-cluster/notebooks/deployment/2019/deploy-bdc-existing-openshift.ipynb
- extensions/mssql/notebooks/TSG/cluster-status.ipynb
> Update azdata login namespace param

- extensionsGallery-insider.json
ADO build link for ML extension 0.8.0: https://mssqltools.visualstudio.com/_apis/resources/Containers/2880981/drop?itemPath=drop%2Fextensions%2Fmachine-learning-0.8.0.vsix
> Update extensionsGallery-insider.json for ML extension 0.8.0

- extensionsGallery.json
Extension file is already uploaded and used in Insider marketplace
> Update extensionsGallery.json for ML 0.8.0

- extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
> Fix value being passed in to reset memory limit 

- extensions/asde-deployment/package.json
> vbump asde extension

- src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
- src/sql/workbench/contrib/welcome/page/browser/welcomePage.css
- src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
- src/vs/base/browser/dom.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14686
> [Port] Fix welcome page (#14701)

- src/sql/workbench/services/connection/browser/connectionManagementService.ts
Missed updating some of the actual function implementations in https://github.com/microsoft/azuredatastudio/pull/14660/files
> Update missed connection management return values

- extensions/kusto/config.json
- extensions/kusto/package.json
> Bumped sqltoolservice version to 82 and kusto package version to 0.5.1

- extensions/data-workspace/package.nls.json
This PR fixes #13678 . Updated the texts as discussed in the workitem.
> Change no workspace content text

- extensions/resource-deployment/src/ui/resourceTypeWizard.ts
- extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14673
> [Port] Fix filtered resource options persisting across deployments (#14702)

- extensions/sql-database-projects/src/controllers/projectController.ts
> sqlproj - keep new object input box open when user navigates UI

- src/bootstrap-window.js
- src/bootstrap.js
Port fix for https://github.com/microsoft/azuredatastudio/issues/14623 to release/1.27
> Fix script loading in sandbox windows (#14727)

- src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
Closes https://github.com/microsoft/azuredatastudio/issues/14738
Links to https://aka.ms/AzureSQLSurvey
> [Port] Add Product Feedback survey link to welcome page (#14705)

- extensions/notebook/package.json
- extensions/notebook/package.nls.json
- extensions/notebook/src/book/bookTocManager.ts
- extensions/notebook/src/book/bookTreeItem.ts
- extensions/notebook/src/book/bookTreeView.ts
- extensions/notebook/src/common/utils.ts
- extensions/notebook/src/extension.ts
- extensions/notebook/src/test/book/bookTocManager.test.ts
This PR fixes #14116 
Book notebooks:
Standalone notebooks:
> Remove book notebook from toc

- extensionsGallery-insider.json
> Bumped kusto extension version to 0.5.1

- extensions/sql-assessment/src/assessmentResultGrid.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/browser/modelComponents/table.component.ts
I thought this might have been caused by my recent changes, but it was wrong, we never exposed the resizable option for table column.
This PR fixes #14599
> expose the resizable option for table column

- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/14522 and https://github.com/microsoft/azuredatastudio/issues/14360
> Fix database name edit box not announcing required

- README.md
> Updating README for March Release

- extensionsGallery.json
Updating the release/extensions as part of the release process
> March Extensions Update

- package.json
Updating the version number for next month's release
> Update version number for next release

- extensionsGallery-insider.json
- extensionsGallery.json
> add manifest for QPI extension

- extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts
> Clear updates in discard

- extensions/arc/package.nls.json
> Update replicas text

- extensionsGallery-insider.json
build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=97184&view=artifacts&pathAsName=false&type=publishedArtifacts
> update sql database projects to 0.8.0 in insiders

- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
It's been a while since we've done this so I went through and pulled out the APIs that I think are ready to go into stable.
Also fixed up some spelling mistakes while I was at it.
> Promote some proposed APIs to stable

- extensions/arc/src/models/postgresModel.ts
- extensions/arc/src/test/mocks/fakeAzdataApi.ts
- extensions/arc/src/test/models/postgresModel.test.ts
- extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresCoordinatorNodeParametersPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresWorkerNodeParametersPage.ts
- extensions/azdata/src/api.ts
- extensions/azdata/src/azdata.ts
- extensions/azdata/src/typings/azdata-ext.d.ts
This reverts commit 318559dcd7f0758fe0707b2f72a036f724bf5511
This will be moved into a separate feature branch until the backend changes are ready to ship.
> Revert Arc changes for Postgres CRD consolidation

- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
Fixes: 
- https://msdata.visualstudio.com/Database%20Systems/_workitems/edit/1073399
- https://msdata.visualstudio.com/Database%20Systems/_workitems/edit/1069362
- Bug where it showed 1 warning even when there were none.
> Fixed formatting/bugs

- src/sql/workbench/services/notebook/browser/sql/sqlNotebookManager.ts
Noticed that the SqlNotebookManager class was implementing the wrong interface.
> Notebooks: Clean up SqlNotebookManager code

- extensions/sql-database-projects/src/test/projectController.test.ts
forgot to merge main before checking in #14759 so I missed updating this new test which was added in #14740
> fix build errors in projectController.test.ts

- extensions/arc/src/ui/dashboards/postgres/postgresCoordinatorNodeParametersPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts
- extensions/arc/src/ui/dashboards/postgres/postgresWorkerNodeParametersPage.ts
Added Try catch block to edit functions in dashboard. Able to catch unexpected code error and show error message notification. 
This PR fixes #14803
> Postgres Parameters edit calls missing try catch block

- extensions/import/package.json
- extensions/import/yarn.lock
- extensions/kusto/package.json
- extensions/kusto/yarn.lock
- extensions/liveshare/package.json
- extensions/liveshare/yarn.lock
- extensions/mssql/package.json
- extensions/mssql/yarn.lock
Just keeping these up to date - no specific fixes/changes here that are needed
> Update sqlops-dataprotocolclient to 1.2.2

- resources/localization/LCL/zh-Hant/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hant/big-data-cluster.xlf.lcl
- resources/localization/LCL/zh-Hant/dacpac.xlf.lcl
- resources/localization/LCL/zh-Hant/mssql.xlf.lcl
- resources/localization/LCL/zh-Hant/notebook.xlf.lcl
- resources/localization/LCL/zh-Hant/resource-deployment.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210319154205844 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210319154205844 to main

- extensions/arc/src/test/ui/dashboards/postgresOverviewPage.test.ts
- extensions/arc/src/ui/components/dashboard.ts
- extensions/arc/src/ui/components/dashboardPage.ts
- extensions/arc/src/ui/dashboards/controller/controllerDashboard.ts
- extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaConnectionStringsPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaDashboard.ts
- extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresConnectionStringsPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresCoordinatorNodeParametersPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresDashboard.ts
- extensions/arc/src/ui/dashboards/postgres/postgresDiagnoseAndSolveProblemsPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts
- extensions/arc/src/ui/dashboards/postgres/postgresPropertiesPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresResourceHealthPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresSupportRequestPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresWorkerNodeParametersPage.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/browser/mainThreadModelViewDialog.ts
- src/sql/workbench/api/common/extHostModelViewDialog.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
Closes https://github.com/microsoft/azuredatastudio/issues/11852
I also fixed a bug where the extension host implementation didn't implement a getter for the handle - which meant that it was passing undefined for the handle instead of the actual value.
> Add close method to ModelView dashboards

- extensions/arc/notebooks/arcDataServices/_config.yml
- extensions/arc/notebooks/arcDataServices/_data/toc.yml
- extensions/arc/notebooks/arcDataServices/content/postgres/readme.md
- extensions/arc/notebooks/arcDataServices/content/postgres/toc.yml
- extensions/arc/notebooks/arcDataServices/content/postgres/tsg100-troubleshoot-postgres.ipynb
- extensions/arc/notebooks/arcDataServices/readme.md
- extensions/arc/src/ui/dashboards/postgres/postgresDashboard.ts
- extensions/arc/src/ui/dashboards/postgres/postgresDiagnoseAndSolveProblemsPage.ts
Updates the Arc Postgres troubleshooting notebook with recent changes moving from 2 -> 1 resource type.
> Update Arc Postgres troubleshooting notebook

- src/sql/workbench/contrib/notebook/test/stubs.ts
- src/sql/workbench/contrib/query/browser/statusBarItems.ts
- src/sql/workbench/services/notebook/browser/models/cell.ts
- src/sql/workbench/services/notebook/browser/notebookService.ts
- src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts
- src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/14369
> Enable status bar for notebooks

- extensionsGallery-insider.json
- extensionsGallery.json
Add support for unicode and varbinary
> Update simple-data-scripter extension

- resources/localization/LCL/ja/azurecore.xlf.lcl
- resources/localization/LCL/ja/big-data-cluster.xlf.lcl
- resources/localization/LCL/ja/dacpac.xlf.lcl
- resources/localization/LCL/ja/mssql.xlf.lcl
- resources/localization/LCL/ja/notebook.xlf.lcl
- resources/localization/LCL/ja/resource-deployment.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210322033318241 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210322033318241 to main

- resources/localization/LCL/de/azurecore.xlf.lcl
- resources/localization/LCL/de/big-data-cluster.xlf.lcl
- resources/localization/LCL/de/dacpac.xlf.lcl
- resources/localization/LCL/de/mssql.xlf.lcl
- resources/localization/LCL/de/notebook.xlf.lcl
- resources/localization/LCL/de/resource-deployment.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210322160951003 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210322160951003 to main

- resources/localization/LCL/es/azurecore.xlf.lcl
- resources/localization/LCL/es/big-data-cluster.xlf.lcl
- resources/localization/LCL/es/dacpac.xlf.lcl
- resources/localization/LCL/es/mssql.xlf.lcl
- resources/localization/LCL/es/notebook.xlf.lcl
- resources/localization/LCL/es/resource-deployment.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210322213526729 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210322213526729 to main

- resources/localization/LCL/de/azurecore.xlf.lcl
- resources/localization/LCL/de/dacpac.xlf.lcl
- resources/localization/LCL/de/mssql.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/azurecore.xlf.lcl
- resources/localization/LCL/es/dacpac.xlf.lcl
- resources/localization/LCL/es/mssql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/ja/azurecore.xlf.lcl
- resources/localization/LCL/ja/dacpac.xlf.lcl
- resources/localization/LCL/ja/mssql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hant/mssql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210323033600745 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210323033600745 to main

- resources/localization/LCL/de/azurecore.xlf.lcl
- resources/localization/LCL/de/dacpac.xlf.lcl
- resources/localization/LCL/de/mssql.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/azurecore.xlf.lcl
- resources/localization/LCL/es/dacpac.xlf.lcl
- resources/localization/LCL/es/mssql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/ja/azurecore.xlf.lcl
- resources/localization/LCL/ja/dacpac.xlf.lcl
- resources/localization/LCL/ja/mssql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hant/mssql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210323093512251 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210323093512251 to main

- extensions/notebook/src/test/book/bookTocManager.test.ts
Use path.posix.join to build test toc.
Fix book editing tests that were failing locally.
> fix tests on windows

- src/sql/base/browser/ui/scrollableView/scrollableView.ts
- src/sql/base/browser/ui/table/asyncDataView.ts
- src/sql/base/browser/ui/table/hybridDataProvider.ts
- src/sql/base/browser/ui/table/interfaces.ts
- src/sql/base/browser/ui/table/media/table.css
- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/base/browser/ui/table/plugins/rowNumberColumn.plugin.ts
- src/sql/base/browser/ui/table/table.ts
- src/sql/base/browser/ui/table/tableDataView.ts
- src/sql/base/common/dataProvider.ts
- src/sql/base/test/browser/ui/scrollableView/scrollableView.test.ts
- src/sql/platform/query/common/query.ts
- src/sql/workbench/common/editor/query/gridTableState.ts
- src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
- src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
- src/sql/workbench/contrib/query/browser/actions.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
- src/sql/workbench/contrib/resourceViewer/browser/resourceViewerTable.ts
- src/sql/workbench/services/insights/browser/insightsDialogView.ts
- src/sql/workbench/services/query/common/gridDataProvider.ts
- src/sql/workbench/services/query/common/queryRunner.ts
this is to merge the changes to main, all the changes have been reviewed in this PR: https://github.com/microsoft/azuredatastudio/pull/14589
> query results filtering and sorting

- src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
> Deselect row everytime setProperties called

- src/sql/workbench/browser/modelComponents/media/card.css
- src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts
> card link styles

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
- extensions/sql-migration/src/wizard/sqlSourceConfigurationPage.ts
For now I am adding a better username and authentication type for sql source configuration.
> Making source config more intiutive and hiding assessment cards until assessment is done

- resources/localization/LCL/es/big-data-cluster.xlf.lcl
- resources/localization/LCL/es/notebook.xlf.lcl
- resources/localization/LCL/es/resource-deployment.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210324033348910 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210324033348910 to main

- resources/localization/LCL/de/azurecore.xlf.lcl
- resources/localization/LCL/de/dacpac.xlf.lcl
- resources/localization/LCL/de/mssql.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/azurecore.xlf.lcl
- resources/localization/LCL/es/dacpac.xlf.lcl
- resources/localization/LCL/es/mssql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/ja/azurecore.xlf.lcl
- resources/localization/LCL/ja/dacpac.xlf.lcl
- resources/localization/LCL/ja/mssql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/azurecore.xlf.lcl
- resources/localization/LCL/ko/dacpac.xlf.lcl
- resources/localization/LCL/ko/mssql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/azurecore.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hant/mssql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210323153537964 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210323153537964 to main

- resources/localization/LCL/fr/azurecore.xlf.lcl
- resources/localization/LCL/fr/dacpac.xlf.lcl
- resources/localization/LCL/fr/mssql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/ko/azurecore.xlf.lcl
- resources/localization/LCL/ko/dacpac.xlf.lcl
- resources/localization/LCL/ko/mssql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/azurecore.xlf.lcl
- resources/localization/LCL/pt-BR/dacpac.xlf.lcl
- resources/localization/LCL/pt-BR/mssql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210323213358010 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210323213358010 to main

- resources/localization/LCL/it/azurecore.xlf.lcl
- resources/localization/LCL/it/big-data-cluster.xlf.lcl
- resources/localization/LCL/it/dacpac.xlf.lcl
- resources/localization/LCL/it/mssql.xlf.lcl
- resources/localization/LCL/it/notebook.xlf.lcl
- resources/localization/LCL/it/resource-deployment.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ru/azurecore.xlf.lcl
- resources/localization/LCL/ru/big-data-cluster.xlf.lcl
- resources/localization/LCL/ru/dacpac.xlf.lcl
- resources/localization/LCL/ru/mssql.xlf.lcl
- resources/localization/LCL/ru/notebook.xlf.lcl
- resources/localization/LCL/ru/resource-deployment.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hans/big-data-cluster.xlf.lcl
- resources/localization/LCL/zh-Hans/dacpac.xlf.lcl
- resources/localization/LCL/zh-Hans/mssql.xlf.lcl
- resources/localization/LCL/zh-Hans/notebook.xlf.lcl
- resources/localization/LCL/zh-Hans/resource-deployment.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210324153404847 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210324153404847 to main

- src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
> fire selection event when re-entered regardless whether the selection is changed

- resources/localization/LCL/ru/mssql.xlf.lcl
- resources/localization/LCL/ru/notebook.xlf.lcl
- resources/localization/LCL/ru/resource-deployment.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210324213452033 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210324213452033 to main

- extensions/sql-migration/package.json
- extensions/sql-migration/package.nls.json
- extensions/sql-migration/src/main.ts
> add 'start migration' action to dashboard toolbar

- src/sql/workbench/contrib/extensions/browser/extensions.contribution.ts
Forgot to commit this in previous PR...
> Add return type to handler

- extensions/dacpac/src/wizard/dataTierApplicationWizard.ts
- src/sql/azdata.proposed.d.ts
- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/api/browser/mainThreadModelViewDialog.ts
- src/sql/workbench/api/common/extHostModelViewDialog.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
- src/sql/workbench/browser/modal/modal.ts
- src/sql/workbench/services/dialog/browser/customDialogService.ts
- src/sql/workbench/services/dialog/browser/wizardModal.ts
- src/sql/workbench/test/electron-browser/api/extHostModelViewDialog.test.ts
- src/sql/workbench/test/electron-browser/api/mainThreadModelViewDialog.test.ts
Adding telemetry to see how many times the dacpac wizard gets opened and if it's opened from command palette or context menu of db or server.
> Add telemetry for opening dacpac wizard

- extensions/arc/src/localizedConstants.ts
- extensions/arc/src/ui/dialogs/connectControllerDialog.ts
> Add info and placeholder for controller URL/name

- src/sql/platform/serialization/common/serializationService.ts
- src/sql/workbench/contrib/notebook/browser/models/fileNotebookInput.ts
- src/sql/workbench/contrib/notebook/browser/models/untitledNotebookInput.ts
- src/sql/workbench/contrib/query/browser/actions.ts
This PR fixes 
- https://github.com/microsoft/azuredatastudio/issues/14881 (caused by getEncoding check being added here https://github.com/microsoft/azuredatastudio/pull/14533/files) 
- https://github.com/microsoft/azuredatastudio/issues/14867
> Notebooks: fix save as csv/excel/json/xml

- extensions/sql-database-projects/src/controllers/projectController.ts
> Fix telemetry for Sql db projects

- extensions/mssql/config.json
https://github.com/microsoft/sqltoolsservice/releases/tag/v3.0.0-release.89
Adds support for SQL Auth for Migration Assessments
> Bump sts version

- extensions/azurecore/src/azureResource/azure-resource.d.ts
- extensions/azurecore/src/azureResource/utils.ts
- extensions/azurecore/src/azurecore.d.ts
- extensions/azurecore/src/extension.ts
- extensions/machine-learning/src/test/stubs.ts
- extensions/sql-migration/package.json
- extensions/sql-migration/package.nls.json
- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
- extensions/sql-migration/src/dialog/createSqlMigrationService/createSqlMigrationServiceDialog.ts
- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialogModel.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/accountsSelectionPage.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
- extensions/sql-migration/src/wizard/sqlSourceConfigurationPage.ts
- extensions/sql-migration/src/wizard/wizardController.ts
Adding managed databases api in azure core.
Added some more validations and restrictions on resources.
Displaying some non blocking errors as warning.
> Migration Private preview 1 fixes 2

- extensions/kusto/src/features.ts
Refactored getToken to set tenantId based on providerId. This will be merged after changes to the ADSLiveSite extension and SqlToolService.
SqlToolService PR
https://github.com/microsoft/sqltoolsservice/pull/1183
ADSLivesite Extension PR
https://mssqltools.visualstudio.com/ADS%20LiveSite%20Support/_git/LivesiteExtension/pullrequest/3720
> dstsAuth Token Refresh

- src/sql/base/browser/ui/slider/slider.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14908
Fixes https://github.com/microsoft/azuredatastudio/issues/14907
> Fix slider component

- extensions/notebook/src/book/bookTocManager.ts
- extensions/notebook/src/book/bookTreeItem.ts
- extensions/notebook/src/book/bookTreeView.ts
- extensions/notebook/src/book/bookTrustManager.ts
> fix search action

- test/smoke/src/sql/main.ts
Using official Microsoft org one - same content as https://github.com/kburtram/azuredatastudio-sqlite
> Switch azuredatastudio-sqlite repo

- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
> Sort Dbs by number of issues

- src/sql/base/browser/ui/checkbox/checkbox.ts
- src/sql/base/browser/ui/radioButton/radioButton.ts
This PR fixes #14964
use the standard way of adding label for checkbox and radio button. https://www.w3schools.com/tags/att_input_type_radio.asp
> fix checkbox and radio button click issue

- src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
Closes https://github.com/microsoft/azuredatastudio/issues/14939
> Remove survey link

- src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
> [Port] Remove survey link

- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
Port https://github.com/microsoft/azuredatastudio/pull/14963 to release branch
This PR fixes #14962
> [Port Request] redraw table header (#14963)

- build/azure-pipelines/win32/sql-product-build-win32.yml
For https://github.com/microsoft/azuredatastudio/issues/14953
We should look into signing all DLLs like VS Code does, but keeping this as a targeted fix to reduce chance of issues. 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build?definitionId=295&_a=summary
> Sign vulkan-1 DLL

- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
I mistakenly forgot to set the target branch in this PR: https://github.com/microsoft/azuredatastudio/pull/14972
set correct target branch this time.
This PR fixes #14962
> redraw table header (#14963)

- build/azure-pipelines/win32/sql-product-build-win32.yml
> [Port] Sign vulkan-1 DLL (#14976)

- extensions/kusto/package.json
> Increased ADS version required from 1.27 to 1.28

- extensions/arc/package.json
- extensions/big-data-cluster/package.json
Closes https://github.com/microsoft/azuredatastudio/issues/14997
> [Port] Update minimum required azdata version

- src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
- src/sql/workbench/contrib/notebook/test/calloutDialog/linkCalloutDialog.test.ts
This PR fixes #14724.
The PR from main: #14987
> [PORT] See and Edit Selected Links in Callout Dialog

- extensionsGallery.json
VSIX from the release build: https://mssqltools.visualstudio.com/_apis/resources/Containers/2938048/drop?itemPath=drop%2Fextensions%2Fmachine-learning-0.9.0.vsix
> Update extensionsGallery.json for Machine Learning 0.9.0 - RC 

- extensions/kusto/package.json
> Increased required version for Kusto from 1.27 to 1.28

- extensions/schema-compare/src/schemaCompareMainWindow.ts
This PR fixes #14957. Cherry picking commit of this PR https://github.com/microsoft/azuredatastudio/pull/14999
> [Port] fix schema compare dropdown not selecting correct db when multiple active connections

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
- extensions/sql-migration/src/models/stateMachine.ts
Fixed the following:
- Added a warnings count
- Changed Warnings -> Issue Details when a DB is selected
- Updated db count when new dbs selected
> ADS Migration UI Fixes

- extensionsGallery.json
build with schema compare vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=99644&view=artifacts&pathAsName=false&type=publishedArtifacts
> update schema compare to 1.10.0 in RC

- extensionsGallery-insider.json
- extensionsGallery.json
Reverts microsoft/azuredatastudio#14924
> Revert "Update to extensions gallery json with upcoming language pack update"

- product.json
> bump sqlservernotebook version

- product.json
> bump sqlservernotebook version (#15025)

- extensionsGallery-insider.json
Link to build containing VSIX:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=99662&view=results
> Update Kusto to 0.5.2

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/dataworkspace.d.ts
- extensions/data-workspace/src/dialogs/projectDashboard.ts
- extensions/data-workspace/src/test/projectProviderRegistry.test.ts
- extensions/data-workspace/src/test/workspaceTreeDataProvider.test.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/dashboardData/dashboardData.ts
- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
This PR aims to fix the issue where multiple projects are showing same data for dashboard : #15020 
Post fix this is how it looks :
> Fix for Bug #15020 dashboard update with multiproject

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/dataworkspace.d.ts
- extensions/data-workspace/src/dialogs/projectDashboard.ts
- extensions/data-workspace/src/test/projectProviderRegistry.test.ts
- extensions/data-workspace/src/test/workspaceTreeDataProvider.test.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/dashboardData/dashboardData.ts
- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
This PR fixes #15020 (Project data for dashboard incorrectly shows all projects data at once)
Main PR merged : https://github.com/microsoft/azuredatastudio/pull/15029
> Fix for Bug #15020 dashboard update with multiproject (#15029)

- src/sql/workbench/contrib/backup/browser/backupActions.ts
- src/sql/workbench/contrib/restore/browser/restoreActions.ts
This PR fixes #15040
Main PR Merged : #15041
> Porting fix for bug 15040 (Backup/Restore Launch issue)

- extensionsGallery.json
Link to build containing VSIX
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=99724&view=results
> Update Kusto to 0.5.2 RC1

- extensionsGallery-insider.json
- extensionsGallery.json
Updates version of schema-visualization extention
> Update version of schema visualization

- extensionsGallery.json
build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=99872&view=artifacts&pathAsName=false&type=publishedArtifacts
> update sql database projects to 0.8.1 in RC

- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
- src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts
- src/sql/workbench/contrib/notebook/test/browser/htmlMarkdownConverter.test.ts
* fix anchor links in wysiwyg
[test.zip](https://github.com/microsoft/azuredatastudio/files/6280829/test.zip)
This PR fixes #14734
> fix anchor links in wysiwyg (#14950)

- src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookSearch.ts
> fix search loading animation

- src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookSearch.ts
> fix search loading animation (#15063)

- extensionsGallery-insider.json
vsixs were already uploaded for RC updates in in https://github.com/microsoft/azuredatastudio/pull/15055 and https://github.com/microsoft/azuredatastudio/pull/15018
> update schema compare to 1.10.0 and sql database projects to 0.8.1 in insiders

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/controllers/projectController.ts
This PR fixes #15070
Main PR merged #15073
> Porting fix for bug 15070 (deployment data for dashboard)

- src/sql/workbench/contrib/editorReplacement/common/editorReplacerContribution.ts
> Fix for Rendered Notebook Diff from Timeline View (#15069)

- extensionsGallery-insider.json
same vsix as in https://github.com/microsoft/azuredatastudio/pull/15084
> update sql database projects to 0.8.2 in insiders

- extensionsGallery.json
updating to get this [fix](https://github.com/microsoft/azuredatastudio/pull/15080)
build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=100042&view=artifacts&pathAsName=false&type=publishedArtifacts
> update sql database projects to 0.8.2 in RC

- src/sql/base/browser/ui/table/media/table.css
- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/workbench/contrib/assessment/browser/asmtResultsView.component.ts
This PR fixes some issue with the table header
when typed in the search box
1. The result is displayed horizontally
2. For query editor, a not implemented exception is thrown
Before:
After:
> fix search box issue

- extensions/kusto/config.json
- extensions/kusto/package.json
SqlToolService build completed 4/13
https://github.com/microsoft/sqltoolsservice/releases/tag/v3.0.0-release.92
> Bumped version of Kusto to 0.5.3 for SqlToolService 92

- test/smoke/src/main.ts
https://github.com/Microsoft/azuredatastudio-smoke-test-repo
Test build : https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=100253&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=f7e3bacc-79f9-5aef-ec63-f7078932cd4c
> Update smoke test repo

- src/vs/editor/common/viewModel/viewModelImpl.ts
- src/vs/editor/contrib/codelens/codelensController.ts
- src/vs/workbench/contrib/comments/browser/commentThreadWidget.ts
- src/vs/workbench/contrib/debug/browser/media/repl.css
- src/vs/workbench/contrib/debug/browser/repl.ts
- src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts
This PR fixes https://github.com/microsoft/vscode/issues/121208
Commit from vscode - https://github.com/microsoft/vscode/commit/2e165500a6d5449fdd076f0ddbaa588f1e5743c7
> fixed css for font family

- build/hygiene.js
- extensions/git-ui/src/main.ts
- package.json
- src/vs/workbench/api/node/extHostCLIServer.ts
- src/vs/workbench/contrib/terminal/browser/remoteTerminalService.ts
Issue - https://github.com/microsoft/vscode/issues/121212
PR follows code from https://github.com/microsoft/vscode/commit/c826e9aabd26be0e6a8fa61947256a601ca4b069
Code is a bit different and I tried to make the changes as close as possible
> Remote CLI fixes

- build/hygiene.js
- extensions/git-ui/src/main.ts
- package.json
- src/vs/workbench/api/node/extHostCLIServer.ts
- src/vs/workbench/contrib/terminal/browser/remoteTerminalService.ts
(cherry picked from commit 1b780082587c330d988d06a544a149f4b7499c07)
Original PR to main - https://github.com/microsoft/azuredatastudio/pull/15117
> Remote CLI fixes (#15117)

- src/vs/editor/common/viewModel/viewModelImpl.ts
- src/vs/editor/contrib/codelens/codelensController.ts
- src/vs/workbench/contrib/comments/browser/commentThreadWidget.ts
- src/vs/workbench/contrib/debug/browser/media/repl.css
- src/vs/workbench/contrib/debug/browser/repl.ts
- src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts
(cherry picked from commit 90868bc0ad4b69ccd7a37c1e3a5e61d716bcee11)
Original PR to main - https://github.com/microsoft/azuredatastudio/pull/15119
> fixed css for font family (#15119)

- package.json
- src/vs/platform/remote/common/remoteAgentEnvironment.ts
- src/vs/platform/request/common/request.ts
- src/vs/workbench/services/extensions/electron-browser/extensionService.ts
- src/vs/workbench/services/remote/common/remoteAgentEnvironmentChannel.ts
This PR fixes https://github.com/microsoft/vscode/issues/121207
Commit taken from - https://github.com/microsoft/vscode/commit/ceda963326caf9df3fa973e2d6cb989b865e56d8
> add flag for proxy

- extensionsGallery-insider.json
Here is the ADS RC build with the updated extension
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=100398&view=results
> Increased Kusto version to 0.5.3 in RC1

- extensionsGallery-insider.json
Here is the build that contains the new extension
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=100399&view=results
> Increased Kusto version to 0.5.3 in Insiders

- src/sql/base/browser/ui/table/media/table.css
- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/platform/theme/common/styler.ts
- src/sql/workbench/browser/modelComponents/table.component.ts
- src/sql/workbench/contrib/assessment/browser/asmtResultsView.component.ts
- src/sql/workbench/contrib/jobManagement/browser/jobsView.component.ts
- src/sql/workbench/contrib/jobManagement/browser/notebooksView.component.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
- src/sql/workbench/contrib/resourceViewer/browser/resourceViewerTable.ts
1. previously the sort buttons are not keyboard accessible, use standard button to replace them
2. add style for inputbox
3. just noticed that contextViewService doesn't take care of the visibility of the context view, so in some cases, the context view will be cut off, so I copied code that was deleted by me previously to determine the position of the context view.
Before:
After:
> a couple more fixes for table filter

- package.json
- src/vs/platform/remote/common/remoteAgentEnvironment.ts
- src/vs/platform/request/common/request.ts
- src/vs/workbench/services/extensions/electron-browser/extensionService.ts
- src/vs/workbench/services/remote/common/remoteAgentEnvironmentChannel.ts
Co-authored-by: kburtram <karlb@microsoft.com>
Co-authored-by: chgagnon <chgagnon@microsoft.com>
(cherry picked from commit b6bdb68596c77742cb58efbfec272ca4866a047b)
PR that was merged to main - https://github.com/microsoft/azuredatastudio/pull/15125
> add flag for proxy (#15120)

- extensionsGallery-insider.json
- extensionsGallery.json
ADS RC Extension Build
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=100398&view=results
> Update kusto to 0.5.3 rc1

- src/sql/workbench/contrib/modelView/browser/webview.component.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts
- src/vs/editor/browser/core/markdownRenderer.ts
- src/vs/editor/browser/services/openerService.ts
- src/vs/editor/contrib/gotoError/gotoErrorWidget.ts
- src/vs/editor/contrib/hover/modesContentHover.ts
- src/vs/editor/contrib/links/links.ts
- src/vs/editor/test/browser/services/openerService.test.ts
- src/vs/platform/opener/browser/link.ts
- src/vs/platform/opener/common/opener.ts
- src/vs/workbench/api/browser/mainThreadWebviews.ts
- src/vs/workbench/browser/parts/notifications/notificationsViewer.ts
- src/vs/workbench/browser/parts/views/viewPaneContainer.ts
- src/vs/workbench/contrib/comments/browser/commentsTreeViewer.ts
- src/vs/workbench/contrib/extensions/browser/extensionEditor.ts
- src/vs/workbench/contrib/markers/browser/markersTreeViewer.ts
- src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts
- src/vs/workbench/contrib/preferences/browser/settingsTree.ts
- src/vs/workbench/contrib/remote/browser/remote.ts
- src/vs/workbench/contrib/welcome/walkThrough/browser/walkThroughPart.ts
(cherry picked from commit e151668c813103d2299b1960707d5b9f315da075)
PR from main - https://github.com/microsoft/azuredatastudio/pull/15118
> Links handling in commands (#15118)

- test/smoke/src/main.ts
This is trying to fix the merge conflict in the merge distro build step.
> Update the path to the smoke test

- src/sql/workbench/contrib/notebook/test/browser/cellToolbarActions.test.ts
- src/sql/workbench/contrib/notebook/test/browser/markdownTextTransformer.test.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookEditor.test.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookService.test.ts
- src/sql/workbench/contrib/notebook/test/electron-browser/notebookEditorModel.test.ts
- src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts
- src/sql/workbench/test/electron-browser/api/mainThreadNotebook.test.ts
> show notebook as trusted when it belongs to a trusted book

- extensions/sql-migration/package.json
- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
> Fixing migration extension to reflect latest RP changes

- CHANGELOG.md
- README.md
> release notes

- extensions/mssql/config.json
Pick up latest sqltoolsservice changes.
> Bump STS to 3.0.0-release.93

- extensionsGallery-insider.json
I am waiting for the extension icon to be added in main before pushing this PR to insiders gallery
> Adding sql migration extension to insiders gallery

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
Displays a no issues message for DBs without any issues
> Display "No Issues" Message

- extensions/integration-tests/src/onboarding/developers.ts
- Onboarding pull request for Hai Cao (caohai)
> Onboarding pull request (caohai)

- src/sql/workbench/contrib/editorReplacement/common/editorReplacerContribution.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15180
> [Port] Fix crash when opening SQL diff input (#15183)

- extensions/arc/src/test/models/postgresModel.test.ts
- extensions/arc/src/test/ui/dashboards/postgresConnectionStrings.test.ts
Fix compile errors found in unit test.
> Included roles in fake show output for testing

- extensions/arc/src/models/miaaModel.ts
- extensions/arc/src/models/postgresModel.ts
- extensions/arc/src/test/models/postgresModel.test.ts
- extensions/arc/src/test/ui/dashboards/postgresConnectionStrings.test.ts
- extensions/arc/src/ui/dashboards/miaa/miaaComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaConnectionStringsPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts
- extensions/azdata/src/typings/azdata-ext.d.ts
> Update arc specs

- extensionsGallery-insider.json
Updating migration extension to 0.0.11
This is the build for the vsix file. 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=101633&view=results
> Vbump migration extension

- extensions/server-report/package.json
- extensions/server-report/yarn.lock
- samples/sp_whoIsActive/package.json
- samples/sp_whoIsActive/yarn.lock
- samples/sqlservices/package.json
- samples/sqlservices/yarn.lock
This PR fixes the handlebars Component governance issue raised in build pipelines. 
Here is a successful build with this fix. (error in smoke test is unrelated)
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=101859&view=results
> Updating handle bars to 4.7.7 to fix a component governance issue

- package.json
Brings in latest merge updates
> Bump distro

- src/sql/workbench/services/connection/browser/media/connectionBrowseTab.css
> add nowrap to tree label

- extensions/arc/package.json
> Bump arc version

- extensions/schema-compare/package.json
- extensions/sql-database-projects/package.json
bumping versions after the April release
> bump version for schema compare and sql database projects

- extensionsGallery-insider.json
Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=102424&view=artifacts&pathAsName=false&type=publishedArtifacts
> update sql database projects to 0.9.0 in insiders

- extensions/mssql/config.json
This PR fixes #15200
Original STS PR https://github.com/microsoft/sqltoolsservice/pull/1199
> Bumping mssql to 98 to fix notebook history bug in agent

- src/sql/base/browser/ui/selectBox/selectBox.ts
Missed commit from PR #15082
This commit was based on PR comments but missed to push from the last PR - please take a look.
> Missed commit from PR #15082

- extensions/big-data-cluster/.vscodeignore
- extensions/big-data-cluster/extension.webpack.config.js
- extensions/big-data-cluster/package.json
- extensions/big-data-cluster/src/bigDataCluster/auth.ts
- extensions/big-data-cluster/yarn.lock
- extensions/mssql/.vscodeignore
- extensions/mssql/extension.webpack.config.js
- extensions/mssql/package.json
- extensions/mssql/src/util/auth.ts
- extensions/mssql/yarn.lock
https://github.com/microsoft/ads-kerberos
This is an exact copy of https://github.com/aasimkhan30/ads-kerberos#readme.
Had @abist test that kerberos functionality is still working as intended.
> Use official Microsoft ads-kerberos

- extensions/sql-database-projects/package.json
bumping version after extension was updated in insiders gallery
> bump sql database projects version to 0.9.1

- src/sql/base/browser/ui/selectBox/selectBox.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/15305
Will fix the backup issue sperately as that is lower pri than this and has been there for a long time.
> Reverting a change to ensure immediate notebook fix

- extensionsGallery-insider.json
Kusto extension 0.5.4 was built here:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=102717&view=results
> Bumped Kusto version to 0.5.4

- src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts
Tests around addCellAttachment function.
> add tests for cell attachment changes

- extensionsGallery-insider.json
- extensionsGallery.json
> remove an extension that is no longer working

- product.json
> remove extension from recommended list

- extensionsGallery-insider.json
- extensionsGallery.json
This PR 
* update extension Sql Data Inspector to 0.2.0
> Update Sql Data Inspector to 0.2.0

- extensionsGallery.json
Kusto extension 0.5.4 was built here:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=102717&view=results
> Update Kusto to 0.5.4 for GA

- extensions/azurecore/package.json
- extensions/azurecore/yarn.lock
- extensions/machine-learning/package.json
- extensions/machine-learning/yarn.lock
- extensions/resource-deployment/package.json
- extensions/resource-deployment/yarn.lock
Updating the necessary libraries to remove the CG error. I will request reviews from the area owners for testing and sanity check. 
1. Extensions/Features directly or indirectly affected by the package updates:
> Updating axios package to fix component governance issue.

- src/sql/workbench/contrib/notebook/browser/cellViews/placeholderCell.component.html
- test/automation/src/sql/notebook.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
Mostly followed the steps in this test plan: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_workitems/edit/1644
Note: added id's to the +code and +text elements in the placeholder cell so that we can properly select them.
> Add smoke test for basic text cell functionality

- src/sql/workbench/services/notebook/browser/models/cell.ts
> fix attach image on rehydration

- src/sql/workbench/services/query/common/queryRunner.ts
> fix line number display issue

- test/smoke/src/sql/areas/notebook/notebook.test.ts
Temporarily skip text cell smoke test while I investigate the issue.
> Skip failing notebook smoke test

- extensions/sql-migration/README.md
> Fixing the broken gif on migration readme

- src/sql/workbench/contrib/backup/browser/backup.component.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/14649 (second part)
I can open a sperate task for figuring out overall select issue but want to fix this for backup this month
> Doing a point fix for backup since select box has other impacts

- src/vs/platform/extensions/common/extensions.ts
- src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts
This PR fixes #15408
Port the commit: https://github.com/microsoft/azuredatastudio/pull/15409 to release branch
> [Port Request] Remove the filters not applicable to ads (#15409)

- remote/web/yarn.lock
- remote/yarn.lock
- yarn.lock
This PR fixes https://github.com/microsoft/azuredatastudio/issues/15421
PR in main - https://github.com/microsoft/azuredatastudio/pull/15419
> update remote yarn lock  (#15419)

- test/smoke/src/sql/areas/notebook/notebook.test.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/15416
PR in main: https://github.com/microsoft/azuredatastudio/pull/15411
> Skip notebook text cell smoketest

- src/vs/code/electron-browser/sharedProcess/sharedProcessMain.ts
- src/vs/code/node/cliProcessMain.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15430
> [Port] Fix event prefix (#15429)

- src/sql/platform/actions/browser/menuEntryActionViewItem.ts
- src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts
- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
- src/vs/platform/actions/browser/menuEntryActionViewItem.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15394
> [Port] Fix dashboard icons (#15400)

- extensions/azurecore/src/azureResource/commands.ts
- extensions/azurecore/src/azureResource/interfaces.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/15444
> fix azure context menu

- extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15360
> Bugfix for Schema Compare panel okay button enabled state

- extensions/notebook/src/book/bookTreeView.ts
- extensions/notebook/src/extension.ts
- extensions/notebook/src/test/book/book.test.ts
Only focus elements when the selected tree item is not visible.
https://user-images.githubusercontent.com/34872381/118040545-810a5800-b326-11eb-9f11-0ebd4593b679.mov
This PR adresses #15092
> Notebooks View: Do not recenter view when selecting a notebook that is visible

- extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
> Bugfix for Schema Compare panel okay button enabled state (#15450)

- extensions/azurecore/src/azureResource/services/terminalService.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/15441
The issue was the dimension of the terminal kept changing, calling `setDimensions` multiple times, causing terminal to show gibberish. 
Before - 
After -
> Fix cloud shell

- src/vs/workbench/browser/parts/views/viewPane.ts
This PR fixes #15369 along with #15437 and #15439.
Fix taken from https://github.com/microsoft/vscode/commit/23e346ab55a317c322a184eab4d10597927cd491
Initial link handling fix came with #15118 in ADS.
> Fix link handling in viewPane

- extensionsGallery-insider.json
same vsixs as the RC gallery update PR https://github.com/microsoft/azuredatastudio/pull/15463
> update sql database projects and schema compare in insiders

- extensions/azurecore/src/azureResource/commands.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/15444
PR in main - https://github.com/microsoft/azuredatastudio/pull/15447
> fix azure context menu (#15447)

- src/vs/workbench/browser/parts/views/viewPane.ts
This PR fixes #15369
PR in `main`: #15458
> [Port] Fix link handling in viewPane (#15458)

- src/sql/media/icons/loading.svg
- src/sql/media/icons/loading_inverse.svg
- src/sql/workbench/browser/modelComponents/media/loading.svg
- src/sql/workbench/browser/modelComponents/media/loading_inverse.svg
- src/sql/workbench/contrib/query/browser/modelViewTab/media/loading.svg
- src/sql/workbench/contrib/query/browser/modelViewTab/media/loading_inverse.svg
- src/sql/workbench/contrib/tasks/browser/media/loading.svg
- src/sql/workbench/contrib/tasks/browser/media/loading_inverse.svg
- src/sql/workbench/services/dialog/browser/media/loading.svg
- src/sql/workbench/services/dialog/browser/media/loading_inverse.svg
- src/vs/base/parts/tree/browser/loading-dark.svg
- src/vs/base/parts/tree/browser/loading-hc.svg
- src/vs/base/parts/tree/browser/loading.svg
This PR fixes #15395 
original PR: https://github.com/microsoft/azuredatastudio/pull/15471
> [Port Request] fix animated svg issue (#15471)

- src/bootstrap-window.js
(cherry picked from commit d797ef433a9231da6f9e0548e61d9c5d9305eaa9)
Fixes https://github.com/microsoft/azuredatastudio/issues/15253
> [Port] Fix Issue Reporter (#15467)

- resources/localization/LCL/zh-Hant/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hant/cms.xlf.lcl
- resources/localization/LCL/zh-Hant/dacpac.xlf.lcl
- resources/localization/LCL/zh-Hant/notebook.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210514033502079 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210514033502079 to main

- resources/localization/LCL/fr/dacpac.xlf.lcl
- resources/localization/LCL/fr/import.xlf.lcl
- resources/localization/LCL/fr/notebook.xlf.lcl
- resources/localization/LCL/fr/resource-deployment.xlf.lcl
- resources/localization/LCL/fr/schema-compare.xlf.lcl
- resources/localization/LCL/ja/big-data-cluster.xlf.lcl
- resources/localization/LCL/ja/dacpac.xlf.lcl
- resources/localization/LCL/ja/import.xlf.lcl
- resources/localization/LCL/ja/notebook.xlf.lcl
- resources/localization/LCL/ja/resource-deployment.xlf.lcl
- resources/localization/LCL/ja/schema-compare.xlf.lcl
- resources/localization/LCL/zh-Hant/dacpac.xlf.lcl
- resources/localization/LCL/zh-Hant/import.xlf.lcl
- resources/localization/LCL/zh-Hant/notebook.xlf.lcl
- resources/localization/LCL/zh-Hant/resource-deployment.xlf.lcl
- resources/localization/LCL/zh-Hant/schema-compare.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210514093438921 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210514093438921 to main

- extensions/sql-migration/package.json
- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
- extensions/sql-migration/src/models/migrationLocalStorage.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
- extensions/sql-migration/src/wizard/migrationModePage.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
- extensions/sql-migration/src/wizard/summaryPage.ts
The arm endpoints are broken, so the blob storage bits are currently disabled by UI. I am just pushing to code to the main to save some progress. 
There are some fixes and UI changes that I have made to the overall extension.
> Adding blob storage support to migration (WIP)

- resources/localization/LCL/ja/azurecore.xlf.lcl
- resources/localization/LCL/ja/cms.xlf.lcl
- resources/localization/LCL/ja/dacpac.xlf.lcl
- resources/localization/LCL/ja/notebook.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/dacpac.xlf.lcl
- resources/localization/LCL/ko/import.xlf.lcl
- resources/localization/LCL/ko/notebook.xlf.lcl
- resources/localization/LCL/ko/resource-deployment.xlf.lcl
- resources/localization/LCL/ko/schema-compare.xlf.lcl
- resources/localization/LCL/zh-Hans/dacpac.xlf.lcl
- resources/localization/LCL/zh-Hans/import.xlf.lcl
- resources/localization/LCL/zh-Hans/notebook.xlf.lcl
- resources/localization/LCL/zh-Hans/resource-deployment.xlf.lcl
- resources/localization/LCL/zh-Hans/schema-compare.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210514153254861 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210514153254861 to main

- extensionsGallery-insider.json
Vbumping migration extension 
Link to the build 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=104241&view=results
> Vbumping migration extension to 13 to fix cancel migration bug

- src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts
Addresses #15167.
I'm not a huge fan of this solution, but I haven't found a better way to do this. Any suggestions welcome 😄.
In actionbar.ts, it handles both KEY_DOWN and KEY_UP events. I checked the past 3 releases, and this functionality is broken in all of those releases while in split/md mode, so I'm fairly convinced that this has just never worked.
> Fix KEY_UP Eventing in Link Callout Dialog

- src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts
> Handle key_up in callout dialog (#15472)

- build/azure-pipelines/docker/createDrop.sh
- build/azure-pipelines/docker/sql-product-build-docker.yml
- build/azure-pipelines/linux/createDrop.sh
- build/azure-pipelines/linux/sql-product-build-linux.yml
- build/azure-pipelines/sql-product-build.yml
- build/azure-pipelines/web/sql-product-build-web.yml
- build/azure-pipelines/win32/sql-product-build-win32.yml
- build/gulpfile.reh.js
- package.json
- src/vs/workbench/contrib/terminal/common/remoteTerminalChannel.ts
Updates to reenable the web builds in the CI pipelines.  Corresponding changes in the distro branch.
> Enable docker build in CI pipeline

- extensions/mssql/config.json
Fixes https://github.com/microsoft/azuredatastudio/issues/12228
> Update SqlToolsService for language service fix

- extensions/schema-compare/package.json
- extensions/sql-database-projects/package.json
bumping the versions after these two extensions were released in insiders and RC
> bump schema compare and sql db proj versions

- CHANGELOG.md
- README.md
> May 2021 release updates

- extensionsGallery.json
will be merged and published on May release day.
> merge from rc1 gallery to stable gallery

- package.json
> update ads version after release

- src/sql/azdata.d.ts
noticed these issues when updating azdata types package
> update typing file

- extensionsGallery-insider.json
Build for the vsix file: 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=104851&view=results
> Updating migration extension in insiders 0.1.0

- extensions/notebook/src/dialog/remoteBookDialog.ts
- extensions/notebook/src/dialog/remoteBookDialogModel.ts
This PR addresses the console errors from #15524
I'll keep the issue open since I cannot repro the bug.
> Init assets in dialog model

- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
the last outstanding issue in the master issue: https://github.com/microsoft/azuredatastudio/issues/14587
> add sorting state indicator

- build/azure-pipelines/linux/sql-product-build-linux.yml
This reverts commit db5b68e04a669991d0ae63449f4d2de2599b5bff.
there is a build break caused by this commit, reverting it for now.
> Revert "Disable npm recompile step (#15548)"

- src/vs/workbench/browser/parts/editor/editorGroupView.ts
This PR fixes #14106 
I didn't observe issues with this change.
> fix file compare issue

- extensions/mssql/config.json
This PR updates the STS release version number in the config.json file for the mssql extension.
> SqlToolService release version updated to 105 from 104

- extensionsGallery-insider.json
Build to get vsix:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=105490&view=results
> Updating migration extension to 0.1.1 in insiders gallery 

- build/azure-pipelines/win32/sql-product-build-win32.yml
> Added build changes to add TSGOps extensions into the build

- extensions/machine-learning/config.json
- extensions/machine-learning/src/packageManagement/sqlRPackageManageProvider.ts
Updating sqlmlutils Python to 1.1.0 and R to 1.0.0. the new versions include multiple hotfixes.
> ML Extension - Updating sqlmlutils package for R and Python

- extensions/notebook/src/book/bookModel.ts
- extensions/notebook/src/book/bookPinManager.ts
- extensions/notebook/src/book/bookTreeView.ts
- extensions/notebook/src/common/utils.ts
- extensions/notebook/src/test/common/utils.test.ts
> Show book's notebook TOC title in pinned notebooks view

- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/setup.js
- src/sql/workbench/contrib/notebook/browser/notebookViews/notebookViewsGrid.component.ts
- src/vs/code/browser/workbench/workbench-dev.html
- src/vs/code/browser/workbench/workbench.html
> Fix Gridstack DD import

- extensions/arc/notebooks/arcDeployment/deploy.postgres.existing.arc.ipynb
- extensions/arc/package.json
- extensions/arc/src/providers/arcControllersOptionsSourceProvider.ts
> Use namespace for azdata login with postgres deployment 

- build/azure-pipelines/distro-build.yml
- build/azure-pipelines/docker/Dockerfile
- build/azure-pipelines/linux/Dockerfile
- build/azure-pipelines/sql-product-build.yml
ubuntu 16.04 is obsolete, update it to use 18.04
testing build: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=106165&view=results, it failed because I included unstable tests.
> update ubuntu version

- extensions/sql-migration/package.json
- extensions/sql-migration/src/api/azure.ts
> Adding more regions to migration target page

- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/15396
before:
after:
> Filter out system dbs from create project from db dialog

- extensionsGallery-insider.json
Build link 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=106300&view=results
> Updating migration extension in insiders to 0.1.2

- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.css
> flex style in split mode

- src/sql/workbench/contrib/notebook/browser/cellViews/interfaces.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
- src/sql/workbench/contrib/notebook/browser/find/notebookFindDecorations.ts
- src/sql/workbench/contrib/notebook/browser/find/notebookFindModel.ts
- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
- src/sql/workbench/contrib/notebook/browser/notebookEditor.ts
- src/sql/workbench/contrib/notebook/test/stubs.ts
- src/sql/workbench/services/notebook/browser/notebookService.ts
Highlight all matches in a notebook when find is invoked with a search string:
> Highlight all matches in Notebook on Find

- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
This PR addresses https://github.com/microsoft/azuredatastudio/issues/15632
> Filter out prose package from recommended pip packages during Python upgrade

- extensionsGallery-insider.json
- extensionsGallery.json
Link to VSIX: 
https://microsoft-my.sharepoint.com/:u:/p/danmar/EfjgpHgZADZIgce87OHHjFABwSqf7Qehf4kDU15zuAU0MA?e=MRfbu1
> Update SandDance extension 3.2.0

- extensions/machine-learning/package.json
Version bump for Machine learning extension
> ML extension version bump

- extensions/sql-migration/src/api/utils.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
This PR fixes
* error in function returning -1 when index is 0
* pick better constant name for table column width
> fix findDropDownItemIndex index search bug

- src/sql/azdata.d.ts
This has been around long enough and I think it's time to promote this. Not promoting the other callout-related params since I'm still not sure those are the cleanest way to handle those (maybe it's time to make a separate options interface for those?)
Brought up in https://github.com/microsoft/azuredatastudio/issues/15643
> Promote updated width parameter for createModelViewDialog to stable

- extensions/machine-learning/package.json
Merging a commit for updating ML extension version: https://github.com/microsoft/azuredatastudio/commit/95704dc45ecedef4d88076466fbccba4ffc11dae
Adding a link to the aprroved item : https://github.com/microsoft/azuredatastudio/issues/15650
> ML extension version bump (#15407)

- extensionsGallery-insider.json
VSIX from the release build: https://mssqltools.visualstudio.com/_apis/resources/Containers/3115191/drop?itemPath=drop%2Fextensions%2Fmachine-learning-0.10.0.vsix
> Update extensionsGallery-insider.json for ML 0.10.0

- extensionsGallery.json
VSIX from the release build: https://mssqltools.visualstudio.com/_apis/resources/Containers/3115191/drop?itemPath=drop%2Fextensions%2Fmachine-learning-0.10.0.vsix
> Updating extensionGallery.json for ML 0.10.0

- extensionsGallery-insider.json
VSIX from the release build: https://mssqltools.visualstudio.com/_apis/resources/Containers/3115191/drop?itemPath=drop%2Fextensions%2Fsql-database-projects-0.10.0.vsix
> Updating extensionsGallery for Sql Database Projects(insider)

- extensions/kusto/src/utils.ts
- extensions/mssql/src/utils.ts
This passes in the current locale of ADS so the tools can switch to the appropriate languages (will be used in conjunction with a PR for sqltoolsservice)
> Localization option added to Kusto and MSSQL

- CHANGELOG.md
- README.md
- extensions/admin-pack/README.md
- extensions/admin-tool-ext-win/README.md
- extensions/agent/README.md
- extensions/arc/README.md
- extensions/asde-deployment/README.md
- extensions/azdata/README.md
- extensions/azdata/src/constants.ts
- extensions/azurecore/README.md
- extensions/azurehybridtoolkit/README.md
- extensions/big-data-cluster/README.md
- extensions/cms/README.md
- extensions/dacpac/README.md
- extensions/data-workspace/README.md
- extensions/import/README.md
- extensions/notebook/README.md
- extensions/profiler/README.md
- extensions/query-history/README.md
- extensions/resource-deployment/README.md
- extensions/schema-compare/README.md
- extensions/sql-assessment/README.md
- extensions/sql-database-projects/README.md
- extensions/sql-migration/README.md
- product.json
The links should be locale-independent (they will redirect to the appropriate language based on user browser settings)
> Remove en-us from links

- src/sql/azdata.d.ts
- src/sql/workbench/contrib/query/browser/queryResultsView.ts
- src/sql/workbench/contrib/query/browser/statusBarItems.ts
- src/sql/workbench/services/query/common/query.ts
this PR fixes #7335
Adding null checks.
> add null check for errors in the console while using query editor

- src/sql/workbench/contrib/query/browser/gridPanel.ts
- src/sql/workbench/contrib/query/browser/queryResultsView.ts
this is a follow up of https://github.com/microsoft/azuredatastudio/pull/15711
previous PR fixes the original error, after it is merged, I was trying to verify it in the main branch and noticed some other errors when I waited for the cancel to finish. these changes are all related to the same error as the PR mentioned above.
> fix more issues related to query cancel

- package.json
- test/automation/src/sql/createBookDialog.ts
- test/automation/src/workbench.ts
- test/smoke/package.json
- test/smoke/src/sql/areas/notebook/createBook.test.ts
- test/smoke/src/sql/main.ts
- test/smoke/yarn.lock
Simple smoke test to create new book using dialog
Note that I had to add a sleep at the beginning to wait for STS to start up. I'm going to follow up with looking into a better way to do that since this is something a lot of tests are going to need to do.
> Add smoke test for Create Book dialog

- extensions/arc/src/test/ui/components/filePicker.test.ts
- extensions/arc/src/ui/components/filePicker.ts
- extensions/arc/src/ui/dialogs/connectControllerDialog.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15717
> Add aria-label to kube config input box

- extensions/mssql/config.json
Contains the updates from this PR: https://github.com/microsoft/sqltoolsservice/pull/1215 enables logging from Migration Assessments which will get put in the `\User\AppData\Roaming\azuredatastudio\logs\[dateTtimestamp]\exthost1\Microsoft.mssql` file path
> Bump STS Version to 109

- src/sql/base/browser/ui/buttonMenu/buttonMenu.css
- src/sql/base/browser/ui/taskbar/media/taskbar.css
Fixes https://github.com/microsoft/azuredatastudio/issues/15784
Query Editor :
Dashboard : 
Notebook Editor :
> Fix SQL taskbar icons

- extensions/arc/src/localizedConstants.ts
- extensions/arc/src/ui/components/keyValueContainer.ts
- extensions/arc/src/ui/dashboards/miaa/miaaComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15756
Labels added to : 
* Copy buttons on Connection Strings pages
* Spin inputs on Compute + Storage pages 
* Copy buttons on PG Properties page
> Add aria labels to buttons and spin inputs on Arc dashboards

- extensions/arc/src/test/ui/components/filePicker.test.ts
- extensions/arc/src/ui/components/filePicker.ts
- extensions/arc/src/ui/dialogs/connectControllerDialog.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15732
`Kube Config File Path  edit  required  C:\Users\chgagnon\.kube\config`
> Add required field to kube config picker

- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.css
Fixes #15797. Was introduced lately (before merge), but I haven't root caused it.
> Notebooks: Remove Unnecessary Horizontal Scrollbar

- extensionsGallery-insider.json
Link for the build: 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=108043&view=results
> Updating extension to 0.1.3 and adding feature preview flag

- test/automation/src/application.ts
Note this fixes them not running at all - it's likely that the individual tests may require fixing themselves with the changes brought in by the merge.
> Fix smoke tests

- test/automation/src/application.ts
- test/smoke/src/sql/areas/notebook/createBook.test.ts
Also added some comments I meant to add in an earlier PR
> Wait for SqlToolsService to start before running smoke tests

- build/azure-pipelines/sql-product-build.yml
give it 30 minutes more to experiment and see whether the compile step can finish within reasonable extra time.
> increase the timeout for compile step

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/common/iconHelper.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/controllers/mainController.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/models/dataSources/sqlConnectionStringSource.ts
- extensions/sql-database-projects/src/models/publishProfile/publishProfile.ts
- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
- extensions/sql-database-projects/yarn.lock
Same as https://github.com/microsoft/azuredatastudio/pull/15871
> Handle no azdata API in sql db proj extension gracefully

- extensions/arc/package.json
- extensions/azdata/package.json
Skipping one since that's being used for bugbash testing currently.
> vBump arc and azdata

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/dialogs/openExistingDialog.ts
> Remove duplicate extensions from browse filter

- extensions/integration-tests/src/test/schemaCompare.test.ts
Adding better logs for transient failure cases in schema compare.
> Adding more logs for transient failure cases in schema compare

- test/automation/src/sql/notebook.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
PR creates a suite for the notebookToolbar actions that we can add to. This specific smoke test focused on Collapse and Expand Cells Action.
> Add simple smoke test for collapse/expand cell 

- test/automation/src/sql/notebook.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
- moved trust notebook test into notebook toolbar actions suite
- remove toolbar methods from notebook class
> Clean up trust notebook smoke test

- extensions/theme-monokai/themes/monokai-color-theme.json
- src/vs/platform/actions/browser/menuEntryActionViewItem.css
- src/vs/workbench/contrib/scm/browser/media/scm.css
- src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts
- src/vs/workbench/contrib/tasks/browser/taskQuickPick.ts
- src/vs/workbench/contrib/tasks/browser/tasksQuickAccess.ts
- src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts
- src/vs/workbench/contrib/terminal/browser/terminalTabbedView.ts
- src/vs/workbench/contrib/terminal/common/remoteTerminalChannel.ts
- src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts
- src/vs/workbench/services/configurationResolver/common/configurationResolver.ts
- src/vs/workbench/services/configurationResolver/common/variableResolver.ts
1.56.1 - https://github.com/microsoft/vscode/releases/tag/1.56.1
https://github.com/microsoft/vscode/commit/7259955ce318a2bb2a86ee121c34dcaab0a86e45
https://github.com/microsoft/vscode/commit/5f3466a21e80b2c016a1c0cbe2af683c9072d0a7
https://github.com/microsoft/vscode/commits/1.56.1 
(note this one is weird, they say they fixed them but the only thing I see in that branch is a distro bump. My best guess is that their distro has all these files in it, but ours doesn't so I'm going to make the changes here for us as well)
1.56.2 - https://github.com/microsoft/vscode/releases/tag/1.56.2
https://github.com/microsoft/vscode/commit/fb3e51a1f0912c186d91d021b8885dee4ab9b638
https://github.com/microsoft/vscode/commit/e95e22e03aacbfdde8339de5a4982d3de4d53279 …
> Port VS Code 1.56.0 Hotfixes 

- src/sql/workbench/contrib/queryHistory/browser/queryHistoryView.ts
- src/sql/workbench/contrib/queryHistory/electron-browser/queryHistory.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15909
Register actions using registerAction2 with a menu contribution.
> Fix query history view actions

- extensions/sql-database-projects/package.json
Bump version after insider+RC release.
> Bump Sql Db Projects extension version

- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.css
> fix WYSIWYG toolbar

- test/automation/src/sql/notebook.ts
This PR utilizes the helper function that was created previously to get cellIds instead.
> Clean up smoke test to use helper function

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dashboard/sqlServerDashboard.ts
- src/sql/workbench/browser/modelComponents/divContainer.component.ts
- src/sql/workbench/browser/modelComponents/media/divContainer.css
-Moving dashboard card styling to outer div container from inner form container
This PR fixes #15734 
Fixing focus outline
Before:
After:
Before:
Fixing hover background
Focus and hover on different themes:
Dark:
Light:
HC:
> - Adding mouse in and out styling to clickbale divs

- .yarnrc
- cgmanifest.json
- package.json
- src/vs/platform/windows/electron-main/window.ts
- yarn.lock
For https://github.com/microsoft/azuredatastudio/issues/15968 (needs validation first)
This is a cherry-pick of https://github.com/microsoft/vscode/commit/d17d7ca46cc166b156e91c6205465d7f01826189 which addresses a similar issue in VS Code : https://github.com/microsoft/vscode/issues/123105
> Bump electron@12.0.7

- package.json
- test/smoke/src/sql/main.ts
Forgot to do this when I updated electron.
> Update sqlite for new electron version

- extensions/xml-language-features/package.json
- resources/xlf/LocProject.json
- resources/xlf/en/admin-tool-ext-win.xlf
- resources/xlf/en/agent.xlf
- resources/xlf/en/arc.xlf
- resources/xlf/en/azurecore.xlf
- resources/xlf/en/cms.xlf
- resources/xlf/en/dacpac.xlf
- resources/xlf/en/data-workspace.xlf
- resources/xlf/en/import.xlf
- resources/xlf/en/machine-learning.xlf
- resources/xlf/en/notebook.xlf
- resources/xlf/en/profiler.xlf
- resources/xlf/en/schema-compare.xlf
- resources/xlf/en/server-report.xlf
- resources/xlf/en/sql-assessment.xlf
- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql-migration.xlf
- resources/xlf/en/sql.xlf
- resources/xlf/en/xml-language-features.xlf
This is just a simple XLF update using the new update script, also added XML-Language-Features to LocProject.json since it wasn't added before.
I will await for translations from the localization team before creating new language packs based on these files. 
Import doesn't work currently, but its kept in here just for reference and also to make it easier to reuse translations when it is updated to be webpacked.
This new langpack will be intended for the July Release due to it using the latest resources.
> Update for English XLFs

- src/sql/workbench/contrib/notebook/browser/notebook.css
This PR fixes https://github.com/microsoft/azuredatastudio/issues/15895
> Fix notebook toolbar when ADS screen width is decreased

- extensions/notebook/package.json
> Add create book entry point to the bookTreeView

- extensions/azcli/package.json
- extensions/azcli/package.nls.json
- extensions/azcli/src/constants.ts
- extensions/azcli/src/extension.ts
Updating some of the values that will conflict with the existing azdata CLI extension now to avoid weird errors and issues during dev builds. Rest of the references can be cleaned up later as time permits.
> Update some key az CLI references

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/mainController.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
- extensions/sql-database-projects/src/models/publishProfile/publishProfile.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
- extensions/sql-database-projects/src/typings/vscode-mssql.d.ts
WIP, this is pretty much all of the UI bits. Getting it out now to reduce size of PRs. Next step is to start hooking up the DacFX/Schema Compare/Connection stuff from the MSSQL extension. 
For this initial PR focus mostly on issues with the code itself - the actual flow of the quickpick is going to be reviewed separately so things like string changes, quickpick options, etc can be commented on but I'll likely just collect those and fix them in a follow-up PR once I've been able to walk people through the entire experience end-to-end. 
1. 
2. 
3. 
4. 
5.
> Add basic structure for publish project quickpick

- extensions/notebook/package.json
- extensions/notebook/src/book/bookTocManager.ts
- extensions/notebook/src/book/bookVersionHandler.ts
- extensions/notebook/src/test/book/bookTocManager.test.ts
- extensions/notebook/yarn.lock
Fix some of the broken tests after the vscode merge (I still need to fix another one, but I'll create a separate PR for it) 
I added js-yaml definition to the package.json.
This PR fixes #15791
> Fix book toc manager tests

- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
- extensions/notebook/src/jupyter/jupyterSessionManager.ts
- extensions/notebook/src/test/model/sessionManager.test.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/15656
> Check kernel dependencies when a new session is started

- extensions/azuremonitor/package.json
> Set azuremonitor Extension ID to 83

- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
- src/sql/workbench/browser/modelComponents/loadingComponent.component.ts
Before:
After:
Fixing Loading component alignment in the page:
Before:
After:
> Fixing some assessment styling

- extensionsGallery-insider.json
> Added AzureMonitor to insider gallery

- src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
- src/sql/workbench/services/queryEditor/common/queryEditorService.ts
- src/sql/workbench/services/queryEditor/test/common/testQueryEditorService.ts
- src/vs/workbench/browser/parts/editor/editorGroupView.ts
- src/vs/workbench/browser/parts/editor/tabsTitleControl.ts
(cherry picked from commit 9fc2cff6541479bf8598d37ec9e3fb898edf3e40)
Fixes #16074
> [Port] Fix opening new untitled query (#16078)

- src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.contribution.ts
Ports fix for https://github.com/microsoft/azuredatastudio/issues/15980
> Remove duplicate Getting Started menu (#16077)

- build/lib/i18n.js
- build/lib/i18n.ts
- resources/xlf/en/arc.xlf
- resources/xlf/en/sql.xlf
This changes i18n.ts to sort the string keys found in the map to guarantee a consistent SQL file each time the update function is run (tested). It also adds in the now sorted sql core xlf file and a small change to the arc file to include a new string. 
Currently there is no way to directly get a key array from the json key map as its a custom class, (using "properties" or "keys" returns undefined), however using "in" works as before.
> Added Sorted Core Strings

- extensionsGallery-insider.json
> Fixed azuremonitor extension in insider gallery

- src/sql/workbench/services/accountManagement/browser/media/accountPicker.css
This PR fixes #15820
original pr:https://github.com/microsoft/azuredatastudio/pull/16086
> port account dropdown fix

- extensionsGallery-insider.json
- extensionsGallery.json
This PR fixes some bugs and adds new features.
See [Change Log](https://github.com/ernstc/SqlDataInspector/blob/main/CHANGELOG.md) for full details.
> Updated extension Sql Data Inspector to version 0.3.0

- extensions/integration-tests/src/onboarding/developers.ts
> Developer added

- extensions/azurecore/package.json
- extensions/azurecore/src/azureResource/azure-resource.d.ts
- extensions/azurecore/src/azureResource/utils.ts
- extensions/azurecore/src/azurecore.d.ts
- extensions/azurecore/src/extension.ts
- extensions/azurecore/yarn.lock
- extensions/machine-learning/src/test/stubs.ts
- extensions/sql-migration/src/api/azure.ts
> Adding blob containers and storage key api to azure core

- extensions/sql-database-projects/package.json
Need to bump this because of the changes in the data workspace extension to remove the references to workspaces.
> bump ADS dependency for sql database projects

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/azurecore.xlf.lcl
- resources/localization/LCL/fr/notebook.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/azurecore.xlf.lcl
- resources/localization/LCL/ko/notebook.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210713214953133 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210713214953133 to main

- extensions/sql-database-projects/package.json
Closes #16105. Cherry-picked from #16092
> [Port] bump ADS dependency for sql database projects

- extensions/machine-learning/src/prediction/predictService.ts
- extensions/mssql/src/main.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/browser/mainThreadQueryEditor.ts
- src/sql/workbench/api/common/extHostQueryEditor.ts
- src/sql/workbench/api/common/sqlExtHost.api.impl.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
Fixes #16108
(cherry picked from commit a0f46fec65665a106bc42fff05d7705bed7aa47c)
> [Port] Add openQueryDocument API (#16117)

- resources/localization/LCL/pt-BR/azurecore.xlf.lcl
- resources/localization/LCL/pt-BR/notebook.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/azurecore.xlf.lcl
- resources/localization/LCL/ru/notebook.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714033438677 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714033438677 to main

- resources/localization/LCL/de/azurecore.xlf.lcl
- resources/localization/LCL/de/notebook.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/ja/azurecore.xlf.lcl
- resources/localization/LCL/ja/notebook.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hans/notebook.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hant/notebook.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714153526881 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714153526881 to main

- resources/xlf/de/sql.de.xlf
- resources/xlf/es/sql.es.xlf
- resources/xlf/fr/azurecore.fr.xlf
- resources/xlf/fr/notebook.fr.xlf
- resources/xlf/fr/sql.fr.xlf
- resources/xlf/it/sql.it.xlf
- resources/xlf/ja/sql.ja.xlf
- resources/xlf/ko/azurecore.ko.xlf
- resources/xlf/ko/notebook.ko.xlf
- resources/xlf/ko/sql.ko.xlf
- resources/xlf/pt-br/azurecore.pt-BR.xlf
- resources/xlf/pt-br/notebook.pt-BR.xlf
- resources/xlf/pt-br/sql.pt-BR.xlf
- resources/xlf/ru/azurecore.ru.xlf
- resources/xlf/ru/notebook.ru.xlf
- resources/xlf/ru/sql.ru.xlf
- resources/xlf/zh-hans/sql.zh-Hans.xlf
- resources/xlf/zh-hant/sql.zh-Hant.xlf
Adds small updates to notebook, sql, and azurecore.
This will be the last XLF pull request before being used to create the new langpacks.
> Last Language XLF update before creation of langpacks

- src/sql/workbench/contrib/dataExplorer/browser/dataExplorerViewlet.ts
- src/sql/workbench/contrib/resourceDeployment/browser/resourceDeployment.contribution.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15824
PR to main - https://github.com/microsoft/azuredatastudio/pull/16122
(cherry picked from commit 5524a3659cbf1221728eaa2fad933bf9521e95ca)
> Secondary actions (#16122)

- resources/localization/LCL/es/azurecore.xlf.lcl
- resources/localization/LCL/es/notebook.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/it/azurecore.xlf.lcl
- resources/localization/LCL/it/notebook.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714213324106 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714213324106 to main

- resources/localization/LCL/es/azurecore.xlf.lcl
- resources/localization/LCL/es/notebook.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/it/azurecore.xlf.lcl
- resources/localization/LCL/it/notebook.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714213342277 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714213342277 to main

- resources/localization/LCL/es/azurecore.xlf.lcl
- resources/localization/LCL/es/notebook.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/it/azurecore.xlf.lcl
- resources/localization/LCL/it/notebook.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714213406653 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714213406653 to main

- resources/localization/LCL/es/azurecore.xlf.lcl
- resources/localization/LCL/es/notebook.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/it/azurecore.xlf.lcl
- resources/localization/LCL/it/notebook.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714213442633 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714213442633 to main

- resources/localization/LCL/es/azurecore.xlf.lcl
- resources/localization/LCL/es/notebook.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/it/azurecore.xlf.lcl
- resources/localization/LCL/it/notebook.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714213542984 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714213542984 to main

- resources/localization/LCL/es/azurecore.xlf.lcl
- resources/localization/LCL/es/notebook.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/it/azurecore.xlf.lcl
- resources/localization/LCL/it/notebook.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714213731525 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210714213731525 to main

- resources/xlf/en/sql.xlf
Very Small PR that adds the Resource Deployment Title string to the English XLF. This will be checked in later tonight to be localized by the team.
> Resource deployment title string added to SQL

- extensions/azurecore/src/azureResource/providers/azuremonitor/azuremonitorTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/kusto/kustoTreeDataProvider.ts
Added missing properties in kustoTreeDataProvider and azuremonitorTreeDataProvider
> Fixed Kusto and AzureMonitor in Azure Viewlet

- resources/xlf/en/arc.xlf
Loc resources PR complementary to #16150
> Update to arc extension resources

- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/16079
> Only show Python upgrade prompt once when Jupyter server is started

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/ko/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/ko/data-workspace.xlf.lcl
- resources/localization/LCL/ko/sql-assessment.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/kusto.xlf.lcl
- resources/localization/LCL/pt-BR/machine-learning.xlf.lcl
- resources/localization/LCL/pt-BR/sql-assessment.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/asde-deployment.xlf.lcl
- resources/localization/LCL/ru/query-history.xlf.lcl
- resources/localization/LCL/ru/sql-assessment.xlf.lcl
- resources/localization/LCL/zh-Hant/machine-learning.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715093855171 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715093855171 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/ko/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/ko/data-workspace.xlf.lcl
- resources/localization/LCL/ko/sql-assessment.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/kusto.xlf.lcl
- resources/localization/LCL/pt-BR/machine-learning.xlf.lcl
- resources/localization/LCL/pt-BR/sql-assessment.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/asde-deployment.xlf.lcl
- resources/localization/LCL/ru/query-history.xlf.lcl
- resources/localization/LCL/ru/sql-assessment.xlf.lcl
- resources/localization/LCL/zh-Hant/machine-learning.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715093926733 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715093926733 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/ko/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/ko/data-workspace.xlf.lcl
- resources/localization/LCL/ko/sql-assessment.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/kusto.xlf.lcl
- resources/localization/LCL/pt-BR/machine-learning.xlf.lcl
- resources/localization/LCL/pt-BR/sql-assessment.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/asde-deployment.xlf.lcl
- resources/localization/LCL/ru/query-history.xlf.lcl
- resources/localization/LCL/ru/sql-assessment.xlf.lcl
- resources/localization/LCL/zh-Hant/machine-learning.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715094002970 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715094002970 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/ko/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/ko/data-workspace.xlf.lcl
- resources/localization/LCL/ko/sql-assessment.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/kusto.xlf.lcl
- resources/localization/LCL/pt-BR/machine-learning.xlf.lcl
- resources/localization/LCL/pt-BR/sql-assessment.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/asde-deployment.xlf.lcl
- resources/localization/LCL/ru/query-history.xlf.lcl
- resources/localization/LCL/ru/sql-assessment.xlf.lcl
- resources/localization/LCL/zh-Hant/machine-learning.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715094050718 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715094050718 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/ko/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/ko/data-workspace.xlf.lcl
- resources/localization/LCL/ko/sql-assessment.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/kusto.xlf.lcl
- resources/localization/LCL/pt-BR/machine-learning.xlf.lcl
- resources/localization/LCL/pt-BR/sql-assessment.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/asde-deployment.xlf.lcl
- resources/localization/LCL/ru/query-history.xlf.lcl
- resources/localization/LCL/ru/sql-assessment.xlf.lcl
- resources/localization/LCL/zh-Hant/machine-learning.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715094204553 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715094204553 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/ko/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/ko/data-workspace.xlf.lcl
- resources/localization/LCL/ko/sql-assessment.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/kusto.xlf.lcl
- resources/localization/LCL/pt-BR/machine-learning.xlf.lcl
- resources/localization/LCL/pt-BR/sql-assessment.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/asde-deployment.xlf.lcl
- resources/localization/LCL/ru/query-history.xlf.lcl
- resources/localization/LCL/ru/sql-assessment.xlf.lcl
- resources/localization/LCL/zh-Hant/machine-learning.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715094404547 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715094404547 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/ko/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/ko/data-workspace.xlf.lcl
- resources/localization/LCL/ko/sql-assessment.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/kusto.xlf.lcl
- resources/localization/LCL/pt-BR/machine-learning.xlf.lcl
- resources/localization/LCL/pt-BR/sql-assessment.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/asde-deployment.xlf.lcl
- resources/localization/LCL/ru/query-history.xlf.lcl
- resources/localization/LCL/ru/sql-assessment.xlf.lcl
- resources/localization/LCL/zh-Hant/machine-learning.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715153705687 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715153705687 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/ko/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/ko/data-workspace.xlf.lcl
- resources/localization/LCL/ko/sql-assessment.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/azurehybridtoolkit.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/kusto.xlf.lcl
- resources/localization/LCL/pt-BR/machine-learning.xlf.lcl
- resources/localization/LCL/pt-BR/sql-assessment.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/asde-deployment.xlf.lcl
- resources/localization/LCL/ru/query-history.xlf.lcl
- resources/localization/LCL/ru/sql-assessment.xlf.lcl
- resources/localization/LCL/zh-Hant/machine-learning.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715153737180 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210715153737180 to main

- resources/xlf/en/sql-database-projects.xlf
> changes to sqldatabaseprojects

- extensions/data-workspace/src/dialogs/newProjectDialog.ts
- extensions/data-workspace/src/dialogs/openExistingDialog.ts
This is Main branch PR for https://github.com/microsoft/azuredatastudio/issues/16113
> Fixing the error order for Project dialog validation

- extensions/azurecore/src/azureResource/providers/azuremonitor/azuremonitorTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/kusto/kustoTreeDataProvider.ts
Added missing properties in kustoTreeDataProvider and azuremonitorTreeDataProvider (#16153)
> [Port] Fixed Azure Viewlet for Kusto and Azure Monitor

- extensions/azcli/src/extension.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/16152
@candiceye You'll need to add some of this logic back in for your PR, but for the time being just trying to reduce annoyance for the other devs 😄
> Remove second prompt for azdata install

- extensions/data-workspace/src/dialogs/newProjectDialog.ts
- extensions/data-workspace/src/dialogs/openExistingDialog.ts
* Fixing the error order for Project dialog
* Taking PR review comments and making the change for open project also
This PR fixes #16113
> Fixing the error order for Project dialog validation (#16141)

- src/sql/workbench/browser/modelComponents/viewBase.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/16131
(cherry picked from commit 1e81b6f0540eb1b01c627cb04a4025e8f878b1d4)
> [Port] Fix component unregistering from parent (#16166)

- extensions/azcli/src/extension.ts
This is to fix some smoke tests that were failing because of a new prompt that the new Azure CLI extension added. This extension isn't going to be released in this release so no concerns about functionality changes here. 
(cherry picked from commit 2a74ad4190fa2d2aa5e3eae28d8647ecae634c7d)
> Remove second prompt for azdata install (#16182)

- extensionsGallery-insider.json
- extensionsGallery.json
Link to VSIX:
https://microsoft-my.sharepoint.com/:u:/p/danmar/Ee0Ja8jFtntJjjnBBDbDPQwBmnHMqVKiWycemidnMsuwVg?e=EGyFN7
> Update SandDance extension 3.3.0

- extensions/import/package.json
> Updating import extension version in package.json

- src/vs/base/browser/ui/button/button.ts
port fix to release branch
This PR fixes #16142
> [Port] make button not focusable when disabled (#16185)

- extensions/import/package.json
This PR fixes #16202
PR to the main branch #16190
> Updating import extension version in July release 

- extensionsGallery-insider.json
Link to the Build https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=111409&view=artifacts&pathAsName=false&type=publishedArtifacts
> Updating import extension to 1.3.1 in RC

- test/smoke/src/sql/areas/notebook/addRemoteBook.test.ts
Until https://github.com/microsoft/azuredatastudio/issues/16039 can be fixed
> Disable add remote book test

- extensions/azurecore/extension.webpack.config.js
- resources/xlf/en/data-workspace.xlf
- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql-migration.xlf
Adds azure-storage to the webpack as its an external dependency, (required for webpacking to work properly)
> azurecore extension webpack update with new XLFs for other extensions

- src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts
- src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts
- src/sql/workbench/contrib/notebook/common/utils.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookMarkdown.test.ts
This PR fixes #15942
PR from main #16133
> [PORT] Fix Windows WYSIWYG linking issue

- extensionsGallery-insider.json
- extensionsGallery.json
> Fixing RC gallery update for import extension 

- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
This PR fixes #16021
This PR fixes #15999
> set the focus back to table after sort/filter

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717033749918 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717033749918 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717033848732 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717033848732 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717033958046 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717033958046 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717034129234 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717034129234 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717034257431 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717034257431 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717034508823 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717034508823 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717094038355 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717094038355 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717094108312 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717094108312 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717094142877 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717094142877 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717094229261 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717094229261 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717094338490 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717094338490 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717094535063 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210717094535063 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718033439401 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718033439401 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718033457773 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718033457773 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718033520847 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718033520847 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718033555733 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718033555733 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718033655130 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718033655130 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718033842635 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718033842635 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718093356697 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718093356697 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718093417348 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718093417348 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718093442536 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718093442536 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718093519926 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718093519926 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718093620574 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718093620574 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718093809077 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718093809077 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718153416692 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718153416692 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718153436370 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718153436370 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718153501620 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718153501620 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718153538577 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718153538577 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718153639216 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718153639216 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718153827699 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718153827699 to main

- resources/xlf/en/sql-migration.xlf
- resources/xlf/en/sql.xlf
> added more migration and profiler core strings

- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718213248092 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718213248092 to main

- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718213331739 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718213331739 to main

- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718213408148 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718213408148 to main

- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718213510687 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718213510687 to main

- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718213712538 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718213712538 to main

- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718213307408 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210718213307408 to main

- resources/localization/LCL/ru/data-workspace.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719033310398 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719033310398 to main

- resources/localization/LCL/ru/data-workspace.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719033330033 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719033330033 to main

- resources/localization/LCL/ru/data-workspace.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719033354615 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719033354615 to main

- resources/localization/LCL/ru/data-workspace.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719033431718 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719033431718 to main

- resources/localization/LCL/ru/data-workspace.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719033532782 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719033532782 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719153303039 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719153303039 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719153322032 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719153322032 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719153346148 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719153346148 to main

- extensionsGallery.json
build with vsix https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=111513&view=artifacts&pathAsName=false&type=publishedArtifacts
> update sql database projects to 0.11.0 in RC

- resources/xlf/en/arc.xlf
> small string to arc added

- extensionsGallery-insider.json
Link to the Build https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=111409&view=artifacts&pathAsName=false&type=publishedArtifacts
> Updating import to 1.3.1 in Insiders

- extensions/theme-carbon/themes/dark_carbon.json
- extensions/theme-carbon/themes/light_carbon.json
> update badge colors

- extensionsGallery-insider.json
> update sql database projects to 0.11.0 in insiders

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719213315167 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719213315167 to main

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719213334486 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719213334486 to main

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719213359439 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719213359439 to main

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719213437510 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719213437510 to main

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719213538877 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719213538877 to main

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719213728004 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210719213728004 to main

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720033315610 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720033315610 to main

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720033334392 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720033334392 to main

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720033358262 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720033358262 to main

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720033434883 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720033434883 to main

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720033535491 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720033535491 to main

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720033723912 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720033723912 to main

- test/automation/src/code.ts
Makes for easier debugging (for example if an unexpected element is being selected).
Additional follow-up tasks that could be useful to consider as needed : 
1. See if we can get the actual HTML node back from the driver to print out
2. Add to more functions, I just added it to a few that seemed most useful to start with
Some examples of output : 
`[2021-07-20T02:21:10.726Z] got elements {"tagName":"DIV","className":"notebook-cell","textContent":"\n\t\t\t\t\n\t\t\t\t\n\n\t\n\t\t\n\n\t[ ]\n\t\n\t\t\n\t\t\t\n\t\t\t\t1-- testEnter to Rename, Shift+Enter to Preview\n\t\t\t\n\t\t\n\t\t\n\n\t\n\n\n\t\t\n\t\n\n\n\t\n\t\n\t\t\n\t\t\n\t\n\n\n\t\t\t\t\n\t\t\t","attributes":{"class":"notebook-cell","id":"0"},"children":[],"left":312,"top":149}`
```
[2021-07-20T02:21:10.554Z] got elements …
```
> Print out found elements during smoke tests

- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720093329094 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720093329094 to main

- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720093349273 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720093349273 to main

- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720093413668 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720093413668 to main

- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720093450684 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720093450684 to main

- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720093551377 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720093551377 to main

- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720093740512 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720093740512 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720153329271 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720153329271 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720153349492 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720153349492 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720153414356 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720153414356 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720153451953 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720153451953 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720153554845 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720153554845 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720153745917 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720153745917 to main

- extensionsGallery-insider.json
> update to extensionsGallery insider.

- resources/xlf/en/arc.xlf
- resources/xlf/en/sql.xlf
> small update to arc and sql

- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
- extensions/sql-database-projects/src/typings/vscode-mssql.d.ts
Lets the MSSQL extension handle prompting the user to choose a connection.
> List connections for sql proj publish quickpick

- src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts
> Fixed actions in scripting.contribution.ts for Azure Monitor

- extensions/azurecore/src/azureResource/providers/azuremonitor/azuremonitorTreeDataProvider.ts
> Fixed container label for Azure Monitor Logs in Azure Viewlet.

- extensions/azuremonitor/package.json
> Changed Kernel Name from LogAnalytics to AzureMonitorLogs

- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720213444428 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210720213444428 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210721033317194 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210721033317194 to main

- resources/localization/LCL/es/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210721153244277 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210721153244277 to main

- extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresResourceHealthPage.ts
Switched to dataValues in declarative tables and use of setDataValues for tables that will be updated. 
(Left out parameters dashboard since this will be fixed in a separate PR)
> Switched deprecated data in declarative table to be dataValues

- CHANGELOG.md
- README.md
> Update README.md and changelog.md for release1.31

- extensions/azuremonitor/package.json
Bumped version for changes made to AzureMonitorLogs extension.
> AzureMonitorLogs version bump

- extensionsGallery-insider.json
- extensionsGallery.json
> Merge from Extensions/rc1 to Release/extensions

- resources/localization/LCL/de/arc.xlf.lcl
- resources/localization/LCL/de/azurecore.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ja/azurecore.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210721213426074 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210721213426074 to main

- resources/localization/LCL/de/arc.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
- resources/localization/LCL/pt-BR/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210722093320954 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210722093320954 to main

- resources/localization/LCL/de/arc.xlf.lcl
- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/ru/azurecore.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210722153257080 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210722153257080 to main

- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
- extensions/sql-database-projects/src/typings/vscode-mssql.d.ts
Goes with https://github.com/microsoft/vscode-mssql/pull/17019
> Separate connect and listdatabases call for publish

- resources/localization/LCL/es/arc.xlf.lcl
- resources/localization/LCL/es/azurecore.xlf.lcl
- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/fr/azurecore.xlf.lcl
- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/it/azurecore.xlf.lcl
- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/ko/azurecore.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210722213523221 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210722213523221 to main

- src/sql/azdata.d.ts
> Fix azdata.d.ts linting issues

- extensions/sql-database-projects/package.json
bumping version after July release
> bump sql database projects version to 0.12.0

- build/azure-pipelines/publish-types/publish-types.yml
- build/azure-pipelines/publish-types/update-types.js
- build/azure-pipelines/publish-types/update-types.ts
Will be documenting the process in our docs repo...
> Fix update typings pipeline to work for us

- src/sql/workbench/services/resourceProvider/browser/firewallRuleDialog.ts
> Fixed a minor typo in comment

- src/sql/workbench/api/common/sqlExtHost.protocol.ts
> materialzied -> materialized

- src/sql/platform/clipboard/browser/clipboardService.ts
- src/sql/platform/clipboard/common/clipboardService.ts
- src/sql/platform/clipboard/electron-browser/clipboardService.ts
> clipbaord -> clipboard

- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/azurecore.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210723093313510 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210723093313510 to main

- resources/localization/LCL/es/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210723153247677 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210723153247677 to main

- resources/xlf/en/sql-migration.xlf
> [Loc] added cancelling for sql-migration xlf

- extensionsGallery-insider.json
link to build:  https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=112545&view=results
> updating sql-migration version to 0.1.4 for insiders

- extensions/arc/src/localizedConstants.ts
- extensions/arc/src/ui/components/keyValueContainer.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15750
> Add aria label to connection string pages

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/arc.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210723213527723 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210723213527723 to main

- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210724033322636 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210724033322636 to main

- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210724093242243 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210724093242243 to main

- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210724153241691 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210724153241691 to main

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210724213305528 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210724213305528 to main

- resources/localization/LCL/ru/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210725093242679 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210725093242679 to main

- resources/xlf/en/arc.xlf
> [Loc] update to arc connection string

- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210725153515997 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210725153515997 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210725213248205 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210725213248205 to main

- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210726153310307 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210726153310307 to main

- extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/extHostModelView.ts
- src/sql/workbench/api/common/sqlExtHost.api.impl.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/sql/workbench/browser/modelComponents/text.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/15776
Light
Dark
HC
> Add TextType property

- resources/localization/LCL/de/arc.xlf.lcl
- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/ko/azurecore.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/ru/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210727093315797 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210727093315797 to main

- test/automation/src/sql/notebook.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
This PR adds simple checks for code completion suggestion and colorization.
> Add intellisense checks in code cell smoke test

- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210727153242641 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210727153242641 to main

- resources/localization/LCL/es/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210727213350206 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210727213350206 to main

- resources/xlf/en/sql-database-projects.xlf
> [Loc] update to sql-database-projects

- src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
- src/vs/workbench/services/editor/browser/editorOverrideService.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/16436
(cherry picked from commit 2d8e0d648aeae043e342b3a3ca500285bfcde659)
> [Port] Fix SQL/Notebook editors opening as plaintext (#16442)

- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210728213300795 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210728213300795 to main

- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210729033312557 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210729033312557 to main

- CHANGELOG.md
Only updating the Changelog.md. No changes required in README.md
> Updating Change log.md for Hotfix v1.31.1

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
- extensions/sql-migration/src/dialog/createSqlMigrationService/createSqlMigrationServiceDialog.ts
- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
- extensions/sql-migration/src/dialog/migrationStatus/migrationStatusDialog.ts
- extensions/sql-migration/src/dialog/targetDatabaseSummary/targetDatabaseSummaryDialog.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
> Adding aria label to all the migration extension tables

- extensions/azurecore/src/account-provider/providerSettings.ts
- extensions/azurecore/src/azureResource/utils.ts
- extensions/azurecore/src/azurecore.d.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
> Adding support for different azure cloud providers in rest calls 

- extensions/sql-migration/src/telemtery.ts
- extensions/sql-migration/src/wizard/wizardController.ts
> Adding wizard step telemetry for sql migration wizard

- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210729153322213 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210729153322213 to main

- resources/xlf/en/sql-migration.xlf
> [Loc] Added change to sql-migration

- extensions/sql-migration/src/dashboard/sqlServerDashboard.ts
- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
- extensions/sql-migration/src/dialog/migrationStatus/migrationStatusDialog.ts
- extensions/sql-migration/src/models/migrationLocalStorage.ts
This PR fixes - 
* a reentrancy issue in the UI refresh logic that results in an application hang.
* a runtime error when telemetry is called with an undefined session id.
> SQL-Migration extension - fix refresh reentrancy hang

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210729213307988 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210729213307988 to main

- src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts
This PR fixes a left-out commit that was not added to this PR #16417.
> Fix email notebook render condition

- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210730033241006 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210730033241006 to main

- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
> Name added for more info link in Assessment Dialog - accessibility

- extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts
> Enable information tip buttons so they can be focused on

- extensions/sql-migration/package.json
This PR 
* updates the extension version from  0.1.4 to 0.1.5 for package release to insiders
> update extension package to v 0.1.5

- resources/xlf/en/resource-deployment.xlf
- resources/xlf/en/sql-migration.xlf
- resources/xlf/en/sql.xlf
> [Loc] update for xlfs 8/1/2021

- extensionsGallery-insider.json
Link to build:  https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=113569&view=artifacts&pathAsName=false&type=publishedArtifacts
> updating sql-migration version to 0.1.5 for insiders

- resources/xlf/en/arc.xlf
- resources/xlf/en/resource-deployment.xlf
> [Loc] small update to arc and resource-deployment

- extensions/big-data-cluster/package.json
- extensions/resource-deployment/src/services/tools/azdataTool.ts
- extensions/resource-deployment/src/services/toolsService.ts
- extensions/resource-deployment/src/test/services/toolsService.test.ts
We no longer have two "azdata tools" so we can rename this back to just azdata.
> azdataToolOld -> azdataTool

- extensions/notebook/src/test/common/stubs.ts
- extensions/notebook/src/typings/refs.d.ts
- src/sql/workbench/api/common/extHostModelViewTree.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
- src/vs/vscode.proposed.d.ts
- src/vs/workbench/api/browser/mainThreadTreeViews.ts
- src/vs/workbench/api/common/extHost.protocol.ts
- src/vs/workbench/api/common/extHostTreeViews.ts
- src/vs/workbench/api/common/shared/treeDataTransfer.ts
- src/vs/workbench/browser/parts/views/treeView.ts
- src/vs/workbench/common/views.ts
- src/vs/workbench/test/browser/api/mainThreadTreeViews.test.ts
Cherry-pick the following PRs:
https://github.com/microsoft/vscode/pull/122239
https://github.com/microsoft/vscode/pull/123542
https://github.com/microsoft/vscode/pull/128666
> Integrate drag and drop api

- i18n/ads-language-pack-de/package.json
- i18n/ads-language-pack-es/package.json
- i18n/ads-language-pack-fr/package.json
- i18n/ads-language-pack-it/package.json
- i18n/ads-language-pack-ja/package.json
- i18n/ads-language-pack-ko/package.json
- i18n/ads-language-pack-pt-BR/package.json
- i18n/ads-language-pack-ru/package.json
- i18n/ads-language-pack-zh-hans/package.json
- i18n/ads-language-pack-zh-hant/package.json
> [Loc] bumped version for langpacks

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210802213403054 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210802213403054 to main

- resources/xlf/en/resource-deployment.xlf
- resources/xlf/en/sql-migration.xlf
> [Loc] another update to resource-deployment and sql-migration

- extensionsGallery-insider.json
> Azure Monitor update short description

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210803033355205 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210803033355205 to main

- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210803093351666 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210803093351666 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210803153321448 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210803153321448 to main

- resources/xlf/en/sql-database-projects.xlf
> [Loc] update to sql-database-projects strings

- resources/localization/LCL/de/arc.xlf.lcl
- resources/localization/LCL/de/resource-deployment.xlf.lcl
- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/arc.xlf.lcl
- resources/localization/LCL/es/resource-deployment.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/fr/resource-deployment.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/it/resource-deployment.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ja/resource-deployment.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/ko/resource-deployment.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
- resources/localization/LCL/pt-BR/resource-deployment.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/ru/resource-deployment.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/resource-deployment.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/resource-deployment.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210803213435396 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210803213435396 to main

- .github/CODEOWNERS
- extensions/arc/package.json
Also updating CODEOWNERS while I'm at it
> Update arc required engine version

- extensions/integration-tests/src/onboarding/developers.ts
> Add a new developer to the list of developers for onboarding purposes

- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210804093308518 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210804093308518 to main

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210804153302598 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210804153302598 to main

- resources/xlf/en/sql.xlf
> [Loc] added in changes to sql.xlf

- extensions/azurecore/src/azureResource/providers/azuremonitor/azuremonitorTreeDataProvider.ts
- extensions/azuremonitor/README.md
Changed README.md and changed name of azuremonitorlogs container label.
> Azure Monitor Logs review feedback

- .github/workflows/ci.yml
As seen here: https://github.com/microsoft/vscode/pull/130068/files
The keytar electron unit tests were failing hitting [this error](https://github.com/atom/node-keytar/issues/76).  I created a temporary keychain so the unit tests can succeed.
> Keytar CI Build Fix

- resources/localization/LCL/es/arc.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210804213559325 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210804213559325 to main

- extensions/notebook/package.json
- extensions/notebook/yarn.lock
Bump tar npm version in notebook extension.
> Bump tar in notebook extension

- resources/xlf/en/azurecore.xlf
- resources/xlf/en/sql-migration.xlf
> [Loc] Update for sql-migration and azurecore

- extensions/data-workspace/src/services/workspaceService.ts
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseQuickpick.ts
- extensions/sql-database-projects/src/models/api/import.ts
- extensions/sql-database-projects/src/test/dialogs/createProjectFromDatabaseDialog.test.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
Note this currently doesn't have it hooked up to the OE menu contribution - there's enough changes there that I'm going to follow up with that in a separate PR.
> Add Create Project from Database quickpick

- resources/xlf/en/sql-database-projects.xlf
> [Loc] Another update for sql-database-projects xlf

- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql-migration.xlf
- resources/xlf/en/sql.xlf
> [Loc] Update for sql-database-projects, sql-migration, and sql

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210805213350533 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210805213350533 to main

- resources/localization/LCL/pt-BR/azurecore.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210806033328866 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210806033328866 to main

- resources/localization/LCL/ja/azurecore.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/azurecore.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210806153336101 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210806153336101 to main

- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/dialog/createSqlMigrationService/createSqlMigrationServiceDialog.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
- extensions/sql-migration/src/wizard/summaryPage.ts
This PR fixes. 
Summary label
DMS creation retry times
DMS dropdown resetting every time we enter the page.
> Migration extension summary and dms page fixes  

- extensions/azuremonitor/config.json
> Bumped AzureMonitor ToolsService version from 110 to 119.

- src/sql/workbench/browser/modal/optionsDialog.ts
https://msdata.visualstudio.com/Database%20Systems/_workitems/edit/1276698
fix: apply the styles first before showing the dialog.
before:
after:
> fix accessibility issue

- resources/xlf/en/sql-migration.xlf
> [Loc] update sql-migration with latest strings

- extensionsGallery-insider.json
- extensionsGallery.json
> Fixed powershell icon for Powershell extension

- extensionsGallery-insider.json
> Azure Monitor bump version for Insiders

- resources/localization/LCL/de/azurecore.xlf.lcl
- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/azurecore.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/azurecore.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210807033432354 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210807033432354 to main

- resources/xlf/en/sql-database-projects.xlf
> [Loc] update to sqldatabaseprojects

- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
> SQL Migration: Striped file support and assessment error handling

- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/models/stateMachine.ts
> Changing to resource group level api to fetch dms in Migration

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/azurecore.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210807153439301 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210807153439301 to main

- resources/xlf/en/sql-migration.xlf
> [Loc] added continue message to sql-migration

- extensions/mssql/config.json
> Updating sts to get migration service fixes

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts
- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceQuickpick.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
Select project 
Location 
Database Name & var (only if different DB)
Server name & var (only if different server)
Suppress errors
For Azure/DW
DB Name
Suppress Errors
Location
Select dacpac
Db name/var (only if different DB)
Server name/var (only if different server)
Suppress errors
> Add DB Reference quickpick dialog

- extensionsGallery-insider.json
Link to build:  
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=114692&view=artifacts&pathAsName=false&type=publishedArtifacts
> updating sql-migration version to 0.1.6 for insiders

- extensions/machine-learning/src/views/models/manageModels/currentModelsComponent.ts
Fixed the issue when loading model list UI.
> ML- Fixed a bug with loading model list

- extensions/machine-learning/src/views/models/manageModels/currentModelsComponent.ts
> Porting a commit to fix a bug with loading model list in ML Extension (#16640)

- resources/xlf/en/sql-database-projects.xlf
> [Loc] small update to sql-database-projects

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210810033442223 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210810033442223 to main

- extensions/mssql/config.json
issue: https://github.com/microsoft/azuredatastudio/issues/16639
PR for main branch: #16627
> updating sts to get migration service fixes (#16627)

- extensionsGallery.json
using this build:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=114692&view=artifacts&pathAsName=false&type=publishedArtifacts
> add sql-migration v0.1.6 extension to stable gallery

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- yarn.lock
See https://github.com/microsoft/SlickGrid.ADS/pull/1
Fixes https://github.com/microsoft/azuredatastudio/issues/15753
> Fix clickable announce for slickgrid tables

- extensions/mssql/config.json
- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
This PR fixes: 
#16626 
#16643
> Updating STS to get azure DBs getServerInfo fixes.

- src/sql/workbench/services/connection/browser/connectionManagementService.ts
For https://github.com/microsoft/azuredatastudio/issues/16556
As detailed in there - I wasn't able to find a fix that wasn't risky/incomplete so in the meantime adding some more logging to help with further efforts in this area.
> Add more connection logging

- package.json
Bump distro to bring in latest webview fix
> Bump distro to bring in webview fix

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/azurecore.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210811033418256 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210811033418256 to main

- resources/xlf/en/arc.xlf
- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql-migration.xlf
- resources/xlf/en/sql.xlf
> [Loc] Update for English XLFs 8-10-2021

- extensionsGallery-insider.json
Bumped Azure Monitor Logs version to 0.1.2 in insiders
> Azure Monitor Logs insiders version bump to 0.1.2

- extensions/mssql/config.json
- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
Fixes #16626, #16643, #16549
Ported from main branch PR: #16658
> Updating mssql to get azure dashboard fixes: (#16658)

- extensions/admin-tool-ext-win/package.json
Reverting back to smaller version bump until we have a release that warrants a minor version bump.
> Update admin-tool-ext-win version

- extensionsGallery-insider.json
- extensionsGallery.json
August Langpack update to the version gallery.
The generated langpacks can be found in this ad-hoc build: 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=114485&view=results
> Bumped extensionsGallery version for langpacks for code complete

- extensionsGallery-insider.json
@smartguest Make sure these are updated for future updates
> Update missed langpack properties in gallery

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/tools/netcoreTool.ts
Issue: https://github.com/microsoft/azuredatastudio/issues/16676
PR for main: https://github.com/microsoft/azuredatastudio/pull/16694
> Porting fix to display correct error when no or old .NET installation is found

- extensions/azuremonitor/package.json
> Bumped AzureMonitor version to 0.1.3

- extensionsGallery-insider.json
> Azure Monitor Logs extension to 0.1.3

- extensionsGallery.json
> Add AzureMonitor to RC Gallery

- extensionsGallery-insider.json
Build with VSIX: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=115233&view=artifacts&pathAsName=false&type=publishedArtifacts
> Update sql database projects to 0.12.0 in insiders gallery

- extensionsGallery.json
This PR will add the August langpacks to the stable branch
Branch to get the langpacks from: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=114847&view=results
> Added August langpacks to stable gallery

- extensionsGallery.json
VSIX from the release build: https://mssqltools.visualstudio.com/_apis/resources/Containers/3341137/drop?itemPath=drop%2Fextensions%2Fmachine-learning-0.11.0.vsix
> Update extensionsGallery.json for ML 0.11.0

- src/vs/workbench/contrib/welcome/page/browser/welcomePage.contribution.ts
Port fix for https://github.com/microsoft/azuredatastudio/issues/16628 to release/1.32.  PR to main is https://github.com/microsoft/azuredatastudio/pull/16734.
> Use preview welcome page if enabled (#16734)

- resources/xlf/en/sql-migration.xlf
> [Loc] Added all fields required message for sql-migration

- extensions/azuremonitor/package.json
> Bumped AzureMonitor version to 0.1.4

- extensionsGallery.json
Build with VSIX: same as https://github.com/microsoft/azuredatastudio/pull/16719
> Update sql database projects to 0.12.0 in RC

- src/sql/base/browser/ui/table/plugins/autoSizeColumns.plugin.ts
This PR improves the performance of the auto size columns plugin. Most of the logic is the same as before, I only changed the order of things to prevent layout thrashing (https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing).
Ex. To get the width of each header text, previously we were 
1. Adding a header element onto the DOM
2. Reading the width
And repeating this for each column. Layout would be called each time we read the width since the DOM has changed.
Now we are adding all the header elements onto the DOM, then reading all the widths. This way layout only needs to be called once. 
Note: Each layout call takes the same amount of time since the entire notebook is scoped into the layout. For a 2mb notebook, each layout …
> Refactor auto size columns plugin

- src/sql/azdata.d.ts
- src/sql/workbench/browser/modelComponents/viewBase.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/16691
Fixes https://github.com/microsoft/azuredatastudio/issues/16751
(also including azdata API fix to be included in typings update)
> [Port] Fix modelview container removal issue (#16753)

- extensions/sql-migration/README.md
- extensions/sql-migration/package.json
issue: #16702 
PR for main branch: #16729
> [Port] update readme public preview (#16729)

- extensionsGallery-insider.json
> Insiders - Azure Monitor Logs extension version bump to 0.1.4

- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialogModel.ts
- extensions/sql-migration/src/models/migrationLocalStorage.ts
issue: #16704 
PR for main branch: #16696
> [Port] improve migration context loading (#16696)

- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
issue: #16703 
PR for main branch: #16701
> [Port] filter assessment results by MigationTargetType (#16701)

- extensions/sql-migration/src/api/azure.ts
issue: #16728 
PR for main branch: #16731
> [Port] Listing filtered locations for migration service public preview. 

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210813153410216 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210813153410216 to main

- resources/xlf/en/data-workspace.xlf
- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql-migration.xlf
> [Loc] updates to xlfs in sql-migration, database-projects, data-workspace

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/providerSettings.ts
- extensions/azurecore/src/azurecore.d.ts
- extensions/kusto/package.json
- src/sql/azdata.proposed.d.ts
- src/sql/platform/accounts/common/interfaces.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
Added a specific resource for getting AAD token for Kusto.
> Fix for getting auth token for Kusto resource

- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210815033330895 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210815033330895 to main
