microsoft/azuredatastudio

- src/sql/base/browser/ui/inputBox/inputBox.ts
- src/sql/workbench/browser/modal/dialogHelper.ts
- src/sql/workbench/services/connection/browser/connectionWidget.ts
This PR fixes #16621
1. add required indicator for server and user name
2. previously for integrated auth mode, we will show user name/password as disabled, I am changing the code to hide the fields to be consistent with the behavior of other fields.
3. code refactoring
> add required indicator

- .config/CredScanSuppressions.json
- extensions/cms/src/cmsUtils.ts
- src/sql/platform/connection/test/common/connectionStore.test.ts
Scanner was recently updated and filed a few new issues, suppressing them since none are actually valid problems
> Suppress scan hits

- resources/xlf/en/azurecore.xlf
- resources/xlf/en/sql-migration.xlf
> [Loc] added new strings for azurecore and sql-migration

- extensions/notebook/src/test/book/book.test.ts
This test has failed twice in the last two weeks. I'll be investigating the cause during test Mondays.
> Mark test as unstable

- src/sql/workbench/browser/modal/modal.ts
- src/sql/workbench/services/dialog/browser/wizardModal.ts
This PR fixes #16687
this features was documented but never actually implemented.
> handle page custom buttons for wizard

- extensions/mssql/src/main.ts
- extensions/mssql/src/mssql.d.ts
- extensions/mssql/src/mssqlApiFactory.ts
- extensions/mssql/src/sqlToolsServer.ts
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/tools/buildHelper.ts
- extensions/sql-database-projects/src/typings/vscode-mssql.d.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/16770
Get the install location for STS from the extensions so we don't have to do the logic ourselves
> Get tools service install location from extensions

- src/sql/workbench/contrib/notebook/test/browser/notebookMarkdown.test.ts
Add a few more marked.js tests
Also updated the test names to be able to correspond them to the source nb/cell
> Add more marked.js tests

- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql.xlf
> [Loc] added changes to sql-database-projects and sql

- extensionsGallery-insider.json
Build: 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=115834&view=artifacts&pathAsName=false&type=publishedArtifacts
> Updating import insiders to 1.4.0

- extensions/azurecore/src/azureDataGridProvider.ts
- extensions/azurecore/src/azureResource/commands.ts
- extensions/azurecore/src/azureResource/interfaces.ts
- extensions/azurecore/src/azureResource/services/subscriptionService.ts
- extensions/azurecore/src/azureResource/tree/accountTreeNode.ts
- extensions/azurecore/src/azureResource/tree/flatAccountTreeNode.ts
- extensions/azurecore/src/azureResource/tree/flatTreeProvider.ts
- extensions/azurecore/src/azureResource/utils.ts
- extensions/azurecore/src/test/azureResource/tree/accountTreeNode.test.ts
Remove getAllSubscriptions and consolidate logic into a single function.
> Consolidate getSubscriptions

- extensions/sql-migration/package.json
- extensions/sql-migration/src/constants/strings.ts
This PR incorrect string in create dms dialog and bumps extension version to 0.1.8
current bug:
update:
> bump sql migration ext to 0.1.8 with string fix

- extensions/sql-migration/package.json
- extensions/sql-migration/src/constants/strings.ts
This PR incorrect string in create dms dialog and bumps extension version to 0.1.8
PR for main branch: https://github.com/microsoft/azuredatastudio/pull/16808
current bug:
update:
> update create dms description string

- src/sql/workbench/services/serverGroup/browser/serverGroupDialog.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/13777
> fix arrow keys not working in server group dialog

- resources/xlf/en/azurecore.xlf
- resources/xlf/en/sql-migration.xlf
> [Loc] Update to azurecore and sql-migration

- extensions/dacpac/package.json
- extensions/dacpac/package.nls.json
- resources/xlf/en/dacpac.xlf
Added localization for the title and category in the package.json of dacpac.
This is to start the fix for: #6326
> Added localization for title and category for dacpac

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dashboard/sqlServerDashboard.ts
- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
This PR updates sql migration extension strings based on content review, uniforms format to only capitalize first word, adds periods to end of statements.
> Update sql migration extension strings

- extensions/azurecore/src/azureResource/interfaces.ts
- extensions/azurecore/src/azureResource/services/subscriptionService.ts
- extensions/azurecore/src/azureResource/utils.ts
- extensions/azurecore/src/extension.ts
Not sure how I missed this...but the dangers of any. The account was any in the code and so it didn't flag the missing id property as an issue.
> Fix error when getting subscriptions for specific tenants

- extensionsGallery-insider.json
Build:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=116260&view=results
> Updating migration insiders to 0.1.8

- extensions/sql-database-projects/package.json
bumping version after August release
> bump sql database projects version to 0.13.0

- resources/xlf/en/sql-migration.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to sql-migration and sql.xlf

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/dialogs/addSqlBindingQuickpick.ts
- extensions/sql-database-projects/src/typings/vscode-mssql.d.ts
Hooking up the add sql binding quick pick(https://github.com/microsoft/azuredatastudio/pull/16553) with the apis exposed in https://github.com/microsoft/vscode-mssql/pull/17036 and https://github.com/microsoft/vscode-mssql/pull/17043.
> hook up add sql binding

- extensions/azurecore/src/account-provider/providerSettings.ts
Fixes the Kusto resource uri for generating auth token
Also, fixes the KQL-M support in Kusto extension
> Fix kusto resource uri for auth token

- resources/xlf/en/sql.xlf
> [Loc] Remove optimized table

- resources/xlf/en/sql-migration.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to sql and sql-migration

- extensions/sql-migration/README.md
> Update public preview readme for sql migration extension

- extensions/notebook/src/book/bookModel.ts
- extensions/notebook/src/book/bookPinManager.ts
- extensions/notebook/src/book/bookTocManager.ts
- extensions/notebook/src/book/bookTreeView.ts
- extensions/notebook/src/book/githubRemoteBook.ts
- extensions/notebook/src/common/notebookUtils.ts
- extensions/notebook/src/extension.ts
- extensions/notebook/src/jupyter/jupyterController.ts
- extensions/notebook/src/jupyter/jupyterNotebookManager.ts
- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
- extensions/notebook/src/jupyter/jupyterServerManager.ts
- extensions/notebook/src/prompts/adapter.ts
- extensions/notebook/src/protocol/notebookUriHandler.ts
- extensions/notebook/src/test/common.ts
First set of fixes here. These are all just ones that are ignored - usually because they're calling into VS Code stuff and aren't anything we can do much if they fail (like showing error toast)
> Fix some unhandled promise lint errors

- extensions/notebook/src/common/localizedConstants.ts
- extensions/notebook/src/dialog/addFileDialog.ts
- extensions/notebook/src/test/book/addFile.test.ts
These tests bring the code coverage for this file up to 84%.
> Add unit tests for Book AddFile dialog

- extensions/data-workspace/.vscode/launch.json
- extensions/data-workspace/src/dialogs/newProjectQuickpick.ts
- extensions/sql-database-projects/.vscode/launch.json
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
New Project : 
- Browse icon
- Also added the default save location path as the first option shown (similar to create project from DB)
Publish DB : 
Also added launch.json files for more easily debugging the extensions
> Add icons for some quickpick items

- extensions/azuremonitor/config.json
- extensions/azuremonitor/package.json
Bumped version of AzureMonitor toolservice to 125. Bumped version to 0.1.5
> Azure Monitor Logs version to 0.1.5

- resources/xlf/en/Microsoft.sqlservernotebook.xlf
- resources/xlf/en/admin-tool-ext-win.xlf
- resources/xlf/en/agent.xlf
- resources/xlf/en/arc.xlf
- resources/xlf/en/asde-deployment.xlf
- resources/xlf/en/azurecore.xlf
- resources/xlf/en/azurehybridtoolkit.xlf
- resources/xlf/en/big-data-cluster.xlf
- resources/xlf/en/cms.xlf
- resources/xlf/en/dacpac.xlf
- resources/xlf/en/data-workspace.xlf
- resources/xlf/en/import.xlf
- resources/xlf/en/kusto.xlf
- resources/xlf/en/machine-learning.xlf
- resources/xlf/en/mssql.xlf
- resources/xlf/en/notebook.xlf
- resources/xlf/en/profiler.xlf
- resources/xlf/en/query-history.xlf
- resources/xlf/en/resource-deployment.xlf
- resources/xlf/en/schema-compare.xlf
- resources/xlf/en/server-report.xlf
- resources/xlf/en/sql-assessment.xlf
- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql-migration.xlf
- resources/xlf/en/sql.xlf
- resources/xlf/en/xml-language-features.xlf
This PR adds in updated English XLFs in anticipation of the September release and new vscode merge, this may take a couple of days to fully translate.
> [Loc] Update to English XLFs for September's Langpack

- resources/xlf/en/cms.xlf
- resources/xlf/en/kusto.xlf
- resources/xlf/en/mssql.xlf
- resources/xlf/en/profiler.xlf
- resources/xlf/en/sql.xlf
> [Loc] added additional localization

- build/gulpfile.vscode.js
- resources/xlf/LocProject.json
> [Loc] removed azdata.xlf as its no longer relevant

- resources/xlf/LocProject.json
> [Loc] added server report to locProject

- extensions/sql-database-projects/.eslintrc.json
- extensions/sql-database-projects/src/controllers/mainController.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts
- extensions/sql-database-projects/src/dialogs/addSqlBindingQuickpick.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/extension.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/models/publishProfile/publishProfile.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
- extensions/sql-database-projects/src/tools/netcoreTool.ts
- extensions/sql-database-projects/src/tools/packageHelper.ts
Didn't find any issues here, so everything here is just making the linter happy for the most part (I did add awaits for some extra stuff like updating properties which isn't strictly necessary, but in general I wouldn't consider that a bad thing to do at this point in time)
> Add no-floating-promises rule to sql-database-projects extension

- extensionsGallery.json
Build: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=116260&view=artifacts&pathAsName=false&type=publishedArtifacts
Inline Migration service will be in public preview on 9/1/21. We would like to merge this PR and publish the changes on the morning of 9/1.
> Add sql-migration extension V0.1.8 to stable extension gallery

- extensions/data-workspace/.eslintrc.json
- extensions/data-workspace/src/common/dataWorkspaceExtension.ts
- extensions/data-workspace/src/common/workspaceTreeDataProvider.ts
- extensions/data-workspace/src/dialogs/newProjectDialog.ts
- extensions/data-workspace/src/dialogs/openExistingDialog.ts
- extensions/data-workspace/src/main.ts
- extensions/data-workspace/src/services/workspaceService.ts
- extensions/data-workspace/src/test/workspaceTreeDataProvider.test.ts
> Enable no-floating-promises for data-workspace

- lgtm.yml
Missed this one in earlier cleanup
> Remove LGTM yml

- extensions/azurecore/.eslintrc.json
- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/azureAccountProvider.ts
- extensions/azurecore/src/account-provider/azureAccountProviderService.ts
- extensions/azurecore/src/azureResource/commands.ts
- extensions/azurecore/src/azureResource/interfaces.ts
- extensions/azurecore/src/azureResource/services/cacheService.ts
- extensions/azurecore/src/azureResource/services/subscriptionFilterService.ts
- extensions/azurecore/src/azureResource/services/subscriptionService.ts
- extensions/azurecore/src/azureResource/services/terminalService.ts
- extensions/azurecore/src/azureResource/tree/accountTreeNode.ts
- extensions/azurecore/src/azureResource/tree/baseTreeNodes.ts
- extensions/azurecore/src/azureResource/tree/connectionDialogTreeProvider.ts
- extensions/azurecore/src/azureResource/tree/flatAccountTreeNode.ts
- extensions/azurecore/src/azureResource/tree/flatTreeProvider.ts
- extensions/azurecore/src/extension.ts
- extensions/azurecore/src/test/account-provider/utils/simpleWebServer.test.ts
- extensions/azurecore/src/test/azureResource/tree/accountTreeNode.test.ts
- package.json
Nothing really of note fixed here, just a few tests that weren't awaiting properly.
> Enable no-floating-promises for azurecore

- extensions/mssql/.eslintrc.json
- extensions/mssql/src/contextProvider.ts
- extensions/mssql/src/credentialstore/credentialstore.ts
- extensions/mssql/src/dashboard/bookWidget.ts
- extensions/mssql/src/dashboard/serviceEndpoints.ts
- extensions/mssql/src/features.ts
- extensions/mssql/src/hdfs/hdfsModel.ts
- extensions/mssql/src/hdfs/ui/hdfsManageAccessDialog.ts
- extensions/mssql/src/main.ts
- extensions/mssql/src/objectExplorerNodeProvider/command.ts
- extensions/mssql/src/objectExplorerNodeProvider/fileSources.ts
- extensions/mssql/src/objectExplorerNodeProvider/hdfsCommands.ts
- extensions/mssql/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts
- extensions/mssql/src/prompts/adapter.ts
- extensions/mssql/src/resourceProvider/resourceProvider.ts
- extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts
- extensions/mssql/src/sparkFeature/dialog/sparkJobSubmission/sparkConfigurationTab.ts
- extensions/mssql/src/sparkFeature/dialog/sparkJobSubmission/sparkJobSubmissionDialog.ts
- extensions/mssql/src/sparkFeature/historyTask.ts
- extensions/mssql/src/sqlToolsServer.ts
- extensions/mssql/src/telemetry.ts
- extensions/mssql/src/utils.ts
No real issues found for this one either
> Enable no-floating-promises for mssql extension

- src/sql/workbench/contrib/extensions/browser/scenarioRecommendations.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/14274
> Respect ignore recommendation setting 

- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql-migration.xlf
- resources/xlf/en/sql.xlf
Reverts microsoft/azuredatastudio#16993 Need to include constants.ts
> Revert "[Loc] update to sql-database and migration and core sql files"

- extensions/sql-migration/package.json
> tab fix for sql-migration after compile

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210905153429857 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210905153429857 to main

- extensions/azuremonitor/package.json
- extensions/cms/package.json
- extensions/dacpac/package.json
- extensions/kusto/package.json
- extensions/profiler/package.json
This bumps the versions of the extensions so that localization and other small bug fixes can be added to a gallery update that will be created later.
> vBump for now localized extensions to enable localization

- src/sql/workbench/contrib/query/browser/queryActions.ts
This PR simplifies duplicated `isConnected` checks in `RunQueryAction` so we can reduce to one `refreshAzureAccountTokenIfNecessary` call for both `run` and `runCurrent`.
This is a follow-up to the AAD token expiration handling PR #16936
> Simplify connection checks in RunQueryAction

- test/automation/src/sql/configurePythonDialog.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/17017
> Smoke test: increase python installation timeout to 5 min

- resources/xlf/en/sql.xlf
> [Loc] added defaultAuthenticationType strings

- extensions/sql-migration/src/dialog/createSqlMigrationService/createSqlMigrationServiceDialog.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
This PR 
updates styling for pre-selected values in the extension
Before
After
> Remove the gray background/gray text for pre-selected values

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210910033604392 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210910033604392 to main

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210910153408349 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210910153408349 to main

- resources/xlf/en/sql-migration.xlf
> [Loc] added Add Account for sql migration strings

- extensions/sql-migration/src/dashboard/sqlServerDashboard.ts
This PR updates the card styling on extension dashboard
> Update card styling on extension dashboard

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210912033346111 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210912033346111 to main

- resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210911153312158 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210911153312158 to main

- extensions/notebook/src/book/bookTreeView.ts
Modify table of contents and move notebooks/files only if the target is a section or a book.
> Check that the target is a section or a book

- resources/xlf/en/sql.xlf
> [Loc] Added defaultDropdownErrorMessage for localization

- product.json
This PR adds sql-migration extension to the list of recommended extensions.
> Add sql-migration extension to recommendation list

- extensions/notebook/package.json
- extensions/notebook/package.nls.json
- extensions/notebook/src/book/bookTocManager.ts
- extensions/notebook/src/book/bookTreeItem.ts
- extensions/notebook/src/book/bookTreeView.ts
- extensions/notebook/src/common/localizedConstants.ts
- extensions/notebook/src/dialog/addTocEntryDialog.ts
- extensions/notebook/src/extension.ts
- extensions/notebook/src/test/book/addTocEntry.test.ts
- extensions/notebook/src/test/book/bookTocManager.test.ts
Support creating new sections from UI
https://user-images.githubusercontent.com/34872381/133197913-3c4148ec-0c17-48cb-a658-cc57eed7587f.mov
> Book Editing: Support adding new sections to a book

- resources/localization/LCL/de/server-report.xlf.lcl
- resources/localization/LCL/es/server-report.xlf.lcl
- resources/localization/LCL/fr/server-report.xlf.lcl
- resources/localization/LCL/it/server-report.xlf.lcl
- resources/localization/LCL/ja/server-report.xlf.lcl
- resources/localization/LCL/ko/server-report.xlf.lcl
- resources/localization/LCL/pt-BR/server-report.xlf.lcl
- resources/localization/LCL/ru/server-report.xlf.lcl
- resources/localization/LCL/zh-Hans/server-report.xlf.lcl
- resources/localization/LCL/zh-Hant/server-report.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210914001103799 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210914001103799 to main

- extensions/machine-learning/src/views/externalLanguages/addEditLanguageTab.ts
- extensions/machine-learning/src/views/externalLanguages/languageContentView.ts
- extensions/notebook/src/dialog/managePackages/addNewPackageTab.ts
- extensions/resource-deployment/src/ui/modelViewUtils.ts
- extensions/sql-migration/src/dashboard/sqlServerDashboard.ts
- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/extHostModelView.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/sql/workbench/browser/modelComponents/text.component.ts
> Adding lists support in text component

- resources/localization/LCL/de/server-report.xlf.lcl
- resources/localization/LCL/es/server-report.xlf.lcl
- resources/localization/LCL/fr/server-report.xlf.lcl
- resources/localization/LCL/it/server-report.xlf.lcl
- resources/localization/LCL/ja/server-report.xlf.lcl
- resources/localization/LCL/ko/server-report.xlf.lcl
- resources/localization/LCL/pt-BR/server-report.xlf.lcl
- resources/localization/LCL/ru/server-report.xlf.lcl
- resources/localization/LCL/zh-Hans/server-report.xlf.lcl
- resources/localization/LCL/zh-Hant/server-report.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210914001142130 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210914001142130 to main

- resources/localization/LCL/de/server-report.xlf.lcl
- resources/localization/LCL/es/server-report.xlf.lcl
- resources/localization/LCL/fr/server-report.xlf.lcl
- resources/localization/LCL/it/server-report.xlf.lcl
- resources/localization/LCL/ja/server-report.xlf.lcl
- resources/localization/LCL/ko/server-report.xlf.lcl
- resources/localization/LCL/pt-BR/server-report.xlf.lcl
- resources/localization/LCL/ru/server-report.xlf.lcl
- resources/localization/LCL/zh-Hans/server-report.xlf.lcl
- resources/localization/LCL/zh-Hant/server-report.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210914001225466 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210914001225466 to main

- resources/localization/LCL/de/server-report.xlf.lcl
- resources/localization/LCL/es/server-report.xlf.lcl
- resources/localization/LCL/fr/server-report.xlf.lcl
- resources/localization/LCL/it/server-report.xlf.lcl
- resources/localization/LCL/ja/server-report.xlf.lcl
- resources/localization/LCL/ko/server-report.xlf.lcl
- resources/localization/LCL/pt-BR/server-report.xlf.lcl
- resources/localization/LCL/ru/server-report.xlf.lcl
- resources/localization/LCL/zh-Hans/server-report.xlf.lcl
- resources/localization/LCL/zh-Hant/server-report.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210914001320507 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210914001320507 to main

- resources/localization/LCL/de/server-report.xlf.lcl
- resources/localization/LCL/es/server-report.xlf.lcl
- resources/localization/LCL/fr/server-report.xlf.lcl
- resources/localization/LCL/it/server-report.xlf.lcl
- resources/localization/LCL/ja/server-report.xlf.lcl
- resources/localization/LCL/ko/server-report.xlf.lcl
- resources/localization/LCL/pt-BR/server-report.xlf.lcl
- resources/localization/LCL/ru/server-report.xlf.lcl
- resources/localization/LCL/zh-Hans/server-report.xlf.lcl
- resources/localization/LCL/zh-Hant/server-report.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210914001439754 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210914001439754 to main

- resources/localization/LCL/de/server-report.xlf.lcl
- resources/localization/LCL/es/server-report.xlf.lcl
- resources/localization/LCL/fr/server-report.xlf.lcl
- resources/localization/LCL/it/server-report.xlf.lcl
- resources/localization/LCL/ja/server-report.xlf.lcl
- resources/localization/LCL/ko/server-report.xlf.lcl
- resources/localization/LCL/pt-BR/server-report.xlf.lcl
- resources/localization/LCL/ru/server-report.xlf.lcl
- resources/localization/LCL/zh-Hans/server-report.xlf.lcl
- resources/localization/LCL/zh-Hant/server-report.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210914001647413 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210914001647413 to main

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210915033531653 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210915033531653 to main

- extensions/sql-database-projects/src/test/dialogs/addSqlBindingQuickpick.test.ts
- extensions/sql-database-projects/src/test/packageHelper.test.ts
- extensions/sql-database-projects/src/test/testContext.ts
This adds a few tests for the add SQL binding quick pick and package helper that have recently been added.
> Adding a few tests for Add SQL binding

- resources/localization/LCL/de/notebook.xlf.lcl
- resources/localization/LCL/de/server-report.xlf.lcl
- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/notebook.xlf.lcl
- resources/localization/LCL/es/server-report.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/notebook.xlf.lcl
- resources/localization/LCL/ko/server-report.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/notebook.xlf.lcl
- resources/localization/LCL/pt-BR/server-report.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/notebook.xlf.lcl
- resources/localization/LCL/zh-Hant/server-report.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210916033420869 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210916033420869 to main

- resources/localization/LCL/ja/notebook.xlf.lcl
- resources/localization/LCL/ja/server-report.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210916153335914 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210916153335914 to main

- resources/localization/LCL/fr/notebook.xlf.lcl
- resources/localization/LCL/fr/server-report.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/notebook.xlf.lcl
- resources/localization/LCL/it/server-report.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/notebook.xlf.lcl
- resources/localization/LCL/ru/server-report.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/notebook.xlf.lcl
- resources/localization/LCL/zh-Hans/server-report.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210917092523643 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210917092523643 to main

- resources/xlf/en/sql-database-projects.xlf
> added sql database projects strings

- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR fixes #17101
This may have been created by Notebook Views
> Set kernelAlias in startSession when isValidConnection is truthy

- resources/xlf/en/sql-database-projects.xlf
> [Loc] Small change to generatingProjectFailed

- src/sql/workbench/contrib/query/browser/query.contribution.ts
> Change keybindings for copying query with Results

- resources/xlf/en/arc.xlf
- resources/xlf/en/sql-database-projects.xlf
> [Loc] Update for arc and sql-database-projects

- extensions/machine-learning/package.json
> ML extension vbump

- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
Fixed a bug with canceling publish after the first quickpick option.
> SQl Proj - Fixed a bug with canceling publish

- resources/localization/LCL/de/kusto.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210927153707349 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210927153707349 to main

- resources/localization/LCL/ko/kusto.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210928033458453 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210928033458453 to main

- build/actions/package.json
- build/actions/yarn.lock
- extensions/azurecore/package.json
- extensions/azurecore/yarn.lock
- extensions/resource-deployment/package.json
- extensions/resource-deployment/yarn.lock
Update dependency versions per Component Governance guidance.
> Bump axios to 0.21.4

- extensions/kusto/config.json
- extensions/kusto/package.json
Bumped Kusto toolsservice version to 125 and bumped version to 0.5.6
> Kusto version bump to 0.5.6

- extensions/azuremonitor/config.json
- extensions/azuremonitor/package.json
> AzureMonitor bump extension 0.1.7

- extensionsGallery-insider.json
- extensionsGallery.json
Link to the build 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=120874&view=results
> Updating import extension to include derived column changes 

- extensions/data-workspace/src/common/constants.ts
> update data workspace restart ADS to open workspace message

- resources/localization/LCL/de/arc.xlf.lcl
- resources/localization/LCL/de/import.xlf.lcl
- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/ru/import.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/import.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210929153522222 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210929153522222 to main

- resources/xlf/en/data-workspace.xlf
> [Loc] Add a small change to dataworkspace

- extensions/mssql/config.json
This PR fixes #16438 and fixes #16617
It is also part of #17187 but there may be more features needed to be implemented.
>  bump to sqltoolsservice version

- resources/localization/LCL/es/arc.xlf.lcl
- resources/localization/LCL/es/import.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/fr/import.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210930033626162 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210930033626162 to main

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/assessmentResults/assessmentResultsDialog.ts
- extensions/sql-migration/src/wizard/wizardController.ts
This PR updates action button texts
> Update action buttons texts

- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/it/import.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/import.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210930153529685 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20210930153529685 to main

- resources/xlf/en/notebook.xlf
> [Loc] small update to notebook xlf

- resources/xlf/en/sql.xlf
> [Loc] Small addition to sql.xlf

- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211004153456112 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211004153456112 to main

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/data-workspace.xlf.lcl
- resources/localization/LCL/es/notebook.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/data-workspace.xlf.lcl
- resources/localization/LCL/it/notebook.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/data-workspace.xlf.lcl
- resources/localization/LCL/ko/notebook.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/notebook.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211004033534231 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211004033534231 to main

- resources/xlf/en/arc.xlf
> [Loc] update to arc strings

- src/sql/workbench/services/connection/browser/connectionDialogWidget.ts
> fix tab header missing issue in connection dialog

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211005153436732 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211005153436732 to main

- extensions/sql-database-projects/yarn.lock
> Small update to Yarn.lock (automatically generated during compilation)

- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211006033521648 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211006033521648 to main

- resources/xlf/en/notebook.xlf
- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql.xlf
> [Loc] additions to notebook, sql-database-projects and sql.xlf

- resources/localization/LCL/es/notebook.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211029153423051 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211029153423051 to main

- extensions/azuremonitor/package.json
- src/sql/platform/connection/common/providerConnectionInfo.ts
- src/sql/workbench/common/editor/query/queryEditorInput.ts
- src/sql/workbench/contrib/query/browser/queryActions.ts
- src/sql/workbench/contrib/query/browser/queryEditor.ts
check whether database name option is supported for the following scenarios
1. query editor title
2. databases dropdown in query editor toolbar
3. object explorer connection node label
**BEFORE**
Oracle: 
SQL Server:
Object Explorer:
**AFTER**
Oracle:
SQL Server
Object Explorer:
> optional database name option

- resources/xlf/en/arc.xlf
> [Loc] update to arc xlf

- extensions/admin-pack/package.json
- extensions/admin-tool-ext-win/package.json
- extensions/agent/package.json
- extensions/arc/package.json
- extensions/asde-deployment/package.json
- extensions/azcli/package.json
- extensions/azurecore/package.json
- extensions/azurehybridtoolkit/package.json
- extensions/azuremonitor/package.json
- extensions/bat/package.json
- extensions/big-data-cluster/package.json
- extensions/cms/package.json
- extensions/dacpac/package.json
- extensions/data-workspace/package.json
- extensions/import/package.json
- extensions/kusto/package.json
- extensions/machine-learning/package.json
- extensions/mssql/package.json
- extensions/notebook/package.json
- extensions/profiler/package.json
- extensions/query-history/package.json
- extensions/resource-deployment/package.json
- extensions/schema-compare/package.json
- extensions/server-report/package.json
- extensions/sql-assessment/package.json
- extensions/sql-database-projects/package.json
- extensions/sql-migration/package.json
This PR fixes #https://github.com/microsoft/azuredatastudio/issues/17535.  The built-in extensions haven't been updated to supported restricted mode.  This change will allow all the built-in extensions to work in this mode.
> Add untrusted workspace supported flags

- extensions/notebook/src/dialog/managePackages/installedPackagesTab.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/16088
Before:
After:
> Remove unnecessary scrollbars in Manage Packages Dialog

- resources/xlf/en/sql.xlf
> [Loc] Update to table designer

- src/sql/base/common/locConstants.ts
- src/vs/workbench/contrib/workspace/browser/workspace.contribution.ts
> VS Code -> ADS setting descriptions

- resources/xlf/en/sql.xlf
> [Loc] update to workspace trust xlf

- extensions/arc/package.json
- extensions/azcli/package.json
Bumping the versions before arc and azcli extension updates.
> Bumping version for arc and azcli extensions.

- resources/xlf/en/sql.xlf
> [Loc] added xlf strings for designer and tabledesigner

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/models/project.ts
This adds some try catches around the different parts of parsing the sqlproj so that there's a better error message if there's an error reading a sqlproj. Hopefully will help for troubleshooting cases like https://github.com/microsoft/azuredatastudio/issues/16121.
> show better error messages when parsing sqlproj

- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/models/deploy/deployService.ts
- extensions/sql-database-projects/src/test/deploy/deployService.test.ts
- extensions/sql-database-projects/src/test/netCoreTool.test.ts
- extensions/sql-database-projects/src/tools/autorestHelper.ts
- extensions/sql-database-projects/src/tools/netcoreTool.ts
- extensions/sql-database-projects/src/tools/shellExecutionHelper.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/17088 by adapting `deployService` to use `shellExecutionHelper`
> Dedupe shell command execution logic

- extensionsGallery-insider.json
Updated the lastUpdated fields and the azcli and arc version numbers to the latest (arc 0.9.7 and azcli 0.1.1).
> Updating the arc and azcli extensions for Arc release.

- extensions/arc/package.json
- extensions/arc/package.nls.json
- extensions/arc/src/common/utils.ts
- extensions/arc/src/localizedConstants.ts
- extensions/arc/src/models/miaaModel.ts
- extensions/arc/src/ui/dashboards/miaa/miaaBackupsPage.ts
- extensions/arc/src/ui/dialogs/configureRPOSqlDialog.ts
- extensions/arc/src/ui/dialogs/restoreSqlDialog.ts
- extensions/azcli/package.json
- extensions/azcli/src/api.ts
- extensions/azcli/src/az.ts
- extensions/azcli/src/typings/az-ext.d.ts
Port over one change from main (#17506) to be released into stable
> [Port] Link Database Earliest and Latest Point in time with DryRun (#17506)

- extensions/mssql/package.json
- src/sql/workbench/contrib/preferences/browser/sqlSettingsLayout.ts
- src/sql/workbench/contrib/tableDesigner/browser/tableDesigner.contribution.ts
> feature flag for table designer

- resources/xlf/en/sql.xlf
> [Loc] update to table designer XLF

- build/azure-pipelines/linux/sql-product-build-linux.yml
- build/azure-pipelines/web/sql-product-build-web.yml
They added support for .NET 3.1 & 5.0 in October
> Update dotnet version used by codesign

- resources/xlf/en/sql.xlf
> [Loc] change location  of designer strings

- extensions/mssql/config.json
> STS VBump with v147

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/baselines/baselines.ts
- extensions/sql-database-projects/src/test/baselines/openNewStyleSqlProjectWithBuildRemoveBaseline.xml
- extensions/sql-database-projects/src/test/project.test.ts
This adds support for <Build Remove="..."> in the new msbuild sdk style sql projects.
> add support for Build Remove

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211110043612198 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211110043612198 to main

- .github/workflows/update-galleries-list-reminder.yml
Will be updating the update instructions at the link as a follow up to include instructions for new extensions being added.
> Add extension gallery update reminder action

- .github/workflows/update-galleries-list-reminder.yml
Porting to the correct branch...
> Add update galleries list reminder action

- extensions/sql-database-projects/src/dialogs/addSqlBindingQuickpick.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/17570.
> Show connection string example for add sql binding quickpick

- extensions/mssql/config.json
the main thing i want to bring in is the table designer changes. other folks please confirm your changes are good to go.
changes:
> use latest STS

- extensions/mssql/config.json
Updating to take Tools Service changes to Schema Compare service that allows targeting projects for updating.
Only other included changes are updated localization strings
> Bump tools service to 154

- build/package.json
- build/yarn.lock
- extensions/arc/package.json
- extensions/arc/yarn.lock
- extensions/azcli/package.json
- extensions/azcli/yarn.lock
- extensions/big-data-cluster/package.json
- extensions/big-data-cluster/yarn.lock
- extensions/cms/package.json
- extensions/cms/yarn.lock
- extensions/integration-tests/package.json
- extensions/integration-tests/yarn.lock
- extensions/machine-learning/package.json
- extensions/machine-learning/yarn.lock
- extensions/mssql/package.json
- extensions/mssql/yarn.lock
- extensions/notebook/package.json
- extensions/notebook/yarn.lock
- package.json
- yarn.lock
I have checked all the [commits](https://github.com/kriszyp/json-schema/commits/master) since 0.2.3 release [commit](https://github.com/kriszyp/json-schema/commit/07ae2c618b5f581dbc108e065f4f95dcf0a1d85f) of this package, and none of them have behavior changes.
also noticed 3 extensions that have indirect dependency on the json-schema package do not actually use the root packages, so removing them.
> fix issue reported by component governance

- extensions/mssql/config.json
This PR has the version bump for STS which has the below fixes
* Target win-x64 instead of win7-x64
* Bump version
* Update descriptions & fix path
* Target Framework upgrade for ManagedBatchParser proj according to DacFx_160 Nuget.
> sts 156 vbump

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/tools/packageHelper.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/17580
> Sql Binding: Add "Check out pane for more details" when nuget package download fails

- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql.xlf
> [Loc] Update to sql-database-projects and sql.xlf

- resources/xlf/en/sql.xlf
> [Loc] update to tabledesignercomponentinput xlf

- extensions/mssql/config.json
the changes since the current STS version:
> bump sts version to 159

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211118043652765 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211118043652765 to main

- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211119163441911 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211119163441911 to main

- src/sql/workbench/browser/designer/designer.ts
noticed that the width of a new property i am working on is not set to 100%.
turns out I am passing in the wrong setWidth flag for controls in TabsView, so I did a refactoring and removed the unnecessary flag and use the view parameter instead.
> input width in designer

- src/sql/workbench/services/connection/browser/connectionWidget.ts
This PR fixes #17594 
turns out the issue was introduced by my previous [change](https://github.com/microsoft/azuredatastudio/pull/16777/files#diff-6cbed09935af5348af95a7fe0c504191ac5e2ee347e0325d5d89d6237dd90698L459) when I was refactoring the code, the save password checkbox should only be unchecked when the auth type is not SqlLogin.
> save password checkbox fix

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211120043551137 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211120043551137 to main

- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211120163413090 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211120163413090 to main

- extensions/sql-database-projects/src/tools/buildHelper.ts
Missed this one when merging the renaming into the #17675
> Update one more variable name for sdk style projects

- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211121043418978 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211121043418978 to main

- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211121163419645 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211121163419645 to main

- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211122163356622 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211122163356622 to main

- resources/xlf/en/schema-compare.xlf
> [Loc] Update to schema-compare XLF

- extensions/resource-deployment/DEVELOPER_GUIDE.md
- extensions/resource-deployment/src/ui/modelViewUtils.ts
- samples/sample-resource-deployment/package.json
- samples/sample-resource-deployment/package.nls.json
Just doing the static arrays for now, we can add the source provider sample later.
> Add resource deployment samples for options

- resources/xlf/en/sql-database-projects.xlf
> [Loc] update to sql-database-projects xlf

- extensionsGallery-insider.json
- extensionsGallery.json
Releasing a new version of SQL Prompt for ADS
> Update sqlprompt version

- resources/localization/LCL/de/arc.xlf.lcl
- resources/localization/LCL/de/schema-compare.xlf.lcl
- resources/localization/LCL/es/arc.xlf.lcl
- resources/localization/LCL/es/schema-compare.xlf.lcl
- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/fr/schema-compare.xlf.lcl
- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/it/schema-compare.xlf.lcl
- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ja/schema-compare.xlf.lcl
- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/ko/schema-compare.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
- resources/localization/LCL/pt-BR/schema-compare.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/ru/schema-compare.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/schema-compare.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/schema-compare.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211201043552459 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211201043552459 to main

- resources/localization/LCL/es/arc.xlf.lcl
- resources/localization/LCL/es/schema-compare.xlf.lcl
- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/it/schema-compare.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/schema-compare.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211201164343436 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211201164343436 to main

- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/ko/schema-compare.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211202043419609 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211202043419609 to main

- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ja/schema-compare.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211202163428409 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211202163428409 to main

- src/sql/workbench/contrib/query/browser/queryResultsView.ts
This PR fixes #6763 
from the most recent screenshot in the issue, I can't really tell why my previous PR https://github.com/microsoft/azuredatastudio/pull/17278 didn't work for the user, so I am adding another guard (try-catch block) to make sure the query editor is not crashing when this happens again.
> do not crash query editor

- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to sql-database-projects and sql xlfs

- src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
- src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/17606
> Wait for all notebook models to load before shutting down active sessions during python upgrade

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211204043643393 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211204043643393 to main

- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211204163405636 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211204163405636 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211205043622626 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211205043622626 to main

- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211205163431594 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211205163431594 to main

- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211206043442899 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211206043442899 to main

- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211206163514866 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211206163514866 to main

- resources/xlf/en/sql-migration.xlf
> [Loc] update to sql-migration

- src/sql/workbench/contrib/notebook/test/browser/cellToolbarActions.test.ts
- src/sql/workbench/services/notebook/browser/models/cellEdit.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
> Add undo/redo to convert cells

- resources/xlf/en/sql.xlf
> [Loc] added convertcelltypeedit

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211208043438738 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211208043438738 to main

- src/sql/workbench/contrib/query/browser/media/gridPanel.css
This PR fixes #17833
port #17837 to release branch.
> fix grid actionbar (#17837)

- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211208163344543 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211208163344543 to main

- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/17850
> [Port] fix load publish profile not working (#17851)

- extensionsGallery-insider.json
Link to latest product build:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=131709&view=artifacts&pathAsName=false&type=publishedArtifacts
> updating sql-migration version to 0.1.11 for insiders 

- src/sql/workbench/contrib/notebook/test/browser/cellToolbarActions.test.ts
- src/sql/workbench/services/notebook/browser/models/cellEdit.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
* add undo/redo to convert cells
This PR fixes #17822
> Add undo/redo to convert cells (#17835)

- extensionsGallery-insider.json
- extensionsGallery.json
link to build:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=131709&view=artifacts&pathAsName=false&type=publishedArtifacts
> updating sql-migration extension to 0.1.11 for stable/release galleries (in RC)

- src/sql/workbench/contrib/notebook/test/electron-browser/notebookModel.test.ts
- src/sql/workbench/services/notebook/browser/models/cellEdit.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
* fix split cell undo
This PR fixes  #17820
> Fix split cell undo (#17845)

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211209043437479 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211209043437479 to main

- resources/localization/LCL/pt-BR/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211209163408411 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211209163408411 to main

- extensionsGallery-insider.json
Updating sql database projects to 0.14.0 in insiders. 
Same vsix as in https://github.com/microsoft/azuredatastudio/pull/17883
> update sql database projects to 0.14.0 in insiders

- extensionsGallery.json
Updating sql database projects to 0.14.0 for the December release.
build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=131888&view=artifacts&pathAsName=false&type=publishedArtifacts
> update sql database projects to 0.14.0 in RC gallery

- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211210043424882 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211210043424882 to main

- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211210163429718 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211210163429718 to main

- extensionsGallery-insider.json
- extensionsGallery.json
Updated "ExtraSqlScriptAs" extension to version 0.4.1
> Updated "ExtraSqlScriptAs" extension to 0.4.1

- src/sql/azdata.d.ts
Noticed this while working on some other stuff...
> Fix API docs for NotebookEditorEdit

- src/sql/base/common/locConstants.ts
- src/vs/workbench/contrib/files/browser/files.contribution.ts
> Update setting description product name (Code -> ADS)

- extensionsGallery-insider.json
- extensionsGallery.json
Langpacks are available here: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=132612&view=artifacts&pathAsName=false&type=publishedArtifacts
This adds the langpacks for the December release
> Add langpacks to RC1 branch for December release

- extensionsGallery-insider.json
Langpacks are from this release: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=132612&view=artifacts&pathAsName=false&type=publishedArtifacts 
Adds December langpacks to Insider gallery, a companion PR to #17914
> added changes to extensionsGallery-insider

- resources/xlf/en/sql.xlf
> [Loc] Small update to sql.xlf

- resources/localization/LCL/ru/cms.xlf.lcl
- resources/localization/LCL/ru/mssql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211215043513899 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211215043513899 to main

- resources/xlf/en/arc.xlf
- resources/xlf/en/sql.xlf
> [Loc] Additions to arc and sql xlfs

- extensions/mssql/config.json
Mitigation for issue https://github.com/microsoft/azuredatastudio/issues/17926.
> Bump STS to rollback data type changes

- extensions/mssql/config.json
Port mitigation for https://github.com/microsoft/azuredatastudio/issues/17926.
> Bump STS to rollback data type changes (#17935)

- extensions/mssql/config.json
> Fix typo in vbump

- extensions/mssql/config.json
> Fix typo in vbump (#17937)

- extensionsGallery.json
> PR to merge changes from "extensions/rc1" to "release/extensions"

- resources/localization/LCL/es/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211216043630194 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211216043630194 to main

- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211216163420297 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211216163420297 to main

- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
Register Undo/Redo commands when using Edit Menu to undo/redo at cell level.
This PR fixes #17821
> Register undo redo command

- extensions/sql-migration/package.json
bump sql-migration version to 0.1.12
> sql-migration vbump 0.1.12

- extensions/sql-database-projects/package.json
vbumping sql database projects to 0.15.0 now that the December release is done.
> vbump sql database projects to 0.15.0

- resources/localization/LCL/de/arc.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/arc.xlf.lcl
- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211217043954523 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20211217043954523 to main

- src/sql/platform/connection/common/connectionConfig.ts
- src/sql/platform/connection/common/connectionStore.ts
- src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts
these were added by me a couple days ago, today I saw a null reference error in the console, so fixing it.
> null check before calling isDisposable

- src/sql/workbench/contrib/notebook/browser/notebookViews/notebookViews.component.ts
- src/sql/workbench/contrib/notebook/test/stubs.ts
- src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts
No reason to have duplicate of these
> Consolidate INotebookEditOperation interfaces

- src/sql/workbench/services/notebook/browser/models/cellEdit.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
Implement redo action for Split Cells
> Add redo action for split cells

- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/baselines/openSdkStyleSqlProjectWithFilesSpecifiedBaseline.xml
- extensions/sql-database-projects/src/test/project.test.ts
This PR makes is mostly tests and a small change to get delete folder working for SDK style projects.
> Handle delete folder for SDK style sql projects

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/base/browser/ui/table/table.ts
- yarn.lock
remove the workaround in ADS and use new version of slickgrid.
slickgrid changes: https://github.com/microsoft/SlickGrid.ADS/pull/3
> fix table focus issue

- extensionsGallery-insider.json
- extensionsGallery.json
> update powershell extension

- resources/xlf/en/sql.xlf
> [Loc] update with strings from vscode notebook

- extensionsGallery-insider.json
- extensionsGallery.json
updating sql database projects with fix for https://github.com/microsoft/azuredatastudio/issues/17963
build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=134615&view=artifacts&pathAsName=false&type=publishedArtifacts
> update sql database projects to 0.14.1

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/test/projectTree.test.ts
Making the same test update and comment addition from #17982 in main.
> update sql projects test and add comment

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220106163557145 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220106163557145 to main

- build/azure-pipelines/common/installPlaywright.js
- build/azure-pipelines/common/installPlaywright.ts
- package.json
- yarn.lock
This PR fixes #18003.
The issue was found with the latest VS code merge.
Issue from Playwright: #18003
Fix from Playwright: https://github.com/microsoft/playwright/commit/3c7d2aae6a0596df717239d24b60ba3702f5fdb8
in v1.17.1
> vbump playwright to vs code latest

- resources/xlf/en/sql.xlf
> [Loc] update to sql.xlf

- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220107043451738 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220107043451738 to main

- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220107163444063 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220107163444063 to main

- package.json
- test/smoke/src/main.ts
- test/smoke/src/sql/areas/import/import.test.ts
- test/smoke/src/sql/areas/notebook/addRemoteBook.test.ts
- test/smoke/src/sql/areas/notebook/createBook.test.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
- test/smoke/src/sql/areas/notebook/notebookView.test.ts
- test/smoke/src/sql/areas/queryEditor/queryEditor.test.ts
- test/smoke/src/sql/main.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/17998
1. Bump sqlite for new electron version
2. Fix the smoke test setup to handle changes VS Code made to the base setup stuff
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=135070&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=05af1eac-c39c-5c75-1e3f-dd115ec8907d
The smoke tests now run but there's some failures that will still need investigation. (Import @aasimkhan30)
> Fix smoke tests not running

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220108164505460 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220108164505460 to main

- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220109163432138 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220109163432138 to main

- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220110043424580 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220110043424580 to main

- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220110164051843 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220110164051843 to main

- extensions/sql-database-projects/src/models/deploy/deployService.ts
- extensions/sql-database-projects/src/typings/vscode-mssql.d.ts
Bringing up to the latest - mostly for syncing up the indentation so there aren't formatting differences.
> Update VS Code MSSQL typings

- resources/xlf/en/sql.xlf
> [Loc] added strings for queryPlan2

- src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/17999
We'll need the debug service to enable these
> Remove Notebook debug contributions

- extensions/sql-database-projects/src/models/project.ts
This updates project.ts to add the types where any was used before since now it's possible after the changes in #17539
> add types instead of using any in project.ts

- extensions/schema-compare/package.json
- extensions/sql-database-projects/package.json
> update azdata dependency for schema compare and sql database projects

- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to sql-database-projects and sql

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220116043617927 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220116043617927 to main

- resources/xlf/LocProject.json
> [Loc] update LocProject with git project

- resources/xlf/en/sql.xlf
> [Loc] removed noQueryFoundForUri from sql.xlf

- build/gulpfile.vscode.js
- resources/xlf/LocProject.json
- resources/xlf/en/azcli.xlf
> [Loc] add azcli for localization

- resources/xlf/en/azurecore.xlf
> [Loc] add change to token retry message

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/azurecore.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/azurecore.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/ko/azurecore.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/azurecore.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220121163511951 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220121163511951 to main

- resources/xlf/en/sql-database-projects.xlf
> [Loc] another update to sql-database-projects

- build/actions/yarn.lock
- build/yarn.lock
- extensions/azurecore/package.json
- extensions/azurecore/yarn.lock
- extensions/github-authentication/package.json
- extensions/github-authentication/yarn.lock
- extensions/github/yarn.lock
- extensions/machine-learning/yarn.lock
- extensions/microsoft-authentication/package.json
- extensions/microsoft-authentication/yarn.lock
- extensions/notebook/package.json
- extensions/notebook/yarn.lock
- test/smoke/package.json
- test/smoke/yarn.lock
- yarn.lock
Update node-fetch to resolve build break.
> Bump node-fetch to 2.6.7

- extensions/mssql/src/mssql.d.ts
This PR adds PaaS/IaaS specific interfaces
> update sku interfaces

- resources/xlf/en/sql.xlf
> [Loc] added string for compatabilitydescription

- product.json
add the nps survey url, the code the consumes this is already in place: https://github.com/microsoft/azuredatastudio/blob/main/src/vs/workbench/contrib/surveys/browser/nps.contribution.ts
> add nps survey url

- package.json
- yarn.lock
This PR bumps the azdataGraph package version.
> Updates azdataGraph package version.

- resources/localization/LCL/de/azurecore.xlf.lcl
- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/azurecore.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/azurecore.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/azurecore.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220127043615938 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220127043615938 to main

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220127163650691 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220127163650691 to main

- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220128043444982 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220128043444982 to main

- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220129164011799 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220129164011799 to main

- package.json
- yarn.lock
This PR bumps the azdataGraph version to 0.0.7
> Bumps azdataGraph version to 0.0.7

- resources/xlf/en/azurecore.xlf
- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to azurecore sql-database-projects sql

- resources/xlf/en/sql.xlf
> [Loc] added message for defaultRemoveRowConfirmationMessage

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/skuRecommendationResults/skuRecommendationResultsDialog.ts
This PR refactors the storage properties requirements text into a table format.
> create storage properties table

- extensionsGallery-insider.json
- extensionsGallery.json
Update Redgate SQL Prompt extension to version 0.2.10
> Update Redgate SQL Prompt

- extensions/mssql/config.json
- extensions/mssql/src/tableDesigner/tableDesigner.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/browser/designer/designer.ts
- src/sql/workbench/browser/designer/interfaces.ts
- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
refresh the designer when the changes are published to make sure the table information is up to date.
STS changes in the new version:
@VasuBhog please confirm you changes are good to be included.
> refresh the table designer after publishing

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/azurecore.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/azurecore.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/azurecore.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/azurecore.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/azurecore.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220204163928420 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220204163928420 to main

- resources/localization/LCL/de/azurecore.xlf.lcl
- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/azurecore.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/azurecore.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220205163643821 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220205163643821 to main

- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220206163844549 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220206163844549 to main

- package.json
- yarn.lock
Need to update azdataGraph to pickup some changes for webmode.
> Bump azdataGraph to 0.0.11

- resources/localization/LCL/de/arc.xlf.lcl
- resources/localization/LCL/es/arc.xlf.lcl
- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220209163819893 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220209163819893 to main

- resources/xlf/en/arc.xlf
- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to arc, sql-database-projects, and sql xlfs

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/vs/code/browser/workbench/workbench-dev.html
- src/vs/code/browser/workbench/workbench.html
Changes to module loading to fix webmode build.  Reverts back the module maps in workbench.html.  I'll look into updating back the newer approach during the next merge.
> Fix web build

- resources/localization/LCL/it/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220210163414363 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220210163414363 to main

- extensions/mssql/config.json
- remote/package.json
@alanrenmsft and @Charles-Gagnon do the changes look okay to bring in.
> Vbumping STS to get latest Query Plan code

- extensions/mssql/package.json
> add table designer menu to Azure view

- extensions/resource-deployment/DEVELOPER_GUIDE.md
Added documentation for dynamic options and its related behavior to CategoryValues.
> Added Dynamic Options description

- extensions/json/package.json
Fixes https://github.com/microsoft/azuredatastudio/issues/18310
Same fix as VS Code : https://github.com/microsoft/vscode/commit/cf0231eb6e0632a655c71ab8a55b2fa0c960c3e3
> Fix Notebook registered file type

- resources/localization/LCL/de/arc.xlf.lcl
- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/arc.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220211163633587 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220211163633587 to main

- resources/xlf/en/sql-migration.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to sql-migration and sql

- src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts
> Fixed tooltip not hiding when scrolling through graph control.

- src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts
- src/sql/workbench/services/query/common/queryManagement.ts
> Removing feature specific preview flag in query plan

- extensions/sql-migration/src/wizard/targetSelectionPage.ts
> removing warning 'logError' is declared but its value is never read

- resources/xlf/en/arc.xlf
- resources/xlf/en/sql.xlf
> [Loc] Update to arc and sql xlf

- src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts
> Adding save file functionality to query plan

- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220212163624645 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220212163624645 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220214163537283 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220214163537283 to main

- resources/xlf/en/sql-migration.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to sql.xlf and sql-migration

- src/sql/workbench/contrib/queryplan2/browser/constants.ts
- src/sql/workbench/contrib/queryplan2/browser/media/queryPlan2.css
- src/sql/workbench/contrib/queryplan2/browser/widgets/customZoomWidget.ts
> Using proper zoom icon

- src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts
> Fixing graph edges disconnecting in query plan

- i18n/ads-language-pack-de/CHANGELOG.md
- i18n/ads-language-pack-es/CHANGELOG.md
- i18n/ads-language-pack-fr/CHANGELOG.md
- i18n/ads-language-pack-it/CHANGELOG.md
- i18n/ads-language-pack-ja/CHANGELOG.md
- i18n/ads-language-pack-ko/CHANGELOG.md
- i18n/ads-language-pack-pt-BR/CHANGELOG.md
- i18n/ads-language-pack-ru/CHANGELOG.md
- i18n/ads-language-pack-zh-hans/CHANGELOG.md
- i18n/ads-language-pack-zh-hant/CHANGELOG.md
Update langpack release date to match that of February Release
> Small update to the changelog

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- yarn.lock
This PR bumps the version for the azdataGraph package from 0.0.14 to 0.0.15
> azdataGraph version bump to 0.0.15

- .github/CODEOWNERS
Going to follow up with figuring out if there's a better way to have the release DRI be included - this branch is meant to be temporary so not sure this is going to work updating the CODEOWNERS here specifically. But for now just getting her on reviews.
> Update CODEOWNERS for extensions/rc1

- src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts
This PR fixes #18360 
PR to main branch #18361
> Fixing graph editing (#18361)

- src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
> avoid auto language detection for sql editor

- src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
port the fix to release branch
This PR fixes #18399
> avoid auto language detection for sql editor (#18402)

- resources/localization/LCL/de/azcli.xlf.lcl
- resources/localization/LCL/de/git.xlf.lcl
- resources/localization/LCL/es/azcli.xlf.lcl
- resources/localization/LCL/es/git.xlf.lcl
- resources/localization/LCL/fr/azcli.xlf.lcl
- resources/localization/LCL/fr/git.xlf.lcl
- resources/localization/LCL/it/azcli.xlf.lcl
- resources/localization/LCL/it/git.xlf.lcl
- resources/localization/LCL/ja/azcli.xlf.lcl
- resources/localization/LCL/ja/git.xlf.lcl
- resources/localization/LCL/ko/azcli.xlf.lcl
- resources/localization/LCL/ko/git.xlf.lcl
- resources/localization/LCL/pt-BR/azcli.xlf.lcl
- resources/localization/LCL/pt-BR/git.xlf.lcl
- resources/localization/LCL/ru/azcli.xlf.lcl
- resources/localization/LCL/ru/git.xlf.lcl
- resources/localization/LCL/zh-Hans/azcli.xlf.lcl
- resources/localization/LCL/zh-Hans/git.xlf.lcl
- resources/localization/LCL/zh-Hant/azcli.xlf.lcl
- resources/localization/LCL/zh-Hant/git.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220216124329564 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220216124329564 to main

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220216163528265 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220216163528265 to main

- extensions/notebook/package.json
- extensions/notebook/yarn.lock
For https://github.com/microsoft/azuredatastudio/issues/18423
> Bump url-parse

- src/sql/workbench/contrib/queryplan2/browser/queryPlanPropertiesView.ts
This PR fixes #18357, #18375 
The main branch PR is #18400
> Adding tooltips and fixing spacing (#18400)

- src/sql/workbench/browser/designer/designerScriptEditor.ts
this PR fixes: #18401 
port the commit from main to release branch.
original PR: https://github.com/microsoft/azuredatastudio/pull/18406
> port table designer fix

- src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts
This PR fixes #18377, fixes #18387
> Fixing context menu strings

- src/sql/workbench/contrib/queryplan2/browser/media/queryPlan2.css
- src/sql/workbench/contrib/queryplan2/browser/widgets/customZoomWidget.ts
This PR fixes #18380 
Before:
Now: 
Tooltip:
> Adding zoom button

- src/sql/workbench/contrib/queryplan2/browser/media/queryPlan2.css
- src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts
- src/sql/workbench/contrib/queryplan2/browser/queryPlanPropertiesView.ts
This PR fixes #18382 
Before:
After:
> Fixing the height of the query plan

- src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/codeCell.component.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
- src/sql/workbench/contrib/notebook/browser/notebook.component.html
- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
* fix click code cell
* modified editmode when updating active cell
This PR fixes #18299
> Fix on click edit mode states (#18321)

- src/sql/workbench/browser/modelComponents/treeComponentRenderer.ts
For https://github.com/microsoft/azuredatastudio/issues/18429
> Fix contributed icons for ModelView trees not showing

- src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/18377, fixes https://github.com/microsoft/azuredatastudio/issues/18387
PR to main branch: https://github.com/microsoft/azuredatastudio/pull/18404
> Fixing context menu strings (#18404)

- src/sql/workbench/contrib/queryplan2/browser/constants.ts
- src/sql/workbench/contrib/queryplan2/browser/media/queryPlan2.css
- src/sql/workbench/contrib/queryplan2/browser/widgets/customZoomWidget.ts
This PR fixes #18380
Main branch PR #18407
> Adding zoom button (#18407)

- src/sql/workbench/contrib/queryplan2/browser/media/queryPlan2.css
- src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts
- src/sql/workbench/contrib/queryplan2/browser/queryPlanPropertiesView.ts
This PR fixes #https://github.com/microsoft/azuredatastudio/issues/18382
PR to main branch https://github.com/microsoft/azuredatastudio/pull/18409
> Fixing the height of the query plan (#18409)

- resources/xlf/en/sql-migration.xlf
- resources/xlf/en/sql.xlf
> [loc] changes to sql-migration and sql xlfs

- extensions/mssql/config.json
- src/sql/azdata.proposed.d.ts
- src/sql/base/browser/ui/panel/panel.ts
- src/sql/workbench/browser/designer/designer.ts
- src/sql/workbench/browser/designer/designerMessagesTabPanelView.ts
- src/sql/workbench/browser/designer/designerScriptEditor.ts
- src/sql/workbench/browser/designer/designerScriptEditorTabPanelView.ts
- src/sql/workbench/browser/designer/interfaces.ts
- src/sql/workbench/browser/designer/media/designer.css
- src/sql/workbench/contrib/query/browser/queryResultsView.ts
- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
add validation, when there are validations errors, the publish action will be disabled and the errors tab will be opened along with the number of errors in the tab title.
when no validation error is detected, the errors tab will be removed
NOTE: I need to include the STS changes once a new build is available. STS PR: https://github.com/microsoft/sqltoolsservice/pull/1411
> table designer validation support

- extensions/mssql/config.json
- src/sql/azdata.proposed.d.ts
- src/sql/base/browser/ui/panel/panel.ts
- src/sql/workbench/browser/designer/designer.ts
- src/sql/workbench/browser/designer/designerMessagesTabPanelView.ts
- src/sql/workbench/browser/designer/designerScriptEditor.ts
- src/sql/workbench/browser/designer/designerScriptEditorTabPanelView.ts
- src/sql/workbench/browser/designer/interfaces.ts
- src/sql/workbench/browser/designer/media/designer.css
- src/sql/workbench/contrib/query/browser/queryResultsView.ts
- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
This PR fixes #18383 
This PR fixes #18445 
original PR: https://github.com/microsoft/azuredatastudio/pull/18438
> port table designer fixes to release branch

- extensions/sql-database-projects/src/dialogs/addSqlBindingQuickpick.ts
- extensions/sql-database-projects/src/test/testContext.ts
- extensions/sql-database-projects/src/typings/vscode-mssql.d.ts
This PR fixes #18012
vscode-mssql PR: https://github.com/microsoft/vscode-mssql/pull/17231
Introduced a way to get the connection string with connection details so we can now remove this and use the exposed APIs from mssql.
> Add SQL Binding Disconnected Scenario

- build/azure-pipelines/win32/sql-product-test-win32.yml
* Add option to disable running integration tests
(cherry picked from commit 932865ceeef51af743fabf8b6524030972455b32)
> Add option to disable running integration tests (#18454)

- extensionsGallery-insider.json
Link to build https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=141330&view=artifacts&pathAsName=false&type=publishedArtifacts
> Updating sql-migration extension version to 0.1.12 for insiders

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts
- yarn.lock
This PR adds a tooltipTitle prop to the diagram node, so that the azdataGraph library can use that rather than manipulating the subtext information to extract a title for tooltips.
> Adds a tooltip title prop to the diagram node.

- extensionsGallery.json
Link to build https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=141330&view=artifacts&pathAsName=false&type=publishedArtifacts
> Update sql migration extension to 0.1.12

- extensions/mssql/config.json
https://github.com/microsoft/azuredatastudio/issues/18457
> fix a typo in table designer

- extensions/mssql/config.json
This PR fixes #18457 
port table designer typo fix, original PR: https://github.com/microsoft/azuredatastudio/pull/18464
> port typo fix

- extensions/sql-migration/package.json
Bump azdata version to latest 1.35
> Update package.json with latest  azdata version 1.35

- resources/localization/LCL/de/azcli.xlf.lcl
- resources/localization/LCL/de/git.xlf.lcl
- resources/localization/LCL/es/azcli.xlf.lcl
- resources/localization/LCL/es/git.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/azcli.xlf.lcl
- resources/localization/LCL/fr/git.xlf.lcl
- resources/localization/LCL/it/azcli.xlf.lcl
- resources/localization/LCL/it/git.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/azcli.xlf.lcl
- resources/localization/LCL/ja/git.xlf.lcl
- resources/localization/LCL/ko/azcli.xlf.lcl
- resources/localization/LCL/ko/git.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/azcli.xlf.lcl
- resources/localization/LCL/pt-BR/git.xlf.lcl
- resources/localization/LCL/ru/azcli.xlf.lcl
- resources/localization/LCL/ru/git.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/azcli.xlf.lcl
- resources/localization/LCL/zh-Hans/git.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/azcli.xlf.lcl
- resources/localization/LCL/zh-Hant/git.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220218163528108 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220218163528108 to main

- src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts
(cherry picked from commit a1a1793221f2cd541049890f96bd4e0c9ef4d717)
Fixes https://github.com/microsoft/azuredatastudio/issues/18465
> [Port] Add timeout delay to Notebook cell connect (#18475)

- resources/xlf/en/sql.xlf
> [Loc] small update to sql xlf with table designer

- src/vs/platform/protocol/electron-main/protocolMainService.ts
- src/vs/workbench/contrib/webview/browser/pre/index.html
Port upstream bug fixes for https://github.com/microsoft/vscode/issues/142556.  To fix https://github.com/microsoft/azuredatastudio/issues/18494.
> Port - Restrict which sites out webview iframe can frame

- src/sql/workbench/contrib/notebook/browser/find/notebookFindWidget.ts
- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
* fix search on notebooks
* keep focus on findwidget
This PR fixes #18472
> [Port] Fix search experience in notebooks (#18474)

- src/sql/workbench/contrib/welcome/page/browser/gettingStartedTour.ts
This PR fixes #18490 
The PR to the main branch is #18492
> Fixing welcome tour popup images in release. 

- src/vs/workbench/contrib/welcome/telemetryOptOut/browser/telemetryOptOut.contribution.ts
- src/vs/workbench/contrib/welcome/telemetryOptOut/browser/telemetryOptOut.ts
- src/vs/workbench/contrib/welcome/telemetryOptOut/electron-sandbox/telemetryOptOut.contribution.ts
- src/vs/workbench/contrib/welcome/telemetryOptOut/electron-sandbox/telemetryOptOut.ts
- src/vs/workbench/workbench.sandbox.main.ts
- src/vs/workbench/workbench.web.main.ts
> Fix opt out prompt behavior

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts
This PR fixes #18519. This got introduced when I added a confirmation message for apply in #18199. This moves the confirmation message to only show when the selected action is "Apply all changes"
> only show confirmation message for apply all changes, not for view changes in Schema Compare

- src/vs/workbench/contrib/welcome/telemetryOptOut/browser/telemetryOptOut.ts
(cherry picked from commit 5731366a1cf8dfa4ebb22adb4d7aa2e1995a12e3)
Fixes https://github.com/microsoft/azuredatastudio/issues/18523
> Fixing query editor smoke test (#18515)

- build/azure-pipelines/darwin/sql-product-build-darwin-signing.yml
(cherry picked from commit 23cbb98162f162ca77e2826160447ddf5c2713c5)
> [Port] Fix Mac signing (#18534)

- extensionsGallery-insider.json
This updates schema compare to 1.13.0 and sql database projects to 0.15.0 in insiders.
Build with vsixs: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=142107&view=results
> update schema compare and sql database projects in insiders

- extensionsGallery.json
Update extensionsGallery.json to have arc and azcli be version 1.0.0 for Feb release.
> Updated extensionsGallery.json to have 1.0.0 arc and azcli

- CHANGELOG.md
- README.md
> Updating Readme and Changelog for 1.35.0 release

- CHANGELOG.md
- README.md
(cherry picked from commit 0193f8a6dca902a4d7a35eeb9ddcb4bc4ae2454b)
> Updating Readme and Changelog for 1.35.0 release (#18543)

- .github/CODEOWNERS
- build/azure-pipelines/updateGalleries.yml
- extensionsGallery-insider.json
- extensionsGallery.json
Merging in all the changes from RC1
> Update Gallery for Release

- extensionsGallery-insider.json
- extensionsGallery.json
- scripts/validateGalleries.js
Add check for certain assets to be hosted on Github or our blob storage to prevent CORS issues we saw with the latest merge. 
Also fixed a few places that were missed when updating the galleries previously.
> Add check and fix galleries

- CHANGELOG.md
> fixing links that got swapped

- CHANGELOG.md
> fixing links that got swapped (#18557)

- package.json
bumping the version after a successful release
> bumping version to 1.36 following 1.35's release

- .github/label-actions.yml
This will create an automated comment whenever the `Needs Logs - Azure` label is added to an issue.
> Add label instructions for Needs Logs - Azure

- extensionsGallery-insider.json
- extensionsGallery.json
- scripts/validateGalleries.js
Only support MM/DD/YYYY format currently
> Fix date in galleries

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220226164204149 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220226164204149 to main

- extensionsGallery-insider.json
Adds in the most recent langpacks to the Insiders gallery. If the date needs to be changed let me know, but they were uploaded on that date technically. (Posting this again to account for changes to the release/extensions branch)
> added langpack update to insiders gallery

- .github/workflows/ci.yml
Currently our windows builds fail with the error:
[12](https://github.com/microsoft/azuredatastudio/runs/5364797958?check_suite_focus=true#step:5:12)*** Invalid C/C++ Compiler Toolchain. Please check https://github.com/microsoft/vscode/wiki/How-to-Contribute.
I am updating to be compatible with windows-2022
> Update CI for new windows-latest

- test/smoke/src/sql/areas/notebook/notebook.test.ts
Automating https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_workitems/edit/8192
> Add a couple Notebook smoke tests for rendering links/imgs

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/azcli.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220302163615906 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220302163615906 to main

- extensionsGallery-insider.json
- extensionsGallery.json
Update extensions gallery to include latest version of `Extension for Oracle`. This includes few bug fixes, so only bumping patch version.
> Update Extension for Oracle to v0.1.1

- resources/xlf/en/sql.xlf
> [Loc] added changes for sql xlf

- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
Instead of checking that the find widget is not visible, we should check that is not focused.
This PR fixes  #18505
> check find widget is not focused

- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220303163807319 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220303163807319 to main

- package.json
- resources/win32/VisualElementsManifest.xml
Fixes https://github.com/microsoft/azuredatastudio/issues/18618
> Fix pinned app name

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220304163613540 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220304163613540 to main

- resources/xlf/en/sql.xlf
> [Loc] fixed path for editableDropdown

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
> add learn more link for sdk style in create project from db dialog

- resources/xlf/en/sql-bindings.xlf
- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql-migration.xlf
> [Loc] Updates to sql files with changes

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220305163820033 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220305163820033 to main

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220306163954445 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220306163954445 to main

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220307163624354 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220307163624354 to main

- src/sql/workbench/services/tableDesigner/browser/tableDesignerPublishDialog.ts
Added a markdown renderer inside the publish changes dialogs. I tested out with test markdown strings myself.
> added markdown renderer for publish dialog

- extensions/sql-bindings/package.nls.json
> Fix display name and description key for sql bindings ext

- resources/xlf/en/sql-bindings.xlf
> [Loc] added small fix to sql-bindings

- build/azure-pipelines/darwin/sql-product-build-darwin.yml
- build/azure-pipelines/web/sql-product-build-web.yml
- test/smoke/src/sql/areas/notebook/notebook.test.ts
SMOKE_FAIL_ON_ERROR = false https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=144051&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=a5e52b91-c83f-5429-4a68-c246fc63a4f7
SMOKE_FAIL_ON_ERROR = true https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=144050&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=a5e52b91-c83f-5429-4a68-c246fc63a4f7
> Add var to let smoke tests fail build

- build/azure-pipelines/sql-product-build.yml
Turn off Windows Test step to get a new insiders build while build break is being investigated.
> Turn off Windows Test step

- resources/xlf/en/sql-bindings.xlf
> [Loc] update to sql-bindings xlf file

- extensions/mssql/src/contracts.ts
- extensions/mssql/src/features.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/browser/mainThreadDataProtocol.ts
- src/sql/workbench/api/common/extHostDataProtocol.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
- src/sql/workbench/services/tableDesigner/browser/tableDesignerPublishDialog.ts
PR fixes https://github.com/microsoft/azuredatastudio/issues/18650
> add ability for md + text reports

- extensions/sql-bindings/package.nls.json
- resources/xlf/en/sql-bindings.xlf
This PR adds in a missing string that the package.json of sql binding tries to load but could not find.
@VasuBhog please let me know if this string matches what you have in mind for the Add Sql Binding title.
> Added fix to sql-bindings nls file

- resources/xlf/en/sql.xlf
> [Loc] add table designer XLF

- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
- src/sql/base/browser/ui/infoBox/infoBox.ts
- src/sql/base/browser/ui/infoBox/media/infoBox.css
- src/sql/workbench/api/common/extHostModelView.ts
- src/sql/workbench/browser/modelComponents/infoBox.component.ts
New Clickable infobox
Small text:
Large text:
Multiline text:
Arrow is outlined when we hover over infobox and cursor is changed to pointer: 
Light:
HC:
Normal infobox:
Design inspiration from portal:
> Making infobox clickable

- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
move some APIs that has been there for a while to the stable api set, added comments for those without it.
> promote some APIs to stable api set.

- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
Probably some more we could move - planning on going through this in chunks. 
(FYI the data grid stuff isn't something I'm planning on moving over now. Or probably ever - at some point I'm likely just to rip it out since there's nothing we're actually using it for)
> Move some more azdata APIs to stable

- extensions/sql-bindings/src/common/telemetry.ts
- extensions/sql-bindings/src/common/utils.ts
- extensions/sql-bindings/src/extension.ts
This PR fixes issues when testing out vscode development using the steps [here](https://github.com/microsoft/azuredatastudio/blob/main/extensions/sql-bindings/VSCODE_DEVELOPMENT.md).
Changing the Telemetry to find the package.json name using a function rather than hardcoding the value as it hardcoding may not work for all use cases and will result in the extension failing when using SQL bindings commands.
> Fixes issues with SQL Bindings vscode dev

- resources/xlf/en/sql-migration.xlf
> [Loc] small update to sql-migration

- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220312163637268 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220312163637268 to main

- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220313153520837 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220313153520837 to main

- extensions/mssql/src/credentialstore/sqlCredentialService.ts
Default to inbuilt secret storage on Linux.
> default to native credential service in linux

- resources/xlf/en/data-workspace.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to data-workspace xlf and sql xlf

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- yarn.lock
bring in this fix: https://github.com/microsoft/SlickGrid.ADS/pull/4
> vbump slickgrid to bring in an accessibility fix

- extensions/mssql/config.json
@aasimkhan30 has confirmed his changes were good to go.
> vbump STS to bring in  fixes for a couple data type handling issues.

- resources/xlf/en/data-workspace.xlf
- resources/xlf/en/sql-bindings.xlf
> [Loc] update to data-workspace and sql-bindings xlfs

- extensions/mssql/config.json
This PR fixes #18630 
This PR fixes #18615
> new STS with fixes for hotfix release

- package.json
> Bump version to 1.35.1

- resources/xlf/en/sql-migration.xlf
> [Loc] small update to sql-migration xlf

- resources/localization/LCL/de/data-workspace.xlf.lcl
- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/data-workspace.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/data-workspace.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/data-workspace.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/data-workspace.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/data-workspace.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/data-workspace.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/data-workspace.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/data-workspace.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220316153624231 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220316153624231 to main

- resources/xlf/en/data-workspace.xlf
> [Loc] update to data-workspace xlf

- resources/xlf/en/sql.xlf
> added changes to sql xlf

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
- extensions/sql-bindings/src/dialogs/addSqlBindingQuickpick.ts
- extensions/sql-bindings/src/extension.ts
- extensions/sql-bindings/src/sql-bindings.d.ts
Refactor the AddSqlBindingQuickpick function and create different methods to reuse later.
> Update SQL Bindings API

- extensionsGallery-insider.json
- extensionsGallery.json
Link to build: 
https://mssqltools.visualstudio.com/_apis/resources/Containers/4047878/drop?itemPath=drop%2Fextensions%2Fsql-migration-0.1.13.vsix
> Update sql-migration extension version to 0.1.13

- resources/localization/LCL/de/data-workspace.xlf.lcl
- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/data-workspace.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/data-workspace.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/data-workspace.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220317153547861 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220317153547861 to main

- CHANGELOG.md
> Updating Changelog with Hotfix notes

- CHANGELOG.md
> Updating Changelog with Hotfix notes (#18760)

- extensions/sql-migration/package.json
bump sql-migration version to 0.1.14
> sql migration extension version bump 0.1.14

- src/sql/base/browser/ui/infoBox/infoBox.ts
This makes sure that clickable state is set properly when initializing info boxes.
> Fixing clickable state of infobox not setting properly when initializing it.

- resources/xlf/en/arc.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to arc and sql XLFS

- extensionsGallery-insider.json
- extensionsGallery.json
Updating to latest version of extension for oracle v0.1.2
> vbump for extension for oracle

- .github/CODEOWNERS
Add code owners for sql-bindings extension
> code owners for sql-bindings

- resources/xlf/en/sql.xlf
> [Loc] added loading notebook message

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220327153558594 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220327153558594 to main

- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220328153802115 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220328153802115 to main

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/deployDatabaseQuickpick.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
- extensions/sql-database-projects/src/dialogs/utils.ts
If project target is Azure, adding the name "SQL Server Azure" to all the titles and messages
> Chaning the name of server in deploy option if target is Azure

- resources/xlf/en/sql-database-projects.xlf
> [Loc] change to sql-database-project xlf

- resources/localization/LCL/ja/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220329171809532 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220329171809532 to main

- extensions/notebook/src/jupyter/jupyterKernel.ts
- extensions/notebook/src/test/common.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/browser/mainThreadNotebook.ts
- src/sql/workbench/api/common/extHostNotebook.ts
- src/sql/workbench/api/common/notebooks/vscodeExecuteProvider.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
- src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts
- src/sql/workbench/contrib/notebook/test/emptySessionClasses.ts
- src/sql/workbench/contrib/notebook/test/stubs.ts
- src/sql/workbench/services/notebook/browser/models/clientSession.ts
- src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts
- src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts
- src/sql/workbench/test/electron-browser/api/mainThreadNotebook.test.ts
First part of #18661. Doing the plumbing + hooking up Jupyter implementation.
> Restart kernel initial implementation

- resources/xlf/en/data-workspace.xlf
- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to xlfs

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- yarn.lock
This PR 
fixes #18290 
fixes #18379
fixes #18386
> Updating azdataGraph package to get tooltip improvements

- extensions/sql-bindings/src/common/telemetry.ts
- extensions/sql-bindings/src/common/utils.ts
- extensions/sql-bindings/src/dialogs/addSqlBindingQuickpick.ts
- extensions/sql-bindings/src/extension.ts
- extensions/sql-bindings/src/services/azureFunctionsService.ts
- extensions/sql-bindings/src/sql-bindings.d.ts
This PR adds bindings telemetry to capture the addSQLBinding Quickpick flow as well as create an azure function from the table.
> Add bindings telemetry

- src/sql/azdata.proposed.d.ts
- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
- src/sql/workbench/services/tableDesigner/browser/tableDesignerMetadata.ts
- src/sql/workbench/services/tableDesigner/browser/tableDesignerService.ts
This PR addresses https://github.com/microsoft/azuredatastudio/issues/18887
STS change - https://github.com/microsoft/sqltoolsservice/pull/1448
> added graph node types from edit and publish results

- resources/xlf/en/sql.xlf
> [Loc] add table filter xlf

- resources/localization/LCL/de/data-workspace.xlf.lcl
- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/data-workspace.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/data-workspace.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/data-workspace.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/data-workspace.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/data-workspace.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/data-workspace.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220401154038956 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220401154038956 to main

- resources/localization/LCL/es/data-workspace.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/it/data-workspace.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220403204248531 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220403204248531 to main

- resources/xlf/en/sql-database-projects.xlf
> [Loc] added updatedtosdkstyleerror

- extensions/sql-bindings/package.json
- extensions/sql-bindings/src/dialogs/addSqlBindingQuickpick.ts
- extensions/sql-bindings/src/services/azureFunctionsService.ts
- extensions/sql-bindings/yarn.lock
This PR adds another sessionID GUID which will allow us to tie all the telemetry points I added in the previous PR all together based on the sessionID.
> Add guid for session ID

- extensions/mssql/config.json
Fixes https://github.com/microsoft/azuredatastudio/issues/18892
Full set of changes https://github.com/microsoft/sqltoolsservice/compare/v3.0.0-release.216...v3.0.0-release.226
@aasimkhan30 @lewis-sanchez @kisantia @raymondtruong @abist @alanrenmsft @caohai Please let me know if your changes shouldn't be in yet
@benrr101 FYI
> Update STS to .226

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
This PR fixes #17827.
Using the doc here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings
I used the list to remove the settings and only list connection strings settings.
> Remove known settings from ConnectionStringSettingName prompt

- extensions/sql-bindings/src/common/constants.ts
- extensions/sql-bindings/src/services/azureFunctionsService.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/18907.
Adds progress bar for Add SQL Binding.
(reopened since a check was stuck (license check)).
> Add progress bar for adding sql binding

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- yarn.lock
This PR fixes #18818
As seen in the screenshot, operator names are no longer being truncated.
> Bumps azdataGraph version to 0.019

- resources/xlf/en/sql-bindings.xlf
> [Loc] added small string for sql-bindings

- src/sql/azdata.proposed.d.ts
- src/sql/base/browser/ui/table/plugins/contextMenuColumn.plugin.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/sql/workbench/browser/modelComponents/media/table.css
- src/sql/workbench/browser/modelComponents/table.component.ts
- src/sql/workbench/test/electron-browser/modalComponents/table.component.test.ts
> Adding context menu to table component

- resources/xlf/en/sql.xlf
> [Loc] added table show actions xlf

- extensions/arc/package.nls.json
Quick fix for the release: add text to the deployment tile as shown below.
> Added text to the Arc DC deploy tile that user must have done az login before continuing.

- .yarnrc
- package.json
- test/smoke/src/sql/main.ts
- yarn.lock
Update to latest Electron 13 build for April release.
> Bump Electron to 13.6.6

- package.json
Need to bump distro from merge conflict in smoke test main
> Bump distro for electron bump

- resources/xlf/en/arc.xlf
> [Loc] small update to arc xlf

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220406160426103 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220406160426103 to main

- resources/localization/LCL/de/arc.xlf.lcl
- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/arc.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220407154028529 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220407154028529 to main

- resources/xlf/en/sql-database-projects.xlf
> [Loc] add converttosdkstyleconfirmation message

- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/ko/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220408153712767 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220408153712767 to main

- i18n/ads-language-pack-de/translations/extensions/sql-database-projects.i18n.json
- i18n/ads-language-pack-es/translations/extensions/sql-database-projects.i18n.json
- i18n/ads-language-pack-fr/translations/extensions/arc.i18n.json
- i18n/ads-language-pack-fr/translations/extensions/sql-database-projects.i18n.json
- i18n/ads-language-pack-it/translations/extensions/sql-database-projects.i18n.json
- i18n/ads-language-pack-ja/translations/extensions/sql-database-projects.i18n.json
- i18n/ads-language-pack-ko/translations/extensions/arc.i18n.json
- i18n/ads-language-pack-ko/translations/extensions/sql-database-projects.i18n.json
- i18n/ads-language-pack-pt-BR/translations/extensions/sql-database-projects.i18n.json
- i18n/ads-language-pack-ru/translations/extensions/sql-database-projects.i18n.json
- i18n/ads-language-pack-zh-hans/translations/extensions/sql-database-projects.i18n.json
- i18n/ads-language-pack-zh-hant/translations/extensions/sql-database-projects.i18n.json
- resources/xlf/de/sql-database-projects.de.xlf
- resources/xlf/es/sql-database-projects.es.xlf
- resources/xlf/fr/arc.fr.xlf
- resources/xlf/fr/sql-database-projects.fr.xlf
- resources/xlf/it/sql-database-projects.it.xlf
- resources/xlf/ja/sql-database-projects.ja.xlf
- resources/xlf/ko/arc.ko.xlf
- resources/xlf/ko/sql-database-projects.ko.xlf
- resources/xlf/pt-br/sql-database-projects.pt-BR.xlf
- resources/xlf/ru/sql-database-projects.ru.xlf
- resources/xlf/zh-hans/sql-database-projects.zh-Hans.xlf
- resources/xlf/zh-hant/sql-database-projects.zh-Hant.xlf
This is the last update to be pushed in.
> [Loc] Last update to langpack source files for April release.

- src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR fixes #17657
we need to retrieve data from the data source that is being displayed.
before:
after:
> fix for issue that when filtered json data opened in editor not the same as data in cell issue

- resources/xlf/en/sql-bindings.xlf
> [Loc] update to sql-bindings

- extensionsGallery-insider.json
- extensionsGallery.json
This PR updates Schema compare, dacpac and SQLProject extensions for insiders and stable gallery for April.
Build for insiders : https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=148998&view=artifacts&pathAsName=false&type=publishedArtifacts
Build for stable: Waiting on release branch
> updating extensions for insiders and stable gallery for April

- extensionsGallery-insider.json
- extensionsGallery.json
Update for Lazy Scripts v 1.2.0
> Update for Lazy Scripts v 1.2.0

- extensions/sql-migration/package.json
- src/sql/platform/extensions/common/extensions.ts
- src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts
- src/sql/workbench/contrib/dashboard/browser/core/dashboardTab.contribution.ts
- src/sql/workbench/contrib/dashboard/browser/core/dashboardWidget.ts
- src/sql/workbench/services/dashboard/browser/common/interfaces.ts
> Adding flag to hide refresh button in dashboards.

- extensions/mssql/config.json
- src/sql/base/browser/ui/editableDropdown/browser/dropdown.ts
- src/sql/base/browser/ui/editableDropdown/browser/media/dropdownList.css
- src/sql/base/browser/ui/table/tableCellEditorFactory.ts
- src/sql/workbench/services/tableDesigner/browser/tableDesignerMetadata.ts
1. handle when metadata is not available
2. editable dropdown doesn't fit perfectly into the grid cell
before:
after:
3. when tab key is pressed inside editable dropdown, the focus will move out of the 
before:
after:
4. move focus from editable dropdown directly to somewhere outside of the grid will not trigger the commit action
before:
after:
sts changes are all table designer related
> fix table designer issues

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220410153816807 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220410153816807 to main

- resources/xlf/en/sql.xlf
> [Loc] added hiderefreshtask string

- extensions/sql-database-projects/package.json
This PR fixes #19001. We still need some more time to finalize including system dacpacs in the Microsoft.Build.Sql SDK, so hiding in this release.
> [Port] hide convert to sdk-style from project context menu (#19002)

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- yarn.lock
This PR updates the azdataGraph package version from 0.0.19 to 0.0.20
This update truncates long vertex labels, so they don't overlap with other labels
> Updates azdataGraph package version to 0.0.20

- extensions/sql-bindings/src/services/azureFunctionsService.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/18932.
This PR in main: https://github.com/microsoft/azuredatastudio/pull/18962.
> [PORT] suppress create function prompt (#18962)

- extensionsGallery-insider.json
Push in changes for April release.
> Update insiders gallery with April Langpacks

- extensions/mssql/config.json
#19006 
#18999 
#18997
#18987
#18985
> bring in fixes for a few table designer issues

- extensions/schema-compare/package.json
> update schema compare version to 1.13.1

- resources/xlf/en/sql-migration.xlf
- resources/xlf/en/sql.xlf
> [Loc] added updated strings for sql-migration

- extensions/mssql/config.json
original PR: #19020
This PR fixes #19006 
This PR fixes #18999 
This PR fixes #18997
This PR fixes #18987
This PR fixes #18985
> port table designer fixes

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- yarn.lock
This PR fixes #18818, which is an issue around node labels in query execution plans overlapping with other node labels. As mentioned in this comment: https://github.com/microsoft/azuredatastudio/issues/18818#issuecomment-1092168829
The merged PR that resolved this in the main branch is found here: https://github.com/microsoft/azuredatastudio/pull/19009
> Updates azdataGraph package version to 0.0.20 (#19009)

- extensions/schema-compare/package.json
> [Port] update schema compare version to 1.13.1 (#19026)

- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
- fix bug in sql-migration extension to use new cancel/cutover put api format
- fix start migration telemetry bug
- removed duplicate IR nodes copy
> bug - use new cancel/cutover api format

- test/automation/src/sql/managePackagesDialog.ts
- test/automation/src/sql/notebook.ts
- test/automation/src/workbench.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
This smoke test installs the pyarrow pip package through the Manage Packages wizard.
> Add smoke test for manage packages wizard

- extensions/sql-database-projects/images/azure.svg
> Updating Azure svg for Database Projects 

- extensions/sql-database-projects/images/azure.svg
> [Port] update Azure svg to current logo (#19034)

- extensions/mssql/config.json
> vbump sts to bring in a fix for table designer

- extensions/mssql/config.json
This PR fixes #19035
original PR: https://github.com/microsoft/azuredatastudio/pull/19053
> port fix for #19035

- extensionsGallery-insider.json
This PR adds SQL Bindings extension to the insider gallery (sql-database-projects is updated in insiders as well).
Build for VSIX (using RC1 build):
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=149954&view=artifacts&pathAsName=false&type=publishedArtifacts
> Add SQL Bindings Extension to insiders gallery

- extensions/sql-database-projects/src/tools/shellExecutionHelper.ts
Linking the issue https://github.com/microsoft/azuredatastudio/issues/19065. Will close only after port.
> Fix for sensitive text in output message

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220414154555496 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220414154555496 to main

- extensions/sql-database-projects/src/tools/shellExecutionHelper.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/19065
> Fix for sensitive text in output message (#19071)

- test/smoke/src/sql/areas/notebook/notebook.test.ts
> Temporarily skip manage packages test

- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
This PR fixes #18274 and fixes #19067
> [Port Request] Fix cell nav (#19082)

- product.json
- src/sql/workbench/services/notebook/browser/models/cell.ts
This PR ports the following commits to release:
https://github.com/microsoft/azuredatastudio/commit/8bd5ea5c84f78541fbb625846c3b667ff9840901
https://github.com/microsoft/azuredatastudio/commit/8747ac5c52e10a64bd383b79b229f4eee8ed40ce
These are the tracking issues for those two fixes:
https://github.com/microsoft/azuredatastudio/issues/18980
https://github.com/microsoft/azuredatastudio/issues/19066
> Port cell hover fix and new Interactive extension metadata additions to release branch.

- src/sql/workbench/contrib/executionPlan/browser/executionPlanView.ts
This PR fixes #19084 
The PR to the main branch #19086
> Fixing broken tooltip toggle label in release

- src/sql/workbench/contrib/executionPlan/browser/executionPlanFileView.ts
- src/sql/workbench/contrib/executionPlan/browser/executionPlanTab.ts
This PR fixes #19046
PR to the main branch #19057
>  Fix for broken query plan caching in release

- extensionsGallery.json
Updating 4 extensions:
- dacpac
- schema compare
- sql database projects
- sql bindings
Build with extensions: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=150079&view=results
> Update RC extensions gallery with dacpac, schema compare, sql projects, and sql bindings

- extensions/sql-bindings/src/services/azureFunctionsService.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/19105
PR in main: https://github.com/microsoft/azuredatastudio/commit/e1cf51653e3aea9dbe59d9156b1d14660c70e784
> [PORT] remove extra error message

- extensionsGallery-insider.json
This PR removes the SQL Bindings extension as it will be only published in VSCode Marketplace.
> Remove sql bindings from insiders gallery

- extensionsGallery.json
This PR removes the SQL Bindings extension as it will be only published in VSCode Marketplace.
> Remove sqlbindings from RC gallery

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220415154237106 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220415154237106 to main

- src/sql/base/browser/ui/colorbox/colorbox.ts
- src/sql/workbench/services/serverGroup/browser/serverGroupDialog.ts
> add title for color box

- resources/localization/LCL/de/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220416160637768 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220416160637768 to main

- CHANGELOG.md
- README.md
> Updating readme and change log to reflect major changes in 1.36

- resources/xlf/en/sql-bindings.xlf
- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql.xlf
> [Loc] added xlf updates for 4-18-2022

- resources/xlf/en/arc.xlf
- resources/xlf/en/azcli.xlf
> [Loc] update to arc and azcli xlfs

- src/sql/workbench/browser/editor/tableDesigner/tableDesignerInput.ts
- src/sql/workbench/services/tableDesigner/browser/tableDesignerService.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/19080
Updated screenshot-
> Add confirmation dialog before closing app

- extensionsGallery.json
> Merging from extensions/RC1 for release!

- src/sql/workbench/services/tableDesigner/browser/tableDesignerService.ts
shorten code from https://github.com/microsoft/azuredatastudio/pull/19139#discussion_r853522892
> Change style

- extensions/arc/src/localizedConstants.ts
- extensions/arc/src/ui/dashboards/controller/controllerUpgrades.ts
- extensions/azcli/src/az.ts
- Log upgrade errors/debug outputs to console instead of blocking the upgrade
- Removed extraneous link in dashboard toolbar
- Changed text in dashboard to be:
> Bug fixes for DC upgrade in arc extension

- CHANGELOG.md
Update changelog for 1.36.1 hotfix release.
> Update changelog for 1.36.1 hotfix

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/workbench/contrib/executionPlan/browser/azdataGraphView.ts
- yarn.lock
> Fixing badge positions when the execution plan is zoomed

- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
- extensions/sql-database-projects/src/test/dialogs/createProjectFromDatabaseDialog.test.ts
This PR fixes #19063.
Automatically connect if possible:
Open connection dialog if can't automatically connect (updated from first iteration to open connection dialog first, before opening create project from db dialog):
> Fix create project from db not loading dbs when disconnected

- package.json
> updating to v1.37.0 now that 1.36 is published

- src/sql/workbench/contrib/query/browser/gridPanel.ts
the accessibility testing has been done and all issues were addressed. we can remove the preview feature flag for this feature now.
> remove the preview feature flag check for query result grid filter/sort feature

- extensions/admin-tool-ext-win/src/main.ts
- extensions/admin-tool-ext-win/src/test/extension.test.ts
- extensions/admin-tool-ext-win/src/test/stubs.ts
- extensions/admin-tool-ext-win/src/test/utils.test.ts
- extensions/admin-tool-ext-win/src/utils.ts
- extensions/agent/tsconfig.json
- extensions/azurecore/tsconfig.json
- extensions/big-data-cluster/tsconfig.json
- extensions/cms/tsconfig.json
- extensions/dacpac/tsconfig.json
- extensions/import/tsconfig.json
- extensions/integration-tests/tsconfig.json
- extensions/liveshare/tsconfig.json
- extensions/mssql/tsconfig.json
- extensions/notebook/tsconfig.json
- extensions/schema-compare/tsconfig.json
- extensions/tsconfig.base.json
https://www.typescriptlang.org/tsconfig#strictNullChecks
Having this enabled helps prevent issues such as what happened in https://github.com/microsoft/azuredatastudio/pull/19192
Disabled for extensions which have too many errors for me to fix right now, but this will ensure we have it for some of them and new extensions going forward.
> Enable strictNullChecks for extensions by default

- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220424210020361 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220424210020361 to main

- resources/localization/LCL/de/arc.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/arc.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220425154518725 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220425154518725 to main

- extensions/sql-database-projects/src/common/telemetry.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
Adding this after realizing in a meeting today that we didn't know the usage of this
> send telemetry for generate project from OpenApi spec

- extensions/dacpac/package.json
- extensions/schema-compare/package.json
- extensions/sql-database-projects/package.json
Updating extension versions for dacpac, schema compare, and sql database projects after the April release
> update versions of data developer extensions

- resources/xlf/en/sql-bindings.xlf
> [Loc] update to sql bindings xlf

- extensions/mssql/config.json
Getting in updated SMO + SqlClient and the autoflush fix
> Bump STS to .243

- resources/xlf/en/sql-bindings.xlf
> [loc] added connectionProgressTitle

- extensions/sql-bindings/src/services/azureFunctionsService.ts
This PR addresses logic that was supposed to be removed in #19211. I'm not sure how this commit didn't go in but it is possible due to the merging main that I had to do. 
This is the duplicated logic that was changed with the PR above and is already asked to the user.
> Remove additional logic from sql bindings

- resources/xlf/en/sql-database-projects.xlf
> [Loc] added strings for sql-database-projects

- test/smoke/src/sql/areas/notebook/notebook.test.ts
Tracking the issue here
https://github.com/microsoft/azuredatastudio/issues/19256
> Skip key nav smoke test

- extensionsGallery-insider.json
This PR updates the version of sql-migration in insiders to v1.0.1.
Link to build: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=152647&view=artifacts&pathAsName=false&type=publishedArtifacts
> Update sql-migration in insiders to v1.0.1

- resources/xlf/en/sql-migration.xlf
> [Loc] Sql-migration xlf update for 5-3-2022

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220504193140518 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220504193140518 to main

- resources/xlf/en/sql.xlf
> [Loc] Sql xlf update for 5-3-2022 (add untitledNotSupported)

- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql-migration.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220506153723565 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220506153723565 to main

- src/sql/workbench/contrib/executionPlan/browser/executionPlanView.ts
This PR fixes #18286
For the hot key to work, this PR must also be merged: https://github.com/microsoft/azuredatastudio/pull/19294 since the logic to focus on the execution plan container is needed.
> Adds hot key combination for finding nodes in execution plans.

- extensionsGallery-insider.json
- extensionsGallery.json
This PR update the version of "ExtraSqlScriptAs" extension to the last version (0.5.0)
> Updated "ExtraSqlScriptAs" extension to 0.5.0

- resources/localization/LCL/de/sql-migration.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql-migration.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql-migration.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql-migration.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql-migration.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql-migration.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220507215231328 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220507215231328 to main

- resources/xlf/en/mssql.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to mssql and sql xlfs

- extensions/sql-bindings/package.json
Fixed the versioning to use a minor version instead of patch versioning. 
https://semver.org/
> vBump sql bindings extension

- extensions/arc/package.json
- extensions/arc/src/models/miaaModel.ts
- extensions/arc/src/ui/dashboards/miaa/miaaBackupsPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaConnectionStringsPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaUpgradeManagementPage.ts
- extensions/arc/src/ui/dialogs/configureRPOSqlDialog.ts
- extensions/arc/src/ui/dialogs/restoreSqlDialog.ts
- extensions/azcli/package.json
- extensions/azcli/src/typings/az-ext.d.ts
SqlMiShowResult interface was out-of-date. Updated it to the latest, so that backup & restore and SQL MIAA upgrade work again.
> Fixed SqlMiShowResult to be up to date

- extensions/mssql/config.json
Fixes https://github.com/microsoft/azuredatastudio/issues/19229
Also included (of my changes) : 
- Improved OE verbose logging
- Don't query for unsupported server properties
> Bump STS to .247

- extensionsGallery.json
This PR updates the version of sql-migration in the public gallery to v1.0.1.
The vsix was already published and released to the insiders gallery last week as part of https://github.com/microsoft/azuredatastudio/pull/19275.
> Update public gallery with sql-migration v1.0.1

- resources/localization/LCL/de/mssql.xlf.lcl
- resources/localization/LCL/es/mssql.xlf.lcl
- resources/localization/LCL/fr/mssql.xlf.lcl
- resources/localization/LCL/ko/mssql.xlf.lcl
- resources/localization/LCL/pt-BR/mssql.xlf.lcl
- resources/localization/LCL/zh-Hans/mssql.xlf.lcl
- resources/localization/LCL/zh-Hant/mssql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220511162822170 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220511162822170 to main

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
- extensions/sql-bindings/src/common/constants.ts
- extensions/sql-bindings/src/extension.ts
- extensions/sql-bindings/src/sql-bindings.d.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/19325
> Show function name when prompting user for sql binding type

- extensions/mssql/config.json
Fixes https://github.com/microsoft/azuredatastudio/issues/19335
I'm working with the SMO people to figure out the issue and will bring back the SMO bump once that's resolved.
> Bump STS to .249

- resources/xlf/en/sql-bindings.xlf
- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to xlfs 5-11-2022

- extensions/sql-database-projects/src/controllers/projectController.ts
send which docker image was selected for publish to container
> add docker image with telemetry for publish to container

- resources/localization/LCL/de/arc.xlf.lcl
- resources/localization/LCL/es/arc.xlf.lcl
- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/it/mssql.xlf.lcl
- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ja/mssql.xlf.lcl
- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/ru/mssql.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220512213846450 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220512213846450 to main

- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220513163417979 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220513163417979 to main

- extensions/mssql/config.json
- extensions/mssql/src/features.ts
Adds token refresh logic for intellisense: https://github.com/microsoft/sqltoolsservice/pull/1476
Fixes https://github.com/microsoft/azuredatastudio/issues/17179
Also fixes a typo when checking for an account
> Bump STS to .251

- extensions/sql-bindings/src/services/azureFunctionsService.ts
> Exit infite loop after closing error message

- extensions/sql-bindings/package.nls.json
- extensions/sql-bindings/src/common/constants.ts
This PR fixes #19337 and fixes #19347.
Removed constants that are not used and re-organized the file into constants, localized constants, and functions section
> SQL Bindings fix preview flag and constants file

- resources/xlf/en/mssql.xlf
- resources/xlf/en/sql-bindings.xlf
- resources/xlf/en/sql.xlf
> [Loc] String updates for 5/13/2022

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/arc.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/arc.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220515160818916 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220515160818916 to main

- extensionsGallery-insider.json
Add extension Database Migration Assessment for Oracle v1.2.1 for insiders build.
Update for Database Migration Assessment -
Version 1.2.1 - 2022-05-16 
Added
- Enhanced telemetry to include custom events.
- Ability to change command & query timeout configs through config file.
Fixed
- UI Bugs
- Fix for text getting overlapped in constraint window for feature compatibility tab
- Added tooltip on feature compatibility tab
- Floating box for comments added in feature compatibility tab
- Some styling changes
- Comments string update on feature compatibility
> Adding extension Database Migration Assessment for Oracle v1.2.1 

- resources/localization/LCL/de/arc.xlf.lcl
- resources/localization/LCL/de/mssql.xlf.lcl
- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/mssql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/fr/mssql.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/mssql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/mssql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/mssql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/ru/mssql.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/mssql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220516162608119 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220516162608119 to main

- extensions/arc/src/models/miaaModel.ts
- extensions/arc/src/ui/dashboards/miaa/miaaBackupsPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaConnectionStringsPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaUpgradeManagementPage.ts
- extensions/arc/src/ui/dialogs/configureRPOSqlDialog.ts
- extensions/azcli/src/az.ts
- extensions/azcli/src/typings/az-ext.d.ts
The output of 'az sql mi-arc show' has a different shape for indirect vs. direct mode. Right now, we only cover direct mode shape. This PR takes the output of **either** the direct mode shape or the indirect mode shape, and combines it into one "normalized" shape called SqlMiShowResult.
> Fixed az sql mi-arc show for indirect scenario

- extensions/azcli/src/az.ts
Fixes bug in unit test:
After fix:
> Added optional metadata to fix bug

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/providerSettings.ts
- extensions/azurecore/src/azurecore.d.ts
- src/sql/azdata.d.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/18845 for the PBI case.  Still need to update connection service to lookup endpoint over TDS to solve more generally.
> Fix connection issue with wrong resource endpoint

- extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts
Added DC status so user can see if it is Ready or Upgrading.
> Added DC Status to DC Dashboard

- extensions/sql-migration/package.json
- extensions/sql-migration/src/api/azure.ts
* update code to use latest DMS V2 API
* update code to use new listMonitoringData post API.
* bump extension version to 1.0.0
* update ADS dependency to >=1.37.0
> update DMSV2 API and listMonitoringData to latest

- resources/xlf/en/sql.xlf
> [Loc] Added changes to sql.xlf

- src/sql/workbench/contrib/executionPlan/browser/images/icons/badge_parallelism.svg
https://github.com/microsoft/azuredatastudio/issues/19390
After:
Now:
> Adding the mirrored parallelism icon

- .github/label-actions.yml
Ask users to enable the "all" logging level for MSSQL so we get the full set of logging from STS.
> Add verbosity update to need logs request

- resources/localization/LCL/ja/mssql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/mssql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220517162754481 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220517162754481 to main

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
PR fixes https://github.com/microsoft/azuredatastudio/issues/19348
We weren't quoting the path so any paths with spaces in them weren't working
> Quote paths in add package command

- extensionsGallery-insider.json
- extensionsGallery.json
Changing version of extension in extension-gallery to release v1.2.1
> Releasing v1.2.1 for Database Migration Assessment for Oracle extension.

- extensions/arc/package.json
- extensions/azcli/package.json
Bump version of arc and azcli to 1.3.0 in the package.json for BC GA
> Bump version of arc and azcli to 1.3.0

- extensions/sql-bindings/src/test/testUtils.ts
- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/common/httpClient.ts
- extensions/sql-database-projects/src/common/telemetry.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseQuickpick.ts
- extensions/sql-database-projects/src/dialogs/deployDatabaseQuickpick.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
- extensions/sql-database-projects/src/dialogs/utils.ts
- extensions/sql-database-projects/src/models/deploy/azureSqlClient.ts
- extensions/sql-database-projects/src/models/deploy/deployProfile.ts
- extensions/sql-database-projects/src/models/deploy/deployService.ts
- extensions/sql-database-projects/src/test/deploy/azureSqlClient.test.ts
- extensions/sql-database-projects/src/test/deploy/deployService.test.ts
- extensions/sql-database-projects/src/test/dialogs/publishDatabaseDialog.test.ts
- extensions/sql-database-projects/src/test/utils.test.ts
- extensions/sql-database-projects/yarn.lock
- extensions/types/vscode-mssql.d.ts
Ports changes for local docker deploy to release branch for //Build release.  The hotfix version of these changes should _only_ be released for VSCode, and are not intended for an out-of-band ADS release.
Issue: #19421
Original PRs:
* #19100
* #18833
* #19297
* #19360
> [Port] //Build features for VSCode database projects extension release only

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/providerSettings.ts
- extensions/azurecore/src/azurecore.d.ts
- src/sql/azdata.d.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
* Fix connection bug accessing PBI resource
* Address CR feedback
* Fix null check
> Fix connection issue with wrong resource endpoint (#19387)

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/workbench/contrib/executionPlan/browser/azdataGraphView.ts
- yarn.lock
> Fixing badge zooming in april hotfix2

- src/sql/workbench/contrib/executionPlan/browser/images/icons/badge_parallelism.svg
Port Adding the mirrored parallelism icon (#19391)
> Adding the mirrored parallelism icon (#19391)

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220519161154386 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220519161154386 to main

- extensions/sql-bindings/src/extension.ts
- extensions/sql-bindings/src/sql-bindings.d.ts
Making this usable by other extensions
> Add createAzureFunction to extension API

- extensionsGallery-insider.json
This adds the [Azure CosmosDB extension](https://github.com/Azure/azure-cosmosdb-ads-extension) to the Insider build catalog.
> Add CosmosDB extension to Insider catalog

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
- extensions/sql-database-projects/src/sqldbproj.d.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
Let caller specify the default name, falling back to the current default based on the item type if not provided.
> Add default name to promptAddItem

- extensions/sql-database-projects/resources/projectAssets/AzureV12/README.MD
> SQL Project : Fixed the formatting issues in SQL project readme file

- resources/xlf/en/arc.xlf
- resources/xlf/en/azurecore.xlf
- resources/xlf/en/sql-bindings.xlf
> [Loc] update to arc, azurecore, and sql-bindings.

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220520162113836 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220520162113836 to main

- extensions/mssql/config.json
Commits from last bump
https://github.com/microsoft/sqltoolsservice/compare/v3.0.0-release.251...4.0.0.1
> Updating sts to get some execution plan changes 

- extensionsGallery-insider.json
link to build:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=155089&view=results
link to artifacts:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=155089&view=artifacts&pathAsName=false&type=publishedArtifacts
> updating sql-migration version to 1.0.2 for insiders

- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
> SQL Project: Adding firewall rule prompt when publishing to existing server

- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/ja/azurecore.xlf.lcl
- resources/localization/LCL/ko/arc.xlf.lcl
- resources/localization/LCL/ko/azurecore.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/ru/azurecore.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/azurecore.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220522162500906 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220522162500906 to main

- resources/xlf/en/sql.xlf
> [Loc] xlf update for 5-23-2022

- extensions/sql-bindings/README.md
This PR fixes the links shown in the SQL Bindings extension when installed:
> Fix SQL Bindings README

- extensionsGallery.json
link to build:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=155089&view=results
link to artifacts:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=155089&view=artifacts&pathAsName=false&type=publishedArtifacts
> updating sql-migration version to 1.0.2 in public gallery

- scripts/validateGalleries.js
Changing path param name so it doesn't conflict with path module
Also making some constants for a couple values
> Script cleanup

- extensionsGallery-insider.json
- extensionsGallery.json
link to build:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=155570&view=results
link to artifacts:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=155570&view=artifacts&pathAsName=false&type=publishedArtifacts
> updating sql-migration version to 1.0.3 in insiders then prod galleries

- extensions/notebook/yarn.lock
- package.json
- yarn.lock
> Updating tar across ads

- src/sql/workbench/contrib/executionPlan/browser/media/executionPlan.css
This PR scopes down css that's causing weird issues in table designer.
> Scoping down execution plan css 

- package.json
- yarn.lock
> Reverting gulp-untar resolution

- CHANGELOG.md
Update the changelog to include notes for the two April hotfixes.
> Update changelog for April hotfixes

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220526161321984 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220526161321984 to main

- yarn.lock
> updating normalize-url

- yarn.lock
> Updating set-value

- yarn.lock
> Small yarn lock update

- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220527162216325 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220527162216325 to main

- resources/xlf/en/data-workspace.xlf
- resources/xlf/en/notebook.xlf
> [Loc] update to data-workspace and notebook

- resources/localization/LCL/de/data-workspace.xlf.lcl
- resources/localization/LCL/de/notebook.xlf.lcl
- resources/localization/LCL/es/data-workspace.xlf.lcl
- resources/localization/LCL/es/notebook.xlf.lcl
- resources/localization/LCL/fr/data-workspace.xlf.lcl
- resources/localization/LCL/fr/notebook.xlf.lcl
- resources/localization/LCL/it/data-workspace.xlf.lcl
- resources/localization/LCL/it/notebook.xlf.lcl
- resources/localization/LCL/ja/data-workspace.xlf.lcl
- resources/localization/LCL/ja/notebook.xlf.lcl
- resources/localization/LCL/pt-BR/data-workspace.xlf.lcl
- resources/localization/LCL/pt-BR/notebook.xlf.lcl
- resources/localization/LCL/ru/data-workspace.xlf.lcl
- resources/localization/LCL/ru/notebook.xlf.lcl
- resources/localization/LCL/zh-Hans/data-workspace.xlf.lcl
- resources/localization/LCL/zh-Hans/notebook.xlf.lcl
- resources/localization/LCL/zh-Hant/data-workspace.xlf.lcl
- resources/localization/LCL/zh-Hant/notebook.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220530163305847 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220530163305847 to main

- resources/localization/LCL/ko/data-workspace.xlf.lcl
- resources/localization/LCL/ko/notebook.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220531162517469 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220531162517469 to main

- src/sql/workbench/services/connection/browser/connectionWidget.ts
> make sure controls are enabled when needed

- extensionsGallery-insider.json
This PR updates azure-cosmosdb-ads-extension to 0.1.1.
See [changelogs](https://github.com/Azure/azure-cosmosdb-ads-extension/blob/main/CHANGELOG.md)
> Update azure-cosmosdb-ads-extension to 0.1.1 in extensionsGallery-insider.json

- resources/xlf/en/mssql.xlf
- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to xlfs for 6-2-2022

- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/contrib/executionPlan/browser/executionPlanComparisonEditorView.ts
- src/sql/workbench/contrib/executionPlan/browser/executionPlanView.ts
This PR adds telemetry to execution plans. Specific examples include how plans are invoked, when the execution plan button is used, and when the plan comparison properties button is used.
> Execution Plan Telemetry for Plan Comparisons

- extensions/sql-database-projects/package.json
Updating the azdata dependency for sql database projects because of the added support for table designer
> update sql database projects azdata dependency to 1.37.0

- extensions/mssql/config.json
https://github.com/microsoft/sqltoolsservice/compare/4.0.0.9...4.0.0.10
> Updating sqltoolsservice

- resources/xlf/en/sql.xlf
> [Loc] update to sql xlf

- extensions/mssql/config.json
Commits from STS being brought in with this change:
> update STS version to get DacFx fixes for update project and table designer

- extensions/sql-bindings/package.json
This PR bumps SQL Bindings for June Release.
Will create a Port Request for release branch as well.
> vbump SQL Bindings for June Release

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/models/publishProfile/publishProfile.ts
- extensions/sql-database-projects/yarn.lock
Fixes dependabot issue. 
The xmldom package is no longer being updated - see https://github.com/xmldom/xmldom/issues/271
The new package includes the typings in it so no need to pull those separately.
> Update xmldom to 0.8.2

- resources/xlf/en/sql-database-projects.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to xlfs for 6-6-2022

- extensions/sql-bindings/package.json
- extensions/sql-bindings/package.vscode.json
This PR fixes issues found in https://github.com/microsoft/azuredatastudio/pull/19645.
> Fix SQL Bindings VSCode telemetry issues

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
- extensions/sql-bindings/src/extension.ts
- extensions/sql-bindings/src/sql-bindings.d.ts
Include the addNugetReferenceToProjectFile method in the sql bindings api
> Extend sql bindings api

- extensionsGallery-insider.json
> update azdata requirement for cosmosdb extension

- extensions/sql-bindings/package.json
PR in main: https://github.com/microsoft/azuredatastudio/pull/19639
> [PORT] vbump SQL Bindings for June Release (#19639)

- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
Porting to release branch. Tracking issue: https://github.com/microsoft/azuredatastudio/issues/19668
> Add new cells after the current one when adding a cell from the notebook toolbar. (#19649)

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/common/utils.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/19646. Porting this change from main: https://github.com/microsoft/azuredatastudio/pull/19645
> [Port] Fix sql database projects vscode telemetry (#19645)

- extensions/sql-database-projects/src/controllers/mainController.ts
This PR fixes #19666. Porting this fix from main https://github.com/microsoft/azuredatastudio/pull/19667
> [Port] fix table designer error when sql project has folders (#19667)

- src/sql/base/browser/ui/table/table.ts
> Fixing edit data execution in release. 

- extensionsGallery-insider.json
- extensionsGallery.json
Pull request to release ```ADS (Database Migration Assistance for Oracle)``` version ```1.3.1``` for ```Azure Data Studio Insider``` and ```Azure Data Studio```
> updated version for new release v1.3.1

- extensionsGallery.json
Adds in the most recent langpacks for the June release to the RC branch.
Vsixes can be found here: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=157976&view=artifacts&pathAsName=false&type=publishedArtifacts
> langpack updates for June 2022

- src/sql/workbench/services/notebook/browser/models/notebookUtils.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/19554
PR in main: https://github.com/microsoft/azuredatastudio/pull/19678
> [Port] Fix notebook saving issue with Jupyter extension

- extensions/sql-database-projects/src/controllers/projectController.ts
> SQL Project - Fixing the telemetry property docker image name

- extensionsGallery-insider.json
Langpacks already added in RC1 branch
> Update to insiders gallery for June langpack release

- extensions/sql-database-projects/src/controllers/projectController.ts
Porting a fix in SQL Project telemetry https://github.com/microsoft/azuredatastudio/pull/19685
This PR fixes #19683
> Fixing the telemetry property docker image name (#19685)

- package.json
version bumping since we have forked the current release as per disccusion with Alan
> Version Bumping main to 1.38

- resources/xlf/en/sql-migration.xlf
> [Loc] removed one string for sql-migration

- resources/localization/LCL/de/mssql.xlf.lcl
- resources/localization/LCL/de/sql-database-projects.xlf.lcl
- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/mssql.xlf.lcl
- resources/localization/LCL/es/sql-database-projects.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/mssql.xlf.lcl
- resources/localization/LCL/fr/sql-database-projects.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/mssql.xlf.lcl
- resources/localization/LCL/it/sql-database-projects.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/mssql.xlf.lcl
- resources/localization/LCL/ja/sql-database-projects.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/mssql.xlf.lcl
- resources/localization/LCL/ko/sql-database-projects.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/mssql.xlf.lcl
- resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/mssql.xlf.lcl
- resources/localization/LCL/ru/sql-database-projects.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/mssql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/mssql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220609154331010 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220609154331010 to main

- extensionsGallery.json
Updating sql database projects to 0.17.1 and schema compare to 1.14.0
Build with vsixs: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=158067&view=artifacts&pathAsName=false&type=publishedArtifacts
> update sql database projects and schema compare in RC gallery

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/workbench/contrib/executionPlan/browser/executionPlanViewHeader.ts
- src/sql/workbench/contrib/executionPlan/browser/media/executionPlan.css
- yarn.lock
> Fixing graph root padding and truncating long queries in execution plan

- extensionsGallery-insider.json
- extensionsGallery.json
- scripts/validateGalleries.js
Validate that the preview flag matches on the extension gallery and package.json.
I will be reaching out to extension owners as appropriate to determine if the preview flag is accurate, some of them may still be technically in preview and so will need to have their package.json updated.
> Validate preview flag

- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220611154022072 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220611154022072 to main

- extensions/mssql/config.json
- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/tree/projectTreeItem.ts
- extensions/sql-database-projects/src/test/projectTree.test.ts
- i18n/ads-language-pack-de/package.json
- i18n/ads-language-pack-es/package.json
- i18n/ads-language-pack-fr/package.json
- i18n/ads-language-pack-it/package.json
- i18n/ads-language-pack-ja/package.json
- i18n/ads-language-pack-ko/package.json
- i18n/ads-language-pack-pt-BR/package.json
- i18n/ads-language-pack-ru/package.json
- i18n/ads-language-pack-zh-hans/package.json
- i18n/ads-language-pack-zh-hant/package.json
This reverts commit 3f347823a08e2739dca3c65100f50e7a505c0b0c, reversing
changes made to b4f5816f5d60cbb9b87edc8cc73f1aab0cb04820.
> Revert unintended commit to release/1.34 branch

- extensions/sql-bindings/src/test/addConnectionStringStep.test.ts
- extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts
- extensions/sql-bindings/src/test/dialog/addSqlBindingQuickpick.test.ts
- extensions/sql-bindings/src/test/service/azureFunctionsService.test.ts
This PR cleanup SQL Binding test after discussion in this PR: https://github.com/microsoft/azuredatastudio/pull/19717. 
Ensure we use fluent assertions and include messages/descriptions for each assertions.
> Cleanup some SQL Binding tests

- CHANGELOG.md
- README.md
> updating changelog for 1.37

- extensions/data-workspace/package.json
- extensions/schema-compare/package.json
- extensions/sql-database-projects/package.json
Vbumping the data developer extensions released in June
> vbump data developer extensions after release

- src/sql/base/browser/ui/checkbox/checkbox.ts
- src/sql/base/browser/ui/editableDropdown/browser/dropdown.ts
- src/sql/base/browser/ui/inputBox/inputBox.ts
- src/sql/workbench/browser/designer/designer.ts
- src/vs/base/browser/ui/selectBox/selectBox.ts
- src/vs/base/browser/ui/selectBox/selectBoxCustom.ts
- src/vs/base/browser/ui/selectBox/selectBoxNative.ts
> add aria description

- src/sql/workbench/browser/modelComponents/text.component.ts
> Hiding description tooltip on escape key. 

- build/azure-pipelines/updateGalleries.yml
No need to update the galleries for other changes in the repo
> Only update galleries when gallery files updated

- src/vs/base/browser/ui/selectBox/selectBox.ts
- src/vs/base/browser/ui/selectBox/selectBoxCustom.ts
- src/vs/base/browser/ui/selectBox/selectBoxNative.ts
follow up of this PR: https://github.com/microsoft/azuredatastudio/pull/19739
Cherry-pick the following commits to ADS.
https://github.com/microsoft/vscode/commit/49b05c51f896d1d60ef124bd16bab146eedb91cd
https://github.com/microsoft/vscode/commit/d19ac496df108aba3f48bfe33804d027a8944d68
> port vscode changes

- extensions/arc/package.json
- extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts
Fixed a bug in Dynamic Enablement where use of Dynamic Options would re-set the enabled state.
> Fixed dynamic enablement

- resources/xlf/en/arc.xlf
> [Loc] update to arc.xlf

- src/sql/workbench/contrib/notebook/test/browser/notebookMarkdown.test.ts
- src/sql/workbench/contrib/notebook/test/calloutDialog/linkCalloutDialog.test.ts
Link to sections within the same file were broken after the last vscode merge https://github.com/microsoft/azuredatastudio/issues/18477
> Add tests for anchor links

- resources/localization/LCL/es/arc.xlf.lcl
- resources/localization/LCL/fr/arc.xlf.lcl
- resources/localization/LCL/ja/arc.xlf.lcl
- resources/localization/LCL/pt-BR/arc.xlf.lcl
- resources/localization/LCL/ru/arc.xlf.lcl
- resources/localization/LCL/zh-Hans/arc.xlf.lcl
- resources/localization/LCL/zh-Hant/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220619153425200 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220619153425200 to main

- resources/xlf/en/query-history.xlf
- resources/xlf/en/sql.xlf
> [Loc] Alex update to xlfs

- extensions/sql-migration/package.json
bump sql-migration version to 1.0.4
> sql migration vbump 1.0.4

- test/smoke/src/main.ts
> Removes vscode download for smoke tests

- resources/localization/LCL/de/sql.xlf.lcl
- resources/localization/LCL/es/sql.xlf.lcl
- resources/localization/LCL/fr/sql.xlf.lcl
- resources/localization/LCL/it/sql.xlf.lcl
- resources/localization/LCL/ja/sql.xlf.lcl
- resources/localization/LCL/ko/sql.xlf.lcl
- resources/localization/LCL/pt-BR/sql.xlf.lcl
- resources/localization/LCL/ru/sql.xlf.lcl
- resources/localization/LCL/zh-Hans/sql.xlf.lcl
- resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220623153900323 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220623153900323 to main

- resources/xlf/en/sql-bindings.xlf
> [Loc] update to sql-bindings xlf

- src/sql/workbench/contrib/executionPlan/browser/executionPlanContribution.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
- src/sql/workbench/contrib/query/browser/queryActions.ts
This PR centralizes a category string for execution plan actions.
> Centralizes localized category string for the execution plan category

- resources/xlf/en/sql.xlf
> [Loc] update to sql xlf for 6/28/2022

- extensionsGallery.json
Add extension Database Migration Assessment for Oracle v1.4.1 for Azure Data Studio.
Version 1.4.1 - 2022-06-29
Fixed
Localization bug fixes.
> Varsha/release extension 1.4.1

- resources/xlf/en/arc.xlf
- resources/xlf/en/notebook.xlf
- resources/xlf/en/sql.xlf
> [Loc] update to several extensions xlfs

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/deploy/deployService.ts
- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
- extensions/sql-database-projects/src/sqldbproj.d.ts
- extensions/sql-database-projects/src/test/deploy/deployService.test.ts
Couple more I need to use for the stuff I'm working on. Slight refactoring to move the logic in more separate functions, but no changes to the logic itself.
> Add getDockerImageSpec and cleanDockerObjects to API

- extensions/dacpac/src/test/testDacFxService.ts
- extensions/mssql/config.json
- extensions/mssql/src/contracts.ts
- extensions/mssql/src/dacfx/dacFxService.ts
- extensions/mssql/src/mssql.d.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/dialogs/publishDatabaseDialog.test.ts
- extensions/sql-database-projects/src/test/dialogs/publishOptionsDialog.test.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
- extensions/sql-database-projects/src/test/testContext.ts
- extensions/sql-database-projects/src/test/testUtils.ts
fixed the unstable test case as well as a few test cases that were not reported as failures (noticed some unhandled promise rejections when inspecting the logs) but not executing properly.
original PR: https://github.com/microsoft/azuredatastudio/pull/19897
> resend previous PR with test fixes

- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
- src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR adds telemetry for:
- Text cell toolbar actions
- Text cell keyboard shortcut actions
> Add telemetry for WYSIWYG

- build/lib/stats.ts
- extensions/admin-tool-ext-win/package.json
- extensions/admin-tool-ext-win/yarn.lock
- extensions/dacpac/package.json
- extensions/dacpac/yarn.lock
- extensions/data-workspace/package.json
- extensions/data-workspace/yarn.lock
- extensions/notebook/package.json
- extensions/notebook/yarn.lock
- extensions/resource-deployment/package.json
- extensions/resource-deployment/yarn.lock
- extensions/schema-compare/package.json
- extensions/schema-compare/yarn.lock
- extensions/sql-assessment/package.json
- extensions/sql-assessment/yarn.lock
- extensions/sql-bindings/package.json
- extensions/sql-bindings/yarn.lock
- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/yarn.lock
- extensions/sql-migration/package.json
- extensions/sql-migration/yarn.lock
- src/vs/platform/telemetry/node/appInsightsAppender.ts
- src/vs/workbench/services/telemetry/browser/telemetryService.ts
Port of https://github.com/microsoft/azuredatastudio/pull/19841 for releasing updated versions of extensions
I also updated the versions of the extensions we'll be releasing updates for - I just did a patch bump since this is a minor update with no functionality changes.
> [Port] Update Telemetry endpoints 

- resources/xlf/en/sql-bindings.xlf
> [Loc] sql-bindings xlf update

- resources/xlf/en/sql-assessment.xlf
> [Loc] update to sql-assessment 7/6/2022

- extensionsGallery-insider.json
These are from the 1.37 branch.
Pushing to insiders initially to verify things look good then will plan on updating stable gallery tomorrow.
I'll be updating the VS Code version of the extensions at the same time.
> Update extensions with new telemetry endpoint

- extensions/mssql/config.json
- extensions/sql-database-projects/src/common/utils.ts
> STS version bump

- resources/localization/LCL/de/sql-assessment.xlf.lcl
- resources/localization/LCL/es/sql-assessment.xlf.lcl
- resources/localization/LCL/fr/sql-assessment.xlf.lcl
- resources/localization/LCL/it/sql-assessment.xlf.lcl
- resources/localization/LCL/ja/sql-assessment.xlf.lcl
- resources/localization/LCL/ko/sql-assessment.xlf.lcl
- resources/localization/LCL/pt-BR/sql-assessment.xlf.lcl
- resources/localization/LCL/ru/sql-assessment.xlf.lcl
- resources/localization/LCL/zh-Hans/sql-assessment.xlf.lcl
- resources/localization/LCL/zh-Hant/sql-assessment.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220708153704690 to main with localized lcls
> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220708153704690 to main

- extensions/arc/package.json
- When direct connectivity mode is selected, disable cluster context
- Moved connectivity mode selection to the first question of page 2.
- Moved config profile field to page 2 (deleting page 3)
> DC Create - if direct mode, do not prompt for cluster context
