- src/sql/workbench/browser/modelComponents/queryTextEditor.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/code.css
- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR fixes #14483 & fixes #15943.
This PR addresses the horizontal scrollbar issues users see when they have word wrap off in the split view for markdown cells. Every time the user updates the layout (either from editing the cell, scrolling the terminal window over the cell, or making the ADS smaller in resolution) we have to set the horizontal scrollbar accordingly. The way we can identify whether to set the horizontal to a fixed position is only by comparing the markdown editor space to that of the scrollable space. This required additional offset values as well in order to get a precise comparison. 
https://user-images.githubusercontent.com/23587151/133418762-dfaa6eed-4beb-432a-8a3e-03955f27e06f.mp4
> Markdown Horizontal Scrollbar Fix

- src/sql/workbench/contrib/notebook/browser/notebookViews/notebookViewsCard.component.ts
- src/sql/workbench/contrib/notebook/browser/notebookViews/notebookViewsGrid.component.html
- src/sql/workbench/contrib/notebook/browser/notebookViews/notebookViewsGrid.component.ts
- src/sql/workbench/services/notebook/browser/notebookViews/autodash.ts
Two small fixes:
- Adjust grid row size
- Fix grid restore logic when switching between views
These changes are confined to Notebook Views, and I think pretty straight forward. Please let me know if you would like a deeper explanation of the changes.
Thanks!
> Notebook Views grid fixes

- extensions/data-workspace/package.json
- extensions/data-workspace/package.nls.json
- extensions/data-workspace/src/main.ts
- extensions/data-workspace/src/services/workspaceService.ts
This PR fixes #16986. This adds back remove project which was removed in #15921, but this time the projects excluded from the projects viewlet are specified in the workspace file. When a project is added back using the "Open existing project" dialog, it gets removed from the exclude list.
I also tested this with an untitled workspace and verified that remove project works and also still works after saving the workspace file.
example of removing and adding back a project:
> Add back "Remove Project"

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/dialogs/addSqlBindingQuickpick.ts
This PR fixes #17156. This adds a check for if the file is dirty before starting the add sql bindings quickpick flow.
If cancelled, the add sql binding quickpick doesn't start:
If save is selected, the file is saved before the quickpick starts:
*gifs aren't updated, but the warning string is updated now to `There are unsaved changes in the current file. Save now?`
> Check if file is dirty before adding sql binding

- extensions/sql-migration/src/api/azure.ts
This PR fixes: 
The ADS UI queries all the regions DMS V2 is available and limits the discovered regions to a smaller fixed list. 
- remove list filter logic to allow all available DMS regions to be used.
**Locations results before ->**
**Locations result after ->**
> Remove list filter logic to allow all available DMS regions to be used

- extensions/azuremonitor/config.json
- extensions/azuremonitor/package.json
- extensions/kusto/config.json
- extensions/kusto/package.json
Bumped AzureMonitor and Kusto to use SqlToolsService 133. Bumped extension version for Kusto to 0.5.7 and AzureMonitor to 0.1.8
> Kusto and AzureMonitor version bump

- src/sql/workbench/common/editor/profiler/profilerState.ts
Makes the Profiler Panel expanded by default instead of collapsed.
This PR fixes #17183
> set panel collapsed to false by default

- extensionsGallery-insider.json
Bumped Kusto to 0.5.7 and AzureMonitor to 0.1.8 in extensionsGallery-insiders
> Insiders - Kusto and AzureMonitor version bump

- extensions/schema-compare/src/schemaCompareMainWindow.ts
Fixes the error not getting shown as reported in https://github.com/microsoft/azuredatastudio/issues/17077 and https://github.com/microsoft/azuredatastudio/issues/15330. This wasn't a problem before because the schema compare result success was almost never false, even when it should have been if there was an error during the schema compare.
Now that the correct result is getting passed back with the change in https://github.com/microsoft/sqltoolsservice/pull/1250, this exposes this problem that if the schema compare result was not valid, the error message would show, but the loading spinner and wait text wouldn't be removed. Expected behavior is that the schema compare window should get reset so a new comparison can be made.
old:
fixed:
> Reset schema compare window when comparison result is not success

- src/sql/workbench/services/query/common/gridDataProvider.ts
Replaces the empty string with a space when copying a newline character, to follow with other applications
This PR fixes #15220
> Replace empty string with space

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
This PR fixes #17199. `validateWorkspace()` was getting called twice - once during the dialog validation and then again in the callback. Since the new project and open project dialogs have this validation in the dialog validation, I kept that one and removed the callback one.
Also reordered the validation checks to fix the same problem fixed in #16141 for the new and open project dialogs.
> Fix warning showing twice for create project from db dialog

- src/sql/azdata.proposed.d.ts
- src/sql/workbench/contrib/connection/browser/connection.contribution.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
This PR fixes #16856
the interface that I am modifying is for the object passed back to ADS core by the connection provider, adding a flag so that the connection can tell us whether the target server is unsupported.
the logic of determining whether a SQL Server is supported needs to be added in STS, I will have a separate PR.
> add unsupported version warning

- product.json
This PR fixes #9163.  So the license link in the product opens the raw license text file rather than Github page with repo header, etc.
> Update license path to refer to raw text file

- extensionsGallery-insider.json
- extensionsGallery.json
This is the supporting extension, on which all other extensions that we build will depend. The extension by itself does not add any functionality to ADS and merely allows other extensions to use .NET Core runtime without requiring user to install it manually.
> Add .NET Core 3.1 Runtime extension to the marketplace.

- extensions/sql-database-projects/package.json
- src/tsconfig.base.json
I finally decided to dig into why we kept needing to do these weird casts in the vs code when merging in their changes. It's because we have `strictNullChecks` set to false - without this the compiler isn't able to do a lot of the type narrowing and other features that it can with that enabled and so it just errors out instead.
Unfortunately enabling that is a large task (as Anthony found out when he tried starting it a while back...) and so I at least decided to document here why we have these values disabled in case other people have the same questions.
During this I did some other cleanup in the tsconfig.base.json : 
`noImplicitThis` `alwaysStrict` `strictBindCallApply` - These are already set to true by `strict` being set to true per https://www.typescriptlang.org/tsconfig#strict so …
> Clean up tsconfig.base.json

- src/sql/platform/connection/common/connectionProfile.ts
- src/sql/platform/connection/test/node/connectionStatusManager.test.ts
This PR fixes https://github.com/microsoft/azuredatastudio-postgresql/issues/113
there are 2 bugs behind this issue:
1. one needs to be made in PG extension, @nasc17 as we chatted offline, please add 'isIdentity= true' to the port option in your package.json, this will make ADS be able to treat them as different connections.
2. Object explorer is not using the actual unique string of connections to compare instead it is using the hardcoded options when looking for existing profiles, I am fixing this problem with this PR.
btw, MSSQL do not have the same issue because we are hardcoding it in ADS core to append the port number after the server name.
> use the actual unique id to compare connection

- extensions/sql-database-projects/src/dialogs/addSqlBindingQuickpick.ts
This PR fixes #17248. This is how it looks now with a placeholder:
> use placeholder for table name in add sql bindings quickpick

- extensions/sql-database-projects/package.json
This PR fixes #https://github.com/microsoft/azuredatastudio/issues/17255. I added the "MS SQL" category to the "Add SQL Binding" command so it's like the commands contributed by the MSSQL extension, but we can change it to something else if another category makes more sense. This command only shows in the command palette when the current file is a C# file.
> add category for Add Sql Binding command

- azure-pipelines.yml
Cory noticed this while looking at something else, this was brought in by a VS Code merge a while back. It doesn't really do much since we define our own triggers in ADO anyways (and apparently doesn't cause the parsing to fail) but there's no need for this to be here.
> Remove duplicate pipeline trigger

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/tools/packageHelper.ts
This PR fixes #https://github.com/microsoft/azuredatastudio/issues/17253.  If there's only one AF project in the workspace, the package reference gets added automatically, but this warning shows if there are multiple AF projects. This adds a link to the readme of the SQL bindings repo.
> Add link to sql bindings repo

- extensions/notebook/src/common/logger.ts
- extensions/notebook/src/extension.ts
- extensions/notebook/src/jupyter/jupyterSessionManager.ts
Add some basic logging to help debug issue with spark BDC connections a customer is having.
I added the logger instead of passing in the appcontext because I think that's a much better pattern to use overall, easier to access and will let us add stuff like outputting to different sources, logging levels, etc. later on. 
I plan to come back and add logging level awareness so we don't log everything to the output channel all the time. This first PR is just to get the logging out there to help debug the issue ASAP
example output
> Add BDC spark connection logging

- extensions/azurecore/package.json
- extensions/azurecore/src/extension.ts
- extensions/azurecore/src/typings/ref.d.ts
- extensions/resource-deployment/src/typings/resource-deployment.d.ts
Some cleanup here - this never ended up being used so getting rid of it and simplifying the type passed to registered value providers so they don't have to check what type is coming in. 
(also adding comments cause comments are good...)
> Delete azurecore value provider and simplify type

- src/sql/workbench/contrib/query/browser/actions.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
Missed a few in https://github.com/microsoft/azuredatastudio/pull/17134
Noticed that we never actually used accountForNumberColumn (it was always true) so just removing it
> Add a few missed instantiation service usages

- .vscode/launch.json
- .vscode/tasks.json
This way people can directly launch the sample extension and debug into it to see how it works themselves. (as well as starting a watch task in the background)
> Add launch target for sample-resource-deployment

- .eslintrc.json
- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/workbench/contrib/queryPlan/browser/queryPlan.ts
- src/vs/code/browser/workbench/workbench-dev.html
- src/vs/code/browser/workbench/workbench.html
- yarn.lock
Change the reference to html-query-plan to use npm.js.  I've changed the name of the package to an obviously temporary name so that it won't be confused with the official package.  This package is planned to be replaced in Dec once we have an the internal execution plan control available.
> Update reference to html-query-plan to use npm.js

- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/models/publishProfile/publishProfile.ts
- extensions/sql-database-projects/src/test/baselines/baselines.ts
- extensions/sql-database-projects/src/test/baselines/publishProfileDefaultValueBaseline.publish.xml
- extensions/sql-database-projects/src/test/publishProfile.test.ts
This PR fixes #15989. Values should only be loaded from `<Value>`, even if `<DefaultValue>` is specified for a SQLCMD variable in publish profiles. This is the same behavior as SSDT.
> fix DefaultValue getting loaded for publish profiles

- extensions/agent/package.json
- extensions/arc/package.json
- extensions/asde-deployment/package.json
- extensions/azcli/package.json
- extensions/azuremonitor/package.json
- extensions/big-data-cluster/package.json
- extensions/cms/package.json
- extensions/dacpac/package.json
- extensions/data-workspace/package.json
- extensions/import/package.json
- extensions/kusto/package.json
- extensions/machine-learning/package.json
- extensions/profiler/package.json
- extensions/query-history/package.json
- extensions/resource-deployment/package.json
- extensions/schema-compare/package.json
- extensions/server-report/package.json
- extensions/sql-assessment/package.json
- extensions/sql-database-projects/package.json
- extensions/sql-migration/package.json
Bump all non-builtin extensions in release/1.33. Some of the extensions won't be released with the hotfix and others are already bumped from what's currently in marketplace. For the first group, we can ignore the vbump. For the second group, we can grab the extension from previous build if that version number is preferred.
Bumping all extensions is quicker than tracking down which will ship at which version in order to get build going sooner. This PR is not intended to be ported back to main.
> Bump non-builtin extensions in release/1.33

- src/sql/azdata.proposed.d.ts
- src/sql/base/browser/ui/designer/interfaces.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
1. add  2 common column properties: `precision` and `scale` 
2. add description to property definition
3. allow extensions to determine the properties to be displayed in the columns table
> add column properties

- src/sql/azdata.proposed.d.ts
- src/sql/base/browser/ui/designer/designer.ts
- src/sql/base/browser/ui/designer/interfaces.ts
- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
1. add options to allow extension to control whether add/remove rows should be enabled
2. if multiple groups are detected, add a default 'General' group for the properties that do not have a group specified.
3. adjust the min size for content pane.
code reviewers:
for this PR, I wrapped 2 blocks of existing code into if statements and changed the indention, it would be much easier to review the changes if you ignore the whitespaces
> allow extension to control whether add/remove rows should be enabled

- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/17579 (there are some perf issues mentioned there that this doesn't specifically address, we can follow up to see if those are still happening after this fix goes in)
This was introduced by https://github.com/microsoft/azuredatastudio/pull/17180
The problem here is that the `onCellMarkdownModeChanged` and `onCellPreviewModeChanged` callbacks are being called every time we switch cells - even if the text cell in question isn't active. In `focusIfPreviewMode` there was logic added that gets the current window selection and then replaces it with a new selection for the text cell - but this means that if we're moving into a code cell this event is still being fired and thus we're still running the code to get the current selection …
> Fix not being able to type in code cell after switching from text

- src/sql/base/browser/ui/designer/designer.ts
- src/sql/base/browser/ui/designer/designerPropertiesPane.ts
- src/sql/base/browser/ui/designer/media/designer.css
1. remove the object name from the properties pane header, it could be long and messy.
2. make the group header more obvious.
before:
after:
> a couple properties pane UI changes

- src/sql/workbench/browser/editor/tableDesigner/tableDesignerInput.ts
the table designer tab is taking too much space, I am changing it so that name (tab header) is less descriptive and the subject (application title and the hover-over tooltip) contains the more descriptive information.
before:
after:
> separate title and name for table designer editor

- extensions/mssql/config.json
This version of Tools Service splits an API in two, so Schema Compare is broken until the new ADS logic is in place.  Because that'll take a few days for code to be reviewed and out, I'm reverting Tools Service and will do a multi-step swapover.
> Revert "Bump tools service (#17607)"

- scripts/test-extensions-unit.js
Running test-extensions-unit.js(ex: `node test-extensions-unit.js sql-database-projects`) started not working on mac after this commit https://github.com/microsoft/azuredatastudio/commit/867a96388230066d7ed7cdb88cd90e54f0a15670 added the env stuff when executing the command. 
Error: 
The tests were still running on windows, so this only updates the script to not pass in the env info for mac. The env stuff wasn't there before and I think this script is only used for local testing, so it should be ok to not have for mac.
> fix test-extension-unit.js on mac

- extensionsGallery.json
Updating arc from 0.9.6 --> 0.10.0 and azcli from 0.1.0 --> 0.2.0 because Insider's is now using 0.9.* and 0.1.*. Made this change so that Insider's releases for these extensions and stable releases can both make hotfixes if needed.
> Update arc version to 0.10.0 and azcli version to 0.2.0

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts
- extensions/sql-database-projects/src/models/IDatabaseReferenceSettings.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/models/projectEntry.ts
- extensions/sql-database-projects/src/models/tree/databaseReferencesTreeItem.ts
- extensions/sql-database-projects/src/models/tree/projectTreeItem.ts
- extensions/sql-database-projects/src/test/project.test.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
- extensions/sql-database-projects/src/test/projectTree.test.ts
No functionality changes, just moving the project entry classes (file, database references, sqlcmd var) to their own file so they aren't at the bottom of project.ts anymore.
> Move project entry classes to separate file

- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
previously as long as there were edits made, if the user has reverted the changes manually, we still considered it as changed.
fix: save the original view model and do deep compare to decide the dirty state
> fix dirty state of table designer

- src/sql/workbench/contrib/query/browser/queryEditor.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/17642
This was broken in  https://github.com/microsoft/azuredatastudio/pull/17538
When restoring the editors we don't have providers registered yet and so providerId was undefined which meant it was throwing an exception on line 297 (attempting to get connection of undefined).
Fixing this by defaulting to not showing the dropdown and then hooking up to the capabilities service to listen for when our provider is registered and updating the taskbar again then.
> Fix query editors restoring as plain text

- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
This PR fixes #17501 
Refactored how the decorations are applied on text cells. Instead of going by each decoration range, changed it to filter by each cell and applying the ranges in those cells and moving on.
> refactor deltaDecorations logic

- src/vs/base/common/network.ts
This PR fixes #17172
The change is to resolve the same-origin policy violation that only occurs when ADS web is running in a container and the themes or language syntax settings are changed.
> Resolves same-origin-policy violation when ADS web is running in a container

- extensions/sql-database-projects/src/models/project.ts
- Moved the bigger chunks of logic in `readProjFile()` to their own helper functions (files, folders, pre/post deploy scripts, and database references) so `readProjFile()` is easier to read.
- Use a set instead of checking if a files already there before adding it to avoid duplicates when loading the files included in the project.
> Refactoring readProjFile()

- test/smoke/src/main.ts
This PR fixes #17632 
This PR resolves an ENOENT (Error no Entry) error affecting smoke tests in the web build pipeline. The ENOENT error was occurring because an attempt to copy from a path that didn't exist was being made.
In regard to the missing screenshots, the YAML file is already configured to capture screenshots when a test fails, but doesn't capture any for passing tests. In this case, tests weren't failing, so there weren't any screenshots.
> Corrects Web Build Pipeline ENOENT Error

- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/project.test.ts
For msbuild sdk style projects, the folders and most of the files can be found by the project folder globbing, so a build entry only needs to be added to the sqlproj in a couple cases:
- file is outside the project's folder
- external streaming job because it needs the Type attribute (`<Build Include="ExternalStreamingJob2.sql" Type="ExternalStreamingJob" />`) to identify it as an external streaming job so the extension knows that streaming job validation can run on it.
> update add file/folder for msbuild sdk style projects

- src/sql/workbench/browser/modelComponents/treeComponentRenderer.ts
During accessibility testing, it was discovered that screen reader does not announce what checkboxes in the tree view represent. It was merely announcing "checkbox unchecked", so it was not clear without visuals which checkbox the focus is on.
This change sets an `aria-label` of the checkbox elements to match the label of the owning tree node. This way the announcement becomes "My Node; checkbox; unchecked". This is fine as a quick solution to the problem, but in the future we may want to consider adding additional checkbox label property to the nodes exposed by the tree provider, so that each checkbox can announce additional information, if needed.
> Provide aria-labels for node checkboxes in the tree view.

- src/sql/workbench/browser/modelComponents/tree.component.ts
- src/vs/base/parts/tree/browser/treeImpl.ts
During accessibility testing it was discovered that tree view in our wizard reads "Tree Node tree view" instead of the proper label that is specified. It turned out to be the problem with the tree component, where `ariaLabel` was hardcoded to "Tree Node", instead of the one provided in the options.
This change addresses the problem by passing through `ariaLabel` from the options object to the underlying tree control. I also removed the default `Tree Node` hardcoded label, as it didn't make much sense. This does mean that all tree views that do not explicitly specify their aria-label will now get an empty label (announced as just the "tree view"). I think this is better than having unrelated, unlocalized `Tree Node`.
I'm also worried about changes to the `ariaLabel` property after the …
> Respect ARIA label specified in the tree component options.

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/package.nls.json
- extensions/sql-database-projects/src/controllers/mainController.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/tools/netcoreTool.ts
This PR fixes #17667 and the double warning also mentioned in that issue. Now the .net 6 installed warning only shows when trying to build a project and it "Do Not Show Again" hasn't been selected.
before (two warnings):
now:
> Fix sql projects net6 warnings

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/tools/netcoreTool.ts
Undo adding the space in the config so customers don't lose this setting if they had it configured. We'll need to update this again later to remove the core from the name since it isn't just .net core anymore.
> undo adding space in net core sdk location setting

- build/azure-pipelines/sql-product-build.yml
- build/azure-pipelines/win32/sql-product-build-win32.yml
update the vmImage for jobs to upgrade to newer windows version
for macos I am updating it to use more specific version (the current value of  macos-latest) to avoid unexpected failures just in case.
tested the changes with the Ad Hoc product build pipeline.
> update the vmImage for build jobs

- src/sql/workbench/browser/designer/designer.ts
- src/sql/workbench/browser/designer/designerPropertiesPane.ts
- src/sql/workbench/browser/designer/media/designer.css
- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
1. previously, once we go into a second level object, it is not possible to show the table object properties, now I am adding logic if the focus goes into a none-table object in the content area, we should the properties of the table.
2. show the description for the tables in the properties pane.
3. adjust the properties pane style
> properties pane improvements

- src/sql/azdata.proposed.d.ts
- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
columns table, foreign keys table, constraints table and the ones we need to add all share the same properties, currently they are repeatedly defined inside the main view interface, in this PR I am introducing a new interface to extract the common properties to make the definition simpler.
> code refactoring

- src/sql/workbench/services/dialog/browser/wizardNavigation.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/17670
Our extension is relying on the wizard dialog. During accessibility testing it was discovered that wizard step buttons are being reported as links by the screen reader (NVDA, JAWS). Claimed expected behavior by the tester is that they should be announced as buttons.
This change addresses the problem by adding `role` attribute to the said elements with the value of a `button`.
Elements in question are these circle buttons:
You can navigate to them using a Tab button, at which point they were announced as links, i.e. "One; **Link**; Visited; Select objects to convert". With this change it will be announced as "One; **Button**; Visited; Select objects to convert".
This will affect all wizard dialogs in ADS, but I assume we need …
> Set role to button for the wizard step links.

- src/sql/workbench/services/dialog/browser/wizardModal.ts
Direction is a little redundant since it can be calculated from the index, but figured it's easier to save the backend a little extra processing and just do it here.
> Add additional properties to wizard page navigation events

- src/sql/workbench/services/query/common/resultSerializer.ts
- src/vs/workbench/electron-sandbox/window.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/17618
This is a port of https://github.com/microsoft/vscode/commit/1834a0da4deb642ba13f7e15891723e170e93018 so no CARBON EDIT tag needed
Also fixed up the path displayed to the user, previously it would show as `/C:/Users/chgagnon/Desktop/Results.xlsx` for Windows users, now it'll be `c:\Users\chgagnon\Desktop\Results.xlsx`
> Fix open external not working

- src/sql/workbench/services/connection/browser/connectionManagementService.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/17691
We were hardcoding it to change to the sql flavor every time a connection was made which would override the sqlcmd flavor that had been set earlier.
Note this doesn't fix the issue the comment mentions where making a connection will set it to sql no matter the actual language...fixing that is likely going to be a bigger task and so I'm just leaving it with the previous behavior for now.
> Fix language flavor change on connection when in sqlcmd mode

- extensions/sql-database-projects/src/tools/netcoreTool.ts
- extensions/sql-database-projects/src/tools/packageHelper.ts
Currently we're throwing an error when adding the SQL binding package reference if the user has .NET 6 installed on their machine. But the version check is supposed to only be for building a sql proj - adding a package reference with .NET 6 is fine.
Fixing this to allow callers to say they don't care about the version of .NET as long as it's installed
> Fix "unsupported version" error when adding sql binding package

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/package.nls.json
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/tools/netcoreTool.ts
ADS has been updated to use DacFx 160, which supports building sql project with .net 6, so we can remove this version cutoff. I verified that after this cutoff version is unset, projects are successfully building when .net 6 is installed.
> Remove .net 6 version cutoff for building sql projects

- src/sql/workbench/contrib/notebook/test/browser/notebookLinkHandler.test.ts
- src/sql/workbench/contrib/notebook/test/calloutDialog/linkCalloutDialog.test.ts
Added some relative links cases to the Link Dialog and Link Handler tests to better capture the manual steps in our test plan.
> Add additional tests for handling relative links in notebooks.

- src/sql/platform/accounts/common/interfaces.ts
- src/sql/platform/accounts/test/common/testAccountManagementService.ts
- src/sql/workbench/services/accountManagement/browser/accountManagementService.ts
- src/sql/workbench/services/accountManagement/browser/autoOAuthDialogController.ts
This PR fixes an issue around copying user codes and opening a new browser window to add an Azure account to ADS.
To test this:
- Launch ADS in web mode.
- Click on "Sign in to Azure"
- Select "Azure Device Code"
- In the "Add Azure Account" blade
- Click on "Copy & Open"
- In the newly opened browser tab
- Paste the code in the login page..
RESULT: The correct user code will be present in the login page.
> Fixes ADS Web bug around copying user codes and opening a browser tab when adding an Azure Account.

- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
This PR fixes #17402.
Just adding the `title` attribute to the buttons that open callout dialogs.
I briefly looked at refactoring this to remove the need for the button containers, but decided to leave this alone for now, since that change would be much larger than something that I can do at the moment with my current capacity.
> Notebooks: Add Tooltips for Link/Image Buttons on Markdown Toolbar

- src/sql/base/browser/ui/table/tableDataView.ts
- src/sql/base/test/browser/ui/table/tableDataView.test.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR fixes #17633
root cause
1. the current implementation relies on the sample data (the first row in the data set) to determine the  column type, it works well for certain scenarios, but for scenarios described in issue above, it will produce inconsistent results.
2. we are treating Null as a string (using its display value) when sorting, when sorting with strings the results will be wrong.
fix:
1. use the order: undefined -> number -> string to sort the values which will produce consistent results.
2. treat null as a special value
new results using the example provided in the issue:
results with mixed values: null, empty string, string, number
> fix sorting bug

- src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.css
This PR fixes #17408 
the style of the separator is now defined in the taskbar component, the only actual customation is the height which is causing problem. so removing it altogether.
before
after
style defined in the taskbar component:
> update dashboard taskbar separator

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/package.nls.json
Reverting this PR: https://github.com/microsoft/azuredatastudio/pull/17340 with two new changes:
- added (preview) to command title
- added `resourceExtname` to when clause to hide the command for untitled files and fixes https://github.com/microsoft/azuredatastudio/issues/17571
> Enable add sql binding quickpick

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/package.nls.json
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/mainController.ts
- extensions/sql-database-projects/src/test/netCoreTool.test.ts
- extensions/sql-database-projects/src/tools/netcoreTool.ts
This PR fixes #17685. This updates a couple user facing strings and the related variables to remove "Core" since .net 5 and 6 are also supported, not just .net core anymore.
> update .net sdk location strings now that .net 6 is supported

- extensions/sql-migration/src/models/migrationLocalStorage.ts
adding a bug fix to help prevent a race condition where a new migration started in the background can be lost/deleted while the migrations list is refreshing.
> add migration state management improvement

- extensions/notebook/package.json
Add Section command should only be visible by right clicking a book tree item.
> Do not show add section command

- extensions/sql-migration/package.json
- extensions/sql-migration/src/dialog/sqlMigrationService/sqlMigrationServiceDetailsDialog.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
this change 
* auto-populates target database name entries with source database name as a default
* bump extension version to 0.1.11
* use async setDataValues
> set initial target db name

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/retryMigration/retryMigrationDialog.ts
- extensions/sql-migration/src/dialog/targetDatabaseSummary/targetDatabaseSummaryDialog.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
- extensions/sql-migration/src/wizard/summaryPage.ts
This PR adds support to enter unique network share locations for each selected database. This feature only supports network share locations using the same windows credentials and storage account information.
This PR also fixes the bug preventing multiple db migrations in a single wizard experience.
Database backup page
* Removed the single network share location input box
* Added new column, Network share path, to network share target database table
Summary page 
* Moved the network share location information to the Target Database Summary Dialog
> Support multiple database migrations using network share

- build/azure-pipelines/linux/Dockerfile
- build/azure-pipelines/sql-product-build.yml
Doing this update since Ubuntu 16.04 used in the current linux builds has passed EOL 
This PR fixes #17773
Link to the adhoc build: 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=131021&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=34fc863e-00ed-50b5-30ee-f50930ed6e81
> Updating pipeline linux agent image to Ubuntu 18.04

- src/sql/workbench/contrib/query/browser/media/gridPanel.css
#17833 
in previous vscode merge, vscode added default padding for action-label and as a result the size of the action bar items was changed and it is taking more space now, the fix is to add a grid specific rule to make sure it is compact.
I've updated the query editor test case to include a "one row" test.
https://github.com/microsoft/azuredatastudio/pull/15681/files?file-filters%5B%5D=.css&hide-deleted-files=true#diff-addd7132dee13457b17c0ce8af86416722108e69b8a60d63a865f524a8323f5fR50
before:
after:
> fix grid actionbar

- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
- src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts
- src/sql/workbench/services/notebook/browser/models/cell.ts
This started as just wanting to make an automated test for deleting attachments - but during this I found that this was only happening in the cell component code. So to make testing easier as well as get the benefit of having any changes to source from anywhere cleaning up the attachments I moved it into the cell model class itself. 
Because of this I had to make sure to check for current attachments that were being used in the source - where it was being done before would always reset the source back to the raw base64 encoded attachments (which were then parsed and inserted back). But now since we're doing it on any source change then this can trigger from other places that were setting it with the attachments already set.
> Always clear unused attachments when updating cell source

- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
Addresses https://github.com/microsoft/azuredatastudio/issues/17850. This got introduced with the publish to container changes in https://github.com/microsoft/azuredatastudio/pull/17495.
Load publish profile was failing when the radio buttons aren't toggled before loading the publish profile. The error was happening because the value of the database textbox is trying to get set, but that only gets created when the "Publish to new server in container" radio button is selected.
> fix load publish profile not working

- extensions/mssql/config.json
This PR fixes #17825
port fix to release branch, original PR: https://github.com/microsoft/azuredatastudio/pull/17865
> vbump sts (#17865)

- src/sql/platform/connection/common/connectionProfile.ts
for: https://github.com/microsoft/azuredatastudio/issues/17844
root cause:
in this PR: https://github.com/microsoft/azuredatastudio/pull/17266 a new option (originalDatabase) is added to the connection profile and used it to determine whether we are trying to open a database dashboard or server dashboard.
when we open database dashboard from OE, we are cloning the profile and set the database name, but the originalDatabase is not set, as a result it is being treated as request to open server dashboard.
fix:
when we clone the profile with a database name, we should also set the originalDatabase property.
P.S. I've been testing the database dashboard directly from the server dashboard, I've added a test case to the test plan to check this entry point as well.
> open database dashboard

- src/sql/workbench/contrib/notebook/test/electron-browser/notebookModel.test.ts
- src/sql/workbench/services/notebook/browser/models/cellEdit.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR is for #17820 
Keep track of how we split the cells in an array. The first entry will always have the original cell and the subsequent cells will be the newly created cells.
To merge the cells we concatenate the sources from the other cells and attached them to the original cell.
https://user-images.githubusercontent.com/34872381/145117471-0b4ee8fe-5dfd-47ff-bcd2-9c1e6a83e709.mov
> Fix split cell undo

- src/sql/platform/connection/common/connectionProfile.ts
This PR fixes #17844
port https://github.com/microsoft/azuredatastudio/pull/17871 to release branch.
> port dashboard fix

- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
For https://github.com/microsoft/azuredatastudio/issues/17878
I have no idea how this worked in the first place - per https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key 
`The KeyboardEvent interface's key read-only property returns the value of the key pressed by the user, taking into consideration the state of modifier keys such as Shift as well as the keyboard locale and layout.`
So the value should have been `H` instead of `h`
But apparently this works fine on Macs as it is so maybe there's a bug in Chrome there. 
Regardless this isn't a safe way to check these - using the StandardKeyboardEvent should be the preferred way of handling any keyboard related input. 
Note that this still isn't really how we should be handling these things - using our own key handling logic …
> Use standard key events for Notebook keybindings

- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/17869. The focus should be on the first enabled component, which used to be the publish profile input box but is now the radio buttons. Alan made a change a while ago that automatically sets the focus on the first enabled component, so we don't need to explicitly set the focus anymore.
> fix focus when opening publish dialog

- src/sql/workbench/contrib/commandLine/electron-browser/commandLine.ts
requested by a partner team.
1. the partner team do not have query provider support right now, we shouldn't assume it is and directly open query editor
2. ability to open the dashboard after connection is made.
> update commandline handler

- src/sql/base/browser/ui/table/table.ts
This PR fixes #17808 
in my previous PR: https://github.com/microsoft/azuredatastudio/pull/16206 I fixed the table not getting focused issue by keyboard. there is a flaw in the implementation, I meant to only handle the keyboard scenario. in the case that user directly clicks the table, we shouldn't do focus redirection.
before:
after:
> fix table focus issue

- src/sql/base/browser/ui/table/table.ts
This PR fixes #17898 
(I have run the command "Toggle Tab Key Moves Focus" while recording the following images)
**Before** 
The table is not keyboard focusable after tab switching, the focus goes from tab header to the 'Save as CSV' button directly.
after:
> table keyboard focus

- src/sql/platform/connection/common/connectionConfig.ts
- src/sql/platform/connection/common/connectionStore.ts
- src/sql/platform/connection/common/providerConnectionInfo.ts
- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
- src/sql/workbench/services/connection/browser/connectionDialogService.ts
- src/sql/workbench/services/objectExplorer/browser/asyncServerTree.ts
- src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts
We've had this annoying issue for a long time, as you can see from the screenshot below, just after a couple operations like: make a new connection, disconnect. we already have 470 listeners registered.
Root Cause:
we are creating ConnectionProfile objects but not disposing them properly after use.
Fix:
1. properly dispose the connection profile objects after use for the places that I discovered.
2. for this particular event, we don't really need to subscribe to it, we can just retrieve the value when we need it, so removing the event, but leaving the class as Disposable in case we really need it to be disposable in the future.
before I completely remove the event from the class, with the other changes , there are still leaked listeners that are not very obvious to find, the number has …
> fix listener leaks

- extensions/arc/package.json
- extensions/azcli/package.json
Bumped up the version numbers in the package.json of extensions:
- arc-0.11.0
- azcli-0.3.0
Stable and Insiders will have the same version. Updating extension galleries in an upcoming PR after this.
> Bumped versions of azcli and arc in package.json

- src/sql/base/browser/ui/table/table.ts
This reverts commit 177663cc29c9763a4f005055f9a5a88841ea2392.
sigh, I have to revert the change. it is causing more problems. the scrolling is broken with my previous change. these changes are considered workarounds, I need to make a proper fix to handle the keyboard navigation in our slickgrid so that we don't have to use these workarounds.
before the revert.
after the revert.
> Revert "table keyboard focus (#17903)"

- test/automation/src/sql/configurePythonDialog.ts
Adding logs to help debug when smoke tests fails on the configure Python wizard
> Add logging for python smoke test

- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/project.test.ts
This fixes how add folder is handled for sdk style sql projects. This fixes the ADS sql projects implementation to match how csprojs are handled in VS when adding new folders. 
In the initial changes to handle SDK style projects, all folders in the project's folder were included by default. After taking a closer look at how csprojs handles it, there's actually a Folder entry added to the project file when a new folder is added, then the Folder entry is removed from the csproj when the folder is no longer empy, like when a file is added inside. Empty folders are not shown in the UI unless there's a Folder entry for it in the project file.
Examples of adding folders and how the project file gets updated:
sqlproj:
csproj:
> Add folder for SDK style sql projects

- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/baselines/openSdkStyleSqlProjectWithGlobsSpecifiedBaseline.xml
- extensions/sql-database-projects/src/test/project.test.ts
- extensions/sql-database-projects/src/test/testUtils.ts
I realized the pre and post deploy scripts were getting counted twice (in files and in the pre/post/none deploy script arrays) while implementing delete for sdk style projects when the pre and post deploy scripts were trying to get deleted twice. The pre and post deploy scripts were getting picked up by the file globbing, so they need to be removed from the list of files so that they're only kept track of in the pre/post/none deploy script arrays.
> fix pre/post deploy scripts getting double counted in the files for sdk style projects

- extensionsGallery-insider.json
- extensionsGallery.json
- .NET 6: 0.1.0 -> 1.0.0 (use RTM runtime)
- DSCT (Oracle to MS SQL): 0.1.1 -> 0.2.0 (support user-defined data type mappings)
> Update .NET 6 and DSCT extensions to latest

- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
We can remove disposable listeners for undo/redo commands, since we are using the vscode undo/redo commands instead.
> Remove undo/redo listeners from notebook component

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/tree/projectTreeItem.ts
- extensions/sql-database-projects/src/test/projectTree.test.ts
This PR fixes #17963. This was already fixed in main in #17826, but to minimize the changes, this PR only has the 2 line fix and test change. This looks related to this previous test issue that #11026 that wasn't investigated before because it was only failing in tests.
This wasn't a problem before because this line of code wasn't being hit in most cases. By default when created in VS or ADS, sqlprojs have the folders listed first before the files and the project loading logic would go through the ItemGroups in order so the folders would be loaded first. If the order is changed to have files first, then folders, this would also be a problem in the previous extension versions. The test was previously failing because the folder was added after the files.
This got exposed in recent changes …
> fix adding nested items not being created in the correct location in the project

- .yarnrc
- cgmanifest.json
- package.json
- yarn.lock
The VS Code updates didn't seem to need to update anything in the core app so this should be safe to get in. I did some basic validation and things seem fine.
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=134859&view=results
Fixes a security issue with the version we got from the merge. I decided to update to the latest version VS Code is using since there weren't any major changes needed to do so.
> Bump Electron to 13.5.0

- extensions/mssql/config.json
the only commit included in this version: https://github.com/microsoft/sqltoolsservice/commit/995e9baeab26c23220d3e4ab9a06fe288ff4ebaf
this PR fixes: #275
> bump sts to bring in the data type handling changes

- src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts
Fixes #18019, which i assume is just a result of a merge conflict issue from the merge.
> Remove Extra Split Cell Action in Notebook Cell Taskbar

- src/sql/workbench/contrib/profiler/browser/profilerEditor.ts
Adds in null check (which has been removed for editor inputs with the vscode-merge) for profiler input
This PR fixes #18023
> Added undefined check to profiler

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/baselines/baselines.ts
- extensions/sql-database-projects/src/test/baselines/openSdkStyleSqlProjectNoProjectGuidBaseline.xml
- extensions/sql-database-projects/src/test/project.test.ts
This PR fixes #17847. Instead of showing an error when opening a sql project without a project guid, the behavior is now the same as SSDT and a project guid is added to the sqlproj.
> add a project guid if a sql project doesn't have one

- src/vs/workbench/contrib/welcome/page/browser/welcomePage.contribution.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/18001
VS Code started replacing all the old legacy welcome page code with the newer Getting Started (walkthrough) experience and this was one of the things deleted. Bringing it back for now (the getting started stuff is all commented out for now).
> Bring back welcome menu item

- src/sql/workbench/api/common/vscodeNotebookEditor.ts
- src/sql/workbench/test/electron-browser/api/vscodeNotebookApi.test.ts
- src/vs/workbench/api/common/extHost.api.impl.ts
This change adds support for the following VS Code extension APIs:
vscode.workspace.notebookDocuments
vscode.window.activeNotebookEditor
We already had our own version of these APIs, so the main part of this change was adding a class to convert between the azdata NotebookEditor class and vscode's. We also only need the **document** field from NotebookEditor for Interactive support, so the other methods in the conversion class are no-ops.
> Enable VS Code extension APIs for getting opened notebook documents

- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
This PR fixes #17864. Previously, only the sqlcmd variables from the publish profile were being used. This updates the vscode publish database quickpick to also use the database name and deploy options if a publish profile is loaded and has them.
> load name and options from publish profile for vscode publish quickpick

- src/sql/workbench/browser/designer/designerScriptEditor.ts
- src/sql/workbench/contrib/profiler/browser/profilerEditor.ts
Noticed this issue during my testing, scenarios will run into this problem:
1. open a profiler editor and drag it to a different editor group
2. open a profiler editor and then open a table designer
3. open a table designer editor and drag it to a different editor group
When creating UntitledTextEditorModel, we have to make sure the URI is unique. I think this is introduced by recent vscode merge, I remembered I tested the multiple editor group scenario for table designer before.
I searched in the code base and the other places like Notebook code cell is handling this correctly.
> fix issue with profiler and table designer editor

- extensions/notebook/src/dialog/configurePython/configurePythonWizard.ts
This PR adds a check in the wizard navigation validator to return false when the pages have not been registered yet. Previously, a user can click next before the installation path is loaded on the first page and the wizard ends up in this weird state where it goes to the second page but the kernel dependencies never load and the previous button does not work. 
I think this is what is happening during the Python smoke test that fails occasionally. Although it is still not clear what is causing the next button to be clicked (logs don’t show any clicks or enter key pressed) - I will continue to investigate that.
> Disable next button on Python wizard creation

- src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts
When we wait for kernels to be registered (as well as for execute and serialization providers), we run 2 promises in parallel: one for the actual registration completion, and a timeout promise that emits an error to the log. The registration was always completing successfully, but that timeout promise was still running in the background, and was then adding a faulty error to the log. The fix for that is to check if the provider instance exists when that timeout promise finishes. In addition, I improved some of the waiting logic to reduce the number of times we queue up those racing promises in the first place.
Fixes #18022
> Improve logic used to wait for standard kernel registration

- test/automation/src/sql/notebook.ts
- test/smoke/src/sql/areas/notebook/notebookView.test.ts
ADS gets refreshed after each test suite, so we need to configure python every time. 
Pinning a SQL notebook to prevent the Configure Python Wizard from popping up.
> Fix Notebook Tree View smoke tests

- extensions/mssql/src/contracts.ts
- extensions/mssql/src/mssql.d.ts
- extensions/mssql/src/sqlMigration/sqlMigrationService.ts
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
This PR adds the relevant contracts and backend changes to enable calls to `migration/getskurecommendations` (see: https://github.com/microsoft/sqltoolsservice/pull/1362). The 'assessment results' UI is extended to serve as a placeholder UI for SKU recommendation results, which will be reverted when an actual UI is implemented.
> Implement GetSkuRecommendation call + contract changes

- build/lib/rollup.js
- build/lib/rollup.ts
Fix webmode build.  Changed previous PR to use toString instead of stringify, as I believe this is more compatible with previous behavior.  The web container is still broke at runtime for other issue that will be investigated separate from build break.
> Fix webmode build

- extensions/sql-database-projects/package.json
This PR fixes #18123. There isn't quickpick support for this yet, so this should be hidden in vscode.
> remove update project from database in vscode

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/auths/azureAuthError.ts
This started off as just fixing the error message displayed prompting the user to open the developer tools (I just added a command link) but then was finally able to figure out where the error displayed to the user as '`{}`' was coming from which has been an issue that pops up occasionally for a while now. 
The main issue is that we were never setting the `_originalMessage` property - it was passed into the constructor but then never assigned. So then the call to `getPrintableString` returned an empty object which was then displayed to the user.  
In fixing this though I didn't like the idea of us showing these values to the user when we already had a localized error message, so changed it so that was displayed to the user instead and then print the original error/exception in the console …
> Fix azure auth error display

- extensions/mssql/package.json
This PR adds "New Table" context menu to Tables node in OE.
The end-to-end workflow to add a new table and persist the table to db works fine. (Along with my changes to DacFx)
> [Table Designer] Add "New Table" menu to Tables node in OE

- extensions/data-workspace/package.json
- extensions/data-workspace/package.vscode.json
This was causing the MSSQL to extension to activate upon startup - even if the user wasn't using any of the features.
This has a couple negative side effects : 
1. Launch times for VS Code is increased - even if the user doesn't intend to use any features of the MSSQL extension
2. Our telemetry numbers are greatly increased since we currently use activation as a way to determine users of the extension. But now activation isn't really accurate for that count
Making the data-workspaces extension not activate on startup is another potential solution, but looking into that it gets tricky because we purposely hide the view until the extension can activate and determine if there's a project provider available (so we aren't showing it if we don't have anything that can contribute projects). …
> Remove extension dependency from VS Code data workspace

- src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
- src/sql/workbench/contrib/notebook/browser/models/untitledNotebookInput.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookInput.test.ts
This PR fixes #18088 
VSCode added autodetectLanguage step whenever file content changes. And unless the file mode (language) is explicitly set, it tries to pick a language for the file.
Added setMode in notebookInput to explicitly set the language.
> set mode explicitly to notebook

- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/project.test.ts
This PR fixes #18070. The pre/post/none deploy entries were getting removed from the sqlproj when excluding these before, but because of the *.sql glob include, they were then getting included as files and still showing in the project tree. This PR fixes that by adding a <None Remove="script.sql"> entry when excluding a pre/post/none deploy script and removing those entries from the file list when reading the project files.
> fix excluding pre/post/none deploy scripts in sdk style projects

- extensions/sql-database-projects/src/controllers/projectController.ts
Right now the command is returning immediately - but callers should be able to wait on completion of the command to know when the publish is actually finished.
> Have sql db proj publish command return publishing promise

- src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/18097
In the VS Code merge the code path for saving/replacing editors change significantly. The change that broke this was that the code now picks the editor ID from the input - which for the basic `FileEditorInput` (that we use as the underlying input for Notebooks) is [default](https://github.com/microsoft/azuredatastudio/blob/main/src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts#L42). Previously the editor ID was passed in explicitly and so was undefined, which meant it went through the editor resolver logic and picked the correct input based on the extension. But now since the input passes in a specific editor ID it skips that and just chooses the default text editor (which displays as the raw JSON).
I looked …
> Fix untitled notebook save opening as JSON

- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
- src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts
- src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookMarkdown.test.ts
- src/vs/base/common/network.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/18062
The issue here is that VS Code changed it so that all direct file:// access is blocked - images have to be loaded using the vscode-file protocol now. So the fix here is to use `asBrowserUri` to transform the URI into one that we can load when the URI is a file on disk.
See https://github.com/microsoft/vscode/issues/80352 for a similiar-ish issue in their own markdown renderer
Notebook with local, web and embedded images :
> Fix images in Notebook not showing

- src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
- src/vs/base/browser/dom.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/18002
With the protocol schema changes these changed from being file:// URIs to vscode-file://
> Fix welcome page images

- src/sql/workbench/browser/modelComponents/hyperlink.component.ts
This was removed in the VS Code merge I did for some reason. I have no idea why - but it shouldn't have been done in the first place.
Fixes https://github.com/microsoft/azuredatastudio/issues/15741
> Fix modelview hyperlink outline color

- build/filters.js
These shouldn't be checked for indentation and fail hygiene if ran locally
> Add some more ignore folders to indentation filters list

- extensions/mssql/config.json
These commits will also come with the vbump
@smartguest , does it look okay?
> vbumping sts to get latest execution plan changes

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/18077. This wraps the previous logic in handleUpdateButtonClick() so it only gets called if the user clicks "yes" when prompted if they really want to update their project.
> add confirmation message to update project from db dialog

- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/output.component.ts
Adding a telemetry event to track when MIME renderers aren't found in notebook outputs.
> Notebooks: Add telemetry event for mime type renderer not found

- src/sql/workbench/contrib/query/browser/query.contribution.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/18049
Fall back to the default text diff editor for SQL files.
> Fix query editor diff compare

- src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/18004
The root issue is that STS is for some reason setting the schema of a node to the schema of its parent if it doesn't have a schema itself : 
https://github.com/microsoft/sqltoolsservice/blob/main/src/Microsoft.SqlTools.ServiceLayer/ObjectExplorer/SmoModel/SmoTreeNode.cs#L86
So for columns (which don't belong directly to a schema themselves) we were seeing that it had a schema in the metadata and adding that.
Doing the check here isn't my favorite option - but I'm worried that if I change the behavior in STS that it'll break other things so probably best to leave it alone for now unless we find other places that are broken by this.
> Fix drag and drop for columns

- src/sql/platform/common/pathUtilities.ts
- src/sql/workbench/services/query/common/resultSerializer.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/18115
For untitled files if we haven't previously saved something then the default file path was undefined since there wasn't a location for the resource. In that case we fall back to the system default so we always have a save location to then set the default save name for. 
(this also applies to query editor result grids as well)
I also did some cleanup with a duplicate schema name var.
> Fix export results default save location

- extensions/mssql/src/tableDesigner/tableDesigner.ts
- extensions/mssql/src/telemetry.ts
previously, the table info was put in the fillServerInfo method which is not reusable.
> minor code refactoring

- extensions/arc/package.json
- extensions/arc/package.nls.json
- extensions/arc/src/localizedConstants.ts
- extensions/arc/src/ui/dashboards/miaa/miaaBackupsPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaComputeAndStoragePage.ts
- extensions/azcli/package.json
- extensions/azcli/src/api.ts
- extensions/azcli/src/az.ts
- extensions/azcli/src/typings/az-ext.d.ts
- Releasing the arc and azcli extensions out of preview and into GA.
- Updated the az command "edit" to be "update", in line with new Azure CLI arcdata extension commands
- Azure CLI arcdata SQL MIAA update now works for both direct and indirect modes (bug fix)
- Azure CLI arcdata SQL MIAA backup now works for both direct and indirect modes (bug fix)
> Arc and Azure CLI extensions GA + bug fix for SQL MIAA update

- src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/18021
The fix is similar to the fix for images not working https://github.com/microsoft/azuredatastudio/pull/18160.
We need to convert the vscode-file URI to file URI when opening. It is still not clear to me why the URI is vscode-file only on Mac and not Windows.
> Fix file links not opening in Notebooks on Mac

- src/sql/workbench/services/connection/browser/connectionBrowseTab.ts
the connection profile object passed in only contains data (from extension), we need to create a ConnectionProfile object from it just like other places.
This PR fixes #18029
this only happens for double click scenario, surprisingly, no customer has reported this issue :)
> fix double click issue in browse connections

- src/sql/workbench/browser/designer/designerScriptEditor.ts
This PR fixes #18232 
there is a race condition when moving table designer from one editor group to another, the editor model might not be ready when the content is set.
the fix is to call updateEditor() at both places.
> fix move editor group issue

- extensions/arc/package.json
- extensions/arc/package.nls.json
- Put connectivity mode field in step 2 of the DC deployment wizard instead of step 5
- Removed some left over (preview) tags in package.nls.json
> Removed preview from package.nls for arc and re-ordered connectivity mode in DC deployment wizard.

- extensions/mssql/config.json
- extensions/mssql/src/tableDesigner/tableDesigner.ts
1. Enables AAD authentication for table designer - by the new STS version and the changes the mssql extension
2. This PR fixes #18233 - by the new STS version.
3. This PR fixes #17960 - by the new STS version.
changes in STS since last update:
> enable AAD auth for table designer

- src/sql/base/common/network.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
- src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts
- src/sql/workbench/contrib/notebook/browser/utils.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookLinkHandler.test.ts
- src/sql/workbench/contrib/notebook/test/electron-browser/notebookUtils.test.ts
This PR fixes #17662 
As the issue states if user enters an encoded url such as https://github.com/search/advanced?q=test&r=microsoft%2Fazuredatastudio&type=Code we re-encode it and show it as https://github.com/search/advanced?q=test&r=microsoft%252Fazuredatastudio&type=Code.
In this PR, I've added a check to see if the url has encoded components using an example method from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent .
> check for encoded components

- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
Removing the SDK style template for before the release branch snaps so a new version of sql database projects can be released in vscode for other changes. Will add back later for insiders release.
> Remove sdk style project template

- extensions/mssql/config.json
- extensions/mssql/src/contracts.ts
- extensions/mssql/src/mssql.d.ts
- extensions/mssql/src/sqlMigration/sqlMigrationService.ts
This PR includes several new changes in preparation for the new SKU recommendation feature in the SQL migration extension.
Changes include:
- updating sqltoolsservice to `3.0.0-release.202`, which includes an updated version of the assessment NuGet which enables the new SKU recommendation features
- defining new interfaces for the SKU recommendation functionality such as backend calls for generating SKU recommendations, as well as starting, stopping, and refreshing SQL performance data collection from ADS
See https://github.com/microsoft/azuredatastudio/pull/18252 and https://github.com/microsoft/sqltoolsservice/pull/1399 for corresponding changes.
Changes have been built and tested locally.
> Update mssql/sqltoolsservice for SKU recommendation changes

- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/18269
This isn't what I'd consider an ideal fix - preferably the event handler would be in the Notebook component only and so if the focus wasn't on the Notebook then we wouldn't even get these events.
But to do that we'd need to make the Notebook and cell components focusable in the first place which is not only a big change to be making (and should go through a full design review) but also wasn't something I was able to easily set up since setting tabindex on the cell components alone wasn't enough (we also need to be tracking the focus so we can update the active cell based on that, but I was having issues doing that since the cell components are divs).
So I went with this approach, which is a bit of a brute force solution but …
> Fix Notebook navigation key events triggering incorrectly

- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
- extensions/sql-migration/src/wizard/wizardController.ts
Changes:
- previously, we implemented the case where users would start data collection, save and quit, come back, and _continue_ their existing migration, which works as intended - data is still collected and the user picks up where they left off. However, the case where they start collection, save and quit, come back, and _start a new migration_, the new migration would start just fine except the old data collection would still be running and wouldn't have a way to be stopped. Now, whenever the user selects that they want to start a new migration, any existing data collection will be terminated.
- update the data collection / SKU recommendation timers to their production values - query every 30 seconds, generate SKUs after 10 minutes
> Stop existing data collection when leaving and starting a new migration + update timers

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/skuRecommendationResults/getAzureRecommendationDialog.ts
- extensions/sql-migration/src/dialog/skuRecommendationResults/skuEditParametersDialog.ts
- extensions/sql-migration/src/dialog/skuRecommendationResults/skuRecommendationResultsDialog.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
This PR:
- refactors SKU page refresh logic
- adds last refresh time 
- stop button also refreshes the sku rec
- adds Learn more link
- for users who have already inputted Get Azure Recommendation location, the dialog remembers their previous input
- fixes issues reopening VM View Details card 
- removes info box from integration runtime page
> Sku bug bash ux fixes

- build/lib/locFunc.js
- build/lib/locFunc.ts
This PR makes it so that extensions that were originally from vscode but have altered strings in ADS won't have their ID changed to Microsoft.extension-name by the update langpack task. (Currently, the only example is git, but more can be added in the future if needed)
> Added exclusion list for altered vscode extension localization

- extensionsGallery-insider.json
- extensionsGallery.json
This PR updates WakaTime to latest version `18.0.5`.
> Update WakaTime to v18.0.5

- src/sql/workbench/browser/designer/designerScriptEditor.ts
#18401
I was able to reproduce the issue by forcing the `this._content` to be undefined.
> table designer - fix for a race condition

- extensions/notebook/package.json
- extensions/notebook/yarn.lock
(cherry picked from commit 3dbd5ac2c1ec86910aea4103b648605595962467)
Fixes https://github.com/microsoft/azuredatastudio/issues/18423
> [Port] Bump url-parse (#18422)

- src/sql/workbench/browser/modelComponents/treeComponentRenderer.ts
* Fix contributed icons for ModelView trees not showing
(cherry picked from commit 2be13947489651084bb6f61f8eb8e6ff76b3ae78)
Fixes https://github.com/microsoft/azuredatastudio/issues/18429
> [Port] Fix contributed icons for ModelView trees not showing (#18430)

- extensions/arc/src/test/ui/components/radioOptionsGroup.test.ts
- extensions/arc/src/ui/components/radioOptionsGroup.ts
Fixes the color contrast accessibility bug as seen here: https://github.com/microsoft/azuredatastudio/issues/15776
Now looks like:
This PR fixes #15776
> Fixed color contrast for error message in connect a dc window.

- src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts
This PR fixes #18374, which allows us to include cost information to graph cells in ADS. An example of this cost information appearing is seen here:
> Adds Operational Cost to Query Plan Vertex Labels.

- build/azure-pipelines/win32/sql-product-test-win32.yml
Set up to explicitly require disabling integration tests (by setting RUN_INTEGRATION_TESTS to false) so that nothing changes by default. 
Porting to 1.35 directly for quick turnaround, will bring to main after this is in.
> Add option to disable running integration tests

- extensions/azurecore/src/account-provider/azureAccountProvider.ts
- src/sql/workbench/services/connection/browser/connectionWidget.ts
Fix to clear the azure account tokens from the cache before refreshing for new tokens
This PR addresses https://github.com/microsoft/azuredatastudio/issues/12637 https://github.com/microsoft/azuredatastudio/issues/14159
> [PORT] Clear account tokens before refresh (#18452)

- src/sql/platform/connection/common/connectionStatusManager.ts
- src/sql/platform/connection/test/node/connectionStatusManager.test.ts
- src/sql/workbench/services/connection/test/browser/connectionManagementService.test.ts
I added this a while back to try and figure out why we hit this occasionally but it hasn't really turned out to be useful for tracking anything down and generally when it happens isn't a critical error (when I've seen it it's because the connection was deleted before the onConnectionComplete handler was called which isn't necessarily unexpected).
Handling cases like that correctly will require some more investigation, but for the time being we should remove this since it doesn't provide useful information and often times isn't something that impacts the user.
> Remove connection error popup notification

- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
Adding back the SDK project template for insiders. It was originally added in #18058 and was hidden in https://github.com/microsoft/azuredatastudio/pull/18308.
> add back SDK style project template

- src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts
This PR is for #18477
The new vscode file parser removes the fragment from the uri and returns undefined.
> fix section markdown and html link

- ThirdPartyNotices.txt
The thirdpartynotices.txt should include mxgraph since this is used for the new showplan feature. This PR fixes #18484.
> Add mxgraph to thirdpartynotices.txt

- src/sql/workbench/contrib/profiler/browser/profiler.contribution.ts
These are removed from the create statement as the SQL server should automatically allocate memory based on the available hardware (from my research into what max_memory does), it appears to work fine on my local SQL server when I ran it. If I need to test it on other configurations, please provide me with example servers to connect to on Teams.
This PR fixes #17975 based on a suggestion from @williammsft
> Removed max_memory from profiler create statements

- src/sql/workbench/browser/designer/designer.ts
- src/sql/workbench/browser/designer/designerMessagesTabPanelView.ts
- src/sql/workbench/browser/designer/designerPropertiesPane.ts
- src/sql/workbench/browser/designer/designerPropertyPathValidator.ts
- src/sql/workbench/browser/designer/interfaces.ts
- src/sql/workbench/browser/designer/media/designer.css
- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
This PR fixes #18511 
1. replace the error list implementation with the accessible solution (using list component).
2. when error item is selected, bring the problematic item into view and then highlight it (make it easier to visually spot it).
3. fix some accessibility issues.
> highlight problematic property in the designer when error is selected

- build/azure-pipelines/updateGalleries.yml
Pipeline to automatically update published galleries when the gallery files are updated. 
- When `release/extensions` branch is updated both `extensionsGallery.json` and `extensionsGallery-insider.json` are updated
- When `extensions/rc1` branch is updated the `extensionsGallery-test.json` is updated
> Add pipeline to update galleries

- .eslintrc.json
- extensions/azurecore/src/azurecore.d.ts
- src/sql/platform/azureAccount/common/azureAccountService.ts
- src/sql/workbench/api/browser/extensionHost.contribution.ts
- src/sql/workbench/api/browser/mainThreadAzureAccount.ts
- src/sql/workbench/api/common/extHostAzureAccount.ts
- src/sql/workbench/api/common/sqlExtHost.api.impl.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
- src/sql/workbench/services/azureAccount/browser/azureAccountService.ts
- src/typings/refs.d.ts
- src/vs/workbench/workbench.desktop.main.ts
@nemanja-milovancevic FYI
Initial implementation of service for core ADS to be able to query for Azure resources from the azurecore extension.
More types of resources can be added later - this is just the first bit to keep it focused on the bits required to hook everything up.
> Add AzureAccount service

- extensions/arc/package.json
- extensions/azcli/package.json
- Bumped arc to 1.0.0 and azcli to 1.0.0 for GA for Feb release
- Bumped azdata version requirement to 1.35
> Bumped versions of arc and azcli to 1.0.0 for GA

- extensions/arc/package.json
- extensions/azcli/package.json
- Updates version of arc to 1.0.0
- Updates version of azcli to 1.0.0
- Updates min required azdata for both extensions to be 1.35
Closes https://github.com/microsoft/azuredatastudio/issues/18521
> Updated package.json for arc and azcli extensions to version 1.0.0

- src/vs/workbench/contrib/welcome/telemetryOptOut/browser/telemetryOptOut.ts
- test/smoke/src/sql/areas/queryEditor/queryEditor.test.ts
The recent changes to the telemetry opt out feature have created a notification toast that is blocking the connect button thereby failing query editor smoke tests. This PR clears that toast notification before running those tests.
Example of the bug:
This PR fixes #18515 and fixes https://github.com/microsoft/azuredatastudio/issues/18523
> Fixing query editor smoke test

- src/vs/workbench/contrib/welcome/telemetryOptOut/electron-sandbox/telemetryOptOut.ts
While diffing release 1.34 code to the main code I found out that this carbon edit was not ported back.
> Bringing back leftover changes for telemetry opt-out

- extensions/theme-carbon/themes/dark_carbon.json
- extensions/theme-carbon/themes/light_carbon.json
This PR fixes #18528 
root cause: the color is not defined.
fix: copied the values from vscode theme files.
before:
after:
> fix 'Read More' icon not visible issue

- build/azure-pipelines/darwin/sql-product-build-darwin-signing.yml
.NET 2.1 is being removed from all hosted agents 
https://github.com/actions/virtual-environments/issues/4871
This is currently required for the signing task and so install it manually for now until the signing task can be updated to not require 2.1. Note that this is only required for Macs though - the other OSes have been updated to use .NET 6 per https://marketplace.visualstudio.com/items?itemName=SFP.build-tasks&targetId=465e99f0-a0f9-4257-95e0-04c716327b00
```
11/29/2021 (CodeSign task v1.9.101, ScanTask v1.6.90)
Add .net core 6 support (not include Mac OS)
```
> Fix Mac signing

- extensionsGallery.json
Fixes https://github.com/microsoft/azuredatastudio/issues/18546
Two types of fixes : 
1. github.com/raw.github.com links changed to raw.githubusercontent.com. The first two don't allow any origin so our request fails because we're set as the `vscode-file://vscode-app` origin
2. All others moving content to be hosted on our blob storage for now until follow up actions can be taken.
Most likely we'll want to start hosting all content ourselves since this is not only safer in general (not loading stuff we have no control over) but also means we won't get broken in the future if they decide to change their access policies. But that can be done as a follow up task since that'll take a lot longer to move everything over.
> Fix broken extension gallery links

- extensionsGallery-insider.json
- extensionsGallery.json
- scripts/validateGalleries.js
Their storage account was updated to allow the vscode-file://vscode-app origin so adding them to the allowed list so they can continue to own their assets.
@nahk-ivanov FYI
> Revert oracle ext assets back

- src/sql/platform/accounts/common/interfaces.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
- src/sql/workbench/services/resourceProvider/browser/firewallRuleDialogController.ts
- src/sql/workbench/test/electron-browser/api/extHostAccountManagement.test.ts
We already have this defined in https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/api/common/sqlExtHostTypes.ts#L434 - there's no reason to have it duplicated like this.
> Remove duplicate AzureResource enum

- .github/workflows/update-galleries-list-reminder.yml
This should fix the errors we see running this workflow when external contributors open a PR. PRs from forks are locked down on purpose so have to specify the types of permissions a workflow should have. (we still have control over approving the workflow to run in the first place too)
> Fix gallery workflow errors from external contributors

- extensions/notebook/yarn.lock
- src/sql/workbench/contrib/notebook/browser/cellViews/code.component.html
- src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/code.css
- src/sql/workbench/contrib/notebook/browser/notebookStyles.ts
- src/sql/workbench/contrib/notebook/test/stubs.ts
- src/sql/workbench/services/notebook/browser/models/cell.ts
- src/sql/workbench/services/notebook/browser/notebookService.ts
- src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts
- src/vs/workbench/contrib/notebook/browser/contrib/coreActions.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
In order to support polyglot notebooks (i.e. .NET Interactive) we need to be able to configure cell languages individually. So, this change adds a language picker to the lower right corner of the cell, similar to what VS Code has. Language lookup is based off of the current provider and kernel display name, so if we're using Interactive we get all of its languages, but when using the Python 3 kernel we only get Python as an option.
> Add language picker to notebook cells.

- build/azure-pipelines/web/sql-product-build-web.yml
The smoke tests have been failing in the web builds recently due to non-product bug.  This disables this step of build pipeline until we have time to investigate and fix.
> Disable smoke tests in web build

- extensions/sql-migration/src/wizard/targetSelectionPage.ts
- extensions/sql-migration/src/wizard/wizardController.ts
The telemetry event to get subscriptionid, tenantid and other information was not working at 'OnPageLeave' event of target selection page. I noticed we already collect similar information at page clicks. To avoid duplicating same telemetry event removing telemetry from 'onpageleave' and adding 'tenantid' to 'PageButtonClick'. This event takes care of all possible clicks (prev/next) similar to 'OnPageLeave'.
Tested locally using latest -
> Fixing telemetry

- extensions/data-workspace/src/dialogs/projectDashboard.ts
- extensions/machine-learning/src/views/widgets/dashboardWidget.ts
- extensions/sql-migration/src/dashboard/sqlServerDashboard.ts
With latest VS Code merge files loaded by ADS are required to use the vscode-file scheme, not the file scheme.
Having extensions contribute CSS like this directly isn't something that VS Code supports hence why there isn't any built in functionality for this - and in general it's not something we should be encouraging people to do so I'm not planning on adding any helper functionality for this. The fix is easy enough to do on a one-off basis as needed.
I checked all our extensions and these were the only ones that I found that did this - although if anyone knows of any others please let me know!
Before:
After:
Before:
After:
Before:
After:
> Fix some more images not loading

- src/sql/workbench/contrib/notebook/browser/cellToolbarActions.ts
- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
- src/sql/workbench/contrib/notebook/test/electron-browser/notebookModel.test.ts
- src/sql/workbench/contrib/notebook/test/stubs.ts
- src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
> Preserve previous code cell's language when creating a new code cell from an existing context.

- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
Currently there's a bug in text cells where if you double click on text to highlight it, the highlight is cleared and the cursor is reset to the beginning of the editor. This is because we update the current cell to be the active cell when double clicking on it, regardless of whether it's already in edit mode. If a cell is already the active cell, then calling updateActiveCell on it clears its edit mode before enabling it again, and clearing the edit mode is what resets the cursor position.
This PR fixes #18493
> Only update active cell if the cell isn't currently in edit mode.

- extensions/sql-database-projects/resources/templates/newSdkSqlProjectTemplate.xml
- extensions/sql-database-projects/src/test/baselines/newSdkStyleSqlProjectSdkImportAttributeBaseline.xml
- extensions/sql-database-projects/src/test/baselines/newSdkStyleSqlProjectSdkNodeBaseline.xml
- extensions/sql-database-projects/src/test/baselines/newSdkStyleSqlProjectSdkProjectAttributeBaseline.xml
- extensions/sql-database-projects/src/test/baselines/openSdkStyleSqlProjectBaseline.xml
- extensions/sql-database-projects/src/test/baselines/openSdkStyleSqlProjectNoProjectGuidBaseline.xml
- extensions/sql-database-projects/src/test/baselines/openSdkStyleSqlProjectWithBuildRemoveBaseline.xml
- extensions/sql-database-projects/src/test/baselines/openSdkStyleSqlProjectWithFilesSpecifiedBaseline.xml
- extensions/sql-database-projects/src/test/baselines/openSdkStyleSqlProjectWithGlobsSpecifiedBaseline.xml
This updates the new SDK project template to have the latest Microsoft.Build.Sql SDK version and also updates the test templates to reference a valid version of the SDK. The tests using those templates weren't failing since they weren't actually building the projects, but it's still good to update them to reference a valid SDK version.
> update Microsoft.Build.Sql version to 0.1.3-preview in templates

- build/azure-pipelines/sql-product-compile.yml
- src/sql/azdata.proposed.d.ts
This was something VS Code added a while back that we didn't bring over to our pipelines. There's no reason we should be publishing source maps for every build - adhoc runs and PR validation runs for example shouldn't.
> Add option to not publish source maps

- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
In this PR, we fix the CSS overflow behavior on the migration cutover dialog in order to avoid truncating fields such as the file names of the last applied backup files.
Previously, it looked like this, making it impossible for users to see the full file name if it was too long:
Now, the fields will wrap properly, making it possible to read full file names:
> [SQL Migration] Fix overflow behavior on migration cutover dialog to avoid truncating backup file names

- extensions/sql-migration/src/models/stateMachine.ts
In this PR, we fix SKU recommendations not working for named (non-default) instances. As part of the API call made to request the generation of SKU recommendations, the instance name must be passed in order to construct the file names that the assessment NuGet expects when reading collected performance data. However, the previous approach(es) used to derive the instance name would only look at the _machine_ name:
(note that this named instance is actually named `RATRUONG-P330\MSSQLSERVER01`)
This would work for unnamed (default) instances since specifying the default instance name is optional, but when trying with named instances, this would result in an error implying that data was not collected, since the NuGet would be looking for the wrong file names (thinking it's an unnamed …
> [SQL Migration] Fix SKU recommendations not working for named (non-default) instances

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
In this PR, we add new help text info boxes to the database backup page in the SQL migration extension, in two places:
1) at the top, when the user is prompted to select their backup location, they are now informed that backups must be taken with checksums enabled:
This is shown in all scenarios, for both network share and blob container storage, for both MI and VM targets, for both online and offline migrations.
2) further down the page, when the user is prompted to enter storage account details, they are now informed that they cannot use a storage account that has a private endpoint. The UI is a bit different depending on whether the backups are on a network share or in a blob container, but the same message is shown:
Network share scenario:
Blob container scenario:
This is shown in all …
> [SQL Migration] Add more help text to database backup page

- src/sql/base/browser/ui/table/tableCellEditorFactory.ts
- src/sql/workbench/browser/designer/designer.ts
**This PR fixes #18700** 
currently, user has to move the focus to a different cell in order to commit the change, this is the default slick grid behavior.
with automatic commit:
**This PR fixes #18699** 
root cause: the editor component is not wired to the theme change event.
Before:
After:
> table designer bug fixes

- src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts
VS Code emits a "onNotebook:*" activation event whenever a notebook is opened, in addition to a more specific one for the provider e.g. "onNotebook:jupyter-notebook". We were missing that previous general event, so I've added it in this PR.
For reference, this is where VS Code emits their events: https://github.com/microsoft/azuredatastudio/blob/main/src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts#L483
> Add missing onNotebook:* activation event for VS Code notebook compatibility.

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/dialogs/newProjectQuickpick.ts
This adds SDK-style as an option in the vscode new project quickpick if a template has specified it as an option. This was added to the new project dialog in ADS in https://github.com/microsoft/azuredatastudio/pull/18698.
> add SDK style option to new project quickpick

- extensions/sql-bindings/package.json
- extensions/sql-bindings/src/contracts/azureFunctions/azureFunctionsContracts.ts
- extensions/sql-bindings/src/dialogs/addSqlBindingQuickpick.ts
- extensions/sql-bindings/src/extension.ts
- extensions/sql-bindings/src/services/azureFunctionsService.ts
- extensions/sql-bindings/src/sql-bindings.d.ts
- extensions/sql-bindings/src/sqlbindings.d.ts
- extensions/sql-bindings/src/test/testUtils.ts
- extensions/sql-bindings/src/typings/vscode-mssql.d.ts
- extensions/sql-bindings/yarn.lock
This PR adds remaining logic that was dependent on STS in vscode-mssql to SQL bindings extension. Now that there is a sendRequest API in mssql we can then bring over the logic for both addSQLBinding and getAzureFunctions. I also added these to our own API to be utilized as well. 
For the moment I had to delete the vscode-mssql typings in order to make sure the build passes. I will be updating the vscode-mssql typings as well with the corresponding updates.
> Add rest of sql-bindings/azure funcs logic to sql bindings ext

- src/sql/workbench/contrib/charts/browser/chartView.ts
- src/sql/workbench/contrib/charts/browser/graphInsight.ts
This PR fixes #3538 
noticed this today while testing the feature and found this old issue.
Root cause: we are not differentiating 0 and undefined when processing the options.
Fix: check for undefined explicitly.
With the fix:
> fix the issue that chart axis's min/max value can't be zero

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/dialogs/newProjectQuickpick.ts
Selecting the target platform for new sql projects was added in #16091. This adds the same option to the new project quickpick in vscode. This step only shows if a template provides target platforms. If a default target platform is specified, then the default target platform is moved to the top of the list and has "Default" next to it like in the screenshot below.
> Add select target platform to new project quickpick

- extensions/notebook/package.json
- src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts
- src/sql/workbench/api/common/extHostNotebookDocumentsAndEditors.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
- src/sql/workbench/common/constants.ts
- src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
- src/sql/workbench/contrib/notebook/browser/models/untitledNotebookInput.ts
- src/sql/workbench/contrib/notebook/test/stubs.ts
- src/sql/workbench/services/notebook/browser/models/notebookUtils.ts
- src/sql/workbench/services/notebook/browser/notebookService.ts
- src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts
After some investigation I found out that we didn't actually support the .NET Interactive notebook format (.dib files) for untitled files. Creating a new notebook with the dib format via palette command would work, but underneath it would always be ipynb and would only prompt to save as ipynb. This change adds the proper support for untitled dib files, so that they're created and saved properly, as well as having the correct kernels displayed.
This PR fixes #18642
> Correctly handle creating and saving untitled notebook .dib files.

- extensions/data-workspace/package.json
- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/common/constants.ts
This adds "(Preview)" to the SDK-style project checkbox label in the create project from db dialog, to match the label new project dialog. Also bumping the extension versions so we don't forget before the next release.
> Add preview for SDK-style projects checkbox and bump extension versions

- src/sql/azdata.proposed.d.ts
- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
Currently validation errors (user input validation and schema validation) are treated no differently compared to unexpected errors, when looking at the telemetry report, we want to know how many application errors users ran into, with current implementation, we won't have a clear answer.
with this change, the table designer provider will explicitly include the validation error in the response.
I personally don't think we need to collect data for the validation errors, but we are going to have a telemetry review discussion next week sometime, we can always add telemetry for it if we decide to.
> table designer - handle validation error differently

- extensions/sql-bindings/src/test/testUtils.ts
Cleaning this up to just use basic mocks instead of hard definitions so that we don't have to keep updating these every time the underlying type changes.
> Cleanup sql bindings test utils

- extensions/liveshare/package.json
- extensions/liveshare/src/hostSessionManager.ts
- extensions/liveshare/src/main.ts
- extensions/liveshare/yarn.lock
- extensions/sql-bindings/package.json
- extensions/sql-bindings/yarn.lock
- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/yarn.lock
Noticed some extensions still had this package, but we switched to eslint a while back (and it's run from the top level now using `yarn extensions-lint`) so removing these since they're unnecessary now.
> Remove tslint from extensions

- src/sql/base/browser/ui/table/tableCellEditorFactory.ts
- src/sql/workbench/browser/designer/designer.ts
a few days ago I changed the commit trigger condition for input box https://github.com/microsoft/azuredatastudio/pull/18701, the changes will committed as the user is typing (200ms delay), as we are adding validation, this turns out to be a very annoying thing, so I am reverting to is previous behavior (SSDT's behavior). 
One of the goal for my previous PR was to solve the problem that user has to navigate to a different cell in order to commit the change. this PR won't regress this feature.
also, I tested and confirmed that the commit event won't be triggered twice.
1. when navigating to a different cell, the navigation is controlled by slickgrid, the change will be committed and the inputbox will be disposed, so the losefocus event will never fire.
2. when move focus away from the grid, …
> change the trigger of inputbox commit event

- extensions/dacpac/src/telemetry.ts
- extensions/dacpac/src/wizard/dataTierApplicationWizard.ts
Cleaning up the telemetry in the dacpac extension that was added last year in #13859. Summary of the changes:
- send ErrorEvents when a DacFx operation fails instead of previously it was an ActionEvent with ExportStatus/ImportStatus/etc as a property
- removed most of the different telemetry view enums. This is all in the Data tier application wizard and the action names are enough to differentiate
- removed properties that were always true or never got sent
-  removed unnecessary try catches. If there was an exception thrown in STS, it would be reflected in the result.success being false. I checked in kusto to verify that the exceptionOccurred property was never true for any event sent from the dacpac extension, so this confirms that the code wasn't getting called. 
- removed unused …
> cleanup dacpac extension telemetry

- src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts
- src/sql/workbench/services/notebook/browser/models/cell.ts
Unit test for last edit mode changes.
Updated the showMarkdown and showPreview values to their defaults when not in edit mode. This is because the currentMode value is not reflecting the correct value since these values are not updated on edit mode change (i.e. whenever user comes out of edit mode, they still retain their values while on edit mode)
Tested the basic scenarios after the update and didn't find any behavioral changes.
> Add test for last edit mode

- src/sql/workbench/services/notebook/browser/models/notebookUtils.ts
- src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts
In my recent .dib file PR, I added a small optimization to the NotebookService.getProvidersForFileType() method that removed duplicate providers from the output. However, if the retrieved providers array was undefined (like for an unknown file type), then the method would now return an empty array instead of undefined. As a result, when trying to open an unknown notebook file type, we wouldn't fall back to the default notebook file behavior (i.e. ipynb), because we were specifically checking for undefined providers in that edge case. This change now correctly returns undefined from getProvidersForFileType(), and also checks the providers array length in getProvidersForFileName() (in addition to undefined) to protect against future issues like this.
This PR fixes #18777
> Fix issues with unknown notebook file types not opening as a default notebook.

- extensions/dacpac/src/wizard/dataTierApplicationWizard.ts
Adding a few more properties to send from the dacpac wizard:
- page and selected operation when cancelling to see at which point people are cancelling out of the wizard since it's the second most used action.
- send version for extract. I suspect no one is changing this from the default version (1.0.0.0), so I'd like to get rid of the option if it isn't getting used.
> Add a few more properties for dacpac telemetry

- .github/workflows/ci.yml
- build/azure-pipelines/darwin/sql-product-build-darwin.yml
- build/azure-pipelines/linux/sql-product-build-linux.yml
- build/lib/compilation.js
- build/lib/compilation.ts
- src/vs/workbench/browser/parts/editor/editorGroupView.ts
- test/unit/coverage.js
I was able to track down what was causing the coverage to hang, but in the end I don't have a fully clear idea of why it's failing for us and presumably not for VS Code.
The line in question that led me to the fix was this : 
`[4225:0318/190144.273645:INFO:CONSOLE(109)] "Uncaught SyntaxError: Unexpected token '??'", source: vm.js (109)`
After digging around in loader.js for a bit I was able to get it to spit out what file it came from and from there was just a matter of seeing which one of the ??'s was causing the issue.
There are numerous other reports of similar invalid code generation being done by instanbul, but since this fixes the issue and is relatively scoped I chose to end my investigation here since there isn't much value to be gained currently from digging into it more. …
> Fix and enable core unit test coverage

- src/vs/platform/files/test/browser/fileService.test.ts
- src/vs/workbench/contrib/notebook/browser/contrib/cellOperations/test/cellOperations.test.ts
- src/vs/workbench/contrib/testing/test/common/testResultService.test.ts
Hopefully temporary - going to investigate why these only fail when --coverage is set (they pass without that)
VS Code has the same issue
> Disable broken tests

- test/automation/src/sql/notebook.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
These new smoke tests cover all the text toolbar actions besides links and font size. Those last two have secondary windows that pop up, so I'm still figuring those out. I'll take care of them in next week's round of fundamentals.
> Add smoke tests for text cell toolbar actions.

- extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts
This PR fixes #18074. This sorts the databases dropdown to have the system dbs at the bottom of the list so it's easier to find user dbs.
> move system dbs to bottom of the list in update project from db dialog

- extensions/sql-database-projects/package.json
The old projects view sqlDatabaseProjectsView was removed in https://github.com/microsoft/azuredatastudio/pull/12563 in the data-workspace branch, but these were missed since they got added in main before the data-workspace branch was merged.
> cleanup sql database projects package.json

- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
See corresponding backend sqltoolsservice PR: https://github.com/microsoft/sqltoolsservice/pull/1441
---
In this PR, we fix the SQL migration extension's 'assessment results' dialog to show the correct recommendations provided by the assessment NuGet when viewing detected issues. Previously, the recommendation provided to the user was actually just the preview text for the 'more info' link duplicated. 
Before:
After:
The results now match the results provided by DMA exactly:
Also, we now show 'N/A' when a recommendation is not available. Since it's possible for the assessment NuGet to not provide a recommendation, it was possible for both the recommendation text and the preview text for the 'more info' link to be completely blank since both were mapped to the same thing.
Before:
After:
> [SQL Migration] Show correct recommendation when viewing issues in assessment results

- extensions/admin-tool-ext-win/package.json
- extensions/admin-tool-ext-win/yarn.lock
- extensions/azuremonitor/package.json
- extensions/azuremonitor/yarn.lock
- extensions/import/package.json
- extensions/import/yarn.lock
- extensions/kusto/package.json
- extensions/kusto/yarn.lock
- extensions/mssql/package.json
- extensions/mssql/yarn.lock
the new version has a new version of mkdirp which is no longer relying on the minimist package that were having security issues.
tested on all platforms and made sure STS downloading went well.
> new service downloader version

- src/vs/loader.js
Related to https://github.com/microsoft/azuredatastudio/pull/18781 - it took me a long time to track down where this failure was coming from because the error being thrown wasn't very useful : 
`Uncaught SyntaxError: Unexpected token '??'`
this will make it now display something like this 
`Uncaught Error: Error compiling file:///.../vs/workbench/browser/parts/editor/editorGroupView.js. SyntaxError: Unexpected token '??'`
PR for VS Code : https://github.com/microsoft/vscode-loader/pull/37
> Throw more detailed error when compilation fails

- extensions/mssql/src/contracts.ts
- extensions/mssql/src/mssql.d.ts
- extensions/mssql/src/schemaCompare/schemaCompareService.ts
- extensions/schema-compare/src/test/testSchemaCompareService.ts
This PR fixes #18128. schemaComparePublishChanges is no longer used after the update project from db changes replaced it with schemaComparePublishProjectChanges and schemaComparePublishDatabaseChanges.
> remove unused SchemaComparePublishChanges

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/project.test.ts
This adds basic migration from legacy style to SDK-style sqlproj. It removes the ADS and SSDT SqlTargets imports and adds the SDK node. A backup copy of the sqlproj gets created before a legacy project gets converted.
I'll send out a separate PR to expose this in the project tree and for the option to further simplify the sqlproj (remove Build includes, default properties) later, to help keep these PRs easier to review :)
> add initial SDK-style project migration

- extensions/schema-compare/src/schemaCompareMainWindow.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
This PR fixes #18849. When updating a project by doing schema compare apply, the project file was not actually getting updated and there was an error saying update failed, even though the task said it completed successfully. result.ErrorMessage was getting returned as null when the operation was successful, but that doesn't equal an empty string, which is what these checks were expecting.
This was introduced by #18532, which was trying to solve the opposite problem where a success notification was showing when there was an error.
> fix sql project not getting updated after schema compare update

- extensionsGallery-insider.json
Just noticed I didn't update the year to 2022 when I updated these two extensions in insiders last month.
> update the lastUpdated year to 2022 for schema compare and sql database projects

- extensionsGallery-insider.json
- extensionsGallery.json
The upload instructions were a little unclear on who does what, so I already uploaded the vsix files to our extension blob storage.
.NET Interactive vsix: https://sqlopsextensions.blob.core.windows.net/extensions/dotnet-interactive-vscode/dotnet-interactive-vscode-1.0.3175020.vsix
Jupyter vsix: https://sqlopsextensions.blob.core.windows.net/extensions/jupyter/ms-toolsai.jupyter-2021.8.1046824664.vsix
> Add .NET Interactive and Jupyter extensions to stable and insiders.

- extensionsGallery-insider.json
These need to match the publisher ID in the package.json, otherwise we get issues like not installing the dependent extensions automatically from the gallery.
> Fix publisher IDs for .NET extensions

- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR fixes #18707
previously 'undefined' and empty string are not added to the filter list. I am adding them to the list as requested by user. also added handled the whitespace(s) while implementing the feature.
filter by NULL
filter by Blanks
filter by string
exported results:
```
[
{
"col1": " ",
"col2": "1 space"
},
{
"col1": null,
"col2": "NULL"
},
{
"col1": "abc",
"col2": "abc"
},
{
"col1": null,
"col2": "NULL"
},
{
"col1": "",
"col2": "Empty"
},
{
"col1": "bcd",
"col2": "bcd"
},
{
"col1": "   ",
"col2": "3 spaces"
}
]
```
> handle special values in the table filter

- extensions/dacpac/src/wizard/dataTierApplicationWizard.ts
This PR fixes #18870. It was a little confusing showing an error notification with "unknown" failure, but the error is actually shown in the tasks pane.
> don't show error notification if no error message in dacpac extension

- src/sql/base/query/browser/untitledQueryEditorInput.ts
- src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
This PR fixes #18800
in this PR: https://github.com/microsoft/azuredatastudio/pull/18402, I fixed the scenario that the auto language is changing the language mode for newly opened query editors. but missed some other places that the UntitledQueryEditorInput is created, for example, the untitled query editors restored from previous ADS sessions. and as a result, auto language detection will still kick in for it.
fix:
instead of adding the mode setting all over the places, I am moving it to the untitledQueryEditorInput constructor to make sure the mode is set regardless of entry points. FileQueryEditorInput do not have this problem because it is backed by a .sql file and no language detection is needed.
> fix language change issue

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/baselines/baselines.ts
- extensions/sql-database-projects/src/test/baselines/newSqlProjectNoPropertiesFolderBaseline.xml
- extensions/sql-database-projects/src/test/project.test.ts
- extensions/sql-database-projects/src/test/testUtils.ts
This updates the conversion from legacy to sdk-style sqlproj to simplify the project file so that the Build and Folder Includes for files and folders included by the default **/*.sql glob are removed, along with excluding files that are in the project folder, but were not included in the legacy sqlproj. This is important for keeping file parity, because without this, it's possible that files would get included by the glob even though they weren't listed in the legacy sqlproj.
I added tests for various scenarios, but please let me know if there are other scenarios I missed and should add tests for :)
> Remove build and folder includes when converting to SDK-style project

- src/sql/workbench/services/connection/browser/connectionWidget.ts
This PR fixes #17894
Resolves unknown tenant issue when adding a connection for an Azure account with multiple tenants.
The error was occurring because `accountInfo.azureTenantId` is set to `undefined` outside the async callback, but contains a valid tenant ID once the callback is executing. Since `tenantId` was being initialized outside the callback and referenced in the callback body instead of `accountInfo.azureTenantId`, an undefined tenant error would appear when a user would try to connect to Azure Data Explorer (Kusto).
By moving the `tenantId` initialization to inside the callback, the error no longer appears.
> Resolves undefined tenant error while adding an account.

- extensions/sql-bindings/src/services/azureFunctionsService.ts
This PR fixes #18928.
Once the user clicks `Create Azure Function Project` on this then we would pre-populate the language to be C# and use .NET 3.1 runtime for the createFunction settings. 
Future outlook:
- Merge this logic and if a user already has an azure function project to just set up one createAzurefunction with SQL binding template instead. (This would require a good bit of refactoring which I will look at once all other bugs are covered).
> Pre-fill prompts with language and .Net runtime 

- extensions/arc/package.json
- extensions/azcli/package.json
Bumping version numbers of arc and azcli extensions to 1.1.0 for both.
> Bump version numbers of arc and azcli extensions

- extensionsGallery-insider.json
- extensionsGallery.json
(To be merged in tomorrow morning after the .vsix files have been generated in tonight's nightly build)
For arc and azcli extensions:
- Bumped version up to 1.1.0
- Updated .vsix file links
- Removed preview flags
> Update extensionsGallery.json version bump for arc and azcli and remove Preview flag

- extensions/sql-bindings/src/services/azureFunctionsService.ts
This PR fixes #18925 and fixes #18927.
This will not show any error if a user exits out of a create an azure function with SQL binding quick pick or create azure function.
In order to know when a user cancels out of the prompt we would need to use the timeout error to understand that it was canceled since that would result in the promise.race rejecting with timeout error. As such we can log this using the errorType we get and still capture any other errors that may potentially happen and send telemetry for it.
> fix timeout warning when exiting create function

- .github/workflows/ci.yml
- build/lib/compilation.js
- build/lib/compilation.ts
- test/unit/README.md
This was changed in https://github.com/microsoft/azuredatastudio/pull/18781/files
Unfortunately, not inlining the source maps breaks debugging. For some reason the JS debugger isn't able to properly load the map.js files, which results in breakpoints not being able to be bound. 
So to unblock that I'm reverting this change by default and will follow up with trying to understand why that isn't working and whether there's a better fix we can make. The `SQL_NO_INLINE_SOURCEMAP` environment variable controls the inlining so we can disable it during CI runs to enable reporting to coveralls to still generate the correct coverage.
> Inline source maps in dev build

- src/sql/workbench/browser/editor/tableDesigner/tableDesignerInput.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/18960
Explicitly check for null or empty string for icons (didn't exist for Folder type node)
> Fix new table issue

- extensions/sql-bindings/src/services/azureFunctionsService.ts
This PR fixes #18932.
After user clicks on `Create Azure Function Project`
it directly opens the templates (instead of asking the user again to create the project):
> Suppress create function prompt

- extensionsGallery-insider.json
This PR updates the insiders extension gallery to bump the sql-migration extension to v1.0.0, and removes the preview flag.
Link to build:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=149768&view=results
PR to update the public extension gallery as well (the intention is to merge this on 4/13 at 8 AM, on time for our service's GA announcement):
https://github.com/microsoft/azuredatastudio/pull/19023
> Update sql-migration to v1.0.0 - Insiders

- extensionsGallery.json
This PR updates the public extension gallery to bump the sql-migration extension to v1.0.0, and removes the preview flag.
VSIX has already been uploaded to the storage account as part of the previous PR to update the insiders extension gallery:
https://github.com/microsoft/azuredatastudio/pull/19022
The intention is to merge this on 4/13 at 8 AM, on time for our service's GA announcement.
> Update sql-migration to v1.0.0

- src/sql/workbench/api/common/extHostNotebook.ts
- src/sql/workbench/api/common/notebooks/adsNotebookController.ts
- src/sql/workbench/api/common/notebooks/vscodeExecuteProvider.ts
- src/vs/workbench/api/common/extHost.api.impl.ts
This fix enables cell cancellation for Interactive notebooks. Without it, an Interactive cell can potentially run forever unless the user restarts the whole application. These changes are limited to the .NET Interactive code path, so there's low risk to the rest of our notebook code.
Port request issue: https://github.com/microsoft/azuredatastudio/issues/18979
> Enable cell cancellation for Interactive notebooks (#19005)

- src/sql/workbench/contrib/executionPlan/browser/executionPlanFileView.ts
- src/sql/workbench/contrib/executionPlan/browser/executionPlanTab.ts
This PR fixes the issue where the actual cache entry was not updated whenever I reinitialized the cache entry. I have also added a check to removeChild node only when the child is contained within the parent container. 
issue: #19046
> Updating the execution plan cache entry whenever the entry is reinitialized 

- src/sql/workbench/contrib/executionPlan/browser/executionPlanView.ts
Issue: #19084
This fixed the broken logic causing some wrong labels in actions used to enable and disable tooltips in execution plan.
> Fixing broken action label logic.

- product.json
I left out Jupyter from the recommended extensions since it's mainly a dependency for Interactive, so not all of its features are supported yet.
This PR fixes #19066
> Add .NET Interactive extension info to product.json.

- src/sql/workbench/services/notebook/browser/models/cell.ts
Currently, prompting for user input with .NET Interactive breaks when mousing over the cell because we always re-focus on the cell when changing the execution state on hover. So if you click run on a cell that prompts for input and mouse anywhere off of the run button, then the input box closes immediately. The hover state is only used to determine if the cell's Run button should be visible, so my fix here is to only fire the hover state change if the cell isn't active, since the Run button is always visible while active anyway.
This PR fixes #18980
> Only update hover execution state if cell is not active.

- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
After introducing the fix for tab navigation through cells,  we focus on the selected cell and we need to update the condition to take that into account.
When clicking, tabbing, and moving the active element in the document is the cell. However when we hit escape to exit edit mode the focus is lost and we need the original check `DOM.isAncestor(this.container.nativeElement, document.activeElement)`
Also, when moving to another cell we need to focus on the new active cell, so the focus doesn't stay in the previous cell.
This pr is for #19058
> Fix cell navigation

- extensions/sql-bindings/src/services/azureFunctionsService.ts
This PR addresses #19105.
We will show only the vscode-mssql warning when the connection isn't able to connect when user is using `Create Azure Function with SQL Binding` from the command palette.
> Removes sql-bindings connection error message

- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/contrib/executionPlan/browser/executionPlanView.ts
- src/sql/workbench/contrib/queryPlan/browser/topOperations.ts
This PR fixes #19102, The original PR that has been merged into the main branch is here: https://github.com/microsoft/azuredatastudio/pull/19039/
The PR adds additional telemetry around query execution plans. The telemetry being added is for the following areas and tracks how areas are being accessed (context menu vs action bar):
- execution plan properties window,
- execution plan zoom functionality,
- execution plan top operations tab
- execution plan open query option
- execution plan node searching
> Telemetry for Query Execution Plans

- extensions/sql-bindings/src/common/constants.ts
- extensions/sql-bindings/src/services/azureFunctionsService.ts
For https://github.com/microsoft/azuredatastudio/issues/19116
Because of https://github.com/microsoft/vscode-azurefunctions/issues/3115 we have to get the folder ourselves before calling createFunction in order to keep the options
I also added the logic to use the sql binding templates so we actually generate a valid function with the binding added already. This should address https://github.com/microsoft/azuredatastudio/issues/18929, although we still want to revisit this flow to make sure there's nothing else that we need to do. 
Now this is what the user sees : 
Prompted to create project (unchanged)
Prompted to browse project file location 
Select folder
Prompted for binding info (no longer prompted for language/framework)
Project is created
> Fix SQL Binding when creating new project

- src/vs/workbench/services/themes/common/themeConfiguration.ts
the name of high contrast theme is wrong and as a result, ADS is not responding the OS theme change.
This PR fixes #18555
> Fix High Contrast theme name

- extensions/sql-bindings/src/common/constants.ts
- extensions/sql-bindings/src/services/azureFunctionsService.ts
* Fix SQL Binding when creating new project
* Use sql binding templates
* fix openDialog to use select
Co-authored-by: Vasu Bhog <vabhog@microsoft.com>
This PR fixes #19116
PR in main: https://github.com/microsoft/azuredatastudio/commit/784f8ac963e008868f7d3f6fac006ff310515d55
> [Port] Fix SQL Binding when creating new project (#19118)

- product.json
The Interactive extension hadn't been uploaded to the stable gallery when I was testing the product.json changes last week, so I couldn't see the changes in the extensions list in my local dev build. I copied the existing format of Publisher Display Name and then extension name for the recommended extensions, but it should be publisher ID instead. I didn't realize installed extensions would still get starred if listed as recommended, in addition to their gallery entry, so I missed this one.
> Fix dotnet-interactive extension's publisher ID in recommended extensions list.

- extensionsGallery-insider.json
Noticed that the Jupyter extension was using the wrong publisher ID here. I didn't notice before because Jupyter was automatically getting installed alongside .NET Interactive just fine, but if you check Interactive's dependencies tab in the gallery page, then nothing shows up. Interestingly, it _does_ show up fine in the dependencies tab after you've installed Interactive.
> Fix publisher ID for Jupyter extension in .NET Interactive's dependencies list.

- extensionsGallery-insider.json
- extensionsGallery.json
A repeat of this other PR, but for the RC1 branch. https://github.com/microsoft/azuredatastudio/pull/19144
I noticed that the Jupyter publisher ID was wrong in the .NET Interactive dependencies list. This doesn't affect install at all, which is why I didn't notice it before, but it does mean there won't be any extension dependencies listed for Interactive on its gallery page.
> Fix Jupyter publisher ID in stable gallery files.

- src/sql/workbench/contrib/dataExplorer/browser/media/dataExplorer.contribution.css
- src/sql/workbench/contrib/notebook/browser/media/notebook.contribution.css
This PR fixes #18587
Notebook and Connections view container are contributed with sql theme icon which are not actually codicons, as a result the focus highlighting does work for them.
just like the other css styles in these 2 files, I am adding a special selector for them to handle it.
before:
after:
> fix activitybar icon focus style

- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
- extensions/sql-database-projects/src/sqldbproj.d.ts
Allows sdk-style option to be specified when creating a project using the exposed sql project apis. Changed the default from true to false so people using this api don't get surprised with an SDk-style project getting created without specifying it. As far as I know, only the data workspace new project dialog uses this and passes this parameter, so nothing should be affected by this default change.
> add sdk-style option to exposed sql project apis

- extensionsGallery.json
Schema compare 1.13.1 was already uploaded, but I put the wrong version in the previous PR https://github.com/microsoft/azuredatastudio/pull/19098 when updating this extension in the RC gallery.
> update schema compare version to 1.13.1

- extensions/sql-bindings/README.md
Just noticed this when installing the extension in VS Code. Removing references to ADS, since we're not shipping the extension there.
> Cleanup references to ADS in SQL Bindings Readme

- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
Fixes #19068 by at least being defensive and not clogging up the console. Tested numerous scenarios and didn't see any differences. There are parts of the text cell component/cell models that would need to be rewritten to truly fix some of these issues, but I'll have another PR to fix some eventing that's gone wrong here in a bit.
Just doing some basic fixes here to get a start in the right direction 😄.
> Notebooks: Preventing "previousSibling of Null" Errors on Cell Selection

- extensionsGallery-insider.json
- extensionsGallery.json
The azdata extension was only used for the Arc extension and doesn't really provide any other useful functionality for users so removing it from the gallery (especially since we deleted the JSON file that was keeping track of the latest released version since we no longer maintained that)
> Remove azdata extension

- package.json
Bump version directly in the release branch for April hotfix.
> Bump version to 1.36.1 for April hotfix.

- extensions/mssql/config.json
Reverts the OE graph icon change which introducing metadata overhead when expanding Tables folder.
> Update SQL Tools Service in release/1.36 for OE icon revert

- src/sql/workbench/api/common/notebooks/notebookUtils.ts
- src/sql/workbench/api/common/notebooks/vscodeExecuteProvider.ts
- src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
- src/sql/workbench/test/electron-browser/api/vscodeNotebookApi.test.ts
We have to do some conversion for .NET Interactive notebooks so that their kernel spec matches our internal representation. This is because our Jupyter notebook kernels line up with the contributed kernels from our notebook extension, but .NET Interactive ipynb notebooks have kernels that don't match the kernel contributed from the Interactive extension. Our code is built on top of Jupyter kernels originally, so a kernelspec is often our source of truth for a lot of notebook details. Thus we need to change up the Interactive notebook's kernelspec in order to get VS Code API compatibility to work. We were already doing this conversion when opening an existing Interactive notebook, but not when changing to the .NET Interactive kernel on the fly in an opened notebook. This change adds that …
> Convert .NET Interactive notebooks' kernel spec to a VS Code compatible kernel when saving.

- extensions/data-workspace/package.json
- extensions/data-workspace/src/common/telemetry.ts
- extensions/data-workspace/src/services/workspaceService.ts
Adding this since someone asked today how many projects people typically have open, but we didn't have an answer for him since we don't currently collect this info. It would also be interesting to see how many excluded projects users typically have.
We do currently send the number of handled and unhandled projects [here](https://github.com/microsoft/azuredatastudio/blob/d774548951aa28dd05f8d209dbd77feac3775508/extensions/data-workspace/src/common/workspaceTreeDataProvider.ts#L84-L89), but it gets fired every time the project tree is refreshed, which can skew the numbers since the project tree gets refreshed for every change on the tree. Sending the number of projects when the extension is activated will give a more accurate picture of how many projects people work with.
> add telemetry on how many projects are open

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
- extensions/sql-bindings/src/dialogs/addSqlBindingQuickpick.ts
- extensions/sql-bindings/src/extension.ts
- extensions/sql-bindings/src/services/azureFunctionsService.ts
- extensions/sql-bindings/src/sql-bindings.d.ts
- extensions/sql-bindings/src/test/dialog/addSqlBindingQuickpick.test.ts
There's no reason to return the entire quickpick object - that's more of an implementation detail and shouldn't ever be something callers need to use.
> Return BindingType directly from promptForBindingType

- extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts
1. Use path.join to ensure that correct path separators are used
2. Remove EOL uses, apparently JSON.stringify will always insert `\n` regardless of the OS
> Fix SQL Bindings tests on windows

- extensions/sql-bindings/.eslintrc.json
- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
- extensions/sql-bindings/src/common/constants.ts
- extensions/sql-bindings/src/common/utils.ts
- extensions/sql-bindings/src/services/azureFunctionsService.ts
Good practice to always have the parameters in the doc comments - this will ensure that we don't miss updating these in PRs
Also removed an unnecessary function - all localized strings should just use the arg format support in the localize function.
> Add require-param rule for sql-bindings

- extensions/arc/package.json
- extensions/azcli/package.json
Updated versions for both azcli and arc to 1.2.0 for the Azure Arc-enabled Data Services release.
> Updating version numbers in package.jsons

- extensionsGallery-insider.json
This change adds one our extensions to insiders gallery:
- **Database Migration Assessment for Oracle**: An extension which provides a mechanism to evaluate the configuration of Oracle Database for migration to Azure
We are currently adding this to insiders gallery and will follow-up with bump up to mainstream in a couple days.
> adding dma extension to insiders gallery

- extensions/azcli/src/api.ts
- extensions/azcli/src/az.ts
- extensions/azcli/src/typings/az-ext.d.ts
Adding SQL MIAA upgrade command to the Azure CLI extension API.
Output of 'az sql mi-arc upgrade --help' for reference:
> Add 'az sql mi-arc upgrade' command to azcli api

- extensionsGallery-insider.json
- extensionsGallery.json
This change adds one of our extensions to ADS marketplace gallery:
**Database Migration Assessment for Oracle**: An extension which provides a mechanism to evaluate the configuration of Oracle Database for migration to Azure
This extension is already available in insider's gallery, and I am following up to bump this up to mainstream for our release.
> Adding DMA for Oracle to extensionsGallery.json

- extensionsGallery-insider.json
- extensionsGallery.json
Updates stable and insiders extension galleries to have arc and azcli version 1.2.0.
> Update extensionsGallery.json for arc and azcli 1.2

- extensions/sql-bindings/package.json
- extensions/sql-bindings/src/common/utils.ts
- extensions/sql-bindings/src/extension.ts
- extensions/sql-bindings/src/typings/ref.d.ts
This PR fixes #19103.
This removes all references of azdata and azuredatastudio apart from the license and vscode-development instructions. We can further discuss where this extension should live in the future.
> Remove ADS/azdata refs from SQL Bindings

- extensions/sql-bindings/src/common/constants.ts
- extensions/sql-bindings/src/services/azureFunctionsService.ts
This PR fixes #19107 and fixes #19106.
After the user chooses a connection from the connection profile list we will show this progress notification:
If we are unable to connect then it will go back to the prompt for choosing a connection. We will also go back to the connection profile picker if the user exits from the database prompt or objectName. 
#19108 - this issue seems to be on vscode-mssql side for promptForConnection since I correctly pass in ignoreFocusOut parameter as true but it does not respect it.
> Fix connection profile prompt for Create Function with SQL Binding

- extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts
This PR fixes #18072. This fixes 2 alignment issues:
- Lines up the location label and input box
- "Action" label now lines up the first radio button, instead of being centered, to be consistent with the other dialogs with radio buttons and labels
before:
after:
> fix alignment in update project from db dialog

- extensions/mssql/src/utils.ts
A problem I've noticed a bunch when looking at the MSSQL logs it that they'll often be incomplete - sometimes only containing part of a log message. 
The issue is that currently we write the log messages but don't flush it manually, which means that it only gets written to disk when the buffer fills up (don't know exactly what that value is, but found a couple references to 8KB on stack overflow).
Given that partial logs like this can easily leave out important information (such as the last few things to happen before a crash...) it seems better to me to enable autoflushing so that every message written is immediately written to disk. 
There is the issue of possible performance implications, but given the relatively low amount of logging we do I don't see that being a huge issue. 
There …
> Enable autoflush for STS logs

- extensions/sql-migration/src/models/stateMachine.ts
Logging three input parameters (scaling factor, target percentile and enable preview features) which might affect the result of SKU recommendation.
> Add 'input parameters' used for recommending SKUs to telemetry

- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
- src/sql/workbench/services/objectExplorer/test/browser/objectExplorerService.test.ts
- src/sql/workbench/services/objectExplorer/test/browser/testObjectExplorerService.ts
This will help us diagnose how often these issues happen and help determine if changes impact node expansion.
To start with this is just tracking timeout since there isn't an easy way to tell the full set of errors that may occur. I plan on following up with looking at adding an optional `errorType` property to the expand response but want to think about that a bit more so getting this in now so we at least have something. 
Note that this is only for the MSSQL provider since we have full control over that. Later on we can add for all providers if needed, but we'll need to do some extra work to ensure we're not sending any personal information coming from a provider (the folder names)
Had to refactor the OE service a bit to get the node type down to the place where the expansion error is …
> Add event to track node expansion errors

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
This PR fixes #13936
Solution context:
The "Cannot read property 'accessToken' of undefined" error was occurring because the `refreshToken` method can return undefined when the `handleInteractionRequired` method determines that there isn't a need for additional user interactions to authenticate a login.
In the event that a firewall rule is missing or the database is in a paused state, the following error message will be seen and the database will need to be checked in the Azure portal.
> Resolves cannot read property 'accessToken' of undefined error while connecting to a cloud DB

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/project.test.ts
If a sql project has these properties with these conditions, this removes them when converting a legacy sql project to SDK-style. For SDK-style projects, these properties are specified in the SDK [here](https://github.com/microsoft/DacFx/blob/main/src/Microsoft.Build.Sql/sdk/Sdk.props#L50-L55).
Removing these:
```
<PropertyGroup>
<VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">11.0</VisualStudioVersion>
<SSDTExists Condition="Exists('$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets')">True</SSDTExists>
<VisualStudioVersion Condition="'$(SSDTExists)' == ''">11.0</VisualStudioVersion>
</PropertyGroup>
```
> remove default VS properties when converting legacy to SDK-style sql projects

- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookActions.test.ts
Running a notebook with parameters is unsupported for untitled notebooks, but currently we don't block that or show a notification.
Fixes https://github.com/microsoft/azuredatastudio/issues/19114
> Show a notification when trying to run an untitled notebook with parameters.

- extensions/markdown-language-features/src/commands/showSource.ts
Cherry-pick https://github.com/microsoft/vscode/commit/d3585388be90a5763d9f491b6e5b674f0af398fd
Fixes #19288
> Make sure markdown.showSource correctly awaits opening the document

- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
I forgot about `getAzdataApi()` and why the import was originally `import type * as azdataType` when I was adding connection api calls in #19129 - turns out it was because the vscode extension doesn't load and throws an error about azdata not being found, even though this dialog isn't actually used in vscode.
> change import back to import type * as azdataType in create project from db dialog

- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
- src/sql/workbench/contrib/notebook/browser/notebookViews/notebookViews.component.ts
I noticed we've had a bunch of toolbar functionality behind preview flags for a long time, and apparently that preview flag is no longer necessary. This change removes the preview restriction for the following features:
1. Button styling for the notebook toolbar.
2. Insert Image and Insert Link dialogs in text cells.
3. Replacing button labels with tooltips for contributed actions in the notebook toolbar and the notebook views toolbar.
I also removed usage of the preview flag from the text cell component since it wasn't being used for anything.
> Remove preview restriction for various notebook toolbar features.

- src/sql/workbench/contrib/executionPlan/browser/azdataGraphView.ts
This PR fixes keyboard navigation in execution plan graph. 
I am also changing the click event to get the selected cell to selection change event. This event works for both clicks and keyboard navigation selection changes. 
This PR fixes #18285
> Fixing keyboard navigation in execution plan graph

- extensions/sql-bindings/package.json
- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
- extensions/sql-bindings/src/createNewProject/addConnectionStringStep.ts
- extensions/sql-bindings/src/services/azureFunctionsService.ts
- extensions/sql-bindings/yarn.lock
- extensions/types/vscode-azurefunctions.api.d.ts
This PR fixes #19203.
PR in https://github.com/microsoft/vscode-azurefunctions/pull/3150.
The issue was the when a user is creating a new azure function project with the command `Create Azure Function with SQL binding` they would eventually be prompted to open the project:
If a user chooses `Open in current window` or `Open in new window` then the logic to add the connectionString to the local.settings.json would not be executed due to the vscode window reloading and therefore the extension host restarting. 
I worked with vscode-azurefunctions team to find a solution that would benefit users generically for azure functions. Allowing for an execute step to execute prior to the OpenFolderStep in order for us to execute the logic with the newly create azure function project that is handled …
> Add Connection String Execute Step for SQL Bindings

- src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR fixes #17634
instead of relying on STS to do the JSON check only on the first row: https://github.com/microsoft/sqltoolsservice/blob/main/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/ResultSet.cs#L740, I am moving the logic to ADS, when a cell is clicked, we check whether it is a json cell and then open a new editor for it.
similarly render the cell as hyperlink if it is a json cell.
before:
after:
> fix json cell handling issue

- build/filters.js
Only really matters for local runs, but the stuff in these shouldn't be ran through the check.
> Ignore coverage folders during hygiene

- extensionsGallery-insider.json
The built vsix for this new version can be found here: https://dev.azure.com/dnceng/_apis/resources/Containers/10386963/vscode?itemPath=vscode%2Fads-stable%2Fdotnet-interactive-vscode-1.0.3255010.vsix
> Update .NET Interactive extension version in insiders gallery.

- package.json
- yarn.lock
One of the automated systems recommended to update this dependency.  This is the version vscode is currently using in their `main` branch.
> Update keytar to latest 7.X release

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/common/httpClient.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/dialogs/deployDatabaseQuickpick.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
- extensions/sql-database-projects/src/dialogs/utils.ts
- extensions/sql-database-projects/src/models/deploy/deployProfile.ts
- extensions/sql-database-projects/src/test/utils.test.ts
- extensions/sql-database-projects/yarn.lock
Adding a new UI for SQL project extension in VS code, to list the image tags for user to choose from. Currently sql project hard code the tag to "latest" but user should be able to select from list of tags specially in ARM platforms which one of the older Azure SQL Edge image supports. If user doesn't select any tag, we default to empty string now which makes docker client to choose the right tag that matches with the host platform. The list is also filtered to the ones that matches with project target version. For instance for target project Azure or 2019, there's no point to show 2017 tags.
> SQL Project Deploy to docker container - Adding a UI for user to select docker image tag

- test/smoke/src/sql/areas/notebook/notebook.test.ts
Skipping the manage packages test for now. 
The test is unstable because of the way that the wizard is initialized. While debugging I realized the wizard contents get reset twice. This isn't an issue for users since it happens really quickly (before the user can type anything). But it makes the smoke test unstable since sometimes, 'pyarrow' gets typed and then cleared by the reset. I need to do some refactoring for how the wizard initialization.
> Skip manage packages test

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
- extensions/sql-bindings/src/common/constants.ts
Using the same description as the official [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-azure-sql?tabs=in-process&pivots=programming-language-csharp)
This PR fixes https://github.com/microsoft/azuredatastudio/issues/19340
> Add description of each binding type

- extensions/arc/package.nls.json
- extensions/arc/src/common/pricingUtils.ts
Changes: 
- Set price per vcore for Business Critical SQL MI to $434 for LicenseIncluded and $160 for BasePrice.
- Removed [Preview] label from Business Critical option in SQL MI create wizard
> Take SQL MI billing Business Critical out of preview

- extensions/mssql/config.json
Fixes failing test. 
Also bringing in a fix for backup devicetype.
> Bump STS to .250

- src/sql/workbench/browser/designer/designer.ts
- src/sql/workbench/browser/designer/designerIssuesTabPanelView.ts
- src/sql/workbench/browser/designer/interfaces.ts
- src/sql/workbench/browser/designer/media/designer.css
This PR fixes https://github.com/microsoft/azuredatastudio/issues/19078
STS PR: https://github.com/microsoft/sqltoolsservice/pull/1494
Also adds the functionality to add clickable links to designer errors in the Issues tab:
> Added clickable more info links to designer validation issues

- src/sql/platform/capabilities/common/capabilitiesService.ts
- src/sql/workbench/services/connection/browser/connectionDialogWidget.ts
- src/sql/workbench/services/connection/test/browser/connectionDialogService.test.ts
- src/sql/workbench/services/connection/test/browser/connectionDialogWidget.test.ts
- src/sql/workbench/services/connection/test/browser/testConnectionDialogWidget.ts
This PR fixes #19299
When the selected resource's provider type isn't supported, instead of doing nothing I am showing a prompt with the problem statement and an action to go to the extensions view.
Ideally, the extension metadata in the extension gallery should include the supported providers and in ADS we can query and directly show the extension, but that is not a trivial change, and the priority doesn't seem high enough to justify the cost since user can easily find the extension in the extensions view.
**Before**:
Nothing helps when you click on a resource that is not supported.
**After**:
Provider not added to the mapping list:
provider with known extension:
> show proper message when extension is not installed for a connection provider

- extensions/sql-migration/src/dialog/migrationCutover/migrationCutoverDialog.ts
fix bug where migration details target server name is displaying target database name instead.
> fix invalid bug target server name showing target database name

- extensions/sql-bindings/package.json
- extensions/sql-bindings/yarn.lock
Usage added in https://github.com/microsoft/azuredatastudio/pull/18912 but the package was never added as a dependency. Any direct dependencies like this need to be added to the dependency list or stuff may break.
In this case it happened to work because webpacking picked up the root uuid dependency, but that's generally unsafe to rely on and was making it so this was broken for me when using an un-webpacked version.
> Add UUID dependency to sql-bindings

- extensions/arc/src/models/controllerModel.ts
- extensions/arc/src/ui/dashboards/controller/controllerDashboard.ts
- extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts
- extensions/arc/src/ui/dashboards/controller/controllerUpgrades.ts
- extensions/arc/src/ui/dashboards/miaa/miaaBackupsPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaDashboard.ts
- extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaUpgradeManagementPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresDashboard.ts
- extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts
- extensions/arc/src/ui/dashboards/postgres/postgresPropertiesPage.ts
- extensions/arc/src/ui/dialogs/connectControllerDialog.ts
- extensions/arc/src/ui/tree/controllerTreeNode.ts
- extensions/azcli/src/api.ts
- extensions/azcli/src/az.ts
- extensions/azcli/src/test/az.test.ts
- extensions/azcli/src/typings/az-ext.d.ts
Changes:
- Changed az arcdata dc config show to take resourceGroup as a param for direct mode
- Handled direct mode and indirect mode az arcdata dc config show differences
- Made refresh() call either refreshDirectMode() or refreshIndirectMode() depending on connectionMode
- Added resourceGroup as a param for all calls to refresh()
This is an example of the refresh button that will call refresh():
> Make data controller refresh handle direct mode

- extensions/integration-tests/package.json
- extensions/integration-tests/setEnvironmentVariables.js
- extensions/integration-tests/yarn.lock
This PR fixes #https://github.com/microsoft/azuredatastudio/security/dependabot/249
the library we were using is no longer supported and the script is no longer working, I am updating it to use the new library to retrieve AKV secrets and with this change the offending lib 'async' is no longer being referenced.
> fix a dependent bot issue

- extensions/sql-database-projects/src/controllers/mainController.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
- extensions/sql-database-projects/src/sqldbproj.d.ts
- extensions/sql-database-projects/src/templates/templates.ts
- extensions/sql-database-projects/src/test/project.test.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
Need access to this for some work I'm doing. 
In doing this I needed to slightly change the function signatures to take in an ISqlProject, which then also required added the deployment script properties to the public interface. Didn't seem like a bad change so getting that in as well.
And finally converting the list of item types to an enum for ease of use. They're still passed around as strings in the codebase so no functional change.
I really would have preferred this to live on the ISqlProject itself (so you'd call project.addItem(...) instead) but unfortunately addItem requires access to the project controller which the project itself doesn't know about and refactoring all that was out of scope of what I wanted to be doing here. So leaving it as is for now and I may look into doing …
> Move promptAddItem to extension API

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
This PR fixes #19436.
We were not awaiting the inputBox result and as a result, we went straight to the function name prompt.
> Fixes manually enter table name due to await

- test/automation/src/sql/configurePythonDialog.ts
Fixes these issues blocking the python smoke tests:
1. The select box option selector was using a unix path separator, which would fail on Windows.
2. The select box wait in the finally statement was looking for exactly the monaco-select-box class, but there were several classes present.
> Fix Python smoke test failures.

- extensions/import/yarn.lock
this is a follow up of https://github.com/microsoft/azuredatastudio/pull/19455
I missed to update the minimist version in import extension.
This PR fixes #https://github.com/microsoft/azuredatastudio/security/dependabot/234
> bump minimist for import extension

- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/dialog/createSqlMigrationService/createSqlMigrationServiceDialog.ts
fix incorrect parameters 'resource group name' instead of 'resource group id' being passed into the following api's.
* get migration service status
* get migration service authentication keys
> fix resource group parameter, name

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
This PR fixes #19451.
We should return undefined so that the azureFunctionService would then continue back to prompt the user to choose the connection profile.
> fix loop for cancelling out databases

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
- extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts
This PR fixes #19452.
Short-term fix for non-SQL auth types only.
Removes `Password=******;` from connection string.
> remove password for connection string non sql auth types

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- yarn.lock
This PR bumps azdataGraph version from 0.0.26 to 0.0.27, which fixes a bug that was present in the azdataGraph library that was impacting how polygons were being drawn.
Before:
After:
> Update azdataGraph version from 0.0.26 to 0.0.27

- src/sql/workbench/services/connection/browser/media/connectionDialog.css
the account field is still showing when switched to connection string option.
Before
After
> hide account when using connection string

- extensions/notebook/src/dialog/managePackages/addNewPackageTab.ts
Removing the resetPageFields() call since it also gets called here
https://github.com/microsoft/azuredatastudio/blob/8c3c18e8dcda702d09b9dfe766db91eec7e3a76d/extensions/notebook/src/dialog/managePackages/installedPackagesTab.ts#L60-L64 when the wizard is initialized. 
I was a bit confused before I saw this change (https://github.com/microsoft/azuredatastudio/pull/13691) since I was expecting DropDownComponent.onValueChanged() to not be called when the dropdown value is initialized.
This should fix the smoke test failing because the content typed in the inputbox would get cleared by the second resetPageFields call.
> Fix manage packages wizard being reinitialized twice

- extensions/sql-migration/package.json
lowering the required ads version to 1.36 as 1.37 is not released.
> vbump and fix ads version dependency

- extensions/arc/src/models/miaaModel.ts
- extensions/arc/src/models/postgresModel.ts
- extensions/arc/src/ui/dialogs/connectSqlDialog.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/models/deploy/deployService.ts
- extensions/sql-database-projects/src/models/publishProfile/publishProfile.ts
- src/sql/azdata.d.ts
The doc comment hadn't been updated with the new params so fixed it and added more details around the different return values and how they're used. 
I also fixed the typings to be correct for the result since those could be undefined currently. 
Because of the fixed typings we had some build failures in the extensions with strict null checking enabled - so I fixed those up. 
The arc ones were already properly checking the connected status so I just added the ! since the connection ID will always be filled if the connection is successful. 
For the sql proj stuff I added in a check for the connection being successful - without that if the connection failed then it would just silently continue on and fail elsewhere (because the connection ID wasn't valid)
> Clean up docs for connect and ConnectionResult

- test/smoke/src/sql/areas/notebook/notebook.test.ts
I took a look through the recent failures for the basic code cell functionality smoke test, and every time it failed there was a docs pane open next to the completions list, as seen below. When this pane is open the aria-label for that SELECT list item can change, so the test is likely failing because we were looking for an aria-label of "SELECT", rather than the "SELECT, docs: SELECT keyword" label that shows up with the docs pane. I added an extra assert in the test to account for that additional case.
> Also check for docs pane label in code cell completions test.

- src/sql/workbench/browser/designer/designerTableUtil.ts
This PR fixes #19403
issue: there shouldn't be a vertical scrollbar inside the table.
fix: when setting the height of the table, we also need to consider the horizontal scrollbar. 
before:
after:
> adjust the grid's height in table designer

- src/sql/workbench/services/query/common/queryRunner.ts
This PR fixes #18067
I added this a while back to debug the query editor crash issue, but based on the user's reply, the call stack is always the same as per conversation in this issue: https://github.com/microsoft/azuredatastudio/issues/6763, so removing it to avoid confusion. 
btw, user is happy with what we have implemented to prevent the data loss, so we don't have an immediate need to figure out what is causing the early disposal of the query runner object.
> remove the tracing

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
- extensions/sql-bindings/src/common/constants.ts
This PR fixes #19458.
Typically this would only be shown when there are a lot of tables within a selected database. Otherwise, it would just execute quickly and return the below prompt:
> Add progress notifications for database that would contain lots of tables

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
- extensions/sql-bindings/src/createNewProject/addConnectionStringStep.ts
- extensions/sql-bindings/src/services/azureFunctionsService.ts
- extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts
- extensions/sql-bindings/src/test/service/azureFunctionsService.test.ts
- extensions/sql-bindings/src/test/testUtils.ts
This PR adds Azure Function with SQL binding tests specifically for 5 scenarios:
1. Should show info message to install azure functions extension if not installed
2. Should create azure function project using the command from command palette (no connection info)
3. Should create azure function project using command via the sql server table OE
4. Should open link to learn more about SQL bindings when no azure function project found in folder or workspace
5. Should ask the user to choose a folder to use for the azure project and create an azure function with the selected folder
Figma design doc: https://www.figma.com/file/sC2e3Dgitogj04uQZbuL47/SQL-Bindings-0.1.0?node-id=51%3A417
Coverage > 70% (more to come as well :smiley:)
> Adds SQL Binding Create Azure Function with SQL Binding tests

- src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts
- src/sql/workbench/contrib/dashboard/browser/pages/databaseDashboardPage.component.ts
- src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.component.ts
workaround for https://github.com/microsoft/azuredatastudio/issues/14128
based on the debugging in ADS, the zoom reset happened during the Angular's internal processing, I'll debug electron and figure out the root cause. but the actual fix most likely won't make it to June release.
the workaround is not perfect since you will still see the zoom level being changed by the dashboard, but definitely better than what it was before.
before
after
> workaround for the dashboard resets zooming issue

- .eslintignore
Has a bunch of generated files which fail linting that should just ignore
> Skip automation out dir for linting

- src/sql/platform/connection/common/connectionManagement.ts
- src/sql/workbench/api/browser/mainThreadConnectionManagement.ts
- src/sql/workbench/contrib/assessment/browser/asmtActions.ts
- src/sql/workbench/contrib/assessment/test/browser/asmtActions.test.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
- src/sql/workbench/services/connection/test/browser/connectionManagementService.test.ts
I was trying to use this in an extension and noticed that it didn't always work - for example if I open a new query window, enter a query, execute it and then select a connection then `azdata.connection.getConnection(<editor URI>)` would return undefined.
The root of the issue was that `getActiveConnections` filters down the list of connections so that only a single connection per ID exists - but this means we can easily lose the connection we're trying to find if there's multiple things using the same base profile (for example multiple editors). 
While investigating this I noticed that getConnection is barely even used anywhere - and we already had a `getConnectionProfile` which does basically the same thing but doesn't have the above issue (it looks at all connections for the one with …
> Fix azdata.connection.getConnection

- src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts
- src/sql/workbench/services/notebook/browser/models/cell.ts
- src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
Set attachments to the created cell after splitting a cell. We don't need to remove the attachments, because we clean the unused attachments after updating the cell source .
This PR fixes #19519
> Fix split cell not working with attachments

- build/azure-pipelines/sql-product-compile.yml
This is to fix the docker errors we've been seeing recently (exit code 137, OOM)
In a recent PR I did I added additional linting to extensions, specifically adding a rule that requires parsing the extension projects (many of which weren't being parsed before). This extra parsing required bumping up the memory used for the tasks, which then started hitting the limits of the container when all these were run in parallel.
https://github.com/microsoft/azuredatastudio/pull/19571
Splitting these out into separate calls should fix this, with the cost being a slightly longer build time (~15min -> ~20min)
> Run hygiene separately

- extensions/sql-bindings/src/services/azureFunctionsService.ts
- extensions/sql-bindings/src/test/addConnectionStringStep.test.ts
- extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts
This PR adds more tests specifically ensuring that the execute step that is added here: https://github.com/microsoft/azuredatastudio/pull/19293
This is when a user creates a new azure function project and ensures we get all paths covered:
Coverage for file - 25% to 100%.
> [SQL Bindings] Add tests for connection string execute step 

- src/sql/workbench/api/common/notebooks/vscodeExecuteProvider.ts
- src/sql/workbench/common/constants.ts
- src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts
When changing the connection for a SQL notebook, the underlying session has its queryRunner field nulled out, which causes a few problems. First, running a SQL cell checks for the existence of a queryRunner before executing, so we can get 2 cells running at once when changing the connection after running a cell. Second, trying to cancel a running cell after changing the connection will fail because the queryRunner we're trying to cancel with is now undefined. My fix here was to use a boolean flag when setting a new connection, rather than clearing the queryRunner.
While debugging those issues I also noticed some problems with output routing while running a cell. For example, if you try to run a SQL cell while another is running, the original cell is cancelled, but the query cancellation …
> Fix issues with changing SQL notebook connection while a cell is executing

- src/sql/base/browser/ui/table/table.ts
Issue: #19620
This PR remove the filter from table component as it is not needed anymore. The treeGrid component used by execution plan already has this filter.
> Removing filter from table component set Data

- extensions/sql-database-projects/src/controllers/mainController.ts
This PR addresses #19666. The project.files contains both the files and the folders of the project, which is a little confusing and it's one of the code cleanup items to split them up to be separate. The model building on the DacFx end was failing when passed folders because it's only expecting to get .sql files.
Before:
Fixed:
> fix table designer error when sql project has folders

- extensions/sql-migration/src/api/utils.ts
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/wizard/targetSelectionPage.ts
Previously, we had added client-side validation in the SQL Migration extension to ensure that users would not select a target Azure SQL MI/VM that was in a state that was not ready for migration. In order to do so, when fetching the list of available target resources to show to the user, we also look at the resources' properties. 
For SQL MI, we look at the `state` property, which correctly reports the state of the managed instance, which we can use for pre-migration validation by making sure it equals 'Ready'. However, for SQL VM, since such a `state` property doesn't exist, we instead looked at the `provisioningState` property, which is in fact not a property we should look at for determining the readiness of the target VM. 
This is because, for example, if a migration is attempted …
> [SQL Migration] Remove faulty SQL VM state validation

- src/sql/workbench/services/notebook/browser/models/notebookUtils.ts
This PR addresses https://github.com/microsoft/azuredatastudio/issues/19554
The issue was caused by sql notebooks having `jupyter-notebook` as the notebook provider instead of `sql` when the Jupyter extension is installed.
> Fix save notebook with Jupyter Extension installed

- extensions/mssql/config.json
This PR fixes #19656
changes since current version are in the red rectangle. 
the vbump change I did was to update the version to 4.0.1.x
BTW, this is not technically a port from main branch since this build is produced from a release branch of STS. but to follow the process of making changes in release branch, I am still adding the `Port Request` label here.
> update STS to bring in a table designer fix

- src/sql/workbench/contrib/notebook/browser/models/outputProcessor.ts
- src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts
- src/sql/workbench/services/notebook/common/localContentManager.ts
Currently, if we find an unknown output type while loading a notebook, an Error gets thrown which is never surfaced as a notification, and the notebook is opened as an empty tab. This change removes that thrown Error, and instead adds an error message to the output. The original output types are preserved until the user re-runs the cell or clears the output, so that we preserve any output types that are still usable elsewhere.
This PR fixes #18238
Here's an example where I replaced some of the output types in a simple SQL query:
> Show an error in cell output when trying to load an unsupported output type.

- .gitignore
- extensionsGallery-insider.json
- extensionsGallery.json
- package.json
- scripts/validateGalleries.js
- yarn.lock
Validates that the package.json metadata matches what's in the gallery files. 
Currently checks : 
1. VS Code engine version
2. Azdata engine version
3. Extension name
4. Publisher ID
5. Extension version
Couple other things : 
* I noticed Agent version in insiders was also incorrect, stable was updated to .48 a while ago but apparently insiders was missed
* I removed the check for only allowing either azdata or vs code engine version (not both). While many extensions should only have one or the other, some may want to keep both if they publish to both VS Code and ADS. Trying to keep up with that list of special cases was going to be annoying, and in general having both isn't breaking or anything so it's fine to allow. 
* @kisantia @Benjin The schema-compare extension was updated to have …
> Validate package.json metadata against gallery metadata

- scripts/validateGalleries.js
Currently we're running the extension checks sequentially, which now that we're downloading and unpacking the VSIXs for each extension can take a long time. These can all be done in parallel though - they don't have any impact on each other.
> Parallelize gallery checks

- .gitignore
- extensionsGallery-insider.json
- extensionsGallery.json
- package.json
- scripts/validateGalleries.js
- yarn.lock
Bringing over the package.json validate logic and the fixes needing to be made for that.
Two other things : 
1. This also caught a couple issues with the langpack versions where the VSIX link was updated but the gallery version wasn't @erpett  https://github.com/microsoft/azuredatastudio/pull/19681
2. It updates the oracle extension which was updated in the stable gallery but not also updated here
> Bring extensions/rc1 up to date with latest from release/extensions

- extensions/sql-bindings/package.json
- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
- extensions/sql-bindings/src/common/utils.ts
- extensions/sql-bindings/src/test/addConnectionStringStep.test.ts
- extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts
- extensions/sql-bindings/src/test/common/util.test.ts
- extensions/sql-bindings/src/test/dialog/addSqlBindingQuickpick.test.ts
- extensions/sql-bindings/src/test/service/azureFunctionsService.test.ts
This PR vbumps version of SQL Bindings and adds further testing for scenarios and coverage of files.
Additional Testing:
for all testing files I ran organize imports 
- Add SQL Binding Tests: reorganized the layout to follow successfully adding, errors, and then re-prompting situations when the user cancels.
- AzureFunctionUtils Tests: GetAzureFunctionFiles and PromptForObjectName tests coverage
- Utils file tests: Add tests covering the file further
Coverage is above 80% now.
> Add SQL Bindings Tests / Vbump

- src/sql/base/browser/ui/panel/media/panel.css
made a mistake in my previous PR: https://github.com/microsoft/azuredatastudio/pull/19731
Forgot to add back the 'auto' value after testing.  
without it, the tab headers will be collapsed:
after:
> fix tab header width

- src/sql/workbench/services/errorMessage/browser/errorMessageDialog.ts
This PR fixes #19413 
similar to the alert dialog, I think it is reasonable to expect the error message to be read out. 
the error message dialog:
with this change the message will also be announced:
> add message as aria-description

- src/sql/base/browser/ui/editableDropdown/browser/dropdown.ts
- src/vs/base/browser/ui/list/listWidget.ts
- src/vs/base/browser/ui/selectBox/selectBoxCustom.ts
This PR fixes #19412
This PR fixes #19676 
1. the selectionTrait was disabled for listbox role, which I believe is a mistake. searched in the code and all references are providing a value, none of them are using list role.
2. set the selection properly for the list before it is displayed
@Charles-Gagnon @aasimkhan30 I created a PR in vscode: https://github.com/microsoft/vscode/pull/152274, but I don't want to be blocked on that, I'll get this PR into ADS first and then cherry-pick the changes from VSCode to ADS once it is merged.
Screenshots:
For normal select box, I am using Output channels dropdown as an example 
I highlighted a few of them using white line in screenshot below
for editable dropdown:
> fix selected state of select boxes

- src/sql/base/browser/ui/panel/media/panel.css
Inspiration:
Before:
After:
This PR fixes #18852
> Removing truncation from tab header components to make it match the portal look

- extensions/data-workspace/src/common/utils.ts
- extensions/sql-database-projects/src/common/utils.ts
Finally got around to fixing and verifying sending the correct extension name with the data workspace vscode extension's telemetry. Similar to the fix done in https://github.com/microsoft/azuredatastudio/pull/19645. 
I also noticed the fullName in IPackageInfo in the sql database projects extension was never getting used, so removing that to clean up.
> Fix data workspace vscode telemetry

- src/sql/base/browser/ui/table/plugins/buttonColumn.plugin.ts
- src/sql/base/browser/ui/table/plugins/media/buttonColumn.plugin.css
- src/sql/workbench/browser/designer/designer.ts
#19562
1. set header text for action columns
2. add a new column to make the row's context menu easier to access, previously user can use the context menu key to open the menu, but on certain cells, it is not possible, because the cell will enter edit mode and the context menu will be for the text editor.
before:
after:
this PR fixes #19329
> designer table improvements

- build/win32/code.iss
Fix windows installer to not inherit permissions from parent directory.  This is a port from upstream.
> win32 setup: disable app dir inheritance

- extensions/schema-compare/src/dialogs/schemaCompareOptionsDialog.ts
- extensions/schema-compare/src/schemaCompareMainWindow.ts
- extensions/schema-compare/src/telemetry.ts
- extensions/sql-database-projects/src/common/telemetry.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/publishOptionsDialog.ts
Previously, there was only telemetry for when the options dialogs were opened. This adds telemetry in these two extensions for when:
- options are reset
- user changes at least one option and clicks "Ok"
> Add telemetry for schema compare and sql database projects options dialogs

- src/sql/workbench/contrib/query/browser/queryActions.ts
This PR updates the actual execution plan button text to "Disable Actual Plan" and "Enable Actual Plan".
> Updates actual plan text to enable/disable instead of include/exclude

- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
This PR fixes #19285
the save button is disabled when there are no changes, but CTRL+S can still trigger the save action.
> check state before saving

- test/smoke/src/sql/areas/notebook/notebook.test.ts
Currently python notebook smoke tests can only be run all together, since the first test case sets up the python installation that the other test cases rely on. This change adds that python installation step to all the tests, and skips it if already setup by a previous test.
> Add python configuration step to each python smoke test so they can be run independently.

- extensions/sql-database-projects/src/common/telemetry.ts
- extensions/sql-database-projects/src/models/publishProfile/publishProfile.ts
Currently we only have telemetry for if a profile has been loaded when a publish or generate script happens. This adds another event for when a profile gets loaded to get more information on what users are using the profile for.
Publish options get parsed and returned from the STS `dacfxService.getOptionsFromProfile()` call, so we'd have to add logic there to return if there are any publish options specified in the publish profile. When SSDT creates a new profile, IncludeCompositeObjects set to true is added by default to override the default, so almost all publish profiles will have at least this option specified.
> Add telemetry for what users have in publish profile

- extensions/notebook/src/book/bookTreeView.ts
Fixes #19222.
Attempting to fix the always-failing "unstable" tests.
Turned on exceptions, and got the `cannot read property 'getAllNotebooks' of undefined` message, indicating that `currentBook` wasn't set in this case.
Just adding a quick check against this appears to allow these tests to pass again. This should be safe because all that it does is prevent this exception from being thrown in product code.
Will continue looking at unstable tests over the next few weeks to see how unstable they really are.
> Attempt to Fix Unstable Notebooks Tests

- extensions/notebook/src/book/bookTocManager.ts
As part of #19806, I turned on strict null checks locally, and found that there were 2 cases where we weren't calling functions correctly (and therefore the condition was always evaluating as true)
This capability has existed in TS since TS 3.7. I wasn't able to find a knob that toggled _just_ this functionality (have to enable strict null checks).
https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#improved-uncalled-function
> Fix Uncalled Function in Notebooks Extension

- extensions/query-history/src/queryHistoryProvider.ts
- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/browser/mainThreadQueryEditor.ts
- src/sql/workbench/api/common/extHostQueryEditor.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
- src/sql/workbench/api/common/sqlExtHostTypeConverters.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/sql/workbench/services/query/common/queryModelService.ts
Sending over the entire query text each time has perf implications - and it turns out there's no need for this since the extension can just get the text from the range directly. The extension host keeps its own copy of the text documents locally so it doesn't have go ever go outside of the process when doing it this way. This allowed me to greatly simplify the event logic as well.
Note that there are still perf issues with executing queries for large documents (I started hitting issues in the 100MB range). But I didn't see any noticeable impact from having these events firing (even with query history enabled) compared to stable ADS.
- Changed IQueryInfo/IQueryMessage to just QueryInfo and QueryMessage to more align with how VS code extensibility names their types
- Fixed core logic typing …
> Switch query events to just send ranges instead of full query text

- extensions/query-history/package.json
Didn't notice that this had already been bumped from what was listed in the gallery (0.1.0 currently). So reverting back to 0.2.0 until after the next version is released.
> Revert query-history version back to 0.2.0

- extensionsGallery-insider.json
Add extension Database Migration Assessment for Oracle v1.2.1 for insiders build.
Version 1.4.0 - 2022-06-27 
- Localization bug fixes.
> Adding extension Database Migration Assessment for Oracle v1.4.0

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/deployDatabaseQuickpick.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
- extensions/sql-database-projects/src/models/deploy/deployProfile.ts
- extensions/sql-database-projects/src/models/deploy/deployService.ts
- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
- extensions/sql-database-projects/src/sqldbproj.d.ts
- extensions/sql-database-projects/src/test/deploy/deployService.test.ts
- extensions/sql-database-projects/src/test/dialogs/publishDatabaseDialog.test.ts
Follow up to previous PR : 
1. Adding visibility modifier to rest of ProjectProvider functions. Not necessary but I find it better to be explicit for this kind of stuff
2. Removing redundant awaits in ProjectProvider
3. Rename some of the interfaces/properties in the typings file to more clearly indicate their purpose
> Additional SQL Proj cleanup

- src/sql/workbench/contrib/executionPlan/browser/executionPlanContribution.ts
- src/sql/workbench/contrib/query/browser/keyboardQueryActions.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
This PR adds an "Execution Plan" prefix to commands, so that they're easier to find. 
NOTE: The actual execution plan command is being adjusted in a different PR (https://github.com/microsoft/azuredatastudio/pull/19840) since that action will no longer execute queries.
> Adds "Execution Plan" prefix to Execution Plan commands

- src/sql/workbench/contrib/executionPlan/browser/executionPlanContribution.ts
- src/sql/workbench/contrib/query/browser/keyboardQueryActions.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
- src/sql/workbench/contrib/query/browser/queryActions.ts
This PR adjusts the `ctrl`/`cmd` + `M` shortcut, so that it no longer executes queries automatically. The intention behind this is to prevent a user from executing a query unexpectedly.
Clicking on or using a shortcut to execute this command:
Toggles the state of this Enable/Disable Actual Plan button:
> Actual Execution Plan No Longer Executes Queries

- extensions/arc/src/ui/dialogs/connectControllerDialog.ts
Bug: SQL MIAA create was not taking the custom location from its data controller
Solution: Connecting DC was not properly parsing out the custom location from the metadata. Fixed regex and now it works fine.
> Fixed customlocation parsing for connecting DC

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/deployDatabaseQuickpick.ts
- extensions/sql-database-projects/src/models/deploy/deployService.ts
- extensions/sql-database-projects/src/sqldbproj.d.ts
- extensions/sql-database-projects/src/test/deploy/deployService.test.ts
It's annoying having to deal with checking these properties everywhere and it doesn't seem to make sense to have them optional - we should always have these properties both exist when we finish gathering the publish options.
> Make publish to docker settings properties required

- extensions/dacpac/src/test/testDacFxService.ts
- extensions/mssql/config.json
- extensions/mssql/src/contracts.ts
- extensions/mssql/src/dacfx/dacFxService.ts
- extensions/mssql/src/mssql.d.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/testContext.ts
- extensions/sql-database-projects/src/test/testUtils.ts
This PR fixes #19600
previously, we were using string search to determine whether a script file contains create table statement. this would not work if:
1. the string is commented out.
2. there are more whitespaces between `create` and `table`.
we need a more reliable way to do the detection, in dacfx, there is a script parser that does the job, so adding a new API to DacFx service and made it extensible for other similar scenarios in the future.
below are the changes in STS since 4.1.0.4
@Charles-Gagnon @ssreerama  @smartguest , please confirm these changes are ready to be brought to ADS.
> use reliable way to detect createtable statements

- extensions/arc/package.json
Added a default value, 7, for PITR in SQL MIAA create wizard.
> Add default value for PITR in SQL MIAA create

- extensions/notebook/src/extension.ts
- extensions/notebook/src/telemetry.ts
- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/contrib/notebook/browser/cellToolbarActions.ts
- src/sql/workbench/services/notebook/browser/models/cell.ts
This PR adds telemetry events for: 
- Add Remote Jupyter Book
- Cell Execution Failed (including kernel type and error message)
- Move Cell (including move direction)
> Add Notebook telemetry events

- extensions/dacpac/src/test/testDacFxService.ts
- extensions/mssql/config.json
- extensions/mssql/src/contracts.ts
- extensions/mssql/src/dacfx/dacFxService.ts
- extensions/mssql/src/mssql.d.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/testContext.ts
- extensions/sql-database-projects/src/test/testUtils.ts
This reverts commit 9a22c429a9e98cd16909fbac2900b9a78cb3b193.
original PR #19897
I noticed an extension unit test has been failing inconsistently since my commit, reverting it for now and I will investigate the test failure.
> Revert "use reliable way to detect createtable statements (#19897)"

- extensions/sql-database-projects/src/models/deploy/deployService.ts
Toast notifications will disappear automatically after a set amount of time (varies based on type of notification). When this happens they go into the notification tray but otherwise aren't easily visible anymore. This can make the publish process seem like it's hanging since nothing is happening - in reality it's waiting for the notification to be dismissed before moving on.
Updating this to use a quickpick instead, for two reasons : 
1. Fixing the issue described above
2. Making the flow better for users, right now they'll be entering information into the top of the screen and then suddenly have this appear in the notification area which isn't very intuitive
> Fix container cleanup message disappearing - causing apparent hang

- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts
- src/sql/workbench/browser/modelComponents/flexContainer.component.ts
This PR addresses #19884. This adds an aria-label option for flexContainers, like how radioCardGroupComponent also sets the ariaLabel option: https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/browser/modelComponents/radioCardGroup.component.html#L1
Before:
After:
> Add aria-label option for flexContainer 

- extensions/sql-assessment/package.json
- extensions/sql-assessment/src/htmlReportGenerator.ts
- extensions/sql-assessment/src/localized.ts
Our recent update of the Sql Server Assessment has changed severity levels of the assessment results.
This PR makes the Sql Assessment extension handle these new levels properly.
> Updated htmlReportGenerator to work with 4 levels severity model

- extensions/machine-learning/src/views/models/manageModels/importModelWizard.ts
Fixing a bug with validate was not called for the last page causing import for invalid model
> ML Extension - Validate was not called for the last page causing import for invalid model

- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
today, I ran into an error opening table designer and surprisingly I don't see the 'copy details' button in the error dialog which was introduced in this PR: https://github.com/microsoft/azuredatastudio/pull/19713.
The reason is that I mistakenly included the error?.data as a parameter of the localize method for 4 operations. It wasn't noticed because I only seeded error for process edit operation.
> include call stack data properly for table designer errors

- build/azure-pipelines/darwin/sql-product-build-darwin.yml
Before:
Now: 
Working task
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=162205&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=22325323-cbb2-580d-876a-9766e4a9c105&l=1
> Fixing macos test results publishing warnings

- package.json
- yarn.lock
This PR updates braces@^1.8.2 to braces@^2.3.2  which is used by gulp atom electron. Since I was not able to get a new version of braces directly, I have updated gulp-atom-electron to the latest minor version and that got me braces@^2.3.2
> Updating gulp-atom-electron to update braces 

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/sqldbproj.d.ts
Adding SQL Server 2022 as an option for sql projects since SQL Server 2022 is public preview. 
I tested a project targeting 160 with a permission added in SQL Server 2022 and verified that the project built successfully and that after changing the target platform to 150, build with that permission failed.
> Add SQL Server 2022 as a target platform option for sql projects

- src/sql/platform/connection/common/connectionConfig.ts
- src/sql/platform/connection/test/common/connectionConfig.test.ts
This PR fixes #19984 
Previously, if `Connections Sort Order` is set to `displayName`, we do a case-sensitive sorting by connection name. This PR changes sorting to case-insensitive using`localeCompare`
Before: (with `Connections Sort Order` set to displayName)
After:  (with `Connections Sort Order` set to displayName)
> Fix connection sorting by name in OE

- src/vs/base/browser/dom.ts
- src/vs/workbench/contrib/welcome/walkThrough/browser/walkThroughPart.ts
This PR fixes #https://github.com/microsoft/azuredatastudio/issues/20003.  The safeInnerHtml was rewritten during vscode merge and lost a couple patches we'd made to support the ADS welcome page.
> Fix button links on welcome page

- src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts
Part of #19993. Simple fix caused by merge. Here's what it looked like in the merge:
> Re-enable notebook outputprocessor tests

- build/lib/compilation.js
- build/lib/compilation.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/20025
This was something I added a while back that got lost in the merge, just adding it back (the pipeline already sets the env var)
> Fix code coverage not mapping correctly

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/workbench/contrib/executionPlan/browser/azdataGraphView.ts
- yarn.lock
This azdataGraph version update changes the constructor signature for azdataQueryPlan's to take a single object as an argument instead of several arguments.
> Updates azdataGraph version to 0.0.33

- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/publishOptionsDialog.ts
This PR Adds the ability to toggle the reset button on option updates.
1. Enables when the option is changed.
2. Disables when the defaults are set.
Total scenarios: 
Operations - Reset state (Disable)
1. Opens options tab first time- disabled
2. Options changes - enable instantly
3. Options changes + ok - Enables
4. Options changes + cancel - Disable (or depends on prev state)
5. Options changed + reset clicked + cancel - Disable (or depends on prev state)
6. Options changed + reset clicked + ok - Disable
7. Reset clicked followed by ok clicked - Disable
8. Reset clicked +option changed + cancel- Disable (or depends on prev state)
9. Reset clicked + option changed +ok - Enable
When no option is changed:
When there is a change identified through the publish process:
> Toggle reset button on option change

- extensions/schema-compare/package.json
- extensions/sql-database-projects/package.json
Need to update the azdata dependency of these extensions because of recent STS changes for DacFx deployment options. They will no longer work with older versions of ADS because of the options changes.
> update azdata dependency for schema-compare and sql-database-projects

- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
This PR disables the publish tab 'advanced publish options' button for the upcoming the next release, as the options is planned to release in August release and there are some more options coming to the tab.
> Disabling options button for the release

- src/sql/workbench/api/common/notebooks/notebookUtils.ts
- src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts
- src/sql/workbench/services/notebook/browser/models/cell.ts
When you create a .NET Interactive notebook in ADS and then try to use it in vscode, the cell language is not populated correctly in vscode's notebook viewer. This PR adds a .NET Interactive-specific bit of cell metadata during serialization to fix that issue. This also fixes the scenario where a pre-existing Interactive notebook's dotnet_interactive cell metadata doesn't update upon saving.
> Set dotnet_interactive cell metadata when converting cell into JSON.

- extensions/theme-seti/icons/vs-seti-icon-theme.json
This PR fixes #20043
the icon for shell has changed in recent vscode merge, which is no longer appropriate to represent dashboard, I am using the default icon for now and will request a new icon for it.
before:
after:
> change icon for dashboard

- extensions/arc/notebooks/arcDeployment/deploy.sql.existing.arc.ipynb
- extensions/azcli/src/az.ts
- Upon startup, if arcdata extension is detected, attempt an update of arcdata quietly. If it is already up to date, nothing will be done. (PM requested feature)
- Update SQL MIAA create in notebook to use --use-k8s and --namespace for direct mode create. Removed location, custom location, and resource group as they are no longer needed.
> Auto-update arcdata extension and update SQL MIAA create

- extensions/git/src/test/smoke.test.ts
Occasionally see failures like this 
```
[File Watcher (parcel)] Unexpected error: inotify_add_watch failed: No such file or directory (EUNKNOWN) (path: /tmp/tmp.rmbCWxi6yu)
[File Watcher (parcel)] restarting watcher after error: inotify_add_watch failed: No such file or directory
[3247:0715/074318.539234:INFO:CONSOLE(29)] "%c WARN color: #993 SharedProcess: createWorker found an existing worker that will be terminated (window: 1, moduleId: vs/platform/files/node/watcher/parcel/watcherApp)", source: vscode-file://vscode-app/__w/1/azuredatastudio-linux-x64/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (29)
[3247:0715/074318.540765:INFO:CONSOLE(29)] "%c INFO color: #33f Worker process with pid 3371 terminated normally (type: watcherServiceParcelSharedProcess, …
```
> Fix git integration test failure

- .vscode/extensions.json
- build/azure-pipelines/darwin/sql-product-build-darwin.yml
Noticed that we're currently running the unit & integration tests in the `PR Smoke Test Validation` pipeline. This increases the chance for false positives due to some slight instability with all the tests and just makes (already long) check take even longer. So I'm changing it to support a new `RUN_SMOKE_TESTS` variable that will ONLY run the smoke tests when specified which we'll use for that pipeline. 
RUN_TESTS = Run all tests (even smoke)
RUN_SMOKE_TESTS = Run ONLY smoke tests
I did this so we aren't changing the current behavior of RUN_TESTS - at some point maybe we can make it RUN_ALL_TESTS or something but for now I wanted to avoid making too many changes (especially since we share this with VS Code)
> Only run smoke tests in Smoke PR validation

- extensions/mssql/package.json
We have been testing with this flag turned on for a while and I also received confirmation from users that enabling this haven't caused any issue for them. 
In this PR, I am turning it on by default so that we can have more users test it out.
> enable the ParallelMessageProcessing by default

- extensions/sql-bindings/package.json
Found that the contributions to the menu (`Create Azure Function with SQL Binding`) for Tables and Views was not working. 
Will utilize the `matches` operator found [here](https://code.visualstudio.com/api/references/when-clause-contexts#conditional-operators).  
Tables:
Views:
> [SQL Bindings] Fix package.json when menu command

- extensions/arc/package.json
- extensions/arc/package.nls.json
Removing the checkbox for "Accept terms of use" and opting for agreement text instead.
The checkbox will actually be removed when[ this PR ](https://github.com/microsoft/azuredatastudio/pull/20047)gets merged in to fix the bug where a title for "Accept terms of use" stays even when agreement item is removed in package.json
> Replace checkbox for SQL MIAA create with terms of use text.

- extensions/arc/notebooks/arcDeployment/deploy.arc.data.controller.ipynb
- extensions/arc/package.json
- extensions/arc/package.nls.json
- extensions/arc/src/models/controllerModel.ts
- extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaUpgradeManagementPage.ts
- extensions/arc/src/ui/dialogs/connectControllerDialog.ts
- extensions/resource-deployment/src/ui/modelViewUtils.ts
Make connection mode in Data Controller deploy wizard use displayNames Direct and Indirect and actual values direct and indirect respectively. This will make the Azure CLI commands generated in the notebook lowercase and thus the config info of the DC will be lowercase.
> Make connection mode a displayname

- extensions/arc/package.json
Gave High Availability and Service Tier fields in SQL MIAA create wizard default values:
Related to this PR: https://github.com/microsoft/azuredatastudio/pull/20070
> Changed default values for high availability and service tier to accommodate resource-deployment fix

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
- extensions/sql-bindings/src/common/constants.ts
Not intended for July release. 
This PR addresses changes that were made in vscode-mssql [PR](https://github.com/microsoft/vscode-mssql/pull/17350). 
Mainly adds progress notification when the user selects a connection profile via vscode-mssql. 
Also, if the user uses `Creates Connection Profile`:
If it fails to connect then the user can cancel out of the error (shown below via `x`), then we prompt them the list of connection profiles (shown above) instead of canceling out of the entire flow.
> [SQL Bindings] Delete progress notification not needed

- package.json
- yarn.lock
This is causing a build break in the webmode CI build.  It looks like the version of tar being patched is not completely compatible with gulp-untar and is causing an exception in the `nodejs()` function in the gulp.reh build script.
```
// in file .../azuredatastudio/node_modules/gulp-untar/index.js
var parse = require('tar').Parse // import "parse" symbol
// ...
contentsStream
.pipe(parse()) // call parse like a function but it's a class
```
Generates this exception
```
Exception has occurred: TypeError: Class constructors cannot be invoked without 'new'
at DestroyableTransform._transform (/Users/kburtram/repos/web/azuredatastudio/node_modules/gulp-untar/index.js:25:11)
at DestroyableTransform.Transform._read (/Users/kburtram/repos/web/azuredatastudio/node_modules/readable-stream/lib/_str …
```
> Revert "Bring back tar vBump"

- extensions/resource-deployment/src/interfaces.ts
- extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts
Problem: Default values were not showing if fields used resourceType displayName in radio options fields.
Solution: Added ResourceTypeOptionValue as a type for radio options' defaultValue. When generating component, use the displayName as the defaultValue.
> Fixed default value for radio options builder if using resourceType displayName

- extensions/arc/notebooks/arcDeployment/deploy.sql.existing.arc.ipynb
- extensions/arc/package.json
- extensions/arc/package.nls.json
Fixes:
- Added a description to Location field for DC deploy wizard: if direct mode, this field will be disregarded. This is a temp solution to dropdown not being able to do dynamic enablement yet
- If SQL MIAA deployment wizard specifies General Purpose, disable High Availability field
- If SQL MIAA deployment wizard specifies General Purpose, remove the flags for replicas, readable-secondaries, and sync-to-secondary-commit in the notebook
> Various fixes in Arc extension

- extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts
I merged in this PR https://github.com/microsoft/azuredatastudio/pull/20070 without seeing the comment for restructuring the check for defaultvalue type. This PR changes the code to not requiring casting.
> Edits to resource-deployment changes

- extensions/theme-seti/icons/images/dashboard.svg
- extensions/theme-seti/icons/vs-seti-icon-theme.json
new icon for dashboard, same as the dashboard icon in Azure portal.
Follow up of: https://github.com/microsoft/azuredatastudio/pull/20046
Before:
After:
> new dashboard icon

- src/sql/workbench/services/restore/browser/restoreDialog.ts
- src/sql/workbench/services/restore/browser/restoreViewModel.ts
This avoids some null reference exceptions introduced by https://github.com/microsoft/azuredatastudio/commit/65ef41d53d635c50faadf9b04386df694a8db01c in the case that there are no non-system databases on a server.  This is to fix https://github.com/microsoft/azuredatastudio/issues/19783.
> Fix restore dialog null references

- build/azure-pipelines/linux/sql-product-build-linux.yml
This PR fixes https://github.com/microsoft/azuredatastudio-docs/issues/131
I created a new pipeline to only run the steps that are needed to produce vsix files for extensions.
test run: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=163917&view=results
run existing pipeline against the branch with the new variable: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=163941&view=results
> support build pipeline that only produces extension vsix files

- extensions/arc/package.json
- extensions/resource-deployment/src/interfaces.ts
- extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts
Seems that CategoryValue and ResourceTypeOptionsValue are nearly the same thing, and loadOptions for radiobuttons already checks for CategoryValue. This change was not necessary, the bug was in arc extension code.
> Reverted changes to Radio buttons default value

- .github/workflows/update-galleries-list-reminder.yml
Same as https://github.com/microsoft/sqltoolsservice/pull/1590 - pull_request actions don't have write permissions so we need to use pull_request_target instead.
> Fix gallery list reminder action for PRs from forks

- extensions/arc/package.json
- Connectivity mode field in DC create must now have defaultvalue { name, displayName }
- Variable in package.json was named connection_mode instead of connectivity_mode
> Changed connetivity mode to have object defaultvalue. Changed connection to connectivity mode.

- src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts
- src/sql/workbench/services/notebook/browser/models/cell.ts
This PR fixes #19546 
Issue: When user pastes an image in wysiwyg mode and goes out of the edit mode, the image disappears.
Why: When user pastes an image into a notebook that already has html tags in it, the image is added as html inside span tags. And when we parse for attachments, we're replacing the valid base64 value of the image with attachment:imageName inside the image tags src attribute, which renders the image broken.
Fix: Check if the image is added as an html image element before adding it to the list of attachments of the cell. ( By checking if the valid base64 value being added to the attachments is in an image tag)
Also tried to add it as an actual attachment and replacing the entire image tag with markdown attachment syntax. But since that's embedded in-between other html …
> fix: image disappear issue

- src/vs/editor/browser/widget/diffEditorWidget.ts
This PR addresses #20117. Schema compare uses the diffEditor.component, which reverses the coloring of the diff editor [here](https://github.com/microsoft/azuredatastudio/blob/26455e9113fb97398b2c86273af64c42d218a71a/src/sql/workbench/browser/modelComponents/diffeditor.component.ts#L80). This got broken in the vscode merge where the way `this._options` was getting set changed in diffEditorWidget.ts. Instead of getting set directly to the options passed in, the `validateDiffEditorOptions()` function was added, which didn't have the additional reverse option so it wasn't getting set anymore.
Schema compare diff editor has correct reversed colors now:
Normal diff editor (not reversed):
> fix schema compare diff editor colors not getting reversed after vscode merge

- extensions/integration-tests/readme.md
Tried to clean this up to make it a lot clearer, and then added a section on skipping the python installation tests. 
I also removed everything about the smoke tests and instead just provided a link to the README for those to keep things simpler.
> Update extension integration test guide

- src/vs/editor/browser/widget/diffEditorWidget.ts
This PR fixes #20117. Porting fix from main 3196e99bd649094adc7c7c4d1734ff924b55a979
> [Port] fix diff editor colors not getting reversed after vscode merge (#20118)

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/baselines/openSdkStyleSqlProjectBaseline.xml
- extensions/sql-database-projects/src/test/project.test.ts
Addressing #20082 for the July release, reverting #19987. The fix for this would be more risking to take in ask mode, so this reverts to the previous behavior for now until the full fix is implemented.
> Revert "Fix sql projects not using OutputPath in sqlproj for publishing (#19987)"

- src/sql/workbench/contrib/views/browser/treeView.ts
For https://github.com/microsoft/azuredatastudio/issues/20137
In the VS Code merge last year the `ITreeViewDataProvider` interface changed getChildren to also be able to return undefined. 
https://github.com/Microsoft/azuredatastudio/commit/2bc6a0cd012de69504061a876070cfa43533fedc#diff-38a5184ff0054efc3aad42bd72ab863dc19354fa8706990b4eb27b74139f9db9L826
In our code we have a custom shim provider (for handling data explorer/OE stuff) that wraps this provider : https://github.com/Microsoft/azuredatastudio/blob/29811faeb0f451c933052310ac90d6850a4013ec/src/sql/workbench/contrib/views/browser/treeView.ts#L190
But during the merge it wasn't updated to take into account the new possibly-undefined value, and it's expected to always return a non-undefined value.
Note this is the same root cause …
> Fix null ref in contributed tree views

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/baselines/openSdkStyleSqlProjectBaseline.xml
- extensions/sql-database-projects/src/test/project.test.ts
This PR fixes #20082. Cherry-picking dc7522c661a953db5ca5e34d638948a5f8585fb3 from main. Reverting a commit that broke sql projects publish for legacy style projects.
> [Port] Revert "Fix sql projects not using OutputPath in sqlproj for publishing (#19987)" (#20127)

- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
This PR fixes #20092
A cell's edit state first gets set from the notebookModel when it's created, but setting the cell's edit mode to false when creating a text component cleared part of this state (cellModel.showMarkdown). So, when checking the current mode of the cell in the markdown toolbar component, the cell would appear to not be in markdown mode, so processing keyboard shortcuts would be skipped. When changing the text cell view or re-opening the cell, the showMarkdown state would get updated correctly, which is why the keyboard shortcuts were only failing when first creating the cell.
> Prevent cell's edit mode from being incorrectly cleared when a text component is initialized.

- extensions/mssql/config.json
This PR fixes #20143
This is a targeted fix for the release branch to get an hotfixed version of DacFx with the bug fix. A separate PR will be created for main, as mentioned in https://github.com/microsoft/sqltoolsservice/pull/1598.
> update STS version

- src/sql/base/browser/ui/editableDropdown/browser/dropdown.ts
- src/sql/base/browser/ui/editableDropdown/browser/media/dropdownList.css
This PR fixes #19826
Currently the width calculation doesn't take the padding/font size into the consideration, as a result, the calculated size is not accurate.
before:
after:
> fix the dropdown menu width logic

- extensions/azcli/src/api.ts
- extensions/azcli/src/az.ts
- extensions/azcli/src/common/utils.ts
Fixed a bug where the user would not be prompted to download arcdata if they didn't have it downloaded upon extension startup. Now, if user doesn't have arcdata extension installed on their Azure CLI, they are prompted to download it.
This PR fixes https://github.com/microsoft/azuredatastudio/issues/16518
> Prompt for arcdata install upon extension activation (fix)

- extensions/arc/notebooks/arcDeployment/deploy.arc.data.controller.ipynb
- extensions/arc/notebooks/arcDeployment/deploy.sql.existing.arc.ipynb
Fixes bug found in bug bash where SQL MIAA create is blocked by typo in notebook. Also convert connectivity mode to lowercase before comparison in case users have deployed instances that have capitalized connectivity mode in their configs.
> Change connection to connectivity, .lower on notebook

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
- extensions/sql-bindings/src/common/telemetry.ts
- extensions/sql-bindings/src/services/azureFunctionsService.ts
This PR adds further telemetry points specifically where the user cancels out of the flow. This will help in understanding the cancel/error/success ratio metrics when a user utilizes the Create Azure Function with SQL Binding command.
> SQL Bindings add telemetry points

- src/sql/workbench/contrib/notebook/browser/models/fileNotebookInput.ts
- src/sql/workbench/contrib/query/browser/fileQueryEditorInput.ts
This PR fixes #20103 
notebook and query editor didn't implement the `toUntyped()` method that is used by vscode to determine whether an editor should be added to the recent closed list when an editor is getting closed.
https://github.com/microsoft/azuredatastudio/blob/main/src/vs/workbench/services/history/browser/history.ts#L724
I am not adding this to the untitled query editor and notebook because the underlying resource can't be mapped to the correct  input, it doesn't seem to be trivial to implement. giving the fact that open a new query editor and new notebook is easy enough, i am going to leave these 2 scenarios as is.
> support recent closed feature for query editor and notebook

- extensions/arc/src/localizedConstants.ts
- extensions/arc/src/models/miaaModel.ts
- extensions/arc/src/ui/dashboards/controller/controllerUpgrades.ts
- extensions/arc/src/ui/dashboards/miaa/miaaBackupsPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaUpgradeManagementPage.ts
- extensions/arc/src/ui/dialogs/connectControllerDialog.ts
- When checking connectivity mode, check using .toLowerCase() because some DC configs may have been made with capital 'Direct' or 'Indirect'
- Upgrade message now specifies the exact command and params used in the Azure CLI command, rather than just "Updating instance 'dc1'...
> Added az command message to the upgrade experience. Check connectivity mode with .toLowerCase().

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- yarn.lock
This PR adds collapse/expand keyboard shortcuts to execution plans by updating the azdataGraph library version to 0.0.38.
The user can use the enter or space keys to collapse/expand an execution plan node depending on it's current collapsed state.
> Bumps azdataGraph version to 0.0.38

- extensions/query-history/package.json
- extensions/query-history/package.nls.json
- extensions/query-history/src/constants.ts
- extensions/query-history/src/main.ts
- extensions/query-history/src/queryHistoryProvider.ts
Closes https://github.com/microsoft/azuredatastudio/issues/7437
Adds double click support for query history - either opening the query or running it based on the user configuration.
Open:
Run:
> Add double click action support for query history

- src/sql/base/browser/ui/table/plugins/cellSelectionModel.plugin.ts
- src/sql/base/browser/ui/table/plugins/rowNumberColumn.plugin.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR fixes #19771
the issue is caused by a race-condition that happens when trying to set the active cell to the first cell of the column in response to the column header click, in the meanwhile, in the scroll handler it has some logic to restore the scroll position. there are couple issues:
1. doing scroll restore in the scroll handler seems wrong and I dug in to the history and it was a workaround for a issue that no longer exists, so I am removing the related code. the problem will go away with the code removal.
2. setting the active cell to the first cell of the column when the header is clicked is not user friendly, as a user, I would like to stay at where I am right now. (setting active cell is needed so that user can directly press ctrl+c to copy the selected cells)
as shown in …
> fix the grid goes blank issue

- src/sql/workbench/contrib/query/browser/queryActions.ts
- src/sql/workbench/contrib/query/browser/queryEditor.ts
- src/sql/workbench/contrib/query/test/browser/queryActions.test.ts
- src/sql/workbench/contrib/query/test/browser/queryEditor.test.ts
#20008
block query execution when the editor is in multi-selection mode to avoid unexpected result.
I also checked notebook feature, it will run the whole cell regardless of the selection (I think it is by design)
similar change needs to be made in vscode-mssql
> do not run query in multi-selection mode

- test/smoke/src/sql/areas/notebook/notebook.test.ts
I noticed we've been having a lot of failures in the basic code cell behavior smoke test. The autocomplete test has been failing because "SELECT" doesn't show up at the top of the autocomplete list when typing "SEL". I can't tell why typing in "SEL" all at once isn't working in the smoke tests, since it never repros manually; however, I found out that typing each letter individually before checking the autocomplete is a good workaround for the test.
> Type out query text one letter at a time in autocompletion test.

- extensions/arc/src/models/controllerModel.ts
- extensions/arc/src/models/miaaModel.ts
- extensions/arc/src/ui/dashboards/miaa/miaaBackupsPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaComputeAndStoragePage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaUpgradeManagementPage.ts
- extensions/azcli/src/api.ts
- extensions/azcli/src/az.ts
- extensions/azcli/src/typings/az-ext.d.ts
- Direct mode commands are now supported by the Kubernetes API
- This change makes all SQL MIAA commands, such as create, delete, update, show, list, and upgrade, use the Kubernetes API for both direct and indirect connectivity mode. 
- Comments that used to say "Indirect mode arguments" or "Direct mode arguments" now say "K8s API arguments" or "ARM API arguments" respectively, because we are shifting the language we use to describe the "mode" of resources. 
- Even though ARM API arguments are not being used right now, I left them in the Azure Arc API within ADS because we may implement ARM in ADS in the future.
> Converting all SQL MIAA commands to use K8s API commands

- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
- test/smoke/src/sql/areas/notebook/notebook.test.ts
This PR fixes #20093
We call toggleEditMode when first creating the text cell component, but we don't set the previewMode value when making the cell editable. This means the preview pane will always show when first creating the cell, even if the default is markdown only. Changing the cell view mode updates the preview mode correctly, which is why you only see this when first creating the cell.
> Set cell preview mode when toggling edit mode.

- src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR fixes #20013
during the document switch, when the view is not results view, it will still be created and then disposed in the onHide event handler, but the scrollable view will call the onDidInsert in a timer function and will cause the error of adding disposable to an already disposed disposableStore.
the fix it to mark it as disposed and no-op if it is disposed.
> no-op is the object is disposed

- src/sql/workbench/contrib/query/browser/queryResultsView.ts
This PR fixes #20233
The issue is because when we reset the input, the query runner variable for the results view is not cleared.
> fix query results view issue

- src/sql/base/browser/ui/table/formatters.ts
This PR fixes #20176
I was able to identify that the dead link as the root cause, but still not sure why electron decides to reset the zoom level.
before:
after:
> fix the zoom reset issue

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
- extensions/sql-bindings/src/common/utils.ts
- extensions/sql-bindings/src/services/azureFunctionsService.ts
- extensions/sql-bindings/src/test/service/azureFunctionsService.test.ts
This PR removes the need to watch for the completion of the createFunction file due to upgrades ([here](https://github.com/microsoft/vscode-azurefunctions/pull/3268)) with vscode-azurefunctions as well as past changes.
The main thing I will work on is that we get proper error handling from vscode-azurefunctions createFunction API call when a user cancels out of the quickpick options.
> [SQL-bindings] remove watcher for files

- src/sql/base/browser/ui/colorbox/colorbox.ts
- src/sql/base/browser/ui/colorbox/media/colorbox.css
- src/sql/workbench/services/serverGroup/browser/media/serverGroupDialog.css
- src/sql/workbench/services/serverGroup/browser/serverGroupDialog.ts
This PR fixes #19870
use text together with color to represent the server group color.
tested with screen reader and keyboard navigation.
before:
after:
> show server group color name

- extensions/sql-database-projects/src/common/constants.ts
The previous eula links were for specific versions: edge and 2017. This updated link, found under the dockerhub for SQL Server at the bottom at "license", will cover the various images being pulled down from MCR that have other SQL Server versions. 
I left the current text in dialog and quickpick as is - @dzsquared let me know if this should be updated too.
> update container eula link

- extensions/markdown-math/package.json
The extension was trying to find the css file in the wrong location, instead of the output folder.
Here's how it's done in vscode -> https://github.com/microsoft/vscode/blob/main/extensions/markdown-math/package.json#L71
This PR fixes #20091
> Update relative path to katex css

- extensionsGallery-insider.json
- extensionsGallery.json
Updated extension gallery for insiders and stable, arc and azcli extensions are now 1.5.0 using the vsixs here https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=166732&view=artifacts&pathAsName=false&type=publishedArtifacts
> Update extensiongallery for 1.5.0

- test/smoke/src/sql/areas/notebook/notebook.test.ts
These smoke tests have been failing a lot in the CI, so disabling them for now while I investigate.
> Temporarily disable cell toolbar smoke tests

- extensions/arc/package.json
- extensions/arc/src/common/utils.ts
- extensions/arc/src/models/controllerModel.ts
- extensions/azcli/package.json
- extensions/azcli/src/az.ts
- extensions/azcli/src/typings/az-ext.d.ts
Bug: Refresh not working because it calls az sql mi-arc list, which now outputs something different.
This fix enables ADS to work with new Azure CLI arcdata ext. The command 'az sql mi-arc list' now outputs this string before the array of objects:
'Found 1 Arc-enabled SQL Managed Instances in namespace ns1'
Changes:
- Added a function that splits the output of az sql mi-arc list into lines and removes the first one.
- After removing first line of text, turn the rest into a JSON output
- Changed the output of az sql mi-arc list in the ADS azcli extension to be SqlMiListRawOutput instead of SqlMiListResult[]
> SQL MIAA list now accounts for new text output from Azure CLI

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/utils.ts
- extensions/sql-database-projects/src/test/dialogs/utils.test.ts
This PR fixes #20142. Since we now allow projects to target SQL Server 2022, this makes it so that the default SQL Server container will be SQL Server 2022 for project's targeting 2022 so that the new features can be used.
There currently isn't a way to choose the image tag in ADS, only the base docker image can be selected. Previously, the default image is used for SQL Server, which strangely points to the 2017 docker image. As letting the user select the image tag isn't currently exposed, this PR adds logic to choose the appropriate latest image tag behind the scenes for the project's target platform for SQL Server.
Preview is added in the base docker image display name for project's targeting SQL Server 2022:
Project's targeting other versions only have "Microsoft SQL Server", same as …
> Add image tag matching target platform for publish to docker

- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
Currently the toolbar dropdown that changes the markdown text size always says "Paragraph" for the label, regardless of which size option is selected. I've changed that label to "Text Size" here for better clarity.
> Use a "Text Size" label for markdown heading dropdown.

- extensions/sql-database-projects/src/dialogs/publishOptionsDialog.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/20282
There is a fraction of seconds delay on initializing the Deployment options component and better to have a loading spinner in place.
Updated:
https://user-images.githubusercontent.com/74571829/184442605-5a480807-a201-4eeb-af80-e29b453055b2.mp4
Old:
https://user-images.githubusercontent.com/74571829/184214799-c5945c12-54eb-4c12-83af-b3a7660c9288.mp4
> Adding a loader spinner before the options load

- test/smoke/src/sql/areas/notebook/createBook.test.ts
Skip remaining failing smoke tests temporarily until we get to the bottom of these failures.
Manually verified scenarios, they are passing.
> Skip failing smoke tests temporarily

- extensions/schema-compare/src/schemaCompareMainWindow.ts
This PR fixes #19228.
After the changes that went in for publishing changes to database projects from remote database, a small functionality was missed where schema compare file when opened didn't understand how to read and use database projects information stored in the scmp file. This PR fixes that scenario.
While working on this, this issue was found: https://github.com/microsoft/azuredatastudio/issues/20332 . For better testing: https://github.com/microsoft/azuredatastudio/issues/20334
> Save db project information when saved in scmp file

- extensions/sql-bindings/src/common/azureFunctionsUtils.ts
- extensions/sql-bindings/src/common/constants.ts
This PR fixes #19470.
I added the `SQL Bindings` output channel which will output the sql NuGet dotnet add command which would allow for further understanding of errors.
We will open the channel once we get the result from the `dotnet add package` command scenarios where the user is adding a new Azure function to an existing azure function project.
The one thing that had issues would be to edit the warning shown in the issue as that is coming from core command failure logic rather than executing command found [here](https://github.com/microsoft/azuredatastudio/blob/main/extensions/sql-bindings/src/common/utils.ts#L43) where we can add a button to open the channel.
> Add output channel for SQL Bindings extension

- extensions/azurecore/src/azureResource/utils.ts
- extensions/azurecore/src/azurecore.d.ts
- extensions/azurecore/src/extension.ts
- extensions/machine-learning/src/test/stubs.ts
- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/api/utils.ts
The SQL Migration extension makes use of several functions which interact with the ARM REST API, such as `getLocations`, `createResourceGroup`, `getSqlMigrationService`, `getAvailableSqlVMs`, and more. 
Some of the more common ones (such as `getLocations` and `createResourceGroup`) are provided via the Azure Core API, whereas the others that are more migration specific (such as `getSqlMigrationService` and `getAvailableSqlVMs`) are implemented by the SQL Migration extension API itself. 
An issue was reported (https://github.com/microsoft/azuredatastudio/issues/20275) which stated that non-public cloud users were unable to proceed in the SQL Migration wizard, due to the fact that these functions were trying to call the ARM REST API endpoint for the public cloud (`management.azure.com`) …
> [Azure Core, SQL Migration] Fix wrong endpoints being used for non-public clouds 

- extensions/mssql/src/mssql.d.ts
- extensions/sql-migration/src/api/utils.ts
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/assessmentResults/assessmentResultsDialog.ts
- extensions/sql-migration/src/dialog/skuRecommendationResults/getAzureRecommendationDialog.ts
- extensions/sql-migration/src/dialog/skuRecommendationResults/skuRecommendationResultsDialog.ts
- extensions/sql-migration/src/models/stateMachine.ts
In this PR, we:
- add a button to the assessment results dialog which allows the user to save the assessment report (in json format) to a directory of their choosing
- ![image](https://user-images.githubusercontent.com/11844501/181862758-0c15cee7-1c5c-41c9-b318-0adf70a908aa.png)
- this also fixes an issue where previously, running multiple assessments in a short time (e.g. by going backwards, changing the database list, and assessing again) would cause all subsequent assessments to fail
- add a button to the SKU recommendation results details dialog which allows the user to save the SKU recommendation reports (in HTML format) to a directory of their choosing
- ![image](https://user-images.githubusercontent.com/11844501/181863070-39f520a7-f54d-4844-8355-809b6ae84030.png)
----------
See …
> [SQL Migration] Add buttons to allow saving assessment/recommendation reports

- extensions/mssql/config.json
This PR bumps the version of sqltoolsservice in mssql from 4.2.0.16 to 4.2.1.1, which includes the latest changes from SQL Migration.
See https://github.com/microsoft/sqltoolsservice/pull/1638 and https://github.com/microsoft/azuredatastudio/issues/20370 for more details.
> [Port request] Vbump sqltoolsservice in release/1.39

- extensions/agent/src/dialogs/jobStepDialog.ts
This PR fixes #https://github.com/microsoft/azuredatastudio/issues/20171.  The controls custom validation is failing since the placeholder property doesn't set the component value.  This requires updating the retry controls to rerun the validation code.  This fix uses the component value properties instead so validation passes on these controls during dialog initialization.
> Replace Job Step retry placeholders with values

- extensions/notebook/src/book/bookModel.ts
- extensions/notebook/src/book/bookTreeView.ts
We looking for the notebook tree item in the book model, we need to convert the uri to vscode Uri format, otherwise the notebook is not found in windows since we are trying to match` c://path/to/notebook` to `c:\\path\\to\\notebook`
This PR addresses #20392
> Fix unpin notebook 

- extensions/mssql/src/contracts.ts
- extensions/mssql/src/features.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/browser/mainThreadDataProtocol.ts
- src/sql/workbench/api/common/extHostDataProtocol.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
- src/sql/workbench/contrib/executionPlan/browser/executionPlanContribution.ts
- src/sql/workbench/contrib/executionPlan/common/executionPlanInput.ts
- src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
- src/sql/workbench/services/executionPlan/common/executionPlanService.ts
- src/sql/workbench/services/executionPlan/common/interfaces.ts
- src/sql/workbench/services/query/common/queryManagement.ts
- src/sql/workbench/services/query/common/queryRunner.ts
- src/sql/workbench/services/query/test/common/testQueryManagementService.ts
This PR is adds functionality to open an execution plan from a DMV.
1. Query a DMV that contains execution plan XML:
2. Click on the XML hyper link will automatically launch the execution plan viewer when appropriate for the table cell data.
> Adds functionality to open execution plans from DB tables and DMVs.

- extensions/mssql/config.json
This PR fixes #18844 as Microsoft.Data.SqlClient v3.1.1 brings in the fix to Kerberos Authentication on Unix platforms with .NET 6
Changeset (release 4.2): https://github.com/microsoft/sqltoolsservice/pull/1648
Changeset (main): https://github.com/microsoft/sqltoolsservice/pull/1646
> Update STS version to port SqlClient library update

- build/azure-pipelines/distro-build.yml
- build/azure-pipelines/linux/Dockerfile
- build/azure-pipelines/sql-product-build.yml
- build/azure-pipelines/sql-web-build.yml
This PR bumps pipeline image to Ubuntu 20.04
Product build and web build are passing with this change.
I've done basic sanity testing with the build drop on Windows, Mac and Ubuntu 18.04, no outstanding issues.
> bump pipeline image to Ubuntu 20.04

- extensions/data-workspace/src/dialogs/newProjectDialog.ts
This PR fixes #19272. Previously, the location text box started as empty. To help speed up the create project flow, this changes populates that with an initial location in a couple cases. Similar to the change in https://github.com/microsoft/azuredatastudio/pull/20414
With this change, if the `Default Project Save Location` setting has a location set, the location text box will be initially populated with that value. Otherwise if there is an open folder, that folder, or the first workspace folder if there are multiple, is the initial value in the location text box.
> use default folder or open folder as initial location in new project dialog

- extensions/data-workspace/src/dialogs/newProjectQuickpick.ts
This PR fixes the vscode part of #19272. This adds the current open folder, or the first workspace folder if there are multiple, as options to speed up the create new project flow.
New project dialog with one open folder:
when one or more folders in the workspace and the user also has the `Default Project Save Location` setting, both are added in the quickpick
no workspace/no folder open
> add current open folder to new project quickpick

- extensions/query-history/package.json
- extensions/query-history/src/queryHistoryProvider.ts
- extensions/query-history/src/test/queryHistoryProvider.test.ts
- extensions/query-history/yarn.lock
Fixes https://github.com/microsoft/azuredatastudio/issues/20424
Instead of getting the text at the end of the query (which would be wrong if any changes were made between the start and end) we get it at the start and then store it until the query is complete. 
To do this we assume that when a query is started that the active editor is the one executing the query. This means that we only display queries coming from editors - not adhoc queries (such as those ran by extensions). This will be expected behavior for now and later on we can look into supporting other sources of queries being executed.
> Fix query history text race condition

- extensionsGallery-insider.json
- extensionsGallery.json
Update SQL Agent extension to 0.49.0 to pickup bug fix for Add Step dialog OK button not enabling.
The latest extension is available in the Aug release build https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=168186&view=results.
> Update SQL Agent extension in gallery to 0.49.0

- build/lib/util.js
- build/lib/util.ts
The root cause here is that we have a package (sanitize-html) that contains embedded source maps. These were being blindly rewritten to append the source map URL, which resulted in an invalid URL. 
So fixing this by ignoring embedded source maps when rewriting the URLs. VS Code doesn't seem to have this problem (the package that was causing this isn't used by them and I didn't see any others that were like this) so they don't currently bother doing this kind of check.
> Fix 'failed to load source map' warnings in console

- extensions/azurecore/src/azureResource/commands.ts
- extensions/azurecore/src/azureResource/messageTreeNode.ts
- extensions/azurecore/src/azureResource/tree/accountTreeNode.ts
- extensions/azurecore/src/azureResource/tree/baseTreeNodes.ts
- extensions/azurecore/src/azureResource/tree/connectionDialogTreeProvider.ts
- extensions/azurecore/src/azureResource/tree/flatAccountTreeNode.ts
- extensions/azurecore/src/azureResource/tree/flatTreeProvider.ts
- extensions/azurecore/src/azureResource/tree/subscriptionTreeNode.ts
- extensions/azurecore/src/azureResource/tree/treeProvider.ts
- extensions/azurecore/src/azureResource/treeNode.ts
- extensions/azurecore/src/extension.ts
- extensions/azurecore/tsconfig.json
~250 errors to fix so going to be doing this bit by bit. We've had a couple of bugs in the past due to this and with VS Code moving towards having their entire codebase be strict-null compliant it'd be good for us to be doing that as well. 
I opted to go for simplicity over pure correctness if I was worried about potential side effects. The idea being that if I don't have context on what the "correct" behavior is and finding that out would not be an easy task then leaving it with the current functionality (and just using features like the non-null assertion operator `!`) would be the safest route and we can come back and fix any errors more correctly if they end up being a problem.
> Initial work on enabling strict nulls in azurecore

- src/sql/base/browser/ui/taskbar/taskbar.ts
- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/20086
Following on from an offline design discussion, we should be removing invalid taskbar actions when changing notebook providers, rather than keeping them and marking them as disabled. For example, the Manage Packages button will get cleared when changing kernels from Python 3 to SQL.
> Clear invalid taskbar actions when changing notebook providers.

- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/wizard/targetSelectionPage.ts
Initially, we had an [issue](https://github.com/microsoft/azuredatastudio/issues/20275) reported where the SQL Migration extension did not work for customers in USGov. Upon further investigation, it was determined that this was due to a bug in the Azure Core API (which the SQL Migration extension relies on) which incorrectly assumed that all customers were in the public cloud.
So, in a previous PR (https://github.com/microsoft/azuredatastudio/pull/20304), we added a new `getProviderMetadataForAccount` function to the Azure Core API, which fixed the issue, and then we started consuming this new function all over the SQL Migration extension. 
In its current state, the extension works properly on insiders, as well as on local dev builds of ADS. However, it does not work properly (i.e. …
> [SQL Migration] Revert dependency on new Azure Core API changes

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
- extensions/sql-migration/src/wizard/summaryPage.ts
After the changes in https://github.com/microsoft/azuredatastudio/pull/20403, a bug was introduced that would cause the "Create new" button on Step 6 of the migration wizard to not do anything if there isn't a resource group selected: 
Of course the problem is that the behavior of these dropdowns is such that only resource groups containing a DMS service are shown, so any new user that doesn't have any DMS services yet won't have any resource groups to choose from, which in turn blocks them from creating a new one. The only way to fix this issue would have been to deploy a DMS service through other means, and then return to the extension.
This issue wasn't caught earlier since all of our test subscriptions already have a bunch of DMS services lying around, so the only way to repro this …
> Fix broken 'Create new' DMS dialog

- build/azure-pipelines/publish-types/publish-types.yml
Currently this pipeline fails when a hotfix tag (like 1.39.1) is made. There's no reason to run the pipeline at all though - we can just skip it for any non-0 tags and save the failed build notifcation.
> Don't run publish typings for hotfixes

- src/sql/workbench/services/accountManagement/browser/accountPickerImpl.ts
- src/sql/workbench/services/accountManagement/browser/tenantListRenderer.ts
This PR fixes #17162 by including tenant Id in Account display information.
Before: (as shared in original issue)
After:
> Update account dropdown content to include tenant Id

- src/sql/azdata.d.ts
Original PR : https://github.com/microsoft/azuredatastudio/pull/20511
Companion PRs:
https://github.com/microsoft/sqlops-dataprotocolclient/pull/66
https://github.com/microsoft/sqltoolsservice/pull/1665
I'm further updating this to : 
1. Fix the actual types to be correct - most of the properties here can be null based on whether the connection was successful or not so making that explicit to help avoid errors with not properly checking them. This is technically a breaking change for anyone who might be compiling in strict mode - but given that this is just fixing the typings to be correct (we're currently sending null for those values) it's better to have it be correct so that consumers can fix it themselves when they update their typings. This doesn't affect anything at runtime. 
2. …
> Further update to ConnectionInfoSummary typings

- extensions/sql-database-projects/src/controllers/mainController.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/tree/fileFolderTreeItem.ts
This PR fixes #19788. This adds a file watcher when opening a script of sql project so that if a create table statement was added to the script and the file didn't contain one before, then the "Open in Designer" option is now available for that file in the project tree without needing to refresh the projects viewlet.
This only refreshes the projects viewlet if the "Open in Designer" option should be added or removed, so it doesn't happen for every change made to a file.
> the fix open in designer menu item is not available after script is updated with newly added create table statements

- extensions/azurecore/src/azureResource/services/subscriptionService.ts
This PR fixes #20505 by disabling subscription error messages for "stale" accounts.
New behavior with fix:
https://user-images.githubusercontent.com/13396919/187599924-441a0e5d-535a-4ac7-931a-72fd9439d4b1.mp4
To reproduce the same, below steps can be followed:
1. Sign in to Azure and when logged in, clear token cache.
2. Restart Azure Studio
ADS should mark the account as "Stale" as it cannot find credentials in cache, and will prompt user for new credentials as shown in video, instead of showing subscription failures.
The PR also adds below changes:
- Includes account name in error message for a more meaningful message.
- Check for "undefined" token and prompts accordingly.
> Fix to not prompt user when token acquisition fails for stale user accounts.

- extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
This PR fixes #20395.
Project structure dropdown component was missed during the initial changes for Update project from db, to be added in the target component list. This PR adds it appropriately.
> Fix Scmp dialog not presenting Folder Structure option for Projects as Target

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/package.nls.json
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/tools/buildHelper.ts
Fixes #20526. By adding this configuration option, users can change the version of Microsoft.Build.Sql used for building legacy style projects if they want to, which could be helpful for testing fixes without needing to release a whole new version of the extension. If not set, the default Microsoft.Build.Sql version specified in the extension will be used. 
The version is output in the Output window so the user can see what's being downloaded: 
When an invalid version is set, then these errors show and build is not continued.
> add config option for Microsoft.Build.Sql version used to build legacy sql projects

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/azureAccountProvider.ts
- extensions/azurecore/src/account-provider/azureAccountProviderService.ts
Mostly just initializing stuff but I did add a few new errors/warnings that I thought were better to have.
1. If the user doesn't have an auth method chosen. It would be good to go over the auth method selection in the settings at some point - since right now a user can uncheck all auth methods which will break everything anyways. 
2. If for some reason we aren't able to find the expected auth method - right now it would just return undefined which isn't something we handle anywhere else so we'd end up with a very unhelpful error. This will at least make it clear what the problem is (and tying into one, this isn't something we should generally be allowing anyways since I expect that we should require at least one auth method to be chosen at any given time regardless)
> AzureAccountProvider & AzureAccountProviderService strict nulls

- src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts
- src/sql/workbench/services/objectExplorer/browser/mssqlNodeContext.ts
Was writing up some documentation about menu item contributions and was greatly confused by this since nothing I saw was showing the MssqlNodeContextKey being bound for OE items. Dug into it and found out that it's actually https://github.com/Microsoft/azuredatastudio/blob/main/src/sql/workbench/services/connection/common/serverInfoContextKey.ts#L16 being bound - which just happens to share the EngineEdition field and so it seemed to work correctly. 
So I'm just fixing that and adding a comment to try and help avoid this in the future (in addition to the docs I'm writing in the wiki)
> ServerInfoContextKey instead of MssqlNodeContextKey for OE items

- extensions/azurecore/src/constants.ts
- extensions/azurecore/src/extension.ts
Currently we use a folder whose name is localized, which means if the user changes their display language they : 
1. Lose all existing tokens (since it'll be looking in a different folder)
2. End up with a new folder being created, e.g. `Cuentas de Azure` (one for each language)
So this is fixing that.
Note that currently this will just ignore any token caches in the old localized folder location - I considered adding logic to copy over the tokens but that got to be kind of annoying to consider all the edge cases (like a stale cache overwriting a newer one) and so instead of bothering with that I think it's fine to just keep it like this and for anyone who is using a localized version of ADS they'll just have to log in again to their account (which any errors should make clear).
> Don't use localized folder for azure tokens

- extensionsGallery-insider.json
This PR updates the Insiders extension gallery to the latest release candidate version of the SQL Migration extension. It also bumps the dependent version of ADS (`Microsoft.AzDataEngine`) to 1.39 to match what is defined in our [package.json](https://github.com/microsoft/azuredatastudio/blob/main/extensions/sql-migration/package.json#L13).
Link to `Azure Data Studio - Extensions` pipeline run containing vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=170305&view=results
> [SQL Migration] Release 1.0.5 to Insiders

- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
Noticed while working on these that the links were all broken, VS Code expects to use the `@link` tag instead for code links
> Fix relative links in azdata.*.d.ts

- extensions/mssql/package.json
- src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts
- src/sql/workbench/services/objectExplorer/browser/media/objectTypes/objecttypes.css
This PR fixes #20570 by removing invalid context menu options from ledger objects.
This PR also fixes the broken ledger icon references from changing the ledger SubTypes in STS.
Manual Verification of context menus:
- Append-Only Ledger Table:
'Edit Data' option is removed
- Dropped Ledger Tables:
All options but 'Select Top 1000' and 'Refresh' are removed
- Append-Only dropped table
- Updatable dropped table
- Ledger View:
All options but 'Select Top 1000' and 'Refresh' are removed
- Dropped Ledger View:
All options but 'Select Top 1000' and 'Refresh' are removed (same as for active ledger views)
- Updatable Ledger Table Context Menu (no change):
> Remove irrelevant context menu options from ledger objects in OE

- src/sql/platform/connection/common/connectionManagement.ts
- src/sql/platform/connection/test/common/testConnectionManagementService.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
this PR fixes https://github.com/microsoft/azuredatastudio-mysql/issues/46
I wanted to transfer it to ads repo but couldn't.
the issue happened because we are assigning the AzureMFA as the default auth type and it fails the check for AzureMFA authentication type. 
fix: do not set authentication type if the auth type option is not specified by the connection provider.
> handle default auth type

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
This PR fixes #20363.
Currently, all the database projects created from the databases are assigned DSP (target platform) as "Sql Server 2019". instead of its current version. The changes in PR reads the server metadata to determine its version and maps & assigns it appropriately to the target platform for the database project.
Steps to repro:
1. Connect to DW server with a user db.
2. Create project from this user db.
-- The project should now be created with appropriate target platform.
This PR doesn't handle the VSCode version of Projects.
> Set target platform for database project from the server metadata

- src/sql/platform/connection/common/connectionManagement.ts
- src/sql/platform/connection/test/common/testConnectionManagementService.ts
- src/sql/workbench/api/browser/mainThreadConnectionManagement.ts
- src/sql/workbench/contrib/dashboard/browser/dashboardActions.ts
- src/sql/workbench/services/connection/browser/connectionDialogWidget.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
- src/sql/workbench/services/connection/test/browser/connectionDialogService.test.ts
- src/sql/workbench/services/connection/test/browser/connectionDialogWidget.test.ts
- src/sql/workbench/services/connection/test/browser/connectionManagementService.test.ts
- src/sql/workbench/services/connection/test/browser/testConnectionDialogWidget.ts
This PR fixes #20533 
previously I added the provider check for the browse connection view, now also add it for the azure tree scenarios.
unknown provider - direct user to extensions view:
known provider - open the extension page directly:
> handle unsupported connection provider

- src/sql/platform/connection/common/connectionProfileGroup.ts
- src/sql/platform/connection/common/providerConnectionInfo.ts
- src/sql/workbench/contrib/dashboard/browser/dashboardActions.ts
- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
- src/sql/workbench/contrib/objectExplorer/test/browser/serverTreeView.test.ts
- src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts
- src/sql/workbench/services/objectExplorer/browser/serverTreeRenderer.ts
- src/sql/workbench/services/objectExplorer/browser/treeSelectionHandler.ts
This is a follow up of my PR last week to address all the unsupported connection type scenarios: https://github.com/microsoft/azuredatastudio/pull/20577
when we uninstall a connection provider extension, the previous connection will be displayed as `Loading...`.
fix:
1. Show unsupported connections as "unsupported connection" instead of "loading..."
2. Reuse the unsupported connection handler I added last week
3. add a debounce for the OE refresh to reduce the number of OE refreshes at launch time.
before:
after:
OE refresh comparison
> handle unsupported connections in OE/Recent connections view

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/azurecore.d.ts
- extensions/azurecore/src/test/azureResource/tree/accountTreeNode.test.ts
I'm going to investigate the endpoints more - we should have valid endpoints for all clouds. But for the time being just leaving them as potentially undefined (which right now would just fail with a null ref error anyways)
> azureAuth.ts strict nulls

- src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerTable.ts
- src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerWidget.component.ts
This PR fixes #20564
fix: refresh the grid on re-layout to make sure it is displayed properly.
> dashboard refresh fix

- extensionsGallery-insider.json
- extensionsGallery.json
Bump arc and azcli to version 1.6.0 in extension gallery for stable and insiders.
> Update extension galleries for Arc and Azure CLI

- extensions/azurecore/src/azureResource/providers/azuremonitor/azuremonitorTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/cosmosdb/mongo/cosmosDbMongoTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/database/databaseTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/kusto/kustoTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/mysqlFlexibleServer/mysqlFlexibleServerTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/resourceTreeDataProviderBase.ts
- extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcTreeDataProvider.ts
- extensions/azurecore/src/azureResource/resourceService.ts
- extensions/azurecore/src/azureResource/tree/subscriptionTreeNode.ts
- extensions/azurecore/src/azurecore.d.ts
- extensions/azurecore/src/test/azureResource/providers/database/databaseTreeDataProvider.test.ts
- extensions/azurecore/src/test/azureResource/providers/databaseServer/databaseServerTreeDataProvider.test.ts
- extensions/azurecore/src/test/azureResource/resourceService.test.ts
- extensions/azurecore/src/test/azureResource/resourceTreeNode.test.ts
- extensions/azurecore/src/test/azureResource/tree/subscriptionTreeNode.test.ts
This started off as just fixing more strict nulls - in this case the ones in the `*TreeDataProvider` classes with `createContainerNode` since we were passing undefined for account/subscription/tenantId. This whole thing seemed very weird so I dug into it and tried to untangle this mess. 
The root problem here is that this stuff was loosely based off of the VS Code TreeDataProvider logic - but with a bunch of custom stuff thrown in. 
At a rough glance here's how it currently works : 
- Custom resource providers are registered. This is done by extensions in a [package.json contribution](https://github.com/Microsoft/azuredatastudio/blob/87391555c30f3288f2c0707faf9cebc0d40c8ea5/extensions/azurecore/src/azureResource/resourceService.ts#L109) (which the azurecore extension does itself as well) …
> Simplify IAzureResourceTreeDataProvider

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/common/logger.ts
- extensions/data-workspace/src/common/workspaceTreeDataProvider.ts
- extensions/data-workspace/src/main.ts
- extensions/data-workspace/src/services/workspaceService.ts
Adding logging to help investigate slow activation times in vscode, like reported in https://github.com/microsoft/vscode-mssql/issues/17403. This will output the logging in the new Data Workspace output channel and also in the extensions log folder so that it will be easy to get the logs from users.
> add logging for data workspace extension

- extensions/mssql/config.json
- extensions/mssql/package.json
- extensions/mssql/package.nls.json
- extensions/mssql/src/tableDesigner/tableDesigner.ts
- extensions/mssql/src/utils.ts
Currently, the initial launch of table designer takes more time than subsequent ones, introduce a user setting to let user decide whether preload of the database model should be performed to make the initial launch experience smoother.
when user opens table designer (for both new and existing tables) for the first time, we show the following prompt.
regardless of the choice, this prompt will not show again.
STS changes since current version:
> table designer perf improvement - add user setting for preload db model 

- extensions/azurecore/src/azureResource/utils.ts
Note that places where I'm adding a new error being thrown it would have thrown later on anyways with a null ref error. So this is more about making it so that if it does happen it's clear where it came from. (although at some point we likely will want to be investigating better ways to handle these situations)
> AzureResource utils strict nulls

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
These have been there a long time and don't seem like something we'll be changing. This also makes it so the `getSecurityToken` being deprecated doesn't require the user to use the proposed APIs for the replacement. 
I also clarified some of the doc comments and while I was there added comments for the token claims stuff (taken from the link provided in the doc comment for the class)
> Promote some Azure account API typings

- extensions/mssql/config.json
This PR fixes #20483
Commits since last STS version:
https://github.com/microsoft/sqltoolsservice/compare/4.3.0.23...4.3.0.24
@cheenamalhotra Let me know if it's okay to bring your commits to ADS.
> bump STS to support table rename in designer

- extensions/sql-bindings/src/test/testUtils.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
- extensions/types/vscode-mssql.d.ts
This PR fixes #20576.
Read server metadata sent from mssql-vscode extension to set target platform automatically when creating project from database.
> Set target platform for db projects from server metadata: mssql vscode extension

- extensions/mssql/config.json
- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
This PR fixes #20422
Allow user to reorder the columns in primary key
before:
after:
changes in STS since current version:
> Support reordering columns in Primary Key

- src/sql/workbench/contrib/executionPlan/browser/executionPlanComparisonEditorView.ts
- src/sql/workbench/contrib/executionPlan/browser/executionPlanComparisonPropertiesView.ts
This PR fixes an issue around the "Left operation" and "Right operation" labels changing back to "Top operation and "Right operation" when plans are vertically oriented and a different node is selected.
Before:
After:
> Fixes incorrect operation label when plans are oriented vertically and node selection changes.

- test/smoke/test/index.js
Use `invert` and `grep` properties instead of calling the methods.
In my previous PR: https://github.com/microsoft/azuredatastudio/pull/20639, I used the `grep()` and `invert()` methods directly because I don't see the `invert` option in `Mocha.Options` interface. Today, I looked at the mocha.js directly and noticed the `invert` property are actually supported, it is the typing file that do not have it included. 
I only find the `invert` property being included in the 9.x typing file which is different from our mocha's major version, so I am not going to update the typing file version.
tested with the following builds.
All Test Cases:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=171977&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=05af1eac-c39c-5c75 …
> use grep and invert option

- src/vs/workbench/api/common/extHostTerminalService.ts
Been seeing this error a lot when exiting ADS during development - and while I'm not sure exactly when it would come up that the ID would be set to null during normal runtime theoretically that seems to be possible so better to prevent the error. 
(VS Code is just sending _activeTerminal which is undefined at that point : https://github.com/microsoft/vscode/blob/release/1.62/src/vs/workbench/api/common/extHostTerminalService.ts#L470. But our build won't let us do that since the types don't match so I'm just hardcoding it to undefined since this stuff is all going to be refactored away here in an upcoming merge)
> Fix null ref error in terminal service

- extensionsGallery-insider.json
- extensionsGallery.json
This PR updates the Azure CosmosDB ADS extension version to 0.1.3 in both ADS and ADS insider.
[Binary location](https://msdata.visualstudio.com/CosmosDB/_build/results?buildId=72449532&view=artifacts&pathAsName=false&type=publishedArtifacts)
> Upgrade  azure-cosmosdb-ads-extension to 0.1.3

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/azureAccountProvider.ts
- extensions/azurecore/src/account-provider/providerSettings.ts
Uses the default scope, this fixes the issue where it failed to open the Azure pane.
More on the default scope: https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#the-default-scope
Here's the important bit:
> Using scope={resource-identifier}/.default is functionally the same as resource={resource-identifier} on the v1.0 endpoint (where {resource-identifier}
Also fixes an issue where MSAL accounts would be marked as "stale" automatically upon generating the accounts pane
> Fix Scope, Azure Pane

- extensions/azurecore/src/account-provider/azureAccountProvider.ts
- extensions/azurecore/src/account-provider/azureAccountProviderService.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
Right now, after a token has expired (1.5 hours after being issued) you are not able to run any more queries.
After this change, the token gets refreshed automatically. 
I also fixed the typing of the authLibrary
> Fix Query Token Expiration

- src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts
- src/sql/base/browser/ui/table/plugins/media/checkboxSelectColumn.plugin.css
- src/sql/workbench/browser/modelComponents/table.component.ts
This PR fixes #20658 
I have fixed the two issues that I had introduced with my previous PR. https://github.com/microsoft/azuredatastudio/pull/20514
1. The row selection events were not fired because I had set the selectedActiveRow to false in the row Selection model. I have reverted that change.
2. I was not properly adding css classes to the cells which caused the component getting rid of any styling that the extension added. This PR fixes that as well.
> Fixing row selection and styling in select column

- src/sql/platform/connection/common/connectionProfile.ts
- src/sql/platform/connection/common/providerConnectionInfo.ts
- src/sql/platform/connection/test/common/connectionProfile.test.ts
- src/sql/workbench/api/browser/mainThreadQueryEditor.ts
- src/sql/workbench/test/browser/taskUtilities.test.ts
Not sure if this ever worked, but currently it's completely broken. It takes in an azdata.connection.ConnectionProfile but then in $connectWithProfile when we convert that to an IConnectionProfile it loses all the properties that the connection logic requires. 
In addition - the function was returning a created promise but never actually resolving it so it just hung indefinitely. 
This PR fixes both of these by : 
- Updating ConnectionProfile constructor to take in an azdata.connection.ConnectionProfile as well. It's pretty bad we have this many "connection profile" types floating around, but we can't really do anything about that without a significant refactor so for now at least trying to consolidate the logic as best I can. (side note - most of the properties were the same, there were …
> Fix queryDocument.connect

- test/smoke/src/sql/areas/notebook/notebook.test.ts
Added unstable tag for the smoke test since it failed more than once during build.
> add unstable tag

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
Improves the error logging for the get tenants call, before this we did not capture the response code/message returned from the tenantResponse, if it fails this will get put into the logs along with the headers which sometimes contain more useful information for debugging issues.  Will also throw an error after we detect the tenantResponse failure.
before: 
```
[Error]: Error fetching tenants :TypeError: Cannot read property 'map' of undefined - []
[Error]: Login failed - []
[Error]: Error: Error retrieving tenant information - []
```
after:
```
[Verbose]: Fetching tenants - ["https://management.azure.com/tenants?api-version=2019-11-01"]
[Pii]: GET request  response={"error":{"code":"AuthenticationFailed","message":"Authentication failed."}} - …
```
> Improve the tenant logging

- src/sql/base/browser/ui/table/formatters.ts
- src/sql/base/common/numbers.ts
- src/sql/workbench/contrib/executionPlan/browser/executionPlanComparisonPropertiesView.ts
- src/sql/workbench/contrib/executionPlan/browser/executionPlanPropertiesViewBase.ts
- src/sql/workbench/contrib/executionPlan/browser/media/executionPlan.css
This PR isn't associated with any issue, and is an enhancement to the execution plan comparison properties view. The enhancement changes the following things:
1. Adds a summary section to the properties view that includes 3 different items
2. Reorganizes the properties table, so that differences appear first and equivalent properties are collapsed at the bottom.
Equivalent properties collapsed:
Equivalent properties expanded:
> Reorganized Execution Plan Comparison Properties View

- extensions/admin-tool-ext-win/package.json
- extensions/admin-tool-ext-win/yarn.lock
- extensions/azuremonitor/config.json
- extensions/azuremonitor/package.json
- extensions/azuremonitor/src/azuremonitorServer.ts
- extensions/azuremonitor/yarn.lock
- extensions/import/config.json
- extensions/import/package.json
- extensions/import/src/services/serviceClient.ts
- extensions/import/yarn.lock
- extensions/kusto/config.json
- extensions/kusto/package.json
- extensions/kusto/src/kustoServer.ts
- extensions/kusto/yarn.lock
- extensions/mssql/config.json
- extensions/mssql/package.json
- extensions/mssql/src/sqlToolsServer.ts
- extensions/mssql/src/utils.ts
- extensions/mssql/yarn.lock
1. Use new version of service downloader and simplify the runtime/file mapping section.
2. Fix the error in azuremonitor and kusto so that it can actually log messages into the output channel.
> upgrade service downloader

- extensions/query-history/package.json
- extensions/query-history/package.nls.json
- extensions/query-history/src/constants.ts
- extensions/query-history/src/queryHistoryProvider.ts
Closes https://github.com/microsoft/azuredatastudio/issues/7361
Default to 100 to start with since that's a pretty large amount of queries - will be using telemetry to see if people change this value to determine if that should be increased.
> Add max entries to query history

- extensions/query-history/package.json
Typo - meant this didn't show up in the context menu
> Fix query history context item

- extensions/query-history/package.json
- extensions/query-history/src/main.ts
- extensions/query-history/src/queryHistoryProvider.ts
- extensions/query-history/src/telemetry.ts
- extensions/query-history/yarn.lock
Initial set of events : 
- Timing for important actions like reading/writing storage file
- Errors
- Settings changed
Actions executed are already captured by core telemetry so don't need to do anything more there.
> Add query history telemetry

- src/sql/platform/query/common/query.ts
- src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
- src/sql/workbench/services/query/common/resultSerializer.ts
**Description**: As a prerequisite to the hackathon project I'm working on to add support for exporting to Markdown, I propose giving saveAsExcel its own configuration section. This will be expanded later to give Markdown its own section, as well.
This fixes a (well, what I perceive as a) bug where the configuration for save as CSV (specifically, include headers) is used as the config for save as Excel. Thus, although the configuration states that `queryEditor.results.saveAsCSV.includeHeaders` the setting only impacts "saving results as CSV", it actually impacts saving to CSV *and* Excel. To resolve this, I have added a new configuration setting `queryEditor.results.saveAsExcel.includeHeaders` that controls header inclusion just for Excel. To facilitate this, the `getConfigForExcel` …
> Give saveAsExcel its own config options

- extensions/mssql/src/utils.ts
- extensions/query-history/src/queryHistoryProvider.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/sqlExtHost.api.impl.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/vs/workbench/api/common/extHost.protocol.ts
- src/vs/workbench/services/extensions/browser/webWorkerExtensionHost.ts
- src/vs/workbench/services/extensions/common/remoteExtensionHost.ts
- src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts
There are times we want to know the app quality in extensions - and while they can get it by reading the product.json like MSSQL was doing it'd be a lot easier/safer to instead add it to the extension API directly. 
I chose to make it default to `dev` when there isn't a quality since that's the only (supported) scenario that'd happen right now. Every released version should have an actual quality. 
I also fixed an issue with query history persistence - the storage folder is the same for all flavors of ADS currently but the secret storage is per-flavor so what was happening was that we would generate a new key/IV for each flavor which would then fail to decrypt the persisted file. This seems like fine behavior to me - I'm more of the opinion that the different flavors shouldn't actually …
> Add app quality to extension API

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
In this PR, we:
- fix a bug where the SQL MI target card showed the incorrect number of databases which can be migrated (without issues)
- update assessment results card to say "xxx/yyy databases can be migrated **without issues**", since the old card text was slightly confusing
- fix a bug where SQL DB assessment results would grey out and prevent users from migrating databases with blocking issues to MI, even if there were no blocking issues to DB
- fix a bug where the error banner message that would appear in the assessment results when a database has blocking issues informing the user to use another target platform would 1) display the wrong text, as we now support more than MI+VM, and 2) erroneously appear in the SQL DB scenario when it wasn't supposed to
> [SQL Migration] Fix assessment UI issues

- extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
In this PR, we:
- fix an issue where the assessment results dialog for SQL MI and SQL DB targets would show incorrect instance-level issues/warnings:
- before (note that it shows 8 warnings for MI, yet there are only 3, and it includes random SQL DB warnings which are not relevant to this migration scenario):
- after (note that it now shows the correct number of warnings, and only displays warnings applicable to this migration scenario):
> [SQL Migration] Fix incorrect assessment results showing for SQL DB/MI

- extensionsGallery-insider.json
New VSIX can be found here: https://dev.azure.com/dnceng/_apis/resources/Containers/11962194/vscode?itemPath=vscode%2Fads-stable%2Fdotnet-interactive-vscode-1.0.3504060.vsix
> Update .NET Interactive extension to version 1.0.3504060.

- src/sql/workbench/contrib/executionPlan/browser/executionPlanComparisonPropertiesView.ts
- src/sql/workbench/contrib/executionPlan/browser/executionPlanPropertiesView.ts
- src/sql/workbench/contrib/executionPlan/browser/executionPlanPropertiesViewBase.ts
This PR fixes #20741 by adding the ability to expand or collapse all property rows for an execution plan. This functionality was added to single execution plans and to execution plans being compared.
> Add functionality to expand and collapse all property rows.

- src/sql/workbench/contrib/executionPlan/browser/executionPlanComparisonEditorView.ts
- src/sql/workbench/contrib/executionPlan/browser/media/executionPlan.css
This PR fixes #20742 by adding the following things:
1. A new context menu to add an execution plan has been added to the bottom half of the execution plan comparison view
2. A button to add an execution plan has also been added to the bottom half of the execution plan comparison view.
> Adds add execution plan button and context menu to the bottom half of the plan comparison screen

- extensionsGallery-insider.json
Upgrade version of mysql extension.
MySQL VSIX 0.2.2 : [vsix file](https://github.com/microsoft/azuredatastudio-mysql/releases/download/v0.2.2/azuredatastudio-mysql-0.2.2.vsix)
> Upgrading mysql extension insider version to 0.2.2

- build/azure-pipelines/darwin/sql-product-build-darwin.yml
not sure why I decided to generate macos archive with different names based on whether signing is enabled. the new universal app related script failed because it was not able to find the xxx-unsigned.zip file. 
Instead of fixing the new script to know what file to look for, I am making it consistent so that regardless of signing or not, the file name is consistent.
> fix unstable test build pipeline issue

- extensions/query-history/src/main.ts
- extensions/query-history/src/queryHistoryProvider.ts
- Adds double click setting to SettingChanged events
- Send initial setting values on startup
- Don't send "SettingChanged" events on startup. We were always sending them after initialize was done if the values set were different than the default values - instead now we'll only send them when the user actually changes the value
> Query history telemetry fixes

- extensions/sql-database-projects/src/models/connections/connectionService.ts
Fixing this error causing the sql-database-projects-vscode extension to not activate, introduced in https://github.com/microsoft/azuredatastudio/pull/20699:
> fix sql projects vscode extension not activating because it can't find azdata

- src/sql/workbench/contrib/executionPlan/browser/executionPlanPropertiesViewBase.ts
This PR fixes #20786 by correcting the title the narrator reads aloud to a user.
> Fixes same title for reverse alphabetical properties button

- extensions/sql-migration/src/api/sqlUtils.ts
this PR fixes an issue when creating a temporary connection / caching that returns a successful cached connection after changing the password to a different / invalid value.
> fix caching issue with connection profile

- src/sql/workbench/contrib/executionPlan/browser/media/executionPlan.css
This PR fixes an issue around the find node widget's combo box hiding behind the object explorer panel, which is making it unusable.
> Fixes resize bug affecting the find node widget

- src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR fixes #20819
previously, we will treat anything with `{}` in it as JSON, now making it a little bit stricter.
> make the json regex better

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- yarn.lock
This PR updates the azdataGraph version from 0.0.45 to 0.0.46. The update makes the following improvements:
- Narrator will no longer say childless operations in query execution plans are expanded
- Expensive operator highlighting and selection colors have been adjusted to be more accessible.
> Updates azdataGraph version from 0.0.45 to 0.0.46

- src/sql/workbench/common/views.ts
- src/sql/workbench/contrib/dataExplorer/browser/nodeCommands.common.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts
This PR fixes #20789
previously we were using a hash key generated by the payload(connection info) and viewid  to determine whether a new session is needed, but since the payload changes for database nodes and their child nodes, when expanding a database node, we will end up creating a new connection/OE Session which is totally unnecessary.
I am using the session id directly and set on the node and it will be passed to its children so that no new session is created for a connectable node.
tested with azure sql server, azure sql db, mysql, pgsql. all look good.
@rishky-msft FYI.
> avoid unnecessary connections in azure view

- build/azure-pipelines/sql-product-build.yml
When checking the health of the build pipelines, I noticed that the Release step was run for the unstable test pipeline. 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=174566&view=results
The only recent change for the release step is its level, moved from job level to its own stage. the issue seems to be caused by the result of `succeeded()` in the condition expression is different at stage level vs at job level. But in the meanwhile, there is a bug in our pipeline definition, previously, if an unstable test build passes, the condition would be evaluated as true.
To actually fix the issue, I am introducing another variable to control whether insiders build should be released from it, this will make the logic much clear. I will modify the build pipeline …
> more control over the release step condition

- src/sql/workbench/browser/scriptingActions.ts
- src/sql/workbench/browser/scriptingUtils.ts
- src/sql/workbench/contrib/scripting/browser/scriptingActions.ts
noticed that we don't actually surface the scripting errors to the user while investigating: https://github.com/microsoft/azuredatastudio/issues/20241, actual fix for this issue is in STS: https://github.com/microsoft/sqltoolsservice/pull/1724
changes: 
1. Show error dialog when scripting failed.
2. Updated the methods that doesn't need to have a boolean return type to void.
> show error when scripting fails

- extensions/cms/package.json
- extensions/cms/package.nls.json
- extensions/mssql/package.json
- extensions/mssql/package.nls.json
- resources/xlf/en/cms.xlf
- resources/xlf/en/mssql.xlf
- src/sql/workbench/test/browser/modal/optionsDialogHelper.test.ts
"Asynchronous Processing" was dropped from MDS 4.0 onwards, and does not apply to MDS 5.0 anymore. This property was also always a no-op for .NET Core, and only applied to .NET Framework driver, but is now removed from driver completely. 
It's a no-op for Azure Data Studio.
Reference links: 
- https://github.com/dotnet/SqlClient/pull/1148
- [SqlConnectionStringBuilder Properties for SqlClient v3.1](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionstringbuilder?view=sqlclient-dotnet-core-3.1#properties)
> Remove deprecated "Asynchronous Processing" connection property

- extensions/sql-migration/package.json
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
this pr:
* fixes an issue in the sql db targeting scenario when the user selects an initial target database and tables for a migration then changes the target database and table selection resulting in displaying and using wrong target database for migration.
* bumps the version to 1.1.0 for next insiders release.
> target database mapping and selection bug

- extensions/sql-migration/src/models/stateMachine.ts
This PR updates the query that is used during SKU recommendation to fetch the server name of the current connection, since the file names of the performance data files that it's looking for are derived from the server name. This query is the correct one that is also used by the recommendation NuGet when the files are being written. 
This was causing an issue where recommendations would fail in situations like this: https://stackoverflow.com/questions/26097229/servername-vs-serverpropertyservername
> [SQL Migration] Update server name query

- build/azure-pipelines/darwin/sql-product-build-darwin.yml
The tools services are currently crashing during the tests and causing other tests to fail. Created https://github.com/microsoft/azuredatastudio/issues/20846 to track figuring out what the issue is since it seems likely that this is an actual problem with how those services are built and/or ran. 
This should help with the stability of our smoke tests - the toasts that show up because of this can cause other tests to fail.
> Disable Kusto & Azure Monitor during smoke tests

- src/sql/base/browser/ui/table/plugins/cellSelectionModel.plugin.ts
- src/sql/base/browser/ui/table/plugins/rowNumberColumn.plugin.ts
- src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
- src/sql/workbench/contrib/executionPlan/browser/topOperationsTab.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
- src/sql/workbench/services/notebook/browser/outputs/tableRenderers.ts
Fixes the following issues:
1. This PR fixes #2727
2. Support cell selections on macOS (previously the multi-selection using keyboard never worked)
3. The rowNumber plugin and cellSelectionModel is conflicting since they both do selection management; it is just a matter of the event registration order to decide who gets called first. To fix the issue, I am adding options to the plugins and the consumer of the components can set those options properly. 
**NOTE**: The multi-selection key is CTRL for Windows/Linux, CMD key for macOS.
**Scenarios**
1. Select all - click the header of row number column
4. Select a single column - click the column header
5. Select columns individually - click the header of the columns with CTRL/CMD key pressed
6. Select columns in a range - select the start …
> table cell selection improvement

- extensions/types/vscode-mssql.d.ts
I missed adding `includePermissions` to the `ExtractParams` interface in my last PR #20845. I also noticed a few differences between this vscode-mssql.d.ts and the [vscode-mssql.d.ts](https://github.com/microsoft/vscode-mssql/blob/main/typings/vscode-mssql.d.ts) in vscode-mssql extension repo, so fixing them here so the two files match.
> update vscode-mssql.d.ts to match the one in vscode-mssql

- build/azure-pipelines/sql-product-build.yml
This will only be enabled on the official build pipeline so that other pipelines don't have to run these steps to save build time.
> additional variable for macOS arm64 jobs

- src/sql/platform/serialization/common/serializationService.ts
- src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
- src/sql/workbench/contrib/notebook/test/browser/dataResourceDataProvider.test.ts
When trying to convert query results into different file types, we were always picking the first registered serialization provider, which meant the request would get routed to the Kusto service rather than the SQL Tools one. This change routes that request to the right service, while also adding a new providerID field in case we want to use this serialization service for other file types in the future.
This PR fixes #20432
> Correctly route notebook serialization requests to SQL Tools Service.

- extensionsGallery-insider.json
link to extension artifacts:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=175590&view=artifacts&pathAsName=false&type=publishedArtifacts
> hotfix: updating sql-migration version to 1.1.1 for insiders

- src/sql/base/browser/ui/table/treeGrid.ts
I used this guide to fix this issue: https://www.w3.org/WAI/ARIA/apg/example-index/treegrid/treegrid-1.html?cell=force
Since, we cannot select the rows in the grid, we have to add the aria-expanded attribute to the cell of the first column.
Issue: #20783
> Fixing NVDA not announcing treeGrid collapse/expanded state.

- build/azure-pipelines/publish-types/publish-types.yml
Typo in yaml causes failed CI task to publish types.
> Fix publish types CI task

- src/sql/workbench/contrib/notebook/browser/find/notebookFindDecorations.ts
Similar issue that affected text cells. Scroll does not work if we pass in the smooth option. 
This PR fixes #20904
> Remove smooth behavior from scroll for code cells

- src/sql/workbench/contrib/objectExplorer/browser/media/serverTreeActions.css
- src/vs/base/browser/ui/splitview/paneview.css
This PR fixes #20886 
this block of {{SQL CARBON EDIT}} code change was deleted during the merge, bring it back.
with the fix:
> fix the server action icon's size issue

- src/sql/workbench/contrib/profiler/browser/profiler.contribution.ts
This PR fixes # https://github.com/microsoft/azuredatastudio/issues/20908
It allows the profiler to extract the host name and display in the window
> add hostname in profiler

- package.json
- yarn.lock
This PR fixes https://github.com/microsoft/azuredatastudio/security/dependabot/256 .
After the latest vscode merge, jpeg-js version came down to 0.4.3, which has security vulnerabilities (vulnerable to DoS). It is a dependency for playwright/test. Updating playwright to 1.26.0 to remove this dependency.
> Update playwright version from 1.21.0 to 1.26.0

- src/sql/platform/connection/common/connectionConfig.ts
- src/sql/platform/connection/test/common/connectionConfig.test.ts
- src/sql/workbench/services/connection/browser/connectionDialogService.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
- src/sql/workbench/services/objectExplorer/browser/serverTreeActionProvider.ts
Fixes #18736, #10424
1. Editing a connection does not load saved password as the profile loaded via context menu does not populate it.
2. The current design of 'Edit Connection' used the same OLD profile id and assigned it to the new connection profile, so it could refresh the same connection in Server tab. But doing so led to Connection profile manager having to maintain MULTIPLE different connection profiles with same IDs, which is a design flaw as ID needs to be unique among connection profiles. This further led to OE and Extensions and many more code paths picking up wrong connections often if they simply used ID for identification.
1. Added 1 line change to add saved password when loading saved connection profile in context menu.
2. The fix now uses Old profile ID to match with the …
> Fix Edit Connection behavior that affects multiple areas working with edited connection

- extensions/resource-deployment/src/test/services/apiService.test.ts
- scripts/test-integration.bat
- scripts/test-integration.sh
The git tests are failing in the CI build and are being disabled for investigation so I can enable the other integration tests.
> Disable failing integration tests

- extensions/azurecore/extension.webpack.config.js
The `universalify` package needs to be webpacked for bundled builds.
> Fix module load issue in azurecore

- package.json
- src/vs/code/browser/workbench/workbench.html
The vscode merge switch the module load order making it possible for some of the angular components to load prior to the reflect-metadata module.  This is to fix the ADS hangs on folder open bug https://github.com/microsoft/azuredatastudio/issues/20932.
> Load angular prior to loader.js

- src/sql/workbench/browser/designer/media/designer.css
This PR fixes #20925 
There are some changes between Chromium 91 and 98 in sizing calculation for CSS grid layout. after reviewing all the options, according to https://www.w3.org/TR/css-grid-1/#fr-unit, I found that using '1fr' is the correct value for what we want: 1st column takes whatever it needs, and 2nd column takes the rest. 
before: 
after:
> fix designer grid sizing issue

- src/vs/base/browser/ui/actionbar/actionbar.css
This PR fixes #20941
This issue has been fixed in vscode, cherry-pick the commit to ADS, original PR: https://github.com/microsoft/vscode/pull/149172
before:
after:
> Fix disabled state for debug toolbar icons (#149172)

- src/sql/workbench/common/constants.ts
- src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts
This fixes https://github.com/microsoft/azuredatastudio/issues/20931 and fixes https://github.com/microsoft/azuredatastudio/issues/20933.  Though there still are some additional issues in the custom Notebook editor implementation around auto-save, etc. that I'll continue to look into.
> Fix Notebook language ids

- src/sql/workbench/browser/editor/profiler/dashboardInput.ts
- src/sql/workbench/browser/modelComponents/editor.component.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts
- src/sql/workbench/contrib/notebook/browser/models/notebookEditorFactory.ts
- src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts
- src/sql/workbench/contrib/notebook/test/browser/markdownTextTransformer.test.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
- src/sql/workbench/contrib/query/browser/queryEditor.ts
- src/sql/workbench/contrib/query/browser/queryEditorFactory.ts
- src/sql/workbench/services/notebook/browser/models/cell.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
Cleanup - this service changed from `ModeService` to `LanguageService` in the last VS Code merge - just updating the var names to match. I'll be following up with doing a separate PR to clean up any outdated references to mode (it's now languageID).
> ModeService to LanguageService var names

- src/sql/workbench/common/constants.ts
- src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
- src/sql/workbench/services/notebook/browser/models/notebookUtils.ts
- src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts
1. Make typed vars for create calls. This was something broken in the merge (fixed by https://github.com/microsoft/azuredatastudio/pull/20938) because the name of the option changed but passing in an object like this currently doesn't cause a compilation error when there's unknown property names specified (there's a feature coming in TS 4.9 that will add support for that though - `satisfies`). Moving it out like this will make sure this doesn't happen again in the future
2. Rename a few things from mode to languageId
> Notebook cleanup

- src/vs/platform/credentials/common/credentialsMainService.ts
There is an issue in vscode 1.67 with keytar throwing an `Unexpected token` error as seen here: https://github.com/microsoft/vscode/issues/149931 
This issue is fixed in this PR: https://github.com/microsoft/vscode/pull/150402
I have cherry picked this commit to put into main.
Fixes #20957
> Fix deletePassword in Keytar

- extensions/mssql/config.json
Brings below changes over v4.3.0.39:
- Update Microsoft.Data.SqlClient to v5.0.1 ([microsoft/sqltoolservice#1708](https://github.com/microsoft/sqltoolsservice/pull/1708))
- Update parser & autocomplete list ([microsoft/sqltoolservice#1729](https://github.com/microsoft/sqltoolsservice/pull/1729))
- Update packages validation comment action ([microsoft/sqltoolservice#1730](https://github.com/microsoft/sqltoolsservice/pull/1730))
- Fix schema comparing empty project showing more differences than expected ([microsoft/sqltoolservice#1727](https://github.com/microsoft/sqltoolsservice/pull/1727))
- Make SerializeDataStartRequestParams properties public so they can be populated properly wehn deserializing the RPC request. ([microsoft/sqltoolservice#1726](https://github.com/microsoft/sqltoolsservic …
> Bump STS to v4.3.0.42

- src/sql/workbench/contrib/welcome/page/browser/welcomePage.contribution.ts
- src/vs/workbench/workbench.common.main.ts
This PR fixes #20965
1. bring back the welcome page file that got deleted during the merge (it has been removed in vscode), instead of keeping it in the vs folder, I am moving it to sql folder to avoid such issues in future merges.
3. removed the SQL CARBON EDIT tags from it 
4. changed once occurrence of 'VS Code' to 'Azure Data Studio'
> bring back welcome page

- build/gulpfile.extensions.js
- product.json
This restores the SQL 19 notebook download related to https://github.com/microsoft/azuredatastudio/issues/20947. The custom gulp task was failing with latest build lib updates from vscode merge.
> Restore the SQL Server 2019 notebook download

- build/azure-pipelines/win32/sql-product-build-win32.yml
Per discussion, removing unstable test step from `sql-product-build-win32.yml`
> Remove unstable test step from win32 product build

- extensionsGallery-insider.json
After the recent VS Code merge, some of the extension APIs changed in such a way that it breaks the current version of the Jupyter extension in our gallery. 
Here's the link to the extension VSIX in the VS Code marketplace: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2022.4.1021342353/vspackage
This PR fixes #20898
> Update Jupyter extension in insiders to version 2022.4.1021342353

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/workbench/contrib/executionPlan/browser/azdataGraphView.ts
- src/sql/workbench/contrib/executionPlan/browser/executionPlanComparisonEditorView.ts
- src/sql/workbench/contrib/executionPlan/browser/executionPlanView.ts
- yarn.lock
1. Navigation info announcement when user enter graph
Issue: #20778
This is pattern is very commonly used in vscode to let users know important key shortcut. I am adding the navigation information to the graph so it gets announced whenever the focus enters an execution plan.
Vscode example:
```
<textarea class="xterm-helper-textarea" aria-label="Terminal 2, powershell
Use Ctrl+UpArrow and Ctrl+DownArrow to navigate the terminal buffer" aria-multiline="false" autocorrect="off" autocapitalize="off" spellcheck="false" tabindex="0" style="left: 115.2px; top: 180px; width: 7.2px; height: 18px; line-height: 18px; z-index: -5;"></textarea>
```
1. Allowing users to expand/collapse button
1. Tooltips shown only when enter is pressed on the node. Hover based tooltips are disabled by default. This …
> Announcing nav info when user enter ep and removing F3 shortcut to show/hide tooltip.

- src/sql/platform/connection/test/common/providerConnectionInfo.test.ts
Split options check into its own test.
Also added big warning to the original test to try and prevent issues like https://github.com/microsoft/azuredatastudio/issues/20972 from happening again
> Add/update providerConnectionInfo.getOptionsKey tests

- extensionsGallery-insider.json
- extensionsGallery.json
Added a new little extension I initially developed for VS Code, but it's equally (or even more) useful in ADS, so I made an ADS version as well. (I goofed up and accidentally added an icon for this due to copy/paste error, but can't edit it here since I used GitHub's direct-edit. Sent a different PR for fix that.)
This PR fixes #20936
> Add column-aligner-ads

- src/vs/workbench/contrib/welcomeViews/common/newFile.contribution.ts
This PR fixes #20993
VSCode added a new `New File...` entry to the `File` menu. This PR removes this entry as ADS has its own `New File` entry
Before this PR:
After this PR:
For comparison, ADS 1.39.1:
> remove "New File..." from File menu

- extensions/notebook/package.json
- src/sql/workbench/api/common/extHostNotebookDocumentsAndEditors.ts
- src/sql/workbench/common/constants.ts
- src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts
- src/sql/workbench/contrib/notebook/test/electron-browser/notebookModel.test.ts
- src/sql/workbench/contrib/notebook/test/electron-browser/notebookUtils.test.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
- src/sql/workbench/services/notebook/browser/models/notebookUtils.ts
- src/sql/workbench/services/notebook/browser/notebookService.ts
- src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts
- src/sql/workbench/services/notebook/common/notebookRegistry.ts
- src/vs/workbench/api/browser/mainThreadNotebook.ts
- src/vs/workbench/api/browser/mainThreadNotebookProxyKernels.ts
- src/vs/workbench/api/common/extHost.api.impl.ts
- src/vs/workbench/services/extensions/common/extensionHostManager.ts
We had to bump the Jupyter extension version because of some vscode extension API changes after the merge, but that new version broke the Interactive kernel in Ipynb notebooks. The old Jupyter extension had a notebooks contribution in its manifest that associated the provider Interactive uses with the Ipynb file extension, but that was removed in the new extension version. I'm guessing they look at the jupyter.kernels contributions instead because Ipynb is already built in, but no idea. This PR adds that old manifest contribution to our builtin notebook extension to get the file association working again.
I also fixed some other things here and there and disabled new VS Code notebook ExtHost bits we don't need while I was at it.
> Re-enable .NET Interactive in Ipynb notebooks

- src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR fixes #20964
It seems it had nothing to do with the merge. When the new execution plan editor tab was opened, dispose was called and the editor input was disposed causing the new tab to close.
> Fixing result grid plans not opening execution plan editor.

- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
- src/sql/workbench/contrib/notebook/test/electron-browser/notebookModel.test.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR address 2 issues related to using aliased kernels in notebooks e.g. Kusto and LogAnalytics.
1. Fixes a problem where the Kusto kernel was being reset to SQL when first opening a Kusto kernel notebook. When I added the new event for handle kernel additions, I re-used an existing "kernelChanged" event to notify the KernelDropdown, but that event was actually meant to notify when a client session had been initialized instead. Thus we were overwriting the saved kernel with the SQL default as soon as the session started. I'll removed that client session event in a subsequent PR, since it isn't actually used anywhere that I could tell.
2. Fixes a problem where trying to change between aliased kernels would fail, like changing to LogAnalytics from Kusto and vice versa. We were …
> Fix issues with loading aliased kernels in notebooks

- src/sql/workbench/contrib/notebook/test/stubs.ts
- src/sql/workbench/services/notebook/browser/models/clientSession.ts
- src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
Noticed that the ClientSession statusChanged event wasn't being used for anything, so I went through and removed all the unused members from the ClientSession interface. KernelsChanged in notebookModel wasn't being used either, so I removed that too.
> Remove unused ClientSession members.

- src/sql/workbench/services/connection/browser/connectionWidget.ts
This PR fixes #21032 as username/password were not clearing on auth type change, due to bug.
> Fix bug where username/password values won't clear on auth type change

- src/sql/workbench/services/connection/browser/connectionWidget.ts
PR https://github.com/microsoft/azuredatastudio/pull/21033 led to a new bug being discovered where username/password wouldn't populate when loading saved profile, this change fixes that scenario, retaining the original fix.
_P.S. I'll proceed to merge this to prevent regression from being captured in insider build._
> Fix population of username/password on loading saved profile

- build/gulpfile.extensions.js
- build/lib/builtInExtensions.js
- build/lib/builtInExtensions.ts
- build/lib/extensions.js
- build/lib/extensions.ts
- product.json
Fixes https://github.com/microsoft/azuredatastudio/issues/20091
Fixes https://github.com/microsoft/azuredatastudio/issues/20968
Extension media building was disabled during the last merge for some reason which means we weren't generating the necessary script and style files for the builtin markdown extensions. This PR brings those back and brings them in line with what's in https://github.com/microsoft/vscode/tree/release/1.67/build/lib
@chlafreniere @barbaravaldez I was seeing some unexpected behavior like links opening up the Notebooks but opening them at the bottom of the Notebook. We should take some extra time to test link opening after this gets in to make sure there aren't any other issues that were hidden behind the issues fixed in this PR.
> Re-enable extension media building

- src/sql/base/query/browser/untitledQueryEditorInput.ts
- src/sql/workbench/contrib/query/browser/queryEditor.ts
- src/sql/workbench/contrib/query/test/browser/queryEditor.test.ts
- src/vs/workbench/services/editor/browser/editorService.ts
This PR fixes #https://github.com/microsoft/azuredatastudio/issues/21038.  The `replaceEditor` functionality is different post-merge and overwrites the input state when resolving editors.  Previous implementation didn't resolveEditor during the replace operation.  Also, the return value from `createFileQueryEditorInput` was now an untyped editor input rather than a query editor input.
> Fix lost results on query editor save

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/utils.ts
This adds the ability to select the image tag used when publishing a sql project to docker in ADS. This is already an option in the vscode extension. The value in adding this is that users can have the option of publishing their project to a 2019 container, rather than forcing them to use the latest, which is currently 2022.
The image tags can be filtered and the image tag options are updated when the base docker image is changed:
https://user-images.githubusercontent.com/31145923/198695504-a454fbec-2d79-47e6-98dc-df682e4ec344.mp4
> Add image tag dropdown for publish to docker in ADS

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/skuRecommendationResults/skuRecommendationResultsDialog.ts
Allow the Hyperscale recommendations to show the right service tier on the "Azure configuration" property in the recommendation results dialog.
> [SQL Migration] Add Hyperscale as service tier for SqlDB

- src/sql/workbench/contrib/welcome/notifyEncryption/notifyEncryption.contribution.ts
- src/sql/workbench/contrib/welcome/notifyEncryption/notifyEncryptionDialog.ts
- src/sql/workbench/services/errorMessage/browser/errorMessageDialog.ts
- src/vs/workbench/workbench.common.main.ts
This PR adds a welcome message for the encryption change when ADS launches. This dialog will only show up once.
The link https://aka.ms/azuredatastudio-connection is not working yet and will be correctly updated later by @erinstellato-ms
> add a welcome message for encryption change

- src/sql/base/browser/ui/breadcrumb/breadcrumb.component.ts
- src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts
- src/sql/workbench/contrib/dashboard/browser/dashboard.component.ts
- src/sql/workbench/contrib/dashboard/browser/pages/databaseDashboardPage.component.ts
- src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.component.ts
- src/sql/workbench/contrib/dashboard/browser/services/dashboardServiceInterface.service.ts
- src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerTable.ts
- src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerWidget.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/14128.
The problem is due to Angular/router always reloading the dashboard module components when navigating. I read about it and found some helpful articles which led me to try this solution, using `skipLocationChange` and `relativeTo` parameters.
Behavior with fix:
I have covered all router navigations, so this should fix the issue for all dashboard routes. The temporary workaround is also removed.
> Fix zoom reset behavior when adding new connection

- resources/xlf/en/sql.xlf
- src/sql/platform/connection/common/constants.ts
- src/sql/platform/errorMessage/common/errorMessageService.ts
- src/sql/workbench/services/connection/browser/connectionDialogService.ts
- src/sql/workbench/services/errorMessage/browser/errorMessageDialog.ts
- src/sql/workbench/services/errorMessage/browser/errorMessageService.ts
- src/sql/workbench/services/errorMessage/browser/media/errorMessageDialog.css
This PR updates error dialog to show instruction text when exception occurs due to SSL cert validation failure.
User is provided option to enable trust server certificate on the connection profile to continue connecting with enabled encryption but skipping certificate validation or they can cancel and return to Connection Dialog.
Updated dialog on SSL cert validation failure to as under:
The link redirects to [MS docs](https://learn.microsoft.com/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine) that provides official SQL Server documentation around encryption.
Also updated custom actions to be primary than the 'Close' button.
> Update error dialog to include instructions text for SSL cert validation failure

- src/sql/workbench/contrib/dashboard/browser/dashboard.component.ts
When connected to a database and not server, I noticed the zoom reset happening, since navigation was not controlled.
This PR fixes the behavior by navigating to database-dashboard when connection is based on a database.
> Add dashboard navigation to database when connected to a database

- src/sql/workbench/contrib/welcome/notifyEncryption/notifyEncryptionDialog.ts
- src/sql/workbench/services/errorMessage/browser/errorMessageDialog.ts
1. We generally shouldn't be making injected services optional - especially when we don't then also update the class to handle the service potentially not being there. It's simple and low-cost to just pass in all the services and makes things much more consistent across the application
(if you wanted to do something like that then it'd be better to make a common abstract class that both can inherit from and just exclude the services that aren't needed by both)
2. Also removed some uses of null - we should prefer to use undefined but in this case they're optional anyways so we can just completely remove them.
> Cleanup encryption dialog

- extensions/sql-migration/package.json
this pr updates the sql-migration extension version to 1.1.2 for creating the next official release for insiders.
> update sql-migration extension to version 1.1.2 for release

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/yarn.lock
This PR bumps the @xmldom/xmldom package that is used in Azure Data Studio to parse xml DOM's. This PR patches an issue around document object models that contain multiple root elements.
> Updates @xmldom/xmldom package version from 0.8.3 to 0.8.4

- extensions/arc/src/models/miaaModel.ts
- extensions/arc/src/ui/dashboards/miaa/miaaBackupsPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaConnectionStringsPage.ts
- extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts
- extensions/azcli/src/typings/az-ext.d.ts
Changes: 
- Added status.endpoints (dictionary)
- Added status.highAvailability and status.roles.sql
- Replaced status.logSearchDashboard to use status.endpoints.logSearchDashboard instead.
- Replaced status.metricsDashboard to use status.endpoints.metricsDashboard instead.
- Replaced status.primaryEndpoint to use status.endpoints.primary instead.
- Replaced status.readyReplicas to use status.roles.sql.readyReplicas instead.
> Status dictionary update for MIAA

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
> Fix account name to display UTF8 characters

- src/sql/workbench/services/connection/browser/connectionDialogService.ts
This PR fixes #21067 
Behavior with fix:
_P.S. Test case added for internal testing._
> Fix instability when canceling editing connection

- extensions/notebook/src/dialog/managePackages/installedPackagesTab.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/16088 by shortening the installed package table to remove extra scrollbars in the dialog.
> Remove extra scrollbars from manage packages dialog

- package.json
with the most recent build, a memory allocation error occurs when you run Yarn Run Watch. Specifically, when running watch extensions on Azurecore. To fix this, the memory for that process has been bumped up to allow it to work.
> Add more memory to watch extension task

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/workbench/contrib/query/browser/queryResultsView.ts
- yarn.lock
Previously, whenever a query returned an execution plan in screen reader optimized mode, we switched to plan tree in the results grid. Now, since the execution plan graph is accessible, there is no need to do that.
Also updating azdata graph library for an undefined error fix.
> Removed plan tree as default for screen reader mode

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/workbench/contrib/executionPlan/browser/widgets/highlightExpensiveNodeWidget.ts
- yarn.lock
This PR fixes #20870
The "no nodes found" warning message was removed since the highlight expensive operation widget only contains metrics that are present in a query execution plan.
> Bumps azdataGraph version to 0.0.56

- extensionsGallery-insider.json
- extensionsGallery.json
This PR fixes updates azure-cosmosdb-ads-extension to version 0.1.4 and fixes its Engine dependencies.
Please find the signed VSIX build [here](https://msdata.visualstudio.com/CosmosDB/_build/results?buildId=75703604&view=artifacts&pathAsName=false&type=publishedArtifacts).
> Update azure-cosmosdb-ads-extension version to 0.1.4

- extensions/admin-tool-ext-win/package.json
- extensions/agent/package.json
- extensions/azurehybridtoolkit/package.json
- extensions/import/package.json
- extensions/liveshare/package.json
- extensions/machine-learning/package.json
- extensions/profiler/package.json
- extensions/query-history/package.json
- extensions/sql-assessment/package.json
- extensions/sql-bindings/package.json
Follow up to https://github.com/microsoft/azuredatastudio/pull/20769/files
I'll be releasing new versions of these extensions that use the new key now that the 1DS onboarding is completed. 
Also removed the key value from extensions that don't actually have send any telemetry. 
Note there's already a number of extensions that were updated that already had their version bumped so I'll just be releasing with that version so they aren't included in this PR.
> vBump extensions with updates to 1DS key

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/azurecore.d.ts
- extensions/azurecore/src/test/account-provider/auths/azureAuth.test.ts
- extensions/azurecore/src/test/azureResource/providers/database/databaseTreeDataProvider.test.ts
- extensions/azurecore/src/test/azureResource/providers/databaseServer/databaseServerTreeDataProvider.test.ts
- extensions/azurecore/src/test/azureResource/resourceService.test.ts
- extensions/azurecore/src/test/azureResource/resourceTreeNode.test.ts
- extensions/azurecore/src/test/azureResource/tree/accountTreeNode.test.ts
- extensions/azurecore/tsconfig.json
This PR shall fix #20701 #20517 and many more similar issues where tenant IDs are not respected.
Current implementation contained a logic to fetch home tenant, which would look into all tenants and find the first 'Home' tenant. It is entirely possible that an Azure account contains multiple 'Home' tenants (as it is in my account), so this implementation was incorrect.
* Wrong tenant identified can lead to different account Id being fetched when refreshing token. This is why when reopening ADS, we would see multiple account entries in Azure Tree for same Corp account generally observed by users also have a personal AD. https://github.com/microsoft/azuredatastudio/issues/20701#issuecomment-1301483198
The implementation is now updated to fetch the tenant Id from `token claims > tid` as …
> Fix tenant Id design for Azure accounts

- extensions/asde-deployment/notebooks/edge/deploy-sql-edge-azure-sshkey.ipynb
- extensions/asde-deployment/notebooks/edge/deploy-sql-edge-azure.ipynb
- extensions/asde-deployment/notebooks/edge/deploy-sql-edge-local.ipynb
- extensions/asde-deployment/notebooks/edge/deploy-sql-edge-remote.ipynb
- extensions/asde-deployment/notebooks/edge/deploy-sql-edge-single-device.ipynb
- extensions/resource-deployment/notebooks/docker/2017/deploy-sql2017-image.ipynb
- extensions/resource-deployment/notebooks/docker/2019/deploy-sql2019-image.ipynb
- extensions/resource-deployment/notebooks/docker/2022/deploy-sql2022-image.ipynb
- src/sql/workbench/contrib/connection/browser/connection.contribution.ts
This PR fixes #20987
for locally deployed SQL Server instances, we should make the experience smoother by automatically set the trustServerCertificate parameter in order to connect.
1. the only actual change in the notebooks is to add `"options": {"trustServerCertificate":true}` as additional parameter to connect. the other changes are generated by the notebooks automatically. NOTE: I didn't run these notebooks, simply added the string and saved the notebooks, testing was done using copies of these notebooks.
2. modified the azdata.connect command to accept additional options.
> Fix connections issues in resource deployment notebooks.

- src/vs/workbench/browser/parts/editor/editorDropTarget.ts
This PR fixes #https://github.com/microsoft/azuredatastudio/issues/20986.  The `untitledOrFileResources` is being assigned a promise instead of the result of the promise as intended.
> Fix open file on drop-n-drop

- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/services/connection/browser/connectionDialogService.ts
- src/sql/workbench/services/connection/test/browser/connectionDialogService.test.ts
PR adds a telemetry action event when user clicks on the newly added action button.
I believe the error message is already captured with 'createErrorEvent' from connectionManagementService (onConnectionComplete), so we need not log it again.
Would appreciate any other feedback for capturing better telemetry with the new changes.
> Send telemetry action event when user selects 'Enable Trust Server Certificate'

- build/gulpfile.extensions.js
- yarn.lock
This was updated during the merge, but this update broke the bundle-marketplace-extensions-build task. Reverting it for now until we can investigate further to see what needs to change to be able to update it. 
Also reverts the changes done in https://github.com/microsoft/azuredatastudio/pull/21063 and https://github.com/microsoft/azuredatastudio/pull/20979 - those never actually fixed the issue, just hid it since we no longer returned the stream that was timing out which meant it completed immediately regardless of there being issues in the tasks themselves. 
Fixes https://github.com/microsoft/azuredatastudio/issues/20947
> Revert gulp-rename

- extensionsGallery-insider.json
- extensionsGallery.json
This PR fixes #21124
This PR fixes #21125
The recent changes to the import extension caused some regressions, since out pipeline is not building the vsix for this extension properly, I made a VSIX with the content of 1.5.0 version. I am not reverting the version to 1.5.0 because a lower version won't trigger auto update. I will v-bump it to 1.5.4 in the source code and I've commented in this issue: https://github.com/microsoft/azuredatastudio/issues/20679 so that @aasimkhan30 is aware of the issues with current code.
> revert import extension to the actual content of 1.5.0

- extensionsGallery-insider.json
For extensions that had been bumped in the repo already I left the version as that version - which is why some have build version bumps and some have minor version bumps. 
Went through and verified that the extensions all still at least start up and can do some basic functionality to make sure that telemetry package updates didn't break anything.
> [Insiders] Update extensions with new aiKey

- extensionsGallery.json
Updating the versions of dacpac, schema compare, and sql projects in the RC gallery to the same version as in insiders. These extensions were already updated for insiders yesterday in #21130.
> update dacpac, schema compare, and sql projects extensions for November release

- extensions/git/src/protocolHandler.ts
Port this commit from vscode repo, which resulted in a hotfix https://github.com/microsoft/vscode/commit/c5da5332d54f610b1b3e6dd9ea9b699971b57407
> Port VS Code issue 149177

- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
As discussed, removing the Edge specific sql project template due to low usage and to avoid confusion for users. Now there's only the Azure template and Sql Server database template.
ADS:
vscode:
> remove edge template from sql projects new project dialog

- extensionsGallery-insider.json
This PR upgrades the version of mysql extension in insider gallery to 0.2.3.
VSIX Link: https://github.com/microsoft/azuredatastudio-mysql/releases/download/v0.2.3/azuredatastudio-mysql-0.2.3.vsix
> Upgrading mysql extension insider to 0.2.3

- extensionsGallery-insider.json
- extensionsGallery.json
Please use vsix files **arc-1.7.0.vsix** and **azcli-1.7.0.vsix** from the below link, but please don't merge in the PR until I give the OK: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=178506&view=artifacts&pathAsName=false&type=publishedArtifacts
> Update extension galleries for Arc and Azcli 1.7.0

- src/vs/base/common/idGenerator.ts
This bug is called due to https://github.com/microsoft/azuredatastudio/blob/0aefecf0c2568ca0f7ee63de0c4af39caeed373f/src/vs/base/browser/dom.ts#L822
The line selects and clears all the css rules for components starting with the substring.
For example: 
If we are trying to clear css rules for 'model-view-component-icon-7' we will also clear css rules for  model-view-component-icon-7<any string>
Causing the images to disappear on all components sharing the same prefix. 
Issue: #19226
> Updating component icon id generation logic to avoid substring overlaps

- src/sql/workbench/services/connection/browser/cmsConnectionController.ts
- src/sql/workbench/services/connection/browser/cmsConnectionWidget.ts
- src/sql/workbench/services/connection/browser/connectionDialogService.ts
This PR will address #21177 
Root causes:
* There were missed changes in cmsConnectionWidget to load custom options on main connection dialog.
* CMS provider name (MSSQL-CMS) was not being updated to MSSQL in provided connection profile in else case (since it was first time use of the 'handleOnConnect' method with profile provided) which led to issues when reconnecting.
> Fix custom option support in CMS + fix updating ProviderName in provided profile

- extensions/sql-database-projects/package.json
Putting Generate project form OpenApi/Swagger spec behind the preview flag so the command will only show in the command palette and Database Projects overflow menu when "Enable Preview Features" is checked.
> put Generate project from OpenApi/Swagger spec behind preview flag

- .github/workflows/ci.yml
GH workflow has been failing to trigger GH actions with [Startup failures](https://github.com/microsoft/azuredatastudio/actions) since PR #21099 (inclusive), as the AzDO yml syntax is not same as GH workflow...
Reference: [Workflow syntax for GitHub actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions)
> Fix GitHub workflow

- extensionsGallery-insider.json
Releasing v3.0.4 of Database Migration Assessment for Oracle in ads-insiders.
> Releasing version 3.0.4 of Database Migration Assessment for Oracle

- src/sql/workbench/services/connection/browser/connectionWidget.ts
I intended to address #20517 for Azure Tree connections with PR https://github.com/microsoft/azuredatastudio/pull/21086, but seems like a block of code got missed out.
This change makes sure the corresponding tenant is loaded in connection when attempting to connection/edit connection.
> Select available tenant Id instead of first one as default

- src/sql/workbench/contrib/notebook/browser/models/fileNotebookInput.ts
- src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
- src/sql/workbench/contrib/notebook/browser/models/untitledNotebookInput.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookEditor.test.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookInput.test.ts
VS Code changed some of their EditorInput saving behavior a while back, which we picked up in the latest merge. AbstractTextResourceInput now returns an IUntypedEditor result, which just contains the editor URI. It used to handle resolving the new editor, but that's now supposed to be handled by downstream sources. I brought back that old editor resolving logic in our notebook save methods to fix problems we've been having with saved untitled notebooks notebooks not closing and reopening properly. Here's the original VS Code commit for reference about the code I brought back in: https://github.com/microsoft/vscode/commit/0e04328299ad24b0d7ff83bc9c763fa1ac5312bc#diff-9065af890ec775428cb4361fbd0b4eeb8131ea56f2e64a161440275e9fd98bdeL69
This PR fixes #21075
> Bring back old editor resolving logic to fix saving in notebooks.

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
Adding "Preview" next to "Publish to new Azure SQL server local development container" option in the publish sql project dialog:
general SQL (160/150/etc) projects publish to container does not have the preview:
> add preview for publish to Azure development container

- src/sql/platform/serialization/common/serializationService.ts
- src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
- src/sql/workbench/contrib/notebook/test/browser/dataResourceDataProvider.test.ts
This PR addresses https://github.com/microsoft/azuredatastudio/issues/21180
Before this fix in STS https://github.com/microsoft/sqltoolsservice/pull/1726, the includeHeaders parameter was not actually being set so we were adding the headers as part of the row data.
> Fix headers being exported twice from notebooks

- src/sql/workbench/contrib/notebook/browser/models/fileNotebookInput.ts
- src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
- src/sql/workbench/contrib/notebook/browser/models/untitledNotebookInput.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookEditor.test.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookInput.test.ts
Porting this change to the release branch. Fixes a bug in notebooks where doing Save As on a notebook won't close and reopen the editor with the new name, which causes further problems when trying to open a new untitled notebook that has the same name as the open one, since it switches to that open tab rather than creating a new one.
This PR fixes #21075
> Bring back old editor resolving logic to fix saving in notebooks. (#21186)

- build/azure-pipelines/sql-product-build.yml
remove the RunTests variable, I took another look, we don't run tests in Windows build job. so, no reason to have this variable to avoid confusion.
> remove tests variable for windows on arm build

- .yarnrc
- package.json
- yarn.lock
This updates from 19.1.3 to 19.1.6.  Previous PR caught us up to latest upstream, this one gets the current 19.xx release.
> Bump to Electron 19.1.6

- extensionsGallery-insider.json
- extensionsGallery.json
This PR adds in strings from the VS 1.67.0 release into ADS, the build to get the langpack are from this build: 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=179573&view=artifacts&pathAsName=false&type=publishedArtifacts
If this needs to only go into Insiders, I can remove the entries.
> Patch langpack to 1.40.1

- build/gulpfile.sql.js
- extensions/sql-database-projects/package.nls.json
- extensions/sql-database-projects/package.vscode.json
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
This hides the "Publish to New Azure Server" option in the publish quickpick if the "Enable preview SQL Database Projects features" setting is not checked. 
Because vscode doesn't have an "enable preview features" setting like ADS, I had to add a new setting in the sql database projects vscode extension (it's only added in the vscode extension and does not show in ADS). This PR updates the package-external-extensions gulp task to add support for copying over configuration properties specified in the package.vscode.json.
> Hide publish sql project to new azure server behind preview setting

- extensions/azurecore/src/account-provider/azureAccountProvider.ts
The prompt to select auth / device code does not appear anymore, this PR fixes that.
Old behavior (doesn't prompt for auth/device code when both options are selected in settings):
New behavior (prompts for auth/device code now):
This PR fixes #21269
> fix prompt for auth/device auth method

- extensions/azurecore/src/azureResource/constants.ts
- extensions/azurecore/src/azureResource/providers/database/databaseTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcTreeDataProvider.ts
- extensions/azurecore/src/azureResource/tree/flatAccountTreeNode.ts
This PR fixes issues when selecting SQL Server/SQL Database from Azure Tree in browse, doesn't populate right tenant info + few improvements to use constants. It should address issue discussed in https://github.com/microsoft/azuredatastudio/issues/21255#issuecomment-1319211916
Additionally, also fixes logic to fetch tokens for tenants instead of all subscriptions. This is one part of the big issue with listing children where access tokens are repeatedly fetched.
Before (Note the Azure AD Tenant selectbox):
With Fix (Note the Azure AD Tenant selectbox):
> Fix Browse azure tab not populating right tenant

- src/sql/platform/connection/common/connectionManagement.ts
- src/sql/platform/connection/test/common/testConnectionManagementService.ts
- src/sql/workbench/contrib/objectExplorer/test/browser/connectionTreeActions.test.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
- src/sql/workbench/services/objectExplorer/browser/connectionTreeAction.ts
This PR fixes multiple issues including #21174 where access token refresh design had some issues:
- When opening/refreshing a treeNode, corresponding `connectionProfile` would sometimes contain expired access token which is possible if connections are kept open and not used for a long time. This led to STS layer failing to connect to target servers.
With this change, we make sure to check whether the parent connection is connected which will in-turn refresh any expired access token **before** sending request to the STS layer.
> Fix access token refresh design

- CHANGELOG.md
(cherry picked from commit 8d13d4054a3522a9cce38695adc8f1e9b98bc0b7)
Noticed that the links were added here in 1.39.1 for some reason as well, typically we haven't been doing that in the past so removing those (will update main separately) to keep things cleaner
> Update changelog for 1.40.1 release (#21297)

- src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
We were only disposing the underlying text model after the notebook editor had been created, so if a notebook editor was already open when starting ADS and we hadn't clicked on it yet, then the text model wouldn't be able to be disposed when closing that editor. A practical consequence of this is that editor numbers wouldn't be freed in the untitled editor service when closing notebook tabs that haven't been clicked on yet, so when opening a new untitled notebook the tab numbers would skip to higher numbers for no obvious reason.
This PR fixes #21134
> Dispose underlying text input in notebook input to clear editor service references correctly.

- extensions/azurecore/src/account-provider/azureAccountProviderService.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/contrib/objectExplorer/test/browser/connectionTreeActions.test.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
- src/sql/workbench/services/objectExplorer/browser/connectionTreeAction.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
- src/sql/workbench/services/objectExplorer/test/browser/objectExplorerService.test.ts
This PR fixes #21174 with companion PR https://github.com/microsoft/sqltoolsservice/pull/1772
_Validated by refreshing connections after 2 hours on inactivity with a TCP drop (forcing connection drop from network)._
- Before PR: Expanding nodes after token expires would lead to: `Failed to connect to server <>`
- After PR: Nodes expand and refresh normally as connection is refreshed with renewed access token.
+Updated Persistence cache to retry more as it often leads to cache lock issues when acquiring token using MSAL.
> Refresh token with SqlToolService session update

- src/sql/base/browser/ui/dropdownList/media/dropdownList.css
- src/vs/base/browser/ui/dropdown/dropdownActionViewItem.ts
- src/vs/workbench/contrib/extensions/browser/media/extensionsViewlet.css
Fixes https://github.com/microsoft/azuredatastudio/issues/20877
There's two things being fixed here : 
1. Fixes the arrow key issue. I plan on submitting this to VS Code too since they have the same issue (https://github.com/microsoft/vscode/issues/164050)
2. Bring back the action menu for the extension gallery editor. This was hidden in the latest merge because it was "broken" (see before picture). I tracked this down to the styles applied globally in dropdownList.css. Those have been around forever so there isn't any history of why it was done in the first place - but I removed them and am not seeing any of our dropdowns looking broken. And even if they were doing global changes to all dropdowns like that isn't something we should need to be doing so we should be fixing those on a …
> Fix action dropdowns focusing hidden button & fix ext action button

- extensionsGallery-insider.json
Releasing v3.0.5 of Database Migration Assessment for Oracle in ads-insiders.
> Releasing v3.0.5 for Database Migration Assessment for Oracle on Insiders

- src/sql/azdata.proposed.d.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
Fixes receiving token in backend for refresh logic as property name mismatched to that in STS (introduced in #21308) 
Renaming to fix the issue.
> Rename to security token to match STS

- extensionsGallery-insider.json
This change updates the version of Database-Schema-Conversion-Toolkit extension from v0.2.0 to v0.3.0 for insider's gallery.
> DSCT 0.3.0 version for insider

- extensions/azurecore/package.json
Switch MSAL to the default authentication library, as ADAL is going out of support.
> Make MSAL default auth library

- src/sql/workbench/services/connection/browser/connectionWidget.ts
This PR fixes #21353 
Custom Option select boxes were not setting values differently, but labels were only provided. I had identified and fixed this issue in #21256 but the PR is delayed due to internal reasons, so it would be best to get the fix extracted for upcoming release.
The change sets actual values separately so they can be retrieved as-is.
Quick Demo using dummy label:
> Set both labels and values to custom options select Boxes

- product.json
this extension has been removed from the gallery by @corivera.
> remove dotnet-interactive-vscode extension

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/base/browser/ui/table/plugins/cellSelectionModel.plugin.ts
- src/typings/slickgrid.d.ts
- yarn.lock
This PR fixes #14541
before:
after:
> select cell after keyboard navigation

- extensionsGallery.json
This PR updates the Worldwide extension gallery to the latest version of the SQL Migration extension. It also bumps the dependent version of ADS to 1.40, matching the extension definition.
This vsix was already built, uploaded, and released to Insiders as part of https://github.com/microsoft/azuredatastudio/pull/21337.
Closes #21074
Closes #20275
> [SQL Migration] Release v1.1.3 to Worldwide

- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
I was testing some Spark notebooks after we removed the spark kernels in the BDC cleanup, and noticed that we switch to the default SQL kernel without any notification. This change adds a message saying we don't support the kernel the notebook was saved with.
> Show a message if kernel is not supported when first opening a notebook.

- src/sql/base/browser/ui/table/media/slickColorTheme.css
- src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR fixes #313
1. handle line breaks in the json string
2. use pointer cursor for link cells
3. inherit the whitespace setting from parent cell for link cell to avoid showing things in multiple lines.
Before
After
> fix json cell handling in query editor

- src/sql/workbench/contrib/query/browser/queryEditor.ts
This PR fixes #21231
redo the layout after the content of taskbar changes since it could impact the height of the taskbar.
Before:
After:
> fix h-scrollbar cutoff issue

- extensions/dacpac/src/wizard/dataTierApplicationWizard.ts
This PR fixes #16904. The dacpac wizard was using the current active connection, rather than the connection info of the node the wizard was launched from, which are not the same if the node is not actively selected. 
Before:
Fixed:
> Fix dacpac wizard not always using correct connection

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
This PR fixes #21371
If 'tid' is not found in 'TokenClaims' which corresponds to default active directory for user, we can fallback to 'common' tenant for authentication.
> Fallback to 'common' tenant if 'tid' not found

- .github/workflows/cleanup-stale-issues.yml
- .github/workflows/on-issue-comment.yml
This PR will auto close issues that have need logs label after 7 days of inactivity. However, if there is a comment made on an issue from anyone outside the team, the need logs label will be removed.
> Auto closing issues that needs logs after 7 days of inactivity. 

- src/sql/workbench/services/connection/browser/connectionController.ts
- src/sql/workbench/services/connection/browser/connectionWidget.ts
This PR should address #21371.
I misunderstood the issue to be related with MSAL before and confused it with Azure tree token issue.
The reported issue got introduced with this [change](https://github.com/microsoft/azuredatastudio/commit/405b3bbfdb3e3d963fcc344d9a9e2d333db7d492#diff-6cbed09935af5348af95a7fe0c504191ac5e2ee347e0325d5d89d6237dd90698) to fix the way AzureTenantId was being pulled from Browse Azure tree.
This fix simplifies things with AzureTenantId and will ensure the final selected tenant Id from dropdown ends up being populated in the model when opening the connection, and not the one that arrives to Connection Widget when pre-populating the dialog data (i.e., `this._azureTenantId` - which could be `undefined` as in this case), as the dropdown value should be the final …
> Fix issues when setting azureTenantId

- src/sql/base/browser/ui/table/plugins/autoSizeColumns.plugin.ts
This PR fixes #4438
only resize if the calculated width is larger than the current width.
> auto resize column update
