microsoft/azuredatastudio

extensions/notebook/package.json, extensions/notebook/yarn.lock
The root dependency is "@jupyterlab/services" and we cannot update to the latest version as it is a breaking change. 
I have played around with the notebooks a bit and it seems to be working. @chlafreniere, can you please verify that everything is working?
=> updating ajv

resources/xlf/en/schema-compare.xlf, resources/xlf/en/sql-database-projects.xlf
=> [Loc] updates to schema-compare and sql-database-projects xlfs

extensionsGallery-insider.json, extensionsGallery.json
Also updated date that I missed updating last time
@vchvlad FYI
=> Update stable extensions with new telemetry endpoint

resources/xlf/en/git.xlf
=> [Loc] update to xlfs 7-11-2022

extensions/mssql/config.json
Changes from previous version:
https://github.com/microsoft/sqltoolsservice/compare/4.1.0.13...4.1.0.16
=> Updating sts to get latest top operations fixes 

resources/xlf/en/sql.xlf
=> [Loc] update to loc 7-12-2022

package.json, yarn.lock
Bringing back vBump made here : https://github.com/microsoft/azuredatastudio/pull/19507/files
This was lost during the merge
=> Bring back tar vBump

src/sql/base/browser/ui/taskbar/media/disabled-actual-execution-plan-inverse.svg, src/sql/base/browser/ui/taskbar/media/disabled-actual-execution-plan.svg, src/sql/base/browser/ui/taskbar/media/enabled-actual-execution-plan-inverse.svg, src/sql/base/browser/ui/taskbar/media/enabled-actual-execution-plan.svg, src/sql/workbench/contrib/query/browser/queryActions.ts
This PR fixes #19701. The PR updates the icon that appears on the actual execution plan button.
Light Mode:
Dark Mode:
=> Updates Actual Execution Plan button icon

resources/localization/LCL/de/git.xlf.lcl, resources/localization/LCL/es/git.xlf.lcl, resources/localization/LCL/fr/git.xlf.lcl, resources/localization/LCL/it/git.xlf.lcl, resources/localization/LCL/ja/git.xlf.lcl, resources/localization/LCL/ko/git.xlf.lcl, resources/localization/LCL/pt-BR/git.xlf.lcl, resources/localization/LCL/ru/git.xlf.lcl, resources/localization/LCL/zh-Hans/git.xlf.lcl, resources/localization/LCL/zh-Hant/git.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220713153854779 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220713153854779 to main

extensions/arc/package.json, extensions/azcli/package.json
Bump arc and azcli version for hotfix where customloc error was blocking sql miaa create.
=> Bump to 1.4.1 for hotfix

src/sql/workbench/services/insights/common/insightsUtils.ts
This function was made async with the merge
Follow up issue I noticed : https://github.com/microsoft/azuredatastudio/issues/20036
=> Fix insight widgets not displaying

extensionsGallery-insider.json, extensionsGallery.json
Updating extension galleries for stable and insiders arc and azcli 1.4.1
=> Update extensiongallery for hotfix 1.4.1

src/sql/workbench/browser/modelComponents/editor.component.ts, src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts, src/sql/workbench/contrib/query/browser/query.contribution.ts, src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts, src/sql/workbench/services/queryEditor/browser/queryEditorService.ts, src/sql/workbench/services/queryEditor/test/browser/testQueryEditorService.ts, src/vs/workbench/services/editor/browser/editorService.ts, src/vs/workbench/services/editor/common/editorService.ts, src/vs/workbench/test/browser/workbenchTestServices.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/20036
=> Make createEditorInput async

package.json, remote/package.json, remote/web/package.json, remote/web/yarn.lock, remote/yarn.lock, src/sql/workbench/contrib/executionPlan/browser/azdataGraphView.ts, src/sql/workbench/contrib/executionPlan/browser/executionPlanComparisonEditorView.ts, yarn.lock
=> Making better ep node highlights

resources/localization/LCL/de/arc.xlf.lcl, resources/localization/LCL/es/arc.xlf.lcl, resources/localization/LCL/fr/arc.xlf.lcl, resources/localization/LCL/it/arc.xlf.lcl, resources/localization/LCL/ja/arc.xlf.lcl, resources/localization/LCL/ko/arc.xlf.lcl, resources/localization/LCL/pt-BR/arc.xlf.lcl, resources/localization/LCL/ru/arc.xlf.lcl, resources/localization/LCL/zh-Hans/arc.xlf.lcl, resources/localization/LCL/zh-Hant/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220718155101019 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220718155101019 to main

package.json
=> Version Bumping now that the release branch is forked

extensions/arc/package.nls.json
Missing comma in the package.nls.json file (causes the file to not be parsed properly)
=> Fix package.nls.json comma

resources/xlf/en/arc.xlf
=> [Loc] arc xlf update

extensions/query-history/package.json
(cherry picked from commit d31e33835cd8fa9f6bb8190e03fef618e39228db)
For https://github.com/microsoft/azuredatastudio/issues/20079
=> [RC1] vBump query history extension (#20081)

extensionsGallery.json
Fixes https://github.com/microsoft/azuredatastudio/issues/20079
=> [RC1] Update query-history to 0.2.1

src/sql/workbench/services/restore/browser/restoreDialog.ts, src/sql/workbench/services/restore/browser/restoreViewModel.ts
Port fix for https://github.com/microsoft/azuredatastudio/issues/19783 to release/1.38.
=> Fix restore dialog null references (#20096)

extensions/resource-deployment/src/ui/deployClusterWizard/pages/serviceSettingsPage.ts
For https://github.com/microsoft/azuredatastudio/issues/18594
=> Add size to aria labels on BDC deployments

extensions/resource-deployment/DEVELOPER_GUIDE.md
Add a reminder to use the CategoryValue's displayName as the defaultValue for options.
=> Updated CategoryValue defaultValue docs

extensionsGallery-insider.json, extensionsGallery.json
This PR updates the version number of the CosmosDB for Mongo extension to 0.1.2
vsix build is [here](https://msdata.visualstudio.com/CosmosDB/_build/results?buildId=67652852&view=artifacts&pathAsName=false&type=publishedArtifacts)
=> Rev up cosmosdb extension to 0.1.2

extensions/big-data-cluster/src/bigDataCluster/tree/controllerTreeDataProvider.ts
The view would get "stuck" showing the `Loading controllers...` message if there were no registered BDC clusters. This isn't a complete blocker since users could still run the commands to register a new BDC cluster just fine and then things would work as expected, it was only this initial load that things could get stuck.
This is because we were firing the `_onDidChangeTreeData` event while getting the children, which would cause it to cancel the original children query and end up returning undefined instead. 
getChildren is already a promise so instead of doing this roundabout way of loading where we kick off the load async'ly and then refresh the tree once it's done we just always wait to load the nodes when getting the children to start with. (the original method was likely due to the …
=> Fix BDC tree getting stuck loading

extensionsGallery.json
Langpacks can be retrieved here: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=164185&view=artifacts&pathAsName=false&type=publishedArtifacts
This will update the rc1 gallery with the latest langpacks
=> Extensions Gallery Update for RC1

extensionsGallery-insider.json
Companion PR for https://github.com/microsoft/azuredatastudio/pull/20131
=> Insider Gallery Update for Langpacks

src/sql/workbench/contrib/views/browser/treeView.ts
(cherry picked from commit 1367f29a8a5a90eac1e881fdfcc037d62077017a)
Fixes https://github.com/microsoft/azuredatastudio/issues/20137
=> [1.38] Fix null ref in contributed tree views (#20138)

package.json, remote/package.json, remote/web/package.json, remote/web/yarn.lock, remote/yarn.lock, src/sql/workbench/contrib/executionPlan/browser/executionPlanComparisonEditorView.ts, yarn.lock
This PR enables collapse/expand nodes in execution plans that are being compared by updating the azdataGraph version to 0.0.37.
=> Update azdataGraph version to 0.0.37

extensions/mssql/config.json
This PR fixes #20130
making a targeted fix directly in the release branch. A more complete fix will be made to main branch separately.
=> fix agent notebooks tab not loading issue

resources/localization/LCL/de/arc.xlf.lcl, resources/localization/LCL/de/resource-deployment.xlf.lcl, resources/localization/LCL/de/sql-database-projects.xlf.lcl, resources/localization/LCL/es/arc.xlf.lcl, resources/localization/LCL/es/resource-deployment.xlf.lcl, resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/fr/arc.xlf.lcl, resources/localization/LCL/fr/resource-deployment.xlf.lcl, resources/localization/LCL/fr/sql-database-projects.xlf.lcl, resources/localization/LCL/it/arc.xlf.lcl, resources/localization/LCL/it/resource-deployment.xlf.lcl, resources/localization/LCL/it/sql-database-projects.xlf.lcl, resources/localization/LCL/ja/arc.xlf.lcl, resources/localization/LCL/ja/resource-deployment.xlf.lcl, resources/localization/LCL/ja/sql-database-projects.xlf.lcl, resources/localization/LCL/ko/arc.xlf.lcl, resources/localization/LCL/ko/resource-deployment.xlf.lcl, resources/localization/LCL/ko/sql-database-projects.xlf.lcl, resources/localization/LCL/pt-BR/arc.xlf.lcl, resources/localization/LCL/pt-BR/resource-deployment.xlf.lcl, resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl, resources/localization/LCL/ru/arc.xlf.lcl, resources/localization/LCL/ru/resource-deployment.xlf.lcl, resources/localization/LCL/ru/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hans/arc.xlf.lcl, resources/localization/LCL/zh-Hans/resource-deployment.xlf.lcl, resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hant/arc.xlf.lcl, resources/localization/LCL/zh-Hant/resource-deployment.xlf.lcl, resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220722154031353 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220722154031353 to main

resources/xlf/en/resource-deployment.xlf
=> [Loc] change to resource deployment

extensionsGallery.json
Updating schema compare and sql database projects in the RC gallery.
Build with vsixs: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=164478&view=results
=> update Schema Compare and Sql Database Projects in RC gallery

resources/localization/LCL/de/resource-deployment.xlf.lcl, resources/localization/LCL/fr/resource-deployment.xlf.lcl, resources/localization/LCL/it/resource-deployment.xlf.lcl, resources/localization/LCL/ko/resource-deployment.xlf.lcl, resources/localization/LCL/pt-BR/resource-deployment.xlf.lcl, resources/localization/LCL/ru/resource-deployment.xlf.lcl, resources/localization/LCL/zh-Hans/resource-deployment.xlf.lcl, resources/localization/LCL/zh-Hant/resource-deployment.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220724153818370 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220724153818370 to main

resources/localization/LCL/es/resource-deployment.xlf.lcl, resources/localization/LCL/ja/resource-deployment.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220725153813588 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220725153813588 to main

extensions/mssql/config.json
=> vbump sts to bring in a dacfx fix

extensions/arc/package.json, extensions/azcli/package.json
Bumping versions of arc and azcli for bugbash
=> Bump to 1.4.2 for bugbash

extensions/sql-migration/src/dashboard/tabBase.ts
remove unnecessary webpack import and fix localization build break
=> hotfix - remove unnecessary webpack import

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220726153652100 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220726153652100 to main

resources/xlf/en/sql-migration.xlf
=> [Loc] SQL migration xlf update

src/sql/workbench/contrib/executionPlan/browser/executionPlanTreeTab.ts, src/sql/workbench/contrib/query/browser/queryResultsView.ts
=> Adding plan tree to execution plan

resources/xlf/en/sql.xlf
=> [Loc] added strings to sql.xlf

extensionsGallery.json
=> Post release merging extensions/rc1 back into release/extensions

CHANGELOG.md
=> updating changelog for 1.38

CHANGELOG.md
=> updating changelog for 1.38 (#20182)

extensions/mssql/config.json
changes since the current sts version.
=> bring the latest STS to ADS

CHANGELOG.md
=> updating changelog with additional changes

CHANGELOG.md
=> fixing indent

CHANGELOG.md
=> bringing the changes over to 1.38

resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql-migration.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220729153613975 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220729153613975 to main

resources/xlf/en/query-history.xlf
=> [Loc] addition to query-history

extensions/query-history/package.json
=> vBump query history

resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/arc.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/arc.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/arc.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/arc.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/arc.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220730154003990 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220730154003990 to main

resources/localization/LCL/de/arc.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/query-history.xlf.lcl, resources/localization/LCL/fr/query-history.xlf.lcl, resources/localization/LCL/it/arc.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/arc.xlf.lcl, resources/localization/LCL/ja/query-history.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/query-history.xlf.lcl, resources/localization/LCL/pt-BR/query-history.xlf.lcl, resources/localization/LCL/ru/arc.xlf.lcl, resources/localization/LCL/ru/query-history.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/arc.xlf.lcl, resources/localization/LCL/zh-Hans/query-history.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/query-history.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220731153825655 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220731153825655 to main

resources/localization/LCL/de/query-history.xlf.lcl, resources/localization/LCL/it/query-history.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220801153846057 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220801153846057 to main

extensions/mssql/config.json, extensions/mssql/package.json, extensions/mssql/src/utils.ts, src/sql/azdata.proposed.d.ts, src/sql/workbench/contrib/objectExplorer/test/browser/connectionTreeActions.test.ts, src/sql/workbench/contrib/scripting/test/browser/scriptingActions.test.ts, src/sql/workbench/services/objectExplorer/browser/mssqlNodeContext.ts, src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts, src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts, src/sql/workbench/services/objectExplorer/browser/serverTreeActionProvider.ts, src/sql/workbench/services/objectExplorer/common/treeNode.ts, src/sql/workbench/services/objectExplorer/common/treeNodeContextKey.ts, src/sql/workbench/services/objectExplorer/test/browser/asyncServerTreeDragAndDrop.test.ts, src/sql/workbench/services/objectExplorer/test/browser/dragAndDropController.test.ts, src/sql/workbench/services/objectExplorer/test/browser/objectExplorerService.test.ts
This PR fixes #20217
use new object type property instead of node's display string (localizable string) to determine what menu item to be displayed
with the fix:
=> fix menu item not showing up for non-English languages

extensions/sql-migration/src/wizard/skuRecommendationPage.ts
=> Adding ariaLive to assessment in progress in sql-migration extension

build/azure-pipelines/sql-product-build.yml
More DRI updates (to remove warnings)
=> Mac OS product build vm image bump

extensions/arc/package.json, extensions/azcli/package.json
Bump arc and azcli versions to 1.4.3.
=> Bump version for preview

extensions/sql-migration/src/wizard/databaseSelectorPage.ts, extensions/sql-migration/src/wizard/skuRecommendationPage.ts, src/sql/azdata.proposed.d.ts, src/sql/workbench/api/common/extHostModelView.ts, src/sql/workbench/browser/modelComponents/text.component.ts
=> Adding arialive to text component

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220804154127610 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220804154127610 to main

resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220805153740212 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220805153740212 to main

extensions/arc/package.json, extensions/azcli/package.json
- Bump Azure CLI extension to 1.5.0
- Bump Arc extension to 1.5.0
=> Bumped azure cli and arc ext to 1.5.0 in package.json

extensions/arc/src/ui/dashboards/miaa/miaaComputeAndStoragePage.ts, extensions/azcli/src/az.ts
- SyncSecondaryToCommit now a part of az sql mi-arc update
- Update field for SyncSecondaryToCommit now has a limit of 2
- Increment now works for SQL MIAA compute+storage page
https://user-images.githubusercontent.com/22386690/183537962-08399723-5a4b-443c-b3b3-c1b556018d16.mp4
=> Fixes to SQL MIAA Compute + Storage page

extensionsGallery-insider.json
- Release v2.0.0 with breaking changes.
- Enhanced the core framework.
Note: Existing assessments are unsupported with this latest update (v2.0.0). Please follow the [documentation](https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions/database-migration-assessment-for-oracle-extension) to access them
=> Updating extensionGallery-insider.json for release of v2.0.0 of DMAO

resources/xlf/en/sql.xlf
=> [Loc] small change to sql color value

src/sql/workbench/contrib/query/browser/gridPanel.ts
#19872
announce the critical events for query execution.
=> announce query execution events

resources/localization/LCL/de/arc.xlf.lcl, resources/localization/LCL/de/sql-database-projects.xlf.lcl, resources/localization/LCL/es/arc.xlf.lcl, resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/fr/arc.xlf.lcl, resources/localization/LCL/fr/sql-database-projects.xlf.lcl, resources/localization/LCL/it/arc.xlf.lcl, resources/localization/LCL/it/sql-database-projects.xlf.lcl, resources/localization/LCL/ja/arc.xlf.lcl, resources/localization/LCL/ja/sql-database-projects.xlf.lcl, resources/localization/LCL/ko/arc.xlf.lcl, resources/localization/LCL/ko/sql-database-projects.xlf.lcl, resources/localization/LCL/pt-BR/arc.xlf.lcl, resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl, resources/localization/LCL/ru/arc.xlf.lcl, resources/localization/LCL/ru/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hans/arc.xlf.lcl, resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hant/arc.xlf.lcl, resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220810153751933 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220810153751933 to main

extensions/arc/src/ui/dashboards/miaa/miaaComputeAndStoragePage.ts
Reverts back to original workaround
=> Fix compute+storage always disabled

extensions/mssql/package.json
there are users reporting issues with this turned on by default, I'll have to revert the value to false and then investigate the issues later.
=> set the default value to false

src/vs/workbench/contrib/extensions/browser/extensionEditor.ts
#19895
ADS doesn't have multi-version support for extensions.
=> comment out install another version action for extension

resources/xlf/en/sql.xlf
=> [Loc] added sql query execution lines

extensionsGallery-insider.json, extensionsGallery.json
Hotfix version bump for this bug: https://github.com/microsoft/azuredatastudio/pull/20305
=> Update extensiongalleries for 1.5.1 hotfix - arc and azcli

extensionsGallery-insider.json, extensionsGallery.json
- Release v2.0.1 with breaking changes.
- Enhanced the core framework.
Note: Existing assessments are unsupported with this latest update (v2.0.0). Please follow the [documentation](https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions/database-migration-assessment-for-oracle-extension) to access them
=> Updating the release version to 2.0.1

resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/arc.xlf.lcl, resources/localization/LCL/fr/sql-database-projects.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220811153733711 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220811153733711 to main

resources/xlf/en/sql-migration.xlf, resources/xlf/en/sql.xlf
=> [Loc] update to sql and sql-migration xlfs

src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR fixes #19694
previously, we are hardcoding the copy keybinding to CTRL/cmd + C, if the user changes the keybinding, it won't work in the query result grid.
=> grid copy handler

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220812154545836 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220812154545836 to main

extensions/mssql/config.json
This PR fixes #20133.
Bringing in these commits from STS. FYI @nofield @raymondtruong @smartguest
=> update STS to 4.2.0.15

resources/xlf/en/sql.xlf
=> [Loc] addition of heading text

resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql-migration.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220813153636632 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220813153636632 to main

i18n/ads-language-pack-de/translations/main.i18n.json, i18n/ads-language-pack-es/translations/main.i18n.json, i18n/ads-language-pack-fr/translations/main.i18n.json, i18n/ads-language-pack-it/translations/main.i18n.json, i18n/ads-language-pack-ja/translations/main.i18n.json, i18n/ads-language-pack-ko/translations/main.i18n.json, i18n/ads-language-pack-pt-BR/translations/main.i18n.json, i18n/ads-language-pack-ru/translations/main.i18n.json, i18n/ads-language-pack-zh-hans/translations/main.i18n.json, i18n/ads-language-pack-zh-hant/translations/main.i18n.json, resources/xlf/de/sql.de.xlf, resources/xlf/es/sql.es.xlf, resources/xlf/fr/sql.fr.xlf, resources/xlf/it/sql.it.xlf, resources/xlf/ja/sql.ja.xlf, resources/xlf/ko/sql.ko.xlf, resources/xlf/pt-br/sql.pt-BR.xlf, resources/xlf/ru/sql.ru.xlf, resources/xlf/zh-hans/sql.zh-Hans.xlf, resources/xlf/zh-hant/sql.zh-Hant.xlf
=> json and xlf update for 8-13-2022

resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220814154448821 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220814154448821 to main

package.json
=> version bump post release branch split

resources/xlf/en/sql-bindings.xlf, resources/xlf/en/sql-migration.xlf
=> [Loc] update to sql-bindings and migration

extensionsGallery.json
Branch to get langpack files from:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=167447&view=results
=> Update to extensions gallery for rc1 langpacks

extensions/sql-bindings/src/common/azureFunctionsUtils.ts, extensions/sql-bindings/src/common/constants.ts
This PR fixes #19470.
PR in main: https://github.com/microsoft/azuredatastudio/pull/20336
* add output channel for SQL Bindings extension
=> [PORT] Add output channel for SQL Bindings extension (#20336)

extensions/mssql/config.json
This PR fixes #20360
changes included: https://github.com/microsoft/sqltoolsservice/pull/1640
=> fix for #20360

resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/es/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220817153846602 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220817153846602 to main

extensions/agent/src/dialogs/jobStepDialog.ts
Port fix for https://github.com/microsoft/azuredatastudio/issues/20171 to release/1.39.
=> Port Replace Job Step retry placeholders with values

extensions/mssql/config.json
https://github.com/microsoft/azuredatastudio/issues/20366
STS port PR: https://github.com/microsoft/sqltoolsservice/pull/1645
STS main PR: https://github.com/microsoft/sqltoolsservice/pull/1644
https://github.com/microsoft/sqltoolsservice/compare/4.2.1.3...4.2.1.4
=> [Port] Fix table designer reloading when only descriptions are being updated

src/sql/workbench/browser/designer/media/designer.css
part of the work for: https://github.com/microsoft/azuredatastudio/issues/20358
=> allow user to select text from the description box

extensions/sql-bindings/src/common/azureFunctionsUtils.ts, extensions/sql-bindings/src/dialogs/addSqlBindingQuickpick.ts, extensions/sql-bindings/src/services/azureFunctionsService.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/20353
PR in main: #20390
=> [PORT] Ensure SQL extension package installs latest 

extensions/notebook/src/book/bookTreeView.ts
* convert uri to vscode uri
This PR fixes https://github.com/microsoft/azuredatastudio/issues/20392
=> [Port] Fix unpin notebook  (#20393)

src/sql/workbench/browser/designer/designer.ts, src/sql/workbench/browser/designer/designerPropertiesPane.ts
for #20358
I decided to make it even better so that user can click on the links directly.
=> use markdown for description pane

extensions/mssql/config.json
https://github.com/microsoft/azuredatastudio/issues/20366
ADS Port PR: https://github.com/microsoft/azuredatastudio/pull/20394
https://github.com/microsoft/sqltoolsservice/compare/4.3.0.3...4.3.0.4
=> Fix table designer reloading when only descriptions are being updated

extensionsGallery.json
Updating schema compare and sql database projects for August release.
Build with vsixs: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=167957&view=results
=> update sql db projects and schema compare in RC gallery

extensionsGallery-insider.json
Updating these 2 extensions in insiders. Same vsixs as in the RC gallery PR #20408
=> update schema compare and sql db projects in insiders

resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220818153817313 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220818153817313 to main

extensions/sql-migration/src/dialog/skuRecommendationResults/getAzureRecommendationDialog.ts, extensions/sql-migration/src/wizard/skuRecommendationPage.ts
=> Adding arialabel to radio groups

src/sql/base/browser/ui/colorbox/colorbox.ts, src/sql/workbench/services/serverGroup/browser/serverGroupDialog.ts
after our today's chat, I went ahead to also apply this to a place I changed recently.
=> use aria-label for radio group

resources/xlf/en/sql.xlf
=> [Loc] remove serverGroup.colorValue

resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220820154110817 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220820154110817 to main

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220821153909700 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220821153909700 to main

resources/xlf/en/sql-migration.xlf
=> [Loc] sql-migration massive update

resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/es/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220824154604024 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220824154604024 to main

extensions/git/package.json, extensions/git/src/git.ts, extensions/git/yarn.lock
Completing dependabot PR : https://github.com/microsoft/azuredatastudio/pull/20153
VS Code did this recently - just taking their changes. https://github.com/microsoft/vscode/pull/156411
=> Bump file-type

CHANGELOG.md
=> Post release changelog update (#20458)

extensions/query-history/package.json
=> Bump query-history to 0.5.0

extensionsGallery.json
Bumping straight to 0.4.0 to get the latest fixes and features.
=> [Stable] Update query-history to 0.4.0

resources/xlf/en/schema-compare.xlf
=> [Loc] update to schema-compare

resources/xlf/en/arc.xlf, resources/xlf/en/sql-migration.xlf
=> [Loc] updates to arc and sql-migration

src/vs/platform/workspaces/electron-main/workspacesHistoryMainService.ts, src/vs/platform/workspaces/electron-main/workspacesMainService.ts, src/vs/workbench/browser/dnd.ts, src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts, src/vs/workbench/services/dialogs/electron-sandbox/fileDialogService.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/20453
This was actually behavior we inherited from VS Code, but they recently fixed it themselves so just porting over the fix here as well. https://github.com/microsoft/vscode/pull/157503
=> Add saved files to recently opened

resources/localization/LCL/de/arc.xlf.lcl, resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/es/arc.xlf.lcl, resources/localization/LCL/fr/arc.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/it/arc.xlf.lcl, resources/localization/LCL/ja/arc.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ko/arc.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/arc.xlf.lcl, resources/localization/LCL/ru/arc.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/arc.xlf.lcl, resources/localization/LCL/zh-Hant/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220829153730357 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220829153730357 to main

extensions/mssql/config.json
Update STS to pick up the async revert update for issue https://github.com/microsoft/azuredatastudio/issues/20472.
=> Bumps STS to pick async revert

extensions/mssql/config.json
Port the STS update for https://github.com/microsoft/azuredatastudio/issues/20472 to release/1.39 branch.
=> Update STS to 4.2.1.6 for async revert

resources/localization/LCL/es/arc.xlf.lcl, resources/localization/LCL/es/sql-migration.xlf.lcl, resources/localization/LCL/it/arc.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/arc.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/arc.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/arc.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220830154019353 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220830154019353 to main

extensions/data-workspace/package.json
bumping the version after the August 2022 release
=> vbump data workspace

CHANGELOG.md
Update the changelog for 1.39.1 hotfix release.
=> Update changelog for 1.39.1 release

README.md
Update the fwlinks in readme for 1.39.1.  Currently they refer to 1.37.0.
=> Update fwlinks in readme for 1.39.1

src/sql/azdata.d.ts
This PR updates the documentation based on suggestions from: https://github.com/microsoft/sqltoolsservice/pull/1660
=> Update to connectioninfo documentation for ErrorMessage and Messages

extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts, extensions/sql-migration/src/constants/strings.ts, extensions/sql-migration/src/dialog/assessmentResults/assessmentResultsDialog.ts, extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts, src/sql/azdata.d.ts, src/sql/azdata.proposed.d.ts, src/sql/base/browser/dom.ts, src/sql/base/test/browser/dom.test.ts, src/sql/workbench/browser/modelComponents/listView.component.html, src/sql/workbench/browser/modelComponents/listView.component.ts, src/sql/workbench/browser/modelComponents/media/listView.css
This PR fixes #19866
Before:
After:
=> Adding image support to list view

extensions/sql-database-projects/src/common/utils.ts, extensions/sql-database-projects/src/models/project.ts
Moving this to utils so that it can easily be reused elsewhere. I'm planning on using it for the fix for #19788
=> move checking if a file contains a create table statement to utils

resources/xlf/en/sql-database-projects.xlf, resources/xlf/en/sql-migration.xlf
=> [Loc] sql updates 8-31-2022

extensions/sql-database-projects/src/test/netCoreTool.test.ts, extensions/sql-database-projects/src/tools/netcoreTool.ts
=> Update default .NET installation for Linux

resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220901153516789 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220901153516789 to main

resources/xlf/en/azurecore.xlf
=> [Loc] update to Azurecore xlf

resources/localization/LCL/de/sql-database-projects.xlf.lcl, resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/es/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql-database-projects.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/it/sql-database-projects.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql-database-projects.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ko/sql-database-projects.xlf.lcl, resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/ru/sql-database-projects.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220902153839952 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220902153839952 to main

extensions/mssql/config.json, src/sql/azdata.proposed.d.ts, src/sql/workbench/services/tableDesigner/browser/media/tableDesignerPublishDialog.css, src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts, src/sql/workbench/services/tableDesigner/browser/tableDesignerPublishDialog.ts
This PR fixes #20421 
This PR fixes #20359 
This PR fixes #20352 
This PR fixes #20351 
This PR fixes #20345 
changes in STS since current version:
=> a few table designer fixes

resources/localization/LCL/de/azurecore.xlf.lcl, resources/localization/LCL/fr/azurecore.xlf.lcl, resources/localization/LCL/it/azurecore.xlf.lcl, resources/localization/LCL/ko/azurecore.xlf.lcl, resources/localization/LCL/ko/sql-database-projects.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/azurecore.xlf.lcl, resources/localization/LCL/ru/azurecore.xlf.lcl, resources/localization/LCL/zh-Hans/azurecore.xlf.lcl, resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220903154829706 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220903154829706 to main

resources/localization/LCL/es/azurecore.xlf.lcl, resources/localization/LCL/ja/azurecore.xlf.lcl, resources/localization/LCL/zh-Hant/azurecore.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220905153821003 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220905153821003 to main

extensions/azurecore/src/account-provider/simpleTokenCache.ts
Just fixing strict null check errors, leaving functionality as it is except for changing log messages to warn in some cases.
=> Strict null check SimpleTokenCache

extensions/azurecore/src/account-provider/auths/azureAuth.ts, extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts, extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts, extensions/azurecore/src/account-provider/utils/fileDatabase.ts, extensions/azurecore/src/account-provider/utils/simpleWebServer.ts
I'm going to look at replacing the current deferred usage at some point too - the way it's done now works fine but strict checking doesn't like it since it relies on setting up the deferred object in a callback. Using the same deferred object we use in a bunch of other extensions is a much easier way.
=> Fix more azurecore strict nulls

extensions/big-data-cluster/src/extension.ts
Warning will only show : 
- If the user has a BDC server registered
- The first time this is detected
=> Show warning about upcoming BDC deprecation

resources/xlf/en/azurecore.xlf, resources/xlf/en/big-data-cluster.xlf, resources/xlf/en/mssql.xlf
=> [Loc] updates to xlfs for 9-7-2022

resources/localization/LCL/de/sql-database-projects.xlf.lcl, resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/ja/sql-database-projects.xlf.lcl, resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl, resources/localization/LCL/ru/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220908153814093 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220908153814093 to main

extensionsGallery-insider.json, extensionsGallery.json
Link to VSIX:
https://microsoft.github.io/SandDance/dist/azdata/v4/azdata-sanddance-4.0.0.vsix
=> Update SandDance extension 4.0.0

resources/xlf/en/arc.xlf, resources/xlf/en/sql.xlf
=> [Loc] changes made to xlfs

resources/localization/LCL/es/azurecore.xlf.lcl, resources/localization/LCL/es/big-data-cluster.xlf.lcl, resources/localization/LCL/es/mssql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220910155317318 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220910155317318 to main

resources/localization/LCL/de/arc.xlf.lcl, resources/localization/LCL/es/arc.xlf.lcl, resources/localization/LCL/fr/arc.xlf.lcl, resources/localization/LCL/it/arc.xlf.lcl, resources/localization/LCL/ja/arc.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/arc.xlf.lcl, resources/localization/LCL/pt-BR/arc.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/arc.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/arc.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/arc.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220911154112401 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220911154112401 to main

resources/localization/LCL/de/arc.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/arc.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/arc.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/arc.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ko/arc.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220912153837684 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220912153837684 to main

extensions/notebook/src/test/book/book.test.ts
Skip these two book tests for now.
Tracking it here: https://github.com/microsoft/azuredatastudio/issues/20589
=> Skip failing book tests

resources/xlf/en/azurecore.xlf, resources/xlf/en/sql.xlf
=> [Loc] update to xlfs for 9-12-2022

resources/xlf/en/arc.xlf
=> [Loc] Removed strings for arc

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/azurecore.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/azurecore.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/azurecore.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/azurecore.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/azurecore.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220914154740040 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220914154740040 to main

resources/localization/LCL/de/azurecore.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/fr/azurecore.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/azurecore.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ko/azurecore.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/zh-Hant/azurecore.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220915154141156 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220915154141156 to main

resources/xlf/en/mssql.xlf
=> [Loc] mssql update 9-15-2022

extensions/azurecore/src/azureResource/providers/azuremonitor/azuremonitorService.ts, extensions/azurecore/src/azureResource/providers/cosmosdb/mongo/cosmosDbMongoService.ts, extensions/azurecore/src/azureResource/providers/database/databaseService.ts, extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerService.ts, extensions/azurecore/src/azureResource/providers/kusto/kustoService.ts, extensions/azurecore/src/azureResource/providers/mysqlFlexibleServer/mysqlFlexibleServerService.ts, extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerService.ts, extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerService.ts, extensions/azurecore/src/azureResource/providers/resourceGroup/resourceGroupService.ts, extensions/azurecore/src/azureResource/providers/resourceTreeDataProviderBase.ts, extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceService.ts, extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcService.ts, extensions/azurecore/src/azureResource/resourceTreeNode.ts, extensions/azurecore/src/azureResource/services/cacheService.ts, extensions/azurecore/src/azureResource/services/subscriptionFilterService.ts, extensions/azurecore/src/azureResource/services/subscriptionService.ts, extensions/azurecore/src/azureResource/services/terminalService.ts
Same general stuff as the others, mostly just setting proper default values and occasionally doing some extra null checking and throwing a useful error if it fails.
=> More Azure strict nulls

resources/localization/LCL/de/mssql.xlf.lcl, resources/localization/LCL/es/mssql.xlf.lcl, resources/localization/LCL/fr/mssql.xlf.lcl, resources/localization/LCL/it/mssql.xlf.lcl, resources/localization/LCL/ja/mssql.xlf.lcl, resources/localization/LCL/ko/mssql.xlf.lcl, resources/localization/LCL/pt-BR/mssql.xlf.lcl, resources/localization/LCL/ru/mssql.xlf.lcl, resources/localization/LCL/zh-Hans/mssql.xlf.lcl, resources/localization/LCL/zh-Hant/mssql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220917155636544 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220917155636544 to main

extensions/azurecore/src/test/account-provider/auths/azureAuth.test.ts, extensions/azurecore/src/test/azureResource/resourceTreeNode.test.ts, extensions/azurecore/src/test/azureResource/tree/accountNotSignedInTreeNode.test.ts, extensions/azurecore/src/test/azureResource/tree/accountTreeNode.test.ts, extensions/azurecore/src/test/azureResource/tree/subscriptionTreeNode.test.ts, extensions/azurecore/src/test/azureResource/tree/treeProvider.test.ts, extensions/azurecore/src/test/stubs/credentialsTestProvider.ts, extensions/azurecore/tsconfig.json
Last ones! 🎉 All test stuff this time.
(strict is inherited from tsconfig.base.json so can just completely remove it here now)
=> Finish strict null azurecore

resources/xlf/en/sql.xlf
=> [Loc] updated sql xlf

src/sql/workbench/services/fileBrowser/browser/fileBrowserTreeView.ts, src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
=> fix: typos

test/smoke/README.md, test/smoke/src/sql/areas/notebook/addRemoteBook.test.ts, test/smoke/src/sql/areas/notebook/createBook.test.ts, test/smoke/src/sql/areas/notebook/notebook.test.ts, test/smoke/test/index.js
This PR fixes #20637
The only change I need to make in the ADO is to change the default value of VSCODE_BUILD_MACOS variable to true in the unstable test cases build pipeline.
I've kicked 2 builds to do final verification.
=> introduce unstable smoke test suite

resources/xlf/en/sql.xlf
=> [Loc] sql xlf update 9-21-2022

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220923153849880 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220923153849880 to main

resources/xlf/en/sql.xlf
=> [Loc] update to execution plan

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220925153838700 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220925153838700 to main

extensions/azurecore/src/account-provider/auths/azureAuth.ts, extensions/azurecore/src/account-provider/azureAccountProvider.ts, extensions/azurecore/src/account-provider/providerSettings.ts
Reverts microsoft/azuredatastudio#20665
=> Revert "Fix Scope, Azure Pane"

resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220926153737001 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220926153737001 to main

extensionsGallery-insider.json
Updates SsmsMin to 16.0.19061.0
=> Update admin-tools-ext-win to 0.1.0

resources/xlf/en/sql-migration.xlf
=> [Loc] update to sql-migration xlfs

resources/xlf/en/sql-migration.xlf
=> [Loc] sql-migration update

resources/localization/LCL/es/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220928153802150 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220928153802150 to main

extensions/mssql/config.json
This PR fixes #20659
This PR fixes #20660 
Changes since last STS version: https://github.com/microsoft/sqltoolsservice/compare/4.3.0.26...4.3.0.30
=> bump STS to bring in table designer fixes

resources/xlf/en/sql.xlf
=> [Loc] added sql xlf update

src/sql/workbench/contrib/executionPlan/browser/executionPlanPropertiesViewBase.ts, src/sql/workbench/contrib/executionPlan/browser/topOperationsTab.ts
=> Fixing filter stylings

resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220930154803138 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20220930154803138 to main

extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerTreeDataProvider.ts
This PR fixes #17036 for `databaseServers\`
(partially fixed for `database\` in PR #16999)
https://user-images.githubusercontent.com/13396919/192958051-72048afd-0119-49bb-a466-38013ed314d3.mp4
https://user-images.githubusercontent.com/13396919/192957863-9ebb98ed-afb8-4511-99da-36fe787b304a.mp4
=> Fix default SQL Login prompts in SQL Servers under Azure Tree

extensions/microsoft-authentication/src/AADHelper.ts
We do not use this redirect-uri location, so just changing it back at @Charles-Gagnon request.
=> Change Redirect URI 

extensionsGallery-insider.json
- This adds the [MySQL extension](https://github.com/microsoft/azuredatastudio-mysql) to the Insider build catalog.
- VSIX File for MySQL Extension: [MySQL Extension VSIX 0.2.1](https://github.com/microsoft/azuredatastudio-mysql/releases/download/v0.2.1/azuredatastudio-mysql-0.2.1.vsix)
=> Add MySQL extension to Insider catalog

src/vs/platform/telemetry/common/telemetryLogAppender.ts
Also updating text to match latest from VS Code
https://github.com/microsoft/vscode/blob/main/src/vs/platform/telemetry/common/telemetryLogAppender.ts#L27
=> Use ADS name for telemetry log

extensions/query-history/README.md, extensions/query-history/package.json, extensions/query-history/package.nls.json, extensions/query-history/src/constants.ts, extensions/query-history/src/main.ts, extensions/query-history/src/queryHistoryProvider.ts
Update to match latest changes. Also adding helper command to open the storage folder.
=> Update Query History README

extensions/query-history/README.md, extensions/query-history/package.json, extensions/query-history/package.nls.json, extensions/query-history/src/constants.ts, extensions/query-history/src/main.ts, extensions/query-history/src/queryHistoryProvider.ts, extensions/query-history/src/test/queryHistoryProvider.test.ts
Loading with entries stored
Loading with no entries stored
=> Add loading text to query history view

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221001154740767 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221001154740767 to main

resources/localization/LCL/ja/git.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221004153807318 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221004153807318 to main

extensions/mssql/package.json, extensions/sql-database-projects/package.json, src/sql/workbench/contrib/tableDesigner/browser/tableDesignerEditor.ts
Getting ready for the Oct release. 🎆 🎈 🎉
=> Remove preview flag for table designer

resources/xlf/en/kusto.xlf, resources/xlf/en/mssql.xlf, resources/xlf/en/query-history.xlf, resources/xlf/en/sql-migration.xlf, resources/xlf/en/sql.xlf
=> [Loc] first xlf update of the day for 10-4

resources/xlf/en/sql.xlf
=> [Loc] removed missing string in sql.xlf

resources/xlf/en/sql-migration.xlf, resources/xlf/en/sql.xlf
=> [Loc] sql and sql-migration xlf updates

extensions/azurecore/src/azureResource/services/subscriptionService.ts
Before: seeing multiple of same subscription under one account
After: Only seeing on of each subscription for an MSAL account
=> Fix multiple of same subscription under MSAL account

extensionsGallery-insider.json
This PR updates the Insiders extension gallery to the latest release candidate version of the SQL Migration extension.
Link to `Azure Data Studio - Extensions` pipeline run containing vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=173834&view=results
=> [SQL Migration] Release 1.0.6 to Insiders

scripts/test-integration.sh
This PR updates the integration-test script to match the vscode one. It also prints all the children processes after running each test suite. 
Hopefully, it helps us figure out what exactly is happening here:  https://github.com/microsoft/azuredatastudio/issues/20593
Subprocess tree:
=> Updating integration test script and adding additional logging. 

resources/xlf/en/sql.xlf
=> [Loc] SQL xlf update

resources/localization/LCL/de/kusto.xlf.lcl, resources/localization/LCL/de/mssql.xlf.lcl, resources/localization/LCL/de/query-history.xlf.lcl, resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql-migration.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/kusto.xlf.lcl, resources/localization/LCL/ja/mssql.xlf.lcl, resources/localization/LCL/ja/query-history.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/kusto.xlf.lcl, resources/localization/LCL/zh-Hans/mssql.xlf.lcl, resources/localization/LCL/zh-Hans/query-history.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221007153957789 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221007153957789 to main

resources/xlf/en/sql.xlf
=> [Loc] update to sql XLF for 10/7/2022

extensionsGallery-insider.json
Releasing v3.0.0 for Database Migration Assessment for Oracle in insiders.
=> Adding DMAO v3.0.0 release in insiders

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221009154223734 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221009154223734 to main

resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221010154033643 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221010154033643 to main

src/sql/workbench/contrib/notebook/browser/cellViews/interfaces.ts
Remove smooth behavior from scroll
fix #20795
https://user-images.githubusercontent.com/34872381/194920337-7f63e790-a761-4fcc-99eb-023393a9e5d8.mov
=> Fix scroll to results

src/sql/workbench/contrib/commandLine/electron-browser/commandLine.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/20712
This requires https://github.com/microsoft/azuredatastudio/pull/20771 as well so that the extension is installed when we try to connect. 
There's still some more work that could be done here to improve this experience - currently it will always pop up the connection dialog because there isn't an account in the connection info so the connection fails. But that's "expected" behavior since we haven't ever tried to do anything with choosing the account automatically and that information isn't passed in the URI.
=> Handle unsupported providers when launching from command line

resources/xlf/en/sql.xlf
=> [Loc] small update to loc

resources/localization/LCL/fr/sql.xlf.lcl
This PR fixes CI build failures introduced due to conflicted change that got checked in with PR https://github.com/microsoft/azuredatastudio/pull/20791
Failing builds: https://dev.azure.com/ms/azuredatastudio/_build?definitionId=453&_a=summary
=> Resolve conflict in Loc file auto-commit

src/sql/workbench/contrib/executionPlan/browser/widgets/highlightExpensiveNodeWidget.ts, src/sql/workbench/contrib/executionPlan/browser/widgets/nodeSearchWidget.ts
This PR is to address issue 20781 by adding titles to the combo boxes and edit boxes that appear inside of widgets.
=> Adds titles to execution plan widget combo boxes

resources/xlf/en/sql.xlf
=> [Loc] added changes for executionPlan strings

build/azure-pipelines/sql-product-build.yml
spaces are not allowed in job name.
=> fix job name

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221013153919124 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221013153919124 to main

extensionsGallery-insider.json, extensionsGallery.json
Releasing v3.0.2 of Database Migration Assessment for Oracle in ads and ads-insiders.
=> Releasing v3.0.2 for Database Migration Assessment for Oracle

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221014154854270 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221014154854270 to main

extensions/mssql/config.json, src/sql/workbench/browser/scriptingUtils.ts
This PR fixes #20241
changes since current sts version:
also slide in a resource string change related to this as a follow up of my previous PR.: https://github.com/microsoft/azuredatastudio/pull/20843/files#r995228000
=> fix select top 1000 issue for Synapse databases

extensionsGallery-insider.json
link to extensions build artifacts:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=175102&view=artifacts&pathAsName=false&type=publishedArtifacts
=> updating sql-migration version to 1.1.0 for insiders

build/azure-pipelines/upload-sourcemaps.js, build/azure-pipelines/upload-sourcemaps.ts
Revert source map publishing changes for build break in official build.
=> Revert source map publishing for build break

extensionsGallery.json
link to extension artifacts:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=175590&view=artifacts&pathAsName=false&type=publishedArtifacts
=> release / update sql-migration version to 1.1.1 in public extension gallery

src/sql/base/browser/ui/table/media/slick.grid.css, src/sql/base/browser/ui/table/table.ts, src/sql/base/browser/ui/table/treeGrid.ts
Before:
After:
Light:
Dark:
HC:
=> Changing tree grid toggle icon color when the cell is selected

package.json, remote/package.json, remote/web/package.json, remote/web/yarn.lock, remote/yarn.lock, src/sql/workbench/contrib/executionPlan/browser/azdataGraphView.ts, src/sql/workbench/contrib/executionPlan/browser/executionPlanContribution.ts, src/sql/workbench/contrib/preferences/browser/sqlSettingsLayout.ts, yarn.lock
When enabled tooltips will show on hover, if disabled (default value) tooltip will show on click or 'F3'
Issue: #20796
When the window is extremely small, the tooltips are still visible and are aligned properly:
Now:
Before:
Issue: #20748
Graph nodes are highlighted using accessible colors:
Now:
Before:
Issue: #20765
Now tootips are announced to the user using the status api.
Issue: #20777 
Adding 'tree' role to right parent element fixed this issue:
https://github.com/microsoft/azdataGraph/blob/d37c74accb53bfc09368639d2372f57498f7adf7/src/js/azdata/azdataQueryPlan.js#L329
=> Adding accessible tooltips and tooltip based alerts

build/lib/optimize.js, build/lib/optimize.ts
=> set svgmin option

.github/workflows/ci.yml, build/azure-pipelines/darwin/sql-product-build-darwin.yml, build/azure-pipelines/linux/sql-product-build-linux.yml, build/azure-pipelines/win32/product-build-win32.yml, build/azure-pipelines/win32/sql-product-build-win32.yml, extensions/admin-tool-ext-win/src/test/extension.test.ts, extensions/data-workspace/src/test/workspaceService.test.ts, extensions/mssql/src/test/util/dataCache.test.ts, extensions/query-history/src/test/queryHistoryProvider.test.ts, extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts, scripts/test-extensions-unit.bat, scripts/test-extensions-unit.sh
I'm going to use this PR to reenabled tests post VSCode merge.  I may reach out to individual area owners to help investigate test failures in their areas.
=> Reenable disabled tests post VSCode refresh

build/azure-pipelines/darwin/sql-product-build-darwin.yml, build/azure-pipelines/linux/sql-product-build-linux.yml, scripts/test-integration.sh
Turn on integration tests disabled during recent VS Code refresh.
=> Reenable integration tests

extensions/schema-compare/package.json
updating schema compare's azdata dependency to 1.40.0
=> update schema compare azdata dependency to 1.40.0

extensions/query-history/package.json, extensions/query-history/src/localizedConstants.ts, extensions/query-history/src/queryHistoryProvider.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/20889
=> Add accessibility information to query history items

extensions/sql/cgmanifest.json, extensions/sql/syntaxes/sql.tmLanguage.json
Update grammar with latest from VS-Code MSSQL
https://github.com/microsoft/vscode-mssql/commits/main/syntaxes/SQL.plist
=> Update SQL grammar

src/sql/workbench/services/connection/browser/connectionWidget.ts
=> Fix get Modal value validation

src/sql/platform/connection/common/providerConnectionInfo.ts, src/sql/platform/connection/test/common/providerConnectionInfo.test.ts
=> Change back to existing identity design

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221015154310234 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221015154310234 to main

resources/localization/LCL/de/sql-database-projects.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql-database-projects.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql-database-projects.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql-database-projects.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql-database-projects.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221016153845711 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221016153845711 to main

src/sql/workbench/contrib/executionPlan/browser/executionPlanTab.ts, src/sql/workbench/contrib/executionPlan/browser/executionPlanTreeTab.ts, src/sql/workbench/contrib/executionPlan/browser/topOperationsTab.ts, src/sql/workbench/contrib/query/browser/queryEditor.ts, src/sql/workbench/services/query/common/queryManagement.ts
=> Remove preview flag from execution plan

src/vs/base/browser/dom.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/20978
Fixes https://github.com/microsoft/azuredatastudio/issues/20984
=> Fix embedded images not rendering

.yarnrc, cgmanifest.json, package.json, yarn.lock
Bump to the latest Electron 17 version to pickup minor bumps.
=> Update to latest Electron 17

resources/localization/LCL/de/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221028153820878 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221028153820878 to main

src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts, src/sql/workbench/browser/modelComponents/table.component.ts
=> Fixing schema compare checkbox column functions

extensions/notebook/src/book/bookTreeView.ts, src/vs/workbench/api/common/extHostTreeViews.ts, src/vs/workbench/browser/parts/views/treeView.ts
Reimplement drag and drop using the new vscode API.
=> Reimplement drag and drop with the new interface

extensions/mssql/config.json
Brings changes from latest STS release: https://github.com/microsoft/sqltoolsservice/compare/4.3.0.42...4.3.0.44
=> Update to latest STS release 4.3.0.44

extensionsGallery-insider.json, extensionsGallery.json
Extension ADO link: https://mssqltools.visualstudio.com/_apis/resources/Containers/4896041/drop?itemPath=drop%2Fextensions%2Fmachine-learning-0.12.0.vsix
=> Updated ML extension version in the gallery

build/gulpfile.vscode.js, src/vs/platform/environment/test/node/nativeModules.test.ts
=> Update @vscode/ripgrep path

extensions/mssql/config.json
PR shall fix issue #20985 
https://github.com/microsoft/sqltoolsservice/compare/4.3.0.44...4.3.0.45
=> Update SqlToolsService to v4.3.0.45

build/gulpfile.extensions.js
implements the change made in https://github.com/microsoft/azuredatastudio/commit/4ade808695a6636e2bed986a8fd1ca1cd6503da5 to the localization task (as it uses the same function)
=> Fix to localization task bundle marketplace extension build

extensionsGallery-insider.json, extensionsGallery.json
link to extensions build artifacts:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=177331&view=artifacts&pathAsName=false&type=publishedArtifacts
=> updating sql-migration version to 1.1.2 for insiders

extensionsGallery-insider.json, extensionsGallery.json
Link to VSIX:
https://microsoft.github.io/SandDance/dist/azdata/v4/azdata-sanddance-4.0.1.vsix
=> Update SandDance extension 4.0.1

extensions/import/package.json
=> remove preview flag

extensions/azurecore/src/azureResource/services/subscriptionService.ts
Removed localization from error messages as per this comment: https://github.com/microsoft/azuredatastudio/pull/20516#discussion_r959202510
This PR fixes #20524
=> Removed localization from error messages

resources/xlf/en/git.xlf, resources/xlf/en/query-history.xlf, resources/xlf/en/sql-database-projects.xlf, resources/xlf/en/sql-migration.xlf, resources/xlf/en/sql.xlf
=> [Loc] XLF update for 11-2-2022

extensionsGallery-insider.json, extensionsGallery.json
This PR fixes #20498
This PR fixes #20998 
I will remove the preview flag from extension's package.json in a separate PR.
=> remove preview flag for import extension

extensions/mssql/config.json
This PR fixes #20950
This PR fixes #20838 
https://github.com/microsoft/sqltoolsservice/compare/4.3.0.45...4.3.0.47
=> vbump sts to fix a couple table designer issues

extensions/sql-database-projects/src/test/projectController.test.ts
Adding a few tests for projectController.ts to increase code coverage in this file.
=> Add a few tests for projectController

resources/xlf/en/azurecore.xlf, resources/xlf/en/sql.xlf
=> [Loc] update to azurecore and sql xlfs

src/sql/workbench/contrib/welcome/notifyEncryption/notifyEncryptionDialog.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/21097
This PR fixes https://github.com/microsoft/azuredatastudio/issues/21098
=> Encryption welcome dialog followup

package.json, remote/package.json, remote/web/package.json, remote/web/yarn.lock, remote/yarn.lock, src/sql/workbench/contrib/executionPlan/browser/azdataGraphView.ts, src/sql/workbench/contrib/executionPlan/browser/widgets/highlightExpensiveNodeWidget.ts, yarn.lock
This PR fixes #20869.
Below is a gif of this working correctly:
=> Centers selected node found by the expensive operation widget

extensions/arc/package.json, extensions/azcli/package.json
Bumped Arc and Azure CLI to 1.7.0 for November release
=> Bump to 1.7.0 for Nov release

extensions/azuremonitor/package.json, extensions/azuremonitor/yarn.lock, extensions/kusto/package.json, extensions/kusto/yarn.lock, extensions/mssql/package.json, extensions/mssql/yarn.lock
update data protocol client to latest version.
=> update data protocol client to latest

resources/xlf/en/sql.xlf
=> [Loc] xlf update 11-4-2022

.github/workflows/ci.yml, build/azure-pipelines/linux/sql-product-build-linux.yml
This PR adjusts the pipeline build script to continue when the extension unit tests fail.
=> Extension unit tests should continue on error

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221107163900168 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221107163900168 to main

package.json
=> vbump post release branch split

extensionsGallery.json
Porting these from the insiders gallery into stable.
=> Update stable versions of .NET Interactive and Jupyter extensions.

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl
This PR adds in the latest checked in strings from last Friday's build of ADS.
Linked issue here: https://github.com/microsoft/azuredatastudio/issues/21142
=> Port Request last LEGO LCL check in for November Release

extensionsGallery.json
link to extensions build artifacts:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=177331&view=artifacts&pathAsName=false&type=publishedArtifacts
=> release / update sql-migration version to 1.1.2 in public extension gallery

extensionsGallery.json
This PR adds the MySQL Extension in RC1 gallery.
VSIX Link: https://github.com/microsoft/azuredatastudio-mysql/releases/download/v0.2.3/azuredatastudio-mysql-0.2.3.vsix
=> Adding MySQL extension to rc1 gallery

extensions/git/src/protocolHandler.ts
Follow-up port from vscode for issue https://github.com/microsoft/azuredatastudio/issues/21158.
=> Port VS Code issue 149177 (#21153)

src/sql/workbench/contrib/executionPlan/browser/executionPlanComparisonEditorView.ts, src/sql/workbench/contrib/executionPlan/browser/executionPlanContribution.ts, src/sql/workbench/contrib/executionPlan/browser/executionPlanView.ts
Fixes issue https://github.com/microsoft/azuredatastudio/issues/21167
=> Fix casing on execution plan command titles

src/sql/workbench/contrib/executionPlan/browser/executionPlanComparisonEditorView.ts, src/sql/workbench/contrib/executionPlan/browser/executionPlanContribution.ts, src/sql/workbench/contrib/executionPlan/browser/executionPlanView.ts
Port fix for https://github.com/microsoft/azuredatastudio/issues/21167 to release branch
=> Fix casing on execution plan command titles (#21170)

resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221109163936392 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221109163936392 to main

resources/xlf/en/sql.xlf
=> [Loc] small change to sql.xlf

extensions/sql-migration/package.json
This PR vbumps the SQL Migration extension, and also updates the dependent version of ADS to include the backend changes that will be available in the upcoming ADS 1.40 release.
=> [SQL Migration] Update package.json

extensions/sql-migration/src/api/utils.ts, extensions/sql-migration/src/constants/helper.ts
This PR adds an additional condition for migration cutover, only applicable to SQL MI cases. Discussed offline with team
=> [SQL Migration] Add additional condition for cutover 

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221110163839470 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221110163839470 to main

src/sql/workbench/services/connection/browser/cmsConnectionController.ts, src/sql/workbench/services/connection/browser/cmsConnectionWidget.ts, src/sql/workbench/services/connection/browser/connectionDialogService.ts
This PR will address #21177 for release/1.40 branch
(Ports commit from #21183)
=> [Release 1.40] Fix custom option support in CMS + update providername in provided profile

src/vs/base/common/idGenerator.ts
This PR fixes #19226 
PR to the main branch #21181
=> Updating id generation logic to avoid substring overlaps (#21181)

src/vs/base/common/idGenerator.ts
=> Adding SQL Carbon edit comment in vs idGenerator 

resources/xlf/en/sql-database-projects.xlf
=> [Loc] small update to sql-database-projects.xlf

src/sql/platform/serialization/common/serializationService.ts, src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts, src/sql/workbench/contrib/notebook/test/browser/dataResourceDataProvider.test.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/21180
Pr in main: https://github.com/microsoft/azuredatastudio/pull/21195
=> [Port] Fix headers being exported twice from notebooks

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221111164026766 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221111164026766 to main

resources/localization/LCL/de/sql-database-projects.xlf.lcl, resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/fr/sql-database-projects.xlf.lcl, resources/localization/LCL/it/sql-database-projects.xlf.lcl, resources/localization/LCL/ja/sql-database-projects.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql-database-projects.xlf.lcl, resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl, resources/localization/LCL/ru/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221113165604395 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221113165604395 to main

.github/label-actions.yml
Add instructions for workaround for #20924
=> Adds instructions to close Developer Tools Console

extensionsGallery.json
the version with new service downloader that works with macOS on ARM.
=> update kusto and azure monitor logs extensions

CHANGELOG.md, README.md
Readme and Changelog updates for 1.40
=> Updates for 1.40 readme and changelog

CHANGELOG.md
=> Typo in CHANGELOG

resources/xlf/en/sql-database-projects.xlf, resources/xlf/en/sql.xlf
=> [Loc] changes for 11/16/2022

extensions/sql-migration/src/api/azure.ts
Accidentally missed a comment on the previous PR https://github.com/microsoft/azuredatastudio/pull/21184: 
This PR removes unnecessary parameters from a few Azure Core API calls.
=> [SQL Migration] Address minor comment from previous PR 

resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql-database-projects.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/ko/sql-database-projects.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql-database-projects.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221118164216506 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221118164216506 to main

extensionsGallery.json
The extension gallery is missing the Query History GA bump.
=> Update query history extension for Nov

resources/localization/LCL/de/sql-database-projects.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/it/sql-database-projects.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql-database-projects.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221119163941295 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221119163941295 to main

resources/localization/LCL/de/sql-database-projects.xlf.lcl, resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/ja/sql-database-projects.xlf.lcl, resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl, resources/localization/LCL/ru/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221120164123198 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221120164123198 to main

resources/localization/LCL/fr/sql-database-projects.xlf.lcl, resources/localization/LCL/it/sql-database-projects.xlf.lcl, resources/localization/LCL/ko/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221121163735365 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221121163735365 to main

extensions/mssql/config.json, package.json
Fix for https://github.com/microsoft/azuredatastudio/issues/21245
=> Update SMO to 4.3.1.2

extensions/mssql/config.json
For https://github.com/microsoft/azuredatastudio/issues/21245
=> Bump STS to 4.4.0.7

resources/localization/LCL/de/sql-database-projects.xlf.lcl, resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/it/sql-database-projects.xlf.lcl, resources/localization/LCL/ko/sql-database-projects.xlf.lcl, resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl, resources/localization/LCL/ru/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221123173210096 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221123173210096 to main

extensionsGallery-insider.json, extensionsGallery.json
Upgrade the MySQL Extension in insider gallery.
VSIX File: https://github.com/microsoft/azuredatastudio-mysql/releases/download/v0.2.4/azuredatastudio-mysql-0.2.4.vsix
=> Upgrading mysql extension in insider gallery

resources/xlf/en/azurecore.xlf
=> [Loc] update to azurecore xlf 11-24-2022

resources/localization/LCL/de/azurecore.xlf.lcl, resources/localization/LCL/es/azurecore.xlf.lcl, resources/localization/LCL/fr/azurecore.xlf.lcl, resources/localization/LCL/it/azurecore.xlf.lcl, resources/localization/LCL/ja/azurecore.xlf.lcl, resources/localization/LCL/ko/azurecore.xlf.lcl, resources/localization/LCL/pt-BR/azurecore.xlf.lcl, resources/localization/LCL/ru/azurecore.xlf.lcl, resources/localization/LCL/zh-Hant/azurecore.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221125170229478 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221125170229478 to main

resources/localization/LCL/zh-Hans/azurecore.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221127163748785 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221127163748785 to main

extensionsGallery.json
Upgrading the MySQL extension version to 0.2.4 in stable release.
The version is already upgraded in insider release.
=> Upgrade mysql extension version to 0.2.4 in stable gallery

src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts
This PR fixes #21301
Since the file protocol is vscode-file and we're only checking for file, all the relative file links with protocol vscode-file are going through wrong flow and ending up being updated to absolute path.
=> check for file protocol of vscode-file

build/azure-pipelines/win32/sql-product-build-win32.yml, build/darwin/create-universal-app.js, build/darwin/create-universal-app.ts, extensions/azurecore/package.json, extensions/azurecore/yarn.lock
=> Skip signing node_modules

extensions/mssql/config.json
Bringing latest changes from STS:
https://github.com/microsoft/sqltoolsservice/compare/4.4.0.7...4.4.0.8
=> Update sqltoolsservice to v4.4.0.8

extensionsGallery-insider.json
This PR updates the Insiders extension gallery to the latest release candidate version of the SQL Migration extension. It also bumps the dependent version of ADS to 1.40, matching the extension definition.
Link to `Azure Data Studio - Extensions` pipeline run containing vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=179860&view=results
=> [SQL Migration] Release v1.1.3 to Insiders

extensionsGallery.json
Releasing v3.0.5 of Database Migration Assessment for Oracle in ads
=> Releasing v3.0.5 for Database Migration Assessment for Oracle

extensionsGallery-insider.json
Dotnet6 runtime extension version v1.1.0 with minor bug fixes for insider build
Changes:
Bug fixes.
=> Dotnet6 runtime extension v1.1.0 with bug fixes

extensionsGallery-insider.json, extensionsGallery.json
Version upgrade from v1.0.0 to v1.1.0.
- Bug fixes.
=> Dotnet6 Extension bug fixes.

samples/extensionSamples/yarn.lock, samples/sp_whoIsActive/yarn.lock, samples/sqlservices/yarn.lock, yarn.lock
=> Updating decode URI lib

resources/xlf/en/sql.xlf, src/sql/workbench/services/connection/browser/passwordChangeDialog.ts
=> [Loc] added small change to password change dialog localization

extensionsGallery-insider.json, extensionsGallery.json
Changes:
[CHANGELOG.md#2210-2022-12-08](https://github.com/wakatime/vscode-wakatime/blob/master/CHANGELOG.md#2210-2022-12-08)
=> Upgrade wakatime extension to v22.1.0

resources/localization/LCL/fr/arc.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221208163933102 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221208163933102 to main

resources/xlf/en/sql.xlf
=> [Loc] sql xlf update, add not supported kernal message

src/sql/workbench/contrib/query/browser/statusBarItems.ts
=> enhance the selection summary

resources/xlf/en/sql.xlf
=> [Loc] Added status query summary text

build/gulpfile.extensions.js, extensions/import/.vscodeignore, extensions/import/config.json, extensions/import/extension.webpack.config.js, extensions/import/package.json, extensions/import/yarn.lock
=> updating data client protocol in import extension

resources/xlf/en/import.xlf
=> [Loc] added refactored import.xlf

extensionsGallery-insider.json, extensionsGallery.json
=> Updating import to 1.5.4 in both insiders and stable

resources/localization/LCL/de/import.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/import.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/import.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/import.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/import.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/import.xlf.lcl, resources/localization/LCL/pt-BR/import.xlf.lcl, resources/localization/LCL/ru/import.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/import.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/import.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221211164417851 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221211164417851 to main

src/sql/workbench/contrib/query/browser/keyboardQueryActions.ts
=> Check current notebook cell when refreshing intellisense cache

extensions/sql-database-projects/src/models/project.ts
This PR fixes #21331. Using rm instead of the deprecated rmdir.
=> Remove fs.promises.rmdir

resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221213164123560 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221213164123560 to main

src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR fixes #21418
The regex that I updated recently contains some capture groups that are not efficient and caused the browser to hang, update it to use character set.
=> fix regex perf issue

extensions/mssql/config.json
This PR fixes #21401
This PR fixes #18714
=> new STS version

resources/xlf/en/azurecore.xlf
=> [Loc] remove cacheErrorRemove from azurecore xlf

extensionsGallery-insider.json
link to build:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=183541&view=artifacts&pathAsName=false&type=publishedArtifacts
=> updating sql-migration version to 1.2.0 for insiders

resources/xlf/en/sql-database-projects.xlf, resources/xlf/en/sql-migration.xlf
=> [Loc] update to sql-database-projects and sql-migration xlfs

extensions/mssql/config.json
This PR brings firewall rule name changes:
=> Update STS for firewall rule name

resources/xlf/en/sql-migration.xlf, resources/xlf/en/sql.xlf
=> [Loc] updates to sql-migration and sql

resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/es/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/ru/sql-database-projects.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221218164726369 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221218164726369 to main

extensionsGallery-insider.json, extensionsGallery.json
This PR sets the repository URL to the Azure Data Studio Github for the following 3 extensions:
1. .NET 6 Runtime
2. Oracle
3. DSCT (Database Schema Conversion Toolkit)
Note: The latter extension (DSCT) only updates the `extensionGallery-insider.json` file because the last release was intended to be available for insiders only.
=> Change the repository URL to point to the Azure Data Studio Github.

resources/localization/LCL/de/sql-database-projects.xlf.lcl, resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/es/sql-migration.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql-database-projects.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql-database-projects.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql-database-projects.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql-database-projects.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221220164135572 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20221220164135572 to main

src/vs/platform/terminal/node/terminalProfiles.ts
This PR ports fix https://github.com/microsoft/vscode/commit/fe7273d5402e326858e36f8272aa20e3ee7c096d for https://github.com/microsoft/vscode/issues/160827 Related PR: https://github.com/microsoft/vscode/pull/160845
=> Port fix for vscode issue 160827

package.json, src/vs/platform/terminal/node/terminalProfiles.ts
Ports fix https://github.com/microsoft/azuredatastudio/pull/21457 to release/1.40 branch.
=> Port fix for vscode issue 160827 to release/1.40

src/sql/workbench/contrib/dashboard/browser/dashboardActions.ts, src/sql/workbench/contrib/objectExplorer/test/browser/connectionTreeActions.test.ts
=> Fixes object explorer's manage keybinding shortcut

extensions/mssql/config.json
update STS for sql assessment version 1.1.17
=> update STS for sql assessment version 1.1.17 (#1797)

CHANGELOG.md
Update the changelog for the November Hotfix 2.
=> Update changelog for Nov Hotfix 2

extensionsGallery-insider.json
Releases v3.0.6 for Database Migration Assessment for Oracle extension.
=> Releasing v3.0.7 for DMAO

resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql-migration.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230102164143072 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230102164143072 to main

resources/xlf/en/azurecore.xlf
=> [Loc] update to azurecore xlf for 1-3-2023

src/sql/workbench/services/accountManagement/browser/media/accountPicker.css
Fixes https://github.com/microsoft/azuredatastudio/issues/21429
Just bringing back the styles for the dropdown on this dialog only, didn't dig into trying to refactor the layout to not need this stuff since it seems reasonable enough for now.
=> Fix Firewall Rule dialog dropdowns

src/sql/workbench/services/accountManagement/browser/accountManagementService.ts
=> Filter accounts based on Auth library in accounts management service

extensionsGallery.json
This PR releases version 3.0.7 for Database Migration Assessment for Oracle extension
=> Releasing v3.0.7 for DMAO extension

package.json, scripts/validateGalleries.js, yarn.lock
Validate that : 
- If an extension exists in stable it also exists in insiders (barring special case for deprecated extensions)
- That if an extension exists in both the stable version is <= insiders version
=> Validate extensions are valid between stable & insiders

package.json, remote/package.json, remote/web/package.json, remote/web/yarn.lock, remote/yarn.lock, yarn.lock
This PR fixes #2550
original PR: https://github.com/microsoft/SlickGrid.ADS/pull/12
=> fix navigation issue with up and down keys

scripts/validateGalleries.js
Makes this easier to work with. Could also make this a TS script, but then would have the extra overhead of having to transpile it which isn't really necessary for a simple script like this.
=> Add typings for validateGalleries script

extensionsGallery.json
This PR updates the worldwide extension gallery to the latest version of the SQL Migration extension. 
This vsix was already built, uploaded, and released to Insiders as part of https://github.com/microsoft/azuredatastudio/pull/21439.
=> [SQL Migration] Release v1.2.0 to worldwide

resources/localization/LCL/de/azurecore.xlf.lcl, resources/localization/LCL/es/azurecore.xlf.lcl, resources/localization/LCL/fr/azurecore.xlf.lcl, resources/localization/LCL/it/azurecore.xlf.lcl, resources/localization/LCL/ja/azurecore.xlf.lcl, resources/localization/LCL/ko/azurecore.xlf.lcl, resources/localization/LCL/pt-BR/azurecore.xlf.lcl, resources/localization/LCL/ru/azurecore.xlf.lcl, resources/localization/LCL/zh-Hans/azurecore.xlf.lcl, resources/localization/LCL/zh-Hant/azurecore.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230105171657930 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230105171657930 to main

resources/localization/LCL/ja/azurecore.xlf.lcl, resources/localization/LCL/zh-Hans/azurecore.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230106164035861 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230106164035861 to main

extensionsGallery-insider.json
=> changed install

extensionsGallery-insider.json, extensionsGallery.json
This PR has the changes which release v3.0.8 for Database Migration Assessment for Oracle extension.
=> Releasing v3.0.8 for DMAO

extensionsGallery-insider.json, extensionsGallery.json
This PR 
changes the version to 3.0.8 for Database Migration Assessment for Oracle extension.
=> Releasing v3.0.8 for Database Migration Assessment For Oracle extension in ADS

resources/xlf/en/sql.xlf
=> [Loc] update to SQL xlf for 1-11-2023

extensions/sql-migration/src/api/sqlUtils.ts, extensions/sql-migration/src/constants/strings.ts, extensions/sql-migration/src/dialog/retryMigration/retryMigrationDialog.ts, extensions/sql-migration/src/models/stateMachine.ts, extensions/sql-migration/src/wizard/databaseSelectorPage.ts, extensions/sql-migration/src/wizard/targetSelectionPage.ts
Adding collation validation in target database selection page.
collecting source database info including state, size, collation etc in the step 1 (select databases to assess and migrate)
comparing source database collation and target database collation in target selection page.
=> [SQLDB]collation validation 

extensions/mssql/config.json
Changes since last version [microsoft/sqltoolsservice@4.4.0.21...4.4.0.22](https://github.com/microsoft/sqltoolsservice/compare/4.4.0.21...4.4.0.22)
=> bump STS 4.4.0.22

resources/xlf/en/sql-migration.xlf
=> [Loc] update to sql-migration xlf

resources/xlf/en/sql-migration.xlf
=> [Loc] additional strings added to sql-migration

src/sql/workbench/services/connection/browser/connectionManagementService.ts
Small change to fix a possible null reference error as captured in https://github.com/microsoft/azuredatastudio/issues/7440#issuecomment-1378237248
=> Null check for info.errorNumber

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230113164226746 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230113164226746 to main

extensions/mssql/src/constants.ts, extensions/mssql/src/contracts.ts, extensions/mssql/src/mssql.d.ts, extensions/mssql/src/mssqlApiFactory.ts, extensions/mssql/src/sqlToolsServer.ts, extensions/mssql/src/tdeMigration/tdeMigrationService.ts
Contracts for tde-mi feature. No UI changes. 
Extracted from reviewed PR https://github.com/microsoft/azuredatastudio/pull/21573/files
+ Adding SQL Tools explicitly because we are modifying mssql code.
@Charles-Gagnon @aasimkhan30
=> tde-mi contracts

resources/xlf/en/mssql.xlf
=> [Loc] update to mssql xlf with tracing string

extensionsGallery.json
Upgrades the MySQL extension in stable gallery.
VSIX file: https://github.com/microsoft/azuredatastudio-mysql/releases/download/v0.2.5/azuredatastudio-mysql-0.2.5.vsix
=> Upgraded mysql extension in stable gallery

resources/localization/LCL/it/mssql.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/ko/mssql.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/mssql.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230116164552190 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230116164552190 to main

src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
Will help with issues such as https://github.com/microsoft/azuredatastudio/issues/21578
Only shows up when Developer Log Level is set to Trace
=> Add trace debug logging to OE service

extensionsGallery-insider.json, extensionsGallery.json
And moving to direct links now that we have it in the ADS repo
=> [Insiders] Update datavirtualization to 1.13.0

resources/xlf/en/mssql.xlf, resources/xlf/en/notebook.xlf, resources/xlf/en/resource-deployment.xlf, resources/xlf/en/sql.xlf
This reverts commit db329049ff28e5493edbce949e9d346db4a26feb.
Missed when bringing back BDC stuff in release branch, without these strings won't be localized.
=> [Port] Revert "[Loc] updates to xlfs after removal of BDC (#21375)"

.github/CODEOWNERS
=> Adding an owner for ML extension

extensions/machine-learning/package.json
We don't need to update ML extension for Jan release. I already verified version 0.12 works fine. This is for any future releases if needed.
=> Updating ML version for next release

extensionsGallery.json
@dzsquared spotted this mistake in the gallery file.
=> update repo for column-aligner

extensions/mssql/config.json
For https://github.com/microsoft/azuredatastudio/issues/21654
=> [RC1] Bump STS to 4.4.1.3

extensionsGallery-insider.json
Companion gallery update for https://github.com/microsoft/azuredatastudio/pull/21652
=> Update to insider gallery for release

resources/xlf/en/resource-deployment.xlf, resources/xlf/en/sql.xlf
=> [Loc] update to sql and resource-deployment xlfs for 1-19-2023

extensionsGallery.json
@chlafreniere FYI
This is just getting the new aiKey - missed doing this last release.
=> [RC1] Update sql-assessment to 0.6.4

src/sql/workbench/contrib/query/browser/gridPanel.ts
Porting fix to release branch.
This PR fixes #21645
=> [Port] Build vertical actionbar before results table so that it shows above the table. (#21668)

extensionsGallery.json
We good for this to make it into stable this release?
=> [RC1] Remove .NET Interactive extensions

extensionsGallery.json
=> [RC1] Add MongoDB extension

extensionsGallery.json
@sridharanprasanna @sergten - is this good for bring to the stable gallery?
=> [RC1] Update dsct-oracle-to-ms-sql to 0.3.0

resources/xlf/en/sql.xlf
=> [Loc] added sql.xlf schema

extensionsGallery-insider.json, extensionsGallery.json
Please find the corresponding [vsix build](https://msdata.visualstudio.com/_apis/resources/Containers/164520180/drop?itemPath=drop%2Fazure-cosmosdb-ads-extension-0.2.0.vsix) to upload.
=> Update azure-cosmosdb-ads-extension to 0.2.0

src/vs/workbench/contrib/notebook/browser/diff/diffElementOutputs.ts, src/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.ts, src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts
Porting VS Code commit https://github.com/microsoft/vscode/commit/5b8361bc717608db4359c2572d5b447f94bc3fb8.
=> Safer construction of notebook html (#170987)

src/vs/workbench/contrib/webview/browser/resourceLoading.ts
Porting vscode commit fad9089781c40e7b35e43076ca2951085aa8264d
=> Normalize resources when checking valid roots (#163327)

src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts
Port vscode commit d2cff714d5410c570043e259fd72c75bbf387b7a
=> Add allow list of valid notebook command uris (#163322)

src/vs/workbench/contrib/notebook/browser/diff/diffElementOutputs.ts, src/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.ts, src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts
Port...
Co-authored-by: Martin Aeschlimann <martinae@microsoft.com>
=> Safer construction of notebook html (#170987) (#21699)

src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts
Ports...
* Add allow list of valid notebook command uris (#163322)
This restricts notebooks to run three command uris. These 3 commands should all be safe to run, even with untrusted inputs
* Fix incorrectly resolved merge conflict
Co-authored-by: Matt Bierner <matb@microsoft.com>
=> Add allow list of valid notebook command uris (#163322) (#21701)

extensions/sql-migration/package.json
This PR bumps sql-migration version in order to release login migration to insiders gallery.
=> [SQL-Migration] Bump sql-migration version to 1.2.1

resources/xlf/en/sql-migration.xlf
=> [Loc] update to sql migration xlf for 1-23-23

extensions/sql-database-projects/src/test/dialogs/createProjectFromDatabaseQuickpick.test.ts
=> Cleanup sql project TestProject created by test

extensions/azurecore/src/azureResource/services/subscriptionService.ts
=> Do not show warning messages for stale Azure accounts

resources/xlf/en/arc.xlf, resources/xlf/en/sql.xlf
=> [Loc] update to arc and sql xlfs for 1-24-2023

extensionsGallery-insider.json
This PR updates the Insiders extension gallery to the latest release candidate version of the SQL Migration extension. 
Link to Azure Data Studio - Extensions pipeline run containing vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=187439&view=results
=> Bump sql-migration to 1.2.3 on insiders gallery

resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/es/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230125165553635 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230125165553635 to main

CHANGELOG.md, README.md
=> Post release Changelog/Readme updates

CHANGELOG.md, README.md
=> Post release Changelog/Readme updates (#21726)

resources/xlf/en/cms.xlf, resources/xlf/en/mssql.xlf, resources/xlf/en/sql-database-projects.xlf, resources/xlf/en/sql-migration.xlf
=> [Loc] updated xlfs for 1-25-2023

resources/localization/LCL/de/arc.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/arc.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/arc.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/arc.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/arc.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/arc.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/arc.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/arc.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/arc.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/arc.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230126164950302 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230126164950302 to main

extensions/cms/package.json, extensions/cms/package.nls.json, extensions/mssql/package.json, extensions/mssql/package.nls.json, resources/xlf/en/cms.xlf, resources/xlf/en/mssql.xlf
=> Introduce 'Command Timeout' option for MSSQL and CMS providers

package.json
=> updating version number for hotfix

resources/xlf/en/cms.xlf, resources/xlf/en/mssql.xlf
=> [Loc] changes to CMS and MSSQL xlfs

extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts
This PR fixes #21745
before:
fixed:
=> fix update project from db dialog not choosing the db of the connection

extensions/mssql/config.json
Update STS to 4.4.1.5
https://github.com/microsoft/sqltoolsservice/compare/4.4.1.4...4.4.1.5
=> [Hotfix 1.41] Update STS

src/sql/base/browser/ui/selectBox/selectBox.ts, src/sql/workbench/services/connection/browser/connectionWidget.ts
=> [Hotfix 1.41] Fix account and tenant selection behavior (#21749)

src/sql/workbench/services/connection/browser/connectionWidget.ts
=> [Port] Show tenant dropdown when selecting 'AzureMFA' for first time (#21763)

CHANGELOG.md
Update changelog for 1.41.1 hotfix.
=> Update changelog for 1.41.1

resources/localization/LCL/fr/cms.xlf.lcl, resources/localization/LCL/fr/mssql.xlf.lcl, resources/localization/LCL/it/cms.xlf.lcl, resources/localization/LCL/it/mssql.xlf.lcl, resources/localization/LCL/zh-Hans/cms.xlf.lcl, resources/localization/LCL/zh-Hans/mssql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230131164415383 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230131164415383 to main

src/sql/workbench/api/browser/mainThreadConnectionManagement.ts
This PR reverts changes from #21627 to `mainThreadConnectionManagement` that caused issues for inbuilt extensions ([reported here](https://github.com/microsoft/azuredatastudio/pull/21627#issuecomment-1411529492)).
Changing back the connection conversion logic to as before as the 'removeFunction' did not carry context of 'connectionManagementService' in Utils. It's best to keep the original conversion logic intact to avoid any issues, since it's not required to be changed.
=> Revert changes in mainThreadConnectionManagement

src/sql/platform/connection/common/utils.ts
Follow up PR to https://github.com/microsoft/azuredatastudio/pull/21802#discussion_r1093562590
=> Removed deepcopy and remove credentials functions from rpc conversion

resources/xlf/en/sql-database-projects.xlf, resources/xlf/en/sql-migration.xlf, resources/xlf/en/sql.xlf
=> [Loc] changes made to xlfs for 2-1-2023

resources/xlf/en/data-workspace.xlf
=> [Loc] update to the data-workspace xlf

extensionsGallery-insider.json, extensionsGallery.json
Link to VSIX:
https://microsoft.github.io/SandDance/dist/azdata/v4/azdata-sanddance-4.0.3.vsix
=> Update SandDance extension 4.0.3

extensionsGallery-insider.json
This PR updates the Insiders extension gallery to the latest release candidate version of the SQL Migration extension. This change includes bug fixes for login migrations, removing parameter that was blocking customers in in validate IR, and improved error messages for collation violations. 
Link to Azure Data Studio - Extensions pipeline run containing vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=188654&view=results
=> Bump sql-migration insiders version to 1.3.0

resources/localization/LCL/de/sql-database-projects.xlf.lcl, resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/fr/sql-database-projects.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql-database-projects.xlf.lcl, resources/localization/LCL/ja/sql-database-projects.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql-database-projects.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230203163954985 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230203163954985 to main

.github/workflows/update-galleries-list-reminder.yml
Clarifying who the message is meant for so external people aren't confused
=> Specify extension list update audience

resources/xlf/en/azurecore.xlf
=> [Loc] removed clouds from Azurecore

resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/es/sql-migration.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/it/sql-database-projects.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ru/sql-database-projects.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230204164312212 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230204164312212 to main

resources/localization/LCL/de/data-workspace.xlf.lcl, resources/localization/LCL/fr/data-workspace.xlf.lcl, resources/localization/LCL/ko/data-workspace.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230206164004959 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230206164004959 to main

resources/xlf/en/sql-database-projects.xlf
=> [Loc] Sql-Database-Projects XLF update

resources/xlf/en/mssql.xlf, resources/xlf/en/sql-database-projects.xlf, resources/xlf/en/sql.xlf
=> [Loc] update to xlfs for 2-7-2023

package.json
=> Bump to 1.41.2 for hotfix

extensions/mssql/src/sqlToolsServer.ts
=> auto reveal STS language client output channel only in dev mode

extensions/azurecore/src/account-provider/auths/azureAuth.ts, extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts, extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts
=> [Port] Fix Cloud Endpoints (#21805)

resources/localization/LCL/de/mssql.xlf.lcl, resources/localization/LCL/de/sql-database-projects.xlf.lcl, resources/localization/LCL/es/mssql.xlf.lcl, resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/fr/mssql.xlf.lcl, resources/localization/LCL/fr/sql-database-projects.xlf.lcl, resources/localization/LCL/it/mssql.xlf.lcl, resources/localization/LCL/it/sql-database-projects.xlf.lcl, resources/localization/LCL/ja/mssql.xlf.lcl, resources/localization/LCL/ja/sql-database-projects.xlf.lcl, resources/localization/LCL/ko/mssql.xlf.lcl, resources/localization/LCL/ko/sql-database-projects.xlf.lcl, resources/localization/LCL/pt-BR/mssql.xlf.lcl, resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl, resources/localization/LCL/ru/mssql.xlf.lcl, resources/localization/LCL/ru/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hans/mssql.xlf.lcl, resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hant/mssql.xlf.lcl, resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230209164917683 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230209164917683 to main

CHANGELOG.md
Document hotfixed issues from https://github.com/microsoft/azuredatastudio/milestone/97 into the changelog.
=> Update changelog for 1.41.2

extensions/mssql/config.json, src/sql/workbench/services/connection/browser/connectionManagementService.ts
This PR fixes #4105
This PR fixes #21884 
Remove the client-side sorting and only rely on the sorting in the server side so that collation is respected.
there are quite a lot of new changes in STS: https://github.com/microsoft/sqltoolsservice/compare/4.5.0.8...4.5.0.18
@cheenamalhotra , @SakshiS-harma , @Benjin , @aasimkhan30 , please confirm that your changes are good to be brought in here.
Before:
After:
SSMS:
=> remove client side sorting for db list

resources/localization/LCL/ko/mssql.xlf.lcl, resources/localization/LCL/zh-Hans/mssql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230210164036933 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230210164036933 to main

src/sql/workbench/contrib/telemetry/common/telemetry.contribution.ts
Clean up more noisy events that we don't care about
=> Filter more command IDs

extensions/mssql/src/objectManagement/ui/userDialog.ts
=> Fix references to dialogInfo

resources/localization/LCL/de/cms.xlf.lcl, resources/localization/LCL/de/mssql.xlf.lcl, resources/localization/LCL/es/cms.xlf.lcl, resources/localization/LCL/es/mssql.xlf.lcl, resources/localization/LCL/fr/cms.xlf.lcl, resources/localization/LCL/fr/mssql.xlf.lcl, resources/localization/LCL/it/cms.xlf.lcl, resources/localization/LCL/it/mssql.xlf.lcl, resources/localization/LCL/ja/cms.xlf.lcl, resources/localization/LCL/ja/mssql.xlf.lcl, resources/localization/LCL/ko/cms.xlf.lcl, resources/localization/LCL/ko/mssql.xlf.lcl, resources/localization/LCL/pt-BR/cms.xlf.lcl, resources/localization/LCL/pt-BR/mssql.xlf.lcl, resources/localization/LCL/ru/cms.xlf.lcl, resources/localization/LCL/ru/mssql.xlf.lcl, resources/localization/LCL/zh-Hans/cms.xlf.lcl, resources/localization/LCL/zh-Hans/mssql.xlf.lcl, resources/localization/LCL/zh-Hant/cms.xlf.lcl, resources/localization/LCL/zh-Hant/mssql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230212165154337 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230212165154337 to main

resources/localization/LCL/de/cms.xlf.lcl, resources/localization/LCL/de/mssql.xlf.lcl, resources/localization/LCL/es/cms.xlf.lcl, resources/localization/LCL/es/mssql.xlf.lcl, resources/localization/LCL/ko/cms.xlf.lcl, resources/localization/LCL/ko/mssql.xlf.lcl, resources/localization/LCL/pt-BR/cms.xlf.lcl, resources/localization/LCL/pt-BR/mssql.xlf.lcl, resources/localization/LCL/zh-Hans/cms.xlf.lcl, resources/localization/LCL/zh-Hans/mssql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230213164318709 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230213164318709 to main

extensionsGallery-insider.json, extensionsGallery.json
=> Updating DMAO extension to 4.0.1

src/sql/workbench/services/dialog/browser/wizardNavigation.component.ts
=> add aria-label for step link in wizard

extensionsGallery-insider.json
This PR updates the insiders extension gallery to the latest version of the SQL Migration extension. The main change here is the decoupling of the migration extension from STS, where we instead now use our own dedicated Migration service - see https://github.com/microsoft/azuredatastudio/pull/21781
+@aasimkhan30 to verify that no special changes are needed in the extension galleries with this new change.
Link to `Azure Data Studio - Extensions` pipeline run off `main` containing vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=189857&view=results
=> [SQL Migration] Release v1.4.0 to Insiders

resources/xlf/en/cms.xlf, resources/xlf/en/mssql.xlf, resources/xlf/en/sql-database-projects.xlf, resources/xlf/en/sql-migration.xlf, resources/xlf/en/sql.xlf
=> [Loc] update to XLFS for 2-13-2023

src/sql/workbench/services/profiler/browser/profilerFilterDialog.ts
https://msdata.visualstudio.com/Data%20Studio/_workitems/edit/1654895
=> move the focus to newly added filter field.

extensions/sql-migration/src/models/loginMigrationModel.ts, extensions/sql-migration/src/models/stateMachine.ts, extensions/sql-migration/src/wizard/loginMigrationStatusPage.ts, extensions/sql-migration/src/wizard/loginSelectorPage.ts
This PR refactors to encapsulate all login migration functionality into LoginMigrationModel
=> [SQL-Migration] Encapsulate all login migration functionality into LoginMigrationModel

extensions/dacpac/src/wizard/pages/deployConfigPage.ts
This PR addresses https://github.com/microsoft/azuredatastudio/issues/9326.
Upgrade existing database selected so database name is a dropdown:
New Database selected so database name is an input box:
=> Fix database name in dacpac wizard not saying required

src/sql/workbench/contrib/profiler/browser/profilerFindWidget.ts, src/sql/workbench/contrib/profiler/browser/profilerTableEditor.ts
In my previous PR: https://github.com/microsoft/azuredatastudio/pull/21931 I didn't properly handle the initial state of the find wdiget, in this PR, I fixed it and also moved the hide/show logic into the widget class.
https://msdata.visualstudio.com/Data%20Studio/_workitems/edit/1613458
=> fix the find widget hide issue

src/sql/workbench/services/profiler/browser/profilerFilterDialog.ts
1. announce the new clause action and remove all action
2. add aria-label for the value input component
https://msdata.visualstudio.com/Data%20Studio/_workitems/edit/1613311
https://msdata.visualstudio.com/Data%20Studio/_workitems/edit/1655604
=> profiler a11y bug fixes

extensionsGallery-insider.json
Updating the dacpac extension in insiders to release an accessibility fix.
Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=190067&view=artifacts&pathAsName=false&type=publishedArtifacts
=> Update dacpac extensions in insiders

resources/xlf/en/mssql.xlf, resources/xlf/en/sql.xlf
=> [Loc] update to mssql and sql xlf files

src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts, src/sql/workbench/contrib/objectExplorer/test/browser/serverTreeView.test.ts
Issue: #21578 
@cheenamalhotra , can you please verify if this fixes your issue. 
This has reduced another repeated create session call
=> Replacing select with focus in OE 

resources/localization/LCL/de/cms.xlf.lcl, resources/localization/LCL/de/mssql.xlf.lcl, resources/localization/LCL/de/sql-database-projects.xlf.lcl, resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/cms.xlf.lcl, resources/localization/LCL/es/mssql.xlf.lcl, resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/es/sql-migration.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/cms.xlf.lcl, resources/localization/LCL/fr/mssql.xlf.lcl, resources/localization/LCL/fr/sql-database-projects.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/pt-BR/cms.xlf.lcl, resources/localization/LCL/pt-BR/mssql.xlf.lcl, resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230216164409169 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230216164409169 to main

extensionsGallery-insider.json, extensionsGallery.json
Releasing this for DMAO ADS extension insiders and public
=> Releasing 4.0.2 of DMAO ADS Extension

extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
This PR fixes #21962.
Before the changes, database dropdown was getting reset while saving the "databaseName". 
Also, after loading profile, code wasn't trying to enable Publish and Generate Script buttons. Fixed that here as well.
=> Fix Publish project UI

src/sql/workbench/services/connection/browser/connectionWidget.ts
=> Fix missing null ref check causing extension issues

resources/localization/LCL/de/mssql.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/fr/mssql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/ja/mssql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/pt-BR/mssql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/mssql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hant/mssql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230217164703043 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230217164703043 to main

extensions/mssql/package.json, extensions/mssql/package.nls.json
=> Adding setting for OE expansion timeout

resources/localization/LCL/es/mssql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/it/mssql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ko/mssql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/zh-Hans/mssql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230218164737005 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230218164737005 to main

extensionsGallery-insider.json, extensionsGallery.json
Please find the binary [here](https://msdata.visualstudio.com/_apis/resources/Containers/169188863/drop?itemPath=drop%2Fazure-cosmosdb-ads-extension-0.2.1.vsix).
=> Update azure-cosmosdb-ads-extension to 0.2.1

resources/xlf/en/mssql.xlf
=> [Loc] update to MSSQL xlf for 2-21-2023

resources/xlf/en/data-workspace.xlf, resources/xlf/en/sql-database-projects.xlf
=> [Loc] update to strings for 2-21-2023 

extensionsGallery.json
Upgrades the MySQL extension in stable gallery.
=> upgraded mysql extension in stable gallery to 0.2.6

extensions/sql-migration/src/dashboard/migrationsListTab.ts, src/sql/azdata.proposed.d.ts, src/sql/base/browser/ui/table/plugins/hyperlinkColumn.plugin.ts, src/sql/workbench/browser/modelComponents/table.component.ts
=> Adding aria role to hyperlink cell in slickgrid

extensions/sql-database-projects/package.json
Updating the sql projects azdata dependency because the next release will depend on new changes from STS
=> update sql projects azdata dependency

resources/localization/LCL/de/data-workspace.xlf.lcl, resources/localization/LCL/de/mssql.xlf.lcl, resources/localization/LCL/de/sql-database-projects.xlf.lcl, resources/localization/LCL/es/mssql.xlf.lcl, resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/fr/mssql.xlf.lcl, resources/localization/LCL/fr/sql-database-projects.xlf.lcl, resources/localization/LCL/it/mssql.xlf.lcl, resources/localization/LCL/it/sql-database-projects.xlf.lcl, resources/localization/LCL/ja/data-workspace.xlf.lcl, resources/localization/LCL/ja/mssql.xlf.lcl, resources/localization/LCL/ja/sql-database-projects.xlf.lcl, resources/localization/LCL/ko/data-workspace.xlf.lcl, resources/localization/LCL/ko/mssql.xlf.lcl, resources/localization/LCL/ko/sql-database-projects.xlf.lcl, resources/localization/LCL/pt-BR/data-workspace.xlf.lcl, resources/localization/LCL/pt-BR/mssql.xlf.lcl, resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl, resources/localization/LCL/ru/data-workspace.xlf.lcl, resources/localization/LCL/ru/mssql.xlf.lcl, resources/localization/LCL/ru/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hans/data-workspace.xlf.lcl, resources/localization/LCL/zh-Hans/mssql.xlf.lcl, resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hant/data-workspace.xlf.lcl, resources/localization/LCL/zh-Hant/mssql.xlf.lcl, resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230223164743768 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230223164743768 to main

resources/xlf/en/azurecore.xlf, resources/xlf/en/mssql.xlf, resources/xlf/en/sql-migration.xlf, resources/xlf/en/sql.xlf
=> [Loc] update to xlfs for 2-23-2023

.eslintrc.json, package.json, remote/package.json, remote/web/package.json, remote/web/yarn.lock, remote/yarn.lock, src/vs/code/browser/workbench/workbench-dev.html, src/vs/code/browser/workbench/workbench.html, yarn.lock
This has been replaced by the azdataGraph package so isn't being used anymore
=> Remove kburtram-query-plan

resources/localization/LCL/es/data-workspace.xlf.lcl, resources/localization/LCL/es/mssql.xlf.lcl, resources/localization/LCL/es/sql-database-projects.xlf.lcl, resources/localization/LCL/fr/data-workspace.xlf.lcl, resources/localization/LCL/fr/mssql.xlf.lcl, resources/localization/LCL/fr/sql-database-projects.xlf.lcl, resources/localization/LCL/it/data-workspace.xlf.lcl, resources/localization/LCL/it/mssql.xlf.lcl, resources/localization/LCL/it/sql-database-projects.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230224164330029 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230224164330029 to main

resources/xlf/en/data-workspace.xlf
=> [Loc]  update to data-workspace xlf

resources/localization/LCL/fr/data-workspace.xlf.lcl, resources/localization/LCL/it/data-workspace.xlf.lcl, resources/localization/LCL/it/mssql.xlf.lcl, resources/localization/LCL/it/sql-database-projects.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/pt-BR/data-workspace.xlf.lcl, resources/localization/LCL/pt-BR/mssql.xlf.lcl, resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/zh-Hant/data-workspace.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230226165412143 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230226165412143 to main

resources/localization/LCL/de/data-workspace.xlf.lcl, resources/localization/LCL/de/mssql.xlf.lcl, resources/localization/LCL/de/sql-database-projects.xlf.lcl, resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/data-workspace.xlf.lcl, resources/localization/LCL/ja/data-workspace.xlf.lcl, resources/localization/LCL/ko/data-workspace.xlf.lcl, resources/localization/LCL/ru/data-workspace.xlf.lcl, resources/localization/LCL/zh-Hans/data-workspace.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230227163924260 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230227163924260 to main

extensions/sql-migration/src/dialog/skuRecommendationResults/getAzureRecommendationDialog.ts
=> Adding aria label to text fields 

extensions/mssql/src/objectManagement/ui/loginDialog.ts, extensions/mssql/src/objectManagement/ui/objectManagementDialogBase.ts, extensions/mssql/src/objectManagement/ui/userDialog.ts
use in-dialog loading indicator 
before
after
=> use the dialog's loading indicator

resources/xlf/en/sql-database-projects.xlf
=> [Loc] update to SQL-Database-Projects XLF for 2-27-2023

resources/xlf/en/mssql.xlf, resources/xlf/en/sql-database-projects.xlf
=> [Loc] update to mssql and sql-database-projects xlfs

build/gulpfile.vscode.win32.js
This PR fixes #21266
Before:
After:
=> Fix default install location for system installer of Windows on ARM build

extensions/sql-migration/src/constants/strings.ts
This PR updates the infobox for upcoming public preview mode.
=> Update login migration infobox for public preview

extensions/admin-tool-ext-win/README.md, extensions/azuremonitor/README.md, extensions/dacpac/README.md, extensions/datavirtualization/README.md, extensions/import/README.md, extensions/kusto/readme.md, extensions/notebook/README.md, extensions/query-history/README.md, extensions/resource-deployment/README.md, extensions/schema-compare/README.md, extensions/sql-assessment/README.md, extensions/sql-migration/README.md
Slight wording update on the Telemetry section text
=> Update extension READMEs

resources/xlf/en/mssql.xlf, resources/xlf/en/sql-migration.xlf
=> [Loc] update to mssql and sql-migration xlf files

extensions/sql-migration/src/constants/strings.ts, extensions/sql-migration/src/dialog/validationResults/validateIrDialog.ts, extensions/sql-migration/src/telemetry.ts
Adds error handling for validateIR gateway timeout and returns user friendly message.
=> add error handler for validateIR gateway timeout

extensions/sql-database-projects/src/controllers/projectController.ts, extensions/sql-database-projects/src/models/project.ts
Similar to https://github.com/microsoft/azuredatastudio/pull/22071, moving the STS call to update the project into project.ts
=> move delete sqlcmd variable to project.ts

extensions/sql-migration/README.md, extensions/sql-migration/src/constants/strings.ts
In this PR, the preview tag is removed across the SQL Migration extension for the SQL DB scenario, in preparation for GA.
Screenshots: 
- <img width="455" alt="image" src="https://user-images.githubusercontent.com/11844501/222280106-d173d49d-d617-4c35-96e8-b4c196cac5db.png">
=> [SQL Migration] Remove preview tag from SQL DB scenario

extensions/mssql/src/objectManagement/ui/objectManagementDialogBase.ts
This PR fixes #22105
use a promise to make sure the modelView is set before initializing the UI.
=> fix null reference issue

resources/xlf/en/mssql.xlf, resources/xlf/en/sql-migration.xlf
=> [Loc] xlf update for 3-2-2023

extensions/sql-database-projects/src/test/projectController.test.ts
Adding a couple small tests for the quickpicks for add and edit sqlcmd variable before I forget
=> Add test for add and edit sqlcmd variable

extensions/admin-pack/README.md, extensions/admin-tool-ext-win/README.md, extensions/agent/README.md, extensions/arc/README.md, extensions/asde-deployment/README.md, extensions/azcli/README.md, extensions/azurecore/README.md, extensions/azurehybridtoolkit/README.md, extensions/azuremonitor/README.md, extensions/cms/README.md, extensions/dacpac/README.md, extensions/data-workspace/README.md, extensions/datavirtualization/README.md, extensions/import/README.md, extensions/kusto/readme.md, extensions/machine-learning/README.md, extensions/notebook/README.md, extensions/profiler/README.md, extensions/query-history/README.md, extensions/resource-deployment/README.md, extensions/schema-compare/README.md, extensions/sql-assessment/README.md, extensions/sql-bindings/README.md, extensions/sql-database-projects/README.md, extensions/sql-migration/README.md
Update privacy statements with latest approved wording and to use fwlink instead of direct link.
=> Update extension privacy statements

build/lib/extensions.js
introduced in this commit: https://github.com/microsoft/azuredatastudio/commit/f53119c2a6f1d6f0e02fca3c703e73445c916cac#diff-840679d0c064c8c0ac3fc603b67d63fb20d7fa6137eed0a9ec56d94ac8230cfeL288
extensions.ts is updated but the compiled js file is not included.
=> update the compiled js file

extensions/sql-migration/config.json
This PR bumps up the Migration Service version to 4.5.0.38. This version includes login migration nuget changes to expose error codes to the user.
=> [SQL-Migration] Bump Migration Service version number

resources/localization/LCL/de/mssql.xlf.lcl, resources/localization/LCL/es/mssql.xlf.lcl, resources/localization/LCL/fr/mssql.xlf.lcl, resources/localization/LCL/it/mssql.xlf.lcl, resources/localization/LCL/it/sql-database-projects.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/ja/mssql.xlf.lcl, resources/localization/LCL/ko/mssql.xlf.lcl, resources/localization/LCL/pt-BR/mssql.xlf.lcl, resources/localization/LCL/ru/mssql.xlf.lcl, resources/localization/LCL/ru/sql-database-projects.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/mssql.xlf.lcl, resources/localization/LCL/zh-Hant/mssql.xlf.lcl, resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230303164110539 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230303164110539 to main

src/sql/workbench/services/connection/browser/connectionWidget.ts
This PR addresses ask for MySQL extension using AzureMFAAndUser to pre-populate username with selected Azure account's email.
_Recording includes fix from #22138_
=> Pre-populate username for selected user account (AzureMFAAndUser)

src/sql/workbench/services/connection/browser/cmsConnectionWidget.ts, src/sql/workbench/services/connection/browser/connectionWidget.ts
When changing auth mode, username field is not cleared everytime, this PR fixes the behavior.
Before:
After:
=> Fixes clearing of username/password on auth type change

resources/xlf/en/mssql.xlf, resources/xlf/en/sql.xlf
=> [Loc] updates to xlfs 3-5-2023

resources/localization/LCL/ko/azurecore.xlf.lcl, resources/localization/LCL/ko/mssql.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/zh-Hans/azurecore.xlf.lcl, resources/localization/LCL/zh-Hans/mssql.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230305164151174 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230305164151174 to main

resources/localization/LCL/de/azurecore.xlf.lcl, resources/localization/LCL/de/mssql.xlf.lcl, resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/mssql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/mssql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/mssql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/mssql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230306164853268 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230306164853268 to main

extensions/mssql/src/objectManagement/ui/userDialog.ts
=> disable the checkbox for schemas owned by user

extensions/mssql/src/objectManagement/ui/userDialog.ts
for #22173
port https://github.com/microsoft/azuredatastudio/pull/22178 to release branch.
=> disable the checkbox for schemas owned by user (#22178)

extensions/mssql/src/objectManagement/ui/userDialog.ts
Part of changes to finish user management for March tracked here https://github.com/microsoft/azuredatastudio/issues/22173.
=> Only support 'user with login' in dialog (#22175)

extensions/mssql/config.json
Update STS for latest user management changes.
=> Bump STS to 4.6.0.1

extensions/mssql/config.json
Porting changes related to https://github.com/microsoft/azuredatastudio/issues/22173.
=> Update STS to pickup user changes

extensions/mssql/src/objectManagement/commands.ts, extensions/mssql/src/objectManagement/ui/objectManagementDialogBase.ts
- Fix misspelling
- Add units, all measurements should generally have units associated with them
=> Fix telemetry property names

extensions/mssql/src/objectManagement/commands.ts, extensions/mssql/src/objectManagement/ui/objectManagementDialogBase.ts
(cherry picked from commit a575eb1b8744680295877ea7173730cb98db9073)
Fixes https://github.com/microsoft/azuredatastudio/issues/22192
=> [Port] Fix object management event property names (#22190)

resources/localization/LCL/fr/mssql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/mssql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/mssql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/mssql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/zh-Hant/mssql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230307165240996 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230307165240996 to main

extensions/mssql/config.json
PR in STS main https://github.com/microsoft/sqltoolsservice/pull/1907
Port PR in STS release https://github.com/microsoft/sqltoolsservice/pull/1910
STS changes since last version:
https://github.com/microsoft/sqltoolsservice/compare/4.5.1.1...4.5.1.2
=> [Port Requst] Update STS to pick up login fix

extensionsGallery.json
=> [RC1] Update Powershell to 2023.2.1

extensionsGallery-insider.json
=> [Insiders] Update Powershell to 2023.2.1

extensions/query-history/src/main.ts
Test code snuck in during my last PR here....https://github.com/microsoft/azuredatastudio/pull/22069
=> Fix query history storage folder creation

src/sql/workbench/services/executionPlan/common/executionPlanService.ts
Issue: #22237 
Was a wrong syntax in the for loop
=> Fixing execution plan not finding provider

src/sql/workbench/services/executionPlan/common/executionPlanService.ts
This PR fixes #22237 
Link to main PR #22238
=> Fixing execution plan not finding provider (#22238)

extensions/mssql/config.json
Bump STS to pick-up several bug fixes.
=> Bump STS to 4.5.1.3 in release/1.42

extensions/mssql/src/utils.ts
Ports #22233 to release branch
=> [Release 1.42] Include App Path in service launch arguments (#22233)

extensionsGallery.json
This PR updates the insiders extension gallery to the latest version of the SQL Migration extension. This is the same version as in Insiders.
=> Akma/sql migrations 1.4.2

extensions/data-workspace/src/dialogs/newProjectDialog.ts, extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts, extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
This PR addresses https://github.com/microsoft/azuredatastudio/issues/22134.
=> Add required property in missing places in sql projects

extensions/sql-database-projects/src/test/project.test.ts, extensions/sql-database-projects/src/test/projectController.test.ts
Fixing a couple database reference tests that started failing after the swap to call STS for these operations
=> fix a couple database reference tests

extensions/sql-database-projects/src/sqldbproj.d.ts, extensions/sql-database-projects/src/test/utils.test.ts
Updating the text from "Azure Synapse Dedicated SQL Pool" to "Azure Synapse SQL Pool" now that DacFx supports serverless sql pools
=> update target platform text for azure synapse sql pool

extensions/mssql/config.json, extensions/mssql/src/objectManagement/commands.ts, extensions/mssql/src/objectManagement/localizedConstants.ts, extensions/mssql/src/objectManagement/objectManagementService.ts, extensions/mssql/src/objectManagement/ui/objectManagementDialogBase.ts, extensions/mssql/src/objectManagement/ui/userDialog.ts
1. use latest STS to bring in user management bug fixes
2. handle the scenario that connection uri cannot be retrieved.
3. close the dialog if something goes wrong when initializing the dialog instead of keeping the loading dialog open forever.
4. fix a typo in the management service.
=> user management fixes

extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts
This PR addresses https://github.com/microsoft/azuredatastudio/issues/22100 and https://github.com/microsoft/azuredatastudio/issues/22099 by adding aria labels and required
=> fix accessibility issues in update project from db dialog

extensions/azurecore/src/account-provider/auths/azureAuth.ts, src/sql/platform/accounts/common/accountStore.ts
Addresses below error captured in log in https://github.com/microsoft/azuredatastudio/issues/22227#issuecomment-1461121833
```
[error] TypeError: Cannot read properties of undefined (reading 'providerId')
at Pi.findAccountByKey (vscode-file://vscode-app/c:/Users/MyUser/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:877:13833)
at vscode-file://vscode-app/c:/Users/MyUser/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:877:12510
at Array.findIndex (<anonymous>)
```
+Improves error handling by including error message when available.
=> Null & Error handling in Azure core

extensions/data-workspace/src/main.ts
This PR fixes #22278. Porting fix from main https://github.com/microsoft/azuredatastudio/commit/394d88445a11a73756ff7997dc0fdccd40ac3640
=> [Port] undo remove project change in data workspace (#22283)

extensions/mssql/config.json
Pickup more user management updates.
=> Update STS to 4.5.1.4

src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
Port request of #22269 for 1.42 release.
Tested and works the same as on main branch.
=> Port of newline fix for editdata

extensions/azurecore/src/account-provider/auths/azureAuth.ts
=> Use Preferred username over email as 'user' property

extensions/mssql/config.json
bring in the fix for https://github.com/microsoft/azuredatastudio/issues/22280
=> use latest STS version

extensions/sql-database-projects/src/controllers/projectController.ts, extensions/sql-database-projects/src/test/project.test.ts
This PR fixes this error when adding a file to a sql project, introduced by #22166. 
Also removing an unused import that was no longer needed after some tests were removed from a previous PR.
=> fix error when opening file after adding a file to sql project

resources/xlf/en/datavirtualization.xlf, resources/xlf/en/mssql.xlf, resources/xlf/en/sql-migration.xlf, resources/xlf/en/sql.xlf
=> [Loc] update to XLFS for 3-13-2023

src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts, src/sql/workbench/contrib/objectExplorer/common/serverGroup.contribution.ts, src/sql/workbench/contrib/objectExplorer/test/browser/serverTreeView.test.ts, src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts, src/sql/workbench/services/objectExplorer/test/browser/objectExplorerService.test.ts
=> Fixing new connections not expanding in object explorer in release

resources/xlf/en/sql.xlf
=> [Loc] SQL xlf update (Added node expansion labels)

extensions/sql-database-projects/src/common/constants.ts
- adding regions to make it more clear where a section ends
- removed some strings that aren't used anymore now that DacFx.Projects is doing the project parsing, like SSDT target paths, SDK version, collation
=> cleanup constants.ts

extensions/sql-database-projects/src/models/project.ts, extensions/sql-database-projects/src/models/tree/projectTreeItem.ts
Fix empty folders not showing up in the project tree and the "Properties" folder of legacy projects showing in the project tree
=> fix folders not showing in project tree

resources/localization/LCL/de/mssql.xlf.lcl, resources/localization/LCL/de/sql-migration.xlf.lcl, resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/mssql.xlf.lcl, resources/localization/LCL/es/sql-migration.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/mssql.xlf.lcl, resources/localization/LCL/ja/sql-migration.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/mssql.xlf.lcl, resources/localization/LCL/ko/sql-migration.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/pt-BR/mssql.xlf.lcl, resources/localization/LCL/pt-BR/sql-migration.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/mssql.xlf.lcl, resources/localization/LCL/ru/sql-migration.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/mssql.xlf.lcl, resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230315234519077 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230315234519077 to main

resources/localization/LCL/fr/mssql.xlf.lcl, resources/localization/LCL/fr/sql-migration.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/mssql.xlf.lcl, resources/localization/LCL/it/sql-migration.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/pt-BR/sql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/mssql.xlf.lcl, resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230316192338900 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230316192338900 to main

extensions/azurecore/package.json, extensions/azurecore/src/account-provider/auths/azureAuth.ts, extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts, extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts, extensions/azurecore/src/account-provider/azureAccountProvider.ts, extensions/azurecore/src/account-provider/azureAccountProviderService.ts, extensions/azurecore/src/account-provider/utils/fileDatabase.ts, extensions/azurecore/src/account-provider/utils/fileEncryptionHelper.ts, extensions/azurecore/src/account-provider/utils/msalCachePlugin.ts, extensions/azurecore/src/account-provider/utils/simpleTokenCache.ts, extensions/azurecore/src/account-provider/utils/simpleWebServer.ts, extensions/azurecore/src/azureDataGridProvider.ts, extensions/azurecore/src/azureResource/providers/resourceTreeDataProviderBase.ts, extensions/azurecore/src/azureResource/services/terminalService.ts, extensions/azurecore/src/constants.ts, extensions/azurecore/src/extension.ts, extensions/azurecore/src/localizedConstants.ts, extensions/azurecore/yarn.lock
Ports #22335 to release/1.42
- Needs STS version update from https://github.com/microsoft/sqltoolsservice/pull/1948
=> [Release 1.42] MSAL cache encryption + log improvements (#22335)

extensions/mssql/config.json
=> [Release 1.42] Bump STS

resources/localization/LCL/de/sql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/ja/sql.xlf.lcl, resources/localization/LCL/ko/sql.xlf.lcl, resources/localization/LCL/zh-Hans/sql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230317154311330 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230317154311330 to main

extensions/mssql/config.json
=> Bump tools service to bring in a fix for file/folder deletion in DacFx

resources/localization/LCL/it/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230318154256685 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230318154256685 to main

extensionsGallery-insider.json
Updates vsix file used by this release:
https://github.com/microsoft/azuredatastudio-mysql/releases/download/v0.2.7/azuredatastudio-mysql-0.2.7.vsix
=> Updating vsix file for v0.2.7 in insiders 

build/azure-pipelines/sql-product-build.yml, extensions/datavirtualization/coverConfig.json, extensions/datavirtualization/package.json, extensions/datavirtualization/src/test/index.ts, extensions/datavirtualization/yarn.lock, scripts/test-extensions-unit.bat, scripts/test-extensions-unit.js, scripts/test-extensions-unit.sh
Closes https://github.com/microsoft/azuredatastudio/issues/21603
=> Enable datavirtualization tests

src/sql/workbench/services/connection/browser/connectionManagementService.ts
=> Fixing connection group change for connections

extensions/sql-database-projects/src/test/buildHelper.test.ts
Updating baseline with new parameter
=> Fixing buildHelper test

extensions/mssql/config.json, extensions/mssql/src/objectManagement/ui/userDialog.ts
Enables adding Windows users without login.  This will need an STS bump with https://github.com/microsoft/sqltoolsservice/pull/1957/ prior to merge.
=> Support adding Windows users

CHANGELOG.md, README.md
=> Changes for release

extensions/dacpac/package.json
=> vbump dacpac extension

extensionsGallery-insider.json, extensionsGallery.json
Azure Postgres Migration Next Release 2.0.4
=> Azure Postgresql Migration Next Release 2.0.4

extensions/mssql/src/credentialstore/contracts.ts, extensions/mssql/src/credentialstore/sqlCredentialService.ts, extensions/mssql/src/features.ts, extensions/mssql/src/objectManagement/ui/objectManagementDialogBase.ts, extensions/mssql/src/util/dataCache.ts, extensions/mssql/tsconfig.json
Next up after this is full strict mode, but this should help a lot in the meantime to ensure type correctness.
=> Enable strict null in MSSQL extension

CHANGELOG.md, README.md
=> Changes for release (#22409)

extensionsGallery-insider.json, extensionsGallery.json
Please find the vsix binary [here](https://msdata.visualstudio.com/_apis/resources/Containers/174906294/drop?itemPath=drop%2Fazure-cosmosdb-ads-extension-0.3.0.vsix).
=> Release Cosmos DB extension to 0.3.0

extensions/mssql/config.json, extensions/mssql/src/objectManagement/ui/userDialog.ts
Continued work to add support for the various user types.
=> Enable contained and Windows user types

extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
This PR addresses https://github.com/microsoft/azuredatastudio/issues/22132
=> fix aria label for name input box in create project from db dialog

extensions/mssql/config.json
Bump STS to pickup a fix for https://github.com/microsoft/azuredatastudio/issues/22323.
=> Bump STS to pick-up Intellicode fix

extensionsGallery.json
Upgrades the MySQL extension in stable gallery.
=> upgraded mysql extension in stable gallery to 0.2.8

src/sql/workbench/contrib/dataExplorer/browser/media/connectionViewletPanel.css, src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts
=> Fixing async tree styling

extensions/sql-migration/src/api/utils.ts, extensions/sql-migration/src/dialog/tdeConfiguration/tdeMigrationDialog.ts, extensions/sql-migration/src/models/stateMachine.ts, extensions/sql-migration/src/service/contracts.ts, extensions/sql-migration/src/service/features.ts, extensions/sql-migration/src/telemetry.ts, extensions/sql-migration/src/wizard/skuRecommendationPage.ts
This PR 
* Fixes the tde Teleemtry view name.
* expand on the tde telemetry to add the user actions on the UX.
**Views/Actions**
TdeConfigurationDialog
*  TdeConfigurationUseADS
*  TdeConfigurationIgnoreADS
TdeMigrationDialog
* TdeMigrationSuccess
* TdeMigrationClientException
* TdeMigrationFailures
=> telemetry for tde user actions

src/vs/workbench/api/browser/mainThreadMessageService.ts
This PR fixes #22487
The gif below shows the difference between builtin and non-builtin extensions after the change.
=> only show "Manage Extension" action for non-builtin extensions

extensionsGallery-insider.json, extensionsGallery.json
This PR release v4.0.4 for Database Migration Assessment for Oracle extension in ADS.
=> Releasing v4.0.4 for Database Migration Assessment for Oracle extension in ADS.

src/sql/workbench/contrib/dataExplorer/browser/media/connectionViewletPanel.css, src/sql/workbench/services/objectExplorer/browser/iconRenderer.ts, src/sql/workbench/services/objectExplorer/browser/media/objectTypes/objecttypes.css
After: 
Before:
Element focused and selected styling:
After:
Before:
=> Fixing icon styling in OE tree

src/sql/workbench/contrib/query/browser/gridPanel.ts
=> Fix hover for query editor result cells

src/sql/platform/serialization/common/serializationService.ts, src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
This PR fixes #22441
I am using a MySQL test server to demonstrate the fix below.
Before:
After:
=> fix notebook serialization issue for non-mssql providers

src/sql/azdata.d.ts, src/sql/azdata.proposed.d.ts
Been a while so went through and picked out some that seem stable enough to promote and could be useful for extension developers to have easier access to.
=> Promote some proposed typings

resources/localization/LCL/de/azurecore.xlf.lcl, resources/localization/LCL/de/mssql.xlf.lcl, resources/localization/LCL/es/azurecore.xlf.lcl, resources/localization/LCL/es/mssql.xlf.lcl, resources/localization/LCL/es/sql.xlf.lcl, resources/localization/LCL/fr/azurecore.xlf.lcl, resources/localization/LCL/fr/mssql.xlf.lcl, resources/localization/LCL/fr/sql.xlf.lcl, resources/localization/LCL/it/azurecore.xlf.lcl, resources/localization/LCL/it/mssql.xlf.lcl, resources/localization/LCL/it/sql.xlf.lcl, resources/localization/LCL/ja/azurecore.xlf.lcl, resources/localization/LCL/ja/mssql.xlf.lcl, resources/localization/LCL/ko/azurecore.xlf.lcl, resources/localization/LCL/ko/mssql.xlf.lcl, resources/localization/LCL/pt-BR/azurecore.xlf.lcl, resources/localization/LCL/pt-BR/mssql.xlf.lcl, resources/localization/LCL/ru/azurecore.xlf.lcl, resources/localization/LCL/ru/mssql.xlf.lcl, resources/localization/LCL/ru/sql.xlf.lcl, resources/localization/LCL/zh-Hans/azurecore.xlf.lcl, resources/localization/LCL/zh-Hans/mssql.xlf.lcl, resources/localization/LCL/zh-Hant/azurecore.xlf.lcl, resources/localization/LCL/zh-Hant/mssql.xlf.lcl, resources/localization/LCL/zh-Hant/sql.xlf.lcl
LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230329154135186 to main with localized lcls
=> LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230329154135186 to main

extensions/mssql/config.json
=> update sts to bring in a couple fixes

extensionsGallery-insider.json
Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=195539&view=artifacts&pathAsName=false&type=publishedArtifacts
=> update sql projects to 0.23.0 in insiders

extensions/sql-database-projects/src/common/constants.ts, extensions/sql-database-projects/src/common/utils.ts, extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts, extensions/sql-database-projects/src/dialogs/addDatabaseReferenceQuickpick.ts, extensions/sql-database-projects/src/test/utils.test.ts
=> Surfacing better error messages about SQLCMD var names

extensions/sql-database-projects/README.md
Updating the commands in the readme to match the actual commands
=> cleanup sql projects readme

src/sql/workbench/api/browser/mainThreadConnectionManagement.ts
This PR addresses https://github.com/microsoft/azuredatastudio/issues/17037 (2b)
=> Fix selected server group when connecting from Azure tree view

extensions/azurecore/src/account-provider/auths/httpClient.ts, extensions/azurecore/src/azureResource/utils.ts, extensions/sql-migration/src/api/azure.ts
Update the rest of the axios calls to HttpClient
This PR fixes #22431
Note: marking as draft for now because I have not completed testing.
=> Update remaining Axios calls

extensions/sql-database-projects/package.json
vbump sql database projects for the April release!
=> vbump sql projects to 1.0.0

extensions/sql-database-projects/src/common/constants.ts, extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
=> Disabling revert button when no changes to SQLCMD vars at publish time

extensionsGallery-insider.json, extensionsGallery.json
Azure PostgreSQL Migration v2.0.5 Release
=>  Azure PostgreSQL Migration v2.0.5 Release

src/sql/workbench/services/objectExplorer/browser/asyncServerTree.ts
=> Fixing edited connections not working for root in Async Server Tree

package.json
=> version bump 1.44

src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts, src/sql/workbench/services/connection/browser/connectionDialogService.ts, src/sql/workbench/services/connection/browser/connectionManagementService.ts, src/sql/workbench/services/objectExplorer/browser/asyncServerTree.ts, src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts, src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts
=> Removing oe service changes from release 1.43

extensions/mssql/src/objectManagement/ui/objectManagementDialogBase.ts
This PR fixes #22448
Port the fix to release branch.
=> fix the empty schema issue (#22594)

extensionsGallery-insider.json
Companion PR for 
https://github.com/microsoft/azuredatastudio/pull/22600/files
=> Update to insiders gallery for release/extensions for April

extensionsGallery-insider.json, extensionsGallery.json
Langpacks to merge from are found here:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=196071&view=artifacts&pathAsName=false&type=publishedArtifacts
=> Update to langpack extensions gallery for April Release

extensions/mssql/config.json
Bump STS for https://github.com/microsoft/azuredatastudio/issues/22563
=> Bump STS to pickup contained user bug fix

extensions/mssql/config.json
Fixes for https://github.com/microsoft/azuredatastudio/issues/22426 and https://github.com/microsoft/azuredatastudio/issues/22447.
=> Bump STS for additional user management fixes

extensions/sql-database-projects/src/controllers/projectController.ts, extensions/sql-database-projects/src/models/project.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/22590
=> Fix issue where errors during project update were swallowed

extensions/sql-database-projects/src/controllers/projectController.ts, extensions/sql-database-projects/src/models/project.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/22590
=> Port fix for issue where errors during project conversion would be swallowed (#22612)

extensions/mssql/config.json
Update STS to fix https://github.com/microsoft/azuredatastudio/issues/22607
=> Bump STS to 4.6.1.3 to pickup NoConnect user bug fix

extensions/azurecore/src/account-provider/auths/httpClient.ts, extensions/azurecore/src/azureResource/utils.ts, extensions/sql-migration/src/api/azure.ts
This reverts commit ccd5775093ae31e05734aa99ae7ad51db65fa5ca.
=> Revert "Update remaining Axios calls (#22525)"

extensions/mssql/src/constants.ts, extensions/mssql/src/sqlToolsServer.ts
…o monitor updates
Adding telemetry config to client config so they can be sent to STS to monitor the config updates.
=> Adding telemetry config to client config to send to STS

extensionsGallery.json
Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=196333&view=artifacts&pathAsName=false&type=publishedArtifacts
=> Update version of projects extension to 1.0.0 in RC branch

extensionsGallery-insider.json
Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=196338&view=artifacts&pathAsName=false&type=publishedArtifacts
=> Update sql projects to 1.0.0 in insiders and remove preview flag

extensions/mssql/config.json
=> Updating STS to get dataverse read only database fixes 

extensions/sql-database-projects/package.json, extensions/sql-database-projects/src/models/project.ts, extensions/sql-database-projects/src/sqldbproj.d.ts
=> Fix for issue where bulk-adding scripts could perform a rescan after each script

extensionsGallery-insider.json
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=196757&view=artifacts&pathAsName=false&type=publishedArtifacts
=> Updating SQL Database Projects to 1.0.1 in insider gallery

extensionsGallery.json
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=196757&view=artifacts&pathAsName=false&type=publishedArtifacts
=> Updating SQL Database Projects to 1.0.1 in RC gallery

CHANGELOG.md, README.md
=> Update changelog for 1.43 and update readme with evergreen links

extensions/azurecore/src/account-provider/providerSettings.ts
Adding MS Graph endpoint for US Gov, we are also missing the OSSRDBMS endpoint for China & the ADO endpoint for Us Gov/China so will be adding those before merging this PR.
=> Add ms graph endpoint for us gov

extensionsGallery-insider.json
This PR updates the insiders extension gallery to the latest version of the SQL Migration extension.
Link to `Azure Data Studio - Extensions` pipeline run off main containing vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=196654&view=results
=> [SQL Migration] Release v1.4.3 to Insiders

extensions/sql-database-projects/package.json
=> vbump sql database projects to 1.1.0

extensionsGallery-insider.json, extensionsGallery.json
Releasing new extension - Azure Cosmos DB Migration for MongoDB
link to - [binary](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvODk1NDAyNTEvYXJ0aWZhY3ROYW1lL2Ryb3BfYnVpbGRfbWFpbg2/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-1.0.0.vsix)
=> Releasing new extension - Mongo Migration to CosmosDB

build/azure-pipelines/common/publish.js, build/azure-pipelines/common/publish.ts
Now that I finally figured out a way to test this.. validated locally and it should work!
=> Fix blob file upload

src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts, src/sql/workbench/contrib/objectExplorer/common/serverGroup.contribution.ts, src/sql/workbench/contrib/objectExplorer/test/browser/connectionTreeActions.test.ts, src/sql/workbench/contrib/objectExplorer/test/browser/serverTreeView.test.ts, src/sql/workbench/contrib/scripting/test/browser/scriptingActions.test.ts
=> Adding restart ads notification when async server tree is toggled 

src/sql/workbench/contrib/query/common/resultsGrid.contribution.ts
=> adjust the default max column width

extensionsGallery.json
Changed dsct version to 0.4.0 and updated all the links to point towards the new vsix and resources.
Updated the name and description according to the requirements from PM.
This push follows the update of dsct in insider.
=> Changed dsct extension version to 0.4.0 in marketplace and changed name, description.

src/sql/platform/theme/common/colorRegistry.ts
=> Add more description to queryEditor.nullBackground color setting

src/sql/workbench/browser/modal/modal.ts
=> auto focus message area

extensions/mssql/config.json
Bump STS to pick-up User AAD support.
=> Bump STS to 4.7.0.11

src/sql/azdata.d.ts, src/sql/azdata.proposed.d.ts
Linting issue fix + moving type I missed when I was promoting stuff to stable (this was caught by the Definitely Typed PR so is fixed there already)
=> Fix typings

src/sql/workbench/contrib/dashboard/browser/core/actions.ts, src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts
=> add tooltip for dashboard learn more button

src/sql/platform/connection/common/connectionProfileGroup.ts, src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
Moving connection group child connection modification logic to connection server group class.
=> Cleaning up some code in Async Server Tree.

extensions/mssql/config.json
Picks up a fix for the login portion of https://github.com/microsoft/azuredatastudio/issues/22736
=> Bump STS to 4.7.0.12 for Login script fix

extensions/sql-database-projects/src/models/IDatabaseReferenceSettings.ts, extensions/sql-database-projects/src/models/project.ts, extensions/sql-database-projects/src/models/projectEntry.ts, extensions/sql-database-projects/src/test/baselines/newSdkStyleSqlProjectSdkNodeBaseline.xml, extensions/sql-database-projects/src/test/project.test.ts
This updates project.ts and related files to handle reading and adding nukpg database references. Next PR will add nukpg database reference in the Add Database Reference dialog!
=> Handle nukpg database references in project.ts

extensions/sql-database-projects/src/models/projectEntry.ts
Making an abstract class `UserDatabaseReferenceProjectEntry` that the database reference classes can inherit from so that all the sqlcmd variables don't need to be copied in each of those classes.
=> make UserDatabaseReferenceProjectEntry class

extensions/azurecore/src/account-provider/auths/azureAuth.ts, extensions/azurecore/src/account-provider/auths/httpClient.ts, extensions/azurecore/src/account-provider/auths/networkUtils.ts, extensions/azurecore/src/azureResource/utils.ts, extensions/sql-migration/src/api/azure.ts
This PR addresses concerns regarding breaking changes from PR https://github.com/microsoft/azuredatastudio/pull/22525
=> Rename 'body' to 'data' to prevent breaking change

build/azure-pipelines/linux/sql-product-build-linux.yml
The DEB build step is disabled.
=> Reenable DEB build

build/azure-pipelines/linux/sql-product-build-linux.yml, build/azure-pipelines/linux/sql-publish.ps1
The DEB build needs to be investigated.  Disabling in the meantime to get the insider build out.
=> Disable DEB publish step

extensions/mssql/config.json
=> Bumping STS to 4.7.0.15

extensions/data-workspace/src/common/constants.ts, extensions/data-workspace/src/common/utils.ts, extensions/data-workspace/src/common/workspaceTreeDataProvider.ts
=> Improving error message when projects fail to load

package.json
This PR updates the distro commit hash.
=> Update distro commit hash

extensions/mssql/config.json, extensions/mssql/src/contracts.ts, extensions/mssql/src/mssql.d.ts, extensions/mssql/src/sqlProjects/sqlProjectsService.ts, extensions/types/vscode-mssql.d.ts
=> Bumping SqlToolsService to 4.7.0.17

extensions/azurecore/src/account-provider/utils/msalCachePlugin.ts, src/sql/platform/connection/common/constants.ts, src/sql/platform/connection/common/utils.ts, src/sql/workbench/services/connection/browser/connectionManagementService.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/22824 and an issue with cache update
=> Prevent reconnects for mssql provider

extensionsGallery-insider.json
Releasing a hotfix for DSCT and updating the version to 0.4.1
=> Updating DSCT version to 0.4.1

extensionsGallery.json
This PR updates the wolrdwide extension gallery to the latest version of the SQL Migration extension. This version was already released to insiders in https://github.com/microsoft/azuredatastudio/pull/22788 and the same vsix can be used.
=> [SQL Migration] Release v1.4.4 to Worldwide

extensionsGallery-insider.json
This PR upgrades the MySQL Extension in insider gallery.
VSIX file: https://github.com/microsoft/azuredatastudio-mysql/releases/download/v0.2.9/azuredatastudio-mysql-0.2.9.vsix
=> upgrade mysql extension in insider

build/azure-pipelines/updateGalleries.yml
Task started failing with HTTP error 400, updating to fix that
=> Update AzureFileCopy task

extensionsGallery.json
Hotfix release for DSCT to marketplace.
Insider release has been done and tested.
=> Change DSCT version to 0.4.1

extensions/mssql/config.json
Picks up the latest User management bug fixes and perf optimizations.
=> Bump STS to pickup latest User management updates

src/vs/workbench/services/configuration/test/browser/configurationService.test.ts, test/unit/node/index.js
Reenables two tests that were previously marked to be skipped. Remaining tests that need to be enabled are being tracked here: https://github.com/microsoft/azuredatastudio/issues/22858
=> Enables previously skipped tests

samples/sqlservices/gulpfile.js, samples/sqlservices/package.json, samples/sqlservices/src/featureProviders/objectExplorerProvider.ts, samples/sqlservices/tasks/buildtasks.js, samples/sqlservices/yarn.lock
1. the instructions in the README.md doesn't work anymore, the gulpfile is not present
2. add copytypings task so that the compile would work
3. fix compilation errors
=> fix the sqlservices sample extension

src/sql/workbench/contrib/query/browser/query.contribution.ts
=> update shortcut keys for parse query

extensions/azurecore/package.nls.json, extensions/azurecore/src/account-provider/auths/azureAuth.ts, extensions/azurecore/src/account-provider/azureAccountProvider.ts, extensions/azurecore/src/azureResource/services/subscriptionService.ts, extensions/azurecore/src/azureResource/tree/accountTreeNode.ts, extensions/azurecore/src/azureResource/tree/flatAccountTreeNode.ts, extensions/azurecore/src/azureResource/utils.ts, extensions/azurecore/src/constants.ts, extensions/azurecore/src/utils/TenantIgnoredError.ts
=> Update error for ignored tenants

extensions/azurecore/src/account-provider/auths/azureAuth.ts, extensions/azurecore/src/account-provider/azureAccountProvider.ts
Following up on remaining error handling + fixup prompt
=> Touch up MSAL errors

extensionsGallery-insider.json, extensionsGallery.json
Updated SQL 4 CDS extension details to v7.2.1
=> SQL 4 CDS Extension update

resources/xlf/en/azurecore.xlf, resources/xlf/en/mssql.xlf, resources/xlf/en/sql-database-projects.xlf, resources/xlf/en/sql-migration.xlf, resources/xlf/en/sql.xlf
=> [Loc] update to XLF on 5-1-2023 prior to code complete

extensions/mssql/src/errorDiagnostics/errorDiagnosticsConstants.ts, extensions/mssql/src/errorDiagnostics/errorDiagnosticsProvider.ts
=> Add new password reset code 

extensionsGallery-insider.json, extensionsGallery.json
Link to VSIX:
https://microsoft.github.io/SandDance/dist/azdata/v4/azdata-sanddance-4.1.1.vsix
Includes updated README with license for #22885
=> Update SandDance extension 4.1.1

extensionsGallery-insider.json, extensionsGallery.json
Publishing versions with updated README content
=> Update whoisactive and serverreports extensions

extensions/sql-database-projects/src/common/telemetry.ts, extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
Add telemetry for the save publish profile button that will be new in the May release
=> add telemetry for saving publish profiles

resources/xlf/en/sql-database-projects.xlf, resources/xlf/en/sql-migration.xlf
=> [Loc] Localization update for 5-2-2023 (Second to last before code complete)

extensions/sql-migration/config.json, extensions/sql-migration/src/models/loginMigrationModel.ts, extensions/sql-migration/src/telemetry.ts, extensions/sql-migration/src/wizard/loginMigrationStatusPage.ts, extensions/sql-migration/src/wizard/loginMigrationTargetSelectionPage.ts, extensions/sql-migration/src/wizard/loginSelectorPage.ts
- Bucketized errors to track top errors
- Created separate login migration specific error to improve monitoring
FYI for @Charles-Gagnon: No PII will be exposed in the errorCodeString. We log the type of error with no user context. I also added a new errorMessage field.
=> [SQL-Migration] Improve log migrations telemetry
