- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceQuickpick.ts
This PR fixes #19062. This validation was previously added in the dialog in ADS in https://github.com/microsoft/azuredatastudio/pull/14877, but wasn't added in the vscode quickpick.
Adds a placeholder in the browse step mentioning that the dacpac reference needs to be on the same drive as the project:
If the user selects a dacpac on a different drive, then an error notification shows and the browse quickpick shows again:
> Add validation for checking for dacpac being on the same drive

- src/sql/workbench/contrib/executionPlan/browser/executionPlanView.ts
Currently the default save location for a SQL execution plan (when not in a workspace) is the filesystem root. This PR changes the default save location so instead of `/` like it is now:
It is instead the users home directory:
This PR fixes #21460
> Change execution plan default save location when not in a workspace

- src/sql/base/browser/ui/table/formatters.ts
this PR fixes #10078
1. apply the line breaking and maximum length logic used in text cells to link cells
2. display line break characters.
before:
after:
> handle the line breaks in link cells

- extensions/azurecore/src/account-provider/azureAccountProvider.ts
- src/sql/workbench/services/connection/browser/connectionWidget.ts
Fixes a use-case for issue #21371 when user account has no tenant dropdown, i.e. only 1 tenant.
Azure core doesn't receive tenant info in that case, so the owning tenant should be set to the default tenant in that case.
> Handle default tenant to be set when no dropdown exists

- extensions/mssql/package.json
- src/sql/platform/capabilities/common/capabilitiesService.ts
- src/sql/workbench/services/executionPlan/common/executionPlanService.ts
This PR fixes #21451
Problem: 
The following error was logged when trying to open a JSON cell: `No valid execution plan handler is registered`
Root Cause:
When the provider is not an execution plan provider, an error will be thrown when checking whether the string is execution plan.
Fix:
1. Add `IsExecutionPlanProvider` to the provider metadata so that we know it without needing to activate the extension
2. Update the service so that it returns false if the provider is not an execution plan provider
3. refactor the execution plan service
With the fix:
MySQL - Json
MSSQL - Execution Plan
MSSQL - JSON
> fix issue caused by execution plan provider

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/providerSettings.ts
This PR fixes #21536
Resource endpoints are appended to scope when request is made to MSAL, therefore they need to end with slash (`/`)
This change is backwards compatible with ADAL.
> Fix resource endpoints to end with slash

- src/sql/platform/connection/common/connectionManagement.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
- src/sql/workbench/services/objectExplorer/browser/serverTreeActionProvider.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/21363
Call to fetch access token can be safely skipped when opening context menu, as it will eventually be fetched when any action is taken on server tree node or its expanded.
> Skip fetching access token when opening context menu in OE

- src/sql/workbench/contrib/executionPlan/browser/executionPlanView.ts
This PR fixes #18385
Previously when you clicked on the "Save Plan File" button. The save file dialog would appear recommending "plan.sqlplan" as the file name, even if there was already a file with that same name in the save folder location. This PR appends a number to the default file name, so any new files being saved with the default name will appear as "plan1.sqlplan", "plan2.sqlplan", and so on.
> Save sql plan no longer uses the exact same name as the default

- src/sql/workbench/contrib/query/browser/actions.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR fixes #2119
The PR adds functionality to copy all column headers as a comma separated list.
> Adds functionality to copy table column headers

- extensions/azurecore/src/azureResource/commands.ts
- src/sql/workbench/services/accountManagement/browser/accountDialog.ts
- src/sql/workbench/services/accountManagement/browser/accountManagementService.ts
This PR brings first set of changes to append accounts from alternate authentication library if absent from current library account list and cache. The accounts are added and marked as 'stale' so their credentials can be refreshed by user.
**Current behavior:**
When users switch authentication library from ADAL to MSAL, accounts are not transitioned and align with only 1 library. Users need to add accounts again after switching authentication library.
**New behavior (with PR changes):**
User accounts will be combined from both libraries such that when users transition from one library to another, and reload ADS, their Azure account list stays the same.
**Validations:**
- Validated accounts for both toggles: ADAL > MSAL and MSAL > ADAL
- Accounts are merged and marked stale if missing from …
> Azure core | Include alternate library accounts if found

- src/sql/platform/query/common/query.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
This PR fixes #21538
The PR adds the ability to show and hide the actions bar that appears in the results pane.
The space between tables when multiple queries are executed are adjusted accordingly when the action bar isn't present:
Action bar hidden:
Action bar visible:
> Add option to show and hide the action bar in the query results view

- extensions/mssql/package.json
- extensions/mssql/package.nls.json
- extensions/mssql/src/sqlToolsServer.ts
This will let us easily turn on debug logging for the client side (we already have logging in STS for messages received/sent). Will help with issues such as https://github.com/microsoft/azuredatastudio/issues/21578 to ensure that messages are being received (and examine their contents if needed).
This will be logged to the "SQL Tools Service" output channel. 
Example messages : 
Example verbose :
> Add config for enabling STS communication logging

- src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts
- src/sql/workbench/browser/modelComponents/table.component.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/21491
There were a couple of rowSelectionEvents fired whenever a checkbox state was changed in slickgrid.
First there was rowSelectionEvent fired for row whose value was just changed by the RowSelectionModel plugin and then there was a second rowSelectionEvent fired for all the checked rows by CheckboxSelectColumn plugin.
This PR fixes that issue. Now, if a checkbox column is used for row selection, the duplicate event is not fired anymore.
Previously, the table data was not updated when the value of the checkbox was updated. This PR also fixes that issue. Now, the value of the table is always updated before the checkbox action event is fired so it truly reflects what is seen in the UI.
This change should be completely back …
> Adding better handling for checkbox column based row selection

- extensions/mssql/config.json
This PR bumps the version of sqltoolsservice in mssql from 4.4.1.1 to 4.4.1.2, which includes the latest changes from SQL Migration. Discussed internally in ADS Shiproom.
See https://github.com/microsoft/sqltoolsservice/pull/1814 and https://github.com/microsoft/azuredatastudio/issues/21629 for more details.
> [Port request] vbump sqltoolsservice in release/1.41

- src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
- src/sql/workbench/contrib/query/browser/actions.ts
- src/sql/workbench/services/query/common/gridDataProvider.ts
- src/sql/workbench/services/query/common/queryRunner.ts
This PR fixes #21571
This PR fixes #21570
This port request adds functionality to copy column headers for selected columns.
> [Port Request] Fix Column Header Copy Issue

- build/lib/extensions.js
Fixes https://github.com/microsoft/azuredatastudio/issues/21634
The BDC removal commit that was reverted updated build/lib/extensions.ts but didn't rebuild the build folder - which means the checked in js was never updated in that commit.
Recently a separate PR then also made changes to that file and rebuilt it - which meant that the js file then finally had the bdc extension removed. 
https://github.com/microsoft/azuredatastudio/pull/21594/files#diff-66f0c65d9f46c3d32db2a94bd8b71c9f14fa0a0b6833a9daa018895f5436ef0dL284
But with the revert that part was missed, so it never rebuilt the native node modules the extension requires.
> [Port] Add back missing big-data-cluster extension rebuild

- extensions/big-data-cluster/package.json
VS Code changed this at some point - it's now `debug-disconnect` (https://code.visualstudio.com/api/references/icons-in-labels)
Switching to just use the plug icon instead to better match the "connect" action being done here.
> [RC1] Fix missing BDC connect icon

- .github/workflows/ci.yml
- scripts/validateGalleries.js
Skip checking insiders gallery since otherwise we'll have to keep updating whenever insiders updates are made or the checks will fail (since rc1 branch will have outdated values).
When we eventually merge the rc1 branch into release/extensions then it'll check both and verify everything is matching between the two.
> Don't check insiders gallery on RC1 branch

- src/sql/workbench/contrib/query/browser/gridPanel.ts
When the showActionBar setting was added for the query results grid, some DOM operations got reordered, causing the actionbar to always be built after the results table. When building a horizontal actionbar, it should instead come before the results table. This PR is a partial reversion of the gridPanel changes here: https://github.com/microsoft/azuredatastudio/commit/7683259097f29d7316d81057fd266c37d5ccb99a#diff-d3d6744fd0e03a75fd04780ac9f6a90520bb80c6678668f3df17566bab3e5991L486
> Build vertical actionbar before results table so that it shows above the table.

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- yarn.lock
Previously, user was not able to enter the scan mode as the graph was consuming the event. I have fixed azdata graph to let the user enter scan mode.
Issue #20777
> Fixing nvda scan mode on execution plans 

- extensions/mssql/package.json
- src/sql/platform/capabilities/common/capabilitiesService.ts
- src/sql/workbench/contrib/connection/common/connectionProviderExtension.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
This PR fixes #21587.
MSSQL provider was not registering 'azureResource' in it's 'connectionProvider' configuration, hence it lead to warning when 'provider.properties.azureResource' was not found.
> Add Azure Resource 'Sql' to MSSQL extension.

- extensionsGallery-insider.json
Updating these extensions for the January ADS release in insiders:
- dacpac
- schema compare
- sql database projects
Build with vsixs: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=186852&view=artifacts&pathAsName=false&type=publishedArtifacts
> Update dacpac, schema compare and sql database projects extensions for January release (Insiders)

- extensionsGallery-insider.json
- extensionsGallery.json
Updating these extensions for the January ADS release in RC gallery:
- dacpac
- schema compare
- sql database projects
Build with vsixs: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=186852&view=artifacts&pathAsName=false&type=publishedArtifacts
> Update dacpac, schema compare, and sql database projects extensions for January release (RC gallery)

- extensions/mssql/config.json
This PR bumps the version of sqltoolsservice in mssql from 4.4.1.3 to 4.4.1.4, which includes the latest changes from SQL Migration. Discussed internally in ADS Shiproom.
See https://github.com/microsoft/sqltoolsservice/pull/1819 and https://github.com/microsoft/azuredatastudio/issues/21679 for more details.
> [Port request] vbump sqltoolsservice to 4.4.1.4 in release/1.41

- extensions/arc/package.json
VS Code renamed this to `debug-disconnect` at some point. Changing to just use the plug icon since that better aligns with the "connect" action being taken. 
Before : 
After :
> Fix connect icon for Arc extension

- extensions/mssql/src/contracts.ts
- extensions/mssql/src/errorDiagnostics/errorDiagnosticsConstants.ts
- extensions/mssql/src/errorDiagnostics/errorDiagnosticsService.ts
- src/sql/azdata.proposed.d.ts
- src/sql/platform/connection/common/connectionManagement.ts
- src/sql/workbench/api/browser/mainThreadConnectionManagement.ts
- src/sql/workbench/api/browser/mainThreadErrorDiagnostics.ts
- src/sql/workbench/api/common/extHostConnectionManagement.ts
- src/sql/workbench/api/common/extHostErrorDiagnostics.ts
- src/sql/workbench/api/common/sqlExtHost.api.impl.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
- src/sql/workbench/services/connection/browser/passwordChangeDialog.ts
- src/sql/workbench/services/connection/test/browser/connectionManagementService.test.ts
- src/sql/workbench/services/connection/test/common/testErrorDiagnosticsService.ts
- src/sql/workbench/services/diagnostics/browser/errorDiagnosticsService.ts
- src/sql/workbench/services/diagnostics/common/errorDiagnosticsService.ts
This PR now makes it so that when an error code is checked on the provider side, the provider will first have to get the profile that was causing the error via an API call (temporarily stored until error handling is done, and it can be used for all kinds of errors not just password reset, and CMS won't know anything about error codes), then after converting it back and forth from interfaces.IConnectionProfile to azdata.connection.ConnectionProfile, it will then call the existing change password dialog via another API call. 
Additionally, the params for the password change dialog are removed as it's only the default connection type that is passed in this scenario. 
Attempts to include the connection profile and params in one class as part of the error code handling (as an 'any' type) …
> Added provider-based handling for change password/generic error handling.

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
This PR adds an info box to step 5 of the wizard for VM migrations which informs the user to ensure that provided database names don't already exist on the target VM, which will hopefully reduce these types of failures. This is a temporary measure until a proper validation experience is supported.
> [SQL Migration] Add info boxes for VM existing database names  

- src/vs/workbench/contrib/webview/browser/resourceLoading.ts
Port...
Fix MSCR 74267
Fix https://github.com/microsoft/vscode-internalbacklog/issues/3140
Remove extra indexOf check
This could cause failures for files such as `img..png`
Co-authored-by: Matt Bierner <matb@microsoft.com>
> Normalize resources when checking valid roots (#163327) (#21700)

- extensionsGallery-insider.json
This PR updates the Insiders extension gallery to the latest release candidate version of the SQL Migration extension. It also bumps the dependent version of ADS (Microsoft.AzDataEngine) to 1.41 to match what is defined in our [package.json](https://github.com/microsoft/azuredatastudio/blob/main/extensions/sql-migration/package.json#L13).
Link to Azure Data Studio - Extensions pipeline run containing vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=187242&view=results
> [SQL-Migration] Release 1.2.1 to insiders 

- extensions/sql-migration/package.json
- extensions/sql-migration/src/dashboard/dashboardTab.ts
- extensions/sql-migration/src/dashboard/migrationsListTab.ts
This PR bumps sql-migration version to 1.2.2 in order to release to insider's gallery. This also disables the LoginMigration button as we do not want to release it to public yet.
> Bump sql-migration version to 1.2.2

- extensionsGallery-insider.json
- extensionsGallery.json
Updating arc and azcli extensionGalleries to 1.8.0.
PR containing version bump: https://github.com/microsoft/azuredatastudio/pull/21725
VSIX files to be used are drop/extensions/arc-1.8.0.vsix and drop/extensions/azcli-1.8.0.vsix from this link: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=187482&view=artifacts&pathAsName=false&type=publishedArtifacts
> Update extensionsGallery for Arc and Azcli 1.8.0

- extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
This PR fixes #21210.
Currently while creating a list of servers in the schema compare dialog (for database comparison), the code will either pick the newly added connection or the one with which schema compare extension was started from, to set as the selected server- whichever came later. It should rather follow the hierarchy of picking the newly added connection first, if it doesn't exist then pick the one where SC context was launched from. This PR made the change to select newly added connection first; if not, then select contextual server from the SC was launched.
Before the changes:
After the changes:
Tested other scenarios as well (adding/selecting other servers in the server list).
> Set current connection as the selected connection in schema compare dialog

- extensionsGallery.json
This PR updates the worldwide extension gallery to the latest version of the SQL Migration extension. It also bumps the dependent version of ADS to 1.41, matching the extension definition.
Link to `Azure Data Studio - Extensions` pipeline run containing vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=187362&view=results
~~(This version has not gone to insiders (and probably won't) because it's basically identical to the 1.2.1 version currently in insiders, with a one line change to disable a preview feature that was intended only for insiders and not public consumption. We will do another follow up insiders release soon to add more stuff anyways)~~
> [SQL Migration] Release v1.2.2 to worldwide

- src/sql/base/browser/ui/selectBox/selectBox.ts
- src/sql/workbench/services/connection/browser/connectionWidget.ts
This PR fixes #21643 and tenant selection issues as well.
I had been intermittently facing this issue and was able to finally debug and root cause it. The issue had been present due to selectBox defaulting to 'first' item by default in `fillInAzureAccountOptions()` which when called without any data always ends up selecting first account in the list. This fires event that populates tenant and we start getting console errors as under:
_(captured in v1.41.0)_
Which should not be the case as the subscription ID "72f988bf-***" is not applicable to live account. This PR makes sure the correct account is selected after this call completes only in `fillInConnectionInputs(connectionInfo)` when connection Info is available.
Also removed unwanted `_azureTenantId` assignments that were causing …
> Fix account and tenant selection behavior

- extensions/dacpac/src/wizard/api/models.ts
- extensions/dacpac/src/wizard/dataTierApplicationWizard.ts
This PR fixes #21626. The error was because `potentialDataLoss` doesn't get set for deploy to new db, only for deploy to existing db.
> fix undefined error in dacpac extension when sending telemetry

- src/sql/workbench/services/connection/browser/connectionWidget.ts
The PR fixes an edge case for #21749, when selecting 'Azure MFA' auth mode over another mode on a new connection dialog, and an account is selected that contains tenants, tenant dropdown doesn't show up.
Switching accounts, selecting a saved connection with Azure MFA or opening connection dialog again brings the tenant dropdown again.
> Show tenant dropdown when selecting 'AzureMFA' the first time

- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/api/dataModels/azure/networkInterfaceModel.ts
- extensions/sql-migration/src/api/sqlUtils.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/loginMigrationTargetSelectionPage.ts
This PR adds support for migrating logins to SQL VM. Adding support for 2 scenarios supported here: VMs with private IP and public IP.
- I've successfuly tested the private IP code path end to end.
- I haven't been able to test public IP path end to end due to network configuration issues inherited from MSFT subs (tried baston + ER routes), however i have stepped through debugger to confirm the values sent to connection string are as expected. The public IP address is extremely rare for customers and the only way to test is with a non msft subscription. After syncing with Sreraman, the approach I took and testing I did for this scenario should be sufficient.
> [SQL-Migration] Enable login migrations to SQL VM

- extensions/sql-migration/package.json
This PR bumps sql-migration version to 1.2.4 in order to release to insider's gallery. This version now supports login migration for SQL VM as a target.
> Bump sql migration version to 1.2.4

- extensions/mssql/src/errorDiagnostics/errorDiagnosticsProvider.ts
- src/sql/workbench/services/connection/browser/media/passwordDialog.css
- src/sql/workbench/services/connection/browser/passwordChangeDialog.ts
Hi @smartguest 
Adding some improvements with logging, styling for the change password dialog.
Please take a look.
Thanks :)
Attaching screenshot of updated dialog for reference:
_Note: undefined profile properties seems related to RPC conversion, which Alex is working on._
> Improvements for Change password dialog + logs added

- extensionsGallery-insider.json
This PR updates the Insiders extension gallery to the latest release candidate version of the SQL Migration extension. This change includes login migrations support for SQL VM.
Link to Azure Data Studio - Extensions pipeline run containing vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=188220&view=results
> Bump sql-migration insiders to 1.2.4

- extensions/sql-migration/package.json
- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/models/stateMachine.ts
This PR removes the `encryptConnection` property from the IR validation request body, which was breaking certain customer migration workflows (e.g. see https://github.com/microsoft/azuredatastudio/issues/21769) when it was being hardcoded to `true`. A longer term fix is in the works to properly respect the user's provided values for `encryptConnection` as well as `trustServerCertificate`, which requires backend RP changes.
This PR also vbumps the extension, as discussed internally, we are looking to release this ASAP to unblock stuck customers who cannot proceed past IR validation (along with an ongoing RP hotfix deployment).
> [SQL Migration][Hotfix] Remove parameter from IR validation

- src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts
The current code leads to the redrawing of the entire OE every time a new session is initiated, resulting in the loss of the previously focused connection in the tree. The code attempted to refocus the element using `tree. Select()`, but this function caused the creation of two sessions if the session was not already created. To resolve this, the code has been changed to use `tree.Focus()` instead, which prevents the creation of two sessions and maintains the focus on the desired element.
However, there are still frequent tree redraws which is not ideal, so a more comprehensive solution may be necessary to prevent UI-related errors in the future.
> Replacing select with focus to prevent second create session

- extensions/azurecore/package.disabled.json
- extensions/azurecore/package.json
- extensions/azurecore/src/account-provider/azureAccountProviderService.ts
- extensions/azurecore/src/account-provider/providerSettings.ts
The only clouds listed [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud) are: 
- Azure China
- Azure US Government
- Azure Public Cloud
It seems like the Germany cloud was decommissioned, so removing that one along with the US National Cloud (which seems to also have been removed).
Additionally, in an effort to consolidate the Token Cache for MSAL to share easily with STS, changed to a hardcoded token cache key.
> Remove Germany and US National clouds

- extensions/sql-migration/package.json
- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/api/sqlUtils.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/loginMigrationTargetSelectionPage.ts
- extensions/sql-migration/src/wizard/loginSelectorPage.ts
This PR fixes a regression for migration login for MI instances that was introduced in https://github.com/microsoft/azuredatastudio/pull/21776/files#diff-93c1a62583fa32d99f775b71ad27922cf31f660d10717ecc6966784306de1b6f. 
After that change, support for MI would fail as MI server types were going into the Sql VM path in sqlutils because the underlying logic for isSqlServerVM() was returning wrong results. 
The new approach uses the targetType set in StateMachine to extract the correct serverName for connection string based on the targetType.
Testing:
- Tested SQL VM login migration end to end
- Tested SQL MI login migration end to end
This change also bumps the version to 1.3.0
> Fix connecting to MI login bug

- extensionsGallery-insider.json
- extensionsGallery.json
Added listing for SQL 4 CDS extension to let users query data in Microsoft Dataverse/Dynamics 365 instances from Azure Data Studio.
I've included both a direct link to the vsix file and to the GitHub release page for the downloads, please let me know if I need to remove one of them.
More information about the extension is available at https://markcarrington.dev/2023/01/31/sql-4-cds-v7-1-released/#azure_data_studio
> Initial SQL 4 CDS extension listing

- src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts
This PR fixes #21843 
before:
after:
> fix issue with checkbox column in model view table component

- src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/codeCell.component.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
- src/sql/workbench/contrib/notebook/browser/notebookEditor.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookEditor.test.ts
- src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts
- src/sql/workbench/services/notebook/browser/models/cell.ts
- src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR
- renames onCellModechanged to onCellEditModeChanged
- removes some duplicate detectChanges and toggleEditMode calls
> Minor improvements in notebook edit mode handling

- extensions/sql-migration/src/api/sqlUtils.ts
Issue:
Fixes an error that occurs when there are databases with very large sizes, which can't fit in the integer value.
Action
Updated the query to bigint and validated the query with a client experiencing the issue.
> databases query updated to prevent error when casting large numbers.

- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
`profileUsed` was getting initialized to false here https://github.com/microsoft/azuredatastudio/blob/985a30d7730b00812eadb905ae50708c9deb791f/extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts#L59
but never got set to true when a publish profile was loaded in ADS, so it made it seem like no one was using publish profiles in ADS. The publish quickpick for vscode was correctly `profileUsed`.
> Fix publish profile telemetry for ADS

- extensionsGallery.json
This PR updates the stable extension gallery to the latest release candidate version of the SQL Migration extension. This change includes bug fixes for login migrations, removing parameter that was blocking customers in in validate IR, and improved error messages for collation violations.
Link to Azure Data Studio - Extensions pipeline run containing vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=188884&view=results
Note: We are releasing this version to insiders on 02/03 and to stable on 02/06. I'm creating a draft PR just to have it ready, but we will merge this PR on 2/6.
> [SQL-Migration] Bump sql-migration version to 1.3.0

- extensions/sql-migration/src/api/sqlUtils.ts
Adding recommendations from SQL team related to the query. Adding the SQL tools team PR as reference. https://github.com/microsoft/sqltoolsservice/pull/1845
Root cause for the issue was related to how the SUM function works. Because it keeps the type for the value it receives on the input, it will overflow when passing the data type size.
> Adding SQL tools team recommendations

- src/sql/workbench/services/accountManagement/browser/accountDialog.ts
- src/sql/workbench/services/accountManagement/browser/accountManagementService.ts
- src/vs/workbench/common/views.ts
Fixes a few bugs in the Account Dialog relating to having multiple providers:
Old Behavior:
1. `setSelection([0])` caused an index error on an empty list, and as a result `_providerViewsMap` was not updated.
2. After removing a provider, re-adding it caused this error:
3. When two providers (for example China & US Gov) were selected but none of them contained any accounts, only one "Add an Account" option was shown when there should be two, one for each provider.
4. There was an index out of bounds error because we weren't correctly incrementing/decrementing the index stored in providerView when we add/remove elements to the splitView  
New Behavior:
1. Check the length of firstView.view before calling `setSelection([0])
2. Check if a provider has been added already
3. Check how many …
> Fix Account Dialog with Multiple Providers

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/package.nls.json
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/mainController.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
This PR fixes #15312. This adds support for renaming files in a sql project. This will swap over to using the Move api in the DacFx projects when we move to use those apis.
Input boxes in treeviews aren't currently supported, which is why a quickpick is used for entering the new file name.
error when a file with the same name at that location already exists:
> Rename file support in sql projects

- extensions/mssql/src/sqlToolsServer.ts
For #21851
The PR: https://github.com/microsoft/azuredatastudio/pull/21591 hooked up the 'SQL Tools Service' output channel with the Data Protocol Client and the errors started show up in there in a very noticeable way. The particular error in the issue has always been there but caught the user's attention because of the different output locations.
for 1.41 release, I am reverting the output channel change so that users won't be annoyed, and, in the meanwhile, I will fix the actual problem in main branch.
> revert the language clent channel change

- extensionsGallery-insider.json
This PR updates the Insiders extension gallery to the latest release candidate version of the SQL Migration extension. This change includes hot fixes for encrypt / trust sever certificate error and update databases query. 
Link to Azure Data Studio - Extensions pipeline run containing vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=189284&view=results
> Bump sql-migration insiders to 1.3.1

- extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts
Removing these functions since they aren't being used so that they don't need to be updated with the changes needed for adding drag and drop support.
`getParent` is an optional function to implement of `TreeDataProvider`. The way we had it implemented uses a circular reference that child parents had to the parent, which is something I'm getting rid of later which is necessary for drag and drop support.
`focus` was added before the Data Workspace extension was introduced to display tree views, and this function was no longer used after that change.
> Remove unused SqlDatabaseProjectTreeViewProvider functions

- extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/tree/baseTreeItem.ts
- extensions/sql-database-projects/src/models/tree/databaseReferencesTreeItem.ts
- extensions/sql-database-projects/src/models/tree/fileFolderTreeItem.ts
- extensions/sql-database-projects/src/models/tree/projectTreeItem.ts
- extensions/sql-database-projects/src/models/tree/sqlcmdVariableTreeItem.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
- extensions/sql-database-projects/src/test/projectTree.test.ts
Splitting this out from the drag and drop changes to make it easier to review. A couple small cleanup tasks for the projects tree:
- Remove MessageTreeItem - this was originally added for SpacerTreeItems, but those haven't been used for a couple years when Data Workspace changed the project tree loading to load each project separately
- Rename projectUri to relativeProjectUri
> Cleanup sql projects tree

- extensions/sql-database-projects/src/models/tree/baseTreeItem.ts
- extensions/sql-database-projects/src/models/tree/databaseReferencesTreeItem.ts
- extensions/sql-database-projects/src/models/tree/fileFolderTreeItem.ts
- extensions/sql-database-projects/src/models/tree/projectTreeItem.ts
- extensions/sql-database-projects/src/models/tree/sqlcmdVariableTreeItem.ts
- extensions/sql-database-projects/src/test/projectTree.test.ts
Part 1 of removing the circular references from the sql projects tree. Because there are so many changes needed for removing the circular reference, I'm splitting this effort into different parts.
This PR updates the sql project tree items to no longer use the parent node for calculating paths, but the actual removal of the parent node will be in the next PR. 
**More info on why the parent references are causing problems with adding drag and drop support:**
Drag and drop support can be added by a tree provider implementing the `vscode.TreeDragAndDropController`, which has the functions `handleDrag` and `handleDrop`.
When I tried implementing this for the sql projects tree, I was running into this error about circular references that was causing `handleDrop` to not get called:
In order for …
> Update sql projects tree to use sqlproj uri instead of parent nodes

- src/sql/base/browser/ui/table/formatters.ts
- src/sql/base/browser/ui/table/media/slickColorTheme.css
- src/sql/platform/query/common/query.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
- src/sql/workbench/contrib/query/browser/queryResultsEditor.ts
- src/sql/workbench/contrib/query/common/resultsGrid.contribution.ts
This PR fixes #21908
1. The underline decoration only shows on hover.
3. add a setting to control whether we treat JSON cells differently.
Before:
After:
With the setting on (default)
With the setting off
> update the default json cell style and allow user to disable special handling for JSON cells

- extensions/dacpac/src/test/testDacFxService.ts
- extensions/mssql/src/contracts.ts
- extensions/mssql/src/dacfx/dacFxService.ts
- extensions/mssql/src/mssql.d.ts
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/models/publishProfile/publishProfile.ts
- extensions/sql-database-projects/src/test/testContext.ts
- extensions/types/vscode-mssql.d.ts
This PR is the first part for saving publish profile (https://github.com/microsoft/azuredatastudio/issues/12185).
The missing functionality in PR:
- present profile in tree and add context menu to it
- add publish profile information to sqlproj.
Before changes:
After changes:
Publish to existing server:
Publish to new SQL container
> Add profile section in Publish project UI

- src/sql/workbench/contrib/profiler/browser/profilerTableEditor.ts
https://msdata.visualstudio.com/Data%20Studio/_workitems/edit/1613458
when hidden, the elements are still in the DOM, we need to set display to none so that keyboard focus won't go into it.
> completely hide the hidden widget

- extensions/sql-database-projects/src/controllers/mainController.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/tree/baseTreeItem.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
Part 2 of removing the circular references in the sql projects tree. Part 1 was https://github.com/microsoft/azuredatastudio/pull/21901
This PR removes all the references to the `root` of sql project tree items, which is what the circular reference was being used to access the project stored at the root `ProjectRootTreeItem`. All those places using the root for that purpose are now opening the project using the sqlproj uri. I tried passing the `Project` to each `BaseProjectTreeItem`, but that also resulted in circular reference errors from drag and drop because of the project xml that's stored in the `projFileXmlDoc` of a `Project`, which is why I had to go down this route.
Several tests had to be updated to reopen the project now that the same project object that was previously stored in …
> Remove references to root in sql projects

- src/sql/workbench/services/connection/browser/connectionDialogService.ts
- src/sql/workbench/services/connection/browser/connectionWidget.ts
- src/sql/workbench/services/connection/test/browser/connectionDialogService.test.ts
This PR fixes #21812
This PR fixes a bug around remembered passwords for connections not appearing in the connection blade. Clicking on the "Connect" button for a server that has previously been connected to and set to have the password remembered will now appear in the connection pane.
1. Click on the "Connect" button (plug icon) on a server node that has previously been connected to.
1.1. Switch the authentication type to SQL Login (May not need to do this if default auth type is SQL Login).
2. The user name and password for the connection will be filled in.
> Fix missing password in Connection pane for Server connections with remembered passwords

- src/sql/workbench/contrib/notebook/browser/cellViews/outputArea.css
- src/sql/workbench/contrib/notebook/browser/outputs/plotlyOutput.component.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/21859
> Add horizontal scrollbar to Kqlmagic table and remove plotly graph max width

- src/sql/workbench/services/connection/browser/connectionDialogService.ts
Opening the connection dialog was failing because this model reference was undefined. Introduced by this change: https://github.com/microsoft/azuredatastudio/commit/d9b24522e5c5ab11301ebc9c3addbcedf8e9229b#diff-1c35cfd3000efef5f2127a369f5c49e1c5c6c8d83e12582d42b78326a1605f76R418
> Add a check for an undefined model when creating the connection dialog model.

- src/sql/base/browser/ui/colorbox/colorbox.ts
- src/sql/base/browser/ui/colorbox/media/colorbox.css
- src/sql/workbench/contrib/objectExplorer/common/serverGroup.contribution.ts
- src/sql/workbench/services/serverGroup/browser/media/serverGroupDialog.css
- src/sql/workbench/services/serverGroup/browser/serverGroupDialog.ts
https://github.com/microsoft/azuredatastudio/issues/9203
**Problem**
Currently, the server group color is using opacity to indicate which is the current selected color, there are couple issues with it:
1. The color box with low opacity doesn't meet the contrast ratio requirement.
2. Not obvious about which color is currently selected.
also, 2 predefined colors do not meet the contrast ratio requirement.
**Fix**
1. use the native radio button to indicate the checked state and display the color in a box without opacity.
2. add a white border for the color box, so that the contrast ratio meet the contrast requirement even in dark mode.
3. also fixed an issue that the color selected using keyboard are not persisted.
4. updated the 2 predefined colors to meet the contrast ratio requirement. …
> fix server group color a11y issue

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- src/sql/workbench/browser/modelComponents/table.component.ts
- src/sql/workbench/contrib/profiler/browser/profilerEditor.ts
- src/sql/workbench/contrib/profiler/browser/profilerTableEditor.ts
- src/sql/workbench/services/profiler/browser/profilerFilterDialog.ts
- src/typings/slickgrid.d.ts
- yarn.lock
https://msdata.visualstudio.com/Data%20Studio/_workitems/edit/1655874
**Problem**
In profiler, the data in text and details components are changed based on the selected row in the events table, currently keyboard-only won't be able to reach these components if they want to see the details of a particular row.
**Fix**
Disable the tab navigation in the events grid so that users can use the arrow keys to navigate within the table and can also reach the details when they need to using Tab key.
**Changes**
1. Implement the tab navigation option in slickgrid directly to make this feature more accessible.
2. Remove the previous implementation in model view component.
Notes: I personally would prefer to disable in grid tab navigation for all read-only tables to make it easier to navigate through …
> add tab navigation option for slickgrid

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/models/dataSources/sqlConnectionStringSource.ts
- extensions/sql-database-projects/src/models/publishProfile/publishProfile.ts
This PR fixes #21927.
Prior changes did not read Encrypt and Trust Server Certificate value, hence doesn't load the connection properly and throws an error. The changes here reads it and uses these values to create a connection profile with proper options.
> Read server options from publish profile

- extensions/sql-migration/src/wizard/targetSelectionPage.ts
this code fixes a bug in the target selection wizard step that would not correctly auto-populate child dropdown selections when a new target value does not change... resulting in un-triggered value change event resulting in uninitialized or stale components.
Tested with the following settings targeting SQL MI by toggling between the two locations:
and:
> SQL migration extension - fix target selection bug

- src/sql/workbench/services/connection/browser/connectionWidget.ts
This PR fixes #21979
The error was occurring because the `_initialConnectionInfo` property was undefined when the auth type was being set. This PR fixes that by ensuring that `_initialConnectionInfo` is set to a value before the auth type is set to SQL Login. The auth type needs to be set because the `addSavedPassword` call checks for the auth type to be SQL Login so it can retrieve the password from the credential service.
> Fix set authenticationType of undefined error in connection dialog

- src/sql/workbench/services/connection/browser/connectionWidget.ts
Current behavior:
1. Remove all registered Azure accounts
2. Open connection dialog
3. If AzureMFA isn't selected select it, then close and reopen connection dialog
4. See error in console   ERR Unexpected error populating initial Azure Account options : TypeError: Cannot read properties of undefined (reading 'key')
New Behavior:
- No error message displayed 
This PR fixes #21642
> Handle undefined error when opening connection dialog

- extensions/mssql/src/contracts.ts
- extensions/mssql/src/mssql.d.ts
- extensions/mssql/src/sqlProjects/sqlProjectsService.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
Exposing the `newProject` api from STS and swapping the sql projects extension to use it for creating new projects
> Swap create new project api for sql projects

- .github/CODEOWNERS
Helps make sure relevant owners are included on PRs.
> Add Codeowners for import and sql-migration

- extensions/admin-tool-ext-win/README.md
- extensions/azuremonitor/README.md
- extensions/dacpac/README.md
- extensions/data-workspace/README.md
- extensions/datavirtualization/README.md
- extensions/import/README.md
- extensions/kusto/readme.md
- extensions/notebook/README.md
- extensions/query-history/README.md
- extensions/resource-deployment/README.md
- extensions/schema-compare/README.md
- extensions/sql-assessment/README.md
- extensions/sql-bindings/README.md
- extensions/sql-database-projects/README.md
- extensions/sql-migration/README.md
This was brought up in a recent review that extensions don't make it clear how to disable reporting - so adding a section to all extensions that send it. 
Note 1 : I'll also be updating https://github.com/Microsoft/azuredatastudio/wiki/How-to-Disable-Telemetry-Reporting#how-to-disable-telemetry-reporting a bit later since right now it's not up to date with the latest setting changes that we've gotten from VS Code
Note 2 : The SQL Bindings extension links to the VS Code docs since it's currently a VS Code-only extension and the SQL Projects/Data Workspace has the VS Code links added as well.
> Add telemetry section to extension READMEs

- src/sql/workbench/api/browser/mainThreadConnectionManagement.ts
- src/sql/workbench/services/connection/browser/connectionDialogService.ts
This PR fixes #21835
This PR will stop Azure connections with the "< Do not save >" server group option selected from appearing in the default server group list in the "Servers" pane.
> Stops Azure connection with the "Do not save" server group option from being stored in the default server group list.

- src/sql/workbench/services/objectExplorer/browser/connectionTreeAction.ts
This PR fixes #21935
The PR fixes the connection delete prompt by showing the server name when the optional connection name isn't provided.
> Fix empty connection name in delete connection prompt

- extensions/data-workspace/package.json
- extensions/data-workspace/src/common/interfaces.ts
- extensions/data-workspace/src/main.ts
- extensions/data-workspace/src/services/workspaceService.ts
- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/test/dialogs/createProjectFromDatabaseDialog.test.ts
- extensions/sql-database-projects/src/test/dialogs/createProjectFromDatabaseQuickpick.test.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
This PR fixes #21978. This removes the * activationEvent for the data workspace extension. This was originally added because in ADS, we didn't want the projects view to show unless the sql projects extension was also installed. With this change, the projects view will always show on the Activity Bar in ADS and vscode, but it will only be activated when the view is opened, the projects new or open command is run, or if the sql projects extension is activated by one of its activation events.
> Remove data workspace * activationEvent

- src/sql/workbench/services/objectExplorer/browser/serverTreeActionProvider.ts
This PR fixes #1866
The refresh action doesn't do anything when a connection profile is disconnected and it also doesn't show any indicator that it didn't do anything. By hiding the action we can make it clear that the action only refreshes connected profiles and not disconnected profiles.
Disconnected profiles don't show the refresh context menu action:
Connected profiles show the refresh context menu action:
> Hide refresh context menu action on disconnected connections

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/services/accountManagement/browser/accountManagementService.ts
Improve Error Messages coming from azurecore extension
Current Behavior:
When adding an account fails due to an MSAL error, we proceed with an undefined account until it hits an undefined error
New Behavior:
We capture the error message and throw a more detailed message to the user
> Update api to pass more detailed error messaging from azurecore

- extensions/sql-database-projects/src/tools/buildHelper.ts
This updates the default version of Microsoft.Build.Sql to pull the DacFx dlls from for building legacy style sql projects. The default version for creating new SDK-style projects has already been updated in DacFx.
> Update version of Microsoft.Build.Sql used for building legacy sql projects

- src/sql/platform/telemetry/common/adsTelemetryService.ts
- src/sql/platform/telemetry/common/telemetry.ts
Left over from previous versions of the telemetry service, don't need with latest changes made from previous VS Code merge.
> Remove unused things from ads telemetry service

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/tree/sqlcmdVariableTreeItem.ts
- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
This hooks up the sqlcmd variable delete to the STS project apis. It also adds opening projects in STS when the projectProvider loads projects to display them in the projects view
> Hookup sqlcmdvar delete

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/models/tree/projectTreeItem.ts
- extensions/sql-database-projects/src/test/baselines/baselines.ts
- extensions/sql-database-projects/src/test/baselines/openSqlProjectWithAdditionalPublishProfileBaseline.xml
- extensions/sql-database-projects/src/test/baselines/openSqlProjectWithAdditionalSqlCmdVariablesBaseline.xml
- extensions/sql-database-projects/src/test/project.test.ts
This PR is the second part for saving publish profile (https://github.com/microsoft/azuredatastudio/issues/12185) and it completes the UI functionality. It adds the ability to present created profiles in the project tree and add it to the sqlproj file. 
The only remaining piece for finalizing the profile work is to add the upstream functionality to read deployment options appropriately.
> Add publish profile to sql proj and tree

- extensions/sql-migration/config.json
This PR updates the JSON-RPC Migration service to the latest version. Critically, it also changes the dotnet version to 7.0. The STS dotnet version was recently changed, which changed the names of the release packages and broke our existing links.
> Update migration service to 4.5.0.28 and dotnet version to 7.0

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/common/dataWorkspaceExtension.ts
- extensions/data-workspace/src/main.ts
- extensions/data-workspace/src/services/workspaceService.ts
Now that the projects view is always visible in ADS after https://github.com/microsoft/azuredatastudio/pull/22005, this adds showing an error if a user tries to open or create a project without an extension that contributes a database project type installed.
> Show error if trying to create or open project when no project extension is installed

- extensionsGallery.json
This PR updates the insiders extension gallery to the latest version of the SQL Migration extension. The main change here is the decoupling of the migration extension from STS, where we instead now use our own dedicated Migration service - see https://github.com/microsoft/azuredatastudio/pull/21781
Link to Azure Data Studio - Extensions pipeline run off main containing vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=189857&view=results
> [SQL-Migration] Release v1.4.0 to Stable

- extensions/notebook/package.json
- extensions/notebook/src/book/bookTreeView.ts
- extensions/notebook/src/typings/refs.d.ts
Integrated our Jupyter Books viewlet with the VS Code-style notebooks. I opted to have the extension check the useVSCodeNotebooks flag, rather than changing azdata's showNotebookDocument, to prevent potential side effects for callers that I haven't tested yet.
> Open books in VS Code notebooks if the setting is enabled.

- src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts
This PR fixes #21887 
When the cell values are undefined, I am falling back to simple Boolean values for the cell. There was also a null check that I added for header checkboxes
> Adding null checks and fixing values in slickgrid checkbox column plugin 

- src/sql/platform/connection/common/connectionConfig.ts
Just adding null checks fixes this issue. On a new ADS installs the profiles are undefined and filter function returns a runtime exceptions causing the group to not get deleted. 
This PR fixes #21831
> Adding null checks to let users delete server groups on fresh ADS install

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/models/tree/fileFolderTreeItem.ts
- extensions/sql-database-projects/src/models/tree/projectTreeItem.ts
- extensions/sql-database-projects/src/test/projectTree.test.ts
Adding this info in the tree to keep track of what type of item each file is. This will simplify the changes in https://github.com/microsoft/azuredatastudio/pull/22051 so that each collection doesn't need to be iterated to determine which collection is part of.
> Have different node types for the different item types in sql project tree

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/tree/fileFolderTreeItem.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
- extensions/sql-database-projects/src/test/projectTree.test.ts
This updates the rename file function to call the DacFx move apis for renaming sql object scripts, pre, and post deploy scripts.
Example of renaming a sql object script and a pre deployment script in a legacy project:
> Swap rename to use DacFx move api

- extensions/mssql/src/main.ts
Fixes #22044
When I added a listener for query completion in the SQL kernel, it broke the rest of the editors listening on the MSSQL provider. Disabling this controller for now.
> Disable the vscode SQL notebook controller since it breaks query editor.

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
This switches `moveFile()` used for drag and drop to use the DacFx api exposed in STS to move the file on disk and in the .sqlproj. Also moves the move part to a helper function so both rename and moveFile can call it.
> Update sql project file move to use DacFx api

- extensions/mssql/config.json
Brings in a variety of bug fixes for SqlProjectsService, and support for project properties and `None` entries
> Bump SqlToolsService to 4.5.0.33

- extensions/sql-migration/package.json
- extensions/sql-migration/src/api/sqlUtils.ts
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/main.ts
- extensions/sql-migration/src/models/loginMigrationModel.ts
- extensions/sql-migration/src/telemetry.ts
- extensions/sql-migration/src/wizard/loginMigrationStatusPage.ts
- extensions/sql-migration/src/wizard/loginMigrationTargetSelectionPage.ts
- extensions/sql-migration/src/wizard/loginSelectorPage.ts
- extensions/sql-migration/src/wizard/wizardController.ts
This PR enhances telemetry for login migrations (and  in the following ways:
- Add details for starting migration (number of logins migrating, type of logins)
- Log Migration result (number of errors per step, duration of each step, type of logins, if system error occurred)
- Add sql-migration extension to our telemetry
- Adds details when trying to connect to target
- Tracks clicking "done" from the wizard
-  Fixes bucketizing for navigating telemetry in the login migration wizard 
Sample usage of kusto query for new telemetry:
RawEventsADS
| where EventName contains 'sql-migration'
| extend view = tostring(Properties['view'])
| extend action = tostring(Properties['action'])
| extend buttonPressed = tostring(Properties['buttonpressed'])
| extend pageTitle = …
> [SQL-Migration] Login migrations telemetry

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/project.ts
After some more thought, it makes more sense for the calls to STS to update a project to go through project.ts, rather than happening in projectController.ts. This way, all the calls to STS to update a project, like add file, exclude, delete, etc, will go through project.ts.
This also updates `rename()` and `move()` to not swallow errors returned from STS and now shows an error notification if there was an error.
> Move call to STS move api into project.ts

- extensions/mssql/config.json
- extensions/mssql/src/contracts.ts
- extensions/mssql/src/mssql.d.ts
- extensions/mssql/src/sqlProjects/sqlProjectsService.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/project.test.ts
- extensions/types/vscode-mssql.d.ts
This removes `Value` as a parameter for add/update sqlcmd variables, as done in STS in https://github.com/microsoft/sqltoolsservice/pull/1885, and swaps over to use the STS apis for adding and updating sqlcmd variables in a sql project.
> Swap add and update sqlcmd variables in sql projects to use STS apis

- src/sql/workbench/api/browser/extensionHost.contribution.ts
- src/sql/workbench/api/browser/mainThreadDataProtocol.ts
- src/sql/workbench/api/browser/mainThreadPerf.ts
- src/sql/workbench/api/common/extHostDataProtocol.ts
- src/sql/workbench/api/common/extHostPerf.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
- src/sql/workbench/services/query/common/queryManagement.ts
- src/sql/workbench/services/query/common/queryRunner.ts
- src/vs/workbench/api/common/extHost.protocol.ts
#21741
This is an initial PR for adding perf tracing to query execution. A few marks have been added in renderer and extHost processes. Log level needs to be set to debug for this msg to show up.
Next steps will be adding more tracing during rendering in UI and STS.
> Add perf marks for query execution

- src/sql/workbench/api/common/sqlExtHost.protocol.ts
Was looking through my commit for enabling vscode notebooks and noticed this leftover $connect change that didn't get cleaned up.
> Remove unused $connect arg leftover from vscode notebooks change.

- extensions/sql-migration/config.json
This PR vbumps the version of the backend migration service in order to pull in the latest version of the assessment NuGet, which includes several improvements including adding support for assessing SQL Server 2022. 
See sqltoolsservice PR for more details: https://github.com/microsoft/sqltoolsservice/pull/1889
> [SQL Migration] vbump migration service

- extensions/mssql/config.json
Brings update for AAD Interactive Auth support from STS
https://github.com/microsoft/sqltoolsservice/compare/4.5.0.35...4.5.0.36
> Bump STS for AAD Interactive support

- src/sql/workbench/services/errorMessage/browser/errorMessageDialog.ts
Handle null reference of promise when dialog is opened synchronously.
Fixes console error:
```
[renderer1] [error] this._promiseResolver is not a function: TypeError: this._promiseResolver is not a function
at ErrorMessageDialog.close (vscode-file://vscode-app/e:/azuredatastudio/out/sql/workbench/services/errorMessage/browser/errorMessageDialog.js:127:22)
at ErrorMessageDialog.ok (vscode-file://vscode-app/e:/azuredatastudio/out/sql/workbench/services/errorMessage/browser/errorMessageDialog.js:121:18)
```
> Fix console error raised from error dialog action

- extensionsGallery-insider.json
This PR updates the Insiders extension gallery to the latest release candidate version of the SQL Migration extension. Some of the key changes are:
- [SQL migration extension - fix target selection bug ](https://github.com/microsoft/azuredatastudio/pull/21977)
- [Adding aria role to hyperlink cell in slickgrid](https://github.com/microsoft/azuredatastudio/pull/21998)
- [[SQL Migration] Allow folders inside blob containers](https://github.com/microsoft/azuredatastudio/pull/21952)
- [Update login migration infobox for public preview](https://github.com/microsoft/azuredatastudio/pull/22074)
- [[SQL-Migration] Login migrations telemetry](https://github.com/microsoft/azuredatastudio/pull/22038)
- [Improve error handling for ValidateIR](https://github.com/microsoft/azuredatastudio/pull/22091)
- …
> Bump sql-migration version in insiders

- src/sql/workbench/services/accountManagement/browser/accountDialog.ts
- src/sql/workbench/services/accountManagement/browser/accountManagementService.ts
- src/sql/workbench/services/accountManagement/test/browser/accountManagementService.test.ts
- src/sql/workbench/services/accountManagement/utils.ts
- src/sql/workbench/services/connection/browser/connectionWidget.ts
We've been getting issues like below:
"TypeError: Cannot read properties of undefined (reading 'authLibrary')"
Ref: https://github.com/microsoft/azuredatastudio/issues/16655#issuecomment-1422720048
I noticed, we weren't defaulting to MSAL properly in AccountManagementService, this would have caused trouble when migrating accounts from ADAL to MSAL. This PR moves authLibrary to Utils, and ensures MSAL is selected by default.
Should potentially fix https://github.com/microsoft/azuredatastudio/issues/22056, fix https://github.com/microsoft/azuredatastudio/issues/21874, etc.
> Fix AuthLibrary detection and use MSAL by default

- extensions/mssql/src/objectManagement/ui/loginDialog.ts
- extensions/mssql/src/objectManagement/ui/objectManagementDialogBase.ts
- extensions/mssql/src/objectManagement/ui/userDialog.ts
when the dialog is canceled (by pressing escape key or clicking the cancel button), the disposeView request should be send immediately, but when OK button is clicked, the disposeView request should be send after the operation is complete.
> dispose view after the operation is done

- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
Adding vscode-mssql handling for getting sql projects service now that it's been added in vscode-mssql
> add vscode mssql handling for getSqlProjectsService()

- extensions/sql-database-projects/src/models/project.ts
I missed this when swapping out the add dacpac reference code in https://github.com/microsoft/azuredatastudio/pull/22116. On Windows, `settings.dacpacFileLocation.fsPath` has a leading backslash that needs to be removed for build to work on Windows, so this replaces that with `pathForSqlProj()` which removes the leading slash
https://github.com/microsoft/azuredatastudio/blob/5b95a47ca6f6baadb49bbd7829c6a3e3d68f57ac/extensions/sql-database-projects/src/models/projectEntry.ts#L69-L72
> Fix path for dacpac reference on windows

- src/vs/workbench/browser/parts/editor/editorDropTarget.ts
This PR fixes #22057
before:
after:
> escape the special character

- src/sql/workbench/contrib/executionPlan/browser/executionPlanContribution.ts
- src/sql/workbench/contrib/executionPlan/browser/executionPlanEditor.ts
- src/sql/workbench/contrib/executionPlan/browser/executionPlanInput.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
- src/sql/workbench/services/executionPlan/common/executionPlanService.ts
This PR fixes #20902 
This PR registers execution plan editor early in the workbench lifecycle. That will  make it available for the URI based file to use when ADS starts.
> Fixing URI openings for execution plans 

- src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/interfaces.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
- src/sql/workbench/contrib/notebook/test/stubs.ts
- src/sql/workbench/services/notebook/browser/notebookService.ts
This started off with me noticing in markdownToolbar.component.ts that we weren't calling the hasEditor function itself - only checking that the function existed. But then looking at it I don't even see why this needs to exist - the same logic can be done by calling getEditor and checking if it's undefined or not. So just removing it to keep things simpler.
> Remove hasEditor from ICellEditorProvider

- extensionsGallery.json
Updating the dacpac extension to 1.13.0 in RC to the same version that was released in insiders in https://github.com/microsoft/azuredatastudio/pull/21946
> update dacpac extension in RC gallery

- extensions/mssql/src/objectManagement/ui/userDialog.ts
This is part of the changes for https://github.com/microsoft/azuredatastudio/issues/22173.  For March release we will only support User with Login, and add other user types for May.
> Only support 'user with login' in dialog

- extensions/mssql/config.json
Brings in a cross-platform path bug for SqlProjects service
> Bumping SQL Tools Service to 4.6.0.2

- extensions/sql-database-projects/src/models/project.ts
After this is swapped out, then the system dacpac ADS and SSDT paths stored in TS can be removed since DacFx does all that work.
> Swap changeTargetPlatform to call STS

- extensions/data-workspace/package.json
Fixes https://github.com/microsoft/azuredatastudio/issues/22194. The data workspace extension used to have a `*` activation event that was removed in https://github.com/microsoft/azuredatastudio/pull/22005. The sql projects extension was also updated in that PR, but since we aren't releasing sql projects this release, the data workspace extension wasn't getting activated when the sql projects was getting activated from these commands. 
As a temporary fix before the next sql projects extension is released, this adds these commands as activation events for data workspace.
> add sql project commands to data workspace activation events

- extensions/mssql/package.json
https://github.com/microsoft/azuredatastudio/issues/22207
these commands were added and then removed due to schedule change, but I missed removing them from the commandPalette.
> remove non-exist commands from commandPalette menu contribution point

- extensionsGallery.json
updating the extensions gallery to align with the insiders gallery so that the diff will no longer flag these items
> updating the extensions gallery to align with the insiders gallery

- extensions/mssql/config.json
- extensions/mssql/src/contracts.ts
- extensions/mssql/src/mssql.d.ts
- extensions/mssql/src/sqlProjects/sqlProjectsService.ts
Bringing over the STS fix https://github.com/microsoft/sqltoolsservice/pull/1915 for the delete database reference request handler not being set and changing the params for the request to the correct interface.
> Fix delete database reference request

- extensions/mssql/package.json
This PR fixes #22207
port https://github.com/microsoft/azuredatastudio/pull/22218 to release branch.
> remove nonexistent commands (#22218)

- extensions/datavirtualization/package.json
- extensions/datavirtualization/src/command.ts
- extensions/datavirtualization/src/wizards/wizardCommands.ts
azdata.connection.ConnectionProfile.createFrom isn't getting the updated database correctly - there's a couple issues.
1. The options property bag has `database` - not `databaseName`
2. The value of `database` seems to be the original value of the connection itself, not the one of the current context (i.e. I have a connection to master, but then right click on a database and it ends up with `options.database` being `master` and `databaseName` being the database I clicked)
For a quick fix I'm just directly copying over the databaseName value, although following up with 2 to see what's going on there is something we should do at some point. 
(also did a bit of cleanup of some unused stuff I noticed while fixing this)
> Fix datavirtualization wizard opening to wrong database

- extensions/azurecore/package.json
- extensions/azurecore/yarn.lock
Updating @azure/msal-node to hopefully resolve this issue: https://github.com/microsoft/azuredatastudio/issues/22227#issuecomment-1461202478
Also removed `msal` npm package not used by the extension.
> Update @azure/msal-node to 1.16.0

- extensions/data-workspace/src/main.ts
This PR addresses https://github.com/microsoft/azuredatastudio/issues/22278. This change was originally made in https://github.com/microsoft/azuredatastudio/pull/21956 for the drag and drop changes for the sql projects tree. Because sql projects isn't being released this month, this change needs to be undone so that the older versions of the sql projects extension will be able to remove projects from the data workspace projects view.
> undo remove project change in data workspace

- src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
- src/sql/workbench/contrib/editData/browser/media/editData.css
PR adds proper regex for replacing null characters after an edit.
It adds a check to see if the unicode null character exists in a pre-edit string or not. If it does, you will not be able to edit it and the cell's text will be highlighted in yellow along with an warning explaining why you cannot edit the cell if it is selected, either automatically upon launch if it's the first cell or when a user tries to click it. (although I am not able to test this scenario in SSMS as I found it was not possible to add it via SSMS to a SQL server) 
Also removes row number in loadItem as it's not being used at all and does not exist on Slickgrid.
Initial screen with comparison to SSMS:
Screen while editing multiline cell:
Screen after editing multiline cell:
Hypothetical (test scenario without checks) …
> Fix for Edit Data grid newline on multiline strings

- extensions/azurecore/package.json
- extensions/azurecore/yarn.lock
Hopefully addresses https://github.com/microsoft/azuredatastudio/issues/22227 ([reported issues](https://github.com/microsoft/azuredatastudio/issues/22227#issuecomment-1461202478)) with v1.16.0 of @azure/msal-node npm package.
v1.16.0 Release notes for ref: https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-node-v1.16.0
The previous update attempt could have been fine, but due to today's AAD issues, it got me worried if insiders was reproducing issues due to this update. But I updated and verified again and it looks good to go!
> Update @azure/msal-node to v1.16.0

- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/test/project.test.ts
- organizing sqlcmd variable and db reference functions in project.ts
- added reloading sqlcmd variables and db references after their helper functions run so tests don't need to reload the project
- moved database reference tests to their own suite to make them easier to run on their own
> Organizing sqlcmd variable and db reference code

- src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR fixes #22252
Recently a new export to markdown action was added, but the min-height is not adjusted.
> fix action bar size

- extensions/sql-database-projects/src/test/project.test.ts
Removing a few tests that are now covered in DacFx. The `SystemDatabaseReferenceProjectEntry` no longer has `ssdtUri` after the swap since DacFx handles adding and removing the reference from the xml, which is why this test was commented out before.
> remove system dacpac tests that were moved to DacFx

- extensions/sql-migration/src/dialog/createSqlMigrationService/createSqlMigrationServiceDialog.ts
fixes an issue with the SQLMigration extension to include SHIR registration added to the Create Service dialog when SQL DB is a target
> SQL Migration extension - add SHIR registration for create service for sqldb

- extensions/sql-database-projects/src/controllers/projectController.ts
Fix this error when excluding a table and externalStreamingJob from a sqlproj after #22166. These two have their own DatabaseProjectItemType subtype because they have commands specific to their object types, but they should be handled like the other sqlObjectScripts.
> fix exclude for table and externalStreamingJob

- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
Add reload project parameter to `openProject()` so that the refresh tree button actually works and reloads the project if the project was updated outside of the sql projects extension
> add reload project

- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
- src/sql/workbench/contrib/objectExplorer/common/serverGroup.contribution.ts
- src/sql/workbench/contrib/objectExplorer/test/browser/serverTreeView.test.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
- src/sql/workbench/services/objectExplorer/browser/treeSelectionHandler.ts
- src/sql/workbench/services/objectExplorer/test/browser/objectExplorerService.test.ts
This PR addresses issue #22303.
The "expandOrRefreshNode" function in Object Explorer can sometimes get stuck in an infinite wait state when node providers fail to return nodes, preventing the main promise of the method from resolving. To address this, I've implemented a new method that checks if the required results are available within 45 seconds. If not, the promise is forcibly resolved.
Additionally, I've added a new check to ensure that no duplicate sessions are created for connections in the OE tree. If a node is already part of the tree, it is just focused rather than selected again (which can create a new session) and fetch nodes. 
Node timeouts
https://user-images.githubusercontent.com/6816294/224863028-ff74bba6-5cac-4b43-9f82-a968771a02c2.mp4
> Fixing new connections not expanding in object explorer.

- extensions/sql-database-projects/src/models/project.ts
A couple tests were failing because this was hardcoded and they were expecting a different target platform
> set DSP from STS

- extensions/mssql/package.nls.json
This PR fixes #22340
add a preview label for the new ADS properties dialog to differentiate it from the SSMS-Min menu item. when the new feature is ready for GA, I'll update the SSMS-Min extension and remove the menu item contributions for the node types we support natively in ADS.
for the comment about move the new `Properties` menu item to the bottom of the default group, it is not possible due to the way we implemented it in core, `Refresh` will always be the last one in the default group. 
@aasimkhan30 could you please work with the PM to define the menu item order/grouping guideline?
> update the display name

- extensions/datavirtualization/src/test/stubs.ts
- extensions/resource-deployment/package.json
- extensions/resource-deployment/yarn.lock
- extensions/sql-database-projects/src/dialogs/publishOptionsDialog.ts
- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/extHostModelView.ts
This PR addresses #22165. This adds ariaLive to the option descriptions so that they get announced by the screenreader when the option description changes.
> add ariaLive to publish options description

- extensions/sql-database-projects/src/common/constants.ts
I had changed these last week in https://github.com/microsoft/azuredatastudio/pull/22215 because DacFx was expecting the uppercase values, but after discussion, changing them back to lowercase since that's the more common way to see them cased. A separate change will be made in DacFx to handle the different casing.
lowercase system db names back in the UI:
> change system dbs back to lowercase in sql projects

- extensions/sql-database-projects/src/tools/buildHelper.ts
The old project XML logic in ADS used to add system db references for legacy projects with the variable  `$(NETCoreTargetsPath)`, so the path would look like` $(NETCoreTargetsPath)\SystemDacpacs\160\master.dacpac`. The new projects library adds system db references for both legacy and SDK-style projects with the variable `$(SystemDacpacsLocation)`, so now this variable also needs to get passed in when building legacy projects.
> pass SystemDacpacsLocation when building legacy style sql projects

- extensions/azurecore/yarn.lock
Seems this entry got missed during a recent PR, as it's showing up for me when running `yarn` on a fresh copy of main.
> Updated yarn.lock file

- extensions/admin-tool-ext-win/src/test/stubs.ts
- extensions/azurecore/src/azureResource/messageTreeNode.ts
- extensions/azurecore/src/azureResource/resourceTreeNode.ts
- extensions/azurecore/src/azureResource/tree/accountNotSignedInTreeNode.ts
- extensions/azurecore/src/azureResource/tree/accountTreeNode.ts
- extensions/azurecore/src/azureResource/tree/flatAccountTreeNode.ts
- extensions/azurecore/src/azureResource/tree/flatTreeProvider.ts
- extensions/azurecore/src/azureResource/tree/subscriptionTreeNode.ts
- extensions/azurecore/yarn.lock
- extensions/azuremonitor/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts
- extensions/cms/src/cmsResource/messageTreeNode.ts
- extensions/cms/src/cmsResource/tree/cmsResourceEmptyTreeNode.ts
- extensions/cms/src/cmsResource/tree/cmsResourceTreeNode.ts
- extensions/cms/src/cmsResource/tree/registeredServerTreeNode.ts
- extensions/cms/src/cmsResource/tree/serverGroupTreeNode.ts
- extensions/datavirtualization/src/hdfsProvider.ts
- extensions/kusto/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts
- extensions/mssql/config.json
- src/sql/azdata.d.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/common/extHostObjectExplorer.ts
- src/sql/workbench/contrib/objectExplorer/test/browser/connectionTreeActions.test.ts
- src/sql/workbench/contrib/scripting/test/browser/scriptingActions.test.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts
- src/sql/workbench/services/objectExplorer/browser/serverTreeActionProvider.ts
- src/sql/workbench/services/objectExplorer/common/treeNode.ts
- src/sql/workbench/services/objectExplorer/test/browser/objectExplorerService.test.ts
- src/sql/workbench/test/electron-browser/api/extHostObjectExplorer.test.ts
This PR fixes #22342
Depends on: https://github.com/microsoft/sqltoolsservice/pull/1949
Root cause:
the schema information is set on the table column node, but the node path doesn't have it, as a result, we couldn't find the parent path. 
Fix:
The extension side shouldn't have knowledge of how the provider is constructing the node path (especially schema is not a common concept across all providers), if we need to know it, we should get it directly from the providers. 
this is the actual change: https://github.com/microsoft/azuredatastudio/pull/22356/files#diff-29942eaeb9ec5e20de436b4fd36ae4ee41588c3d50e58761787ccc863ec50a4aR100, all other changes are just to add the new property.
STS changes:
> fix find parent node issue

- extensions/sql-database-projects/src/test/projectController.test.ts
All projectController tests are passing or skipped after these fixes. 
- skips the one AutoRest test since it's hidden under a preview flag
- fixes database reference test after I missed updating the test after changing master back to lowercase in https://github.com/microsoft/azuredatastudio/pull/22353
> fix projectController tests

- extensions/mssql/src/contextProvider.ts
- extensions/mssql/src/contracts.ts
- extensions/mssql/src/features.ts
- extensions/mssql/src/localizedConstants.ts
- extensions/mssql/src/main.ts
- extensions/mssql/src/telemetry.ts
- src/sql/azdata.d.ts
Going to start poking at getting to enabling strict null checks in the MSSQL extension, this is the first batch. Mostly pretty straightforward although I did uncover some incorrect typings that I fixed up (including some in the published types). 
There is a behavior change with having the failed STS requests throw instead of just return undefined - but since the typings currently don't specify undefined as being valid and an error actually occurred it makes sense to me to just pass the error up and let the caller handle it if they choose since that should be the expected behavior.
> Some MSSQL strict null check fixes

- src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
This PR fixes addresses the accessibility issue https://github.com/microsoft/azuredatastudio/issues/22156 where users using a screenreader wouldn't know what the checkboxes in the table correspond to. 
Before this change, the ariaLabel property for `DeclarativeTableCellValue` was only getting set if the cell type was `string`. This change makes it so that the `ariaLabel` of the cell will get set if the property is set for non-string cells.
checkbox in DeclarativeTable with aria label set (the aria label is the string getting announced before the row number):
> Add aria label for checkboxes in declarative table

- src/sql/workbench/services/connection/browser/connectionWidget.ts
Optional name and grouping should not be ignored
when creating a new connection using a connection string.
This PR fixes https://github.com/Azure/azure-cosmosdb-ads-extension/issues/46
Also improves error handling if the extension failed to parse the connection string:
"Copy details" will copy the error message and the stacktrace to the clipboard.
> Preserve name and group when using Connection String

- extensions/mssql/src/sqlToolsServer.ts
Fixing up the strict null stuff and noticed this was being done incorrectly - it will always evaluate to true. We should be using the default value parameter of `get` instead.
> Fix incorrect default for proxy setting when downloading STS

- extensions/sql-database-projects/src/dialogs/publishOptionsDialog.ts
- extensions/sql-database-projects/src/models/options/deployOptionsModel.ts
Similar to the change made in https://github.com/microsoft/azuredatastudio/pull/22390 for the exclude object types table, this updates the other tab, publish options, to use `DeclarativeTableComponent` instead of `TableComponent` to avoid the accessibility issues of wrong row numbers being announced.
before:
after:
gif that shows the option description at the bottom still gets updated when the selected row changes and that the reset button still works:
> change publish options to use declarative table

- extensions/azurecore/src/account-provider/azureAccountProviderService.ts
- extensions/azurecore/src/account-provider/utils/fileEncryptionHelper.ts
- extensions/azurecore/src/account-provider/utils/msalCachePlugin.ts
- extensions/azurecore/src/azurecore.d.ts
- extensions/azurecore/src/extension.ts
- extensions/machine-learning/src/test/stubs.ts
- extensions/mssql/src/contracts.ts
- extensions/mssql/src/sqlToolsServer.ts
Sends notification to backend SqlToolsService to update encryption keys in a cross-platform compatible way.. 
Addresses https://github.com/microsoft/azuredatastudio/issues/22364 paired with https://github.com/microsoft/sqltoolsservice/pull/1955
> Notify STS when encryption keys are updated in azurecore

- extensions/azuremonitor/src/azuremonitorServer.ts
- extensions/datavirtualization/src/services/serviceClient.ts
- extensions/import/src/services/serviceClient.ts
- extensions/kusto/src/kustoServer.ts
- extensions/sql-migration/src/service/serviceClient.ts
Realize we had this same logic in a number of other extensions, so fixing this everywhere else...
This will currently always evaluate to true. We should be using the default value parameter of get instead for the fallback value.
> More strict SSL proxy setting fixes

- src/sql/platform/connection/common/connectionManagement.ts
- src/sql/platform/connection/test/common/testConnectionManagementService.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
- src/sql/workbench/services/connection/test/browser/connectionManagementService.test.ts
Doing some quick cleanup I noticed while looking at this for https://github.com/microsoft/azuredatastudio/pull/22341
1. Since undefined has never been a part of the typings having it throw if it can't find the provider instead - especially now that we're displaying the error to the user
2. Converting to async for better readability (and Thenable->Promise since there's no need to use Thenable here)
3. Making provider required - maybe that was optional at some point in the past but it's definitely required now
> Clean up buildConnectionInfo

- src/sql/workbench/services/accountManagement/browser/accountManagementService.ts
Previous behavior: 
One account is left in the account list after running clear all accounts action
New behavior:
All accounts are cleared, also add logging error message
This PR fixes #22285
> Fix Clear All Accounts action

- extensions/mssql/src/mssql.d.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts
- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceQuickpick.ts
- extensions/sql-database-projects/src/dialogs/utils.ts
- extensions/sql-database-projects/src/models/IDatabaseReferenceSettings.ts
- extensions/sql-database-projects/src/models/project.ts
- extensions/sql-database-projects/src/models/projectEntry.ts
- extensions/sql-database-projects/src/models/tree/databaseReferencesTreeItem.ts
- extensions/sql-database-projects/src/sqldbproj.d.ts
- extensions/sql-database-projects/src/test/baselines/databaseReferencesReadBaseline.xml
- extensions/sql-database-projects/src/test/project.test.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
- extensions/types/vscode-mssql.d.ts
`DatabseNameLiteralValue` and `DatabaseSqlCmdVarName` are two different things, but were being treated as one due to how the SSDT (and therefore ADS) dialogs prompted for them.  I've changed the flow to make the determination whether the user entered a literalValue or variable name as soon as possible, and to keep them separate for the rest of flow.
> Refactoring database references to split literalVariable from databaseName

- extensions/azurecore/src/account-provider/azureAccountProviderService.ts
- extensions/azurecore/src/account-provider/utils/fileEncryptionHelper.ts
- extensions/azurecore/src/account-provider/utils/msalCachePlugin.ts
- extensions/azurecore/src/azurecore.d.ts
- extensions/azurecore/src/extension.ts
- extensions/machine-learning/src/test/stubs.ts
- extensions/mssql/src/sqlToolsServer.ts
Noticed an issue with firing of event from SqlToolsServer - in case where azurecore cache gets activated first, event if fired only once. And if event listener is not registered, we end up losing emitted event.
Since we absolutely need to read encryption keys to work, I'm introducing a direct access API to be able to read Encryption keys right after STS activation and send notification to backend service. Not considering emitting event multiple times to avoid unnecessary events being fired that would impact performance.
> Handle out of sync extension activations for encryption keys updated event

- extensions/azurecore/package.json
- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/auths/httpClient.ts
- extensions/azurecore/src/account-provider/auths/networkUtils.ts
- extensions/azurecore/src/constants.ts
- extensions/azurecore/src/proxy.ts
- extensions/azurecore/src/utils.ts
Old Behavior: used axios to make get/post request calls
New Behavior: use HttpClient to make get/post request calls, since axios does not officially support proxy
Fixes #21837
> Replace Axios calls with HttpClient

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
This PR reduces attempts to force refresh silent auth request when fetching token for account's full tenant (owning tenant), as the issues only apply for non-owning tenants for multi-tenant scenarios.
This should also improve performance when acquiring access tokens silently for full tenant resources.
Helps address #22403 for account org tenants but throttling issue from MSAL.NET is primarily dependent on https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3687 as MSAL.js doesn't throw throttling error, even though we force refresh on all token requests.
> Skip forceRefresh for full (owning) tenant

- src/sql/workbench/contrib/tasks/browser/tasksRenderer.ts
This PR addresses https://github.com/microsoft/azuredatastudio/issues/22158. This makes it so that the label of tasks gets announced when it first show ups and changes. I initially tried setting `aria-live="polite"` and `assertive`, but it was only announcing when the label changed to "task succeeded" and not the initial "task in progress"  message. Setting role to alert announces both.
> Make screenreader announce task status

- extensions/azurecore/package.json
- extensions/azurecore/src/constants.ts
- extensions/azurecore/src/extension.ts
- extensions/azurecore/src/localizedConstants.ts
This will display a message to the user upon selection of the ADAL Auth Library indicating that ADAL is being deprecated:
Also I found one more location where MSAL was not set as default Auth Library, but this is only used as a fallback if the authentication library setting could not be fetched.
> Show message indicating that ADAL is being deprecated

- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts
This PR addresses https://github.com/microsoft/azuredatastudio/issues/22098 and https://github.com/microsoft/azuredatastudio/issues/22133. Adding an aria label to the container of the radio group in a couple of the sql database projects dialogs.
> add aria labels to a couple radio groups in sql database projects

- extensions/mssql/package.json
- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
- src/sql/workbench/services/objectExplorer/browser/serverTreeActionProvider.ts
- src/sql/workbench/services/objectExplorer/browser/treeSelectionHandler.ts
- src/vs/platform/actions/common/actions.ts
- src/vs/platform/actions/common/menuService.ts
- src/vs/workbench/services/actions/common/menusExtensionPoint.ts
This PR fixes #950
This PR fixes #16377
This PR fixes #22427
There are 3 ways we can implement this feature:
1. in the node information, include a command property and use it as the default command.
2. create another menu similar to the current object explorer item context menu contribution point.
3. add a `isDefault` property to the existing menu contribution (the implementation in this PR)
the downside of the first 2 implementations is that the logic of when the menu item is available needs to be duplicated either in backend service (approach 1)or the package.json (approach2).  the third approach is chosen because of minimum change required from extension side.
when there are multiple default actions, an error will be logged for us to troubleshoot.
I have covered both the tree view and …
> support default action for OE node

- src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR fixes #3643
select the entire row when a cell is double clicked so that it is easier to know whichrow is selected when the user needs to scroll horizontally.
> select the row on double click

- extensions/sql-database-projects/package.json
After the swap to use the DacFx.Projects library, excluding folders is not yet supported. Rather than show an error when a user tries to exclude a folder, it's better to hide it from the folder context menu until it is supported.
before:
after:
> hide exclude folder from context menu until it's supported

- extensions/arc/src/test/mocks/fakeControllerModel.ts
- extensions/azcli/src/test/testUtils.ts
Bringing them back but commenting them out in case we decide to re-enable the arc/azcli tests in the future.
> Bring back arc/azcli test files

- src/vs/platform/extensionManagement/common/extensionGalleryService.ts
This PR fixes #22469
bring back a SQL CARBON edit that was removed in https://github.com/microsoft/azuredatastudio/pull/20883/files#diff-603115949ed162957f481f65cc3266ebf96b817933aa46cf23c25be3592d1e5cL667.
> hide extensions with 'hidden' flag

- extensions/data-workspace/src/common/pathUtilsHelper.ts
This PR fixes #22479. The first time this function gets called when opening the create project from db dialog, the db dropdown hasn't been populated yet which is why it's passing in undefined.
> fix undefined error when opening Create Project from Database dialog

- extensions/schema-compare/src/schemaCompareMainWindow.ts
- extensions/schema-compare/src/test/schemaCompare.test.ts
- extensions/schema-compare/src/test/testContext.ts
- extensions/schema-compare/src/test/testSchemaCompareService.ts
- extensions/schema-compare/tsconfig.json
I felt like doing some code cleanup, so this turns on the `noUnusedParameters` check in the schema compare extension. Most of the errors were from test functions having unused parameters, and the rest were click handlers that weren't actually using the click parameter being passed in.
> turn on noUnusedParameters in Schema Compare

- src/sql/base/common/locConstants.ts
- src/vs/workbench/contrib/extensions/browser/extensionsActions.ts
This came up from a recent discussion around the gallery and it's been something that's bugged me for a while so just doing it now. Previously we would show the "Install" button for all extensions - even 3rd party ones that open up a download page instead. This PR just changes it to show "Download" instead to make it clearer to users what is going to happen when they click the button.
> Switch "Install" to "Download" for downloaded extensions

- extensions/azurecore/src/account-provider/providerSettings.ts
This PR adds Kusto endpoints for non-public clouds.
Fixes the first part of #22437
> Add kusto endpoints for non-public clouds

- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/services/accountManagement/browser/accountManagementService.ts
- src/sql/workbench/services/accountManagement/test/browser/accountManagementService.test.ts
This PR fixes #22505 
Captured in logs:
`[2023-03-28 17:06:56.518] [095ed29e-2e35-47c0-8c06-8db1b7a7ad3a] [trace] telemetry/action {"properties":{"properties.view":"LinkedAccounts","properties.action":"RefreshAzureAccount","properties.target":"","properties.source":"","properties.AuthenticationLibrary":"MSAL","common.machineId":"*****","sessionID":"640af70b-8409-4949-aba2-c2c6b215d90e1680048390341","commitHash":"9ca6200018fc206d67a47229f991901a8a453781","version":"1.43.0","common.platformVersion":"10.0.22621","common.platform":"Windows","common.nodePlatform":"win32","common.nodeArch":"x64","common.product":"azuredatastudio Dev","common.application.name":"Azure Data Studio Dev","quality":"dev",....}}`
`[2023-03-28 17:07:38.716] [095ed29e-2e35-47c0-8c06-8db1b7a7ad3a] [trace] …
> Send telemetry with Auth Library when adding/refreshing account

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/deployDatabaseQuickpick.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
- extensions/sql-database-projects/src/dialogs/publishToDockerQuickpick.ts
- extensions/sql-database-projects/src/models/deploy/deployProfile.ts
- extensions/sql-database-projects/src/models/deploy/deployService.ts
- extensions/sql-database-projects/src/models/deploy/publishSettings.ts
- extensions/sql-database-projects/src/projectProvider/projectProvider.ts
- extensions/sql-database-projects/src/sqldbproj.d.ts
- extensions/sql-database-projects/src/test/deploy/deployService.test.ts
- extensions/sql-database-projects/src/test/dialogs/publishDatabaseDialog.test.ts
Moving these publish interfaces out of sqldbproj.d.ts to remove the need for the imports from `mssql` and `vscode-mssql`, which were causing some difficulties for extensions consuming sqldbproj.d.ts. These publish interfaces were moved into sqldbproj.d.ts last year for another project, but they are no longer being used and don't need to be exposed outside of the extension anymore.
> move publish interfaces out of sqldbproj.d.ts

- extensions/sql-database-projects/src/controllers/projectController.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/22522 and other places in projectController using `path` instead of `fsPath`
> use fsPath instead of path when calculating relative path to sqlproj

- src/sql/workbench/contrib/dashboard/browser/pages/databaseDashboardPage.contribution.ts
- src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.contribution.ts
- src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts
- src/sql/workbench/contrib/notebook/browser/notebook.css
- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
The New Notebook dashboard button got removed in the big BDC cleanup. We were using an mssqlCluster new notebook command before. This change adds a new internal task for opening a new notebook from the dashboard.
This PR fixes #22514
> Add New Notebook task to server and database dashboards.

- extensions/azurecore/src/constants.ts
- extensions/azurecore/src/extension.ts
- extensions/azurecore/src/localizedConstants.ts
Add a warning message upon startup of the AzureCore extension if pii logging enabled:
This PR fixes #22389
> Add warning message when pii logging enabled

- src/sql/workbench/services/objectExplorer/browser/asyncServerTree.ts
Cleaning up restoring expanded state for update children by using existing methods defined for this use case.
> Cleaning update children logic in async server tree

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/common/dataWorkspaceExtension.ts
- extensions/data-workspace/src/common/pathUtilsHelper.ts
- extensions/data-workspace/src/dataworkspace.d.ts
- extensions/data-workspace/src/dialogs/newProjectDialog.ts
- extensions/data-workspace/src/dialogs/newProjectQuickpick.ts
- extensions/data-workspace/src/test/dialogs/pathUtilsHelper.test.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseQuickpick.ts
This PR fixes #22523.
The underlying problem was the filename used for validation was been parsed to remove appended path, but the code was only testing the filename. Hence "/" and "\\" were been removed from validation altogether. This PR updates the code to take the filename and test it directly, instead of using the parsed base name.
The change in validation is valid for project names while creating new project and creating new project from database.
This PR also fixes #22524. Before the changes, the names with "/", "\\" characters were not throwing an error, hence the project was getting created with empty name (and within another folder). After these changes, the code throws error for these characters, hence creation of project with these filenames is suppressed.
Before (incorrect …
> Fix project name validation

- src/sql/workbench/services/objectExplorer/browser/asyncServerTree.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
Expanding a node in the tree using the OE service generates a new treenode object every time. Nonetheless, this is redundant when we re-expand a previously expanded node as the children stay the same. To prevent unnecessary object creation, I am introducing a caching mechanism in the OE service that retrieves nodes from the cache instead of creating new objects.
The caching mechanism is particularly beneficial in async tree since we can reuse the same objects in the tree, eliminating the need for an elaborate process to map new objects to old objects and replace them in the tree.
> Adding caching in OE service

- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
- src/sql/workbench/services/connection/browser/connectionDialogService.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
- src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts
1. Bug 1: fixing connections with forgot password not connecting.
Previously, we encountered a bug when attempting to connect a profile that didn't have a saved password. Our usual workflow involved opening a connection dialog and prompting users to enter their password before connecting to the server. In such cases, the 'onConnectionProfileConnected' event was triggered. However, this created an issue since the connection returned from the connection dialog was completely new, and we couldn't locate it in the tree.
This PR modifies the connection management service. Instead of triggering the 'onConnectionProfileConnected' event, the service now triggers an 'onConnectionProfileEdited' event. This event includes the profile ID of the old connection in the tree and the new connection from …
> Fixing connection without saved password not connecting in Async Server Tree

- src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
Since SlickGrid cannot move to the non existent new row when enter is pressed and therefore cannot trigger the cell submission process, this code will manually call the cell submission process if we press enter on the null row, then move to the newly created row below if successful. Invalid edits have been tested to work. Additionally, empty cells with a blank display value that aren't null are now properly treated as empty null cells (previously they weren't, causing blank spaces to appear after a new row has been added)
Valid edit and refresh afterwards:
Invalid edit and correct one afterwards:
Fixes #19126
> Add fix to enter press on last row of Edit Data.

- src/sql/base/browser/ui/taskbar/media/taskbar.css
- src/sql/workbench/contrib/query/browser/keyboardQueryActions.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
- src/sql/workbench/contrib/query/browser/queryActions.ts
- src/sql/workbench/contrib/query/browser/queryEditor.ts
This PR fixes: #22295
1. Add proper CSS styles to taskbar so that it can handle codicon. 
2. Update the strings used by parse query action.
3. Add `Parse` to query editor toolbar for MSSQL.
4. Add keybindings for Parse Query action.
> update parse query action

- extensions/sql-database-projects/src/models/project.ts
Fixes #22573 by renaming existing backup file with an incrementing counter
> Patching issue where error would be thrown when backup file already exists for sqlproj

- extensions/sql-database-projects/src/models/project.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/22573
> Port fix for erroring when backup file already exists for sqlproj (#22613)

- src/sql/workbench/browser/modelComponents/text.component.ts
- src/sql/workbench/browser/ui/infoBox/infoBox.ts
If the component doesn't have any text it can be hard to figure out where it came from, providing the link as well can help track it down.
Previously: 
` WARN Could not find placeholder text {0} in text `
Now:
`WARN Could not find placeholder text {0} in text ''. Link: {"text":"Known issues, limitations, and troubleshooting","url":"https://aka.ms/dms-migrations-troubleshooting"}`
> Improve missing placeholder warning message

- src/sql/workbench/contrib/query/browser/queryActions.ts
This PR fixes #22637
"Change Connection" -> "Change"
"Export as Notebook" -> "To Notebook"
The original label is now used as tooltip.
> reduce toolbar space

- src/sql/platform/connection/common/connectionProfileGroup.ts
This PR fixes issue #22616 
Whenever a new connection profile was added to a connection group, I used to enforce a parent to ensure that we can easily identify the group to which the connectionProfile's parent belongs, and refresh it when the connection is established. However, this approach had an issue: when a connection was created from the connection dialog, which did not belong to the tree, the connection profile's uri returned to the extension had group as undefined. Despite this, the connection was added to the group in OE, which necessitated assigning a parent to it. This resulted in the version of the connection URI in the extension being different from the version of URI in ads core.
> Removed parent override when adding connection profiles to groups 

- extensions/azurecore/src/account-provider/auths/azureAuthError.ts
- extensions/azurecore/src/account-provider/utils/fileDatabase.ts
- extensions/azurecore/src/azureDataGridProvider.ts
- extensions/azurecore/src/azureResource/providers/cosmosdb/mongo/cosmosDbMongoTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/mysqlFlexibleServer/mysqlFlexibleServerTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/resourceTreeDataProviderBase.ts
- extensions/azurecore/src/azureResource/resourceService.ts
- extensions/azurecore/src/azureResource/services/terminalService.ts
- extensions/azurecore/src/test/account-provider/auths/azureAuth.test.ts
- extensions/azurecore/src/utils/Logger.ts
To help avoid issues like https://github.com/microsoft/azuredatastudio/issues/22606 and https://github.com/microsoft/azuredatastudio/issues/22631 it would be good to be much stricter on the typing we allow. The [no-unsafe-assignment](https://typescript-eslint.io/rules/no-unsafe-assignment/) eslint rule will help with that as it will prevent assigning any `any` var to a variable. 
If the rule had been enabled  then we would have gotten an error here when assigning the body value : https://github.com/microsoft/azuredatastudio/blob/3f882c5d73e6cbcf58f1c3959c26d9200460e7df/extensions/azurecore/src/azureResource/utils.ts#L399
which would have told us that we don't actually know what type the body was when it came in. 
But before enabling it we have to fix up all the existing issues - so this …
> Fix some no unsafe assignment errors in azurecore

- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
Some of the python setup calls will fail if the python executable is in a folder that requires admin access. This was causing installs to get stuck in a halfway state because we weren't clearing the installInProgress flag on error.
This PR fixes #22391
> Add more error handling for python installation

- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/createSqlMigrationService/createSqlMigrationServiceDialog.ts
- extensions/sql-migration/src/dialog/tableMigrationSelection/tableMigrationSelectionDialog.ts
- extensions/sql-migration/src/telemetry.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
- extensions/sql-migration/src/wizard/summaryPage.ts
This PR:
- improves the SQL DB table selection user experience by adding a refresh button, error handling and missing target tables list.  
- adds error handling around loading from previously saved migration states.
New table view loading:
tables loaded w/missing targets
missing tables tab
load table list error:
lots of missing target tables
missing source tables
source and target schema match:
> SQL-Migration: improve SQL DB table selection ux to include missing tables

- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
This PR fixes #22668 
In case of new connections, I am checking if the connection already exists in the group and then replace the connection instead of appending it to the end.
@smartguest can you please verify if the fix works.
> Fixing duplicate connections in Async sever tree

- src/sql/platform/connection/common/connectionConfig.ts
- src/sql/platform/connection/common/connectionProfileGroup.ts
- src/sql/platform/connection/common/connectionStore.ts
- src/sql/platform/connection/common/providerConnectionInfo.ts
- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
- src/sql/workbench/services/connection/browser/connectionController.ts
- src/sql/workbench/services/connection/browser/connectionDialogService.ts
- src/sql/workbench/services/connection/browser/connectionDialogWidget.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
- src/sql/workbench/services/objectExplorer/browser/asyncServerTree.ts
- src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts
Was looking at this and realized we don't need ProviderConnectionInfo or ConnectionProfileGroup to be disposable anymore - the listeners that were originally being registered were removed a while back in https://github.com/microsoft/azuredatastudio/pull/17913
> Remove disposable from connection

- src/sql/workbench/services/accountManagement/browser/accountPicker.ts
- src/sql/workbench/services/accountManagement/browser/accountPickerImpl.ts
- src/sql/workbench/services/accountManagement/browser/accountPickerService.ts
- src/sql/workbench/services/accountManagement/test/browser/accountPickerService.test.ts
- src/sql/workbench/services/resourceProvider/browser/firewallRuleDialog.ts
- src/sql/workbench/services/resourceProvider/browser/firewallRuleDialogController.ts
Pre-select Firewall Dialog Account & Tenant based on details selected by the user in the Connection Dialog.  I noticed the account was not being selected correctly (even though the issue only mentions the tenant behavior) so I have fixed that as well.
Previous Behavior: The first account & tenant in their respective lists were selected.
New Behavior: The account & tenant are matched to the account & tenant selected in the connection dialog page, and pre-selected for the user. 
This PR fixes #22300
> Firewall Dialog Account/Tenant Selection

- build/azure-pipelines/common/publish.js
- build/azure-pipelines/common/publish.ts
Fixes publish issues due to missing endpoint suffix.
Verified connection string from Azure Portal for storage account, validated with local testing.
> Append Endpoint suffix to storage blob connection string

- src/sql/platform/connection/common/connectionConfig.ts
- src/sql/platform/connection/common/providerConnectionInfo.ts
- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
- src/sql/workbench/services/connection/test/browser/connectionManagementService.test.ts
- src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts
This PR addresses the connection titles not updating for the async server tree, and also removes the dispose function for the connection profile since it's no longer needed. 
Additionally I am unable to reproduce the SQL Migration bug with a built version of my STS branch, so I assume that's an issue only with the debug version.
> Added changes and fixes for feat/connectionuri

- extensions/data-workspace/src/services/workspaceService.ts
This PR fixes #22517.
Example of a workspace where two of the workspace folders include the same project:
before:
fixed:
> fix project listed twice when using multi root workspaces

- extensions/mssql/src/baseService.ts
- extensions/mssql/src/contracts.ts
- extensions/mssql/src/dacfx/dacFxService.ts
- extensions/mssql/src/schemaCompare/schemaCompareService.ts
- extensions/mssql/src/sqlProjects/sqlProjectsService.ts
Expanding the helper method that's already being used for `sqlProjectService` to `dacFxService` and `schemaCompareService`, just to test the waters a little more with extensions I'm more familiar with.  Once this is in, I'll convert the remaining services.
> Changing dacFxService and schemaCompareService to use shared logic for error handling

- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts
- extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts
`onDidClick()` for radio buttons was deprecated a while ago, so this updates the places in sql projects that were still using it to to use `onDidChangeCheckedState()` instead.
> replace deprecated onDidClick() handler in sql projects

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/utils/fileEncryptionHelper.ts
- extensions/azurecore/src/account-provider/utils/msalCachePlugin.ts
Fixes #22716 that may occur if IV/KEY is corrupted due to any reason.
The best action here is to reset IV/KEY combination to allow resetting cache.
Fix verified with log:
```log
[Verbose]: Initialized Azure account extension storage. - []
[Verbose]: FileEncryptionHelper: Fired encryption keys updated event. - []
[Verbose]: Initializing stored accounts [] - []
[Information]: [Fri, 14 Apr 2023 17:21:04 GMT] : @azure/msal-node@1.16.0 : Info - getTokenCache called - []
[Verbose]: [Fri, 14 Apr 2023 17:21:04 GMT] : @azure/msal-node@1.16.0 : Trace - getAllAccounts called - []
[Error]: FileEncryptionHelper: Error occurred when decrypting data, IV/KEY will be reset: Error: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH - []
[Information]: FileEncryptionHelper: …
```
> Reset IV/Key if MSAL cache file decryption fails

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/auths/httpClient.ts
- extensions/azurecore/src/account-provider/auths/networkUtils.ts
- extensions/azurecore/src/azureResource/utils.ts
- extensions/azurecore/src/utils/Logger.ts
Continuing cleanup to fix no-unsafe-assignment issues in azurecore. Should be pretty straightforward - but I did add another helper function for parsing PromptFailedResults to consolidate logic and refactored the NetworkUtils module to just have the helper functions be exported directly.
> More azurecore cleanup

- src/sql/platform/connection/common/constants.ts
- src/sql/workbench/services/notebook/browser/interfaces.ts
- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
- src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts
This PR fixes #21472 
Noticed that all 3 providers are registered for 'sql' kernel when creating new notebook connection, but are not available when reloading ADS with an opened notebook and trying to connect, as explained in the linked issue.
> Register mysql, pgsql with mssql as default 'sql' kernel providers

- extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
After the record to map swap in https://github.com/microsoft/azuredatastudio/pull/22758, the sqlcmd table in the publish dialog no longer was showing as expected.
before: 
fixed:
> fix sqlcmd table var table in publish dialog

- src/sql/workbench/browser/modal/modal.ts
This PR fixes #22777
introduced in https://github.com/microsoft/azuredatastudio/pull/22743.
the fix is to only reset the focus if the message area was previously not visible.
> fix error message steal focus issue

- extensionsGallery-insider.json
This PR updates the insiders extension gallery to the latest version of the SQL Migration extension.
Very recently we released v1.4.3 to Insiders, however that build still contained changes from https://github.com/microsoft/azuredatastudio/pull/22525, meaning it was not backwards compatible across both stable and Insiders ADS. Since this was recently reverted in https://github.com/microsoft/azuredatastudio/pull/22761, this means that v1.4.3 will no longer work in insiders ADS. 
With the latest changes pulled in, our updated vsix now works on both insiders and stable ADS.
Link to `Azure Data Studio - Extensions` pipeline run off main containing vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=197623&view=results
> [SQL Migration] Release v1.4.4 to Insiders

- extensions/sql-database-projects/src/common/constants.ts
Updating the string to make it more clear that it's the default value of the SQLCMD variable that will get updated
> change value to default value in edit sqlcmd variable prompt

- product.json
These APIs are required to enabled embedded suggestions in the editor.  Otherwise, only the Copilot suggestion document scenario is working.
> Enable proposed APIs for copilot

- extensions/data-workspace/src/common/constants.ts
- extensions/data-workspace/src/dialogs/openExistingDialog.ts
This addresses the last of the many issues in #22127, "Open existing Project - Location : Voiceover is not announcing as required for location radio group". Because it's a radio button, it doesn't need the required attribute since one of them is always selected. I added a title to the project file input box and made that required since that needs to be filled out.
open dialog before:
open dialog after:
open dialog git repo option (not changed):
gif showing voiceover announcing required for the project location input box:
> fix accessibility issue for open dialog location radio button

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts
- extensions/azurecore/src/account-provider/auths/httpClient.ts
Couple simple fixes, mostly just disabling the warning for stuff that's going to go away before too long. Doing these in smaller chunks to make them easier to review.
> Few more no-unsafe-assignment cleanups

- extensions/azurecore/src/account-provider/auths/httpClient.ts
- extensions/azurecore/src/azureResource/utils.ts
This fixes an no-unsafe-assignment issue on line 403 of utils.ts. The incoming body is typed as `any`, but we're assigning it to NetworkRequestOptions which expects it to be `string | undefined`. @cssuh originally fixed this by having the HttpClient handle stringifying it, but that's unnecessary in most cases since the makeHttpRequest function is the only place that we're passing in something that isn't already a string.
I'd like to remove the `any` from the body parameter too - but unfortunately we expose that in the azurecore API which is used heavily by the sql-migration extension. So to avoid breaking them like we did recently (because of mismatched ADS/extension versions) we'll just leave it as any for now and then just make sure we handle the any appropriately later on.
> Move stringifying of request body for azure REST calls

- extensions/azurecore/src/account-provider/auths/httpClient.ts
- extensions/azurecore/src/account-provider/auths/networkUtils.ts
- extensions/azurecore/src/azureResource/utils.ts
- extensions/azurecore/src/azurecore.d.ts
- extensions/azurecore/src/extension.ts
- extensions/machine-learning/src/test/stubs.ts
- extensions/sql-migration/src/api/azure.ts
More work towards enabling no-unsafe-assignments, going through and adding typings to all our HTTP calls. Had to move some stuff around and did some cleanup of things but there shouldn't be any functional changes here.
I briefly looking around to see if these ARM response types were declared in any of their stuff we pull in, but it doesn't look like it (or they're in a different package). I might go poking around for a typings package with these later - but that's not super important right now.
SQL Migration folks - I mostly left your stuff alone. It would probably be a good exercise for you to take a look at these calls and decide whether you care to try and handle the cases where we don't get a response. It's hard to imagine that being a normal scenario - but for better or worse we've …
> Add azurecore HTTP typings

- extensions/sql-bindings/src/test/testUtils.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/models/connections/connectionService.ts
- extensions/sql-database-projects/src/test/deploy/azureSqlClient.test.ts
- extensions/sql-database-projects/src/test/dialogs/testUtils.ts
- extensions/types/vscode-mssql.d.ts
Originally I was just going to make the same changes that were made in https://github.com/microsoft/vscode-mssql/pull/17657, but noticed there were several other differences. These files are supposed to stay in sync, so this updates the vscode-mssql.d.ts file in ADS to match the current state of the file in the vscode-mssql repo (pending a small sql projects `NoneItems` change that needs to be added in https://github.com/microsoft/vscode-mssql/pull/17659).
> Update vscode-mssql.d.ts to match what's in the vscode-mssql repo

- .eslintignore
- extensions/azurecore/.eslintrc.json
- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/auths/httpClient.ts
- extensions/azurecore/src/azureResource/utils.ts
Finished the last few of these. The error responses seem like something we should build into all the Azure REST calls...I'm assuming that's a possible response from any of these. But that's out of the scope of this work here.
I did disable the check for the header conversion stuff - I have no idea what's going on with that so I just opened an issue to look into this (which I would recommend doing since right now this could easily cause something to break at runtime if a header is converted into an object unexpectedly...) https://github.com/microsoft/azuredatastudio/issues/22835
> Finish up no-unsafe-assignment fixes in azurecore

- src/sql/workbench/services/connection/browser/connectionWidget.ts
Fixes a minor edge case that happens when switching accounts - if the selected account has single tenant, the dropdown doesn't get updated with new tenant and connection leads to an error as the selected tenant still points to previously selected tenant from last account selection.
> Fix resetting tenant values when dropdown is not visible

- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceQuickpick.ts
I noticed add db ref telemetry was only getting sent in ADS, but not in vscode.
> add telemetry for add database reference quickpick

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/azureResource/utils.ts
- extensions/azurecore/src/azurecore.d.ts
These were broken in https://github.com/microsoft/azuredatastudio/pull/22828 - I wrapped the results one too many times which ended up causing an error to be thrown when making some API calls. Unfortunately, this kind of thing is hard to catch with just static analysis since we're doing all our own custom requests - so if a mistake like this gets in then it won't show up until runtime. 
I went through and verified all the public API calls seem to be working correctly after this fix so we should be good now, and going forward this should be avoided by making sure to properly test new calls as they're added.
> Fix Azure rest calls not working

- src/vs/editor/browser/widget/diffEditorWidget.ts
Fixes #22850. After the latest merge, the schema compare diff colors weren't swapped like they're supposed to be because the `reverse` parameter wasn't getting passed in. 
before:
after:
> fix schema compare diff editor colors not being reversed after merge

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/constants.ts
Adds support for AADSTS70043 and AADSTS50173 error codes, to prompt user to add account again:
**AADSTS70043**: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on {issueDate} and the maximum allowed lifetime for this request is {time}.
**AADSTS50173**: FreshTokenNeeded - The provided grant has expired due to it being revoked, and a fresh auth token is needed. Either an admin or a user revoked the tokens for this user, causing subsequent token refreshes to fail and require reauthentication. Have the user sign in again.
Addresses #22844 and #22624 
// TODO later (tracked internally): Investigate more error codes from doc: https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes that …
> Prompt user to refresh account credentials

- extensions/sql-database-projects/src/test/testUtils.ts
Fix build errors introduced by https://github.com/microsoft/azuredatastudio/pull/22847 for unused imports.
> fix build errors introduced by sql projects test file

- src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
- src/sql/workbench/services/objectExplorer/browser/serverTreeRenderer.ts
- src/sql/workbench/services/objectExplorer/common/treeNode.ts
Adding filtering support to OE service. This PR mainly adds caching filters in the OE service and adds the filtered suffix to the node rendered so that we see a filtered sign.
> Adding filtering to OE Service

- src/sql/workbench/browser/modelComponents/infoBox.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/22628
Turns out we were setting the links first, which triggered the check and warning to be displayed since the text hadn't been set.
> Fix missing placeholder warning for infoboxes

- src/vs/workbench/contrib/extensions/browser/extensionEditor.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/22901
Fixes https://github.com/microsoft/azuredatastudio/issues/22902
Removes broken publisher link (we don't have anything useful to link to for publishers since we don't have a public UI for the gallery) and fixes the License link not showing up. 
With fixes : 
Extension without license (only a couple of those)
> Remove publisher link and fix license link

- src/sql/workbench/services/connection/browser/connectionWidget.ts
Minor change to only select account when found.
Addresses below error in log:
`[renderer1] [error] Unexpected error populating initial Azure Account options : TypeError: Cannot read properties of undefined (reading 'key')`
> Handle no matching account scenario

- .vscode/launch.json
- src/sql/workbench/api/browser/mainThreadConnectionManagement.ts
- src/sql/workbench/browser/actions.ts
- src/sql/workbench/contrib/commandLine/electron-browser/commandLine.ts
- src/sql/workbench/contrib/commandLine/test/electron-browser/commandLine.test.ts
- src/sql/workbench/contrib/connection/browser/connection.contribution.ts
- src/sql/workbench/contrib/dashboard/browser/dashboardActions.ts
- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
- src/sql/workbench/contrib/objectExplorer/test/browser/connectionTreeActions.test.ts
- src/sql/workbench/contrib/profiler/browser/profilerActions.ts
- src/sql/workbench/services/connection/browser/connectionDialogService.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
- src/sql/workbench/services/objectExplorer/browser/connectionTreeAction.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts
- src/sql/workbench/services/objectExplorer/browser/treeSelectionHandler.ts
- src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/22869
`ShowDashboard` should be not enabled by default for any connection type, as it fails its purpose if connection type is not defined. This PR enables 'showDashboard' where it should be visible, and retains the public API promise to not show dashboard unless specified.
> Respect 'showDashboard' disabled by default

- .vscode/launch.json
Adds launch configuration "Attach to VS Code" for test run/debug support with "[VS Code Selfhost test provider](https://github.com/microsoft/vscode-selfhost-test-provider)" extension.
> Add launch config for VS Code selfhost test provider

- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts
This PR fixes #22923  (and #20363).
Two problems fixed in this PR:
1. In a prior PR (https://github.com/microsoft/azuredatastudio/pull/20607), target platform was getting incorrectly set (just considers the vscode version, and doesn't read the ADS version of the enum values used). Updated assignment in this one.
2. Target platform wasn't getting set in the Schema Compare object that was been sent from Update database from projects codeflow. Because of this, the code was using the default target platform of 160 (Sql Server 2022), hence the comparison failed. Assignment added in this PR.
Tested scenarios:
- Create project from database sets correct target platform for Azure and DW databases.
- Update project from database and Schema comparison workflows complete successfully for Azure …
> Fix schema comparison failure for Azure synapse dedicated pool

- samples/sp_whoIsActive/package.json
Since this doesn't match the typings we import the VSCE tool complains when we try to package it up. This engine version isn't actually necessary so just removing it.
> Remove vs code engine version for whoisactive extension

- build/azure-pipelines/linux/sql-product-build-linux.yml
Until #22935 is addressed, publish tasks are disabled.
> Disable publishing crash reports temporarily

- extensions/mssql/package.json
This PR fixes #22866
I accidentally added rename support for database but missed adding it to STS side, since @corivera has already started working on full feature support (create/update/rename/delete) for database object type, I am going to remove it and let Cory handle it when it is ready.
> remove the rename db context menu

- src/sql/base/browser/ui/label/label.ts
- src/sql/base/browser/ui/label/media/label.css
- src/sql/workbench/browser/modelComponents/text.component.ts
- src/sql/workbench/services/serverGroup/browser/serverGroupDialog.ts
PR for #22658
1. Add required indicator for server group name in the server group dialog
2. refactor the existing code to use the same style.
Before
example of the text component.
After
> add required indicator for server group name

- src/sql/workbench/contrib/objectExplorer/common/serverGroup.contribution.ts
- src/sql/workbench/services/objectExplorer/browser/asyncServerTree.ts
- src/sql/workbench/services/objectExplorer/browser/asyncServerTreeDataSource.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
- src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts
- src/sql/workbench/services/objectExplorer/test/browser/objectExplorerService.test.ts
1. This removes the OE timeout from various async server tree performances. Fixes #22737 and #22801 
2. Previously, Async server tree used to show its own error dialog in case of connection issues, Now, I am avoiding that and let connection service handle and show error dialogs in case of connection issues. Attempts to fix #22798 and fix #22917 
3. Previously, in the case of expansion where there was only one expansion provider, the tree used to not return the error nodes message indicating the exact error that had occured. That's why the user only "failed to expand node" Fixes #22801
> Fixing async server tree error handling and removing timeout. 

- extensions/mssql/package.json
Noticed these - and while the errors don't seem to actually matter for some reason the reason they're outlined makes sense (we should be escaping the backslash so that it reduces down to just a single backslash for the regex). And then I'm also closing out the regex properly with a /.
I believe the backslashes work currently because `\/` isn't a valid escape sequence so it just ignores it and leaves it in.
Menus after fix:
Table columns:
View columns:
> Fix validation errors in package.json when clause

- src/sql/base/browser/ui/panel/panel.component.ts
For #22694 
followed the example of vscode to differentiate the selected vs focused item by using dashed and solid outline style.
VSCode
High Contrast Light
High Contrast Dark
Dark Theme - No Change
Light Theme - No Change
> fix tab style in hc mode

- src/sql/workbench/browser/modal/dialogHelper.ts
- src/sql/workbench/browser/modal/optionsDialog.ts
- src/sql/workbench/services/connection/browser/connectionWidget.ts
Introduced by this PR https://github.com/microsoft/azuredatastudio/pull/22971, The class name is used in other places, caused duplicate required indicators. I've check and made sure no other places are using the class name.
Before:
After:
> fix duplicate required indicator

- extensions/mssql/src/objectManagement/commands.ts
- extensions/mssql/src/objectManagement/localizedConstants.ts
- extensions/mssql/src/objectManagement/ui/applicationRoleDialog.ts
- extensions/mssql/src/objectManagement/ui/databaseRoleDialog.ts
- extensions/mssql/src/objectManagement/ui/findObjectDialog.ts
- extensions/mssql/src/objectManagement/ui/loginDialog.ts
- extensions/mssql/src/objectManagement/ui/objectManagementDialogBase.ts
- extensions/mssql/src/objectManagement/ui/serverRoleDialog.ts
- extensions/mssql/src/objectManagement/ui/userDialog.ts
- extensions/mssql/src/objectManagement/utils.ts
- extensions/mssql/src/ui/dialogBase.ts
- extensions/mssql/src/ui/localizedConstants.ts
- extensions/mssql/src/ui/scriptableDialogBase.ts
- extensions/mssql/src/util/objects.ts
For Backup/Restore I want to reuse the script logic being used for Object Management, so I'm splitting it out into a separate `ScriptableDialogBase` class - which the OM stuff then extends itself. 
I did a few minor cleanup - renaming stuff and adding comments - while I was here too. 
Example showing create login dialog after changes - I didn't go through all the dialogs but if anything was broken I would expect it to be broken for everything (since nearly all the changes were in the base classes)
> Create separate ScriptableDialogBase

- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseQuickpick.ts
This PR fixes #22995.
The first option in the showQuickPick becomes the default value. So updating the folder structure default by resequencing "Schema/Object Type" to the top.
Before:
After:
> Update default folder structure option in VSCode

- src/sql/base/browser/ui/fieldset/fieldset.ts
- src/sql/base/browser/ui/fieldset/media/fieldset.css
- src/sql/workbench/browser/modal/media/modal.css
- src/sql/workbench/browser/modal/modal.ts
- src/sql/workbench/services/connection/browser/connectionDialogWidget.ts
- src/sql/workbench/services/connection/browser/connectionWidget.ts
For #22680
1. Introduce the [fieldset](https://www.w3schools.com/tags/tag_fieldset.asp) component and use it to group controls so that screen readers can properly announce the group of an element. (only when navigating into a group either by keyboard or mouse click).
2. add a form tag to the modal dialog in order to make the fieldset work. all dialogs/wizards where we might need to use fieldset are covered by this.
3. while at this dialog, I also added label for input type and grouped the radio buttons with fieldset.
No visual changes introduced by the fieldset and form.
> introduce fieldset component

- build/actions/api/octokit.js
- build/actions/api/testbed.js
- build/actions/auto-labeler/index.js
- build/actions/utils/utils.js
It seems port labeler runs on 'main' branch (affecting multiple port PRs), I'm rebuilding actions folder from it's root to resolve errors, as compiling from build\ leads to different output. Need to investigate later why compilation results in different output for both folders.
Opened issue #23050 to track improvements to build\actions code.
> Reverting changes to actions folder

- src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts
Fixes #23047
Port request for a VS Code security bug fix that notifies a user before rerunning a command.
> Use notification prompt before running a command (#23035)

- extensions/data-workspace/src/common/workspaceTreeDataProvider.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/22989. I didn't add `application/vnd.code.tree.workspacetreedataprovider` to the `dragMimeTypes` originally because the doc comments say it's automatically added and it was working as expected, but adding it now since it's causing a warning in the console. 
https://github.com/microsoft/azuredatastudio/blob/e7d3d047ec5ac8bdade3d40ea5ab0b0a085c1f1a/src/vscode-dts/vscode.d.ts#L10223-L10229
> fix warning in console when drag and dropping in sql projects

- extensionsGallery-insider.json
- extensionsGallery.json
This brings the copilot extension into RC1 gallery for next release.
The insider changes aren't strictly necessary, but were just brought along with the merge (and don't hurt to have)
> Sync RC1 gallery with main

- src/sql/base/browser/ui/table/media/table.css
- src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
For #22655 
Updated the code to make sure the menu can fit on the screen.
Scenario: Small window size
Before
After:
Scenario: Normal window size
Before
After:
> fix the filter plugin menu size and location issue

- src/sql/azdata.proposed.d.ts
- src/sql/platform/telemetry/common/telemetryKeys.ts
- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
- src/sql/workbench/contrib/objectExplorer/test/browser/serverTreeView.test.ts
- src/sql/workbench/services/objectExplorer/browser/connectionTreeAction.ts
Adding telemetry to ads oe filtering
Sample event:
```js
{
filterCount: 2
filterPropertyNames: "[\"Name\",\"Create Date\"]"
objectType: "Databases"
}
```
> Adding telemetry to ads OE filter

- extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts
This addresses https://github.com/microsoft/vscode-mssql/issues/17682. This was caused by the Record to Map swap in https://github.com/microsoft/azuredatastudio/pull/22758. 
https://github.com/microsoft/vscode-mssql/pull/17683 was only part of the fix, but these other changes had to be made for this to functionally work as expected. Generate script was failing with the error `object is not iterable (cannot read property Symbol(Symbol.iterator))` when trying to convert the sqlcmd variables [here](https://github.com/microsoft/vscode-mssql/blob/0c2b2ed75710e326bdf0d9356f78f12b0308b1e8/src/services/dacFxService.ts#L114) because the quickpick wasn't passing it the object it expected.
before (generate script broken):
Project w/sqlcmd variables:
Project w/o sqlcmd variables:
> fix sqlcmd variables not getting loaded correctly in vscode

- extensions/markdown-language-features/package.json
- src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts
For https://github.com/microsoft/azuredatastudio/issues/23100
The workbench file path was changed from electron-browser to electron-sandbox. Also, I noticed that some of the markdown links in preview mode were not working properly and saw these errors in console:
Adding the notebookEditor fixed the issue.
> Update workbench file and fix relative link not working in markdown

- src/sql/platform/connection/common/connectionConfig.ts
- src/sql/platform/connection/common/connectionProfile.ts
- src/sql/platform/connection/common/connectionStore.ts
- src/sql/platform/connection/common/providerConnectionInfo.ts
- src/sql/platform/connection/test/common/connectionConfig.test.ts
- src/sql/platform/connection/test/common/providerConnectionInfo.test.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
- src/sql/workbench/services/connection/test/browser/connectionManagementService.test.ts
In reverting the PR for the connection string, I found out that a separate fix for the duplicate edit issue (https://github.com/microsoft/azuredatastudio/issues/21939), was reverted as well. Since this feature does not rely on the connection string property being of the new kind and can work with the old format, I have brought it back with some adjustments to better fit the current profile id and since it's an existing issue not brought up by my change:
> Added back fix for duplicate edits

- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
Adding back the check to async server tree that ignores disconnections from other areas of ads. 
This PR fixes #22686, fixes #22709, fixes #23074
> Fixing OE disconnecting connections when other types of connections are disconnected

- src/sql/platform/capabilities/test/common/testCapabilitiesService.ts
- src/sql/platform/connection/common/providerConnectionInfo.ts
- src/sql/workbench/contrib/commandLine/electron-browser/commandLine.ts
- src/sql/workbench/contrib/commandLine/test/electron-browser/commandLine.test.ts
Addresses #23081 
This came as an internal request from Cosmos DB team.
With this PR, Command Line Arguments will support passing advanced connection properties in JSON format: `{"key1":"value1","key2":"value2",...}` pairs to be able to pass these to respective provider.
e.g. `azuredatastudio://connect?server=*****&user=*****&authenticationType=*****&connectionProperties={"key1":"value1"}`
or `azuredatastudio --server localhost --provider mssql --user sa --connectionProperties '{"key1":"value1"}'`
cc @languy @sevoku
> Support advanced options in command line arguments

- extensionsGallery-insider.json
This PR updates the insiders extension gallery to the latest version 1.4.5 of the SQL Migration extension.  sql-migration-1.4.5.vsix
Link to Azure Data Studio - Product Build (nightly) pipeline run off main 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=199880&view=artifacts&pathAsName=false&type=publishedArtifacts
-> sql-migration-1.4.5.vsix
> [SQL Migration] Release v1.4.5 to Insiders

- extensionsGallery-insider.json
- extensionsGallery.json
- scripts/validateGalleries.js
Going forward we'll require that extensions not only have a license file linked in their metadata, but that the README also contains a license section. Adding the check for that now - with a number of 3rd party extensions that currently don't have this added to a skip list since we don't control those.
Currently there's still a number of 1st party extensions that need to be fixed - will keep this PR open until they can be addressed.
@dzsquared For the ones that you own, are you planning on keeping those around? We can help with getting them updated if so, just want to make sure we couldn't just remove them if they aren't useful anymore.
> Add check for extension READMEs to have license header

- scripts/validateGalleries.js
These have been updated with the new content so no longer need to be skipped
> Remove skipped license checks in validate galleries check

- extensions/mssql/config.json
This PR fixes https://github.com/microsoft/azuredatastudio/issues/23143
STS PR to main: https://github.com/microsoft/sqltoolsservice/pull/2068
STS Port PR: https://github.com/microsoft/sqltoolsservice/pull/2069
Change since last STS version: https://github.com/microsoft/sqltoolsservice/compare/4.7.1.3...4.7.1.4 The above PR is the only change got in.
I've verified the fix with this STS build.
> Port fix for db role member in user management

- extensions/sql-bindings/package.json
- extensions/sql-bindings/src/services/azureFunctionsService.ts
Addresses https://github.com/microsoft/azuredatastudio/issues/23156 as we should update `targetFramework` and `version` used when creating the azure function.
> Update SQL Bindings VSCode target framework and version, and vbump

- extensions/mssql/src/ui/dialogBase.ts
Noticed a few small things while working on some other stuff: 
1. Unnecessary await on registerContent
2. removeHandler wasn't defined as returning a Promise but was having await called on it. It makes sense for it to return a Promise for callers to implement async handlers so just fixing the parameter typing
> Cleanup mssql dialog base

- src/sql/workbench/browser/modal/modal.ts
- src/sql/workbench/contrib/backup/browser/backupUiService.ts
- src/sql/workbench/services/restore/browser/restoreServiceImpl.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/23158
For non-MSSQL backups/restores we were storing the dialog instances on a per-provider basis but then never updating the title, which meant it would always have the title of the first dialog opened. 
This doesn't affect MSSQL backup/restores since it sets the title when the dialog is opened.
> Fix backup/restore dialog titles not updating

- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseQuickpick.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/23057
https://github.com/microsoft/vscode-mssql/pull/17676 already fixed the error showing up in the console, but that should be preempted by the sqlproj extension before it calls into the mssql.
> Validating connectionProfile for missing server before attempting to connect

- src/sql/workbench/contrib/table/browser/table.contribution.ts
this PR fixes #12822
and https://msdata.visualstudio.com/Data%20Studio/_workitems/edit/1654903
add a keyboard shortcut to sort the columns. the default binding is SHIFT+ALT+O
> sort table by keyboard

- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
Previously (error nodes looked like the parent node). 
Now:
Double clicking the node will open the error message in an error dialog
> Fixing OE nodes error handling.

- extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts
- extensions/sql-database-projects/src/test/dialogs/updateProjectFromDatabaseDialog.test.ts
- extensions/sql-database-projects/src/test/testContext.ts
This PR fixes #23160.
When a user tries to update project from database, it populates various parameters to get the target project information. But in the scenario where the Update Project UI doesn't start from the project context, the code never pulled the project details. After https://github.com/microsoft/azuredatastudio/pull/22938 change went in, the code looked up for version information of the project. For the scenario where Update project was started from db context (non-project context), it didn't have the project information, and the code was failed. This PR fixes it by opening project from the chosen project filepath, before accessing the project information.
> Populate Project in Update project from db UI

- extensions/data-workspace/src/services/workspaceService.ts
- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/package.nls.json
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/mainController.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/models/tree/databaseReferencesTreeItem.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/23170
I thought ADS used to cascade opening referenced projects, but it appears SSDT doesn't either.  Instead of opening the full tree of project references automatically, I opted to add a hook to open referenced projects in ADS.
https://github.com/microsoft/azuredatastudio/assets/1609827/49e20d03-a405-4ba7-983a-0f38bf0142a7
> Adding option to open referenced project from SQL Project reference item

- build/azure-pipelines/darwin/sql-product-build-darwin.yml
- build/azure-pipelines/linux/sql-product-build-linux.yml
- extensions/sql-database-projects/src/test/projectController.test.ts
After the vscode merge that happened with PR https://github.com/microsoft/azuredatastudio/pull/22780 following changes can be seen:
- Darwin: Core integration tests aren't running 
- Linux: Extension unit tests aren't running
This PR adds them back to pipeline.
> Update product pipelines to add back tests

- src/sql/workbench/contrib/query/browser/gridPanel.ts
a bug introduced in this PR: https://github.com/microsoft/azuredatastudio/pull/23206 yesterday.
before
after
> fix missing actions issue

- extensions/mssql/src/objectManagement/localizedConstants.ts
- extensions/mssql/src/objectManagement/ui/databaseRoleDialog.ts
- extensions/mssql/src/objectManagement/ui/findObjectDialog.ts
- extensions/mssql/src/objectManagement/ui/serverRoleDialog.ts
Issue: In the following scenarios, the type is displayed with underlying type name instead of display name:
1. Add Server Role Member
2. Browse database role owner
3. Add database role member
Fix:
Enforce the full object type so that the Find Object Dialog doesn't need to handle special cases.
Before
After
> fix find object dialog type display name issue

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/23135 to allow adding sqlcmd variables without a DefaultValue using through the projects add sqlcmd variable quickpick.
> Allow adding new sqlcmd variables to sql project without DefaultValue

- extensions/mssql/src/mssql.d.ts
- extensions/mssql/src/objectManagement/localizedConstants.ts
- extensions/mssql/src/objectManagement/ui/applicationRoleDialog.ts
- extensions/mssql/src/objectManagement/ui/databaseRoleDialog.ts
- extensions/mssql/src/objectManagement/ui/findObjectDialog.ts
- extensions/mssql/src/objectManagement/ui/loginDialog.ts
- extensions/mssql/src/objectManagement/ui/objectSelectionMethodDialog.ts
- extensions/mssql/src/objectManagement/ui/principalDialogBase.ts
- extensions/mssql/src/objectManagement/ui/serverRoleDialog.ts
- extensions/mssql/src/objectManagement/ui/userDialog.ts
- extensions/mssql/src/ui/dialogBase.ts
- extensions/mssql/src/ui/scriptableDialogBase.ts
- src/sql/workbench/browser/modelComponents/groupContainer.component.ts
- src/sql/workbench/browser/modelComponents/media/groupLayout.css
1. New dialog to add database level serurables.
2. Add search text field to the FindObjects dialog.
3. This PR fixes #23240
specific objects
all objects of certain types
all objects of a schema
> add objects dialog

- src/vs/workbench/contrib/quickaccess/browser/viewQuickAccess.ts
Remove the debugService dependency from the Open View command handler to address issue https://github.com/microsoft/azuredatastudio/issues/23236.
> Remove debugService dependency from Open View

- src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
- src/sql/workbench/contrib/query/browser/actions.ts
- src/sql/workbench/services/query/common/gridDataProvider.ts
- src/sql/workbench/services/query/common/queryRunner.ts
Fixing #21570 
Some of the code was accidentally removed by my light theme PR. This just brings it back
> Fixing copy headers in results grid

- src/sql/workbench/contrib/query/browser/messagePanel.ts
For issue: #22673
Add the timestamp information to the aria label when it is available.
the screen capture below shows how NVDA reads it.
> fix aria label for message items

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/azureAccountProvider.ts
- extensions/azurecore/src/account-provider/utils/msalCachePlugin.ts
Addresses #23286 
When reading from local/MSAL cache, if decryption fails we currently were only resetting current cache file, and not the other. This leads to other cache file causing malfunctions and unwanted errors when due to any reason IV/KEY encryption keys go bad (edge case scenario). The changes make sure both cache files are cleared in such an event and users are able to transparently reconnect.
> Delete both cache files on decryption failure

- src/sql/workbench/contrib/objectExplorer/browser/media/serverTreeActions.css
This PR fixes #22941 
Now:
Before:
> Fixing add server group icon when azure viewlet is disabled. 

- extensions/sql-database-projects/package.json
Fixing https://github.com/microsoft/azuredatastudio/issues/23308
Before:
After:
> Fixing issue where "delete" would also show up for database reference root node

- src/sql/base/browser/ui/table/formatters.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
this PR fixes #304
1. When inspecting the cells, I realized that the aria-label has the full value which is adding a lot of content to the DOM tree.
2. Refactor the formatter method
before
after
> handle long text cells

- src/sql/workbench/contrib/query/browser/actions.ts
this PR fixes #2830
Handle the scenario when the rows or columns are more than the Excel limits. This is added in ADS core for the following purposes:
1. It can fail fast.
2. All database providers can benefit from it.
> handle Excel limits

- src/sql/workbench/contrib/query/browser/queryActions.ts
- src/sql/workbench/services/connection/browser/connectionManagementService.ts
A few code improvements to handle below errors in logs when user 'Cancel's a connection attempt:
```
ERR Cannot read properties of undefined (reading 'connectHandler'): TypeError: Cannot read properties of undefined (reading 'connectHandler')
at vscode-file://vscode-app/c:/Users/cmalhotra/Code/GitHub/azuredatastudio/out/sql/workbench/services/connection/browser/connectionManagementService.js:1099:46
```
```
ERR Cannot read properties of undefined (reading 'connectHandler'): TypeError: Cannot read properties of undefined (reading 'connectHandler')
at wa.tryAddActiveConnection (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2710:34986)
at vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app …
```
> Handle error cases properly

- src/sql/workbench/contrib/commandLine/electron-browser/commandLine.ts
- src/sql/workbench/contrib/commandLine/test/electron-browser/commandLine.test.ts
- src/vs/platform/environment/common/argv.ts
- src/vs/platform/environment/node/argv.ts
While investigating #23267 I figured out that native execution of command line arguments wasn't working for most options (mostly newer ones I guess?), as they seem to only work when `NativeParsedArgs` contained those options, which hadn't been updated in a while.
e.g. run `azuredatastudio --server localhost --integrated --showDashboard` (_showDashboard_ is not supported and doesn't work, similarly _authenticationType_ and all the options fixed with this PR were missing support in native command line).
The `SqlArgs` type and tests have been misleading and native command line support had been missing most options due to this reason. This PR drops SqlArgs type as it contains simply duplicated properties and adds no value and fixes `NativeParsedArgs` to include all options that are supported, …
> Fix broken native command line argument support

- extensions/mssql/config.json
- extensions/mssql/src/objectManagement/ui/databaseDialog.ts
Previously we were using "<default>" for those fields to match SSMS, but after some team discussion we decided having actual values in those fields was better. These changes mostly come SQL Tools Service.
SQL Tools changes in this version bump:
> Update default values for Owner and Collation in Create Database dialog

- extensions/azurecore/src/azureResource/constants.ts
- extensions/azurecore/src/azureResource/interfaces.ts
- extensions/azurecore/src/azureResource/providers/cosmosdb/mongo/cosmosDbMongoService.ts
- extensions/azurecore/src/azureResource/providers/cosmosdb/mongo/cosmosDbMongoTreeDataProvider.ts
- extensions/azurecore/src/azureResource/providers/queryStringConstants.ts
- extensions/azurecore/src/azureResource/providers/universal/universalService.ts
- extensions/azurecore/src/azurecore.d.ts
- src/sql/workbench/services/connection/browser/connectionWidget.ts
This PR adds support for Cosmos DB Mongo vCore in `azurecore`. The cluster will now be properly listed in the Azure browser and the connection settings will be set accordingly. However connecting to a cluster needs a new Cosmos DB extension with https://github.com/Azure/azure-cosmosdb-ads-extension/pull/69.
> Initial support for MongoDB clusters / vCore

- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
During performance data collection for SKU recommendation in the SQL Migration extension, the source instance is periodically (default: every 30 seconds, but configurable) queried, but if that fails for whatever reason (e.g. source instance is temporarily unavailable, etc.) then an error event is emitted (`RefreshDataCollectionFailed`). However, this event is quite noisy and can be removed, considering:
- any errors during data collection are shown to the user as a toast in ADS anyways, so having them in telemetry doesn't really help
- data collection is a long running ongoing process, so there isn't a need to potentially constantly re-emit the same errors over and over
- we still have separate telemetry/error events for actually generating the recommendations (e.g. …
> [SQL Migration] Remove noisy telemetry error event

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts
- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceQuickpick.ts
- extensions/sql-database-projects/src/test/dialogs/addDatabaseReferenceDialog.test.ts
Changing the name of `ReferenceType` to `ReferenceDatabaseType` so that https://github.com/microsoft/azuredatastudio/pull/23309 can use `ReferenceType` for distinguishing between `ArtifactReference` and `PackageReference`
No changes in the ADS UI, but the vscode quickpick for adding a db reference is updated with the new name:
> Change ReferenceType to ReferencedDatabaseType

- src/sql/platform/accounts/common/accountActions.ts
- src/sql/workbench/services/accountManagement/browser/accountPickerImpl.ts
> Hide tenant dropdown until account is refreshed

- extensions/sql-migration/package.json
- extensions/sql-migration/src/api/utils.ts
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/restartMigration/restartMigrationDialog.ts
- extensions/sql-migration/src/dialog/selectMigrationService/selectMigrationServiceDialog.ts
- extensions/sql-migration/src/dialog/tdeConfiguration/tdeMigrationDialog.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/telemetry.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
- extensions/sql-migration/src/wizard/loginMigrationTargetSelectionPage.ts
- extensions/sql-migration/src/wizard/targetSelectionPage.ts
Fix issue with migration wizard selecting a default tenant and preventing tenant selection to change again.
Typically tenant selection is hidden if only one tenant is available.  In this case the tenants array was overwritten with the selected tenant, thus hiding and preventing further selection or change.
> SQL-Migration, fix tenant selection, multi-tenant issue

- extensions/import/src/test/utils.test.ts
- src/sql/azdata.proposed.d.ts
add copyResults to query provider definition, this is needed to improve the performance of copying large amount of data.
follow up PRs will be send in dataprotocol-client repo and sts repo, eventually in ADS again.
> add copy results to query provider

- extensionsGallery-insider.json
This PR updates the insiders extension gallery to the latest version 1.4.6 of the SQL Migration extension. sql-migration-1.4.6.vsix
Link to Azure Data Studio - Extensions Product pipeline run off main:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=202526&view=artifacts&pathAsName=false&type=publishedArtifacts
> [SQL Migration] Release v1.4.6 to Insiders

- src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts
- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
- src/sql/workbench/contrib/notebook/browser/notebookViews/notebookViews.component.ts
- src/sql/workbench/contrib/notebook/test/browser/notebookActions.test.ts
Was working on an a11y issue and took the opportunity to clean these actions up so they're easier to use and understand. (and in a separate PR to avoid cluttering up the other one I'll be sending out). No functional changes being done here. 
1. Make AddCellAction abstract - it should never be instantiated directly
2. Made the toggle dropdown actions their own separate actions. They were previously using AddCellAction which worked, but was unnecessary and confusing
3. Renamed all the "button" variables to actions - since that's what they actually are. (ActionViewItems are the actual DOM elements themselves)
> Cleanup Notebook actions

- src/sql/workbench/browser/editor/tableDesigner/tableDesignerInput.ts
- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
Added in https://github.com/microsoft/azuredatastudio/pull/23370 - this parameter is optional so should be defined as such. We can't make the actual parameter optional because the injected service parameters are non-optional and required to be last, but in this case we just need to update the type to be `| undefined` since we can guarantee we'll always be passing a value.
(the public API will stay as optional to make it simpler for extensions to call if they don't have an OE context)
It's important for us to try and keep our typings correct - it helps make sure that we're handling them correctly and eventually we want to be able to enable strict null checking and incorrect typings like this would cause that to fail.
> Fix table designer parameter typings

- src/sql/workbench/contrib/notebook/browser/cellToolbarActions.ts
- src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts
- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
- src/sql/workbench/contrib/notebook/browser/notebookActions.ts
- src/sql/workbench/contrib/notebook/browser/notebookViews/notebookViewsActions.ts
- src/sql/workbench/contrib/notebook/browser/notebookViews/notebookViewsCard.component.ts
- src/sql/workbench/contrib/notebook/common/notebookLoc.ts
- src/sql/workbench/contrib/notebook/test/browser/cellToolbarActions.test.ts
For https://github.com/microsoft/azuredatastudio/issues/22672
As noted in the issue, there were two main problems : 
1. The dropdown menus (add cell & more) were being treated as separate tab targets, with the result that the arrow keys would only move between the middle actions and never go to the ones on either end.
2. Keyboard support for triggering the actions wasn't working
The root issue was this was all the custom toolbar stuff we had - our custom toolbar allowed raw HTML elements in addition to the actions themselves which meant that the dropdown actions (which were being created separately in their own div containers) weren't being treated as actual actions, and thus the keyboard support never took them into account.
It's possible that we could have fixed up the custom toolbars …
> Refactor Notebook cell toolbar dropdown actions

- src/sql/base/common/gridRange.ts
- src/sql/platform/query/common/query.ts
- src/sql/workbench/contrib/query/browser/gridPanel.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
- src/sql/workbench/contrib/query/browser/statusBarItems.ts
- src/sql/workbench/services/query/common/gridDataProvider.ts
- src/sql/workbench/services/query/common/queryManagement.ts
- src/sql/workbench/services/query/common/queryRunner.ts
- src/sql/workbench/services/query/test/common/queryRunner.test.ts
- src/sql/workbench/services/query/test/common/testQueryManagementService.ts
1. This PR fixes #23377
Problem: Similar to the original copy result issue, a request is send to retrieve all the rows.
Fix:  
a. paginate the fetch result request.
b. show a confirmation when user selected more than a certain number of rows. user can choose to do not show this dialog again.
c. show user a prompt so that the user is aware of the work in progress (only when it is taking more than 1 second) and can cancel it.
d. any new selection request will cancel the currently running request.
e. when the selection is small, user wouldn't notice any difference.
2. This PR fixes #22807 
Problem: Cells that appear in multiple selection ranges were calculated multiple times. 
Fix: Merge the selection ranges and only go through each cell once.
3. Fix an issue when there are too many cells …
> query result selection summary improvement (both perf and usability)

- extensionsGallery.json
This PR updates the worldwide extension gallery to the latest version of the SQL Migration extension 1.4.6.
This version was already released to insiders via PR:
https://github.com/microsoft/azuredatastudio/pull/23361
> [SQL Migration] Release v1.4.6 to Worldwide

- extensions/mssql/config.json
Fixes https://github.com/microsoft/azuredatastudio/issues/23381
Creating a new Data Warehouse instance in Azure is disabled in Portal, and trying to create one through TSQL throws a deprecated error message. So we decided to remove this option in the Create Database dialog.
STS changes with this version bump:
> Disable DataWarehouse Azure option in Create Database dialog

- extensions/mssql/src/objectManagement/localizedConstants.ts
- extensions/mssql/src/objectManagement/ui/databaseDialog.ts
- extensions/mssql/src/ui/dialogBase.ts
We had a discussion offline that the options for an Azure database in the New Database dialog are a bit ambiguous, and you could easily create an expensive instance without knowing it. This change adds a hyperlink in the Azure Configure SLO section to the azure pricing calculator so that users can see the costs for each option.
> Add link to Azure pricing calculator in New Database dialog

- extensions/mssql/src/mssql.d.ts
- extensions/mssql/src/mssql.proposed.d.ts
- extensions/sql-assessment/src/typings/ref.d.ts
Any extensions using the mssql.d.ts typings currently need to also bring over the azdata.proposed.d.ts typings because of the SqlAssessment definitions. This is generally just an annoyance for extensions, since most of them don't need these typings at all.
So to make this better I'm splitting the MSSQL typings into "stable" and "proposed" like we do with ADS. This way anything depending on azdata.proposed.d.ts typings can go into a separate typings file without impacting other extensions.
> Add mssql.proposed.d.ts

- extensions/mssql/config.json
This PR fixes https://github.com/microsoft/azuredatastudio/issues/23365
STS changes since last version:
https://github.com/microsoft/sqltoolsservice/compare/4.8.0.23...4.8.0.26
> bump STS to remove Linked Server Logins from OE

- extensions/sql-migration/src/models/loginMigrationModel.ts
- extensions/sql-migration/src/wizard/loginMigrationStatusPage.ts
Fixing bug in login migrations telemetry where the error codes weren't getting logged due to error in JSON.stringify for the numberOfLoginsPerStep column of the telemetry. Simplified it by adding the error codes in string array and doing a toString of the final map. Tested it on ADS with sideloading the custom vsix and was able to see the error codes on the telemetry:
[Associated ADO work item: https://msdata.visualstudio.com/Database%20Systems/_workitems/edit/2393077]
> Removing stringify and replacing with constructed string.

- extensionsGallery-insider.json
This PR updates the insiders extension gallery to the latest version 1.4.7 of the SQL Migration extension. sql-migration-1.4.7.vsix
Link to Azure Data Studio - Extensions Product pipeline run off main:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=203568&view=artifacts&pathAsName=false&type=publishedArtifacts
> [SQL Migration] Release v1.4.7 to Insiders

- extensionsGallery.json
This PR updates the stable extension gallery to the latest version of the SQL Migration extension 1.4.7.
This version was already released to insiders via PR:
https://github.com/microsoft/azuredatastudio/pull/23430
> [SQL Migration] Release v1.4.7 to stable gallery

- extensions/azurecore/src/account-provider/auths/httpClient.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/22835
JSON parse is unnecessary as later in code headers are casted again to `Record<string, string>`.
> Cleanup JSON parse

- extensionsGallery-insider.json
- extensionsGallery.json
Releasing v4.2.1 for Database Migration Assessment for Oracle in ADS Insiders and Public.
> Releasing v4.2.1 for Database Migration Assessment for Oracle

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/azureResource/services/subscriptionService.ts
- extensions/azurecore/src/constants.ts
`multiple_matching_tokens` is a rare error that can occur in scenarios when users try to run ADS as different users, reference issue: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5134
Full error message: `multiple_matching_tokens: The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements such as authority or account.`
The API that causes error is: [TokenCache.getAccountByHomeId(accountId)](https://azuread.github.io/microsoft-authentication-library-for-js/ref/classes/_azure_msal_node.tokencache.html#getaccountbyhomeid) where `accountId` is in format:
`00000000-0000-0000-77ed-ec3c7f46d602.9188040d-6c67-4c5b-b112-36a304b66dad`.
This error is likely a bug in MSAL.js. It was observed when fetching …
> Handle multiple matching tokens error

- extensions/sql-migration/package.json
- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/api/utils.ts
Add custom User-Agent to rest API calls
ex: "AzureDataStudio/1.45.0 (dev) Microsoft.sql-migration/1.4.8"
> sql-migration: add custom User-Agent to rest API calls 

- extensions/mssql/package.json
- extensions/mssql/package.nls.json
- src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
I also fixed 2 other issues:
1. Detach Database was incorrectly showing up in the command palette
2. New Notebook context menu entry was being placed in the middle of the object management actions.
New Context Menu layout:
Now New Query is always in the same group order as Manage, and New Notebook is in the group order immediately below that
> Add Preview tags to object management context menu entries

- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
- src/sql/workbench/services/objectExplorer/browser/connectionTreeAction.ts
- src/sql/workbench/services/objectExplorer/browser/filterDialog/filterDialog.ts
- src/sql/workbench/services/objectExplorer/browser/serverTreeActionProvider.ts
Removing Filter Dialog:
Removing double node path and fixing filter:
Before:
Now:
> Removing preview flag from OE filtering

- src/vs/workbench/contrib/terminalContrib/accessibility/test/browser/bufferContentTracker.test.ts
- src/vs/workbench/contrib/terminalContrib/links/test/browser/terminalLinkManager.test.ts
- src/vs/workbench/contrib/welcomeGettingStarted/test/browser/gettingStartedMarkdownRenderer.test.ts
- src/vs/workbench/services/configuration/test/browser/configuration.test.ts
- src/vs/workbench/services/configuration/test/browser/configurationEditing.test.ts
- src/vs/workbench/services/configurationResolver/test/electron-sandbox/configurationResolverService.test.ts
These suites are intermittently being impacted by the xterm glyph issue.  The actual upstream product functionality seems to be working fine, so it seems safe to disable in our test runs since we don't routinely modify these product areas.
> Skip flaky vscode test suites

- src/vs/workbench/services/configuration/test/browser/configurationService.test.ts
Continuing to disable upstream suites impacted by xterm glyph issue in automation runs.
> Disable failing vscode test suite

- src/sql/workbench/services/connection/browser/connectionBrowseTab.ts
Fixes #23526 
_(Line height is set to 23 to match Recent connection tree line height)_
> Fix line height in Saved Connections tree

- src/sql/workbench/contrib/dataExplorer/browser/dataExplorer.contribution.ts
- src/sql/workbench/contrib/objectExplorer/common/serverGroup.contribution.ts
- src/sql/workbench/contrib/preferences/browser/sqlSettingsLayout.ts
Fixes #22756
Adding a new category in Data for Object Explorer
OE will contain all server tree and server group related settings.
> Fixing setting layout in OE

- src/vs/workbench/services/configuration/test/browser/configurationService.test.ts
Additional upstream test suite that is impacted by xterm glyph issue that is being investigated.  It appears all the configuration tests intermittently encounter this exception.
> Disable vscode remote configuration suite

- src/vs/workbench/services/editor/test/browser/editorResolverService.test.ts
Continuing to turn off failing suites impacted by xterm glyph bug to stabilize canary/PR builds.
> Disable editor resolver service test suite

- src/vs/workbench/services/extensionManagement/test/browser/extensionEnablementService.test.ts
This suite is also failing for xterm glyph issue.  Plan is to reenable after further investigation and stabilization.
> Disable upstream extension enablement suite

- src/vs/workbench/contrib/extensions/browser/extensionsViews.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/23552, where installing initial extensions don't refresh the Extension Manager install view without a manual refresh or ADS restart.  The page model is updating from a different path than the initial code that populates the query model, so we can use the list model directly to get the correct Pager object.  I left the fallback to query model "just in case" but it shouldn't be needed as the code that updates query model also updates the list model.
> Fix issue updating installed extension list

- src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.component.ts
Fixes #23521 
Dashboard widget's `updateTheme` was going against theme color scheme by setting 'NULL' color (SIDE_BAR_FOREGROUND), which now has a default dull color, that causes accessibility issues. PR fixes issue by removing color overrides to keep text/background color in sync with theme.
> Remove dashboard color overrides

- extensionsGallery-insider.json
This PR updates the insiders extension gallery to the latest version 1.4.8 of the SQL Migration extension. sql-migration-1.4.8.vsix
Link to Azure Data Studio - Extensions Product pipeline run off main:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=204539&view=artifacts&pathAsName=false&type=publishedArtifacts
> [SQL Migration] Release v1.4.8 to Insiders

- extensionsGallery.json
This PR updates the stable extension gallery to the latest version of the SQL Migration extension 1.4.8.
This version was already released to insiders via PR: https://github.com/microsoft/azuredatastudio/pull/23567
> [SQL Migration] Release v1.4.8 to stable gallery

- src/sql/base/browser/dom.ts
- src/sql/base/browser/ui/table/plugins/additionalKeyBindings.plugin.ts
- src/sql/base/browser/ui/table/plugins/cellSelectionModel.plugin.ts
- src/sql/base/browser/ui/table/plugins/checkboxColumn.plugin.ts
- src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts
- src/sql/base/browser/ui/table/plugins/copyKeybind.plugin.ts
- src/sql/base/browser/ui/table/plugins/rowSelectionModel.plugin.ts
- src/sql/base/browser/ui/table/plugins/tableColumn.ts
- src/sql/workbench/services/insights/browser/insightsDialogView.ts
- src/sql/workbench/services/restore/browser/restoreDialog.ts
This PR fixes: #23561
With the recent merge, all the SlickGrid keyboard event handlers are broken due to a change in the StandardKeyboardEvent class: https://github.com/microsoft/azuredatastudio/blob/main/src/vs/base/browser/keyboardEvent.ts#L145. previously we would cast the event to KeyboardEvent type but it has always been a JQuery Event, it doesn't have the method `getModifierState`.
the fix is to use the original keyboard event to construct the StandardKeyboardEvent.
this is the error that will be thrown whenever we try to handle the keydown event of SlickGrid.
> fix slickgrid keyboard event handler

- src/vs/base/browser/ui/button/button.ts
This PR fixes: #23544
BTW, this is not a regression, it has been like this forever.
> fix image button style

- src/sql/workbench/contrib/scripting/browser/scriptingActions.ts
this is something I added a while back for the scripting actions, but it is not accurate, the actions are more than just generating script, it actually wait for the editor to be opened and executed, also edit data action is covered by this, so change the text to a more generic one.
> change the text to more generic

- src/vs/workbench/contrib/experiments/test/electron-sandbox/experimentService.test.ts
- src/vs/workbench/services/extensions/test/browser/extensionService.test.ts
- src/vs/workbench/services/history/test/browser/historyService.test.ts
Disabling additional upstream vscode test suites while investigating xterm glyph issue.  The canary builds are still unstable and resolving this bug will require additional investigation.
> Skip a few more suites impacted by xterm issue

- extensions/admin-tool-ext-win/package.json
- extensions/azurecore/package.json
- extensions/mssql/package.json
For https://github.com/microsoft/azuredatastudio/issues/23577 (not closing it since there's further work to be done)
Fixes https://github.com/microsoft/azuredatastudio/issues/23510
Fixes https://github.com/microsoft/azuredatastudio/issues/22346
This moves a few items around to more cleanly organize the context menu. This is the first step - further cleanup will happen once we solidify the grouping we want.
There are three new groups being added - with the goal that we will eventually land on a clearly defined set of default groups with recommendations for where new items should go. 
`x_admin` - Administration related items - e.g. profiler, scripting
`y_portal` - Items related to the Azure portal
`z_objectexplorer` - General items relating to the OE/Azure tree nodes such as refreshing and …
> Cleanup OE context menu order

- src/sql/base/query/browser/untitledQueryEditorInput.ts
- src/sql/platform/connection/common/connectionStatusManager.ts
- src/sql/platform/connection/test/node/connectionStatusManager.test.ts
- src/sql/workbench/browser/editData/editDataInput.ts
- src/sql/workbench/browser/scriptingUtils.ts
- src/sql/workbench/common/editor/query/queryEditorInput.ts
- src/sql/workbench/contrib/query/browser/queryEditorFactory.ts
- src/sql/workbench/contrib/query/test/browser/queryActions.test.ts
- src/sql/workbench/contrib/query/test/browser/queryEditor.test.ts
- src/sql/workbench/contrib/query/test/browser/queryInputFactory.test.ts
- src/sql/workbench/services/connection/test/browser/connectionManagementService.test.ts
- src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
- src/sql/workbench/services/queryEditor/common/queryEditorService.ts
- src/sql/workbench/services/queryEditor/test/browser/testQueryEditorService.ts
Reverting #22376 as there have been numerous complaints on the after affects across providers.
Will look into it again - the change is critical to address #6406 but the URI changes need to be handled across all areas.
This reverts commit 89386c9c11c704243b908c34d05201966a426d0d.
Fixes #23597 
Fixes #23562 
Fixes #23501 
Fixes #23414
> Revert "Fix for database name in connection details after changing database"

- extensions/theme-defaults/themes/light_vs.json
This pr fixes: #23541
this is not a regression.
now in Visual Light and Light+ themes:
> fix input border in some light themes

- extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts
Fixes #23140 to show proper error message.
Dummy message:
> Azure auth - throw original error message

- src/vs/workbench/contrib/experiments/test/electron-sandbox/experimentService.test.ts
- src/vs/workbench/contrib/experiments/test/electron-sandbox/experimentalPrompts.test.ts
Was looking into test failures and noticed that the experiments service tests seem flaky - e.g. https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=204756&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=c43d40ac-bf1b-572f-0943-b12cf91eb3c7
Looking into it VS Code actually just removed this service completely from their repo - I started with trying to port that over but it ended up being a few too many changes over a couple PRs so I decided to just disable the tests for now and we'll get that in a future merge.
https://github.com/microsoft/vscode/pull/185658
> Disable all experiements tests

- build/azure-pipelines/linux/Dockerfile
- build/azure-pipelines/linux/sql-product-build-linux.yml
- build/azure-pipelines/sql-product-build.yml
This PR fixes the esrp task, which requires dotnet 5.0. However, dotnet 5.0 does not use libssl 3.0 in ubuntu22 but instead relies on libssl1.0. This PR manually installs libssl in the ubuntu22 container image so that we can use esrp to sign extensions.
Example build:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=204703&view=artifacts&pathAsName=false&type=publishedArtifacts
> Adding libssl to build-image to sign extension. 

- src/sql/workbench/contrib/executionPlan/browser/topOperationsTab.ts
This PR fixes #23611
This PR removes an additional filter icon that didn't do anything and would appear over a query:
Now:
Before:
> Remove extra filter icon from Top Operations tab

- .vscode/settings.json
Set default schema for our azure pipeline yaml files for validation/autocomplete. Note that there are a number of "errors" that show up due to various issues with the validation - but overall this is still useful (if anything for the hover and autocomplete support)
> Add YAML schema setting for pipeline yamls

- extensions/theme-carbon/themes/light_carbon.json
Fixes #23484. The active border around the input controls in the ADS issue reporter weren't very visible in the default ADS light theme because the `inputOption.activeBorder` was so similar to the `input.border` color. Other places in ADS with input boxes and dropdowns, like the connection dialog, already have a blue border when they are the active control with the default light theme, so this change makes the issue reporter do the same.
By removing `inputOption.activeBorder` from the light_carbon theme, the default `inputOption.activeBorder` that's used by other light themes now gets used: https://github.com/microsoft/azuredatastudio/blob/01e66ab3e68200cbc0b9937cae39446b777bbadb/src/vs/platform/theme/common/colorRegistry.ts#L244
before:
fixed:
> fix active border on input box in issue reporter not being visible

- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
Fixes #23693. Pre-merge, we weren't setting the IButtonOptions. Setting it explicitly to null ensures that the VS default styles aren't added in addition to all of the custom notebook styles.
Before:
After:
> Don't set buttonoption for link/image Actions in Markdown Toolbar

- extensions/markdown-math/syntaxes/md-math-block.tmLanguage.json
- extensions/markdown-math/syntaxes/md-math-inline.tmLanguage.json
- extensions/markdown-math/syntaxes/md-math.tmLanguage.json
Fixes #23573. Copying syntaxes folder over from vscode, which doesn't look like it ever made its way over to ADS:
VS Code: [vscode/extensions/markdown-math at main · microsoft/vscode · GitHub](https://github.com/microsoft/vscode/tree/main/extensions/markdown-math)
ADS: [azuredatastudio/extensions/markdown-math at main · microsoft/azuredatastudio · GitHub](https://github.com/microsoft/azuredatastudio/tree/main/extensions/markdown-math)
I also thought about turning off markdown-math, but that would introduce yet another diff between ADS + VS Code, which could come back and bite us later.
> Add syntaxes folder to markdown-math

- extensions/query-store/src/common/utils.ts
- extensions/query-store/src/reports/baseQueryStoreReport.ts
I noticed the utils function `createTwoComponentFlexContainer()` doesn't actually need to be async while looking into the horizontal split view bug, so removing these all these unnecessary awaits.
> Cleanup uneccessary awaits in query store extension

- src/sql/base/browser/ui/dropdownList/dropdownList.ts
Account Picker Dropdown in the Firewall Rule Dialog was not expanding when clicked, this fixes that issue.
Fixes: #23707
> Fix dropdown behavior

- extensions/mssql/package.json
Tracking issue: https://github.com/microsoft/azuredatastudio/issues/23747
> Limit Detach Database and Database/Server Properties to insider and dev builds.

- extensions/mssql/package.json
- extensions/mssql/package.nls.json
- extensions/mssql/src/objectManagement/commands.ts
We cannot modify the generic `New` command title because it's shared with other types of sql objects.  Unfortunately, it seems that the only option is creating a new one for database.
For: https://github.com/microsoft/azuredatastudio/issues/23731
> Create new context menu item for Database

- extensions/profiler/package.json
After bumping the version for Profiler extension, it still doesn't install because of vscode version.
Updating the version in this PR.
> Update vscode version for Profiler extension

- extensions/mssql/package.json
Porting change to release branch. Disables Detach Database and Database/Server Properties dialogs for stable releases since they're still incomplete experiences.
Closes https://github.com/microsoft/azuredatastudio/issues/23747
> Limit Detach Database and Database/Server Properties to insiders and dev builds.

- extensions/profiler/package.json
Ports https://github.com/microsoft/azuredatastudio/pull/23767 to release/1.45 branch
This PR fixes #23779.
> [Port] Update vscode version for Profiler extension 

- extensions/mssql/src/objectManagement/ui/databaseDialog.ts
This change restricts the user to enter negative numbers in seconds for the target recovery input.
> Recovery time In seconds validation

- product.json
For https://github.com/microsoft/azuredatastudio/issues/23834 - switching to fwlink so we can update it more easily in the future.
> Update telemetry opt out URL

- src/sql/workbench/services/dialog/browser/dialogModal.ts
- src/sql/workbench/services/dialog/browser/wizardModal.ts
- src/tsec.exemptions.json
For https://github.com/microsoft/azuredatastudio/issues/23827
In the latest VS Code merge they added a check to the label setter to no-op if the label is the same. But because we were clearing the label directly here by setting the innerHTML the button still thought it had the original text so never "refreshed" with the original text. 
Before : 
After :
> Fix dialog buttons

- extensions/sql-migration/package.json
- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/api/utils.ts
This PR fixes an issue when an error occurs while loading a customer's subscriptions.  In the current behavior the api returns all subscriptions or nothing if an error occurs while loading all tenants / subscriptions.
This PR changes the behavior and loads available subscriptions and ignores subscription w/errors.
> SQL-Migration:  fix get subscriptions failure, that prevents valid subscriptions from loading.

- src/sql/workbench/contrib/connection/browser/connection.contribution.ts
Previously, right options for command-based connections were not set. Now, I am making the connection type as default so that the connection can be saved in OE. 
Issue: #23833
> Setting right options of command based new connections

- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
Fix for https://github.com/microsoft/azuredatastudio/issues/23861. The update project from db dialog did not have this problem because it uses `getAzdataApi()!.connection.getCurrentConnection()` to get the current connection, rather than using the profile that may or may not be passed in. Since it would be a bigger change to update the create project from db dialog to do the same thing, this is a smaller fix to verify that the profile actually has connection information, and not only `{ preserverFocus: false}`.
I tested the other entry points (right click on server or db, command palette) to the create project from db dialog to make sure they are still working as expected.
> Fix error when opening create project from db dialog without connection

- src/sql/workbench/services/fileBrowser/browser/fileBrowserDialog.ts
For https://github.com/microsoft/azuredatastudio/issues/23832
This dialog is set up so that when the filter option is changed it fires an event to tell the provider to refresh the tree. But STS expects that this only happens AFTER the initial open event is sent so it initializes properly. And there was a race condition here where the select box event firing could happen before this initial event was actually completed.
So to fix this we send the initialize event before actually setting the filter box contents - this ensures the message is sent before we get the filter notification. 
A slightly better solution would probably be to refactor this to be completely async and keep track of whether the initialize event has been sent before sending the filter event - but that's beyond the scope …
> Fix file browser opening race condition

- src/sql/workbench/contrib/notebook/browser/cellToolbarActions.ts
- src/sql/workbench/contrib/notebook/browser/notebook.component.ts
Addresses: https://github.com/microsoft/azuredatastudio/issues/23826
Dropdowns in cell toolbar:
Dropdowns in notebooks toolbar:
> Fix Notebook toolbar and cell toolbar dropdown alignment

- src/sql/workbench/contrib/profiler/browser/profilerActions.contribution.ts
- src/sql/workbench/services/profiler/browser/interfaces.ts
- src/sql/workbench/services/profiler/browser/profilerService.ts
This PR works on fixing https://github.com/microsoft/azuredatastudio/issues/23806.
For files within 100MB, no notification is posted.
For files from 100MB-1GB, a notification is posted:
For files more than 1GB, an error is thrown and file is not loaded:
> Add limit on the file size that can be opened with Open XEL feature

- src/sql/workbench/contrib/profiler/browser/profilerActions.contribution.ts
- src/sql/workbench/services/profiler/browser/interfaces.ts
- src/sql/workbench/services/profiler/browser/profilerService.ts
> [Port] Add limit on the file size that can be opened with Open XEL feature

- extensions/mssql/src/objectManagement/ui/databaseDialog.ts
- extensions/mssql/src/ui/dialogBase.ts
- extensions/mssql/src/ui/localizedConstants.ts
Add basic dynamic validation for database names:
- No empty values
- No more than 128 characters
For https://github.com/microsoft/azuredatastudio/issues/23823
For https://github.com/microsoft/azuredatastudio/issues/23822
> Add basic validation to database names

- extensions/sql-migration/src/dialog/targetDatabaseSummary/targetDatabaseSummaryDialog.ts
This PR fixes a but in the SQL migration extension that shows the wrong migration details summary page for SQL DB database/table selection details.
> SQL-Migration: fix migration summary details page view for sqldb target

- src/sql/workbench/services/fileBrowser/browser/fileBrowserDialog.ts
With further testing I found I was still occasionally hitting the error in https://github.com/microsoft/azuredatastudio/issues/23832
Dug into it more and found out that while the order the messages was being sent in was now correct, the STS code still has async issues. 
Here is the handler for the open request : https://github.com/microsoft/sqltoolsservice/blob/main/src/Microsoft.SqlTools.ServiceLayer/FileBrowser/FileBrowserService.cs#L96
Notice that we kick off the task but then immediately return true - which then allows the follow message to start processing. Normally the order would be expected to be this : 
1. Open message received with no change filter (initialize)
2. Create FileBrowserOperation here : https://github.com/microsoft/sqltoolsservice/blob/main/src/Microsoft.SqlTools.Serv …
> Better fix for file browser race condition

- extensions/mssql/src/objectManagement/ui/databaseDialog.ts
- extensions/mssql/src/ui/dialogBase.ts
Fix: https://github.com/microsoft/azuredatastudio/issues/23822
https://github.com/microsoft/azuredatastudio/commit/6e84766cec909cd66cf78e1b3fe7301a1eda9b15
> [Port Request] Add basic validation to database names (#23842)

- src/sql/workbench/services/connection/browser/connectionManagementService.ts
Addresses #23886
This error occurred as when user selected "Enable Trust Server Certificate", the same old URI was still used to create connection, and `trustServerCertificate` was not accounted into. This conflicted with Scripting, as it ended up not finding connection for the new URI and failed with error: `Cannot read properties of undefined (reading 'serverInfo')`
Sending no URI on reconnect, allows new URI to be generated when saving new connection profile.
**Before:**
**After:**
> Fix serverInfo undefined due to wrong connection URI set on connection

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/wizard/targetSelectionPage.ts
Added info box on target selection page of wizard to inform users of the need to click "Migrate certificates" button.
> Added info box to help user navigate the wizard

- extensionsGallery-insider.json
- extensionsGallery.json
This change updates the Gallery version for the DSCT extension to 0.6.0.
> Update DSCT version to 0.6.0, build number 23198.1

- src/vs/platform/configuration/test/common/testConfigurationService.ts
- src/vs/workbench/contrib/experiments/test/electron-sandbox/experimentService.test.ts
- src/vs/workbench/contrib/terminalContrib/accessibility/test/browser/bufferContentTracker.test.ts
- src/vs/workbench/contrib/terminalContrib/links/test/browser/terminalLinkManager.test.ts
- src/vs/workbench/contrib/welcomeGettingStarted/test/browser/gettingStartedMarkdownRenderer.test.ts
- src/vs/workbench/services/configuration/test/browser/configuration.test.ts
- src/vs/workbench/services/configuration/test/browser/configurationEditing.test.ts
- src/vs/workbench/services/configuration/test/browser/configurationService.test.ts
- src/vs/workbench/services/configurationResolver/test/electron-sandbox/configurationResolverService.test.ts
- src/vs/workbench/services/editor/test/browser/editorResolverService.test.ts
- src/vs/workbench/services/extensionManagement/test/browser/extensionEnablementService.test.ts
- src/vs/workbench/services/extensions/test/browser/extensionService.test.ts
- src/vs/workbench/services/history/test/browser/historyService.test.ts
This reverts commit 952bab7542c1dd6bdea24cd3fe621aa611d6df8a.
This PR is linked to: https://github.com/microsoft/azuredatastudio/issues/23509
> Revert "Fix flaky ADS unit tests by using DOM rendering (#23770)"

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/azureAccountProviderService.ts
- extensions/azurecore/src/account-provider/utils/fileEncryptionHelper.ts
- extensions/azurecore/src/account-provider/utils/msalCachePlugin.ts
- extensions/azurecore/src/extension.ts
- extensions/azurecore/src/localizedConstants.ts
- extensions/azurecore/src/utils.ts
Ports #23875 to release/1.45 branch for July release.
_[This change is specific to `Azure Accounts: Clear Azure Account Token Cache` command]_
Addresses #23688
> [Release/1.45] Clean encryption keys with cache clear command (#23875)

- extensions/mssql/src/objectManagement/localizedConstants.ts
- extensions/mssql/src/objectManagement/ui/detachDatabaseDialog.ts
- extensions/mssql/src/objectManagement/ui/objectManagementDialogBase.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/23730
Fixes https://github.com/microsoft/azuredatastudio/issues/23647
If the dialog is creating a new object, then the button will say "Create", otherwise it will say "Apply" for existing objects.
> Change OK button label based on whether the dialog is creating a new object or updating an existing one.

- extensionsGallery-insider.json
This PR updates the insiders extension gallery to the latest version 1.4.9 of the SQL Migration extension. sql-migration-1.4.9.vsix
Link to Azure Data Studio - Extensions Product pipeline run off main:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=206710&view=artifacts&pathAsName=false&type=publishedArtifacts
> [SQL Migration] Release v1.4.9 to Insiders

- build/azure-pipelines/linux/Dockerfile
- build/azure-pipelines/sql-product-build.yml
This updates GCC to version 7, which address issue https://github.com/microsoft/azuredatastudio/issues/23902.
> Update build container to use G++-7

- src/vs/workbench/contrib/experiments/test/electron-sandbox/experimentService.test.ts
- src/vs/workbench/contrib/terminalContrib/accessibility/test/browser/bufferContentTracker.test.ts
- src/vs/workbench/contrib/terminalContrib/links/test/browser/terminalLinkManager.test.ts
- src/vs/workbench/contrib/welcomeGettingStarted/test/browser/gettingStartedMarkdownRenderer.test.ts
- src/vs/workbench/services/configuration/test/browser/configuration.test.ts
- src/vs/workbench/services/configuration/test/browser/configurationEditing.test.ts
- src/vs/workbench/services/configuration/test/browser/configurationService.test.ts
- src/vs/workbench/services/configurationResolver/test/electron-sandbox/configurationResolverService.test.ts
- src/vs/workbench/services/editor/test/browser/editorResolverService.test.ts
- src/vs/workbench/services/extensionManagement/test/browser/extensionEnablementService.test.ts
- src/vs/workbench/services/extensions/test/browser/extensionService.test.ts
- src/vs/workbench/services/history/test/browser/historyService.test.ts
This PR fixes #https://github.com/microsoft/azuredatastudio/issues/23917
This PR enables the tests that were previously turned off when xterm was breaking.
> Turn on tests that were previously disabled due to xterm canvas undefined exception.

- extensions/schema-compare/src/schemaCompareMainWindow.ts
Fixes #8276. #23889 added support for split view model view components to be the size of the model view container, rather than requiring the size to be specified. Schema compare had previously hard coded the height of the split view to be 800px, which didn't use up all the space on larger screens.
**Bigger window**
before - empty space below Compare Details:
after:
**Smaller window**
before - didn't show Compare Details and had to scroll down to see them:
after - split view shows both the top and bottom components from the start:
> Remove fixed size of schema compare split view

- extensions/mssql/config.json
- src/sql/platform/connection/common/connectionConfig.ts
- src/sql/platform/connection/common/connectionProfile.ts
Paired with https://github.com/microsoft/sqltoolsservice/pull/2151, addresses #23921
- Fixes profiles without 'user' property on read.
- Allows Empty strings to be stored in connection options.
Bump STS o 4.5.0.6: https://github.com/microsoft/sqltoolsservice/compare/4.9.0.5...4.9.0.6
> Allow empty username + fix profiles on read

- src/sql/workbench/services/connection/browser/connectionManagementService.ts
This check was causing the change connection Uri to throw thereby preventing a connection being moved from one group to other. 
Issue: #23931
> Fixing moving connections from group to other 

- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
- src/sql/workbench/services/objectExplorer/browser/asyncServerTree.ts
#23830 
Storing and restoring expansion states of elements are causing the expanded nodes to refresh. This creates a problem in the case of errored nodes as the expansion of the nodes surfaces a duplicate error message. This prevents unnecessary expansion of elements in asynctree. Thereby matching the behavior of previous tree.
> Removing unnecessary tree expansions causing errors to popup again

- extensionsGallery.json
This PR updates the stable extension gallery to the latest version of the SQL Migration extension 1.4.9.
This version was already released to insiders via PR: https://github.com/microsoft/azuredatastudio/pull/23909
> [SQL Migration] Release v1.4.9 to stable gallery

- src/sql/workbench/contrib/views/browser/treeView.ts
Fixes #23941 and #23942 as well.
The change fixes both issues as well as Azure tree's context menu as it uses the same tree view.
The bug got introduced post merge with VS code update, due to duplicate copy of `treeView` being maintained.
> Fix context menu in treeViews

- src/sql/workbench/contrib/views/browser/treeView.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts
Follow up for https://github.com/microsoft/azuredatastudio/issues/23941
See the comment in the code for the description of the issue and the fix. This is definitely something I feel should be temporary - if we don't fix it in a safer way then we're very likely to run into issues down the line as tree items continued to be modified by VS (or us).
Couple notes : 
- This is similar to the fix Cheena had out earlier, but covers all providers. Removing the parent property ensures that those childProvider commands are always handled like they were previously (going through the Data Explorer argument processor to put the information in the format the DE commands expect)
- Just removing "parent" from the node wasn't enough - as that meant that ALL items were being treated as DE items, and so …
> Temporary fix for Data Explorer context menus

- extensionsGallery-insider.json
- extensionsGallery.json
Extension 'Data Migration for Oracle' for migrating data from Oracle source to Azure SQL.
> New extension for migrating data from Oracle to Azure SQL

- extensions/notebook/README.md
This replaces the old jupyter notebook link which is no longer available on jupyter.org with the new working link.
> Fix broken link in notebook README.md

- extensions/azurecore/src/account-provider/azureAccountProviderService.ts
- extensions/azurecore/src/constants.ts
- extensions/azurecore/src/localizedConstants.ts
If a user has no clouds selected, they will receive the following popup:
Also localized some additional strings that were not localized.
Fixes #23216, #23208
> Add no clouds selected warning popup

- src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
This is to fix the cell edit trigger for submitting cells that only worked if it detected changes in the cell from slickgrid. Previously the cell was left alone during an invalid edit (and recognized by slickgrid as having no changes), which meant that when submitting again the trigger would not be fired, causing the invalid data in the cell to be falsely added to the grid. Now a cell revert is done and the invalid cell data is restored so that the cell is recognized as dirty again by slickgrid.
This is similar to the existing logic for invalid edits in the new row. 
Fixes https://github.com/microsoft/azuredatastudio/issues/21182
GIFS of the change in action:
Existing row:
New row:
> Added working cell revert for invalid submissions in edit data.

- src/vs/base/common/event.ts
For now, we are disabling this check to unblock the extension. The right fix will be to fix the memory leaks. 
Issue: https://github.com/microsoft/azuredatastudio/issues/23994
> Commenting out listener threshold to fix extensions having mem leaks registering more listeners.

- extensions/mssql/config.json
- extensions/mssql/src/objectManagement/interfaces.ts
- extensions/mssql/src/objectManagement/ui/databaseDialog.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/23726
Fixes https://github.com/microsoft/azuredatastudio/issues/23649
Previously we were putting the default dropdown values at the top of the list, which caused confusion due to messing up the ordering of values. This PR incorporates a default index for each of those fields so the default value can be selected without changing the ordering.
This PR also bumps the STS version to the latest. Here are the changes included:
> Select default database dropdown values based on a default index value

- product.json
The latest merge actually brought us up to 1.79.2, but the product.json value was never updated to match. The MongoDB extension currently requires 1.79.1 so this makes users unable to install it - even though it should be supported just fine.
So updating this value to fix that. 
For https://github.com/microsoft/azuredatastudio/issues/24021
> Update vs code engine version to 1.79.2

- src/sql/workbench/contrib/profiler/browser/profilerEditor.ts
- src/sql/workbench/services/profiler/browser/profilerService.ts
Addresses https://github.com/microsoft/azuredatastudio/issues/23998 .
When an XEL file is opened, it doesn't populate the dropdown. Accidentally in the original change, the condition was wrongly set- updated it in this change.
Before:
After:
Also, after a session is stopped and then started again, the running state was incorrectly set, which was not enabling Stop and Pause button (and start was enabled), after a session started. SessionType is not always set, it can be undefined in one case. Hence updated the check to verify against LocalFile enum instead of RemoteSession enum.
Before (when the session is running):
After:
> Update session dropdown and fix running state info

- src/sql/workbench/services/connection/browser/connectionDialogService.ts
Removes unnecessary saveProfile check for isTemporaryConnection. This was probably added while figuring out how connection profiles were going to be added with the new advanced connection options feature (Probably during a meeting, we thought about making it so Query Connections won't be saved in recent, but it appears that is not expected by most users). In the final result, the query editor connection won't be added to the Connection Tree, but it will show up in recent connections as it did before.
For #24008
> Fix to Query Editor entry in recent connections

- src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts
Addresses issue https://github.com/microsoft/azuredatastudio/issues/24027 which seems like has a significant impact on the stability of connection browser.
Async Server tree renderer assumes that server tree view is available, which may be collapsed on startup.
The PR fixes the renderer to load action bar only when server tree view is available.
> Add null checks for server tree view

- src/sql/platform/query/common/query.ts
- src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
- src/sql/workbench/services/query/common/gridDataProvider.ts
- src/sql/workbench/services/query/common/queryRunner.ts
Addresses #24009 by auto-closing Copy notification in 3 seconds.
Additionally added support to disable notifications:
New behavior:
> Auto-close copy notification after 3 seconds + configuration support

- extensions/mssql/config.json
Bump STS: https://github.com/microsoft/sqltoolsservice/compare/4.9.0.8...4.9.0.10
> Bump STS to v4.9.0.10

- src/sql/workbench/contrib/charts/browser/chartView.ts
- src/sql/workbench/contrib/query/browser/keyboardQueryActions.ts
- src/sql/workbench/services/insights/browser/insightsDialogController.ts
- src/sql/workbench/services/insights/test/browser/insightsDialogController.test.ts
- src/sql/workbench/services/query/common/queryManagement.ts
- src/sql/workbench/services/query/common/queryModelService.ts
- src/sql/workbench/services/query/common/queryRunner.ts
- src/sql/workbench/services/query/test/browser/queryRunner.test.ts
- src/sql/workbench/services/query/test/common/testQueryManagementService.ts
For https://github.com/microsoft/azuredatastudio/issues/24095 - see my comment in that thread for a full description of the issue
This is the "easy" fix, but doesn't solve the root problem. Further discussion will be had about resolving that - but this at least gets us back to the state we were in before 1.45.0.
The fix just reverts the Notebook code to use the old way of fetching row data (doing it all at once) instead of in batches/pages. The rest of ADS will still use this new functionality as I don't see any problems with the actual paged API itself (just the Notebook code that's using it)
> Fix Notebook results being out of order

- extensions/mssql/src/mssql.d.ts
- extensions/mssql/src/objectManagement/constants.ts
- extensions/mssql/src/objectManagement/objectManagementService.ts
- extensions/mssql/src/objectManagement/ui/deleteDatabaseDialog.ts
Cleaning up some lingering details from my earlier Delete Database PR. The generic Delete Object command calls Drop methods internally, so these changes are to make Delete Database consistent with that style. We still use Delete in user facing areas, but Drop otherwise.
> Rename internal references to Delete Database to Drop Database

- extensions/schema-compare/src/dialogs/schemaCompareOptionsDialog.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/24120. The latest vscode merge changed how modal messages are shown, making it so that the close button gets set to the option with `isCloseAffordance` set to true. The `isCloseAffordance` option is meant to be specified for the button/option that will get triggered when the `ESC` key is used, and the schema compare options dialog was incorrectly setting it to true for both the Yes and No option. The fix is to have it only set to true for the No option. 
change from vscode merge that caused the change in behavior: 
Before:
Fixed:
> Fix schema compare 'Yes' button not showing for recomparing after changing options

- src/sql/workbench/contrib/editData/browser/media/editData.css
Fixes #23569
Screenshots showing the change made:
Default Light in High Contrast Dark:
Default Dark:
Default Light:
HC Dark:
HC Light:
> Add correct edit data background and content colors for edited cell

- extensions/mssql/package.json
- extensions/mssql/package.nls.json
- extensions/mssql/src/objectManagement/commands.ts
- extensions/mssql/src/objectManagement/constants.ts
- extensions/mssql/src/objectManagement/localizedConstants.ts
- extensions/mssql/src/objectManagement/ui/dropDatabaseDialog.ts
I noticed we use Delete and Drop interchangeably in some places, so we had an offline discussion and settled on using drop for all "delete" object operations to align with TSQL terminology.
> Replace usage of Delete with Drop in object management code

- src/sql/workbench/browser/modelComponents/splitviewContainer.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/23888. This adds supports for splitviews resizing when the window is resized, if the splitview wasn't created with a set height.
before:
QDS - has a horizontal and vertical splitview
schema compare - notice that the bottom section doesn't keep expanding and there is blank space
after:
> Resize splitview when window is resized

- src/vs/workbench/contrib/extensions/browser/extensionsActions.ts
Addresses this accessibility issue https://github.com/microsoft/azuredatastudio/issues/24161. Vscode announces the extension installation, but ADS wasn't going into the `if` block with the alert because `extension?.local` was undefined. I found that the extension getting returned from `this.install()` was an [ILocalExtension](https://github.com/microsoft/azuredatastudio/blob/01e66ab3e68200cbc0b9937cae39446b777bbadb/src/vs/platform/extensionManagement/common/extensionManagement.ts#L261), but it extends an [IExtension](https://github.com/microsoft/azuredatastudio/blob/01e66ab3e68200cbc0b9937cae39446b777bbadb/src/vs/platform/extensions/common/extensions.ts#L321) interface that does not have the local property. There is a different[ IExtension …
> Announce when extension install is finished

- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
- extensions/notebook/src/test/python/jupyterInstallation.test.ts
A new `notebook` pip package was released and is not backwards compatible with previous versions of the package, causing issues from our users (e.g. https://github.com/microsoft/azuredatastudio/issues/23945)
Some details can be found here: 
https://github.com/jupyter/notebook/releases/tag/v7.0.0
https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html
https://jupyter-server.readthedocs.io/en/latest/operators/migrate-from-nbserver.html
I have some code that gets us 50% of the way to notebook v7 but is flaky, and don't feel comfortable pushing that at the moment. Here's the beginnings of it: https://github.com/microsoft/azuredatastudio/compare/chlafren/nb7?expand=1. This attempts to support both 6.x and 7.x.
Ideally, we can move everyone to 7.x and support that going …
> Ensure Notebook v6 Pip Package Installed

- extensions/mssql/config.json
https://github.com/microsoft/sqltoolsservice/compare/4.9.0.18...4.9.0.22
> Bump STS to v4.9.0.22

- src/sql/workbench/contrib/welcome/browser/welcomePage.ts
Fixes #24210 where the "Install" button no longer had the text. It looks like it was mistakenly removed during the vscode merge. 
Also fixes this accessibility issue #10642 by removing the tooltips from the "Install" and "Installed" buttons. The tooltips were unnecessary because the labels are self explanatory.
before:
fixed:
> Add back "Install" text on welcome page button and remove tooltip

- extensions/sql-database-projects/README.md
- extensions/sql-database-projects/src/tools/buildHelper.ts
Update the Microsoft.Build.Sql SDK version used to build legacy style sql projects to 0.1.12-preview. Fixes https://github.com/microsoft/azuredatastudio/issues/24170
> update Microsoft.Build.Sql SDK version to 0.1.12-preview

- extensions/sql-database-projects/package.json
Update azdata dependency of sql projects since recent Fabric and microsoft.build.sql version updates depend on recent STS changes, so wouldn't work with older versions of ADS.
> update sql projects azdata dependency to 1.46.0

- extensions/mssql/config.json
- extensions/mssql/package.json
- extensions/mssql/src/contracts.ts
- extensions/mssql/src/mssql.d.ts
- extensions/mssql/src/objectManagement/objectManagementService.ts
- extensions/mssql/src/objectManagement/ui/detachDatabaseDialog.ts
- extensions/mssql/src/objectManagement/ui/dropDatabaseDialog.ts
The ADS counterpart to this STS change: https://github.com/microsoft/sqltoolsservice/commit/724d533090b426c5f0acf1b74f743508742fdd0d
We need to pass through the database names here so that when we call `ClearPool` during Detach and Drop operations, we'll be hitting the same connection pool as the other DB connections since pools are indexed by connection string. Without that our connection string has "master" as the database, which clears a different pool.
Fixes https://github.com/microsoft/azuredatastudio/issues/23653
> Pass through database names to enable connection cleanup

- src/sql/workbench/services/contextualization/common/serverContextualizationService.ts
This closes #24262
The PR adds logging to the server contextualization service.
> Adds logging to contextualization service

- src/sql/workbench/browser/editor/profiler/profilerInput.ts
- src/sql/workbench/contrib/profiler/browser/profilerEditor.ts
- src/sql/workbench/contrib/profiler/browser/profilerTableEditor.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/23883.
The loading indicator is turned off when the whole file is been read. Since the data comes in large chunks and presented in the profiler table, it overlaps a little (as seen in the end of the clip).
Also, if we switch between Profiler tabs while the file is been loaded, the indicator moves around to the other tabs (and goes away when the reading is completed).
> Add loading indicator when an XEL File is opened

- extensions/mssql/src/objectManagement/localizedConstants.ts
- extensions/mssql/src/objectManagement/ui/attachDatabaseDialog.ts
- extensions/mssql/src/objectManagement/ui/detachDatabaseDialog.ts
- extensions/mssql/src/objectManagement/ui/dropDatabaseDialog.ts
- extensions/mssql/src/objectManagement/ui/objectManagementDialogBase.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/24188
Currently we display "Updating X" in the tasks pane for all these operations after clicking OK in the dialogs. This change updates those to "Attach database", "Detach database X", and "Drop database X".
> Update task labels for Attach, Detach, and Drop Database

- extensions/mssql/src/contracts.ts
- extensions/mssql/src/features.ts
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/browser/mainThreadDataProtocol.ts
- src/sql/workbench/api/common/extHostDataProtocol.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
- src/sql/workbench/services/contextualization/common/serverContextualizationService.ts
This PR closes #24263
The PR consolidates the generate and get context request endpoints to just get context which generates context or returns previously generated context.
> Consolidate 2 context endpoints to just one

- src/sql/platform/connection/common/connectionConfig.ts
- src/sql/platform/connection/test/common/connectionConfig.test.ts
- src/sql/workbench/services/objectExplorer/browser/asyncServerTreeDragAndDrop.ts
- src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts
- src/sql/workbench/services/objectExplorer/test/browser/asyncServerTreeDragAndDrop.test.ts
- src/sql/workbench/services/objectExplorer/test/browser/dragAndDropController.test.ts
Fixes the check used to determine if a connection profile can be dropped in or not:
Fixes: https://github.com/microsoft/azuredatastudio/issues/24250
Also adds pop up notification on drag stating if a duplicate connection profile already exists in the connection group.
> Added fix to drag and drop 

- extensions/query-store/package.json
- extensions/query-store/package.nls.json
- extensions/query-store/src/common/constants.ts
- extensions/query-store/src/extension.ts
- extensions/query-store/src/reports/baseQueryStoreReport.ts
- extensions/query-store/src/reports/overallResourceConsumption.ts
- extensions/query-store/src/reports/queryStoreDashboard.ts
- extensions/query-store/src/reports/topResourceConsumingQueries.ts
Initial changes to make the query store reports all be available in a query store dashboard. This removes the previous commands to open the two placeholder reports and adds a single "Query Store" command to open this dashboard (having this in the command palette is to speed up testing and will be removed later). 
Still several things to come in the next PRs after this is checked in:
- Add launch point from Object Explorer in the context menu of db's with query store enabled and pass actual db's name to report
- add launch point to Manage dashboard
- add button to toolbar to open the current report in another editor tab
- update editor title to have current report in name (if possible)
> Initial changes for query store dashboard

- extensions/mssql/src/objectManagement/commands.ts
- extensions/mssql/src/objectManagement/localizedConstants.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/23962
We weren't handling undefined nodeInfo properties for the Drop and New Database commands, which caused failures when trying to open those commands from the data explorer viewlet.
> Handle undefined nodeInfo for top-level database objects

- extensions/mssql/src/objectManagement/ui/serverPropertiesDialog.ts
Managed instance:
Local server:
> Hide individual processors table in managed instance

- src/vs/workbench/contrib/debug/browser/debugCommands.ts
This PR fixes #24233. 
This change disables custom F11 keybinding added to step into the code while debugging in VSCode. This adds back the functionality of F11 to toggle between full screen.
Before:
After (on pressing F11 it toggles between full screen and current size):
> Fix F11 key binding

- src/sql/workbench/contrib/notebook/test/browser/dataResourceDataProvider.test.ts
- src/sql/workbench/services/query/common/resultSerializer.ts
This PR fixes #24329 .
Works as expected on Mac as well.
> Add Open file location as an option after an excel file is saved

- samples/sqlservices/README.md
- samples/sqlservices/src/controllers/mainController.ts
- samples/sqlservices/tslint.json
Planning to do this in a series of passes to slowly wrangle this file into readability while preserving useful diffs in the history.
1. Organize main methods + construction of dialog tabs
2. Organize core UI examples in first dialog tab
WebUI and wizards look pretty okay, so not planning to do much with them.
> Organizing code to be easier to follow

- extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts
This PR fixes #23382.
Added required indicator on the labels and removed required from textbox (so that customer has one source of truth, instead of two).
After changes:
Same database:
Different database, same server:
Different database, different server:
> Update required indicators in Add Database Reference Dialog

- extensions/mssql/package.json
These changes were recently added in PR #23407 but look irrelevant as they both don't work.
https://github.com/microsoft/azuredatastudio/pull/23407/files#diff-fdd531ac83f636b3015220925db3e0512f8304be6e1b3e6ad969e1670126d663R498-R502
Fixes #24051 and also below error when 'Script as Alter' command is run:
cc @Charles-Gagnon
> Remove 'Script As Alter' command and don't show for table nodes

- extensions/mssql/src/objectManagement/ui/serverPropertiesDialog.ts
Fix https://github.com/microsoft/azuredatastudio/issues/24312
Fix https://github.com/microsoft/azuredatastudio/issues/24305
> Fix some of the issues found in the bug bash

- extensions/mssql/src/objectManagement/constants.ts
- extensions/mssql/src/objectManagement/interfaces.ts
- extensions/mssql/src/objectManagement/localizedConstants.ts
- extensions/mssql/src/objectManagement/ui/serverPropertiesDialog.ts
- Add locks validations: https://github.com/microsoft/azuredatastudio/issues/24316
- Disable scan startup procs and locks properties for Sql MI: https://github.com/microsoft/azuredatastudio/issues/24365
- Only notify user to restart server if they apply changes.
> More server properties fixes

- src/sql/workbench/browser/modelComponents/componentBase.ts
@barbaravaldez  reached out to me for help on this issue: https://github.com/microsoft/azuredatastudio/issues/24200
I noticed the following problems while changing the value (valid to invalid or invalid to valid), apparently, some components are not registered or disposed properly. 
I think we should add warning for these scenarios as a safe guard. and in the meanwhile, @barbaravaldez, please investigate what caused the component to be undefined and fix it.
> handle error scenarios for validity check

- extensions/mssql/src/objectManagement/ui/databaseFileDialog.ts
Issue fixed for: https://github.com/microsoft/azuredatastudio/issues/24322
check/un-check 'enable Autogrowth 'checkbox is leaving the maxfilesize input box editable even unchecked.
> max file size input field has wierd enable/disable behavior #24322

- src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
Fixes a bug/oversight that was encountered during testing and mentioned in this issue:
Posted here for release DRI: https://github.com/microsoft/azuredatastudio/issues/24421 
Will be ported into September release as this is a regression.
This should prevent the cell from moving in the new row, using the existing logic.
Introduced here: https://github.com/microsoft/azuredatastudio/pull/23981
Before:
After:
> Added fix to new row revert

- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
- extensions/notebook/src/test/python/jupyterInstallation.test.ts
Addresses: https://github.com/microsoft/azuredatastudio/issues/24405
Later versions of ipykernel (>=6.x) changed the display name from 'Python 3' to 'Python 3 (ipykernel)' in the kernel spec. This caused issues for us since our display name is 'Python 3' and we could not find a provider for 'Python 3'.
> Pin ipykernel package to v5.5.5

- src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
Ports #24422 to Release/1.46
Addresses: https://github.com/microsoft/azuredatastudio/issues/24421
> [Release/1.46] Fix Edit Data Revert for New Row.

- src/sql/workbench/services/notebook/browser/models/notebookModel.ts
I somehow got in a state where non-SQL kernels weren't being registered. This manifested as the Notebook just silently switching back to the SQL kernel when I tried to switch - without any error or message of any sort. I was able to track it down to this code path being the reason why that was happening, although unfortunately the issue went away before I could root cause it.
But I figured adding this log message will at least help us know when this is happening in the future. It was very confusing to just have it switch back to the SQL kernel (seemed like nothing was happening). I considered having it be an actual toast notification, but sticking with this for now to start with since it's unclear when/how often this would happen.
> Add log message when falling back to default kernel

- extensions/mssql/src/objectManagement/ui/objectManagementDialogBase.ts
- extensions/mssql/src/ui/scriptableDialogBase.ts
Currently, the script and ok buttons are enabled when the dialog is dirty. However, the ok button is later enabled or disabled depending on the validity of the ModelView object in the [dialogModal](https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/services/dialog/browser/dialogModal.ts#L78) object. We need to add this functionality to the script button to disable the button for invalid values.
For: https://github.com/microsoft/azuredatastudio/issues/24311
> Fix enable/disable script button behavior

- extensions/mssql/src/objectManagement/ui/databaseDialog.ts
- extensions/mssql/src/ui/dialogBase.ts
This PR adds the ability to enable disable Add button of the table component. 
https://github.com/microsoft/azuredatastudio/issues/24309
> Filegroup Memory optimized table Add button should be disabled when have at least one filegroup

- extensions/sql-migration/config.json
- extensions/sql-migration/package.json
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/tdeConfiguration/tdeConfigurationDialog.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/models/tdeModels.ts
- extensions/sql-migration/src/service/contracts.ts
- extensions/sql-migration/src/service/features.ts
This pull request makes changes to the TDE migration dialog of the Azure SQL Migration extension.
A user is now required to pass validation checks prior to completing the configuration dialog.
Failed validation:
Successful validation:
> Added validations to configure dialog

- extensions/sql-migration/src/dialog/createSqlMigrationService/createSqlMigrationServiceDialog.ts
I added missing aria-label for Input Box in create Migration Service Dialog
Resolving one of the issue in the bug - https://github.com/microsoft/azuredatastudio/issues/23897
"ORCA screen reader is not announcing "Name" edit field label name along with edit box."
> Added Arialabel for SqlMigration Service Name InputBox

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
- extensions/azurecore/src/account-provider/interfaces.ts
- extensions/azurecore/src/account-provider/providerSettings.ts
- extensions/azurecore/src/azurecore.d.ts
- extensions/azurecore/src/utils.ts
- src/sql/azdata.d.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
Azure Active Directory Graph API is getting [retired](https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-overview) after Sept 30th, removing the endpoints from ADS.
> Remove deprecated azure graph endpoints

- src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts
- src/sql/workbench/services/objectExplorer/browser/mssqlNodeContext.ts
Fixes #24458 
Enabled 'Select Top 1000' on History table.
> Support select execution on History Table

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/assessment/sqlDatabasesTree.ts
Azure SQL Managed Instance supports maximum 100 user databases per instance. Enforce the threshold limit at the time of DB selection for migration.
[Work item](https://github.com/microsoft/azuredatastudio/issues/23352)
Experience details:
1. Customers selects than Azure MI supported limit (100 DBs), dialog will show an error message and select button will be disabled.
2. As soon as user selected DB count goes under limit, it will show an info message and select button will be enabled.
> Azure SQL MI supports maximum 100 DB per instance.

- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
- extensions/notebook/src/test/python/jupyterInstallation.test.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/24445
Follow-up to https://github.com/microsoft/azuredatastudio/issues/24443. A new version of the notebook package was released (6.5.6) that fixes that issue so the pinned version of traitlets is no longer needed.
https://github.com/jupyter/notebook/pull/7051
Ideally we would be able to specify notebook < 7 and >= 6.5.6 to allow future updates in the 6.x band but the package manager logic doesn't support that yet so just keeping it pinned to 6.5.6 for now.
Verified with notebook 6.5.6 and 5.10.0 traitlets
> Require jupyter notebook >= 6.5.6

- src/sql/workbench/browser/ui/infoBox/infoBox.ts
Fixes #24475. This updates `InfoBox` to use the vscode `Link` to create the links so that they have the correct theming. The text component also does this for creating links: https://github.com/microsoft/azuredatastudio/blob/86cd0003fe65ed660bfde4b8ec61d335461c4908/src/sql/workbench/browser/modelComponents/text.component.ts#L191-L195
Before:
After:
> fix hyperlink in infoBox not visible in dark theme

- extensions/notebook/src/common/utils.ts
- extensions/notebook/src/jupyter/serverInstance.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/24489
According to the Node.JS docs, any listener that gets called for the process 'exit' event has to be run synchronously. If it's async, then any portion after an await won't be called because the process exits. As a result, the python process we start as part of jupyter notebooks wasn't getting shutdown properly when ADS would exit, leading to a buildup of orphaned processes in the task manager.
Docs: https://nodejs.org/api/process.html#event-exit
The relevant portion: "Listener functions must only perform synchronous operations. The Node.js process will exit immediately after calling the 'exit' event listeners causing any additional work still queued in the event loop to be abandoned."
> Use sync callback to stop Jupyter server when ADS process exits

- extensions/mssql/package.json
Fixes #24476 by defining upper limit in integer settings, and specifically using non-floating integer types.
I figured we couldn't use 64-bit `long` in STS, due to SQL Server limits in [Text Size](https://learn.microsoft.com/en-us/sql/t-sql/statements/set-textsize-transact-sql?view=sql-server-ver16#arguments), and similarly for other settings, it didn't feel necessary to change any existing behavior.
Therefore setting max limit in integer settings would error out invalid values that would fail in backend due to overflow exceptions as captured in https://github.com/microsoft/azuredatastudio/issues/24476#issuecomment-1732225384
> Use non-floating integers with max limits in settings

- extensionsGallery-insider.json
- extensionsGallery.json
* Added "**Inspect data**" menu item in the context menu of the editor. This menu item starts the extension showing immediately the object corresponding to the selected text in the editor.
* Added server name to header.
* Added selected table/view name to header.
* Improved visualization of `geography` and `geometry` columns.
* Implemented the filter by name on the list of tables/views.
* Improved performance during objects filtering avoiding to query the database for refreshing the list.
* Columns of type `binary|text|image|geography|geometry|variant|xml|json` now show the count of **NULL** and **NOT NULL** values in the "**Distinct Values**" section. Before this update no values where shown because these type of columns have not been considered for distinct values selection.
* Requires …
> Updated extension sql-data-inspector to version 0.7.0

- extensions/machine-learning/src/packageManagement/sqlRPackageManageProvider.ts
- extensions/sql-bindings/src/common/utils.ts
These two lines had warnings about only the first occurrence getting replaced. By adding the global flag, all occurrences in the string will get replaced.
> Fixing a couple codeql warnings about incomplete string replacement

- extensions/ipynb/package.json
- extensions/ipynb/src/ipynbMain.ts
- extensions/ipynb/src/typings/refs.d.ts
- src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/23859
This new notebook command is contributed from the ipynb built-in extension, which is only used for vscode notebooks. This change redirects that command to our notebook code if the useVSCodeNotebooks setting isn't enabled. This was the only palette command contributed by the ipynb extension.
> Redirect vscode New Jupyter Notebook command

- extensions/resource-deployment/src/services/tools/azCliTool.ts
Issues flagged by CodeQL. Technically shouldn't be necessary, since the output from these commands is well-known (there shouldn't be more than 1 instance of each) - but doesn't hurt to add it just in case.
> Fix regex replace

- extensionsGallery-insider.json
This PR updates the insiders extension gallery to the latest version 1.4.10 of the SQL Migration extension. sql-migration-1.4.10.vsix
Link to Azure Data Studio - Extensions Product pipeline run off main: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=212174&view=results
https://mssqltools.visualstudio.com/_apis/resources/Containers/6113733/drop?itemPath=drop%2Fextensions%2Fsql-migration-1.4.10.vsix
> Ramudaykumar/vbump sql migration 1.4.10 insiders

- extensions/mssql/src/objectManagement/localizedConstants.ts
- extensions/mssql/src/objectManagement/ui/findObjectDialog.ts
- extensions/mssql/src/objectManagement/ui/objectSelectionMethodDialog.ts
- src/sql/workbench/services/fileBrowser/browser/fileBrowserDialog.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/23738
This PR changes the cancel button label for the file browser and find object dialogs we use in the basic admin space. Those are inner dialogs that get opened from another dialog, so having Cancel for those may cause confusion as to whether it will close the entire dialog or just the inner one. Using Back instead seems more appropriate.
> Change Cancel button label to Back for inner dialogs.

- build/azure-pipelines/linux/sql-product-build-linux.yml
The pipeline agents started failing today due to disk space running out. This deletes the compilation.tar.gz after it's been extracted to clear up some space.
> Delete compilation.tar.gz after it's been extracted

- src/sql/workbench/browser/modelComponents/formContainer.component.ts
Addresses https://github.com/microsoft/azuredatastudio/issues/24217. The info tooltip used to have a role of image, so this changes it to be tooltip for accessibility.
> make form container info have tooltip role

- src/sql/workbench/services/connection/browser/connectionManagementService.ts
Fixes #22621
Before: Selecting "Manage" on a database node would still open the server dashboard.
https://github.com/microsoft/azuredatastudio/assets/18150417/ab6093a3-094a-4bea-ad7e-d24714e43757
After: Selecting "Manage" on a database node opens the correct database dashboard.
https://github.com/microsoft/azuredatastudio/assets/18150417/9642c1c1-329e-453f-8fb8-a702ab84456c
> Fix dashboard opening server vs database view

- extensions/mssql/src/objectManagement/localizedConstants.ts
- extensions/mssql/src/objectManagement/ui/databaseDialog.ts
This PR adds a label to the filegroup input box and fixes the issue of row filegroup table remove button (where the button adds the rows instead of removing it). Also, Add and remove button automatically focuses on the newly added input box and next row after delete respectively.
> Adding fiilegroup name label to the input box and auto focus of newly added row

- src/sql/workbench/contrib/profiler/browser/profilerEditor.ts
- src/sql/workbench/contrib/profiler/browser/profilerTableEditor.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/24540.
Somehow setting the padding to move the loading indicator down messed up the columns' resize functionality. Localizing the issue to when the loading indicator is actually added and removing the padding when it is removed.
Before:
Profiling server:
Opening XEL File:
After:
Profiling server:
Opening XEL File:
> Fix column resize issue in profiler

- build/azure-pipelines/linux/sql-product-build-linux.yml
Cherry picking https://github.com/microsoft/azuredatastudio/commit/883d5714cca6c16f7d0aebf1b0b7ddf859fba42c from main to delete compilation.tar.gz after it's been extracted to deal with the "No disk space left on device" error on the linux agent in the pipeline.
> [Port] Delete compilation.tar.gz after it's been extracted (#24539)

- extensions/mssql/src/objectManagement/ui/databaseDialog.ts
This PR fixes the unnecessary scroll bar on DSC tab, caused due to the primary and secondary input/dropdown types are e existing on the DOM but just invisible. Used display property instead of the visibility. Below is the ss comparison of before and after the fix. Fixes the issue #24314
> Database Properties: Database Scoped Configuration Table Has Unnecessary Double Scrollbars

- extensions/sql-migration/config.json
- extensions/sql-migration/package.json
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/skuRecommendationResults/skuRecommendationResultsDialog.ts
- extensions/sql-migration/src/service/contracts.ts
- extensions/sql-migration/src/service/features.ts
- extensions/sql-migration/src/wizard/skuRecommendationPage.ts
Include Premium SSD v2 disks in SQL VM recommendations.
SQL VM recommendations (Removed Disk details to keep clean): 
Configuration details to show disk details:
> Premium SSD v2 disks in SQL VM recommendations

- extensionsGallery.json
This PR updates the extension gallery to the latest version 1.4.10 of the SQL Migration extension. sql-migration-1.4.10.vsix
Insider Gallery PR: https://github.com/microsoft/azuredatastudio/pull/24528
> vbump sql migration 1.4.10 in extension gallery

- extensions/mssql/src/objectManagement/ui/databaseDialog.ts
Apply button enabling while opening query store tab even though no changes have been made. This issue is caused by waitStatisticsCaptureMode which comes as On/Off but the dropdown options we provide are ON/OFF, when the value is replaced to block letters, there causes the grid dirty and enables the button.
fixes:
1. https://github.com/microsoft/azuredatastudio/issues/24570
2. https://github.com/microsoft/azuredatastudio/issues/24605
We can either fix this by getting the new options as On/Off or by sending the expected value.
> Fix to Disable Apply button for Query Store tab when no changes are made

- extensions/mssql/config.json
- src/sql/workbench/services/query/common/queryManagement.ts
- src/sql/workbench/services/query/common/queryModelService.ts
- src/sql/workbench/services/query/common/queryRunner.ts
Before: Saving a query before executing would put the query editor into a disconnected state (because a query runner does not exist)
After: Connection URI is transferred correctly even without a query runner present
STS Changes: https://github.com/microsoft/sqltoolsservice/pull/2265
Fixes https://github.com/microsoft/azuredatastudio/issues/21988
> Transfer URI Correctly

- build/azure-pipelines/win32/sql-product-build-win32.yml
Downgrade python version to fix ARM build error: `ModuleNotFoundError: No module named 'distutils'`
- VSCode also seems to be using v3.11.x in their [product pipelines](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=236040&view=logs&j=b599f925-57da-5b26-3abb-63aa7efd9fc6&t=14b645b8-df47-5692-9b0c-ccd40e27a6e6&l=9) that is fetched from cache.
Will update Wiki accordingly to address #24582
> Use python 3.11

- extensions/sql-database-projects/package.json
This updates the sql projects azdata dependency since 63a78e62aa4181ce5cc6dec9616e6447746cda2d brought in a new version of STS that required a couple changes in the sql projects extension for create project to work again. The sql projects extension will need to be updated in insiders after this is merged to fix https://github.com/microsoft/azuredatastudio/issues/24659.
> update sql projects azdata dependency

- build/azure-pipelines/win32/sql-product-build-win32.yml
- package.json
Update distro commit hash to 8c77b1784802cb3c0304e990fdeca1dd823b99c4, and remove build step
> Update distro commit to 8c77b1784802cb3c0304e990fdeca1dd823b99c4

- extensionsGallery-insider.json
- extensionsGallery.json
* Added column information such as nullability (indicated with a question mark "?"), size and precision.
* Added new feature for copying all the values of the selected column and their corresponding counts. Copied values can be pasted on Excel for further analysis.
* The filters panel is now collapsible. This makes the usage of the workspace area more efficient when no filters are defined.
* Values for columns of type **date**, **datetime**, **datetime2** and **datetimeoffset** are sorted descending by default. This can be useful for monitoring columns with datetime for creations, updates and similar.
* Fixed a bug in the live monitoring that was preventing the data from refresh.
> Updated extension SqlDataInspector to 0.7.1

- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts
- extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts
Addresses https://github.com/microsoft/azuredatastudio/issues/24163. This switches two of the sql projects dialogs that have section headings to use the `groupContainer` component so that the section header gets announced by screenreaders. There changes in the look is that the section headers are no longer bold and the items in each group are slightly indented compared to the section title - this is how it also looks in other dialogs that use the `groupContainer` component, like the New Database dialog.
Before: 
After:
Screenreader announcing the section heading when the first item in the group is navigated to:
https://github.com/microsoft/azuredatastudio/assets/31145923/1ca2df11-09bb-4837-8eab-44e84b5fd61f
> Fix so screenreaders will announce section headers in sql projects dialogs

- .github/workflows/basic.yml
- .github/workflows/ci.yml
+Updates set-output to GitHub Output
(ref: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
The CI build is disabled in VSCode repo as well so I'm open to keeping it disabled if needed, as we're not really running integration tests.
> Fix and enable GitHub CI workflow

- src/vs/editor/common/config/editorConfigurationSchema.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/24712. This setting defaulted to false in the previous ADS release and the default was changed to true in the latest vscode merge. Besides the colors not being swapped when using the diff editor version2, there's other weird behavior that the schema compare diff editor component stays when the tab is changed.
The diff editor version2 is still experimental, so it makes more sense to default to not using it right now rather than trying to get schema compare to work with it when it isn't stable yet. Users can change the setting to true if they want to use the experimental version2 of the diff editor.
https://github.com/microsoft/azuredatastudio/assets/31145923/82c22c50-359e-4653-9c35-94806389a210
> Change default value of diffEditor.experimental.useVersion2 back to false

- src/sql/base/common/locConstants.ts
- src/vs/workbench/electron-sandbox/parts/dialogs/dialogHandler.ts
This PR closes #24709
This PR removes the electron build ID since it's appearing as undefined.
VS Code doesn't use public Electron builds and use their own private builds, so the build ID could be coming in through a mixin that ADS doesn't have access to, which is why it's appearing as undefined.
> Fix About Dialog post merge for Azure Data Studio

- src/vs/workbench/contrib/surveys/browser/nps.contribution.ts
As confirmed internally by the DTP Survey teams, the parameters with NPS URL are needed to be sent via context parameters, as explained here: https://meganvwalker.com/passing-variables-through-the-forms-pro-survey-url/
This PR updates the same to be able to capture the parameters in survey results.
cc @erinstellato-ms 
I'm also working on a similar PR for VS Code so we can get the update in future merges.
> Update NPS survey URL to capture context parameters

- extensionsGallery-insider.json
This PR closes #24743
Update Copilot version in the insiders extension gallery to 1.128.504 after VS Code version 1.82 was merged into ADS.
Link to files to upload: https://microsoft-my.sharepoint.com/:f:/p/lewissanchez/EukjwrSRcRJMvQRR5FN50bMBZ6BD2rhfd0rnsp4Hv3iuGw?e=mRxXHz
> Bump GitHub Copilot extension version to 1.128.504

- src/sql/workbench/browser/editData/editDataInput.ts
- src/sql/workbench/common/editor/query/queryEditorInput.ts
Changes the header to use short format identical to that of query editor.
> Added short header for editDataInput (from Query Editor

- src/sql/workbench/contrib/views/browser/treeView.ts
- src/sql/workbench/services/connection/test/browser/testTreeView.ts
Fixes #24738
VS Code merge brought this event, but it was added without initialization, that caused the error in the issue reported. This PR initializes it and fixes registering the new event handler.
> Add emitter for onDidChangeSelectionAndFocus event handling

- src/sql/workbench/api/browser/mainThreadConnectionManagement.ts
- src/sql/workbench/browser/taskUtilities.ts
- src/sql/workbench/contrib/backup/browser/backupActions.ts
- src/sql/workbench/contrib/connection/browser/connectionStatus.ts
- src/sql/workbench/contrib/dashboard/browser/dashboardActions.ts
- src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
- src/sql/workbench/contrib/objectExplorer/test/browser/connectionTreeActions.test.ts
- src/sql/workbench/contrib/profiler/browser/profilerActions.contribution.ts
- src/sql/workbench/contrib/query/browser/queryActions.ts
- src/sql/workbench/contrib/query/browser/queryEditorFactory.ts
- src/sql/workbench/contrib/restore/browser/restoreActions.ts
- src/sql/workbench/services/objectExplorer/browser/asyncServerTree.ts
- src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts
- src/sql/workbench/services/objectExplorer/browser/serverTreeActionProvider.ts
- src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts
- src/sql/workbench/services/objectExplorer/test/browser/objectExplorerService.test.ts
- src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
- src/sql/workbench/test/browser/taskUtilities.test.ts
There are multiple reports of serverTreeView initialization errors where users are not able to open SQL files in Query Editor, and it's not readily reproducible in all environments. This is likely related with calls to get global connection, where async server tree being unrendered is causing issues. 
This PR improves null reference handling to prevent NRE exceptions like below:
```
2023-10-24 19:12:16.516 [error] Cannot read properties of undefined (reading 'style'): TypeError: Cannot read properties of undefined (reading 'style')
at Ne (vscode-file://vscode-app/c:/Users/HendrikPetzer/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:194:43234)
at e.ServerTreeView.refreshTree (vscode-file://vscode-app/c:/Users/HendrikPetzer/AppData/Local …
```
> Improve null handling in ServerTreeView

- extensions/azurecore/package.json
- extensions/azurecore/yarn.lock
Internally found: The latest update of MSAL 2.2.0 led to non-returning login redirect. The redirection to `login.microsoftonline.com` after proxy authentication would not complete, which had worked in the past in the same proxy-enabled environment.
> Downgrade MSAL to 1.16.0 to resolve potential proxy auth issues

- src/sql/workbench/contrib/profiler/browser/profilerEditor.ts
- src/sql/workbench/contrib/profiler/common/interfaces.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/24467.
After this change went in https://github.com/microsoft/azuredatastudio/pull/23206, search keybinding for profiler stopped working. 
Updated the code to look for profiler editor as a precondition instead of context key which wasn't getting appropriately set.
After the changes., Ctrl + F works as expected. It brings up the search box in the profiler table editor.
> Fix search in profiler editor

- src/sql/base/common/locConstants.ts
> Include VS Code version missing in About dialog

- package.json
The AGC team decided they didn't want the migration extension for now because it doesn't work in a disconnected environment since it needs to install STS separately, they want to plan on adding it back at a later time.
To be merged after ADS-release PR is merged.
> Update distro - Remove SQL Migration builtin extension

- build/.moduleignore
- src/vs/code/electron-main/app.ts
- src/vs/platform/encryption/electron-main/encryptionMainService.ts
- src/vs/platform/encryption/node/encryptionMainService.ts
- src/vs/platform/environment/test/node/nativeModules.integrationTest.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/24737
VS Code has gone through significant changes to move away from keytar and a customized encryption module (vscode-encrypt) in the past few releases. The changes aren't compatible, although VS Code did have a migration story where they migrated over secrets from the old store & format into the new storage & format. 
More details about this here : https://github.com/microsoft/vscode/issues/193301
The specific part that's impacting us and caused the decryption issue is that we completed skipped over the migration of the storage format (how they're encrypted) by jumping from 1.79 to 1.82. Specifically this PR where the migration code was removed : https://github.com/microsoft/vscode/pull/189252
Because of this when the secret …
> Bring back vscode-encrypt

- src/sql/workbench/contrib/backup/browser/backup.component.ts
- src/sql/workbench/services/restore/browser/restoreDialog.ts
Reverts some of the changes from this commit: https://github.com/microsoft/azuredatastudio/commit/1e51c573504267b167cab05281230d4bc19bdff3
The backup & restore dialogs currently don't support switching between File and URL modes, so non-MI instances were being forced to use a URL-only mode.
> Partially revert URL support for backup and restore dialogs.

- src/sql/workbench/browser/scriptingUtils.ts
May address https://github.com/microsoft/azuredatastudio/issues/21737
The root cause of why connection is not available when selecting scripting option in context menu needs to be investigated, but adding null check in the meantime to unblock code paths to proceed further.
> Adding a null check for serverInfo

- src/sql/workbench/contrib/welcome/browser/welcomePage.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/24085. With this change, when someone unselects the `Show welcome page on startup` checkbox on the welcome page, their `workbench.startupEditor` setting will get set to `none` instead of `newUntitledFile`. Users who have already unselected `Show welcome page on startup` will have to update this setting themselves in their user settings.
The vscode welcome page also sets the configuration value to `none`, not `newUntitledFile` when the  checkbox is unchecked, so it makes sense to have the same default behavior in ADS. https://github.com/microsoft/azuredatastudio/blob/3d1e81d12e00e928554a603989202540673af785/src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.ts#L762-L771
> Change showOnStartUp default to 'none' when welcome page is not shown on startup

- package.json
- yarn.lock
Addresses #24839 
Turned out the issue was in the resolved versions for `http-proxy-agent' and 'https-proxy-agent' NPM packages.
With this change, proxy resolution is restored for extensions:
> Fix http(s)-proxy-agent dependencies

- src/vs/workbench/electron-sandbox/window.ts
Updates the download links when the emulated version of ADS is running on ARM64 MacOS
Original PR : https://github.com/microsoft/azuredatastudio/pull/24841
For https://github.com/microsoft/azuredatastudio/issues/24840
> Update MacOS ARM64 download links

- extensions/sql-migration/src/wizard/assessmentDetailsPage/assessmentDetailsPage.ts
- extensions/sql-migration/src/wizard/assessmentDetailsPage/instanceSummary.ts
This PR fixes the bug for TDE dialog. Earlier we were opening TDE dialog whenever MI as target was selected. But the experience was discussed to be changed, now TDE dialog will open up only on user click.
> [Bug Fix] New Migration Experience display UI bug

- src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts
For: https://github.com/microsoft/azuredatastudio/issues/24415
Remove extra call insertFormattedMarkdown, which is causing the duplicating issue.
> Fix markdown image 

- extensions/kusto/package.json
- extensions/kusto/package.nls.json
Command implementation was there, but command was not exposed in package.json
PR exposes the same, so logs can be opened in ADS itself.
> Expose command to show Kusto Service log

- extensions/sql-database-projects/src/common/uiConstants.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/24868.
Create project from database- Before:
Create project from database- After:
Update project from database- Before:
Update project from database- After:
> Toss out scroll bar from Project's UI

- src/sql/workbench/browser/modelComponents/text.component.ts
Addresses https://github.com/microsoft/azuredatastudio/issues/24217. This changes the role from `img` to `tooltip`, as requested by the accessibility issue.
> Set text component description role to tooltip

- extensions/mssql/package.json
Fixes https://github.com/microsoft/azuredatastudio/issues/24391
We had some design feedback that New Database should only be present at the folder level i.e. when right-clicking on the "Databases" folder. This change removes the New Database command for database nodes, which we originally added for a consistent experience with SSMS.
> Remove New Database command for Database nodes

- src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
This is to fix an issue with edit data upon revert for an invalid edit causing the current Cell to become reset when it should only be done for manual revert. (This results in additional edits after the revert on the cell not working until you move to a different row or refresh the edit session entirely).
Additionally, this PR addresses a bug where empty spaces at the end are a part of the value retrieved from the cell and that failure to delete those or overwrite them causes a "exceeded length" error, this PR adds trimming to values from the cell (and it still registers as being unchanged by the editor).
> Address issues with revert in Edit Data and also add trim to string data from cells.

- extensions/mssql/src/objectManagement/localizedConstants.ts
- extensions/mssql/src/objectManagement/ui/backupDatabaseDialog.ts
Fixes these issues:
1. Backup set name changing every time backup type is changed
2. File list going blank when adding other rows
3. File list allowing duplicate entries
> Fix lingering issues with backup database dialog

- build/azure-pipelines/win32/sql-product-build-win32.yml
Addresses https://github.com/microsoft/azuredatastudio/issues/24930. This reverts the changes to sql-product-build-win32.yml in https://github.com/microsoft/azuredatastudio/pull/21311. There no longer seems to be the issue with signing failing for `.node` files, and for some reason the minimatch pattern was not finding all the expected files. 
We'll need to keep an eye on this in case there are signing issues again due to the .node files, but vscode uses a [pattern](https://github.com/microsoft/vscode/blob/9be65968a46ecda4e4d91e4c53d58112f7647a9c/build/azure-pipelines/win32/product-build-win32.yml#L205) include that includes `*.node` (although using a differen task), so I'm less concerned about that.
> fix windows signing

- extensionsGallery.json
vbump 1.5.0 for sql migration on stable (Insider Addws with PR #24892)
This PR updates the stable extension gallery to the latest version 1.5.0 of the SQL Migration extension. 
sql-migration-1.5.0.vsix
Link to Azure Data Studio - Extensions Product pipeline run off main: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=215652&view=artifacts&pathAsName=false&type=publishedArtifacts
VSIX: https://mssqltools.visualstudio.com/_apis/resources/Containers/6336540/drop?itemPath=drop%2Fextensions%2Fsql-migration-1.5.0.vsix
> vbump 1.5.0 for sql migration on stable

- extensionsGallery-insider.json
- extensionsGallery.json
[Mongo migration 2.0.0](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTEwNDIxNjMzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-2.0.0.vsix)
> Release new version of mongo migration extension (2.0.0)

- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/api/sqlUtils.ts
- extensions/sql-migration/src/api/utils.ts
- extensions/sql-migration/src/constants/helper.ts
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dashboard/migrationDetailsTableTab.ts
- extensions/sql-migration/src/dashboard/migrationsListTab.ts
- extensions/sql-migration/src/dashboard/sqlServerDashboard.ts
- extensions/sql-migration/src/dialog/tableMigrationSelection/schemaMigrationAssessmentDialog.ts
- extensions/sql-migration/src/dialog/tableMigrationSelection/tableMigrationSelectionDialog.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
- extensions/sql-migration/src/wizard/databaseSelectorPage.ts
- extensions/sql-migration/src/wizard/targetSelectionPage.ts
**First time to table selection page, schema migration shows 'Not selected'.**
**If schema migration is enabled, assessment results will be checked. If any assessment issues that might fail schema migration are found, it will show the assessment results link to check the details.
If schema migration is not enabled, there are two cases. If there are missing tables on the target but users don't select 'migrate schema to target' option, it will show 'Not selected'. If there are no missing tables on target, it will show 'Not needed'.**
**There are three tabs after click 'Edit'：**
**The source tables exist on the target and have rows:**
**The source tables don't exist on the target and have rows:**
**The source tables dont have rows. These tables are not available to select for data migration. …
> add schema migration

- extensions/mssql/package.json
Managed instances require URL mode for backups which isn't supported in the new backup dialog yet. I also updated usage of the engineEdition context key, since "mssql:engineedition" was returning undefined.
> Disable new Backup Database dialog for managed instances

- extensions/mssql/src/objectManagement/localizedConstants.ts
- extensions/mssql/src/objectManagement/ui/principalDialogBase.ts
Fix https://github.com/microsoft/azuredatastudio/issues/24852
> Show info message when schema is empty

- extensions/sql-migration/src/dialog/assessment/assessmentUtils.ts
- extensions/sql-migration/src/dialog/assessment/importAssessmentDialog.ts
The hygiene checks started failing after https://github.com/microsoft/azuredatastudio/pull/24811 got checked in. The license was recently updated, so the headers of the files in this repo should have `MIT License` in the header now, not `Source EULA`
> fix incorrect header in sql migration files

- build/azure-pipelines/darwin/sql-product-build-darwin.yml
This PR sets the Darwin pipeline's python version to 3.11 to make it consistent with the other pipelines and seemed to fix an error about distutils missing that would cause the build to fail during the install dependencies step.
> Use python v3.11 for Darwin

- extensions/github-authentication/yarn.lock
Regenerated github-authentication extension's yarn.lock to bump some outdated vscode-tas-client dependencies that were causing this dependabot alert: https://github.com/microsoft/azuredatastudio/security/dependabot/661
> update vscode-tas-client version

- build/azure-pipelines/linux/sql-product-build-linux.yml
The extension unit tests were disabled back in June for the vscode merge. I ran an adhoc build with the extension unit tests re-enabled and they all passed, so it doesn't look like any other changes need to be made before enabling them again: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=216436&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=b2ac4860-fb3b-5a51-42a7-7423ead0721b
> Re-enable extension unit tests on linux build

- extensions/sql-migration/src/dashboard/sqlServerDashboard.ts
Bug: When assessment is imported first time it imports correct. When another assessment is imported after it, the previously imported assessment is shown again and not the new one. 
Fix: Model to new imported assessment was not updated.
> [Bug fix] Update Import model while importing assessment

- extensions/sql-migration/src/wizard/assessmentDetailsPage/assessmentDetailsPage.ts
- extensions/sql-migration/src/wizard/assessmentDetailsPage/assessmentDetialsBody.ts
- extensions/sql-migration/src/wizard/assessmentDetailsPage/treeComponent.ts
Bug : [Bug 2824863](https://dev.azure.com/msdata/Database%20Systems/_workitems/edit/2824863): We are not able to migrate few of the assessed DBs, it always selects all assessed.
Fix:  Change1 : remove `await this._body.treeComponent.initialize(this.migrationStateModel);` from `executechange` method &
change `const selectedDbs = this._dbNames.filter(db => this.model._databasesForAssessments.includes(db));` to 
`const selectedDbs = this._dbNames.filter(db => this.model._databasesForMigration.includes(db));`
Change 2: Due to above change, when a tde enabled db is selected, tde info container was not showing up.
Fix:  Update `this.model._databasesForMigration = this.selectedDbs();` whenever any db is selected or unselected. This require pass of `migrationstatemodel` to treecomponent.
Change …
> [SQL Migration] [Bugfix] Not able to migrate few of the assessed DBs, it always selects all assessed. 

- .github/workflows/basic.yml
- .github/workflows/ci.yml
Fixes GH workflow errors related to 'disutils', e.g:
https://github.com/microsoft/azuredatastudio/actions/runs/6951032805/job/18912283805#step:8:72
> Use python 3.11.x in GitHub workflows

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/assessment/importAssessmentDialog.ts
- extensions/sql-migration/src/wizard/assessmentDetailsPage/assessmentDetailsPage.ts
This PR has two changes:
1. Select all databases by default to migrate on Assessment results page. (changes in` assessmentDetailsPage.ts `file)
2. Import feedback by Abhishek -  (changes in` importAssessmentDialog.ts` file)
a. Change Import heading.
b. Select MI as default on import page and don't show no target selection page.
> Select all databases to migrate by default and Import feedback.

- extensionsGallery-insider.json
This PR updates the insider extension gallery to the latest version 1.5.1 of the SQL Migration extension. sql-migration-1.5.1.vsix
Link to Azure Data Studio - Extensions Product pipeline run off main: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=216779&view=results
VSIX Link: https://mssqltools.visualstudio.com/_apis/resources/Containers/6419380/drop?itemPath=drop%2Fextensions%2Fsql-migration-1.5.1.vsix
> vbump 1.5.1 for sql migration to inside gallery

- package.json
- src/sql/workbench/contrib/query/browser/gridPanel.ts
- src/tsec.exemptions.json
- yarn.lock
Fixes #25004 and potentially other issues related to XML data formatting, where rows are not being rendered..
Xml2js is failing to parse cell data like below, due to likely a parsing bug, failing as root node error:
```xml
'<p>What the heck?</p><p> </p><p>&nbsp;</p>'
```
Parsing Error:
```
[error] Text data outside of root node.
Line: 0
Column: 33
Char: &: Error: Text data outside of root node.
Line: 0
Column: 33
Char: &
at error (C:\Users\cmalhotra\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\sax\lib\sax.js:651:10) [<root>]
at strictFail (C:\Users\cmalhotra\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\sax\lib\sax.js:677:7) [<root>]
at SAXParser.write (C:\Users\cmalhotra\AppData\Local\Programs\Azure Data Studio …
```
> Use DomParser for xml parsing

- build/azure-pipelines/darwin/sql-product-build-darwin-signing.yml
- build/azure-pipelines/linux/sql-product-build-linux.yml
- build/azure-pipelines/web/sql-product-build-web.yml
- build/azure-pipelines/win32/sql-product-build-win32.yml
[Successful run](https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=216729&view=results) (minus release)
> Updating signing tasks to use .NET 6

- src/sql/workbench/contrib/query/browser/gridPanel.ts
Small change with PR https://github.com/microsoft/azuredatastudio/pull/25018
> Fix parserError comparison for non-XMLs

- extensions/sql-migration/src/api/sqlUtils.ts
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/models/loginMigrationModel.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/loginMigrationTargetSelectionPage.ts
- extensions/sql-migration/src/wizard/loginSelectorPage.ts
- extensions/sql-migration/src/wizard/targetSelectionPage.ts
- This PR adds the support for public endpoint for SQL Managed instance in login migration by providing a target port field along with the existing target username and password. The port was defaulted to 1433 in the backend previously which is a private endpoint default port. By provided a field to enter the port, we are adding the flexibility to enter the user desired port. The port 3342, the public endpoint default port. can also be entered now. 
- Added Port validation - the port number is a required field and the value entered should be a valid number in the range of 0-65535. The connect button gets enabled on the valid port value along with existing checks.
- Added logic to generate MI target server name based on the endpoint selected (public or private)
Public endpoint format: …
> Added support of MI public endpoint in Login Migration

- extensions/mssql/src/objectManagement/localizedConstants.ts
- extensions/mssql/src/objectManagement/ui/backupDatabaseDialog.ts
- extensions/mssql/src/objectManagement/ui/restoreDatabaseDialog.ts
When clicking script in the Restore Database dialog, it kept showing a message saying there was no action to be scripted even though a script window was being opened in the background. The dialog needed to have its opensEditorSeparately flag set to true, since the Restore scripting operation opens an editor separately from the usual object management workflow.
Also fixed some unlocalized strings in the backup dialog while I was at it.
> Fix restore dialog not showing a message after clicking Script

- src/sql/workbench/contrib/commandLine/electron-sandbox/commandLine.ts
- src/sql/workbench/contrib/commandLine/test/electron-browser/commandLine.test.ts
Discussed here: https://github.com/microsoft/azuredatastudio/issues/25055#issuecomment-1830834739
Fixes an issue where command line interface always connects connection profile despite user specifying 'openConnectionDialog'.
> Fix to not connect when opening connection dialog

- extensionsGallery.json
This PR updates the SQL Migration extension version to 1.5.1 into stable gallery.
Insider Gallery vBump PR: https://github.com/microsoft/azuredatastudio/pull/25028
> vBump sql-migration 1.5.1

- extensionsGallery-insider.json
- extensionsGallery.json
Adds [Catppuccin for Azure Data Studio](https://github.com/catppuccin/vscode) to both `extensionsGallery` and `extensionsGallery-insider`.
It's pulling from our VSCode theme, but the VSIX is a special build for ADS.
> add Catppuccin theme extension

- extensions/integration-tests/package.json
- extensions/integration-tests/yarn.lock
Updating azdata-test version to remove the dependency on `debug@^2.2.0`, causing this alert https://github.com/microsoft/azuredatastudio/security/dependabot/596.
azdata-test was updated in the other extensions in https://github.com/microsoft/azuredatastudio/pull/24978.
> update azdata-test version in extensions/integration-tests

- extensionsGallery-insider.json
- extensionsGallery.json
- scripts/validateGalleries.js
We currently shouldn't have any (non-trusted) external extensions as direct VSIX installs. This is adding a check for that and updating the one extension that needed fixing.
> Add trusted publishers check for galleries

- extensionsGallery-insider.json
- extensionsGallery.json
This is the link to download latest vsix
[migration extension 2.0.2](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTEyNzI4ODA4L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-2.0.2.vsix)
> Release 2.0.2 of Mongo migration extension

- src/sql/workbench/services/restore/browser/restoreDialog.ts
> Add restore from url for SQL Server

- extensionsGallery-insider.json
Please find the binary [here](https://msdata.visualstudio.com/_apis/resources/Containers/226559185/drop?itemPath=drop%2Fazure-cosmosdb-ads-extension-0.4.0.vsix).
The binary size has increased as we are shipping a new query editor app and a .net proxy. (We might move it to the storage in the future is size is an issue)
We are only releasing to insider for now, while we work on ADS to support the new type of resource.
> Release Cosmos DB extension v0.4.0 to insider gallery

- src/sql/platform/connection/common/providerConnectionInfo.ts
Potentially addresses #25078 
Default values could be non-strings, it seems to cause #25078 for some connection profiles.
> Convert to string before locale lower case

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/tableMigrationSelection/tableMigrationSelectionDialog.ts
Issue:
If tables in "Missing on target" tab are selected, schema migration option won't be checked automatically. It causes that the selected tables dont exist in target and fail the SqlInfoCollector validation.
Fix:
if users don't select schema migration option and just select the tables in "missing on target" tab, enable schema migration automatically.
> [SQL Migration] Fix schema migration table selection issue

- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/api/sqlUtils.ts
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/tableMigrationSelection/tableMigrationSelectionDialog.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
- extensions/sql-migration/src/wizard/targetSelectionPage.ts
1. adding IR version validation. Before going to RP, if users enable schema migration and the IR node doesn't support schema migration, disable the schema migration option. The SQLDB migration validation failure rate will have significant reduction.
2. Windows login is currently supported in SHIR. Therefore, if users use WIndows auth to connect the source instance for schema mgiration, disable the schema migration option. The SQLDB migration failure due to "login failed for user" will have significant reduction.
In Step 4, adding infor banner
In Step 6, check the IR nodes version and windows login. If true, show the warning message on the top and disable the schema migration option.
> [SQL Migration] Add schema migration validation

- extensions/sql-migration/src/api/azure.ts
RP saves the schema migration errors in the errors list of SqlSchemaMigrationStatus.
> [SQL Migration] Populate schema migration errors to UI

- .github/workflows/basic.yml
- .github/workflows/ci.yml
Ports #25019 to release/1.47 branch to fix GitHub CI workflows.
> [Release/1.47] Use python 3.11.x in GitHub workflows (#25019)

- build/azure-pipelines/darwin/sql-product-build-darwin.yml
Ports #24976 to release/1.47 to fix ADO macOS issues.
> [Release/1.47] Use python v3.11 for Darwin (#24976)

- build/azure-pipelines/linux/sql-product-build-linux.yml
Fixes extension pipeline builds, recently affected by #24977 
+Update code signing task version
> Fix pipeline to not sign deb/rpm if built for extensions only

- build/azure-pipelines/darwin/sql-product-build-darwin-signing.yml
- build/azure-pipelines/linux/sql-product-build-linux.yml
- build/azure-pipelines/web/sql-product-build-web.yml
- build/azure-pipelines/win32/sql-product-build-win32.yml
Ports #25021 to release/1.47 branch
* Updating signing tasks to EsrpCodeSigning@3
* Updating .NET versions
* removing UseDotNet steps
* Restoring UseDotNet for linux builds
> [Release/1.47] Updating signing tasks to use .NET 6 (#25021)

- build/azure-pipelines/win32/sql-product-build-win32.yml
The windows builds started consistently failing on the initial run over a week ago with the error "There is not enough space on the disk". This should free up space, similar to fix made a couple months ago for linux builds in https://github.com/microsoft/azuredatastudio/pull/24539.
Adhoc build (with signing enabled like the nightly product build): https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=219026&view=logs&j=471dc74f-2452-533b-c058-e43cd1b98abf&t=69447ecb-e768-5cc0-89bc-3e5a8b725059
> delete compilation.tar.gz after extracting for windows pipeline

- extensionsGallery-insider.json
- extensionsGallery.json
* Added extension settings that will let the user to customize the extension behaviour. 
* Columns ordering can be changed from the extension settings. Since now the columns have been ordered alphabetically by default. From now on, the default ordering will be the ordinal ordering, but from the extension settings is possible to enable the alphabetical ordering. It also possible to choose if the primary key columns must be shown as first columns. 
* Columns ordering can also be changed by clicking on the columns name header. This overrides the settings, but once enabled, can be disabled repeating clicking on the header until the sorting icon disappears. 
* The status of some controls is now persisted in the extension settings. The persisted controls are: `page size`, `show tables`, `show …
> Updated extension SqlDataInspector to 0.7.2

- build/azure-pipelines/win32/sql-product-build-win32.yml
Ports #25089 to release/1.47 branch.
Addresses https://github.com/microsoft/azuredatastudio/issues/24964
> [Release/1.47] Codesign unis000.exe with ESRP client (#25089)

- extensionsGallery-insider.json
- extensionsGallery.json
- scripts/validateGalleries.js
VS Code requires PNG (since SVGs can contain code) so enforcing that for us as well.
Also updating the pieces-azure-data-studio extension to use a direct commit link n(follow up from https://github.com/microsoft/azuredatastudio/pull/25173) to reduce the chance of changes to master breaking the gallery. I'm trying to think of a good way to enforce this as well and will follow up with adding a check for that if I come up with one - but for now we'll just ask people to update them as they submit new extensions.
FYI @caleb-at-pieces
> Only allow PNG icons in gallery and use commit link for pieces-azure-data-studio

- build/actions/yarn.lock
- build/yarn.lock
- extensions/azurecore/yarn.lock
- extensions/github-authentication/yarn.lock
- extensions/resource-deployment/yarn.lock
- extensions/sql-bindings/yarn.lock
- extensions/sql-database-projects/yarn.lock
Updating follow-redirects to update it from version 1.15.3 to 1.15.4 to fix a vulnerability.
> Update follow redirects dependency to 1.15.4 for release branch 1.47

- build/actions/yarn.lock
- extensions/azurecore/yarn.lock
- extensions/github-authentication/yarn.lock
- extensions/resource-deployment/yarn.lock
- extensions/sql-bindings/yarn.lock
- extensions/sql-database-projects/yarn.lock
Updating follow-redirects to update it from version 1.15.3 to 1.15.4 to fix a vulnerability.
> Update follow redirects dependency to 1.15.4 for release branch 1.41

- extensionsGallery-insider.json
- extensionsGallery.json
Updating import and data virtualization extensions to bring in the MDS update in their services. I tested installing these two extensions from this build and that the correct services versions were downloaded and the wizards started up.
Build with vsixes: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=219502&view=artifacts&pathAsName=false&type=publishedArtifacts
> update import and data virtualization extensions

- extensions/sql-migration/src/api/azure.ts
- extensions/sql-migration/src/api/sqlUtils.ts
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/tableMigrationSelection/tableMigrationSelectionDialog.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
- extensions/sql-migration/src/wizard/targetSelectionPage.ts
Background:
SHIR 5.37.8767.4 (Will be released on 1/12/2024) supports Windows login to connect source instance. Therefore, update the schema migration info message and validation.
Changes:
1. Update the info message in step 4.
2. Update the schema migration validation. 5.37 is the min version supporting schema migration.
> [SQL Migration] Schema migration support Windows login

- extensions/sql-migration/config.json
- extensions/sql-migration/src/service/contracts.ts
- extensions/sql-migration/src/service/features.ts
- Updated the new version of SQL tools service from 4.11.0.13 to 4.11.0.17 that created 4 RPC corresponding to the below validation api's
1. ValidateSysAdminPermissions
2.  ValidateAADDomainName
3. ValidateLoginEligibility
4. ValidateAADDomainName
- Created the RPC requests for the validation API's 
1. ValidateSysAdminPermissionRequest
2. ValidateUserMappingRequest
3. ValidateAADDomainNameRequest
4. ValidateLoginEligibilityRequest
- Testing
Tested all the RPC calls to the validation API's by consuming the sqltoolsservice in the ADS client locally.
> Added Login Migration Validation API RPC support

- src/sql/workbench/services/connection/browser/connectionManagementService.ts
Fixes command-line behavior where email address wouldn't work when trying to connect using Azure MFA.
E.g. 
`azuredatastudio --server <serverName> --authenticationType AzureMFA --user <email address> --command connect`
Before:
Launches ADS, but doesn't connect immediately, opens connection dialog instead. Below errors are captured in logs:
```
Could not find Azure account with name undefined
Failed to connect due to error: Error
```
After:
Launches ADS and creates a new connection if email address is found associated with an Azure account.
> Fixes azure account detection to work with email address

- extensions/mssql/src/objectManagement/localizedConstants.ts
- extensions/mssql/src/objectManagement/ui/databaseFileDialog.ts
- extensions/mssql/src/objectManagement/ui/restoreDatabaseDialog.ts
For https://github.com/microsoft/azuredatastudio/issues/25129
Adds a "Browse files" aria label for browse buttons that only have an ellipsis label ('...').
> Add aria labels for browse files buttons

- src/vs/code/electron-sandbox/issue/issueReporterService.ts
Addresses https://github.com/microsoft/azuredatastudio/issues/24219.
This adds an aria label to the description area in the issue reporter. The title changes between "Steps to Reproduce" and "Description" depending on if it's a bug or a feature request.
Description:
Steps to Reproduce:
> add aria label for issue reporter's description text area

- extensionsGallery-insider.json
- extensionsGallery.json
his PR updates the insider extension gallery to the latest version 1.5.2 of the SQL Migration extension. sql-migration-1.5.2.vsix
Link to Azure Data Studio - Extensions Product pipeline run off main: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=219911&view=results
VSIX Link: https://mssqltools.visualstudio.com/_apis/resources/Containers/6671724/drop?itemPath=drop%2Fextensions%2Fsql-migration-1.5.2.vsix
> vbump 1.5.2 for sql migration to inside gallery

- extensions/sql-migration/src/dialog/tableMigrationSelection/tableMigrationSelectionDialog.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
The current code was failing for scenarios when DMS service and target are in different resource groups. 
Updated the correct resource group for DMS Service in IR Validation checks.
For more context regarding validation - https://github.com/microsoft/azuredatastudio/pull/25138
> [Fix] Updated the correct resource group for DMS Service check.

- extensionsGallery-insider.json
This PR updates the insider extension gallery to the latest version 1.5.3 of the SQL Migration extension. sql-migration-1.5.3.vsix
Link to Azure Data Studio - Extensions Product pipeline run off main: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=220472&view=results
VSIX Link: https://mssqltools.visualstudio.com/_apis/resources/Containers/6717657/drop?itemPath=drop%2Flangpacks&%24format=zip&saveAbsolutePath=false
> vbump 1.5.3 sql-migration (Hot Fix ) to InsiderGallery

- extensions/mssql/package.json
- extensions/mssql/src/objectManagement/localizedConstants.ts
- extensions/mssql/src/objectManagement/ui/restoreDatabaseDialog.ts
Closes https://github.com/microsoft/azuredatastudio/issues/25247
Adds the Restore Database command to the context menu for the Databases folder so a user doesn't need to create a database first before restoring it. I also fixed 2 other issues:
1. An incorrect section name for the restore plan section.
2. A bug where the source database dropdown would not get properly updated when switching between Database and File restore modes.
3. A bug where the target database name wasn't getting updated when switching between different restore sources.
Since there's no database context when opening the Restore dialog from a folder, the dialog will be initially populated with the first entry in the source database list.
> Add Restore Database command to Databases folder

- extensionsGallery.json
This PR updates the Stable extension gallery to the latest version 1.5.3 of the SQL Migration extension. sql-migration-1.5.3.vsix
Link to Azure Data Studio - Extensions Product pipeline run off main: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=220472&view=results
VSIX Link: https://mssqltools.visualstudio.com/_apis/resources/Containers/6717657/drop?itemPath=drop%2Flangpacks&%24format=zip&saveAbsolutePath=false
> vbump 1.5.3 sql-migration (Hot Fix ) to Stable Gallery

- extensions/mssql/src/objectManagement/ui/backupDatabaseDialog.ts
- extensions/mssql/src/objectManagement/ui/objectManagementDialogBase.ts
- extensions/mssql/src/objectManagement/ui/restoreDatabaseDialog.ts
- extensions/mssql/src/objectManagement/ui/serverPropertiesDialog.ts
- extensions/mssql/src/ui/dialogBase.ts
When performing backup & restore operations from the new admin dialogs, two tasks were being started in the tasks pane. This is because STS starts its own task in the background when doing the restore operation, in addition to the one that always gets started when clicking OK in an admin dialog. This change skips starting a background task on OK if the dialog is a backup or restore one. I refactored the submit logic for the dialogs so that they start a background task in the Dialog `onClosed` callback, rather than registering a background task up front in `initialize` that then gets started after closing. Subclass dialogs then extend the `handleDialogClosed` callback method registered for `onClosed` to add more functionality.
Fixes https://github.com/microsoft/azuredatastudio/issues/25105
> Skip starting a separate task for backup and restore operations

- extensions/mssql/src/objectManagement/ui/databaseDialog.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/24193
I increased the max number of rows in the table before it will create an internal scrollbar. The dialog instead becomes scrollable if the table is too large. This prevents the table from "flickering" after updating due to having to reselect the previously selected row after updating it, causing the whole table to refresh and then immediately scroll down for items at the bottom.
Screenshots:
> Increase max size of DB Scoped Config table to remove table scrollbar

- extensions/mssql/src/objectManagement/ui/restoreDatabaseDialog.ts
When first switching to File mode in the Restore dialog, the loading spinner in the corner would keep running forever without any data showing up in the table. This is because an error was being thrown (from the ModelView code) due to an undefined value in the source database dropdown, and so resetting the loading state would get skipped. This change fixes that undefined string issue and also adds a try-finally block for the loading logic so it doesn't get stuck on error.
> Handle undefined source database name in restore dialog

- extensions/sql-database-projects/src/tools/buildHelper.ts
Updated from 161.8817.2 to 161.8910.0 version
> vBump ScriptDom version for sql projects

- src/sql/workbench/browser/modal/media/modal.css
- src/sql/workbench/browser/modal/modal.ts
For: https://github.com/microsoft/azuredatastudio/issues/25124
I needed to add an extra div to include the scrollbar to the dialog content and the dialog footer.
Adding more examples of this: 
Adding a database user
Restore database
Deployment options wizard:
> Modal dialogs become unreadable after applying max zoom

- extensions/mssql/src/objectManagement/ui/S3AddBackupFileDialog.ts
- extensions/mssql/src/objectManagement/ui/restoreDatabaseDialog.ts
-Add some checks to verify that S3 Url dialog result is not undefined
> Add checks for undefined

- build/npm/gyp/yarn.lock
- remote/yarn.lock
- yarn.lock
Updating the `socks` package to resolve to version 2.7.3 that no longer has a dependency on the `ip` npm package, which has the vulnerability https://github.com/advisories/GHSA-78xj-cgh5-2h22.
> update socks package to remove dependency on ip npm package

- extensions/notebook/src/jupyter/jupyterServerInstallation.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/25049
If there's an error when retrieving the list of python packages we return an empty array instead. In most places we iterate over this list, so being empty isn't an issue. In this spot we were using a `find` call though, which would return undefined when the array is empty. This change adds an undefined check before using the results of that find call.
> Handle empty package list during python installation

- src/vs/workbench/contrib/search/browser/searchView.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/24877
The search bar used in the notebook viewlet overrides the default search view rendering behavior, which means the include/exclude pattern objects in the base class never get created. This was causing undefined errors when trying to open the notebook find results in the editor, so the fix here was just to add some optional chaining operators. We weren't using include & exclude patterns for notebook searches, so there's no issue leaving those as undefined. I checked the console log and no errors were getting reported from passing undefined values either.
> Add null checks for undefined include/exclude patterns in search view

- src/vs/workbench/contrib/search/browser/searchView.ts
Closes https://github.com/microsoft/azuredatastudio/issues/24877
> Add null checks for undefined include/exclude patterns in search view (#25336)

- .github/workflows/on-pr-open.yml
Opening this PR to see if the permissions issue is fixed with the PR labelling action.
Edit: Label action succeeded, so we can actually merge this change
> Add write permissions to PR labelling action

- .github/workflows/on-pr-open.yml
Porting action fix to release branch. This action only runs for release port request PRs, so we need it here.
Fixes https://github.com/microsoft/azuredatastudio/issues/25360
> Add write permissions to PR labelling action (#25356)

- extensions/notebook/src/book/bookTocManager.ts
- extensions/notebook/src/book/githubRemoteBook.ts
- extensions/notebook/src/extension.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/25369
Commands registered for the notebook viewlet actionbar get passed a BookTreeItem as an argument. The openNotebookFolder command registration had a string as its first argument though, so when it was passed a BookTreeItem it tried to treat it as a string, which led to errors elsewhere.
> Fix arguments for openNotebookFolder command registration

- src/sql/workbench/services/connection/browser/connectionWidget.ts
Addresses #25378 
Use Widget's value instead of value provided by selection event, which is diaplay value by design.
> Fix custom options selection event

- extensions/mssql/config.json
This PR adds the fix for the issue causing to the dacfx extensions to fail with DacFX-net8.0 version support. updating STS release version generated from the STS/main branch to ADS/main branch.
> MainVBump STS to 4.12.0.3

- extensions/mssql/config.json
This PR adds a fix to the DacFx net8.0 version causing issues.
> STS vBump to 4.11.1.1

- extensions/mssql/package.json
For https://github.com/microsoft/azuredatastudio/issues/25366
We already have Drop commands in the context menu, so the inline commands are unnecessary and can be clicked accidentally.
> Remove inline commands for dropping objects

- extensions/sql-migration/config.json
- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/dialog/assessment/assessmentUtils.ts
- extensions/sql-migration/src/dialog/restartMigration/restartMigrationDialog.ts
- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/service/contracts.ts
- extensions/sql-migration/src/service/features.ts
- extensions/sql-migration/src/wizard/databaseSelectorPage.ts
This PR:
Adds UI to ask customer to collect Ad-hoc queries using QDS and based on selection send boolean parameter to service to trigger collection and extraction.
Testing:
When Collect ad hoc query using QDS : we have following output true coming from nuget
> QDS ADS integration

- extensions/sql-migration/config.json
Taking latest version of sqltoolservice which having fix for SKU recommendation issues.
Issue: Recommending SKU way higher than the requirements in EU region due to Double parsing in local culture. Format mismatch was the root-cause.
> Update SQL Tools migration service version.

- extensions/mssql/src/objectManagement/ui/databaseDialog.ts
Changes were already approved, just that they weren't actually included in the PR: #25325 This PR actually adds in the new declarative table. The changes made to databaseDialog were accidentally removed while trying to revert it to an earlier version
> Added in missed changes for databaseDialog

- package.json
- remote/package.json
- remote/web/package.json
- remote/web/yarn.lock
- remote/yarn.lock
- yarn.lock
For some reason, nvda browse mode wasn't working when I set query plan's role as tree view. However, changing the role to 'group' made it work.
Issue: #20777
>  Fixing nvda browse mode in query plan

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
Change - 
If the user clicks on the "Validation Button"  before entering mandatory data such as Storage account details, Network share credentials, etc. It does not validation, instead, it throws an error that data in some fields are missing.
> Fill mandatory fields to run validations.

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/wizard/databaseSelectorPage.ts
> Disable QDS on UI

- extensionsGallery-insider.json
This PR updates the insider extension gallery to the latest version 1.5.4 of the SQL Migration extension.
Link to Azure Data Studio - Extensions Product pipeline run off main: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=222581&view=results
VSIX Link: https://mssqltools.visualstudio.com/_apis/resources/Containers/6909296/drop?itemPath=drop%2Fextensions%2Fsql-migration-1.5.4.vsix
> vbump 1.5.4 for sql migration to inside gallery

- extensionsGallery.json
This PR updates the insider extension gallery to the latest version 1.5.4 of the SQL Migration extension.
Link to Azure Data Studio - Extensions Product pipeline run off main: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=222581&view=results
VSIX Link: https://mssqltools.visualstudio.com/_apis/resources/Containers/6909296/drop?itemPath=drop%2Fextensions%2Fsql-migration-1.5.4.vsix
> vbump 1.5.4 for sql migration to extension gallery

- extensionsGallery-insider.json
- extensionsGallery.json
This is a maintenance release: the build is now properly signed and from an Official OneBranch build.
Please find the binary [here](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTIxOTcxMzc2L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2Fazure-cosmosdb-ads-extension-0.4.3.vsix).
> Upgrade Cosmos DB extension to v0.4.3

- extensionsGallery-insider.json
- extensionsGallery.json
[Mongo migration 2.1.0](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTIxOTY2Mzk3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-2.1.0.vsix)
> Release new version of mongo migration extension (2.1.0)

- extensionsGallery-insider.json
- extensionsGallery.json
There was an issue on yesterday's release.
This is a patch to fix it.
New VSIX Location: https://artprodscussu1.artifacts.visualstudio.com/A011b8bdf-6d56-4f87-be0d-0092136884d9/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RldmRpdi9wcm9qZWN0SWQvMGJkYmM1OTAtYTA2Mi00YzNmLWIwZjYtOTM4M2Y2Nzg2NWVlL2J1aWxkSWQvOTI5MjkzNS9hcnRpZmFjdE5hbWUvdnNpeA2/content?format=file&subPath=%2Fvscodeintellicode-1.3.1.vsix
> Update intellicode VSIX to 1.3.1

- samples/extensionSamples/yarn.lock
- samples/sp_whoIsActive/yarn.lock
- samples/sqlservices/yarn.lock
The new pipelines flagged `minimist 1.2.5` needing to be updated because of this vulnerability: https://github.com/advisories/GHSA-xvch-5gv4-984h
It was previously dismissed as the vulnerability not being used, I figured might as well update it since it's a small change and only in the sample code.
> update places with minimist 1.2.5

- extensions/kusto/config.json
- extensions/mssql/config.json
Updating the version of STS that the Kusto extension uses to one that has signed dlls, since it got flagged in the new ADS Extensions pipeline. I did a quick check locally to make sure it downloads and the Kusto Service starts, but I'm not planning on releasing a new version of the Kusto extension. This change is just necessary to unblock the new ADS extension pipeline.
Too many differences to screenshot, but here's a link to the differences for the STS used by the Kusto extension: https://github.com/microsoft/sqltoolsservice/compare/4.11.0.20...5.0.0.2
Also updating STS in mssql for consistency. Differences for STS used by mssql: https://github.com/microsoft/sqltoolsservice/compare/4.12.0.3...5.0.0.2
> Update Kusto STS version to 5.0.0.2

- extensions/sql-migration/package.json
- extensions/sql-migration/yarn.lock
updated the node module version to fix the issue. This seems to be known issue with the older versions of azure/storage-blob module.
found similar issue here - https://github.com/Azure/azure-sdk-for-js/issues/28059#issuecomment-1971053922
ADO bug link - https://msdata.visualstudio.com/Database%20Systems/_workitems/edit/3044065
> Upload to blob container fix

- extensionsGallery-insider.json
- extensionsGallery.json
[Mongo migration 2.1.1](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTI0MDM4ODYyL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-2.1.1.vsix)
> Release new version of mongo migration extension (2.1.1)

- extensions/notebook/src/dialog/configurePython/configurePathPage.ts
The Configure Python dialog currently has a placeholder component where the install selection controls get hidden if a python instance is already setup. After removing the New Python Install option last week, there aren't many controls to hide behind that placeholder, so it would be better to remove it. Note that if python is already setup, the path selection dropdown will have the current python instance as its default first value.
How dialog opens when python is already setup:
> Remove path placeholder components in Configure Python dialog

- extensionsGallery-insider.json
Follow up to https://github.com/microsoft/azuredatastudio/pull/25634
Since I will be gone after this week, this will need to be ported to the main gallery once the RC1 branch is out, (just bump to 1.49 as done here)
Build with artifacts here:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=225682&view=artifacts&pathAsName=false&type=publishedArtifacts
> update to insiders gallery for release branch 1.49 release

- extensionsGallery-insider.json
- extensionsGallery.json
Updates the Catppuccin theme initially added in #25077.
There are a few additional branch name & path changes, because the source repo changed to a monorepo.
> bump Catppuccin theme to v3.14.0

- extensionsGallery-insider.json
- extensionsGallery.json
Updating SQL MI dashboard extension to 0.4.3
This version introduces support for Next-Gen General Purpose edition, as well as aligns the extension with the increased limits for log rate, as well as new hardware generations and their memory limitations
> Updating SQL MI dashboard extension to 0.4.3

- extensionsGallery-insider.json
- extensionsGallery.json
Update extension gallery metadata to use the latest stable release of Copilot extension.
> Bump Copilot extension to 1.199.0

- src/vs/platform/update/electron-main/updateService.darwin.ts
**Problem:**
After switching to static file based update feed, we are seeing infinite update loop on `macOS` when the current ADS is the latest version.
**Root cause:**
For `macOS`, ADS uses the [autoUpdater](https://www.electronjs.org/docs/latest/api/auto-updater) in `electron` for auto update, which is different from `windows`/`linux` update behavior. Previously we used an update server as the update feed for `autoUpdater`. In that case the update server would return `200` and the build metadata when an update is available and return `204(No Content)` if there's no update, the version check is done on the server side.
In my previous PR https://github.com/microsoft/azuredatastudio/pull/25677, I changed the updater feed url to a static metadata file that contains the latest build …
> Fix Mac update loop

- build/azure-pipelines/sql-product-build.yml
- build/azure-pipelines/sql-product-compile.yml
Since we've removed our custom infrastructure from Azure, the release branch needs to be updated.
This change was originally part of [this commit](https://github.com/microsoft/azuredatastudio/commit/11c8e67ea6c9e65be54790e76714a97980954ea4#diff-7d483a5cbd2f5f973879bdca17fd3f2695ade79289e63a5212934289381ca2d0), but I'm being more selective with the port to the release branch.
> [Port] Changing container image from custom to standard ubuntu

- build/gulpfile.vscode.win32.js
The new internal official pipeline requires this gulp task.  Porting it to `release/1.48` allows us to fully validate the new pipeline against the release branch. 
Dependent on https://github.com/microsoft/azuredatastudio/pull/25706 to get PR builds against this release branch to run.
> [Port] Adding gulp task that adds ads metadata to exe file.  (#25665)

- scripts/validateGalleries.js
Getting this error
`sql-search - Error fetching Microsoft.SQLOps.DownloadPage with URL https://www.redgatefoundry.com/SQLSearch. HTTPError: Response code 503 (Service Unavailable: Back-end server is at capacity)`
So just skipping for now so the validation script can run successfully.
> Skip sql-search extension file validation

- src/sql/workbench/contrib/connection/browser/connectionStatus.ts
This PR fixes #25409
The PR makes sure the `resource` property on the `activeEditor` contains a truthy value before `toString` is invoked.
> Add missing check before calling toString

- extensionsGallery-insider.json
- extensionsGallery.json
[Mongo migration 3.1.0](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTMyODQ2NDE3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-3.1.0.vsix)
> Release new version of mongo migration extension (3.1.0)

- extensions/kusto/config.json
- extensions/mssql/config.json
Update to latest STS to 5.0.20240716.2 to pickup transaction isolation level and Azure Identity vbump.
> Update to latest STS

- src/sql/workbench/api/common/extHostModelView.ts
Fix this issue: https://github.com/microsoft/azuredatastudio/issues/25443
> Fixed column screen reader bug and ensure tests work

- extensions/sql-database-projects/README.md
- extensions/sql-database-projects/resources/templates/newSdkSqlProjectTemplate.xml
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/common/utils.ts
- extensions/sql-database-projects/src/sqldbproj.d.ts
- extensions/sql-database-projects/src/tools/buildHelper.ts
- extensions/types/vscode-mssql.d.ts
- src/sql/azdata.d.ts
- src/sql/workbench/api/common/sqlExtHostTypes.ts
This PR adds the sql fabric database support to the sql projects extension. And also updating the BuildSdk version to 0.2.0-perview that supports the fabric platform.
> Adding Fabric SQL Mirrored support to the SQL Projects

- extensionsGallery-insider.json
- extensionsGallery.json
[Mongo migration 3.1.1](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTM1NTg4ODk2L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-3.1.1.vsix)
> Release new version of mongo migration extension (3.1.1)

- extensions/sql-database-projects/src/common/utils.ts
The mssql API returns the engine edition to be 5 (SqlDatabase) for Fabric DW, which might be a bug in itself. Since the server name check would only be applicable to the 2 valid Fabric DW domain, this change should be fine.
Fixes #25811
> Fix SQL version determination logic for Fabric DW

- build/gulpfile.vscode.win32.js
This fixes issue https://github.com/microsoft/azuredatastudio/issues/25804.
> Use the correct version variable for file metadata

- src/vs/platform/extensionManagement/common/extensionGalleryService.ts
- src/vs/platform/extensionManagement/common/extensionManagementUtil.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/25819.  There are two issues, first is that the vscode & ads engine versions are being incorrectly checked during update scan and second the Copilot extension has inconsistent ID values in package.json and extensionsGallery.json files causing uninstall of current extension version to fail during update process.
> Fix bugs blocking extension upgrade

- extensionsGallery-insider.json
- extensionsGallery.json
Update Powershell extension and correct publisher.  The mismatched publisher value in extension manifest and extension gallery file is causing issues with update checks with latest Extension Manager changes in hotfix.  https://github.com/microsoft/azuredatastudio/issues/25843.
> Update Powershell extension and correct publisher

- src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
This PR will fix #25536
Before:
After:
> Fix apostrophe escape issue in table designer

- src/sql/workbench/browser/editor/profiler/profilerInput.ts
A .xel file produced outside of SQL Server may contain a different set of columns. Since Azure Data Studio's SQL Server Profiler has its own set of display columns, these non-default ones are simply ignored.
This PR adds support for displaying non-default columns in the details section while preserving the default behavior that fixes #25906 issue.
Before:
After:
> Displaying non-default columns for local .xel files

- extensions/azuremonitor/package.json
- extensions/azuremonitor/yarn.lock
- extensions/datavirtualization/package.json
- extensions/datavirtualization/yarn.lock
- extensions/import/package.json
- extensions/import/src/test/utils.test.ts
- extensions/import/yarn.lock
- extensions/kusto/package.json
- extensions/kusto/yarn.lock
- extensions/mssql/config.json
- extensions/mssql/package.json
- extensions/mssql/yarn.lock
- extensions/sql-migration/package.json
- extensions/sql-migration/yarn.lock
- src/sql/azdata.proposed.d.ts
- src/sql/workbench/api/browser/mainThreadDataProtocol.ts
- src/sql/workbench/api/common/extHostDataProtocol.ts
- src/sql/workbench/api/common/sqlExtHost.protocol.ts
- src/sql/workbench/contrib/query/browser/query.contribution.ts
- src/sql/workbench/services/query/common/queryManagement.ts
- src/sql/workbench/services/query/common/queryModelService.ts
- src/sql/workbench/services/query/common/queryRunner.ts
- src/sql/workbench/services/query/test/common/testQueryManagementService.ts
This PR will fix https://github.com/microsoft/azuredatastudio/issues/25632
The other PR's needed for this PR:
sqlops-dataprotocolclient - https://github.com/microsoft/sqlops-dataprotocolclient/pull/101
sqltoolsservice - https://github.com/microsoft/sqltoolsservice/pull/2385
The reason copying was very slow from the SQL Tools Service was because `ToString` was repeatedly being called on the `StringBuilder` before `EndsWith`: https://github.com/microsoft/sqltoolsservice/blob/18ffbe6d76c511881a76f636d2e59467dfe8c4d6/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/QueryExecutionService.cs#L866
In the PR for the SQL Tools Service `ToString` is only called once to correct this issue. With this correction in place, copying from STS is significantly faster, as can be seen in this gif where …
> Speed up query results copying

- extensions/notebook/src/jupyter/requiredJupyterPackages.ts
Fixes #25327. Allows Python 3.12+ runtime configuration.
Related: https://github.com/zeromq/pyzmq/issues/2030#issuecomment-2337602511
> Bumped `notebook` version to `7.2.2`

- extensions/sql-migration/src/constants/strings.ts
- extensions/sql-migration/src/wizard/loginSelectorPage.ts
This PR takes care of  2 more validation scenarios
1. Cx succesfully validates with a set of logins , and now cx selects a new login and proceed for migration without validation. We shouldn't allow this
2. Cx selects a windows login, successfully validates it, but now changes the entra. We shouldn't allow this
> Adding validations for change in aad and logins after a successful validation

- extensions/sql-migration/config.json
This PR consumes the latest STS release having the latest login nuget that modifies the AAD errors to MicrosoftEntraDomain Errors (due to the name change)
> Consuming Latest Sql Tools Service

- extensions/mssql/snippets/mssql.json
This snippet in particular is conflicting with DESC keyword and causing a problem that has been reported a few times, e.g., https://github.com/microsoft/azuredatastudio/issues/25762. This doesn't fix the underlying issue with the keyword & snippets conflicting all-up, but it resolved the most common rough spot. And the snippet isn't really that useful (compared to DESC keyword)
> Remove sqlDropStoredProc snippet which conflicts with DESC keyword

- extensions/mssql/config.json
> bumping STS to match mssql dependency

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseQuickpick.ts
- extensions/sql-database-projects/src/test/dialogs/createProjectFromDatabaseQuickpick.test.ts
When creating a project from database via VS Code quickpick, the connection data is never passed to the controller, so it always defaulted to 160/Sql2022 target platform in the sqlproj. There used to be an option to create project from right clicking on a database in mssql, but it was removed at some point, making quickpick the only option. This PR fixes the code path via quickpick by passing the create project function as a callback.
> Fix target platform when creating project from database via quickpick

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseQuickpick.ts
- extensions/sql-database-projects/src/test/dialogs/createProjectFromDatabaseQuickpick.test.ts
Fixes #26052 
Porting #26049 and #26053
When creating a project from database via VS Code quickpick, the connection data is never passed to the controller, so it always defaulted to 160/Sql2022 target platform in the sqlproj. There used to be an option to create project from right clicking on a database in mssql, but it was removed at some point, making quickpick the only option. This PR fixes the code path via quickpick by passing the create project function as a callback.
> [Port to release/1.50] Fix target platform when creating project from database via quickpick

- .github/workflows/codeql.yml
- extensions/sql-migration/src/dashboard/migrationsListTab.ts
- extensions/sql-migration/src/wizard/databaseBackupPage.ts
- extensions/sql-migration/src/wizard/integrationRuntimePage.ts
Added required indicator in sql migration extension experience:
1) For subscription field
2) For database backup fields
Linked issue: https://github.com/microsoft/azuredatastudio/issues/25919
Task link: https://dev.azure.com/msdata/Database%20Systems/_workitems/edit/3563160
Fix:
**Before:**
**After:**
> Add required indicators to fields

- extensions/sql-migration/src/wizard/assessmentDetailsPage/assessmentDetailsHeader.ts
Import assessment Wizard failed to load because the fields _viewDetailsLink , _generateTemplateLink , _separator were undefined
Added a null check for the fields to fix the issue.
ADO task - https://msdata.visualstudio.com/Database%20Systems/_workitems/edit/3297592/?view=edit
The import assesment wizard is loading now -
> import assessment wizard fix

- extensions/sql-database-projects/README.md
- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/resources/templates/newSdkSqlProjectTemplate.xml
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseQuickpick.ts
- extensions/sql-database-projects/src/test/dialogs/createProjectFromDatabaseQuickpick.test.ts
- extensions/sql-database-projects/src/tools/buildHelper.ts
Porting changes from #26049, #26053, #26095, and #26099 to the release branch for the database projects extension 1.4.5.
> Porting changes to release branch for database projects extension 1.4.5

- extensionsGallery-insider.json
- extensionsGallery.json
[Mongo migration 3.1.5](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTUyNzEyNTk1L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-3.1.5.vsix)
> Release new version of mongo migration extension (3.1.5)

- extensionsGallery-insider.json
- extensionsGallery.json
[Mongo migration 3.1.6](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTUzMzMyMjAzL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-3.1.6.vsix)
> Release new version of mongo migration extension (3.1.6)

- extensions/notebook/src/jupyter/serverInstance.ts
Add a warning confirmation prompt prior to loading the Jupyter server if there are shared configuration scripts in ProgramData directory.  The user can still load the server if they are confident the scripts are fine to execute.
> Add warning prompt for shared Python notebook config scripts

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/25990, 
The PR configures Axios, an HTTP client that Azure Data Studio has a dependency on, to successfully make requests from a proxied environment. In cases where an HTTP proxy is used, the request to get tenants is unable to go through when a proxy only supports HTTP traffic. This can result in the request to hang and prevent completion. To avoid hanging an HTTPS request from a HTTP proxy, an HTTPS over HTTP tunnel is needed, which is what this PR adds.
I validated my changes, by having Azure Data Studio connect to the proxy endpoint set up by ProxyMan, and reviewed the following resources to identify that when Axios makes requests in proxy environments, it can result in errors that stop the request from completing. …
> Adding HTTP(S) over HTTP(S) proxy support to add accounts.

- extensions/azurecore/src/account-provider/auths/azureAuth.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/25990
Ports: https://github.com/microsoft/azuredatastudio/pull/26137
> [Port] Adding HTTP(S) over HTTP(S) proxy support to add accounts

- README.md
- src/sql/workbench/contrib/welcome/browser/az_data_welcome_page.ts
- src/sql/workbench/contrib/welcome/browser/retirementAnnouncement.contribution.ts
- src/sql/workbench/contrib/welcome/browser/retirementAnnouncement.ts
- src/sql/workbench/contrib/welcome/browser/welcomePage.css
- src/vs/workbench/workbench.desktop.main.ts
- src/vs/workbench/workbench.web.main.ts
Added a visible yellow banner to the welcome page and a notification that pops up each launch until the user selects "Don't show again".
> Adding banner to notify users of Azure Data Studio's retirement announcement.

- extensionsGallery-insider.json
- extensionsGallery.json
[Mongo migration 3.1.7](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTYxMDcxNzA0L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-3.1.7.vsix)
> Release mongo migration extension (3.1.7)

- extensions/sql-database-projects/README.md
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/sqldbproj.d.ts
1. modifies a dialog that displays `(preview)` when creating a project
2. updates sqlproj extension readme to move SDK-style projects out of preview list
3. corrects target platform description for SQL database in Fabric
> cosmetic SDK GA changes

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/tools/buildHelper.ts
- extensions/sql-database-projects/src/tools/netcoreTool.ts
Addresses #26254 
Projects extension uses binaries from Microsoft.Build.Sql to build non-SDK style projects, but SDK 1.0.0 has a breaking change that is shipping net8.0 DLLs instead of netstandard2.1. Updating the binaries path here and also updating the corresponding ScriptDom version to 161.9142.1.
SDK 1.0.0 release notes: https://github.com/microsoft/DacFx/blob/main/release-notes/Microsoft.Build.Sql/1.0.0.md
> Fix download path for Microsoft.Build.Sql binaries

- extensions/sql-migration/src/models/stateMachine.ts
- extensions/sql-migration/src/telemetry.ts
- extensions/sql-migration/src/wizard/databaseSelectorPage.ts
- extensions/sql-migration/src/wizard/skuRecommendation/skuRecommendationPage.ts
- extensions/sql-migration/src/wizard/sourceSelectionSection.ts
Bugs and fixes:
1) Remove dot after arc server link name.
2) Next button not enabled on No tracking migration option. 
Fix: The button is disabled due to loading states of dropdowns. Temporary fix - Remove loaders in all dropdowns as setting loading = false or marking button enabled has no effect on behavior.
3) Avoid arc resource creation and handling when user chooses not to track migrations.
> Fix no source tracking for SQL Migrations

- extensions/sql-database-projects/src/common/utils.ts
Porting #26263 to release/1.52
Addresses #26260
Fixing this for March release, but correct fix would be to add SqlDbFabric to isCloud in SqlToolsService https://github.com/microsoft/sqltoolsservice/blob/65d6dd4c815813edebbd3ef7cc726c7b6feda7b8/src/Microsoft.SqlTools.ManagedBatchParser/ReliableConnection/ReliableConnectionHelper.cs#L38
> [PORT] Add condition for Fabric engine edition

- extensions/data-workspace/src/services/workspaceService.ts
- extensions/data-workspace/src/test/workspaceService.test.ts
Projects to the SQL database projects pane are not ordered. This change sorts the projects based on the project name.
Before:
After:
> Sorting the projects in sql database projects pane based on the project name

- extensions/sql-migration/src/telemetry.ts
- extensions/sql-migration/src/wizard/skuRecommendation/skuRecommendationPage.ts
Captured the following info into telemetry:
1) If SQL Server is enabled by Arc or not
2) If user has clicked the Arc assessment link
> Add missing client telemetry for source tracking

- extensions/sql-database-projects/package.json
Issue: https://github.com/microsoft/azuredatastudio/issues/26297 : "Generate SQL Project from OpenAPI / Swagger Spec (preview) " appears as an overflow menu option when not in context 
Issue:
with Fix:
> Fixing the Generate SQL Project from OpenAPI preview option appears for all tabs menu options

- extensions/data-workspace/src/services/workspaceService.ts
- extensions/data-workspace/src/test/workspaceService.test.ts
This PR fixed the sorting issue of the database projects on each load.
Issue: https://github.com/microsoft/azuredatastudio/issues/26275
Before:
After:
> Porting - SQL Database projects sorting fix

- .github/CODEOWNERS
This pull request updates the `CODEOWNERS` file to reflect changes in ownership for the `sql-database-projects` extension.
Ownership update:
* [`.github/CODEOWNERS`](diffhunk://#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7L14-R14): Reassigned ownership of `/extensions/sql-database-projects/` from `@Benjin` and `@kisantia` to `@ssreerama`, `@chlafreniere`, `@llali`, and `@zijchen`.
> updating SQL database projects extension code owners list

- extensions/sql-database-projects/package.json
- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/extension.ts
- extensions/sql-database-projects/src/tasks/sqlDatabaseProjectTaskProvider.ts
- extensions/sql-database-projects/src/test/tasks/sqlDatabaseProjectTaskProvider.test.ts
This pull request introduces task provider support for SQL database projects in Visual Studio Code. It adds functionality to define, register, and manage tasks for building `.sqlproj` files, including tasks with optional code analysis. It also includes tests to validate the new functionality. Below are the most important changes grouped by theme:
* Introduced a new `SqlDatabaseProjectTaskProvider` class to provide tasks for `.sqlproj` files. It supports creating build tasks and build-with-code-analysis tasks, leveraging `vscode.Task` and `vscode.ShellExecution`. The class also includes file system watchers to dynamically update tasks when `.sqlproj` files are added, modified, or removed. (`extensions/sql-database-projects/src/tasks/sqlDatabaseProjectTaskProvider.ts`)
* Added task …
> VsCode Tasks PR2: Adding sqlproj-build Task Definition and Problem Matcher to Extension Package

- extensions/sql-database-projects/src/common/constants.ts
- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/extension.ts
- extensions/sql-database-projects/src/tasks/sqlDatabaseProjectTaskProvider.ts
- extensions/sql-database-projects/src/test/buildHelper.test.ts
- extensions/sql-database-projects/src/test/tasks/sqlDatabaseProjectTaskProvider.test.ts
- extensions/sql-database-projects/src/tools/buildHelper.ts
This pull request refactors the build and task handling logic for SQL database projects to improve modularity, reduce redundancy, and enhance maintainability. Key changes include splitting the `dotnet build` command into separate command and arguments, simplifying task provider initialization, and improving test coverage to reflect these updates.
1. SQL Project file path has space.
2. Duplicate tasks are shown in the RunTask command pallet view, for `.sqlproj` files when workspace folders are parent-child hierarchy.
3. Opening existing projects should create 'RunTask' tasks instantly without reloading the vs code instance.
* Replaced the single `dotnet build` command string with separate `dotnet` and `build` constants in `constants.ts`. Updated related logic to use an array of arguments …
> Fixing Tasks related issues found while testing

- src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts
This PR improves HTML rendering by sanitizing string text before adding it to the DOM.
Notebook HTML rendering continues to work as expected:
> Cleans up HTML rendering

- package.json
- yarn.lock
This PR updates the slickgrid version used by Azure Data Studio.
Multiple query results continue to work as expected with the changes made to slickgrid.ads:
Editing table data also continues to work as expected with the changes made to slickgrid.ads:
This PR updates the slickgrid.ads version being used.
> Bump slickgrid to version 2.3.50

- extensions/sql-database-projects/src/controllers/projectController.ts
- extensions/sql-database-projects/src/test/projectController.test.ts
This pull request improves the handling of file extensions when users create new files through the project controller. Now, any file extension (such as `.sql`) that users include in their input will be automatically removed, even if repeated or in different cases. This ensures that files are not created with redundant extensions. Additionally, comprehensive tests have been added to verify this behavior.
File extension handling improvements:
* Updated `ProjectsController` to strip any file extension (case-insensitive and repeated) from the user-provided file name before creating the file. This prevents files from being created with multiple or incorrect extensions.
Testing enhancements:
* Added a new test in `projectController.test.ts` to verify that file extensions are correctly removed …
> Removing the fileextension from the object name

- extensions/sql-database-projects/src/controllers/projectController.ts
This PR fixes the publish/genScript issue with any sqlobject added and publish the project without building it. Publish will take care of the build, but here the issue is scripting database is not waiting for the build task to complete and it uses the available old dacpac to generate the script.
Issue:  https://github.com/microsoft/vscode-mssql/issues/19991 
Issue:
After Fix:
> Fix for " Database Project Publish or GenScripts does not wait for build to run with newly added changes"
