microsoft/azuredatastudio

extensions/sql-migration/package.json

Bump sql-migration version

---

extensions/mssql/config.json

Picks up a fix for the User w/ Login dropdown on SQL DB user database bug.

Bump STS to 4.7.0.26 for User w Login fix

---

resources/xlf/en/sql-migration.xlf

[Loc] final update to localization before code complete

---

extensionsGallery-insider.json

Updating sql projects version in Insiders to share a fix with customer, and verify that it is working as expected after the code change.
Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=199226&view=results

Update sql projects in insiders

---

extensionsGallery.json

This PR upgrades MySQL extension in stable gallery.

upgraded mysql extension in stable gallery to 0.2.9

---

extensions/mssql/config.json

Needed for https://github.com/microsoft/azuredatastudio/pull/22948

Bump SQL Tools dependency to 4.7.0.28

---

extensions/sql-database-projects/README.md

Updating SqlProjects readme to have absolute github link for image

---

src/sql/platform/connection/common/constants.ts
src/sql/workbench/contrib/welcome/notifyHiddenTenant/notifyHiddenTenantDialog.ts
src/sql/workbench/services/connection/browser/utils.ts
src/sql/workbench/services/connection/test/browser/connectionDialogService.test.ts
src/sql/workbench/services/connection/test/browser/connectionManagementService.test.ts

Ensure MSAL is enabled when disabling tenant dropdown

Validate MSAL library is enabled

---

src/sql/base/browser/ui/taskbar/media/taskbar.css
src/sql/workbench/contrib/query/browser/queryEditor.ts

for: https://github.com/microsoft/azuredatastudio/issues/22675
1. add label for database dropdown
2. reduce separator margin and move the separator so that it is clear what the new text is for.

add label for database dropdown

---

extensions/sql-database-projects/src/common/constants.ts
extensions/sql-database-projects/src/controllers/projectController.ts
extensions/types/vscode-mssql.d.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/22988
VSCode-MSSQL changes here: https://github.com/microsoft/vscode-mssql/pull/17675

Fixing deleteDatabaseReference call for vscode-mssql

---

build/azure-pipelines/linux/sql-product-build-linux.yml
build/azure-pipelines/linux/sql-publish.ps1
build/linux/debian/dependencies-generator.js
build/linux/debian/dependencies-generator.ts
build/linux/rpm/dependencies-generator.js
build/linux/rpm/dependencies-generator.ts
build/package.json
build/yarn.lock

These are the changes I needed to make to the `cheena/try-fix-build-update` branch to be able to create a deb file in my VM. There were a few issues from missing dependencies in the `build` folder that were preventing that folder from compiling. Adding those allowed a deb file to be generated locally.

Generates deb file

---

extensionsGallery-insider.json
extensionsGallery.json

Releasing a new extension version 1.0.1
This is the [binary](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvOTIwMTk1ODIvYXJ0aWZhY3ROYW1lL2Ryb3BfYnVpbGRfbWFpbg2/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-1.0.1.vsix)

Mongo migration extension release - 1.0.1

---

src/sql/workbench/services/objectExplorer/browser/serverTreeActionProvider.ts

@Charles-Gagnon , this error is happening because an additional check was added in this merge. (https://github.com/microsoft/azuredatastudio/pull/15681) This happened whenever we were trying to generate context menu in both server tree (Async and ITree). This was causing error to show up in console
This PR fixes #22928

Fixing element already has context attribute in server tree

---

resources/localization/LCL/de/sql-migration.xlf.lcl
resources/localization/LCL/es/sql-migration.xlf.lcl
resources/localization/LCL/fr/sql-migration.xlf.lcl
resources/localization/LCL/it/sql-migration.xlf.lcl
resources/localization/LCL/ja/sql-migration.xlf.lcl
resources/localization/LCL/ko/sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/sql-migration.xlf.lcl
resources/localization/LCL/ru/sql-database-projects.xlf.lcl
resources/localization/LCL/ru/sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230508154231869 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230508154231869 to main

---

src/sql/workbench/services/objectExplorer/browser/asyncServerTree.ts

Fixing delete server group error when we try to focus on root

---

src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts

Clearing connection node children when disconnecting them

---

src/vs/workbench/contrib/markers/browser/markersTreeViewer.ts

Port a vscode fix for issue #23021

---

extensions/sql-database-projects/package.json

Updating version to 1.1.1 for May release because version 1.1.0 was released in insiders last week

vbump sql projects to 1.1.1

---

package.json

updating version in main now that release branch has split

---

src/vs/workbench/contrib/markers/browser/markersTreeViewer.ts

This PR fixes #23021 
(waiting for shiproom approval)

Port fix for 23021 to release branch

---

extensions/sql-database-projects/package.json

Port https://github.com/microsoft/azuredatastudio/pull/23029 to fix https://github.com/microsoft/azuredatastudio/issues/23038

[Port] vbump sql projects to 1.1.1 (#23029)

---

extensions/mssql/config.json

Fixes https://github.com/microsoft/azuredatastudio/issues/22992

Bumping SQL Tools Service to 4.7.1.1

---

extensionsGallery-insider.json
extensionsGallery.json

Add Copilot to extension gallery files for May release.

Add Copilot to extension gallery files

---

src/sql/workbench/contrib/objectExplorer/common/serverGroup.contribution.ts

disabling async tree by default in may release

---

extensions/import/src/common/utils.ts
extensions/import/src/wizard/pages/summaryPage.ts

Ports #23004 to fix #22999 in release/1.44 branch

[Release/1.44] Fixes import wizard to work with enabled SQL auth provider (#23004)

---

extensionsGallery-insider.json
extensionsGallery.json

Please find the vsix binary [here](https://msdata.visualstudio.com/_apis/resources/Containers/184301409/drop?itemPath=drop%2Fazure-cosmosdb-ads-extension-0.3.3.vsix).

Update cosmosdb extension to version 0.3.3

---

extensions/mssql/config.json

Bringing back these commits into main
https://github.com/microsoft/sqltoolsservice/compare/4.7.0.31...4.8.0.1

Readding oe filtering back into main

---

src/sql/base/browser/ui/inputBox/inputBox.ts
src/sql/base/browser/ui/selectBox/selectBox.ts

this PR fixes #23065 
introduced in this PR: https://github.com/microsoft/azuredatastudio/pull/21256
Before
After

fix input element id

---

src/sql/workbench/browser/modelComponents/divContainer.component.ts
src/sql/workbench/browser/modelComponents/image.component.ts

for #22754 and #22753
set the necessary accessibility related attributes on divContainer and image components.

fix model view component issues

---

src/vs/base/browser/ui/actionbar/actionViewItems.ts

https://github.com/microsoft/azuredatastudio/issues/22656

set aria label for action item

---

src/sql/platform/connection/common/connectionStore.ts

Support migrating credentials to new format

---

extensions/mssql/src/contracts.ts
extensions/mssql/src/dacfx/dacFxService.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/23079

Fixing bug where SQLCMD vars weren't getting JSONified

---

extensions/mssql/src/contracts.ts
extensions/mssql/src/dacfx/dacFxService.ts

Porting https://github.com/microsoft/azuredatastudio/pull/23082 to fix https://github.com/microsoft/azuredatastudio/issues/23079

Porting fix for SQLCMD var bug in SQL Database Projects

---

extensionsGallery-insider.json

Langpacks from this build (same as https://github.com/microsoft/azuredatastudio/pull/23092):
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=199907&view=artifacts&pathAsName=false&type=publishedArtifacts

Update to insiders gallery for release/extensions for May 2023 release

---

extensionsGallery.json

Langpacks to merge are from this build:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=199907&view=artifacts&pathAsName=false&type=publishedArtifacts

Update to langpacks for RC1 in Extensions Gallery for May 2023 release

---

extensions/notebook/package.json

Fixes #23107.
Remove the provided sql2019 bds book.

remove the BDC provided book from Books View

---

extensions/markdown-language-features/package.json
src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts

Fixes  https://github.com/microsoft/azuredatastudio/issues/23100

[Port] update workbench file and fix relative link not working in markdown 

---

src/sql/platform/connection/common/connectionStore.ts

Ports #23088 to fix #23087 for release/1.44

[Release/1.44] Support migrating credentials to new format (#23088)

---

src/sql/azdata.proposed.d.ts
src/sql/platform/telemetry/common/telemetryKeys.ts
src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
src/sql/workbench/contrib/objectExplorer/test/browser/serverTreeView.test.ts
src/sql/workbench/services/objectExplorer/browser/connectionTreeAction.ts

Fixes #23090 
PR to main branch #23070

Adding telemetry to OE filtering in may release

---

extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts

Porting https://github.com/microsoft/azuredatastudio/pull/23103 to fix https://github.com/microsoft/vscode-mssql/issues/17682 for the sql database projects vscode extension

[Port] fix sqlcmd variables not getting loaded correctly in vscode (#23103)

---

extensions/notebook/package.json

Ports #23105 to release. Fixes #23107

[Port] Remove BDC book from provided books

---

extensions/mssql/src/dacfx/dacFxService.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/23111

Fix deploy/generatePlan/saveProfile when no sqlcmdvars are defined

---

extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/23115
Before: 
https://github.com/microsoft/azuredatastudio/assets/1609827/278262b0-f24a-4de8-a029-ad186dc3f716
After:
https://github.com/microsoft/azuredatastudio/assets/1609827/859592e5-a7b2-4b38-939b-0f1c69c03a82

Fixing issue where sqlcmdvars wouldn't load from publish profile in ADS

---

extensions/mssql/src/dacfx/dacFxService.ts

Port #23112 to fix https://github.com/microsoft/azuredatastudio/issues/23111

Port Fix deploy/generatePlan/saveProfile when no sqlcmdvars are defined #23112

---

extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts

Porting https://github.com/microsoft/azuredatastudio/pull/23116 to fix https://github.com/microsoft/azuredatastudio/issues/23115

Porting Fixing issue where sqlcmdvars wouldn't load from publish profile in ADS #23116

---

src/sql/platform/capabilities/test/common/testCapabilitiesService.ts
src/sql/platform/connection/common/providerConnectionInfo.ts
src/sql/workbench/contrib/commandLine/electron-browser/commandLine.ts
src/sql/workbench/contrib/commandLine/test/electron-browser/commandLine.test.ts

Ports #23104 to fix #23081 for release/1.44

[Release/1.44] Support advanced options in command line arguments (#23104)

---

resources/xlf/en/azurecore.xlf
resources/xlf/en/mssql.xlf
resources/xlf/en/sql-database-projects.xlf
resources/xlf/en/sql-migration.xlf
resources/xlf/en/sql.xlf

[Loc] End of week update for langpack xlfs for 5-12-2023

---

src/vs/workbench/api/common/extHostTypes.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/22865
Porting over https://github.com/microsoft/vscode/pull/157771

Fix invalid tree icon warning

---

extensions/mssql/config.json
src/sql/azdata.proposed.d.ts
src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
src/sql/workbench/services/objectExplorer/browser/filterDialog/filterDialog.ts
src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts

UI:
When group by schema is disabled:
When group by schema is enabled:
Filters for schema:
Updating STS to get the backend changes:
https://github.com/microsoft/sqltoolsservice/compare/4.8.0.1...4.8.0.5

Adding filtering to group by schema and switching to using name from displayName in oe filters. 

---

extensions/sql-database-projects/package.json
extensions/sql-database-projects/package.nls.json
extensions/sql-database-projects/resources/templates/newPublishProfileTemplate.publish.xml
extensions/sql-database-projects/src/common/constants.ts
extensions/sql-database-projects/src/controllers/mainController.ts
extensions/sql-database-projects/src/controllers/projectController.ts
extensions/sql-database-projects/src/sqldbproj.d.ts
extensions/sql-database-projects/src/templates/templates.ts
extensions/sql-database-projects/src/test/projectController.test.ts
extensions/sql-database-projects/src/test/templates.test.ts

Add ability to create publish profile from project context

---

extensions/mssql/package.json

Removing duplicate default commands that prevented default actions

Removing duplicate default commands from mssql OE items

---

src/sql/workbench/contrib/connection/browser/connection.contribution.ts
src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts

Adding collapse all to OE

---

src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts

update install vsix prompt to include license terms

---

extensionsGallery.json

Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=200497&view=artifacts&pathAsName=false&type=publishedArtifacts

Update extensions gallery for Schema compare and Sql Db Projects extensions

---

extensionsGallery-insider.json

Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=200497&view=artifacts&pathAsName=false&type=publishedArtifacts

Update insiders gallery for Schema compare and Sql Db Projects extensions

---

extensions/sql-database-projects/src/dialogs/publishDatabaseQuickpick.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/23138
Before:
https://github.com/microsoft/azuredatastudio/assets/1609827/5bff0a97-6cd2-4d95-86d5-e4e1920035a4
After:
https://github.com/microsoft/azuredatastudio/assets/1609827/88f7e153-e170-4947-8d42-eabce874c991

Fixing quickpick options for publishing a project in VS Code

---

extensions/mssql/config.json
extensions/mssql/package.json
extensions/mssql/package.nls.json

This PR fixes https://github.com/microsoft/azuredatastudio/issues/22546
This change depends on STS change https://github.com/microsoft/sqltoolsservice/pull/2070
Before:
After disabling this setting:
STS changes since last version: https://github.com/microsoft/sqltoolsservice/compare/4.8.0.9...4.8.0.10

Table Designer: Add config for table designer trigger behavior

---

extensionsGallery.json

update cms extension - rc1

---

extensionsGallery-insider.json

update cms extension - insiders

---

src/sql/workbench/browser/modal/media/modal.css
src/sql/workbench/browser/modal/modal.ts
src/sql/workbench/services/connection/browser/media/passwordDialog.css
src/sql/workbench/services/connection/browser/passwordChangeDialog.ts
src/sql/workbench/services/errorMessage/browser/errorMessageDialog.ts
src/sql/workbench/services/errorMessage/browser/media/errorMessageDialog.css
src/sql/workbench/services/objectExplorer/browser/media/filterDialog.css
src/sql/workbench/services/profiler/browser/media/profilerFilterDialog.css
src/sql/workbench/services/profiler/browser/profilerFilterDialog.ts
src/sql/workbench/services/tableDesigner/browser/media/tableDesignerPublishDialog.css

This PR fixes #23176
I was working on this bug: https://msdata.visualstudio.com/Data%20Studio/_workitems/edit/1613524, and realized this is a common issue for all normal dialogs, so I went ahead and fixed all the places that have such problem.
model view dialog example:
table designer publish dialog:
object explorer filter dialog:
error dialog:
change password dialog:
profiler filter dialog:

fix normal dialog vertical scrolling issue

---

resources/xlf/en/mssql.xlf
resources/xlf/en/sql-database-projects.xlf
resources/xlf/en/sql.xlf

[Loc] end of week xlf update for 5-19-2023

---

extensionsGallery-insider.json

Insider release for oracle extension 0.1.3

Oracle extension release 0.1.3

---

extensionsGallery-insider.json

Update copilot to 1.82.15 due to bug in previous version

Update copilot to 1.82.15 due to bug in previous version

---

extensionsGallery.json

Verion change for 'Extension for Oracle' in ADS to v 0.1.3

Version 0.1.3 Oracle Extension

---

extensions/sql-database-projects/src/test/projectController.test.ts

Move folder support was added, so the tests needed to be updated to remove move folder from the not allowed test and to add a test for move folder.

fix sql project move folder tests

---

src/sql/workbench/contrib/executionPlan/browser/media/executionPlan.css
src/sql/workbench/contrib/executionPlan/browser/widgets/nodeSearchWidget.ts

Accessibility Issue: #21414 
Now:
Before:

Adding visual label to find node widget in execution plan

---

resources/localization/LCL/de/mssql.xlf.lcl
resources/localization/LCL/de/sql-database-projects.xlf.lcl
resources/localization/LCL/de/sql.xlf.lcl
resources/localization/LCL/es/mssql.xlf.lcl
resources/localization/LCL/es/sql-database-projects.xlf.lcl
resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/mssql.xlf.lcl
resources/localization/LCL/fr/sql-database-projects.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/it/mssql.xlf.lcl
resources/localization/LCL/it/sql-database-projects.xlf.lcl
resources/localization/LCL/it/sql.xlf.lcl
resources/localization/LCL/ja/mssql.xlf.lcl
resources/localization/LCL/ja/sql-database-projects.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl
resources/localization/LCL/ko/mssql.xlf.lcl
resources/localization/LCL/ko/sql-database-projects.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/pt-BR/mssql.xlf.lcl
resources/localization/LCL/pt-BR/sql-database-projects.xlf.lcl
resources/localization/LCL/pt-BR/sql.xlf.lcl
resources/localization/LCL/ru/mssql.xlf.lcl
resources/localization/LCL/ru/sql-database-projects.xlf.lcl
resources/localization/LCL/ru/sql.xlf.lcl
resources/localization/LCL/zh-Hans/mssql.xlf.lcl
resources/localization/LCL/zh-Hans/sql-database-projects.xlf.lcl
resources/localization/LCL/zh-Hans/sql.xlf.lcl
resources/localization/LCL/zh-Hant/mssql.xlf.lcl
resources/localization/LCL/zh-Hant/sql-database-projects.xlf.lcl
resources/localization/LCL/zh-Hant/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230525155716692 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230525155716692 to main

---

extensions/sql/language-configuration.json

Fixes https://github.com/microsoft/azuredatastudio/issues/23167

Set offSide to sql lang configuration to true

---

extensionsGallery-insider.json
extensionsGallery.json

This updates import extension to the latest release with AAD fixes
The vsix can be found here: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=201203&view=artifacts&pathAsName=false&type=publishedArtifacts
Fixes #23220

Updating import extension to fix AAD with auth provider

---

extensions/import/package.json

Vbumping import extension

---

extensionsGallery-insider.json
extensionsGallery.json

VSIX files location: https://github.com/microsoft/azuredatastudio-postgresql/releases/download/v0.3.1/azuredatastudio-postgresql-0.3.1.vsix

PostgreSQL Extension to 0.3.1

---

package.json

Update version to 1.44.1 for hotfix

---

extensions/mssql/config.json

This ports the fix for https://github.com/microsoft/azuredatastudio/issues/23210 to release/1.44

Bump STS to 4.7.1.5 to pick up AAD email fix

---

src/vs/workbench/contrib/quickaccess/browser/viewQuickAccess.ts

Port fix for https://github.com/microsoft/azuredatastudio/issues/23236 to release branch.

Remove debugService dependency from Open View (#23246)

---

extensions/mssql/config.json

Fix https://github.com/microsoft/azuredatastudio/issues/23210 in main branch.

Bump STS to 4.8.0.14 to pickup AAD '-' in email bug fix

---

extensions/mssql/config.json

Bump STS to pickup fix for https://github.com/microsoft/azuredatastudio/issues/22970.

Bump STS to 4.7.1.6 in release branch for connection pool issue

---

extensions/mssql/config.json

Bump STS to fix https://github.com/microsoft/azuredatastudio/issues/22970.

Bump STS to 4.8.0.15 for connection pool issue

---

src/sql/workbench/services/objectExplorer/browser/serverTreeActionProvider.ts

Removing inline actions from context menu in OE

---

CHANGELOG.md

Updating Changelog Post 1.44 release

---

extensions/azurecore/src/azureDataGridProvider.ts
extensions/azurecore/src/azureResource/constants.ts
extensions/azurecore/src/azureResource/providers/mysqlFlexibleServer/mysqlFlexibleServerTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/postgresFlexibleServer/postgresFlexibleServerService.ts
extensions/azurecore/src/azureResource/providers/postgresFlexibleServer/postgresFlexibleServerTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/queryStringConstants.ts
extensions/azurecore/src/azureResource/providers/universal/universalService.ts
extensions/azurecore/src/azureResource/utils.ts
extensions/azurecore/src/azurecore.d.ts
extensions/azurecore/src/constants.ts
extensions/azurecore/src/localizedConstants.ts
extensions/azurecore/src/utils.ts

Add support for PgSql Flexible Servers

---

.github/CODEOWNERS

Adding codeowners for the query store extension so we all get added automatically to PRs for changes in the extension.

add codeowners for query-store extension

---

CHANGELOG.md

changelog for 1.44.1

---

extensions/query-store/README.md

update query store readme

---

extensions/sql-migration/src/constants/helper.ts
extensions/sql-migration/src/dashboard/migrationDetailsTableTab.ts

Fixing bug where if copy duration went over 24h it would reset to 00:00:00. This came from the below ICM
https://portal.microsofticm.com/imp/v3/incidents/details/393457962/home
Fix shown below with copy duratio of 27 hours:

 Fixing bug where if copy duration went over 24h it would reset to 00:00:00

---

src/sql/workbench/services/objectExplorer/browser/connectionTreeAction.ts

Adding status message for connection and connection group deletion.

---

extensions/azurecore/src/azureResource/providers/resourceTreeDataProviderBase.ts

Fix resource group query filter

---

extensions/mssql/src/objectManagement/ui/loginDialog.ts

This PR fixes https://github.com/microsoft/azuredatastudio/issues/22857
MUST_CHANGE should be enabled when it's a new login or there's a password change.

Fix must_change option for login management

---

extensions/import/src/test/wizard/pages/modifyColumnsPage.test.ts
extensions/import/src/wizard/pages/modifyColumnsPage.ts
src/sql/workbench/browser/modelComponents/declarativeTable.component.html
src/sql/workbench/browser/modelComponents/declarativeTable.component.ts

Issue: #22372 
Before: 
```<input type="checkbox" id="d11763dc-bf1b-4046-bce0-235a472d8558" aria-label="" style="vertical-align: middle;">```
After:
```<input type="checkbox" id="8f2df910-631e-4eb1-9a83-dd4e88c50701" aria-label="Primary Key" style="vertical-align: middle;">```

Adding aria-labels to checkbox cells in declarative table

---

resources/xlf/en/azurecore.xlf
resources/xlf/en/mssql.xlf
resources/xlf/en/sql-database-projects.xlf
resources/xlf/en/sql-migration.xlf
resources/xlf/en/sql.xlf

[Loc] update to xlfs for 6-9-2023

---

.github/label-actions.yml

add the step to set ADS log level to Trace and fix the formatting of the comment.
Before
After

update needs logs action

---

.github/label-actions.yml
src/sql/workbench/api/browser/mainThreadQueryEditor.ts
src/sql/workbench/browser/scriptingUtils.ts
src/sql/workbench/contrib/query/browser/keyboardQueryActions.ts
src/sql/workbench/contrib/query/browser/queryActions.ts
src/sql/workbench/contrib/query/browser/queryEditor.ts
src/sql/workbench/contrib/query/browser/queryEditorFactory.ts
src/sql/workbench/contrib/query/test/browser/queryActions.test.ts
src/sql/workbench/contrib/query/test/browser/queryInputFactory.test.ts
src/sql/workbench/contrib/tasks/common/tasksAction.ts
src/sql/workbench/services/query/common/queryManagement.ts
src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
src/sql/workbench/services/queryEditor/common/queryEditorService.ts
src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts
src/sql/workbench/services/tasks/common/tasksService.ts

1. Fix an issue with the Query Management Service logging, I was logging the objects instead of count.
3. Refactor the RunQueryAction
4. Fix some typos I noticed while debugging an issue.

Query Management log message update

---

resources/xlf/en/azurecore.xlf
resources/xlf/en/mssql.xlf
resources/xlf/en/sql-database-projects.xlf
resources/xlf/en/sql.xlf

[Loc] update to xlfs for 6-16-2023

---

extensionsGallery-insider.json
extensionsGallery.json

Please find the vsix package [here](https://msdata.visualstudio.com/_apis/resources/Containers/186950714/drop?itemPath=drop%2Fazure-cosmosdb-ads-extension-0.3.4.vsix).

Update Cosmos DB extension to version 0.3.4

---

src/sql/base/common/strings.ts

Brought up from https://github.com/microsoft/SlickGrid.ADS/pull/17#discussion_r1234315129

Added fix to escape switch for single quote

---

src/sql/base/common/strings.ts

Follow up PR for https://github.com/microsoft/sqltoolsservice/commit/7f6b357eb00dac65fc6003c564b05518ba38e3ce Fixes the escape function so that it actually parses the ' character

Added fix to regex for string escape

---

resources/localization/LCL/de/azurecore.xlf.lcl
resources/localization/LCL/de/mssql.xlf.lcl
resources/localization/LCL/de/sql-database-projects.xlf.lcl
resources/localization/LCL/de/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230620154443163 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230620154443163 to main

---

.github/label-actions.yml

for some reason, the actual comments doesn't look like the same if you copy them directly as markdown. adding an extra line break to see whether it helps.
how it looks now.

add line breaks

---

src/sql/workbench/contrib/scripting/browser/scriptingActions.ts

for #23414, add progress and error handling.
1. show progress when the action is being executed and catch error.
2. code refactoring.

show progress for scripting actions

---

extensions/mssql/config.json

This PR fixes #23145
This PR fixes #23428
https://github.com/microsoft/sqltoolsservice/compare/4.8.0.26...4.8.0.28

bring in a few STS fixes

---

package.json
remote/package.json
remote/web/package.json
remote/web/yarn.lock
remote/yarn.lock
yarn.lock

New Slickgrid Version (HTML escape for aria label)

---

extensions/mssql/config.json

This PR updates the STS version from 4.8.0.28 to 4.8.0.29, And below screenshot has the commit differences for the two versions.

STS version bump to 4.8.0.29

---

src/sql/workbench/contrib/scripting/browser/scriptingActions.ts

Follow up of https://github.com/microsoft/azuredatastudio/pull/23435
In case of error:
1. stop the progress
2. provide a close button

update the scripting error notification.

---

extensionsGallery-insider.json

vsix file: https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.4.0-insiders

[PostgreSQL] Release v0.4.0 to Insiders 

---

extensionsGallery-insider.json
extensionsGallery.json

This PR upgrades MySQL extension for GA release in stable and insider gallery.
VSIX file: https://github.com/microsoft/azuredatastudio-mysql/releases/download/v1.0.0/azuredatastudio-mysql-1.0.0.vsix

updated mysql extension version to 1.0.0 for GA release

---

resources/xlf/en/mssql.xlf
resources/xlf/en/sql.xlf

[Loc] XLF update 6-23-2023

---

extensions/azurecore/src/extension.ts
extensions/azurecore/src/localizedConstants.ts

Added this warning message that will show every time a user starts ADS:
precursor to #23360

Add adal deprecated warning upon ADS startup

---

extensionsGallery-insider.json
extensionsGallery.json

This is the link for new version
[mongo migration extension 1.1.0](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvOTc0NjI3NTMvYXJ0aWZhY3ROYW1lL2Ryb3BfYnVpbGRfbWFpbg2/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-1.1.0.vsix)

Releasing new version for mongo migration extension

---

extensions/mssql/config.json

Updating STS version to bring in schema compare bug fix. Fixes #21378.

update STS to 4.8.0.32

---

src/sql/workbench/services/objectExplorer/browser/filterDialog/filterDialog.ts

Fix build break from unused okButton variable.  This looks like something that came in from a late iteration on the merge PR.

Fix build break from unused okButton variable

---

build/azure-pipelines/linux/sql-product-build-linux.yml

Related to https://github.com/microsoft/azuredatastudio/issues/23505.

Temporary disable extension signing in CI build

---

src/sql/workbench/contrib/views/browser/treeView.ts

Updated treeView with upstream design to fix missing Custom tree icons as observed in #23512 
Left (with PR changes) <> Right (Insiders build)

Fix treeView to render icons

---

src/sql/workbench/services/objectExplorer/browser/filterDialog/filterDialog.ts
src/sql/workbench/services/objectExplorer/browser/media/filterDialog.css

Fixing filter layout 

---

extensions/admin-tool-ext-win/package.json
extensions/admin-tool-ext-win/package.nls.json

Fixes https://github.com/microsoft/azuredatastudio/issues/23511
I considered using submenus, but in general Properties menu items are always on the top level so decided not to do that here.

Update admin tools ext properties menu item text

---

extensionsGallery-insider.json
extensionsGallery.json

VSIX files location:  https://github.com/microsoft/azuredatastudio-postgresql/releases/download/v0.4.0/azuredatastudio-postgresql-0.4.0.vsix

PostgreSQL Extension to 0.4.0

---

src/sql/workbench/contrib/views/browser/treeView.ts

Fixes #23554 
Also noticed context menu and actions were gone.. now fixed!

Fix Azure tree view

---

extensions/schema-compare/package.json
extensions/sql-database-projects/package.json

Forgot to vbump these two right after the May release

vbump sql projects and schema compare

---

extensionsGallery-insider.json
extensionsGallery.json

VSIX files location: https://github.com/microsoft/azuredatastudio-postgresql/releases/download/v0.4.1/azuredatastudio-postgresql-0.4.1.vsix

PostgreSQL Extension to 0.4.1

---

src/sql/workbench/contrib/commandLine/electron-browser/commandLine.ts

Fix continuous loop on Cancel

---

src/sql/workbench/services/connection/browser/connectionWidget.ts

Fix console error for new connection dialog

---

src/sql/workbench/contrib/scripting/browser/scriptingActions.ts

follow up of this PR: https://github.com/microsoft/azuredatastudio/pull/23582
Add the action name to the executing action label.

add action name to label

---

src/sql/workbench/common/views.ts
src/sql/workbench/contrib/views/browser/treeView.ts

Cleaned up treeView class to be as close to vs treeview as possible - leaving only tracked changes
Fixes #23590

Bring parity with vs treeview for all non tracked code.

---

build/gulpfile.extensions.js
build/gulpfile.vscode.js
resources/xlf/en/sql.xlf

[Loc] fixes for gulpfile and update to SQL xlf

---

src/sql/workbench/contrib/dataExplorer/browser/media/connectionViewletPanel.css
src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts

Remove server group colors from connection profile in OE

---

extensionsGallery-insider.json
extensionsGallery.json

Update Powershell to 2023.6.0

---

product.json

This PR fixes #23588
I used the copilot extension before and after adding this proposed API and didn't find anything that would negatively impact how the extension works. Adding the proposed API from this PR will remove the console warning message seen in the issue description.

Add proposed interactive copilot API

---

resources/xlf/en/sql.xlf

[Loc] update for Wednesday prior to code complete

---

extensionsGallery-insider.json
extensionsGallery.json

VSIX files location: https://github.com/microsoft/azuredatastudio-postgresql/releases/download/v0.4.2/azuredatastudio-postgresql-0.4.2.vsix

PostgreSQL Extension to 0.4.2

---

extensions/mssql/src/objectManagement/commands.ts
extensions/mssql/src/objectManagement/constants.ts
extensions/mssql/src/objectManagement/interfaces.ts
extensions/mssql/src/objectManagement/localizedConstants.ts
extensions/mssql/src/objectManagement/ui/serverPropertiesDialog.ts
extensions/mssql/src/objectManagement/utils.ts
extensions/mssql/src/test/util/utils.test.ts

I separated the changes from the other PR to only include the server properties fixes.
Included the fix for https://github.com/microsoft/azuredatastudio/issues/23652
Also fixed the issue for dialog not opening properties when user is connected to localhost and a database

Server properties fixes

---

src/vs/workbench/services/themes/common/themeConfiguration.ts
src/vs/workbench/services/themes/common/workbenchThemeService.ts

restore default theme

---

src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts

this pr fixes #23678
before:
after:

fix button text issue in welcome page

---

resources/localization/LCL/de/sql.xlf.lcl
resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/it/sql.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/pt-BR/sql.xlf.lcl
resources/localization/LCL/ru/sql.xlf.lcl
resources/localization/LCL/zh-Hans/sql.xlf.lcl
resources/localization/LCL/zh-Hant/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230707153920135 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230707153920135 to main

---

extensions/azuremonitor/package.json
extensions/azuremonitor/yarn.lock
extensions/datavirtualization/package.json
extensions/datavirtualization/yarn.lock
extensions/import/package.json
extensions/import/yarn.lock
extensions/kusto/package.json
extensions/kusto/yarn.lock
extensions/mssql/package.json
extensions/mssql/yarn.lock
extensions/sql-migration/package.json
extensions/sql-migration/yarn.lock

Fixes https://github.com/microsoft/azuredatastudio/issues/23565
Fixes https://github.com/microsoft/azuredatastudio/issues/23677
See https://github.com/microsoft/sqlops-dataprotocolclient/pull/89 for more details about the issue

Update dataprotocolclient to 1.3.6

---

extensions/mssql/src/objectManagement/interfaces.ts
extensions/mssql/src/objectManagement/localizedConstants.ts
extensions/mssql/src/objectManagement/ui/serverPropertiesDialog.ts
extensions/mssql/src/ui/dialogBase.ts

Check for minimum and maximum value for memory settings

Add memory inputs validation

---

extensions/mssql/config.json

Include latest commits for basic admin bug fixes

include latest changes in sts

---

resources/localization/LCL/de/sql.xlf.lcl
resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/it/sql.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/pt-BR/sql.xlf.lcl
resources/localization/LCL/ru/sql.xlf.lcl
resources/localization/LCL/zh-Hans/sql.xlf.lcl
resources/localization/LCL/zh-Hant/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230708154147687 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230708154147687 to main

---

resources/localization/LCL/fr/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230709153719563 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230709153719563 to main

---

package.json

updating post release branch split

---

extensions/profiler/package.json

Update profiler extension to pick new changes for opening XEL files.

Vbump profiler extension

---

extensions/profiler/package.json

Update profiler extension to pick new changes for opening XEL files.

Update profiler version and related azdata dependency

---

i18n/ads-language-pack-de/translations/main.i18n.json
i18n/ads-language-pack-es/translations/main.i18n.json
i18n/ads-language-pack-fr/translations/main.i18n.json
i18n/ads-language-pack-it/translations/main.i18n.json
i18n/ads-language-pack-ja/translations/main.i18n.json
i18n/ads-language-pack-ko/translations/main.i18n.json
i18n/ads-language-pack-pt-BR/translations/main.i18n.json
i18n/ads-language-pack-ru/translations/main.i18n.json
i18n/ads-language-pack-zh-hans/translations/main.i18n.json
i18n/ads-language-pack-zh-hant/translations/main.i18n.json
resources/xlf/de/sql.de.xlf
resources/xlf/es/sql.es.xlf
resources/xlf/fr/sql.fr.xlf
resources/xlf/it/sql.it.xlf
resources/xlf/ja/sql.ja.xlf
resources/xlf/ko/sql.ko.xlf
resources/xlf/pt-br/sql.pt-BR.xlf
resources/xlf/ru/sql.ru.xlf
resources/xlf/zh-hans/sql.zh-Hans.xlf
resources/xlf/zh-hant/sql.zh-Hant.xlf

This is for a port request PR for 1.45

[Loc] added translated getting started to langpack

---

i18n/ads-language-pack-de/translations/main.i18n.json
i18n/ads-language-pack-es/translations/main.i18n.json
i18n/ads-language-pack-fr/translations/main.i18n.json
i18n/ads-language-pack-it/translations/main.i18n.json
i18n/ads-language-pack-ja/translations/main.i18n.json
i18n/ads-language-pack-ko/translations/main.i18n.json
i18n/ads-language-pack-pt-BR/translations/main.i18n.json
i18n/ads-language-pack-ru/translations/main.i18n.json
i18n/ads-language-pack-zh-hans/translations/main.i18n.json
i18n/ads-language-pack-zh-hant/translations/main.i18n.json
resources/xlf/de/sql.de.xlf
resources/xlf/es/sql.es.xlf
resources/xlf/fr/sql.fr.xlf
resources/xlf/it/sql.it.xlf
resources/xlf/ja/sql.ja.xlf
resources/xlf/ko/sql.ko.xlf
resources/xlf/pt-br/sql.pt-BR.xlf
resources/xlf/ru/sql.ru.xlf
resources/xlf/zh-hans/sql.zh-Hans.xlf
resources/xlf/zh-hant/sql.zh-Hant.xlf

Fixes https://github.com/microsoft/azuredatastudio/issues/23745

[Loc] added translated getting started to langpack (#23744)

---

extensionsGallery-insider.json

Insiders langpack gallery update for release/extensions:
Langpacks can be found here:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=205708&view=artifacts&pathAsName=false&type=publishedArtifacts

July update to insiders gallery langpacks for release/extensions

---

extensionsGallery-insider.json
extensionsGallery.json

Same langpacks as https://github.com/microsoft/azuredatastudio/pull/23748

Update to extensions rc1 langpack for July release.

---

src/sql/base/browser/ui/dropdownList/dropdownList.ts

Account Picker Dropdown in the Firewall Rule Dialog was not expanding when clicked, this fixes that issue.
Fixes: https://github.com/microsoft/azuredatastudio/issues/23707

[Port] Fix dropdown behavior (#23708)

---

extensions/mssql/package.json
extensions/mssql/package.nls.json
extensions/mssql/src/objectManagement/commands.ts

Fix https://github.com/microsoft/azuredatastudio/issues/23731

Create new context menu item for Database (#23771)

---

extensionsGallery-insider.json

This PR closes #23663 
Update Copilot version in the insiders extension gallery to 1.95.239 to align with Copilot proposed API changes.
Link to files to upload: https://microsoft-my.sharepoint.com/:f:/p/lewissanchez/IgA67soStD2xT7Q15op97pP4AdJfPwISUMmDSvmErITyx2o?e=j0IK6t

Update copilot to 1.95.239 for updated API proposals metadata

---

src/vs/platform/configuration/test/common/testConfigurationService.ts
src/vs/workbench/contrib/experiments/test/electron-sandbox/experimentService.test.ts
src/vs/workbench/contrib/terminalContrib/accessibility/test/browser/bufferContentTracker.test.ts
src/vs/workbench/contrib/terminalContrib/links/test/browser/terminalLinkManager.test.ts
src/vs/workbench/contrib/welcomeGettingStarted/test/browser/gettingStartedMarkdownRenderer.test.ts
src/vs/workbench/services/configuration/test/browser/configuration.test.ts
src/vs/workbench/services/configuration/test/browser/configurationEditing.test.ts
src/vs/workbench/services/configuration/test/browser/configurationService.test.ts
src/vs/workbench/services/configurationResolver/test/electron-sandbox/configurationResolverService.test.ts
src/vs/workbench/services/editor/test/browser/editorResolverService.test.ts
src/vs/workbench/services/extensionManagement/test/browser/extensionEnablementService.test.ts
src/vs/workbench/services/extensions/test/browser/extensionService.test.ts
src/vs/workbench/services/history/test/browser/historyService.test.ts

This PR fixes #23780
The PR is intended to bring test stability and reliability to the release branch pipelines.

[Port] Fix flaky ADS unit tests by using DOM rendering (#23770)

---

src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts

Fixes: #22883 
I was not able to repro the bug on my end. However, adding null checks should fix this error

Adding null checks in disconnecting connections from async tree

---

resources/xlf/en/sql.xlf

[Loc] small update for sql XLF for 7-11 2023

---

src/sql/workbench/services/connection/browser/connectionManagementService.ts
src/sql/workbench/services/objectExplorer/browser/treeSelectionHandler.ts

This PR fixes #23604 
Original PR #23758

Fixing unsupported providers behavior on Async Server Tree (#23758)

---

extensions/mssql/config.json

Fixes this issue in the New Database dialog: https://github.com/microsoft/azuredatastudio/issues/23729
New changes in this version:

Bump SQL Tools version to 4.9.0.3

---

extensionsGallery-insider.json
extensionsGallery.json

This PR closes #23782
The PR bumps the copilot extension in the stable extension gallery to 1.95.239
Files to upload: https://microsoft-my.sharepoint.com/:f:/p/lewissanchez/IgA67soStD2xT7Q15op97pP4AdJfPwISUMmDSvmErITyx2o?e=hMAylX

Bumps Copilot extension version to 1.95.239

---

extensions/mssql/src/objectManagement/ui/databaseDialog.ts

This PR disables the Ledger Property from the database properties dialog.

Making IsLedger Property to Read-only

---

extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/wizard/skuRecommendationPage.ts

Description:
1. Renamed constant name fixing typo.
2. Reduced number of method calls for same method.

Minor bug-fixing and optimization method call reduction

---

product.json

(cherry picked from commit 8bdc7d0346b8a42662d6d1f2c59943d3dee779e6)
For https://github.com/microsoft/azuredatastudio/issues/23834

Update telemetry opt out URL (#23835)

---

src/sql/workbench/contrib/charts/browser/graphInsight.ts

Fixing graph insights min max scale values 

---

src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookSearch.ts

For #23793 
VSCode updated ITreeElement with ICmpressedTreeElement on the search results view.

update ITreeElement with ICompressedTreeElement

---

src/sql/workbench/services/dialog/browser/dialogModal.ts
src/sql/workbench/services/dialog/browser/wizardModal.ts
src/tsec.exemptions.json

Fixes https://github.com/microsoft/azuredatastudio/issues/23827
(cherry picked from commit d294c81588950dcdb80453bb8aa066fc40581fb1)

[Port] Fix dialog buttons (#23843)

---

extensions/mssql/config.json

Fixes https://github.com/microsoft/azuredatastudio/issues/23729
Included commits in this version bump:

Update SQL Tools version to 4.8.1.3

---

src/sql/workbench/contrib/charts/browser/graphInsight.ts

Fixes: #23818 
PR to main branch: #23831

Fixing chartjs scale values in release 

---

resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/it/sql.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/pt-BR/sql.xlf.lcl
resources/localization/LCL/ru/sql.xlf.lcl
resources/localization/LCL/zh-Hans/sql.xlf.lcl
resources/localization/LCL/zh-Hant/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230713153841427 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230713153841427 to main

---

src/sql/workbench/contrib/connection/browser/connection.contribution.ts

Fixes: #23833 
PR to main branch: #23849

Fixing azdata connect command not adding connection to OE in release. 

---

src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookSearch.ts

Fixes #23793 
cherry picked from commit [4d6b657](https://github.com/microsoft/azuredatastudio/commit/4d6b657e5db7096d1be6521ca93d63f887ed50f5)

[Port] update ITreeElement with ICompressedTreeElement (#23839)

---

src/sql/workbench/services/fileBrowser/browser/fileBrowserDialog.ts

(cherry picked from commit db4e12577b5bbd19c2f65e5facf995c218aafa12)
Fixes https://github.com/microsoft/azuredatastudio/pull/23867

[Port] Fix file browser opening race condition

---

extensions/sql-database-projects/src/dialogs/createProjectFromDatabaseDialog.ts

Fixes #23861. Cherry-picked 221408c7a3273ce4fc401f98ae9ecd94e0c8fc91

[Port] Fix error when opening create project from db dialog without connection

---

src/sql/workbench/contrib/notebook/browser/cellToolbarActions.ts
src/sql/workbench/contrib/notebook/browser/notebook.component.ts

Fixes: https://github.com/microsoft/azuredatastudio/issues/23826
PR in main: https://github.com/microsoft/azuredatastudio/pull/23870

[Port] Fix Notebook toolbar and cell toolbar dropdown alignment

---

resources/localization/LCL/de/sql.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230714154102378 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230714154102378 to main

---

src/sql/workbench/services/fileBrowser/browser/fileBrowserDialog.ts

(cherry picked from commit 46f5f7a216b0b4069b7b8a11495ad25c9fafa25f)
Fixes https://github.com/microsoft/azuredatastudio/issues/23832

Better fix for file browser race condition

---

src/sql/workbench/services/connection/browser/connectionManagementService.ts

Ports https://github.com/microsoft/azuredatastudio/pull/23884 to release/1.45

[Release/1.45] Fix serverInfo undefined due to wrong connection URI set on connection

---

extensionsGallery-insider.json
extensionsGallery.json

Azure PostgreSQL Migration Next Release 2.0.6

Azure PostgreSQL Migration Next Release 2.0.6

---

extensionsGallery-insider.json

Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=206555&view=artifacts&pathAsName=false&type=publishedArtifacts

Update insiders for Dacpac, Schema compare, Sql Projects and Profiler

---

package.json
remote/package.json
remote/web/package.json
remote/web/yarn.lock
remote/yarn.lock
yarn.lock

This PR fixes #23509 by updating the xterm-canvas-addon package to version 0.4.2.

Updates the xterm-addon-canvas package to 0.4.2

---

package.json
remote/package.json
remote/web/package.json
remote/web/yarn.lock
remote/yarn.lock
yarn.lock

This PR fixes #https://github.com/microsoft/azuredatastudio/issues/23915
The PR switches the xterm-addon-canvas version to an official package version.

Switch xterm-addon-canvas to official version

---

extensions/mssql/config.json
src/sql/platform/connection/common/connectionConfig.ts
src/sql/platform/connection/common/connectionProfile.ts

Ports #23924 to release/1.45 branch to address #23921 
Paired with https://github.com/microsoft/sqltoolsservice/pull/2152

[Release/1.45] Allow empty username + fix profiles on read (#23924)

---

extensionsGallery.json

Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=206555&view=artifacts&pathAsName=false&type=publishedArtifacts

Update version of Dacpac, Schema compare, Sql Projects and Profiler extensions in RC branch

---

src/sql/workbench/services/connection/browser/connectionManagementService.ts

Fixes: #23931 
PR to main branch:  #23933

Fix connection drag and drop in release.

---

src/sql/workbench/browser/modal/optionsDialog.ts
src/sql/workbench/contrib/notebook/browser/calloutDialog/imageCalloutDialog.ts
src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts
src/sql/workbench/contrib/notebook/browser/find/notebookFindWidget.ts
src/sql/workbench/contrib/profiler/browser/profilerFindWidget.ts
src/sql/workbench/services/backupRestoreUrlBrowser/browser/urlBrowserDialog.ts
src/vs/base/common/themables.ts
src/vs/platform/extensionManagement/common/extensionGalleryService.ts
src/vs/workbench/services/themes/browser/workbenchThemeService.ts

Remove some of the SQL CARBON TODOs for dead code or areas that don't require additional updates.

Remove some TODOs mostly for styling

---

.config/CredScanSuppressions.json

Scanner filed a few issues with the new vscode merge, suppressing them since both aren't actually valid problems.
Fixes https://msdata.visualstudio.com/Database%20Systems/_queries/edit/2504173/?triage=true filed issue.

Suppress cred scan issues

---

src/sql/workbench/services/accountManagement/browser/accountDialog.ts

Before: If multiple clouds are enabled, when the user selects the Add Account Action from the Account Dialog, they will be prompted asking which cloud (provider) they want to add an account for, even though there are separate add account icons for each cloud provider (as shown in the image below)
After: The provider ID is passed to the runAddAccountAction so it does not need to prompt the user asking which cloud they want to add an account for.
Fixes https://github.com/microsoft/azuredatastudio/issues/23207

Pass provider ID info to runAddAccountAction

---

src/sql/workbench/contrib/views/browser/treeView.ts

Ports #23948 to `release/1.45` branch
Fixes https://github.com/microsoft/azuredatastudio/issues/23941 
Fixes https://github.com/microsoft/azuredatastudio/issues/23942

[Release/1.45] Fix context menu in treeViews (#23948)

---

resources/xlf/en/sql.xlf

[Loc] update to sql xlf for 7-21-2023

---

resources/localization/LCL/de/sql.xlf.lcl
resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/it/sql.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/pt-BR/sql.xlf.lcl
resources/localization/LCL/ru/sql.xlf.lcl
resources/localization/LCL/zh-Hans/sql.xlf.lcl
resources/localization/LCL/zh-Hant/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230723153919791 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230723153919791 to main

---

src/sql/workbench/contrib/views/browser/treeView.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/23941
(cherry picked from commit a182b852b125c0daa950d4c069b27aefff722d91)

[Port] Temporary fix for Data Explorer context menus (#23957)

---

extensionsGallery-insider.json

**EDITED:**
vsix file: https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.4.3-insiders

[PostgreSQL] Release v0.4.3 to Insiders

---

extensionsGallery-insider.json
extensionsGallery.json

Good day,
I would like to add SearchEverywhere extension. I think it could be useful for ads users.

Update extensionsGallery.json SearchEverywhere extension added

---

CHANGELOG.md

Changelog for 1.45

---

CHANGELOG.md

fixing where the table didnt format correctly

fixing the minor changelog issue with table

---

CHANGELOG.md

Erpett/changelog port1.45

---

extensionsGallery-insider.json
extensionsGallery.json

Please find the vsix package [here](https://msdata.visualstudio.com/_apis/resources/Containers/201634025/drop?itemPath=drop%2Fazure-cosmosdb-ads-extension-0.3.5.vsix)

Update Cosmos DB extension to version 0.3.5

---

extensions/azurecore/src/account-provider/auths/azureAuth.ts
extensions/azurecore/src/constants.ts

Added more relevant error codes for account refresh
ref: https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-error-codes

Added more relevant error codes

---

extensions/mssql/src/objectManagement/ui/objectManagementDialogBase.ts
extensions/mssql/src/ui/scriptableDialogBase.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/23723
Fixes https://github.com/microsoft/azuredatastudio/issues/23646

Connect query editor when producing script from object management dialogs.

---

product.json

(cherry picked from commit b08d33dcd7a3325c77ed23980048fb1d3ebd18db)
For https://github.com/microsoft/azuredatastudio/issues/24021

[Port] Update vs code engine version to 1.79.2 (#24020)

---

build/npm/gyp/package.json
build/npm/gyp/yarn.lock
build/npm/preinstall.js

(cherry picked from commit f99fd366afc177f82dca883df235a7e02fc1a99b)

[Port] Bump node-gyp to 9.4.0 (#24034)

---

src/vs/base/common/event.ts

Commenting out listener threshold to fix extensions having mem leaks

---

src/sql/workbench/contrib/profiler/browser/profilerEditor.ts
src/sql/workbench/services/profiler/browser/profilerService.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/23998
Original PR: https://github.com/microsoft/azuredatastudio/pull/24019

(July hotfix port) Update session dropdown and fix running state info 

---

src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts

Porting https://github.com/microsoft/azuredatastudio/issues/24038 to release/1.45 branch
Fixes #24027

[Release/1.45] Add null checks for server tree view (#24038)

---

extensionsGallery-insider.json
extensionsGallery.json

vsix file: https://github.com/microsoft/azuredatastudio-postgresql/releases/download/v0.5.0/azuredatastudio-postgresql-0.5.0.vsix

[PostgreSQL] Release v0.5.0

---

resources/xlf/en/sql.xlf

[Loc] update to SQL XLF for 8-1-2023

---

resources/localization/LCL/de/sql.xlf.lcl
resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/it/sql.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/pt-BR/sql.xlf.lcl
resources/localization/LCL/ru/sql.xlf.lcl
resources/localization/LCL/zh-Hans/sql.xlf.lcl
resources/localization/LCL/zh-Hant/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230803153959515 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230803153959515 to main

---

build/azure-pipelines/darwin/sql-product-build-darwin.yml
build/azure-pipelines/docker/sql-product-build-docker.yml
build/azure-pipelines/linux/sql-product-build-linux.yml
build/azure-pipelines/sql-product-compile.yml
build/azure-pipelines/web/sql-product-build-web.yml
build/azure-pipelines/win32/sql-product-build-win32.yml

We've been getting intermittent errors when performing `git fetch distro` in pipelines on multiple OSes, stages/jobs.
The error messages are as:
- error: RPC failed; HTTP 500 curl 56 GnuTLS recv error (-54): Error in the pull function. ([link](https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=208194&view=logs&j=bd1e231b-cef9-51a2-e461-b67194c0a817&t=ab758b51-335c-5fef-2682-4f91bf9267f0&l=12))
- error: RPC failed; HTTP 500 curl 56 Recv failure: Connection reset by peer 
fatal: expected 'acknowledgments' ([link](https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=208202&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=77130470-8bc4-5ef7-e47e-b9c1547cf69d&l=12))
- error: RPC failed; HTTP 500 curl 56 Recv failure: Connection reset …

Update git configs

---

resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230804154154390 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230804154154390 to main

---

src/sql/base/browser/ui/selectBox/selectBox.ts
src/sql/workbench/services/connection/browser/connectionWidget.ts

Convert values to string when selecting in selectbox

---

extensionsGallery-insider.json
extensionsGallery.json

Releasing the extension to marketplace for public preview.

New extension for migrating data from Oracle to Azure SQL

---

CHANGELOG.md

changelog update post hotfix release

---

extensionsGallery-insider.json
extensionsGallery.json

Please find the binary [here](https://msdata.visualstudio.com/_apis/resources/Containers/203067248/drop?itemPath=drop%2Fazure-cosmosdb-ads-extension-0.3.6.vsix).

Update Cosmos DB extension to version 0.3.6

---

extensionsGallery-insider.json

Build: 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=208742&view=artifacts&pathAsName=false&type=publishedArtifacts

Updating import in insiders to 1.5.6

---

extensions/mssql/src/objectManagement/ui/applicationRoleDialog.ts
extensions/mssql/src/objectManagement/ui/databaseDialog.ts
extensions/mssql/src/objectManagement/ui/databaseRoleDialog.ts
extensions/mssql/src/objectManagement/ui/findObjectDialog.ts
extensions/mssql/src/objectManagement/ui/loginDialog.ts
extensions/mssql/src/objectManagement/ui/serverPropertiesDialog.ts
extensions/mssql/src/objectManagement/ui/serverRoleDialog.ts
extensions/mssql/src/objectManagement/ui/userDialog.ts
extensions/mssql/src/ui/dialogBase.ts

Use the new inputbox create method and send custom properties.
Fix https://github.com/microsoft/azuredatastudio/issues/23742

Refactor create  inputbox method

---

resources/localization/LCL/ko/Microsoft.kusto.xlf.lcl

[Loc] fix for already localized Korean file

---

resources/xlf/en/Microsoft.mssql.xlf

[Loc] update to MSSQL XLF for 8-16-2023

---

src/sql/workbench/browser/editor/profiler/dashboardInput.ts
src/sql/workbench/contrib/dashboard/browser/services/breadcrumb.service.ts

Added changes to breadcrumb service and dashboard tab.

---

extensions/azurecore/src/account-provider/auths/azureAuth.ts

Moving from http client back to axios, customers were reporting proxy issues and this fixes them.

Change proxy to Axios

---

build/azure-pipelines/win32/sql-product-build-win32.yml
extensions/mssql/config.json

Adding sql core dll to esrp code signing and updating sts

---

.github/CODEOWNERS

Removing Aasim from query store codeowners to not spam him with PR notifications since he isn't actively working on it anymore :)

update Query Store codeowners

---

extensionsGallery-insider.json
extensionsGallery.json

Bump version of schema-visualization extension

bump version

---

extensions/mssql/config.json

Update STS to 4.9.0.18

---

extensions/mssql/src/objectManagement/ui/serverPropertiesDialog.ts

Fix https://github.com/microsoft/azuredatastudio/issues/24195

Enable script button for Server properties

---

extensionsGallery-insider.json
extensionsGallery.json

Release/extensions Join [MSSQL]Store Procedure To Sql 

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230822154732412 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230822154732412 to main

---

src/sql/workbench/contrib/query/browser/queryEditor.ts

Remove SQLCMD button from preview

---

src/sql/workbench/contrib/query/browser/queryEditor.ts

Reverts microsoft/azuredatastudio#24224 - not ready to preview this yet...my bad for not making the PR a draft!

Revert "Remove SQLCMD button from preview"

---

resources/xlf/en/sql.xlf
src/sql/workbench/contrib/editData/browser/editDataActions.ts

[Loc] update to editDataActions close SQL button

---

resources/localization/LCL/de/sql.xlf.lcl
resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/it/sql.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/pt-BR/sql.xlf.lcl
resources/localization/LCL/ru/sql.xlf.lcl
resources/localization/LCL/zh-Hans/sql.xlf.lcl
resources/localization/LCL/zh-Hant/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230827154022575 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230827154022575 to main

---

extensions/mssql/config.json

STS version bump to 4.9.0.25

---

extensions/mssql/src/objectManagement/constants.ts
extensions/mssql/src/objectManagement/interfaces.ts
extensions/mssql/src/objectManagement/localizedConstants.ts
extensions/mssql/src/objectManagement/ui/serverPropertiesDialog.ts

Add security tab for server properties

---

src/sql/base/browser/ui/propertiesContainer/propertiesContainer.component.ts
src/sql/base/browser/ui/table/asyncDataView.ts
src/sql/base/browser/ui/table/hybridDataProvider.ts
src/sql/base/browser/ui/table/plugins/checkboxColumn.plugin.ts
src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts
src/sql/base/browser/ui/table/plugins/copyKeybind.plugin.ts
src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
src/sql/base/browser/ui/table/plugins/tableColumn.ts
src/sql/base/browser/ui/table/tableDataView.ts
src/sql/base/parts/tree/browser/treeImpl.ts
src/sql/base/parts/tree/browser/treeModel.ts
src/sql/base/parts/tree/browser/treeView.ts
src/sql/base/parts/tree/browser/treeViewModel.ts
src/sql/base/parts/tree/test/browser/treeModel.test.ts
src/sql/base/test/browser/ui/editableDropdown/dropdown.test.ts
src/sql/base/test/browser/ui/selectBox/selectBox.test.ts

More changes to follow to dispose these disposables in next PRs.

Part 3 - Make base browser components disposable

---

resources/xlf/en/Microsoft.mssql.xlf
resources/xlf/en/Microsoft.query-store.xlf
resources/xlf/en/sql.xlf

[Loc] xlf update for 8-29-2023

---

extensions/azurecore/package.json
extensions/azurecore/src/constants.ts
extensions/azurecore/src/telemetry.ts
extensions/azurecore/src/utils.ts
extensions/azurecore/yarn.lock

Adds telemetry to custom provider endpoints
Fixes #23922

Add telemetry to custom provider endpoints

---

resources/xlf/en/Microsoft.mssql.xlf

[Loc] update to MSSQL xlf for 8-30-2023

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/de/Microsoft.query-store.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.query-store.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.query-store.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.query-store.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.query-store.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.query-store.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.query-store.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.query-store.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.query-store.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.query-store.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230831153956722 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230831153956722 to main

---

resources/xlf/en/Microsoft.mssql.xlf

[Loc] update to MSSQL xlf for 8-31-2023

---

extensions/mssql/config.json

This PR bumps the STS version to 4.9.0.28

Bump STS version to 4.9.0.28

---

extensions/mssql/src/contracts.ts

This PR fixes a comment block footer for the server contextualization API.

Fix comment block footer for Server Contextualization API

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.query-store.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.query-store.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.query-store.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230901154338064 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230901154338064 to main

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230902183958559 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230902183958559 to main

---

extensions/mssql/config.json

Bumping SqlToolsService to 4.9.0.29

---

extensions/mssql/config.json

Update STS to 4.9.0.31

---

extensions/mssql/config.json

Bump STS version to 4.9.0.32

---

extensionsGallery-insider.json

Update sql projects in insiders to 1.3.0. Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=211080&view=artifacts&pathAsName=false&type=publishedArtifacts

update sql projects to 1.3.0 in insiders

---

resources/xlf/en/Microsoft.mssql.xlf
resources/xlf/en/Microsoft.query-store.xlf
resources/xlf/en/sql.xlf

[Loc] xlf update for 9-6-2023

---

extensions/sql-migration/package.json

Bump-up SQL-Migration Extension Version as we have some changes in this extension.

SQL-Migration Extension Version bump-up

---

samples/sqlservices/.vscode/launch.json
samples/sqlservices/README.md

Adding additional info to sample readme, updating product strings

---

extensions/data-workspace/src/common/promise.ts
extensions/sql-database-projects/src/common/promise.ts

Cleaning up the casing in a couple other places, as mentioned in https://github.com/microsoft/azuredatastudio/pull/24303#discussion_r1317945532.

cleanup casing in a couple files

---

src/vs/workbench/contrib/debug/browser/debugCommands.ts

Marking carbon edit with begin and end tags. Makes resolving merge conflicts during the VS Code merge process a little easier

Mark carbon edit with begin and end tags

---

resources/xlf/en/Microsoft.query-store.xlf
resources/xlf/en/sql.xlf

[Loc] final XLF update prior to code complete for 9-7-2023

---

src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts

Fixes #24297 
_Bug introduced in #24244_

Fixes a typo in headerfilter plugin

---

extensions/mssql/src/objectManagement/ui/databaseDialog.ts
extensions/mssql/src/ui/dialogBase.ts

Accidentally added these changes to the PR and merged without knowing. This won't cause any issue opening the properties and saving but row filegroup table. Reverting all the unwanted changes.

Revert the changes of row fileGroup table which was added accidentally

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/de/Microsoft.query-store.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.query-store.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.query-store.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.query-store.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.query-store.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.query-store.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.query-store.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/sql.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.query-store.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.query-store.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/sql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.query-store.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230908183910058 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230908183910058 to main

---

extensions/mssql/package.nls.json

Update placeholder text for mssql server name

---

resources/xlf/en/Microsoft.mssql.xlf

[Loc] update to MSSQL xlf for 9-8-2023

---

extensions/mssql/config.json

Fixes https://github.com/microsoft/azuredatastudio/issues/24166

update STS to 4.9.0.37

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/de/Microsoft.query-store.xlf.lcl
resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/de/sql.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.query-store.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.query-store.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/sql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.query-store.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.query-store.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230909153928076 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230909153928076 to main

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/de/sql.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/sql.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.query-store.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.query-store.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/sql.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.query-store.xlf.lcl
resources/localization/LCL/ru/sql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/sql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.query-store.xlf.lcl
resources/localization/LCL/zh-Hant/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230910154305184 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230910154305184 to main

---

extensionsGallery-insider.json
extensionsGallery.json

Updated SQL 4 CDS extension to 7.5.1

---

extensions/mssql/config.json

STS vbump to 4.10.0.1

---

extensions/mssql/src/objectManagement/interfaces.ts
extensions/mssql/src/objectManagement/localizedConstants.ts
extensions/mssql/src/objectManagement/objectManagementService.ts
extensions/mssql/src/objectManagement/ui/databaseDialog.ts
extensions/mssql/src/objectManagement/ui/databaseFileDialog.ts

This PR fixes the below issues:
1. https://github.com/microsoft/azuredatastudio/issues/24359
2. https://github.com/microsoft/azuredatastudio/issues/24307
3. https://github.com/microsoft/azuredatastudio/issues/24197
4. https://github.com/microsoft/azuredatastudio/issues/24196
5. https://github.com/microsoft/azuredatastudio/issues/24192
6. https://github.com/microsoft/azuredatastudio/issues/24371
7. https://github.com/microsoft/azuredatastudio/issues/24372

Database properties options fixes

---

extensions/mssql/src/objectManagement/interfaces.ts
extensions/mssql/src/objectManagement/localizedConstants.ts
extensions/mssql/src/objectManagement/objectManagementService.ts
extensions/mssql/src/objectManagement/ui/databaseDialog.ts
extensions/mssql/src/objectManagement/ui/databaseFileDialog.ts

Below all fixes are addressed in this PR:
1. https://github.com/microsoft/azuredatastudio/issues/24359
2. https://github.com/microsoft/azuredatastudio/issues/24307
3. https://github.com/microsoft/azuredatastudio/issues/24197
4. https://github.com/microsoft/azuredatastudio/issues/24196
5. https://github.com/microsoft/azuredatastudio/issues/24192
6. https://github.com/microsoft/azuredatastudio/issues/24371
7. https://github.com/microsoft/azuredatastudio/issues/24372

Cherry Pick - Database properties fixes

---

extensions/mssql/src/objectManagement/constants.ts
extensions/mssql/src/objectManagement/interfaces.ts
extensions/mssql/src/objectManagement/localizedConstants.ts
extensions/mssql/src/objectManagement/ui/serverPropertiesDialog.ts

* fix locks min value
* disable login auditing in linux
* disable some properties from advanced tab
Fix https://github.com/microsoft/azuredatastudio/pull/24366

More server properties fixes (#24366)

---

extensions/mssql/config.json

sts vBump 4.9.1.2 from 4.9.0.37

---

extensions/mssql/package.json

Adding new database inline icon

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/de/Microsoft.query-store.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.query-store.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.query-store.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.query-store.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.query-store.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.query-store.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230912153919267 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230912153919267 to main

---

extensions/mssql/package.json

Original PR: #24375 
Fixes Issue: #23655

Adding new database inline icon in release (#24375)

---

src/sql/workbench/browser/modelComponents/componentBase.ts

Fix https://github.com/microsoft/azuredatastudio/issues/24200

handle error scenarios for validity check (#24393)

---

extensions/mssql/package.json

Enable Server properties, Database Properties, and Detach Database functionality in stable
For: https://github.com/microsoft/azuredatastudio/issues/24404

Enable server and db properties and detach db

---

extensions/mssql/package.json

Fix https://github.com/microsoft/azuredatastudio/issues/24404

enable server and db properties (#24406)

---

extensions/azurecore/src/account-provider/auths/azureAuth.ts
extensions/azurecore/src/constants.ts

Addresses #24419
Handle error code AADSTS700082 and prompt user to re-authenticate.
Reference: [MS Docs](https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-error-codes#:~:text=amount%20of%20time.-,AADSTS700082,-ExpiredOrRevokedGrantInactiveToken%20%2D%20The%20refresh)

Prompt to refresh account on error AADSTS700082

---

extensions/azurecore/src/account-provider/auths/azureAuth.ts
extensions/azurecore/src/constants.ts

Ports #24423 to release/1.46
Addresses https://github.com/microsoft/azuredatastudio/issues/24419

[Release/1.46] Prompt to refresh account on error AADSTS700082 (#24423)

---

extensions/notebook/src/jupyter/jupyterServerInstallation.ts
extensions/notebook/src/test/python/jupyterInstallation.test.ts

Fixes: https://github.com/microsoft/azuredatastudio/issues/24405
PR in main: https://github.com/microsoft/azuredatastudio/pull/24429

[Release/1.46] Pin ipykernel package to v5.5.5

---

extensions/notebook/src/jupyter/jupyterServerInstallation.ts
extensions/notebook/src/test/python/jupyterInstallation.test.ts

Addresses: https://github.com/microsoft/azuredatastudio/issues/24443

Pin traitlets package to v5.9.0

---

extensions/notebook/src/jupyter/jupyterServerInstallation.ts
extensions/notebook/src/test/python/jupyterInstallation.test.ts

Fixes: https://github.com/microsoft/azuredatastudio/issues/24443
PR in main: https://github.com/microsoft/azuredatastudio/pull/24444

[Release/1.46] Pin traitlets package to v5.9.0

---

extensions/mssql/src/ui/scriptableDialogBase.ts

Fix https://github.com/microsoft/azuredatastudio/issues/24311

[Port Request] Fix enable/disable script button behavior 

---

extensionsGallery.json

Build with schema compare and sql projects vsixs: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=211925&view=artifacts&pathAsName=false&type=publishedArtifacts

update schema compare and sql projects in RC gallery

---

extensionsGallery.json

Companion PR to https://github.com/microsoft/azuredatastudio/pull/24454

Update to RC 1 langpack gallery for September 2023

---

extensionsGallery-insider.json
extensionsGallery.json

Langpack gallery update for insiders
langpacks found here: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=211925&view=artifacts&pathAsName=false&type=publishedArtifacts

Update to langpack gallery for insiders September 2023

---

extensionsGallery-insider.json

same extensions as the ones that were uploaded for RC build in https://github.com/microsoft/azuredatastudio/pull/24453

update schema compare and sql projects in insiders

---

extensions/sql-migration/src/constants/helper.ts
extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/constants/styles.ts
extensions/sql-migration/src/wizard/assessmentDetailsPage/assessmentDetailsHeader.ts
extensions/sql-migration/src/wizard/assessmentDetailsPage/assessmentDetailsPage.ts
extensions/sql-migration/src/wizard/assessmentDetailsPage/assessmentDetialsBody.ts
extensions/sql-migration/src/wizard/assessmentDetailsPage/databaseSummary.ts
extensions/sql-migration/src/wizard/assessmentDetailsPage/instanceSummary.ts
extensions/sql-migration/src/wizard/assessmentDetailsPage/issueSummary.ts
extensions/sql-migration/src/wizard/assessmentDetailsPage/treeComponent.ts
extensions/sql-migration/src/wizard/skuRecommendation/skuRecommendationPage.ts

This PR:
- Adds Select target functionality on Assessment Result page.
- All CSS fixes
- Added comments.
- Removed assessment dialog link on target selection page.
TODO:
Fix Recommended configuration value. (will be done once SKU recommendation page changes are merged)
Screenshot for Page:
Work Item link:
[Task 2637956](https://msdata.visualstudio.com/Database%20Systems/_workitems/edit/2637956): Assessment Selection based on target

[SQL Migration] [New Migration Experience] Select Target Platform Functionality

---

extensionsGallery-insider.json
extensionsGallery.json

Need to update the extension gallery with the latest extension from MongoDB (v 1.2.1)

Update extensionsGallery.json for mongodb

---

extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/constants/styles.ts
extensions/sql-migration/src/dialog/tdeConfiguration/tdeConfigurationDialog.ts

This Pull Request improves migration info text on the TDE configuration dialog of the Azure SQL Migration extension.
Before the change:
After the change:

SQL Migration (TDE) - Improved migration info text

---

extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/wizard/skuRecommendation/assessmentSummaryCard.ts
extensions/sql-migration/src/wizard/skuRecommendation/skuRecommendationPage.ts

1) Removed current skuRecommendation Page.
2) Added new skuRecommendation page with new assessment summary cards.
3) Updated Assessement summary result logic with actual data based on Assessment result. Also verified data is correct with one of the test servers.
4) Removed Target Selection and TDE option. Since they are moved to next page.
5) Removed Sku Recommendations options for now. Will add them later, once we start implementing the respective dialogs for Data Collection.

Assessment Summary backend changes

---

CHANGELOG.md

Changelog for 1.46

---

extensions/mssql/config.json
extensions/mssql/src/contracts.ts
extensions/mssql/src/mssql.d.ts
extensions/mssql/src/objectManagement/objectManagementService.ts
extensions/mssql/src/objectManagement/ui/databaseDialog.ts
extensions/mssql/src/objectManagement/ui/detachDatabaseDialog.ts
extensions/mssql/src/objectManagement/ui/dropDatabaseDialog.ts

The ADS half of this STS change: https://github.com/microsoft/sqltoolsservice/pull/2245
Leaving this as a draft until the new STS build is published.

Remove redundant usage of object URNs in database commands

---

extensions/schema-compare/package.json
extensions/sql-database-projects/package.json

vbump schema compare and sql projects after release

---

resources/xlf/en/Microsoft.notebook.xlf
resources/xlf/en/Microsoft.sql-migration.xlf

[Loc] update to langpacks for 9-22-2023

---

extensions/theme-solarized-light/package.nls.json
resources/xlf/en/Microsoft.sql-database-projects.xlf
resources/xlf/en/sql.xlf

[Loc] fix for package.nls.json and xlf update

---

extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/wizard/skuRecommendation/skuDataCollectionToolbar.ts
extensions/sql-migration/src/wizard/skuRecommendation/skuRecommendationPage.ts

Created a new start data collection popup window for selecting the path.
The actual data collection will be added in further PR.
Here is the screenshot for same -
Mocks for same - https://www.figma.com/file/EC2tJwlwy4RveRYhhGiHP4/Proposal-for-UI-improvement---SQL-Migration-ADS?type=whiteboard&node-id=0-1&t=CB5YVEg0XX4fijyE-0

Creating new start data collection popup window

---

extensions/mssql/src/objectManagement/commands.ts
extensions/mssql/src/objectManagement/constants.ts
extensions/mssql/src/objectManagement/ui/attachDatabaseDialog.ts
extensions/mssql/src/objectManagement/ui/detachDatabaseDialog.ts
extensions/mssql/src/objectManagement/ui/dropDatabaseDialog.ts
extensions/mssql/src/objectManagement/ui/objectManagementDialogBase.ts

Adds telemetry events for opening various basic admin dialogs as well as running operations after clicking OK in the dialog.

Add additional telemetry for basic admin operations

---

extensions/mssql/src/objectManagement/ui/loginDialog.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/23366

Move new login dialog's advanced options into the general section

---

extensions/sql-migration/src/wizard/skuRecommendation/skuDataCollectionToolbar.ts
extensions/sql-migration/src/wizard/skuRecommendation/skuRecommendationPage.ts

-> added functionality for refresh SKU Recommendation and Stop data collection buttons
Sample output for SKU Recommendation value

added functionality for refresh SKU Recommendation and Stop data collection buttons

---

extensions/sql-migration/src/wizard/assessmentDetailsPage/assessmentDetailsPage.ts
extensions/sql-migration/src/wizard/wizardController.ts

This PR:
Adds capability to save assessment report on new assessment results page.

[New Migration Experience] Save Assessment Report

---

.yarnrc
package.json
test/smoke/src/sql/main.ts
yarn.lock

Bump Electron to 22.3.25

---

.yarnrc
package.json
test/smoke/src/sql/main.ts
yarn.lock

Port Bump Electron to 22.3.15 (#24554) to release/1.46

Bump Electron to 22.3.15 (#24554)

---

resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230930153756674 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20230930153756674 to main

---

extensionsGallery-insider.json
extensionsGallery.json

Added definitions to `extensionsGallery.json` and `extensionsGallery-insider.json` for the Black color theme extension.

Added Black theme extension.

---

extensions/sql-migration/src/wizard/skuRecommendation/skuDataCollectionToolbar.ts

Updated editSkuRecommendationParam button to open dialog
Sample-

[New Migration Experience] updated editSkuRecommendationParam button to open dialog

---

extensions/sql-migration/src/dialog/skuRecommendationResults/skuEditParametersDialog.ts
extensions/sql-migration/src/wizard/skuRecommendation/assessmentSummaryCard.ts
extensions/sql-migration/src/wizard/skuRecommendation/skuRecommendationPage.ts

1) Added the "view details" link on sku recommendation summary.
2) Added opening of Sku Recommendation Result Dialog on "view details" link click.
3) Added card loading for Sku Recommendation summary update.
Sample for loading on Refresh SKU Recommendation - 
Sample for Sku recommendation summary with "view details" link -
Sample of SKU result dialog after "view details" link is clicked -

[New Migration Experience] Added opening SkuRecommendationResultDialog on link click

---

extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/wizard/skuRecommendation/skuRecommendationPage.ts

Created the assessment sku recommendation update notification.
Mocks - https://www.figma.com/file/UaD2zc58Y2iGKxnqDFQY3Q/End-to-End-Design-GA---SQL-Migration-ADS?type=design&node-id=2984-115159&mode=design&t=8suKXQpqbDX8UgIt-0
Sample Image -

[New Migration Experience] Created the assessment sku recommendation update notification.

---

extensionsGallery-insider.json

Update extensionsGallery-insider.json for releasing DMAO v4.2.2 in GA

Update extensionsGallery-insider.json for releasing DMAO v4.2.2 in GA

---

build/azure-pipelines/win32/sql-product-build-win32.yml

Updates the commit hash for the AGC merge coming from ads-release

Update commit hash for AGC merge

---

extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/wizard/skuRecommendation/assessmentSummaryCard.ts
extensions/sql-migration/src/wizard/skuRecommendation/skuDataCollectionToolbar.ts
extensions/sql-migration/src/wizard/skuRecommendation/skuRecommendationPage.ts

Changes include -
1) Added dropdown for RefreshAssessment and Refresh SKU.
2) Updated the default path for start data collection as per mocks.
3) Added Restart data collection functionality once users start and stop data collection after first time.
4) Updated the card loading to show correct message for data collection status.
5) Updated to call disposables for SKU data toolbar and assessment summary card once the view is closed.
6) Updated the visibilities of different buttons of sku toolbar based on status of sku data collection being start, stop and other stages.

[New Migration Experience] Update Refresh Buttons + other changes.

---

extensionsGallery-insider.json

Insider release for DSCT GA

---

extensionsGallery-insider.json

This PR add an entry for a new extension Database Migration Service pack for Oracle.

Update extensionsGallery-insider.json for releasing Database Migration Service Pack v1.1.1 in GA

---

.github/workflows/ci.yml

Updating to latest version of actions + node for extension gallery check

Update pipeline actions for validate extension gallery

---

extensionsGallery-insider.json

Version Change Insider for 'Extension for Oracle ' to 0.1.4

0.1.4 Oracle Extension Insider Release

---

CHANGELOG.md

changelog for 1.46.1

---

resources/xlf/en/sql.xlf

[Loc] removed noQueryRunnerForUri

---

package.json

Update distro commit to 37199be719d05d53f4eaa7d96018e579021fe3b0

Update distro commit to 37199be719d05d53f4eaa7d96018e579021fe3b0

---

resources/xlf/en/Microsoft.mssql.xlf
resources/xlf/en/Microsoft.sql-migration.xlf
resources/xlf/en/sql.xlf

[Loc] xlf update 10-11-2023

---

extensions/mssql/config.json

Incoming changes:
For PRs:
- #24550 
- #24653

Bump STS version to 4.10.0.17

---

extensions/mssql/src/constants.ts
extensions/mssql/src/main.ts
extensions/mssql/src/utils.ts

Addresses #24548 
Paired with https://github.com/microsoft/sqltoolsservice/pull/2256

Pass Http proxy URL and strict SSL flag to backend STS

---

extensionsGallery-insider.json

Need to update sql projects to bring the fix for https://github.com/microsoft/azuredatastudio/issues/24659 in insiders.
Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=213802&view=artifacts&pathAsName=false&type=publishedArtifacts

update sql projects to 1.4.0 in insiders

---

extensions/mssql/package.json
extensions/mssql/package.nls.json
extensions/mssql/src/objectManagement/commands.ts

Fix https://github.com/microsoft/azuredatastudio/issues/24571 and https://github.com/microsoft/azuredatastudio/issues/23737

Specify object type in context menu when creating a new object

---

resources/xlf/en/Microsoft.mssql.xlf
resources/xlf/en/sql.xlf

[Loc] update to xlfs for 10-12-2023

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/de/sql.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/sql.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/sql.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/sql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/sql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231013154213358 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231013154213358 to main

---

extensions/sql-database-projects/package.json

vbump after updating the extension in insiders yesterday.

vbump sql projects after insiders release

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/sql.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/sql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/sql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231014154038549 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231014154038549 to main

---

extensionsGallery-insider.json

DSCT 1.0.1 insider release

---

extensionsGallery-insider.json

Version Upgrade to 0.1.5 Insiders For Oracle Extension

Version Upgrade to 0.1.5 Insiders For Oracle Extension

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/de/sql.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/sql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231015153850591 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231015153850591 to main

---

extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/dialog/skuRecommendationResults/skuEditParametersDialog.ts
extensions/sql-migration/src/wizard/skuRecommendation/assessmentSummaryCard.ts
extensions/sql-migration/src/wizard/skuRecommendation/skuDataCollectionToolbar.ts
extensions/sql-migration/src/wizard/skuRecommendation/skuRecommendationPage.ts

Resolved bugs -
1) [start data collection and save and close the assessment . Button of stop data collection is disabled but it should not](https://dev.azure.com/msdata/Database%20Systems/_workitems/edit/2753870 )
2) [Tool tips are not having right description](https://dev.azure.com/msdata/Database%20Systems/_workitems/edit/2747982)
3) [Refresh dropdown icon missing](https://dev.azure.com/msdata/Database%20Systems/_workitems/edit/2753852)
Also, some other changes include updating the correct SKU recommendation notification and some other text values for Assessment summary and SKU recommendation page.

[New Migration Experience] [Resolved few bugs]

---

extensions/mssql/package.json

Follow up to #24660 
-------------------
_(Updated with feedback from @Charles-Gagnon )_

Fix command name for Group by Schema

---

build/azure-pipelines/win32/sql-product-build-win32.yml

Remove AGC step for adding pre-installed extensions, this will be done a different way using ADS-release.

Remove AGC step

---

build/package.json
build/yarn.lock
package.json
src/sql/workbench/contrib/query/browser/gridPanel.ts
yarn.lock

Support XML data formatting in varchar columns

---

extensionsGallery-insider.json

Insider release DSCT 1.0.2

---

extensionsGallery-insider.json
extensionsGallery.json

DMAO GA release with v4.2.3

---

extensionsGallery-insider.json
extensionsGallery.json

This PR release Database Migration Service Pack v1.1.4 in ADS stable build and updates version in ADS insiders build.

Releasing new extension - Database Migration Service Pack v1.1.4 in ADS stable build

---

resources/localization/LCL/de/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231018153840053 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231018153840053 to main

---

package.json

Update distro hash to d146f84ae415cdb64ed001d44e33729a1ca79b4c, updating the builtinExtensions for the AGC build.

Update distro hash to d146f84ae415cdb64ed001d44e33729a1ca79b4c

---

extensions/azurecore/package.json
extensions/azurecore/src/account-provider/auths/azureAuth.ts
extensions/azurecore/src/account-provider/utils/fileEncryptionHelper.ts
extensions/azurecore/src/account-provider/utils/msalCachePlugin.ts
extensions/azurecore/yarn.lock

Fixes #24604 
Upgrading to v2.2.0 and downgrading to v1.16.0 seems to fix the issue.
v1.18 contains bug that surfaced app. Will proceed to upgrading to 2.2.0 and watch over stability for next week.
Related issue in MSAL.js known issue: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6425#issuecomment-1769798054

Upgrade azure/msal to 2.2.0 and some minor changes

---

extensions/git/package.nls.json
resources/xlf/en/Microsoft.azurecore.xlf
resources/xlf/en/sql.xlf
resources/xlf/en/vscode.git.xlf

[Loc] fix to git command text and update to localized resources

---

extensionsGallery-insider.json

This PR updates the insiders extension gallery to the latest version 1.4.11 of the SQL Migration extension. sql-migration-1.4.11.vsix
Link to Drop of Azure Data Studio - Extensions Product pipeline run off main:
https://mssqltools.visualstudio.com/_apis/resources/Containers/6221441/drop?itemPath=drop%2Fextensions%2Fsql-migration-1.4.11.vsix

[SQL Migration] Release v1.4.11 to Insiders

---

extensionsGallery.json

Update the Stable ADS Build Oracle Extension Version to 0.1.5

Update ADS (Stable) Oracle Extension Version 0.1.5

---

.github/workflows/basic.yml
.github/workflows/ci.yml

Use sql-computeNodeModulesCacheKey

---

src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts

Close notifications on completion

---

extensions/mssql/src/objectManagement/ui/databaseDialog.ts

Increased the DSC table height by 5rows, so that the table occupies most of the dialog

Adjusting DSC table height

---

.github/respond-to-issue-based-on-label.yml

Addresses feedback from https://github.com/microsoft/azuredatastudio/issues/24369#issuecomment-1716076593

Link common authentication issues doc with github actions

---

extensions/mssql/src/main.ts

Accidently checked this in my previous PR

Remove test code

---

extensions/mssql/config.json

update STS to 4.10.21

---

resources/localization/LCL/de/sql.xlf.lcl
resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/it/sql.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/pt-BR/sql.xlf.lcl
resources/localization/LCL/zh-Hant/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231026155118974 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231026155118974 to main

---

extensions/mssql/src/objectManagement/commands.ts
extensions/mssql/src/objectManagement/ui/databaseDialog.ts
extensions/mssql/src/objectManagement/ui/serverPropertiesDialog.ts

Fix https://github.com/microsoft/azuredatastudio/issues/24625

Fix properties dialog width

---

resources/localization/LCL/ru/sql.xlf.lcl
resources/localization/LCL/zh-Hans/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231027154103091 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231027154103091 to main

---

src/vs/workbench/contrib/surveys/browser/nps.contribution.ts

Captured here: https://github.com/microsoft/vscode/pull/195952#discussion_r1374301677

Missed a bracket

---

extensionsGallery-insider.json

Release v1.2.0 for Data migration for Oracle extension

---

extensions/sql-migration/src/dialog/skuRecommendationResults/importPerformanceDataDialog.ts
extensions/sql-migration/src/wizard/skuRecommendation/skuDataCollectionToolbar.ts
extensions/sql-migration/src/wizard/skuRecommendation/skuRecommendationPage.ts

This includes some of the bug fixes -
1) Removed await for azure recommendation [Major Fix]
Previously, the dialog was open till the time azure recommendation is not ready. Instead now we do not await and instead show card Loading till recommendation is calculated. 
2) Added missing notifcation message on successful Import data collection and recommendation based on it.
3) During last bug fix, stopDataCollection got enabled by mistake. So disabled it at the beginning of toolbar creation.

[New Migration Experience] Bug fixes in Import Data Collection.

---

extensionsGallery.json

This PR updates the extension gallery to the latest version 1.4.11 of the SQL Migration extension. sql-migration-1.4.11.vsix
Insider Gallery PR: https://github.com/microsoft/azuredatastudio/pull/24747

[SQL Migration] Release v1.4.11 to Stable

---

resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/sql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231028154103160 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231028154103160 to main

---

package.json

version bumping to 1.48 after release branch split

---

extensions/sql-migration/src/api/azure.ts
extensions/sql-migration/src/api/sqlUtils.ts
extensions/sql-migration/src/api/utils.ts
extensions/sql-migration/src/constants/helper.ts
extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/dashboard/migrationDetailsTableTab.ts
extensions/sql-migration/src/dashboard/migrationsListTab.ts
extensions/sql-migration/src/dashboard/sqlServerDashboard.ts
extensions/sql-migration/src/dialog/tableMigrationSelection/schemaMigrationAssessmentDialog.ts
extensions/sql-migration/src/dialog/tableMigrationSelection/tableMigrationSelectionDialog.ts
extensions/sql-migration/src/models/stateMachine.ts
extensions/sql-migration/src/wizard/databaseBackupPage.ts
extensions/sql-migration/src/wizard/databaseSelectorPage.ts
extensions/sql-migration/src/wizard/targetSelectionPage.ts

**First time to table selection page, schema migration shows 'Not selected'.**
**If schema migration is enabled, assessment results will be checked. If any assessment issues that might fail schema migration are found, it will show the assessment results link to check the details.
If schema migration is not enabled, there are two cases. If there are missing tables on the target but users don't select 'migrate schema to target' option, it will show 'Not selected'. If there are no missing tables on target, it will show 'Not needed'.**
**There are three tabs after click 'Edit'：**
**The source tables exist on the target and have rows:**
**The source tables don't exist on the target and have rows:**
**The source tables dont have rows. These tables are not available to select for data migration. …

[SQL Migration] Add schema migration

---

product.json

Addresses https://github.com/microsoft/azuredatastudio/issues/24816. Updates the link to https://aka.ms/ads-license, which will be available later this afternoon.

update link for Help -> View License

---

extensions/sql-migration/src/dialog/tableMigrationSelection/schemaMigrationAssessmentDialog.ts
src/vs/platform/encryption/node/encryptionMainService.ts

Updating the license in the header of a couple more files that were added before https://github.com/microsoft/azuredatastudio/pull/24799 got merged. This should fix the canary build failures.

update the license in the header of a couple more files

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/de/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231031154116574 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231031154116574 to main

---

package.json

Addresses https://github.com/microsoft/azuredatastudio/issues/24817.

update distro - add License.rtf files

---

extensions/sql-migration/src/wizard/skuRecommendation/skuDataCollectionToolbar.ts

Default Path was decided later.
Since we decided to take the change in default path in extension setting later. Chaning the default path for new migration release.

Changing the default path for data collection

---

package.json

Fixes #24817. Cherry-picked from dc97749c779c750d455eebc5aaaa39154afb5e8a

[Port] update distro - add License.rtf files

---

product.json

Fixes https://github.com/microsoft/azuredatastudio/issues/24816. Cherry-picked fcbe47400453791c928d81d7da8e028d4f4ac976 from main

[Port] update link for Help -> View License (#24818)

---

src/vs/workbench/electron-sandbox/window.ts

(cherry picked from commit 943a1ad98e1bd8e3054df539d88cd3174c6b273a)
Fixes https://github.com/microsoft/azuredatastudio/issues/24840

[Port] Update MacOS ARM64 download links (#24842)

---

package.json
yarn.lock

Ports #24847 to release/1.47 branch

[Port] Fix http(s)-proxy-agent dependencies (#24847)

---

extensions/mssql/src/objectManagement/ui/applicationRoleDialog.ts
extensions/mssql/src/ui/dialogBase.ts

When creating a new role, we need to provide a name and password otherwise it will fail silently.

Require password and name when creating an App role 

---

extensions/mssql/config.json

Takes in this STS change: https://github.com/microsoft/sqltoolsservice/pull/2279 from @cheenamalhotra

Bump STS to version 4.11.0.2

---

extensions/mssql/config.json

https://github.com/microsoft/sqltoolsservice/compare/4.10.0.22...4.10.1.1

Bump STS for release branch

---

extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/dialog/skuRecommendationResults/importPerformanceDataDialog.ts
extensions/sql-migration/src/wizard/skuRecommendation/skuRecommendationPage.ts

Few bugs found during the test-
1) Next button was reenabled on successful assessment (A bug that next button not working on successful assessment).
2) Some Text fixes for importa performance data

[New Migration Experience] bug fixes

---

src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/24870. Cherry-picked 6bfa92936eef5e84593824aebc633472feaa611e from main

[Port]Fixing dashboard tab loading for non activable extensions (#24871)

---

extensions/mssql/config.json

Main branch STS VBump from 4.11.0.2 to 4.11.0.3

STS vBump to 4.11.0.3

---

extensions/mssql/config.json

STS Release branch (release/1.47) vBump from 4.10.1.1 to 4.10.1.2

STS VBump from 4.10.1.1 to 4.10.1.2

---

src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts

Fix https://github.com/microsoft/azuredatastudio/issues/24415

[Port] Fix markdown attach image 

---

extensions/mssql/package.json

For https://github.com/microsoft/azuredatastudio/issues/24869

Clean up basic admin commands

---

extensionsGallery.json

Updating sql projects in RC extensions gallery now that testing is finished.
Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=215440&view=artifacts&pathAsName=false&type=publishedArtifacts

update sql projects to 1.4.1 in RC gallery

---

extensionsGallery-insider.json

update sql projects to 1.4.1 in Insiders gallery. Same vsix as the one for RC in https://github.com/microsoft/azuredatastudio/pull/24884

update sql projects to 1.4.1 in Insiders Gallery

---

extensions/mssql/package.json

Fix https://github.com/microsoft/azuredatastudio/issues/24869

[Port] Clean up commands (#24879)

---

extensions/sql-migration/README.md

This is a minor PR to remove Preview tag from readme file against SKU recommendation.

[SQL Migration] Remove preview tag from readme again SKU recommendation

---

extensionsGallery-insider.json

This PR updates the insiders extension gallery insiders to the latest version 1.5.0 of the SQL Migration extension. sql-migration-1.5.0.vsix
Link to Azure Data Studio - Extensions Product pipeline run off main: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=215652&view=artifacts&pathAsName=false&type=publishedArtifacts
VSIX: https://mssqltools.visualstudio.com/_apis/resources/Containers/6336540/drop?itemPath=drop%2Fextensions%2Fsql-migration-1.5.0.vsix

[SQL Migration] Release v1.5.0 to Insiders

---

extensionsGallery.json

Langpack files are found here:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=215560&view=artifacts&pathAsName=false&type=publishedArtifacts

Vbump to November 2023 release langpacks for RC1 branch

---

extensions/mssql/config.json
extensions/mssql/src/objectManagement/ui/loginDialog.ts
extensions/mssql/src/objectManagement/ui/principalDialogBase.ts

Porting this change to release branch: https://github.com/microsoft/azuredatastudio/pull/24888
The new release STS build hasn't dropped yet, so leaving this as a draft till that's in.

Hide permissions if a login doesn't support it (#24888)

---

CHANGELOG.md

Updating changelog for 1.47

---

extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/dashboard/dashboardTab.ts
extensions/sql-migration/src/dashboard/migrationsListTab.ts
extensions/sql-migration/src/dashboard/tabBase.ts
extensions/sql-migration/src/dialog/help/helpAndSupportDialog.ts
extensions/sql-migration/src/dialog/help/helpSupport.ts

Bug Link - https://dev.azure.com/msdata/Database%20Systems/_workitems/edit/2774419
In order to have consistency cross the extensions, we are redesigning  the help and support tab similar to other migration extension.
New links added in the dialog -
Documentation  -  https://aka.ms/dms-overview
QnA - https://aka.ms/DMSqna
Support Request - https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportrequest (Same as before)
Dialog Box -

[SQL Migration] New Help and Support Dialog

---

resources/xlf/en/Microsoft.kusto.xlf
resources/xlf/en/Microsoft.mssql.xlf
resources/xlf/en/Microsoft.sql-migration.xlf

[Loc] update to XLFs for 11/8/2023

---

src/sql/workbench/contrib/query/browser/gridPanel.ts

Handle empty values to determine xml cells

---

extensions/mssql/config.json

https://github.com/microsoft/sqltoolsservice/compare/4.11.0.4...4.11.0.6

Bump STS to v4.11.0.6

---

resources/localization/LCL/de/Microsoft.kusto.xlf.lcl
resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/es/Microsoft.kusto.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/Microsoft.kusto.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.kusto.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.kusto.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.kusto.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.kusto.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/Microsoft.kusto.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231112164030531 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231112164030531 to main

---

resources/localization/LCL/zh-Hant/Microsoft.kusto.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231113164031752 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231113164031752 to main

---

extensions/mssql/src/objectManagement/ui/databaseDialog.ts

Fix https://github.com/microsoft/azuredatastudio/issues/23823

Require name when creating database

---

resources/xlf/en/Microsoft.mssql.xlf
resources/xlf/en/Microsoft.sql-migration.xlf

[Loc] Update to xlfs for 11/13/2023

---

extensionsGallery.json

This PR is to remove the Data migration extension for Oracle from ADS public marketplace.

Remove Data migration extension for Oracle from ADS Public marketplace.

---

extensionsGallery-insider.json
extensionsGallery.json

This PR is raised to release oracle extension pack version 1.1.5 in ADS stable. We are not doing these changes in insiders, thus insiders has still the previous version(1.1.4)

Release oracle extension pack version 1.1.5 in ADS stable.

---

resources/xlf/en/Microsoft.mssql.xlf
resources/xlf/en/Microsoft.sql-migration.xlf

[Loc] update to xlfs for 11-14-2023

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231116164200530 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231116164200530 to main

---

extensionsGallery-insider.json
extensionsGallery.json

This PR release latest version of oracle extension (0.1.6) on ADS insiders and stable.

Release Oracle Extension version 0.1.6 in ADS insiders and stable

---

extensionsGallery-insider.json
extensionsGallery.json

This PR release extension pack version 1.1.6 with preview tag removed.

Releasing extension pack 1.1.6

---

resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231117164204057 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231117164204057 to main

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231118164142151 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231118164142151 to main

---

resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231119164005230 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231119164005230 to main

---

src/sql/workbench/contrib/backup/browser/backup.component.ts

Enable backup url support for SQL Server 
Fix https://github.com/microsoft/azuredatastudio/issues/24589

Enable backup url support for SQL Server

---

resources/xlf/en/Microsoft.mssql.xlf
resources/xlf/en/Microsoft.sql-migration.xlf
resources/xlf/en/sql.xlf

[Loc] update to XLFS 11-20-2023

---

extensions/sql-migration/src/scripts/SHIR-auto-configuration.ps1

Description -> This script automatically configures SHIR on a Windows machine including downloading, installing Integration runtime, and configuring SHIR with DMS.
Testing -> It has been tested by the team on 4 different windows configurations 
1. Windows 10
2. Windows 11
3. Windows 19 server
4. Windows 22 server
Scenarios covered -
Snapshot -

[SQL Migration] Single Click SHIR

---

extensionsGallery-insider.json
extensionsGallery.json

Updated SQL 4 CDS extension to 8.0.0

Updated SQL 4 CDS extension to 8.0.0

---

resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/sql.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/sql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231123163935150 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231123163935150 to main

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/de/sql.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/sql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231124164131287 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231124164131287 to main

---

extensionsGallery-insider.json

vsix file: https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.5.1-insiders

[PostgreSQL] Release v0.5.1 to Insiders

---

extensions/mssql/config.json

vBump STS version to 4.11.0.12

---

resources/xlf/en/Microsoft.mssql.xlf
resources/xlf/en/Microsoft.sql-migration.xlf

[Loc] update to XLFs for 11/27/2023

---

resources/xlf/en/Microsoft.mssql.xlf

[Loc] Added restore database strings to MSSQL

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231130164026375 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231130164026375 to main

---

resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231201164056775 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231201164056775 to main

---

extensionsGallery-insider.json
extensionsGallery.json

vsix file: https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.6.0

[PostgreSQL] Release v0.6.0 official stable release

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231202163910126 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231202163910126 to main

---

resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231203163946252 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231203163946252 to main

---

extensions/mssql/config.json

STS vbump from 4.11.0.12 to 4.11.0.14

---

extensions/sql-migration/config.json
extensions/sql-migration/src/constants/strings.ts

Diff - https://github.com/microsoft/sqltoolsservice/compare/4.10.0.9...4.11.0.13
Changes for Migration - https://github.com/microsoft/sqltoolsservice/commit/ffe8bb651b662356ac2cd1d0b081b38c40293891

Bumping STS Version to v4.11.0.13

---

build/azure-pipelines/win32/sql-product-build-win32.yml

Addresses #24964 
[Build for verification](https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=217363&view=results)

Codesign unis000.exe with ESRP client

---

resources/xlf/en/Microsoft.mssql.xlf
resources/xlf/en/Microsoft.sql-migration.xlf

[Loc] XLF update 12-11-2023

---

package.json
yarn.lock

The PR bumps the package version of vscode/test-web to 0.0.42.

Update test-web to version 0.0.42

---

extensions/sql-migration/src/dashboard/sqlServerDashboard.ts
extensions/sql-migration/src/dashboard/tabBase.ts
extensions/sql-migration/src/dialog/assessment/importAssessmentDialog.ts
extensions/sql-migration/src/telemetry.ts

This PR adds the telemetry view for import assessment to analyse the usage of this feature.

Add telemetry view for import assessment

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231213163957107 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231213163957107 to main

---

resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231214163910130 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231214163910130 to main

---

resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231215164023190 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20231215164023190 to main

---

resources/xlf/en/Microsoft.sql-migration.xlf
resources/xlf/en/sql.xlf

[Loc] update to sql migration and sql xlf for 12-18-2023

---

resources/xlf/en/Microsoft.azurecore.xlf

[Loc] added Azure CosmosDB for NoSQL entry

---

package.json

Update version to 1.47.1 for hotfix

---

extensionsGallery-insider.json

Version Change Insiders for DSCT Extension to V1.1.0

V1.1.0 DSCT ADS Extension

---

src/sql/workbench/contrib/query/browser/gridPanel.ts

Fixes #24929 
Ports #24933 to release/1.47 branch.

[Release/1.47] Handle empty values to determine XML cells (#24933)

---

.github/workflows/basic.yml
.github/workflows/ci.yml
build/azure-pipelines/darwin/sql-product-build-darwin-signing.yml
build/azure-pipelines/darwin/sql-product-build-darwin.yml
build/azure-pipelines/linux/sql-product-build-linux.yml
build/azure-pipelines/web/sql-product-build-web.yml
build/azure-pipelines/win32/sql-product-build-win32.yml
package.json

Porting pipeline fixes from main to the 1.41 branch for the pipeline to run successfully. Also bumping the patch version to 1.41.3
Successful ad hoc pipeline run: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=219044&view=results

[Port] Porting pipeline fixes

---

resources/xlf/en/sql.xlf

[Loc] added github copilot sign out

---

extensionsGallery.json

Version Change for DSCT Extension to V1.1.0

Version Change v1.1.0 DSCT Extn

---

src/sql/workbench/common/editor/query/queryEditorInput.ts

added SPID to queryEditorInput title

---

extensions/mssql/config.json

update STS to 4.10.2.1

---

extensions/mssql/config.json

update STS to 4.11.0.17

---

extensionsGallery-insider.json

Please find the binary [here](https://msdata.visualstudio.com/_apis/resources/Containers/231341758/drop?itemPath=drop%2Fazure-cosmosdb-ads-extension-0.4.1.vsix);

Upgrade cosmosdb to 0.4.1 in Insider only

---

extensions/datavirtualization/config.json
extensions/datavirtualization/package.json
extensions/import/config.json
extensions/import/package.json

Updating the scale out data service and flat file import service to bring in an MDS version update. I verified that the new service versions download, but would be great to get help doing a basic functionality test to make sure nothing broke with the new versions.
Scale out data service:
Flat file import service:

Update import and data virtualization services

---

CHANGELOG.md

…as the last branch with BDC support seems wise to keep it up to date

getting all the changelog history popped over into 1.41 branch

---

CHANGELOG.md

CHangelog updates for our latest releases

---

resources/localization/LCL/de/Microsoft.azurecore.xlf.lcl
resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/de/sql.xlf.lcl
resources/localization/LCL/es/Microsoft.azurecore.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.azurecore.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/sql.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.azurecore.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/sql.xlf.lcl
resources/localization/LCL/ru/Microsoft.azurecore.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/sql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.azurecore.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240110164126212 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240110164126212 to main

---

resources/localization/LCL/fr/Microsoft.azurecore.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/ja/Microsoft.azurecore.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl
resources/localization/LCL/ko/Microsoft.azurecore.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.azurecore.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240111165412896 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240111165412896 to main

---

extensions/sql-migration/package.json

SQL Migration Extension Version bump up

---

extensionsGallery-insider.json
extensionsGallery.json

Also changing resource links to a specific tag so changes in master don't break our stuff
@andyleejordan FYI

Update Powershell to 2024.0.0

---

resources/xlf/en/Microsoft.sql-migration.xlf

[Loc] update to sql-migration for 1-17-2024

---

extensions/kusto/config.json
extensions/kusto/package.json

Updating to bring in this change for the kusto service to update the System.Data.SqlClient version used to 4.8.6: https://github.com/microsoft/sqltoolsservice/pull/2320

update kusto service to version with SDS 4.8.6

---

src/vs/code/electron-sandbox/issue/issueReporterPage.ts

Addresses: https://github.com/microsoft/azuredatastudio/issues/24218. This adds aria labels to the combo boxes in the issue reporter.

add aria lablels for issue reporter

---

resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240122235524101 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240122235524101 to main

---

extensions/mssql/src/objectManagement/ui/serverPropertiesDialog.ts

For https://github.com/microsoft/azuredatastudio/issues/25159

Add required flag to input container

---

extensionsGallery-insider.json

Please find the binary [here](https://msdata.visualstudio.com/_apis/resources/Containers/233809563/drop?itemPath=drop%2Fazure-cosmosdb-ads-extension-0.4.2.vsix).

 Upgrade Cosmos DB extension to 0.4.2 in Insider gallery only

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/sql.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/sql.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/sql.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/sql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240125164135374 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240125164135374 to main

---

extensions/sql-migration/package.json

SQL Migration Extension Version bump up to 1.5.3 with hotfix

SQL Migration Extension Version bump up to 1.5.3 with hotfix

---

resources/localization/LCL/de/sql.xlf.lcl
resources/localization/LCL/ja/sql.xlf.lcl
resources/localization/LCL/pt-BR/sql.xlf.lcl
resources/localization/LCL/ru/sql.xlf.lcl
resources/localization/LCL/zh-Hans/sql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240126164127038 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240126164127038 to main

---

extensionsGallery-insider.json
extensionsGallery.json

This PR update the gallery with an extension to formatting brazilian documents (CPJ/CNPJ), from selected texts in queries editor.

Adding extension cpf / cnpj to Gallery

---

resources/xlf/en/Microsoft.mssql.xlf

[Loc] added restore database new string for 2-1-2024

---

resources/xlf/en/Microsoft.mssql.xlf

[Loc] added s6 strings for localization

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240207164051250 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240207164051250 to main

---

resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240208164046326 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240208164046326 to main

---

resources/xlf/en/Microsoft.cms.xlf
resources/xlf/en/Microsoft.mssql.xlf

[Loc] added updated strings for 2-14-2024

---

src/sql/workbench/services/accountManagement/browser/accountManagementService.ts
src/sql/workbench/services/connection/browser/connectionManagementService.ts

Fixes #24899 ([comment](https://github.com/microsoft/azuredatastudio/issues/24899#issuecomment-1908705696))

Fix email comparisons to be case insensitive

---

resources/xlf/en/Microsoft.notebook.xlf

[Loc] added update to notebook xlf

---

resources/localization/LCL/de/Microsoft.cms.xlf.lcl
resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.cms.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.cms.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.cms.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.cms.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.cms.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.cms.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.cms.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.cms.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.cms.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240216202403811 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240216202403811 to main

---

.github/workflows/on-label.yml

Provide issue:write permission to label actions.

Fix GitHub workflow - label triggers

---

extensions/mssql/config.json

Updating STS version from 4.11.0.19 to 4.11.0.22

---

package.json

version bumping to 1.49 post release branch split

---

extensions/mssql/config.json

Porting STS version update to release branch 1.48

---

package.json

Follow up to https://github.com/microsoft/azuredatastudio/issues/25371. Not planning to port to release branch since this isn't a functional change - and going forward this will ensure it isn't an issue for future testing.

Enable telemetry by default in RC1 builds

---

extensions/mssql/src/objectManagement/ui/databaseDialog.ts
extensions/mssql/src/ui/dialogBase.ts

Addresses
https://github.com/microsoft/azuredatastudio/issues/25209
https://github.com/microsoft/azuredatastudio/issues/25210
https://github.com/microsoft/azuredatastudio/issues/25130
Styling is not finalized, but it uses whatever is known of other declarative tables.

Added converted rows filegroup declarative table (merge first)

---

resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240222164422260 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240222164422260 to main

---

extensions/sql-database-projects/package.json

Sql project extension version is updating to 1.4.2, which is required for the release as we have updated the scriptDom version recently here: https://github.com/microsoft/azuredatastudio/commit/f599ca63dcf9e35f4e61e08a5dd4dcf3e99c7c4a

Updating sql project extension verison

---

extensions/sql-database-projects/package.json

This PR vbumps the sql-database-projects extension version number

Porting sql-database-project extension version to 1.4.2

---

src/sql/workbench/services/connection/browser/connectionWidget.ts

Ports #25380 to release/1.48
Addresses https://github.com/microsoft/azuredatastudio/issues/25378

[Port] Fix custom options selection event (#25380)

---

extensions/notebook/src/book/bookTocManager.ts
extensions/notebook/src/book/githubRemoteBook.ts
extensions/notebook/src/extension.ts

Closes https://github.com/microsoft/azuredatastudio/issues/25369

Fix arguments for openNotebookFolder command registration (#25374)

---

resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240223164022478 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240223164022478 to main

---

extensions/mssql/package.json

Cherry-picking 9c4f37f1f335528bb9e4033ad24c783d5e2db083 from main to fix https://github.com/microsoft/azuredatastudio/issues/25366

[Port] Remove inline commands for dropping objects (#25399)

---

extensionsGallery-insider.json
extensionsGallery.json

Replacement PR for  #25401.
Add new ADS Column Chooser extension to the gallery.   Addresses #23489

Release/extensions ADS Column Chooser

---

extensionsGallery-insider.json
extensionsGallery.json

Companion PR to https://github.com/microsoft/azuredatastudio/pull/25415

Langpack Bump for RC1 gallery (February 2024 release)

---

extensionsGallery-insider.json

Companion PR to https://github.com/microsoft/azuredatastudio/pull/25413
Langpacks found here: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=222166&view=artifacts&pathAsName=false&type=publishedArtifacts

Update to insiders gallery langpacks for release branch (Feburary 2024 release)

---

extensionsGallery-insider.json
extensionsGallery.json

The binary has already been uploaded when we pointed the insider gallery to 0.4.2 in #25257 .

Update Cosmos DB ADS extension version in main gallery to 0.4.2

---

resources/xlf/en/Microsoft.sql-migration.xlf

[Loc] update to sql migration XLF for 2-27-2024

---

extensions/sql-migration/package.json

version bump for sql-migration ADS extension

version bump for sql-migration extension

---

CHANGELOG.md

Update changelog for 1.48

---

extensions/import/config.json
extensions/import/package.json

Updating the import service to remove outdated, unnecessary SDS version that was being included. I verified on windows and mac that the new version downloads and successfully imports data from a csv file.

update import service

---

extensionsGallery-insider.json
extensionsGallery.json

Build with vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=222472&view=results
Updating this to pick up an updated version of the import service that removes an outdated SDS version depdendency.

update import extension to version 1.6.1

---

extensions/sql-migration/src/wizard/databaseBackupPage.ts

Bug Fix - Removed checks for mandatory fields for SQL db Target since these fields are not need for SQL DB Target

[Quick Fix] Removed validation button errors for Sql Db target

---

resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240301165507358 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240301165507358 to main

---

resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240304062103170 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240304062103170 to main

---

src/sql/workbench/services/accountManagement/browser/accountManagementService.ts
src/sql/workbench/services/connection/browser/connectionManagementService.ts

Addresses https://github.com/microsoft/azuredatastudio/issues/25454

Add null checks to email/account id

---

resources/localization/LCL/de/Microsoft.mssql.xlf.lcl
resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/es/Microsoft.mssql.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.mssql.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.mssql.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/Microsoft.mssql.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240309021313868 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240309021313868 to main

---

resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240310154709674 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240310154709674 to main

---

resources/localization/LCL/fr/Microsoft.cms.xlf.lcl
resources/localization/LCL/fr/Microsoft.mssql.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.cms.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.mssql.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240315201548060 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240315201548060 to main

---

resources/xlf/en/Microsoft.sql-migration.xlf

[Loc] added updated XLF strings for Sql-Migration

---

extensionsGallery-insider.json
extensionsGallery.json

Updated "ExtraSqlScriptAs" extension to 0.6.0

Updated "ExtraSqlScriptAs" extension to 0.6.0

---

extensionsGallery-insider.json
extensionsGallery.json

VSIX Url: https://artprodscussu1.artifacts.visualstudio.com/A011b8bdf-6d56-4f87-be0d-0092136884d9/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RldmRpdi9wcm9qZWN0SWQvMGJkYmM1OTAtYTA2Mi00YzNmLWIwZjYtOTM4M2Y2Nzg2NWVlL2J1aWxkSWQvOTI4MzU4OS9hcnRpZmFjdE5hbWUvdnNpeA2/content?format=file&subPath=%2Fvscodeintellicode-1.3.0.vsix

Update IntelliCode for ADS extension

---

resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240322154215761 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240322154215761 to main

---

extensions/sql-migration/config.json
extensions/sql-migration/package.json
extensions/sql-migration/src/api/utils.ts
extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/dialog/skuRecommendationResults/skuRecommendationResultsDialog.ts
extensions/sql-migration/src/service/contracts.ts
extensions/sql-migration/src/service/features.ts

This PR integrates the changes to display Next-Gen General purpose for MI recommendations on UI.

Next-Gen General Purpose For MI integration

---

resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240327154101383 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240327154101383 to main

---

resources/xlf/en/Microsoft.sql-migration.xlf

[Loc] added next-gen general purpose string

---

resources/localization/LCL/es/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/fr/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240330154621523 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240330154621523 to main

---

resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240331154031488 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240331154031488 to main

---

extensions/sql-migration/src/dialog/skuRecommendationResults/skuEditParametersDialog.ts
extensions/sql-migration/src/models/stateMachine.ts
extensions/sql-migration/src/service/features.ts

This PR makes NextGen GP recommendations to be produced based on toggle preview button.

Attaching Preview option with Next gen GP enabled

---

resources/localization/LCL/de/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240402153738408 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240402153738408 to main

---

resources/xlf/en/Microsoft.notebook.xlf

[Loc] added changes to notebook for 4-10-2024

---

resources/xlf/en/Microsoft.sql-migration.xlf

[Loc] more changes to sql migration for 4-12-2024

---

resources/localization/LCL/de/Microsoft.notebook.xlf.lcl
resources/localization/LCL/es/Microsoft.notebook.xlf.lcl
resources/localization/LCL/fr/Microsoft.notebook.xlf.lcl
resources/localization/LCL/it/Microsoft.notebook.xlf.lcl
resources/localization/LCL/it/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ja/Microsoft.notebook.xlf.lcl
resources/localization/LCL/ja/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ko/Microsoft.notebook.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.notebook.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/ru/Microsoft.notebook.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.notebook.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.sql-migration.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.notebook.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.sql-migration.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240414153807110 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240414153807110 to main

---

resources/xlf/en/Microsoft.notebook.xlf

[Loc] added changes to notebook for 4-17-2024

---

resources/localization/LCL/de/Microsoft.notebook.xlf.lcl
resources/localization/LCL/es/Microsoft.notebook.xlf.lcl
resources/localization/LCL/it/Microsoft.notebook.xlf.lcl
resources/localization/LCL/ja/Microsoft.notebook.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240419154143946 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240419154143946 to main

---

extensionsGallery-insider.json
extensionsGallery.json

see https://github.com/microsoft/azuredatastudio/pull/25565

Release/extensions update proc convert 2 sql 1.0.3 

---

resources/localization/LCL/fr/Microsoft.notebook.xlf.lcl
resources/localization/LCL/ko/Microsoft.notebook.xlf.lcl
resources/localization/LCL/pt-BR/Microsoft.notebook.xlf.lcl
resources/localization/LCL/ru/Microsoft.notebook.xlf.lcl
resources/localization/LCL/zh-Hans/Microsoft.notebook.xlf.lcl
resources/localization/LCL/zh-Hant/Microsoft.notebook.xlf.lcl

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240427160904695 to main with localized lcls

LEGO: Pull request from lego/hb_04604851-bac4-4681-9f74-73de611d6e48_20240427160904695 to main

---

extensionsGallery-insider.json
extensionsGallery.json

Updated "ExtraSqlScriptAs" extension to 0.6.1

Updated "ExtraSqlScriptAs" extension to 0.6.1

---

extensionsGallery-insider.json
extensionsGallery.json

Updated "ExtraSqlScriptAs" extension to 0.6.2

Updated "ExtraSqlScriptAs" extension to 0.6.2

---

build/gulpfile.vscode.win32.js

Adding gulp task that adds ads metadata to exe file. 

---

extensionsGallery-insider.json
extensionsGallery.json

Update ExtraSqlScriptAs version

Update ExtraSqlScriptAs version

---

package.json

Bump version to 1.48.1 for hotfix

---

src/vs/platform/update/electron-main/updateService.darwin.ts

PR to `main`: https://github.com/microsoft/azuredatastudio/pull/25694

[Port] Fix Mac update loop (#25694)

---

extensionsGallery-insider.json
extensionsGallery.json

Updated ExtraSqlScriptAs version to 0.7.0: added support to MySQL provider thanks to @olegrumiancev

Updated ExtraSqlScriptAs version

---

extensionsGallery-insider.json
extensionsGallery.json

[Mongo migration 2.2.0](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTMwMDU5OTQxL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-2.2.0.vsix)

Release new version of mongo migration extension (2.2.0)

---

extensionsGallery-insider.json
extensionsGallery.json

[Mongo migration 3.0.0](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTMxNjgyNTM2L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-3.0.0.vsix)

Release new version of mongo migration extension (3.0.0)

---

extensions/kusto/config.json
extensions/mssql/config.json

Bump STS version to pick up DacFx and MS.Azure.Kusto.Data updates.

Bump STS version to pick up DacFx and MS.Azure.Kusto.Data

---

scripts/validateGalleries.js

Site appears to be down so skipping to unblock check for other extensions

Skip pieces extension in validate galleries check

---

package.json

vBumping post release branch split

---

extensions/mssql/config.json

Pick up fix for the "Enable SET NOEXEC" option (https://github.com/microsoft/sqltoolsservice/pull/2380)

Update STS to 5.0.20240718.1

---

extensionsGallery-insider.json
extensionsGallery.json

Please find the binary [here](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTM0MDgyMzU2L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2Fazure-cosmosdb-ads-extension-0.4.5.vsix).

Upgrade cosmosdb to 0.4.5

---

extensions/import/yarn.lock
extensions/kusto/config.json
extensions/mssql/config.json
package.json

This PR merges all recent changes from main to release branch, which is basically just the STS bumps to pickup fixes made in that component.

Port STS and dependency bumps to release/1.49

---

src/sql/workbench/api/common/extHostModelView.ts

Fixed issue described in this bug: https://github.com/microsoft/azuredatastudio/issues/25443

Fixed column header screen reader bug

---

src/sql/workbench/api/common/extHostModelView.ts

This reverts commit ae652f71af911ab13826a648c4929fd2c8df57ef.

Revert "fixed column header screen reader bug (#25768)"

---

extensions/kusto/config.json
extensions/mssql/config.json

Update STS to 5.0.20240724.1

---

extensions/sql-database-projects/package.json

Updating SQL Projects extension version to 1.4.3

SQL Project version bump

---

src/sql/workbench/api/common/extHostModelView.ts
src/sql/workbench/browser/modelComponents/formContainer.component.ts
src/sql/workbench/browser/modelComponents/text.component.ts

Fix these two bugs: 
https://github.com/microsoft/azuredatastudio/issues/25445
https://github.com/microsoft/azuredatastudio/issues/25444

Fixed text focus/ page item focus issue on forms and wizards

---

extensions/sql-database-projects/package.json

Porting SQL Projects version bump to Release/1.49

Porting - SqlProj extension vbump

---

extensions/sql-database-projects/README.md
extensions/sql-database-projects/resources/templates/newSdkSqlProjectTemplate.xml
extensions/sql-database-projects/src/common/constants.ts
extensions/sql-database-projects/src/common/utils.ts
extensions/sql-database-projects/src/sqldbproj.d.ts
extensions/sql-database-projects/src/tools/buildHelper.ts
extensions/types/vscode-mssql.d.ts
src/sql/azdata.d.ts
src/sql/workbench/api/common/sqlExtHostTypes.ts

Porting 'Fabric SQL Mirrored support to SQL Projects' changes to release/1.49

Porting - Adding Fabric SQL Mirrored support to SQL Projects

---

cli/Cargo.lock
extensions/arc/yarn.lock
extensions/azcli/yarn.lock
extensions/azurecore/yarn.lock
extensions/cms/yarn.lock
extensions/dacpac/yarn.lock
extensions/data-workspace/yarn.lock
extensions/datavirtualization/yarn.lock
extensions/kusto/config.json
extensions/mssql/config.json
package.json
src/sql/workbench/api/common/extHostModelView.ts
src/sql/workbench/browser/modelComponents/formContainer.component.ts
src/sql/workbench/browser/modelComponents/text.component.ts

Port dependency bumps and accessibility fixes to rel/1.49 branch

---

extensionsGallery.json

Updating sql-database-projects verison and lastUpdated date from 1.4.2 to 1.4.3

Updating sql-database-projects verison and lastUpdated date

---

resources/xlf/en/sql.xlf

[Loc] updated XLFs for exthostModelView

---

build/gulpfile.vscode.win32.js

Use correct version (#25821)

---

src/vs/platform/extensionManagement/common/extensionGalleryService.ts
src/vs/platform/extensionManagement/common/extensionManagementUtil.ts

Fix bugs blocking extension upgrade (#25825)

---

package.json

Bump version to 1.49.1

---

extensionsGallery-insider.json
extensionsGallery.json

[Mongo migration 3.1.2](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTM3MDk5ODY4L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-3.1.2.vsix)

Users/skrishnan/version 3.1.2

---

.github/workflows/codeql.yml

The previous pipeline was not working and giving some warnings. I have recreated this workflow for Code QL.

Create Code QL workflow.

---

extensionsGallery-insider.json
extensionsGallery.json

Fix PowerShell metadata to fix update bug.  I am going to run through a little more validation prior to merging.

Fix PowerShell metadata to fix update bug

---

.github/workflows/ci.yml

Switch to intel based mac image

---

extensions/notebook/kernels/powershell/kernel.json

fix for https://github.com/microsoft/azuredatastudio/issues/25833

pwsh support for powershell kernel - fix for 25833

---

README.md

Given that #25718 notes that insider builds will no longer be available, this commit updates README.md to reflect this.

Remove broken links to insider builds from readme

---

extensionsGallery-insider.json
extensionsGallery.json

* Added support for **MySQL** databases. 
* Added support for **PostgresSQL** databases.  
* Ordering distinct values by Count or by Value does a reorder in place without reloading data from the database.
* Removed loader spinner thanks to the new mechanism of query execution tracking.
* Minor fixes

Update extension SqlDataInspector to version 0.8.0

---

extensions/git/src/main.ts

This PR will fix https://github.com/microsoft/azuredatastudio/issues/25584

Fix post commit command issue after successfully making a commit

---

extensionsGallery-insider.json
extensionsGallery.json

Updates in extensionsGallery.json and extensionsGallery-insider.json for version 3.1.3
Link to new new extension VSIX - [Mongo Migration 3.1.3](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTM5MzE3OTI2L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2FProduct%2FAdsMongoMigration%2Fbin%2Fads-extension-mongo-migration-3.1.3.vsix)

Version 3.1.3

---

extensionsGallery.json

Updates extensionsGallery.json for new Deployer third party extension version.

Updates Deployer extension version

---

extensionsGallery-insider.json
extensionsGallery.json

Please find the binary [here](https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/ba574a88-a171-48e0-8fcb-5fef6d23739c/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTQyMDY0ODEyL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41/content?format=file&subPath=%2Fazure-cosmosdb-ads-extension-0.4.6.vsix).

Upgrade Cosmos DB extension to 0.4.6

---

extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/models/stateMachine.ts
extensions/sql-migration/src/wizard/loginMigrationTargetSelectionPage.ts

This PR is for communicating clearly to customers the prerequisites for login migration on 1st page of login migration wizard

Add Login migration prerequisites in Target selection page

---

extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/dialog/loginMigration/loginPreMigrationValidationDialog.ts

For each validation correcting the implementation to add all exceptions.

Adding all errors for each validations

---

extensionsGallery-insider.json
extensionsGallery.json

It is used to solve the problem that the remote test stored procedure is difficult to debug and the test code must modify the stored procedure
If you want to use the conversion function on any software, you can download the software from the cloud storage. The software in the cloud storage also supports version management, one click download of data sources, local search tables, stored procedures, and supports converting t-SQL to SQL strings
https://drive.google.com/drive/folders/1_CB8gOL83MpJiyxfugClP6rHi7O_nyod?usp=sharing
new version upgrade https://t.me/qssq666

Release/extension Store Procdure To SQL 1.0.5  

---

extensions/sql-migration/src/api/utils.ts
extensions/sql-migration/src/constants/strings.ts

This PR displays Iops value on UI for Next Gen GP scenerio.

iops added

---

extensionsGallery-insider.json
extensionsGallery.json

This is link for vsix of new extension [vsix](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa%2Fba574a88-a171-48e0-8fcb-5fef6d23739c%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYmE1NzRhODgtYTE3MS00OGUwLThmY2ItNWZlZjZkMjM3MzljL2J1aWxkSWQvMTQ0NDkzMzExL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX21haW41%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FProduct%252FAdsMongoMigration%252Fbin%252Fads-extension-mongo-migration-3.1.4.vsix&data=05%7C02%7CBharath.Palaksha%40microsoft.com%7Ca3eee02b893b4e5de43e08dcec22ab83%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638644880854862860%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=qCn …

Release new version of mongo migration extension (3.1.4)

---

extensionsGallery-insider.json
extensionsGallery.json

* Now is possible to adjust the height of the Rows area using drag and drop.

Update extension SqlDataInspector to version 0.8.1

---

extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/wizard/loginMigrationTargetSelectionPage.ts

Modified Strings in 2 cases below - 
1. Login migration Prerequisite strings
2. Corrected the error string to show when the cx clicks next without filling required details on target selection page

Modified strings in Login Migration

---

extensions/sql-database-projects/package.json

Update sql-database-projects extension version to 1.4.4

---

build/azure-pipelines/darwin/sql-product-build-darwin.yml
build/azure-pipelines/sql-product-compile.yml

The Node.JS 20 bump is using more memory.  I'll work through the various PR validations with this one to get this heap size option step where needed.

Add additional node heap memory to Compile step in PR pipeline

---

extensionsGallery-insider.json
extensionsGallery.json

Update Copilot to latest stable build 1.242.0

Update Copilot to latest build 1.242.0

---

extensions/sql-migration/src/api/utils.ts
extensions/sql-migration/src/dialog/configureIR/configureIRDialog.ts
extensions/sql-migration/src/service/features.ts

Changes: Content of configure  shir dialog was not visible earlier which is now fixed and visible.

[Bug fix] Configure shir dialog was blank

---

package.json
yarn.lock

Bump @vscode/test-web version to 0.0.62

---

extensionsGallery-insider.json

Pipeline run: https://msdata.visualstudio.com/SQLToolsAndLibraries/_build/results?buildId=147244822&view=results
VSIX URL: https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/c6789c20-b819-4bfd-9917-11471655156e/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYzY3ODljMjAtYjgxOS00YmZkLTk5MTctMTE0NzE2NTUxNTZlL2J1aWxkSWQvMTQ3MjQ0ODIyL2FydGlmYWN0TmFtZS9kcm9wX1dpbmRvd3NfRXh0ZW5zaW9ucw2/content?format=file&subPath=%2Fextensions%2Fsql-migration-1.5.6.vsix

SQL migration extension (1.5.6) release in ADS insiders

---

extensionsGallery.json

Insiders release: https://github.com/microsoft/azuredatastudio/pull/26015
Pipeline run: https://msdata.visualstudio.com/SQLToolsAndLibraries/_build/results?buildId=147244822&view=results
VSIX URL: https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/c6789c20-b819-4bfd-9917-11471655156e/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYzY3ODljMjAtYjgxOS00YmZkLTk5MTctMTE0NzE2NTUxNTZlL2J1aWxkSWQvMTQ3MjQ0ODIyL2FydGlmYWN0TmFtZS9kcm9wX1dpbmRvd3NfRXh0ZW5zaW9ucw2/content?format=file&subPath=%2Fextensions%2Fsql-migration-1.5.6.vsix

SQL migration extension (1.5.6) release in ADS stable

---

package.json

vbump to 1.51 post release branch split

---

extensions/mssql/config.json

Pick up latest STS w/ DacFX bump

Pick up latest STS w/ DacFX bump

---

extensions/mssql/config.json

Pick up latest STS w/ DacFX bump (#26056)

Pick up latest STS w/ DacFX bump (#26056)

---

extensions/mssql/config.json

Bump STS to 5.0.20241115.1

---

extensions/mssql/config.json

Bump STS to 5.0.20241115.1 (#26066)

---

extensions/sql-migration/package.json

Update sql migration extension version to 1.5.7

Update version for sql migration extension

---

extensionsGallery-insider.json

Pipeline run: https://msdata.visualstudio.com/SQLToolsAndLibraries/_build/results?buildId=151031695&view=results
VSIX URL: https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/c6789c20-b819-4bfd-9917-11471655156e/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYzY3ODljMjAtYjgxOS00YmZkLTk5MTctMTE0NzE2NTUxNTZlL2J1aWxkSWQvMTUxMDMxNjk1L2FydGlmYWN0TmFtZS9kcm9wX1dpbmRvd3NfRXh0ZW5zaW9ucw2/content?format=file&subPath=%2Fextensions%2Fsql-migration-1.5.7.vsix

SQL migration extension (1.5.7) release in ADS insiders

---

extensions/sql-database-projects/README.md
extensions/sql-database-projects/resources/templates/newSdkSqlProjectTemplate.xml
extensions/sql-database-projects/src/tools/buildHelper.ts

Updating default Microsoft.Build.Sql version to 0.2.5-preview for creating new projects

Update default SDK version to 0.2.5-preview

---

extensions/sql-database-projects/package.json

Update sql-database-projects extension to 1.4.5

Update sql-database-projects extension to 1.4.5

---

extensionsGallery.json

Pipeline run: https://msdata.visualstudio.com/SQLToolsAndLibraries/_build/results?buildId=152767690&view=results
VSIX artifact: https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/c6789c20-b819-4bfd-9917-11471655156e/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYzY3ODljMjAtYjgxOS00YmZkLTk5MTctMTE0NzE2NTUxNTZlL2J1aWxkSWQvMTUyNzY3NjkwL2FydGlmYWN0TmFtZS9kcm9wX1dpbmRvd3NfRXh0ZW5zaW9ucw2/content?format=file&subPath=%2Fextensions%2Fsql-database-projects-1.4.5.vsix

SQL Database Projects Extension 1.4.5 Release

---

extensionsGallery.json

Insiders release: https://github.com/microsoft/azuredatastudio/pull/26082
Pipeline run: https://msdata.visualstudio.com/SQLToolsAndLibraries/_build/results?buildId=151031695&view=results
VSIX URL: https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/c6789c20-b819-4bfd-9917-11471655156e/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYzY3ODljMjAtYjgxOS00YmZkLTk5MTctMTE0NzE2NTUxNTZlL2J1aWxkSWQvMTUxMDMxNjk1L2FydGlmYWN0TmFtZS9kcm9wX1dpbmRvd3NfRXh0ZW5zaW9ucw2/content?format=file&subPath=%2Fextensions%2Fsql-migration-1.5.7.vsix

SQL migration extension (1.5.7) release in ADS stable 

---

extensionsGallery-insider.json
extensionsGallery.json

Based on last discussion with Charles, created single PR to assist with removing DSCT & DMAO extension from both insiders and public gallery.
Reference issues:
https://github.com/microsoft/azuredatastudio/issues/26110
https://github.com/microsoft/azuredatastudio/issues/26111

Removal of extensions DSCT & DMAO

---

extensions/data-workspace/images/data-workspace.svg

Updating the Icon as per the request: #25788 
Before: 
After:

Updating SQL database Projects activity bar icon that matches with the projects icon

---

extensions/notebook/resources/pythonScripts/startNotebook.py
extensions/notebook/src/jupyter/jupyterServerManager.ts
extensions/notebook/src/jupyter/requiredJupyterPackages.ts
extensions/notebook/src/jupyter/serverInstance.ts

Update Python notebook dependencies to a new version.  And fix related build and runtime errors that occurred from the upgrade.

Update Python notebook dependencies

---

.github/workflows/basic.yml
.github/workflows/ci.yml
extensions/notebook/src/test/model/executeManager.test.ts
extensions/notebook/src/test/model/serverManager.test.ts
package.json
scripts/test-extensions-unit.sh
yarn.lock

This PR fixes the previously broken GitHub CI checks that are setup for Azure Data Studio.
Before:
After:

Fix broken GitHub CI checks

---

extensions/mssql/config.json

STS bump to 5.0.20250115.1 to match vscode-mssql

---

extensions/mssql/config.json

(cherry picked from commit c4ee10c733bbabb99ca275d78a321bc2f25cb32b)

STS bump to 5.0.20250115.1 to match vscode-mssql (#26155)

---

package.json

vbump ADS main post release branch split

---

CHANGELOG.md

Catching up the changelog since it was behind

---

extensionsGallery.json

This PR fixes https://github.com/microsoft/azuredatastudio/issues/26181

Remove palenight theme extension because it was removed at it's source

---

extensionsGallery.json

TabPainter for Azure Data Studio is an extension that colors your editor interface based on the active database connection, providing customizable color schemes and visual safeguards to help prevent running queries on unintended servers.

Add TabPainter to extensionsGallery.json

---

CHANGELOG.md

updated readme to reflect retirement hotfix

---

extensions/data-workspace/package.json

Looks like we missed bumping this after the last release

Bumping data workspace extension version

---

extensions/data-workspace/package.json

Bumping data-workspace version number since that was missed last time and we need to release a new version

Port bumping data workspace extension version (#26207)

---

extensions/sql-database-projects/package.json

Updating SQL Project extension version

---

extensions/azurecore/src/account-provider/auths/azureAuth.ts
extensions/azurecore/src/account-provider/azureAccountProvider.ts
extensions/azurecore/src/azureResource/providers/resourceTreeDataProviderBase.ts
extensions/azurecore/src/azureResource/resourceService.ts
extensions/azurecore/src/azureResource/resourceTreeNode.ts
extensions/azurecore/src/azureResource/tree/subscriptionTreeNode.ts
extensions/azurecore/src/extension.ts

Add additional logging to connection tree view

---

extensions/sql-bindings/yarn.lock
extensions/sql-database-projects/README.md
extensions/sql-database-projects/package.json
extensions/sql-database-projects/src/common/constants.ts
extensions/sql-database-projects/src/controllers/projectController.ts
extensions/sql-database-projects/src/sqldbproj.d.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/25797 
Updating the default value of SQL Build SDK version in SQL Project extension

Updating the default value of SQL Build SDK version in SQL Project extension (#26245)

---

extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/wizard/skuRecommendation/skuRecommendationPage.ts
extensions/sql-migration/src/wizard/sourceSelectionSection.ts

Text updates:
- Remove Arc usages.
- Update SQL Server Instance -> SQL Server instance
- Update assessment messages. (Refer screenshots)
- Bug Fix: https://msdata.visualstudio.com/Tina/_sprints/taskboard/WS%20-%20Migration/Tina/2025-04-03%20to%202025-04-16?workitem=4050666

Source tracking - Text updates and bug fixes

---

extensions/sql-migration/src/constants/strings.ts
extensions/sql-migration/src/wizard/sourceSelectionSection.ts

Added hint for user to select associated SQL Server if it is already being tracked in Azure.

Add SQL Server hint for user - Source tracking

---

extensions/sql-migration/package.json

Update SQL migration extension version to 1.5.8

Update version - SQL Migration extension

---

extensionsGallery.json

Pipeline run : https://msdata.visualstudio.com/SQLToolsAndLibraries/_build/results?buildId=170200608&view=results
Vsix: https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/c6789c20-b819-4bfd-9917-11471655156e/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYzY3ODljMjAtYjgxOS00YmZkLTk5MTctMTE0NzE2NTUxNTZlL2J1aWxkSWQvMTcwMjAwNjA4L2FydGlmYWN0TmFtZS9kcm9wX1dpbmRvd3NfRXh0ZW5zaW9ucw2/content?format=file&subPath=%2Fextensions%2Fsql-migration-1.5.8.vsix

Update SQL-Migration extension to version 1.5.8

---

extensions/sql-database-projects/package.json

Version Bumping from 1.5.1 to 1.5.2
This change brings in the SQL Projects sorting fix into the release

vBump SqlProjects to 1.5.2

---

extensions/sql-database-projects/package.json

Porting Generate SQL Project from OpenAPI menu option issue along with version bump.
This PR consists of:
1. https://github.com/microsoft/azuredatastudio/pull/26299 
2. https://github.com/microsoft/azuredatastudio/pull/26298

Porting - SQL Project 'Gen Open API option issue' and vBump

---

extensions/data-workspace/package.json

Version bump from 0.6.1 to 0.6.2 for DataWorkspace extension

vbump data workspace extension to 0.6.2

---

extensions/data-workspace/package.json

Version bump from 0.6.1 to 0.6.2 for data workspace extension

port - version bump for workspace

---

product.json

This PR updates the privacy statement to use the forward link specified by the privacy team.

Use forward link for privacy statement

---

src/vs/platform/terminal/node/terminalEnvironment.ts
src/vs/platform/terminal/node/terminalProcess.ts
src/vs/platform/terminal/test/node/terminalEnvironment.test.ts
src/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh

Back ports https://github.com/microsoft/vscode/commit/2f2e2c47d406976b6976ec6114eab8ac44d63513

Add sticky bit to zsh config folder

---

extensions/data-workspace/package.json
extensions/sql-database-projects/package.json

This pull request includes version updates for two extensions to ensure compatibility and reflect the latest changes.
Version updates:
* [`extensions/data-workspace/package.json`](diffhunk://#diff-799dcebe516c7ceb33b0bc61339f7ed1c1befa2dffdf2eb5cb80359da93f6c15L5-R5): Updated the version from `0.6.2` to `0.6.3`.
* [`extensions/sql-database-projects/package.json`](diffhunk://#diff-49766d064fa812f3a78f2a121c7603b811d3a55546d5b5c82b5d12b6c26e25b9L5-R5): Updated the version from `1.5.2` to `1.5.3`.

vBump Data-WorkSpace and Sql Proj extensions

---

package.json

Correcting version in release branch.

Correcting version number to reflect that we never shipped 1.52 even though this was bumped

---

extensions/sql-database-projects/package.json
extensions/sql-database-projects/src/controllers/projectController.ts
extensions/sql-database-projects/src/tasks/sqlDatabaseProjectTaskProvider.ts
extensions/sql-database-projects/src/test/tasks/sqlDatabaseProjectTaskProvider.test.ts

This pull request introduces changes to streamline the handling of build arguments and project styles in the SQL Database Projects extension. The updates include the addition of a `BuildHelper` class, modifications to task definitions, and the integration of project styles for more efficient task creation and execution.
* **Refactored build argument handling in `ProjectsController`:** Updated the logic to use the `BuildHelper.constructBuildArguments` method for generating build arguments, ensuring consistency and reusability. (`extensions/sql-database-projects/src/controllers/projectController.ts`, [extensions/sql-database-projects/src/controllers/projectController.tsL319-R319](diffhunk://#diff-63fe770ed4061d88b5579f1e141073f3f1c3515e63e7e1ea46c364c417c1afb9L319-R319))
* **Integrated …

Fixing  'Run Task' Build for the legacy projects

---

extensions/mssql/config.json

STS version bump to 5.0.20250616.1

STS bump to 5.0.20250616.1

---

extensionsGallery.json

Build: https://msdata.visualstudio.com/SQLToolsAndLibraries/_build/results?buildId=176518869&view=artifacts&pathAsName=false&type=publishedArtifacts
VSIX: https://artprodeussu2.artifacts.visualstudio.com/A8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa/c6789c20-b819-4bfd-9917-11471655156e/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zZGF0YS9wcm9qZWN0SWQvYzY3ODljMjAtYjgxOS00YmZkLTk5MTctMTE0NzE2NTUxNTZlL2J1aWxkSWQvMTc2NTE4ODY5L2FydGlmYWN0TmFtZS9kcm9wX3dpbjMyX3g2NA2/content?format=file&subPath=%2Fextensions%2Fsql-database-projects-1.5.3.vsix

Update sql-database-projects to 1.5.3

---

extensions/markdown-language-features/package.json
extensions/markdown-language-features/yarn.lock
yarn.lock

Bump dompurify to version 3.2.4

---

package.json
yarn.lock

This PR closes https://github.com/microsoft/azuredatastudio/issues/26357

Remove dependencies using hash.js

---

README.md

This PR removes broken download links and adds a link to the latest release page.

Update README.md to remove broken download links

---

extensionsGallery.json
scripts/validateGalleries.js

* updating the net-6-runtime extension's URLs to point to new location
* re-adding dependent extensions to runtime checks

update net6 URLs

---

extensions/sql-database-projects/package.json

Version bump from 1.5.3 to 1.5.4

vBump sqlproj extension

---

extensions/sql-database-projects/CHANGELOG.md

Sql Projects extension CHANGELOG update for 1.5.4 release

---

build/gulpfile.vscode.js
src/vs/base/node/crypto.ts
src/vs/base/parts/ipc/node/ipc.net.ts
src/vs/platform/backup/electron-main/backupMainService.ts
src/vs/platform/checksum/node/checksumService.ts
src/vs/platform/checksum/test/node/checksumService.test.ts
src/vs/platform/languagePacks/node/languagePacks.ts
src/vs/platform/workspaces/node/workspaces.ts
src/vs/server/node/remoteExtensionHostAgentServer.ts

Hashing clean up

---

extensions/sql-database-projects/package.json

This pull request updates the extension version in the `sql-database-projects` package to reflect a new release.
Version update:
* Incremented the version number in `package.json` from `1.5.4` to `1.5.5` to prepare for a new release.

[PORT] VBump SQL Projects extension version from 1.5.4 to 1.5.5
