src/sql/parts/grid/views/query/query.component.html

This makes it possible to tab to the export buttons

Make it possible to tab to result export buttons

---

src/sql/parts/modelComponents/toolbarContainer.component.ts
src/sql/parts/modelComponents/toolbarLayout.css
src/sql/sqlops.proposed.d.ts
src/sql/workbench/api/common/sqlExtHostTypes.ts
src/sql/workbench/api/node/extHostModelView.ts
src/sql/workbench/api/node/sqlExtHost.api.impl.ts

- Added support for defining a vertical toolbar
- Remove border in this case since it's not taking up the full vertical space. We should consider removing the separator in all cases since this isn't how the query editor's toolbar works
- Removed padding to bring this in line with the query editor toolbar
- In vertical mode the title is exposed as a tooltip instead of being show in the toolbar itself

Support vertical orientation for toolbar

---

src/sql/parts/profiler/editor/profilerEditor.ts
src/sql/parts/profiler/service/interfaces.ts
src/sql/parts/profiler/service/profilerService.ts

Update Profiler to (1) prompt the user to create a new session when they try to profile a server for the first time (2) remember the session that was most recently used for a server and select it by default next time.

Prompt to create Profiler session per server

---

src/sql/parts/dashboard/widgets/tasks/tasksWidget.component.ts
src/sql/platform/tasks/common/tasks.ts
src/sql/workbench/common/actions.contribution.ts

add support to allow registering a command without exposing it in command palette, and use the way to hide backup/restore from command palette.
#1781

hide the backup restore commands from command palette

---

src/sql/parts/modelComponents/editor.component.ts
src/sql/parts/modelComponents/modelComponentWrapper.component.ts
src/sql/parts/modelComponents/modelEditor/modelViewEditor.ts
src/sql/platform/dialog/dialogContainer.component.ts
src/sql/platform/dialog/dialogPane.ts
src/sql/sqlops.proposed.d.ts

- This needs to be set directly on the editor component so cannot just use CSSStyles feature
- Given its importance to this scenario, it also warrants a dedicated property.
Fixes #2313 where editor doesn't respond to expand/collapse of the left nav bar. We now send events to the modelview components to re-layout when this happens

Support position property in editor component

---

src/sql/parts/query/editor/gridPanel.ts
src/sql/parts/query/editor/messagePanel.ts
src/sql/parts/query/editor/queryResultsView.ts

We now have to explicitly call `render` on the grid and message result panels after creating them
Fixes the "Execute query doesn't render results" merge bug from #2361

Render query result and message panels

---

src/sql/base/browser/ui/table/table.ts
src/sql/parts/profiler/editor/controller/profilerTableEditor.ts

The recent grid refactoring added an optional configuration option when creating a table but needed some null checks. I also added some logic for sorting since it looks like that logic got pushed out to whatever code creates the table

Fix grid changes that broke profiler

---

package.json
yarn.lock

Reverting to this version of SlickGrid appears to address https://github.com/Microsoft/sqlopsstudio/issues/2372 and https://github.com/Microsoft/sqlopsstudio/issues/1971.
I'll queue a release build with this change so we can assess if this revert introduces other regressions.

Revert SlickGrid to 2.3.25

---

src/sql/parts/accountManagement/accountDialog/media/accountDialog.css

This is the issue that Ken brought this morning.

hide the account count badge in linked account dialog

---

extensions/mssql/package.json
src/sql/parts/connection/common/connectionProfile.ts
src/sql/parts/connection/common/providerConnectionInfo.ts
src/sql/parts/connection/connectionDialog/connectionWidget.ts
src/sql/parts/objectExplorer/viewlet/connectionTreeAction.ts
src/sql/parts/objectExplorer/viewlet/serverTreeRenderer.ts
src/sql/sqlops.d.ts
src/sql/workbench/api/common/sqlExtHostTypes.ts
src/sqltest/common/telemetryUtilities.test.ts
src/sqltest/parts/accountManagement/firewallRuleDialogController.test.ts
src/sqltest/parts/connection/connectionManagementService.test.ts
src/sqltest/parts/connection/connectionProfile.test.ts
src/sqltest/parts/connection/connectionStatusManager.test.ts
src/sqltest/parts/connection/connectionStore.test.ts
src/sqltest/parts/connection/connectionTreeActions.test.ts
src/sqltest/parts/connection/objectExplorerService.test.ts
src/sqltest/parts/connection/providerConnectionInfo.test.ts
src/sqltest/parts/insights/insightsDialogController.test.ts
src/sqltest/stubs/capabilitiesTestService.ts

Connection names are saved in config and will be loaded on startup.
Server names, db and auth type are shown on hover.
Names are optional and will makes the server tree look like before if no name is given:
I liked the third mockup of this: https://github.com/Microsoft/sqlopsstudio/issues/240
Unfortunately I don't think there is support for multiple lines in the treeview at the moment which brought me to the solution above.
Fixes #66

Feature: Ability to add connection name

---

scripts/sql-cli.sh

- This copies up to date contents from code-cli.sh. Alternatively we could remove this file and force use of code-cli.sh always

Update sql-cli.sh so it actually works

---

extensions/import/src/services/config.json

This is for #2390. There were 2 issues there that prevent the Import extension from working in Linux in the current release. This PR fixes the issue where the config had a single generic Linux download path but that option is not actually part of `service-downloader` yet (it's in Kevin's open PR but never got merged). 
The other issue is that our build was zipping up the Mac build and publishing it as the Linux build, which I've already fixed. In order to force Linux users to redownload the service this change bumps the version number to 0.0.2.

Fix Import extension Linux download config

---

src/sql/workbench/api/node/sqlExtHost.api.impl.ts

Matching sqlExtHost.api.impl.ts to extHost.api.impl.ts to utilize the URI.file().fsPath in the call for extensionPaths.findSubstr().
Long story short, without this fix, the extension id cannot be extracted from the extension path reliably on Windows (case sensitive comparisons, hooray!), and "defaultApiImpl" is set to true.

fix for extensionPaths.findSubstr not using URI.file(<filename>).fspath

---

src/vs/workbench/parts/extensions/electron-browser/extensionTipsService.ts

Fix regression so Recommended extensions sort first in the Extension Manager Marketplace pane.

Fix Extension Manager marketplace sorting

---

src/sql/sqlops.d.ts
src/sql/sqlops.proposed.d.ts
src/sql/workbench/api/node/extHostConnectionManagement.ts
src/sql/workbench/api/node/mainThreadConnectionManagement.ts
src/sql/workbench/api/node/sqlExtHost.api.impl.ts
src/sql/workbench/api/node/sqlExtHost.protocol.ts

Add parameter connectionCompletionOptions of type IConnectionCompletionOptions to connection.openConnectionDialog.
export interface IConnectionCompletionOptions {
saveTheConnection: boolean;
showDashboard: boolean;
showConnectionDialogOnError: boolean;
showFirewallRuleOnError: boolean;
}

Enable the support for post-connection behaviors for openConnectionDialog

---

src/vs/platform/extensionManagement/node/extensionGalleryService.ts

Fixes #2425.
The latest VS Code merge added some code that puts '&install=true' or '&update=true' on the end of URLs when installing extensions, which doesn't work with our extension blob storage

Fix extension installation that broke in merge

---

src/sql/parts/modelComponents/tree/treeViewDataProvider.ts
src/sql/workbench/common/views.ts

IModelViewTreeViewDataProvider extends ITreeViewDataProvider, which already has a getChildren method. This new getChildren method was causing undefined promise errors in Item.refreshChildren() in treeModel.ts.

Remove redundant getChildren method in IModelViewTreeViewDataProvider.

---

src/sql/parts/objectExplorer/common/registeredServer.contribution.ts
src/sql/parts/taskHistory/common/taskHistory.contribution.ts
src/vs/workbench/parts/debug/electron-browser/debug.contribution.ts
src/vs/workbench/parts/extensions/electron-browser/extensions.contribution.ts
src/vs/workbench/parts/files/electron-browser/files.contribution.ts
src/vs/workbench/parts/scm/electron-browser/scm.contribution.ts
src/vs/workbench/parts/search/electron-browser/search.contribution.ts

Fixes https://github.com/Microsoft/sqlopsstudio/issues/2465.  It looks like negative viewlet order IDs are n longer supported.

Fix Action Bar viewlet ordering

---

src/sql/parts/connection/connectionDialog/connectionWidget.ts

Move the Connection Name field to the bottom of the dialog based on feedback that this option field shouldn't have initial focus, as it adds an extra step to the default connection workflow (i.e., tabbing to Server).

Reorder Connection Name field in Connection Dialog

---

src/sql/parts/query/editor/media/messagePanel.css

Changes the cursor in the messages panel from being the pointer the entire time, other than on the line link.

Change cursor in message panel to default

---

src/vs/workbench/parts/update/electron-browser/update.ts

Fixes https://github.com/Microsoft/sqlopsstudio/issues/2479 by disabling prompt until we support per-user setup.

Disable the User Setup prompt

---

src/vs/workbench/parts/files/electron-browser/fileCommands.ts
src/vs/workbench/services/editor/browser/editorService.ts

#2423 
Behavior prior to the fix:
for both **Save** and **Save All**  the file(s) will be saved and opened in text editor(s) instead of query editor(s).
Behavior in a build before the vscode merge:
**Save All**: files will be saved but opened in new text editors and the previous query editors will be left open with no content in them.
with the changes in this PR, both issues have be addressed

fix the save and save all for untitled file

---

src/sql/workbench/api/node/extHostAccountManagement.ts

Fix for issue: #2500 
the this._accounts collection is not initialized when we call the getSecurityToken() method, adding the get all accounts operation prior to the getting the security token.

fix the account not found error when creating firewall rules

---

src/sql/parts/modelComponents/modelEditor/modelViewInput.ts
src/sql/sqlops.proposed.d.ts
src/sql/workbench/api/node/extHostModelViewDialog.ts
src/sql/workbench/api/node/mainThreadModelViewDialog.ts
src/sql/workbench/api/node/sqlExtHost.protocol.ts

This PR:
- Adds support for the model view editor programmatically setting isDirty flag on editor. 
- Plumbs through support for save over the sqlops API channel.
This does not fully implement save (issue #2529 and #2530) because we will have to make alterations to the textFileService in order to do that correctly. However there's value in getting the isDirty handling into the product, and having save partially integrated will make the next PR simpler.

Support isDirty flag for model view editors and begin plumb through of save support

---

src/sql/parts/connection/common/connectionStore.ts

#2558
later in the connect logic, we use the password property of the options property collection, but it is not set when the connection is newly added. i could force it to use the password property for password option but it might be needed in other scenarios, so i just set both and avoid other potential issues.

fix the connection issue when opening new query after connection

---

src/sql/base/browser/ui/panel/panel.ts
src/sql/base/browser/ui/scrollableSplitview/scrollableSplitview.ts
src/sql/base/browser/ui/table/plugins/cellRangeSelector.ts
src/sql/base/browser/ui/table/plugins/cellSelectionModel.plugin.ts
src/sql/parts/dashboard/widgets/insights/views/charts/chartInsight.component.ts
src/sql/parts/dashboard/widgets/insights/views/charts/interfaces.ts
src/sql/parts/dashboard/widgets/insights/views/charts/types/barChart.component.ts
src/sql/parts/dashboard/widgets/insights/views/charts/types/doughnutChart.component.ts
src/sql/parts/dashboard/widgets/insights/views/charts/types/horizontalBarChart.component.ts
src/sql/parts/dashboard/widgets/insights/views/charts/types/lineChart.component.ts
src/sql/parts/dashboard/widgets/insights/views/charts/types/pieChart.component.ts
src/sql/parts/dashboard/widgets/insights/views/charts/types/scatterChart.component.ts
src/sql/parts/dashboard/widgets/insights/views/charts/types/timeSeriesChart.component.ts
src/sql/parts/grid/views/query/chartViewer.component.ts
src/sql/parts/query/common/queryResultsInput.ts
src/sql/parts/query/editor/charting/chartOptions.ts
src/sql/parts/query/editor/charting/chartTab.ts
src/sql/parts/query/editor/charting/chartView.ts
src/sql/parts/query/editor/charting/insights/graphInsight.ts
src/sql/parts/query/editor/charting/insights/insight.ts
src/sql/parts/query/editor/charting/insights/interfaces.ts
src/sql/parts/query/editor/gridPanel.ts
src/sql/parts/query/editor/messagePanel.ts
src/sql/parts/query/editor/queryResultsView.ts
src/sql/parts/queryPlan/queryPlan.ts
src/vs/base/browser/ui/splitview/panelview.ts
test/all.js

Handles maintaining the query results state during editor changes. I've tested most scenarios I can think of, but this could probably use more testing to catch edge cases I didn't see.
One ("change" or "bug") that i know of that I didn't bother fixing is when changing editor the chart viewer colors will change. I'm not sure this is a big enough bug to block this feature on though.

Maintain Query State

---

package.json
yarn.lock

the referenced package version was changed to 2.3.25 from 2.3.27 when you were doing the vscode merge.

use latest slickgrid library

---

src/sql/parts/objectExplorer/common/objectExplorerService.ts
src/sql/parts/objectExplorer/viewlet/serverTreeView.ts
src/sql/sqlops.d.ts
src/sql/workbench/api/node/extHostObjectExplorer.ts
src/sql/workbench/api/node/mainThreadObjectExplorer.ts
src/sql/workbench/api/node/sqlExtHost.protocol.ts
src/sqltest/parts/connection/objectExplorerService.test.ts

At @ronychatterjee's request I added a way to programmatically refresh object explorer nodes from extensions and from inside Ops Studio

Add OE node refresh API method

---

src/sql/parts/insights/browser/insightsDialogView.ts

Fixes all bugs noted in https://github.com/Microsoft/sqlopsstudio/issues/2590 by manipulating the collapsible state after data is loaded. Screenshot -

Dashboard: Fixed all insight bugs

---

src/sql/parts/grid/media/slick.grid.css

Since @anthonydresser has added a way of determining dbnull values in the slickgrid cell we could atleast underline NULL values:
In my opinion this is a critical feature that we really need now.
If we later want to add a specific dbnull background color for themes we could replace this solution in the future.
#217

Added text underline CSS for DB NULL values when editing / showing data

---

src/sql/parts/query/editor/messagePanel.ts

Fixes #2642 by using the same method to handle batch links that the old `queryModelService.ts` did in `setEditorSelection`

Scroll query editor when clicking batch links

---

extensions/account-provider-azure/src/account-provider/azureAccountProviderService.ts

The Azure account provider "Clear token cache" command wasn't working because when the command got renamed from "extension.clearTokenCache" it got called "accounts.clearTokenCache" in some places and "accounts.azure.clearTokenCache" in others

Fix broken 'Clear Token Cache' command

---

src/sql/parts/query/editor/charting/chartView.ts

There were 2 errors in the chart state restore logic that caused query editors to fail to restore successfully if the user had opened chart viewer and switched the chart type.
This is a fix for part of the error in #2635

Fix chart error that caused query editor to close

---

src/sql/parts/query/editor/queryEditor.ts

Fixes #2645 by implementing the same logic as normal text editors so that the editor scrolls when setting the editor's options, which happens when the find button gets clicked

Scroll query editor when clicking on global find result

---

src/sql/parts/modelComponents/tree/tree.component.ts
src/sql/parts/modelComponents/tree/treeComponentRenderer.ts

This fix is for the checkbox bug.
The checkbox tree was working previously, but now it has some issues after big code update happened in SqlOpsStudio. There 2 issues are discovered (see attached files for details):
1) The check in checkbox does not stay if we signal tree data is changed.
2) The neutral state of the check box is no longer working.

Fix for broken checkbox status in checkbox tree node

---

extensionsGallery-insider.json
extensionsGallery.json

This updates the SSMSKeymap extension to 1.0.0. This has updated README contents to reference Azure Data Studio and adds 1 additional keybinding for *Refresh Intellisense Cache*

Update the SSMSKeymap extension to 1.0.0

---

src/sql/parts/editData/common/editDataInput.ts
src/sql/parts/query/common/queryInput.ts
src/vs/workbench/browser/parts/editor/tabsTitleControl.ts

Fixes #2742 which broke in the last VS Code merge because the editor group changes removed some of our VS Code source edits and stopped calling tab redraw automatically after a connection

Fix tab color break caused by VS Code merge

---

src/sql/parts/connection/common/connectionManagement.ts
src/sql/parts/connection/common/connectionManagementService.ts
src/sql/parts/connection/connectionDialog/connectionDialogService.ts
src/sql/parts/editData/common/editDataInput.ts
src/sql/parts/objectExplorer/viewlet/treeUpdateUtils.ts
src/sql/parts/query/common/queryInput.ts
src/sqltest/parts/connection/connectionDialogService.test.ts
src/sqltest/parts/connection/connectionManagementService.test.ts

Fixes a bug where the OE spinner keeps spinning forever if you click on a disconnected connection without a saved password and then cancel out of the connection dialog

Stop OE connection spinner when user closes connection dialog

---

src/sql/parts/objectExplorer/common/objectExplorerService.ts
src/sqltest/parts/connection/objectExplorerService.test.ts
src/vs/base/parts/tree/browser/treeModel.ts

If an OE expand operation failed with a timeout or other error then whenever the user tried to reexpand the node it would just pop up the same error message again instead of retrying. This change makes the code call refresh if the node has an error

Fix bug where failed OE expands could not be retried

---

CONTRIBUTING.md

:memo: (Contributing) Fixing a reference to SQL ops studio to match new branding of Azure Data Studio.

📝 (Contributing) Fixing a reference to SQL Ops Studio

---

extensions/mssql/src/config.json
src/sql/parts/connection/common/connectionConfig.ts

Right now if you open the connection dialog and choose an existing connection and then connect, or if you try to connect to a server with an unsaved password and then fill in the password in the dialog once it pops up, the saved connection jumps to the bottom of its group in OE. This code changes the connection saving logic so that the ordering won't change when a connection is edited.
I also increased the Tools Service version to bring in my other OE fixes

Fix bug where connections edited in connection dialog moved to bottom of group

---

src/sql/parts/query/editor/gridPanel.ts

fixes #2743 
This properly handles reset to make grids show up after rerunning after maximizing.
This doesn't maintain the maximized grid, it basically resets the table states. Not sure if we want to restore the maximized state or not.

Restore grids when maximized

---

src/sqltest/parts/connection/connectionConfig.test.ts

These tests got commented out in a VS Code merge about a year ago. In order to test the fix from #2782 I fixed them and added the new test at the end

Bring back Connection Config tests

---

src/sql/parts/modelComponents/editor.component.ts
src/sql/parts/modelComponents/queryTextEditor.ts
src/sql/sqlops.proposed.d.ts
src/sql/workbench/api/node/extHostModelView.ts

Allow for auto-resizable editor component, offering flexibility for the editor to expand dynamically in size and prevent excess scrollbars in notebooks.

Allow for auto-resizable editor component

---

src/sql/parts/dashboard/dashboardInput.ts
src/sql/parts/dashboard/services/breadcrumb.service.ts

Ensuring connection name is used in 'Manage' tab name per this issue:
https://github.com/Microsoft/azuredatastudio/issues/2763

Fixed when right clicking and selecting Manage-correct name displays

---

src/sql/parts/grid/views/editData/editData.component.ts

fixed 2 regressions introduced by my previous merges:
1. Revert row doesn't refresh the data - I cleared the current cell and then later try to use the currentCell.row.
2. In the edge scenario, you will see dirty indicator for 2 rows - fixed it by defining the dirty row and in the meanwhile use the currentCell.row instead of the target cell's row. so only the style can be correctly applied to the dirty row.

revert row edit and dirty row fix

---

extensions/import/package.json
extensions/import/yarn.lock

- Import extension used very old version of telemetry. Updating avoids sending deprecation warning to console which CSS requested we fix.

Remove os.tmpDir deprecation warning

---

build/win32/code.iss

Changes the "Register File handler" product name string from azuredatastudio to Azure Data Studio.  This fixes a customer reported issue, though I could find it while quickly scanning the issue list.

Update product name in Register Files setup checkbox

---

.vscode/launch.json
src/sql/parts/modelComponents/editor.component.ts
src/sql/parts/modelComponents/queryTextEditor.ts
src/sql/sqlops.proposed.d.ts
src/sql/workbench/api/node/extHostModelView.ts

Editor component didn't have a minimum height set, so fixing this by passing through a minimum height to EditorComponent. Now, if the scrollable height of the editor is less than the minimum height, we use the minimum height as the height of the component.
Also fixed an issue where the markdown code editor's height was far too high. Now we're calculating the height on the layout() call, which gets called every  time we display the markdown editor.

Fix Default Height for Editor Component

---

src/sql/parts/queryPlan/queryPlan.ts

Currently the query plan control can have a height larger than the tab panel so the horizontal scrollbar won't be visible.  This sets the height\width on `layout`.

Fix query plan scrollbars

---

src/sql/parts/query/editor/messagePanel.ts

This modifies how we render query messages to support multi-line messages. Previously new lines were stripped from messages, meaning that things like stack traces did not display correctly, and each message was hardcoded to 22px height since it was only ever a single line. Now the height of each message is calculated dynamically based on the number of lines in the message.
This also fixes a couple other bugs with how we displayed messages:
- Maintains the message scroll position when switching between query tabs, which used to work but broke recently
- If a query returned so many messages that it scrolled the message window the message window would start scrolled all the way down instead of starting at the top
Before:
After:

Display multi-line messages correctly in query results

---

src/vs/platform/telemetry/browser/errorTelemetry.ts
src/vs/platform/telemetry/test/electron-browser/telemetryService.test.ts

Since we're not using this event in our reporting, let's remove it.

Remove unhandled exception telemetry

---

src/sql/base/browser/ui/splitview/splitview.css

the removed css class was designed to hide icon in toolbar when HC theme is selected. but I don't see such rule in other parts of the product or VS Code.

fix for issue 2719

---

src/sql/parts/commandLine/common/commandLineService.ts
src/sql/parts/connection/common/connectionManagement.ts
src/sql/parts/connection/common/connectionManagementService.ts

#3065 
aside from the issue tracked in #3065, opening the database dashboard will also cause a connection to be saved in OE.
introduced a parameter so that the commandline can choose whether to save the connection without impacting other features using the connection management service.

fix for issue 3065

---

src/sql/workbench/errorMessageDialog/errorMessageDialog.ts

Fixes a bug where the "Copy details" button on the connection error message pop-up always had white text regardless of its background, making it hard to read on light themes

Use correct foreground color for copy details button

---

src/sql/parts/profiler/editor/profilerInput.ts

#3157 
Give user the option to choose what to do before closing the editor.
**Before**
**After**

fix for issue 3157

---

src/sql/parts/notebook/models/clientSession.ts
src/sql/parts/notebook/models/modelInterfaces.ts
src/sql/parts/notebook/models/notebookModel.ts
src/sql/parts/notebook/notebook.component.ts
src/sql/services/notebook/localContentManager.ts
src/sql/sqlops.proposed.d.ts
src/sql/workbench/api/common/sqlExtHostTypes.ts
src/sql/workbench/api/node/extHostNotebook.ts
src/sql/workbench/api/node/mainThreadNotebook.ts
src/sql/workbench/api/node/sqlExtHost.protocol.ts
src/sqltest/utils/testUtils.ts
src/sqltest/workbench/api/extHostBackgroundTaskManagement.test.ts
src/sqltest/workbench/api/exthostNotebook.test.ts
src/sqltest/workbench/api/mainThreadNotebook.test.ts

Implements provider contribution in the MainThreadNotebook, with matching function calls in the ExtHostNotebook class. This will allow us to proxy through notebook providers (specifically, creation of a notebook manager with required content, server managers) from an extension up through to the main process.
Implemented in this PR:
- Callthroughs for content and server manager APIs
- Very basic unit tests covering provider & manager registration
Not implemented:
- Fuller unit tests on the specific callthrough methods for content & server manager.
- Contribution point needed to test this (so we can actually pass through the extension's existing Notebook implementation)

Begin defining Extension-based Notebook Provider

---

src/sql/parts/profiler/editor/profilerEditor.ts
src/sql/parts/profiler/service/profilerService.ts

1. fix #3123 - this is the UI side of fix, there is another fix at the sqltoolsservice side. basically regardless the error, we will set the UI to allow user to start another session instead of the unrecoverable state. with the service side fix, this should not happen, but just in case.
2. fix the issue that the session selection in the dropdown is lost when switch 2 running profiler editors. previously the code is resetting the collection but not restoring the selection, I refactored the code a bit.

fix for stop session error and session selection lost issue

---

extensions/azurecore/package.json
extensions/azurecore/yarn.lock

Moves the `request` dependency in the azure core extension from 2.63.0 to 2.88.0.

Use newer version of request in azurecore

---

src/sql/parts/jobManagement/views/alertsView.component.ts
src/sql/parts/jobManagement/views/jobsView.component.ts
src/sql/parts/jobManagement/views/operatorsView.component.ts
src/sql/parts/jobManagement/views/proxiesView.component.ts

Improved performance when switching Jobs/Alerts/Operators/Proxies tabs, when they aren't loaded yet. Also fixes some silent angular exceptions.
Improves https://github.com/Microsoft/azuredatastudio/issues/3136

Agent: Improved perf

---

src/sql/parts/connection/connectionDialog/connectionDialogWidget.ts

Fixes #2837 by canceling the connection and keeping the connection dialog open if you hit cancel or escape while a connection is in progress.

Don't close connection dialog when canceling a connection

---

src/sql/parts/common/customInputConverter.ts
src/sql/parts/notebook/notebook.contribution.ts
src/sql/parts/notebook/notebookInput.ts

- After this, the `notebook.enabled` flag must be set to true when testing notebook integration

Add notebook feature flag that is enabled by default

---

src/sql/base/browser/ui/taskbar/media/taskbar.css
src/sql/parts/profiler/editor/profilerEditor.ts

fix for issue #3280.
Before:
After:

make taskbar more readable

---

src/sql/sqlops.d.ts
src/sql/workbench/api/node/extHostAccountManagement.ts
src/sql/workbench/api/node/sqlExtHost.api.impl.ts

I added the `resource` parameter to this API in my AAD changes but it needs to be optional so that it doesn't break any extensions that are already using the API

Make resource parameter optional for getSecurityToken API

---

extensions/profiler/package.json

#3325 
These 3 commands are for internal use only (by the profiler task bar buttons) and require additional parameters to be passed in. I am hiding them in the command palette to avoid confusion.

hide the profiler commands meant for internal use

---

extensions/import/src/wizard/pages/selectOperationpage.ts

The import extension was throwing errors during activation on Ubuntu.

Fix capitalization in dataTierApplicationWizard imports.

---

src/sql/parts/connection/connectionDialog/connectionWidget.ts

The logic I added for hiding/showing the username and password boxes or the Azure account picker only ran if there was an auth type dropdown, which isn't true for all connection providers. This updates it to hide the Azure account picker by default
Fixes #3345

Hide connection account picker when there are no auth type options

---

src/sql/parts/modelComponents/queryTextEditor.ts

Code cells in notebook sometimes show scrollbars (#3359); it turns out this is due to issues surrounding word wrapping. Needed to change the logic that determines the height for a given code cell in order to take into account word wrap.

Fix Notebook Code Cell Height when Lines Wrap

---

src/sql/parts/notebook/notebookActions.ts

AttachTo SelectBox options values are update before this.setOptions in openConnectionDialog by somehow. But from code, didn't find any set. So clear the options value before setOptions

Fixed add multiple connection from "Add new connection" #3387 

---

src/sql/parts/notebook/notebook.component.ts
src/sql/parts/notebook/notebookInput.ts

Exposed setDirty method from NotebookInput class
Consumed it in NotebookComponent when there is a change in the content
Set it back after save

Set active editor with dirty value before and after save #3411

---

src/sql/parts/notebook/notebookActions.ts
src/sql/services/notebook/sessionManager.ts

Assign attach to value as 'localhost' when the kernel is 'No Kernel' which means there is no extension installed.

Defaulting 'attach to' to localhost when no extension is installed #3419

---

src/sql/parts/query/editor/queryResultsView.ts

Related to https://github.com/Microsoft/azuredatastudio/issues/2899.  I'm not sure if this is only issue impacting #2899, but this fixes the leak in the tab-switching scenario.

Dispose of query grid memory on tab switch

---

src/sql/parts/profiler/contrib/profilerActions.contribution.ts
src/sql/parts/profiler/editor/controller/profilerFindWidget.ts
src/sql/parts/profiler/editor/controller/profilerTableEditor.ts
src/sql/parts/profiler/editor/profilerEditor.ts
src/sql/parts/profiler/editor/profilerInput.ts

Fix the following issues
1. #3379 the focus got moved away from the search box on every keystroke, fix it by moving the focus back to the find input box after locating the 1 occurrence in the grid.
2. show the connection in Object Explorer when starting profiling for a connection
3. The find feature is case sensitive, making it hard to search for strings. 
4. sometimes the search is not working as a result of a missing null check, adding the null check to make search more robust
5. CTRL+F will not able to bring up the search box for profiler table after tab switching, this is caused by the context key not being set properly after the view is re-focused.

profiler extension bug fixes

---

src/sql/parts/notebook/models/modelInterfaces.ts
src/sql/parts/notebook/models/notebookModel.ts
src/sql/parts/notebook/notebook.component.ts
src/sql/services/notebook/notebookService.ts
src/sql/sqlops.proposed.d.ts
src/sql/workbench/api/common/sqlExtHostTypes.ts
src/sql/workbench/api/node/extHostNotebookDocumentData.ts
src/sql/workbench/api/node/extHostNotebookDocumentsAndEditors.ts
src/sql/workbench/api/node/extHostNotebookEditor.ts
src/sql/workbench/api/node/mainThreadNotebookDocumentsAndEditors.ts
src/sql/workbench/api/node/sqlExtHost.api.impl.ts
src/sql/workbench/api/node/sqlExtHost.protocol.ts
src/sqltest/parts/notebook/common.ts

- Add edit API that can be used in the extension
- Separated document and editor classes out since this is the point those get big. I can refactor back in if needed to ease code review
- Based this off text editing APIs but tweaked for the fact this is a cell/array based set of edits

Fix #3420 Analyze in notebook doesn't include text

---

src/sql/parts/notebook/notebookInput.ts

- We missed implementing matches functionality. This is required in order to skip reopening of the notebook

Fix #3470 Notebook: Switching between Servers and File Explorer opens a duplicate notebook

---

src/vs/workbench/parts/welcome/gettingStarted/electron-browser/gettingStarted.contribution.ts
src/vs/workbench/parts/welcome/gettingStarted/electron-browser/updateToAzureDataStudio.ts

Add an "Update to ADS" prompt to a final SQL Operations Studio release to notify users still on 0.32.9 that a manual upgrade is required to move to current Azure Data Studio builds.  I'll follow-up over email to nail down the exact notification text and URL targets.

Add "Update to ADS" prompt to SQL Ops Studio

---

.vscode/launch.json
src/sql/parts/common/customInputConverter.ts
src/sql/parts/notebook/notebook.component.ts
src/sql/parts/notebook/notebookUtils.ts
src/sql/services/notebook/notebookRegistry.ts
src/sql/services/notebook/notebookService.ts
src/sql/services/notebook/notebookServiceImpl.ts
src/sql/workbench/api/node/mainThreadNotebookDocumentsAndEditors.ts

- Fixes #3197 Notebooks: builtin provider always used on reopen with notebook file visible
- Fixes #3414 Can't refresh kernel after connect to big data cluster
There are 3 parts to this fix:
- If no notebook provider other than the default is installed, we warn users and prompt to install the SQL2019 extension
- We wait on the extension host registration to complete before determining which provider to use
- We know that the extension registration of the provider instance will be after package.json is read, so if we wait after registration for 10 seconds to give this a chance to happen before returning a provider to the front end

Handle delayed Notebook provider registration

---

src/sql/parts/connection/connectionDialog/media/connectionDialog.css

This is a hacky fix for https://github.com/Microsoft/azuredatastudio/issues/3514 which appears to be related to https://github.com/Microsoft/azuredatastudio/commit/f36f3ffd211b2a6aead709652dd175620a620223#diff-8d7ef5bb586fea22d1506d362b8a2d22.  I'm going to take this fix directly in `release\1.3` branch and a proper fix can be done in master.

Remove a style that is breaking the "Clear MRU" list

---

src/sql/parts/query/execution/queryRunner.ts

I'm seeing the "Something went wrong" error message document in https://github.com/Microsoft/azuredatastudio/issues/3369 much more frequently with the result streaming feature.  
As far as I can tell there is no user impacting issue beyond the annoying notifications.  This PR turns off the notification in the `release/1.3` branch.  The prompt is still enabled in `master` so we can root cause https://github.com/Microsoft/azuredatastudio/issues/3369.

Turn off "something went wrong" message

---

extensionsGallery-insider.json
extensionsGallery.json

Please align this with the December release. I've verified locally that the links all work as expected.

Release version 0.9.1 of the SQL Server 2019 Preview Extension

---

src/sql/parts/grid/views/editData/editData.component.ts
src/sql/parts/query/execution/queryModelService.ts

Fixes #3633 by updating Edit Data to process both 'resultSetAvailable' and 'resultSetUpdated' events, ignoring any event that isn't marked as complete.
This essentially matches the old behavior where it would just listen for a single resultSetComplete notification.

Update edit data for result set streaming changes

---

extensions/import/src/wizard/pages/deployConfigPage.ts

This fixes the database not getting set correctly for deploy scenario if coming from the import page. Previously, the database value was only getting set when the value was undefined, but it is already set to a value when coming a different page before going through the deploy scenario steps.

Fix database not getting set correctly in DacFx wizard deploy scenario

---

src/sql/parts/notebook/cellViews/code.component.ts
src/sql/parts/notebook/models/notebookModel.ts
src/sql/parts/notebook/notebook.component.ts

Fixes #3546. When adding a new code cell, we mark it as the selected cell and add focus to it. When it's markdown, we just mark it as the active cell.
When loading a notebook, I'm just marking the first cell (if it exists) as active/selected.

Notebooks: Fix Selection/Focus when New Cells Added

---

src/sql/parts/notebook/notebook.component.ts

Ensure we call Dispose() on NotebookModel when notebook component is destroyed.
We need a fix on the extension side as well for #3524 but this improves the experience by not throwing errors anymore. Extension PR coming soon...

Ensure we call Dispose() on NotebookModel when notebook component is destroyed

---

src/sql/parts/query/editor/gridPanel.ts

This is for #3673, where result grid selections and scroll positions are no longer getting saved when switching between tabs.
I'm still investigating an issue where the overall result's scroll position gets reset only when switching between a query editor tab and a non-query tab. Also the horizontal scroll position in the grid doesn't get saved but that's not a regression from November at least
Update: Solved the issue with the overall split view's scroll position getting reset

Save grid selection/vertical scroll when switching tabs

---

src/sql/parts/notebook/notebook.component.ts

Setting activeCell on the model to null during cell deselection isn't necessary; on a subsequent cell selection, we were trying to set activeCell.active when activeCell was null, leading to an exception being thrown when trying to add a new cell when a cell wasn't currently selected; this caused new cells not to be drawn until a cell was selected.

Fix Active Cell Null Ref Issue in Specific Deselection Case

---

src/sql/platform/dialog/wizardModal.ts

The DacFx wizard adds and removes pages based on the selected operation. The onValidityChanged listener wasn't getting added to newly added pages, causing the next button to not get enabled even when the page became valid.
This change moves adding the onValidityChanged listener from render() to showPage() so that it gets added to pages that are added to the wizard after the initial start up.

Fix #3676 DacFx wizard import page next button doesn't update

---

src/sql/parts/notebook/models/notebookModel.ts

Fix contentManager and notebookManager undefined issues when 'builtin' manager is used.
This occurs when SQL kernel isn't enabled, and the extension is not installed. After this change, restores the ability to open notebooks using builtin viewer again.

Fix contentManager undefined when builtin manager used

---

src/sql/parts/notebook/cellViews/code.component.ts

When creating a new notebook, adding one cell at a time and calling this.editor.focus() is totally fine.
However, when opening an existing notebook with existing editor cells, this means that every editor instance will demand focus. Which is really bad.
As a workaround for right now, getting rid of the call to focus(). @kevcunnane we need a better solution longterm, as we previously discussed.

Fix focus issue when opening notebooks

---

src/sql/workbench/api/node/mainThreadNotebookDocumentsAndEditors.ts

Notebook always shows as loading kernels if we pass in a connection, which means that we set the providerId upfront.
Regardless of whether the providerId is set or not, we should still get all providers and populate the providers array.

Notebooks: Ensure we always get all providers, regardless if a provider is passed in

---

src/sql/parts/notebook/cellViews/code.component.ts
src/sql/parts/notebook/cellViews/textCell.component.ts
src/sql/parts/notebook/models/notebookModel.ts
src/sql/parts/notebook/notebook.component.ts

- When opening a notebook, no cells are selected/has focus by default; markdown cells are not in edit mode
- When creating a new notebook, the default code cell is selected and has focus
- When creating a new markdown cell, cell opens in edit mode, is selected, and has focus
- When creating a new code cell, cell is selected and has focus
- When creating a new cell (either markdown or code), we scroll to the new cell location

Notebook: Improvements to Cell Selection/Focus/Scrolling + Open Markdown Cells in Edit Mode

---

src/sql/parts/notebook/notebookInput.ts

1. Added confirmation dialog returning of type ConfirmResult while closing current editor.
2. Extended save functionality by consuming notebookService which would pull the active editor
3. Implemented Save/Don't Save/Cancel functionality for existing and new notebooks
4. I see a minor issue for new notebooks. Working on it.

Notebook Doesn't Prompt for Save even when isDirty #3568

---

src/sql/parts/accountManagement/accountDialog/media/accountDialog.css

Fixes https://github.com/Microsoft/azuredatastudio/issues/3777 .  The custom split view PR (https://github.com/Microsoft/azuredatastudio/pull/3467) removed the `provider-view` container div which breaks the below styles. The styles appear specific enough without the container class, so this change remove `provider-view` from the selectors.

Update Azure account picker styles based on splitview change

---

src/sql/parts/dashboard/widgets/explorer/explorerTree.ts

Fix for issue : Search widget in Manage dashboard truncates long names with no hovertext to show full name  (Ref for issue: https://github.com/Microsoft/azuredatastudio/issues/3075)

adding hover text for dashboard serach grid items

---

src/sql/parts/query/editor/actions.ts
src/sql/parts/query/editor/messagePanel.ts

Fixes https://github.com/Microsoft/azuredatastudio/issues/3032
The issue was that we were getting the selection from the tree DOM but all the entries are only rendered when the tree is scrolled. Got all the messages now for a special case of "Select All". Fixed for context menu as well as keyboard shortcuts.
Also fixes https://github.com/Microsoft/azuredatastudio/issues/3044

Copy all messages when selecting all

---

extensions/import/src/wizard/api/models.ts
extensions/import/src/wizard/dataTierApplicationWizard.ts
extensions/import/src/wizard/pages/dacFxSummaryPage.ts
extensions/import/src/wizard/pages/deployActionPage.ts
extensions/import/src/wizard/pages/selectOperationpage.ts
extensions/mssql/src/config.json
extensions/mssql/src/contracts.ts
extensions/mssql/src/features.ts
src/sql/platform/dacfx/common/dacFxService.ts
src/sql/sqlops.d.ts
src/sql/workbench/api/node/mainThreadDataProtocol.ts
src/sql/workbench/api/node/sqlExtHost.protocol.ts

This adds the ability to generate the script for a deployment to the DacFx wizard. An additional page was added to the deploy scenario to choose whether to Deploy, Generate Deployment Script, or do both.
Generate Script:
Generate Script and Deploy:

Add generate script option to DacFx wizard

---

src/sql/parts/notebook/cellViews/placeholderCell.component.html
src/sql/parts/notebook/cellViews/placeholderCell.component.ts
src/sql/parts/notebook/notebook.component.ts

Fixing 2 bugs here:
- When creating a new cell from the placeholder cell, new cell was not active (issue was that unselectCell() was being called from notebook.component after cell was being created, so calling event.stopPropogation() fixes that)
- When creating a new cell, unselecting the cell then selecting it again did not select the cell properly; to fix, setting model.activeCell to undefined when unselecting ensures that the selection logic always works properly
Additionally, in the notebook component, we don't need to call this.selectCell() explicitly, since this is taken care of in the model.

Notebooks: Fix Selection Issues

---

extensions/mssql/src/config.json

Bump sqltoolservice to release 69 to fix #3839 doesn't have model.sys.assemblies

Bump sqltoolservice to release 69 to fix #3839 doesn't have model.sys.assemblies

---

extensions/notebook/src/extension.ts
src/sql/workbench/services/commandLine/common/commandLineService.ts
src/sqltest/parts/commandLine/commandLineService.test.ts

First command to leverage it is new notebook. It turned out we can't serialize the entire ConnectionProfile to the extension so we just pass the id. The id is sufficient for the notebook plugin.

Pass connectionid to registered commands from command line

---

src/sql/workbench/services/notebook/common/sqlSessionManager.ts

Fixes #3856. Matches the Jupyter behavior that we have, where we don't show any message when a connection is required. We no longer will throw a bizarre exception about getOptionsKey being undefined.
Also sets max rows returned to 2000.

Fix weird exception when no connection is present for SQL kernel, Limit Max Rows to 2000

---

src/sql/parts/notebook/models/notebookModel.ts

Fixing an issue where we got a 501 Not Implemented because kernel display name sanitization was not occurring with the _defaultKernel case.
In addition, changed a method name to make it more clear, and removed an erroneous error that would occur every time you opened a notebook without any existing connections. I'm just removing this, as it adds no value.

Fix a not implemented issue when we were not sanitizing kernel display name

---

src/sql/parts/notebook/cellViews/code.component.ts
src/sql/parts/notebook/models/modelInterfaces.ts
src/sql/parts/notebook/models/notebookModel.ts
src/sql/parts/notebook/notebook.component.ts
src/sql/parts/notebook/notebookEditor.ts
src/sql/parts/notebook/notebookInput.ts
src/sqltest/parts/notebook/common.ts
src/sqltest/parts/notebook/model/notebookModel.test.ts

- Editor layout gets called sometimes when other events happen (and Notebook isn't visible)
- Add in a layout call on re-setting input so the cell is updated. This fixes the problem by laying out once the UI is visible again.
Note: long term, should really be destroying the UI (while preserving the model), then restoring it including scroll selection etc. and hooking back up to the model. That is... much more work, but something we'll need long term to avoid issues where we have many Notebooks open at once. Not in scope for this PR

Fix #3734 Notebook cells are shown empty some times even when there is content

---

src/sql/workbench/services/notebook/common/sqlSessionManager.ts

- SQLKernel is the only place to listen for batch and query complete messages now
- It routes to the 1 and only future (since can only have 1 at a time
- It handles query cancelation and not-connected issues correctly

Fix bug where results were added to all cells, and support multiple resultsets

---

src/sql/parts/notebook/cellViews/code.component.html
src/sql/parts/notebook/cellViews/code.css
src/sql/parts/notebook/cellViews/codeCell.component.html

- Make the toolbar sticky and remove overflow:hidden which blocked this working.
UI:
Default: run at top of cell like before
On scroll: run stays at top of visible area
Scroll lower: run sticks where it was inside the toolbar area

Make run cell button float so it's always visible

---

extensions/notebook/package.json
extensions/notebook/package.nls.json
extensions/notebook/src/extension.ts

If config.notebook.sqlKernelEnabled is true, use SQL provider
Use Jupyter provider if Python is install, otherwise use buildIn Kernel.

Ported Analyze notebook code from SqlOpsStudio and make it work.

---

extensions/notebook/package.json
extensions/notebook/package.nls.json
src/sql/parts/notebook/cellViews/code.css
src/sql/parts/notebook/notebook.component.ts
src/sql/parts/notebook/notebookStyles.ts
src/sql/workbench/services/notebook/common/notebookServiceImpl.ts

This was reviewed / worked on with Smitha and will be signed off on by PM via mail.
1 thing left (make run button look better when not selected) will be one in separate review.
Changes
- Add top/bottom padding to editor so it's not cramped
- Added an (on by default) setting `notebook.overrideEditorTheming`. This controls whether new colors etc. are used for notebook editors or if users should see vanilla UI like in standard editor. Settings under this flag are:
- When unselected, editor has same color as toolbar. On selection it goes back to regular editor view so colors work "right"
- In standard light/dark themes we now use a filled in background color instead of border box.
**Screenshots**
_Selected, hovered, and unselected code cells, light theme_
Note how selected has normal editor …

Improve notebook colors and UX

---

src/sql/parts/notebook/models/modelInterfaces.ts
src/sql/parts/notebook/models/notebookModel.ts
src/sql/parts/notebook/notebookActions.ts
src/sqltest/parts/notebook/common.ts

- 'Attach to' dropdown would be defaulted to 'Select connection' if sql(only) connection is selected for Spark kernels
- User will have the ability to add a new connection
- User can toggle existing connections
- Add 'Select connection' to dropdown if an invalid connection is selected. In this case sql connection.
- Remove 'Select connection' from dropdown if a valid bigdata connection is selected.
- Show error message to user upon selecting a sql connection for Spark kernels

#3897: Unified connection integration - sql connection improvements

---

src/sql/parts/modelComponents/table.component.ts
src/sql/parts/modelComponents/table.css
src/sql/sqlops.proposed.d.ts

This adds the toolTip option for TableColumn and also aligns the padding left of headers and cells so that it all aligns.
tooltip:
without padding(left) and with padding(right) :

Add tooltip for table column headers and align header and cell

---

src/sql/parts/notebook/cellToggleMoreActions.ts
src/sql/parts/notebook/cellViews/code.component.ts
src/sql/parts/notebook/cellViews/textCell.component.html
src/sql/parts/notebook/cellViews/textCell.component.ts
src/sql/parts/notebook/notebook.css

Fixes #3939 and #3925.
- Fixed so `...` is now invisible instead of empty when not selected.
- This fixes both the fact it wasn't clickable on hover, and the issue where on hover out it stayed visible. No idea why it fixes hover out but glad it does!
- Also fixed cell output action which used active cell instead of context cell.

Fix toggle more actions staying visible, and clickable issues

---

extensions/mssql/src/objectExplorerNodeProvider/hdfsCommands.ts

Don't know why it works in previous extension not in mssql after ported. But look like needs to call utils.getErrorMessage to get msg.

Fixed #3888 some exception handles in hdfsCommand doesn't use utils.getErrorMessage to get error

---

src/sql/parts/modelComponents/queryTextEditor.ts
src/sql/parts/notebook/cellViews/code.component.ts

Now that word wrap is off by default, we weren't calculating editor height correctly; now we support it better when word wrap is off and on.
Fixes #3947 
I banged my head on how to avoid the magic numbers (like adding 4 to the viewport column), but am unsure how we can calculate that "properly". Things like non-monospaced fonts can absolutely break the calculations, but they could previously as well. I'm confident that we're doing a step in the right direction, though :).

Improve notebook editor height calculations

---

extensions/import/src/wizard/dataTierApplicationWizard.ts
extensions/import/src/wizard/pages/dacFxSummaryPage.ts
extensions/import/src/wizard/pages/deployActionPage.ts
extensions/import/src/wizard/pages/deployConfigPage.ts
extensions/import/src/wizard/pages/deployPlanPage.ts
extensions/import/src/wizard/pages/selectOperationpage.ts
extensions/mssql/src/config.json
extensions/mssql/src/contracts.ts
extensions/mssql/src/features.ts
src/sql/platform/dacfx/common/dacFxService.ts
src/sql/sqlops.d.ts
src/sql/workbench/api/node/mainThreadDataProtocol.ts
src/sql/workbench/api/node/sqlExtHost.protocol.ts

This adds a page to the DacFx wizard for the deploy scenario. This will show if there could be any potential data loss from the deployment and require the user to check a checkbox to proceed if there could be any data loss.
Data loss:
No data loss:

Add Deploy Plan page to DacFx wizard

---

README.md

Adds insiders build links to the readme and clearly marks them as "Insiders build" so that users don't confuse them with the regular download links above.
For now this doesn't include the Linux .rpm or .deb installers since those don't auto update correctly but does include the .tar.gz archive.

Add insiders build links to readme

---

src/sql/parts/notebook/cellViews/code.component.html
src/sql/parts/notebook/cellViews/code.component.ts
src/sql/parts/notebook/cellViews/code.css
src/sql/parts/notebook/cellViews/codeActions.ts
src/sql/parts/notebook/media/dark/stop_cell_solidanimation_inverse.svg
src/sql/parts/notebook/media/light/execute_cell_error.svg
src/sql/parts/notebook/media/light/stop_cell_solidanimation.svg
src/sql/parts/notebook/models/cell.ts
src/sql/parts/notebook/models/modelInterfaces.ts
src/sql/parts/notebook/notebookActions.ts
src/sql/workbench/api/node/mainThreadNotebookDocumentsAndEditors.ts
src/sql/workbench/services/notebook/common/sqlSessionManager.ts

Fixes #3931 
- Align run button correctly so it's centered in new cell
- Refactor to support multi-state button.
- Hidden state is set to show execution count
- Stopped state shows run button
- Running state shows stop button
- Error state (will) show error button. This isn't fully handled right now
- Add execution count to model and to SqlKernel, verify serialization, loading, update matches other notebook viewers
**Notes on implementation**:
I think this is a decent solution for a) showing execution count as text, and b) perfectly centering the run button.
The below solution shows count correctly up to 999 runs (that’s clicking 999 times in a single session), the icon lines up juuust about right with [ ] but for other numbers it is pretty close but probably not exactly right. I wish I …

Support execution count in run button and align correctly

---

package.json

Fixes https://github.com/Microsoft/azuredatastudio/issues/3491.  See https://github.com/anthonydresser/html-query-plan/pull/8 for details.

Bump html_query_plan to 2.6

---

src/sql/parts/notebook/outputs/tableRenderers.ts

With @anthonydresser's help, mapping using the field property in a SlickColumn allows us to map the column names using unique identifiers, instead of their names, which aren't guaranteed to be unique.
The canonical scenario that this fixes is a simple query like "SELECT 1, 2".
Fixes #3927.

Notebook: Fix Grid Issue when Multiple Columns have Same Name

---

src/sql/parts/notebook/models/clientSession.ts
src/sqltest/parts/notebook/model/clientSession.test.ts

stopServer method in the sqlops extension is called twice, one from session object and the other one from notebook.component. Removed code from ClientSession.

Notebook server shutdown error

---

src/sql/parts/modelComponents/queryTextEditor.ts
src/sql/parts/notebook/cellViews/code.component.ts
src/sql/parts/notebook/cellViews/code.css
src/sql/workbench/services/notebook/common/notebookService.ts
src/sql/workbench/services/notebook/common/notebookServiceImpl.ts

- Note that I'm still hiding the overall toolbar section per UX feedback
- Also now hiding line numbers per UX feedback..

Fix #3985 Hide cell toolbar for markdown cells

---

src/sql/parts/modelComponents/queryTextEditor.ts
src/sql/parts/notebook/cellViews/code.component.ts
src/sql/parts/notebook/cellViews/codeCell.component.ts

Fixes #3843. Now includes full fix which limits length and ensures a scrollbar is available
- Set max size for editor. 4000px gets us 200-250 lines before needing a scrollbar. 
- Adds layout updating which should also ensure accurage line highlighting to the right of the editor. What's happening is initial size is slightly off, so need to layout a 2nd time (e.g. layout once, let flex figure things out, then layout a 2nd time). This isn't optimal as there's a minor perf hit but it isn't noticeable overall.
To consider in future PRs:
- Add user configurable setting for max length?
- Handle case where we scroll to bottom but scrollbar is at the top. 
- Consider how intellisense will work on this. We may need to split into a window around the current code when sending to the kernel as it's …

Beginning of fix for notebook perf

---

src/sql/parts/notebook/notebook.component.ts
src/sql/parts/notebook/notebookEditor.ts
src/sql/parts/notebook/notebookInput.ts
src/sql/platform/connection/common/connectionManagement.ts
src/sql/platform/connection/common/connectionManagementService.ts
src/sql/workbench/api/node/mainThreadNotebookDocumentsAndEditors.ts
src/sql/workbench/services/notebook/common/notebookService.ts
src/sqltest/stubs/connectionManagementService.test.ts

The problem is: connectionProfileId is not passed into New Notebook flow.
The fix is: plumbing connectionProfileId via NotebookInput.
I have tested the following scenarios:
- New NB from command palette
- New NB from "Data Services" context menu
- New NB from big data cluster dashboard tab
1. select standalone SQL server in OE
2. select big data cluster master instance
Attach To: shows the correct server from context
Please let me know if there are other cases. Chris and I are trying to find out new NB from SSMS->ADS

Fixed #3954 pass connection info to new notebook flow

---

src/sql/parts/notebook/models/notebookModel.ts
src/sql/workbench/services/notebook/node/localContentManager.ts

- Fix #3844 Failed to open Notebook with saved invalid kernel
- Fix #3955 Attach To: stuck at "Loading contexts... 
- Specs can be null on early load of Jupyter kernels
- Cells were missing in some reference test .ipynb files. We should be resilient to malformed files if possible.

Fix issues due to missing notebook values (specs and cells)

---

extensions/notebook/src/extension.ts

Good to know and fix it in time. I missed this when ported code to core. Thanks Cory

Fixed #4002 Added hard coded pySpark3 kernel for analyze notebook. 

---

src/sql/base/browser/ui/scrollableSplitview/scrollableSplitview.ts
src/sql/parts/query/editor/gridPanel.ts
yarn.lock

Fixes #3993. `ScrollableSplitView`'s `addViews` method expected views in reverse order (the last one in the array passed in would end up at the top), but the views were not being passed in reverse order when minimizing a maximized result set. I've changed `addViews` to expect them in a normal order and updated code where needed.

Fix bug minimizing a maximized result grid

---

src/sql/parts/notebook/notebook.css

Fix left table border to be dotted, no longer have table border on div. Fixes #3988.
Problem previously was that there is a minimum size for the grid's div, so if tabular data came back that was too small for the div, a border would be much too large for the table.
Here's how this looks after the change:
I also tried adding a left border to the 1st column header. That experiment did not go well; all other columns were shifted over by a px or 2, making them out of alignment.

Notebooks: Fix left table border to be dotted, no longer have table border on div

---

src/sql/parts/modelComponents/queryTextEditor.ts
src/sql/parts/notebook/models/modelInterfaces.ts
src/sql/parts/notebook/models/notebookModel.ts
src/sqltest/parts/notebook/model/notebookModel.test.ts

- Fix error where kernel name was compared to itself. This doesn't break anything right now since we happen to have special handling of Python3, and for other kernels they share the same set of supported providers (which is what the check is used for). However it needs fixing for next release.
- Fix console error due to queryTextEditor trying to access model before it's ready
- Fix issues where notebook model hooked to session events multiple times
- Removed calls that weren't needed such as loadActiveContexts (if undefined, does nothing) and passing connection to initialize method

Fix kernel name check bug, double-event hooking, and other Notebook issues

---

src/sql/parts/notebook/models/notebookModel.ts

Ensure we always switch to a kernel that exists in the session manager.
This fixes an issue where the Jupiter kernel throws a 501 not implemented when trying to open a notebook with a kernel that isn't one of its specs.

Ensure we always switch to a kernel that exists in the session manager

---

src/sql/parts/notebook/outputs/common/outputProcessor.ts
src/sql/workbench/services/notebook/common/sqlSessionManager.ts

Final UX is still being worked out for messages, but I would like to do this iteratively to avoid a giant PR later on. Fixes #3974.
This PR is pretty simple, just shows messages in the output of each cell (i.e. "(x rows affected")). In addition, this tweaks the error handling such that errors now show up in the output area instead of in a dialog.
In future PRs, we can tweak the error color (since this can have rippling effects on jupyter errors as well), and change the location for messages. In addition, we need more work to support the "Started executing query at Line <x>" message, as we currently pass a string in for the content, but the queryRunner really needs an object implementing ISelectionData instead (otherwise, it erroneously says that the line number always starts at 1).
Error: …

Notebook: Show Errors and Messages in Output Area

---

src/sql/parts/notebook/models/modelInterfaces.ts
src/sql/parts/notebook/models/notebookModel.ts
src/sql/parts/notebook/notebookActions.ts
src/sqltest/parts/notebook/common.ts

1. Connect ADS to a SQL server(sql only)
2. Create a new notebook by enabling sql kernel feature flag
3. Change kernel to PySpark3, click on 'Add new connection'
4. Connection dialog will be opened, cancel it.
Issue: 'Attach to' shows sql connection.
Expected: 'Select Connection' should be shown with connection invalid message.

'Attach to' with Spark kernel resets to sql connection on cancelling connection dialog

---

src/sql/workbench/services/commandLine/common/commandLine.ts
src/sql/workbench/services/commandLine/common/commandLineService.ts
src/sqltest/parts/commandLine/commandLineService.test.ts
src/vs/code/electron-main/launch.ts

This hooks up the ADS command line service to electron's ipcRenderer pipe. The launch service in main process will forward command line arguments on to it via a new channel after processing the default file arguments etc. I had to refactor the service to move member variables into per-function call state.
This will enable callers to reuse the same ADS window for multiple commands, avoiding a ton of startup costs on subsequent commands.

window reuse for connections

---

test/all.js

After this change we're excluding the following 2 .js files which don't have corresponding js map files:
Excluding: "/Users/chlafren/azuredatastudio/out/vs/base/test/common/filters.perf.data.js"
Excluding: "/Users/chlafren/azuredatastudio/out/vs/base/common/performance.js"
Then just printing out a simple message about where the coverage folder is, so that other folks don't have to hunt anymore 😄.
Command for creating this folder for code coverage is scripts/test.<sh|bat> --coverage

Allow code coverage command to succeed again

---

src/sql/parts/notebook/cellViews/code.component.ts
src/sql/parts/notebook/models/cell.ts
src/sql/parts/notebook/models/notebookModel.ts
src/sql/parts/notebook/notebook.component.ts

Implemented the simple version intelliSense support as we discussed -- make the connection when the cell is active. If this doesn't look good, let's try the other complicate solutions.
Some notes:
- Didn't put connect into Kernel. Right now Kernel doesn't know active cell. also requestExecute is only string. But if we still need to put it in Kernel, we can definitely plumbing through those. Just SQL Kernel has lots of extra stuff comparing other Kernels.
- CellUri is not set until creating editor. so when addCell, uri is undefined, failed to connect.
Move createUri to cell.ts and call it in cell constructor
- We have multiple places set activeCell. Should we consolidate them?

Added SQL notebook IntelliSense

---

src/sql/parts/notebook/notebookActions.ts
src/sql/parts/notebook/notebookUtils.ts
src/sqltest/parts/notebook/model/notebookUtils.test.ts

After this change, users can more easily see if they're connected to master, or directly connected to another database. Now, in the Attach To, users will see connections in the form of "ServerName (DatabaseName)". For connections to master, users will still just see the server name in the dropdown.
Also added some unit tests for the methods that I added in notebookUtils.

Notebooks: Add database name to attach to (if not connected to master)

---

src/sql/parts/notebook/cellViews/outputArea.component.ts

Fixes #4074.
Looks like we had the same problem in ComponentBase, so solving it in the same way here.

Fix the Attempt to use a destroyed view Errors

---

src/sql/workbench/services/notebook/common/sqlSessionManager.ts

@anthonydresser got me thinking about table perf yesterday. He has some good ideas about how we might be able to improve serialization/deserialization for the dataresource MIME type and some suggestions about alternatives to the synchronous way that we're utilizing the queryRunner, both of which we should address soon. 
In this PR, there was some low-hanging fruit with how we're generating a string for an HTML table (in cases where opening a notebook that we've saved in a viewer that doesn't support the dataresource MIME type).
I searched around and it seems like the consensus online is that, for strings, doing str += 'anotherString' is pretty much the fastest way to do string concatenation in javascript. If anyone knows of a way to use a StringBuilder-esque data structure in TypeScript, …

Notebooks: Greatly Reduce Time to Generate HTML Table String

---

extensions/notebook/src/jupyter/serverInstance.ts

Notebooks: Ensure that we preserve rest of PATH when starting the Jupyter process.
This unblocks various cell magics and a few kernels that rely on the PATH variable being populated properly.
Fixes #4112.

Notebooks: Ensure that we preserve rest of PATH when starting Jupyter

---

build/azure-pipelines/common/publish.ts

Some edits we had made to the `publish.ts` script we use for automatically publishing builds got reverted in the VS Code merge when the file got moved. This PR puts them back

Reapply changes to publish.ts script

---

src/sql/parts/notebook/cellViews/textCell.component.ts

@ronychatterjee has been asking for this for quite a while. Until we have new UX for markdown cells, I think this makes it a bit nicer looking.
Tested notebook save/open, markdown cells both with content and no content, double-clicking when the double-click message appears opens an empty markdown editor. Fix seems relatively safe.
Before:
After:

Make "Double-click to edit" in empty markdown cell a bit nicer looking

---

src/sql/parts/notebook/cellViews/code.component.ts

1. Converted 'then' operations to await as the 'modelEditor' object is dependent on the values within then able.
2. Added await keyword to setInput method as it return thenable.

'Couldn't display content' fix in Notebooks

---

ThirdPartyNotices.txt
extensions/notebook/package.json
extensions/notebook/src/jupyter/jupyterServerInstallation.ts

This PR fixes two issues:
1. The **request** npm package was missing, causing the extension to fail to start.
2. Windows python installation was failing due to the sparkmagic wheel no longer being bundled with the extension. My workaround here is to use our "offline" python installation package for the windows setup, since it already has all the needed dependencies bundled together. It also removes the need for hard-coded pip package versions in our Windows pip install code, as well as slightly reducing overall python setup time by about a minute in ad-hoc local testing.

Fix lingering bugs from notebook code merge.

---

src/sql/parts/dashboard/widgets/insights/insightsWidget.component.ts

- For cached insights, it was going down the checkStorage path which wasn't covered

Fix #4145 Possible for loading icon to appear with rendered widget

---

src/sql/parts/notebook/cellViews/code.component.ts

layoutEmitter.fire should be a method but accessed as a property in code.component.ts.
Codecell content is now visible even if we navigate between notebooks. See below.

Fix #3734 - Codecell content disappers when tabbing editors

---

extensionsGallery-insider.json
extensionsGallery.json

Note: We seem to be experiencing inconsistent behaviour when viewing the details page of SQL Search Extension in the extension marketplace. Some users see the new up-to-date details page with details about 0.3.0 version. Other users still see 0.2.1 details page even when they have 0.3.0 installed.

Publish update for Redgate SQL Search extension

---

src/sql/parts/modelComponents/queryTextEditor.ts
src/sql/parts/notebook/cellViews/code.component.ts
src/sql/parts/notebook/notebook.component.ts
src/sql/workbench/services/notebook/common/sqlSessionManager.ts

- Fixes #4129 Overlapping command help windows in notebook
- Do not show parameter hints for inactive cells, to avoid them hanging around when no longer selected
- Fixes #4116 Notebooks: Intellisense Doesn't Work using Add New Connection
- Move connect/disconnect logic to 1 place (code component) instead of 2
- Handle the case where you connect after choosing active cell. We now hook to the event and update connection
- Fix issues in sql session manager where result outputs 0 rows. This was failing to show the empty resultset contents, which is a regression vs. query editor. It also put unhandled error on the debug console
- Fix #3913 Notebook: words selected in other cells should be unselected on cell change
Note: after fix, now looks as follows. Need to do follow up to get correct grid …

Notebook fixes: Fix #4129, fix #4116, Fix #3913, fix empty results error 

---

build/win32/code.iss
scripts/test.bat
src/vs/platform/windows/common/windows.ts

This fixes #4118 and #3812 by disabling VS Code's custom menu entirely, updating the Windows test script to report results to the command line by default, and removing a line that tried to include some missing files in the Windows installers

Fix Windows issues with menu, packaging, and test script

---

src/sql/base/browser/ui/button/button.ts
src/vs/base/browser/ui/button/button.ts

#4095 I also removed one of our changes to the original vscode button since it was no longer needed.

remove builder from button

---

src/sql/platform/query/common/queryRunner.ts

Query result copying stopped working correctly in the VS Code merge because it directly used a config value that used to be `\n` or `\r\n` but now had a default of `auto` to join lines together. This PR updates the logic to use VS Code's `TextResourcePropertiesService` to get the correct new line character for the OS.

Use correct new line character when copying query results

---

src/vs/vscode.d.ts
src/vs/vscode.proposed.d.ts
src/vs/workbench/api/node/extHost.api.impl.ts
src/vs/workbench/api/node/extHost.protocol.ts
src/vs/workbench/api/node/extHostTypes.ts

This adds no-op VS Code debug extensibility APIs to allow extension to work in either host environment without modification.  This is to better support loading extensions like Powershell or Docker that make sense in both contexts, but provide debugging functionality that will only work in VS Code.  See https://github.com/Microsoft/azuredatastudio/issues/4162 or https://github.com/Microsoft/azuredatastudio/issues/3929 for example.
Here is PowerShell extension loaded with working command explorer viewlet and language service.

Add no-op debug extensibility APIs

---

src/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts

Fixes https://github.com/Microsoft/azuredatastudio/issues/4196 by adding a null check before access `extensionIdentifier`.  As far as I can tell, this method has been mostly rewritten in the latest VS Code branch so it's a good candidate for rewrite during the next merge.  In the meantime this gets the VSIX side-loading experience back to before the 1.30 merge.

Add null check to extensionIdentifier to show reload notification

---

src/sql/parts/notebook/notebookStyles.ts

Fix for #4156, one of @twright-msft's asks.
Changing the border-width here was the culprit. After this change, here's a screenshot (how do you attach a video?):

Stop cell content from moving around on hover

---

extensions/notebook/src/jupyter/jupyterServerInstallation.ts

process.env.Path is undefined on Linux, so the whole path wasn't being included.

Use upper case PATH for jupyter environment variables.

---

src/sql/parts/query/editor/resultsGridContribution.ts

Column auto-size needs to be on by default since this is a common friction point.  If there are side-effects let's get those fixed.  We can always disable directly in the release branch for March if absolutely required.

Turn-on auto-size columns by default

---

extensions/agent/src/agentUtils.ts
extensions/agent/src/typings/ref.d.ts
src/sql/azdata.d.ts
src/sql/azdata.proposed.d.ts
src/sql/workbench/api/common/sqlExtHostTypes.ts
src/sql/workbench/api/node/extHostConnectionManagement.ts
src/sql/workbench/api/node/sqlExtHost.api.impl.ts

We are starting a process to review all Azure Data Studio extensibility APIs in order to produce a "Version 1" supported set of supported extensibility points.  Currently some APIs have inconsistent or otherwise undesireable attributes we'd like to correct prior to ensuring long-term backcompat on those interfaces.
The highlevel process is as follows.
1. Create a new typing `azdata` proposed and stable file.
2. Freeze the `sqlops` typings file as deprecated
3. Add all current APIs into the `azdata` proposed file
4. Review all extensibility APIs focus on extensibility scenario and move APIs into the stable file once accepted.
This PR is being used for the following.
1. Create the new extensibility typings file named `azdata` for future extensibility API definitions.
2. Contains the version …

Add azdata.d.ts for new extensibility APIs

---

src/sql/parts/notebook/notebook.component.ts
src/vs/platform/actions/browser/menuItemActionItem.ts

Some changes that were applied to MenuItemActionItem in the big vscode merge also needed to be applied to LabeledMenuItemActionItem for it to render properly.
Fixes https://github.com/Microsoft/azuredatastudio/issues/4219

Update LabeledMenuItemActionItem to match new vscode behavior.

---

src/sql/parts/notebook/cellViews/code.component.ts
src/sql/parts/notebook/models/clientSession.ts
src/sql/parts/notebook/models/modelInterfaces.ts
src/sql/parts/notebook/models/notebookModel.ts

The problems are:
* When change Kernel across provider for example from PySpark3 to SQL, setProviderIdForKernel switches Kernel first. So this.kernel is set SQL already in ClientSession.changeKernel. Then oldKernel and newKernel are the same, we don't have oldKernel info.
The fix is cache the old session in model before switch and use it to get the correct context
* SQL Kenerl could make multiple connects from "Add new connection". While we didn't track them, those connections will stay when close the notebook.
The fix is saving the connections made from "Add new connection" in model. And disconnect them and activeConnection when close notebook
Problem is not solved yet in this PR:
* Jupytper is not disposed when switch kernel from spark to SQL. Haven't found good way to solve it.

Fixed #4181 and #4167 change kernel issue between SQL and Sparks #4238

---

src/sql/workbench/services/notebook/sql/sqlNotebookManager.ts

It looks like a recent commit is referencing the old extensibility namespace.

Update 'sqlops' to 'azdata' in Notebook Manager

---

scripts/watch.bat

It appears `--max_old_space_size` is too small in this bat file and it makes watch very slow.  I've switched to `yarn watch` which has a higher value set, so let's remove this duplicate way to launch watch

Remove watch script and use 'yarn watch' instead

---

extensions/mssql/package.json
extensions/mssql/src/objectExplorerNodeProvider/fileSources.ts
extensions/mssql/src/objectExplorerNodeProvider/hdfsCommands.ts
extensions/mssql/src/objectExplorerNodeProvider/hdfsProvider.ts
extensions/mssql/src/objectExplorerNodeProvider/webhdfs.ts
extensions/mssql/src/utils.ts

Currently WebHDFS node module has several problems such as failure to retrieve correct error message from response object and not localized error messages.
I checked the node module GitHub repository, and found the latest update was an year ago. Bug fix contribution merge request has been hanging almost an year. The repo does not seems to be managed actively.
So I rewrote the WebHDFS for our use. It is rewritten in typescript from original version, no behavior or functional change applied.
The only changes that needs to be focused on is `parseError()` method for get correct error message from response and localized error messages.

Added WebHDFS rewritten to provide correct Error object and localized error messages

---

src/sql/parts/notebook/notebook.component.ts

I was getting "Cannot display contents: {0}" from doLoad when doing some notebook testing, so I added getErrorMessage to convert the caught error to a string.

Convert caught error to string in notebook doLoad error message.

---

extensions/integration-tests/src/objectExplorer.test.ts
extensions/integration-tests/src/testConfig.ts
extensions/integration-tests/src/utils.ts
scripts/setbackendvariables.cmd
scripts/setbackendvariables.sh
scripts/sql-test-integration.bat
scripts/sql-test-integration.sh

Add tests against BDC and standalone instance.
We need to disconnect properly for the active node in OE. So we can simplify the test logic. Create the task: OE integration test needs to add disconnect to close connect properly #4272

Add check OE node tests

---

src/sql/workbench/browser/modal/modal.ts
src/sql/workbench/browser/modal/optionsDialog.ts

Options is not mandatory in the workflow. Added an additional check to see whether options is available before we check the cancelLabel.
Fix for error when clicked on Backup\Restore button:
Unhandled Promise rejection: Cannot read property 'cancelLabel' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'cancelLabel' of undefined
at OptionsDialog.render (workbench.main.js:300769)
at BackupUiService.showBackupDialog (workbench.main.js:306616)
at BackupUiService.showBackup (workbench.main.js:306585)
at new ZoneAwarePromise (C:\Users\azureuser\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:891)
at BackupUiService.showBackup (workbench.main.js:306584)
at exports.showBackup (workbench.main.js:162654)
at new …

Fix backup 

---

extensions/mssql/package.json
extensions/mssql/yarn.lock
package.json

- This was needed in mssql extension, not the main package.json
- undoes the change in commit acc8d5f7b282e36e24a13e0b11f3ba6851c6b2de, and adds to mssql extension instead.

Fix insiders build by adding request dependency to correct package.json

---

extensions/git/src/main.ts

Fixes #4235 where the git extension was failing to activate.
I don't fully understand the root cause and we should investigate it further since it could affect other files in the future. It's some issue with how we process and use web pack on extensions that caused `undefinedundefined` to get inserted in the middle of the minified file.
The built version of `extensions/git/src/main.ts` has a line at the end `//# sourceMappingURL=main.js.map`. We have code in `build/lib/extensions.ts` and elsewhere that rewrites the `sourceMappingURL` comment and I think somehow it was getting messed up, possibly due to the block comment interfering with whatever regular expressions we use to find that line. When I ran webpack on the extension directly the file came out correctly so I don't think it's a …

Fix bug where git extension fails in packaged builds

---

src/sql/parts/dashboard/pages/serverDashboardPage.component.ts

Fixes https://github.com/Microsoft/azuredatastudio/issues/3882 by special-casing `MSSQL` provider.

Set dashboard DB to master only for MSSQL provider

---

extensions/big-data-cluster/src/config/config.ts
extensions/big-data-cluster/src/installer/download.ts
extensions/big-data-cluster/src/installer/installer.ts
extensions/big-data-cluster/src/kubectl/SqlServerBigDataClusterChannel.ts
extensions/big-data-cluster/src/kubectl/binutil.ts
extensions/big-data-cluster/src/kubectl/kubectl.ts
extensions/big-data-cluster/src/kubectl/kubectlUtils.ts
extensions/big-data-cluster/src/main.ts
extensions/big-data-cluster/src/scripting/scripting.ts
extensions/big-data-cluster/src/utility/shell.ts

As part of learning the codebase I spotted a few issues:
- We should localize all strings. Converted to expected nls.localize format
- We get compile warnings due to tslint if we use " instead of '. Fixed
- Converted 1 usage of \n to use os-specific EOL.

cluster deploy extension: Add localization support and fix " to ' strings

---

.github/new_release.yml

Adds the necessary yml for the bot to auto tag new release issues for up to 5 days after a new release, then it will auto delete the label from issues.

Adds new release yml for bot

---

src/sql/parts/grid/media/flexbox.css

Issue #4278 A recent changes in the VSCode layout for that viewlet caused the min-height property to affect the display (the property was set on that class before but the layout prevented it from actually being displayed as it was).
I removed the style for the messages class completely since I couldn't find a place that we actually used that ourselves - and anyways having styling on such a common name like messages isn't really a good practice since it applies to everything in ADS.

Issue #4278 - Fix extra spacing in the file search view

---

extensions/dacpac/src/wizard/dataTierApplicationWizard.ts
extensions/import/src/wizard/flatFileWizard.ts

The flatfile and Dacfx wizards weren't defaulting to the selected connection when launched from the command palette. This fixes #3485

Fix #3485: Flatfile and Dacfx wizards don't default to selected connection

---

src/sql/parts/objectExplorer/viewlet/treeUpdateUtils.ts
src/sql/workbench/services/connection/browser/connectionDialogWidget.ts

This fixes https://github.com/Microsoft/azuredatastudio/issues/4325.  The timing of the tree model refresh has changed and now the Saved Connections view is rendered prior to the model update.  This PR changes the view content update to occur after the tree model is finished updating.

Fix connection dialog 'Saved Connections' refresh timing

---

extensions/big-data-cluster/yarn.lock
src/sql/parts/common/customInputConverter.ts
src/sql/parts/notebook/notebookActions.ts
src/sql/parts/notebook/notebookInput.ts

The Attach To was showing only localhost for SQL, since we overrode the standard kernels from SQL with the ones from Jupyter.
Fix is to save all standard kernels.
Also, added dispose handling for some events I found during debugging and removed unused imports

Notebooks: fix AttachTo showed only Localhost

---

src/sql/parts/notebook/notebookInput.ts

Confirmation dialog will be prompted while closing notebook-editor in order to save/don't save/cancel. This happens only if notebook is dirty. Good thing is, save dialog doesn't show up when you close ADS instead of individual notebook. This was never the case earlier. Here are implementation details.
1. Leveraged TextFileService to apply 'confirm save' for both untitled/titled notebooks
2. TextFileService is used to perform Save operation for UntitledEditorInput where as TextFileEditorModel is used for existing files. Implemented Save() method in NotebookInput, so that when we select 'save' from confirmation dialog content will be saved to disk. 
3. Editor closing is initiated from editGroupView.ts where in it uses doHandleDirty method.

'Confirm save' implementation while closing untitled/existing notebooks

---

extensions/mssql/src/sqlClusterLookUp.ts
extensions/mssql/src/utils.ts
extensions/notebook/src/common/utils.ts
extensions/notebook/src/jupyter/jupyterSessionManager.ts
src/sql/parts/notebook/cellViews/codeActions.ts
src/sql/parts/notebook/models/cell.ts
src/sql/parts/notebook/models/modelInterfaces.ts
src/sql/parts/notebook/notebook.component.ts
src/sql/parts/notebook/notebookUtils.ts

Fixes #4021.
Also ensures that the million IEndpoint interfaces are at least in common utils classes.

Rewrite Spark UI link when using unified connection

---

src/sql/parts/notebook/notebookInput.ts

Removed model update on kernel change event as it is triggered twice after model gets loaded. It introduced anew issue that when we change kernel, editor doesn't show dirty. Created a tracking issue https://github.com/Microsoft/azuredatastudio/issues/4365. Will work on it after the kernel refactoring is complete

#4339: Fix - Notebooks show dirty when loaded(Open/New notebook)

---

extensions/mssql/src/objectExplorerNodeProvider/fileSources.ts

Issue: When preview is clicked on files larger than 30MB, it does not load the file and hangs. 
Fix: Only load 30MB data when they click on preview. Specifying the length param while making the api request would achieve this.

pulling max bytes of data through the webhdfs api

---

extensions/mssql/src/main.ts
extensions/notebook/src/extension.ts
extensions/notebook/src/integrationTest/notebookIntegration.test.ts
extensions/notebook/src/jupyter/jupyterController.ts
src/sql/azdata.proposed.d.ts
src/sql/parts/common/customInputConverter.ts
src/sql/parts/notebook/models/notebookModel.ts
src/sql/parts/notebook/notebook.component.ts
src/sql/parts/notebook/notebookEditor.ts
src/sql/parts/notebook/notebookInput.ts
src/sql/workbench/api/node/extHostNotebookDocumentsAndEditors.ts
src/sql/workbench/api/node/mainThreadNotebookDocumentsAndEditors.ts
src/sql/workbench/api/node/sqlExtHost.protocol.ts
src/sql/workbench/services/commandLine/common/commandLineService.ts
src/sql/workbench/services/notebook/common/notebookService.ts
src/sqltest/parts/commandLine/commandLineService.test.ts

Fix new notebook error by passing profile instead of ID.
- I could've just sent the ID over, but this fix sets the stage for disconnected connections to work (since we have enough info to properly connect).
- There's a bug in NotebookModel blocking the disconnected connection part working, but Yurong's in progress fixes will unblock this. Hence checking in as-is and working to properly unblock once that's in.

Fix #4356 New Notebook from connection doesn't connect

---

src/sql/parts/query/editor/gridPanel.ts
src/sql/parts/query/editor/queryResultsEditor.ts

Re enables the row height setting for the results grid
adds the grid font styles to the messages pane as well. (this might not be the best solution for some users but it seems like the right one until we get specific requests otherwise).
fixes #639
fixes #4302

Row height and message font

---

extensions/mssql/src/config.json

Reverting SQL Tools Service for issue https://github.com/Microsoft/azuredatastudio/issues/4392.  It looks like something with the Managed Batch Parser refactor introduces this issue (since it was the only change included in the previous vbump).

Revert SQL Tools Service to 1.5.0-alpha.71

---

src/sql/base/browser/ui/table/plugins/autoSizeColumns.plugin.ts
src/sql/parts/grid/views/editData/editData.component.ts
src/sql/parts/query/editor/gridPanel.ts
src/sql/parts/query/editor/resultsGridContribution.ts

Fixes #4355. This PR just uses the max width setting and exposes it in config, which matches SSMS, but we should think more about smarter ways to resize columns too

Use max column width when auto-sizing columns

---

src/sql/parts/objectExplorer/viewlet/treeSelectionHandler.ts
src/sql/platform/connection/common/connectionManagementService.ts
src/sql/platform/connection/common/connectionProfile.ts
src/sql/platform/connection/common/connectionStore.ts
src/sqltest/parts/connection/connectionManagementService.test.ts
src/sqltest/parts/connection/connectionStore.test.ts

This is a fix for an issue where connections were being added to the MRU list that really shouldn't be  - such as opening a new query window. 
The fix is to modify where we add active connections so that we can use the saveTheConnection option to decide whether to add a connection to the MRU. This was necessary because the old location was called from onConnectionComplete which is sent by the SqlToolsService - and that doesn't get any UI related information like the options. The new location is still only called after the connection completes and will be added only if the connection succeeds.
So now only calls to connect that specify saveTheConnection as true will be added to the MRU. Currently this is limited to just initial connections in the OE dialog and connections made through the …

#3224 Fix extra connections populating MRU List 

---

src/sql/parts/query/common/queryInput.ts
src/sql/workbench/common/taskUtilities.ts
src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
src/sql/workbench/services/queryEditor/common/queryEditorService.ts

When script create or script drop is used to open a sql editor, we use the object name as the Description of the editor, which shows up in the drop down list of open editors. We also include the object name in the text of the tab itself when sql.showConnectionInfoInTitle config is true.
This commit also fixes the tooltip of the tab and the title bar to display non-truncated text.

Add scripted object name to query editor tab display

---

src/sql/parts/common/customInputConverter.ts
src/sql/parts/notebook/notebookInput.ts
src/sql/workbench/api/node/mainThreadNotebookDocumentsAndEditors.ts
src/vs/workbench/common/editor/editorGroup.ts
src/vs/workbench/services/editor/browser/editorService.ts

Fixed the issue of notebook editors(untitled and titled) not being reopened in a proper way. 
Injected UntitledEditorInput into NotebookInput and made code changes accordingly. Now we have UntitledEditorInput for untitled notebooks and FileEditorInput for existing notebooks at run time. Since these two guys have the editor registration in vscode, notebooks would be reopened with built in behavior.
@kburtram : I would request you not to work on the mitigation plan incase you are on it.
Now that we have editorInputs available in NotebookInput, I will spend some time to reuse these inputs wherever needed. Eg: confrimSave, isDirty etc.
Please see below screenshot

#4363: Reopen notebook editors when ADS launched

---

src/sql/parts/notebook/notebookActions.ts

@vickyharp gave feedback that showing "Loading kernels..." is confusing when a kernel change is ongoing.
Synced with @ronychatterjee, and we came up with the string "Switching kernels..." to use in this instance instead. We still show loading initially.

Change Kernels Dropdown to show Changing instead of Loading On Kernel Change

---

src/sql/parts/notebook/models/notebookModel.ts
src/sql/parts/notebook/notebookActions.ts
src/sql/platform/connection/common/connectionManagementService.ts
src/sql/platform/connection/common/utils.ts

Fixes #4383.
I spent a decent amount of time thinking about this problem, and came up with the following solution due to the following reasons:
- We only currently connect using the ConnectionManagementService in SQL (for the purposes of IntelliSense) for all of the notebooks code, and for the Add new connection scenario in the Attach To
- Any new connections from notebooks (besides Attach To [is there a way to include a purpose to simplify this code even more?]) should include the 'notebook' tag when generating the connection URI (we already do this today)
- I don't want to create new connections when they aren't strictly necessary, and would much prefer pruning them instead of creating new ones
Therefore, when we're closing the notebook, we should only be disconnecting from connections …

Fix Issue when OE connection Disconnects on Notebook Close

---

src/sql/base/browser/ui/scrollableSplitview/heightMap.ts
src/sql/base/browser/ui/scrollableSplitview/scrollableSplitview.ts
src/sql/parts/query/editor/gridPanel.ts

I found theres some grid scrolling issues, where grids would disappear during scrolling. I found this is because the class scrollableSplitview wasn't maintaining an updated size during resizing.
fixes #4391
Also fixes the scrollbar bug.

Grid scrolling bugs

---

src/sql/parts/connection/common/connectionContextKey.ts
src/sql/parts/connection/common/serverInfoContextKey.ts
src/sql/parts/objectExplorer/viewlet/serverTreeActionProvider.ts

Currently context key indicating server major version is not loaded when wizard is launched until  `mssql:serverMajorVersion` key is loaded to context when dashboard opens up.
The missing key causes failure to show "Create External Table" menu on right click on database node before opening dashboard because "Create External Table" menu is set to be shown when server major version is >= 15.
This PR  loads `serverMajorVersion` key to context regardless of dashboard opening so that the extension menu can operate correctly.

Added 'serverMajorVersion' key to context which is missed currently and caused failure for loading 'Create External Table' menu

---

src/sql/parts/notebook/notebookInput.ts

Adding revert method from UntitledEditorInput and FileEditorInput. 
This would delete notebook editor from cache when "don't save" is selected  part of "Confirm Save" functionality.

#4441:Revert notebook editor when "don't save" selected

---

src/sql/parts/objectExplorer/viewlet/serverTreeView.ts
src/sqltest/parts/connection/connectionTreeActions.test.ts
src/sqltest/parts/registeredServer/viewlet/serverTreeView.test.ts
src/sqltest/stubs/capabilitiesTestService.ts

This should fix #4445 though I didn't have a great repro for it. @kburtram if you can still repro this could you try out this fix?
@anthonydresser the code I'm adding back here was removed in #880 which makes me think this may not be the right long term solution. Is it ok for now or is there something better you'd suggest?

Put back code to refresh tree when capabilities provider gets new capabilities

---

src/sql/parts/notebook/notebookStyles.ts

Remove ugly border around text cells

---

src/sql/parts/notebook/notebook.component.ts
src/sql/parts/notebook/notebookEditor.ts
src/sql/parts/notebook/notebookInput.ts
src/sql/workbench/api/node/mainThreadNotebookDocumentsAndEditors.ts
src/sql/workbench/services/notebook/common/notebookService.ts

- Await all extension registration before getting providers and providerId
To do this, we need to await way up in the NotebookInput, and promise the model that we'll have values eventually

Fix #4452 Notebook is reloaded with wrong kernel

---

src/sql/parts/notebook/models/cell.ts

Fixes #4483.
When getting the current executionState, we were looking for the existence of a future to determine if a cell was running. However, we were firing the executionStateChanged event too early (before a future existed). Because of this, we wouldn't show a cell as running until we stopped hovering over the button (and the event had been fired by that point where a future existed).
This is a usability issue that like 3 people have brought up today alone. Not a regression, but we really should fix for the release. It's a 1 line change and helps responsiveness tremendously.

Show running state in cell toolbar immediately when cell is run

---

extensions/notebook/src/jupyter/jupyterServerManager.ts
src/sql/parts/notebook/models/clientSession.ts
src/sql/parts/notebook/models/notebookModel.ts
src/sql/parts/notebook/notebook.component.ts
src/sql/parts/notebook/notebookActions.ts
src/sql/workbench/api/node/extHostNotebook.ts

This is necessary to unblock reverting the kernel on canceling  Python install
- startSession now correctly sets up kernel information, since a kernel is loaded there.
- Remove call to change kernel on session initialize. This isn't needed due to refactor
- Handle kernel change failure by attempting to fall back to old kernel
- ExtensionHost $startNewSession now ensures errors are sent across the wire.
- Update AttachTo and Kernel dropdowns so they handle kernel being available. This is needed since other changes mean the session is likely ready before these get going

Fix #4029 Ensure changeKernels always resolves, even in error states

---

src/sql/parts/notebook/models/notebookModel.ts

- Intra-provider kernel change didn't happen because we only tried changing kernel on new session creation.
- Inverted the logic (e.g. did the right thing) and renamed the method so it's clearer what we're doing & what the boolean value should be
- Manually tested all the known scenarios

FIX #4513 Notebook stuck at changing kernel

---

.vscode/launch.json
scripts/test-extensions-unit.bat
scripts/test-extensions-unit.sh
scripts/test-extensions.bat

Add .bat for running extension unit tests (not full integration tests, currently only Notebook) and set up launch.json with 2 new launch configs for running & debugging extension tests.

Add config for running extension tests

---

src/sql/base/browser/ui/selectBox/selectBox.ts

#3476
Fix dropdowns flickering every other time they're opened. The hide message code was being invoked which called hideContextView (the actual dropdown part) even if no message was ever displayed. Now we'll delay setting the message to null and only call hideContextView if we actually had a message to display.
Also fixed small issue where messages that didn't have a container would throw an error when trying to call removeClass (since this.element is pulled from the container and thus was undefined.
Tested that the flicker is gone and that messages still show up correctly

#3476 Fix ADS dropdown flickering

---

.github/needs_more_info.yml

Changes the message that it leaves per @yualan and enables. Right now it will only listen for the `needs repro` label, we may want to make it `needs info` and change the `needs repro` label to `needs info`.
For a list of issues that this will close atm: refer to #4209

Add needs repro closer bot

---

src/sql/parts/accountManagement/accountDialog/media/accountDialog.css

Fixes https://github.com/Microsoft/azuredatastudio/issues/4551.  It looks like something is explicitly setting monaco-list-rows to 77px.  The old height is 18px.  This seems the most targeted fix with least opportunity for side-effects.

Fix missing Azure account name

---

extensions/mssql/src/objectExplorerNodeProvider/webhdfs.ts

If we get an error from request, then the response object may be null in the request callback. So we need to check the error before trying to check the response.

Check error in webhdfs.sendRequest before trying to check response code.

---

src/sql/parts/notebook/notebookInput.ts

Now that Kernel change is refactored, I have integrated kernelChanged event with Save. Notebooks shows dirty when we change kernel. Of course, we still need to work on reverting dirty which would take some investigation.

#4365: Make notebook dirty when changing kernel

---

src/vs/platform/extensionManagement/node/extensionManagementService.ts
src/vs/workbench/parts/extensions/electron-browser/extensionsActions.ts
src/vs/workbench/parts/extensions/test/electron-browser/extensionsActions.test.ts

I introduced a couple bugs in the VS Code merge that this fixes:
1. Extensions failed to install because I wasn't returning the right metadata in one of our edits (not sure how it compiled)
2. VS Code added a bunch of pop-ups for extensions when they need to be reloaded and these should have been updated to say Azure Data Studio

Fix extension bugs from VS Code 1.31 merge

---

src/sql/platform/connection/common/connectionManagementService.ts

Fix #4554 The actual connection from the connection profile is populated with master (which is what we use as the default if none is specified). But this populates the MRU entry with a connection to master instead which can cause confusion.

Fix recent connections list to use <default> DB if no DB is specified

---

src/sql/workbench/api/node/mainThreadNotebookDocumentsAndEditors.ts

Fixes #4521. We were previously passing in a uri.fsPath as the title to NotebookInput, which includes the entire file system path. Now, we just parse the fsPath using the path library.

Only show filename for notebook titlebar when opening from Open Notebook

---

src/sql/workbench/api/node/mainThreadNotebookDocumentsAndEditors.ts

When we open and edit a note book form Dash board -> SQL Bigdata Cluster tab, right now the dirty notebook can't be closed. Reason being, we are not handling the titled notebooks from MainThreadNotebookDocumentsAndEditors. 
Created fileEditorInput for existing notebooks which is similar to CustomInputConverter. Had to plum through the code and to understand what would happen when we open a notebook from file menu Vs dashboard. One line code change though :)

#4565: Open notebook from Dashboard - can't close dirty notebook 

---

src/sql/parts/notebook/notebook.component.ts

Fixes #4559. Waiting until the notebook provider has been 100% set (after the session has started) to determine whether to add providerId-specific items to the toolbar (which currently only includes Install Packages).

Notebooks: Fix install packages not always showing on startup

---

src/sql/parts/notebook/models/notebookModel.ts
src/sql/parts/notebook/notebook.component.ts
src/sql/parts/notebook/notebookInput.ts

Notebook should be dirty when it's changed to "Trusted". Updating textEditorModel so that dirty will be taken care by model it self.Code change is very minimal as updateModel method already exists in NotebookEditorModel.

#4331: Set notebook dirty when it's changed to 'trusted'

---

extensionsGallery-insider.json
extensionsGallery.json

noticed this while looking into the telemetry. I checked the history of PG repo, Anup changed the name of extension after I added the extension to the gallery manifest. I didn't dig into the impact too much, there shouldn't be any impact for user to actually use the extension, but might cause some problem in the future when new pg extension releases.
I have updated the files in the storage account.

update pg extension name

---

src/vs/platform/extensionManagement/node/extensionGalleryService.ts
src/vs/platform/extensionManagement/node/extensionManagementService.ts

I took another look through https://github.com/Microsoft/azuredatastudio/commit/9e1f04e476f9400f04bfec72c69690c2208f7903 now that the VS Code 1.31 merge is in and reapplied the changes that got messed up as part of the merge.

Reapply extension management edits that were removed in 1.31 merge

---

src/sql/parts/notebook/notebookInput.ts

We use 'applyEdits' method from TextModel which would allow us to edit content before save. It essentially replaces the content with the given range. There was an issue in calculating the range of the content to be replaced. We are now using getLineMaxColumn to define endCloumn of the content which returns the max column of end line.

#4618: Notebook JSON has extra } after save

---

resources/linux/code-url-handler.desktop

This file got missed in a previous VS Code merge. It wasn't causing problems but now Linux packaged builds fail when they can't find it.

Bring over code-url-handler.desktop

---

build/win32/code.iss

The VS Code master merge updated our installer files to look for `LICENSE.rtf` instead of `LICENSE.txt`. I've reverted the change back to what we had before.

Go back to LICENSE.txt for Windows installers

---

src/vs/code/electron-browser/issue/issueReporterMain.ts

Due to a VS Code merge the issue reporter now has "Visual Studio Code" as the text label to file bugs against instead of "Azure Data Studio"

Fix issue reporter 'Visual Studio Code' text

---

src/sql/workbench/api/node/extHostNotebookDocumentsAndEditors.ts
src/sql/workbench/api/node/sqlExtHost.protocol.ts

Fixes #4635.
A VS Code merge redefined editorPosition in ITextEditorAddData (i.e. where it can now explicitly be undefined):
```
export interface ITextEditorAddData {
id: string;
documentUri: UriComponents;
options: IResolvedTextEditorConfiguration;
selections: ISelection[];
visibleRanges: IRange[];
editorPosition: EditorViewColumn | undefined;
}
```
in extHostDocumentsAndEditors, instead of relying solely on 
`typeConverters.ViewColumn.to(data.editorPosition)`
now that editorPosition can be undefined, we need to check for that when passing in viewColumn information into the ExtHostTextEditor constructor:
`typeof data.editorPosition === 'number' ? typeConverters.ViewColumn.to(data.editorPosition) : undefined`
Just copying over those changes from extHostDocuments* to …

Fix the "Failed to show notebook document" errors

---

src/vs/workbench/browser/parts/editor/tabsTitleControl.ts

Fixes #4657 which was a VS Code merge regression that caused tab fill color to disappear when you first started typing in a new query editor
This was happening because VS Code added some code to set the tab's color based on the theme, which sometimes happened after our code had already set the tab color. This way our code always runs last.

Fix query tab color regression

---

src/vs/platform/extensionManagement/node/extensionGalleryService.ts
src/vs/platform/extensionManagement/test/node/extensionGalleryService.test.ts

#4596 
Issue: extension search function is broken
Root cause: the search text has been changed to lower case, but when we are doing the matching we didn't  change the source to lower case.
Fix: use lower case of the target properties to match with the processed search text.
Test: Added UnitTest to cover the matching function.

fix for the extension search issue

---

src/sql/platform/telemetry/telemetry.contribution.ts
src/vs/workbench/browser/workbench.ts
src/vs/workbench/workbench.main.ts

They were removed with a VS Code merge. Changed to using extension contribution to log the telemetry to reduce the amount of VS code edits.

Add ADS Startup Telemetry events back in

---

src/sql/parts/notebook/notebookInput.ts

Now that we are passing untitledEditorInput/fileEditorInput in all the scenarios, changed confirmSave method to use input instead of leveraging TextFileService. This change won't impact the functionality, just code cleanup inline with vscode.

confirmSave using untitledEditorInput/fileEditorInput

---

src/vs/workbench/contrib/extensions/electron-browser/extensions.contribution.ts
src/vs/workbench/contrib/extensions/electron-browser/extensionsViewlet.ts

Fix #4205 We don't track installs for our extensions so the "Popular Extensions" category is just a duplicate of the full list. Removing it to reduce clutter until we can add that functionality in. This also removes the command associated with the view.

Remove popular extensions view

---

extensions/integration-tests/src/notebook.test.ts

Since we couldn't get stable cluster for pySpark end-to-end test, have to disable PySpark3 test. Otherwise insider build will be blocked.

Disable pySpark3 notebook test to unblock insider build

---

src/sql/parts/grid/services/sharedServices.ts
src/sql/parts/profiler/editor/controller/profilerTableEditor.ts
src/sql/parts/profiler/editor/profilerEditor.ts
src/sql/parts/profiler/editor/profilerInput.ts

#4648
Root cause: we escaped the strings in profiler as a result the xml cannot be displayed properly.
Fix: remove the escape call in profiler, this is safe since the underlying slickgrid already have the escaping logic.

render xml properly in the grid

---

extensions/integration-tests/src/notebook.test.ts

Disable Python 3 notebook integration test due to timeout. This is preventing publish for the insiders build.

Disable Python 3 notebook integration test due to timeout

---

src/sql/parts/notebook/notebook.css
src/sql/parts/notebook/outputs/tableRenderers.ts

Fixes #4151. Here's what it looks with this fix like with no rows returned:

Notebooks: Ensure minimum grid height set when grid returns 0 rows

---

extensions/notebook/src/jupyter/jupyterServerInstallation.ts

Was seeing some error messages print out {0} instead of the actual error message.

Use getErrorMessage to get exception messages in python installation code.

---

src/sql/workbench/services/commandLine/common/commandLineService.ts
src/sql/workbench/services/objectExplorer/common/objectExplorerService.ts
src/sqltest/parts/commandLine/commandLineService.test.ts
src/vs/workbench/browser/workbench.ts
src/vs/workbench/workbench.main.ts

This change adds status messages  during connection and invoking of the commands passed from the command line. Is 2.5 seconds a reasonable length of time to display ? The complexity of tracking item lifetime and dismissing the item based on completion of the operation didn't seem worth the minimal benefit.
I also restored code to force instantiation of the command line service which was removed by https://github.com/Microsoft/azuredatastudio/commit/ed2641ea02e7a368c40a074398265cd075ea4900
There may be a more elegant place to put the service instantiation but this unblocked the scenario for now.

Add status messages during command line processing

---

extensions/mssql/src/main.ts
extensions/notebook/src/extension.ts

Untitled counter starts from zero every time when you open a new notebook. Closed untitled notebooks will be disposed and when you open a new notebook, the count value should be - any available number from zero to max number in notebook editor.

#4511: Streamline untitled notebook count

---

src/sql/parts/notebook/models/cell.ts

This is to fix #3585. Improved the error handling by adding a message 'Query execution is canceled' when changing kernel, while execution is in progress. Please let me know the wording if something needs to be added.

#3585: Canceled message when changing kernel

---

src/sql/parts/grid/load/css/qp.css

Fixes https://github.com/Microsoft/azuredatastudio/issues/4737.  It looks like these styles are now being overridden by monaco-editor styles.  These is likely related to a recent vscode merge.

Fix query plan styles to correct rendering

---

src/sql/parts/notebook/models/cell.ts

Fixes #4450.
Since we keep track of one future per cellModel, we weren't disposing it for SQL notebooks, since the handleReply() method isn't implemented. While I could have looked into the implementation there, I like this implementation more, since we ensure that a future is properly disposed without having to wait for a reply message.

Ensure only one cell shows as running at a time

---

extensions/admin-tool-ext-win/package.json
extensions/admin-tool-ext-win/src/main.ts
extensions/admin-tool-ext-win/yarn.lock

Remove error message when activating extension on non-win platforms (instead just don't do anything).
Add hooks to kill child processes on exit if they haven't ended already. 
Switch to using nodejs exec functions directly instead of shelljs (which is just a wrapper around nodejs ones)
Formatting fixes.

Windows extension fixes/improvements

---

src/sql/base/browser/ui/panel/panel.ts
src/sql/workbench/api/node/extHostQueryEditor.ts

It looks like some of the changes I merged for extensibility are triggering these nullrefs.  I'll investigate why the code paths have changed, but these should go in first to avoid triggering exceptions.

Add Query Editor null checks

---

src/sql/base/browser/ui/scrollableSplitview/heightMap.ts
src/sql/base/browser/ui/scrollableSplitview/scrollableSplitview.ts
src/sql/parts/query/editor/gridPanel.ts

This reverts the Message Collapse behavior to match March release.  And fixes https://github.com/Microsoft/azuredatastudio/issues/4743.
@anthonydresser should we back these changes out?  Or are we planning to fix for April?  I think in general we'd like to go to a tab-interface so if it's difficult to fix I think reverting probably makes sense.

Revert Messages Collapse behavior

---

extensions/integration-tests/src/notebook.test.ts

The test would always fail if it was doing the right thing - since it was asserting that there WEREN'T any cells with outputs (the opposite of what it should have been checking).

Fix broken test

---

extensions/notebook/src/test/model/serverManager.test.ts

We no longer call showErrorMessage from the startServer method, so this assert was causing unit tests to fail.

Remove an outdated showErrorMessage assert from Jupyter Server Manager unit tests.

---

src/sql/parts/query/common/timeElapsedStatus.ts

Fixes https://github.com/Microsoft/azuredatastudio/issues/4803.  I don't know why the timers are null, but we can avoid the null ref in this method by checking before accessing.

Check for null ref in query statusbar timer

---

src/sql/parts/query/editor/charting/insights/insight.ts
src/sql/parts/query/execution/queryActions.ts
src/sql/parts/queryPlan/queryPlan.ts
src/sql/parts/taskHistory/viewlet/taskHistoryView.ts
src/sql/platform/accountManagement/browser/accountPicker.ts
src/sql/platform/dialog/dialogModal.ts
src/sql/platform/dialog/dialogPane.ts
src/sql/platform/dialog/wizardModal.ts
src/sql/workbench/parts/connection/electron-browser/connectionViewlet.ts
src/sql/workbench/parts/dataExplorer/browser/connectionViewletPanel.ts
src/sql/workbench/parts/webview/electron-browser/webViewDialog.ts
src/sql/workbench/services/errorMessage/browser/errorMessageDialog.ts

Removes builder from
- server viewlet
- query insights
- database dropdown
- query plan
- task history
- account picker
- dialog modal
- dialog pane
- wizard modal
- webview dialog
- error dialog
Most of the changes are actually pretty small since they were using builder mainly to either to utility functions or as an inital builder mechanism then transition to htmlelements.

More builder removal

---

src/sql/parts/notebook/models/cell.ts

Fixes #4842, which is a regression.

Notebooks: Fix for dispose method of undefined when running empty python cell

---

src/sql/workbench/services/commandLine/common/commandLineService.ts
src/sqltest/parts/commandLine/commandLineService.test.ts

Two issues:
#4386 
#4402 
This helps us avoid creating duplicate connections in settings.json when launching ADS from SSMS or command line directly.

Reuse existing saved connection that matches args

---

src/sql/parts/notebook/models/cell.ts

Fixes #4863. Our notebooks don't open in the Jupyter Notebook viewer without this change.

Notebooks: Always Serialize Execution Count to File

---

src/sql/azdata.proposed.d.ts
src/sql/base/browser/ui/taskbar/media/taskbar.css
src/sql/parts/modelComponents/toolbarContainer.component.ts
src/sql/parts/modelComponents/toolbarLayout.css
src/sql/workbench/api/node/extHostModelView.ts

This adds the option to add a toolbar separator after a toolbar component

Add toolbar separator

---

extensions/mssql/snippets/mssql.json

The intend for other sql snipets is used `\t`.
But this snipet is used the space. 
This PR is to change the indent same as other SQL snipets from space to `\t`.

fixed the indent for sql snipet same as other snipets

---

src/sql/azdata.proposed.d.ts

This adds the splitViewContainer and diffEditor to the ModelBuilder interface. These components were added in PR #4831

Add splitViewContainer and diffEditor to ModelBuilder interface

---

src/sql/workbench/parts/dataExplorer/browser/dataExplorer.contribution.ts
src/sql/workbench/parts/dataExplorer/browser/dataExplorerExtensionPoint.ts

Updates strings for data explorer, doesn't change anything about the extension point
Change default to collpased for extension views.

Update strings for data explorer

---

src/sqltest/parts/insights/insightsUtils.test.ts

This particular test has been failing the past couple of days, blocking insiders builds from succeeding. Adding pfs.RimRafMode.MOVE to match many other calls of pfs.rimraf() to see if the test now succeeds.
Note: I cannot repro this failure on my machine, so I am unsure if this will fix the issue; I am just using tests under src/vs/* to see how they leverage this method in their tests.

Change pfs.rimraf() call in insightsutils test due to test failure

---

extensions/notebook/src/extension.ts

Add back check for textDocuments with same name, should've been there anyhow
On rehydration files show as text docs before clicking as only get
changed by customInputConverter code path.
We should look at this long term - ideally we'd update notebookDocuments
with correct values on initial start. #4958 opened to track this.

Fix #4893 New Notebook Can Open Existing Noteboon

---

src/sql/workbench/parts/notebook/cellToggleMoreActions.ts

Fix #4930 Text cells are referred to as text and markdown in commands

---

src/sql/editor/browser/diffEditorHelper.ts
src/vs/editor/browser/widget/diffEditorWidget.ts
src/vs/editor/common/config/editorOptions.ts
src/vs/monaco.d.ts
src/vs/workbench/browser/parts/editor/textDiffEditor.ts

This changeset adds the color reversing option as an optional parameter for the diff editor. This is needed for the schema compare extension since it uses the text diff editor and needs the colors to be reversed.

Add reverse color option to text diff editor

---

src/sql/parts/modelComponents/diffeditor.component.ts
src/sql/parts/modelComponents/splitviewContainer.component.ts

Three small changes (and some formatting):
1. Add option to add title to diff editor
Example where the title is set to "Object Definitions":
2. The splitter for the SplitViewContainer wasn't showing up because the minimum size was set to the component's current height/width. This sets the minimum size to 50.
3. The component of the SplitPane wasn't getting set, so the height of the components wasn't getting set when the splitter was moved.

Add title for DiffEditor and fix SplitViewContainer

---

extensions/notebook/src/jupyter/jupyterKernel.ts
src/sql/azdata.proposed.d.ts
src/sql/workbench/api/common/sqlExtHostTypes.ts
src/sql/workbench/api/node/extHostNotebook.ts
src/sql/workbench/api/node/mainThreadNotebook.ts
src/sql/workbench/parts/notebook/models/cell.ts
src/sql/workbench/services/notebook/common/sessionManager.ts
src/sql/workbench/services/notebook/sql/sqlSessionManager.ts

This is a partial fix that lays groundwork for full "Prompt to connect" if a kernel needs a connection.
I am waiting on Yurong's refactoring of connection handling before doing any of the prompt work.
- Adds kernel metadata about whether a connection is required.
- For Jupyter, only Spark kernels are listed as requiring a connection
- If this is true and there's no active connection, will show notification and not call execute
In the future, this path will still be used if user is prompted to connect and cancels out.
The future change will be to inject a "connect" handler from notebook.component to the cell callback and use to set connection context

Mitigate (but not fully fix) Run Cell from disconnected notebook

---

extensions/integration-tests/src/notebook.test.ts

In getBdcServer(), we do the following:
```
let servers = await getTestingServers();
return servers.filter(s => s.version === '2019')[0];
```
Adding an assert that that actually returns something (so that we know we're passing something "real" into connectToServer(), and making another variable name clearer).

Add Another Assert for Notebook Test when Server Cannot Be Found

---

extensions/dacpac/src/wizard/dataTierApplicationWizard.ts

Fixing #4447. This removes the error message "Please connect to a server before using this wizard" that was showing after the connection dialog is cancelled.

Fix #4447 remove unnecessary dacpac extension error message

---

src/sql/workbench/parts/dashboard/pages/serverDashboardPage.contribution.ts

Partial fix for #4838 to get a task in the server dashboard for New Notebook. This has been brought up as a usability/discovery issue:
For the Database Dashboard, this is more problematic; the dashboard shows a horizontal scrollbar when I try to add it there, since its size is static. I'd prefer to leave that alone for now.

Add New Notebook Task from Server Dashboard

---

src/sql/workbench/parts/notebook/cellViews/codeCell.component.html
src/sql/workbench/parts/notebook/cellViews/output.component.html
src/sql/workbench/parts/notebook/cellViews/output.component.ts
src/sql/workbench/parts/notebook/cellViews/outputArea.component.html
src/sql/workbench/parts/notebook/cellViews/outputArea.component.ts
src/sql/workbench/parts/notebook/cellViews/outputArea.css
src/sql/workbench/parts/notebook/cellViews/textCell.component.html
src/sql/workbench/parts/notebook/cellViews/textCell.component.ts
src/sql/workbench/parts/notebook/cellViews/textCell.css

If no cell is active, Ctrl+A wouldn’t select anything global.
- Code cell is active
1) Mouse/cursor is in editor, Ctrl+A will select the code content.
2) Mouse/cursor is not in editor, Ctrl+A selects the output
- Markdown is active
1) In preview mode, Ctrl+A selects the text content.
2) In edit mode
	Mouse/cursor is in editor, Ctrl+A selects the text in the editor
	Mouse/cursor is not in editor, , Ctrl+A selects the text in the preview section

Fix ##3479 ctrl+a select active cell output or preview markdown

---

src/sql/base/browser/ui/table/media/table.css
src/sql/base/common/strings.ts

This change aims to fix the bug - https://github.com/Microsoft/azuredatastudio/issues/4104 : Multiple consecutive spaces in query results cells are condensed into one (like HTML)
Now it preserves all consecutive spaces in query results - all beginning, trailing and middle spaces will be shown as is.

Fix for 4104 : Multiple consecutive spaces in query results cells are condensed into one

---

extensions/mssql/src/config.json

Bump SqlToolsService version to[ 1.5.0-alpha.85 ](https://github.com/Microsoft/sqltoolsservice/releases/tag/v1.5.0-alpha.85)to get the fix for an invalid dacpac version crashing SqlToolsService

Bump SQL Tools to 1.5.0-alpha.85 to get invalid dacpac version fix

---

src/sql/platform/accounts/browser/media/accountListRenderer.css

Restores the look of the account renderer
fixes #4975

Restore account list look

---

src/sql/workbench/parts/notebook/cellViews/code.component.ts
src/sql/workbench/parts/notebook/notebookInput.ts

Fix notebook dirty on open issue:
Before model is resolved we weren't getting dirty events.
Solution is to use backing text model until it's ready.
Must hook to the dirty event & notify to get the dot to appear
Also fixes related startup issues found during debugging:
- Do not create notebook model twice on start
- Do not cause disposed warnings due to markdown cell deserialization

Fix  #4500 Untitled notebook reopen doesn't show dirty

---

src/vs/workbench/contrib/update/electron-browser/update.ts

Fix #4835 The "Release Notes" button on the update dialog runs an action that downloads an MD file of the latest release notes - but this is currently hardcoded to VS Code. 
I chatted with Alan and while we have our release notes available in MD format some extra work is going to need to be done to get it showing in a tab in ADS which is scheduled for May. But this quick fix will at least let people easily see the notes instead of browsing to it themselves manually or relying on other links. 
So instead we'll just use the action to open the release notes in the browser which uses the releaseNotesUrl we define for our product so correctly goes to the ADS release notes URL.

Fix wrong release notes being loaded

---

src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts

Fix #4910 The when clause wasn't set up correctly - you need to use the classes like ContextKeyDefinedExpr to build up the expressions. Previously they would show up for all nodes in the tree, with this change it's scoped down to just being on the Server and Database nodes.
Note that I purposely left out Manage from DBs under Server nodes because of #4994 which means they'll always use the first connection you use to connect to the Dashboard and so you'll never be able to view the dashboards for other DBs.

Fix Data Explorer context menu items visibility

---

src/sql/parts/modelComponents/tree/treeComponent.css
src/sql/parts/modelComponents/tree/treeComponentRenderer.ts

This is fix for the bug: https://github.com/Microsoft/azuredatastudio/issues/5021
The string value of `DIV` element with  `model-view-tree-node-item-label` class overflows if its container size is smaller than the string length, and this makes the tree node icon disappears.
This PR fixes the issue.
After fix:

Fixed bug: CheckboxTreeNode label overflows, and node icon disappears

---

src/sql/parts/query/editor/charting/chartView.ts

fix for issue: #5039 - after recent vscode merge, the select box is expecting a new type as options instead of an array of strings, our own selectbox which derived from vs selectbox can handle this properly, I changed the chart view to use our own selectbox. I also double checked other references to the vs selectbox, there are 2 places: backup/restore and listview component, they are both handling that properly right now.
fix for issue: #5051 - the theme change event for this control has been disposed incorrectly, the fix is not to dispose the event for the chart type control when rebuilding the options

fix the selectbox issue for chart

---

src/sql/base/browser/ui/table/media/table.css

There was a regression where the text on header filters weren't themed right for text.
Before -
After -

Fixed agent filter in dark theme

---

src/sql/workbench/parts/notebook/notebook.component.ts

Fixes #4969. Instead of waiting for the session to start, only show the loading spinner when the model isn't created with cell information.
This is in relation to feedback that we got around the loading spinner being redundant when the kernel/attach to dropdown showed "loading" and cells being rendered.

Only show nb loading spinner when no cells shown

---

src/sql/workbench/parts/notebook/cellViews/textCell.css
src/sql/workbench/parts/notebook/notebookStyles.ts

Notebooks: Improve table markdown css

---

src/sql/azdata.proposed.d.ts

This fixes an issue where if you copy azdata.proposed.d.ts to
an extension project, it would fail to compile using default
tsconfig.json settings due to missing return type

Typings reference failing in external extension

---

extensions/notebook/src/common/apiWrapper.ts
extensions/notebook/src/jupyter/jupyterServerInstallation.ts

Also fixed a bug where future installs would get blocked after doing an install that gets skipped.

Show an Install Skipped message when Python already exists at the specified install location.

---

azure-pipelines-linux-mac.yml
azure-pipelines-windows.yml
src/sqltest/parts/jobManagement/jobActions.test.ts
src/sqltest/stubs/jobsManagementViewStub.ts

Switched on code coverage for `sql` directory for every PR build with test results published in the end.

Switch on code coverage

---

src/vs/workbench/contrib/update/electron-browser/update.ts

Fix #5105 #2386 Show Release Notes command was using the VS Code showReleaseNotes code for displaying the notes in a new window - but this is currently hardcoded to always show VS Code release notes. Until we can update that code to download our release notes and show those instead changing the command action to just open the release notes in the browser (which uses the correct URL specified in our config).
Note that while I would have preferred to change the contribution to use the OpenLatestReleaseNotesInBrowserAction instead that action doesn't have the correct constructor to directly replace the ShowCurrentReleaseNotesAction and so to minimize changes I instead changed that action to just run the OpenLatestReleaseNotesInBrowserAction.

Show correct release notes for command

---

src/sql/workbench/services/notebook/sql/sqlSessionManager.ts

Only when the connection is connected, then do disconnect.

Only when the connection is connected, then do disconnect.

---

src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts

Fix casing on welcome page to be consistent

---

extensions/notebook/package.json
src/sql/platform/connection/common/utils.ts
src/sql/workbench/parts/connection/common/connectionContextKey.ts
src/sql/workbench/parts/dashboard/dashboardEditor.ts
src/sql/workbench/parts/dataExplorer/common/nodeContext.ts
src/sql/workbench/parts/objectExplorer/browser/serverTreeActionProvider.ts

#5087 I picked this one since it is related to extensibility.
1. Enable 'New Notebook' context menu for PG server node - introduced a new context for server node: isQueryProvider, notebook should be only available for query providers.
2. Enable 'New Notebook' task for PG dashboard, the issue was when opening server dashboard, we are already been directed to the database dashboard because we have a logic built in to decide whether a connection is server connection, for now I have fixed the particular issue and opened a github issue for permanently fix it.

enable 'New Notebook' entry points for PG SQL

---

extensions/notebook/src/extension.ts

vscode.window.showErrorMessage takes string not error. Pass in err.message.

Fixed #5210

---

extensions/dacpac/src/wizard/api/dacFxConfigPage.ts
extensions/dacpac/src/wizard/pages/deployActionPage.ts
extensions/dacpac/src/wizard/pages/deployConfigPage.ts
extensions/dacpac/src/wizard/pages/exportConfigPage.ts
extensions/dacpac/src/wizard/pages/extractConfigPage.ts
extensions/dacpac/src/wizard/pages/importConfigPage.ts
extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
extensions/schema-compare/src/schemaCompareResult.ts

This changes the default folder in the dacpac and schema compare extensions to be the root path opened in the file explorer if a folder is open, otherwise the default is the user's home folder. 
Fixes  #4457

Change default folder in dacpac and schema compare extensions

---

src/sql/workbench/parts/notebook/models/cell.ts

Fixed #4813
There are two issues:
1) getKnoxEndpoint provider match fails because it was lower case before, so it wouldn't get the correct endpoint.
2) driverLog uri match patter is changed.

Fix driverlog uri in output

---

src/vs/workbench/api/node/extHostExtensionService.ts

This PR forces MSSQL extension to load first during eager load phase to prevent other extensions from causing delays during startup.  It still seems like there is a some delay between `activate` and when the SQL Tools Services launches, but I think that optimization will need to be in the Service Loader component.  While this doesn't seem to make a huge difference I don't see a downside to the change other than further special-casing MSSQL.

Load MSSQL extension first during eager load phase

---

src/sql/workbench/parts/notebook/cellViews/textCell.component.ts

- Copied over click handler from VSCode markdown renderer
- Added logic to only support command links if trusted
Now clicking on a link will do an action or open a file.
Created #5238 to track need to support relative links which doesn't work

Fix #3440 link in Markdown requires cmd+click

---

src/sql/workbench/common/workspaceActions.ts

Fix #5177 - File path wasn't being parsed correctly, URI.file should be used for full file paths.

Fix "Open File Location" for CSV Export

---

extensions/schema-compare/src/schemaCompareResult.ts

The icon for options for dark theme wasn't showing because the path was incorrect:
This is how the dark theme icon looks:

Fix path to dark icon of schema compare options button

---

extensions/notebook/src/common/ports.ts
extensions/notebook/src/jupyter/serverInstance.ts
extensions/notebook/src/test/common/port.test.ts
src/sql/workbench/api/node/extHostNotebook.ts

More hardening around Jupyter server:
- Do not always start at port 8888 (can cause 403 issues in rare cases [should be extremely rare now after last batch of fixes])
- Only log errors around killing the jupyter process when an exception isn't expected: http://pubs.opengroup.org/onlinepubs/9699919799/functions/kill.html [ESRCH]
No process or process group can be found corresponding to that specified by pid.
This means that #4822 should be extremely unlikely to happen, if the current understanding is correct.

Notebooks: More Jupyter Server Hardening

---

extensions/schema-compare/src/schemaCompareResult.ts

This fixes the "Object Definitions" title disappearing after clicking the "Switch direction" button. The problem was that the title wasn't getting set when updating the properties of the diff editor. Also removing an unnecessary line of code left behind.
"Object Definitions" title missing after switching source and target:

Fix "Object Definitions" title disappearing after switching source and target

---

extensions/integration-tests/src/objectExplorer.test.ts
src/sql/workbench/api/node/extHostConnectionManagement.ts
src/sql/workbench/api/node/mainThreadConnectionManagement.ts

#4908 changed the default behavior for connect - previously it would save the connection by default but after the change the default was not to save the connection. Reverting back to having the connection saved by default since that should be the normal case. 
Also fixed ordering of context menu items which have changed with latest SSMS Integration extension changes

Fix failing OE Tests caused by changes in connection API defaults

---

extensions/cms/package.json
extensions/cms/package.nls.json
extensions/cms/src/apiWrapper.ts
extensions/cms/src/cmsResource/tree/cmsResourceEmptyTreeNode.ts
extensions/cms/src/test/cmsResource/tree/cmsResourceEmptyTreeNode.test.ts

Some commands were using CMS and some were using Cms - commands are case-sensitive so this was causing some functionality (such as clicking the + symbol on CMS tree) to not function. 
I've updated the commands and other labels as appropriate to all use Cms to be consistent across the extension.

Fix broken CMS commands

---

src/sql/base/browser/ui/scrollableSplitview/scrollableSplitview.ts
src/sql/base/browser/ui/table/media/slickColorTheme.css
src/sql/platform/query/common/queryRunner.ts
src/sql/workbench/parts/query/browser/queryResultsView.ts
src/sql/workbench/parts/query/electron-browser/gridPanel.ts

This address various grid scrolling issues associated with https://github.com/Microsoft/azuredatastudio/issues/5250.  Specifically, the following.
1. Fix bug in heightmap where `top` is incorrect causing resultset grids not to render when there are multiple results
2. Avoid having double-scrollbars when there is only 1 grid
3. Fire resize events so horizontal scroll doesn't get inaccessible behind messages
4. Make horizontal scrollbar a little taller
5. Better initial proportions between messages and resultgrid

Various results grid scrolling fixes

---

src/sql/workbench/electron-browser/modelComponents/queryTextEditor.ts

Improvements to notebook editor code auto height

---

src/sql/platform/connection/common/connectionProfile.ts

I hit the below exception and from code inspection it looks like VS Code's method doesn't work correctly if both string are null.  I'd prefer not to patch VS Code source so I'll fix at the point of the exception in this case.
```TypeScript
D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280 Unhandled Promise rejection: Cannot read property 'length' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'length' of undefined
at doEqualsIgnoreCase (file:///D:/xplat/azuredatastudio/out/vs/base/common/strings.js:338:50)
at Object.equalsIgnoreCase (file:///D:/xplat/azuredatastudio/out/vs/base/common/strings.js:335:16)
at ConnectionProfile.matches (file:///D:/xplat/azuredatastudio/out/sql/platform/connection/common/.js:39:30)
at …
```

Fix nullref exception in connection profile

---

src/sql/workbench/services/connection/browser/connectionDialogService.ts

Fix #5325 - the recent change to reduce MRU connections resulted in query editor connections not being saved. The fix here means that the connection will be saved to the connection store as well - but I've verified that it doesn't show up in OE or *Saved Connections*, it just adds it to the MRU.
This also doesn't impact changing the database in the dropdown - that still correctly doesn't add the connection to the MRU or saved connections.

Fix connections from editor not saving to MRU

---

extensions/dacpac/src/wizard/api/basePage.ts
extensions/schema-compare/src/dialogs/schemaCompareDialog.ts

This removes the database name from the source and target server field in the schema compare dialog
old:
new:

Remove database name from schema compare source/target server field

---

src/sql/base/browser/ui/table/table.ts
src/typings/globals/slickgrid/index.d.ts

This should fix this in schema compare as well assuming they are using the default options.
fixes #5332

Disable page scrolling in slickgrid

---

extensions/admin-tool-ext-win/src/main.ts
extensions/admin-tool-ext-win/src/test/utils.test.ts

- Display more errors to users to make it clear when the dialog is unable to be launched
- Add fetching of passwords to pass to SsmsMin for SQL Login connections
- Disallow launching from disconnected or Azure nodes (gap in API and dialog support)

SsmsMin integration clean-up and improvements

---

extensions/schema-compare/src/dialogs/schemaCompareDialog.ts

This changes the schema compare dialog to group the source and target components more clearly.
Old:
New:

Fix schema compare dialog spacing

---

extensions/integration-tests/src/objectExplorer.test.ts
extensions/schema-compare/src/dialogs/schemaCompareDialog.ts

This fixes #5314 the schema compare dialog not always opening with the correct default connection if there are multiple connections.
Previously, the server dropdown in the dialog would have the first server be the default value. This fixes that by setting the server dropdown value to the current connection's server if there is a connection.

Fix #5314: schema compare doesn't always open with correct default connection

---

extensions/schema-compare/src/dialogs/schemaCompareDialog.ts

This sets the font size of the title labels in the schema compare dialog to 13px to be consistent. Also fixing the ordering of the source dialog components since the indexes changed after formComponentGroups were added in this PR #5329
old:
new:

Fix schema compare dialog font sizes

---

extensions/azurecore/package.json
extensions/azurecore/src/account-provider/azureAccountProvider.ts
extensions/azurecore/src/test/azureResource/providers/database/databaseTreeDataProvider.test.ts
extensions/azurecore/src/test/azureResource/providers/databaseServer/databaseServerTreeDataProvider.test.ts
extensions/azurecore/tsconfig.json
extensions/azurecore/yarn.lock
src/sql/azdata.proposed.d.ts
src/sql/workbench/api/node/extHostAccountManagement.ts
src/sql/workbench/api/node/mainThreadAccountManagement.ts
src/sql/workbench/api/node/sqlExtHost.protocol.ts
src/sql/workbench/services/accountManagement/browser/accountManagementService.ts
src/sqltest/services/accountManagement/accountManagementService.test.ts

VSCode serialization changed rejection handling to only serialize errors, which caused things to break
- Changed to return either account info or a cancel message in the resolve
- Rewrote to use promises. Tracking how to return canceled through 4+ thenables was way trickier than just using a promise
- Updated unit tests to handle new scenario
- Tested integration tests, realized they a) didn't run and b) didn't passed. 
- Added vscode dev dependency to fix run issue
- Fixed tests to account for behavior changes in tree state.

Fix #4089 Linked account cancel

---

src/sql/workbench/parts/notebook/cellViews/code.component.ts
src/sql/workbench/parts/notebook/cellViews/textCell.component.ts

This is a demo blocker. Stop scrolling to the very top of a code cell when clicking the run button. Ruins demo flows if the notebook is constantly jumping all over the place.
For the run all cells scenario, we still scroll with this change.

Notebooks: Don't scroll when running code cell if in view

---

src/sql/workbench/parts/profiler/browser/profilerTableEditor.ts

#5350 
for some reason, the formatter for the columns got lost during tab switch when multiple profiler windows are opened, I haven't investigated into how the regression was introduced. The changes in this PR will enforce the columns get the correct formatter.

fix profiler formatter issue

---

src/sql/platform/query/common/queryRunner.ts
src/sql/workbench/parts/query/browser/messagePanel.ts
src/sql/workbench/services/notebook/sql/sqlSessionManager.ts

Fixes the messages output of notebooks to be what it was before.

Update notebooks to use new message event

---

extensions/notebook/src/test/common/port.test.ts

There was recently a change in how we calculate valid notebook ports, and instead of relying on a hardcoded starting value (which causes tons of issues in rare cases when Jupyter server doesn't shutdown correctly), we instead choose a random port in a range. This test was flakey because sometimes, with the new behavior, we would choose a port that's < 7100 some small % of the time, causing the assert to fail. Just running the test enough times on my machine I was able to eventually repro the issue.
This should unblock the insider build, we will look at timeouts separately, as I'm unsure why setting timeouts isn't working as we expect.

Notebook Port Test Fix

---

src/sql/workbench/parts/query/electron-browser/gridPanel.ts

Avoid unnecessary scrollbar by adjust some height calculations.  For example, below there is no need for vertical scrollbar since there is a ton of extra vertical space, but the messages can't be made smaller.

Adjust estimated scrollbar height to avoid unneeded scrollbar

---

build/lib/extensions.js
build/lib/extensions.ts

This is part of the effort to make the pipeline produce the extension installers. in this PR I am trying to address the issue that the current visx file naming doesn't include the version information. I've also made changes to a clone of pipeline definition to copy the vsix files to the drop folder, once this PR is merged, I will update the windows pipeline definition and vsix files can be found here:

produce the vsix files during windows build

---

extensions/dacpac/package.json
extensions/integration-tests/src/objectExplorer.test.ts

This adds the Data-tier Application wizard to the context menus of servers and database folders, fixing #4460.

Fix #4460: Add dacfx wizard to server and database folder context menus

---

extensions/mssql/src/objectExplorerNodeProvider/hdfsCommands.ts

Enable stricter compile options on extensions #5044 regressed this, which missed mkdir call.

Fixed #5463 missing mkdir call function

---

src/sql/base/browser/ui/listBox/listBox.ts

Fixing list box in backup dialog to allow selection of file and and not show dropdown at click. This PR fixes bug- #1777 
We might also need overall refracting for list box component but doesn't seem to be in scope for this bug.

Bug fix Backup dialog list box to allow selecting file

---

extensions/dacpac/.gitignore
extensions/dacpac/.vscodeignore
extensions/dacpac/coverageConfig.json
extensions/dacpac/package.json
extensions/dacpac/src/test/dacpac.test.ts
extensions/dacpac/src/test/index.ts
extensions/dacpac/src/wizard/api/dacFxConfigPage.ts
extensions/dacpac/src/wizard/api/utils.ts
extensions/dacpac/src/wizard/pages/deployActionPage.ts
extensions/dacpac/yarn.lock
scripts/test-extensions-unit.bat
scripts/test-extensions-unit.sh

Database names can have characters that are invalid in filenames, so this replaces those invalid characters with an underscore. For example, in|valid*<db?name would become in_valid__db_name. This also adds a few unit tests to test this function.
Fixes #5216

Sanitize db name for dacpac/bacpac file names

---

src/sql/platform/query/common/queryManagement.ts
src/sql/platform/query/common/queryRunner.ts
src/sql/platform/telemetry/telemetryKeys.ts

Keyboard shortcuts now fire the same events the standard query execution events are firing which corrects an issue with the results panel.
This fix will allow keyboard shortcuts to execute procedures or SQL statements without the results pane cluttering up with incomplete meta data. The previous executed results headers would not clear, the new data would fill into those columns, and the new headers would appear below the completed set.
Should fix #4704 .

Corrected Keyboard Shortcut Execution Issue

---

scripts/sql-test-integration.bat

There were a bunch of these folders on the build machine that caused it to run out of disk space - we should always delete these even if the test failed.

Fix test cleanup to remove folders regardless if tests passed or failed

---

src/sql/workbench/api/node/extHostModelViewDialog.ts

`UpdateWizardPageInfo()` in `extHostModelViewDialog` has been using `Wizard` handle where `WizardPage` handle is supposed to be used.

Fixed bug: wrong handle usage in updateWizardPageInfo() in extHostModelViewDialog

---

azure-pipelines-windows.yml
package.json

This is just for the core tests right now (no extensions)
https://coveralls.io/github/microsoft/azuredatastudio

Add pipeline task to push coverage results to coveralls

---

extensions/mssql/src/config.json
extensions/schema-compare/src/schemaCompareResult.ts

Fix #5419. This fixes the formatting problems below. Adding 'GO' after statements and blank lines at the beginning were fixed in SqlToolsService and are in version 1.5.0-alpha.93.
**Blank lines no longer showing as difference:**
old:
fixed:
**No more blank lines at the beginning of some scripts:**
old:
fixed:
**Each statement now starts on its own line:**
old:
fixed:

Fix schema compare diff script formatting

---

extensions/schema-compare/src/dialogs/schemaCompareOptionsDialog.ts

Fix for : https://github.com/microsoft/azuredatastudio/issues/5272 
Adding reset button in schema compare options dialog

Adding reset for options dialog

---

extensions/schema-compare/src/schemaCompareResult.ts

This sets the generated script file path to the last folder opened in the file dialog. Previously it would default to the root path open in file explorer.

Change schema compare generated script filepath

---

extensions/admin-tool-ext-win/package.json
extensions/admin-tool-ext-win/src/main.ts
extensions/admin-tool-ext-win/src/test/utils.test.ts

- Update extension menu when clauses so that the items are only shown for connected nodes (currently nodes need to be connected to launch the dialogs)
- Also hide server properties for Azure servers (Azure servers aren't supported by server properties dialog)
- Add status bar item for feedback that a dialog is being launched since it can take a while to show up
- Fix server name in URN for Azure servers - those require using the "true name" which is everything but the .database.windows.net. This doesn't handle other clouds but I need to look more into how to solve that problem, for now this will solve the majority of the cases.

Fixes/improvements for SsmsMin extension

---

extensions/schema-compare/src/schemaCompareResult.ts
src/sql/azdata.proposed.d.ts
src/sql/workbench/electron-browser/modelComponents/text.component.ts

This changeset lets the css style now be specified for the text component. The text component used to use the user agent stylesheet for the css for p
before with the default css margins:
after specifying margin-bottom: 0px

Add CSSStyles for text component

---

build/win32/code.iss

Update installer warning to refer to ADS instead of VS Code

---

extensions/notebook/src/integrationTest/notebookIntegration.test.ts

The Existing Python Install test updates the user settings after completion, but later notebook tests manually update the python path user setting without changing the useExistingPython setting. This caused the tests to be unable to find the python install. The easiest change here seemed to be to revert the user settings changes after running the existing python test.

Revert user settings changes after running Existing Python Install integration test.

---

extensions/schema-compare/src/dialogs/schemaCompareDialog.ts

This makes two changes to the schema compare dialog server dropdown:
1. Remove duplicate server connections #5445
2. Sort the dropdown values so that the most recent connections are at the top

Schema compare server dropdown changes

---

extensions/mssql/src/config.json
extensions/mssql/src/contracts.ts
extensions/mssql/src/features.ts
extensions/schema-compare/src/schemaCompareResult.ts
src/sql/azdata.proposed.d.ts
src/sql/platform/schemaCompare/common/schemaCompareService.ts
src/sql/workbench/api/node/mainThreadDataProtocol.ts
src/sql/workbench/api/node/sqlExtHost.protocol.ts

This changes the behavior of schema compare generate script to open the script as a temp file instead of saving it after prompting for a file name. Fixes #5284
The change to actually open the script is in SqlToolsService in this PR: https://github.com/microsoft/sqltoolsservice/pull/813. I'll bump the version here after that gets checked in.

Open schema compare script

---

extensions/schema-compare/src/dialogs/schemaCompareDialog.ts

Keep Schema compare dialog Okay button disabled when dialog opens. 
Enable when source/ target are selected as either 1) database or 2) existing dacpac file
tracking issue : https://github.com/microsoft/azuredatastudio/issues/5481

DisableSchema compare dialog's Okay button if source/target isn't selected

---

src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts

Fixes #5371 Restore dialog checkBoxes not visible 
Reason: table cells now preserve white spaces in table which causes checkbox template to be dislocated (https://github.com/microsoft/azuredatastudio/pull/4983)
Fix: remove extra white spaces
(Please suggest if you think the original bug should be fixed in a different way. )

Fixing column plugin to not have extra whitespaces

---

extensions/dacpac/src/wizard/api/dacFxConfigPage.ts

The DacFx wizard extract and export pages were failing to load when launched from the command palette or if the database name was unset in a the deploy page before going to the extract or export pages. The problem was that it was trying to sanitize the database name to generate a default filename, but it was failing when the database was not set.
Fixes #5566.

Fix #5566 DacFx extract/export pages not loading from command palette 

---

src/sql/platform/query/common/queryRunner.ts

Fixes #5478 
Before :
After : 
Note that this is a fix for displaying errors that occurred in the Tools Service layer - it looks like it's failing to parse the code correctly before sending it to the server. Normal SQL syntax errors were already displayed correctly like this :

Fix error callback to display error message instead of {1}

---

extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
src/sql/workbench/electron-browser/modelComponents/formContainer.component.ts
src/sql/workbench/electron-browser/modelComponents/media/formLayout.css

This change widens the dropdowns and textboxes in the schema compare dialog so there isn't so much blank space in the dialog. Also setting the min-width for the title labels to match the look of the connection pane.
Old:
New:

Widen schema compare dialog dropdowns and textboxes

---

extensions/schema-compare/src/dialogs/schemaCompareDialog.ts

The correct default server was not always being chosen when there were multiple connections due to the list of connections getting reversed in this changeset #5552. This fixes that by reversing the list of connections before finding the index of the current connection.

Fix schema compare default server not always being chosen

---

src/sql/platform/connection/common/connectionManagement.ts
src/sql/platform/connection/common/connectionManagementService.ts
src/sql/platform/connection/common/connectionProfile.ts
src/sql/platform/connection/common/connectionStore.ts
src/sql/workbench/parts/objectExplorer/browser/connectionTreeAction.ts
src/sql/workbench/parts/objectExplorer/common/objectExplorerViewTreeShim.ts
src/sql/workbench/services/connection/browser/connectionDialogService.ts
src/sql/workbench/services/connection/common/connectionDialogService.ts
src/sqltest/parts/connection/connectionManagementService.test.ts
src/sqltest/parts/connection/connectionTreeActions.test.ts
src/sqltest/parts/notebook/model/notebookUtils.test.ts
src/sqltest/parts/query/editor/queryActions.test.ts
src/sqltest/stubs/capabilitiesTestService.ts
src/sqltest/stubs/connectionDialogTestService.ts
src/sqltest/stubs/connectionManagementService.test.ts

Adds the necessary changes to enable the data explorer to utilize the connect method which gets the connection dialog and firewall rule perks.

Allow data explorer to use connect

---

extensions/schema-compare/src/schemaCompareResult.ts

This removes the double scrollbar by setting the overflow of the splitview container to hidden.
Before with double scroll bar:
Now:

Get rid of schema compare double scrollbar

---

src/sql/workbench/parts/query/browser/queryEditor.ts

query editor sub editors were being disposed more than once.

Fix editors being disposed multiple times

---

extensions/schema-compare/src/dialogs/schemaCompareOptionsDialog.ts

Options dialog shows two scroll bar - using vh to fit the elements to window better. Using % didn't work.
(Not sure if this fixes the problem all resolutions but fixes for laptop/desktop window resigning)
**Before** 
**After**
Tracking as part of issue #5481

Fix for Schema compare Options dialog double scroll

---

extensions/admin-tool-ext-win/src/utils.ts
extensions/import/src/services/serviceUtils.ts
extensions/import/src/services/telemetry.ts
extensions/mssql/src/telemetry.ts

Also removing extra metadata - userId as it was implemented is mostly useless since it gets regenerated each time ADS is launched and distribution is already included by ApplicationInsights.

Fix extensions to swallow exceptions when sending telemetry

---

extensions/admin-tool-ext-win/package.json
extensions/cms/package.json
extensions/dacpac/package.json

sqlops is no longer recognized and will be ignored, update the with azdata in case we need to restrict the ADS versions for these extensions.

update engine name from sqlops to azdata

---

src/vs/workbench/workbench.main.ts

Until we test/decide we want this we should disable the remote feature

Disable remote contribution

---

src/sql/workbench/electron-browser/modelComponents/media/formLayout.css

This fixes the widths of the dropdowns and textboxes sometimes changing when the radio buttons are clicked

Fix schema compare dialog widths changing

---

src/sql/workbench/electron-browser/modelComponents/modelViewEditor.ts

With the recent change to respect custom settings for title bar style  - the model view editor was getting extra top space. Which in turn causes issue with schema compare rendering. Adding this is a quick fix for model view editor to work in both custom and native window settings. 
Before fix
After fix

Fixing model view editor to layout correctly with native and custom setting

---

src/sql/workbench/parts/jobManagement/electron-browser/alertsView.component.ts
src/sql/workbench/parts/jobManagement/electron-browser/jobManagementView.ts
src/sql/workbench/parts/jobManagement/electron-browser/jobsView.component.ts
src/sql/workbench/parts/jobManagement/electron-browser/operatorsView.component.ts
src/sql/workbench/parts/jobManagement/electron-browser/proxiesView.component.ts

Fixes #5637 At some point the event type changed so this broke. Updating to new type of anchor. Also minor cleanup on the getTableActions functions.

Fix agent context menu to appear in correct location

---

src/sql/base/browser/ui/panel/panel.ts
src/sql/platform/dialog/dialogPane.ts
src/sql/workbench/parts/charts/browser/chartView.ts
src/sql/workbench/parts/profiler/browser/profilerEditor.ts
src/sql/workbench/parts/query/browser/messagePanel.ts
src/sql/workbench/parts/query/browser/queryEditor.ts
src/sql/workbench/parts/query/browser/queryResultsView.ts
src/sql/workbench/parts/query/electron-browser/gridPanel.ts
src/sql/workbench/parts/query/modelViewTab/queryModelViewTab.ts
src/sql/workbench/parts/queryPlan/browser/topOperations.ts
src/sql/workbench/parts/queryPlan/electron-browser/queryPlan.ts
src/sql/workbench/parts/restore/browser/restoreDialog.ts
src/sql/workbench/services/connection/browser/connectionDialogWidget.ts

adds focus logic to the tabbed panel that will transfer focus to the correct tab
also changes the min sizes for the query editor components to zero
fixes #5645
fixes #5643

Add focus logic to the tabbed panel

---

src/sql/platform/connection/common/connectionManagementService.ts
src/sqltest/parts/connection/connectionManagementService.test.ts

This PR makes connection icon to be remembered by memento in ConnectionManagementService so that connections can be rendered with correct icon after ADS execution.

Made connection icon to be remembered by memento in ConnectionManagementService

---

extensions/schema-compare/src/dialogs/schemaCompareOptionsDialog.ts
extensions/schema-compare/src/schemaCompareResult.ts

With this change, the message "Options have changed. Press Compare to see the comparison." will show if any options were changed to notify the user to recompare. 
Updated look:

Show message to recompare when schema compare options change

---

src/sql/workbench/parts/query/browser/queryEditor.ts

Fixes #5684 
This behavior was broken by the editor refactor cf8f890 - previously we were rebuilding the Editor each time based on the type of the QueryEditorInput, so when the input was a FileEditorInput we'd be given a TextFileEditor. The refactor changed the editor to always be a TextResourceEditor - which doesn't allow editing of anything but Untitled inputs.
The fix is to create two editors and swap between them as necessary as the input changes.

Fix query files not being editable

---

src/sql/workbench/parts/query/browser/queryEditor.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/5705.
Here's an example of a default split with this change.

Provide a default result grid height

---

src/sql/platform/theme/common/colors.ts
src/sql/workbench/parts/query/browser/media/messagePanel.css
src/sql/workbench/parts/query/browser/messagePanel.ts

Adds a customizable color for messages error.
The default color is still red for all themes, I'll work with ux to get a good color for our built in themes.
Also fixed the line height logic.
Fixes #5747

Add customizable error color; fix line height in Messages

---

src/sql/workbench/browser/modal/modal.ts
src/sql/workbench/services/insights/browser/insightsDialogView.ts

Fixes #5401 
Insights dialog was reusing custom buttons added in first render (since modal html element preserves the footer buttons) but the OnDidClick function for these returned buttons wasn't coming correctly from previous iteration - removing and recreating footer button solves this issues.

Backup to open correctly from insights dialog

---

src/sql/workbench/parts/query/common/resultsGridContribution.ts

This change makes it so searching messages shows the results grid settings, helping in discoverability.
Changing the actual name of the settings would break back compat so I'm not sure how important this is.

Add messages to title to help discoverability

---

src/sql/workbench/parts/query/common/queryInput.ts

Fixes #5728 (the disconnected title staying active)
The refactor to make this more state based removed the firing of this event. While we now have the EventEmitter for the state being set to connected the _onDidChangeLabel emitter is part of the base VS EditorInput so we should still be calling that if the title is ever updated (in addition to the new state emitter)
Also added fix for disconnect not updating the title. This was actually not a regression - but it's not expected behavior regardless.

Fix editor title not updating after connect

---

extensions/schema-compare/src/schemaCompareResult.ts

This disables the generate script and apply buttons after applying changes because the results are not valid anymore. The tooltip of these two buttons is then changed to "Press Compare to refresh the comparison" to explain why they are disabled.
Fixes #5727.

Disable schema compare generate script and apply buttons after applying changes

---

src/sql/workbench/common/actions.ts

Fixes : #5628 
This PR contains 
1. Show _not supported_ messages for backup and restore if opened from command pallet for an azure db
2. Adding profile creation if not present for restore (same as backup) for robustness
3. reordering some code to reduce unnecessary calls.

show not supported message for backup for Azure

---

src/vs/workbench/common/editor/editorGroup.ts

Fixes : #4051 
Generated scripts in Temp folder will not try to open in next ADS session if the files do not have any change.

Do not add generated files from Temp if file is not dirty

---

src/sql/workbench/parts/notebook/notebookActions.ts
src/sql/workbench/services/notebook/common/notebookServiceImpl.ts

- Notebooks Can be Improperly Trusted After Save + Reopen
Fix was to only save if actually trusted.
Also fixed condition where it wasn't correctly skipping if in the queue

Fix #5765 Trusted state handling

---

extensions/notebook/src/common/constants.ts

Changed output channel name from 'Jupyter Notebooks' to 'Notebooks'
This is how it finally looks:

Changed output channel name from 'Jupyter Notebooks' to 'Notebooks'

---

src/sql/workbench/parts/query/browser/queryResultsView.ts

This will move focus to messages on error even if the user is doing something in the results grid (consistent with ssms)

Focus messages on error

---

src/sql/workbench/electron-browser/modelComponents/diffeditor.component.ts
src/vs/workbench/browser/parts/editor/textDiffEditor.ts

The diff view was editable but it should be diff only. This can be misleading since making changes in the diff editor won't be applied. Fixes #5702
previously:
Fixed:

Fix #5702 Schema Compare Diff is editable

---

src/sql/workbench/parts/objectExplorer/common/objectExplorerViewTreeShim.ts

- Azure token wasn't being copied into profile so expand didn't work, it spun forever
- Fixed this by saving in password/token after the connection profile copy, & refactored to be cleaner
- We should ideally ensure session notifies resolves even on fail so if there's a different error it'll break, not spin forever. Punting this part of the fix for now
- Also doesn't solve issue where we always try to connect even if user + password combo isn't saved. Will investigate / work in a separate PR on this.

Fix #4976 AAD Login will not work from Azure

---

src/sql/workbench/parts/query/browser/queryResultsView.ts

iterating on #5791
Only focus message on error when the query completes, this how ssms behaves.

Change message focus to only on query end

---

src/sql/workbench/parts/query/browser/queryEditor.ts
src/sql/workbench/parts/query/browser/queryResultsView.ts

Pretty high pri issue.
If you open up editors side by side, running a query in the second would cause the results to show up in both. There were a couple of these issues with more editors. This fixes the main issue.

Fix instances of listeners not being disposed in Query Editor

---

src/sql/workbench/parts/notebook/models/clientSession.ts

Fixes #5541. Simple check to see if notebookManager and notebookManager.sessionManager both exist before calling shutdown of the previous session.

Fix Issue when SessionManager is Undefined in Rare Cases

---

extensions/notebook/package.json
extensions/notebook/src/dialog/configurePythonDialog.ts
extensions/notebook/src/dialog/pythonPathLookup.ts
extensions/notebook/src/jupyter/jupyterServerInstallation.ts
extensions/notebook/yarn.lock
extensions/schema-compare/src/schemaCompareResult.ts

The detection logic here is imported from the vscode-python extension for the most part. Anaconda installs are detected using a regex search for common install locations. Python installs are detected by fetching the version info from whatever python versions are present in PATH. A small downside of this change is that the Install Location field in the dialog is no longer directly editable, since we include version info as part of the entries for better clarity. The Browse button still works as expected, though.
I also made some small improvements to error handling in the actual install code. Some code would still run after a reject call, since there weren't any return statements. For example, a python download could continue in the background even if the process couldn't access the …

Automatically detect existing Python/Conda installs in Configure Python dialog.

---

src/sql/workbench/parts/notebook/outputs/tableRenderers.ts

This is for fixing bug: https://github.com/microsoft/azuredatastudio/issues/5836
It was because we did not count border pixels for the rows.
We need to add 1 pixel for each rows bottom border.
This code change fixes that.
Before fix:
After fix:

Fixed bug: Notebooks Vertical Scrollbar is Unnecessary for Some Grid Outputs

---

extensions/admin-tool-ext-win/license/Visual Studio Redist.txt

This isn't necessary since we aren't providing the VS binaries as redist-able. VS has signed off as confirming that the main extension license is enough to cover the VS binaries as well.

Remove VS redist license

---

src/sql/workbench/parts/notebook/cellViews/output.component.ts

This resolves https://github.com/microsoft/azuredatastudio/issues/5770
This change make Notebooks window scroll to its cell execution result.
Before fix:
After fix:

Fixed bug: Execute cell should scroll to its results

---

src/sql/workbench/services/connection/browser/connectionDialogService.ts
src/vs/workbench/services/extensions/electron-browser/extensionService.ts

Fixes -
1. Choose `MSSQL` for the first connection dialog that opens automatically when the app is opened for the first time/has no servers (and has CMS extension installed).

Make sure the first Connection Dialog has correct provider.

---

src/vs/workbench/services/extensions/electron-browser/extensionService.ts

Force CMS to reload. Added another issue to do it the correct way by adding to the extension API - https://github.com/microsoft/azuredatastudio/issues/5889
Fixes https://github.com/microsoft/azuredatastudio/pull/5890

Force cms to reload

---

extensions/integration-tests/package.json
extensions/integration-tests/src/cms.test.ts
extensions/integration-tests/src/utils.ts
extensions/mssql/src/cms/cmsService.ts

Recent changes to CMS API meant the tests fail (we throw instead of returning undefined now).
Also changed the service calls to reject with an error instead of just a plain string. This is the preferred method so that you get information such as stack frames and line numbers.

Fix CMS tests

---

src/sql/workbench/parts/notebook/notebook.component.html

This is a fix for the accessibility bug #5616. We shouldn't have a tabindex for the notebook component, as focusing on the whole thing doesn't make sense (and tabbing appears to "disappear" when it's selected).

Notebooks Accessibility: Remove tabindex=0 for Notebook Component

---

src/sql/workbench/parts/notebook/cellViews/output.component.ts
src/sql/workbench/parts/notebook/cellViews/outputArea.component.ts
src/sql/workbench/parts/notebook/models/cell.ts
src/sql/workbench/parts/notebook/models/modelInterfaces.ts
src/sqltest/parts/notebook/model/cell.test.ts

It should not scroll when opening existing Notebook file.
It change makes Notebook to scroll to output area only when Notebook command is executed.

Making Notebook to scroll to output area only when Notebook command is executed

---

extensions/admin-tool-ext-win/package.json

There were some changes to the context keys in this release that are used by this extension so without those the menu items won't work correctly.

Update admin-tool-ext-win extension to require ADS 1.8.0

---

extensions/schema-compare/src/schemaCompareResult.ts

This disables the generate script and apply buttons when no changes are selected because nothing happens anyway. Fixes #5887.

Disable schema compare generate script and apply buttons when no changes included

---

src/sql/platform/capabilities/common/capabilitiesServiceImpl.ts
src/sql/platform/connection/common/utils.ts
src/sql/platform/connection/test/common/connectionStore.test.ts
src/sql/platform/query/common/queryRunner.ts
src/sql/workbench/api/node/extHostQueryEditor.ts
src/sql/workbench/api/node/sqlExtHost.api.impl.ts
src/sql/workbench/browser/parts/views/customView.ts
src/sql/workbench/parts/dashboard/dashboardInput.ts
src/sql/workbench/parts/dashboard/pages/serverDashboardPage.component.ts
src/sql/workbench/parts/dashboard/widgets/properties/propertiesJson.ts
src/sql/workbench/parts/notebook/models/modelInterfaces.ts
src/sql/workbench/parts/notebook/models/notebookContexts.ts
src/sql/workbench/parts/query/browser/flavorStatus.ts
src/sql/workbench/services/profiler/common/profilerService.ts
src/sqltest/parts/accountManagement/firewallRuleDialogController.test.ts
src/sqltest/parts/connection/connectionProfile.test.ts
src/sqltest/parts/connection/connectionStatusManager.test.ts
src/sqltest/parts/connection/connectionTreeActions.test.ts
src/sqltest/parts/connection/objectExplorerService.test.ts
src/sqltest/parts/connection/providerConnectionInfo.test.ts
src/sqltest/parts/dashboard/widgets/propertiesWidget.component.test.ts
src/sqltest/parts/notebook/model/notebookModel.test.ts
src/sqltest/parts/notebook/model/notebookUtils.test.ts
src/sqltest/stubs/capabilitiesTestService.ts
src/sqltest/stubs/connectionProviderStub.ts
src/sqltest/stubs/objectExplorerProviderTestService.ts
src/sqltest/workbench/api/exthostNotebook.test.ts

Just some cleanup so we're consistent about our use of the provider name. There's additional improvements that should be made at some point too such as updating code to query for display name instead of that being hard-coded as well, but right now I wanted to keep this PR as simple as possible.

Change hardcoded MSSQL provider name to use constant instead

---

src/sql/workbench/parts/notebook/cellViews/media/highlight.css

Fixes #5379 Notebook: markdown Gray code makes Typescript code look wrong 
- Inside a code block, just use foreground color.
Before:
After:

Fix #5379 markdown Gray code makes code look wrong

---

src/sql/workbench/parts/notebook/models/cell.ts

- Only scroll if it's the 1st output, not for subsequent ones
- Otherwise can't use notebook while a cell is running & regularly updating the outputs

Fix outputs constantly focusing on new output

---

src/sql/workbench/parts/query/browser/queryEditor.ts

Fixes #5919 Fix it so we update the input whenever the results visibility is toggled in the editor so that we update the state correctly. This fixes the issue where the results visible event wouldn't fire because the visibility state hadn't been updated so was kept as the original value.

Plumb editor state change through to state object

---

extensions/integration-tests/src/objectExplorer.test.ts

- Updated test baselines
- Removed duplicate 'Standard SQL DB context menu test'
-  it's identical to Azure test
- Standalone database context menu test covers non-Azure

Fix failing integration test due to notebook context menu

---

extensions/cms/package.json
src/vs/platform/extensions/common/extensions.ts
src/vs/workbench/services/extensions/electron-browser/extensionService.ts

Added the ability to force extensions to reload, with CMS being the first extension to use this.
Fixes https://github.com/microsoft/azuredatastudio/issues/5889 and https://github.com/microsoft/azuredatastudio/issues/5846

Added option to force reload extensions

---

src/sql/workbench/parts/dashboard/pages/databaseDashboardPage.contribution.ts
src/sql/workbench/parts/dashboard/widgets/explorer/explorerTree.ts
src/sql/workbench/parts/dashboard/widgets/tasks/media/taskWidget.css
src/vs/platform/contextview/browser/contextMenuHandler.ts

This PR resolves https://github.com/microsoft/azuredatastudio/issues/4945
This PR includes:
* Adding 'New Notebook' task on Database Dashboard
* Adding 'New Notebook' action on the menu when right-clicking db node in Search widget on Server Dashboard

Added 'New Notebook' task on database dashboard

---

extensions/schema-compare/src/schemaCompareResult.ts
src/sql/workbench/electron-browser/modelComponents/diffeditor.component.ts
src/sql/workbench/electron-browser/modelComponents/media/editor.css

Add background color and other formatting to diff editor title to match look of OE. Also changing title for schema compare diff editor to "Compare Details" instead of "Object Definitions"
light theme:
dark theme:
high contrast black:

Formatting diff editor title

---

src/sql/platform/connection/common/connectionProfile.ts

Opening connection dialog was broken if you have a postgres connection
listed in the Connections view and the extension isn't installed.
The capabilities service breaks as it returns an undefined object.
Added handling, so now it does show as "loading..." forever
but doesn't crash

Fix #6022 connection dialog broken

---

src/sql/platform/telemetry/telemetry.contribution.ts

The commandExecuted event was only being sent from actions - not for all commands. So instead hooking up a listener for any command being sent and logging our own event to capture all the events.
Note that while investigating this I found that it seems like the old commandExecuted event wasn't even being sent anymore that I could see - it appears that something in the latest update changed so that the code path is never invoked anymore (whether this is a VSCode bug or not I can't tell). So we shouldn't be relying on the old event anyways.

Add telemetry for all commands

---

i18n/language-pack-de/package.json
i18n/language-pack-es/package.json
i18n/language-pack-fr/package.json
i18n/language-pack-it/package.json
i18n/language-pack-ko/package.json
i18n/language-pack-pt-BR/package.json
i18n/language-pack-ru/package.json
i18n/language-pack-zh-hans/package.json
i18n/language-pack-zh-hant/package.json

Update lang packs to target 1.9.0 and remove "zz" prefix (which was an unsuccessful attempt to get the lang packs to sort together in the Extension Manager).

Fix lang pack names and versions

---

src/sql/base/browser/ui/table/media/table.css

Agent - Fix header filter options layout

---

extensions/notebook/package.json
extensions/notebook/src/common/apiWrapper.ts
extensions/notebook/src/common/constants.ts
extensions/notebook/src/jupyter/jupyterServerManager.ts
src/sql/workbench/parts/notebook/notebook.component.ts

I had to add another check for action contributions after the kernel is changed, since the button state won't be refreshed without it. The actions get added to the toolbar after clicking on a kernel in the dropdown (i.e. when switching to jupyter provider), but they're hidden since python isn't installed yet. So there needs to be this other action check after kernel changes.
Also removed some unused constants in the notebook extension.
Fixes https://github.com/microsoft/azuredatastudio/issues/5955

Disable Manage Packages button if python is not installed

---

src/sql/workbench/parts/query/browser/query.contribution.ts

It looks like SSMS defaults to this option on by default.  We should follow that unless there is a reason not too.

Fix arith abort default value

---

src/sql/platform/connection/common/constants.ts
src/sql/workbench/services/connection/browser/connectionDialogService.ts
src/sql/workbench/services/connection/browser/connectionDialogWidget.ts

1. Updated names to accurately reflect what they contain (provider display names vs the actual provider type). 
2. Removed some code that was filtering out the CMS type - this wasn't working as expected since it was checking the provider type (MSSQL-CMS) but the list contains the display name (Microsoft SQL Server). As CMS is currently handled now what it's doing isn't even necessary - the "duplicate" value of Microsoft SQL Server is removed by the code below it that strips out duplicate values
3. Remove unused cmsProviderDisplayName constant - not only was this unused but it was also inaccurate as the display name is just Microsoft SQL Server as defined in the package.json for the CMS extension.

Connection dialog cleanup

---

src/sql/workbench/services/connection/browser/connectionWidget.ts

Fixes #4997 
This call to onAzureAccountSelected was unnecessary - we already have a handler that does this call when the selection changes and having it here caused it to be called immediately after returning from the Add Azure Account prompt when it still had the "Add anAccount..." selected and thus would trigger displaying the prompt again.

Fix Add Azure Account dialog constantly reappearing

---

src/sql/workbench/parts/notebook/notebookInput.ts

Was getting a content changed loop in the events
Fix is to ignore save events from the input since it sends them

Fix #6078 notebook dirty state after save

---

extensions/schema-compare/src/schemaCompareResult.ts

Align schema compare differences table with source label

---

src/sql/workbench/parts/notebook/cellViews/code.component.ts
src/sql/workbench/parts/notebook/cellViews/codeCell.component.ts
src/sql/workbench/parts/notebook/models/cell.ts
src/sql/workbench/parts/notebook/models/modelInterfaces.ts

Fixes #6106. We've gotten a bunch of feedback over the past day especially that this behavior could be improved and is confusing.
We were always calling setFocusAndScroll() on a hover of a code cell component, which meant that the input box would lose focus if a user moved their mouse inside the active code cell. With this change, users can move their mouse freely, and the input box won't lose focus.

Notebooks: Fix for standard in component losing focus when hovering over code cell

---

extensions/integration-tests/src/schemaCompare.test.ts
extensions/schema-compare/package.json
extensions/schema-compare/src/controllers/mainController.ts
extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
extensions/schema-compare/src/schemaCompareResult.ts
extensions/schema-compare/src/test/schemaCompare.test.ts
extensions/schema-compare/src/test/testSchemaCompareService.ts
extensions/schema-compare/src/utils.ts
src/sql/azdata.proposed.d.ts

This adds the ability to change the schema compare source and target. It also changes the start point of schema compare to be the main page rather than the dialog.
launching from database:
launching from command palette:

Add ability to change source and target to Schema Compare

---

src/vs/platform/environment/node/argv.ts

This change adds entries to --help for the new command line switches for invoking a command and for connecting to a server. 
For #3059 
They go into the Options group. 
I reordered the list slightly so the server connection parameters are clumped together and command sits above them.

add --help documentation

---

extensions/notebook/src/common/utils.ts
extensions/notebook/src/extension.ts
extensions/notebook/src/protocol/notebookUriHandler.ts

Adds a protocol handler for notebook open, which can be used from browsers
Uses extension-based handler support so all URIs must start with `azuredatastudio://microsoft.notebook`
Adds 2 actions:
- `/new` opens a new empty notebook
- `/open` opens a HTTP/S file as an untitled notebook or text document
_New Notebook_:
```
azuredatastudio://microsoft.notebook/open
```
_Open_:
```
azuredatastudio://microsoft.notebook/open?url=https%3A%2F%2Fraw.githubusercontent.com%2Fkevcunnane%2Fmsbuild_ads_demo%2Fmaster%2F0_YoAzdata.ipynb
```
UX flow:
Enter link in browser (likely via a button)
Azure Data Studio opens. Prompt to do the action you requested:
For open notebook, final confirm where you can see the path:
Finally file is opened as a notebook or text document. If file with same name exists …

Add notebook open protocol handler

---

src/sql/workbench/parts/notebook/cellViews/linkHandler.directive.ts
src/sql/workbench/parts/notebook/cellViews/outputArea.component.html
src/sql/workbench/parts/notebook/cellViews/outputArea.component.ts
src/sql/workbench/parts/notebook/cellViews/textCell.component.html
src/sql/workbench/parts/notebook/cellViews/textCell.component.ts
src/sql/workbench/parts/notebook/notebook.module.ts
src/sql/workbench/parts/notebook/notebookStyles.ts

- Single click now works for links inside Output areas
- Command links in untrusted notebooks have link color
- Refactored to use directive so code is in 1 place and can be easily
added elsewhere if needed

Improve notebook link handling

---

extensions/dacpac/src/wizard/api/dacFxConfigPage.ts

This fixes dacpac filepath for extract and bacpac filepath for export getting regenerated every time the config pages are entered instead of remembering if filepath if it was manually changed.
Fixes #5834.

Fix Dacfx filepaths getting regenerated ever time page is entered

---

src/sql/workbench/parts/notebook/notebookStyles.ts

Problem: we were setting the notebook toolbar labels as blue with a recent css change.
Fixes #6139, as the notebook toolbar is in a different div than the scrollable portion of the notebook.
After change:

Only set notebookEditor <a> color in scrollable portion

---

extensions/dacpac/src/wizard/api/basePage.ts
extensions/dacpac/src/wizard/api/dacFxConfigPage.ts
extensions/dacpac/src/wizard/pages/deployConfigPage.ts
extensions/import/src/wizard/api/basePage.ts

Fixes #5809. Removes database name from server dropdowns and adds the required asterisk to the database dropdown titles.

Fix #5809: Data-tier wizard "Source Server" shouldn't show database name

---

src/sql/workbench/parts/profiler/browser/profiler.contribution.ts

#5932 
add database name and database id fields to the applicable events and also add database id and database name columns to the views. with these changes, users will be able to filter the events by database name

add db name to xevent session and view

---

src/sql/workbench/parts/profiler/browser/profilerCopyHandler.ts
src/sql/workbench/parts/profiler/browser/profilerEditor.ts
src/sql/workbench/parts/profiler/browser/profilerTableEditor.ts

#5667
there are 2 tables in profiler, adding copy support for both of them.

handle copy in all profiler tables

---

extensions/profiler/client/src/dialogs/profilerCreateSessionDialog.ts
src/sql/workbench/parts/profiler/browser/profiler.contribution.ts
src/sql/workbench/services/profiler/common/interfaces.ts
src/sql/workbench/services/profiler/common/profilerService.ts

fix for issue #5304 
1. filter the profiler session templates by supported engine types
2. handle the error case in profiler extension when calling the provider directly so that the user can see it in case of error instead of waiting forever.
create session against standalone server:
create session against SQLDB server:

Filter templates by supported engine type

---

extensions/integration-tests/src/notebook.test.ts
extensions/notebook/package.json
extensions/notebook/package.nls.json
extensions/notebook/src/extension.ts
src/sql/azdata.proposed.d.ts
src/sql/workbench/api/node/extHostNotebookEditor.ts
src/sql/workbench/api/node/mainThreadNotebookDocumentsAndEditors.ts
src/sql/workbench/api/node/sqlExtHost.protocol.ts
src/sql/workbench/parts/notebook/notebook.component.ts
src/sql/workbench/services/notebook/common/notebookService.ts

Implements #6019.
Chose Ctrl+Shift+R as Ctrl+Shift+O was already taken. In Jupyter, they use Ctrl+O, which obviously won't work.
Added a command to the command palette, and gave it a keybinding. Also added an integration test.

Notebooks: Add Command + Keyboard Shortcut to Clear Outputs of Active Cell

---

extensions/schema-compare/package.json
extensions/schema-compare/src/schemaCompareResult.ts

Fixes #6175. This remove resetting options to dialog options before executing the comparison since this was causing the scmp options to not be used if the options were changed before the scmp was opened. The options already get set every time the options dialog is closed.

Fix #6175: Schema compare doesn't always use scmp options

---

src/sql/workbench/api/node/extHostModelViewDialog.ts
src/sql/workbench/parts/query/browser/queryResultsView.ts
src/sql/workbench/parts/query/common/queryResultsInput.ts
src/sql/workbench/parts/query/modelViewTab/queryModelViewTab.ts

This fixes a bug when tab switching where all documents share the state of the most recently added dynamic tab.

Properly save and restore dynamic tab state

---

extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
extensions/schema-compare/src/schemaCompareResult.ts

This fixes #6200 schema compare failing when opening an scmp with a dacpac. It was failing because a few fields were null which caused the compare request to fail. 
Also removing a print statement and fixing a comparison.

Fix #6200  schema compare after opening scmp with dacpacs failing

---

extensions/mssql/src/config.json

Contains fix for #4825, schema compare fixes and change to default OE connection nodes to always be at server level

Bump SqlToolsService to 1.5.0-alpha.105

---

extensions/notebook/src/book/bookTreeItem.ts
extensions/notebook/src/book/bookTreeView.ts
extensions/notebook/src/extension.ts

Clicking on a markdown file in the book treeview will show the markdown preview rather than the raw md file. Double clicking anywhere in the markdown preview will open up the raw md file.

Books feature: show markdown preview

---

extensions/schema-compare/src/schemaCompareResult.ts
src/sql/workbench/electron-browser/modelComponents/table.component.ts

This allows table width to be specified. Fixes #6163 where the schema compare differences table scrollbar disappeared after a left margin was added. This fixes that by setting the width to less than 100% so the scrollbar shows up again.
Before where scrollbar is missing:
Now showing scrollbar again after setting width to 98%:

Fix #6163 Schema compare differences table scrollbar missing

---

extensions/integration-tests/src/schemaCompare.test.ts
src/sql/workbench/common/actions.ts

Fix for backup/restore launch from command pallet in context of server - errors differently in MAC and windows : https://github.com/microsoft/azuredatastudio/issues/5797 adding common path and error messages
Another change for test to complete the tasks before exiting the test other wise they show as errors in test ADS window 
Apologies for combining two PRs (did so in favor of time - since both were small)

Fixing backup restore launch bug #5797 (and a test)

---

src/sql/base/browser/ui/selectBox/selectBox.ts

This addresses issue #5679, where a selectbox in a toolbar is read as a 'Button' when using a screen reader on Mac.
After this change, a selectbox will be read as a 'popup button'. I chatted with a couple of folks and verified that this matches VS Code behavior ass well.

Accessibility: Screen Reader Thinks SelectBox is a Button on Mac

---

src/sql/workbench/parts/notebook/cellViews/textCell.component.ts

Ensure that we sanitize the same way that we did as the old renderer.
Fixes #6238.

Notebooks: Make sure we sanitize the same way with in proc markdown

---

extensions/dacpac/package.json
extensions/dacpac/src/wizard/dataTierApplicationWizard.ts

Fixes #6217. Now the connection dialog opens with the connection details of the server the wizard was launched from.

Fix #6217 DacFx: Connection Dialog has no ConnectionProfile loaded 

---

extensions/import/src/services/serviceClient.ts
extensions/mssql/src/main.ts

- Change showing of message window to not take focus when shown
- Only show the message window on install start so that if user closes it it'll stay closed (we can assume they're not interested in the messages if they close it after the initial one)
- Localize the displayed messages
Fixes #6157 #5149 #6110

Change service installation messages to not steal focus

---

src/vs/workbench/api/node/extHost.api.impl.ts

Some VS Code extensions assume this value won't be null, but will return an empty array when no breakpoints are set.

Return an empty arrary from breakpoints API

---

src/sql/workbench/electron-browser/modelComponents/queryTextEditor.ts
src/sql/workbench/parts/notebook/cellViews/code.component.ts

Fixes the known repro for #5217.
Fixes #5852. 
We needed to stop creating a new Configuration object every time we called the setHeightToScrollHeight method (as stress uncovered a memory leak), so this gave me an excuse to fix that as well 😄. Now, we get the layoutInfo and configuration directly from the editorWidget. Also made a change to have the notebook re-calculate lineHeight when the setting is changed.

Support non-default font sizes in notebooks

---

extensions/integration-tests/src/notebook.test.ts
extensions/notebook/src/extension.ts
src/sql/azdata.proposed.d.ts
src/sql/workbench/api/node/extHostNotebookEditor.ts
src/sql/workbench/api/node/mainThreadNotebookDocumentsAndEditors.ts
src/sql/workbench/api/node/sqlExtHost.protocol.ts
src/sql/workbench/parts/notebook/cellToggleMoreActions.ts
src/sql/workbench/parts/notebook/notebook.component.ts
src/sql/workbench/services/notebook/common/notebookService.ts

Customers (both internally and externally) have asked repeatedly to add the ability to run cells above/below the current cell.
This follows the Jupyter convention of the following:
- Run cells after runs the selected code cell and any code cells further down the document
- Run cells before runs every code cell preceding (i.e. not including) the currently selected cell

Notebooks: Run all after/before

---

src/sql/workbench/parts/notebook/notebookActions.ts

Fixes #5769
This isn't the full fix that I'd like to do at some point - which is to decouple the concept of this connection type and the saving of the connection. There's also some other things like that we should probably just hide the group dropdown if we're not saving the connection since it doesn't do anything anyways. But this is meant as a targeted fix to stop this broken behavior now and then we'll revisit a more thorough refactor later.

Fix notebook to not save connections added through dropdown

---

extensions/schema-compare/src/schemaCompareResult.ts

Add only non null changes to ensure index doesnt mismatch between UI and internal dictionary.
Fixes #6234

Add only non null changes to ensure index doesnt mismatch between UI and internal dictionary

---

src/sql/workbench/api/node/extHostConnectionManagement.ts

Undo change made in #6264 - this incorrectly was causing the remapping of providerName -> providerId to not happen (the object we get back is a Connection which has a providerName, but we're returning a ConnectionProfile which uses providerId instead). Without this extensions calling this method that expected a providerId were getting undefined instead and breaking (such as Agent)
Note I'll be following up with a different fix that is more thorough since I don't see any reason why we should have to do this remapping anyways. I don't want that in for July though since it's a lot riskier of a move - this PR is meant for the July release to just fix the issue since it's pretty critical.

Fix connectionId remapping

---

src/sql/base/browser/ui/panel/panel.ts
src/sql/workbench/api/node/extHostModelViewDialog.ts

Fixes #6265
This was broken in #6185. I don't see why the handle var was moved to be static since it doesn't seem like that should be shared, and that was breaking the agent dialog since it caused all the tabs to share the same ID which broke the tab switching logic.
Also fixing a misspelling I noticed while debugging this.

Fix Agent tabs not switching

---

src/sql/workbench/parts/notebook/notebook.contribution.ts

- Fix #6221 Notebooks: Keyboard Shortcut for New Notebook has Changed.
- Use Win+Alt+N instead of Win+Shift+N
- New Grid is now "stable" (forgot to do this in last PR)

Fix #6221 notebook shortcut and use new grid in stable

---

extensions/notebook/src/test/model/serverInstance.test.ts
extensions/notebook/src/test/model/serverManager.test.ts

Previously the execOptions field would get set in configurePackagePaths from the JupyterServerInstallation constructor, but this method had to be moved out of the constructor due to becoming async. The product code references were updated to call the configure method separately, but these test references were missed since they use TypeMoq instead of calling the constructor directly. This was causing the notebook unit tests to fail since execOptions is undefined.
The actual content of execOptions here doesn't matter, since the unit tests mock out any python executing methods like those used in serverInstance.start() & stop().

Manually define JupyterServerInstallation execOptions field in notebook unit tests.

---

src/sql/workbench/parts/notebook/notebook.contribution.ts

Use in proc markdown by default in stable (which was the plan for the July release). It's being called out in the relnotes, so making sure that the default experience is the one that we advertise 😄

Use in proc markdown by default in Stable

---

extensions/notebook/src/jupyter/jupyterServerInstallation.ts

If there's an existing Python 3.6 install, then pre-existing pip packages in the user's package directory will cause our own package installs to be skipped when using the New Python Install option. Since we don't include the user package directory in PATH when using the New Python option, jupyter commands then can't be found when trying to open a notebook.
Also noticed there's a bit of code duplication here, so I'm currently cleaning that up.
Fixes https://github.com/microsoft/azuredatastudio/issues/6309

Ignore existing pip packages when installing our standalone version of python.

---

src/sql/workbench/api/node/extHostConnectionManagement.ts
src/sql/workbench/api/node/mainThreadConnectionManagement.ts
src/sql/workbench/api/node/sqlExtHost.protocol.ts

Note this is the full fix mentioned in #6269
For some reason getCurrentConnection - which returns a ConnectionProfile - was retrieving a Connection instead which is a very different structure (for example it uses providerName instead of providerId) which meant we had to do this remapping of properties to align with the ConnectionProfile definition as expected.
The fix here is to just actually fetch a ConnectionProfile instead from the MainThreadConnectionManagement calls. This does slightly change the result though since the ConnectionProfile returned now contains a lot more fields than Connection does. But given that callers were expecting a ConnectionProfile anyways this should just be more fixing an existing bug than changing behavior. 
I'm also included a fix for an issue I noticed …

Change getCurrentConnection to return full ConnectionProfile

---

src/sql/workbench/parts/dataExplorer/browser/dataExplorer.contribution.ts

Fixes #5774
I would have liked to do ctrl + shift + c but that's taken by notebooks new cell as well as launch native terminal already. So went with ctrl + shift + d since that wasn't taken and it follows the VS Code convention of keybinds for the viewlets (Explorer == E, Search == F, SCM == G)

Change keybinding for showing data explorer viewlet

---

extensions/schema-compare/src/controllers/mainController.ts
extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
extensions/schema-compare/src/dialogs/schemaCompareOptionsDialog.ts
extensions/schema-compare/src/schemaCompareMainWindow.ts
extensions/schema-compare/src/test/schemaCompare.test.ts

Rename SchemaCompareResult to SchemaCompareMainWindow to be more clear since it is now the start point and main page of Schema Compare.

Rename SchemaCompareResult to SchemaCompareMainWindow

---

src/sql/workbench/parts/notebook/models/cell.ts

Internal Spark endpoint value changed. Updated to handle old & new URL

Fix #6396 Spark link is incorrect on latest server

---

src/sql/workbench/parts/objectExplorer/browser/serverTreeActionProvider.ts

- The OEAction calls through a command service implementation that loses the context object.
Directly instantiating the NewNotebookAction solves this.
Also tested NewQuery and that didn't have an issue so left as-is

Fix #6397 right-click New Notebook connects to wrong server

---

extensions/notebook/src/book/bookTreeView.ts

Issue here is that for some reason click in tree causes 2 events:
- Selection Changed
- Resource Opened
Due to this, we get the markdown event 2 times and this misbehaves.
I am not confident in changing markdown so implemented similar pattern:
- Throttle requests if they're for the same resource inside 300ms
- This means 2nd event is ignored
Testing:
- Manual, clicked a bunch of markdowns
- It "just works" for me now

Fix markdown in Jupyter books not working

---

extensions/azurecore/src/account-provider/tokenCache.ts
extensions/azurecore/src/test/account-provider/tokenCache.test.ts
extensions/azurecore/src/test/azureResource/tree/treeProvider.test.ts
extensions/azurecore/src/test/stubs/credentialsTestProvider.ts
scripts/test-extensions-unit.bat
scripts/test-extensions-unit.sh

Fixes an issue where Azure accounts weren't able to be loaded/added. The root issue is that in Electron v4 they switched from using OpenSSL to BoringSSL which doesn't support the encryption algorithm we were specifying (aes256). Thread on the issue here : https://github.com/electron/electron/issues/16195
They instead support specific variants of aes256 - I chose aes-256-cbc because it's backwards compatible with aes256 (verified by saving account using ADS 1.9 which uses aes256 and then making sure it was loaded correctly in master with my changes)

Switch to aes-256-cbc cipher for Azure account storage

---

build/builtInExtensions-insiders.json
build/lib/builtInExtensions.js
build/lib/extensions.js
build/lib/extensions.ts
extensions/mssql/src/dashboard/bookExtensions.ts
extensions/mssql/src/dashboard/serviceEndpoints.ts
extensions/mssql/src/main.ts
extensions/mssql/src/util/arrays.ts
extensions/mssql/src/util/dispose.ts
scripts/sql.bat
scripts/sql.sh
src/vs/platform/extensionManagement/node/extensionManagementService.ts
src/vs/workbench/services/extensions/electron-browser/cachedExtensionScanner.ts

This adds SQL Server Notebook as a built-in extension
by pulling it from blob storage.
It also adds support in mssql extension for reading the contribution points from other extensions.
This will contribute troubleshooting and other books as widgets
In this PR:
- Bundle the extension in the build
- Bundle in sql.sh / sql.bat so it appears in local testing
- Avoid installing in Stable. Should only appear in Dev/Insiders builds
- Extensions with `notebook.books` contribution point will be discovered & their books available in MSSQL
Coming later:
- Integrate this with Maddy's work to show a Notebooks widget in the SQL Server big data cluster UI
- When clause isn't supported yet for filtering. Will be done as we refactor towards more books for different server types

Support installing SQL Server Notebook extension

---

samples/notebookSamples/SampleTSQLNotebook.ipynb

The logo file doesn't show inside my notebook unless I add `blob/master/` within the path.
The path which works on my machine is: `https://github.com/Microsoft/azuredatastudio/blob/master/samples/notebookSamples/Graphics/AzureDataStudioLogo.png?raw=true`

Updating Logo Source Path

---

extensions/dacpac/package.json
extensions/dacpac/src/test/dacpac.test.ts
extensions/dacpac/src/wizard/api/dacFxConfigPage.ts
extensions/dacpac/src/wizard/api/utils.ts
extensions/dacpac/src/wizard/dataTierApplicationWizard.ts
extensions/dacpac/src/wizard/pages/exportConfigPage.ts
extensions/dacpac/src/wizard/pages/extractConfigPage.ts

This adds validation for filenames if the filename is changed directly in the text box instead of in the file explorer for extract and export operations. Also adds the proper file extension if it isn't there and the filename is valid. Fixes #4461.

Fix #4461 Dacpac: Extract lets me save to invalid file path like 'sd' and never adds .dacpac / .bacpac

---

src/sql/workbench/api/common/extHostModelViewTree.ts
src/vs/workbench/api/common/extHostTreeViews.ts

* Issue: Checkbox status is always rendered as `-`
* Cause: `checked` and `enabled` field are missing when item created from tree data model for rendering.
Therefore, `checked` field always has `unidentified` value on rendering time.
(Missing `enabled` field did not cause issue since `unidentified` is considered as `true` for `enabled` field.)
Before fix:
After fix:

Fixed issue on rendering checkbox status of tree node

---

build/azure-pipelines/common/publish.ts

in recent vscode merge, the isReleased flag is set to false, as a result we don’t have insider build for a week. now I am adding back the logic that worked for us before.

set the auto release for insider build

---

build/lib/extensions.js
build/lib/extensions.ts

This was treated as a marketplace install.
Should be built-in but only available in Insiders

Fix #6466 big data clusters section not appearing

---

extensions/big-data-cluster/extension.webpack.config.js

- Entry point is `extension` not `main`

Fix #6485 big-data-cluster extension fails to load

---

extensions/mssql/src/dashboard/serviceEndpoints.ts

Fixes #6401
Having the text be a hyperlink isn't really useful as there's no UI to interact with. Users can use the copy button to copy the endpoint info for using elsewhere (such as BDC tree-view)

Remove hyperlinks from non-management BDC endpoints

---

extensions/notebook/src/jupyter/jupyterServerInstallation.ts

In our provided Windows Python package, the shebangs (lines with #!) in the pip*.exe files are set to a local path picked up when the package was originally built. This is because Windows has no preinstalled version of Python, so we can't use the same portable shebangs that Mac/Linux generally use e.g. "#! /usr/bin/env python3". Thus the Windows shebangs have to updated after the install, since we would have no way of knowing the python install location ahead of time. Otherwise the executable files can't be run by themselves, and have to be run like "python -m pip".
This change reinstalls pip at the end of the installation, so that we pick up the absolute path to the python exe in our package.
Fun fact, apparently the shebang path in the pip*.exe files is currently …

Reinstall pip during python install on Windows to update shebangs in exe files.

---

extensions/big-data-cluster/src/bigDataCluster/tree/controllerTreeNode.ts

Adds the contributed server-level actions to the BDC SQL Master node. 
Removed the connection name value since it isn't used for anything as far as I know and was causing the dashboard to have a title which included the random GUID that we generate for each node. Leaving it blank makes the dashboard generate the title from the connection info itself (this is what we normally do elsewhere such as OE)
Fixes #6402

Add server-level actions to master SQL node in BDC view

---

extensions/mssql/src/dashboard/bookWidget.ts

When Reload/Open new instance is clicked, made changes to open from the book folder.

Fix: reload opens the parent folder not the new books folder

---

src/sql/azdata.proposed.d.ts
src/sql/workbench/parts/notebook/electron-browser/cellViews/code.component.ts
src/sql/workbench/parts/notebook/electron-browser/cellViews/textCell.component.ts
src/sql/workbench/parts/notebook/node/models/cell.ts
src/sql/workbench/parts/notebook/node/models/modelInterfaces.ts
src/sql/workbench/parts/notebook/test/node/cell.test.ts
src/sql/workbench/services/notebook/node/localContentManager.ts
src/sql/workbench/services/notebook/sql/sqlSessionManager.ts

Implements #6431, which we've been talking about doing for quite a long time now. This will make the edit perf improvements easier to do, as we won't need to translate a range from an editor into some offset for a source that is a single line. Added unit tests.
Verified that Jupyter viewer can open notebooks with this change.
Here's a sample serialized code cell, with the before and after:
Before:
{
"cell_type": "code",
"source": "p\nm",
"metadata": {},
"outputs": [],
"execution_count": 0
}
After:
{
"cell_type": "code",
"source": [
"p\n",
"m"
],
"metadata": {},
"outputs": [],
"execution_count": 0
}

Save multiline source in notebooks

---

src/sql/workbench/parts/notebook/common/models/cell.ts

Notebooks: Multiline cell execution fix. Fixes regression caused by multiline saving PR.

Notebooks: Multiline cell execution fix

---

extensions/schema-compare/package.json
extensions/schema-compare/src/dialogs/schemaCompareOptionsDialog.ts
extensions/schema-compare/src/schemaCompareMainWindow.ts

Recomparing from the notification after resetting options wasn't using the correct options because the compare was being started before the options were set to the new values. Fixes #6538.

Fix Schema compare recompare after options reset not using correct options 

---

extensions/big-data-cluster/package.json
extensions/cms/package.json
extensions/cms/src/apiWrapper.ts
extensions/cms/src/appContext.ts
extensions/cms/src/cmsResource/tree/treeProvider.ts
extensions/cms/src/cmsUtils.ts
extensions/cms/src/extension.ts

This way we aren't cluttering up the config more than we have to.
On extension startup it will see if any servers exist in the config and if so store them into the memento storage so that users don't lose existing saved servers. 
Also removed unused config from BDC extension - the servers aren't stored in the config anymore so that setting isn't necessary.

Move CMS saved servers to be stored in memento instead of config

---

extensions/big-data-cluster/src/bigDataCluster/dialog/addControllerDialog.ts

We can't actually stop the endpoints request from completing so just using a flag that will tell us whether to actually add the controller node after completion (and ignore any errors)
Fixes #6400

Add support for cancelling BDC Add Controller request

---

src/sql/platform/telemetry/common/telemetryKeys.ts
src/sql/workbench/parts/query/browser/actions.ts
src/vs/workbench/contrib/extensions/electron-browser/extensionTipsService.ts

Added 'Click' and 'ExtensionRecommendationDialog' telemetry keys and fixed telemetry events for the visualizer recommendation prompt.

Fixed telemetry events for visualizer recommendation prompts

---

extensions/dacpac/src/wizard/api/basePage.ts

This makes two changes to the DacFx wizard server dropdowns:
1. Remove duplicate server connections. Fixes #6562
2. Sort the dropdown values so that the most recent connections are at the top
These are the same changes that were made to the Schema Compare server dropdowns in this PR #5552

DacFx server dropdown fixes

---

src/sql/workbench/services/notebook/common/localContentManager.ts

To date, we’ve been leveraging the vscode json parser when opening notebooks. It’s very fault-tolerant (accepts things such as being able to read JSON when it’s not properly formatted JSON [see: extra } at the end of a document]), which has its pros and cons.
However, this comes at a cost: speed. It’s slow. Like, really, _really_ slow.
Since I’ve been doing other perf work lately, I’ve become familiar with the various JSON parsers that we leverage in ADS and immediately spotted an improvement here. @aasimkhan30 may be interested in this 😄.
Here are preliminary results when loading the same ~30MB file on my machine (just for the parsing portion of loading a file)…
Old parser: 10503ms
New parser: 357ms
= 97% faster

Notebooks: Use much faster json parser when loading notebook initially

---

src/sql/workbench/common/customInputConverter.ts
src/sql/workbench/parts/commandLine/test/electron-browser/commandLine.test.ts
src/sql/workbench/parts/query/browser/keyboardQueryActions.ts
src/sql/workbench/parts/query/browser/queryActions.ts
src/sql/workbench/parts/query/browser/queryResultsView.ts
src/sql/workbench/parts/query/browser/statusBarItems.ts
src/sql/workbench/parts/query/common/queryInput.ts
src/sql/workbench/parts/query/common/queryResultsInput.ts
src/sql/workbench/parts/query/test/browser/queryActions.test.ts
src/sql/workbench/parts/query/test/browser/queryEditor.test.ts
src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
src/sql/workbench/test/common/taskUtilities.test.ts

Reverts microsoft/azuredatastudio#6513
Reverting since it breaks some other features.
This will halt progress in other feature areas, but I'm not sure how long it will take to redesign this area.

Revert "Remove references to query model service in query code"

---

src/sql/workbench/api/common/extHostDataProtocol.ts

Connections weren't able to be made because uriTransformer was null. Everywhere else uriTransformer is used it's assuming to possibly be null and checked appropriately.

Fix connections when uriTransformer is undefined

---

extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts

- Fix spark job failing when 1 or more servers are connected
and listed in getActiveConnections
- If nothing is connected, prompts to choose a server
- Added option to dropdown when 1 or more server is connected
to support picking a different connection
Root bug was trying to access "host" not "server" in options bag, which no longer exists.
**Screenshot - new option in prompt**

Fix #6576 Spark job submit fails from command palette

---

extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
extensions/schema-compare/src/dialogs/schemaCompareOptionsDialog.ts
extensions/schema-compare/src/test/schemaCompare.test.ts

Typically the string "OK" is used for the submit buttons in windows applications.  For example, the below from SSMS.  This updates for Schema Compare for consistency with other UX.

Change 'Ok' to "OK" in schema compare UI

---

extensions/notebook/src/book/bookTreeView.ts
extensions/notebook/src/extension.ts

Fixes #6487 
Previously Book Tree View was only looking at the first folder in a workspace. Now it looks through all folders.

Find all books in workspace with multiple folders

---

extensions/notebook/package.json
extensions/notebook/src/book/bookTreeItem.ts
extensions/notebook/src/book/bookTreeView.ts
extensions/notebook/src/test/book/book.test.ts
extensions/notebook/yarn.lock

This unit test creates a simple test book that contains three items (.ipynb, .md, and external link) and checks that getChildren() correctly creates tree nodes for each item. Test book is removed at the end of unit test.

Added unit test for books getChildren() method

---

src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts

#6600 
our edit got lost during vscode refactoring.

fix viewlet ordering

---

src/sql/workbench/common/actions.ts

Restore was mistakenly blocked from server context when blocking backup for this bug https://github.com/microsoft/azuredatastudio/issues/5797
Reverting the change for restore. Fixes https://github.com/microsoft/azuredatastudio/issues/6608 https://github.com/microsoft/azuredatastudio/issues/6493

Enable restore from server context only backup should be blocked

---

extensions/dacpac/src/wizard/api/dacFxConfigPage.ts

Use previous file path if there was one for the dacpac/bacpac file location when the database changes in the DacFx wizard. Fixes #6606 .

Fix #6606: Data-tier Application extract file location resets when changing database 

---

extensions/admin-tool-ext-win/package.json
extensions/agent/package.json
extensions/dacpac/package.json
extensions/import/package.json
extensions/mssql/package.json
extensions/profiler/package.json
extensions/resource-deployment/package.json
extensions/schema-compare/package.json
product.json
src/vs/code/electron-browser/sharedProcess/sharedProcessMain.ts
src/vs/code/node/cliProcessMain.ts
src/vs/workbench/services/telemetry/browser/telemetryService.ts

Use VS Code iKey for onboarding into Nova. 
Update event prefix to then differentiate our telemetry from their events.

Use VS Code iKey and modify event prefix

---

extensions/schema-compare/src/dialogs/schemaCompareOptionsDialog.ts

Fixes options not getting set when recompare isn't done(now the options get set whenever OK is pressed) and also fixes aggregate not getting unchecked.

Fix schema compare options bugs

---

extensions/mssql/extension.webpack.config.js
extensions/mssql/package.json
extensions/mssql/yarn.lock

Upgrades the language client which allows us to remove all the externals from mssql's webpack, reducing out file count by ~1000

Upgrade language client and remove from webpack

---

extensions/notebook/src/book/bookTreeView.ts
extensions/notebook/src/test/book/book.test.ts

The tests were failing because I moved getTableOfContents() into an async method and getChildren() was being called before the toc.yml files were found. I added an Event to make sure all toc.yml files were found before running the tests.

Fix Books Unit Tests

---

extensions/dacpac/src/wizard/api/basePage.ts

Fixes regression from #6565. The connections list needs to be reversed before the default connection is set.

Fix #6709: default DacFx connection not always being correct

---

src/sql/platform/connection/common/utils.ts
src/sql/platform/connection/test/common/connectionManagementService.test.ts
src/sql/platform/connection/test/common/connectionStatusManager.test.ts
src/sql/workbench/api/common/extHostDataProtocol.ts

fixes #6720
I think vscode changed it so that a uri transformer is always passed which meant we were hitting the encoding steps, so this bug popped up.
We should going forward probably do something cleaner around how we handle connection id's vs actual uris.

Fix encoding of uris for data protocol

---

src/sql/workbench/parts/notebook/browser/notebook.component.html
src/sql/workbench/parts/notebook/browser/notebook.component.ts

When clicking on an inline notebook button to add a cell, the click would also trigger the unselectActiveCell callback of the notebook container, causing the newly added cell to lose focus. This change stops the mouse event propagation after adding a cell to prevent that unselect callback from being triggered, similar to how we block mouse events in selectCell.
Fixes https://github.com/microsoft/azuredatastudio/issues/6705 https://github.com/microsoft/azuredatastudio/issues/6614

Correctly set focus on new Notebook cells after clicking on inline buttons.

---

extensions/dacpac/src/wizard/pages/dacFxSummaryPage.ts
src/sql/azdata.d.ts
src/sql/base/browser/ui/table/table.ts
src/sql/workbench/api/common/extHostModelView.ts
src/sql/workbench/browser/modelComponents/table.component.ts

This adds the option for tables to have a title attribute and adds a title to the summary tables in the DacFx wizard. Addresses accessibility bug #6660.

Add optional title to tables

---

extensions/notebook/src/book/bookTreeView.ts

Issue: Books viewlet was not showing up on Windows because toc.yml files were not being found by fast-glob. 
Solution: Replace all backslashes with forward slashes before passing into fast-glob.

Fix toc.yml path for windows

---

extensions/dacpac/src/wizard/api/dacFxConfigPage.ts
extensions/dacpac/src/wizard/pages/deployConfigPage.ts

Deploy, extract, and export all use the same populateDatabaseDropdown() method. For extract and export, the database dropdown population should result in the generated filepath and selected database to change to the match the top entry in the dropdown. However, for deploy, populating the database dropdown should only update the database if it's updating an existing database(not creating a new db) and the filepath should not be generated because it uses an existing dacpac(not being created like in the other two scenarios).
Fixes #6707.

Fix #6707: deploy filename changing when it shouldn't

---

extensions/dacpac/src/wizard/dataTierApplicationWizard.ts
extensions/dacpac/src/wizard/pages/deployConfigPage.ts
extensions/dacpac/src/wizard/pages/selectOperationpage.ts

Fixes #6771. The summary page had the wrong page number for deploy to new database. This fixes that by removing both the summary and deploy plan pages, then adding the summary page back so that it will have the correct page number.

Fix #6771: Dacfx wizard summary page has wrong page number

---

extensions/mssql/extension.webpack.config.js

Modules depending on node-bindings can't be webpacked. https://github.com/TooTallNate/node-bindings/issues/43

Do not webpack kerberos

---

src/sql/workbench/parts/profiler/browser/profilerInput.ts

#6805 
recent uri transformer change caused the issue, now it is required to pass in a valid uri instead of a guid, otherwise a connection not found error would occur when connection is established. fixing the occurrence for the profiler feature.

add valid uri prefix

---

extensions/dacpac/src/wizard/pages/dacFxSummaryPage.ts
src/sql/azdata.d.ts
src/sql/base/browser/ui/table/table.ts
src/sql/workbench/browser/modelComponents/table.component.ts
src/sql/workbench/services/fileBrowser/browser/fileBrowserDialog.ts

Addresses #6694 
The `aria-rowcount` and `aria-colcount` properties are intended to indicate to a screen-reader how many total, non-DOM rows and columns there are for a virtualized table.  Electron seems to automatically add these properties when the table's first initialized (before we add data), but aria documentation recommends to only include these if there are any non-DOM rows or columns.
As most tables do not have virtualized cells, this change defaults to removing the aria properties, but if you specify the number of cells in the virtualized dataset, they'll be added with the correct values.
Also addresses #6749 by adding `role="presentation"` to the element so screen readers don't announce it.

Improve narration for backup and dacpac UIs

---

extensions/integration-tests/src/schemaCompare.test.ts

Disabling this test for now because it is sometimes failing with "Error: This editor is not connected to a database Parameter name: OwnerUri"

Disable failing schema compare dacpac to database test

---

src/sql/base/browser/ui/radioButton/radioButton.ts

Set the aria-label to the same value as the label for radio buttons so that screenreeders can read it. Addresses  #6825

Set aria-label for radio buttons

---

extensions/dacpac/src/wizard/api/dacFxConfigPage.ts
extensions/schema-compare/src/dialogs/schemaCompareDialog.ts

Adding aria labels to the '•••' buttons so that their names show as "Select file". Addresses #6742.

Add aria labels to '•••' buttons in dacfx and schema compare

---

src/sql/workbench/common/customInputConverter.ts
src/sql/workbench/parts/query/common/queryInput.ts

Recent VS Code merge made it so the URI is always passed through the transformer - so to preserve the normal connection URIs (which had | in them) 6fd4b5eaf26c75c45ad0ecf9af6df2faeae87ce3 was done to not encode the URIs. This broke the file URIs though as we weren't doing that everywhere so as a result the Input objects were storing the encoded URI which didn't match the URI stored by the connection services. 
Fixes #6829 - and I also did some basic testing to verify that this didn't regress behavior for normal untitled queries.

Fix file URI input

---

src/sql/workbench/browser/modelComponents/formContainer.component.ts

Addresses #6744
formContainer UIs are tables under the hood, so screen readers (unnecessarily) announce them as such.  This adds `role="presentation"` to them by default.  Because dataTables are constructed differently, this change shouldn't impact them.

Silences "table" announcement for all UIs built with formContainer

---

extensions/mssql/package.json
extensions/mssql/src/objectExplorerNodeProvider/fileSources.ts
extensions/mssql/src/objectExplorerNodeProvider/webhdfs.ts
extensions/mssql/src/sqlClusterLookUp.ts
extensions/mssql/yarn.lock
extensions/notebook/src/common/utils.ts
extensions/notebook/src/jupyter/jupyterSessionManager.ts

- HDFS now fully supports expanding nodes for all levels, including using cookie for auth
- HDFS now support reading files from HDFS
- HDFS write file is broken and will be fixed (either in PR update or separate PR)
- Removed hack to use gateway-0 instead of actual DNS name now these are supported. Needed for testing

Fix HDFS with AD auth for browse, read file scenarios

---

extensions/xml-language-features/src/extension.ts

Noticed this issue with #6299. Since the XML is truncated, we throw an error to console when we try to display the results.

Fallback to text if xml parser fails parsing

---

src/sql/workbench/parts/objectExplorer/browser/serverTreeDataSource.ts
src/sql/workbench/parts/objectExplorer/browser/serverTreeView.ts
src/sql/workbench/parts/objectExplorer/browser/treeSelectionHandler.ts
src/sql/workbench/parts/objectExplorer/browser/treeUpdateUtils.ts
src/sql/workbench/parts/tasks/browser/tasksView.ts
src/sql/workbench/services/objectExplorer/common/objectExplorerService.ts

Before this we call the expand/refresh/expandAll codepoints without awaiting their response. This was causing random issues and race conditions with our code depending on how fast you clicked.

OE clicking and awaiting the expansion calls

---

src/sql/workbench/parts/dataExplorer/browser/dataExplorerExtensionPoint.ts

https://github.com/microsoft/vscode/commit/8d67f9b13a0290c57a9ca13b150f752918cbebab broke us since we were using the VS CustomTreeView instead of our own.

Fix custom tree views not displaying

---

extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
src/sql/base/parts/editableDropdown/browser/dropdown.ts
src/sql/workbench/browser/modelComponents/dropdown.component.ts

Addresses #6850. Adds names for Server and database editable dropdowns and file location text box. The radio button names were added in #6835

Add names for schema compare dialog

---

extensions/mssql/src/objectExplorerNodeProvider/hdfsCommands.ts
extensions/mssql/src/objectExplorerNodeProvider/webhdfs.ts

- Implemented write stream piping correctly so data is paused until we're ready to push to server
- During testing, noted that things weren't awaited correctly. Tweaked some functions to improve this
This PR "should" work, but I'm blocked by a 500 error during testing.
I'll likely do fixes in a follow up PR as we need this one to unblock wider testing

Fix HDFS AD write support + improve error logging

---

extensions/dacpac/src/wizard/pages/dacFxSummaryPage.ts
src/sql/azdata.d.ts
src/sql/workbench/api/common/extHostModelView.ts
src/sql/workbench/browser/modelComponents/table.component.ts

This PR contains for for https://github.com/microsoft/azuredatastudio/issues/6729. 
Tables in Extensions need a way to override tab so that tabbing in table cells is not possible and tabbing takes control out of Table - this is the accessibility requirement for tables not having actionable cells. Keeping it as a switch so that we can continue having older behavior where needed.

bug/accessibility 3 - Allow only Arrow navigation 

---

extensions/dacpac/src/wizard/api/dacFxConfigPage.ts
src/sql/azdata.d.ts
src/sql/base/browser/ui/inputBox/inputBox.ts
src/sql/workbench/api/common/extHostModelView.ts
src/sql/workbench/browser/modelComponents/inputbox.component.ts

Addresses #6795
Adds support for the `aria-live` property, which indicates to screen-readers that it had dynamic content which may be updated without focus.  Sets level to "polite" for DacFx wizard file selection controls

Adding aria-live label support for input boxes

---

src/vs/workbench/api/common/extHostTreeViews.ts

This was causing some errors when trying to create the database object trees in the External Table wizard.
This edit was missed in this merge commit: https://github.com/microsoft/azuredatastudio/commit/6f297efb880037dde203a6d2fe5ffaff5c1c1924#diff-9cac4292d1fe863254c28648b24ee20eL193

Re-add carbon edit for handling undefined proxy in extHostTreeViews.

---

extensions/dacpac/src/wizard/pages/selectOperationpage.ts
src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts
src/sql/workbench/browser/modelComponents/table.component.ts

Fix for
#6796 (partial) 
Checkbox cells in table don't have name - fixed
Empty cells in table don't have name - not fixed needs followup
#6800 
After space/enter on checkbox cell - focus doesn't stay correctly on the cell
#6745 
After DacFx wizard opens the focus should shift to the wizard
Regression 
After Lint update checkbox columns were not getting rendered. For --> Foreach change fixes this

Bug/Accessibility fix for 6796 (partial), 6800 and 6745

---

extensions/dacpac/src/wizard/pages/deployPlanPage.ts
src/sql/azdata.d.ts
src/sql/base/browser/ui/table/table.ts
src/sql/workbench/api/common/extHostModelView.ts
src/sql/workbench/browser/modelComponents/loadingComponent.component.ts
src/sql/workbench/browser/modelComponents/table.component.ts

Fixes #6943 and #6826 by adding ability Aria `role` attribute support to tables and loadingComponent objects.
Also adds ability to focus an extension table, though it ended up not being necessary for the fix.

Inform screen-readers of Dacpac Deploy loading and loading complete for summary

---

extensions/integration-tests/src/objectExplorer.test.ts
src/sql/workbench/parts/dashboard/browser/dashboard.contribution.ts
src/sql/workbench/parts/objectExplorer/browser/serverTreeActionProvider.ts
src/sql/workbench/parts/query/browser/query.contribution.ts

Hard code in the Tree built in actions into the menu action array. Not an ideal solution, but it solves the problem.
Having the built in actions contributed is ideal, but I was having a lot of bugs pop up with interacting with the tree from a contributed action.
The build in actions are the server group actions, refresh, disconnect and delete. Which are all intrinsic to the tree so its not a problem that they are not contributed.

Fix context menu positioning.

---

src/sql/workbench/parts/commandLine/electron-browser/commandLine.ts
src/sql/workbench/parts/commandLine/test/electron-browser/commandLine.test.ts

- This already handles commandline which needs same logic
- Includes visual confirmation to avoid connecting by default to untrusted server
- If successful will connect & expand in Connections tree
- If failed, will show dialog with all presets
- Shows New Query by default, can add option for New Notebook instead in the future
Connection protocol is `azuredatastudio://connect?server=mysqldw.database.windows.net&database=db1&user=myusername&aad=true`
Same args as commandline, namely:
- server
- database
- user
- aad
- integrated
I have also added `provider` arg to allow non-MSSQL providers. In the future, we should update logic to prompt for install of correct extension for that provider if it's missing.

Add connect protocol handler to SQL command line service

---

extensions/notebook/src/jupyter/serverInstance.ts

```
--no-mathjax
Disable MathJax
MathJax is the javascript library Jupyter uses to render math/LaTeX. It is
very large, so you may want to disable it if you have a slow internet
connection, or for offline use of the notebook.
When disabled, equations etc. will appear as their untransformed TeX source.
```
Since this is a rendering library that's apparently quite large (and since we do our own rendering in ADS), I investigated to see if we could get any perf gains at startup.
Saw a ~5% reduction in startup time for the `jupyter notebook` command, so it seems like it's worthwhile to start jupyter with this option in ADS.

Start Jupyter without MathJax Library by Default

---

extensions/resource-deployment/src/test/resourceTypeService.test.ts

In the resource-deployment extension's package.json, there are 3 resource types listed: sql-image, sql-bdc, and sql-windows-setup. The first 2 are supported on all platforms, and the third only on windows. I've updated the resource type counts in the Resource Type Service tests to reflect this. I also added some extra information in the error messages, since the test runner outputs a lot of junk characters on windows that makes it hard to see the actual vs expected values.

Update Resource Type Service Tests to use correct number of resource types.

---

src/sql/workbench/parts/notebook/browser/notebook.component.ts

Fixes #6922.
Ensure context key provider set before session start. There was the possibility of the previous value being used when session start happens, and the button being added before the value of the current provider was set.

Fix for Manage Packages Showing Up for SQL Kernel (in some cases)

---

src/sql/workbench/parts/backup/browser/backup.component.ts
src/sql/workbench/parts/backup/browser/backup.contribution.ts
src/sql/workbench/parts/backup/browser/backupActions.ts
src/sql/workbench/parts/restore/browser/restoreActions.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/7017 and https://github.com/microsoft/azuredatastudio/issues/7015
These were some recent regression and would be good to take in Sept.
Back up and restore dialogs from OE context menu were always opening in master context. this fixes the same. For backup additionally the task was starting with metadata around master even when dialog was fixed. Needed to ensure it clones the connection profile in DB context. changing to run as OE action fixed this. (Thanks @anthonydresser for the pointers)

Fixing two backup/restore issues - opening context of dialog and footer color

---

src/sql/workbench/parts/notebook/electron-browser/cellViews/textCell.component.ts

Fixes #7026.
Since cell source can now be an array, we were incorrectly doing comparisons between the previous and new source values in the text component. This meant that the "Double-click to edit" message was gone when a markdown cell is empty.

Notebooks: Fix double-click to edit with source as array

---

src/sql/base/browser/ui/panel/panel.ts

The results tab was showing up as the second tab.

Fix index for panel push

---

src/sql/workbench/parts/query/browser/queryActions.ts

Trimming the text for SQLCMD button to remove the word 'Mode'. This helps with the issue : https://github.com/microsoft/azuredatastudio/issues/7010. We will investigate the hiding button behavior for coming releases...

Trimming the text for SQLCMD button

---

src/sql/platform/query/common/gridDataProvider.ts

Removes the EoL string at the end of the copy string
Fixes #6803

Remove the eol character at the end of the copy string

---

extensions/cms/src/cmsUtils.ts

CMS server wasn't getting removed from the tree when deleted because it was still looking in the old place instead of memento which was recently added.

Fix CMS server deletion from memento

---

extensions/agent/package.json

Looks like the extension version was incorrectly reset during Notebook merge.

Fix agent extension version back to 0.42.0

---

src/sql/workbench/parts/objectExplorer/browser/serverTreeActionProvider.ts

Fixes #7038
With Properties (which adds the separator already)
Without properties or built-in actions :

Don't add unnecessary separator to OE action menu

---

i18n/language-pack-fr/README.md

Corrects keyboard shortcut for the command palette in the French lang pack README: changes from "Ctrl+Alt+P" to "Ctrl+Shift+P"

Fix command palette keyboard shortcut in README.md

---

extensionsGallery.json

Extension that adds a 'Delete' option when right-clicking on a database. It prompts the user to confirm the deletion and refreshes the database tree after.

Added Delete Database extension

---

extensions/schema-compare/src/schemaCompareMainWindow.ts

Partial fix for #6909. Voiceover was also reading the tooltip for these columns, but since the tooltip is the same as the column name it's confusing since it looks like the column name is being announced multiple times. Removing the tooltips because they don't add any additional information.

Remove non-descriptive tooltips from schema compare table

---

extensions/dacpac/src/wizard/api/dacFxConfigPage.ts
extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
extensions/schema-compare/src/schemaCompareMainWindow.ts

Update dacpac and schema compare extensions to not use deprecated workspace.rootPath

Update workspace.rootPath in dacpac and SC extensions

---

extensions/dacpac/src/wizard/pages/dacFxSummaryPage.ts
src/sql/azdata.d.ts
src/sql/platform/dialog/browser/wizardModal.ts
src/sql/platform/dialog/common/dialogTypes.ts
src/sql/workbench/api/common/extHostModelViewDialog.ts
src/sql/workbench/api/common/sqlExtHostTypes.ts
src/sql/workbench/api/electron-browser/mainThreadModelViewDialog.ts

Addresses the request made in https://github.com/microsoft/azuredatastudio/issues/6746#issuecomment-524996846
Adds piping to extension buttons to set focus, and automatically sets the focus to the Done button in the summary page of DacFx wizard paths.

Automatically focus the execute button in the DacFx wizard summary screens

---

src/sql/platform/dialog/browser/dialogContainer.component.ts

Fixes #6824. This makes the wizard page names get announced when the page is changed. Previously, only the wizard name was announced when the wizard first opens.

Make wizard page names get announced by screen reader

---

src/vs/base/browser/ui/tree/media/tree.css

This is by suggestion of @angdesign - 
Before :
After :
Fixes #7117

Remove custom tree indent guide

---

tslint-sql.json

We currently have 450 places where we're getting a promise in a function call and we're not making sure it succeeded, failed, etc.
But essentially unawaited promises are an anti pattern and they __should__ be awaited unless we explicitly decide to not enforce the rule on a certain area.
As Palantir puts it: Unhandled Promises can cause unexpected behavior, such as resolving at unexpected times.

New rule to stop floating promises

---

src/sql/workbench/parts/notebook/browser/notebookStyles.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/7207
Here's a sample from the dark brown theme. The new colors are the ones on top.

Use lighter colors for inline notebook buttons in dark themes.

---

src/sql/workbench/browser/modelComponents/queryTextEditor.ts

Fixes #7246.
Caused by https://github.com/microsoft/azuredatastudio/commit/ea0f9e6ce95b45def2b694efcd8ffe909bc43d20#diff-0308fd66e25b4760ce1a2b0a35757513
`this._lineHeight = editorWidget.getConfiguration().lineHeight;`
was changed to
`this._lineHeight = editorWidget.getRawOptions().lineHeight;`
which returns a lineHeight of 0, as getRawOptions() doesn't include any defaults apparently.
Also added a default just in case.

Fix for Notebook Cell Height Not Resizing

---

extensions/integration-tests/src/objectExplorer.test.ts
extensions/integration-tests/src/utils.ts

Update the OE tests to use the normal connect timeout, rather than the shorter timeouts that are currently in the tests.  We're seeing numerous flaky failures in these tests so I'm not sure why they have reduced timeouts.
I've left the timeout parameters in place (using the default value) in case we want to increase the timeouts above the defaults in specific cases in the future.

Use the default connect timeout in OE tests

---

extensions/big-data-cluster/src/bigDataCluster/constants.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardResourceStatusPage.ts

Fixes #7285
We won't always have logs available for instances so show N/A if none are available.
Also did some clean up of the CSS Styles - I need to go through and do a full pass since we still have a lot of duplicated styles around but I wanted to keep this PR focused.
I also will be going through and adding more null/undefined checks for the values returned for the instance status. We shouldn't be assuming the status is going to always come back with the expected values. Again - going to do that in a separate PR to keep this one focused.

Don't show links for BDC logs if none available

---

src/sql/workbench/browser/modelComponents/queryTextEditor.ts
src/sql/workbench/parts/notebook/browser/cellViews/code.component.ts

Fixes #7252.
setHeightToScrollHeight() in queryTextEditor is an expensive operation, as there isn't a great way to determine how many wrapped lines exist in an editor today.
Looking at some perf logs on notebook loading, rendering tends to take the vast majority of the time on larger notebooks, so we should be calling layout() as few times as possible for each code component.
Problem 1: In code.component.ts, we react to this._editorModel.onDidChangeContent. Inside of that event hook, we directly call this._editor.setHeightToScrollHeight(). We were also calling this._layoutEmitter.fire(), which calls layout(), which calls this._editor.setHeightToScrollHeight().
Problem 2: We called layout() in ngAfterViewInit(). This appears to be unnecessary, as it's already been called when each editor …

Ensure we call layout() as few times as possible for notebook cells

---

src/vs/workbench/services/extensions/common/extensionUrlHandler.ts

Re-doing the pull request from a branch off of microsoft/azuredatastudio. PR from a forked branch was hitting issues.
Closes #6348 
Dialog service starts truncating words longer than 80 characters and adds ellipses to it. To show more of the URL, we can show about 80 characters in the beginning and 80 in the end, with ellipses in between. Changed truncation logic to handle this.
Here is the before/after experience for opening this URL: azuredatastudio://microsoft.notebook/open?url= https%3A%2F%2Fraw.githubusercontent.com%2Fmicrosoft%2Fazuredatastudio%2Fmaster%2Fsamples%2FnotebookSamples%2FSampleTSQLNotebook.ipynb
Before:
After:

Show more of the url. Improve readability of warning messages  (closes #6348)

---

src/sql/media/icons/common-icons.css
src/sql/workbench/parts/notebook/browser/cellViews/code.css
src/sql/workbench/parts/notebook/browser/notebook.css

After the vscode merge which has some styling changes (essentially renamed .icon to .codicon), it effected our current styles.
Fixes both #7325  and #7328

renamed .icon to .codicon as per vscode updates that are merged.

---

extensions/integration-tests/src/dacpac.test.ts
extensions/integration-tests/src/objectExplorer.test.ts
extensions/integration-tests/src/schemaCompare.test.ts
extensions/integration-tests/src/utils.ts

This is expected to fix the tests - will disable test temporarily if this doesn't work too.
The common code between ObjExp and Dacpac tests outside of try-catch is **cleanup of DB** which uses SimpleQueryExecute call to delete dB. This call from sqltoolsservice can throw "Editor not connected" if the connection has been removed while the test is going on. Although I am not able to repro the issue and hence not able to confirm this theory 100% - this seems closest based on the range of tests all containing this path.

Trying to remove intermittent ext test failure

---

extensions/integration-tests/src/dacpac.test.ts

The previous fix didn't seem to work. Disabling for now. Will investigate more this Friday.

Disabling Dacpac import test for insiders build to pass

---

extensions/integration-tests/src/dacpac.test.ts
extensions/integration-tests/src/objectExplorer.test.ts

Using test.skip makes it easier to find disabled tests and includes these tests in the test run output (it'll say how many tests it skipped) which is useful to make sure we don't forget about disabled tests.

Use test.skip instead of commenting out disabled test

---

extensions/integration-tests/src/notebook.test.ts

Until we get a SqlClient fix, these tests will fail. Skipping them for now, after the decision was made in DRI meeting.

Skip failing notebook tests due to sqlclient issues

---

extensions/azurecore/src/extension.ts

There's no reason to check here, we also need to recursively build the directory for our exploration.
recursive mkdir won't throw anything

Don't check if directory exists

---

extensions/notebook/src/jupyter/jupyterSessionManager.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/7315

Use python3 as the default python version in Spark sessions.

---

extensions/dacpac/src/wizard/api/dacFxConfigPage.ts
extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
extensions/schema-compare/src/schemaCompareMainWindow.ts
extensions/schema-compare/src/utils.ts

The way to get the folder path was previously changed in #7125, but it only used the name of the folder so it wasn't working for nested folders. This fixes it to use the correct folder path.

Fixing folder path in dacpac and schema compare extensions

---

extensions/resource-deployment/src/ui/deployClusterWizard/deployClusterWizard.ts
src/sql/workbench/browser/modal/media/modal.css

right now, our dialog buttons are fixed width, I ran into a problem that the text doesn't fit anymore. Consulted @angdesign yesterday and he confirmed it is totally to have buttons with different width on one screen. Azure portal is an example.

rename button and update dialog button width

---

extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts

1. add required field indicator for the accept eula checkbox
2. clear the missing tools error message when switching resource types.

fixes #7383 and #7380

---

extensions/query-history/package.json
extensions/query-history/package.nls.json
src/sql/platform/queryHistory/common/queryHistoryService.ts
src/sql/platform/queryHistory/common/queryHistoryServiceImpl.ts
src/sql/workbench/parts/queryHistory/browser/queryHistoryActionProvider.ts
src/sql/workbench/parts/queryHistory/browser/queryHistoryActions.ts
src/sql/workbench/parts/queryHistory/browser/queryHistoryController.ts
src/sql/workbench/parts/queryHistory/browser/queryHistoryPanel.ts
src/sql/workbench/parts/queryHistory/browser/queryHistoryView.ts
src/sql/workbench/parts/queryHistory/electron-browser/queryHistory.contribution.ts
src/sql/workbench/parts/queryHistory/electron-browser/queryHistory.ts

Closes #7360
Add command and actions for clearing all history. 
These show up in :
Command Palette 
Context Menu on tree items
Action button on panel toolbar
Note that I wasn't able to find an easy way to include it in a general context menu for the whole panel - it's only on existing items in the tree. Will investigate further but for now this should be enough to address the major part of the feature.
Also fixed bug where the "No queries to display" message wouldn't show up after clearing all existing entries.

Add Clear All Query History command/action

---

extensions/notebook/kernels/powershell/kernel.json

Add powershell kernel.json so that users don't have to run the extra step when using the powershell kernel to copy the file over to a Jupyter-friendly location.
We already do the same thing with other kernels, just using prior art here 😄

Add powershell kernel.json

---

extensions/agent/src/dialogs/jobDialog.ts
extensions/agent/src/dialogs/notebookDialog.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboard.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardResourceStatusPage.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/bdcServiceStatusPage.ts
extensions/mssql/src/dashboard/bookWidget.ts
extensions/mssql/src/dashboard/serviceEndpoints.ts
extensions/resource-deployment/src/ui/modelViewUtils.ts
extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts
samples/sqlservices/src/controllers/mainController.ts
src/sql/azdata.d.ts
src/sql/sqlops.proposed.d.ts

Noticed that we were using align-items with the value 'left' in a lot of places, but that's not an actual valid value per https://developer.mozilla.org/en-US/docs/web/css/align-items#Values. Adding types to help prevent this in the future.
Note that I just removed the alignItems: 'left' values instead of changing them to something else (like justify-content: 'start') since whoever made this to start with was happy with the look despite that property not actually doing anything - so removing them isn't going to change anything.

Add types for ModelView CSS properties

---

src/sql/workbench/parts/notebook/browser/cellViews/code.component.ts
src/sql/workbench/parts/notebook/browser/cellViews/outputArea.component.ts

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent via https://stackoverflow.com/questions/19669786/check-if-element-is-visible-in-dom 😄 
This fixes the issue that @vickyharp was encountering where you could type into the wrong notebook, as we always grabbed focus on whatever code cell was being executed.
Also did the same check for output areas, as it's silly to grab focus/scroll when it's not in view. May be the cause of another bug there that we didn't know about yet.

Stop grabbing focus when nb editor isn't in view

---

extensions/azurecore/src/extension.ts

{recursive: true} is supposed to not let the EEXIST error be thrown but electron decided to treat it differently.

Create the azure folder differently.

---

extensions/integration-tests/src/objectExplorer.test.ts
extensions/integration-tests/src/utils.ts

This test is failing on linux because getChildren() times out. I'm not sure what the cause is but this shouldn't be blocking PR validation.

Disable one test and add a new utility function

---

extensions/resource-deployment/package.nls.json
extensions/resource-deployment/src/main.ts
extensions/resource-deployment/src/ui/deploymentInputDialog.ts
extensions/resource-deployment/src/ui/dialogBase.ts
extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts

1. fixes #7489. vscode made some changes and will pass extra arguments to the command, adding argument type check and use default resource type if the argument is not string typed.
2. rename the "Open SQL Server deployment dialog" menu to "More deployment options..." to avoid confusion, I've seen people raising question about this multiple times.
3. Refactor the disposable handling logic into the DialogBase class.

fix issue 7489 and disposable handling

---

src/vs/platform/update/common/update.config.contribution.ts
src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts
src/vs/workbench/contrib/update/browser/update.ts

Fix to open ADS release notes instead of VS Code

---

src/sql/setup.js
test/electron/renderer.js

Reverts microsoft/azuredatastudio#7499
Keeping this for later when I can do more tests.

Revert "Revert "allows zone.js to cleanup error stacktraces""

---

src/sql/workbench/parts/notebook/browser/models/notebookTextFileModel.ts
src/sql/workbench/parts/notebook/test/browser/notebookEditorModel.test.ts

This fixes #7468.
We weren't escaping double quotes and backslashes correctly, which meant that we were serializing incorrectly to JSON when serializing directly from the text file service (i.e. File --> Save As to different filename, or rehydrating an unsaved notebook).
Note that the following scenarios would not be impacted:
File --> Save (i.e. save as same filename)
File --> Save As WHEN one of the following is true, even after typing cell content with double quotes/backslashes:
- A cell was added/deleted
- Kernel change occurred
- Trusted state change occurred
The (incorrect) assumption previously was that what was in the editor could be mapped 1:1 with what was mapped in the text editor model. Unfortunately, this is not the case, we need to escape double quotes and backslashes. …

Notebooks: Ensure quotes and backslashes are escaped properly in text editor model

---

extensions/admin-tool-ext-win/src/test/index.ts
extensions/agent/src/test/index.ts
extensions/azurecore/src/test/index.ts
extensions/cms/src/test/index.ts
extensions/dacpac/src/test/index.ts
extensions/notebook/src/integrationTest/index.ts
extensions/notebook/src/test/book/book.test.ts
extensions/notebook/src/test/index.ts
extensions/resource-deployment/src/test/index.ts
extensions/schema-compare/src/test/index.ts
scripts/sql-test-integration-unstable.bat
scripts/sql-test-integration-unstable.sh
scripts/sql-test-integration.bat
scripts/sql-test-integration.sh
scripts/test-extensions-unstable.bat
scripts/test-extensions-unstable.sh
scripts/test-extensions.bat
scripts/test-extensions.sh
scripts/test-unstable.bat
scripts/test-unstable.sh
scripts/test.bat
scripts/test.sh
test/electron/index.js
test/electron/renderer.js

Enables marking both ADS Core tests and Extension tests with @UNSTABLE@ for running separate from main test runs. 
Lots of duplication with the index.ts stuff - at some point we should look into consolidating that into our own test running like vscode has that all our extensions use but for now this is fine to get up and running quickly.

Add unstable test params for core and extension tests

---

extensions/mssql/src/hdfs/ui/hdfsManageAccessDialog.ts
src/sql/azdata.d.ts
src/sql/sqlops.proposed.d.ts
src/sql/workbench/api/common/extHostModelView.ts
src/sql/workbench/api/common/sqlExtHostTypes.ts
src/sql/workbench/browser/modelComponents/inputbox.component.ts
src/sql/workbench/browser/modelComponents/interfaces.ts

This is mostly useful for dialogs where hitting enter within an input box will cause the form to be validated and possibly closed - which isn't always the desired behavior (such as for the HDFS Manage Access dialog)

Add ability to handle enter key propagation for input model components

---

extensions/schema-compare/src/schemaCompareMainWindow.ts
src/sql/workbench/browser/modelComponents/diffeditor.component.ts

This fixes the error in #7357 and the split view with the differences table and diff editor not showing. The behavior change was caused by the vs code merge  ea0f9e6ce95b45def2b694efcd8ffe909bc43d20.

Fix #7357 schema compare results not showing

---

src/sql/setup.js

This reverts commit d91488da6283d42e119667e3bb6367a74cc09799.
Fixes #7562. Don't know exactly why this is breaking but a build produced without this change works as expected.

Revert zone.js changes

---

extensions/integration-tests/src/cms.test.ts
extensions/integration-tests/src/dacpac.test.ts

Marks some tests as @REL@, these tests will get run in the release builds even if they're tagged as unstable.

Release tests

---

extensions/notebook/src/dialog/managePackages/managePackagesDialog.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/7264
RegisterCloseValidator doesn't affect the Cancel button in the dialog, only the OK button (which is hidden here) and the Enter key.

Block Enter key from closing Manage Packages dialog.

---

src/sql/azdata.d.ts
src/sql/sqlops.proposed.d.ts
src/sql/workbench/api/common/extHostModelView.ts
src/sql/workbench/browser/modelComponents/componentBase.ts
src/sql/workbench/browser/modelComponents/flexContainer.component.ts
src/sql/workbench/browser/modelComponents/text.component.ts

This is for upcoming changes I had for the HDFS Manage Access dialog.
Note that note all components implement this - I wanted to keep the changes scoped so while all components have access to the property changes to the template will be needed to be made first. 
I also just updated the normal text portion of the Text Component since it's trickier for the text+info version - again if needed for that in the future we can update the template at that point.

Add display property to ModelView components

---

extensions/notebook/src/book/bookTreeView.ts
extensions/notebook/src/extension.ts

Fixes an issue where the Jupyter Books viewlet wouldn't show anything if a user navigated to it immediately upon opening ADS.
There was a race condition with how the viewlet was originally written, as we weren't properly awaiting async methods, so calls that relied upon this.books being fully populated would instead see this.books as an empty array.

Fix async problem with jupyter book viewlet loading

---

extensions/dacpac/src/wizard/api/dacFxConfigPage.ts
extensions/dacpac/src/wizard/pages/deployConfigPage.ts
extensions/dacpac/src/wizard/pages/importConfigPage.ts

Fixes the wrong label in #6731. Previously it was "Database" instead of "Target Database"

Fix aria labels for dacfx wizard database text boxes

---

src/sql/workbench/services/connection/browser/connectionWidget.ts

Fixes #7565
The server group input was only storing the name of the group - not the full path name - which didn't work because when we populate the dialog we use the group full name.
Changing it so the input now stores the full group name not only fixes this issue but is actually a better experience overall - previously if you had groups with the same name but different paths you'd have no way to know which option was which 
Now since we show the full path it's much clearer (and fixes the issue above so that we select the group correctly not)

Fix connection group input not correctly selecting nested groups

---

src/sql/azdata.d.ts
src/sql/workbench/api/common/extHostNotebookEditor.ts
src/sql/workbench/parts/notebook/browser/models/cell.ts

Fixes https://github.com/microsoft/azuredatastudio/issues/7306
Tried to add an integration test for this, but apparently we don't correctly update the contents in the notebook object returned by openNotebook after inserting a cell. That's a pretty big bug that we need to fix. Manually verified that this works instead.

Add collapsed argument to insertCell extension method.

---

extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardResourceStatusPage.ts

Make health status header wider so text isn't multiline

---

src/sql/workbench/browser/modelComponents/checkbox.component.ts

The div shouldn't have the height and width since that's handled by the checkbox component itself. Putting the height/width on the div breaks the view when a label is added :
After fix :
This is the same thing that the button component does.

Fix checkbox component layout

---

src/sql/workbench/parts/notebook/browser/cellToggleMoreActions.ts

After:
Just adding in separators and changing the order per UX spec.

Adding in separators to notebook cell context menu

---

extensions/big-data-cluster/src/bigDataCluster/utils.ts

Technically this is unnecessary (undefined is returned by default) but it's good to be explicit with returns.

Add return to getControllerEndpoint

---

extensions/big-data-cluster/package.json
extensions/big-data-cluster/package.nls.json
extensions/big-data-cluster/src/bigDataCluster/controller/clusterControllerApi.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/mountHdfsDialog.ts
extensions/big-data-cluster/src/extension.ts

- Delete mount action added
- Refresh mount action added
- Added "mymount" to the end of existing path so that we don't use already-existing HDFS folder. The call fails unless folder doesn't exist
**Screenshots**
Refresh
Delete
Status:

Mount delete, refresh and default to new folder for mount create

---

extensions/notebook/src/jupyter/jupyterServerInstallation.ts

A lot of packages can get installed during upgrades, so if there's another install in progress there can be some file permission failures due to trying to overwrite the same packages.

Skip prompting for package upgrade if a python install is already in progress.

---

src/sql/workbench/browser/modal/modal.ts

Addresses followup in #6728 where the dialog is announced as document, but it shouldn't be announced.

Fix screenreader announcing document for dialogs

---

extensions/agent/src/data/notebookData.ts
extensions/agent/src/mainController.ts

Handling issue mentioned in #7274 where an unsaved notebook resulted in an "invalid notebook path" error, the code now detects if the name of the "path" could be a valid filename via a regex and asks the user to save the notebook before the process can be started. Ideally there needs to be a way to have a save prompt or window pop up so that the user can save immediately onto the disk. Currently it simply prints an error asking the user to save first.

Added notification for unsaved file in scheduling

---

extensions/notebook/src/jupyter/jupyterServerInstallation.ts

A side effect of this change that I noticed is that if we have multiple notebooks waiting to start on Windows, then all but one will fail to start due to them all trying to copy the same kernel definitions at the same time. Seems like that would go away once we move to having a single jupyter server for all the open notebooks, so I won't try to fix it here.

 Wait for python installs to complete before starting a python notebook.

---

src/vs/base/parts/tree/browser/treeView.ts

Temporary fix for #7715. I dug into this a bit but it seems like it might be a VS Code issue so rolling back until we can figure out for sure.

Roll back tree icon merge changes to fix loading icon issue

---

extensions/integration-tests/src/notebook.test.ts

Fixes #7347
SqlClient fix is in so these should be stable again (they've been passing successfully for a while now)

Move Notebook tests back to stable

---

src/sql/workbench/parts/connection/common/connectionProviderExtension.ts
src/vs/workbench/services/extensions/common/extensionsRegistry.ts

Currently the only way to check to see if an extension already has its icon resolved is to see if its light and dark components are URIs or not (It will not parse it if its already has been parsed). There is currently no visible registry or list that can be used to check if an extension has its path resolved or not. Ideally the best solution for this would be to prevent executing resolveIconPath or processing the extension entirely. This is to handle an issue shown in #7471

Handling for parsing of iconpaths

---

extensions/integration-tests/src/notebook.test.ts

These tests have failed on a few PR builds - we might have to mark them as unstable?
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=42195&view=results

Revert "Move Notebook tests back to stable"

---

.vscode/launch.json
src/vs/workbench/contrib/welcome/gettingStarted/electron-browser/telemetryOptOut.ts

Also added debug targets for running/debugging extension integration tests and increased timeout for attach since it can take a while to start up the process

Fix TelemetryOptOut error for tests

---

extensions/resource-deployment/src/ui/deployClusterWizard/pages/clusterSettingsPage.ts

mistakenly left the docker password field as plain text instead of password, now fixing it.

change field type to Password

---

package.json
yarn.lock

This was removed in a vscode merge a while back but they've since added it back, doing this now since it's annoying for new/clean repos to not have these hooks
https://github.com/microsoft/vscode/commit/23059a783ee0dea354b273ab3cd2ca3384ab3bb7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Add husky back for precommit hooks

---

src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts

Problem: for multiple queries in the same batch, we were executing one query, rendering the results, and only then executing the next query, etc..
Instead, we can kick off all of the queries (i.e. the getQueryRows() call) in parallel, and we only need to wait to get rows for whatever table we need to render at any given time.
For the following query:
SELECT * FROM sys.all_objects
GO 30
267003 ms - before change (from when cell was run until the doneDeferred was resolved)
158757 ms - after
= ~40% decrease in time between when cell was run

First improvements for SQL Cell Looping

---

extensions/mssql/src/localizedConstants.ts
extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts
extensions/mssql/src/sparkFeature/dialog/sparkJobSubmission/sparkAdvancedTab.ts
extensions/mssql/src/sparkFeature/dialog/sparkJobSubmission/sparkConfigurationTab.ts
extensions/mssql/src/sparkFeature/dialog/sparkJobSubmission/sparkJobSubmissionDialog.ts
extensions/mssql/src/sparkFeature/dialog/sparkJobSubmission/sparkJobSubmissionModel.ts
extensions/mssql/src/sparkFeature/dialog/sparkJobSubmission/sparkJobSubmissionService.ts

The sparkJobSubmission loc keys are in the format sparkJobSubmission_<subkey> however when xlfs are changed to localized xlfs - the subkey after _ gets dropped.After this while converting to xlf --> loc json dup keys miss to get added.
All other modules' keys use "." in place of "_" so keeping the same pattern here to so that next wave of xlf creation picks up the right keys. Doing this now so that I don't miss later.

Fix Loc keys for spark so that dup key error doesnt occur

---

extensions/big-data-cluster/src/bigDataCluster/controller/clusterControllerApi.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardModel.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/connectControllerDialog.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/hdfsDialogBase.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/mountHdfsDialog.ts
extensions/big-data-cluster/src/common/promise.ts

Here's my take on updating the code to re-prompt for connection information if the status queries for the BDC dashboard fails. 
Note that currently this is based off of my open cluster dashboard PR - since this depends on changes made there so I didn't want to send out this PR with duplicate changes. I'll rebase this once that one is in.
Features in this PR :
- Changed generic HDFS dialog class to be able to return a value from the call to showDialog(). Essentially if the dialog is validated successfully we then return the value that the model is specified to return - otherwise we'll throw an error (for example if the user cancels out of the dialog)
- Added a new dialog that's just for connecting to a controller (so unlike the Mount ones it doesn't add any other sections itself)
- Added …

BDC Dashboard connection retry

---

src/sql/workbench/browser/modelComponents/componentBase.ts
src/sql/workbench/browser/modelComponents/inputbox.component.ts
src/sql/workbench/browser/modelComponents/tree.component.ts

Fixes #6153
This will apply to all ModelView trees, but I feel like that's the correct behavior - that if enter is pressed while a tree is focused it shouldn't go outside of the tree regardless of what it's contained in.

Fix ModelView tree A11y issue

---

extensions/mssql/src/hdfs/hdfsModel.ts

Pressing enter in a blank input box was adding a user with a blank name.

Fix Manage Access dialog to not allow entering blank user

---

build/lib/extensions.js
build/lib/extensions.ts

These extensions should be included with ADS, but in https://github.com/microsoft/azuredatastudio/commit/4dd6db57ee5e01841d84eed805a59c1b4fab1cd1 they were changed to be built as separate VSIX's. 
Fixes #7859

Fix BDC and resource-deploy extensions to not be packaged separately

---

src/sql/workbench/parts/notebook/browser/notebook.contribution.ts
src/sql/workbench/parts/notebook/browser/outputs/factories.ts
src/sql/workbench/parts/notebook/browser/outputs/widgets.ts

Fixes #7786. Adds (what is now) a dummy IPyWidgets renderer to ensure that we can prevent the spark kernels from falling back to ugly text output.
After the fix, with the PySpark kernel:

Add (dummy) IPyWidgets Renderer

---

extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts

fixes #7866 
I have removed this during my code refactoring, during the conflict resolution, Arvind took it back. now the method is being called twice. This is now being handled by the dialogbase class

fix the wizard opened twice issue #7866

---

src/vs/platform/extensionManagement/common/extensionGalleryService.ts
src/vs/platform/extensions/common/extensions.ts
src/vs/workbench/contrib/extensions/browser/extensionTipsService.ts
src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts
src/vs/workbench/contrib/extensions/browser/extensionsActions.ts
src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts
src/vs/workbench/contrib/extensions/common/extensions.ts
tslint.json

Adds heavier linting to vs code making it easier to do other types of refactoring and linting. To do this I had to move some interfaces and consts that were needed from platform but were located in workbench.

Move code for more linting

---

extensions/integration-tests/src/notebook.test.ts

This test has been failing every once in a while.

Add a new unstable test

---

src/vs/platform/telemetry/test/electron-browser/commonProperties.test.ts

We don't add in those properties for stable builds currently so disabling until they're added back in. 
#7881

Disable failing test

---

extensions/big-data-cluster/.vscodeignore
extensions/big-data-cluster/package.json
extensions/big-data-cluster/src/bigDataCluster/controller/apiGenerated.ts
extensions/big-data-cluster/src/bigDataCluster/controller/clusterApiGenerated2.ts
extensions/big-data-cluster/yarn.lock
extensions/resource-deployment/.vscodeignore

Remove the test stuff - we're not using it currently.
Remove node type reference, we get it from the root typings file. The version this extension was referencing was old and contained a [deprecated alias of ClientResponse](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29674#issuecomment-430028328). So also updating that to IncomingMessage - the correct type to use (and verified that API calls still function as expected).

Clean up bdc devDependencies

---

extensions/mssql/src/hdfs/webhdfs.ts

Fixes #7885
A previous change removed the encoding since we were already encoding the URL options in the call to querystring.stringify so it was double-escaping them. 
https://github.com/microsoft/azuredatastudio/pull/7378/files
We still don't want to do the encodeURI for the entire endpoint URL to avoid this - but now we weren't escaping the path correctly so anything with invalid characters was causing an error to occur.
Note - I also fixed the accident removal of setting the user option. This was done mistakenly in a previous PR as well.

Fix HDFS paths to be encoded properly

---

src/sql/workbench/browser/modelComponents/table.component.ts

Fixes #6729. For accessibility, tabbing to a table shouldn't be allowed if the table cells aren't actionable. Previously, if arrow keys were used to navigate into the table, pressing tab for the first time would go to the next cell, then the following tab would exit the table. This fixes that so the first tab will leave the table.

Don't allow tabbing into table

---

src/sql/workbench/parts/notebook/browser/notebook.contribution.ts
src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts

Implements #7862.
Adding option to halt notebook execution when an error occurs with the SQL kernel.
I've defaulted this option to true (as it would match the behavior of other kernels), but totally willing to listen to feedback and change this if this could break existing scenarios.
@yualan can you help as well give some feedback? Also, I probably need help on the strings 😄.

Add Option to Halt Notebook when Error Occurs in SQL Kernel

---

src/sql/workbench/parts/notebook/browser/outputs/notebookMarkdown.ts

In notebook outputs, links are rendered in notebookMarkdown. The method was being returned too quickly, as we want to ensure that a relative path isn't displayed (and we convert it to an appropriate absolute link) in order to prevent ADS from thinking that notebooks live in the extensions folder.

Fix for relative links not being resolved in notebook outputs

---

src/sql/workbench/parts/notebook/browser/cellViews/code.component.ts

Fixes #7961 
Easiest repro was:
- Run "long-running" notebook (with sleeps if necessary 😄)
- Bring another app into focus
- Wait
- Go back to ADS, notice there is a blinking cursor for every cell that ran

Notebooks: Fix Multiple Cursor Issue when ADS not in Focus

---

extensions/notebook/src/jupyter/jupyterNotebookManager.ts
extensions/notebook/src/jupyter/jupyterServerManager.ts
extensions/notebook/src/jupyter/jupyterSessionManager.ts

We add to the path when starting notebooks, which was getting lost when starting sessions due to recent changes in how we use start up servers (we were just passing on whatever the value of PATH was instead of prepending the ADS-specific folders to the PATH)
LocalJupyterServerManager waits on JupyterServerInstallation to complete (i.e. when the pythonPathEnvVars are set), and a session is created in the JupyterNotebookManager with the serverManager already passed in. Long way of saying that the path will be set before the code in the session is run.

Notebooks: ensure python path dirs added to path on session start

---

extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardModel.ts

Fixes #7977
Undefined is use for the overview page (since it's not associated with an actual service)

Fix troubleshoot URL lookup

---

extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardResourceStatusPage.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/commonControls.ts

Improvement for #7510
This is from feedback that using the error toast is confusing. We still want to figure out a better way to display these though - this is just a temporary solution.
ctrl + c can be used to copy the text. We have the ability to add buttons to the dialog that can have actions associated with them (so we could add a "Copy Text" button) but vs code api limitations means that these buttons will always close the dialog which doesn't seem very friendly so I decided not to add that.

Change BDC view errors to use modal dialog instead of error toast

---

extensions/notebook/package.json

Hide the save book action from command pallet since it should only be exposed from the untitled book tree and doesn;t make sense to have it exposed from a common place. 
Leaving the search book action since they can still launch it and it doesn't error out when there aren't books. I can look into hiding it out when there aren't any active books.

hide save book action from command pallet

---

src/sql/workbench/parts/notebook/browser/cellToggleMoreActions.ts

I don't like this. But the canRun() method only takes into account CellContext, not the other items in the items array. If anyone has any other ideas please let me know 😄 
Fixes #7785.
Code cells:
Text cells:

Notebooks: Fix starting and separators in a row

---

build/builtInExtensions-insiders.json
build/lib/builtInExtensions.js

Replacing the builtinExtension-insiders with builtinExtension since we moved the extension details to stable. Missed this update in my previous insidersTostable commit.

builtinExtension-insiders to builtinExtension

---

extensions/notebook/src/jupyter/jupyterKernel.ts

Fixes #7514
Jupyter always strips out the \r (if it exists), so this matches their behavior.

Always send \n instead of \r\n to Jupyter kernel

---

extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts

Very simple fix, since this is essentially still an error but is fixable by installing the tools, this type of situation can be classified as an error as requested in #7903 for all instances it is called. Unless this is ONLY meant to be done for BDC deployment errors, in which case, additional checks will need to be implemented.
This PR fixes #7903

reclassified autoinstallrequired message to error

---

extensions/notebook/package.json

Fixes #7917 
(the second part 😄)
We really don't need search book in the command palette, and given that it doesn't do anything unless the books viewlet is in focus, let's just always hide it from there. It's more confusing than anything else.

Remove Search Book Commands from Command Palette

---

src/sql/workbench/parts/notebook/browser/models/notebookModel.ts

Fixes #7280
The problem was that we were firing the notebook model's kernelChangeEvent too early, before the model updated `_savedKernelInfo`. In addition, we were also not previously waiting for configureKernel() or an updated languageInfo before sending the event, which wasn't good news either.
Here was the previous behavior:
- notebookModel: `kernelChanged()` event fired (from clientSession kernelChange completed)
- notebookEditorModel: listens on `model.kernelChange()`
- notebookTextFileModel asks notebookModel for its `toJson()`
- notebookModel serializes kernel info from  `this._savedKernelInfo` (which is now outdated)
- notebookModel sees that the `await this._activeClientSession.changeKernel()` has returned
- notebookModel calls `updateKernelInfo()`, updating …

Fix Issue when Saving Wrong Kernel

---

src/sql/workbench/parts/scripting/browser/scripting.contribution.ts

Adjusting for sql on demand:
- Hiding 'Edit Data'
- Hiding 'Script as create' for tables and views

Adjusting context menu for SqlOnDemand

---

src/sql/workbench/parts/notebook/browser/models/cell.ts

Fixes #8010 
Needed to send the stdIn input reply on cell cancel to prevent the kernel from hanging (as it's waiting on the stdIn response)

Fix for Canceling Cell while StdIn Visible Breaking Notebook Execution

---

extensions/notebook/src/jupyter/jupyterServerManager.ts
src/sql/workbench/parts/notebook/browser/models/clientSession.ts

Fixes #8016 
There are some details in the bug, but the lowdown is the following:
- The serverManager knows best when a server needs to be started; the clientSession just talks to mainThreadNotebook to ask around whether a server needs to be started, but mainThreadNotebook uses a crappy heuristic to determine this. Better to talk directly to the source.
- Actually set `this._jupyterServer` to undefined when stopping server in the jupyterServerManager, so that future calls to `startServer()` actually go through the whole... starting a server... codepath 🤒

Ensure Jupyter Server Started After Nb Provider Change

---

extensions/resource-deployment/package.json
extensions/resource-deployment/src/interfaces.ts
extensions/resource-deployment/src/services/tools/toolBase.ts
extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts

This is not the final experience of how we want the version check to be, the main purpose of this PR is to stop the user from moving forward if they don't have the correct version. right now we only need to check the version of azdata, for other tools, we haven't experienced any issues so far.
This PR fixes #8021

min version check

---

extensions/notebook/src/common/utils.ts
extensions/notebook/src/jupyter/serverInstance.ts

Fix a couple hygiene errors for non-double quoted args to localize
@corivera This should have been caught by the precommit hooks. Can you check your .git\hooks folder and make sure you have a file named `pre-commit` (no extension)?

Fix hygiene errors

---

extensions/azurecore/extension.webpack.config.js
extensions/azurecore/package.json
extensions/azurecore/src/azureResource/commands.ts
extensions/azurecore/src/azureResource/interfaces.ts
extensions/azurecore/src/azureResource/providers/database/databaseService.ts
extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerService.ts
extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerProvider.ts
extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerService.ts
extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerTreeDataProvider.ts
extensions/azurecore/src/azureResource/providers/resourceTreeDataProviderBase.ts
extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceService.ts
extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceTreeDataProvider.ts
extensions/azurecore/src/azureResource/services/subscriptionService.ts
extensions/azurecore/src/azureResource/tree/accountTreeNode.ts
extensions/azurecore/src/azureResource/tree/subscriptionTreeNode.ts
extensions/azurecore/src/extension.ts
extensions/azurecore/src/test/azureResource/resourceService.test.ts
extensions/azurecore/src/test/azureResource/resourceTreeNode.test.ts
extensions/azurecore/src/test/azureResource/tree/accountTreeNode.test.ts
extensions/azurecore/yarn.lock

- Refactored to use @azure/arm-resourcegraph for all queries
- Refactored database lookup to do just 2 queries, and make these run in parallel
(all servers, all DBS) instead of waiting serially on 1 query per RG
- This fixes significant perf issues expanding the databases node (from 10+ seconds to a couple of seconds)
- Added Azure Database for PostgresSQL Servers support in the tree
- Removed use of older azure APIs in preference to ones compatible with resource graph
- Note: Had to use v1.0 of new subscriptions package because resourcegraph is 2month out of date vs all other packages

Azure: add PostgresSQL support and refactor to use resource graph

---

src/sql/azdata.d.ts
src/sql/workbench/api/common/extHostModelView.ts

Fixes #5970
This was partially fixed in https://github.com/microsoft/azuredatastudio/commit/bd15a96b836669ee2d481d1aa3730c9eef1ac469 but wasn't working for loading components since they're a bit special in that the loading component (that was having the aria-label attribute added) was being replaced with the actual child component when it finished loading and thus doesn't have the correct aria-label.
I chose to do this here instead of in the actual loading component class because in general I think it's appropriate for a loading component and its child component to have different labels. But in this case we want the title to apply to both so they're announced correctly regardless.

Fix aria label for form loading components

---

src/sql/platform/query/common/gridDataProvider.ts

Fixes #7931
Sorts the rows and columns

Cleanup the copy output

---

extensions/azurecore/package.json
extensions/liveshare/package.json

This PR fixes https://github.com/microsoft/azuredatastudio/issues/8070
The reason was that it was failing in the extension packaging task, where it would error out because a couple of extensions didn't have the `repository` field in its `package.json` file

Add repository field for extensions

---

extensions/notebook/package.json
extensions/notebook/package.nls.json
extensions/notebook/src/extension.ts

For #7990 : Added command that opens the localized book content (https://aka.ms/localized-BDC-book) in the browser. Temporary experience for users to get to localized books. 
Command: "Jupyter Books: Get localized BDC troubleshooting book"

added openLocalizedook action that opens up the link to localized books.

---

extensions/mssql/src/mssql.d.ts
extensions/mssql/src/schemaCompare/schemaCompareService.ts
extensions/schema-compare/src/schemaCompareMainWindow.ts
extensions/schema-compare/src/test/testSchemaCompareService.ts
src/sql/azdata.d.ts
src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts
src/sql/workbench/api/common/extHostModelView.ts
src/sql/workbench/api/common/sqlExtHostTypes.ts
src/sql/workbench/browser/modelComponents/table.component.ts

Fixes #7157. Previously, the schema compare differences table wasn't updating the inclusion state of other differences that were affected by the checking/unchecking of a different row. This fixes that by updating the checkboxes of affected dependencies and also resetting the checkbox state if the include/exclude request failed.

Fix schema compare include/exclude behavior

---

extensions/dacpac/package.json
extensions/schema-compare/package.json

Dacpac and Schema Compare extensions are going to be GA so this bumps their versions to 1.0.0 and removes the preview. Will remove the preview flag in the extensionsGallery in another PR. Addresses #8085

Bump dacpac and schema compare extension versions and remove preview

---

src/sql/base/browser/ui/checkbox/checkbox.component.ts
src/sql/base/browser/ui/selectBox/selectBox.ts
src/sql/base/parts/editableDropdown/browser/dropdownTree.ts
src/sql/workbench/browser/modelComponents/card.component.ts
src/sql/workbench/browser/modelComponents/componentBase.ts
src/sql/workbench/browser/modelComponents/inputbox.component.ts
src/sql/workbench/browser/modelComponents/tree.component.ts
src/vs/base/browser/ui/selectBox/selectBox.ts
src/vs/base/browser/ui/selectBox/selectBoxCustom.ts

Fixes #5976
Fixes #5968
Fixes #5741
Fixes some more cases where keyboard events for enter were being propagated up after a control was handling them, causing any parent controls (such as wizard) to get them and possibly have unintended side effects such as moving to the next page.

Fix modal event propagation

---

src/sql/workbench/browser/modal/modal.ts
src/sql/workbench/services/backup/browser/backupUiService.ts

This PR fixes #5930. The modal dialog in ADS has the logic for trapping the tab. However it was not comparing against the right first and last tabbable elements. As a result the tab order could bleed into elements in the background in ADS, outside of the modal dialog. This fix includes the following:
- Find first and last tabbable element on the _bodyContainer, which includes all items in the dialog. This gets the code back in the state it was in August.
- Determine the first and last element on every tab press. The contents of the dialog can change. Just remembering the elements in the beginning does not help.
- Separate the logic for setting the focus on the most logical element in a wizard. This executes once for the dialog. And does not conflict with the tab trapping logic for modal …

Tab trap for modal (closes #5930)

---

extensions/resource-deployment/src/services/notebookService.ts

the accept_eula env variable needs to be set for first time use of azdata. the scenario we are using azdata to execute the notebook already has the accept EULA checkbox.
this pr fixes #8112

accept azdata eula

---

extensions/resource-deployment/src/services/notebookService.ts

Reverts microsoft/azuredatastudio#8114
will use a more scoped approach instead of process.env

Revert "accept azdata eula"

---

extensions/big-data-cluster/src/bigDataCluster/constants.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboard.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardModel.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts
extensions/big-data-cluster/src/bigDataCluster/utils.ts
src/sql/workbench/browser/modelComponents/divContainer.component.ts
src/sql/workbench/browser/modelComponents/loadingComponent.component.ts

For #7721
Add error messages when service calls for BDC dashboard fail or user cancels out of connect dialog.

Add error messages to BDC dashboard page

---

src/sql/workbench/parts/profiler/browser/profilerActions.ts

vscode renamed the icon, update the code to use the new name.
I tried to have this icon in our own code to remove this dependency, but I couldn't find such svg files in our own icons folder. let me know if you guys think we should not have this dependency.
This PR fixes #8130

fix the missing icon issue of expand/collapse btn

---

extensionsGallery-insider.json
extensionsGallery.json

This PR updates Dacpac and Schema compare ext. versions to latest (Jumps to 1.0.0) in gallery.

updating DacPac and SC ext to latest versions

---

extensions/big-data-cluster/src/bigDataCluster/controller/clusterControllerApi.ts

connectWithRetry needed to pass as ... so each arg was set correctly,
instead of having 1st param be an array of the input arguments

Fix #8159 Mount HDFS broken against latest cluster

---

extensions/big-data-cluster/src/bigDataCluster/controller/clusterControllerApi.ts
extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardModel.ts
extensions/big-data-cluster/src/extension.ts
extensions/mssql/src/main.ts

For #8102
We weren't calling saveControllers after updating the info in the dashboard model so while the info was updated for the current session if you closed ADS and tried to connect again we'd prompt for the password again. 
Also fixed it to use the actual value of the remember password option for the node so that we don't overwrite it to false each time. #8136 opened up to cover us not having remember password being an option in the connect controller dialog. 
And finally fixed issue where we weren't saving the controller node when opening from the SQL dashboard if the connection information was right. (If it was wrong then we'd prompt for connection and save it correctly there)

Fix node update in bdc dashboard on reconnect

---

extensions/notebook/src/jupyter/jupyterSessionManager.ts

In notebooks, the current working directory is by default the directory where the server was started, instead of the directory where the notebook lives (or the home dir in the case of untitled files).
To match Jupyter behavior, we should be setting the cwd to the folder of the current notebook.
Jupyter allows customization of the cwd by the %cd magic. We can just add that command to the other commands that we run when starting a session.

Ensure cwd matches notebook path

---

product.json

In preparation for release, this is needed so the correct extension shows in the marketplace without searching.
This fixes #8173

recommend datavirtualization instead of sql-vnext
