extensionsGallery-insider.json, extensionsGallery.json
- Add new datavirtualization extension
- Update sql-vnext extension, clearly indicating it's deprecated
This will only do 1 thing on open: replace itself with data-virtualization
This PR fixes #7992
=> Update data virt and sql-vnext extensions in gallery

extensions/notebook/extension.webpack.config.js, extensions/notebook/package.json, extensions/notebook/yarn.lock
When running in node environments, ws is a required dependency, where as in electron, ws is built into the runtime.
Therefore adding ws as an optional for when we run in node environments instead of electron environments.
I'm investigating if this has any impact on package size at the moment.
=> Add WS as a dep of notebooks

extensions/azurecore/extension.webpack.config.js
These don't need to be externals since webpack handles them without errors.
=> Remove externals for some azure deps

extensions/big-data-cluster/package.json, extensions/big-data-cluster/package.nls.json, extensions/big-data-cluster/src/bigDataCluster/constants.ts, extensions/big-data-cluster/src/bigDataCluster/controller/clusterControllerApi.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/addControllerDialog.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardModel.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/hdfsDialogBase.ts, extensions/big-data-cluster/src/bigDataCluster/utils.ts, extensions/big-data-cluster/src/extension.ts, extensions/mssql/src/hdfs/webhdfs.ts, extensions/mssql/src/objectExplorerNodeProvider/fileSources.ts, extensions/mssql/src/sparkFeature/dialog/sparkJobSubmission/sparkJobSubmissionService.ts, extensions/mssql/src/util/auth.ts, extensions/notebook/resources/jupyter_config/sparkmagic_config.json, extensions/notebook/src/common/utils.ts, extensions/notebook/src/jupyter/jupyterSessionManager.ts
For #8129
Things tested :
- OE HDFS node expansion
- Notebook PySpark kernel executions
- BDC Dashboard
- Spark Submission
- Manage Access dialog
- New Directory
- Upload files
- Mount HDFS
Note that the SQL Dashboard continues to list endpoints because it queries those from SQL directly. 
I also fixed up a small issue with creating a write stream - we were throwing an exception which was causing an unhandled promise rejection. The correct way is to emit an error and handle that error by the calling code.
=> Add config for ignoring SSL errors on BDC queries

azure-pipelines.yml
I noticed after my previous change that ci now triggers for all commits pushed to any branch. So I added back the triggers for the CI.
=> Add triggers for devops ci

extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboard.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardPage.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardResourceStatusPage.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/bdcServiceStatusPage.ts
Fixes #8128
The model events weren't always correctly checking the initialized state correctly which could cause issues if they were called before the page was initialized. To fix this I refactored the pages to queue actions for running after a page is initialized which is a much cleaner design and ensures that we don't lose events if the page isn't initialized.
=> Fix race conditions with BDC dashboard init

src/sql/workbench/services/connection/browser/cmsConnectionWidget.ts, src/sql/workbench/services/connection/browser/connectionDialogWidget.ts, src/sql/workbench/services/connection/browser/connectionWidget.ts
Some very slight behavior changes but they should all be for the better - i.e. making sure we have things loaded before moving on to other tasks when appropriate.
=> Fix floating promises in connection widget

src/sql/workbench/parts/notebook/browser/models/cell.ts
Ran into a situation earlier where a notebook had an undefined source field, which was causing errors to be thrown from locations that referenced cellModel.source, such as the onDidChangeContent handler in code.component.ts
=> Initialize cell source to empty array if notebook file's source is undefined.

extensionsGallery-insider.json, extensionsGallery.json
- Warnings were caused by use of sqlops APIs
- Updated to azdata and moved up to 1.0 since it's stable
Feel free to publish this whenever suits - happy to wait and have this batched with other extension updates.
=> Update NewDatabase extension to remove warnings

src/vs/workbench/contrib/extensions/browser/extensionsActions.ts
The link being generated was nonsense since our serviceUrl points to the JSON file so ended up with something like this :
https://sqlopsextensions.blob.core.windows.net/marketplace/v1/extensionsGallery-test2.json/publishers/Microsoft/vsextensions/powershell/2019.11.0/vspackage
=> Fix link for manual install of VSIX's

src/sql/workbench/browser/modelComponents/formContainer.component.ts, src/sql/workbench/services/dialog/browser/dialogContainer.component.ts, src/sql/workbench/services/dialog/browser/media/dialogModal.css
Fixes #6072
The simplistic "fix" here is to add a heading level 1 for the top-level "title" components for a page. And then have form items (regardless of where they are) use h2 for the titles of the components.
With more complex layouts this may not be enough (for example if a form was nested under a h2 itself), but I don't know of anywhere we currently have that so as a cheap fix this seems fine. And talking with the a11y folks there's some controversy over the use of heading levels for titles anyways so they said something like this should be fine.
I went through a bunch of dialogs to make sure my changes didn't affect the look/layout and things seem fine. Let me know if there's a dialog you'd like me to verify though.
Original 
New
Agent Notebook Job (info help button)
Original
New …
=> Add level to dialog titles and form component titles

src/sql/workbench/parts/query/browser/modelViewTab/media/dialogModal.css, src/sql/workbench/services/dialog/browser/media/dialogModal.css, src/sql/workbench/services/dialog/browser/media/wizardNavigation.css
fixes #5964 
fixes #5784 
fixes #5674 
fixes #7664 
Notes: I didn't look into why do we have 2 copy of the same css file, I remembered @aaomidi mentioned in one PR that now we want to have components have their own css files instead of sharing. I am going to keep it that way and updating both files.
the min width and min height i removed in the PR caused the scroll to not show up or not able to scroll to the bottom of the view.  and the overflow-x: hidden results in no horizontal scrollbar when needed. I have tested with the following scenarios on both windows and macOS. 
**TOP vs Bottom = Before vs After**
=> fix the scroll issue of modal dialog and wizard

extensions/big-data-cluster/src/bigDataCluster/dialog/addControllerDialog.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboard.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/connectControllerDialog.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/mountHdfsDialog.ts, extensions/big-data-cluster/src/extension.ts, extensions/mssql/src/localizedConstants.ts, extensions/mssql/src/sparkFeature/dialog/sparkJobSubmission/sparkJobSubmissionDialog.ts
=> Add preview title to BDC/HDFS components

extensions/big-data-cluster/src/extension.ts
Fixes #8270
There's something to be said for not having the dialog reject if it's cancelled (instead just returning undefined) - but in the BDC dashboard I use this error to show a different string indicating the user needs to enter a connection and I'd rather not refactor it since this doesn't seem that terrible to have as is.
=> Don't show dialog cancelled errors for mount

src/sql/workbench/browser/modelComponents/image.component.ts, src/sql/workbench/browser/modelComponents/media/image.css
Fixes #8200
This fixes an issue caused by https://github.com/microsoft/azuredatastudio/pull/7837 - the ModelView image component was updated to use the codicon class but the underlying ComponentWithIcon base wasn't and so the CSS styles weren't being applied correctly.
Given that the ModelView stuff isn't using any of the codicon fonts (instead it only supports external image files currently) this doesn't need to use codicon and so I'm reverting it back to just use the icon class. At some point we should consider adding codicon support to this component since that'd potentially be useful, but that be a later enhancement if that feature is needed at some point.
=> Undo codicon change to fix modelview images

src/sql/platform/queryHistory/common/queryHistoryServiceImpl.ts
Fixes #8284
If a query is ran without a specific selection the selection array is empty - in that case just get the entire text.
Opened #8303 as a related issue (we probably shouldn't be collecting queries from internal implementations of features)
=> Fix null ref error in query history

src/sql/base/test/node/ui/codicon.test.ts, src/sql/workbench/parts/queryHistory/browser/queryHistoryActions.ts
This icon was removed in https://github.com/microsoft/azuredatastudio/pull/7880
Added test to read the codicon.css file and check that the icons we use are in there as a basic smoke test.
=> Fix missing icon and add test

.github/stale.yml
Adds config for the probot to label and unlabel pr's for stale. Initally not performing as I want to verify it is doing the right thing first. Already tested on test repo.
=> Add stale pr config

src/sql/workbench/parts/notebook/browser/models/cell.ts, src/sql/workbench/parts/notebook/test/electron-browser/cell.test.ts
Fixes #8286. We weren't checking for CellType when setting the _isCollapsed property, which meant that if a user collapsed all cells, they would see the markdown editor in a collapsed state and only be able to see one line.
Also added a test.
=> Prevent Markdown Cells from Collapsing

src/sql/workbench/browser/modelComponents/media/formLayout.css
A recent CSS change made the form titles an h2 instead of a div for accessibility reasons. But the default style for h2s is different, and so this PR is fixing it so they still look as they did before.
Current :
Fixed :
=> Fix spacing for form layout

extensions/big-data-cluster/src/bigDataCluster/dialog/addControllerDialog.ts, extensions/dacpac/src/wizard/pages/selectOperationpage.ts, extensions/schema-compare/src/dialogs/schemaCompareDialog.ts, src/sql/azdata.d.ts, src/sql/platform/model/browser/modelViewService.ts, src/sql/sqlops.proposed.d.ts, src/sql/workbench/api/browser/mainThreadModelView.ts, src/sql/workbench/api/common/extHostModelView.ts, src/sql/workbench/api/common/sqlExtHost.protocol.ts, src/sql/workbench/browser/modelComponents/button.component.ts, src/sql/workbench/browser/modelComponents/checkbox.component.ts, src/sql/workbench/browser/modelComponents/componentBase.ts, src/sql/workbench/browser/modelComponents/inputbox.component.ts, src/sql/workbench/browser/modelComponents/interfaces.ts, src/sql/workbench/browser/modelComponents/radioButton.component.ts, src/sql/workbench/browser/modelComponents/table.component.ts, src/sql/workbench/browser/modelComponents/viewBase.ts
Fixes #7797
There's logic in the modal dialog to pick an initial element to focus - but this isn't working for modelview components. Since angular bootstrapping is done async'ly the elements don't exist in the DOM when that function is called and so aren't able to be correctly focused. 
The solutions I came up with as possibilities :
1. Wait until all the components are finished loading before 
- This doesn't seem easily possible with how things are written
1. Rewrite modelview stuff to not use angular
- A good idea at some point but beyond the scope of what I wanted to do for this fix
1. Let callers focus the element themselves
- A bit more manual effort but in the end I chose this for its simplicity, general usefulness of the method and explicit control it gives to the dialog owner of …
=> Add focus function for modelview components

src/sql/workbench/common/sqlWorkbenchUtils.ts
For offline scripts it shows the flavor as “Choose SQL Language”, this is because in flavorStatus.ts line 150 when we compare (uri === currentUri), the value of current Uri is "file:///d%3A/GitHub/PGExtension/TestDatabase/1ae730a9.sql" whereas the value for uri is "file:///d:/GitHub/PGExtension/TestDatabase/1ae730a9.sql" which ends up returning label ‘Choose SQL Language’.
In queryInput.ts we set public get uri(): string { return this.getResource().toString(true); }
This is the variable that we use in doChangeLanguageFlavor. And as we compare this with getEditorUri() later in flavorStatus.ts, it does not match. So enabling encoding here as well to get the encoded string in both the cases.
This PR fixes #8077
=> Set encoding to true (Bug fix for flavor)

extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboard.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardResourceStatusPage.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/bdcServiceStatusPage.ts, src/sql/azdata.d.ts, src/sql/workbench/api/common/extHostModelView.ts, src/sql/workbench/browser/modelComponents/componentBase.ts, src/sql/workbench/browser/modelComponents/divContainer.component.ts, src/sql/workbench/browser/modelComponents/flexContainer.component.ts, src/sql/workbench/browser/modelComponents/table.component.ts, src/sql/workbench/browser/modelComponents/text.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/7813
Fixes https://github.com/microsoft/azuredatastudio/issues/7815
Fixes https://github.com/microsoft/azuredatastudio/issues/7666
The ideal fix here is probably to add some sort of tab panel component instead of manually creating the divs. Talked with @alanrenmsft offline about this and we're going to bundle that into the dashboard refactor work, for now though this will at least fix the accessibility issues.
Fixes #7669 - role attribute added to ModelView components - the "image" in question here is actually an emoji icon so we use the role="img" attribute to tell screen readers that it's supposed to be viewed as an image
=> Add aria role and selected properties

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
The issue bot won't attempt to operate on issues that are created with labels (by design). So if people used the issue templates, the issue bot would ignore them.
I don't think they are adding much benefit with DRI and the issue bot anyways.
=> Remove labels from issue templates

src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts
Ampersand has been encoded twice due to which on decode, url still has &amp when it should only have &.
Updated the regex to update & to &amp; only when it's not already encoded to &amp
This PR fixes #8093
=> regex to encode & correctly

extensions/mssql/config.json
Pickup a new SMO with 1.1.0 of MS.Data.SqlClient.  The SQL Tools release is still publishing so the CI builds may fail.
=> Bump SQL Tools to 2.0.0-release.35 for SMO update

src/sql/workbench/browser/modelComponents/card.component.html
found a better role for the card component while looking into this issue and hook up the aria-checked state with the selected property.
https://www.w3.org/WAI/PF/aria/states_and_properties#aria-checked
now voiceover is announcing radio as well as selected state.
This PR fixes #7596 and fixes #7600
=> update the card role and add aria-checked state

src/sql/workbench/browser/modelComponents/groupContainer.component.ts
added proper tabIndex, role, and aria-expanded attributes for the group container header.
setting value to null will clear the attribute when not needed, but for tabindex I had to use -1 to make it not keyboard focusable.
also added keyboard handler
enter/space will toggle the collapsed state
left: collapse the container
right: expand the container
This PR fixes #7601
=> make group container header accessible

build/azure-pipelines/darwin/sql-product-build-darwin.yml, build/azure-pipelines/linux/sql-product-build-linux.yml, build/azure-pipelines/win32/sql-product-build-win32.yml, build/gulpfile.sql.js, build/gulpfile.vscode.js, build/lib/extensions.js, build/lib/extensions.ts
Currently we are creating vsix's for our external extensions on every os in the pipelines since it is built into the packaging task. This breaks it out as it's own gulp task and only runs it on the linux (since its the fastest build time).
This only has an impact on the admin-tools-win extensions since it is windows only. But it seems if we just hard code in the windows platform when it downloads the binaries, everything else should be platform agnostic. @Charles-Gagnon let me know if you think there is an issue here. All the other extensions are already platform independent so only building from linux shouldn't be a problem.
Also fixes an issue where we weren't returning the promises the vsix creator was returning so the gulp task never knew about them. This wasn't an issue since they …
=> Only package external extensions on Linux in the pipelines

src/sql/workbench/browser/modelComponents/groupContainer.component.ts
the issue was introduced by my previous PR: https://github.com/microsoft/azuredatastudio/pull/8452
1. only handle the key down events on header
2. make the header check more robust since it could be empty string instead of undefined.
This PR fixes #8487
=> only handle the keyboard events on header

build/azure-pipelines/darwin/sql-publish.ps1, build/azure-pipelines/linux/sql-publish.ps1, build/azure-pipelines/win32/sql-publish.ps1
Since our build pipeline is now source controlled, it makes sense for our publishing scripts to also be source controlled.
I have made no changes here, this is just copy pasted.
=> Add publish scripts to source

extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardModel.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts
The page was initializing from the model as soon as it finished setting up but because the endpoints array was set to be initialized as an empty array it couldn't tell if the model had actually gotten an empty list of endpoints back or hadn't yet finished the remote query. This resulted in us removing the loading component too quickly - which due to the other timing issues I'm working on with the ModelView stuff meant that it got "removed" before it was actually added to the container on the main thread side and thus never got correctly removed.
So this is more of a workaround fix in the meantime since it's essentially just adding a long enough delay so that the component has time to be added to the container before we remove it - but this is a better way to handle the logic anyways so …
=> Fix loading component not being removed

src/sql/workbench/test/electron-browser/api/extHostModelView.test.ts
Tests that components are turned into component IDs correctly before being sent across the proxy and that normal/empty data property is sent correctly. 
I had to refactor the file a bit since the existing tests were doing some setup that I didn't need for these tests - so I split the suite into two separate sub-suites with the shared config being at the top level. The existing tests weren't modified at all except for moving. And the new tests are under the `Declarative table` suite at the bottom.
=> Add tests for declarative table component

build/azure-pipelines/win32/sql-product-build-win32.yml
This PR fixes #8390 
1. This change hooks up to the AzureKeyVault to pull into pipeline variables the set of various connection string secrets necessary for the execution of integration tests.
2. Sets the environment variables that the execution of integration tests need from pipeline variables.
=> Pull integration test connection string variables from secret store

extensions/resource-deployment/src/ui/deployClusterWizard/pages/deploymentProfilePage.ts, extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts, src/sql/azdata.proposed.d.ts, src/sql/workbench/api/common/extHostModelView.ts, src/sql/workbench/api/common/sqlExtHostTypes.ts, src/sql/workbench/browser/modelComponents/componentWithIconBase.ts, src/sql/workbench/browser/modelComponents/components.contribution.ts, src/sql/workbench/browser/modelComponents/iconUtils.ts, src/sql/workbench/browser/modelComponents/media/card.css, src/sql/workbench/browser/modelComponents/radioCardGroup.component.html, src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts
Problems solved by this PR:
1. screen readers do not know the grouping of our custom radio card, for custom radio elements, they need to be placed directly under the group div in order to be recognized by screen readers.
2. our current card doesn't support the standard radio group keyboard navigation. 
tab: navigate away from the group
left or up key: select the previous radio element. special case: first element -> last element
right or down key: select the next radio element. special case: last element -> first element
3. No centralized place to manage the card selection/de-selection logic
4. the card description is not organized using tables
This PR fixes #7936  and fixes #7933
=> accessible radio card

src/sql/workbench/contrib/scripting/browser/scriptingActions.ts
Initially started off just fixing a dangling promise but found a bug here - in line 321 we were fetching the treeNode if we hadn't retrieved it previously. But this was done in an async function - and so the calling code would continue on and check again if treeNode was undefined on line 326 even though the async function may not have completed by that point and so would silently fail to refresh the node. 
Did slightly change the behavior to show an error message if an error occurred during the collapse/expand as well (since it's unlikely to happen and having it be more obvious when that happened should be a good thing)
=> Fix refresh action

src/sql/workbench/browser/modal/modal.ts, src/sql/workbench/services/dialog/browser/wizardModal.ts
Things using the custom message location need to also be able to handle showing/hiding the message element themselves.
=> Fix wizard not displaying error messages

src/sql/azdata.d.ts, src/sql/workbench/api/common/extHostModelView.ts
data virtualization is the only extension I've seen using the card component, I will go and modify it.
this is just to follow the process of deprecating the API
=> deprecate the card component

src/sql/workbench/contrib/notebook/browser/models/cell.ts, src/sql/workbench/contrib/notebook/browser/models/modelInterfaces.ts, src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts, src/sql/workbench/contrib/notebook/test/electron-browser/common.ts
These tests bring code coverage for cell.ts to about 81%. I've been working on this for a while, so I wanted to merge in what tests I have for now. The only things left to cover are the rewriteUrl methods, and random one liners here and there.
=> Add code coverage tests for cell.ts

extensions/integration-tests/src/cms.test.ts, extensions/integration-tests/src/dacpac.test.ts, extensions/integration-tests/src/index.ts, extensions/integration-tests/src/notebook.test.ts, extensions/integration-tests/src/objectExplorer.test.ts, extensions/integration-tests/src/schemaCompare.test.ts, extensions/integration-tests/src/setup.test.ts, extensions/integration-tests/src/testContext.ts
the value of the global variable was reset for each test suite, using the underlying configuration value instead.
=> check setting directly to avoid value reset

src/sql/workbench/browser/modelComponents/radioCardGroup.component.html, src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts
if we are setting a property multiple times using the API, the cards will disappear.
It seems the call to the cd.detectChanges in the onFocus and onBlur methods are causing race condition. removing it fixed the problem. 
I also changed to use strings for internal state instead of objects since the cards could be changed using the API, it is more reliable to use strings than reference comparison.
This PR fixes #8581
=> fix radio card group rendering error

extensions/schema-compare/src/schemaCompareMainWindow.ts, extensions/schema-compare/src/utils.ts
This PR fixes the scenario where SchemaCompare can't reload an scmp where the source or target uses username/password to connect since the password is not persisted.
If the connection profile doesn't yield a connection Uri, the fix actually goes in and checks within the active connections list to get the connection details. If not, connection dialog opens up to get the connection information, upon approval.
This PR fixes #6833
=> Update schema compare extension to support SQL Login

extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts
This change removes the redundant console.warn message as the corresponding appropriate messages are already displayed in an informational/warning tab to the user. So in effect #7907 was already previously addressed, some console.warn which are not as informational were left behind.
This PR fixes #7907
=> remove redundant console.warn messages

extensions/mssql/src/hdfs/aclEntry.ts, extensions/mssql/src/hdfs/ui/hdfsManageAccessDialog.ts, extensions/mssql/src/hdfs/ui/uiConstants.ts, extensions/mssql/src/localizedConstants.ts, src/sql/azdata.d.ts, src/sql/azdata.proposed.d.ts, src/sql/workbench/api/common/extHostModelView.ts, src/sql/workbench/browser/modelComponents/button.component.ts, src/sql/workbench/browser/modelComponents/componentBase.ts, src/sql/workbench/browser/modelComponents/componentWithIconBase.ts, src/sql/workbench/browser/modelComponents/declarativeTable.component.ts, src/sql/workbench/browser/modelComponents/image.component.ts, src/sql/workbench/browser/modelComponents/text.component.ts, src/sql/workbench/browser/modelComponents/titledComponent.ts
Fixes #7806 as well as some other issues found during testing.
The bulk of the changes is converting from a manually created table from divs to using the declarative table component. While doing this I also changed it so the majority of the components aren't created until after the model has been populated since that fixes some display issues related to timing that we had before when we were updating the components after the model populated.
Made proposed API changes to clean up more of the ModelView stuff to be consistent with the other interfaces. Properties interfaces should be the ones containing just the properties and then the Component interfaces inheriting from those so that WithProperties is able to correctly identify which properties to allow. I did this here because some of the …
=> Fix accessibility issues with Manage Access dialog

test/coverage.js
We were instrumenting helper classes too such as stub services, this shouldn't be necessary for getting accurate code coverage numbers. 
(only a very slight increase, ~1%, in coverage from this but an increase is an increase!)
=> Don't instrument any test code for coverage

src/sql/workbench/contrib/notebook/browser/notebookActions.ts
Fixes #8612.
When clicking cancel, we were unnecessarily calling a couple of methods, when we really should have been doing nothing to the attach to dropdown and leaving the state as it was before the user chose Change Connnection.
=> Notebooks: Fix Cancel for Connection Dialog to Actually Close Window

src/sql/workbench/contrib/notebook/browser/cellViews/collapse.component.ts
This hopefully addresses bug #7624. Before the fix, no screen readers would read anything when tabbing to the expand/collapse button in the notebook.
This component is defined as a button in the component html. If anyone feels strongly that we should be defining a couple of properties in the *component.ts and referencing those in the *.html file, more than happy to make that change.
After:
=> Ensure Screen Readers Read Notebook Expand/Collapse Button Names

src/sql/base/browser/ui/selectBox/media/selectBox.css
Fix for #8631 
After:
Tested notebooks and connection dialog on mac and pc and didn't notice any adverse effects
=> Add generic select box padding

extensions/resource-deployment/src/services/tools/toolBase.ts
This change starts to populate each tool's status and version as soon as the tool is constructed. This improves user-perceived performance because, by the time the user clicks on respective cards that need to display these tools, the information is already populated.
This PR fixes #8526
=> Improve performance of tools table painting for bdc deployment tools

src/sql/workbench/contrib/objectExplorer/browser/connectionTreeAction.ts, src/sql/workbench/contrib/objectExplorer/browser/serverTreeActionProvider.ts, src/sql/workbench/contrib/objectExplorer/test/browser/connectionTreeActions.test.ts, src/sql/workbench/contrib/scripting/browser/scriptingActions.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/8512
Fixes https://github.com/microsoft/azuredatastudio/issues/8455
Fixes https://github.com/microsoft/azuredatastudio/issues/7420
Fixes https://github.com/microsoft/azuredatastudio/issues/6787
2 main issues being fixed here :
1. **Refreshing nodes was collapsing the tree up to the server level in OE** 
For non-server nodes we were passing in the ConnectionProfile, which would then be turned into a URI for looking up whether a node was connected. But because we were using the connection to get the node it was always getting the server node and refreshing that instead of the specific node being requested - and thus would refresh the entire tree. The fix is to pass in the TreeNode instead directly if we have it (which we should …
=> Fix tree refresh

src/sql/workbench/browser/modal/optionsDialog.ts, src/sql/workbench/services/insights/browser/insightsDialogView.ts
This PR fixes #8624
Both use the wrong name, it should be .monaco-pane-view instead of .monaco-panel-view (this spelling does not have any CSS files that use it)
Made changes to both optionsDialog and insightDialogView as they are both paneview(lets) (should fix issues related to .monaco-pane-view rules in css files).
=> Change typo for monaco-pane-view

extensions/resource-deployment/package.nls.json, src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
Per UX and PM feedback, changing option from "Deploy SQL Server..." to "New Deployment..." in both connections viewlet and welcome page
=> Change deploy string from connections viewlet/welcome page

src/sql/setup.js
Cleans up the error output from zonejs
Allows ADS to log normally without zonejs consuming the errors
=> zonejs changes

src/sql/workbench/contrib/dataExplorer/test/browser/dataExplorerViewlet.test.ts
Removed in https://github.com/microsoft/azuredatastudio/commit/4ba6a979baa5adb455bc0bb20634b6a72180c05e
@anthonydresser Did you have a specific reason for removing these? I'll admit they're not super useful as written but there don't seem to be any issues running them so I don't see a reason to remove them.
=> Add de viewlet tests back

src/sql/workbench/browser/modal/media/modal.css
(noticed in backup dialog, but would affect any dialog with a select dropdown)
Previous :
After fix :
=> Fix alignment of select dropdown in modal dialogs

src/sql/base/browser/ui/table/formatters.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/8554 and fixes https://github.com/microsoft/azuredatastudio/issues/8543
The `Table` component was failing for tables with numbers as columns.
=> Fix modelview tables failing for number columns

src/sql/workbench/browser/modal/media/optionsDialog.css
=> Fix options dropdown arrow alignment in options dialog

src/sql/workbench/contrib/dataExplorer/browser/dataExplorerViewlet.ts
Fixes #8588
The base ViewPaneContainer has [logic](https://github.com/microsoft/azuredatastudio/blob/master/src/vs/workbench/browser/parts/views/viewPaneContainer.ts#L402) to display the actions of the view when there's only a single one showing which we were overriding. 
Normal (2+ views showing)
Only one view showing
=> Fix missing action buttons with single view

extensions/resource-deployment/src/services/tools/toolBase.ts
This change fixes 2 things:
1. Moves the code to add possible installation location of the tools to system path to the call that discovers the version of tools intalled so that every time we try to discover these tools, we check to see if these know installation locations are in path and add them to system path if they are not.
2. Make a change so that we eliminate duplicate installation paths.
This PR fixes #8685
=> add installation search path to system before tools discovery is done every time

src/sql/workbench/browser/modelComponents/queryTextEditor.ts
Fixes #8675.
In https://github.com/microsoft/vscode/commit/185d71b615e529b154c76907764bfda9270cb42f an alwaysConsumeMouseWheel option was added (and defaulted to true): https://github.com/microsoft/vscode/blob/185d71b615e529b154c76907764bfda9270cb42f/src/vs/editor/common/config/editorOptions.ts#L2328
For a document with 1 editor, this seems reasonable. However, when trying to scroll between editors for notebooks, this was breaking us, as events weren't getting propogated properly. Setting this to false for notebooks fixes this issue.
=> Fix Notebook Scrolling by Setting alwaysConsumeMouseWheel to False

src/sql/workbench/contrib/notebook/browser/models/notebookModel.ts, src/sql/workbench/contrib/notebook/browser/notebook.component.ts
Fixes #8688.
Connection profile was getting set automatically for notebooks in the notebook component for some file->open scenarios.
In addition, a subtle bug where we were using this.connectionProfile when starting a new session instead of using this._activeConnection if it was already set.
=> Fix Notebook Connection Profile Passing Bugs

src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.contribution.ts
I am looking into the area recently and saw this issue, I didn't dig too much into the change history, it makes sense to have new query and new notebook appear first.
This PR fixes #8627 
with the changes:
=> change order of tasks

src/sql/workbench/services/connection/browser/connectionWidget.ts
We noticed that if displayName is undefined this method would return the first auth type it found as getAuthTypeDisplayName() would return undefined.
If the displayName is undefined, we would not have a matchingTYpe and it should be undefined.
This PR fixes #8714
=> Bug fix to return authType as undefined if displayName is not set

src/sql/workbench/contrib/editData/browser/gridParentComponent.ts
Added a simple check to make sure that the context menu doesn't open for the last row (which is the null row) for the data in editdata, this was tested using an empty grid with only the null row, and a table with several rows.
This PR addresses #478
=> Added check for the last null row

src/sql/workbench/contrib/notebook/browser/notebookEditor.ts, src/sql/workbench/contrib/notebook/find/notebookFindDecorations.ts, src/sql/workbench/contrib/notebook/find/notebookFindModel.ts
Fixes the below two issues:
1. On ctr+f show find only when the notebook modal is loaded. Currently the find widget shows no results if it's launched before the notebook modal load.
2. If the find result is in a collapsed cell, it doesn't expand the cell and the user is clueless about it.
This PR fixes #8754
=> Only show find when modal is loaded

src/sql/workbench/contrib/notebook/browser/cellViews/collapse.component.html, src/sql/workbench/contrib/notebook/browser/cellViews/collapse.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/8634
=> Use a single button for expanding and collapsing a notebook cell.

src/sql/base/parts/editableDropdown/browser/dropdown.ts
Fixes #8709
First some context - the main thing causing this issue is that we fetch the database list asynchronously. So when the dropdown is opened we start the query to get the latest database list but then immediately open with the ones that we know about.
This changes it so the dropdown calculates the width immediately upon opening - this makes it so if the longest database name doesn't change after it comes back with the new options then the width won't change.
This DOESN'T fix the issue though that if the query comes back with the longest name being different  it'll still change the size. But this isn't something we can really prevent unless we wanted to only set the size on first open and not when new values are set (so the user would need to close and reopen to see the corrected …
=> Make dropdown update width immediately upon opening

extensions/integration-tests/src/cms.test.ts, extensions/integration-tests/src/dacpac.test.ts, extensions/integration-tests/src/objectExplorer.test.ts, extensions/integration-tests/src/schemaCompare.test.ts, extensions/integration-tests/src/testConfig.ts, extensions/integration-tests/src/utils.ts, extensions/mssql/config.json
1. fix the 'editor is not connected' error, the root cause is we were switching database context of the underlying connection, the fix is to use a new dedicated connection to the desired database. (leaving it as unstable due to new errors were discovered, @kisantia made changes in SQL Tools Service to fix the new issue). 
2. remove the unstable tag for the test cases that are passing consistently.
see the test runs
=> fix unstable tests

src/vs/platform/actions/browser/menuEntryActionViewItem.ts, src/vs/workbench/browser/style.ts
Since the manage packages extension class name is .icon instead of .codicon, the style rules need to account for this as well (changing the class name to .codicon breaks the icon image so its not recommended)
This PR fixes #8721
=> Changed class name for manage packages extension

extensions/dacpac/src/wizard/dataTierApplicationWizard.ts
Remove unnecessary awaits since the wizard closes before the result returns from the SqlToolsService. The status of the operations and any error messages are shown in the Task Viewlet.
=> Cleanup dacpac wizard

build/azure-pipelines/win32/sql-product-test-win32.yml
I've removed all the REL tag from the test files in my recent test improvement, and currently the tests are all running on the mssqltools pool. no need to have the REL test step in the build pipeline.
=> remove REL test step

build/azure-pipelines/darwin/sql-product-build-darwin.yml
We've been hitting a lot of signing timeouts in the Mac builds today, so hopefully increasing the timeout will help. We already use a 600 minute timeout for the Windows signing step, so using 60 minutes here isn't too outrageous.
=> Increase code signing timeout for Mac builds.

extensions/notebook/src/book/bookModel.ts, extensions/notebook/src/book/bookTreeView.ts, extensions/notebook/src/common/localizedConstants.ts, extensions/notebook/src/test/book/book.test.ts
Fixes #8819
The issue here is that we were parsing all workspace folders on startup - but if any of them weren't actual valid book folders they'd display an exception.
I modified the logic to swallow any errors when loading from workspace folders since we can't expect those to necessarily be valid book folders so will often fail to parse. Opening a book directly from the viewlet will still display an error if the folder is invalid though.
Added some tests to cover this scenario and fixed a number of the existing tests that were broken due to other changes made since these tests were moved into unstable. Optimistically moved all the ones I fixed into stable as well and will monitor for reliance in future test runs.
=> Fix book provider load to not throw on startup

src/sql/workbench/api/browser/mainThreadDashboard.ts
In my new extension I need to activate the extension when dashboard is opened. I didn't find any activation event for that so I added one. Please let me know if there's a better way to do it.
=> Adding an activation event for opening the dashboard

extensions/admin-tool-ext-win/src/test/index.ts, extensions/agent/src/test/index.ts, extensions/azurecore/src/test/index.ts, extensions/cms/src/test/index.ts, extensions/dacpac/src/test/index.ts, extensions/integration-tests/src/index.ts, extensions/machine-learning-services/src/test/index.ts, extensions/notebook/src/integrationTest/index.ts, extensions/notebook/src/test/index.ts, extensions/resource-deployment/src/test/index.ts, extensions/schema-compare/src/test/index.ts
It was previously at 600sec which seems like a bit much for these tests and would mean any hanging test would slow down everything else as it waited for the huge timeout to be reached (and usually just end up hitting the build timeout or something in the lab). I see no reason these tests should be taking nearly that long so moving the timeout down to a more reasonable 10sec.
=> Change test timeout for extension unit tests to 10sec

extensions/resource-deployment/src/interfaces.ts, extensions/resource-deployment/src/services/tools/azdataTool.ts, extensions/resource-deployment/src/services/tools/toolBase.ts, extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts
Here is a list of changes in this bug fix:
1. Wrap download and insall of azdata.msl in a try/catch block to ensure exit code is non-zero when a failure happens.
2. Make sure the controls of UI stay disabled when an error/failure happens so that user is unable to continue the workflow.
3. Made the status field of the iTool object publicly readable.
4. Minor method renames for code redability.
This PR fixes #8584
=> fix how failed/errored installation workflow

extensions/azurecore/src/account-provider/providerSettings.ts
Updating the authentication endpoint for US government clouds.  Currently we have the public cloud endpoint and instead we should have the government cloud specific authentication endpoint.
We don't currently support connecting to government cloud fully as we are waiting on the client IDs to get approved so this is simply to make sure we have the right endpoint for government cloud once we have the client IDs.
=> update govt cloud login endpoint

build/azure-pipelines/darwin/sql-product-build-darwin.yml, build/azure-pipelines/sql-product-build.yml
This increases the timeouts for signing and building.
It's based on their SLA of 120 minutes for signing of 50-150 MB packages with large number of files.
We're also going to need to raise this for notarization as well.
=> Increase timeouts

extensions/integration-tests/src/index.ts, extensions/notebook/src/integrationTest/index.ts
Some of our integration tests started timing out after the timeouts were decreased in https://github.com/microsoft/azuredatastudio/commit/7ecb6b442716dd43d080c3c09a2749b9ff63570d
This PR reverts the timeout changes just for the integration tests.
=> Revert timeout changes for integration tests.

src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts, src/sql/workbench/contrib/dashboard/browser/core/dashboardTab.contribution.ts, src/sql/workbench/contrib/dashboard/browser/dashboardRegistry.ts
with the new dashboard design, all contributed tabs will appear under extensions group, add a flag to allow extensions to contribute a top level tab, for now this is designed for the big data cluster dashboard tab.
sample code:
in package.json's tab contribution section add
````JSON
{
"id": "test-modelview",
"description": "bababa",
"provider": "MSSQL",
"title": "bababa",
"when": "connectionProvider == 'MSSQL'",
"isTopLevelTab": true,
"container": {
"modelview-container": {}
}
}
````
in extension code, register a model view provider
````TypeScript
azdata.ui.registerModelViewProvider('test-modelview', async (view) => {
const text = view.modelBuilder.text().withProperties<azdata.TextComponentProperties>({ value: 'my tab goes here' }).component();
return view.initializeModel(text);
});
````
=> allow extension to contribute top level dashboard tab

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts, src/sql/workbench/contrib/notebook/find/notebookFindDecorations.ts
Implemented getEditor for textCell component which returns undefined normally and in edit mode returns the code editor. (This aids Rajesh for his split cell work.)
=> getter for markdown editor on edit mode

extensions/machine-learning-services/src/test/queryRunner.test.ts, extensions/notebook/src/integrationTest/notebookIntegration.test.ts, extensions/notebook/src/test/managePackages/localPackageManageProvider.test.ts, extensions/notebook/src/test/managePackages/managePackagesDialogModel.test.ts
While running the extension unit tests, I noticed that some test cases weren't correctly reporting promise-related failures since the associated methods weren't being awaited. The following tests are the ones that are failing in master, which we can address separately.
1) Manage Package Providers Pip getPackageOverview should return package info successfully:
AssertionError: expected [Promise] to be fulfilled with Object {
name: 'name',
versions: Array [ '0.0.1', '0.0.2' ],
summary: 'summary'
}, but it was rejected with SyntaxError { message: 'Unexpected token i in JSON at position 7' }
at Context.<anonymous> (C:\Users\Cory\Source\azuredatastudio\extensions\notebook\src\test\managePackages\localPackageManageProvider.test.ts:166:3)
2) Manage Package Providers Conda getPackageOverview …
=> Await should() methods involving promises in tests.

extensions/mssql/package.json, extensions/mssql/package.nls.json, src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts, src/sql/workbench/contrib/dashboard/browser/core/dashboardTab.contribution.ts, src/sql/workbench/contrib/dashboard/browser/dashboardRegistry.ts, src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.component.ts, src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.contribution.ts
as per the mock up of new dashboard, we need databases tab under contents group of server dashboard. removed the databases widget from the home tab.
https://www.figma.com/proto/QRkuP8YG7sZr87LRoS210ldo/ADS_Framework_v0.03?node-id=3058%3A97242&scaling=min-zoom
=> content tab group

src/sql/azdata.d.ts
See https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...Charles-Gagnon:chgagnon/fixLintingErrors
This is fixing a number of linting issues with our typings file that were flagged by the [DefinitelyTyped linter](https://github.com/microsoft/dtslint). This first pass is just formatting changes, there are no functionality/code changes.
Fixed rules : 
comment-format
jsdoc-format
max-line-length
no-consecutive-blank-lines
no-mergeable-namespace
no-padding
no-redundant-jsdoc-2
no-unnecessary-qualifier
=> Fix some dtslint errors in azdata.d.ts

src/sql/workbench/contrib/notebook/browser/models/cell.ts, src/sql/workbench/contrib/notebook/browser/models/modelInterfaces.ts, src/sql/workbench/contrib/notebook/browser/notebook.component.html, src/sql/workbench/contrib/notebook/common/models/contracts.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/7658
In the above accessibility issue, there was some confusion around the tab navigation ordering since we highlight the editor text first and then the More Actions button second, even though the button is technically higher in the view. This change makes the notebook cell itself selectable for tab navigation, so that it's more obvious what the ordering of the items is. We select the cell first, then go left to right from Run to Editor to More Actions. I also added an Aria label to announce the types of the cells.
Also removed the 'Raw' cell type, since it didn't seem to be used anywhere.
=> Make notebook cells selectable for tab navigation.

src/sql/workbench/contrib/editData/browser/editData.component.ts
Here are the primary changes listed:
On Line 378 in editdatagridpanel.ts: changed the formatter in the columnDefinitions to use a custom formatter in the class, instead of one in tables.
On Line 171 and 739: NULL is used to indicate a null row as the loading of cell values is handled primarily by slick.grid api which only recognizes NULL, and not undefined, as empty (not counting empty strings)
slick.grid api is called first when a cell is clicked and loads the value in before it can be processed by the main code. The code cannot determine whether a cell has been changed or not because of this.
This PR fixes #8889
=> Fix for null shift-tab/focus

src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts, src/vs/workbench/services/workingCopy/common/workingCopyService.ts
We had 2 problems related to #8936:
- Untitled notebooks opened a notebook window upon reopening ADS with no cells, and a query editor would open with the json representation of the notebook
- Each cell in a notebook was being opened as its own editor tab
Since this issue is quite impactful, I have this PR that mitigates this issue.
1st issue:
For new untitled editors, providing an associatedResource now results in the untitledTextFileInput's hasAssociatedFilePath returning true, which means, on rehydration, a notebook editor with a URI of scheme 'file' was being opened. Not including associatedResource fixes this particular issue.
2nd issue:
The WorkingCopyService now keeps track of every contentChange event of every editor input. The BackupTracker then subscribes to these events, and …
=> Fixes for broken notebook experience

extensions/dacpac/package.json, extensions/dacpac/src/wizard/api/basePage.ts, extensions/dacpac/src/wizard/api/dacFxConfigPage.ts, extensions/dacpac/src/wizard/api/utils.ts, extensions/dacpac/src/wizard/pages/deployConfigPage.ts, extensions/dacpac/src/wizard/pages/importConfigPage.ts, src/sql/azdata.d.ts, src/sql/azdata.proposed.d.ts, src/sql/workbench/browser/modelComponents/inputbox.component.ts
This makes it so a validation error message now can show when input box validation is false. Previously in the dacpac wizard, invalid file names would just disable the Next button but no message would show why. 
This also adds validation in the dacpac wizard to check if database names are unique when deploying dacpacs and importing bacpacs. Fixes #8124. 
Still shows default message when inputbox is empty:
=> Add validation error message for inputbox component

build/azure-pipelines/sql-product-build.yml
The build machine that we use is encountering a couple of configuration issues. Temporarily disabling the Windows_Test job so that we can unblock insiders builds.
=> Temporarily Disable Windows_Test Job in Product Build

extensions/big-data-cluster/src/bigDataCluster/tree/controllerTreeDataProvider.ts, extensions/cms/src/cmsResource/tree/treeProvider.ts
Fixes #8977
I'm not sure what changed here recently - this might have just been a race condition that we hadn't hit yet. But what would happen is that we'd finish the loading code before returning the "Loading..." node - which meant that the children returned didn't contain any of the actual nodes. And then at that point we'd be stuck unless something caused it to refresh the tree.
Noticed this issue for CMS tree as well so also fixed that up to have similar logic.
=> Refactor node loading logic for tree controllers

build/azure-pipelines/sql-product-build.yml
Build machine configuration used for the Windows_Test Job has been updated to have the required pre-reqs and is succeeding again. Re-enabling again.
=> Re-enable windows test Job

src/sql/workbench/contrib/notebook/browser/notebook.component.ts
This PR fixes #8328. We were always calling updateActiveCell() on the notebook model when selecting a cell (or, in this case, attempting to copy text from the output). From the cell model's active setter, fireExecutionStateChanged() was called, which the code component listened to and called setFocusAndScroll (thus stealing focus from the output component).
=> Notebooks: Stop Firing Active Cell Changes when Active Cell Isn't Changing

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
This PR fixes #5023 
On windows, ctrl-A selects the html element but on Mac it invokes the editors select all action even when there is no editor. So added an event on textCell component to listen to cmd-A key event and prevent default behavior & select the active html element.
=> listen to command a and select the active element.

extensions/azurecore/package.json, extensions/azurecore/package.nls.json, extensions/azurecore/src/azureResource/azure-resource.d.ts, extensions/azurecore/src/azureResource/commands.ts, extensions/azurecore/src/azureResource/interfaces.ts, extensions/azurecore/src/azureResource/providers/database/databaseProvider.ts, extensions/azurecore/src/azureResource/providers/database/databaseService.ts, extensions/azurecore/src/azureResource/providers/database/databaseTreeDataProvider.ts, extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerProvider.ts, extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerService.ts, extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerTreeDataProvider.ts, extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerProvider.ts, extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerService.ts, extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerTreeDataProvider.ts, extensions/azurecore/src/azureResource/providers/resourceGroup/resourceGroupService.ts, extensions/azurecore/src/azureResource/providers/resourceTreeDataProviderBase.ts, extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceProvider.ts, extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceService.ts, extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceTreeDataProvider.ts, extensions/azurecore/src/test/azureResource/providers/database/databaseTreeDataProvider.test.ts, extensions/azurecore/src/test/azureResource/providers/databaseServer/databaseServerTreeDataProvider.test.ts, extensions/resource-deployment/src/interfaces.ts, extensions/resource-deployment/src/localizedConstants.ts, extensions/resource-deployment/src/typings/ref.d.ts, extensions/resource-deployment/src/ui/deployClusterWizard/pages/azureSettingsPage.ts, extensions/resource-deployment/src/ui/deployClusterWizard/pages/clusterSettingsPage.ts, extensions/resource-deployment/src/ui/deployClusterWizard/pages/serviceSettingsPage.ts, extensions/resource-deployment/src/ui/deploymentInputDialog.ts, extensions/resource-deployment/src/ui/modelViewUtils.ts
Two major changes in this PR:
1. Add new resource-deployment field type `azure-account` which contains dropdowns for selecting an account, subscription and resource group
2. Add in support to AzureCore for querying subscriptions and resource groups (we get the accounts from the azdata.Account API)
Currently there's a lot of specialized logic being added to the modelViewUtils file which I don't like, but I want to sync with @alanrenmsft on long-term plans for this and the overall design so for now doing this to try and keep the changes scoped.
=> Support for removing hardcoded deployment options

extensions/azurecore/src/azureResource/commands.ts, extensions/resource-deployment/src/ui/modelViewUtils.ts
I was storing references to the maps/dropdowns in the file-level context which was breaking when the dialog was launched multiple times since we never cleared the old references. Refactored it to instead create all the references contained within the context of the field (so multiple azure-account fields would each have their own set of references)
=> Fix error when using azure-account deployment field

src/sql/workbench/services/queryEditor/browser/queryEditorService.ts
An EditData editor created with an untitledResource will not have the name of the table on the top of the head. However, if we use an associatedResource which displays the title, the editor is initialized as dirty by default, and changes to the dirty state will not be detected at all for the editor. To fix this, the dirty state must be manually set to false upon creating the editor, so to detect when the editor has changed.
This PR fixes #9006
=> Fix for table name not showing up on the header.

extensions/azurecore/src/azureResource/commands.ts, extensions/resource-deployment/src/interfaces.ts, extensions/resource-deployment/src/localizedConstants.ts, extensions/resource-deployment/src/ui/modelViewUtils.ts
Part of #8852. This moves the location field to also be under the Azure Account so that we can control clearing it if no account is selected.
Also fixed up some of the error messaging so it actually displays errors to the user now.
=> Add location to azure-account deploy field

extensions/big-data-cluster/src/bigDataCluster/tree/controllerTreeDataProvider.ts, extensions/cms/src/cmsResource/tree/treeProvider.ts, extensions/cms/src/test/cmsResource/tree/treeProvider.test.ts, extensions/cms/src/test/utils.ts
Further fix for #8977 - Some people were still getting stuck in a loading state in the stable RC build. This issue here was still timing - if the load functions completed before the initial call to getChildren had finished (which could easily happen if there weren't any saved nodes to actually load) then both providers were ignoring the new nodes and still returning the loading node. 
Improved the logic here to always return a known set of nodes - which the load functions update when they're done - so that even if they finish quickly the getChildren function will still return the now-updated set of nodes.
=> Even more robust handling of extension tree loading

extensions/resource-deployment/src/interfaces.ts, extensions/resource-deployment/src/localizedConstants.ts, extensions/resource-deployment/src/ui/modelViewUtils.ts
Enhancements for the Arc deployment - let a text field be disabled for values that aren't currently editable (but we still want to look consistent so using readonly_text isn't appropriate for).
Also make default option for account blank per feedback - the fields are optional so leaving them blank is better consistency.
=> Add enabled property and make default account option empty

extensions/notebook/src/book/bookTreeItem.ts, extensions/notebook/src/book/bookTreeView.ts, src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts
This fixes it so the editor titles show the correct basename instead of the fully qualified path.
The issue comes down to the VS Code expects all resource URIs to be posix-like and so in https://github.com/microsoft/azuredatastudio/blob/master/src/vs/base/common/resources.ts#L72 hardcodes it to using posix.basename when getting the resource name for the editor title.
I've tested :
1. Opening book from viewlet (both saved and unsaved)
2. Opening book from command palette (2019 TSG)
3. Opening book from Troubleshooting link on BDC Dashboard
=> Fix Jupyter Book notebook titles

build/gulpfile.vscode.js, package.json, src/bootstrap-window.js, src/sql/workbench/contrib/dashboard/browser/widgets/insights/insightsWidget.component.ts, src/sql/workbench/services/bootstrap/browser/commonServiceInterface.service.ts, test/all.js, test/electron/renderer.js
This PR fixes #9003.  At some point, the `fromPromise` calls stopped working in packaged builds, raising a null ref.  Apparently importing this additional `add` module is needed now.
=> Import "fromPromise" so Observables work correctly

extensions/notebook/src/book/bookTreeItem.ts, extensions/notebook/src/book/bookTreeView.ts, src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts
Fixes #9008.
2 very related issues:
- Conditionally add associatedResource (instead of untitledResource) if the file exists on disk already
- Don't use same untitled numbering logic as other untitled notebooks and use the resource as-is (either the full path uri or the untitled:Notebook-x format)
I've tested the following scenarios:
- Opening saved notebooks + rehydrating
- Untitled new notebooks + rehydrating
- Opening notebook from unsaved books viewlet + clicking relative link (note: rehydration does not work in this case, which is not a regression)
- Opening notebook from saved books viewlet + clicking relative link (rehydration succeeds)
If anyone has any spare cycles and can test, would love any help that you can provide 😄
=> Books: Ensure associatedResource is Present for Untitled Notebooks that have a File Associated with them

src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
The column formatter adds additional formatting that is unnecessary for its purpose, so they have been removed.
This PR fixes #9040
=> Fix for adventureworks formatting issue

extensions/big-data-cluster/package.json
This is for #9049. Needed to add another activationEvent for the open cluster dashboard command.
=> BDC: Add another command for bdc extension activation events

src/sql/workbench/contrib/query/common/queryEditorInput.ts, src/vs/workbench/browser/labels.ts, src/vs/workbench/common/editor/untitledTextEditorModel.ts, src/vs/workbench/test/common/editor/untitledTextEditor.test.ts
untitledTextEditorModel is created without a file path before the Query Editor is instantiated, and it detects whenever the editor text changes. As a result, it will replace the header name with the first line of text in the editor. There is currently no way to alter this behavior outside of vscode.
This PR handles #9058 until updates to vscode have been made.
=> disable updateNameFromFirstLine from untitledTextEditorModel

src/sql/workbench/contrib/notebook/browser/notebook.component.ts
Was looking through some code and found some really old references to the sql-vnext extension, which has since been deprecated. These kernels are now contributed by the notebooks extension, which is built in.
=> Notebooks: Remove unnecessary reference to sql-vnext extension

product.json
Fixes #9085
Two separate links - one for **Search Feature Requests** and one for **Request a missing feature** in the send-a-smile dialog.
Currently they both are set to go to https://github.com/Microsoft/azuredatastudio/issues?q=is%3Aopen+is%3Aissue+label%3AEnhancement+sort%3Areactions-%2B1-desc. This is what VS Code does and seems to make sense for the Request a missing feature link since that doesn't have them fill out a form ahead of time so having users see the currently open list of issues is likely to reduce duplicate issues.
I set up two separate fwlinks though in case we want to change this behavior in the future without requiring a product update. 
Note that currently you can select **Feature Request** from the dropdown in the dialog 
in which case it'll open up a generic issue …
=> Fix feature request links

extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts, extensions/big-data-cluster/src/bigDataCluster/localizedConstants.ts, src/sql/workbench/browser/modelComponents/divContainer.component.ts, src/sql/workbench/browser/modelComponents/loadingComponent.component.ts, src/sql/workbench/browser/modelComponents/media/loadingComponent.css
Fixes #7662
1. "Loading Completed" was always being announced when walking the tree in text mode. Changed to using the general aria status helper function instead - this way it isn't in the DOM so the screen reader won't announce it unnecessarily
2. Clickable was always being announced because we were always hooking up a click handler for divs. I changed it so the click handler is hooked up dynamically now and is removed if clickable is set to false so this no longer announces
Output after loading is completed :
```
menu
menu item
controller:  [IP/user] level 1
Loading health status completed 
```
Output now when walking tree after loading is completed :
```
tab
App
Cluster Properties
Cluster State :
Ready
Health Status :
Healthy
Cluster Overview
Last Updated : 2/7/2020 9:48:09 AM
```
and …
=> Fix loading and clickable div screen reader issues

src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
Added a listener for escape key, row will be reverted upon hitting escape. Also the currentEditCellValue is set to undefined in the function so that the value will not persist upon clicking another cell.
This PR fixes #9083
=> Fix for revert on pressing escape.

src/sql/platform/connection/common/connectionProfileGroup.ts, src/sql/platform/connection/common/utils.ts, src/sql/platform/connection/test/common/connectionProfileGroup.test.ts
Fixes #9086 and fixes #9081
Same basic fix as #9099 but I prefer fixing it this way (plus added tests)
Tests should really be added for the filtering methods as well but that isn't set up to be easily testable so I went with the minimum for now and will look into beefing the other testing up later.
=> Make connectionProfileGroup support undefined values

extensions/notebook/src/dialog/managePackages/addNewPackageTab.ts
(Hopefully) final fix for #7264. I was using the dialog earlier and lamented the lack of this feature, so I did some investigation. Over the past few months, the ability to listen to the Enter key was added to modelView for the Manage Access dialog.
We can use this functionality in the Add Package tab for the Manage Packages dialog in notebooks. Next up, we'll focus on the select box by default when changing the tab. But one step at a time 😄
=> Notebooks: Listen for Enter on Add Package Tab

extensions/notebook/src/jupyter/serverInstance.ts
I noticed when trying to click on the jupyter URL in the notebook output that there are encoded characters which prevent the URL from routing to the right instance. For example, '=' gets replaced by 
'%3D'. This change removes the encoding just for the user-facing message.
=> Print jupyter URL without encoded characters in notebook start message.

src/sql/workbench/browser/modelComponents/inputbox.component.ts
Fixes #9136
I'm going to go through and check other places for these kind of checks, it's likely we're doing this wrong in other places as well.
I looked around for an eslint rule to check this but couldn't immediately find one. @anthonydresser @aaomidi Either of you have any idea whether such a rule exists? (basically don't allow numbers in a logical statement)
=> Fix min/max ignoring 0 value

extensions/mssql/src/hdfs/ui/hdfsManageAccessDialog.ts
This addresses #7794.
On first launch of the dialog, it was possible to get an undefined error because we were trying to call focus() on an element that hadn't been initalized yet. Moved the logic just after we turn off the loading animation.
Also took a look at a potential issue where initializeView() could be called twice, so trying to prevent against that.
=> Fix for manage access dialog focus

src/sql/workbench/contrib/notebook/browser/models/cell.ts, src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts, src/sql/workbench/contrib/notebook/test/stubs.ts, src/sql/workbench/services/notebook/browser/notebookService.ts, src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts
Currently, a notebook that's marked as trusted will be reopened as untrusted after saveAs. This is because the current editor gets closed as part of saveAs, and the trust state is tracked by the editor input's URI. This change adds the new notebook file input's URI to the trusted cache as part of the save call, so that the trusted state is maintained as the new editor opens.
=> Maintain notebook trust status after saving.

extensions/azurecore/src/azureResource/commands.ts, extensions/azurecore/src/azureResource/providers/resourceTreeDataProviderBase.ts, extensions/azurecore/src/azurecore.d.ts, extensions/resource-deployment/src/typings/ref.d.ts, extensions/resource-deployment/src/ui/modelViewUtils.ts
Previously any error while fetching resources would fail the whole fetch. But it's common that a user may not necessarily have access to query all resources and so updated the API to allow ignoring the errors while fetching. 
Then fixed up the resource deployment dialog to do this so that the dropdowns will populate with whatever it's able to get.
These commands were just recently added (and aren't documented) so no one else should be using them at this time. I plan on coming back and adding these to the actual extension API to make discoverability and use of this easier - but for now leaving as just a command to fix the immediate blocking issue.
=> Improve azure resource API error handling

src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
The load dataset function now updates the rendered datasets upon loading a new dataSet (such as after a query).
This PR fixes #9145
=> call refreshDatasets upon loading new dataset

extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts
The buggy code was wiping out the informational messages that we display at the top of the deployment screen that a tool was being installed. The fix makes sure that the informational messages are not cleared out if we are in an 'installing' state.
This PR fixes #8596
=> wipe status message only when not installing

extensions/admin-pack/package.json, extensions/admin-tool-ext-win/package.json, extensions/agent/package.json, extensions/cms/package.json, extensions/dacpac/package.json, extensions/import/package.json, extensions/profiler/package.json, extensions/query-history/package.json, extensions/schema-compare/package.json, samples/serverReports/package.json, samples/sp_whoIsActive/package.json
Proposed change - going forward we'll handle extension version bumps similar to how we handle it for ADS - every time we release the extension to the stable gallery we'll immediately bump the version.
This does mean that if we want to follow semantic versioning and end up doing a bug fix release for an extension we'll have to temporarily revert the version number - but in general I also think it's fine to just always bump up the minor version for every release (and then do major version bumps for major changes). Going along with this I aligned all the version numbers to the next minor version.
So this is the initial version bump for all currently released extensions.
=> Initial post-release extension vBump

src/sql/workbench/browser/parts/views/customView.ts, src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts
Fixes #9184
I'm not sure if this ever worked - I went back a couple releases and it was broken there.
In the end this is due to the refresh for asyncDataTree just calling getChildren on the provider when doing a refresh. Since the provider doesn't have any refresh functionality it expects that this will return the current set of children. But we weren't doing that - instead just returning the known set of children nodes and so any changes made after the initial load wouldn't be picked up.
=> Fix refreshing nodes in Azure view

src/sql/workbench/browser/modal/optionsDialogHelper.ts
Note that this didn't seem to have any functional impact - the setting was applied correctly. This is just making the UI display the selected value if it's specifically selected as False. 
Fixes #9166
=> Fix UI not selecting false options initially

extensions/dacpac/src/wizard/api/dacFxConfigPage.ts, src/sql/base/browser/ui/selectBox/selectBox.ts, src/sql/base/parts/editableDropdown/browser/dropdown.ts, src/sql/workbench/browser/modelComponents/dropdown.component.ts
This PR fixes #9183. Required wasn't being announced for dropdowns because it wasn't getting set.
=> Remove required from dacpac wizard dropdowns

src/sql/workbench/browser/modelComponents/inputbox.component.ts
This PR fixes #9272
the issue was introduced in https://github.com/microsoft/azuredatastudio/pull/9137
width and height can be strings for example 100px ,100%. I am reverting it to what it was before, for the scenario that width or height is 0, it is not a common case also we usually use 0px instead of 0.
with the fix:
=> fix the input width height issue

extensions/azurecore/package.json, extensions/azurecore/package.nls.json, extensions/azurecore/src/account-provider/azureAccountProviderService.ts, extensions/azurecore/src/apiWrapper.ts, extensions/azurecore/src/azureResource/providers/database/databaseTreeDataProvider.ts, extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerTreeDataProvider.ts, extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerProvider.ts, extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerService.ts, extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerTreeDataProvider.ts, extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerTreeDataProvider.ts, extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcProvider.ts, extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcService.ts, extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcTreeDataProvider.ts, extensions/azurecore/src/azureResource/resourceService.ts, extensions/azurecore/src/extension.ts, extensions/azurecore/src/localizedConstants.ts, extensions/azurecore/src/test/azureResource/providers/database/databaseTreeDataProvider.test.ts, extensions/azurecore/src/test/azureResource/providers/databaseServer/databaseServerTreeDataProvider.test.ts
Added a general setting for enabling Arc features - `azure.enableArcFeatures` which these new resource nodes are hidden behind.
This is mostly just a straight port from the work that Kevin did earlier. This also includes the resource renames that was suggested by the platform side.
=> Add Arc Resources to Azure view

extensions/resource-deployment/package.json, extensions/resource-deployment/src/services/bigDataClusterDeploymentProfile.ts, extensions/resource-deployment/src/ui/deployClusterWizard/pages/deploymentProfilePage.ts
This PR fixes #9179 and update the azdata version requirement.
also slide in the change to fix the issue that the card is not tall enough for the AD option.
=> keep up with latest azdata

src/sql/workbench/browser/taskUtilities.ts
The issue was that the `currentConnection` wasn't being resolved for `Dashboard` connections (it assumed the connections only from `ObjectExplorer` or `QueryEditors`
Fixes https://github.com/microsoft/azuredatastudio/issues/9270
=> Fix azdata connection API for dashboard connections

extensions/notebook/src/jupyter/jupyterSessionManager.ts
Should fix #9155 - @chlafreniere @corivera is there an easy way to check that this is actually fixed?
=> Add livy_session_startup_timeout_seconds config back in

src/sql/workbench/services/serverGroup/browser/serverGroupDialog.ts
Fixes #9309
Registering the listeners requires that the dialog be rendered (because it's hooking to the components) so setting isRendered after that call meant we would always throw when trying to do the render.
=> Fix server group dialog open

src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts
If you try to save the notebook right after opening it, the underlying notebook model may not be ready yet. This was causing an undefined error in setTrustForNewEditor.
=> Check if notebook model is undefined in setTrustForNewEditor.

extensions/agent/package.json, extensions/machine-learning-services/package.json, extensions/mssql/package.json
This PR fixes #8938
@kburtram the agent tab is already filtered for standalone server now, i am making furthur changes to make it only visible for server context. also updated other extensions that are contributing dashboard tabs.
agent tab is not showing for database dashboard now:
agent tab is not showing for Azure SQL DB:
=> only show the tabs for server context

src/sql/workbench/common/editor/query/queryEditorInput.ts, src/sql/workbench/contrib/query/common/fileQueryEditorInput.ts
Implements the editor.move api for file query editors. This will allow vscode to handle proper replacing of the editor when an underlying file is renamed. (at the moment if the file is rename we just close the editor and don't reopen the editor for the file.
In theory we could also use this to maintain connection state, but I think that would need a design review and api changes to work properly.
@chlafreniere may also want to implement this for notebooks, but since I'm not familiar and it seems like that might be more complex I'm sticking with just query editor atm.
Also fixes a bug when a disposed editor was trying to trigger an update label.
=> Implement query editor move

extensions/dacpac/src/wizard/api/dacFxConfigPage.ts
This PR fixes #9187. The database dropdowns weren't populating in the dacfx wizard if the user didn't have access to the master db. This is because there was an error during the listDatabases call. For now, this will just add the database from the connection to the databases dropdown if there is an error duing the listDatabases call. Opened #9361 for the error from azdata.connection.listDatabases
=> Fix for dacfx wizard if user doesn't have access to master db

extensionsGallery-insider.json
Removing redundant preview tag (we already have the preview badge in the gallery page) and shorten description - it doesn't wrap so having a long description like that doesn't look nice. The README provides a better description anyways.
=> Update name and description for arc deployment ext

src/sql/workbench/browser/modelComponents/checkbox.component.ts
A 0 width/height element doesn't really make much sense here but we should still do the right check
=> Fix checks for checkbox height/width

extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts, src/sql/azdata.proposed.d.ts, src/sql/base/browser/ui/checkbox/checkbox.ts, src/sql/workbench/browser/modelComponents/checkbox.component.ts
Fixes #9323
Screen reader output now : 
```
I accept Microsoft Privacy Statement, SQL Server License Terms and azdata License Terms.  check box  not checked  required  invalid entry  
```
=> Add required property to checkbox and set it for deployment dialog

src/sql/platform/connection/test/common/connectionStore.test.ts
Not really necessary since this is never actually used for a real connection, but doing this to get rid of the TSA scan flagging this.
=> Use uuid for test

src/vs/workbench/browser/labels.ts
Vscode added special casing of untitled files for the tab titles, that is bypassing our connection info feature.
=> Remove special casing of untitled

build/azure-pipelines/darwin/sql-product-build-darwin.yml, build/azure-pipelines/linux/sql-product-build-linux.yml
this is for the 2nd work item tracked in #9391 - upload the extension unit test coverage files to pipeline artifacts, i am not using the publish test coverage step in the pipeline due to following 2 reasons:
1. ADO limitation, one pipeline can only have one test coverage upload step (mentioned in the issue)
1. having the report for each extension will make it easier for extension authors to only look at their own area
folder structure in the drop artifacts:
download the icov-report folder of an extension and open the index.html, you can have very detailed coverage report.
also fixed the following issues:
1. fix the macos build warning - we are not running integration test in it, removing the step to fix the warning
1. upload the correct test results for linux job
without the fix:
with the …
=> upload the extension unit test coverage files to pipeline

extensions/integration-tests/src/objectExplorer.test.ts
this test has been failing occasionally, mark it as unstable for now.
=> mark as test as unstable

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts, src/sql/workbench/contrib/notebook/find/notebookFindModel.ts, src/sql/workbench/contrib/notebook/test/electron-browser/notebookFindModel.test.ts, src/sql/workbench/services/notebook/browser/models/cell.ts, src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts
At a minimum, this should improve #9275.
Problem: The notebook find model used to use markdown cells' source with some heuristics to get the index for which element to highlight for find results in markdown cells. This causes find not to work for many notebooks.
This solution: The notebook find model needs to access the actual rendered innerText. As long as we use the same mapping array of html elements for finding ranges and doing the actual highlighting, we solve a whole host of issues. We store this rendered output array in the cell model, which is accessible for both the text cell component and the notebook find model.
=> Improve find by tracking actual rendered text

.config/CredScanSuppressions.json
Unfortunately the tool doesn't support any sort of file globbing or wildcards so we'll have to add files one by one. This is currently the only one getting flagged though.
=> Add CredScanSuppressions file

extensions/mssql/config.json
Getting updated DacFx bits and also includes [Correctly skip intellisense for non-MSSQL language flavors ](https://github.com/microsoft/sqltoolsservice/pull/910 )
=> bump sqltoolsservice to 2.0.0-release.50

src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts
- Remove edit from home toolbar
- Add Refresh to the toolbar of other pages too if it has widgets container, grid container, or nav section because these have refresh implemented. Refresh for other tab content types are no ops so refresh won't be shown there because the extensions should define the refresh action themselves.
=> Update toolbar actions

extensions/mssql/package.json, extensions/mssql/package.nls.json, src/sql/workbench/contrib/dashboard/browser/pages/databaseDashboardPage.contribution.ts
- Move objects widget back to database home tab(previously was in a separate tab) so that home tab has content
- Reorder toolbar actions as specified by Hannah
=> Move objects widget back to database home tab

.github/workflows/merger.yml
The merger can't push to protected branches - for now I'll use a PAT but for next month i'll move this to a bot.
=> Change to PAT

.config/CredScanSuppressions.json
It's seeing the authorization header and flagging it because of that - even though this particular usage is just doing a deprecation check for the headers and so there's no actual secrets involved. Suppressing the file since this is build from index.ts anyways so scanning that should catch any issues we care about regardless. 
`[["gitdata", "git"], ["authorization", "oauthAuthorizations"], ["pullRequests", "pulls"]].forEach(([deprecatedScope, scope]) => {`
=> Suppress another file for CredScan

src/sql/workbench/browser/modal/modal.ts
Fixes #9228
The title wasn't being fully updated after changing the title.
Also fixed it so it actually sets the local _title var when set title is called, which seemed like another bug here too. 
Not sure why we were checking for undefined - it would be kind of odd but I don't see why clearing a title after opening a dialog shouldn't be allowed. Although currently if one was to try that it wouldn't look correct since the header area would still be there - just empty. If we really thought this was a supported scenario I suppose we should remove the header. But I figure we'll address that if it ever comes up as a valid scenario.
=> Update aria label for modal dialog when title is updated

src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts
Improves #8428 substantially to where most of the internal link formats are usable (as they are today on Mac). On Windows, the uri fragment's drive letter will be lowercase, where the work bench file path's drive letter will be uppercase, causing the condition to fail, and ADS to open workbench.html.
Tested on Mac and Windows, and using fsPath instead gets us around this issue.
=> Notebooks: Fix Internal Links on Windows

extensions/resource-deployment/src/ui/deployClusterWizard/pages/serviceSettingsPage.ts
previously the port label is not shown and caused confusion on the aria-label for the text boxes. always show it to make it clear.
This PR fixes #9292
=> always show the header

src/sql/workbench/contrib/notebook/find/notebookFindModel.ts, src/sql/workbench/contrib/notebook/test/electron-browser/notebookFindModel.test.ts
Fixes #9505.
We had an off by 1 error when multiple find results happened in the same cell. Only need to conditionally add 1 to the found text index once to convert between 0- and 1-based.
Also added a test.
=> Notebooks: Fix find highlight for multiple find occurrences

src/sql/workbench/browser/modal/modal.ts, src/sql/workbench/contrib/charts/browser/configureChartDialog.ts
I don't know why this was only getting input elements before for the modal body case, but that doesn't seem correct. @alanrenmsft do you have any context on why this might have been done? I tested some other modal dialogs after this change and things seem fine - although we'll want to pay attention to the focusing for the next release to make sure things didn't regress.
With this change though the modal dialog will handle selecting the correct element so we don't need to have the custom logic to focus it in the chart view. 
Also fixed loc key name while I was here.
=> Fix tabbable selector for modals

src/sql/workbench/services/accountManagement/browser/media/accountDialog.css, src/sql/workbench/services/accountManagement/browser/media/accountListRenderer.css
Long text (such as a long display name/account name) was causing the delete action to be pushed offscreen.
I played around with fixing it so that it worked correctly with the hover but couldn't get it to work properly - and after thinking about it a bit I think it's better to just remove the hover stuff anyways. It's not very accessibility-friendly and we've had numerous complaints about discoverability being difficult when actions are hidden.
New look with long text : 
with shorter text : 
Fixes #9435
=> Fix long account dialog text hiding actions

src/sql/workbench/contrib/dashboard/browser/core/actions.ts
this PR fixes #9536 
this is a vscode icon and they have changed the class name, i searched in the code, this is the only placing referencing the icon in sql tree and vscode is also using it as a string directly no constant defined for it. so I just replaced the strings.
before 
after
=> fix collapse widget action icon

src/sql/workbench/browser/modelComponents/formContainer.component.ts
This was changed in https://github.com/microsoft/azuredatastudio/pull/8233. The original issue being fixed is still active (having the steps label for wizards have a heading level). This is just fixing it so form component labels don't have that since they don't have any content below them. 
Fixes #9230
Fixes #9225
Fixes #9172
=> Make form item labels normal text components instead of headers

src/sql/workbench/services/accountManagement/browser/media/accountListRenderer.css
The addition of the overflow: hidden attribute caused the text to be cut off when the refresh message wasn't being displayed.
With fix
=> Fix account label being cut off

.github/commands.yml
Some help from @yualan would be useful for the best wording for the comment.
Also not sure if we want to use the existing `Needs More Info` label or we want to create a label specifically for 'needs logs'.
EDIT:
Moved to `Needs Logs` label
=> Add automated comment for needs logs.

src/sql/workbench/services/accountManagement/browser/media/accountDialog.css, src/sql/workbench/services/accountManagement/browser/media/accountListRenderer.css
Long text (such as a long display name/account name) was causing the delete action to be pushed offscreen.
I played around with fixing it so that it worked correctly with the hover but couldn't get it to work properly - and after thinking about it a bit I think it's better to just remove the hover stuff anyways. It's not very accessibility-friendly and we've had numerous complaints about discoverability being difficult when actions are hidden.
New look with long text :
with shorter text :
=> Fix long account dialog text hiding actions (Port #9449)

src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts
Ports #9513.
Improves #8428 substantially to where most of the internal link formats are usable (as they are today on Mac). On Windows, the uri fragment's drive letter will be lowercase, where the work bench file path's drive letter will be uppercase, causing the condition to fail, and ADS to open workbench.html.
Tested on Mac and Windows, and using fsPath instead gets us around this issue.
=> Notebooks: Fix Internal Links on Windows (#9513)

src/sql/workbench/contrib/extensions/browser/extensions.contribution.ts, src/vs/workbench/workbench.common.main.ts
@v-bbrady is working on the welcome page and he needs the ability to open Extension details using command link, the vscode command: "extension.open" only accept string parameter which doesn't work with command link, command link expects all parameters to be inside an JSON object. adding a shim command for it instead of updating the vscode command to avoid merge conflicts.
usage example to open agent extension page:
href="command:azdata.extension.open?%7B%22id%22%3A%22microsoft.agent%22%7D"
=> add azdata.extension.open command

extensions/notebook/resources/notebooks/JupyterBooksCreate.ipynb
This PR addresses issue 9577. 
With the latest pip, if a package is not installed instead of returning an empty array on pip show, it returning a warning message ex below. Updated the notebook code for checking length > 1 instead of 0. 
https://github.com/microsoft/azuredatastudio/issues/9577
=> check for proper length of the cmdOutput

extensions/notebook/src/book/bookTreeItem.ts
This is for #9595.
Was setting context key incorrectly beforehand; we really need to check for the existence of sections, since that's how the viewlet is populated.
=> Fix search icon only working when section expanded

src/sql/workbench/browser/taskUtilities.ts, src/sql/workbench/contrib/query/browser/flavorStatus.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/9592
Not all inputs have a resource so make sure we check for that. All existing callers of this function were already assuming it could return undefined - just making that more explicit now. 
Original error was from taskUtilities but noticed and fixed some others in flavorStatus while I was looking at this.
=> Check for valid uri/resource

src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.css
adjust the order of css selectors to fix the issue that wrong icon is shown for dark theme.
=> update the order of css selectors

src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.component.html
This PR fixes #9288 
the order the items are added to the DOM tree is opposite of their visual order, now i am using flex property to achieve the same visual effect.
=> update elements order

src/sql/base/browser/ui/panel/tab.component.ts
noticed this for quite a while, finally fixing it. in the screenshot below see the focus indicator (blue line), it is focusing on the whole tab panel, which is unnecessary.
=> remove unnecessary tabindex attribute 

extensions/admin-tool-ext-win/src/main.ts, extensions/admin-tool-ext-win/src/test/utils.test.ts, extensions/admin-tool-ext-win/src/utils.ts
Testing coveralls integration by adding some tests! Still only ~50%, but the majority of the code here isn't really something that is easily covered with a unit test and should probably be done in a full integration test. 
To increase the coverage I did remove a few places where we were doing what should be unnecessary checks. For example the undefined check in getPackageInfo - it's safe to assume that exists since if it doesn't that means things are really broken anyways and there isn't any recovering from that state.
=> Increase test coverage of admin-tool-ext-win

extensions/notebook/src/book/bookTreeView.ts, extensions/notebook/src/common/apiWrapper.ts
Currently trusting a book does not update the Trust status of currently opened, inactive notebooks -- only those which are opened after the book was trusted. This fix updates the trust state of already opened books whenever trusting a book.
=> Fix trusting opened notebooks

src/sql/workbench/browser/modal/modal.ts, src/sql/workbench/services/connection/browser/connectionDialogWidget.ts
Fixes #9410
I considered adding a default "Loading" title if none was specified but I think I prefer that this be an opt-in thing since loading might not make sense in all scenarios.
I also considered doing the suggestion of having a timeout for the announce so we only announce if some amount of time has passed but that seemed like overkill - and I'd actually rather it be consistent in whether it announces something or not.
=> Add connecting title to spinner for Connection dialog

src/sql/workbench/browser/modal/media/modal.css
This PR fixes #9297 
using the same blue color as the wizard page number for the informational message background.
the contrast ratio is now:
also checked the contrast ratio for Error and Warning, they are both greater than 4.5:1, and for high contrast theme, we use default color, and it looks good too.
=> fix the contrast ratio

src/sql/workbench/browser/modal/media/modal.css
This PR fixes #9321 
the default outline color on focus doesn't have enough contrast ratio for the message header, i am setting its color per message level now, also increase the bottom/top margin to make the outline visible
=> fix the focus outline color

src/sql/workbench/browser/modal/modal.ts
This PR fixes #9293
finally figured out why the focus is moving away, setting the dialog.message will change the focus 😆 
the fix is to keep the focus if the it is already inside the dialog.
=> do nothing if the focus is already in dialog

extensions/dacpac/src/wizard/pages/deployPlanPage.ts
This PR fixes #9260. The table wasn't being recognized as a table by screenreaders because the role was alert. This was previously added to solve #6826, but that only asked for the loading status to be announced and it still is after this change.
=> Fix screenreader not reading tabular structure in dacpac deploy page

.github/workflows/ci.yml
This is an attempt to work around an issue with coveralls where push CI builds don't seem to handle parallel uploads correctly. 
https://github.com/lemurheavy/coveralls-public/issues/1403 seems to be the same/a similar type of issue
So instead of using parallel upload I'm just having it merge all the files together before doing the upload.
=> Work around coveralls parallel upload issue

build/azure-pipelines/sql-product-build.yml
Fixes #9642. Goal of this PR is to reduce the likelihood of timeouts for Linux and Windows jobs.
=> Timeout extention for Linux and Windows pipelines

extensions/resource-deployment/src/ui/deployClusterWizard/pages/summaryPage.ts
if two messages come in a short period of time, the screen reader will read the later one, there is really no good fix to the issue, since we already have the same message in the notebook, I am removing it from the wizard to avoid the issue.
This PR fixes #9348
=> remove the message on page enter

src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.component.html, src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.component.ts, src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts, src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.css, src/sql/workbench/contrib/dashboard/browser/core/dashboardPanel.css, src/sql/workbench/contrib/dashboard/browser/core/dashboardPanelStyles.ts, src/sql/workbench/contrib/dashboard/browser/pages/databaseDashboardPage.component.ts, src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.component.ts, src/sql/workbench/contrib/dashboard/browser/widgets/properties/propertiesWidget.component.html, src/sql/workbench/contrib/dashboard/browser/widgets/properties/propertiesWidget.component.ts, src/sql/workbench/contrib/dashboard/test/electron-browser/propertiesWidget.component.test.ts, src/vs/workbench/common/theme.ts
- Update look of left nav
- Dashboard widget wrapper: get rid of grey header, bold title
- Update border lines of toolbar and properties widget to change color with the theme
Mockup: https://www.figma.com/proto/QRkuP8YG7sZr87LRoS210ldo/Azure-Data-Studio?node-id=7109%3A173389&viewport=-833%2C-19569%2C0.5569696426391602&scaling=min-zoom
Changes in this PR:
horizontal tabs are still the old style:
=> Update dashboard style to be closer to mockups

build/azure-pipelines/sql-product-build.yml
This will help discovering builds of a particular type from our product build pipeline. I was originally thinking we'd just create separate pipelines for different types (such as the saw one I created) but that just gets messy and means we might miss updating all the pipelines with configuration changes.
Example build : https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=58427&view=results
=> Add quality build tag to build

src/sql/workbench/browser/modal/media/optionsDialog.css, src/sql/workbench/browser/modal/optionsDialog.ts, src/sql/workbench/contrib/connection/test/browser/advancedPropertiesDialog.test.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/9204
Fixes https://github.com/microsoft/azuredatastudio/issues/9206
The ScrollableSplitview is a huge issue for accessibility - it will add/remove items from the DOM as it scrolls and as such things outside of the view aren't actually in the DOM and so tab navigation doesn't work. 
In the end using the splitview for the options dialog is overkill anyways - the only thing we really gain from that is the collapsible sections but I don't see that being an important enough feature to develop a replacement fix for and so instead I'm just adding the panes directly to the body container.
Old look : 
New look : 
Tabbing in action : 
Verified screen reader is still announcing titles correctly :
```
Connect timeout  edit    30
Connect …
```
=> Refactor options dialog to not use splitview

src/sql/workbench/browser/modal/modal.ts, src/vs/workbench/browser/workbench.contribution.ts
when we close the dialog opened by the action buttons in the view header (e.g. new connection dialog, new server group dialog, connect to BDC controller dialog and so on...), we are not able to easily set the focus back to the original button because it is no longer visible. 
It seems a proper fix for this would not be trivial and might take sometime for vscode team. This PR is a simple/low cost workaround for it.
This PR fixes #9227
=> restore focus

src/sql/media/icons/common-icons.css, src/sql/workbench/contrib/dashboard/browser/pages/databaseDashboardPage.component.ts
1. Backup icon was centered again(probably from merge from master)
2. Database page toolbar border wasn't getting set to the right color when opened from the databases tab in the server dashboard
before:
after:
=> small dashboard toolbar fixes 

src/sql/media/icons/common-icons.css, src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.css
Undo previous changes in common-icons.css that removed the center center from the icons being used in the dashboard toolbar. Now the position for the toolbar icons is getting set in the dashboard page css
=> Add back center center in common-icons.css

src/sql/workbench/contrib/dashboard/browser/widgets/properties/propertiesWidget.component.html
Bottom border of properties widget wasn't showing after collapse action was fixed in #9537
because it moved the other content of the widget down.
before:
fixed:
=> Fix properties widget bottom border not showing

src/sql/base/browser/lifecycle.ts
This PR fixes #9708 
It is because the unsubscribe didn't really do the job. if we pass in the method directly, the `this` reference will not be the subscription object as it expects. I've fixed similar issues before.
@Charles-Gagnon I am not going to convert the Observable to Event now, If we have to stop using Angular if we really want to get rid of all Rx Observables, by that time, we can refactor the code to use Promise directly.
=> fix sub leak

extensions/azurecore/extension.webpack.config.js, extensions/azurecore/package.json, extensions/azurecore/yarn.lock
The core product injects their keytar into the extensions, so you don't need to have it as a dependency.
=> Remove keytar from azurecore

extensions/mssql/package.nls.json, src/sql/base/browser/ui/panel/media/panel.css, src/sql/base/browser/ui/panel/panel.component.ts, src/sql/base/browser/ui/panel/tabHeader.component.ts, src/sql/workbench/contrib/dashboard/browser/core/dashboardPanelStyles.ts
fixes the following issues
1. VoiceOver reads the tab header as presentation
1. VoiceOver reads the tab name twice
1. Focus indicator not visible for focused tab header
1. Should be able to navigate between tabs using arrow keys
=> tab panel fixes

extensions/theme-carbon/themes/light_carbon.json
Per accessibility team we need to meet 3:1 contrast ratio in default themes
Fixes #9205
=> Increase constrast ratio of input boxes in default light theme

src/sql/workbench/browser/modal/optionsDialog.ts
Fixes #9738
The fix here for that was to clear the body of existing child nodes before adding new ones. This logic was in there before, I just missed adding it back in during my refactor.
=> Fix duplicate options in Advanced Options dialog

issue_template.md
The new variant is stored here: https://github.com/microsoft/azuredatastudio/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
so the old one can be removed. 
Github also says the old method is deprecated.
This PR fixes #9746
=> Remove unused issue template

src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts
Fixes almost all cases of #7558.
When saving data from the SQL kernel, our HTML tables were all serialized on one line (e.g. <table><tr><th>blah.....</table>). If there was enough data, in the table (more than 20k characters by default), then users would see a warning around tokenization.
Also tested on Jupyter, and HTML table data was loaded as expected. I also saved a notebook with ADS, edited the JSON, removed the vnd.dataresource output, and the HTML table also loaded in ADS.
I suppose if row data includes more than 20k characters, the message will pop-up for them, but let's start here and decide if we need to refine this further.
=> Fix Notebook Tokenization Warnings

extensions/notebook/package.json
Fixes https://github.com/microsoft/azuredatastudio/issues/9318
The context key these are using were removed in https://github.com/microsoft/azuredatastudio/pull/9139/files#diff-d6b0380fdfb46feed80fd9c6628eb43dL181 and replaced with this new clause but these were missed.
=> Fix notebook command palette clauses

src/sql/workbench/browser/modal/modal.ts, src/sql/workbench/browser/modal/optionsDialog.ts, src/sql/workbench/browser/modal/optionsDialogHelper.ts
Cleaned up the disposable use in the Options and Modal dialog classes. There were a couple issues here : 
1. We were calling dispose on the hide function of the Options dialog, but then re-using the same object and just calling open again later which caused errors to be thrown about trying to add things to a disposed object (through _register). Instead made it follow the Modal dialog way and just changed it to only dispose the things that needed to be disposed of (such as temporary UI elements) when closed
2. Updated Modal to use DisposableStore instead of keeping track of temporary elements separately
=> Clean up modal/options dialog disposable use

extensions/cms/package.json
The CMS commands were showing up in the palette, but as written most of them currently don't do anything when ran and so were just cluttering it up with generic names like "Delete".
The only one I left was "Add Central Management Server" since that will still function correctly.
=> Remove most CMS commands from palette

src/sql/workbench/contrib/telemetry/common/telemetry.contribution.ts
Also removed user type events since we can get that ourselves now. 
This approach is definitely unmaintainable in the long-term, I'm going to think about how to improve this but in the meantime we can at least lower the amount of commands we're tracking that we don't care about.
=> Filter some more commands

extensions/resource-deployment/src/ui/modelViewUtils.ts, src/sql/workbench/browser/modelComponents/checkbox.component.ts, src/sql/workbench/browser/modelComponents/dropdown.component.ts
This is primarily for resource deployment.
Most ModelView components aren't currently correctly hooked up for proper validation. This made it so dialogs which had the components marked as required weren't actually checking that and so the Ok/Next button would still be enabled.
Fixing this for dropdowns and checkboxes so that if they're required then they must have a value/be checked. Other components can be fixed up to do the checks as needed. 
Verified on both MIAA and PostgreSQL Deployment dialogs
Checkbox : 
Dropdown disabled (note other fields are filled in correctly)
Dropdown enabled
=> Add required value validations for checkbox and dropdown

src/sql/workbench/browser/modelComponents/media/declarativeTable.css
Fixes https://github.com/microsoft/azuredatastudio/issues/9666
This was changed in https://github.com/microsoft/azuredatastudio/commit/19dec78349052ca831a589ac9a558baa218cac0f#diff-69a589c622a2a6a973d6f0879cd537d3R20. Likely a typo here that caused it to be left as border-left.
=> Fix declarative table missing right border

src/sql/workbench/browser/modelComponents/media/toolbarLayout.css
the outline-offset for button is set to be 2px in vs code tree (all the buttons in VSCode and ADS behaves). adding 3px of top and bottom padding to the container to accommodate it.
This PR fixes #9792
=> add padding for toolbar container

src/vs/workbench/contrib/extensions/browser/extensionsList.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/9787
This has since been fixed on the VS Code side in https://github.com/microsoft/vscode/commit/643c3fbc31c7fbc1152241395a4f19de9c995406#diff-b1281ff290c54d91138a34a8dd7d76e9
They moved a lot of stuff around - the specific logic here was moved into its own action here : https://github.com/microsoft/vscode/commit/e52f57d02671a33102ae8cc6e5790b594361a4d9
This is a temporary fix until the VS Code fix is merged in.
=> Fix extension gallery

src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
This makes it so that upon a new row cell is selected, a new row is automatically created below, instead of having the new row be created when the change is about to be submitted.
This PR fixes #9033
=> Create new row upon focus on last row

extensions/mssql/package.json, extensions/mssql/package.nls.json, src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.contribution.ts
according to the mock up, the databases tab should be added under the home tab
=> databases tab

extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
This PR fixes #9727. Similar to fix done for DacFx wizard in #9362.
The schema compare dialog wasn't loading if the user didn't have access to master because populating the database dropdowns was failing. For now, this will just add the database from the connection to the databases dropdown if there is an error during the listDatabases call. I previously opened #9361 for the error from azdata.connection.listDatabases.
=> Fix for schema compare dialog if user doesn't have access to master db 

extensions/azurecore/src/account-provider/auths/azureAuth.ts, extensions/azurecore/src/azureResource/tree/accountTreeNode.ts
This PR fixes #9771 
Some subscriptions don't allow us to authenticate with them, causing issues in our code. I'm logging these subscriptions we're filtering out and I don't think this is the best solution, but at least if it happens to anyone we can dig deeper and understand whats going on with these subscriptions.
Special thanks to @chlafreniere for catching this bug and helping me debug it.
=> We can't authenticate to every subscription

src/vs/platform/telemetry/browser/workbenchCommonProperties.ts, src/vs/platform/telemetry/node/commonProperties.ts
Add quality and msftInternal properties to events. Default quality is dev since we don't have quality in the checked in product.json which is the only time it should be undefined.
=> Add some more event properties

src/sql/workbench/services/connection/browser/connectionWidget.ts
The connection widget wasn't selecting the correct linked account when the user had multiple accounts linked.
=> Connection widget dialog fix

src/sql/base/browser/ui/panel/media/panel.css, src/sql/workbench/browser/modelComponents/media/tabbedPanel.css
this pr fixes #9841 
in my previous PR's i have updated the panel css, and didn't realize it impacts the query editor and profiler editor. these changes will revert the query editor's old behavior meanwhile make the dashboard look the same. I will review these styles and try to consolidate them later.
with the change:
offending PRs: https://github.com/microsoft/azuredatastudio/commit/41d21d799cc2adfdd38a85356eb3617b81d4b231#diff-9362485f5d7a7bebeb607a247cda813b
https://github.com/microsoft/azuredatastudio/commit/be83b31e378774ed14879fb1889c47422e68bea5#diff-9362485f5d7a7bebeb607a247cda813b
=> revert the changes impacting query editor and profiler editor

src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts, src/sql/workbench/services/notebook/browser/models/cell.ts
Simple implementation for running ADS commands via notebooks. I don't anticipate that many people will leverage this functionality outside of our team, but I know this is an ask for scenarios such as the DRI notebook.
Wanted to keep it notebook provider-agnostic, so that's why this lives in the cell model for now.
Configured by a setting which is set to false by default.
=> Notebooks: Add ability to run ADS commands

src/sql/workbench/services/dialog/browser/dialogContainer.component.ts, src/sql/workbench/services/dialog/browser/wizardModal.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/7412
We weren't updating the container component when navigating to another page, this fixes that so modifying the page number will update the display accordingly.
=> Update step when page is navigated to

src/sql/workbench/contrib/notebook/browser/notebook.component.ts
This PR fixes offset when navigating to a section on a notebook.
The current method gets the offset relative to the document, which makes the header title no longer visible when navigating to the section. 
We should get the offset relative to the parent node, instead.
=> Fix offset when scrolling to section

src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.css
Fixes these three issues:
old: 
new:
=> Update dashboard breadcrumb style to match mockups

src/sql/workbench/browser/actions.contribution.ts
No longer show the connection dialog on 1st launch since we have a new Welcome page that has a better experience, including a prominent "Create Connection" button.
*Current 1st Launch*
*Proposed 1st Launch*
=> Turn-off connection dialog on 1st-launch

src/sql/workbench/contrib/dashboard/browser/core/dashboardPanelStyles.ts
This fixes: 
When navigating using arrow keys, there isn't a second border around the tab. 
Full outline for active tabs (picture looks better when you click on it):
=> Change active tab to have full outline for high contrast

src/sql/workbench/contrib/notebook/test/electron-browser/notebookUtils.test.ts, src/sql/workbench/services/notebook/browser/models/cell.ts, src/sql/workbench/services/notebook/browser/models/notebookUtils.ts
Noticed that we had some code that we don't need anymore (references to an old CTP for rewriting Spark URLs in notebooks). Tested with the latest CU bits, and the URLs are being rewritten as expected to the external endpoints.
Took the opportunity to refactor a method into the notebookUtils class and just did a couple of quick test cases based on some real-world inputs. I realize it's not exhaustive, but it's a good start.
=> Notebooks: Remove Unnecessary Rewrite Code, Add Tests

src/sql/workbench/contrib/dashboard/browser/containers/dashboardHomeContainer.component.ts, src/sql/workbench/contrib/dashboard/browser/containers/dashboardHomeContainer.css, src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.component.html, src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.component.ts, src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.css, src/sql/workbench/contrib/dashboard/browser/pages/databaseDashboardPage.component.ts, src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.component.ts, src/sql/workbench/contrib/dashboard/browser/widgets/properties/propertiesWidget.component.ts, src/sql/workbench/contrib/dashboard/test/electron-browser/propertiesWidget.component.test.ts
Updates for properties widget to look more like mockup:
- Remove title "SERVER DASHBOARD" because it isn't in mockups 
- Remove ellipses because refresh action has been moved to the toolba
- Move collapse chevron icon to bottom center of widget instead of current top right location 
expanded:
collapsed:
=> Properties widget updates

src/sql/base/browser/ui/panel/media/panel.css
to match the mock up.
**before**
**after**
=> fix dashboard tab style

extensions/azurecore/src/account-provider/auths/azureAuth.ts
This PR fixes #9885 
So it seems like some users have access to tenants that they can't do resource management on. Keeping these tenants in the account seems silly as no operation will work on them.
Let's log and remove these tenants from the user profile in ADS. If they ever do get access to these accounts back, a simple restart of ADS will repopulate these and try again.
=> Remove unusable tenants

extensions/agent/package.json, extensions/mssql/package.json, src/sql/workbench/contrib/dashboard/browser/core/dashboardTab.contribution.ts
in our review meeting, we decided not to allow contribution of the custom tab group, instead, we will predefine the groups/categories. I got this list from @hannahqin , and updated the group of Agent extension. Update to the whoisactive and server reports will be in separate PRs.
=> pre-defined dashboard tab groups

extensions/mssql/config.json
includes these 3 changes:
[Fix default test server names file path construction (#941)](https://github.com/microsoft/sqltoolsservice/commit/1cb0b98148201da54a82a0a27313d14d941cdd4a)
[Fix to not add parens for global variable built in functions (#940)](https://github.com/microsoft/sqltoolsservice/commit/7d37de218a04c33ae0bda758305f2f90766f7063)
[bump DacFx nuget package (#942)](https://github.com/microsoft/sqltoolsservice/commit/bf6c573e7bb42b695c74a11bca3e32901c9f51eb)
=> bump sqltoolsservice to 2.0.0-release.56

build/gulpfile.hygiene.js
Specifically for https://github.com/microsoft/azuredatastudio/blob/master/docs/overview_screen.jpg, but we should be ignoring all JPGs anyways.
=> Ignore jpgs for whitespace check

src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts
Add undo support for markdown toolbar. Detects whether user is trying to do an undo, and acts accordingly.
Yes, I need tests. I'll be busy on Friday.
Note that this is intentionally "dumb" and matches other editors. If there isn't an exact match for the type of markdown that is being added/undone, then it assumes that the text should be transformed as if someone is trying to add the decorations.
=> Add Undo Support for Markdown Toolbar

src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.component.ts, src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.css
The bottom of dashboard widgets got cutoff after the collapse was moved to the bottom for properties widget. This fixes it by hiding the bottom toolbar for collapse when there isn't a bottom collapse.
cutoff bottom on database size widget:
fixed:
=> fix bottom of dashboard widgets being cutoff

src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.css, src/sql/workbench/contrib/dashboard/browser/pages/databaseDashboardPage.component.ts, src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.component.ts
Remove some padding to vertically center properties widget title when collapsed
before:
after:
=> Center properties widget title when collapsed

src/sql/base/browser/ui/panel/media/panel.css, src/sql/base/browser/ui/panel/panel.component.ts, src/sql/base/browser/ui/panel/tabHeader.component.ts
add max-width for tab label and scroll handling
max width - overflow ellipsis
scroll:
also double checked to make sure no impact on the existing UI using panel
=> more dashboard fixes

src/sql/workbench/contrib/dashboard/browser/widgets/properties/propertiesWidget.component.ts, src/sql/workbench/contrib/dashboard/browser/widgets/properties/propertiesWidget.css
To match mockups, opacity of property name should be 0.6 for light theme.
old:
fixed:
=> Fix style of property name in properties widget

extensions/mssql/package.json, src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.contribution.ts
This PR fixes #9831 
for Azure server and managed instance, for now show the databases widget on the home page.
=> show databases for azure server

src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.css
=> Center properties widget collapse icon

src/sql/workbench/contrib/charts/browser/chartView.ts, src/sql/workbench/contrib/charts/test/browser/chartView.test.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/9964
The Create Insight action passes the actual .sql file as part of the InsightsConfig, so the action isn't compatible with notebook files without extracting the notebook cell contents and creating a standalone .sql file. Removing this button for now.
=> Only show Create Insight button in Query Editor charts.

src/sql/workbench/contrib/editData/browser/media/editData.css
height and width for editdata now sizes to 100% to fix for tables with more than ten columns.
This PR fixes #9967
=> Fix for edit data sizing of table

src/sql/platform/telemetry/common/telemetryKeys.ts, src/sql/workbench/contrib/notebook/browser/notebook.component.ts, src/sql/workbench/contrib/notebook/test/electron-browser/notebookEditorModel.test.ts, src/sql/workbench/contrib/notebook/test/electron-browser/notebookFindModel.test.ts, src/sql/workbench/contrib/notebook/test/electron-browser/notebookModel.test.ts, src/sql/workbench/services/notebook/browser/models/notebookModel.ts
* Added Notebook telemetry for livesite
* added back the metadata retension code
* Unified Telemetry services
* fixed names
* Fixed texts to use new NullAdsTelemetryService
* Validate GUID before sending it
* made GUID check a bit more robust
Co-authored-by: Rajesh Kamath <rajkashop@hotmail.com>
This PR fixes  #9906
=> Added Notebook telemetry for livesite notebooks (#9948)

.eslintrc.json, src/sql/azdata.proposed.d.ts, src/sql/workbench/api/common/extHostModelViewDialog.ts, src/sql/workbench/api/common/sqlExtHostTypes.ts, src/sql/workbench/browser/modelComponents/tabbedPanel.component.ts
We weren't setting defaults so we'd get weird behavior if the value was left undefined. I fixed it so we get typings on the withLayout so that's less likely and then added appropriate defaults for the layout options (we should never require any layout options to be mandatory since we don't require calling withLayout to begin with - all layout options should have appropriate defaults). 
@anthonydresser The layering rules were complaining about the sqlExtHostTypes import - but I don't see any reason why that shouldn't be allowed. Does that look OK to you?
Fixes https://github.com/microsoft/azuredatastudio/issues/9947
=> Add typing for TabbedPanelLayout and set defaults

src/sql/base/browser/ui/panel/media/panel.css
This PR fixes #10002 
overwrite the default cursor to use pointer.
=> update the cursor of toggle state button

src/sql/workbench/contrib/notebook/browser/notebook.component.html
#10008 
Talked with design + PM and decided to bring this back for April after doing some testing with the newest bits. 
Pretty simple change; literally just bringing this code back to what it was previously.
=> Notebooks: Bring back hover buttons for adding cells

src/sql/workbench/contrib/welcome/page/browser/welcomePage.css, src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
* makes the preview button hover state stay active when hovering over tooltip
* fixes the duplicating list on the extension pack when a 2nd welcome page tab is opened
#9992
#9943
=> Fix duplicating list on extension pack (#9992) (#10003)

.github/workflows/ci.yml
Disabled in https://github.com/microsoft/azuredatastudio/commit/1868a7d3705e4dc32b438ab24303052ed2cc9f09 but there doesn't seem to be a clear reason why so re-enabling this unless we find a reason for us to also keep it disabled.
=> Re-enable CI pipeline

extensions/notebook/src/jupyter/jupyterServerInstallation.ts
The latest version of Anaconda hangs for a long time when trying to install sparkmagic from the default package channels. The version of sparkmagic from the conda-forge channel installs without any issues, however. The conda-forge version also has the most recent version of sparkmagic, and has way more downloads than the default channel. So I think we should prefer the conda-forge channel for installing our conda packages in the future. According to the conda docs, the install will fall back on the default channels if a package isn't found, so there shouldn't be any issues here with missing packages.
https://docs.conda.io/projects/conda/en/latest/commands/install.html#Channel%20Customization
Fixes https://github.com/microsoft/azuredatastudio/issues/9815
=> Check conda-forge channel first when installing conda packages.

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.html, src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts, src/sql/workbench/contrib/notebook/browser/notebook.component.ts
* Adding enablePreviewFeatures check before showing the new toolbar.
* Removed unused code.
* Added hook to trigger onDidChangeConfiguration -- this makes the UI change after user has checked or unchecked, without having to restart the app.
* Initializing the component with the current config value of enablePreviewFeatures.
This PR fixes #9989
=> UI - Markdown toolbar now behind preview flag (#10024)

src/sql/workbench/services/bootstrap/browser/bootstrapService.ts
The accessor was throwing when calling within the catch because the function was ended by the time the catch callback was called. Instead we should capture the service so we have it in case we need it.
=> Fix logging for angular bootstrapping errors

src/sql/base/parts/editableDropdown/browser/media/dropdownList.css, src/sql/workbench/services/connection/browser/media/connectionDialog.css
Also moved connection dialog specific rules to the connection dialog CSS for better consolidation.
display: flex was added to the icons in a VS code merge a while back - setting it back to inline-block so it displays correctly. 
For #10063
=> Fix arrow alignment for connection dialogs

src/sql/workbench/contrib/notebook/browser/notebook.component.ts
Replaced scrollTop with getBoundingClientRect().top. Created an offset that accounts for the combined height of the tab bar and action bar at top.
This PR addresses #10062
=> Notebook UI - Fixes navigation offset

src/sql/workbench/contrib/notebook/browser/notebook.component.ts
* Addresses bug: 10062. Replaced scrollTop with getBoundingClientRect.top minus the combined height of the top tabs and action bar.
* Setting initial value of chrome offset, and checking for existence of both tool bars before getting their heights.
This PR fixes #10062
=> Notebook UI - Fixes navigation offset (#10067)

extensions/notebook/src/book/bookTreeView.ts, extensions/notebook/src/common/localizedConstants.ts
=> Check treeItem first when building search path in searchJupyterBooks. (#10083)

src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts
#10091.
Non file schemes didn't work because we were checking the fileService for other schemes (e.g. https). Just a simple check here.
=> Notebooks: Ensure Other Schemes Beyond Files Work for Link Handler

src/sql/workbench/contrib/welcome2/gettingStarted/browser/abstractEnablePreviewFeatures.ts, src/sql/workbench/contrib/welcome2/gettingStarted/browser/enablePreviewFeatures.ts, src/sql/workbench/contrib/welcome2/gettingStarted/browser/gettingStarted.contribution.ts, src/sql/workbench/contrib/welcome2/gettingStarted/electron-browser/enablePreviewFeatures.ts, src/sql/workbench/contrib/welcome2/gettingStarted/electron-browser/gettingStarted.contribution.ts, src/sql/workbench/contrib/welcome2/page/browser/az_data_welcome_page.ts, src/vs/workbench/contrib/welcome/page/browser/welcomePage.contribution.ts, src/vs/workbench/contrib/welcome/page/browser/welcomePage.css, src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts
Only show the new welcome page if the preview flag is set to true when ADS is launched.
This addresses issue https://github.com/microsoft/azuredatastudio/issues/10100.
=> Put new welcome page behind preview features flag

build/azure-pipelines/darwin/sql-publish.ps1, build/azure-pipelines/linux/createDrop.sh, build/azure-pipelines/linux/sql-publish.ps1, build/azure-pipelines/sql-product-compile.yml, build/azure-pipelines/win32/sql-publish.ps1
the quality is already part of the version, so remove that part, and move the version generation to the compile step which is guaranteed to always run
=> Removing quality addition in naming and move to compile step

src/sql/base/browser/ui/taskbar/media/taskbar.css
This PR fixes #10001. The width of the toolbar separator was becoming zero sometimes when resizing the toolbar. Setting the padding-left to 1px instead looks the same and doesn't disappear when resizing. 
Previous:
fixed:
=> Fix Taskbar separator sometimes disappearing

src/sql/base/browser/ui/propertiesContainer/propertiesContainer.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/10116
We were subscribing to the event but never unsubscribing when the dashboard was closed (destroyed).
=> Fix view destroyed errors

src/sql/workbench/contrib/dashboard/browser/containers/dashboardHomeContainer.component.ts, src/sql/workbench/contrib/dashboard/browser/contents/widgetContent.component.html, src/sql/workbench/contrib/dashboard/browser/contents/widgetContent.component.ts, src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.html, src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts
1. the content page area doesn't respond to the "Problems/Tasks..." & Editor split panel resizing, this is caused by the use of scrollable component, I looked at the query editor code which is also using the scrollElement as the dashboard page content, but it is recalculating the height based on the Window's mouse event with throttling, I did similar thing, but our scrollable angular directive is not performing the horizontal properly. I went ahead to use the overflow to control the scroll behavior.
2. the widget size will be reduced when the page size is reduced, but never gets restored, i haven't figured out a way to restore the size, but i find it is not very useful, so I changed the configuration to let the widgets maintain their original size.
feel free to let me know if you want a …
=> fix server/database dashboard content scroll

src/sql/base/browser/ui/loadingSpinner/loadingSpinner.component.ts, src/sql/base/browser/ui/loadingSpinner/media/loadingComponent.css, src/sql/base/browser/ui/propertiesContainer/media/propertiesContainer.css, src/sql/base/browser/ui/propertiesContainer/propertiesContainer.component.ts, src/sql/workbench/browser/modelComponents/media/propertiesContainer.css, src/sql/workbench/browser/modelComponents/propertiesContainer.component.ts, src/sql/workbench/contrib/dashboard/browser/containers/dashboardHomeContainer.component.ts, src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.component.html, src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.css, src/sql/workbench/contrib/dashboard/browser/widgets/properties/propertiesWidget.component.ts
We were manually calculating the height of the properties component which was being used by the properties widget to set the height correctly. This was necessary because the layout wasn't being done in such a way that the height of the containers could actually be calculated so this PR is fixing that so the containers actually take up the space that their contents do. 
This makes it a lot easier to include the component in other pieces of the UI - specifically in the dashboards I'm working on.
There were a bunch of other layout changes that needed to be made - but this should be relatively safe since this is really the only place the properties container and this specific loading spinner component is used.
=> Remove properties widget height calculations

src/sql/base/browser/ui/taskbar/overflowActionbar.ts
This PR fixes #10004. This adds a listener to mouse move like how query editor code recalculates the height based on the Window's mouse event, which Alan mentioned in this PR #10138 :)
=> Fix overflow toolbar for split views

extensions/notebook/src/common/utils.ts, extensions/notebook/src/dialog/managePackages/managePackagesDialogModel.ts, extensions/notebook/src/test/book/book.test.ts, extensions/notebook/src/test/book/bookTrustManager.test.ts, extensions/notebook/src/test/common/stubs.ts, extensions/notebook/src/test/common/utils.test.ts, extensions/notebook/src/test/managePackages/managePackagesDialogModel.test.ts
The utils tests are pretty dumb for the most part but they're mostly there for code coverage since there isn't much to test in a lot of those. 
Slightly changed some of the behavior of the managePackageDialogModel as well to be more consistent in how it behaves (when it throws vs returns undefined/empty array)
=> Add and fix notebook extension unit tests

src/vs/editor/contrib/toggleTabFocusMode/toggleTabFocusMode.ts
The use of ctrl + alt default keybindings is discouraged on Windows since it conflicts with ISO keyboards that use that for accent characters. 
There aren't a lot of open options anymore - ctrl + m (the original mapping from VS Code) is currently mapped to "Run query with actual execution plan" which seems more generally useful so I chose to update this one instead.
=> Change use of ctrl + alt default keybinding

extensions/mssql/config.json, src/sql/azdata.proposed.d.ts, src/sql/workbench/contrib/tasks/browser/tasksRenderer.ts, src/sql/workbench/services/tasks/common/tasksNode.ts, src/sql/workbench/services/tasks/common/tasksService.ts
Add support for target location for tasks being added in https://github.com/microsoft/sqltoolsservice/pull/936. Showing file location for extract and export operations because it's more useful than showing the server and database name. Intermediate fix for microsoft/azuredatastudio#9057
=> Add support for target location in tasks

src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts, src/sql/workbench/contrib/notebook/test/browser/MarkdownTextTransformer.test.ts
Adding more markdown toolbar tests + fixing the code behavior to be easier to use and not require users to change the default selection.
Before, we weren't handling the Code button very well, and it really needs to be its own type, so I added WRAPPED_ABOVE_AND_BELOW for a transform that adds some arbitrary text in the line above + line below of the selected text.
Now, when nothing is selected + users click the Code button on the toolbar, the cursor will automatically be placed in the "middle" line:
[three ticks]
[CURSOR]
[three ticks]
Undo also works properly now, whether there is existing code or not. Can click the code button as many times as you want, and the ticks will be added/undone as expected.
=> Improve Notebook Markdown Toolbar Code Selection/Undo, Add More Tests

src/sql/workbench/browser/modelComponents/divContainer.component.ts, src/sql/workbench/browser/modelComponents/flexContainer.component.ts
This lets us set general styles on an entire container (such as margins) without needing to apply the styles to each sub-item or wrap them in a further sub-container and apply the style to the child sub-container.
=> Add CSSStyles to containers

src/sql/base/browser/ui/loadingSpinner/media/loadingComponent.css
setting the display to inline-block will make it take the space circled in red below.
removing it fixes the problem, I tested and didn't notice any issues.
=> fix the issue that loading spinner is always taking space

extensions/notebook/src/common/constants.ts
Fixes #9836 to point to latest version of Python with latest dependencies for notebooks.
=> Notebooks: Update Python Mac Download URL

extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerTreeDataProvider.ts, extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcTreeDataProvider.ts
Received new guidance on naming conventions for Azure Arc resources, so updating the folder names in the Azure view:
(Also updated the type of dash that we were using for PostgreSQL Hyperscale to match what we use for SQLMIAA)
=> Updating Azure Arc Names in Azure View

src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts, src/sql/workbench/contrib/dashboard/browser/core/dashboardTab.contribution.ts, src/sql/workbench/services/dashboard/browser/common/interfaces.ts, src/vs/platform/extensions/common/extensions.ts
Currently we filter ALL contributed tabs when preview features are enabled. This makes more sense to scope down to just filtering out extensions that are actually marked as being in preview - other extensions should still be shown.
=> Only filter preview extensions when preview feat disabled

extensions/notebook/src/book/bookTreeView.ts
Currently, whenever we open any folder that contains notebooks/books in the explorer viewlet, the books viewlet captures the focus afterwards. This is because we "reveal" any item that gets added to the viewlet, which opens the viewlet and focuses on the new item. This change only reveals a book item if the viewlet itself is visible.
=> Only reveal items in the books viewlet if the viewlet is visible.

src/sql/base/browser/ui/taskbar/overflowActionbar.ts
This PR fixes #10181. The overflow menu started disappearing after the listener on mouse move for resizing was added in #10155. It would try to add back the first action in the overflow to the toolbar, which would then trigger the focus out listener(because focus was on the first action) to hide the overflow. Previously, it would try to add an action, then if there wasn't enough space for it, move it back to the overflow. This fixes that by only trying to restore an action from the overflow to the toolbar when the width has increased.
=> Fix overflow menu disappearing

src/sql/workbench/contrib/notebook/browser/notebook.css
Fixes #10191 to bring back the notebook cell margins to previous levels until we have the cell toolbar (in which case we can get rid of the Add code/Add text buttons, and have our desired cell margins).
March release:
April Release:
This fix:
=> Notebooks: Fix Cell Margins to Match Previous Releases

extensions/notebook/src/dialog/managePackages/managePackagesDialogModel.ts, extensions/notebook/src/test/managePackages/managePackagesDialogModel.test.ts
Fixed a bug in package management dialog when the default location in set in the given options. This is only used in package management inside database. Added a test to verify the scenario.
=> Fixed an issue with setting the default location in package management

src/sql/workbench/contrib/query/browser/query.contribution.ts
**Problem**
In Azure Data Studio, queries that insert or update encrypted columns are not supported. Additionally, Selecting data while filtering on encrypted column values in the WHERE clause is not supported.
**Why?**
Azure Data Studio sends the query in the exact same text that was originally typed into the query window by the user, including the values of the data to be inserted, updated, or filtered upon in a SELECT query. As a result, the query fails with an encryption scheme mismatch error because SQL Server expects the values correlating to encrypted columns to be encrypted, not in plain text.
**Solution:**
Implement parameterization of T-SQL variables with inline declarations. Expose a checkbox to enable parameterization. The design needs to include the ability for a user to …
=> Add Always Encrypted Parameterization Option

src/sql/workbench/services/accountManagement/browser/accountDialog.ts
This PR fixes #10213
It looks like the adding to splitView depends on `this.body` of the AccountPanel to not be undefined. This field gets populated in the render() method: https://github.com/microsoft/azuredatastudio/blob/93f35ca321502702000f899928b2978a8e001e27/src/vs/base/browser/ui/splitview/paneview.ts#L229
So calling render before adding to the splitView should fix the problem.
=> Render before adding to the splitView

src/sql/base/browser/ui/taskbar/overflowActionbar.ts, src/sql/base/test/browser/ui/taskbar/overflowActionbar.test.ts
This PR fixes #10244. When the overflow menu opens, the focus should be set to the first item in the overflow. This wasn't happening correctly because the separators were being counted when calculating the index, but when focus is being set, only focusable items are considered. 
old:
fixed:
=> Fix toolbar overflow focus not always going to first element in overflow

src/sql/base/browser/ui/table/table.ts, src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts, src/sql/workbench/contrib/editData/browser/gridParentComponent.ts
this method was added by @smartguest 
in this pr: https://github.com/microsoft/azuredatastudio/commit/32a89676f1b650c886304fd7507150a3d6417e3c#diff-e2b4ff5553a9b7d236f3159d8fd2c1f9
it doesn't seem to be a specific logic (row 0 cell 1) for edit data and shouldn't be added to the table component.
=> remove table setActive

src/sql/workbench/contrib/profiler/browser/profilerEditor.ts
This PR fixes #10282 
ADS is trying to restore it because the editor was set to be dirty when we select different rows. so i am setting the dirty attribute to false everyone time we update its content. I don't fully understand how the whole editor works, this does seem to fix the problem for me, i can no longer repro the issue. please let me know if there is a more proper fix.
=> force the isDirty flag to always be false

extensions/mssql/src/constants.ts, extensions/mssql/src/contracts.ts, extensions/mssql/src/mssql.d.ts, extensions/mssql/src/mssqlApiFactory.ts, extensions/mssql/src/sqlAssessment/sqlAssessmentService.ts, extensions/mssql/src/sqlToolsServer.ts, src/sql/workbench/api/common/sqlExtHostTypes.ts
This is an API for SQL Assessment methods exposing by SqlToolService. It will be used in the SQL Assessment extension.
SQL Assessment extension provides a mechanism to evaluate the configuration
of SQL Server for best practices. It gives a list of recommended actions to improve SQL Server performance or security.
=> mssql sqlAssessmentService

src/sql/workbench/contrib/notebook/browser/notebookActions.ts, src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts, src/sql/workbench/contrib/notebook/test/electron-browser/clientSession.test.ts, src/sql/workbench/contrib/notebook/test/electron-browser/notebookModel.test.ts, src/sql/workbench/contrib/notebook/test/emptySessionClasses.ts
Besides 1 string, we had a file that should've lived in a test folder, as all references were from other test files. Just doing a little refactor here.
=> Notebooks: Refactor Empty Session Classes

extensions/machine-learning/src/test/views/utils.ts, extensions/notebook/src/test/managePackages/managePackagesDialog.test.ts, src/sql/azdata.proposed.d.ts, src/sql/base/browser/ui/panel/panel.component.ts, src/sql/base/browser/ui/panel/tabHeader.component.ts, src/sql/platform/dashboard/browser/interfaces.ts, src/sql/platform/model/browser/modelViewService.ts, src/sql/workbench/api/browser/mainThreadModelView.ts, src/sql/workbench/api/common/extHostModelView.ts, src/sql/workbench/api/common/sqlExtHost.protocol.ts, src/sql/workbench/browser/modelComponents/componentBase.ts, src/sql/workbench/browser/modelComponents/tabbedPanel.component.ts, src/sql/workbench/browser/modelComponents/viewBase.ts
Adds method to update the ItemLayout of an item after initially being added to the container.
Note that depending on implementation the container classes likely will have to be modified to watch for the changes they care about and apply them directly due to how most are currently implemented.
I also modified the updateTabs slightly to now just call setItemLayout for existing tabs and NOT to clear out the container first. This is a breaking change but since this is a new API nothing uses it currently so it shouldn't break anyone - and clearing out existing items was causing some major issues with nested components such as the loading component since they would lose state when they were removed from the container.
=> Add ModelView method SetItemLayout

src/sql/base/browser/ui/table/media/table.css, src/sql/base/browser/ui/table/plugins/buttonColumn.plugin.ts
this pr fixes the button column accessibility issue that when the cell is focused, the focus is not on the button, hence the screenreader doesn't read the role of the button. the fix is to set to focus to the button when the cell is selected, and meanwhile the tabindex is -1 that means the table's focus management won't be impacted.
=> fix button column accessibility issue

extensions/notebook/src/jupyter/jupyterServerInstallation.ts, extensions/notebook/src/jupyter/jupyterSessionManager.ts
I was wrong on my initial diagnosis here. Worked with one of the folks from the powershell team, and he mentioned that he had problems finding the dotnet root in ADS (and the dotnet kernels weren't loading properly on his machine).
Just tried this on my machine, and I can load other kernels just fine; what I previously. saw was actually due to a machine configuration problem. Clearing out DOTNET_ROOT actually helped in my (misconfigured) python case, but it's the wrong fix if a machine is actually configured correctly. When my machine was in a bad state, I couldn't load the dotnet kernels even from the Jupyter UI. Reinstalling anaconda fixed my problem.
=> Notebooks: Stop Altering DOTNET_ROOT

src/sql/workbench/contrib/notebook/test/common/jsonext.test.ts, src/sql/workbench/contrib/notebook/test/common/nbformat.test.ts, src/sql/workbench/services/notebook/common/nbformat.ts
Wanted to do just a small part in the testing realm this week.
Cleaning up some methods that weren't being used elsewhere from nbformat (and which I'm not sure we have any use for anyway), and adding a few simple tests for very simple methods in nbformat.ts and jsonext.ts.
=> Cleanup nbformat, more common tests

src/sql/workbench/contrib/notebook/browser/models/nodebookInputFactory.ts
This addresses #10027.
No file association was found for ipynb on launch, so the default file editor was shown.
Tested following scenarios:
- Notebook opened on first launch (just edited launch.json to provide file path as another parameter
- Opened existing notebook
- Created new notebook + saved it
- Changed language of file from plain text to Notebook
We definitely have cleanup to do here in the future, especially with regards to what the extension contributes file association-wise.
=> Ensure ipynb is associated with notebook editor

src/sql/base/browser/ui/panel/panel.component.ts
Because the options aren't being passed in through Angular as input it wasn't correctly detecting changes to the options - which meant it'd never update with new options when SetLayout was called.
=> Fix tabbed panel not updating correctly when layout updated

src/sql/workbench/services/connection/browser/connectionManagementService.ts
Addresses https://github.com/microsoft/azuredatastudio/issues/9174
I'm not sure if this is a good solution. Do we a part of the code that will be hit when the connection was closed and we're attempting to re-establish the connection? I'd prefer to clear out the token then.
=> Stops caching the AAD token

extensions/big-data-cluster/src/bigDataCluster/constants.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardResourceStatusPage.ts, src/sql/base/browser/ui/table/media/slickColorTheme.css, src/sql/workbench/browser/modelComponents/hyperlink.component.ts
1. Clean up a few redundent get* methods
1. Use opener service instead of letting the browser handle opening
1. Fix slickgrid styles to not apply to all links in the document
1. Add theming support for hyperlink colors
Fixes https://github.com/microsoft/azuredatastudio/issues/7400
=> Hyperlink Component improvements

extensions/notebook/src/book/bookTreeView.ts
This PR fixes #10320 
Opening notebooks from books viewlet started opening them as json after last weeks vscode merge (dbb40d820ca2b490ce5111029bc5801d22602995).
Fix: Instead of opening them as text documents, using azdata.nb.showNotebookDocument.
=> fix for notebooks opening as json

src/sql/workbench/contrib/query/browser/media/queryEditor.css
Fixed the formatting of the buttons in the query toolbar and added more spacing
left side: old
right side: new
This PR fixes #9965
=> Fixed query editor toolbar icons

extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboard.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts, src/sql/azdata.proposed.d.ts, src/sql/platform/dashboard/browser/interfaces.ts, src/sql/platform/model/browser/modelViewService.ts, src/sql/workbench/api/browser/mainThreadModelView.ts, src/sql/workbench/api/common/extHostModelView.ts, src/sql/workbench/api/common/extHostModelViewDialog.ts, src/sql/workbench/api/common/sqlExtHost.protocol.ts, src/sql/workbench/api/common/sqlExtHostTypes.ts, src/sql/workbench/browser/modelComponents/componentBase.ts, src/sql/workbench/browser/modelComponents/tabbedPanel.component.ts, src/sql/workbench/browser/modelComponents/viewBase.ts
Adds generic API call for components `doAction`. This allows the extension side to hook up actions that can be triggered without needing to have a specialized ext host <-> main call for every action. 
An example of this is selecting a tab programmatically - which is done through the action `selectTab` that is being added here.
=> Add doAction API call for ModelView

extensions/notebook/src/dialog/configurePython/configurePathPage.ts
The buttons were showing checked==true, even when selecting other radio buttons in the same group.
=> Uncheck unselected radio buttons in Configure Python wizard.

src/sql/workbench/browser/scriptingUtils.ts, src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts
Exposing the command in the UI, as it's already supported by STS/SMO.
=> Enabling Script as Create for SqlOnDemand

src/sql/workbench/contrib/dashboard/browser/contents/dashboardWidgetWrapper.component.ts
This PR fixes #10384 
This PR fixes #10386 
this seems to be caused by recent vscode merge, but i didn't find out how it broke this scenario, it turns out notebook is also using this action, and it is working properly because it has the context set.
https://github.com/microsoft/azuredatastudio/blob/master/src/sql/workbench/contrib/notebook/browser/cellToggleMoreActions.ts#L59
so i am just doing the same here.
=> set context

extensions/mssql/package.json, src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerWidget.component.ts
fix for #10397 
root cause: SQL on demand servers do not have the views that we need to get the database size and the request will fail
fix: ideally the fix should be made in SQL tools service, i just checked that the STS version in master branch is already higher than the one in release 1.18 branch, to reduce the risk, i am implementing the changes in ADS as a workaround for now and will make proper fix in STS and remove this workaround.
connection service's listdatabases() and the method we use to get databases in this widget are both calling the same request with different parameters, so for now i am using the listdatabases which will only return the database names for sql on demand edition.
=> use listdatabases for sqlondemand

extensions/sql-database-projects/src/common/constants.ts, extensions/sql-database-projects/src/dialogs/deployDatabaseDialog.ts
Update deploy dialog to show "No data sources in this project" instead of an empty dropdown when there aren't any data sources in the project
=> Don't show empty dropdown when no data sources

src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerWidget.component.ts
fix for #10409 
i missed the creating new connection profile for each database entry while doing the refactoring.
https://github.com/microsoft/azuredatastudio/blob/release/1.17/src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerWidget.component.ts#L139
interestingly, all other actions works fine except the manage action, i guess I tested the manage for master database and backup restore for other databases...
=> create a new connection

extensions/resource-deployment/src/ui/modelViewUtils.ts
This PR fixes #10419 & #10422. 
Issues #10419 and #10422  both document scenarios when a user has not yet selected an account or when on resources are accessible for a given selection of account and/or subscription. The fix here is to ensure we always have at least an empty string populated in the drop-down boxes so that the clicking on those drop-down boxes does not throw. It also ensures that we do not end-up looking for subscription(s) of an azure account that is an empty string.
=> fix azure account corner case handling

src/vs/workbench/contrib/extensions/browser/extensionRecommendationsService.ts
This is related to https://github.com/microsoft/azuredatastudio/issues/10425.  It looks like the scenario recommender isn't being initialized which causes charts to fail since it wants to recommend SandDance.
=> Properly initialize scenario recommendations

src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts, src/sql/workbench/contrib/notebook/browser/notebook.component.ts
This PR fixes #10416.
Issue: we were waiting until a session was started  before calling the resolving the modelReady promise. This promise was awaited in a few places to get a reference to the notebook model, one of which was to hook up model contentChange (and kernelChange) events in notebookInput.
This was originally done because there is always a kernelChange event fired when a notebook is opened, so we didn't want to set the document to dirty incorrectly.
Tracking the first kernel change is straightforward, however, which is part of my change here.
Now, users should be able to open a notebook, immediately edit the notebook, and save it, before the session is loaded for the kernel.
=> Ensure Notebook Model Dirty State Can Be Triggered Before Session Start

extensions/azurecore/src/azureResource/services/subscriptionFilterService.ts
For #10438
Not exactly sure why this has just recently started appearing - my best initial guess though is that the Tree used to display the Azure accounts was updated in a recent VS Code merge to cause these to be surfaced. This code has always been broken as far as I can tell from its original implementation (we never were setting the config) and the error itself is also nothing new.
We might want to relook at how we're storing this since currently it's tied to the workspace - but this fix at least gets rid of the error and isn't going to change any existing behavior.
=> Remove config update from subscription filter

extensions/schema-compare/src/controllers/mainController.ts, extensions/schema-compare/src/schemaCompareMainWindow.ts, extensions/schema-compare/src/test/schemaCompare.test.ts, extensions/sql-database-projects/src/common/constants.ts, extensions/sql-database-projects/src/common/utils.ts, extensions/sql-database-projects/src/controllers/mainController.ts, extensions/sql-database-projects/src/controllers/projectController.ts
This adds basic support for schema compare for sql database projects by building the dacpac of the project and setting that as the source when the schema compare is opened
Error if schema compare extension isn't installed:
=> Add sql proj schema compare for dacpac

src/sql/workbench/browser/modelComponents/text.component.ts
Fixes #10448
Port fix for hyperlinks not being easily visible in dark mode.
Regression from April release.
=> Fix link styling for text components (#10449)

src/sql/workbench/contrib/dashboard/browser/widgets/explorer/media/explorerWidget.css
=> fix explorer widget dark theme

src/sql/workbench/browser/modelComponents/text.component.ts
The main point of this was to make it so the links used the opener service instead of opening directly. With this we can also remove the styling hooks since the link takes care of styling itself.
Doing it this way also is just a cleaner way of handling this and also fixes a possible issue where if the text was updated after initial creation it would never get updated in the UI since we we're detecting changes to the value/links properties.
=> Fix text component link to use link component directly

src/vs/platform/list/browser/listService.ts
This is to resolve Extension Manager single-click bug https://github.com/microsoft/azuredatastudio/issues/10447.  It looks like this line didn't get updated correctly in previous merge.
Note: these changes are to make this portion of the file match the vscode release/1.45 branch.
=> Fix extension manager single-click

extensions/sql/syntaxes/sql.tmLanguage.json
Fixes https://github.com/microsoft/azuredatastudio/issues/10208
This has been fixed upstream in the VSCode MSSQL repo and so will make its way to VS Code and then ADS through merges. This PR is a targeted fix for 1.18 only to revert back to the old language file so this is fixed in the stable build ASAP while we wait for those merges to happen.
=> Port Request : Fix sql language colorization

extensions/sql-database-projects/resources/templates/newSqlProjectTemplate.xml, extensions/sql-database-projects/src/test/baselines/newSqlProjectBaseline.xml
Sql proj build previously wasn't working on mac because some reference assemblies couldn't be found. This PR fixes #10464.
=> Fix sql project build on mac

src/sql/workbench/contrib/commandLine/electron-browser/commandLine.ts, src/sql/workbench/contrib/commandLine/test/electron-browser/commandLine.test.ts
The responsibility to send valid URI should be on the caller. We shouldn't be doing weird parsing to try to make sense of it.
We should also avoid using 'boolean' for types of stuff that come externally. There is no guarantee they're a boolean in runtime. (e.g. in this case)
=> Don't do any extra parsing, put the responsibility on the caller

extensions/notebook/src/book/bookTreeView.ts
currentBook might be undefined and these functions were being invoked even if a book wasn't opened - which would cause errors to show up in the logs. I noticed this writing some tests - separating it out for easier reviewing.
There didn't seem to be any functional issues here - this is just clean up to avoid extra errors in the logs.
=> Fix some issues with book tree view

src/sql/workbench/contrib/query/browser/messagePanel.ts
This fixes https://github.com/microsoft/azuredatastudio/issues/10378
Issue: horizontal scrolling and dynamic heights aren't supported simultaneously (https://github.com/microsoft/azuredatastudio/blob/master/src/vs/base/browser/ui/list/listView.ts#L247), and we had dynamic heights to true by default in the message panel. So it would break if a user enabled horizontal scolling.
Fix: Look for user settings for horizontal scrolling and set dynamic height to its opposite.
=> Fix horizontal scroll bug

extensions/big-data-cluster/src/bdc.d.ts, extensions/big-data-cluster/src/bigDataCluster/constants.ts, extensions/big-data-cluster/src/bigDataCluster/controller/apiGenerated.ts, extensions/big-data-cluster/src/bigDataCluster/controller/clusterControllerApi.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/addControllerDialog.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardModel.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/hdfsDialogBase.ts, extensions/big-data-cluster/src/bigDataCluster/tree/controllerTreeDataProvider.ts, extensions/big-data-cluster/src/bigDataCluster/tree/controllerTreeNode.ts, extensions/big-data-cluster/src/extension.ts, extensions/mssql/src/hdfs/webhdfs.ts, extensions/mssql/src/objectExplorerNodeProvider/connection.ts, extensions/mssql/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts, extensions/mssql/src/sqlClusterLookUp.ts, extensions/mssql/src/typings/refs.d.ts, extensions/notebook/src/common/utils.ts, extensions/notebook/src/jupyter/jupyterSessionManager.ts, extensions/notebook/src/typings/refs.d.ts
In CU5 a fix is being made so that the Knox gateway username is no longer going to always be root - instead it'll be whatever the initial username that was specified during deployment.
There's no direct way to query this username so instead we use the SQL login since that by default is going to be the same. This can be modified though (or a new login is made on the SQL instance after deployment) and so in that case we have to just do our best and prompt the user to enter in the username manually. For this first fix this means that user will be reprompted each time they reconnect to the server.
As part of this work I started the implementation of the BDC extension API so other extensions can use that to query BDC resources much more easily.
=> Fix HDFS support for CU5+ BDC instances

extensions/resource-deployment/package.json
bump up the required azdata version for bdc deployment, also, just realized that we only specified the required for one scenario (new aks), so i am also updating the other scenarios.
=> update required azdata version

src/sql/base/browser/ui/panel/panel.component.ts, src/sql/workbench/contrib/dashboard/browser/containers/dashboardNavSection.component.ts
looks like the issue is caused by: https://github.com/microsoft/azuredatastudio/commit/9bcd7cdd80db62f187061b1f61a7eae10d1555a7
with this change, setting the options will cause detecting changes, the fix is to make sure the variables are not undefined.
This PR fixes #10593
=> fix the nav section dashboard container

extensions/dacpac/src/wizard/api/basePage.ts, extensions/dacpac/src/wizard/api/dacFxConfigPage.ts, extensions/dacpac/src/wizard/dataTierApplicationWizard.ts
This PR fixes #7097. There are a few fixes for the dacpac extension in this PR:
- show connection name if there is one instead of server name
- don't open connection dialog if there are active connections, even if there is no "current connection"
- database dropdown was not changing selected database correctly because the database dropdown values got changed to string from CategoryValue in #8909
=> dacpac extension fixes

build/azure-pipelines/docker/sql-product-build-docker.yml
This was generating a warning in our builds :
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=65787&view=logs&j=1c8ce01e-97de-5be9-a863-648419f09741&t=b41ce4de-7bca-5dd5-8638-dc7f5a7157ca&l=11
`##[warning]Please use Download Build Artifact task for downloading Build Artifact type artifact. https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops`
=> Switch to DownloadBuildArtifacts task

.github/workflows/ci.yml, scripts/test-extensions-unit.bat
These tests have been timing out randomly in various pipelines and thus failing the builds. e.g. https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=65857&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=f43345f0-e90d-5fa7-e3aa-7e223f6f3b99
It isn't clear to me exactly what's failing here so just disabling them all until investigation can be done.
=> Disable sql-database-projects tests

extensions/mssql/config.json
Update sqltoolsservice to get DacFx fix for importing/deploying users with external logins to on prem. This PR fixes #9522, fixes #9217
=> bump SqlToolsService to 2.0.0-release.68

extensions/azurecore/package.json, extensions/azurecore/resources/dark/console.svg, extensions/azurecore/resources/light/console.svg
This PR fixes https://github.com/microsoft/azuredatastudio/issues/10504
Removed the `console.svg` file that was the same for both light and dark and use inbuilt codicons instead which are theme aware.
=> use inbuilt codicon instead of image

src/sql/workbench/contrib/profiler/browser/profiler.contribution.ts
This PR fixes #10393 
sqlserver.username field is being captured by our default azure session templates but the field is not added to the view mapping, with this change the username will be displayed:
=> show username for azure sql db

src/sql/workbench/contrib/notebook/browser/notebook.css
This PR fixes a bug in ADS Notebook UI where the word "Cell" appears misaligned with the remainder of the notebook toolbar text.
=> Adjusted + Cell element height to fix layout on Mac and Windows.

src/sql/workbench/browser/scriptingUtils.ts, src/sql/workbench/contrib/query/browser/queryInputFactory.ts, src/sql/workbench/services/queryEditor/browser/queryEditorService.ts, src/sql/workbench/services/queryEditor/common/queryEditorService.ts
Kusto queries to run in unsaved query editor when user clicks "Select Top 1000" by right clicking on Kusto table
=> Temporary fix to make Kusto queries work in unsaved query editor

extensions/integration-tests/src/test/notebook.test.ts
These test cases pass when run manually, but fail during the test runs due to timing issues. Looks like the client session doesn't start fast enough when trying to execute the cells.
=> Disable some unreliable notebook integration tests.

extensions/notebook/src/dialog/configurePython/configurePythonWizard.ts
This reduces the width of the wizard by half, so it removes a lot of empty space.
=> Add custom width to Python wizard to reduce wasted space.

extensions/arc/src/ui/components/keyValueContainer.ts, src/sql/azdata.proposed.d.ts, src/sql/workbench/browser/modelComponents/inputbox.component.ts
Adds a readOnly property to InputBoxComponent.  Used for inputs that the user should select/copy but not edit.
=> Add readOnly property to InputBoxComponent

extensions/sql-database-projects/src/controllers/projectController.ts, extensions/sql-database-projects/src/dialogs/deployDatabaseDialog.ts
This PR fixes #10668. This fixes clicking "generate script" in the deploy dialog calling deploy and also closes the dialog before build starts instead of after. Another issue I found was that the generated script wasn't being opened, so this PR fixes that too by setting the TaskExecutionMode to script instead of execute.
=> Fix sql project generate script

src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts
This PR addresses #10713. The edit cell action should only appear for text cells.
Text cell toolbar:
Code cell toolbar:
=> Only show edit cell action for markdown cells

src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts, src/sql/workbench/contrib/notebook/browser/notebook.component.ts
This is in reference to https://github.com/microsoft/azuredatastudio/issues/10711, in order to create consistency naming-wise for text cells.
PM has decided to go with "Text Cell" everywhere, until we figure the larger story in ADS (and with partners), since we've used that terminology up to now.
=> Change markdown cell to text cell

src/sql/workbench/services/connection/browser/connectionManagementService.ts
Attempts to fix the postgresql issue with authentication.
=> Fixes the azure auth for postgresql

src/sql/workbench/contrib/query/browser/flexibleSash.ts
Since the dimension is not set initially for flexibleSash, there must be a null check done to return a result for getHorizontalSashWidth when the Sash for it is being created.
This PR fixes #10730
=> Fix for edit data grid not showing

package.json
this is a different way of mitigating the problem without introducing the custom agent machines, the compile step will take ~3 minutes more than before. seems an acceptable solution at this point.
the build failed at a later steps, but doesn't seem to be caused by this change, I am rerunning it now. 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=66749&view=logs&j=c7493abb-a1f4-533f-2d24-71780a69f247&t=8d02ba2f-f021-560e-034c-effb4dd4b969
=> reduce max memory

src/sql/workbench/contrib/notebook/browser/find/notebookFindWidget.ts, src/sql/workbench/contrib/profiler/browser/profilerFindWidget.ts
This PR fixes #10729 
recent vscode merge changes the way sash works, we've being using the vertical layout but we only implemented the horizontal layout, now it is requiring the method related to vertical layout, implementing that fixes the problem.
during this i also noticed a couple more issues:
1. the previous, next, close buttons are not visible, it has been like this for a while since the codicon change was introduced. updating the class name fixes the issue
1. the icons are not aligned vertically and turns out find widget for notebook also have similar issue (maybe @MaddyDev copied the code 😃 ), i looked at the vscode find widget, and realized they are using a div container for the actions, the css class 'find-actions' is responsible for centering the items.
**before** - the …
=> fix profiler not launch issue

src/vs/workbench/contrib/extensions/browser/extensionsActions.ts
Fix from VS Code : https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/extensions/browser/extensionsActions.ts#L2976
Fixes https://github.com/microsoft/azuredatastudio/issues/10667
=> Fix error when cancelling out of VSIX dialog

package.json
This reverts commit d62bb1e9fced81565e56c8ac67c7f42902a3c8a6.
as per ADO team, there was an outage last Thursday and Friday. now the issue has been resolved, I queued a test build last night against release/1.18 branch and it passed:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=66911&view=results
seems like we can revert the change I made earlier now. Lets see how the PR validation build goes.
=> Revert "reduce max memory (#10775)"

extensions/sql-database-projects/src/test/baselines/baselines.ts
I ended up not adding a dacpac references baseline file in this PR #10684 to add dacpac references functionality, but forgot to remove this so some tests were failing because this file couldn't be found. I'll add the test for this back after I fix the test to work for both windows and mac.
=> Remove dacpac references baseline

extensions/notebook/src/book/bookModel.ts, extensions/notebook/src/book/bookTreeView.ts, extensions/notebook/src/extension.ts
PR to address the following in June milestone #10780 
Ported just the highlight fix part from #10523 : Previously we're trying to find the notebook to highlight in the current book which can be different when using the navigation links. (Current book is the book that's opened last on the viewlet.) Fix is to get the correct book first and then highlight the notebook in it.
=> highlight correct notebook on navigation.

src/sql/workbench/browser/modelComponents/componentBase.ts
This PR fixes #10811 
previously the checkbox is not set as required, when switching cards, the agreement checkbox container's status is not reset after clear items.
=> reset valid status after clear container

extensions/integration-tests/src/test/notebook.test.ts, src/sql/workbench/contrib/notebook/test/stubs.ts, src/sql/workbench/services/notebook/browser/models/cell.ts, src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts, src/sql/workbench/services/notebook/browser/models/notebookModel.ts
@chlafreniere recently made a change where the notebook model is marked as ready sooner (https://github.com/microsoft/azuredatastudio/commit/452bd6a0cb3336cb5b4e05cd5d6f13a3ba47719c), but the client session can still be loading when that happens. I've added a promise that resolves after the session is initialized, so that we can await that before running a cell. Note that this promise does not throw on error, it just shows whether the model's session has been initialized in some way.
Fun fact: We're awaiting the _sessionLoadFinished promise in the notebook tests, but this field was not being initialized before this change. So we were actually just awaiting on undefined.
=> Wait for clientSession to become available before running a cell.

extensions/admin-tool-ext-win/coverConfig.json, extensions/admin-tool-ext-win/src/main.ts, extensions/admin-tool-ext-win/src/test/extension.test.ts, extensions/admin-tool-ext-win/src/test/utils.test.ts, extensions/admin-tool-ext-win/src/utils.ts
Excluding the main extension file from coverage - there isn't really much value in getting coverage for all the extension setup stuff that happens. I moved the stuff that was already being tested into utils so it still gets counted for coverage though. 
At some point in the future I may come back here and add some tests for the launch* functions but currently there's a couple reasons I don't see that being valuable to do here : 
1. Without having actual live connections the actual benefit of testing these is low since we wouldn't be able to actually test any functionality
2. This is windows only and currently the unit tests only run on linux
=> Clean up coverage for admin-tool-ext-win extension

src/sql/workbench/contrib/notebook/browser/notebook.css
This PR addresses 10801
Modified style rules to make sure no image is being added to the background. This prevents to double icon appearance.
=> Fixed notebook toolbar icon issue in Dark and High Contrast themes.

extensions/admin-tool-ext-win/package.json, extensions/admin-tool-ext-win/yarn.lock, extensions/schema-compare/package.json, extensions/schema-compare/yarn.lock
No functional changes - just pulling officially published version instead of directly from Github.
=> Update ext telemetry package to npm version

extensions/sql-database-projects/src/test/projectController.test.ts
The mock connection profile wasn't getting passed correctly to importNewDatabaseProject(), so tests started failing after the changes in #10820 to handle when there isn't a connection profile got checked in.
=> Fix failing sql project tests

ThirdPartyNotices.txt, extensions/sql-database-projects/package.json, extensions/sql-database-projects/src/models/project.ts, extensions/sql-database-projects/src/test/baselines/SSDTProjectAfterUpdateBaseline.xml, extensions/sql-database-projects/yarn.lock
=> Format sqlproj file XML on serialization

src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
This PR fixes #10637 
the events (validity changed event for this specific issue) of the components added to the declarative table are not being wired properly, this is done by adding them to the container.
**before**
**after** the next button is disabled now
=> fix declarative table issue

extensions/notebook/src/book/bookTreeView.ts, extensions/notebook/src/extension.ts
#10780.
Two issues:
- We were registering the tree data provider twice (one explicitly, via calling `vscode.window.registerTreeDataProvider()`, and once when calling `this._bookViewer = this._apiWrapper.createTreeView(this.viewId, { showCollapseAll: true, treeDataProvider: this });`
- The currentBook selection logic was incorrect, and was trying to find notebooks/markdown files as relative paths to the books locations. If there were nested books, this caused issues finding the right book in the viewlet (depending on the order in which they exist when we discover the books + notebooks in a folder). I've reverted this logic to match what we shipped in May.
=> Fix Notebook Viewlet Highlighting

src/sql/workbench/api/common/extHostModelView.ts
This PR fixes #10655 
So basically the loading component wasn't getting the child property of required and wasn't showing the required star in its title.
Need some feedback regarding this. Should I create a new interface that extends component and has a  'required' field?
=> Adding required 'star' to loading component in forms

src/sql/base/browser/ui/table/media/table.css, src/sql/base/browser/ui/table/plugins/buttonColumn.plugin.ts, src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerTable.ts
This PR fixes #10840 
not sure why did i set the row height to 35 in the first place, it is not necessary and we can simply let slickgrid to handle the height
also, removed the width support for the button column, our css styles doesn't really support that well.
=> use default row height and update button column

extensions/azurecore/package.json, extensions/azurecore/package.nls.json, extensions/azurecore/src/azureResource/commands.ts, extensions/azurecore/src/azureResource/constants.ts, extensions/azurecore/src/azureResource/utils.ts, extensions/azurecore/src/azurecore.d.ts, extensions/azurecore/src/extension.ts, extensions/machine-learning/src/common/apiWrapper.ts, extensions/machine-learning/src/modelManagement/azureModelRegistryService.ts, extensions/machine-learning/src/test/modelManagement/azureModelRegistryService.test.ts, extensions/machine-learning/src/test/stubs.ts, extensions/resource-deployment/src/services/apiService.ts, extensions/resource-deployment/src/ui/modelViewUtils.ts, src/sql/azdata.d.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/9651
Now we only display an error if we didn't get any resource groups/subscriptions from these calls.
I also took this opportunity to move the functions from commands to being actual API calls.
The azdata change is non-breaking, this was something that was already true and so this is just making it so the actual API has the expected return type.
=> Fix deployment warnings to only show if no resources found

extensions/notebook/src/jupyter/jupyterSessionManager.ts
Fixes #10690.
We've been running the `setEnvironmentVars()` method in JupyterSessionManager for every Jupyter kernel. This is great for the Python (and spark) kernels, but neglects the fact that we ship another kernel (PowerShell) that doesn't actually implement the change directory (`%cd`) or set environment variable (`%set_env`) magics. Therefore, we take a perf hit, and end up sending a bunch of messages to a kernel that we know doesn't support the functionality.
I tried ~20 notebooks, and didn't get into a state where, upon switching to the PowerShell kernel, the results weren't being displayed as expected. Not going to declare victory there yet, but this is a good first step.
=> Stop Running %cd and %set_env for PowerShell Kernel

src/vs/platform/files/test/electron-browser/diskFileService.test.ts
These tests fail occasionally. Seems like this was a known issue and they tried to "fix" it by adding a retry but apparently that isn't fully solving the problem : https://github.com/microsoft/vscode/issues/78602
Just disabling them for us since our need for running the core vs tests is low.
=> Disable VS tests that fail randomly

src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
Updates the DeclarativeTableComponent to support the width property.
I'm not sure this is the correct approach.  I had a DeclarativeTableComponent that I wanted to take up 100% width of the parent, and it did not respect the width property until I made this change.
=> Support width for DeclarativeTableComponent

.github/workflows/ci.yml, .github/workflows/on-issue-open.yml
This should fix the issue we've been seeing with the coverage upload failing. See https://github.com/coverallsapp/github-action/issues/55 for some more information - but in short v1 of the action was just pulling the latest all the time. v2.2.0 was changed to pull the commit specified by GITHUB_SHA which is what coveralls uses for the upload and so should ensure that the specified commit always exists. 
I updated all the action versions for consistency - we really only need to update the ci ones but it's best to keep things consistent when we can.
=> Update to checkout action v2.2.0

extensions/arc/src/localizedConstants.ts, extensions/arc/src/models/miaaModel.ts, extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts, extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts, src/sql/azdata.d.ts
1. Adds support for fetching actual database info for MIAA instances
1. Updates `Compute + Storage` property - currently we only get the compute (vCores) so just displaying that for now
1. Hooks up `Open in Azure Portal` button
1. Update a few strings
=> MIAA Dashboard Updates

extensions/sql-database-projects/package.json
This PR fixes #10972. Add database reference should only be launched from the Database Reference node in a project, not from command palette.
=> Remove add database reference from command palette

extensions/sql-database-projects/src/common/constants.ts, extensions/sql-database-projects/src/common/utils.ts, extensions/sql-database-projects/src/controllers/projectController.ts, extensions/sql-database-projects/src/dialogs/deployDatabaseDialog.ts, extensions/sql-database-projects/src/models/IDeploymentProfile.ts, extensions/sql-database-projects/src/models/project.ts, extensions/sql-database-projects/src/test/baselines/baselines.ts, extensions/sql-database-projects/src/test/baselines/publishProfileBaseline.publish.xml, extensions/sql-database-projects/src/test/projectController.test.ts, extensions/sql-database-projects/src/test/testUtils.ts
This PR fixes #10924. This adds support for reading database name and SQLCMD variables from a publish profile. Support for other profile options will be added in later PRs. 
Empty state (no profile loaded and no sqlcmdvars in the sqlproj):
This also fixes #10947 so that the values of SQLCMD variables show and change if the profile has different values for them (support for editing them in the UI will come later).
=> Load profile support for sql project deploy

extensions/sql-database-projects/src/dialogs/deployDatabaseDialog.ts
Disabling the target connection input box for now because it the value there wasn't actually being used for the connection (the connection is getting saved when it's selected in the connection dialog, not read from the input box). SSDT also has this field disabled. Partially addresses #10984
before selecting a connection:
after selecting a connection:
=> Disable target connection input box in publish dialog

extensionsGallery-insider.json
This new version just contains logic that will install the Arc extension and uninstall the old arcdeployment extension.
=> Update Arc Deployment to deprecated version

extensions/sql-database-projects/src/controllers/projectController.ts, extensions/sql-database-projects/src/test/projectController.test.ts
Fixes #10974 by creating a new folder (with the same name as the project) inside the directory the user picked during the new project workflow.
=> Creates new projects inside a same-named folder

extensions/sql-database-projects/src/common/utils.ts, extensions/sql-database-projects/src/controllers/projectController.ts, extensions/sql-database-projects/src/models/project.ts, extensions/sql-database-projects/src/test/projectController.test.ts, extensions/sql-database-projects/src/test/projectTree.test.ts
This PR 
Fixes https://github.com/microsoft/azuredatastudio/issues/10986
Converting the relative path to platform safe path before using in uri. 
Opened a separate bug for MAC --> SSDT.
Fixes https://github.com/microsoft/azuredatastudio/issues/11028 
Adding one more change to allow retry on projects that did not load
=> fix for windows path to show in project tree across platforms correctly

extensions/sql-database-projects/src/controllers/projectController.ts, extensions/sql-database-projects/src/test/projectController.test.ts, extensions/sql-database-projects/src/test/testContext.ts
Work-around for #10589, not calling it "fixed" since we still haven't identified the source of the lock.
=> Copy dacpac to temp folder before publishing to avoid dacpac lock

src/vs/platform/extensionManagement/common/extensionGalleryService.ts
The check was being done using the VS Code engine but against the ADS version so normally would fail (since VS Code engine is much higher). 
Logic here is that we require at least one engine version specified but it can be of either type (so we can support native VS Code extensions that may not have an azdata engine specified).
=> Fix extension gallery query to use correct version

extensions/arc/src/common/utils.ts, extensions/arc/src/test/common/promise.test.ts, extensions/arc/src/test/common/utils.test.ts, extensions/arc/src/test/stubs.ts, scripts/test-extensions-unit.bat
Most of them are pretty standard but the prompt tests are a bit more interesting.
I was getting tired of having to plumb the ApiWrapper through every single thing in an extension and so for this I'm experimenting just overwriting the vscode API directly here for createInputBox.
I chatted with Amir a bit about this and we both agree that while this seems like a good idea it
1. Belongs in a more common place (likely `vscodetestcover` extension)
1. Should be something we can revert back easily after a test is done so it doesn't affect other tests
I'm getting this PR out here as it is as a proof of concept to make sure that the idea itself is usable and to see whether anyone else has any better ideas. Then if we like this I'll start working on a more common solution to this to get in at a …
=> Add more arc tests

extensionsGallery-insider.json, extensionsGallery.json
This change will add the [Settings Sync extension](https://github.com/shanalikhan/code-settings-sync/), popular with VS Code, to Azure Data Studio. The changes in the extension have already taken place so it should work; it just needs to be added to the "gallery" JSON.
Ref: https://github.com/shanalikhan/code-settings-sync/issues/926
=> Add settings sync extension to "gallery"

src/sql/workbench/contrib/notebook/browser/cellToolbarActions.ts
As part of our ongoing efforts to align better to Jupyter commands, one element that we need to change is our "Before/After" strings to match Jupyter -- "Above/Below".
In Jupyter, when a cell isn't in edit mode, pressing 'A' will insert a cell above, and 'B' will insert a cell below. Our current strings would make this quite confusing, so that's the motivation behind this change 😄
=> Change Notebook before/after strings to above/below

extensions/arc/src/models/controllerModel.ts, extensions/arc/src/models/miaaModel.ts, extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts, extensions/arc/src/ui/dashboards/miaa/miaaConnectionStringsPage.ts, extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts, extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts
Fixes this bug where the sqlmiaa pages do not load until you click refresh.  Reproduces every time in my environment.
Cause: The models finish refreshing before the UI pages subscribe to model changes.
The code looks something like this:
```
dashboard = azdata.window.createModelViewDashboard(...)
dashboard.registerTabs(() => // create UI pages);
await dashboard.open();
// Kick these off without waiting for them to finish
controllerModel.refresh()
miaaModel.refresh()
```
The models finish refreshing before the registerTabs callback is executed.  When the models fire their updated events, the UI pages have not yet been created and therefore miss the events.
The pages were designed to initialize the UI with empty data, and rely on the model update events to initialize the data.
There are 2 …
=> Arc - Fix sqlmiaa initial load

extensionsGallery-insider.json
Ready to publish to gallery now, replacing old Arc Deployment extension with new Arc extension (deprecating the old deployment extension)
=> Add Arc extension and deprecate old Arc Deployment extension

src/sql/workbench/contrib/assessment/browser/asmtResultsView.component.ts
Fixing spelling error in sql-assessment extension's table column name
=> spell error in Severity column name

extensions/arc/src/localizedConstants.ts
On data controller dashboard, if a resource has 1 vCore, we currently list that as "1 vCores". Fixing this logic to account for the singular case as well:
=> Update singular vcore string on data controller dashboard

src/sql/platform/dashboard/browser/interfaces.ts, src/sql/workbench/browser/modelComponents/componentBase.ts, src/sql/workbench/browser/modelComponents/modelStore.ts
This has been a long-standing issue, when doing the validity checks for container components if their child hasn't finished initializing yet an exception is thrown since the component isn't added to the ModelStore yet.
I tested out a number of dialogs and views that use validation logic and things seem to work as expected still.
=> Fix errors throw when doing validity checks

extensions/notebook/resources/notebooks/JupyterBooksCreate.ipynb
jupyter-book released new version 7.1 which is not yet supported by us. Made changes on the create book to install the older version 0.6.4 that's currently supported by us.
I tested the below two scenarios with my changes:
1. Install the latest version of jupyter-book and tried running the book, it uninstalls the 7.1 and installs 6.4.
2. Uninstalled jupyter-book and tried running the book, it installs 6.4 and continues. 
My only current concern is, if the users have the latest version installed for their personal use and us uninstalling it. Should I add a prompt to user, that asks users permission to continue to uninstall the version they have? 
Update: Added a note:
This PR fixes #11158
=> check for jupyter-book versions and install 6.4

src/sql/workbench/browser/parts/activitybar/activitybarActions.ts, src/sql/workbench/contrib/accounts/browser/accounts.contribution.ts, src/vs/workbench/browser/parts/activitybar/activitybarPart.ts
This PR fixes #11166
The lower left corner now looks like below.  The account button behaves the same as the previous status bar button, showing the accounts dialog.
=> Move account management icon to action bar

extensions/azurecore/src/account-provider/auths/azureAuth.ts, extensions/azurecore/src/account-provider/interfaces.ts, extensions/azurecore/src/account-provider/providerSettings.ts, src/sql/azdata.d.ts, src/sql/workbench/api/common/sqlExtHostTypes.ts
Adds Azure Devops as a resource for retrieving an account. This will be leveraged by an extension to authenticate against the service.
Initially this change was part of another PR, but breaking it up into more manageable pieces.
=> Add Azure DevOps as a resource for authentication

src/sql/workbench/contrib/notebook/browser/notebookEditor.ts
Issue: When user tries to edit a cell when Find is active (and have a highlight in different cell), it scrolls the focus to the find result cell.
Fix: On edit of a cell, it triggers updateActiveCell which triggers onCellModeChanged on both the previous active cell and the current cell selected for editing. If the previous active cell has an active highlight, find is trying set the highlight again irrespective of it being already highlighted, which in turn triggers the scroll to that cell. Fixed it by only setting the highlight when it's different.
This PR fixes #11120
=> set currentMatch on find changes only

src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts
Fixes #11219. The connection profile of the server/database dashboard wasn't getting passed to the extension contributed actions
=> Pass connection profile to extension contributed actions in dashboard toolbar

src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
This PR removes the show more button on the welcome page from a list element to a div for accessibility alignment.
This PR fixes #10622
=> removes more link from list element into div

extensions/resource-deployment/src/services/bigDataClusterDeploymentProfile.ts
put the storage object under the spec object.
This PR fixes #11185
=> put the storage object under the correct parent node

src/sql/workbench/browser/modelComponents/treeViewDataProvider.ts, src/vs/workbench/api/browser/mainThreadTreeViews.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/11170
In https://github.com/microsoft/vscode/commit/39a406daa381ddeb57323088f920d88f8bc8f40b the tree data provider was modified such that the children elements returned by getChildren were changed into ResolvableTreeItems and being recreated each time.
This broke the ModelView tree component since it relied on custom state being added to the tree items that controlled things such as the checkbox state. 
The fix here is to override the getChildren method and provide our own extended version of the ResolvableTreeItem that we use instead. I kept the logic the same as the base class to reduce chance of this breaking other logic that relies on ResolvableTreeItem being there. 
In the end I think that this is something we're probably …
=> Fix ModelView tree components to keep custom state

extensions/notebook/src/book/bookTreeItem.ts, extensions/notebook/src/book/bookTreeView.ts
Root Book items don't have a URI so this was throwing.
It didn't have a functional impact as far as I can tell since those items never had a parent anyways - but we still should make sure we're handling these cases correctly.
=> Fix error when calling getParent

extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
Moving the "load profile" button to the top of the dialog as discussed with Raden.
=> Move load profile button to top of publish dialog

extensions/notebook/src/book/bookTreeView.ts
Addresses #11268.
For some of our internal books, sections are no longer markdown files (and are instead notebooks). Removing the hardcoded check for notebooks fixes the issue.
=> Fix no books currently selected error in viewlet

src/sql/workbench/browser/modal/optionsDialog.ts
I refactored the dialog a while back to remove the use of the ViewPane (it had some accessibility issues) and missed cleaning this up
=> Remove unused ViewPane implementation

src/vs/workbench/contrib/update/browser/update.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/11294
PR for VS Code as well : https://github.com/microsoft/vscode/pull/102149
=> Only throw if releaseNotesUrl doesn't exist

src/sql/workbench/services/accountManagement/browser/accountDialog.ts, src/vs/workbench/common/views.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/11283
It might be worth it to investigate this further. We have other instances of dialog components using ViewPanes although it looks like those might actually be unused or broken : 
Options dialog - unused? https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/browser/modal/optionsDialog.ts#L41
Insights dialog - seems to be broken, possibly related to the view changes that we had to fix for the other views : https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/services/insights/browser/insightsDialogView.ts#L124
=> Add new ViewContainerLocation for dialogs

src/sql/workbench/services/insights/browser/insightsDialogView.ts
https://github.com/microsoft/azuredatastudio/issues/11284
vscode requires the view container and views to be registered now. also leveraged the new Dialog enum value @Charles-Gagnon added to fix the azure account dialog issue.
=> fix insight details dialog issue

src/vs/platform/environment/node/stdin.ts, src/vs/workbench/services/textfile/common/encoding.ts, src/vs/workbench/services/textfile/test/electron-browser/textFileService.io.test.ts
https://github.com/microsoft/vscode/commit/17a8e253f69b01f0fa3ba4426ed873740682c666 (vscode/release/1.47) Creating files will add 2 times BOM (UTF-8, 16) https://www.github.com/microsoft/vscode/issues/102103 (https://www.github.com/microsoft/vscode/issues/102111)
https://github.com/microsoft/vscode/commit/ff4eb85d58a834b2c83270619ce267149b96761b Reading from stdin via tmp file and pipe raise an exception https://www.github.com/microsoft/vscode/issues/102085 (https://www.github.com/microsoft/vscode/issues/102098)
=> Merge from vscode 17a8e253f69b01f0fa3ba4426ed873740682c666

src/vs/workbench/api/browser/mainThreadTreeViews.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/11297
Another thing broken by https://github.com/microsoft/vscode/commit/39a406daa381ddeb57323088f920d88f8bc8f40b
We couldn't fix it like https://github.com/microsoft/azuredatastudio/pull/11239 since the TreeDataProvider in this case is contributed by the extension and so goes through the vs code side of things. 
I don't like this as a long term fix - I want to talk to the VS Code people and see if they're willing to come up with a solution that will fit both scenarios. In the meantime though this should be safe as a temporary fix (and will also benefit in that if there are any other tree views we have that are broken because of this change they won't be anymore) since we don't register any tree views with a resolve function …
=> Revert to previous behavior for tree data providers getChildren

extensions/azurecore/package.json, extensions/azurecore/package.nls.json, extensions/azurecore/src/account-provider/auths/azureAuth.ts, extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts, extensions/azurecore/src/account-provider/azureAccountProvider.ts, extensions/azurecore/src/extension.ts, extensions/azurecore/src/utils/Logger.ts
This PR allows us to get more logs from the user when authentication fails. Unfortunately these logs will contain PII so we're going to have them disabled by default - but if the need arises the user can go turn them on and see the exact responses from Microsoft Identity/OAuth
=> Optional PII logging

src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
This PR is a fix for #11320 
Before this change, we had a line of code that did 
`this.data = this.data`, this caused the setter for the data value to go and fire an event that changed the properties object in the extHostModelView.ts file.
This fix brings the special call the data setter did to this component.
Thanks to @aasimkhan30  and @alanrenmsft for finding this issue
=> Fixes the declarative table issue

product.json
release/1.20 branch is in sync with vscode 1.47, I will update the main branch (1.48.0) after the release.
=> bump vscodeVersion

src/sql/workbench/contrib/dashboard/browser/widgets/explorer/explorerTable.ts, src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts
This PR fixes #10765
for new notebook action, we need to return the IConnectionProfile to avoid the circular structure issue
for script as create action, it is never meant to be exposed on database context.
=> fix the issue with explorer widget context menu

extensions/resource-deployment/src/localizedConstants.ts, extensions/resource-deployment/src/services/bigDataClusterDeploymentProfile.ts, extensions/resource-deployment/src/ui/deployClusterWizard/deployClusterWizardModel.ts, extensions/resource-deployment/src/ui/deployClusterWizard/pages/clusterSettingsPage.ts, extensions/resource-deployment/src/ui/deployClusterWizard/pages/summaryPage.ts
This PR fixes #10883 
previously we are defaulting the Realm field to the domain name, recently, Akshay from the BDC team reached out to me to saying this field should be exposed now to allow users to specify their own value.
also fixed other issues in the same file I noticed during the testing
1. the cluster context field value was mistakenly removed by Arvind in this commit: https://github.com/microsoft/azuredatastudio/commit/678bbe314283f3e3a9125c8b5a2bddb211954e57#diff-65f92098d2deba3a83e14f6c245ce984L56
2. set default value to empty string for the optional fields, otherwise it will be undefined and a text component won't be created, causing the layout to break. see the app readers, app owners fields in the **Before** screenshot
**Before**
**After**
=> expose realm field to the wizard UI

src/sql/media/icons/common-icons.css, src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts, src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.css, src/sql/workbench/contrib/notebook/browser/notebookStyles.ts
This PR fixes #10653 Markdown Cell Toolbar Keyboard Focus.
I utilized the masked-icon styles to use :before pseudo element similar to that of the notebook toolbar and cell toolbar. I made edits to reduce the CSS mask sizes in order to reduce code as well. 
Below are screenshots for the different themes illustrating the focus. 
Light Theme:
Dark Theme:
High Contrast Theme:
=> Fix markdown cell toolbar focus not being visible

src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
This PR fixes the issue of when a user is using keyboard navigation and presses enter on the "deploy a server" button tile, the next focus-able item was no in focus. It does this by making an invisible element that was being focused instead, no focus-able. The invisible item exists because it is part of a feature still development, and is not needed by the user yet. I have added a comment explaining that as well.
This PR fixes #10621
=> fixes tab focus not being visible after deploying a server

src/sql/workbench/browser/modelComponents/queryTextEditor.ts, src/sql/workbench/contrib/notebook/test/browser/notebookEditor.test.ts, src/sql/workbench/contrib/notebook/test/testCommon.ts
This addresses #11389.
The markdown language actually has editor overrides and always turns on word wrapping, so us relying on the global setting didn't work for this case. We can access whether the editor is wrapping through layoutInfo here.
=> Fix Notebooks Word Wrapping Logic

extensions/notebook/src/book/bookTreeView.ts
Issue: When no book/folder is opened on the viewlet, the treeView is undefined. (On new notebook command revealActiveDocumentInViewlet is invoked which checks for treeView visibility)
This PR fixes #11426
=> fix new notebook console error

extensions/resource-deployment/src/services/tools/kubeCtlTool.ts
this is the output i am getting on windows with latest kubectl. update our code to handle this scenario.
C:\Users\alanren>kubectl version --client -o json
{
"clientVersion": {
"major": "1",
"minor": "16+",
"gitVersion": "v1.16.6-beta.0",
"gitCommit": "e7f962ba86f4ce7033828210ca3556393c377bcc",
"gitTreeState": "clean",
"buildDate": "2020-01-15T08:26:26Z",
"goVersion": "go1.13.5",
"compiler": "gc",
"platform": "windows/amd64"
}
}
=> handle invalid character in kubectl version output

extensions/resource-deployment/src/services/tools/kubeCtlTool.ts
fortunately SemVer is able to handle the gitVersion string,
also tested :
"gitVersion": "v1.18.0",
=> let semver to parse the version

extensions/notebook/src/jupyter/jupyterSessionManager.ts
Got feedback that some customers are running into issues with how we've been hardcoding "python3" for spark kernels in ADS.
"python3" is the default on the cluster-side, and if it's overridden by customers, then we should be honoring that.
=> Stop hardcoding python3 for python version in spark kernels

src/sql/workbench/contrib/notebook/browser/models/outputProcessor.ts, src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts
This PR adds unit tests for OutputProcessor.ts
This PR also fixes #11355 and removes a couple of redundant checks in conditionals.
Testing: 
1.  Ran all unit test
2. Measured code coverage of the new tests.
Coverage:
[Code coverage report for workbench_contrib_notebook_browser_models_outputProcessor.ts.pdf](https://github.com/microsoft/azuredatastudio/files/4928535/Code.coverage.report.for.workbench_contrib_notebook_browser_models_outputProcessor.ts.pdf)
=> First draft of outputProcessor tests

extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
This PR fixes #11468. This adds a couple checks for if the loaded publish profile didn't have any sqlcmd variables: 
- table should only be added if the profile has sqlcmd variables 
- table should be removed if both the profile and project don't have sqlcmd variables
=> Fix sql proj sqlcmd table showing after loading publish profile when it shouldn't

extensions/dacpac/src/test/configPages.test.ts, extensions/dacpac/src/test/testContext.ts, extensions/dacpac/src/test/testDacFxConfigPages.ts, extensions/dacpac/src/test/testUtils.ts, extensions/dacpac/src/wizard/api/basePage.ts, extensions/dacpac/src/wizard/api/dacFxConfigPage.ts, extensions/dacpac/src/wizard/pages/dacFxSummaryPage.ts, extensions/dacpac/src/wizard/pages/deployConfigPage.ts, extensions/dacpac/src/wizard/pages/deployPlanPage.ts, extensions/dacpac/src/wizard/pages/exportConfigPage.ts, extensions/dacpac/src/wizard/pages/extractConfigPage.ts, extensions/dacpac/src/wizard/pages/importConfigPage.ts, extensions/dacpac/src/wizard/pages/selectOperationpage.ts
Also removes redundant variable definitions in dacfx wizard page classes.
Accidentally pushed a large replay on the other branch (https://github.com/microsoft/azuredatastudio/pull/11417), so I just cherry-picked my commits across to here.
=> Add test coverage for dacpac wizard import flow

extensions/azurecore/src/account-provider/auths/azureAuth.ts
oid values aren't present for personal accounts, sub values are different per tenant. This code should get us supporting most all types of accounts. I can't think of any that this would fail on.
=> Use home_oid, over oid, over unique_name, over sub

src/vs/workbench/browser/parts/editor/editorDropTarget.ts
Focus is in editor after dragging and dropping column/table into editor
This PR fixes #11403
=> focus in editor after dropping

src/sql/platform/dashboard/browser/interfaces.ts, src/sql/workbench/browser/modelComponents/modelStore.ts, src/sql/workbench/browser/modelComponents/viewBase.ts
This is specifically to fix an issue with the Arc dashboards where the loading components are having loading set to false too quickly on first load and so spin forever.
In the end this ties back to the race condition issues we keep seeing pop up with ModelView. The short synopsis of the issue is that when we execute the queued up actions they're all triggered at the same time - and order is not guaranteed. This means that we can sometimes run into issues where the initial calls to setProperties happens AFTER properties are updated by the extension side. This then causes those property values to be overwritten and causes issues such as the one above.
This isn't the perfect fix in my eyes - I'd rather we serialize the actions completely so that we always guarantee the order of execution. …
=> Do ModelView initialization actions before others

extensions/sql-database-projects/package.json
This PR fixes #11509. Just using this icon temporarily while we wait for the toolbar icon from UX.
=> Add back toolbar icon for importing db project

extensions/azdata/package.json, extensions/azdata/src/azdata.ts, extensions/azdata/src/common/childProcess.ts, extensions/azdata/src/common/httpClient.ts, extensions/azdata/src/common/promise.ts, extensions/azdata/src/extension.ts, extensions/azdata/src/localizedConstants.ts, extensions/azdata/src/test/azdata.test.ts, extensions/azdata/src/test/common/childProcess.test.ts, extensions/azdata/src/test/common/httpClient.test.ts, extensions/azdata/src/test/common/promise.test.ts, extensions/azdata/yarn.lock
1. Downloaded filename is pulled from URI instead of hardcoding. This may not work for all scenarios possible - but for our purposes in this extension it's controlled enough that this is fine (this is also leading into another enhancement I'm working on where we use that filename to determine the version so we know whether we need to download the installer or not in upgrade scenarios)
1. Show output channel when we start the install
1. Add MacOS installation support
1. Don't error commands on stderr (that's often used as a debug stream, not necessarily that the process failed to execute)
1. Don't block extension activation when prompting user to install azdata. This ends up blocking other extensions and test runs and in general extensions should always activate without needing user input. …
=> azdata improvements

src/sql/workbench/contrib/dashboard/browser/core/actions.ts
the name is not accurate, it is not actually a toggle button, change its name to avoid confusion and wrong expectation
This PR fixes #11552
=> update action name

extensions/dacpac/src/test/configPages.test.ts, extensions/dacpac/src/wizard/api/basePage.ts
This PR fixes #11226. Removes the system dbs from the dropdowns in the dacfx wizard since deploying to them isn't supported.
=> Remove system dbs from dacfx wizard dropdowns

extensions/notebook/src/jupyter/jupyterController.ts, src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts, src/sql/workbench/contrib/notebook/browser/notebook.component.ts, src/sql/workbench/contrib/notebook/browser/notebookActions.ts, src/sql/workbench/contrib/notebook/test/browser/notebookActions.test.ts, src/sql/workbench/contrib/notebook/test/testCommon.ts
Pass URI instead of the entire NotebookComponent for toolbar commands. Verified that the extension side gets the URI as well, which while currently isn't being used could be useful for contributed commands to interact with the editor. 
Fixes https://github.com/microsoft/azuredatastudio/issues/11563
=> Fix Notebook toolbar contributed actions

build/azure-pipelines/sql-product-build.yml
the schedule is defined for the daily insider build, but since it is in the yml file, all other ADS pipelines are getting the scheduled runs automatically. I think this should be at the pipeline level, once merged, I will update the Product Build pipeline to take care of its own schedule.
=> remove the scheduled run info from yml

extensions/dacpac/src/test/dacFxSummaryPage.test.ts, extensions/dacpac/src/test/testDacFxConfigPages.ts, extensions/dacpac/src/test/wizard.test.ts, extensions/dacpac/src/wizard/dataTierApplicationWizard.ts, extensions/dacpac/src/wizard/pages/dacFxSummaryPage.ts
Adding tests for summary page and cleaning up the generateDeployScript operation that didn't get removed when the deploy action page got removed a while ago in #5942.
=> Add DacFx summary page tests

extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
Previously, the fontsize for SQLCMD variables was 14 when the other titles were 12.
=> Make font size consistent in publish dialog

src/vs/base/browser/ui/selectBox/selectBoxCustom.ts
Fixes an error that happens when clicking on a dropdown without any options in it. Didn't appear to have any noticeable impact - this is just cleaning it up.
=> Fix error when clicking on empty dropdown

extensions/notebook/src/book/githubRemoteBook.ts, extensions/notebook/src/book/remoteBook.ts, extensions/notebook/src/book/remoteBookController.ts, extensions/notebook/src/book/sharedRemoteBook.ts, extensions/notebook/src/dialog/remoteBookDialog.ts, extensions/notebook/src/test/book/remoteBookController.test.ts
* Use vscode.URI for local paths
* Use vscode.uri file method to set the name for remotebookfull path compressed file
* Add await on extract tar function
* Replace remote paths too
* Use vscode.uri.file instead of parse for local paths
This PR fixes #11602
=> Replace URL and use vscode.URI on local paths (#11624)

extensions/notebook/src/jupyter/serverInstance.ts
The **notebook** pip package was recently updated, and the newer version uses a different "notebook started" message. We parse the jupyter output in order to detect the the server has started, so this message change broke our string parsing. The newer message format includes the notebook package version, so my fix here is to add a regex to detect that version snippet.
New message format:
"[I 14:28:37.225 NotebookApp] Jupyter Notebook 6.1.1 is running at:"
Old message format:
"[I 14:41:05.133 NotebookApp] The Jupyter Notebook is running at:"
I verified that this works with **notebook** 6.0.3 and 6.1.1.
Addresses https://github.com/microsoft/azuredatastudio/issues/11607
=> Use a regex to detect notebook started message.

extensions/asde-deployment/notebooks/edge/deploy-sql-edge-azure.ipynb, extensions/asde-deployment/package.json
the command `az vm image accept-terms --urn` is about to be removed, update it to use the new command and meanwhile update the required az-cli version.
=> replace obsolete command

src/sql/workbench/services/connection/browser/media/connectionDialog.css
remove the overflow-hidden property, the parent dialog already has the overflow-y scroll set, we can rely on it to have a dialog level vertical scrollbar.
This PR fixes #11644
=> show hidden connection properties

src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
This PR fixes a button height discrepancy between two buttons on the welcome page. It removes a duplication of a CSS class.
This PR fixes #11466
=> fixes button height discrepancy on welcome page

extensions/resource-deployment/src/ui/modelViewUtils.ts
Improves error message shown to the user when there is a failure to fetch the subscription/resource group. Here is what the improved messages look like:
The improved messages are emitted when the account is chosen is no longer available or is no longer signed in. Here are the sample messages for each case:
1. The selected account 'Arvind Ranasaria - arvran@microsoft.com (iIBqJnswLig1ZXx3fBnlL0fBT9XNVk1EDi2eVXTMazs)' is no longer available. Please click the 'Sign in' button to add it again or select a different account.
2. The access token for selected account 'Arvind Ranasaria - arvran@microsoft.com (acc41c7a-3409-4ece-bd95-39ad3e31dd05)' is no longer valid. Please click the 'Sign in' button and refresh the account or select a different account.
This PR fixes #11499.
=> emit better errors for azure access failure

src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
This PR fixes the issue:
1. Open Welcome Page
2. Notice under recent list items have been duplicated
3. Notice a few seconds later it shows the correct list
It does so my filtering the list and removing any duplicate items.
This PR fixes #11366
This PR fixes #11578
=> fixes duplicate list items on welcome #11366

src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
This PR fixes the issue of the open button text not showing. It does this by adding the appropriate class to the button that applies the color styling.
Before:
After:
This PR fixes #11598
=> fixes open button copy not showing #11598

src/sql/workbench/contrib/dashboard/browser/widgets/properties/propertiesWidget.component.ts
Fix for reading "options" property from backend when translating to show Cluster/DB properties on manage dashboard in ADS
=> Fix for reading "options" property from backend in manage dashboard

src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts
This is a fix for https://github.com/microsoft/azuredatastudio/issues/11684 regarding dashboards not showing up without preview flag set.
=> Add welcomePageWithTour to startupEditor check

src/sql/workbench/contrib/dashboard/browser/pages/databaseDashboardPage.contribution.ts, src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.contribution.ts
confirmed with Udeesha, these 2 actions should only be shown for mssql. noticed while working on Kusto dashboard.
=> show backup/restore only for mssql

extensionsGallery-insider.json
This includes a fix for using the new Azure APIs instead of the deprecated commands (which have been removed)
=> Update machine-learning to 0.2.2 insiders

src/sql/workbench/services/connection/browser/connectionManagementService.ts
noticed the following error while connecting to PGSQL
ERR Cannot read property 'isBigDataCluster' of undefined: TypeError: Cannot read property 'isBigDataCluster' of undefined
=> fix connection telemetry error

extensions/machine-learning/package.json
This should have been done when the extension was last updated but apparently was missed. (0.2.1 is the current released version). 
This will be the version released with the August release - where it will be bumped again as per our version bumping guidelines.
=> Update ML package version

extensionsGallery-insider.json
Missed doing this - requires latest ADS version with the azurecore changes
=> Update required azdata version for ML extension

extensions/markdown-language-features/src/commands/openDocumentLink.ts
Port fix for relative links in markdown preview
(cherry picked from commit 3683aaaf2a7e88ab609cf98bd77049c43d97faa7)
Fixes https://github.com/microsoft/azuredatastudio/issues/11657
=> Port : Fix/markdown links (#11708)

src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts
this is more of a short term fix, a proper fix would require us to add new capability to scripting service and query whether specific operations are supported for certain object types. I made an issue to track it: https://github.com/microsoft/azuredatastudio/issues/11735
=> hide edit data and script as create

extensions/azdata/src/test/azdata.test.ts
This a quick fix for findAzdata tests. Previously for unsuccessful test case of findAzdata we were only stubbing the response form searcForCmd function call but since that function is not invoked on mac/linux the test was not working as expected.
With this fix we stub the executeCommand to resolve and reject for sucessful and unsucessful test cases respectively which works on all platforms. We still stub searchForCmd so that will give out an arbitrary path when the test is run so that invocation of that function returns success on windows platform.
=> findAzdata test fix

src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts
Hides Edit Data , Script as Create and Script as drop for Kusto tables. This is short term fix, there is already an issue for proper fix: https://github.com/microsoft/azuredatastudio/issues/11735
=> Hides Edit Data , Script as Create and Script as drop for Kusto tables

src/sql/workbench/browser/editData/editDataInput.ts, src/sql/workbench/browser/editData/editDataResultsInput.ts, src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts, src/sql/workbench/contrib/editData/browser/editDataResultsEditor.ts
Refreshing the grid now uses a promise listener relationship between editDataInput and editDataGridPanel that waits for the refresh to complete fully before returning.
RefreshGrid has been modified to ensure that all steps are completed before returning.
This PR fixes #11259
=> Refresh fix for Edit Data

extensions/sql-database-projects/src/controllers/projectController.ts
This PR fixes #11765. This was caused by a closing curly bracket on the wrong line, probably from a merge conflict in this refactoring PR #11184. Also fixes another bug introduced from that PR which caused the databases to be listed even if the connection from the connection dialog already specified the db.
=> Fix importing new project from server dashboard

extensions/notebook/src/jupyter/jupyterServerInstallation.ts, extensions/notebook/src/test/python/configurePython.test.ts, extensions/notebook/src/test/python/jupyterInstallation.test.ts
There's a lot of code in JupyterServerInstallation, so these tests only increased the code coverage by 10-20%. Unit testing the python installation would require a lot of mocking, so I'll try to tackle that next week.
=> Add some package management unit tests for JupyterServerInstallation

build/azure-pipelines/darwin/sql-product-build-darwin.yml, src/vs/workbench/contrib/welcome/telemetryOptOut/browser/telemetryOptOut.ts, src/vs/workbench/contrib/welcome/telemetryOptOut/electron-sandbox/telemetryOptOut.ts, test/automation/src/sql/connectionDialog.ts
Will get rid of the notifications that are making smoke tests unreliable.
=> Add check for disable telemetry when showing opt out

extensions/sql-database-projects/src/common/constants.ts, extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts, extensions/sql-database-projects/src/models/dataSources/sqlConnectionStringSource.ts, extensions/sql-database-projects/src/test/baselines/openDataSourcesBaseline.json, extensions/sql-database-projects/src/test/datasource.test.ts, extensions/sql-database-projects/src/test/projectController.test.ts
This PR fixes #11262. This adds support for AAD interactive connection strings for data sources and publish profiles. If a profile that has an AAD interactive connection string is loaded, then the connection dialog opens with the authentication type set to Azure Active Directory - Universal with MFA Support.
=> Add support for AAD interactive connection strings for project data sources

src/sql/base/browser/ui/taskbar/media/icons.css, src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts, src/sql/workbench/contrib/query/browser/queryEditor.ts
css gets a bit mangled during the webpacking so it doesn't apply correctly on built versions - the important notation makes sure the rules get applied correctly.
=> Add separate config for enabling nb convert and fix css

src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookSearch.ts
This PR fixes #11779 
Issue: On selection change, irrespective if the node is file/folder, am trying to open it in the editor. 
Fix: Check if the selection is a file resource and only then open it in the editor.
=> open resource only when it's file

extensions/notebook/src/dialog/configurePython/configurePythonWizard.ts, extensions/notebook/src/integrationTest/notebookIntegration.test.ts, extensions/notebook/src/jupyter/jupyterServerInstallation.ts
Our new python installation logic only installs packages needed by a kernel when that kernel actually gets used. Currently the Reinstall action installs required packages for all kernels, which can take a while. This change only installs jupyter as an extra dependency during reinstall, and then others can get installed as the user clicks on different kernels. A nice side effect of this change is now we only track required packages in a single place in **getRequiredPackagesForKernel**, so that package changes will be easier to make in the future.
=> Simplify python reinstallation by only installing jupyter.

src/sql/workbench/browser/scriptingUtils.ts, src/sql/workbench/contrib/dataExplorer/browser/nodeContextUtils.ts, src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts, src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts, src/sql/workbench/services/objectExplorer/browser/media/objectTypes/objecttypes.css, src/sql/workbench/services/objectExplorer/browser/mssqlNodeContext.ts, src/sql/workbench/services/objectExplorer/common/nodeType.ts
Updated scriptingUtils > script to pass providerName when creating newSqlEditor. Added new NodeType Function. Added function node type to scriptasalter menu item. Added function to dragndrop functionality.
=> 2728 Kusto Function Support

extensions/notebook/src/jupyter/jupyterServerInstallation.ts
Python packages are included with ADS when installed on a SAW device, so adding the user package directory to the PATH is unnecessary.
=> Skip adding python user package directory to PATH on SAW devices.

src/sql/workbench/contrib/dashboard/browser/core/actions.ts, src/sql/workbench/contrib/notebook/browser/notebookActions.ts, src/vs/base/browser/ui/actionbar/actionViewItems.ts, src/vs/base/common/actions.ts, src/vs/workbench/contrib/markers/browser/markersViewActions.ts
This PR fixes #11551 
I tried to push the vs part changes to vscode repo, but vscode team is not willing to take it: https://github.com/microsoft/vscode/pull/103577, so I am making those changes directly in ADS. I also noticed the Collapse/Expand cells action of notebook also has the same issue and the fix is also included in this PR.
notebook collapse/expand cell button
dashboard collapse/expand properties widget button
=> support aria-expand for actions

src/sql/workbench/contrib/query/browser/queryEditor.ts
- Fixes the issue where sql editor task bar doesnt show action buttons when there is no connection.
- Bringing back the code when creating a new taskbar (createTaskbar() function).
=> Fix for File -> New Query

src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.css, src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.html, src/sql/workbench/contrib/notebook/browser/cellViews/textCell.css, src/sql/workbench/contrib/notebook/browser/notebookStyles.ts
This PR fixes #11847 - makes the markdown editing toolbar sticky with a longer text cell. 
Before - toolbar is only visible at the very top of the cell: 
After - toolbar is visible after scroll:
=> Make markdown editing toolbar visible at all times

src/sql/workbench/contrib/notebook/browser/cellViews/code.component.html, src/sql/workbench/contrib/notebook/browser/cellViews/code.css
This PR fixes #11902 - the code button now moves with scrolling so you can run the code cell from anywhere. 
Example:
=> Create sticky run code button for notebook code cell

src/sql/workbench/services/objectExplorer/browser/asyncServerTreeDragAndDrop.ts, src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/11886
This was/is actually not behaving correctly in the normal server tree so I'm fixing it there too - we should only be expanding connection nodes if they're connected.
=> Fix dnd auto-connecting profiles when dragging

src/sql/workbench/services/objectExplorer/browser/asyncServerTreeDragAndDrop.ts, src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts, src/sql/workbench/services/objectExplorer/browser/treeCreationUtils.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/11874
Set tree context and targetElement so we can use the old logic.
=> Fix dropping async oe tree item onto root

src/sql/workbench/browser/modelComponents/queryTextEditor.ts
This PR fixes #11860 - change the diffEditor variable to enable word wrap in text cells for notebooks.
=> Add word wrap feature in notebook markdown cells

extensions/notebook/src/dialog/configurePython/configurePythonWizard.ts, extensions/notebook/src/test/python/configurePython.test.ts, src/sql/workbench/browser/modelComponents/viewBase.ts
A couple of problems:
- We weren't awaiting `wizard.open()`
- We were calling `changeRef.detectChanges()` without checking whether the `changeRef` was already `destroyed` in src/sql/workbench/browser/modelComponents/viewBase.ts.
Once I fixed these issues, the tests in question passed without any weird disposableStore exceptions being thrown.
=> Re-enable previously commented out configure python wizard tests

src/sql/platform/browser/editableDropdown/editableDropdown.component.ts, src/sql/platform/browser/selectBox/selectBox.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/11968
We could also expose this as a configurable option if we're worried about this affecting other components - but in general I don't see why we wouldn't want to update the value every time the text changes. 
(also fixed a name mismatch I saw while looking at this issue)
=> Make editable dropdowns emit value change events on type

extensions/mssql/package.json, extensions/mssql/src/contracts.ts, extensions/mssql/src/features.ts, extensions/mssql/src/sqlToolsServer.ts, extensions/mssql/yarn.lock
now that protocol client vbump is available, this PR updates ADS to use 1.2 and to recreate the profilerfeature definition locally.
this is PR replaces an earlier attempt that got messed up by my poor git kungfu.
=> redo profiler feature move from protocolclient

extensions/arc/package.json, extensions/arc/package.nls.json, extensions/arc/src/extension.ts, extensions/arc/src/models/controllerModel.ts, extensions/arc/src/test/mocks/fakeControllerModel.ts, extensions/arc/src/test/models/controllerModel.test.ts, extensions/arc/src/test/ui/dialogs/connectControllerDialog.test.ts, extensions/arc/src/test/ui/tree/azureArcTreeDataProvider.test.ts, extensions/arc/src/ui/dialogs/connectControllerDialog.ts, extensions/arc/src/ui/tree/azureArcTreeDataProvider.ts, extensions/arc/src/ui/tree/controllerTreeNode.ts, extensions/arc/yarn.lock
The main part of this PR is fixing an issue where if the username was changed during a reconnect that we'd see that as a new node instead of updating the existing one.
To fix this I moved away from determining model uniqueness from url + username and instead just generate a UUID for each node to guarantee that when it's updated it will always update correctly. 
This does mean users could have multiple nodes with same url + username which is a bit odd - but that's up to them and they can easily remove duplicate nodes if they want. 
Added test to verify this behavior works as expected.
- Fixed a couple missed awaits I noticed while working on this
- Added "Edit Connection" action since that functionality was pretty much already completely implemented (fixes …
=> Fix arc node info updating

src/sql/workbench/contrib/notebook/browser/cellViews/code.component.html
This PR fixes #11988 - run code cell is still sticky and there is no more overflow on long lines for code cells. \
Before:
After:
=> Fix overflow issues with notebook cells

extensions/kusto/src/main.ts
This PR fixes #11984
Fix for error in VSCode when Kusto extension is getting activated.
=> Fix Kusto startup error

build/azure-pipelines/linux/sql-product-build-linux.yml
Was getting build failures if the tests weren't ran https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=75407&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=113d799d-a361-55ff-50d8-9c14ded0c900
=> Only copy coverage if tests were ran

extensions/sql-database-projects/package.json, extensions/sql-database-projects/src/models/tree/projectTreeItem.ts
1. Hiding Data source from Tree 
2. Hiding Exclude item command from command pallet
=> minor cleanups to hide extra tree and command pallet items 

extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts, src/sql/azdata.proposed.d.ts, src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts
We have the RadioCard object, let's return that to the user. This way the user can put extra metadata on top of the RadioCard and get it back - reducing the need for a lookup table.
The API was in proposed so I don't feel too bad for breaking it. Let's make sure we do this for future components, lookup by ID is so 2019 :D
=> radio card change

src/sql/workbench/services/errorMessage/browser/errorMessageDialog.ts
this PR fixes https://github.com/microsoft/azuredatastudio/issues/12060
introduced by this PR: https://github.com/microsoft/azuredatastudio/commit/adfdd569075e7a83c8a8c2c71a1b897648634cd0#diff-a4aa25990fc5fc205ac53f5b4769e960R78
the connection error dialog is not showing up with the following error message in the console:
root cause, the copybutton is not initialized due to the newly added if check statement.
=> fix the issue that error dialog is not showing

src/sql/workbench/contrib/query/browser/queryEditor.ts
- Sets language mode based on connection type for query editor with no file extensions
- Resolves the issue when user switches between connection types i.e. sql to kusto or vice versa and intellisense etc stops working for the new connection type because language mode is still the old one.
=> Sets language mode based on connection type for query editor with no file extension

src/sql/workbench/contrib/views/browser/treeView.ts
Broken by https://github.com/microsoft/azuredatastudio/pull/12044 - DOM.toggleClass throws an error if you pass in an empty string for the className which was causing our custom tree views to break.
```
ERR Failed to execute 'toggle' on 'DOMTokenList': The token provided must not be empty.: Error: Failed to execute 'toggle' on 'DOMTokenList': The token provided must not be empty.
```
Before 
After
=> Fix tree view icons

src/sql/workbench/browser/editor/profiler/dashboardInput.ts
This PR fixes #12106 
the getter for the container property of the dashboardInput was changed unexpectedly by https://github.com/microsoft/azuredatastudio/commit/d8dcc9085731df0ff6bb9dc336c0a76e6e1a0dd0#diff-fa11a5cd769e38a19da55711f5836079L131
this is causing the container property to be undefined.
=> give back the getter for container property

extensionsGallery-insider.json
Current icon has white background and does not look well in dark mode. Switching icon to one that has transparent icon.
=> Switch Kusto Icon to one that has transparent background

src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts
Without this clicking on the header filter icon would propagate to the header and thus cause it to sort the column as well.
Also added typing to the onCommand event
=> Don't propagate click when clicking on header filter

extensions/azurecore/src/azureResource/utils.ts, extensions/azurecore/src/azurecore.d.ts, extensions/azurecore/src/extension.ts, extensions/machine-learning/src/test/stubs.ts, extensions/sql-migration/src/api/azure.ts
I think there's a better way we could be doing this - because right now you need to :
1. Get all subscriptions for an account - which queries each tenant for the subscriptions on it
2. Then go and again iterate over all the tenants and run the queries against the subs in that tenant
So we get the security token 2 times and go through some extra processing. Could probably shortcut it to allow :
1. Getting all resources for all subscriptions (which wouldn't take in any subscriptions - it'd just run that query itself)
2. Allow specifying a subset of tenants instead so the caller doesn't necessarily have to fetch the subscriptions first
But for now this should be fine and isn't a huge amount of overhead so I think it's fine to keep as is.
=> Allow multiple subs for runResourceQuery

extensions/azurecore/src/azureResource/azure-resource.d.ts, extensions/azurecore/src/azureResource/providers/database/databaseService.ts, extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerService.ts, extensions/azurecore/src/azureResource/providers/kusto/kustoService.ts, extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerService.ts, extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerService.ts, extensions/azurecore/src/azureResource/providers/resourceGroup/resourceGroupService.ts, extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceService.ts, extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcService.ts, extensions/azurecore/src/azureResource/services/subscriptionService.ts, extensions/azurecore/src/localizedConstants.ts, extensions/azurecore/src/test/azureResource/providers/database/databaseTreeDataProvider.test.ts, extensions/azurecore/src/test/azureResource/providers/databaseServer/databaseServerTreeDataProvider.test.ts, extensions/azurecore/src/test/azureResource/resourceService.test.ts, extensions/azurecore/src/test/azureResource/resourceTreeNode.test.ts, extensions/azurecore/src/test/azureResource/tree/accountTreeNode.test.ts, extensions/azurecore/src/test/azureResource/tree/subscriptionTreeNode.test.ts, extensions/azurecore/src/utils.ts, extensions/machine-learning/src/test/modelManagement/azureModelRegistryService.test.ts, extensions/machine-learning/src/test/views/models/ModelManagementController.test.ts, extensions/machine-learning/src/test/views/models/azureModelsComponent.test.ts, extensions/machine-learning/src/test/views/models/predictWizard.test.ts, extensions/machine-learning/src/test/views/models/registerModelWizard.test.ts, extensions/sql-migration/src/api/azure.ts
Subscriptions already had the id property so subscriptionId is redundant. 
Also adding enum for easily getting the resource types and a helper method for the display names of those types (will be used in the resource viewer)
=> Remove extra id property from azure subs and add type name helper

src/sql/azdata.d.ts, src/sql/azdata.proposed.d.ts, src/sql/workbench/api/common/extHostModelView.ts
This PR is branched off of amir/componentGenerics
https://github.com/microsoft/azuredatastudio/pull/12158
This will allow you to do `modelBuilder.inputBox().withProps(` without having to specify the property type
=> Genericify azdata components

extensions/azurecore/package.json, src/sql/platform/resourceViewer/common/resourceViewerRegistry.ts, src/sql/workbench/contrib/resourceViewer/browser/media/resourceViewerView.css, src/sql/workbench/contrib/resourceViewer/browser/resourceViewer.contribution.ts, src/sql/workbench/contrib/resourceViewer/browser/resourceViewerView.ts, src/sql/workbench/contrib/resourceViewer/browser/resourceViewerViewlet.ts, src/sql/workbench/contrib/resourceViewer/common/resourceViewer.ts, src/sql/workbench/contrib/resourceViewer/common/resourceViewerViewExtensionPoint.ts
Adds the initial resource view. Resources are declares in the contributions of extensions that are then rendered in a flat tree. Detects the arc extension and only registers the view if it is installed.
Current:
TODO:
Add icons
=> Add initial resource view

src/sql/workbench/contrib/notebook/browser/notebookActions.ts, src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR fixes #12178 by using currentKernelAlias instead of constants. Should load all connections available when the notebook is not connected to anything.
=> Fixed Kusto change connections for previous notebooks

src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts, src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts, src/sql/workbench/contrib/notebook/browser/notebook.component.html, src/sql/workbench/contrib/notebook/browser/notebook.component.ts, src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts
This PR fixes #12076 
- Adds double click to edit functionality to notebook text cells
- Adds setting to enable or disable feature (enabled by default)
=> Enable double click edit

src/sql/azdata.d.ts, src/sql/azdata.proposed.d.ts, src/sql/workbench/contrib/notebook/browser/cellViews/output.component.ts, src/sql/workbench/contrib/notebook/browser/cellViews/outputArea.component.html, src/sql/workbench/contrib/notebook/browser/cellViews/outputArea.component.ts, src/sql/workbench/contrib/notebook/browser/models/fileNotebookInput.ts, src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts, src/sql/workbench/contrib/notebook/browser/models/untitledNotebookInput.ts, src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts, src/sql/workbench/contrib/notebook/browser/outputs/mimeRegistry.ts, src/sql/workbench/contrib/notebook/test/browser/cellToolbarActions.test.ts, src/sql/workbench/contrib/notebook/test/browser/dataResourceDataProvider.test.ts, src/sql/workbench/contrib/notebook/test/browser/notebookEditor.test.ts, src/sql/workbench/contrib/notebook/test/browser/notebookInput.test.ts, src/sql/workbench/contrib/notebook/test/stubs.ts, src/sql/workbench/services/notebook/browser/models/cell.ts, src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts, src/sql/workbench/services/notebook/browser/models/notebookModel.ts, src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts, src/sql/workbench/services/query/common/queryManagement.ts, src/sql/workbench/services/query/test/common/testQueryManagementService.ts
This PR adds grid streaming support for notebooks. 
Previous grid rendering behavior: wait for entire query result to be returned before converting rows to data types (mimeType and html) and then displaying data.
Changes for streaming: 
- Added listeners for onResultSet and onResultSetUpdate
- Start updating the table before converting rows to mimeType and html
- Moved data conversion logic from sqlSessionManager to DataResourceDataProvider
- Added gridDataConversionComplete to notebook model to make sure that all rows have been converted (in case user tries to save the notebook before conversion is complete)
=> Add grid streaming support for notebooks

extensions/sql-database-projects/src/controllers/projectController.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/12223
The issue was that executing the command to get focus for the view before setting the tree focus caused a race condition to focus the tree twice. Changing the order fixes the race condition.
=> Fix focus order for db projects

extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts, extensions/azdata/src/typings/azdata-ext.d.ts
Fixes #12024. Populating the vCore field if it's returned by azdata (only set if the user specifies it during a `create` or `edit` command; otherwise, show '-'; confirmed with PM):
vcore limit returned by azdata:
no vcore limit returned:
=> MIAA: Add vCore Number to Dashboard

src/sql/workbench/contrib/resourceViewer/browser/media/resourceViewerView.css, src/sql/workbench/contrib/resourceViewer/browser/resourceViewerEditor.ts, src/sql/workbench/contrib/resourceViewer/browser/resourceViewerTable.ts
Super minor tweaks (first part). I'm currently ignoring contributed column widths here in lieu of a full container width experience. Sorry @Charles-Gagnon.
- Filtering now is functional
- CSS tweaks to ensure actions aren't behind labels
- Columns auto-fit to container
=> Quick tweaks to resource viewer (v1)

src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts, src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts, src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts, src/sql/workbench/services/notebook/browser/models/cell.ts, src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts
Fixes #12242. Adds setting for default text cell behavior. Defaults to WYSIWYG.
=> Notebooks: Add setting for default text cell edit behavior

extensions/notebook/src/book/bookTreeItem.ts, extensions/notebook/src/common/appContext.ts, extensions/notebook/src/common/constants.ts
This PR fixes #12103
Next and Previous buttons where not visible on books because _getNavigation_ was getting the pinnedBookTreeViewProvider instead of the bookTreeViewProvider.
=> Fix pinned notebooks navigator

extensions/sql-database-projects/package.json
To address :  https://github.com/microsoft/azuredatastudio/issues/11979
Using vscode icons that look like following. Adding only for current project view in file explorer not the new view since that will be dialog based.
=> adding icon for add new and open project

src/sql/workbench/contrib/query/browser/gridPanel.ts
This PR will fix https://github.com/microsoft/azuredatastudio/issues/12273 in main and will have to be ported to release for September.
This bug was somehow introduced in https://github.com/microsoft/azuredatastudio/pull/11566
Examples of 2 different resultsets maximized-
=> Fix maximize bug

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.css
Removed custom CSS that positioned editor text beneath overlapping layers. Text is now selectable.
This PR corrects issue described in #12284
=> 12284 - Notebook UI - Text cell - Split view Markdown text section fix.

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
Addresses #12270.
Because of https://github.com/markedjs/marked/issues/1733, tables with captions aren't rendered properly. turndown basically does the following:
```
<caption>blah</caption>
| Rule name | Direction | Priority | Purpose |
| --- | --- | --- | --- |
| AllowSSHRule | Inbound | 100 | Allow inbound SSH |
```
Just need to add a new line here after caption.
I checked with PM + design, and it was determined that we should show/render captions instead of hiding them.
=> Notebooks: Add newline after caption for WYSIWYG

src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts, src/sql/workbench/contrib/notebook/browser/notebook.component.ts, src/sql/workbench/services/notebook/browser/models/notebookModel.ts
Addresses #12310.
The onLoad() event doesn't get fired when opening a notebook, because we hook into the event after it's initially loaded. Verified that there are no issues when making the transition from untitled to saved.
Note: discussed with PM and the decision to deliver value incrementally was made (as opposed to waiting for the full experience where the viewlet is updated as well); the viewlet work will be handled separately in an upcoming release.
=> Notebooks: Watch for changes outside of ADS

src/sql/workbench/browser/modelComponents/declarativeTable.component.html
(cherry picked from commit 4dd04cb25038c414b7a09f10de1beb381efc9599)
Fixes https://github.com/microsoft/azuredatastudio/issues/12304
A change was made to the Declarative Table component (used by extensions) which breaks the functionality to allow embedding other components (such as links/images/etc) in the cells for the table. This affects any extension which uses this - of which there's a lot (the BDC/Arc dashboards for example). Uses will just see a blank cell instead of the actual component.
=> Fix component items in declarative table not showing (#12330)

extensions/arc/src/models/controllerModel.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/12227
If multiple refreshes were kicked off at the same time (such as tree node expanding + dashboard refreshing) then we'd often end up duplicating the nodes since we were only clearing once when the refresh started. 
I considered also making it so only one refresh could happen at a time but opted not to do that since the refresh has multiple parts that finish async'ly and fire events to indicate they've been updated - which could mess up callers if they expected that after refresh was called they'd get notified for all those events. If an existing refresh had partially finished though they wouldn't get the events for the ones that had already finished.
=> Fix duplicate arc instance nodes

extensions/arc/package.json, extensions/arc/src/ui/tree/noInstancesTreeNode.ts, extensions/arc/src/ui/tree/refreshTreeNode.ts
The "Manage" action was showing up for nodes it wasn't supposed to be - fix it so that only resource nodes have a truthy viewItem value so the option only appears for them (minus PG until that's fixed)
=> Fix manage action for arc view

src/sql/azdata.d.ts, src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts, src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts, src/sql/workbench/services/notebook/browser/models/cell.ts, src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts
This PR addresses https://github.com/microsoft/azuredatastudio/issues/12275
Added unique query runners for each code cell to prevent updates to result tables in later code cells from affecting/changing tables in earlier code cells. 
Manually tested run all cells, add/delete cells then run again, save notebook, and change connection to make sure there are no regressions. Only change is when a new cell is run for the first time, there is a couple seconds wait time since a new query runner is being added (same wait time as running first cell in a new notebook before). 
Note: Also added missing escape import to gridOutput.component.ts that was causing some column headers to be saved incorrectly.
=> Fix notebook table rendering with multiple code cells

src/sql/workbench/contrib/notebook/browser/models/notebookTextFileModel.ts, src/sql/workbench/contrib/notebook/test/electron-browser/notebookEditorModel.test.ts
Add support in our notebookTextFileModel to overwrite a cell's source. This addresses #12287. 
When in WYSIWYG mode, we cannot rely on their being an editor present, so we don't get the editor content change events for free here. To mitigate this, I've added the ability to overwrite the entirety of a cell's source if a contentChangedEvent isn't present, so that we can localize the changes necessary to at least that cell's source. For a 68MB test notebook, I don't see any noticeable lag when editing a text cell in WYSIWYG after this.
Added tests to ensure consistency, and tried a bunch of manual scenarios as well.
=> Notebooks: Fast update WYSIWYG support for source update

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
* 12360 Notebook UI - Mac/Win fix for Select all.
* Fix for ctrl key selecting all in windows
* Fix undo as well
* preventDefault to prevent confusing behavior
Co-authored-by: chlafreniere <hichise@gmail.com>
This PR fixes #12360
=> 12360 Notebook UI - Mac/Win fix for Select all. (#12383)

src/sql/base/browser/ui/table/tableDataView.ts
It would try to access the first element later on and would throw. No behavior change here - just getting rid of the error popping up in the console.
=> Fix error when clicking on header for tables with no rows

src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts
Change default "Select Top 1000" query label to "Take 10" for Kusto tables
=> Change default Select query label to "Take 10" for Kusto tables

extensions/arc/package.json, extensions/arc/package.nls.json
Update with latest list of valid regions and remove the docker container summary item (the actual field was removed in an earlier PR)
=> Fix arc deployment regions and remove docker summary

src/sql/workbench/browser/modelComponents/card.component.html, src/sql/workbench/browser/modelComponents/card.component.ts, src/sql/workbench/browser/modelComponents/media/legacycard.css
the card.css was shared by the new radioCardGroup component and the deprecated card component. but recently Aasim and Amir have made changes to it for the new style of the radio card group component. the ML extension is still using the card component.
the fix is to copy the content of previous version of card.css and create a new css file that is only used by card component.
after September release, Udeesha will replace the radio component with radio card group component in ML extension and I will remove the card component.
before:
after:
https://github.com/microsoft/azuredatastudio/issues/12420
=> fix the legacy card style issue

src/sql/workbench/contrib/notebook/browser/notebookActions.ts, src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR fixes:
- All Spark kernel connections are being limited to Kusto connections in notebook connection picker
- Issue when Kusto has a connection and is unable to switch to PySpark
Spark kernel connections will display only MSSQL connections.
=> Fix Spark kernel connections and switch from Kusto to Spark kernels

extensions/arc/package.json, extensions/arc/package.nls.json, extensions/arc/src/localizedConstants.ts
Use the official Postgres hyperscale product name.  Fixes:
https://github.com/microsoft/azuredatastudio/issues/12431
https://github.com/microsoft/azuredatastudio/issues/12432
https://github.com/microsoft/azuredatastudio/issues/12433
https://github.com/microsoft/azuredatastudio/issues/12435
https://github.com/microsoft/azuredatastudio/issues/12438
Before and after screenshots:
=> Fix postgres product name

extensions/arc/package.json, extensions/arc/src/models/controllerModel.ts, extensions/arc/src/models/postgresModel.ts, extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts, extensions/arc/src/ui/dashboards/postgres/postgresConnectionStringsPage.ts, extensions/arc/src/ui/dashboards/postgres/postgresDiagnoseAndSolveProblemsPage.ts, extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts, extensions/arc/src/ui/dashboards/postgres/postgresPropertiesPage.ts, extensions/azdata/src/azdata.ts, extensions/azdata/src/extension.ts, extensions/azdata/src/typings/azdata-ext.d.ts
Re-enables the Arc Postgres dashboard.  Gets the overview, connection strings, and properties pages wired up.  Enables reset password, link to azure portal.
Needs workarounds for 2 UI issues.
- Loading components get stuck spinning if you visit the page for the first time after the loading -> !loading transition.  Probably just won't use them on anything other than the default page (overview).
- Properties and connection strings pages get stuck with their initial data.  UI doesn't show the updated values when the text/inputbox component values are modified.
=> Arc - Enable Postgres dashboard

extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/12422
The "Validate EULA" button added to the Deployment Dialog in a previous PR wasn't being hidden immediately so would show up when initially opening the page even if an item that was selected didn't need the button shown (which most don't)
=> [Port] start with eulaCheckButton hidden (#12427)

extensions/arc/package.nls.json
Part of https://github.com/microsoft/azuredatastudio/issues/12148
Adding preview text to Controller deployment to align with rest of Arc items.
=> Add preview to Arc controller deployment

extensions/resource-deployment/package.json, extensions/resource-deployment/src/services/tools/azdataToolOld.ts, extensions/resource-deployment/src/services/toolsService.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/12462
This is a temporary fix - I'll create an issue to follow up and move the BDC contribution to use the azdata extension for post-September release.
=> Revert BDC deployment back to using old azdata check

extensions/arc/package.json
Fixes https://github.com/microsoft/azuredatastudio/issues/12468
Extension should be activated when resource deployment is launched. 
@alanrenmsft We should consider having the resource deployment extension activate any extensions that it finds which contribute resource types.
=> Activate arc extension with resource deployment command

extensions/machine-learning/src/views/models/manageModels/currentModelsTable.ts
This PR addresses https://github.com/microsoft/azuredatastudio/issues/12446 (approved)
It adresses this too : https://github.com/microsoft/azuredatastudio/issues/12464
I know this seems like a weird fix. It seems like is something changed in the behavior of "updateproperties" but don't want to hold for this PR for RCA.
=> change to allow refresh and delete correctly

src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/12476
I added a method in DataResourceDataProvider to update the resultSet. 
Previously the result grid was being updated in DataResourceTable but not in DataResourceDataProvider. This caused issues when serializing the data because the resultSet in DataResourceDataProvider had 0 rows.
=> Notebooks: Fix save result grid actions

extensions/arc/package.json, extensions/arc/package.nls.json
Part of https://github.com/microsoft/azuredatastudio/issues/12082
Controller doesn't have any validation on the azdata side so not going to add any for now.
PG has validation but I'm not sure it's correct - current regex is `^[a-z]([-a-z0-9]{0,8}[a-z0-9])?$` but I was able to make an instance with a much longer name. @bergeron should this be changed?
New error message :
=> Add SQL instance name validation

extensions/machine-learning/src/views/models/manageModels/modelImportLocationPage.ts
To Address : https://github.com/microsoft/azuredatastudio/issues/12444
The table name of model table in ML extension is not getting picked correctly. It seems to have caused by a change to reorder the pages. 28b0d82
Since we would not want to change the order back - adding this change to setup the table name in the last page.
=> add table name to models that are imported

src/sql/workbench/contrib/notebook/browser/notebookActions.ts
This PR address #12488. 
When any Spark Kernel is chosen and the user changes connection via "attach to" to an MSSQL BDC connection it stays as the Spark Kernel. 
Also, this PR ensures another scenario where if a user chooses Kusto, and connects to an MSSQL connection via "attach to", that the kernel will change to SQL.
=> Fix PySpark Kernel Connection Change

src/sql/workbench/contrib/notebook/browser/models/notebookTextFileModel.ts, src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts, src/sql/workbench/contrib/notebook/test/electron-browser/notebookEditorModel.test.ts
This addresses #12473. 
There are changes in how notebook outputs are handled now with how we're doing grid streaming; previously, we would display messages and then the table, but now, we get the messages after we get the grid headers, meaning that we have to insert the messages before the table (whenever we get them).
The notebook text file editor model assumed that outputs could only be appended, and not prepended.
Also needed to tell the text editor model to update once all of the data came back.
Thankfully, we have a "fast" (single-digit ms) version of being able to do clear outputs, so I'm leveraging that to ensure that we're making this change in the JSON file correctly. Is it 100% ideal? No, but as long as it works, I think the mitigation is good enough for now.
=> Notebooks: Fix Grids Not Rendering when Unsaved Notebook Reloaded

extensions/arc/src/localizedConstants.ts, extensions/arc/src/ui/dashboards/miaa/miaaDashboardOverviewPage.ts, extensions/arc/src/ui/dashboards/postgres/postgresOverviewPage.ts
Wasn't happy that there wasn't any feedback that the instance was being deleted - this makes it much clearer.
=> Add progress indicator for arc instance deletion

extensions/arc/src/ui/dashboards/controller/controllerDashboardOverviewPage.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/12508
It would be nice to have more information on this page - but currently querying values such as compute/memory requires one query per instance which is going to get very expensive for the controller. Will revisit adding stuff like that later on but for now replace the vCores property value with one we at least have (and is still useful to see).
=> Replace vCores property with state for arc controller dashboard

extensions/azdata/src/azdata.ts, extensions/azdata/src/common/httpClient.ts, extensions/azdata/src/localizedConstants.ts, extensions/azdata/src/test/azdata.test.ts
azdata MSI installation on Windows requires admin privileges.
Temporarily disabling tests that broke because of this change - will go back right after release and fix these all up.
Also updating the logging a bit to provide additional useful information (such as installation logs)
=> Fix windows azdata install

src/sql/base/browser/ui/table/plugins/textWithIconColumn.ts
this is a new column type plugin I introduced a while ago, by default the text will be escaped, but I forgot to do so when I first introduced it.
before:
after:
=> escape the value for display

extensions/sql-database-projects/src/controllers/mainController.ts, extensions/sql-database-projects/src/controllers/projectController.ts
This fixes some of the project context menu actions not working in the new projects view. Now delete and exclude work and adding a file in a folder adds it correctly instead of at the top level of the project. Some of the other ones were working without the change, but I changed them all from BaseProjectTreeItem to WorkspaceTreeItem because that's what's getting passed.
=> Fix project context menu actions

extensions/arc/src/common/utils.ts, extensions/arc/src/localizedConstants.ts, extensions/azdata/src/azdata.ts, extensions/azdata/src/common/utils.ts, extensions/azdata/src/extension.ts, extensions/azdata/src/localizedConstants.ts, extensions/azdata/src/typings/azdata-ext.d.ts, extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/12365
The error interface doesn't strictly need to be in the typings file like that - but I want other extensions to easily be able to see the shape in case we do other things with it.
=> Remove command link from deployment error

src/sql/workbench/contrib/notebook/browser/cellViews/placeholderCell.component.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/12328
The mouse click event (when clicking +code or +text to add a new cell) was causing the zoom level to change back to the zoom level when ADS was first opened. I'm not sure why this mouse click event is causing the change and other clicks (like selecting a new active cell) isn't. 
This bug was introduced after this vscode merge https://github.com/microsoft/azuredatastudio/commit/0833de1e7cfb76ac3d5a44d2f85157818a5cb9ce,
If anyone has any ideas/clues on what might be the cause please let me know.
=> Notebooks: Fix zoom level change when new cell is added

extensionsGallery-insider.json
This PR fixes #12269. Insiders version didn't get bumped when sql database projects was added to the stable extensions gallery
=> update insiders gallery to have same sql database projects version as stable

src/sql/workbench/contrib/queryHistory/browser/queryHistoryDataSource.ts, src/sql/workbench/contrib/queryHistory/browser/queryHistoryNode.ts, src/sql/workbench/contrib/queryHistory/browser/queryHistoryRenderer.ts, src/sql/workbench/contrib/queryHistory/browser/queryHistoryView.ts
This is part of fixing sql/workbench/contrib/queryHistory - splitting it into separate PRs for easier reviewing.
=> Strict compile for sql/workbench/contrib/queryHistory

src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts
#12572 
I believe these code was introduced by Maddy a while back to fix the issue when editing cells with line breaks, but she modified the actual data instead of an object just for rendering the text edit.
the actual data is not plain string, it is an object with displayValue, ariaLabel and isNull, this block of code will modify the data to plain string and we will lose the aria-label data that was already escaped.
fix: create a temp object for display time required modification
=> edit data: create a temp object for display time required modification

extensions/data-workspace/src/common/dataWorkspaceExtension.ts, extensions/data-workspace/src/common/interfaces.ts, extensions/data-workspace/src/dataworkspace.d.ts, extensions/data-workspace/src/main.ts, extensions/data-workspace/src/services/workspaceService.ts, extensions/sql-database-projects/src/common/constants.ts, extensions/sql-database-projects/src/common/utils.ts, extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts
This PR fixes #12490. Now that projects are part of a workspace, the project dropdown is populated with sql projects in the same workspace instead of sql projects in the same folder.
=> Update db reference dialog to show projects in the workspace

src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
last time I checked with Brian, he only set the tabindex to -1, that would not stop screen reader from getting to it, adding aria-hidden to fix the issue.
This PR fixes #11546
=> set aria-hidden for a non-visible control

src/sql/workbench/services/objectExplorer/browser/serverTreeDataSource.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/12615
This was "broken" in https://github.com/microsoft/azuredatastudio/commit/503090856a291232cc564e397d258e7a2ae03f4f#diff-7159ef3349b8a0d975ddfc700bd99a12
We aren't really using the old tree control correctly (it doesn't really support passing undefined as an item) but refactoring it to be correct is probably not worth it given that this will be replaced with the async server tree at some point anyways.
Using an empty string as the id here should be safe since it'll be the only item in the tree so no chance of collisions.
=> Fix undefined error in server tree data source

src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts, src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
kind of interesting scenario, once we are done with accessibility testing we will be removing this. I thought about closing this issue as by design, to reduce the back and forth communications, I am simplifying it to leverage the native html tooltip, and change its role to img since it is not really doing the things a button would do, for button, the screen reader will read the title, but for img I have to add aria-label in order to make the screen reader read the content.
This PR fixes #11529
This PR fixes #11541
This PR fixes #11542
=> simplify the preview information feature

src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
This PR fixes #11544
not sure why the role was set to navigation, I am updating it to match the '...' button in the following screenshot, they are same type of control.
=> update new button role on welcome page

src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
This PR fixes #11549
use the same css class as other links on this page. tested 3 themes, looks good.
=> fix show all link color

src/sql/base/browser/ui/selectBox/selectBox.ts, src/sql/workbench/contrib/notebook/browser/notebookStyles.ts
This PR fixes https://github.com/microsoft/azuredatastudio/issues/11554
Now the "Kernel" and "Attach to" dropdown content is read before the "V" icon.
=> Fix notebook toolbar screen reader reading order

extensions/mssql/config.json
bump the STS version to take the fix for the edit data's delete row issue. all of the changes between .29 and .35 are KUSTO service related (https://github.com/microsoft/sqltoolsservice/compare/v3.0.0-release.29...main), I did some sanity check locally and things look good to me.
=> bump sts version

extensions/kusto/package.json, src/sql/platform/capabilities/common/capabilitiesService.ts, src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts, src/sql/workbench/services/objectExplorer/browser/iconRenderer.ts, src/sql/workbench/services/objectExplorer/browser/serverTreeRenderer.ts
Changed getIconpath in serverTreeRenderer to always set iconPath if iconId is undefined. Changed renderConnection to always renderServerIcon
This PR fixes #11495
=> 3707 Kusto Icon Fix

src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts, src/sql/workbench/contrib/welcome/page/browser/welcomePage.css, src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts
This PR fixes #11545
1. use context menu service to show the popup menu
2. fix the open file menu item bug, it is opening file on windows/linux but open folder on mac, since the open folder action doesn't really fall under 'New', I have moved it out as a separate secondary button.
3. cleanup and reorganize the code
this is how the buttons look now and the pop up menu behaves just like other places in ADS, for example the '...' button on the Connections view container.
on macOS:
=> update welcome page to use context menu service and some code clean up

.github/workflows/ci.yml, extensionsGallery-insider.json, extensionsGallery.json, scripts/validateGalleries.js
This should help reduce the manual effort in validating the gallery files - I keep finding issues with updates people do to these so automating this is going to be very useful I think.
As the script mentions ideally I would have liked to use the actual code ADS uses to parse it - but I didn't want to spend a whole bunch of time getting the right files and setting up an environment they could run in so I just went for the quick and easy solution. The schema should basically never change so this should be fine.
I also didn't do very specific validation such as making sure certain values are correct - we should consider adding that in too. But I wanted to get this out now and then we can add more updates as we see fit.
=> Add script to validate extension gallery files

extensions/sql-database-projects/package.json, extensions/sql-database-projects/package.nls.json, extensions/sql-database-projects/src/common/constants.ts, extensions/sql-database-projects/src/controllers/mainController.ts, extensions/sql-database-projects/src/controllers/projectController.ts, extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts, extensions/sql-database-projects/src/models/project.ts, extensions/sql-database-projects/src/test/project.test.ts, extensions/sql-database-projects/src/test/projectController.test.ts
This PR fixes #12149. This adds a quick pick to be able to change a project's target platform in the meantime before this functionality is eventually added in project dashboards or somewhere else.
=> Change target platform of project

src/sql/azdata.d.ts, src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts, src/sql/workbench/services/notebook/browser/models/cell.ts, src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts
This PR addresses https://github.com/microsoft/azuredatastudio/issues/12646
The issue was caused by this PR https://github.com/microsoft/azuredatastudio/pull/12363 which added separate queryRunners for each code cell.
I am rolling back grid streaming support for now since the original issue the PR above was fixing will require a different fix.
I reverted the changes of the PR above, removed listener for onResultSetUpdate, and moved data conversion logic back into sqlSessionManager.
=> Notebook: Roll back grid streaming support

extensions/sql-database-projects/src/test/dialogs/addDatabaseReferenceDialog.test.ts
The add database reference dialog tests were failing after #12580 got checked in because I forgot to update the tests to mock getting the workspace projects.
=> Fix sql project tests

src/sql/platform/connection/common/connectionProfileGroup.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/12587 - casing shouldn't matter for the root group name. Group names aren't case sensitive so users can't add their own groups named root so this is safe.
=> Fix root group name check

extensions/big-data-cluster/src/bdc.d.ts, extensions/big-data-cluster/src/bigDataCluster/controller/apiGenerated.ts, extensions/big-data-cluster/src/bigDataCluster/controller/clusterControllerApi.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/hdfsDialogBase.ts, extensions/mssql/config.json, extensions/mssql/src/dashboard/serviceEndpoints.ts, extensions/mssql/src/main.ts, extensions/mssql/src/objectExplorerNodeProvider/hdfsCommands.ts, extensions/mssql/src/objectExplorerNodeProvider/hdfsProvider.ts, extensions/mssql/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts, extensions/mssql/src/objectExplorerNodeProvider/treeNodes.ts, extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts, extensions/mssql/src/sparkFeature/historyTask.ts, extensions/mssql/src/sqlClusterLookUp.ts, extensions/mssql/src/utils.ts, extensions/notebook/src/jupyter/jupyterSessionManager.ts, extensions/notebook/src/test/model/sessionManager.test.ts
For https://sqlhelsinki.visualstudio.com/aris/_workitems/edit/11806
Logins who didn't have access to the sys.dm_cluster_endpoints weren't seeing any BDC related items (HDFS folder node, BDC tab on dashboard) - even though the logins are separate and so shouldn't be tied to each other.
To support this a SERVERPROPERTY was added 'ControllerEndpoint' that can be queried for the controller endpoint. SqlToolsService was updated to use this server property if the DMV is not able to be accessed already - this PR is for updating ADS to handle the new authentication flow that is required.
The first big change is that now we don't try to connect to HDFS until the node is expanded - this prevents the username/password inputs from popping up until the node is attempted to be expanded.
Next - we now …
=> Allow non-admin BDC connections to see BDC features

extensions/azdata/src/test/azdata.test.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/12535 There's better ways to test the actual release JSON - so just modifying it to mock that call out so we at least are still testing the logic as expected.
=> Fix azdata network test failure

extensions/mssql/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts, extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts, extensions/mssql/src/sqlClusterLookUp.ts
Final part of https://sqlhelsinki.visualstudio.com/aris/_workitems/edit/11806 - save the username/password for the BDC/HDFS connections so we don't re-prompt users each time.
=> Save username/password for BDC HDFS connections

extensions/arc/src/extension.ts, extensions/arc/src/localizedConstants.ts
I want to avoid someone hitting an issue with the controller connections not being able to handle multiple clusters at the moment so doing this for now. 
This isn't perfect (users can still modify the kube config and we'd never know) but it should prevent the easiest errors to hit.
=> Only allow one arc controller connection

extensions/import/config.json
This PR bumps up the flat file service version. It includes an updated version of Prose (7.20.0) that fixes the bug which skips backslashes in the import data. 
This PR fixes #12593
=> version bump of flat file services

extensions/sql-database-projects/src/controllers/mainController.ts, extensions/sql-database-projects/src/controllers/projectController.ts, extensions/sql-database-projects/src/models/project.ts, extensions/sql-database-projects/src/test/project.test.ts, extensions/sql-database-projects/src/test/projectController.test.ts
This PR fixes #12601. Moved the update SSDT projects out of projectsController.ts and into project.ts so that it happens when the project gets opened by the projectProvider used by the data-workspace extension. I also removed other code that isn't being used anymore now that there's the projects viewlet(opening project from file, opening referenced projects, focusing on opened project)
=> Update SSDT projects opened in projects viewlet

product.json, src/vs/base/browser/ui/selectBox/selectBoxCustom.ts
When clicking on empty dropdown this error would show up in the console
```
TypeError: Cannot read property 'text' of undefined
at SelectBoxList.setWidthControlElement (file:///C:/src/AzureDataStudio/out/vs/base/browser/ui/selectBox/selectBoxCustom.js:547:61)
```
(since there's no options the "longest" one is undefined)
We really probably should always be showing an option - even if it's just `Loading...` or `No items found` or something similar. But we don't always do this and making it so an error isn't thrown in those cases seems like a safe thing to do anyways.
=> Fix error when clicking empty dropdown

extensions/sql-database-projects/src/common/utils.ts, extensions/sql-database-projects/src/controllers/projectController.ts, extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts
Because projects aren't being kept track of in the ProjectsController anymore, the adding a project reference code needs to be updated to look for the referenced project in the workspace projects now.
=> Fix adding project references in projects viewlet

src/sql/base/browser/ui/checkbox/checkbox.ts
The key handler was stopping the event from propagating so we never got the onchange event - which was then breaking the model view stuff since the extension side would never get its property value updated.
=> Fix checkbox change event not firing on enter press

src/sql/workbench/services/notebook/browser/models/notebookModel.ts
Currently, notebooks doesn't work properly (query and intellisense part) for Kusto clusters after opening first notebook from the Kusto database right click option. This was happening because "Kusto" was getting removed from the list of connectionProvidersIds after loading correct Kusto notebook for the first time, so it was getting default sql config.
=> Fix notebook issue when creating Kusto notebooks 2nd time after launching ADS

extensions/sql-database-projects/src/controllers/mainController.ts, extensions/sql-database-projects/src/controllers/projectController.ts, extensions/sql-database-projects/src/models/dataSources/dataSources.ts, extensions/sql-database-projects/src/test/dialogs/publishDatabaseDialog.test.ts, extensions/sql-database-projects/src/test/projectController.test.ts, extensions/sql-database-projects/src/test/publishProfile.test.ts
- Removed old projects tree provider because now those are kept track of in project workspace extension
- fixed tests failing and causing build errors from these changes and tree refresh fix #12692
- Commented out some data sources code for now (isn't being used anyway) because a circular dependency between dataSources.ts and sqlConnectionStringSource.ts started causing the extension to not activate
=> Remove old projects tree provider

extensions/mssql/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts, extensions/mssql/src/utils.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/12713
When I refactored the node logic to delay creating the HDFS connection until the folder was expanded the logic that short-circuited the creation of the session node was also removed. I'm still leaving that part as it is but now just doing a simple check on the connection before creating the session node.
=> Fix HDFS node to only show up for BDC connections

extensions/sql-database-projects/src/controllers/mainController.ts, extensions/sql-database-projects/src/controllers/projectController.ts, extensions/sql-database-projects/src/models/project.ts, extensions/sql-database-projects/src/test/project.test.ts, extensions/sql-database-projects/src/test/projectController.test.ts
- Removed openProject() from ProjectsController because Project.openProject() is used directly by SqlDatabaseProjectProvider
- Removed ProjectsController openProject() tests, moved a couple SSDT roundtrip tests to Project.test.ts
- some general cleanup (added return types, a little renaming, moved createProjectFromDatabase() out of helper methods region)
=> Cleanup ProjectsController

src/sql/workbench/contrib/welcome/gettingStarted/browser/abstractEnablePreviewFeatures.ts
port the preview feature notification change to Oct release branch: https://github.com/microsoft/azuredatastudio/pull/12723 
The planned initial launch wizard is not ready for release, we chatted on Friday with Alan Yu and Hannah, and decided to update the notification content for Oct release.
=> update preview feature notification (#12723)

src/sql/platform/connection/common/connectionProfileGroup.ts
Fixes #12587 - casing shouldn't matter for the root group name. Group names aren't case sensitive so users can't add their own groups named root so this is safe.
cherry-picked from 253aa7865033c493cbf67a7404ee59a9d181ff8d
=> [Port] Fix root group name check (#12660)

build/lib/extensions.js
These file changes are getting auto-generated in build, so updating checked in copy
=> Fix sorting of extension list in build script

extensions/arc/package.json, extensions/resource-deployment/src/helpers/optionSources.ts, extensions/resource-deployment/src/interfaces.ts, extensions/resource-deployment/src/ui/modelViewUtils.ts
Adds a new options source to fetch dc config profile list from azdata arc dc config list command. Also did some code refactoring to simplify creation of OptionsSource object.
This PR fixes #12372
Testing:
End to end testing of dc create scenario
Extension unit tests.
cherry-pickd from 7bfea07b9bf879f8de307c05dfe3fb040d64e1aa
=> [Port] Fetch arc dc config profile list from azdata #12678

extensions/big-data-cluster/src/bdc.d.ts, extensions/big-data-cluster/src/bigDataCluster/controller/apiGenerated.ts, extensions/big-data-cluster/src/bigDataCluster/controller/clusterControllerApi.ts, extensions/big-data-cluster/src/bigDataCluster/dialog/hdfsDialogBase.ts, extensions/mssql/config.json, extensions/mssql/src/dashboard/serviceEndpoints.ts, extensions/mssql/src/main.ts, extensions/mssql/src/objectExplorerNodeProvider/hdfsCommands.ts, extensions/mssql/src/objectExplorerNodeProvider/hdfsProvider.ts, extensions/mssql/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts, extensions/mssql/src/objectExplorerNodeProvider/treeNodes.ts, extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts, extensions/mssql/src/sparkFeature/historyTask.ts, extensions/mssql/src/sqlClusterLookUp.ts, extensions/mssql/src/utils.ts, extensions/notebook/src/jupyter/jupyterSessionManager.ts, extensions/notebook/src/test/model/sessionManager.test.ts
For https://sqlhelsinki.visualstudio.com/aris/_workitems/edit/11806
Logins who didn't have access to the sys.dm_cluster_endpoints weren't seeing any BDC related items (HDFS folder node, BDC tab on dashboard) - even though the logins are separate and so shouldn't be tied to each other.
To support this a SERVERPROPERTY was added 'ControllerEndpoint' that can be queried for the controller endpoint. SqlToolsService was updated to use this server property if the DMV is not able to be accessed already - this PR is for updating ADS to handle the new authentication flow that is required.
The first big change is that now we don't try to connect to HDFS until the node is expanded - this prevents the username/password inputs from popping up until the node is attempted to be expanded.
Next - we now …
=> [Port] Allow non-admin BDC connections to see BDC features (#12663)

extensions/azurecore/src/azureResource/services/subscriptionFilterService.ts, extensions/azurecore/src/azureResource/utils.ts, extensions/azurecore/src/azurecore.d.ts, extensions/azurecore/src/extension.ts, extensions/machine-learning/src/test/stubs.ts, extensions/resource-deployment/src/localizedConstants.ts, extensions/resource-deployment/src/ui/modelViewUtils.ts
This change exposes selectedSubscription api from azurecore extension and uses that api to populate the subscriptions dropdown in wizards.
This PR fixes first part of #12261
cherry-picked from 39e43d2401f69cc028f617b8269f39574ae05649
=> [Port] use selected subscriptions (#12691)

src/sql/platform/capabilities/test/common/testCapabilitiesService.ts, src/sql/workbench/contrib/notebook/test/electron-browser/notebookModel.test.ts, src/sql/workbench/services/connection/test/browser/connectionManagementService.test.ts, src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR adds tests that ensure we setup Kernel Alias connections and change the kernel appropriately based on the connection. 
- Should connect to Fake (kernel alias) connection and set kernelAliases list properly
- Should change kernel when connecting to Fake (kernel alias) connection 
- Should change kernel from Fake (kernel alias) to SQL when changing to SQL connection
=> Add Notebook tests for Kernel Alias connections

build/.gitattributes
Porting over https://github.com/microsoft/vscode/pull/106822 early so this stops being an annoyance in our repo. It'll be brought over in a vs code merge eventually but no reason not to get it in now.
=> Add line endings gitattribute

extensions/mssql/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts, extensions/mssql/src/utils.ts
Fixes #12713
When I refactored the node logic to delay creating the HDFS connection until the folder was expanded the logic that short-circuited the creation of the session node was also removed. I'm still leaving that part as it is but now just doing a simple check on the connection before creating the session node.
cherry-picked from 572310b9067368be952368b951dea60adb746ddc
=> [Port] Fix HDFS node to only show up for BDC connections (#12714)

extensions/resource-deployment/src/ui/modelViewUtils.ts
I just noticed if we don't set this property or set it to undefined, it will open the last opened directory, which is what we actually needed.
=> use undefined instead of home directory

extensions/notebook/package.json, extensions/notebook/src/book/bookModel.ts, extensions/notebook/src/book/bookPinManager.ts, extensions/notebook/src/book/bookTreeItem.ts, extensions/notebook/src/book/bookTreeView.ts, extensions/notebook/src/common/utils.ts, extensions/notebook/src/extension.ts, extensions/notebook/src/test/common/utils.test.ts, src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookExplorerViewlet.ts, src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookSearch.ts
* fix search for pinned notebooks
* fix filtering when verifying that a search folder is not a subdirectory from the current folder queries path
* Show book node on pinned notebooks search results
* fix parent node on pinned notebooks search results
* fix search for pinned notebook and modify how pinned notebooks are stored in workspace
* update format of pinned notebooks for users that used the september release version
* removed unused functions
* Address PR comments
* fix parent node for legacy version of jupyter books
* remove cast from book path
This PR fixes #12459
=> Fix search for pinned notebooks

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
Addresses issues around #12602 (and tab/untab) and fixes a bug where the same action 'n' times for 'n' different text cells (because of how we were just looking for `document.keydown` events.
=> Notebooks: WYSIWYG Add Redo, Fix Shortcuts

extensions/mssql/src/objectExplorerNodeProvider/objectExplorerNodeProvider.ts, extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts, extensions/mssql/src/sqlClusterLookUp.ts
Final part of https://sqlhelsinki.visualstudio.com/aris/_workitems/edit/11806 - save the username/password for the BDC/HDFS connections so we don't re-prompt users each time.
cherry-picked from b3578d058f1bbd04d2b94a3f782ae63bb6922a4d
=> [Port] Save username/password for BDC HDFS connections (#12667)

extensions/notebook/extension.webpack.config.js, extensions/notebook/package.json, extensions/notebook/yarn.lock
Related to #12247, which I thought wasn't necessary (but is actually necessary for jupyterlab/services as a dependency that isn't listed).
Along the way, I removed dependencies that I couldn't find any obvious references to and moved a couple of types dependencies to be dev dependencies.
Still doing testing and kicked off a full build to make sure that this doesn't break webmode or any integration tests.
=> Prune notebooks package.json, upgrade node-fetch

extensions/sql-database-projects/src/models/project.ts
This PR fixes #12794. Fixes two things: 
1. Wasn't checking if project reference already exists before adding
2. On mac, duplicate references weren't being caught if a project already with a db reference was loaded because the uri read from the sqlproj had Window's slashes. Fix is to make sure slashes are all consistent when doing the comparison
=> Fix duplicate db references being allowed

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
This addresses #12776. Instead of defaulting to absolute path (which can be a destructive action and prevent sharing), defaulting to a relative path. Talked at length with PM and decided that this was a better approach.
=> WYSIWYG: default to relative links in images and links

extensions/arc/src/providers/arcControllersOptionsSourceProvider.ts, extensions/resource-deployment/src/ui/modelViewUtils.ts
Fixes:
1. When submitting an instance method as a callback function we need to capture 'this'. This was missed in 'retrieveVariable' instnace method in ArcControllersOptionsSourceProvider.
This PR addresses #12802.
=> capture 'this' to use retrieveVariable as callback

src/vs/base/browser/ui/dropdown/dropdownActionViewItem.ts
porting https://github.com/microsoft/vscode/commit/989f251ff175fe336d36ecc88ee4ba41d9f35416 from vscode.
vscode introduced an issue that splits the css class names into to, codicon-filter is changed to 'codicon filter', and our filter icon is picked up accidentally without a proper size, for vscode, the symptom is filter icon is not showing.
now in Main branch:
with this fix:
@cssuh FYI since this one looks pretty silly, I decided to cherry pick it to main directly without waiting for the merge bot.
This PR fixes #12774
=> port extension view filter icon fix from vscode

extensions/azurecore/package.json, extensions/azurecore/package.nls.json, extensions/azurecore/src/extension.ts
Seems we removed the logic that actually used this setting a while back so this just isn't doing anything anymore.
=> Remove arc preview setting

extensions/big-data-cluster/src/bigDataCluster/controller/apiGenerated.ts
The path was changed before GA but never got updated here. Both paths existed up until recently when the older path was removed so we don't need to be concerned about backwards compat since only pre-GA controllers would be affected by this.
=> Update HDFS mount path

extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts
This PR fixes #12851 
This fix just disables the ok button when no resources are found after filtering
=> Fix for Depoyment defaults to first item when filter filters out all items

extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts
This PR fixes #12812. The targetDatabaseDropdown.value was getting set to undefined when the value changed(from typing or being loaded from publish profile) when the dropdown didn't have any values.
=> fix publish project button not always enabling correctly

extensions/big-data-cluster/src/bigDataCluster/controller/apiGenerated.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/12867
The path was changed before GA but never got updated here. Both paths existed up until recently when the older path was removed so we don't need to be concerned about backwards compat since only pre-GA controllers would be affected by this.
cherry-picked from https://github.com/microsoft/azuredatastudio/commit/9389a9289661882e3039a04618dffcec845ba8b4
=> Update HDFS mount path (#12865)

src/sql/workbench/contrib/notebook/browser/notebookActions.ts, src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR addresses #12862.
It fixes Kusto to SQL kernel change by removing the connection based on the appropriate kernel.
reverts changes done here: #12750 and address the connection issue that needs to utilize kernel Alias to retrieve the right context.
=> Fix connection when changing kernel from Kusto to SQL

extensions/big-data-cluster/src/bdc.d.ts, extensions/big-data-cluster/src/bigDataCluster/controller/clusterControllerApi.ts, extensions/notebook/src/book/bookTreeView.ts, extensions/notebook/src/common/constants.ts, extensions/notebook/src/common/extensionContextHelper.ts, extensions/notebook/src/common/utils.ts, extensions/notebook/src/dialog/managePackages/installedPackagesTab.ts, extensions/notebook/src/extension.ts, extensions/notebook/src/jupyter/jupyterController.ts, extensions/notebook/src/jupyter/jupyterSessionManager.ts, extensions/notebook/src/prompts/confirm.ts, extensions/notebook/src/prompts/factory.ts, extensions/notebook/src/prompts/input.ts, extensions/notebook/src/prompts/password.ts, extensions/notebook/src/prompts/question.ts, extensions/notebook/src/protocol/notebookUriHandler.ts, extensions/notebook/src/test/common/prompt.test.ts, extensions/notebook/src/test/model/sessionManager.test.ts, src/sql/workbench/api/common/sqlExtHostTypes.ts
This is finishing up the work that was done for the HDFS Node to allow low-privileged users who don't have access to view the endpoints DMV to still run Spark notebooks.
When a user switches to a spark kernel we need to get the Knox endpoint at that time. For users who don't have access to the DMV that means we need to query the controller to get that endpoint. We first try to connect to the controller with the SQL creds and if that fails then prompt the user for the username/password to use, storing them associated with the connection ID for later use by the same connection.
There's some other cleanup that I've done here - but generally all the logic being added is in jupyterSessionManager.ts
Note that this logic is basically the same as what I did in the mssql extension. At some point …
=> Add support for low-privileged user to run spark notebooks

extensions/mssql/src/sqlClusterLookUp.ts
Fixes #12905 - the casing was different so the check wasn't being done properly.
=> [Port] Fix HDFS node for Integrated auth (#12906)

src/vs/base/browser/ui/selectBox/selectBoxCustom.ts
Fixes a null error that happens when you click on a dropdown without any items in it, uses regular handling to resolve the issue.
=> Null check for updatedetail

extensions/mssql/config.json
Reverts microsoft/azuredatastudio#12929
This PR introduced these integration test failures
=> Revert "Bump SQL Tools to 3.0.0-release.42"

test/automation/src/sql/configurePythonDialog.ts, test/automation/src/sql/notebook.ts, test/smoke/src/sql/areas/notebook/notebook.test.ts
The notebook smoke test failed because it could not find the cell output in time. 
I added an extra method to make sure the python installation and kernel change was complete before running the cell.
=> Fix notebook smoke test

src/sql/base/browser/ui/panel/panel.ts, src/sql/workbench/services/connection/browser/connectionDialogWidget.ts, src/sql/workbench/services/connection/browser/media/connectionDialog.css
fix a few issues related to scrolling
1. scrollbar not visible, @abist 's change #12401 added 10px padding-left, and because of the way we do layout, it pushed the tab panel to the right by 10px and caused the scroll bar off screen. I am changing it layout using client width instead of width, also instead of using css I am updating the DOM node directly.
2. the 2 tree views (recent and saved connections) doesn't respond to resizing properly, it is not hooked up with the layout event, I am adding code to handle it.
**Before:**
**After:**
fixes the scrollbar not visible issue in https://github.com/microsoft/azuredatastudio/issues/12909
=> fix connection dialog scroll issue

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts
This PR fixes #12899
On windows,  the href attribute from the html element is removed in untrusted notebooks.
When we convert the text to markdown the href attribute is empty that's why the links disappeared when switching between rich text view to split view.
The other thing that I fixed here is that markdown does not identify a path as a link if it contains whitespaces. When switching from markdown to WYSIWYG, we parse the href link so it removes all the encoding, so I replace all the whitespaces to %20 to keep the link working when switching from Split View to Rich Text View.
=> Fix links on WYSIWYG

test/smoke/src/sql/areas/notebook/notebook.test.ts
Notebook smoke test is still timing out after increasing the timeout. Skipping test for now while this is worked offline.
=> skip notebook smoke tests for now

.github/CODEOWNERS
Adding myself as a code reviewer for arc, azdata, and resource-deployment extensions.
=> Add @ranasaria code reviewer for 3 extensions

src/sql/workbench/browser/modelComponents/inputbox.component.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/12997
Previously when trying to set the inputbox width to 400px:
Fixed:
=> Fix setting inputbox width

src/sql/platform/notebooks/common/outputRegistry.ts, src/sql/workbench/contrib/notebook/browser/cellToolbarActions.ts, src/sql/workbench/contrib/notebook/test/browser/cellToolbarActions.test.ts, src/sql/workbench/contrib/notebook/test/electron-browser/cell.test.ts, src/sql/workbench/services/notebook/browser/models/cell.ts, src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts
This PR introduces the backend cell model work that is required for Parameterization. There are two important tags for parameterization as a whole: **parameters** and **injected-parameters**. This enables the use of [Papermill](https://github.com/nteract/papermill) to work properly with ADS Notebooks. 
The current backend work is demonstrated in the gif below. It focuses on using the cell toolbar action to change the metadata based on the action of "_Make parameter cell_" and "_Remove parameter cell_". I have added tests for both the parameter cell as well as the injected-parameter cell. 
The injected-parameter cell will be added to a notebook below the parameters cell when a user uses Papermill (for example) to parameterize a notebook. 
Please leave any feedback or questions!
**Work to …
=> Backend work for Notebook Parameterization and Tests

extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts
In order to avoid issue being created by having configuation lines/indentation, styling has been removed. 
Before 
After
=> Removed configuration indent

src/sql/workbench/services/connection/browser/connectionManagementService.ts
Noticed this while looking at https://github.com/microsoft/azuredatastudio/issues/12992
In my testing it doesn't seem to actually be the cause of the issue - if I manually cause the icon provider function to throw it still expands correctly. It just won't have the new icon.
This is just fixing it so we adhere to the signature as defined in https://github.com/microsoft/azuredatastudio/blob/main/src/sql/azdata.d.ts#L1302 - serverInfo isn't optional and so we probably shouldn't be passing a possibly undefined object.
We could also considerallowing that value to be undefined though - since perhaps a provider doesn't actually care what the exact type of the connection is (for example all kusto icons are set regardless of the server info). But doing so would be a breaking change so I'm a little …
=> Skip getting icon if we don't have a server info

src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts, src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts, src/sql/workbench/contrib/notebook/test/browser/htmlMarkdownConverter.test.ts
Fixes #13003. OneNote loves to create spans for everything. Previously, we were ignoring all styling for spans, resulting in some confusing behavior for users; they would see all of their styling disappear when copying from OneNote.
This is the beginning of supporting styles for spans. I fully expect the number of styles that we support for spans to increase here, but am focused first on the styles that we support out of the box. I do think that this is a worthy endeavor; as a very simple example:
```
**Test**
```
is much easier to edit than
```
'<p style="margin:0in;font-family:Calibri;font-size:11.0pt"><span style="font-weight:bold">Test</span></p>'
```
(once we add in font size into WYSIWYG, we can support this natively and/or persist font-size styling)
Also refactors out code from …
=> WYSIWYG Span Style Fixes, Refactor, and Tests

extensions/resource-deployment/src/ui/deployClusterWizard/pages/azureSettingsPage.ts, extensions/resource-deployment/src/ui/deployClusterWizard/pages/clusterSettingsPage.ts, extensions/resource-deployment/src/ui/deployClusterWizard/pages/serviceSettingsPage.ts, extensions/resource-deployment/src/ui/modelViewUtils.ts
**The issue:** 
The following lines: https://github.com/microsoft/azuredatastudio/blob/bug/12082/extensions/resource-deployment/src/ui/modelViewUtils.ts#L569-#L570
were trying to get the textField that was just created for the password field from the context.inputComponents collection. 
The clusterSettingsPage (and all other pages of BDC) maintain two inputComponents collections: one for the whole wizard and one for each page. When a page exits, the page code copies over all the inputComponents of the page over to this collection for the wizard.
The clusterSettingsPage sets the wizard's inputComponents collection into the context when the section context is created, however, in the callback of onNewInputComponentCreated, it only updates the inputComponents collection for that page, so the …
=> Bdc wizard pages now track all components in wizard.InputCompnentsInfo

extensions/sql-database-projects/src/common/constants.ts, extensions/sql-database-projects/src/controllers/projectController.ts
This PR fixes #12715. Previously, schema compare would open if there was a dacpac in the project's bin folder. buildProject() returns the undefined if the build failed and the dacpac path if successful, so we can use that instead of creating the dacpac path again.
=> Don't open schema compare if project build fails

extensions/azurecore/src/azureDataGridProvider.ts, extensions/azurecore/src/azureResource/azure-resource.d.ts, extensions/azurecore/src/azureResource/providers/database/databaseService.ts, extensions/azurecore/src/azureResource/providers/databaseServer/databaseServerService.ts, extensions/azurecore/src/azureResource/providers/kusto/kustoService.ts, extensions/azurecore/src/azureResource/providers/postgresArcServer/postgresServerService.ts, extensions/azurecore/src/azureResource/providers/postgresServer/postgresServerService.ts, extensions/azurecore/src/azureResource/providers/sqlinstance/sqlInstanceService.ts, extensions/azurecore/src/azureResource/providers/sqlinstanceArc/sqlInstanceArcService.ts, extensions/azurecore/src/extension.ts, extensions/azurecore/src/test/azureResource/providers/database/databaseTreeDataProvider.test.ts, extensions/azurecore/src/test/azureResource/providers/databaseServer/databaseServerTreeDataProvider.test.ts
Moving the provider into its own class for cleaner separation of logic.
Adding resource group property to azure resources (it was already a property on those resources - just not defined in the typings)
=> Azure provider cleanup and add rg property

extensions/azdata/src/common/childProcess.ts
The name option doesn't allow non-alphanumeric characters except for space so was failing on insiders builds (which have `- Insiders` in the name)
`
=> Use static name value for azdata sudo commands

src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts, src/sql/workbench/contrib/notebook/test/browser/htmlMarkdownConverter.test.ts
There are certain properties that either don't have equivalents in markdown or whose transformations don't have actions defined in WYSIWYG yet.
To prevent overwriting this styling, allowing a small number of styles by default. Can always increase this list in the future.
=> WYSIWYG: Further enhancements to spans

extensions/resource-deployment/src/services/tools/kubeCtlTool.ts
People were getting an error when trying to do Arc DC deployments :
After some investigation it appears that the annotations property object won't always exist on the storage class objects - but we were assuming it was and so we'd throw when we tried to check the property of the annotations object.
=> Fix kubectl storage class check

extensions/integration-tests/src/test/dacpac.test.ts, extensions/integration-tests/src/test/schemaCompare.test.ts
The dacpac and schema compare integration tests have been flakey and timing out, causing builds to be blocked. Marking the rest of them as unstable now and created https://github.com/microsoft/azuredatastudio/issues/13058 to investigate during the committer months.
=> Mark dacpac and schema compare integration tests as unstable

src/sql/workbench/contrib/dashboard/browser/pages/databaseDashboardPage.contribution.ts, src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.contribution.ts
This PR fixes #12974
Backup restore button got hidden for PGSQL due to explicit check for MSSQL only - adding PGSQL back.  Thanks @kisantia for help.
=> Adding backup/restore back for pgsql db and restore for server in dashboard

extensions/notebook/src/jupyter/jupyterKernel.ts, src/sql/workbench/contrib/notebook/test/browser/notebookEditor.test.ts, src/sql/workbench/contrib/notebook/test/stubs.ts, src/sql/workbench/services/notebook/browser/models/cell.ts, src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts, src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR ensures that when a user creates a new Notebook in ADS and adds the parameter tag (via cellToolbar). They will be able to utilize papermill properly (this was done by including the language of the kernel to the kernelSpec).
Moreover, we want to ensure that once a user opens the Parameterized notebook in ADS they can visually see the difference between an injected parameter via Papermill and the original parameters cell.
Exposing the metadata allows us to make sure that the user is only able to create one tagged parameter cell.
=> Notebook Parameterization - Papermill Compatibility 

src/sql/azdata.proposed.d.ts, src/sql/base/browser/ui/table/formatters.ts, src/sql/workbench/browser/editor/resourceViewer/resourceViewerInput.ts, src/sql/workbench/contrib/resourceViewer/browser/resourceViewerTable.ts
Adds support for the hyperlink fields in a DataGrid table - this will support two types of values : 
1. string - a URL to open
1. ExecuteCommandInfo - a command to execute
Note that this initial implementation has the caller that creates the grid also needing to hook up the click handler which isn't great. This is how it's handled in the query editor grid and I didn't see an obvious way to attach the click handler directly to the link itself. I plan on investigating this further, but for now I wanted to move into working on another part that's more important so getting this in as it is now since it at least works.
=> Add hyperlink support to DataGrid columns

extensions/sql-database-projects/src/models/project.ts, extensions/sql-database-projects/src/test/project.test.ts
This PR fixes #12825. The database name(project name or dacpac name) was being used as the database variable instead of the value that was in the text box. Added tests to make sure the correct value is being written to the sqlproj.
=> Fix changing database sqlcmdvar value

src/sql/workbench/contrib/query/browser/flavorStatus.ts, src/sql/workbench/contrib/query/browser/queryEditor.ts
Fixes https://github.com/microsoft/azuredatastudio/issues/13024
A couple parts to this : 
1. Make it so that certain MSSQL-specific actions only show up when the provider is MSSQL
1. Hook into the language flavor change event to update the actions when the language flavor is changed
1. Modify the logic there slightly to get the provider by looking at these in order - taking the first non-falsy one
a. Connection provider ID if we're connected
a. The provider ID for the URI (file) - this is set for disconnected editors by choosing "Language Flavor" from the bottom
a. Default provider if neither of the above is set 
This also fixes it so that if you have a disconnected editor and set it to the Kusto language then it'll show the correct actions
Changing language mode updates actions : …
=> Update query editor taskbar actions on language flavor change

src/sql/platform/accounts/common/accountViewModel.ts, src/sql/platform/accounts/test/common/accountViewModel.test.ts, src/sql/workbench/contrib/accounts/test/browser/accountDialogController.test.ts
For https://github.com/microsoft/azuredatastudio/issues/11260 - it's not clear where the issue is coming from but if it's here this would silently just be failing so adding logging to see if that helps track down what's happening.
=> Add error logging when fetching account provider accounts

src/sql/azdata.proposed.d.ts, src/sql/workbench/browser/modelComponents/inputbox.component.ts
This lets the input box title get set, which is the text that that shows when it's hovered over. I'm adding this so that if the string is longer than the length of the inputbox, the hover text can show the full string.
=> Expose inputbox title so hover text can be set

src/sql/workbench/api/common/extHostModelView.ts
Missed updating this file in #8909 and #13084 so only 
`projectFilePathTextBox.updateProperty('title', this._projectFile)` 
worked, but 
`projectFilePathTextbox.title = this._projectFile` 
wasn't working (and same for validationErrorMessage)
=> Add missing get and set in extHostModelView for title and validationErrorMessage

extensions/azurecore/package.json, extensions/azurecore/src/azureResource/commands.ts, src/sql/workbench/services/connection/browser/connectionBrowseTab.ts
1. Azure node's context menu:
1. Azure account's context menu:
1. Enhance the 'Start Cloud Shell' command
as we discussed in the sync up, it doesn't make sense to move this command to connection dialog, I am enhancing it so that when user run this command directly:
- if there are no accounts -> ask the user to sign in
- if there are only one account -> use it directly
- if there are multiple accounts -> show the account picker
master tracking issue: https://github.com/microsoft/azuredatastudio/issues/12909
=> bring Azure context menu to the new tree and enhance start cloud shell command

src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts
This PR updates copy based on PM direction. It changes the header on the welcome page for the extensions section from "Extend your data studio" to "Extensions".
=> updates copy

extensions/dacpac/src/test/testContext.ts, extensions/sql-assessment/src/assessmentResultGrid.ts, src/sql/azdata.proposed.d.ts, src/sql/platform/dashboard/browser/interfaces.ts, src/sql/workbench/api/common/extHostModelView.ts, src/sql/workbench/api/common/sqlExtHostTypes.ts, src/sql/workbench/browser/modelComponents/table.component.ts
Append data functionality to the table component.
The Sql-Assessment extension performs long-running server assessment and displays results as it gets returned from STS one-by-one during the execution process. This allows a user to see results right away and do not wait until the full assessment is completed. 
Existing table component methods allows to completely replace data source only. This leads to scrolling being re-set to the top of the table every time a new data chunk arrives. 
A new proposed function appends new data to the existing data source and doesn't force the table to re-set its data completely.
=> append data functionality

extensions/azdata/src/azdata.ts
The azdata CLI recently added a confirmation prompt when deleting Postgres.  But when running azdata outside of a terminal you can't respond to the prompt.  So add the --force argument to skip the prompt.  Azure Data Studio already has it's own confirmation dialog anyway.
=> Add --force to azdata arc postgres server delete

extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts, src/sql/workbench/browser/modelComponents/declarativeTable.component.ts
Missed updating this in #12782. Sqlcmdvars were showing up like this after changing a cell value, then loading the values from a publish profile because data is deprecated for DeclarativeTableComponent:
=> Update sqlcmd table to use dataValues instead of deprecated data

extensions/azurecore/src/azureDataGridProvider.ts, extensions/azurecore/src/extension.ts, src/sql/azdata.proposed.d.ts, src/sql/workbench/contrib/resourceViewer/browser/resourceViewerTable.ts
The HeaderFilter plugin isn't set up to accept nested values like these were so I'm reverting that change. At some point it would probably be good to be able to pass in a "value getter" to the filter - but for now I don't actually need the properties to be in the nested object so reverting is the easiest way until we actually have a need for that kind of support.
=> Fix filtering for resource viewer

src/sql/workbench/services/connection/browser/connectionBrowseTab.ts, src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts, src/sql/workbench/services/objectExplorer/browser/treeCreationUtils.ts
1. Currently the tree is not theme aware, the event is hooked up in this PR
2. We discussed in today's sync up and agreed on not showing color
3. show the expander for group regardless to make it clear it is a container.
=> make the tree theme aware and remove group color

extensions/kusto/config.json
Bump sqltoolsservice version to 3.0.0-release.45 for Kusto extension
=> Bump sqltoolsservice version for Kusto extension

src/sql/azdata.proposed.d.ts, src/sql/workbench/contrib/notebook/browser/notebook.component.ts, src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts, src/sql/workbench/contrib/notebook/browser/notebookActions.ts, src/sql/workbench/contrib/notebook/test/browser/cellToolbarActions.test.ts, src/sql/workbench/contrib/notebook/test/electron-browser/notebookEditorModel.test.ts, src/sql/workbench/contrib/notebook/test/electron-browser/notebookFindModel.test.ts, src/sql/workbench/contrib/notebook/test/electron-browser/notebookModel.test.ts, src/sql/workbench/contrib/notebook/test/stubs.ts, src/sql/workbench/services/notebook/browser/models/modelInterfaces.ts, src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR adds the ability to save a connection name (alias) in the notebook metadata.  
If a notebook with a saved connection name is opened, the attach to dropdown is updated to show the connection name. When the first cell is run, we search for the connection profile that matches the connection name. If a valid connection profile is found, we use that, otherwise we show the connection dialog as usual. For now, if there is no connection name, nothing is saved and the behavior is the same as before. 
I added a setting for this feature (by default, connection name saving is off and attachTo dropdown won't be updated). 
Note: There was more discussion around saving an alias vs data source name. For now I am using alias and if we decide to save something different in the future, it will be an …
=> Notebooks: Save connection information in metadata

extensions/azurecore/src/azureDataGridProvider.ts, extensions/azurecore/src/localizedConstants.ts, src/sql/azdata.proposed.d.ts, src/sql/workbench/api/browser/mainThreadDataProtocol.ts, src/sql/workbench/api/common/extHostDataProtocol.ts, src/sql/workbench/api/common/sqlExtHost.protocol.ts, src/sql/workbench/browser/editor/resourceViewer/resourceViewerInput.ts, src/sql/workbench/contrib/resourceViewer/browser/resourceViewerEditor.ts, src/sql/workbench/contrib/resourceViewer/browser/resourceViewerTable.ts, src/sql/workbench/services/dataGridProvider/browser/dataGridProviderService.ts, src/sql/workbench/services/dataGridProvider/common/dataGridProviderService.ts
Title used for editor title and aria title of the grid component.
Also did a slight refactoring of the data grid provider service to just expose getting the provider object itself instead of having to have a separate function for every property/function to query on the providers.
=> Add title property for data grid providers

src/sql/workbench/services/connection/browser/connectionBrowseTab.ts, src/sql/workbench/services/connection/browser/media/connectionBrowseTab.css
requested by UX team.
show folder icon for the following nodes:  'Saved Connections', 'Azure' and connection group nodes. 
refactor the tree item renders since the majority of the code can be reused by different node types. since the connection group node is going to be different from the one in OE, I am using the common renderer for it now, I can switch back to the common one when we would like to have the same UX for it.
=> show folder icon for some tree nodes

extensions/azurecore/package.json, extensions/azurecore/package.nls.json, extensions/azurecore/src/azureDataGridProvider.ts, extensions/azurecore/src/localizedConstants.ts, src/sql/workbench/contrib/resourceViewer/browser/resourceViewer.contribution.ts, src/sql/workbench/contrib/resourceViewer/browser/resourceViewerActions.ts, src/sql/workbench/contrib/resourceViewer/browser/resourceViewerEditor.ts, src/sql/workbench/contrib/resourceViewer/browser/resourceViewerView.ts, src/sql/workbench/services/notebook/browser/sql/sqlSessionManager.ts
1. Show Resource Viewer when preview features enabled
1. Preview text in titles
1. Name column back to just text until there's an actual action to take on click
1. Remove "Edit Columns" button until that feature can be added
1. Only show azure-resources provider in view for now
(also cleaned up a var I missed when removing notebook convert settings)
=> Resource viewer cleanup

src/sql/workbench/services/connection/browser/connectionBrowseTab.ts, src/sql/workbench/services/connection/browser/connectionDialogWidget.ts
currently, keyboard selection of tree item doesn't trigger the connection change event, use proper tree event for it, also redefined the view's external event to make it more business logic focused.
=> handle keyboard selection

src/sql/workbench/services/notebook/browser/models/notebookModel.ts
This PR fixes #13128
The previous functionality was treating the cell source as a string instead of a string array. So now I concat a new string array with the '# Injected-Parameters' comment properly so that we keep the cellModel.source as a string array (which will not include commas to separate the content).
=> Parameterization - Fix injected multiple parameter cell

src/sql/workbench/contrib/notebook/browser/notebook.component.ts
Fixes #13172.
We disable the action until the model is done loading, but there was a change a few months back that only re-enabled the trusted action if the notebook was trusted.
This action should always be clickable (i.e. enabled).
=> Ensure trusted action is always enabled

extensions/notebook/src/integrationTest/notebookIntegration.test.ts, extensions/notebook/src/jupyter/jupyterServerInstallation.ts, extensions/notebook/src/jupyter/serverInstance.ts, extensions/notebook/src/test/python/jupyterInstallation.test.ts
The PROSE python package is no longer being maintained, and we've been asked by the PROSE team to stop shipping the package by default. The team would like to take down their static page that hosts this package as well in the future (exact date TBD).
Because of these two factors, we need to remove the package from the list of packages that we install by default.
=> Remove prose from notebooks default package list

extensionsGallery.json
This is actually reverting back to the 0.5.1 code due to regression found for stable only - hence why insiders is staying at 0.6.0 for now (the issue doesn't occur there)
=> Update arc to 0.6.1

extensions/schema-compare/src/dialogs/schemaCompareDialog.ts
This PR fixes #12769. Previously, the schema compare dialog was waiting for the server and database dropdowns to finish populating before anything showed in the dialog, which could sometimes result in a blank dialog for a couple seconds.
This update makes it so the dropdowns show a loading indicator while waiting for the values to be populated and a little cleanup of unnecessary awaits:
=> Add loading indicators to schema compare dialog
